### ISSUE TITLE
Private link endpoint are not updating implied network interface

### ISSUE THREAD

**Issue by HSoulat** [hashicorp/terraform-provider-azurerm#21292] opened 2023-04-05 07:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I am opening a new issue as #9381 has been closed. 

When a private link endpoint is created, the TAG are propagated to the implied vNIC. However, if we update the TAG on private link endpoint resource, the vNIC is not updated. 

It seems that Terraform don't manage vNIC created by private link endpoint in his state. As the private link endpoint vNIC can't be deployed by another way (separate resource), i would expect that Terraform handle it within private link resource. 

### New or Affected Resource(s)/Data Source(s)

azurerm_private_endpoint

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/9381
https://github.com/hashicorp/terraform/issues/26963

**Comment by tombuildsstuff** [comment] 2023-04-05 09:01
hi @HSoulat 

Taking a look through here, unfortunately accessing the internal implementation details of the Private Endpoint isn't something that we can rely on not to change, and as such this is ultimately a feature request for the Service rather than something we can fix in Terraform.

As this is currently by design within Azure, I'd recommended opening a feature-request for the Azure API [on the `Azure/azure-rest-api-specs` repository](https://github.com/Azure/azure-rest-api-specs) where someone from the Service Team should be able to take a look into this.

However since this is a feature request for the Azure API rather than something we can fix within Terraform, I'm going to close this issue for the moment.

Thanks!

**Closed by tombuildsstuff** 2023-04-05 09:01 UTC
Labels: question
