### ISSUE TITLE
When are you going to support setting Minimum Inbound TLS Cipher Suite via terraform?

### ISSUE THREAD

**Issue by vamshisiram** [hashicorp/terraform-provider-azurerm#25893] opened 2024-05-07 19:12 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

Right now, the Terraform configuration for webapp does not support controlling the cipher suite setting, when will it be made available in terraform?

this setting in azure portal is what i am referring to.
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/90816346/4b8102dd-0281-4429-9f3a-4d495c51b52a)

### Terraform Version

1.8.2

### AzureRM Provider Version

3.102.0

### Affected Resource(s)/Data Source(s)

azurerm_windows_web_app

### Terraform Configuration Files

```hcl
Right now, the Terraform configuration for webapp does not support controlling the cipher suite setting, when will it be made available in terraform?

this setting in azure portal is what i am referring to.
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/90816346/4b8102dd-0281-4429-9f3a-4d495c51b52a)
```

### Debug Output/Panic Output

```shell
Right now, the Terraform configuration for webapp does not support controlling the cipher suite setting, when will it be made available in terraform?

this setting in azure portal is what i am referring to.
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/90816346/4b8102dd-0281-4429-9f3a-4d495c51b52a)
```

**Comment by rcskosir** [comment] 2024-05-07 19:22
Thanks for taking the time to submit this feature request. It looks like this is a duplicate of #24223. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of #24223.

**Closed by rcskosir** 2024-05-07 19:22 UTC
Labels: duplicate, service/app-service, v/3.x
