### ISSUE TITLE
Support for SameZone as the available value for high_availability.mode in azurerm_postgresql_flexible_server

### ISSUE THREAD

**Issue by jchenau** [hashicorp/terraform-provider-azurerm#17593] opened 2022-07-12 03:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

according to the document https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/postgresql_flexible_server#mode it only supports `ZoneRedundant` and it does give me an error when I try to set `mode` to `SameZone`

```
      # │ Error: expected high_availability.0.mode to be one of [ZoneRedundant], got SameZone
      # │
      # │   with module.postgres_flexible_address.azurerm_postgresql_flexible_server.main,
      # │   on ../../../../../terraform-modules/modules/azure-postgres-flexible/main.tf line 26, in resource "azurerm_postgresql_flexible_server" "main":
      # │   26: resource "azurerm_postgresql_flexible_server" "main" {
```

However this value is already available in azure api , e.g. if I manually enabled same zone HA in the portal, and I keep the terraform code without enableing HA , the terraform plan will show this

```
  # module.postgres_flexible_address.azurerm_postgresql_flexible_server.main will be updated in-place
  ~ resource "azurerm_postgresql_flexible_server" "main" {
        name                          = "postgres-o2o-prod-logistics-domain-address"
        # (15 unchanged attributes hidden)

      - high_availability {
          - mode                      = "SameZone" -> null
          - standby_availability_zone = "1" -> null
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
``` 

### New or Affected Resource(s)/Data Source(s)

azurerm_postgresql_flexible_server

**Comment by sinbai** [comment] 2022-07-12 09:42
@jchenship thanks for opening this issue here. Unfortunately, terraform could not currently support it, as `SameZone` is not yet supported in the latest stable verion of [Azure API](https://github.com/Azure/azure-rest-api-specs/blob/16529f1d2f62357a57100a66011c271005989ba1/specification/postgresql/resource-manager/Microsoft.DBforPostgreSQL/stable/2021-06-01/postgresql.json#L1763).

**Comment by sharebear** [comment] 2022-08-08 06:23
As a help to anyone stumbling across this issue looking for a solution, a team working close to me got this working by using the `azapi_update_resource` to set the mode property.

**Comment by nilpferd21** [comment] 2022-11-23 07:13
In the following preview version of the Azure REST API, they support SameZone HA:
https://github.com/Azure/azure-rest-api-specs/blob/7a54c1a83d14da431c0ae48c4315cba143084bce/specification/postgresql/resource-manager/Microsoft.DBforPostgreSQL/preview/2022-01-20-preview/postgresql.json#L1846

Does this help? Is it an option for the Terraform Azurerm provider to use this version of the API?

**Comment by Doctorbal** [comment] 2022-12-08 22:43
> As a help to anyone stumbling across this issue looking for a solution, a team working close to me got this working by using the `azapi_update_resource` to set the mode property.

For others who are looking for an answer...

```
# if region is "westus2" then use "azapi_update_resource" to set high_availablity to SameZone
resource "azapi_update_resource" "repo_flex_db_server_uswest2_high_availability" {
  count       = var.repo_location == "westus2" ? 1 : 0
  type        = "Microsoft.DBforPostgreSQL/flexibleServers@2022-01-20-preview"
  resource_id = azurerm_postgresql_flexible_server.repo_flex_db_server.id

  body = jsonencode({
    properties = {
      highAvailability = {
        mode                    = "SameZone"
        standbyAvailabilityZone = "1"
      }
    }
  })

  depends_on = [
    azurerm_postgresql_flexible_server.repo_flex_db_server
  ]
}
```

**Comment by xadozuk** [comment] 2023-03-02 16:18
Support for `SameZone` have been added in this PR: #20298 
Available in version 3.43 of the provider.

**Comment by lra** [comment] 2023-03-09 15:31
Confirmed to work for us, thanks!

**Comment by sinbai** [comment] 2023-03-10 02:16
@jchenau since the feature is already supported, are you okey if we close this issue ?

**Comment by jchenau** [comment] 2023-03-10 04:59
Yeah sure, we can close it

**Closed** 2023-03-21 12:14 UTC
