### ISSUE TITLE
Support generic OIDC implementation via environment variable

### ISSUE THREAD

**Issue by ekristen** [hashicorp/terraform-provider-azurerm#16901] opened 2022-05-21 00:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.9

### AzureRM Provider Version

3.7.0

### Affected Resource(s)/Data Source(s)

azurerm

### Overview of Problem

The current OIDC authentication for a Service Principal is misleading as it's not actually OIDC support but GitHub Actions implemention of OIDC authentication.

I opened a feature request for implementing OIDC authentication. https://github.com/hashicorp/terraform-provider-azurerm/issues/16900

The current implementation only works for GitHub Actions and not the two other versions of Federated Credentials that are available for Service Principal, Kubernetes and Generic OIDC Issuer.

The provider's documentation indicates that this is authentication with OIDC and then proceeds to mention how to configure it with GitHub Actions, and while technically the final information that is sent to Azure is a JWT for federated OIDC, it's a specific GitHub implementation that only allows it to work with GitHub not actually as an OIDC authenticator.

The documentation should be updated to indicate that this only works with the GitHub Actions Federated Credentials. 

### Background and Fix

For some additional background and explanation for how this works. There are 3 federated credential types for a service principal: GitHub Actions, Kubernetes, and OIDC Issuer. While they are all OIDC, the GitHub Actions requires an extra step which makes the other two method NOT work with this current implementation.

With Kubernetes and OIDC Issuer you must have a valid JWT token from the issuer and pass that via Hamilton or the Azure SDK and autorest/bearer authentication, when this is done, Azure validates the JWT and allows actions to take place.

With GitHub, there's a special HTTP call that must be made **BEFORE** the requests to Azure take place.

When running in GitHub Actions there is not JWT only the equivalent to a PAT and it has to be exchanged for a JWT that is then sent to Azure. 

The current implementation makes use of `ARM_OIDC_REQUEST_URL` which is an alias to `ACTIONS_ID_TOKEN_REQUEST_URL` (this is set by GitHub Actions) and `ARM_OIDC_REQUEST_TOKEN` or `ACTIONS_ID_TOKEN_REQUEST_TOKEN` (again set by GitHub Actions).

When you go to run terraform and these are set it is suppose to call a special e ndpoint that github hosts to exchange a GitHub PAT/Actions Token for a JWT, then take that response and send it as part of the autorest auth for Hamilton and the Azure SDK.

What needs to happen is have an environment variable that has a JWT (ARM_ODIC_TOKEN) and just send direct to Azure and only if any of the ACTIONS_ID_* vars exist do the two step auth where you call to GitHub first.

**Comment by manicminer** [comment] 2022-05-30 10:10
Hi @ekristen, thanks for requesting this. I agree we can improve the documentation to clarify that the OIDC implementation is designed for GitHub Actions.

If I understand correctly, you're saying that a generic implementation such as accepting an ID token directly by environment variable could be made to work with Kubernetes? Do you perhaps have any documentation links on this particular scenario (identity authenticated by Kubernetes on behalf of AAD)?

I appreciate your time taken to open this issue and #16900. I think it makes sense to look at improvements around the documentation and the implementation together, so in the interest of consolidating conversation around this, I've gone ahead and closed the other issue as a duplicate of this one. Thanks!

**Comment by ekristen** [comment] 2022-05-31 02:23
You understand correctly.  If things can be made to accept a JWT token as pass via just the standard client credentials in the hamilton library (via https://github.com/manicminer/hamilton/blob/main/auth/clientcredentials.go#L76) then any OIDC provider (kubernetes or otherwise) that's configured with Azure Service Principals will work.

I would recommend something like `ARM_OIDC_TOKEN` for the provider.

**Comment by hungnguyen10897** [comment] 2022-07-18 13:16
Any updates on this? I agree the documentation is bit misleading, it should state explicitly OIDC for Github Actions. We are using OIDC for Kubernetes workload and we can't authenticate to Terraform azurerm backend.

**Comment by ekristen** [comment] 2022-07-18 14:32
I got a PR merged on the hamilton library, that's the first step to getting true OIDC support built in. I'm using OIDC for Kubernetes as well, which is why I'm making this effort.

**Comment by derkoe** [comment] 2022-08-08 12:20
GitLab has now also a working OIDC implementation (in alpha) which also directly provides the id token. This feature would enable secret-less authentication for GitLab CI pipelines.

See:
- https://docs.gitlab.com/ee/ci/cloud_services/
- https://gitlab.com/gitlab-org/gitlab/-/merge_requests/94461

**Comment by samgladstone** [comment] 2022-08-23 11:22
I'd like to echo @derkoe's comment. I've just lost a load of time trying to get this to work with GitLab, before finally realising this only works with GitHub. 

I see @derkoe's also opened a [pull request](https://github.com/hashicorp/go-azure-helpers/pull/128) against [the above issue](https://github.com/hashicorp/go-azure-helpers/issues/126) to add the generic token support to the go library (Nice 1 👍).

Perhaps we should add a warning to the docs to say that highlight this issue (I've raised a [PR for that here](https://github.com/hashicorp/terraform-provider-azurerm/pull/18081))

**Comment by Amier3** [comment] 2022-08-24 19:08
Just merged Sam's PR for the documentation fix, hopefully this will help in the future. Sorry to all the people that had to figure this out the hard way 😅

**Closed** 2022-08-25 13:48 UTC
Labels: enhancement, good first issue, authentication

**Comment by derkoe** [comment] 2022-08-26 07:23
If you want to see how this can be used with GitLab CI - here is my demo for this: https://gitlab.com/derkoe/azure-terraform-oidc
