### ISSUE TITLE
Support for types over parameters and variables of azure datafactory dataset or pipeline

### ISSUE THREAD

**Issue by carvarr** [hashicorp/terraform-provider-azurerm#19417] opened 2022-11-24 00:04 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When trying to create a dataset or pipeline in azure datafactory usually you could add parameters and variables to them, these properties are typed to one of the following: String, Int, Float, Bool, Array, Object, SecureString.

In terraform if you use this resource azurerm_data_factory_custom_dataset to create a new dataset in azure datafactory, your can pass parameters or variables but it only permit as String type. This is a little anoying because you need to change that directly in datafactory.

Could be feasible to add support for typing in these 2 properties for both datasets and pipelines ?

### New or Affected Resource(s)/Data Source(s)

azurerm_data_factory_custom_dataset, azurerm_data_factory_pipeline

### Potential Terraform Configuration

```hcl
resource "azurerm_data_factory_pipeline" "adf_my_pipeline" {
  name            = "my_pipeline"
  data_factory_id = var.adf_id
  parameters = {
    param1   = {
      type   = bool,
      value  = true
    },
  }
}
```

**Comment by mybayern1974** [comment] 2022-11-28 02:21
@carvarr, thanks for opening this issue.

Taking a look through this appears to be a duplicate of #13131. Rather than having multiple issues open tracking the same thing I'm going to close this issue in favor of that one; would you mind subscribing to #13131 for updates? Or feel free to reopen if you believe these two issues are not talking about the same thing.

Thanks!

**Closed by mybayern1974** 2022-11-28 02:21 UTC
