### ISSUE TITLE
azurerm_storage_share no default access_tier set

### ISSUE THREAD

**Issue by IanMoroney** [hashicorp/terraform-provider-azurerm#17622] opened 2022-07-13 13:28 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.1

### AzureRM Provider Version

3.7.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_share

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "azuretest"
  location = "West Europe"
}

resource "azurerm_storage_account" "example" {
  name                     = "azureteststorage"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_storage_share" "example" {
  name                 = "sharename"
  storage_account_name = azurerm_storage_account.example.name
  quota                = 50

  acl {
    id = "MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI"

    access_policy {
      permissions = "rwdl"
      start       = "2019-07-02T09:38:21.0000000Z"
      expiry      = "2019-07-02T10:38:21.0000000Z"
    }
  }
}
```

### Debug Output/Panic Output

```shell
Terraform will perform the following actions:

  # azurerm_storage_share.example will be updated in-place
  ~ resource "azurerm_storage_share" "example" {
      - access_tier          = "TransactionOptimized" -> null
        id                   = "https://azureteststorage.file.core.windows.net/sharename"
        name                 = "sharename"
        # (6 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Expected Behaviour

`TransactionOptimized` should not be set back to null because `TransactionOptimized` is the default access tier according to [the documentation](https://docs.microsoft.com/en-us/azure/storage/files/storage-how-to-create-file-share?tabs=azure-portal#create-a-file-share)

### Actual Behaviour

The default access_tier of `TransactionOptimized` is set to null on every plan/apply

**Comment by rcskosir** [comment] 2024-09-11 17:50
Thanks for opening this issue. Since time has passed (v4.x is latest) and @mbfrahry was not able to reproduce this issue (see linked PR comments), I am going to mark this issue closed as “can’t reproduce”. If you are able to provide more information to help us reproduce this issue we may re-open this issue or open a new issue, thanks!

**Closed by rcskosir** 2024-09-11 17:50 UTC
Labels: service/storage, v/3.x
