### ISSUE TITLE
OIDC authentication with managed identity broke after version 3.44

### ISSUE THREAD

**Issue by audunsolemdal** [hashicorp/terraform-provider-azurerm#20564] opened 2023-02-20 07:05 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.9

### AzureRM Provider Version

3.44.1

### Affected Resource(s)/Data Source(s)

provider["registry.terraform.io/hashicorp/azurerm"]

### Terraform Configuration Files

```hcl
terraform {
  required_version = "~> 1.3"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.44"
    }
  }

  backend "azurerm" {
    resource_group_name  = "xxx"
    storage_account_name = "xxx"
    container_name       = "xxx"
    key                  = "xxx"
    subscription_id      = "xxx"
    use_azuread_auth     = true
  }
}

provider "azurerm" {
  features {}
  subscription_id = "yyy"
}

Relevant parts of github workflow:


env:
  ARM_CLIENT_ID: "MY_CLIENT_ID"
  ARM_USE_OIDC: true
  ARM_TENANT_ID: "MY_TENANT_ID"

jobs:
  plan:
    permissions:
      id-token: write
      contents: write
    name: Terraform Plan

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: ${{ inputs.tfVersion }}
          terraform_wrapper: false

      - name: terraform init -upgrade
        id: init
        run: terraform init -upgrade

      - name: Terraform Plan with varFile specified
        run: |
          terraform plan -out=plan.tfplan
        continue-on-error: true
```

### Debug Output/Panic Output

```shell
Error: building account: could not acquire access token to parse claims: clientCredentialsToken: received HTTP status 400 with response: {"error":"unauthorized_client","error_description":"AADSTS700016: Application with identifier 'MY_TENANT_ID' was not found in the directory 'MY_TENANT_DISPLAY_NAME'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.\r\nTrace ID: 9d7a29bb-2e0a-44e5-936b-0c6510851900\r\nCorrelation ID: b602ef6f-73e5-403e-93b5-c7c2394999bb\r\nTimestamp: 2023-02-20 06:46:22Z","error_codes":[700016],"timestamp":"2023-02-20 06:46:22Z","trace_id":"9d7a29bb-2e0a-44e5-936b-0c6510851900","correlation_id":"b602ef6f-73e5-403e-93b5-c7c2394999bb","error_uri":"https://login.microsoftonline.com/error?code=700016"}
```

### Expected Behaviour

Either a notice on how to fix the issue or revert to previous behaviour where it worked fine.

The described method worked fine up to version 3.43

### Actual Behaviour

terraform init works fine, while terraform plan/apply is not working

terraform plan for some reason believes that the tenant ID is the application ID, see where the output is sanitized to `MY_TENANT_ID`

### Steps to Reproduce

terraform plan

**Comment by Strikysha** [comment] 2023-02-20 11:14
Duplicate of https://github.com/hashicorp/terraform-provider-azurerm/issues/20546

**Comment by mybayern1974** [comment] 2023-02-21 01:26
Thank you @audunsolemdal for filing this issue. Given it's dup with #20546 as Strikysha pointed, I'm closing this issue in favor of that already filed one that indicates the fix would go live in the next release version 3.45.0.

**Closed by mybayern1974** 2023-02-21 01:26 UTC
Labels: duplicate
