### ISSUE TITLE
MSsql as input for Azure Stream Analytics

### ISSUE THREAD

**Issue by aalvarezd** [hashicorp/terraform-provider-azurerm#4557] opened 2019-10-08 09:05 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure has an *input* alternative for ASA services. This is a connection to MSSQL through queries. It would be interesting to have the resource in Terraform. Thanks

### New or Affected Resource(s)

* azurerm_stream_analytics_input_mssql : New

### References

* https://docs.microsoft.com/en-us/azure/stream-analytics/stream-analytics-use-reference-data#azure-sql-database

**Comment by stephybun** [comment] 2021-11-19 09:16
Duplicate of #9231, closed by #13822 and released in v2.83.0.

**Closed by stephybun** 2021-11-19 09:16 UTC
Labels: new-resource, service/stream-analytics
