### ISSUE TITLE
subscription_id provider property not enforcing the subscription for all resources

### ISSUE THREAD

**Issue by lra** [hashicorp/terraform-provider-azurerm#14415] opened 2021-12-01 09:47 UTC
I'm opening the same issue again, as this is problematic and the original issue has been closed by a robot: https://github.com/hashicorp/terraform-provider-azurerm/issues/13830

If you want more details, check the previous issue. Now that it's been closed, I cannot copy paste the markdown easily.

# Issue

The `subscription_id` property of the provider is ignored when the `az` cli has a default subscription set.

It should be the opposite: when we set a subscription_id property on the provider, it should ignore the default subscription of the `az` cli and use the one defined in the provider block.

This is clearly a bug, and because of this, we have to set a `ARM_SUBSCRIPTION_ID` env var in every terraform workspace using the azurerm provider, and ask every co-worker to do the same on their local setup. And we have a lot.

If we don't do this, terraform will plan and apply resources in whatever current subscription has been set on the az cli at the time of the plan/apply, and it leads to confusion/mistakes. The subscription_id property of the provider is supposed to enforce a subscription, it's not.

**Comment by lra** [comment] 2021-12-01 09:49
Mentioning @lpiob and @MindAwakeBodyAsleep who also encounter this issue, in case more information is needed.

**Comment by MindAwakeBodyAsleep** [comment] 2021-12-01 10:20
@lra do you correctly pass azure provider to module? In our case there was issue with that which was resolved when I declare provider in our terraform live repository like this:

  `provider "azurerm" {
  features {
    key_vault {
      purge_soft_delete_on_destroy = true
    }

    api_management {
      purge_soft_delete_on_destroy = true
    }
  }
  subscription_id = "XXXX"
}`
 and then I pass it to the module:
 
 `module "main" {
  source = "git::ssh://git@git.mycompany.com/group/repo.git?ref=v1.3.0"
  providers = {
    azurerm = azurerm
  }
  ....
`

**Comment by tombuildsstuff** [comment] 2021-12-01 15:12
hi @lra 

Thanks for opening this issue.

As @MindAwakeBodyAsleep has mentioned above, this is a configuration issue - this forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Closed by tombuildsstuff** 2021-12-01 15:12 UTC

**Comment by lra** [comment] 2021-12-01 15:37
Again, this is not a configuration issue.
When I set the `subscription_id` parameter to the `azurerm` provider, it is not followed if I set an `ARM_SUBSCRIPTION_ID` env var on top of it.

This is a bug.

**Comment by tombuildsstuff** [comment] 2021-12-01 17:27
@lra unfortunately this is a Terraform Configuration issue, not a bug in the provider - you'll need to thread the provider blocks through to any modules used, as @MindAwakeBodyAsleep has described above, which is likely the source of this. As mentioned above, since this is a configuration question rather than a bug in the Provider we'll have to redirect this but feel free to open an issue on [the Community Discuss forum](https://discuss.hashicorp.com) where someone should be able to assist with this configuration issue.

Thanks!

**Comment by lra** [comment] 2021-12-01 20:34
Thanks for letting me comment back. That's annoying to dig issues and spend time to try to pin to the actual problem, to see those closed without a way to add feedback.

I'll double check on our side, but this seems strange that only the azure provider would require such a thing, when the aws (with the `allowed_account_ids ` property) and the gcp provider (account_id property) don't require to be passed around when they are the default providers.

I'll double check to make sure, and at least will try to bring a simple way to reproduce the problem if not.

**Comment by lra** [comment] 2021-12-01 20:49
Finally found the issue: You don't need to pass the default provider around, but we had this empty provider definition in a sub-sub-module that was overriding the default provider config from the root module:
```
provider "azurerm" {
  features {}
}
```
Apologies about the trouble, and thanks for helping us solve this issue.
