### ISSUE TITLE
Enable MSI and retrieve object id in azurerm_logic_app_workflow

### ISSUE THREAD

**Issue by gburton1** [hashicorp/terraform-provider-azurerm#2924] opened 2019-02-20 23:49 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We'd like the ability to enable MSI from an azurerm_logic_app_workflow, and then capture that object id into an output that can be used in other resources.

### New or Affected Resource(s)

azurerm_logic_app_workflow

### References

https://docs.microsoft.com/en-us/azure/logic-apps/create-managed-service-identity

**Comment by rohrerb** [comment] 2019-02-21 00:13
@tombuildsstuff or @JunyiYi  do you know if this is possible today or is this a net new feature?

**Comment by dhabierre** [comment] 2019-03-15 16:38
I need this feature too!

Using Terraform I create an **azurerm_logic_app_workflow** resource. The LogicApp needs to access a KeyVault secret.

But at present time it is not possible to enable MSI (it is possible with azurerm_app_service resources) and then retrieve the **object_id** in order to create an access_policy.

Thanks!

**Comment by dhabierre** [comment] 2019-03-16 11:13
My current solution.

**Terraform**

```terraform
locals {
  "domain" = "${var.environment}-${var.application}"
}

resource "azurerm_logic_app_workflow" "logic_app_workflow_get_secret" {
  name                = "${local.domain}-logic-app-get-secret}"
  location            = "${azurerm_resource_group.resource_group.location}"
  resource_group_name = "${azurerm_resource_group.resource_group.name}"
  tags                = "${local.tags}"

  lifecycle {
    ignore_changes = ["parameters", "tags"] # prevent that Terraform fails while updating the container once the LogicApp ARM has been deployed the first time
  }
}
```

**LogicApp that required MSI to access to KeyVault secrets**

Just add _identity.type = "SystemAssigned"_

```json
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": { ... },
  "resources": [
    {
      "apiVersion": "2017-07-01",
      "location": "[parameters('location')]",
      "name": "[parameters('workflowName')]",
      "properties": {
        "definition": {
          "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
          "actions": { ... },
          "parameters": { ... },
          "triggers": { ... },
          "contentVersion": "1.0.0.0",
          "outputs": {}
        },
        "parameters": { ... },
        "identity": {
          "type": "SystemAssigned"
        },
      "tags": { ... },
      "type": "Microsoft.Logic/workflows"
    }
  ],
  "outputs": {}
}
```

Note: this LogicApp is deployed using an _Azure Resource Group Deployment_ task.

**Azure DevOps / Release**

Add an _Azure CLI_ task in order to create the Access Policy:

```powershell
call az resource show --resource-group $(environment)-$(application) --name $(environment)-$(application)-logic-app-get-secret --resource-type Microsoft.Logic/workflows --api-version 2016-06-01 --query "identity.principalId" > tmpData

set /p data= < tmpData

call az keyvault set-policy --name "$(environment)-$(application)-keyvault" --object-id %data% --key-permissions get list --secret-permissions get list
```

**Tips :** to retrieve the LogicApp Url trigger (_Azure PowerShell_ task):

```powershell
$workflowName = "$(environment)-$(application)-logic-app-get-secret"

$data = Get-AzureRmLogicAppTriggerCallbackUrl -ResourceGroupName "$(environment)-$(application)" -Name $workflowName -TriggerName "manual"

$endpoint = $data.Value

Write-Host "##vso[task.setvariable variable=LogicAppGetSecretEndpoint]$endpoint"
```

**Comment by willjblair** [comment] 2020-04-23 14:15
> Just add identity.type = "SystemAssigned"

Does this setup work when deploying for you? In [Microsoft documentation](https://docs.microsoft.com/en-us/azure/logic-apps/create-managed-service-identity#template-system-logic-app) the `identity` is included at the top level of the ARM resource definition, not in the `properties` object.

I agree that this process would be much simpler in terraforms though

**Comment by rom1gal** [comment] 2020-07-31 11:04
Hey there,

Any updates on that issue ?

Thanks !

**Comment by rom1gal** [comment] 2020-11-02 14:43
Hi ! 

Still UPping the topic just in case :)

**Comment by fewbits** [comment] 2020-11-18 01:52
I also needed this feature and end up finding this issue.

I need to create Logic Apps to startup and shutdown some VMs based on a certain recurrence. I was wondering wether to use Logic Apps, Function Apps or Automation Account, but I found that using Logic Apps was the simplest solution. The problem is that I need to use a system assigned or used assigned managed identity onto these Logic Apps to give them permission to control the VMs.

**Comment by shybbko** [comment] 2020-11-18 20:27
> I also needed this feature and end up finding this issue.
> 
> I need to create Logic Apps to startup and shutdown some VMs based on a certain recurrence. I was wondering wether to use Logic Apps, Function Apps or Automation Account, but I found that using Logic Apps was the simplest solution. The problem is that I need to use a system assigned or used assigned managed identity onto these Logic Apps to give them permission to control the VMs.
I might be wrong (and I don't have an active Azure subscription to test / confirm), but I believe that you have an option to configure identity in Logic Apps manually via portal, then download the whole config as an ARM and deploy it that way via Terraform. Something along these lines.

**Comment by BartDevelopment** [comment] 2020-12-28 12:58
Are any updates with it?

**Comment by geekzter** [comment] 2021-01-20 08:31
With Logic Apps [now supporting MSI for (more) connectors](https://techcommunity.microsoft.com/t5/integrations-on-azure/azure-logic-apps-authenticate-with-managed-identity-for-azure-ad/ba-p/2066254), this is becoming a more relevant capability to have.

**Comment by JFolberth** [comment] 2021-01-29 19:27
Still relatively new to Terraform and noticed this wasn't supported but also been working in Project Bicep and noticed they have the same issue and have opened it up with the Logic App project team https://github.com/Azure/azure-rest-api-specs/issues/11986  Not sure if the two are related or not but seems too coincidental.

**Comment by dhabierre** [comment] 2021-01-29 19:44
> > Just add identity.type = "SystemAssigned"
> 
> @dhabierre Does this setup work when deploying for you? In [Microsoft documentation](https://docs.microsoft.com/en-us/azure/logic-apps/create-managed-service-identity#template-system-logic-app) the `identity` is included at the top level of the ARM resource definition, not in the `properties` object.
> 
> I agree that this process would be much simpler in terraforms though

From memory, yes it worked.

**Comment by pjolsen** [comment] 2021-02-03 13:05
So is this being looked at? Would be great to have this functionality in the provider.

**Comment by darren-johnson** [comment] 2021-03-30 06:41
I really need this too. Have done it in the past by creating an arm template and deploying via terraform which isn't our company standard. Any idea of an eta on this?

**Comment by magichappens89** [comment] 2021-03-30 14:44
I also need this feature. Could we get a status update?

**Comment by kaovd** [comment] 2021-05-20 13:33
Still not available in the spec https://github.com/Azure/azure-sdk-for-go/blob/master/services/logic/mgmt/2019-05-01/logic/models.go#L5773

Possibly go dig through azure-rest-api-specs and see what's there at the upstream. Likely to be tracked in the properties section somewhere.

**Comment by sit-md** [comment] 2021-10-06 07:32
Thank you for looking into it @tombuildsstuff. As mentioned by @JFolberth there already is an issue open on the Azure Rest API Specs Repository. It has been opened by the Bicep team because they also had an issue with it being missing from the specs. They had the luxury of being able to work around it though by simply issuing a warning instead of a hard error in their transpiler. Therefore the latest comment in [Azure/azure-rest-api-specs#11986](https://github.com/Azure/azure-rest-api-specs/issues/11986) states that the ETA for the Swagger fix will be sometime in the end of calendar year 2021. Let's hope this comes soon as I am also struggling with this. For the time being as a workaround we will have to rely on deploying ARM files through Terraform to enable this feature.

**Comment by tombuildsstuff** [comment] 2021-10-19 05:21
To give an update here: the Swagger changes have been merged in https://github.com/Azure/azure-rest-api-specs/pull/16181 - so _at some point_ in the near future this'll make it's way through to an upcoming version of the Azure SDK, at which point someone should be able to look at implementing support for this.

**Comment by Tiduster** [comment] 2022-04-08 23:16
Hi !
I was able to create logic_app_workflow with Managed System Identity without any issue.
Even if this issue is still open, do you think this has been resolved by a recent release?

**Comment by pjolsen** [comment] 2022-04-09 11:36
> Hi !
> I was able to create logic_app_workflow with Managed System Identity without any issue.
> Even if this issue is still open, do you think this has been resolved by a recent release?

From memory the issue was that you couldn’t get the Managed id back from the object so any subsequent role assignments etc were not possible

**Comment by Tiduster** [comment] 2022-04-10 20:30
@pjolsen : the following code is working fine in our infrastructure:

```
resource "azurerm_logic_app_workflow" "http_triggered" {
  name                = "logic-${var.environment}-bastion_http-${var.location}"
  location            = azurerm_resource_group.this.location
  resource_group_name = azurerm_resource_group.this.name

  workflow_parameters = {
    "$connections" = jsonencode({ "defaultValue" = {}, "type" = "Object" })
  }

  identity {
    type = "SystemAssigned"
  }

  parameters = {
    "$connections" = jsonencode({
      "arm" = {
        "connectionId"   = azurerm_api_connection.arm.id,
        "connectionName" = azurerm_api_connection.arm.name,
        "connectionProperties" = {
          "authentication" = {
            "type" = "ManagedServiceIdentity"
          }
        },
        "id" = "/subscriptions/${data.azurerm_subscription.current.subscription_id}/providers/Microsoft.Web/locations/francecentral/managedApis/arm"
      }
    })
  }
}

resource "azurerm_role_assignment" "logic_app_workflow_http_triggered_ownership" {
  scope                = azurerm_resource_group.this.id
  role_definition_name = "Owner"
  principal_id         = azurerm_logic_app_workflow.http_triggered.identity[0].principal_id
}

resource "azurerm_role_assignment" "logic_app_workflow_http_triggered_subnet" {
  scope                = var.vnet_resource_group_id
  role_definition_name = var.custom_role_definition_name
  principal_id         = azurerm_logic_app_workflow.http_triggered.identity[0].principal_id
}
```

**Comment by catriona-m** [comment] 2022-11-24 15:14
It looks like this functionality has now been added so this can be closed now. Thanks!

**Closed by catriona-m** 2022-11-24 15:14 UTC
Labels: enhancement, upstream/microsoft, service/logic, sdk/not-yet-supported
