### ISSUE TITLE
The name "" used for the App Service needs to be globally unique and isn't available

### ISSUE THREAD

**Issue by amamidwar** [hashicorp/terraform-provider-azurerm#15059] opened 2022-01-21 13:26 UTC
I am getting the below error while creation of Azure appservices through terraform script (version: 0.13 and 1.11 both),

`Error: The name "" used for the App Service needs to be globally unique and isn't available: Site names only allow alphanumeric characters and hyphens, cannot start or end in a hyphen, and must be less than 64 chars. `

It was working properly earlier in the azure devops release pipeline, but now I am having issue in azure devops release pipeline as well as in my local machine with different name.. which I have tested it as a unique name.. I am able to create azure appservice from the portal by using  same name.. but not working through terraform script... 

I have tried to execute same version with another local machine with another different name, but no luck. 
Can you please help me with this?

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request

**Comment by tombuildsstuff** [comment] 2022-01-21 13:28
hi @amamidwar 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Closed by tombuildsstuff** 2022-01-21 13:28 UTC
Labels: question

**Comment by SebastianBalle** [comment] 2022-01-21 14:23
@tombuildsstuff

We had the same error using AzureRM provider v2.93.0 when initially provisioning the Azure App Service resource. The `apply` command was executed with the `-target` flag. The error was resolved when using AzureRM v2.92.0.
Terraform version used: 1.0.11 via Terraform Cloud. 

After the Azure App Service was provisioned with AzureRM provider v2.92.0 the AzureRM provider was upgraded to v2.93.0 with no issues going forward. The upgrade was made using the `terraform init -upgrade` command. The following was used to control the provider version in the source code.
```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=2.93.0"
    }
  }
```

**Comment by jackofallops** [comment] 2022-01-21 14:44
Hi @amamidwar and @SebastianBalle -   That message can some back from several resources within that service, for a variety of reasons, so we need to understand what was in use, and what was going on at the time? For example, was this with `azurerm_app_service` or one of the replacement resources for that in the beta? Was it part of an App Service Environment?  If one of you could open a new issue using either the [Bug Report](https://github.com/hashicorp/terraform-provider-azurerm/issues/new?assignees=&labels=&template=Bug_Report.md) or [Beta Bug Report](https://github.com/hashicorp/terraform-provider-azurerm/issues/new?assignees=&labels=&template=Beta_Feedback.md), whichever is appropriate with some details, we can review and take action where needed.
Thanks!

**Comment by marcindulak** [comment] 2022-01-21 17:35
Please see https://github.com/hashicorp/terraform-provider-azurerm/issues/15064 for an example to reproduce.
