### ISSUE TITLE
azurerm_mysql_flexible_server report "identity" are not expected here

### ISSUE THREAD

**Issue by rsun-thoughtworks** [hashicorp/terraform-provider-azurerm#20521] opened 2023-02-17 08:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.9

### AzureRM Provider Version

3.38.0

### Affected Resource(s)/Data Source(s)

azurerm_mysql_flexible_server

### Terraform Configuration Files

```hcl
resource "azurerm_mysql_flexible_server" "mysql_server" {
  name                   = var.name
  resource_group_name    = var.resource_group_name
  location               = var.location
  administrator_login    = var.administrator_login
  administrator_password = var.administrator_password
  backup_retention_days  = var.backup_retention_days
  delegated_subnet_id    = azurerm_subnet.mysql_server_subnet.id
  private_dns_zone_id    = azurerm_private_dns_zone.mysql_flexible_server_dns_zone.id
  sku_name               = var.sku_name
  create_mode            = var.create_mode
  version                = var.mysql_version
  zone                   = var.zone
  storage {
    auto_grow_enabled = true
    iops              = var.iops
    size_gb           = var.storage_size_gb
  }
  identity {
    # (Required) The Type of Identity which should be used for this MySQL Server. At this time the only possible value is SystemAssigned.
    type = "SystemAssigned"
  }

  tags = var.tags
}
```

### Debug Output/Panic Output

```shell
Run terraform validate
terraform-bin validate
╷
│ Error: Unsupported block type
│ 
│   on main.tf line 43, in resource "azurerm_mysql_flexible_server" "mysql_server":
│   43:   identity {
│ 
│ Blocks of type "identity" are not expected here.
╵
Error: Terraform exited with code 1.
Error: Process completed with exit code 1.
```

### Expected Behaviour

No error message

### Actual Behaviour

Report error

**Comment by neil-yechenwei** [comment] 2023-02-20 12:57
Thanks for raising this issue. Per the description of azure rest api, seems it only supports [userAssignedIdentity](https://learn.microsoft.com/en-us/rest/api/mysql/flexibleserver/servers/create?tabs=HTTP#managedserviceidentitytype).

**Comment by rcskosir** [comment] 2023-10-31 15:06
Thanks for taking the time to submit this issue. @neil-yechenwei was unable to reproduce this behavior. We’re going to close this issue for now, but if you run into this again with the latest Terraform and Provider versions, please feel free to [open a new issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/new/choose).

**Closed by rcskosir** 2023-10-31 15:06 UTC
Labels: bug, waiting-response, service/mysql, v/3.x
