### ISSUE TITLE
Creation of private Link for Application gateway fails

### ISSUE THREAD

**Issue by MelleD** [hashicorp/terraform-provider-azurerm#16897] opened 2022-05-20 18:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.0

### AzureRM Provider Version

3.7.0

### Affected Resource(s)/Data Source(s)

azurerm_application_gateway

### Terraform Configuration Files

```hcl
locals {
  private_link_configuration_name        = "${var.name}-private-link"
  private_frontend_ip_configuration_name = "${var.name}-frontend-private-link"

}


resource "azurerm_application_gateway" "AppGateway" {
  name                = var.name

  private_link_configuration {
    name = local.private_link_configuration_name

    ip_configuration {
      name                          = "primary"
      subnet_id                     = var.subnet_id
      private_ip_address_allocation = "Dynamic"
      primary                       = true
    }
  }

  frontend_ip_configuration {
    name                            = local.private_frontend_ip_configuration_name
    subnet_id                       = var.subnet_id
    private_link_configuration_name = local.private_link_configuration_name
    private_ip_address_allocation   = "Static"
    private_ip_address              = var.private_ip_address
  }
}

resource "azurerm_private_endpoint" "AppGatewayPrivateEndpoint" {
  name                = "${azurerm_application_gateway.AppGateway.name}-private-endpoint"
  location            = azurerm_application_gateway.AppGateway.location
  resource_group_name = var.resource_group_name
  subnet_id           = var.private_endpoint_subnet_id

  private_service_connection {
    name                           = "${azurerm_application_gateway.AppGateway.name}-private-service-connection"
    private_connection_resource_id = azurerm_application_gateway.AppGateway.id
    is_manual_connection           = false
    subresource_names = [
      local.private_frontend_ip_configuration_name
    ]
  }
}
```

### Debug Output/Panic Output

```shell
Please make sure application gateway has private link configuration.\" Details=[]\n\nError: creating Private Endpoint \"gw-private-endpoint\" (Resource Group \"xxx-rg\"): network.PrivateEndpointsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code=\"ApplicationGatewayPrivateLinkOperationError\" Message=\"Call to Microsoft.Network/applicationGateways failed. Error message: Cannot perform private link operation on ApplicationGateway
```

### Expected Behaviour

Private link is created

### Actual Behaviour

Private link creation fails

### Steps to Reproduce

terraform apply

**Comment by ms-zhenhua** [comment] 2022-08-31 06:23
Hi @MelleD, thank you for reaching out.
Could you kindly help check the [sku](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_gateway#sku) you used in azurerm_application_gateway ? According to this [document](https://docs.microsoft.com/en-us/azure/application-gateway/overview-v2#feature-comparison-between-v1-sku-and-v2-sku), private link is not supported by v1 sku.

If you used v2 sku, could you kindly provide a runnable configuration (you can remove any sensitive information) so that I can try to reproduce this issue with the configuration and do more investigation on it. 
Thanks.

**Comment by MelleD** [comment] 2022-09-13 07:34
Hi @ms-zhenhua thanks for your help.

I tried to create an example. Not sure if it really runs, because we use it as module with a lots of variables. I just make the variables as strings. So don't be confused :)

```

variable "resource_group_name" {
  default = "resource-group"
}


variable "name" {
  default = "app-gateway"
}

variable "backend_pool_ip_addresses" {
  type = list(string)

  default = [
    "10.1.255.254",
  ]
}

data "azurerm_resource_group" "ResourceGroup" {
  name = var.resource_group_name
}

locals {
  private_link_configuration_name        = "${var.name}-private-link"
  private_frontend_ip_configuration_name = "${var.name}-frontend-private-link"

}

# Public IP
resource "azurerm_public_ip" "PublicIP" {
  name                = "local.public_ip_name"
  location            = azurerm_resource_group.ResourceGroup.location
  resource_group_name = azurerm_resource_group.ResourceGroup.name
  allocation_method   = "Static"
  sku                 = "Standard"

  lifecycle {
    ignore_changes = [
      # see breaking change https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/3.0-upgrade-guide#behavioural-updates
      zones
    ]
  }
}

resource "azurerm_virtual_network" "VNet" {
  name                = "vnet-name"
  resource_group_name = data.ResourceGroup.name

  #address_space = [
  #  var.vnet_ip_address_range,
  #]

  location = var.location
}

resource "azurerm_subnet" "Subnet" {
  name                                          = "subnet-name"
  resource_group_name                           = azurerm_resource_group.ResourceGroup.name
  virtual_network_name                          = azurerm_virtual_network.VNet.name
  address_prefixes                              = var.vnet_cluster_subnet_frontend_range
  enforce_private_link_service_network_policies = true

  service_endpoints = [
    "Microsoft.KeyVault"
  ]
}

resource "azurerm_application_gateway" "AppGateway" {
  name                = var.name
  resource_group_name = data.azurerm_resource_group.ResourceGroup.name
  location            = data.azurerm_resource_group.ResourceGroup.location

  sku {
    name = "WAF_v2"
    tier = "WAF_v2"
  }

  gateway_ip_configuration {
    name      = var.gateway_ip_configuration_name
    subnet_id = azurerm_subnet.Subnet.subnet_id
  }

  frontend_port {
    name = "var.https_frontend_port_name"
    port = 443
  }

  frontend_port {
    name = "var.http_frontend_port_name"
    port = 80
  }

  frontend_ip_configuration {
    name                 = "var.frontend_ip_configuration_name"
    public_ip_address_id = var.public_ip_address_id
  }

  backend_address_pool {
    name         = "var.backend_address_pool_name"
    ip_addresses = var.backend_pool_ip_addresses
  }

  backend_http_settings {
    affinity_cookie_name  = "ApplicationGatewayAffinity"
    name                  = "var.http_setting_name"
    cookie_based_affinity = "Disabled"
    port                  = 80
    protocol              = "Http"
    probe_name            = "var.health_probe.name"
  }

  http_listener {
    name                           = "var.http_listener_name"
    frontend_ip_configuration_name = var.frontend_ip_configuration_name
    frontend_port_name             = var.http_frontend_port_name
    protocol                       = "Http"
  }

  request_routing_rule {
    name                       = "var.https_request_routing_rule_name"
    rule_type                  = "Basic"
    http_listener_name         = "var.https_listener_name"
    backend_address_pool_name  = "var.backend_address_pool_name"
    backend_http_settings_name = "var.http_setting_name"
    priority                   = 1
  }

/*   Enable when https://github.com/hashicorp/terraform-provider-azurerm/issues/16897 is fixed
  frontend_ip_configuration {
    name                            = local.private_frontend_ip_configuration_name
    subnet_id                       = var.subnet_id
    private_link_configuration_name = local.private_link_configuration_name
    private_ip_address_allocation   = "Static"
    private_ip_address              = var.private_ip_address
  }

  private_link_configuration {
    name = local.private_link_configuration_name

    ip_configuration {
      name                          = "primary"
      subnet_id                     = var.private_endpoint_subnet_id
      private_ip_address_allocation = "Dynamic"
      primary                       = true
    }
  } */

  waf_configuration {
    enabled                  = true
    firewall_mode            = "Prevention"
    rule_set_type            = "OWASP"
    rule_set_version         = "3.1"
    max_request_body_size_kb = 128
    file_upload_limit_mb     = 1
  }
}

#Diagnostic Settings for Application Gateway
resource "azurerm_monitor_diagnostic_setting" "ApplicationGatewayDiagnostics" {
  name                       = "${azurerm_application_gateway.AppGateway.name}-diagnostics"
  target_resource_id         = azurerm_application_gateway.AppGateway.id
  log_analytics_workspace_id = var.log_analytics_workspace_id

  log {
    category = "ApplicationGatewayFirewallLog"

    retention_policy {
      enabled = true
    }
  }

  log {
    category = "ApplicationGatewayAccessLog"

    retention_policy {
      enabled = true
    }
  }

  log {
    category = "ApplicationGatewayPerformanceLog"

    retention_policy {
      enabled = true
    }
  }

  metric {
    category = "AllMetrics"
    enabled  = true

    retention_policy {
      enabled = true
    }
  }
}
/*   Enable when https://github.com/hashicorp/terraform-provider-azurerm/issues/16897 is fixed
resource "azurerm_private_endpoint" "AppGatewayPrivateEndpoint" {
  name                = "${azurerm_application_gateway.AppGateway.name}-private-endpoint"
  location            = azurerm_application_gateway.AppGateway.location
  resource_group_name = var.resource_group_name
  subnet_id           = var.private_endpoint_subnet_id

  private_service_connection {
    name                           = "${azurerm_application_gateway.AppGateway.name}-private-service-connection"
    private_connection_resource_id = azurerm_application_gateway.AppGateway.id
    is_manual_connection           = false
    subresource_names = [
      local.private_frontend_ip_configuration_name
    ]
  }
}
*/




```

**Comment by randolf720** [comment] 2022-11-01 10:42
If you change the subresource_names to: azurerm_application_gateway.AppGateway.frontend_ip_configuration[0].name it should work. Had the same error message.

**Comment by rcskosir** [comment] 2023-06-09 15:54
@MelleD Thank you for opening this issue. @randolf720 Thank you for your suggested fix. I am going to mark this issue as closed since it appears to be resolved by the suggestions above.

**Closed by rcskosir** 2023-06-09 15:54 UTC
Labels: service/application-gateway

**Comment by PhatAdam** [comment] 2023-12-21 17:55
Could just be me however this appears to still happen even with @randolf720's awsome suggestion.

╷
│ Error: creating Private Endpoint "ACB-AppGateway-pe" (Resource Group "ACB-AppG"): network.PrivateEndpointsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="ApplicationGatewayPrivateLinkOperationError" Message="Call to Microsoft.Network/applicationGateways failed. Error message: Cannot perform private link operation on ApplicationGateway /subscriptions/1357c6fc-7f12-4908-85b7-5a5f417eb9f7/resourceGroups/ACB-AppG/providers/Microsoft.Network/applicationGateways/ACB-AppGateway. Please make sure application gateway has private link configuration." Details=[]
│
│   with azurerm_private_endpoint.network,
│   on main.tf line 132, in resource "azurerm_private_endpoint" "network":
│  132: resource "azurerm_private_endpoint" "network" {
│
