### ISSUE TITLE
Support for setting CURRENT_STACK for Azure Functions, enabling durable Azure Functions on PowerShell

### ISSUE THREAD

**Issue by mariussm** [hashicorp/terraform-provider-azurerm#8867] opened 2020-10-13 08:27 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I am trying to create a azurerm_function_app with PowerShell 7 based durable Azure Functions. When the function app is created, the following setting is blank, which makes the durable functions return 500 internal server error:

![image](https://user-images.githubusercontent.com/426202/95834757-a5c13180-0d3d-11eb-864b-a2e2078c5dfc.png)

### New or Affected Resource(s)

* azurerm_function_app

### Potential Terraform Configuration

It seems that behind the scenes for the Azure Portal, the following is sent when updating the blank field to PowerShell 7.0 (as a part of siteConfig):

```
"metadata": [
    {
        "name": "CURRENT_STACK",
        "value": "powershell"
    }
]
```

```hcl
resource "azurerm_function_app" "function" {
  name                       = "superfunction"
  location                   = var.location
  resource_group_name        = azurerm_resource_group.rg.name
  app_service_plan_id        = azurerm_app_service_plan.function_plan.id
  storage_account_name       = azurerm_storage_account.function_storage.name
  storage_account_access_key = azurerm_storage_account.function_storage.primary_access_key
  version                    = "~3"
  https_only                 = true

  app_settings = {
    ApplicationInsightsAgent_EXTENSION_VERSION = "~2"
    FUNCTIONS_WORKER_RUNTIME                   = "powershell"
    FUNCTION_APP_EDIT_MODE                     = "readonly"
    WEBSITE_NODE_DEFAULT_VERSION               = "10.14.1"
  }

  identity {
    type = "SystemAssigned"
  }

  site_config {
    metadata = [
      {
        name = "CURRENT_STACK"
        value = "powershell"
      }
    ]
  }
}
```

**Comment by adamrushuk** [comment] 2020-11-04 09:12
I also have to manually update that PowerShell Core Version setting, and restart the function app to make it work, so looking forward to this fix.

I've seen other people define `siteConfig.powerShellVersion = "~7"` , eg: https://github.com/neumanndaniel/armtemplates/blob/aa14255f3a2be592ac60dc8ff541fda7cb10c649/aks-snapshot-backup/aks-snapshot-backup-infrastructure.json#L97

**Comment by antonismladenis** [comment] 2021-04-09 08:59
Hi I am facing the same issue with Terraform. I am trying to create a Powershell Function App in Azure with azurerm_function_app and I want to set Powershell Core Version to 7. The issue is that after terraform apply the Function App is created, but the Powershell Core Version is blank. I was able to set the Python version for a Linux Function App, but not for Powershell.

![Screenshot 2021-04-09 at 10 55 24](https://user-images.githubusercontent.com/7003385/114156075-dbc92200-992a-11eb-8f25-889504b31e70.png)

I tried something like that, but with no success:

```
resource "azurerm_function_app" "example" {
  name                       = "functionapptest"
  location                   = azurerm_resource_group.example.location
  resource_group_name        = azurerm_resource_group.example.name
  app_service_plan_id        = azurerm_app_service_plan.example.id
  storage_account_name       = azurerm_storage_account.example.name
  storage_account_access_key = azurerm_storage_account.example.primary_access_key
  version = "~3"
  app_settings = {
        FUNCTIONS_WORKER_RUNTIME = "powershell"
        FUNCTIONS_WORKER_RUNTIME_VERSION = "~7"
       
  }
}
```

I know that in a Linux Function App you can set the the Python version using:
```
site_config {
    linux_fx_version = "PYTHON|3.9"
}
```

Is there any update on this issue?

**Comment by petersgiles** [comment] 2021-04-12 07:00
I would like to know how to do this too

**Comment by bodemckenna** [comment] 2021-05-27 10:32
> Hi I am facing the same issue with Terraform. I am trying to create a Powershell Function App in Azure with azurerm_function_app and I want to set Powershell Core Version to 7. The issue is that after terraform apply the Function App is created, but the Powershell Core Version is blank. I was able to set the Python version for a Linux Function App, but not for Powershell.
> 
> ![Screenshot 2021-04-09 at 10 55 24](https://user-images.githubusercontent.com/7003385/114156075-dbc92200-992a-11eb-8f25-889504b31e70.png)
> 
> I tried something like that, but with no success:
> 
> ```
> resource "azurerm_function_app" "example" {
>   name                       = "functionapptest"
>   location                   = azurerm_resource_group.example.location
>   resource_group_name        = azurerm_resource_group.example.name
>   app_service_plan_id        = azurerm_app_service_plan.example.id
>   storage_account_name       = azurerm_storage_account.example.name
>   storage_account_access_key = azurerm_storage_account.example.primary_access_key
>   version = "~3"
>   app_settings = {
>         FUNCTIONS_WORKER_RUNTIME = "powershell"
>         FUNCTIONS_WORKER_RUNTIME_VERSION = "~7"
>        
>   }
> }
> ```
> 
> I know that in a Linux Function App you can set the the Python version using:
> 
> ```
> site_config {
>     linux_fx_version = "PYTHON|3.9"
> }
> ```
> 
> Is there any update on this issue?

I'm seeing the same issue with powershell Core Version.  

app_settings = {
        FUNCTIONS_WORKER_RUNTIME = "powershell"
        FUNCTIONS_WORKER_RUNTIME_VERSION = "~7"
       
  }

Does not work for me.

Terraform v0.15.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.60.0

Any work arounds?

**Comment by mariussm** [comment] 2021-05-27 18:19
Here is my workaround in an Azure DevOps pipeline PowerShell step:

```
    # Change function app to PS 7
    Write-Host '##[group]Change function app to PS 7'
    $function = az functionapp show --name $functionappname --resource-group $rgname | ConvertFrom-Json
    if($function.siteConfig.powerShellVersion -ne "~7") {
        Write-Host "Updating powershell version to ~7..."
        az functionapp update --name $functionappname --resource-group $rgname --set "siteConfig.powerShellVersion=~7"
    } else {
        Write-Host "Powershell version already set to to ~7"
    }
    Write-Host '##[endgroup]'
```

**Comment by sayandaw** [comment] 2021-05-30 08:42
I am also facing the same issue !! Any Update on when this will be fixed?

**Comment by edomaur** [comment] 2021-06-07 06:03
same issue here, would like any update on this :-)

**Comment by gabrielmccoll** [comment] 2021-06-25 18:19
Heya, just to build on the great work by @mariussm  and as an alt take. 

I did this as a work around and it worked okay running in ADO pipeline.
I'm pretty novice at Terraform so there's likely much more robust ways of doing this.


``` terraform
resource "null_resource" "ucf_fa" {
  provisioner "local-exec" {
    command = <<-EOT
      az login --service-principal --username '${var.sp_appid}' -p='${var.sp_appsecret}' --tenant "${var.tenant}"
      echo az functionapp update --name ${azurerm_function_app.ucf_fa.name} --resource-group ${azurerm_function_app.ucf_fa.resource_group_name} --set siteConfig.powerShellVersion=~7
    EOT
  }
  depends_on = [azurerm_function_app.ucf_fa]
  triggers = {
        build_number = "1"
  }
}
````

**Comment by sayandaw** [comment] 2021-06-27 04:13
@gabrielmccoll, Yes .. thank you so much. I am also very new to terraform.
- In my 1st approach i was executing the az cli commands from the pipeline to set the PowerShellVersion.
- Then one of my colleagues recommended that in Terraform we should use a null resource to achieve this, exactly 💯 like you have shown.

Thank you so much ! This workaround is good for me now 😌

**Comment by srjennings** [comment] 2021-09-09 01:47
PowerShell 6 Support is ending September 30, 2022... would be great to have this feature added!

https://azure.microsoft.com/en-us/updates/azure-functions-support-for-powershell-6-is-ending-on-30-september-2022/

**Comment by bryrod** [comment] 2021-09-20 20:01
I'm also running into this issue. Hard to advocate for IaC when there's a need for manual changes via console.

**Comment by honb** [comment] 2021-10-14 09:09
I'm also getting this issue. Have to update it manual in Azure Portal. 
It would be nice if this can be done by terraform script

**Comment by titoluyo** [comment] 2021-12-02 16:59
I got that this works
`site_config {
  linux_fx_version = "PowerShell|7"
}`

**Comment by srjennings** [comment] 2021-12-03 15:23
> I found the workaround: `siteConfig.powerShellVersion=~7` doesn't work for me.
> 
> I got that this works
> 
> ```terraform
> site_config {
>   linux_fx_version = "PowerShell|7"
> }
> ```

This only works with Linux App Service Plans and Linux Function Apps. A solution is still needed for Windows-based apps and plans.

**Comment by leandroscardua** [comment] 2022-04-20 09:19
HI There,

On the new version: 3.2.0, I`m able to deploy the app using the new version for the provider: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_function_app#powershell_core_version

**Comment by leandroscardua** [comment] 2022-04-20 12:10
Hi Team,

Do you have any update on that issue?

**Comment by erwinkramer** [comment] 2022-08-08 14:02
This is supported through the [powershell_core_version](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_function_app#powershell_core_version) `application_stack` element, you have to move to `azurerm_windows_function_app` first.

**Comment by ju-ge** [comment] 2022-08-08 14:53
> This is supported through the [powershell_core_version](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_function_app#powershell_core_version) `application_stack` element, you have to move to `azurerm_windows_function_app` first.

Hello.

Terraform version : 0.14.1
AzureRM version : 3.17.0

Still Ko PowerShell 7 & 7.2 with `azurerm_windows_function_app`

Configuration => General settings :
![image](https://user-images.githubusercontent.com/106167594/183444446-3b6a9fbf-99a3-4980-8245-ff49f2737bce.png)
Template ARM :
![image](https://user-images.githubusercontent.com/106167594/183445463-ef5a3c43-7655-4a6e-a720-a84ea1e39853.png)
![image](https://user-images.githubusercontent.com/106167594/183445725-6dad7128-9637-4a3b-b9a4-b98e23f1ba8d.png)

However, stack PowerShell 7 & 7.2 work well with `azurerm_linux_function_app`

If anyone has a solution to the problem, I'm interested.
Thanks

**Comment by Annesars90** [comment] 2022-08-12 12:20
Same issue, both on azurerm_windows_function_app & the former azurerm_function_app.

**Comment by tjgruber** [comment] 2022-10-20 18:41
I was able to do it successfully by putting the block inside of the `site_config` block, for example:

```
  site_config {
    use_32_bit_worker = false
    ftps_state = "FtpsOnly"
    application_stack {
      powershell_core_version = 7.2
    }
  }
  ```

I confirmed it was in fact using 7.2 by running the following command: `az functionapp config show --name myFunctionAppName --resource-group myResourceGroupName`
and showed the following result:
`"windowsFxVersion": "PowerShell|7.2",`

I re-confirmed by changing the version in the terraform config to `7`, reran the command to show the configuration, and it shown as:
`"windowsFxVersion": "PowerShell|7",`

So it appears to be functioning correctly, even though the `PowerShell Core Version` in the general app settings web page is blank.

**Comment by erwinkramer** [comment] 2022-10-20 18:57
@tjgruber did you confirm that your function app is actually working by calling a function inside your function app?

**Comment by tjgruber** [comment] 2022-10-20 19:10
@erwinkramer I tested a simple PowerShell HTTP Trigger, and it was successful. I also tested creating a Durable Function, and it let me.

**Comment by erwinkramer** [comment] 2022-10-20 19:16
I think Microsoft made Powershell 7 default so it would work now no matter what, maybe confirm the Powershell version inside the function by calling  $PSVersionTable.PSVersion? Then we know for sure sure it's  actually using 7.2 and not falling back to 7

**Comment by tjgruber** [comment] 2022-10-20 22:56
The function itself is actually defaulting to `7.0.12`.

![image](https://user-images.githubusercontent.com/15575143/197040250-97b109d5-9d97-4c1d-9fdc-12bc82177d99.png)

I just did a comparison, of before and after setting it manually in the Web GUI. Everything stays the same, except these changes:

![image](https://user-images.githubusercontent.com/15575143/197040102-245a6a87-4d87-40bc-84f1-5fabb9deca20.png)

So I did yet some more digging through the Terraform documentation and Microsoft App Settings documentation, found the `powerShellVersion` supported there all the way at the bottom, and added those recommended changes to the Terraform config, which it accepts:

```
  app_settings = {
    "powerShellVersion" = "~7",
  }

  site_config {
    remote_debugging_version = "VS2019"
    application_stack {
      powershell_core_version = 7.2
    }
  }
```

I used Microsoft's suggested `"~7"`, along with all other combinations, none of which work. When I output the settings config, it always shows blank `"powerShellVersion": "",`. The only way I've seen to change it so far is manually in the Web GUI.

The Terraform config doesn't accept `"powerShellVersion" = "~7"` anywhere else, as it's an app setting.

I also tried without the `application_stack` and using the following app_settings, with no luck:
```
  app_settings = {
    "FUNCTIONS_WORKER_RUNTIME" = "powershell",
    "FUNCTIONS_WORKER_RUNTIME_VERSION" = "~7",
  }

  app_settings = {
    "WEBSITE_RUN_FROM_PACKAGE" = "",
    "netFrameworkVersion" = "v6.0",
    "powerShellVersion" = "~7",
    "FUNCTIONS_WORKER_RUNTIME_VERSION" = "~7",
  }
```

https://learn.microsoft.com/en-us/azure/azure-functions/functions-app-settings#powershellversion

https://learn.microsoft.com/en-us/azure/azure-functions/functions-app-settings#netframeworkversion

etc... I tried all kinds of combinations from the documentation, and it's not clear anywhere how to specify this in Terraform using the Terraform resource `azurerm_windows_function_app`.

The way the Terraform resource is interacting with the Azure API or however it's doing it, seems to need fixed. If there is a way to set the PowerShell Core Version in the Terraform config, it's certainly not clear.

**Comment by tjgruber** [comment] 2022-10-21 20:01
In addition to the above, I haven't even been successful in changing the PowerShell version from 7 to 7.2 via Azure CLI. It may be a limitation in Azure CLI, therefore the azurerm_windows_function_app resource. It does look possible to upgrade from 7 to 7.2 via Azure PowerShell and ARM templates... but I'd really like to do this with Terraform.

**Comment by ju-ge** [comment] 2023-02-02 13:00
Hello. 
Since azurerm v3.39.0, the problem does not seem to be present anymore. this issue can be closed.

**Closed** 2023-02-07 11:30 UTC
Labels: enhancement, service/functions
