### ISSUE TITLE
Support for [ Enhancement of using the latest API to allow it the existing module to create V2 alert]

### ISSUE THREAD

**Issue by bhanumaddineni** [hashicorp/terraform-provider-azurerm#15610] opened 2022-02-25 14:12 UTC
Hi Team,

we're requesting to do the enhancement of using the latest API to allow it the existing module to create V2 alert.

Regards,
Bhanu Maddineni
bmaddineni@avidxchange.com

**Comment by tombuildsstuff** [comment] 2022-02-25 14:24
Duplicate of #14999

**Closed by tombuildsstuff** 2022-02-25 14:24 UTC
