### ISSUE TITLE
azurerm version > 3.89.0 is breaking For/for_each loop parsing

### ISSUE THREAD

**Issue by BigFrog-coding** [hashicorp/terraform-provider-azurerm#25635] opened 2024-04-16 14:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.6

### AzureRM Provider Version

3.99

### Affected Resource(s)/Data Source(s)

azurerm_pim_eligible_role_assignment

### Terraform Configuration Files

```hcl
resource "azurerm_pim_eligible_role_assignment" "pim_sub_eligible_assignment" {
  for_each = {
    for role in local.roles : "${role.scope}${role.role_definition_id}" => role
  }
  scope              = each.value.scope
  role_definition_id = each.key
  principal_id       = each.value.principal_id

  schedule {
    start_date_time = time_static.static_time.rfc3339
    expiration {
      duration_days = 364
    }
  }

}

example entry of local.roles =
  {
    "principal_id" = "id here"
    "role_definition_id" = "/providers/Microsoft.Authorization/roleDefinitions/b24988ac-6180-42a0-ab88-20f7382dd24c"
    "scope" = "/subscriptions/id here"
  },
```

### Debug Output/Panic Output

```shell
The debug shows too much PII and is irrelevant
```

### Expected Behaviour

The role key should have been created using the scope and role_definition_id in the for loop. TF plans

### Actual Behaviour

│ Error: Duplicate object key
│
│ on pim.tf line 24, in resource "azurerm_pim_eligible_role_assignment" "pim_sub_eligible_assignment":
│ 23: for_each = toset({
│ 24: for role in local.roles : "${role.scope}${role.role_definition_id}" => role
│ 25: })
│ ├────────────────
│ │ role.role_definition_id is "/providers/Microsoft.Authorization/roleDefinitions/b24988ac-6180-42a0-ab88-20f7382dd24c"
│ │ role.scope is ""
│
│ Two different items produced the key "/providers/Microsoft.Authorization/roleDefinitions/b24988ac-6180-42a0-ab88-20f7382dd24c" in this 'for' expression. If duplicates are expected, use the ellipsis (...) after the value expression to enable grouping by key.
╵

scope is empty
This works great in all previous versions of azurerm provider

### Steps to Reproduce

Terraform plan

**Comment by tombuildsstuff** [comment] 2024-04-16 14:42
Duplicate of #24935

**Closed by tombuildsstuff** 2024-04-16 14:42 UTC
Labels: service/authorization, v/3.x
