### ISSUE TITLE
Data source azurerm_shared_image_version is not returning the actual latest version

### ISSUE THREAD

**Issue by melcloud** [hashicorp/terraform-provider-azurerm#13175] opened 2021-08-29 22:55 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
 
- Terraform version: 1.0.5
- Azure provider version: 2.74.0

### Affected Resource(s)

* `data.azurerm_shared_image_version1st

### Terraform Configuration Files

```hcl
data "azurerm_shared_image_version" "latest" {
  name = "latest"
  gallery_name = azurerm_shared_image.example.gallery_name
  image_name = azurerm_shared_image.example.name
  resource_group_name = azurerm_shared_image.example.resource_group_name
}
```

### Debug Output
Since we have more than 20 images, the API return images in batches and a token to get the latest. However, the provider only find the latest in the first batch. This has been fixed in data source `azurerm_shared_image_versions` 

### Expected Behaviour
Return image of the latest

### Actual Behaviour
Return latest image in the first batch

### Steps to Reproduce

1. `terraform apply`

### References

* #8296
* #10374

**Comment by burnedikt** [comment] 2021-11-03 23:10
I've also stumbled upon this and was quite confused since it was calimed to be fixed in by https://github.com/hashicorp/terraform-provider-azurerm/pull/10519 in version 2.47.0. However, I definitely still face the same behaviour and I think this is also the same issue as https://github.com/hashicorp/terraform-provider-azurerm/issues/10581. I also want to add https://github.com/hashicorp/terraform-provider-azurerm/issues/10516 as a reference from the past where this issue was raised initially.

It appears that [the fix back then](https://github.com/hashicorp/terraform-provider-azurerm/commit/c62c3d0fdc0e410beed2cd141f2274751208c63d) was only applied to `azurerm_shared_image_versions` (obtaining a list of all image versions withint a shared image gallery) but not to `azurerm_shared_image_version` (obtaining a single version by name or keyword `latest` / `recent`).

---

As a workaround for now, I use the working `azurem_shared_image_versions` data source to get **all** versions and then use the last version in the list to reproduce the same behaviour as I would get with a working version of `azurem_shared_image_version` and trying to obtain `latest` like:

```terraform
# obtain all versions, the last version in that list will be the "latest" version
data "azurerm_shared_image_versions" "versions" {
  image_name          = "my-shared-image-name"
  gallery_name        = "my-shared-image-gallery-name"
  resource_group_name = "my-resource-group-name"
}

data "azurerm_shared_image_version" "main" {
  name                = reverse(data.azurerm_shared_image_versions.main.images)[0].name
  image_name          = "my-shared-image-name"
  gallery_name        = "my-shared-image-gallery-name"
  resource_group_name = "my-resource-group-name"
}
```

This effectively reproduces the behaviour of `azurerm_shared_image_version` with name as `latest`, see https://github.com/hashicorp/terraform-provider-azurerm/blob/6029f7148d5490b24ee62868656fd14eead560a5/azurerm/internal/services/compute/shared_image_version_data_source.go#L166-L170

**Comment by gek0** [comment] 2021-12-20 10:31
Hello, I'm having issues with this resource since nor the **latest** or **recent** parameters work for the _name_ attribute
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/shared_image_version#name

We are using a standardized versioning policy - MAJOR.MINOR.PATCH for our images
Example: 1.0.1, 1.0.9, 1.0.10 and so on...
When needed we bump the MINOR and MAJOR numbers, but PATCH is incremented for regular builds

**Current situation: we've built the image versioned to 1.0.10 but 1.0.9 is returned due to a sorting issue**

Example golang code that could fix this - take into account "numeric" string for versioning
```
package main

import (
	"fmt"
	"sort"
	"strconv"
)

func main() {
	s := []string{"1.0.1", "1.0.8", "1.0.9", "1.0.10"}
	sort.Strings(s)
	fmt.Printf("Before: %v\n", s)

	s2 := []string{"1.0.1", "1.0.8", "1.0.9", "1.0.10"}
	sort.Slice(s2, func(i, j int) bool {
		numA, _ := strconv.Atoi(s2[i])
		numB, _ := strconv.Atoi(s2[j])
		return numA < numB
	})

	fmt.Printf("After: %v\n", s2)
}
```

and the resulting output -> where Before is what currently the provider returns
```
Before: [1.0.1 1.0.10 1.0.8 1.0.9]
After: [1.0.1 1.0.8 1.0.9 1.0.10]
```

Can somebody take a look at this and fix it upstream if valid?
At least the **recent** parameter should work but not sure if that is checking the timestamp metadata or name? Looks like the functionality is the same and broken

**Comment by favoretti** [comment] 2021-12-22 10:07
Hi and thanks all for reporting this issue. For my understanding - from what I can see in the docs - the version can be anything really, so `Atoi` approach would fail on anything that's not a numeric version. This makes it kinda hard to sort deterministically. Ay ideas are appreciated here.

**Closed** 2021-12-27 16:56 UTC
Labels: bug, service/images
