### ISSUE TITLE
azurerm_private_dns_resolver_inbound_endpoint constantly recreating

### ISSUE THREAD

**Issue by isobeljones** [hashicorp/terraform-provider-azurerm#19393] opened 2022-11-22 14:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

The following new terraform resources are being recreated with each new deploy:
- azurerm_private_dns_resolver
- azurerm_private_dns_resolver_inbound_endpoint

```
  # module.vpn.azurerm_private_dns_resolver.this must be replaced
-/+ resource "azurerm_private_dns_resolver" "this" {
      ~ id                  = "/subscriptions/<sub-id>/resourceGroups/<resource group id>/providers/Microsoft.Network/dnsResolvers/platforms-aks-dev-eun" -> (known after apply)
        name                = "<-name->"
      - tags                = {} -> null
      ~ virtual_network_id  = "/subscriptions/<sub-id>/resourceGroups/<resource group id>/providers/Microsoft.Network/virtualNetworks/<-name->" -> (known after apply) # forces replacement
        # (2 unchanged attributes hidden)
    }

  # module.vpn.azurerm_private_dns_resolver_inbound_endpoint.this must be replaced
-/+ resource "azurerm_private_dns_resolver_inbound_endpoint" "this" {
      ~ id                      = "/subscriptions/<sub-id>/resourceGroups/<resource group id>/providers/Microsoft.Network/dnsResolvers/<resource group id>n/inboundEndpoints/<-name->" -> (known after apply)
        name                    = "platforms-aks-dev-eun"
      ~ private_dns_resolver_id = "/subscriptions/<sub-id>/resourceGroups/<resource group id>/providers/Microsoft.Network/dnsResolvers/<-name->" -> (known after apply) # forces replacement
      - tags                    = {} -> null
        # (1 unchanged attribute hidden)

      ~ ip_configurations {
          ~ private_ip_address           = ""<-private-ip->" -> (known after apply)
            # (2 unchanged attributes hidden)
        }
    }

Plan: 2 to add, 0 to change, 2 to destroy.
```
This is the original code:
```
resource "azurerm_private_dns_resolver" "this" {
  name                = local.resource_prefix
  resource_group_name = local.resource_prefix
  location            = var.location
  virtual_network_id  = data.azurerm_virtual_network.this.id
}

resource "azurerm_private_dns_resolver_inbound_endpoint" "this" {
  name                    = local.resource_prefix
  private_dns_resolver_id = azurerm_private_dns_resolver.this.id
  location                = var.location

  ip_configurations {
    subnet_id = azurerm_subnet.dns_private_resolver.id
  }
}

data "azurerm_virtual_network" "this" {
  name                = local.resource_prefix
  resource_group_name = local.resource_prefix
}
```

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.0

### AzureRM Provider Version

3.32.0

### Affected Resource(s)/Data Source(s)

azurerm_private_dns_resolver azurerm_private_dns_resolver_inbound_endpoint

### Terraform Configuration Files

```hcl
resource "azurerm_private_dns_resolver" "this" {
  name                = local.resource_prefix
  resource_group_name = local.resource_prefix
  location            = var.location
  virtual_network_id  = data.azurerm_virtual_network.this.id
}

resource "azurerm_private_dns_resolver_inbound_endpoint" "this" {
  name                    = local.resource_prefix
  private_dns_resolver_id = azurerm_private_dns_resolver.this.id
  location                = var.location

  ip_configurations {
    subnet_id = azurerm_subnet.dns_private_resolver.id
  }
}

data "azurerm_virtual_network" "this" {
  name                = local.resource_prefix
  resource_group_name = local.resource_prefix
}


### Expected Behaviour

When a new terraform plan is run no new changes should be identified. 

### Actual Behaviour

Resources are getting recreated with each new run

### Steps to Reproduce

terraform plan

### Important Factoids

_No response_

### References

_No response_

**Comment by wuxu92** [comment] 2022-11-24 09:13
Hi @isobeljones thanks for your feedback, I have tried locally with your configuration, and the apply success, I wonder if there is any special configuration in your `azurerm_virtual_network` resource. so could you please share some more configurations about that azurerm_virtual_network resource?

**Comment by isobeljones** [comment] 2022-11-29 12:44
Hi @wuxu92, I also get success, it's the second time I have issues. It recreates the resources

**Comment by wuxu92** [comment] 2022-12-05 06:17
@isobeljones I cannot reproduce the recreation behavior by your configuration. according to your output

```
-/+ resource "azurerm_private_dns_resolver" "this" {
      ~ id                  = "/subscriptions/<sub-id>/resourceGroups/<resource group id>/providers/Microsoft.Network/dnsResolvers/platforms-aks-dev-eun" -> (known after apply)
        name                = "<-name->"
      - tags                = {} -> null
      ~ virtual_network_id  = "/subscriptions/<sub-id>/resourceGroups/<resource group id>/providers/Microsoft.Network/virtualNetworks/<-name->" -> (known after apply) # forces replacement
        # (2 unchanged attributes hidden)
    }
```
it looks like the tags property is set to `{}` instead of null. so have you set the tags property of `azurerm_private_dns_resolver` and `azurerm_private_dns_resolver_inbound_endpoint`?

**Comment by rcskosir** [comment] 2023-10-30 22:09
Thanks for taking the time to submit this issue. @wuxu92  was unable to reproduce this behavior. We’re going to close this issue for now, but if you run into this again with the latest Terraform and Provider versions, please feel free to [open a new issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/new/choose) with additional information regarding the tags property.

**Closed by rcskosir** 2023-10-30 22:09 UTC
Labels: waiting-response, service/private-dns-resolver, v/3.x
