### ISSUE TITLE
azurerm_automation_dsc_configuration : Error occurred unmarshalling JSON

### ISSUE THREAD

**Issue by mivica** [hashicorp/terraform-provider-azurerm#15404] opened 2022-02-14 09:33 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.1.5
azurerm v2.96.0

### Affected Resource(s)

* `azurerm_automation_dsc_configuration `

### Terraform Configuration Files

```hcl
resource "azurerm_automation_dsc_configuration" "dsc_configuration_servicefabric" {
  name                    = local.configuration_name_servicefabric
  resource_group_name     = local.resource_group_name
  automation_account_name = local.automation_account_name
  location                = local.location
  content_embedded        = data.local_file.configuration_file_servicefabric.content
 }
```
### Expected Behaviour

Terraform generates a plan for azurerm_automation_dsc_configuration resource.

### Actual Behaviour

Terraform throws the following error: 

Error: making Read request on AzureRM Automation Dsc Configuration content "ServiceFabricNode":automation.DscConfigurationClient#GetContent: Failure responding to request: StatusCode=200 -- Original Error: Error occurred unmarshalling JSON - Error = 'invalid character 'C' looking for beginning of value' JSON = 'Configuration "ServiceFabricNode" <% VALID DSC CONFIGURATION %>'

### Steps to Reproduce

1. `terraform plan`

### Important Notes

- observed since azurerm v2.96.0
-- observed on all our azurerm_automation_dsc_configuration  resources
-- our DSC files are valid
- azurerm v2.95.0 works fine

### References

* #0000

**Comment by tombuildsstuff** [comment] 2022-02-16 14:45
Duplicate of https://github.com/hashicorp/terraform-provider-azurerm/issues/10858

**Closed by tombuildsstuff** 2022-02-16 14:45 UTC
Labels: bug, duplicate, upstream-microsoft

**Comment by mivica** [comment] 2022-02-16 15:14
@tombuildsstuff , are we sure this is a duplicate of [#10858](https://github.com/hashicorp/terraform-provider-azurerm/issues/10858)? They do not look the same, the other one is an almost a year old bug whilst this is a provider version specific issue.

**Comment by tombuildsstuff** [comment] 2022-02-16 15:15
@mivica yep, it's related to the base layer

**Comment by mivica** [comment] 2022-02-16 15:17
@tombuildsstuff, do we know when it will get fixed?

**Comment by mivica** [comment] 2022-02-17 09:54
> @mivica yep, it's related to the base layer

@tombuildsstuff, can you please shed more light on how does it work in v2.95.0 and not in v2.96.0?

**Comment by Va55ago** [comment] 2022-02-17 10:11
I agree with @mivica. The fact that this works today in 2.95 and not 2.96 shows that this is something that changed recently.

Now, it could be that #10858 is causing the underlying error to not be "bubbled up" correctly. However, this issue is referring to the underlying problem with the automation account... not the problem with the bubbling up of that error.

**Comment by tombuildsstuff** [comment] 2022-02-17 10:37
@Va55ago which needs to be fixed in the base layer, as this isn't being deserialized correctly - #10858 is tracking fixing the base layer which includes, but isn't limited to bubbling up errors.
