### ISSUE TITLE
azurerm_automation_job_schedule re-creating all schedule links if adding a new one

### ISSUE THREAD

**Issue by ricohomewood** [hashicorp/terraform-provider-azurerm#6466] opened 2020-04-14 16:02 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform 0.12.20

- provider.azurerm v2.2.0

### Affected Resource(s)

* `azurerm_automation_job_schedule`

### Terraform Configuration Files

```hcl
resource "azurerm_automation_schedule" "cleanup-recycle" {
  name                = "cleanup-recycle-schedule"
  description         = "Schedule for running recycle cleanup RunBook daily"
  resource_group_name = local.rg_name
  automation_account_name = azurerm_automation_account.coreautomation.name
  frequency               = "Day"
  interval                = 1
  lifecycle {
    ignore_changes = [start_time, week_days]
  }
}

resource "azurerm_automation_job_schedule" "cleanup-recycle-schedule-link" {
  resource_group_name         = local.rg_name
  automation_account_name = azurerm_automation_account.coreautomation.name
  schedule_name                    = azurerm_automation_schedule.cleanup-recycle.name
  runbook_name                     = "cleanup-recycled-files"

  parameters = {
    environment = var.environment
    pod         = (var.pod_name == "UNDEFINED_POD" ? "pod1" : var.pod_name)
  }
}
```

The above will create a new AA schedule and schedule link fine, however, if you create a new job schedule and schedule link, say like below, terraform wants to re-create the above old scheduled link even though nothing has changed with this one, we are creating a new one.

### Expected Behavior
Adding a new schedule and schedule link should result in just creating those resources ...

```hcl
resource "azurerm_automation_schedule" "stop_np_iaas_schedule" {
  name                        = "stop-np-iaas-schedule"
  description                = "Schedule for shutting down non-prod daily"
  resource_group_name = local.rg_name
  automation_account_name = azurerm_automation_account.coreautomation.name
  frequency               = "Week"
  interval                = 1
  start_time              = "2020-04-01T19:00:00Z"
  week_days               = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
}

resource "azurerm_automation_job_schedule" "stop_np_iaas_schedule_link" {
  resource_group_name         = local.rg_name
  automation_account_name = azurerm_automation_account.coreautomation.name
  schedule_name                   = azurerm_automation_schedule.stop_np_iaas_schedule.name
  runbook_name                    = "Stop-AzureNonProdIaaS"

  run_on = (var.pod_name == "UNDEFINED_POD" ?
    "pod1-${var.environment}-hybridgroup" :
    "${var.pod_name}-${var.environment}-hybridgroup"
  )
}

Terraform plan / apply:

+ resource "azurerm_automation_schedule" "stop_np_iaas_schedule" {
      + automation_account_name = "some-automation-account"
      + description             = "Stop nonprod Iaas"
      + expiry_time             = (known after apply)
      + frequency               = "Day"
      + id                      = (known after apply)
      + interval                = 1
      + name                    = "stop-np-iaas-schedule"
      + resource_group_name     = "rg"
      + start_time              = (known after apply)
      + timezone                = "UTC"
    }

 + resource "azurerm_automation_job_schedule" "stop_np_iaas_schedule_link" {
      + automation_account_name   = "some-automation-account"
      + id                                = (known after apply)
      + job_schedule_id         = (known after apply)
      + parameters              = {
          + "environment" = "env"
          + "pod"         = "pod1"
        }
      + resource_group_name     = "rg"
      + run_on                         = "hybridgroup"
      + runbook_name            = "some_runbook"
      + schedule_name           = "stop-np-iaas-schedule"
    }


```

### Actual Behavior

terraform then shows the previous scheduled link to be re-created as if it is not recognized in the TF state:

```hcl
Terraform plan / apply:

 + resource "azurerm_automation_job_schedule" "cleanup-recycle-schedule-link" {
      + automation_account_name = "some-automation-account"
      + id                      = (known after apply)
      + job_schedule_id         = (known after apply)
      + parameters              = {
          + "environment" = "np"
          + "pod"         = "pod1"
        }
      + resource_group_name     = "rg"
      + runbook_name            = "cleanup-recycled-files"
      + schedule_name           = "cleanup-recycle-schedule"
    }

+ resource "azurerm_automation_schedule" "stop_np_iaas_schedule" {
      + automation_account_name = "some-automation-account"
      + description             = "Stop nonprod Iaas"
      + expiry_time             = (known after apply)
      + frequency               = "Day"
      + id                      = (known after apply)
      + interval                = 1
      + name                    = "stop-np-iaas-schedule"
      + resource_group_name     = "rg"
      + start_time              = (known after apply)
      + timezone                = "UTC"
    }

 + resource "azurerm_automation_job_schedule" "stop_np_iaas_schedule_link" {
      + automation_account_name   = "some-automation-account"
      + id                                = (known after apply)
      + job_schedule_id         = (known after apply)
      + parameters              = {
          + "environment" = "env"
          + "pod"         = "pod1"
        }
      + resource_group_name     = "rg"
      + run_on                         = "hybridgroup"
      + runbook_name            = "some_runbook"
      + schedule_name           = "stop-np-iaas-schedule"
    }
```

### Steps to Reproduce

1. Create initial TF Shedule and Schedule link
2. terraform apply
3. Create another Schedule and Schedule link
4. terraform apply - this will try to re-create the previous schedule link too and fail as it already exists in Azure Automation with the below error:

`Error: automation.JobScheduleClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="A job schedule for the specified runbook and schedule already exists."`

* #0000

**Comment by njuCZ** [comment] 2020-05-08 09:29
@ricohomewood I am sorry I could not reproduce this problem. Could you please give more details about this issue. such as the runbook, is it mansged by terrraform or other ways?

**Comment by ricohomewood** [comment] 2020-05-11 07:40
Hi @njuCZ 

So the runbooks are NOT managed by terraform, these are synced to Azure Automation account as they are managed in Azure Devops / Source control and we sync to azure automation that way.

However the schedules and the links to those schedules are managed by Terraform, including all other aspects of AA.

I don't have a huge amount of time this week but I can look to set up a test rig reproduce this asap if still not able to produce it based on the above.

**Comment by njuCZ** [comment] 2020-09-29 06:16
@ricohomewood since the relevant issue has been fixed, could you please have a try using the latest azurerm. If there is no such problem, we would close this issue.

**Comment by favoretti** [comment] 2021-08-19 11:26
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.

**Closed by favoretti** 2021-08-19 11:26 UTC
Labels: bug, service/automation
