### ISSUE TITLE
Support for enable-artifact-streaming on ACR

### ISSUE THREAD

**Issue by jonathan-fileread** [hashicorp/terraform-provider-azurerm#24285] opened 2023-12-19 22:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

ACR and AKS released a new functionality last month to allow `-enable-artifact-streaming` which improves pull times of images on AKS significantly.

We would like this functionality for AKS nodepools and ACR.

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster_node_pool

### Potential Terraform Configuration

```hcl
Sample default_node_pool configuration in resource AKS

  default_node_pool {
    name           = "system"
    temporary_name_for_rotation = "systembkup"
    **enable_artifact_streaming = true**
    vm_size        = "Standard_d8as_v5"
    only_critical_addons_enabled = true
    vnet_subnet_id = azurerm_subnet.application_primary.id
    enable_auto_scaling = true
    min_count = local.aks_default_pool_min_count
    max_count = local.aks_default_pool_max_count
    zones = [1, 2, 3]
  }
  
  For ACR - I am not sure how to go about doing this, as ACR artifact streaming is per image repository path.
```

### References

https://learn.microsoft.com/en-us/azure/aks/artifact-streaming

**Comment by stephybun** [comment] 2024-06-13 13:33
Duplicate of #23961 please subscribe to #23961 for updates.

**Closed by stephybun** 2024-06-13 13:33 UTC
Labels: enhancement, upstream/microsoft, service/kubernetes-cluster, preview, blocked
