### ISSUE TITLE
Support for Azure Front Door Standard/Premium SKU

### ISSUE THREAD

**Issue by LWNetworks** [hashicorp/terraform-provider-azurerm#16344] opened 2022-04-12 10:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The new Azure Front Door Standard/Premium solution reached GA at the end of March 2022.
https://azure.microsoft.com/en-gb/updates/generally-available-the-new-azure-front-door-a-modern-cloud-cdn-service/

This offers a range of new functionality that the 'Classic' version does not. 

Is it possible to get modules to support deployment and management of Front Door Standard and Premium SKU's via Terraform?

I can see this is linked in https://github.com/hashicorp/terraform-provider-azurerm/pull/15140 and https://github.com/hashicorp/terraform-provider-azurerm/issues/11983 but no current eta of arrival / similar.

Thanks 

### New or Affected Resource(s)/Data Source(s)

azurerm_cdn_frontdoor_*

### References

https://azure.microsoft.com/en-gb/updates/generally-available-the-new-azure-front-door-a-modern-cloud-cdn-service/

**Comment by Marcus-James-Adams** [comment] 2022-04-21 20:08
Duplicate of #13836

**Comment by tombuildsstuff** [comment] 2022-06-03 12:06
Initial support for this (Profiles/Endpoints) shipped in v3.9.0 - the remaining resources will be split out of #16671 then split/refactored as appropriate - however since the initial resources for this have shipped, I'm going to close this issue for the moment.

**Closed by tombuildsstuff** 2022-06-03 12:06 UTC
