### ISSUE TITLE
azurerm_function_app is not idempotent

### ISSUE THREAD

**Issue by bminisi** [hashicorp/terraform-provider-azurerm#3826] opened 2019-07-11 01:19 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

azurerm_function_app

### Terraform Configuration Files

resource "azurerm_function_app" "funcapp" {
  name                      = var.func_app_name
  location                  = var.location
  resource_group_name       = data.azurerm_resource_group.funcapp.name
  app_service_plan_id       = azurerm_app_service_plan.funcapp.id
  storage_connection_string = azurerm_storage_account.funcapp.primary_connection_string
  version                   = var.suffixes["func_app_runtime_version"]
}

### Debug Output

https://gist.github.com/bminisi/01a09b3d1a287800c68ecbb04a971498

### Expected Behavior

When I run the terraform configuration after the first time, it should maintain idempotency.  Most other Terraform resources are idempotent as can be seen in the log file above.

### Actual Behavior

It sees it as a new resource every time and tries to recreate it.  The error states the name of the function app must be globally unique.  It does not know that it created it and the configuration matches what it previously created.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by lucaghersi** [comment] 2019-07-24 07:59
Hi, I have the same issue here. I also tried with a 

```
 lifecycle {
    ignore_changes = all
 }
```
but he has not effect.

**Comment by midacts** [comment] 2019-08-19 18:25
I am running into this as well.

**Comment by hellicott** [comment] 2020-01-03 08:41
Anyone have any updates on this? It's still causing my pipelines to fail unless I manually go and delete the resource first

**Comment by nzthiago** [comment] 2020-01-09 20:52
Seems a duplicate of this: https://github.com/terraform-providers/terraform-provider-azurerm/issues/4939
There's a comment there pointing towards importing the existing functionapp first into Statefile before subsequent template runs...

**Comment by brandonh-msft** [comment] 2020-01-14 22:49
I think I have some more info on this.

I just did a `tf apply` on a brand-new plan for an Azure Function. When the apply ran, it created all the right resources in Azure just fine - this was a completely new RG + Function resources - including an Azure Function name `bh-msft-test` and Plan named `bh-msft-test-plan`. Yet when I look in to the `terraform.tfstate` file now in my local folder, I see this:

```json
            "maximum_elastic_worker_count": 1,
            "maximum_number_of_workers": 0,
            "name": "azure-functions-test-service-plan",
            "per_site_scaling": false,
```

note the **name** shown here. It's not what was in my tf file, nor what was actually created in Azure so of course it will never find that out there and will continue to think it needs to re-deploy the resource.

**Comment by brandonh-msft** [comment] 2020-01-23 16:58
FWIW I'm not seeing this problem at https://github.com/brandonh-msft/azure-functions-terraform when I try to deploy an azure function twice w/ same app name, or even change app settings in the tf file and re-deploy. Am I missing something in my attempt to repro, @bminisi ?

**Comment by bminisi** [comment] 2020-01-26 23:31
@brandonh-msft , It happens when you delete the state file.  Losing the state file or it getting corrupted can happen requires the resource to be deleted in Azure before it can run successfully again.

**Comment by brandonh-msft** [comment] 2020-01-27 16:03
> @brandonh-msft , It happens when you delete the state file. Losing the state file or it getting corrupted can happen requires the resource to be deleted in Azure before it can run successfully again.

Can we add that to 'Steps to Reproduce'?

**Comment by brandonh-msft** [comment] 2020-01-27 16:34
I'll just add that I confirmed these steps. If i `tf apply` an Azure Function plan and it creates RG, App Service Plan, Storage Account, and Function App then I `rm terraform.tfstate` and re-run `tf apply` I end up with this:

~~~
azurerm_resource_group.rg: Creating...
azurerm_resource_group.rg: Creation complete after 1s [id=/subscriptions/.../resourceGroups/...]
azurerm_app_service_plan.sp: Creating...
azurerm_storage_account.sa: Creating...
azurerm_app_service_plan.sp: Creation complete after 5s [id=/subscriptions/.../resourceGroups/.../providers/Microsoft.Web/serverfarms/...-Plan]
azurerm_storage_account.sa: Creation complete after 8s [id=/subscriptions/.../resourceGroups/.../providers/Microsoft.Storage/storageAccounts/...]
azurerm_function_app.fa: Creating...

Error: The name "..." used for the Function App needs to be globally unique and isn't available: Hostname '...' already exists. Please select a different name.

  on main.tf line 26, in resource "azurerm_function_app" "fa":
  26: resource "azurerm_function_app" "fa" {
~~~

**Comment by brandonh-msft** [comment] 2020-01-27 17:27
I'd venture a guess you'll have the same issue with Azure Web Apps as they use the same resource provider path (e.g. `/subscriptions/[sub]/resourceGroups/[rg]/providers/Microsoft.Web/sites/[name]`)

**Comment by bminisi** [comment] 2020-01-27 19:39
Yes, anything that has a public url or endpoint I imagine.

**Comment by favoretti** [comment] 2021-08-18 15:45
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.

**Closed by favoretti** 2021-08-18 15:45 UTC
Labels: bug, service/functions
