### ISSUE TITLE
destroy azurerm_sql_failover_group doesn't remove replica db

### ISSUE THREAD

**Issue by erniebilling** [hashicorp/terraform-provider-azurerm#7938] opened 2020-07-29 00:38 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform 0.12.29
AzureRM provider 2.20.0

### Affected Resource(s)

* `azurerm_sql_failover_group`

### Terraform Configuration Files

```hcl
variable primary_server_name { type = string }
variable secondary_server_name { type = string }
variable resource_group { type = string }


provider "azurerm" {
  version = "~> 2.20.0"  
  features {}

}

data "azurerm_sql_server" "primary_sql_db_server" {
  name                         = var.primary_server_name
  resource_group_name          = var.resource_group
}

data "azurerm_sql_server" "secondary_sql_db_server" {
  name                         = var.secondary_server_name
  resource_group_name          = var.resource_group
}


resource "azurerm_sql_database" "azure_sql_db_primary" {
  name                = "test-db"
  resource_group_name = var.resource_group
  location            = data.azurerm_sql_server.primary_sql_db_server.location
  server_name         = data.azurerm_sql_server.primary_sql_db_server.name
  requested_service_objective_name = "GP_Gen5_2"
  max_size_bytes      = 10 * 1024 * 1024 * 1024
}

resource "azurerm_sql_failover_group" "failover_group" {
  name                = "a-test-failover-group"
  resource_group_name = var.resource_group
  server_name         = data.azurerm_sql_server.primary_sql_db_server.name
  databases           = [azurerm_sql_database.azure_sql_db_primary.id]
  partner_servers {
    id = data.azurerm_sql_server.secondary_sql_db_server.id
  }

  read_write_endpoint_failover_policy {
    mode          = "Automatic"
    grace_minutes = 5
  }
}
```

### Expected Behavior

`terraform apply` successfully creates the database and failover group. A replica database gets created on the secondary server.

`terraform destroy` tears down the failover group and the removes the database from the primary server and the secondary server.

Expect the the state of the secondary server to match its state before `terraform apply` - that is, the replica database should be removed.

### Actual Behavior

`test-db` still exists on the secondary server

### Steps to Reproduce

- Create a primary and secondary SQL servers (via tarraform or other means)
- Use server names and resource group as inputs for this terraform file and `terraform apply`
- `terraform destroy` and see that `test-db` still exists on the secondary server.

### References

* #0000

**Comment by yupwei68** [comment] 2020-07-29 06:05
Hi @erniebilling , thanks for opening this issue. Failover group is by design to achieve high availability and prevent failovers of a group of databases. Sometimes the actions of failover group are more complicated than creating replications in the slave databases because the failover could reverse the primary and secondary databases. Thus it could not revert all its actions, which means by design, it'll not delete the replications while deleting the failover group. 
Besides, I'd like to suggest to open a new sql server to manage all the backups by failover group. Thus, you could delete the sql server to delete all these backups.

**Comment by erniebilling** [comment] 2020-07-30 23:29
Thanks @yupwei68. 

In the nominal case, where no fail over has occurred, it seems reasonable that the two servers should be taken back to their original state following `terraform destroy`. 

`terraform destroy` fails with a proper error message if the fail over group has swapped primary and secondary, so it doesn't seem to dangerous to delete the db from the secondary server if the fail over group is in the *original* state. 

Maybe even an parameter that the caller can set to attempt to delete the secondary db?

**Comment by yupwei68** [comment] 2020-07-31 01:48
Hi @erniebilling , currently this is not supported from the service team. I'd like to suggest open an issue here https://github.com/Azure/azure-rest-api-specs/issues to suggest this feature to the service team.

**Comment by erniebilling** [comment] 2020-08-03 21:51
@yupwei68 Another update to this saga - seems updating settings on the primary database don't get replicated. We're testing the situation where we update `requested_service_objective_name` to increase the size of the instance and when `terraform apply` is run, the primary database is updated but the secondary is not. Something we should take up with the service team as well?

**Comment by yupwei68** [comment] 2020-08-05 03:10
Hi @erniebilling Sure, you could raise another issue for that.

**Comment by favoretti** [comment] 2021-08-25 09:37
Hi @erniebilling, thank you for reporting this issue. As far as I can see from the answers of product team, this is "by design", so since we can not do anything at the moment and it's blocked upstream I'm going to close this issue. You're welcome to raise this with your MSFT representatives and if this is going to change - reopen this issue or open a new one.

**Closed by favoretti** 2021-08-25 09:37 UTC
Labels: service/mssql, upstream-microsoft
