### ISSUE TITLE
terraform import azurerm_lb_backend_address_pool_address command does not seem to work

### ISSUE THREAD

**Issue by ghost** [hashicorp/terraform-provider-azurerm#16997] opened 2022-05-28 09:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

3.8.0

### AzureRM Provider Version

latest

### Affected Resource(s)/Data Source(s)

terraform import azurerm_lb_backend_address_pool_address

### Terraform Configuration Files

```hcl
provider.tf

# Terraform Block
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "3.8.0"
    }
  }
}

# Provider Block
provider "azurerm" {
  features {}
  subscription_id = "f6d3605b-13da-4ebf-b5b4-a6e7757393ec"
}

Main.tf

resource "azurerm_lb_backend_address_pool_address" "yfhjkjl" {

}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

backend target imported upon running the below command:

terraform import azurerm_lb_backend_address_pool_address.yfhjkjl /subscriptions/f6d3605b-13da-4ebf-b5b4-a6e7757393ec/resourceGroups/uthgiokjnkhbt/providers/Microsoft.Network/loadBalancers/ijfpiboitr/backendAddressPools/yfhjkjl/addresses/ipconfig1

### Actual Behaviour

Error out with the following:

PS C:\Users\Faozio\Documents\public LB\Test_LB_import> terraform import azurerm_lb_backend_address_pool_address.yfhjkjl /subscriptions/f6d3605b-13da-4ebf-b5b4-a6e7757393ec/resourceGroups/uthgiokjnkhbt/providers/Microsoft.Network/loadBalancers/ijfpiboitr/backendAddressPools/yfhjkjl/addresses/ipconfig1
azurerm_lb_backend_address_pool_address.yfhjkjl: Importing from ID "/subscriptions/f6d3605b-13da-4ebf-b5b4-a6e7757393ec/resourceGroups/uthgiokjnkhbt/providers/Microsoft.Network/loadBalancers/ijfpiboitr/backendAddressPools/yfhjkjl/addresses/ipconfig1"...
azurerm_lb_backend_address_pool_address.yfhjkjl: Import prepared!
  Prepared azurerm_lb_backend_address_pool_address for import
azurerm_lb_backend_address_pool_address.yfhjkjl: Refreshing state... [id=/subscriptions/f6d3605b-13da-4ebf-b5b4-a6e7757393ec/resourceGroups/uthgiokjnkhbt/providers/Microsoft.Network/loadBalancers/ijfpiboitr/backendAddressPools/yfhjkjl/addresses/ipconfig1]
╷
│ Error: Cannot import non-existent remote object
│
│ While attempting to import an existing object to "azurerm_lb_backend_address_pool_address.yfhjkjl", the provider detected that no object exists with the given id. Only   
│ pre-existing objects can be imported; check that the id is correct and that it is associated with the provider's configured region or endpoint, or use "terraform apply"  
│ to create a new remote object for this resource.
╵

### Steps to Reproduce

Deploy a freshly created LB on portal
Add a backend target (a VM NIC)
try using the import cmd to import the backend target address

### Important Factoids

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/lb_backend_address_pool_address

**Comment by xiaxyi** [comment] 2022-05-31 01:50
@Faozio I can use the terraform import without any issue:
![image](https://user-images.githubusercontent.com/92154856/171076850-2833e822-f3c0-483a-8523-0aa1464e0472.png)
Can you firstly confirm the existence of the backend address pool address id:/subscriptions/f6d3605b-13da-4ebf-b5b4-a6e7757393ec/resourceGroups/uthgiokjnkhbt/providers/Microsoft.Network/loadBalancers/ijfpiboitr/backendAddressPools/yfhjkjl/addresses/ipconfig1 in azure portal or using rest api

**Comment by rcskosir** [comment] 2023-06-08 18:50
The original user is no longer reachable on GitHub (deleted account) and @xiaxyi was unable to reproduce the issue. For that reason I am going to close this issue as unreproducible, since we are not able to get additional information from the user.

**Closed by rcskosir** 2023-06-08 18:50 UTC
