### ISSUE TITLE
Error parsing VMID for disk attachment when disk is attached to Scale Set VM

### ISSUE THREAD

**Issue by alexodle** [hashicorp/terraform-provider-azurerm#5736] opened 2020-02-13 18:52 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
$ terraform -v
 Terraform v0.12.19
+ provider.azuread v0.7.0
+ provider.azurerm v1.43.0
+ provider.null v2.1.2
+ provider.random v2.2.1
```

### Affected Resource(s)

* `azurerm_managed_disk`

### Terraform Configuration Files

```hcl
resource "azurerm_managed_disk" "disks" {
  name                 = "mydisk"
  resource_group_name  = var.resource_group_name
  location             = var.location
  storage_account_type = "Premium_LRS"
  create_option        = "Empty"
  disk_size_gb         = "200"

  zones = ["1"]

  tags = {
    ...
  }
}
```

### Expected Behavior

Azure terraform provider should not error out if I manually attach a disk to a scaleset VM instance. 

### Actual Behavior

Azure terraform provider fails with the following error:

```
Error: Error parsing VMID "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/my-resource-group/providers/Microsoft.Compute/virtualMachineScaleSets/myScaleSet/virtualMachines/myScaleSet_0" for disk attachment: ID contained more segments than required: "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/my-resource-group/providers/Microsoft.Compute/virtualMachineScaleSets/myScaleSet/virtualMachines/myScaleSet_0"

  on cluster/etcd.tf line 1, in resource "azurerm_managed_disk" "disks":
   1: resource "azurerm_managed_disk" "disks" {
```

Problem is that the `arm_managed_disk` resource expects a virtual machine ID, and doesn't allow scaleset virtual machine IDs:

https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/compute/resource_arm_managed_disk.go#L381

### Steps to Reproduce

1. Have terraform create an `azurerm_managed_disk` for you (plan/apply). Should succeed.
2. Via API or AZ cli, attach the disk to a running scaleset VM ([see Azure docs](https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-attached-disks#adding-pre-populated-data-disks-to-an-existing-scale-set))
3. Change something in your terraform (even if unrelated to the managed disk), and apply the changes

### References

* https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/compute/resource_arm_managed_disk.go#L381
* Attaching a disk to a scaleset VM: https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-attached-disks#adding-pre-populated-data-disks-to-an-existing-scale-set

**Comment by mjiderhamn** [comment] 2021-01-08 17:04
Still seeing this with `azurerm` 2.9.0

**Comment by brijchavda** [comment] 2021-02-15 18:47
Any idea, if this is going to be fixed. Blocked because of this issue.

**Comment by brijchavda** [comment] 2021-03-11 23:26
Is there any workaround of this issue?

**Comment by mindrunner** [comment] 2021-07-27 14:08
I am trying to resize a disk in-place with terraform which is currently in use (attached to a scaleset vm). Running into exactly this issue. Unsure if I am supposed to be able to resize like that, though.

**Comment by tombuildsstuff** [comment] 2021-12-10 22:50
hi @alexodle 

Thanks for opening this issue - apologies for the delayed response here.

This resource is intended to be used with a Virtual Machine rather than a VM within a VMSS - as such this is unfortunately working as intended at this time - and as such I'm going to close this issue for the moment.

Thanks!

**Closed by tombuildsstuff** 2021-12-10 22:50 UTC
Labels: question, service/vmss
