### ISSUE TITLE
Host Pool Registration Token : produced an invalid new value for .settings: inconsistent values for sensitive attribute

### ISSUE THREAD

**Issue by akrytus** [hashicorp/terraform-provider-azurerm#11663] opened 2021-05-11 16:25 UTC
When creating a WVD Host Pool with the registration_info block I am unable to reference the registration_info.token value when trying to join a vm to the Host Pool.  The first deployment worked, but fails each run thereafter.

I am using the DSC extension on the vm to join the host pool and reference the token to do so.

**Host Pool Code:** 
`resource "azurerm_virtual_desktop_host_pool" "wvd_pool"{ `
`  registration_info {`
`    expiration_date = "${formatdate("YYYY-MM-DD", timeadd(timestamp(), "24h"))}T00:00:00Z"`
`  }`

**DSC Extension:**
`resource "azurerm_virtual_machine_extension" "dsc" {`
`  settings = <<SETTINGS`
`    {`
`      "modulesUrl": "https://wvdportalstorageblob.blob.core.windows.net/galleryartifacts/Configuration.zip",`
`      "configurationFunction": "Configuration.ps1\\AddSessionHost",`
`      "properties": {`
`        "hostPoolName": "wvd_pool",`
`        "registrationInfoToken": "${azurerm_virtual_desktop_host_pool.wvd_pool.registration_info[0].token}"`
`      }`
`    }`
`  SETTINGS`

**Error:**
Error: Provider produced inconsistent final plan
│ When expanding the plan for azurerm_virtual_machine_extension.ext_dsc_wvdhost[0] to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/azurerm" produced an invalid new value for       
│ .settings: inconsistent values for sensitive attribute.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

**Comment by tombuildsstuff** [comment] 2021-11-15 13:57
hi @akrytus 

Thanks for opening this issue.

Taking a look through this appears to be a duplicate of #13793 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #13793 for updates?

Thanks!

**Closed by tombuildsstuff** 2021-11-15 13:57 UTC
Labels: bug, service/virtual-desktops
