### ISSUE TITLE
Error creating/updating App Service VNet association between

### ISSUE THREAD

**Issue by JerryWang20** [hashicorp/terraform-provider-azurerm#12134] opened 2021-06-09 07:26 UTC
Error creating/updating App Service VNet association between "###" (Resource Group "###") and Virtual Network "VNET-NC-CNE-APP-01": web.AppsClient#CreateOrUpdateSwiftVirtualNetworkConnection: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="LinkedAuthorizationFailed" Message="The client '###' with object id '###' has permission to perform action 'Microsoft.Web/sites/networkConfig/write' on scope '/subscriptions/###/resourceGroups/###/providers/Microsoft.Web/sites/###/networkConfig/virtualNetwork'; however, it does not have permission to perform action 'write' on the linked scope(s) '/subscriptions/###/resourceGroups/###/providers/Microsoft.Network/virtualNetworks/###/subnets/###' or the linked scope(s) are invalid."

**Comment by aristosvo** [comment] 2021-06-11 14:46
Hi @JerryWang20!

This seems a permissions issue, I'm not sure how to help you here. `Network Contributor` permissions on the resource group for your VNet may fix this.

**Comment by bubbletroubles** [comment] 2022-05-14 21:04
Same issue as in #15213

**Comment by tombuildsstuff** [comment] 2022-05-19 06:14
Duplicate of #15213

**Closed by tombuildsstuff** 2022-05-19 06:14 UTC
Labels: question, service/app-service
