### ISSUE TITLE
Azure Monitor agent for Linux not installing with User-assigned managed identity terraform but Windows works fine

### ISSUE THREAD

**Issue by sambhavpandey** [hashicorp/terraform-provider-azurerm#19803] opened 2022-12-29 02:28 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Azure Monitor agent for Linux not installing with User-assigned managed identity terraform 

Same works for Windows perfectly fine.

Also, same works if I remove the user assigned managed identity part and go with system assigned managed identity

### Terraform Version

1.1.0

### AzureRM Provider Version

3.35

### Affected Resource(s)/Data Source(s)

azurerm_XXXXX

### Terraform Configuration Files

```hcl
# Add logging and monitoring extensions. This extension is needed for other extensions
resource "azurerm_virtual_machine_extension" "azure-monitor-agent" {

  for_each = {
    "AzureMonitorWindowsAgent" = {id = "${azurerm_windows_virtual_machine.myWindowsVm1.id}", version = "1.10"}
    "AzureMonitorLinuxAgent" = {id = "${azurerm_linux_virtual_machine.myLinuxVm1.id}", version = "1.24"}
  }
  
  name                  = each.key
  virtual_machine_id    = each.value.id
  publisher             = "Microsoft.Azure.Monitor"
  type                  = each.key
  type_handler_version  =  each.value.version
  automatic_upgrade_enabled  = true
  auto_upgrade_minor_version = true
  
  settings = jsonencode({
    workspaceId               = azurerm_log_analytics_workspace.law.id
    azureResourceId           = each.value.id
    stopOnMultipleConnections = false

    authentication = {
      managedIdentity = {
        identifier-name  = "mi_res_id"
        identifier-value = azurerm_user_assigned_identity.myUserassignedIdentiy.id
      }
    }

  })
  protected_settings = jsonencode({
    "workspaceKey" = azurerm_log_analytics_workspace.law.primary_shared_key
  })
}

# Dependency agent extension
resource "azurerm_virtual_machine_extension" "azure-dependency-agent" {

  depends_on = [  azurerm_virtual_machine_extension.azure-monitor-agent  ]
  
  #type as key
  for_each = {
    "DependencyAgentWindows" = {machine_id = "${azurerm_windows_virtual_machine.myWindowsVm1.id}", version = "9.10"}
    "DependencyAgentLinux" = {machine_id = "${azurerm_linux_virtual_machine.myLinuxVm1.id}", version = "9.5"}
  }
  
  name                  = "DAExtension"
  virtual_machine_id    = each.value.machine_id
  publisher             = "Microsoft.Azure.Monitoring.DependencyAgent"
  type                  = each.key
  type_handler_version  =  each.value.version
  automatic_upgrade_enabled  = true
  auto_upgrade_minor_version = true
}
```

### Debug Output/Panic Output

```shell
Error: Code="VMExtensionProvisioningError" Message="VM has reported a failure when processing extension 'AzureMonitorLinuxAgent'. Error message: \"Not all required GCS parameters are provided\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/vmextensionlinuxtroubleshoot "
with azurerm_virtual_machine_extension.azure-monitor-agent["AzureMonitorLinuxAgent"]
on extensions.tf line 3, in resource "azurerm_virtual_machine_extension" "azure-monitor-agent":
resource "azurerm_virtual_machine_extension" "azure-monitor-agent" {
```

**Comment by teowa** [comment] 2023-01-03 09:05
Hi @sambhavpandey , thanks for submitting this issue!
I mannually install the Azure Monitor agent extension in portal, the json is like:
![image](https://user-images.githubusercontent.com/104055472/210326715-62c1cec5-be85-43ee-8592-abbac57813d6.png)
maybe we need to set `GCS_AUTO_CONFIG` property in azurerm_virtual_machine_extension:
```
  settings = jsonencode({
    workspaceId               = azurerm_log_analytics_workspace.law.id
    azureResourceId           = each.value.id
    stopOnMultipleConnections = false

    authentication = {
      managedIdentity = {
        identifier-name  = "mi_res_id"
        identifier-value = azurerm_user_assigned_identity.myUserassignedIdentiy.id
      }
    }
    setting = {
      GCS_AUTO_CONFIG = true
    }

  })
```
Hope this may help.

**Comment by bdorplatt** [comment] 2023-02-06 21:55
We ran into this issue as well and can confirm that adding "GCS_AUTO_CONFIG = true" allows the installation to complete, however, the VM does not connect to the Log Analytics workspace. If we remove the extension and add it via portal, it hooks up immediately. It seems to be a problem only with deploying the extension via Terraform.

Below is our config:

```
# Azure Monitor Extension
resource "azurerm_virtual_machine_extension" "azuremonitorlinuxagent" {
  count                = var.monitoring_enabled ? 1 : 0
  name                 = "AzureMonitorLinuxAgent"
  virtual_machine_id   = azurerm_linux_virtual_machine.server.id
  publisher            = "Microsoft.Azure.Monitor"
  type                 = "AzureMonitorLinuxAgent"
  type_handler_version = "1.24"
  automatic_upgrade_enabled  = true
  auto_upgrade_minor_version = true

    settings = jsonencode({
    GCS_AUTO_CONFIG           = true
    workspaceId               = var.log_analytics_workspace_id
    azureResourceId           = azurerm_linux_virtual_machine.server.id
    stopOnMultipleConnections = false

        authentication = {
      managedIdentity = {
        identifier-name  = var.log_analytics_mi_identifier_name
        identifier-value = var.log_analytics_mi_identifier_value
      }
    }
  })
  protected_settings = jsonencode({
    "workspaceKey" = var.log_analytics_primary_shared_key
  })
}

resource "azurerm_virtual_machine_extension" "da" {
  count                      = var.monitoring_enabled ? 1 : 0
  depends_on                = [azurerm_virtual_machine_extension.azuremonitorlinuxagent]
  name                       = "DependencyAgentLinux"
  virtual_machine_id         = azurerm_linux_virtual_machine.server.id
  publisher                  = "Microsoft.Azure.Monitoring.DependencyAgent"
  type                       = "DependencyAgentLinux"
  type_handler_version       = "9.5"
  automatic_upgrade_enabled  = true
  auto_upgrade_minor_version = true
}

# Associate to a Data Collection Rule
resource "azurerm_monitor_data_collection_rule_association" "dcra" {
  count                   = var.monitoring_enabled ? 1 : 0
  name                    = "${var.server_name}-dcra"
  target_resource_id      = azurerm_linux_virtual_machine.server.id
  data_collection_rule_id = var.azure_monitor_data_collection_rule_id 
  description             = "Linux VM Data Collection Rule Association"
}

```

**Comment by darren-johnson** [comment] 2023-02-13 13:37
Hi folks,

This appears to be working for me fine.  I am doing things slightly different though as I am not specifying any log analytics workspace info for the Linux VM extension as the azurerm_monitor_data_collection_rule_association resource takes care of that.

My code is below in case this helps anyone:

```hcl
resource "azurerm_virtual_machine_extension" "ama_linux" {
  count                       = var.linux_vm_extensions_enabled.ama ? local.agenttest_msdn_linux_vm_count : 0
  name                        = "AzureMonitorLinuxAgent"
  virtual_machine_id          = azurerm_linux_virtual_machine.linux_vm[count.index].id
  publisher                   = "Microsoft.Azure.Monitor"
  type                        = "AzureMonitorLinuxAgent"
  type_handler_version        = "1.0"
  auto_upgrade_minor_version  = true
  automatic_upgrade_enabled   = true
  failure_suppression_enabled = false
  settings = jsonencode({
    authentication = {
      managedIdentity = {
        identifier-name  = "mi_res_id"
        identifier-value = azurerm_user_assigned_identity.large_scale_ama_deployments.id
      }
    }
  })
}
```

Terraform v1.3.8
on darwin_amd64
provider registry.terraform.io/hashicorp/azuread v2.33.0
provider registry.terraform.io/hashicorp/azurerm v3.41.0

**Comment by tombuildsstuff** [comment] 2023-02-13 17:22
👋 hi folks

Unfortunately the behaviour and configuration of the `azurerm_virtual_machine_extension` resource depends on the Virtual Extension which is being provisioned - whilst Terraform is passing the configuration defined in the Terraform Configuration to the Azure API, ultimately the extensions are running scripts against the Virtual Machine which are very open-ended (and can generally only be diagnosed by retrieving log files from the Virtual Machine itself).

Since each type of Virtual Machine Extension has it's own set of behaviours, whilst the Azure Provider is passing the configuration defined in the configs through to the Azure API - the issues being seen here are configuration issues rather than bugs in the Provider, and unfortunately we're unable to offer guidance with regards to the Terraform Configuration that should be being used for each type of Virtual Machine Extension.

As such I'm going to close this issue for the moment since the Azure Provider is working as intended here, but should you have further configuration questions I'd direct you towards [the Community Discuss forum](https://discuss.hashicorp.com).

Thanks!

**Closed by tombuildsstuff** 2023-02-13 17:22 UTC
Labels: question, service/monitor

**Comment by bdorplatt** [comment] 2023-02-14 16:49
> Hi folks,
> 
> This appears to be working for me fine. I am doing things slightly different though as I am not specifying any log analytics workspace info for the Linux VM extension as the azurerm_monitor_data_collection_rule_association resource takes care of that.
> 
> My code is below in case this helps anyone:
> 
> ```terraform
> resource "azurerm_virtual_machine_extension" "ama_linux" {
>   count                       = var.linux_vm_extensions_enabled.ama ? local.agenttest_msdn_linux_vm_count : 0
>   name                        = "AzureMonitorLinuxAgent"
>   virtual_machine_id          = azurerm_linux_virtual_machine.linux_vm[count.index].id
>   publisher                   = "Microsoft.Azure.Monitor"
>   type                        = "AzureMonitorLinuxAgent"
>   type_handler_version        = "1.0"
>   auto_upgrade_minor_version  = true
>   automatic_upgrade_enabled   = true
>   failure_suppression_enabled = false
>   settings = jsonencode({
>     authentication = {
>       managedIdentity = {
>         identifier-name  = "mi_res_id"
>         identifier-value = azurerm_user_assigned_identity.large_scale_ama_deployments.id
>       }
>     }
>   })
> }
> ```
> 
> Terraform v1.3.8 on darwin_amd64 provider registry.terraform.io/hashicorp/azuread v2.33.0 provider registry.terraform.io/hashicorp/azurerm v3.41.0
> 
> EDIT: Upon checking the agent is connected under "Agents management" but under "Workspace Data Sources > Virtual Machines" it is not. Is that what was meant in the original post as this deploys the MMA instead of the AMA?

The VM's weren't even showing up in Agents Management for us. We went ahead and tried what you have without specifying the ID's and also without the dependency agent and now the VM's are reporting to Log Analytics. It is interesting because we had to have that extra information and the DA extension for this to work for a Windows VM. With the above, the extension also didn't require the "GCS_AUTO_CONFIG = true" to be set.  Thank you for sharing your sample code!

**Comment by darren-johnson** [comment] 2023-02-16 06:26
No problem! I guess this is the nature of cloud with things changing rapidly. I ended up reverse engineering from enabling via the portal to get there in the end.
