### ISSUE TITLE
Intermittent Error with azurerm_monitor_autoscale_setting for Azure App Service Plan - "UnsupportedMetric" (CpuPercentage)

### ISSUE THREAD

**Issue by kbargobdo** [hashicorp/terraform-provider-azurerm#23579] opened 2023-10-16 14:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.3.7

### AzureRM Provider Version

3.75.0

### Affected Resource(s)/Data Source(s)

azurerm_monitor_autoscale_setting

### Terraform Configuration Files

```hcl
resource "azurerm_service_plan" "asp" {
  name                = "${var.tenant}-${var.region_abbr}-${var.subscription}-${var.asp_name_short}-asp"
  location            = var.region
  os_type             = var.asp_os_type
  resource_group_name = var.resource_group_name
  sku_name            = var.asp_sku_name

  lifecycle {
    ignore_changes = [
      # Ignore changes to tags, e.g. because a management agent
      # updates these based on some ruleset managed elsewhere.
      tags,
    ]
  }
}



resource "azurerm_monitor_autoscale_setting" "autoscale_setting" {
  count               = var.asp_sku_name != "Y1" && var.asp_enable_autoscale == true ? "1" : "0"
  name                = "${var.tenant}-${var.region_abbr}-${var.subscription}-${var.asp_name_short}-asp-autoscaleCPU"
  resource_group_name = var.resource_group_name
  location            = var.region
  target_resource_id  = azurerm_service_plan.asp.id

  profile {
    name = "Scale in when CPU and memory usage are LOW at night"

    capacity {
      default = var.asp_scale_in_cpu_default_capacity
      minimum = var.asp_scale_in_cpu_minimum_capacity
      maximum = var.asp_scale_in_cpu_maximum_capacity
    }

    rule {
      metric_trigger {
        metric_name        = "CpuPercentage"
        metric_resource_id = azurerm_service_plan.asp.id
        time_grain         = "PT1M"
        statistic          = "Average"
        time_window        = "PT${var.asp_scale_in_time_threshold}M"
        time_aggregation   = "Average"
        operator           = "LessThan"
        threshold          = var.asp_scale_in_cpu_threshold
      }

      scale_action {
        direction = "Decrease"
        type      = "ChangeCount"
        value     = "1"
        cooldown  = "PT30M"
      }
    }

    rule {
      metric_trigger {
        metric_name        = "MemoryPercentage"
        metric_resource_id = azurerm_service_plan.asp.id
        time_grain         = "PT1M"
        statistic          = "Average"
        time_window        = "PT${var.asp_scale_in_time_threshold}M"
        time_aggregation   = "Average"
        operator           = "LessThan"
        threshold          = var.asp_scale_in_memory_threshold
      }

      scale_action {
        direction = "Decrease"
        type      = "ChangeCount"
        value     = "1"
        cooldown  = "PT30M"
      }
    }

    recurrence {
      timezone = var.asp_scaling_timezone
      days     = ["Saturday", "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
      hours    = [var.asp_scale_in_start_hour]
      minutes  = [var.asp_scale_in_start_minute]
    }
  }

  profile {
    name = "Scale out when CPU and Memory usage is HIGH during business hours"

    capacity {
      default = var.asp_scale_out_cpu_default_capacity
      minimum = var.asp_scale_out_cpu_minimum_capacity
      maximum = var.asp_scale_out_cpu_maximum_capacity
    }

    rule {
      metric_trigger {
        metric_name        = "CpuPercentage"
        metric_resource_id = azurerm_service_plan.asp.id
        time_grain         = "PT1M"
        statistic          = "Average"
        time_window        = "PT${var.asp_scale_in_time_threshold}M"
        time_aggregation   = "Average"
        operator           = "GreaterThan"
        threshold          = var.asp_scale_out_cpu_threshold
      }

      scale_action {
        direction = "Increase"
        type      = "ChangeCount"
        value     = "1"
        cooldown  = "PT5M"
      }
    }

    rule {
      metric_trigger {
        metric_name        = "MemoryPercentage"
        metric_resource_id = azurerm_service_plan.asp.id
        time_grain         = "PT1M"
        statistic          = "Average"
        time_window        = "PT${var.asp_scale_in_time_threshold}M"
        time_aggregation   = "Average"
        operator           = "GreaterThan"
        threshold          = var.asp_scale_out_memory_threshold
      }

      scale_action {
        direction = "Increase"
        type      = "ChangeCount"
        value     = "1"
        cooldown  = "PT5M"
      }
    }

    recurrence {
      timezone = var.asp_scaling_timezone
      days     = ["Saturday", "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
      hours    = [var.asp_scale_out_start_hour]
      minutes  = [var.asp_scale_out_start_minute]
    }
  }

  lifecycle {
    ignore_changes = [
      # Ignore changes to tags, e.g. because a management agent
      # updates these based on some ruleset managed elsewhere.
      tags,
    ]
  }
}
```

### Debug Output/Panic Output

```shell
Cannot re-produce currently due to intermittent issue
```

### Expected Behaviour

App Service Plan deployed with specified app service plan scaling rules. No error expected as the metrics are correct per [Microsoft documentation](https://learn.microsoft.com/en-us/azure/azure-monitor/reference/supported-metrics/microsoft-web-serverfarms-metrics).

### Actual Behaviour

Occasionally (one every few builds) this is erroring out and terminating the run. Re-running the Terraform Plan and Apply always resolves the issue.

### Steps to Reproduce

1. terraform plan (targeting app service plan resource)
2. terraform apply (targeting app service plan resource)

### Important Factoids

Standard

### References

N/A

**Comment by teowa** [comment] 2023-10-17 10:21
Hi @kbargobdo , this is duplicated with https://github.com/hashicorp/terraform-provider-azurerm/issues/22160. This should be service API issue, I guess the `CpuPercentage` is not ready right after App Service is created and thus Autoscale Setting fail to create, could you please try add a [time_sleep](https://registry.terraform.io/providers/hashicorp/time/latest/docs/resources/sleep) to workaround this. Thanks,

**Comment by rcskosir** [comment] 2023-10-18 18:21
@kbargobdo Thanks for taking the time to submit this issue. It looks like this is a duplicate of #22160. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of #22160.

**Closed by rcskosir** 2023-10-18 18:21 UTC
Labels: duplicate, service/monitor, v/3.x
