### ISSUE TITLE
AzureRM Provider Doesn't Handle Storage Account ListKeys Permission Denied (403)

### ISSUE THREAD

**Issue by JPadster** [hashicorp/terraform-provider-azurerm#18687] opened 2022-10-10 14:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.0

### AzureRM Provider Version

3.24.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
Note: To reproduce, Azure RBAC Role *MUST* prevent 'Microsoft.Storage/storageAccounts/listKeys/action'

provider "azurerm" {
  storage_use_azuread = true
}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_storage_account" "example" {
  name                     = "storageaccountname"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "GRS"
  shared_access_key_enabled = false

  tags = {
    environment = "staging"
  }
```

### Debug Output/Panic Output

```shell
Error: listing Keys for Storage Account: (Name: "storageaccountname" / Resource Group "rgstorage"): storage.AccountsClient#ListKeys: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '<client_id>' with object id '<object_id>' does not have authorization to perform action 'Microsoft.Storage/storageAccounts/listKeys/action' over scope '<storage account scope>' or the scope is invalid. If access was recently granted, please refresh your credentials."
```

### Expected Behaviour

No error. The code on 
[https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/storage/storage_account_resource.go#L1768](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/storage/storage_account_resource.go#L1768)
should have handled a scenario where RBAC permission prevents listKeys operation. It handles a `http.StatusUnauthorized` (401) but not a `http.StatusForbidden` (403).

### Actual Behaviour

Error: listing Keys for Storage Account: (Name: "storageaccountname" / Resource Group "rgstorage"): storage.AccountsClient#ListKeys: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '<client_id>' with object id '<object_id>' does not have authorization to perform action 'Microsoft.Storage/storageAccounts/listKeys/action' over scope '<storage account scope>' or the scope is invalid. If access was recently granted, please refresh your credentials."

### Steps to Reproduce

terraform apply

### Important Factoids

RBAC role prevents 'Microsoft.Storage/storageAccounts/listKeys/action'

**Comment by tombuildsstuff** [comment] 2022-10-10 15:18
hi @JPadster 

Thanks for opening this issue.

When provisioning Resources in Terraform we require that we have CRUD access to fully manage this resource - whereas a Data Source by comparison assumes we may not have permissions (and will gracefully fall back where appropriate).

Whilst we could look to handle this use-case, since we're requiring CRUD access to the Storage Account (including listing it's keys) unfortunately this is working as intended at present - ultimately we're looking to use the Resource Manager API where possible, which would remove the need to look up the keys here, which is being tracked in #2977, however unfortunately at this time we're blocked waiting on the Service Team to make the Data Plane and Resource Manager API's feature compatible.

Once the upstream issue is resolved we can look to rely on the Data Plane API rather than the Resource Manager API (and fix #2977), which'll remove the need for the keys here - however since this API call is currently required whilst I'd like to thank you for opening this issue I'm going to close this out as working as intended for the moment.

Thanks!

**Closed by tombuildsstuff** 2022-10-10 15:18 UTC
Labels: question
