### ISSUE TITLE
Hostpool Token inconsistent final plan

### ISSUE THREAD

**Issue by mdlister** [hashicorp/terraform-provider-azurerm#12038] opened 2021-06-02 14:50 UTC
Error: Provider produced inconsistent final plan

When expanding the plan for
module.hostpool["Test3A"].azurerm_virtual_desktop_host_pool.example to include
new values learned so far during apply, provider
"registry.terraform.io/hashicorp/azurerm" produced an invalid new value for
.registration_info[0].expiration_date: was
cty.StringVal("2021-06-22T14:12:51Z"), but now
cty.StringVal("2021-06-12T14:12:51Z").

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.15.4
+ provider registry.terraform.io/hashicorp/azurerm v2.57.0
+ provider registry.terraform.io/hashicorp/time v0.7.1

### Affected Resource(s)

```
resource "time_rotating" "wvd_token" {
  rotation_days = 10
}
resource "azurerm_virtual_desktop_host_pool" "example" {
  resource_group_name = azurerm_resource_group.example.name
  name                = "${var.prefix}-hostpool"
  location            = var.hostpoolmetalocation #Limited locations currently available
  validate_environment     = false
  type                     = var.HostpoolType
  maximum_sessions_allowed = var.HostpoolMaxSessions
  load_balancer_type       = var.Load_Balancer_Type

  registration_info {
    expiration_date = time_rotating.wvd_token.rotation_rfc3339
  }
  depends_on = [
    azurerm_resource_group.example,time_rotating.wvd_token
  ]
}
```

### Expected Behaviour

Hostpool has no registration token on first run it creates hostpool and token, 

After token has expired (max 27 days) create additional machines and new token is generated and applied to new machines.

### Actual Behaviour

If the token has expired and no longer exists you get the following: 

Error: Invalid template interpolation value

```
  on Modules\WVDHost\virtual_machine_extensions.tf line 81, in resource "azurerm_virtual_machine_extension" "additional_session_host_dscextension":
  75:   settings = <<SETTINGS
  76: {
  77:     "modulesURL": "${var.base_url}/DSC/Configuration.zip",
  78:     "configurationFunction": "Configuration.ps1\\AddSessionHost",
  79:      "properties": {
  80:         "HostPoolName":"${var.hostpool_name}",
  81:         "RegistrationInfoToken":"${var.hostpool_token}"
  82:   }
  83: }
  85: SETTINGS
    |----------------
    | var.hostpool_token is null

The expression result is null. Cannot include a null value in a string
template.
```

if you open the azure portal and generate a token for a few hours from now then run the code to create additional machines 

```
When expanding the plan for
module.hostpool["Test3A"].azurerm_virtual_desktop_host_pool.example to include
new values learned so far during apply, provider
"registry.terraform.io/hashicorp/azurerm" produced an invalid new value for
.registration_info[0].expiration_date: was
cty.StringVal("2021-06-22T14:12:51Z"), but now
cty.StringVal("2021-06-12T14:12:51Z").

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

### Steps to Reproduce

Create hostpool and registration token block

wait for the token to expire and try again the token is now missing and will be Null 

1. `terraform apply`

I've tried three ways to generate the token to force the resource to regenerate the token
1. resource "time_offset" "example" {
  offset_days = 7
}
2. resource "time_rotating" "wvd_token" {
  rotation_days = 7
}
3. expiration_date = timeadd (timestamp(), "24h")

**Comment by SebRosander** [comment] 2021-06-08 07:31
We are having similar issue, no matter how we reference to the registration key, it gives us a null value:
`│   on main.tf line 189, in resource "azurerm_virtual_machine_extension" "additional_session_host_dscextension":
│  183:   settings = <<SETTINGS
│  184:         {
│  185:             "ModulesUrl":"https://wvdportalstorageblob.blob.core.windows.net/galleryartifacts/Configuration_3-10-2021.zip",
│  186:             "ConfigurationFunction":"Configuration.ps1\\AddSessionHost",
│  187:             "properties": {
│  188:                 "hostPoolName": "${azurerm_virtual_desktop_host_pool.pooledbreadthfirst.name}",
│  189:                 "registrationInfoToken":"${local.regkey}"
│  190:             }
│  191:         }
│  192: SETTINGS
│     ├────────────────
│     │ local.regkey has a sensitive value
│ 
│ The expression result is null. Cannot include a null value in a string template.
`

**Comment by mdlister** [comment] 2021-06-08 14:00
I have a work around for that, if you are using Azure Pipelines tho you could do it with a terraform null resource 

If the Hostpool Exists and there is no Token you will get this error as Null is not an expected value (even tho it should be) during some testing I did the following:
1. Generate a registration token
2. Apply my TF Code 
3. Token gets updated with the new value 

Hostpool.tf
```
 registration_info {
    expiration_date = timeadd (timestamp(), "24h")
  }
```

We are now using this which will generate a token every time regardless. 

I see 2 ways to fix it, 
1. Generate a 27 day token (max limit of token) 
2. Every 14 days re-run the pipeline, no infrastructure changes will happen but the token will be updated and will always exist. 

Option 2 
1. Include a step in the pipeline that generates hostpool tokens before running the TF code. 
(get all Hostpools, for each hostpool generate token for 6 hours)
Terraform Step will run and generate a new token for xx amount of time defined. In my example 24hr

if you aren't using Azure Pipelines you can do a null resource and call the Azure CLI \ Azure Powershell commands Spring update for WVD gives you more powershell commands (New-AzWvdRegistrationInfo)

**Comment by tombuildsstuff** [comment] 2021-11-15 13:57
hi @mdlister 

Thanks for opening this issue.

Taking a look through this appears to be a duplicate of #13793 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #13793 for updates?

Thanks!

**Closed by tombuildsstuff** 2021-11-15 13:57 UTC
Labels: bug, service/virtual-desktops
