### ISSUE TITLE
Microsoft.StoragePool and Microsoft.MachineLearningServices

### ISSUE THREAD

**Issue by paul-towler** [hashicorp/terraform-provider-azurerm#18820] opened 2022-10-18 03:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.3

### AzureRM Provider Version

3.11.0

### Affected Resource(s)/Data Source(s)

azurerm

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
  subscription_id            = local.subscriptions.azr.prerequisites
}

provider "azurerm" {
  features {}
  alias                      = "infr"
  subscription_id            = local.subscriptions.azr.core_infrastructure
}

provider "azurerm" {
  features {}
  alias                      = "cybr_prd"
  subscription_id            = local.subscriptions.azr.cyber_security_prd
}

provider "azurerm" {
  features {}
  alias                      = "cybr_nprd"
  subscription_id            = local.subscriptions.azr.cyber_security_nprd
}
```

### Debug Output/Panic Output

```shell
Original Error: Cannnot register providers: Microsoft.MachineLearningServices, Microsoft.StoragePool. Errors were: Cannot register provider Microsoft.MachineLearningServices with Azure Resource Manager: resources.ProvidersClient#Register: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an
error. Status=403 Code="AuthorizationFailed" Message="The client '5d1d1900-470c-4f77-904e-a76158e69107' with object id '5d1d1900-470c-4f77-904e-a76158e69107' does not have authorization to perform action 'Microsoft.MachineLearningServices/register/action' over scope '/subscriptions/ca092483-7219-4435-a254-adf960f7acbf' or the scope is invalid.
If access was recently granted, please refresh your credentials.".
Cannot register provider Microsoft.StoragePool with Azure Resource Manager: resources.ProvidersClient#Register: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '5d1d1900-470c-4f77-904e-a76158e69107' with object id
'5d1d1900-470c-4f77-904e-a76158e69107' does not have authorization to perform action 'Microsoft.StoragePool/register/action' over scope '/subscriptions/ca092483-7219-4435-a254-adf960f7acbf' or the scope is invalid. If access was recently granted, please refresh your credentials.".
  with provider["registry.terraform.io/hashicorp/azurerm"].infr,
  on C:\Users\skvirskiys_t1\AppData\Local\Temp\9\Hydro_20221017\terraform\shared-services\00-init.tf line 43, in provider "azurerm":
  43: provider "azurerm" {
Error: Error ensuring Resource Providers are registered.
```

### Expected Behaviour

Microsoft.StoragePool registers successfully

### Actual Behaviour

Microsoft.StoragePool is stuck trying to register and Terraform Apply faila

### Steps to Reproduce

1. terraform apply

### References

From Microsoft:

Microsoft.StoragePool is the provider of the resource DiskPool. You can find the information from Microsoft.StoragePool resource types and Register Microsoft.StoragePool on your subscription to use DiskPool. As we are officially halting the preview of Azure Disk Pools, you will not be able to register the Microsoft.StoragePool resource provider on you subscription and deploy new Disk Pools. That’s why the registering job is stuck at the registering state. Reference document: Attach disk pools to Azure VMware Solution hosts. If Disk Pool is not the resource type you are interested in, please share more details or documents about the resource you are looking for. We will get the right team to help with your request. Thanks!

**Comment by lonegunmanb** [comment] 2022-10-20 03:03
Hi @paul-towler thanks for opening this pr. I've tried the [example code](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/disk_pool) but I've met another issue:

```text
│ Error: creating Disk Pool (Subscription: "xxx"
│ Resource Group Name: "zhe-diskpool"
│ Disk Pool Name: "zjhepool"): pollingTrackerBase#updateRawBody: failed to unmarshal response body: StatusCode=0 -- Original Error: inv
alid character 'F' looking for beginning of value
│
│   with azurerm_disk_pool.example,
│   on main.tf line 49, in resource "azurerm_disk_pool" "example":
│   49: resource "azurerm_disk_pool" "example" {
│
│ creating Disk Pool (Subscription: "xxx"
│ Resource Group Name: "zhe-diskpool"
│ Disk Pool Name: "zjhepool"): pollingTrackerBase#updateRawBody: failed to unmarshal response body: StatusCode=0 -- Original Error:    
│ invalid character 'F' looking for beginning of value
╵
```

I'll try to fix my issue later, but according to your error message:

>Message="The client 'xxxx' with object id
'xxx' does not have authorization to perform action 'Microsoft.StoragePool/register/action' over scope '/subscriptions/xxx' or the scope is invalid. If access was recently granted, please refresh your credentials.".

Would you please try the same code with another account that has higher permission on your subscription? Or would you please give me a minimum sample that could reproduce your issue? Thanks!

**Comment by paul-towler** [comment] 2022-10-20 06:19
Thanks @lonegunmanb. Definitely not an issue with credentials. 

Microsoft has halted the preview of Azure Disk Pools, but the Resource Provider is still listed, but it can't not register because MS has disabled this in the backend on newly provisioned subscriptions.

The azurerm provider, when initialised,  will by default try to enable all Resource Providers available. Because the Disk Pools Resource Provider, although listed, is disabled terraform fails.

The only workaround was to manually enable the Resource Providers available globally and locally , excluding Disk Pools  and update the provider statement with:
``` hcl
skip_provider_registration = true
```

For example:
``` hcl
provider "azurerm" {
  features {}
  alias                      = "infr"
  subscription_id            = local.subscriptions.azr.core_infrastructure
  skip_provider_registration = true
}
```

**Comment by lonegunmanb** [comment] 2022-10-20 06:23
Thanks @paul-towler for your reply, so this issue only occur on new subscription that has never registered DiskPools Resource Provider right? I'll see what I can do to reproduce this issue on my side.

**Comment by paul-towler** [comment] 2022-10-21 00:41
Thanks @lonegunmanb  - Yes, Correct. This issue only occurs on new subscription that has never registered DiskPools Resource Provider, if the DiskPools preview has been disable is your region

**Comment by lonegunmanb** [comment] 2022-10-21 01:52
Hi @paul-towler , could you please share the disk pool code you're using now? What's your AzureRM provider version? Are you using `azurerm_storage_disks_pool` or `azurerm_disk_pool`? Because `azurerm_disk_pool` resource are not using the preview API now. Meanwhile I'm still trying to get a new subscription to reproduce this issue.

**Comment by lonegunmanb** [comment] 2022-10-21 03:15
@paul-towler I've met a different issue. I've registered a new subscription and then applied the following code:

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "zjhe-diskpool"
  location = "eastus"
}

resource "azurerm_virtual_network" "example" {
  name                = "example-network"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  address_space       = ["10.0.0.0/16"]
}

resource "azurerm_subnet" "example" {
  name                 = "example-subnet"
  resource_group_name  = azurerm_virtual_network.example.resource_group_name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefixes     = ["10.0.0.0/24"]

  delegation {
    name = "diskspool"

    service_delegation {
      actions = ["Microsoft.Network/virtualNetworks/read"]
      name    = "Microsoft.StoragePool/diskPools"
    }
  }
}

resource "azurerm_disk_pool" "example" {
  name                = "example-disk-pool"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  sku_name            = "Basic_B1"
  subnet_id           = azurerm_subnet.example.id
  zones               = ["1"]
}
```

The error message is:

```text
azurerm_disk_pool.example: Still creating... [7m40s elapsed]
╷
│ Error: creating Disk Pool (Subscription: "f87eac84-1fc0-494a-821d-58247a1715ce"
│ Resource Group Name: "zjhe-diskpool"
│ Disk Pool Name: "example-disk-pool"): pollingTrackerBase#updateRawBody: failed to unmarshal response body: StatusCode=0 -- Original E
rror: invalid character 'F' looking for beginning of value
│
│   with azurerm_disk_pool.example,
│   on main.tf line 46, in resource "azurerm_disk_pool" "example":
│   46: resource "azurerm_disk_pool" "example" {
│
│ creating Disk Pool (Subscription: "f87eac84-1fc0-494a-821d-58247a1715ce"
│ Resource Group Name: "zjhe-diskpool"
│ Disk Pool Name: "example-disk-pool"): pollingTrackerBase#updateRawBody: failed to unmarshal response body: StatusCode=0 -- Original  
│ Error: invalid character 'F' looking for beginning of value
╵
```

The http request and response:

```text
PUT https://management.azure.com/subscriptions/xxx/resourceGroups/zjhe-diskpool/providers/Microsoft.StoragePool/diskPools/example-disk-pool?api-version=2021-08-01 HTTP/1.1
Host: management.azure.com
User-Agent: Go/go1.18.5 (amd64-windows) go-autorest/v14.2.1 pandora/diskpools/2021-08-01 HashiCorp Terraform/1.3.2 (+https://www.terraform.io) Terraform Plugin SDK/2.10.1 terraform-provider-azurerm/dev pid-222c6c49-1b0a-5959-a213-6608f9eb8820
Content-Length: 290
Content-Type: application/json; charset=utf-8
X-Ms-Authorization-Auxiliary: 
X-Ms-Correlation-Request-Id: ddb50675-7224-c40c-1a6f-7d0681ecc971
Accept-Encoding: gzip

{"location":"eastus","properties":{"availabilityZones":["1"],"subnetId":"/subscriptions/xxx/resourceGroups/zjhe-diskpool/providers/Microsoft.Network/virtualNetworks/example-network/subnets/example-subnet"},"sku":{"name":"Basic_B1","tier":"Basic"},"tags":{}}
HTTP/1.1 502 Forbidden
Cache-Control: no-cache
Pragma: no-cache
Content-Length: 10
Content-Type: text/plain; charset=utf-8
Expires: -1
x-ms-ratelimit-remaining-subscription-writes: 1199
X-Content-Type-Options: nosniff
X-Ms-Client-Request-Id: 1e5ee6e7-e4a1-424e-a16d-653be22060c1
X-Ms-Request-Id: 87c8dfc9-893c-469a-ac9b-719666cd8b11
X-Ms-Return-Client-Request-Id: true
Strict-Transport-Security: max-age=31536000; includeSubDomains
x-ms-correlation-request-id: ddb50675-7224-c40c-1a6f-7d0681ecc971
x-ms-failure-cause: gateway
x-ms-routing-request-id: SOUTHEASTASIA:20221021T024840Z:cb2c99ca-f709-4f7f-9218-3a1da873449a
Date: Fri, 21 Oct 2022 02:48:40 GMT
Connection: close

Forbidden
```

The response body `Forbidden` doesn't meet the sdk's expectation, that's the cause of my error message.

It looks like Azure just forbid all new subscription using Disk Pool, but my subscription registered this StoragePool Resource Provider successfully.

![](https://lonegunman.oss-cn-shanghai.aliyuncs.com/20221021110432.png)

I've also tried to create a disk pool under this new subscription, but there's no az or sku for me to choose:

![](https://lonegunman.oss-cn-shanghai.aliyuncs.com/20221021111108.png)

I guess there nothing to do in Terraform Provider side since it's been blocked in service side. But we can update Terrafor document to warn our user.

**Comment by stephybun** [comment] 2022-10-21 05:56
Closed by #18900

**Comment by paul-towler** [comment] 2022-10-21 05:56
Hi @lonegunmanb. 

I'm not actually using terraform to create Disk Pools.

In the original code to initialise the azurerm provider we didn't use the ``` skip_provider_registration = true ```. For example:
``` hcl
provider "azurerm" {
  features {}
  alias           = "infr"
  subscription_id = local.subscriptions.azr.core_infrastructure
}
```

This cause an issue on new Subscriptions (where Disk Pools is disabled at the backend) when the azurerm provider is initilised because, by default, Terraform will attempt to register any Resource Providers that it supports, even if they're not used in configurations. As noted here: [skip_provider_registration](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#skip_provider_registration)

What we ended up enabling required Resource Providers using PowerShell and adding ``` skip_provider_registration = true ``` to the azurerm provder. This stops Terraform from registering the any Resource Providers. Terraform doesn't recommend doing this, but I had no choice.

We received this from Microsoft today:
``` text
It seems manually unregistering or registering the resource provider failed on our side also. So we are making a fix to address this issue. The fix is a two-step process:

1. Revert a code change that was introduced to prevent new customers from onboarding Microsoft.StoragePool. This change has been merged, and is rolling out now. I expect it to take 5 days to complete in all regions.

2. Update ARM to ensure this resource provider is no longer listed. This should prevent future issues from you and the many other customers.
```

Hope this helps?

Thanks

**Closed by stephybun** 2022-10-21 05:56 UTC
Labels: documentation, service/disks

**Comment by lonegunmanb** [comment] 2022-10-21 06:55
Thanks @paul-towler, I think we need an extra pull request to remove this auto registration for `Microsoft.StoragePool` since the users who used this feature have already registered, and for who haven't they'll meet the exactly issue you've met.

**Comment by lonegunmanb** [comment] 2022-10-21 07:10
@paul-towler I've opened a new pull request to remove registration for `Microsoft.StoragePool`. 

I've noticed that you've met issue on registration for `Microsoft.MachineLearningServices` too, is that issue caused by the same reason? Do you have any official document on that?

Thanks for your detailed response and understanding!

**Comment by paul-towler** [comment] 2022-10-28 04:44
Thanks @lonegunmanb! 

The issue was different for ```Microsoft.MachineLearningServices```. That was resolved by MS

Thanks again for your help!
