### ISSUE TITLE
azurerm_application_insights_workbook (413 with response: "The workbook length is too large)

### ISSUE THREAD

**Issue by brad2190** [hashicorp/terraform-provider-azurerm#24452] opened 2024-01-10 11:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.6

### AzureRM Provider Version

3.86.0

### Affected Resource(s)/Data Source(s)

azurerm_application_insights_workbook

### Terraform Configuration Files

```hcl
locals {
  // Fetch the list of files, so that we can apply Workbooks.
  workbook_list = tolist(fileset(path.root, "/workbooks/*.json"))

  // Convert the list of files to a map.
  workbooks_map = try(length(local.workbook_list) > 0, false) ? {
    for filepath in local.workbook_list :
    trimsuffix(basename(filepath), ".json") => filepath
  } : null
}
resource "random_uuid" "workbook_uuid" {
  for_each = local.workbooks_map
}

resource "azurerm_application_insights_workbook" "workbook" {
  for_each            = local.workbooks_map
  name                = random_uuid.workbook_uuid[each.key].result
  resource_group_name = module.workbooks-rg.name
  location            = var.location
  display_name        = each.key
  data_json           = file(each.value)
  tags                = var.env_tags
}

// Workbook from directory is 3MB
```

### Debug Output/Panic Output

```shell
Error: creating Workbook (Subscription: "Redacted"
│ Resource Group Name: "Redacted"
│ Workbook Name: "Redacted"): unexpected status 413 with response: "The workbook length is too large."
```

### Expected Behaviour

Workbook is read from the directory, jsonencoded and submitted into the AzureRM API.

### Actual Behaviour

Fails with json encoded data to large. (413 with response: "The workbook length is too large)

### Steps to Reproduce

Create a workbook which when exported to json is 3MB in size. (Limit is likely smaller)

**Comment by harshavmb** [comment] 2024-01-10 13:30
Hi @brad2190,

I've not actively worked with workbooks but I do see a limit of 10,000 records [here](https://learn.microsoft.com/en-us/azure/azure-monitor/visualize/workbooks-limits). 

You could check the length with `jq` like `jq length <json-value>`. Does your `data_json` parameter loading a json file more than 10,000 records?

**Comment by teowa** [comment] 2024-01-12 08:50
@brad2190 , it is hard to reproduce this, would you provide some Pseudo data which can reproduce this? From [source code](https://github.com/hashicorp/terraform-provider-azurerm/blob/d9565a2129b1fc3b5956d4e8904d2c80c94b8bf0/internal/services/applicationinsights/application_insights_workbook_resource.go#L162), the provider is passing the json data directly to the Azure API, so the `status 413 with response: "The workbook length is too large."` should be API limitation.

**Comment by rcskosir** [comment] 2024-03-19 20:38
Thanks for taking the time to submit this issue. @teowa was unable to reproduce this behavior. We’re going to close this issue for now, but if you are able to provide us with some more information like pseudo data we can reopen this issue.

**Closed by rcskosir** 2024-03-19 20:38 UTC
Labels: waiting-response, service/application-insights, v/3.x
