### ISSUE TITLE
Support for workload profiles within azurerm_container_app Resources

### ISSUE THREAD

**Issue by colinbjohnson** [hashicorp/terraform-provider-azurerm#22161] opened 2023-06-14 00:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When building a azurerm_container_app within terraform we would like to be able to utilize a `workload_profile_name` property. An example of a Azure Container App (described in JSON format) that includes this property is below:

```
{
    "id": "/subscriptions/x/resourceGroups/my-app/providers/Microsoft.App/containerapps/my-app",
    "name": "my-app",
    "type": "Microsoft.App/containerApps",
    "location": "East US",
    "systemData": {
        "createdBy": "x",
        "createdByType": "User",
        "createdAt": "2023-06-13T18:20:56.7204791",
        "lastModifiedBy": "x",
        "lastModifiedByType": "User",
        "lastModifiedAt": "2023-06-13T18:39:11.0371897"
    },
    "properties": {
        "provisioningState": "Succeeded",
        "managedEnvironmentId": "/subscriptions/x/resourceGroups/aca-prod/providers/Microsoft.App/managedEnvironments/aca-prod",
        "environmentId": "/subscriptions/x/resourceGroups/aca-prod/providers/Microsoft.App/managedEnvironments/aca-prod",
        "workloadProfileName": "E16",
        "outboundIpAddresses": null,
        "latestRevisionName": "my-app--af7pu8m",
        "latestReadyRevisionName": "my-app--af7pu8m",
        "latestRevisionFqdn": "my-app--af7pu8m.delightfulmeadow-d01a5354.eastus.azurecontainerapps.io",
        "configuration": {
            "activeRevisionsMode": "Single",
            "dapr": null,
            "maxInactiveRevisions": null,
            "service": null
        },
        "template": {
            "revisionSuffix": "",
            "containers": [
                {
                    "image": "company.azurecr.io/my-app:latest",
                    "name": "my-app",
                    "resources": {
                        "cpu": 8,
                        "memory": "96Gi",
                        "ephemeralStorage": ""
                    },
                    "probes": []
                }
            ],
            "initContainers": null,
            "scale": {
                "minReplicas": 1,
                "maxReplicas": 1,
                "rules": null
            },
            "volumes": null,
            "serviceBinds": null
        },
        "eventStreamEndpoint": "https://eastus.azurecontainerapps.dev/subscriptions/x/resourceGroups/my-app/containerApps/my-app/eventstream"
    },
    "identity": {
        "type": "None"
    }
}
```

### New or Affected Resource(s)/Data Source(s)

azurerm_container_app

### Potential Terraform Configuration

See the additional property named `workload_profile_name`.

```hcl
resource "azurerm_container_app" "my_app" {
  name                         = "my_app"
  container_app_environment_id = "/subscriptions/x/resourceGroups/aca-prod/providers/Microsoft.App/managedEnvironments/aca-prod"
  resource_group_name          = azurerm_resource_group.my_app.name
  revision_mode                = "Single"
  # the workload_profile_name is the property which we would like to add
  workload_profile_name        = "E16"
  template {
    container {
      name   = "my-app"
      image  = "company.azurecr.io/my-app:latest"
      cpu    = 8.0
      memory = "96Gi"
    }
  }
}
```
```


### References

_No response_

**Comment by si-te** [comment] 2023-06-21 07:57
There is a similiar issue already here: https://github.com/hashicorp/terraform-provider-azurerm/issues/21747 

This is a very anticipated feature, as it is a requirement in enterprise settings where you have requirements for user defined routing.

**Comment by dss010101** [comment] 2023-10-05 06:35
You are not able to attach VNet/Public IP to a Container App (and i assume other similar managed servicces) unless you can set  Workload profiles:  https://learn.microsoft.com/en-us/azure/container-apps/networking?tabs=azure-cli#environment-selection

So this is an important feature...and for us a blocker

**Comment by jackofallops** [comment] 2023-12-04 11:28
Closing as a duplicate of #21747

**Closed** 2023-12-13 16:19 UTC
Labels: enhancement, service/container-apps

**Comment by dss010101** [comment] 2024-03-16 01:33
any idea when this will be released?
