### ISSUE TITLE
azurerm_windows_virtual_machine error creating from image with managed data disks

### ISSUE THREAD

**Issue by fmuntean** [hashicorp/terraform-provider-azurerm#12877] opened 2021-08-06 13:40 UTC
I am trying to build a VM using a Shared Image Gallery Image that has a Data Disk and I get the following error:
Message="StorageProfile.dataDisks.lun does not have required value(s) for image specified in storage profile."

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v1.0.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.70.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0

### Affected Resource(s)

resource "azurerm_windows_virtual_machine"

ease provide a link to a GitHub Gist containing the output of the `crash.log`. --->

### Expected Behaviour

Have expected to be able to create the VM.

### Actual Behaviour

Errors out during the apply phase.

### Steps to Reproduce

Build an image with OS and DATA Disk. Then try to create an VM from it.

**Comment by fmuntean** [comment] 2021-08-10 14:31
I see no update on this issue. How can we create VMs with data disks using terraform ?
Currently this is a blocker for my project.

**Comment by tombuildsstuff** [comment] 2021-08-10 14:41
Duplicate of #7772

**Closed by tombuildsstuff** 2021-08-10 14:41 UTC
