### ISSUE TITLE
terraform plan show state change without code change

### ISSUE THREAD

**Issue by CharmanderJieniJieni** [hashicorp/terraform-provider-azurerm#7215] opened 2020-06-04 20:02 UTC
### Terraform (and AzureRM Provider) Version

Terraform v0.12.26
+ provider.azuread v0.8.0
+ provider.azurerm v2.8.0
+ provider.random v2.2.1

### Affected Resource(s)
azurerm_sql_database

* `azurerm_sql_database`

### Terraform Configuration Files

see code [here](https://github.com/CharmanderJieniJieni/Terraform) 

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output
- log {
          - category = "AutomaticTuning" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = true -> null
            }
        }
      + log {
          + category = "AutomaticTuning"
          + enabled  = true

          + retention_policy {
              + enabled = true
            }
        }
      - log {
          - category = "Blocks" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = true -> null
            }
        }
      + log {
          + category = "Blocks"
          + enabled  = true

          + retention_policy {
              + enabled = true
            }
        }
      - log {
          - category = "DatabaseWaitStatistics" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = true -> null
            }
        }
      + log {
          + category = "DatabaseWaitStatistics"
          + enabled  = true

          + retention_policy {
              + enabled = true
            }
        }
      - log {
          - category = "Deadlocks" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = true -> null
            }
        }
      + log {
          + category = "Deadlocks"
          + enabled  = true

          + retention_policy {
              + enabled = true
            }
        }
      - log {
          - category = "DevOpsOperationsAudit" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      - log {
          - category = "Errors" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = true -> null
            }
        }
      + log {
          + category = "Errors"
          + enabled  = true

          + retention_policy {
              + enabled = true
            }
        }
      - log {
          - category = "QueryStoreRuntimeStatistics" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = true -> null
            }
        }
      + log {
          + category = "QueryStoreRuntimeStatistics"
          + enabled  = true

          + retention_policy {
              + enabled = true
            }
        }
      - log {
          - category = "QueryStoreWaitStatistics" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = true -> null
            }
        }
      + log {
          + category = "QueryStoreWaitStatistics"
          + enabled  = true

          + retention_policy {
              + enabled = true
            }
        }
      - log {
          - category = "SQLInsights" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = true -> null
            }
        }
      + log {
          + category = "SQLInsights"
          + enabled  = true

          + retention_policy {
              + enabled = true
            }
        }
      - log {
          - category = "SQLSecurityAuditEvents" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      - log {
          - category = "Timeouts" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = true -> null
            }
        }
      + log {
          + category = "Timeouts"
          + enabled  = true

          + retention_policy {
              + enabled = true
            }
        }

### Expected Behavior

nothing should be changed
### Actual Behavior

everytime we trigger terraform plan, the output shows up which indicates there is going to be listed changes, even there is no code change at all

### Steps to Reproduce

terraform plan

### References

* #0000

**Comment by magodo** [comment] 2020-06-05 04:08
@CharmanderJieniJieni Thank you for opening this issue :+1: 
The reason you are facing this diff is that you missed two log categories: `DevOpsOperationsAudit` and `SQLSecurityAuditEvents`, which are set by the service side if you didn't explicitly specify. So when you do a diff after apply, are actually telling terraform to remove `DevOpsOperationsAudit` and `SQLSecurityAuditEvents` from` log`, that's why you are getting a diff. So when you want to change `log`, you need to specify it as a whole (not partially).

**Comment by CharmanderJieniJieni** [comment] 2020-06-05 04:43
Thanks @magodo , I added those two into variable file and no longer see that issue, however, when I run terraform plan I am still seeing below change

    ~ threat_detection_policy {
            disabled_alerts      = []
            email_account_admins = "Disabled"
            email_addresses      = [
                "test@abc.com",
            ]
            retention_days       = 30
            state                = "Enabled"
          ~ use_server_default   = "Disabled" -> "enabled"
        }
    }

Even through I already set 'use_server_default' to 'enabled' to begin with. Is there a reason for that?

**Comment by magodo** [comment] 2020-06-05 05:24
@CharmanderJieniJieni What is the current config for the `azurerm_sql_database`? Isn't it the one you linked above? https://github.com/CharmanderJieniJieni/Terraform/blob/99a12f610c1036e03a54f14249bf196e94b83806/sql-database.tf#L14
(As the config marked unmodified above is not the same as the ones in the link)

Would you please provide the detailed step to reproduce this?

**Comment by CharmanderJieniJieni** [comment] 2020-06-05 13:08
@magodo  yes, if you do a terraform apply to deploy the resource, then do a terraform plan without any changes, it will show `~ use_server_default   = "Disabled" -> "enabled"`

**Comment by CharmanderJieniJieni** [comment] 2020-06-05 14:49
I checked in the state file, basically even we set `use_server_default  = "Enabled"`, in the state file it is still showing as `"use_server_default": "Disabled"`

**Comment by magodo** [comment] 2020-06-08 05:18
This seems to be an API issue, I have submitted an issue Azure/azure-rest-api-specs#9762 to track that. I suggest you to either leave `threat_detection_policy` if you intend to use the server default policy or use the new resource set: [mssql_server](https://www.terraform.io/docs/providers/azurerm/r/mssql_server.html), [mssql_database](https://www.terraform.io/docs/providers/azurerm/r/mssql_database.html) and [mssql_server_security_alert_policy](https://www.terraform.io/docs/providers/azurerm/r/mssql_server_security_alert_policy.html) (which only allow server-side policy setting),

**Comment by bcline760** [comment] 2020-08-24 19:51
Has anyone been able to make communication to Microsoft about the upstream bug? We're running into this issue as well.

**Comment by GrooveGod** [comment] 2020-12-09 16:55
Any updates on this?  Still occurring in AzureRM 2.39.
 ```hcl
~ threat_detection_policy { ...
    ~ use_server_default   = "Disabled" -> "Enabled"
}
```

**Comment by pearcec** [comment] 2021-02-11 21:20
Related, duplicate #4556 ?

**Comment by favoretti** [comment] 2021-08-20 08:37
Thanks for opening this issue! Since this issue has been reported a long time ago and relates to an older version of provider - I'm going to close it. If this is still relevant and occurring on the latest version of terraform and provider please do open a new issue!

**Closed by favoretti** 2021-08-20 08:37 UTC
Labels: service/mssql, service/monitor, upstream-microsoft
