### ISSUE TITLE
[azurerm_redis_cache] imported state no fill "maxmemory_policy"

### ISSUE THREAD

**Issue by raphaelquati** [hashicorp/terraform-provider-azurerm#2516] opened 2018-12-14 20:28 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.11.10
+ provider.azurerm v1.20.0
```

### Affected Resource(s)
azurerm_redis_cache

### Terraform Configuration Files
```hcl
resource "azurerm_redis_cache" "redis" {
    name = "teste"
    resource_group_name = "${azurerm_resource_group.teste.name}"
    location = "${azurerm_resource_group.teste.location}"
    enable_non_ssl_port = false
    capacity = 0
    family = "C"
    sku_name = "Basic"
    redis_configuration  { 
        maxmemory_policy = "volatile-lru"
        maxmemory_delta = 2
        maxmemory_reserved = 2
    }
}
```

### Expected Behavior
Field maxmemory_policy filled.
### Actual Behavior
maxmemory_policy = ""

### Steps to Reproduce
terraform import azurerm_redis_cache.redis /subscriptions/xxxx/resourceGroups/xxxxx/providers/Microsoft.Cache/Redis/teste
terraform plan

### Notes

After import, maxmemory_policy  in state is empty

![image](https://user-images.githubusercontent.com/815086/50025398-913e7180-ffcc-11e8-953e-955f9fbd0542.png)

Checking the info in Azure Portal:

![image](https://user-images.githubusercontent.com/815086/50025462-c34fd380-ffcc-11e8-85af-7cb08e58d69c.png)

But calling Azure REST API's, the maxmemory_policy is missing!

![image](https://user-images.githubusercontent.com/815086/50025544-0c078c80-ffcd-11e8-88d4-39d0598f0b43.png)

Azurerm_redis_cache forces "maxmemory_policy" to have a value. So It's impossible to exec **terraform apply** after a **terraform import**: Azure rejects the "update":

![image](https://user-images.githubusercontent.com/815086/50025782-d3b47e00-ffcd-11e8-9339-476a96e5f13f.png)

**Comment by katbyte** [comment] 2018-12-19 20:15
Hi @raphaelquati,

I'm sorry to hear you are having this problem. Thank you for the fix but I believe the root cause here is that the cluster was created with an older/preview version of the API where that property didn't exist. When this happens azure can cache a representation of the resource that lacks the properties of the current API, and when that happens errors like this can happen. Sometimes simply updating the tags via the portal will refresh the cache and fix these issues. I ran your config and didn't get any error:

```tf
[11:48:11] kt@snowbook:~/hashi/2018/gh-2018/az-2516$ cat main.tf
resource "azurerm_resource_group" "test" {
  name     = "kt.201812.az-2516"
  location = "westus"
}

resource "azurerm_redis_cache" "redis" {
    name = "teste"
    resource_group_name = "${azurerm_resource_group.test.name}"
    location = "${azurerm_resource_group.test.location}"
    enable_non_ssl_port = false
    capacity = 0
    family = "C"
    sku_name = "Standard"
    redis_configuration  {
        maxmemory_policy = "volatile-lru"
        maxmemory_delta = 2
        maxmemory_reserved = 2
    }
}

output "id" {
  value = "${azurerm_redis_cache.redis.id}"
}
```

```bash
[11:27:40] kt@snowbook:~/hashi/2018/gh-2018/az-2516$ myazure-buildrun
~/hashi/2018/gh-2018/az-2516 ~/hashi/2018/gh-2018/az-2516
==> Fixing source code with gofmt...
gofmt -s -w ./azurerm
==> Checking that code complies with gofmt requirements...
go install
~/hashi/2018/gh-2018/az-2516

Initializing provider plugins...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
azurerm_resource_group.test: Refreshing state... (ID: /subscriptions/00000000-0000-0000-0000-...b56ba/resourceGroups/kt.201812.az-2516)
azurerm_redis_cache.redis: Creating...
  capacity:                                 "" => "0"
  enable_non_ssl_port:                      "" => "false"
  family:                                   "" => "C"
  hostname:                                 "" => "<computed>"
  location:                                 "" => "westus"
  name:                                     "" => "teste"
  port:                                     "" => "<computed>"
  primary_access_key:                       "<sensitive>" => "<sensitive>"
  private_static_ip_address:                "" => "<computed>"
  redis_configuration.#:                    "" => "1"
  redis_configuration.0.maxclients:         "" => "<computed>"
  redis_configuration.0.maxmemory_delta:    "" => "2"
  redis_configuration.0.maxmemory_policy:   "" => "volatile-lru"
  redis_configuration.0.maxmemory_reserved: "" => "2"
  resource_group_name:                      "" => "kt.201812.az-2516"
  secondary_access_key:                     "<sensitive>" => "<sensitive>"
  sku_name:                                 "" => "Standard"
  ssl_port:                                 "" => "<computed>"
  tags.%:                                   "" => "<computed>"
azurerm_redis_cache.redis: Still creating... (10s elapsed)
...snip...
azurerm_redis_cache.redis: Still creating... (20m10s elapsed)
azurerm_redis_cache.redis: Creation complete after 20m12s (ID: /subscriptions/00000000-0000-0000-0000-.../providers/Microsoft.Cache/Redis/teste)

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

id = /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/kt.201812.az-2516/providers/Microsoft.Cache/Redis/teste
-bash: popd: directory stack empty
```

```bash
[11:57:11] kt@snowbook:~/hashi/2018/gh-2018/az-2516$ rm terraform.tfstate
terraform.tfstate
[11:57:20] kt@snowbook:~/hashi/2018/gh-2018/az-2516$ terraform import azurerm_redis_cache.redis /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/kt.201812.az-2516/providers/Microsoft.Cache/Redis/teste
azurerm_redis_cache.redis: Importing from ID "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/kt.201812.az-2516/providers/Microsoft.Cache/Redis/teste"...
azurerm_redis_cache.redis: Import complete!
  Imported azurerm_redis_cache (ID: /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/kt.201812.az-2516/providers/Microsoft.Cache/Redis/teste)
azurerm_redis_cache.redis: Refreshing state... (ID: /subscriptions/00000000-0000-0000-0000-.../providers/Microsoft.Cache/Redis/teste)

Import successful!
terraform import azurerm_resource_group.test /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/kt.201812.az-2516
azurerm_resource_group.test: Importing from ID "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/kt.201812.az-2516"...
azurerm_resource_group.test: Import complete!
  Imported azurerm_resource_group (ID: /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/kt.201812.az-2516)
azurerm_resource_group.test: Refreshing state... (ID: /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/kt.201812.az-2516)

Import successful!

[12:09:19] kt@snowbook:~/hashi/2018/gh-2018/az-2516$
```

```bash
[12:09:19] kt@snowbook:~/hashi/2018/gh-2018/az-2516$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

azurerm_resource_group.test: Refreshing state... (ID: /subscriptions/c0a607b2-6372-4ef3-abdb-...b56ba/resourceGroups/kt.201812.az-2516)
azurerm_redis_cache.redis: Refreshing state... (ID: /subscriptions/c0a607b2-6372-4ef3-abdb-.../providers/Microsoft.Cache/Redis/teste)

------------------------------------------------------------------------

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
[12:10:43] kt@snowbook:~/hashi/2018/gh-2018/az-2516$
```

As this an issue with azure I don't feel we should work around it, nor make assumptions about what an empty imported value should be. If there was a non-default value there we would overwrite it. Therefore i am going to close your PR #2517.

Please let us know if this doesn't solve your issue

**Comment by katbyte** [comment] 2018-12-19 20:16
Hi @raphaelquati,

I'm sorry to hear you are having this problem. Thank you for the fix but I believe the root cause here is that the cluster was created with an older/preview version of the API where that property didn't exist. When this happens azure can cache a representation of the resource that lacks the properties of the current API, and when that happens errors like this can happen. Sometimes simply updating the tags via the portal will refresh the cache and fix these issues. I ran your config and didn't get any error:

```tf
[11:48:11] kt@snowbook:~/hashi/2018/gh-2018/az-2516$ cat main.tf
resource "azurerm_resource_group" "test" {
  name     = "kt.201812.az-2516"
  location = "westus"
}

resource "azurerm_redis_cache" "redis" {
    name = "teste"
    resource_group_name = "${azurerm_resource_group.test.name}"
    location = "${azurerm_resource_group.test.location}"
    enable_non_ssl_port = false
    capacity = 0
    family = "C"
    sku_name = "Standard"
    redis_configuration  {
        maxmemory_policy = "volatile-lru"
        maxmemory_delta = 2
        maxmemory_reserved = 2
    }
}

output "id" {
  value = "${azurerm_redis_cache.redis.id}"
}
```

```bash
[11:27:40] kt@snowbook:~/hashi/2018/gh-2018/az-2516$ myazure-buildrun
~/hashi/2018/gh-2018/az-2516 ~/hashi/2018/gh-2018/az-2516
==> Fixing source code with gofmt...
gofmt -s -w ./azurerm
==> Checking that code complies with gofmt requirements...
go install
~/hashi/2018/gh-2018/az-2516

Initializing provider plugins...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
azurerm_resource_group.test: Refreshing state... (ID: /subscriptions/00000000-0000-0000-0000-...b56ba/resourceGroups/kt.201812.az-2516)
azurerm_redis_cache.redis: Creating...
  capacity:                                 "" => "0"
  enable_non_ssl_port:                      "" => "false"
  family:                                   "" => "C"
  hostname:                                 "" => "<computed>"
  location:                                 "" => "westus"
  name:                                     "" => "teste"
  port:                                     "" => "<computed>"
  primary_access_key:                       "<sensitive>" => "<sensitive>"
  private_static_ip_address:                "" => "<computed>"
  redis_configuration.#:                    "" => "1"
  redis_configuration.0.maxclients:         "" => "<computed>"
  redis_configuration.0.maxmemory_delta:    "" => "2"
  redis_configuration.0.maxmemory_policy:   "" => "volatile-lru"
  redis_configuration.0.maxmemory_reserved: "" => "2"
  resource_group_name:                      "" => "kt.201812.az-2516"
  secondary_access_key:                     "<sensitive>" => "<sensitive>"
  sku_name:                                 "" => "Standard"
  ssl_port:                                 "" => "<computed>"
  tags.%:                                   "" => "<computed>"
azurerm_redis_cache.redis: Still creating... (10s elapsed)
...snip...
azurerm_redis_cache.redis: Still creating... (20m10s elapsed)
azurerm_redis_cache.redis: Creation complete after 20m12s (ID: /subscriptions/00000000-0000-0000-0000-.../providers/Microsoft.Cache/Redis/teste)

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

id = /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/kt.201812.az-2516/providers/Microsoft.Cache/Redis/teste
-bash: popd: directory stack empty
```

```bash
[11:57:11] kt@snowbook:~/hashi/2018/gh-2018/az-2516$ rm terraform.tfstate
terraform.tfstate
[11:57:20] kt@snowbook:~/hashi/2018/gh-2018/az-2516$ terraform import azurerm_redis_cache.redis /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/kt.201812.az-2516/providers/Microsoft.Cache/Redis/teste
azurerm_redis_cache.redis: Importing from ID "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/kt.201812.az-2516/providers/Microsoft.Cache/Redis/teste"...
azurerm_redis_cache.redis: Import complete!
  Imported azurerm_redis_cache (ID: /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/kt.201812.az-2516/providers/Microsoft.Cache/Redis/teste)
azurerm_redis_cache.redis: Refreshing state... (ID: /subscriptions/00000000-0000-0000-0000-.../providers/Microsoft.Cache/Redis/teste)

Import successful!
terraform import azurerm_resource_group.test /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/kt.201812.az-2516
azurerm_resource_group.test: Importing from ID "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/kt.201812.az-2516"...
azurerm_resource_group.test: Import complete!
  Imported azurerm_resource_group (ID: /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/kt.201812.az-2516)
azurerm_resource_group.test: Refreshing state... (ID: /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/kt.201812.az-2516)

Import successful!

[12:09:19] kt@snowbook:~/hashi/2018/gh-2018/az-2516$
```

```bash
[12:09:19] kt@snowbook:~/hashi/2018/gh-2018/az-2516$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

azurerm_resource_group.test: Refreshing state... (ID: /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/kt.201812.az-2516)
azurerm_redis_cache.redis: Refreshing state... (ID: /subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Cache/Redis/teste)

------------------------------------------------------------------------

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
[12:10:43] kt@snowbook:~/hashi/2018/gh-2018/az-2516$
```

As this an issue with azure I don't feel we should work around it, nor make assumptions about what an empty imported value should be. If there was a non-default value there we would overwrite it. Therefore i am going to close your PR #2517.

Please let us know if this doesn't solve your issue

**Comment by raphaelquati** [comment] 2018-12-20 03:11
No. Not resolved. Redis was created using portal.azure, not API. I'm trying to import my resources to terraform.

**Comment by raphaelquati** [comment] 2018-12-20 03:21
>  If there was a non-default value there we would overwrite it.

And as I wrote before, Terraform cannot overwrite the value, because Azure rejects the update (screenshot above)

**Comment by raphaelquati** [comment] 2018-12-20 03:33
- Via portal, change maxmemory_policy to any value
- Save 
- Change the value back to "volatile_lru"
- terraform refresh

The value is present!!!

![image](https://user-images.githubusercontent.com/815086/50262094-8f264980-03f6-11e9-887d-69cba57111e6.png)

**BUT** 

- Via portal, create a new Redis (basic)
- terraform import

**_value is empty_**!

![image](https://user-images.githubusercontent.com/815086/50262191-0cea5500-03f7-11e9-8568-2fcdb8b4410d.png)

**Comment by favoretti** [comment] 2021-08-18 13:59
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.

**Closed by favoretti** 2021-08-18 13:59 UTC
Labels: question, service/redis
