### ISSUE TITLE
azurerm_cosmosdb_account -> default_identity_type is not updated and db is updated with every next run

### ISSUE THREAD

**Issue by Radamonas** [hashicorp/terraform-provider-azurerm#14630] opened 2021-12-15 13:28 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

cli 1.1.0
azurerm 2.88.1

### Affected Resource(s)

* `azurerm_cosmosdb_account`

### Terraform Configuration Files

```
resource "azurerm_cosmosdb_account" "acc" {
  name                                 = lower(var.cosmosdb_account_name)
  location                              = var.location
  resource_group_name       = azurerm_resource_group.rg.name
  offer_type                          = var.cosmosdb_account_offer_type
  kind                                    = var.cosmosdb_account_kind
  enable_automatic_failover = true

  consistency_policy {
    consistency_level = var.cosmosdb_account_consistency_policy
  }

  default_identity_type = "FirstPartyIdentity"

  geo_location {
    location              = var.location
    failover_priority  = 0
    zone_redundant = var.cosmosdb_zone_redundant
  }
}
```
### Expected Behaviour

Expecting that after the second run the plan step and apply steps will find no changes.

### Actual Behaviour

Rerun the same configuration identifies differences.

```
  # azurerm_cosmosdb_account.acc will be updated in-place
  ~ resource "azurerm_cosmosdb_account" "acc" {
      + default_identity_type                 = "FirstPartyIdentity"
```

### Steps to Reproduce

1. `terraform plan`
1. `terraform apply`

* #0000

**Comment by lonegunmanb** [comment] 2021-12-15 14:20
Hi @Radamonas , I've tried the following code under terraform-provider-azurerm 2.89.0:

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "rg" {
  name     = "zjhe-f14630"
  location = "eastus"
}

resource "random_integer" "ri" {
  min = 10000
  max = 99999
}

resource "azurerm_cosmosdb_account" "db" {
  name                = "zjhe-cosmos-db-${random_integer.ri.result}"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  offer_type          = "Standard"
  kind                = "MongoDB"

  enable_automatic_failover = true

  capabilities {
    name = "EnableAggregationPipeline"
  }

  capabilities {
    name = "mongoEnableDocLevelTTL"
  }

  capabilities {
    name = "MongoDBv3.4"
  }

  capabilities {
    name = "EnableMongo"
  }

  consistency_policy {
    consistency_level       = "BoundedStaleness"
    max_interval_in_seconds = 300
    max_staleness_prefix    = 100000
  }

  default_identity_type = "FirstPartyIdentity"
  geo_location {
    location              = "eastus"
    failover_priority  = 0
  }
}
```

After `terraform apply -auto-approve`, I executed `terraform plan`, and plan output no change:

```powershell
> terraform plan
random_integer.ri: Refreshing state... [id=70463]
azurerm_resource_group.rg: Refreshing state... [id=/subscriptions/#########/resourceGroups/zjhe-f14630]
azurerm_cosmosdb_account.db: Refreshing state... [id=/subscriptions/#########/resourceGroups/zjhe-f14630/providers/Microsoft.
DocumentDB/databaseAccounts/zjhe-cosmos-db-70463]

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # azurerm_cosmosdb_account.db has been changed
  ~ resource "azurerm_cosmosdb_account" "db" {
        id                                    = "/subscriptions/#########/resourceGroups/zjhe-f14630/providers/Microsoft.Docu
mentDB/databaseAccounts/zjhe-cosmos-db-70463"
        name                                  = "zjhe-cosmos-db-70463"
      + network_acl_bypass_ids                = []
      + tags                                  = {}
        # (27 unchanged attributes hidden)





        # (8 unchanged blocks hidden)
    }
  # azurerm_resource_group.rg has been changed
  ~ resource "azurerm_resource_group" "rg" {
        id       = "/subscriptions/#########/resourceGroups/zjhe-f14630"
        name     = "zjhe-f14630"
      + tags     = {}
        # (1 unchanged attribute hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include  
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── 

No changes. Your infrastructure matches the configuration.

Your configuration already matches the changes detected above. If you'd like to update the Terraform state to match, create and apply a refresh-only    
plan:
  terraform apply -refresh-only
```

Have I missed something? Or would you please provide a minimum sample code that can reproduce this issue? Thanks!

**Comment by Radamonas** [comment] 2021-12-15 14:27
Maybe the main difference that db account was created with the older azurerm version and now we just bumped up the version.

**Comment by lonegunmanb** [comment] 2021-12-15 14:58
Hi @Radamonas I'd like to try a fix if I could get a minimum code with procedure that could reproduce this issue, would you help me with that? Thanks!

**Comment by Radamonas** [comment] 2021-12-15 15:58
@lonegunmanb 

I did some test. Amended state file and changed manualy:
```
"default_identity_type": "FirstPartyIdentity",
```

The plan identified that the change was made:
```
Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # azurerm_cosmosdb_account.acc has changed
  ~ resource "azurerm_cosmosdb_account" "acc" {
      - default_identity_type                 = "FirstPartyIdentity" -> null
        id                                    = "/subscriptions...
[...]
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # azurerm_cosmosdb_account.acc will be updated in-place
  ~ resource "azurerm_cosmosdb_account" "acc" {
      + default_identity_type                 = "FirstPartyIdentity"
        id                                    = "/subscriptions/
```
I have more envs with cosmos, so few of the acting this way, while another one haven't returned this part in plan. I need to check what is the difference between those env Cosmosdb state files.

Could you suggest what could be provided for your investigation?

**Comment by Radamonas** [comment] 2021-12-15 16:06
Changing to the latest version 2.89.0 hasn't helped in this case.

**Comment by lonegunmanb** [comment] 2021-12-16 02:32
Hi @Radamonas , I think the reason that Terraform reverted your `default_identity_type` back to "" was it might be empty on service side, would you please check it by azure cli tools [command](https://docs.microsoft.com/en-us/cli/azure/cosmosdb?view=azure-cli-latest#az_cosmosdb_show)? Thanks!

**Comment by Radamonas** [comment] 2021-12-16 07:26
@lonegunmanb 
I executed the az command and got this [output in GIST](https://gist.github.com/Radamonas/9182dafac4e276f3635d4761dd52a9c3)

**Comment by lonegunmanb** [comment] 2021-12-16 07:44
Hi @Radamonas , there's no `default_identity_type` in the response, means that it's null or unset on service side, I now recall a similar issue #14439, which also related to `default_identity_type`. We've tried create cosmosdb account via Terraform and Azure CLI, both without assign `default_identity_type`, and they all assigned a valid default value. We suspect that these kind of cosmosdb accounts without this `default_identity_type` were created via ARM template, but I haven't tested. Is your cosmosdb account created by Terraform or ARM template?

**Comment by Radamonas** [comment] 2021-12-16 07:58
@lonegunmanb our infrastructure is created and maintained only by terraform, however, as you can see, it was created quite long time ago, so this could be related to that.

Is there a way to manually set this value on the instance?

**Comment by lonegunmanb** [comment] 2021-12-16 08:06
> @lonegunmanb our infrastructure is created and maintained only by terraform, however, as you can see, it was created quite long time ago, so this could be related to that.
> 
> Is there a way to manually set this value on the instance?

I would recommend do a test first, especially if this cosmosdb stored production data, we need safety first. If I were you, I would try create a cosmosdb account with no `default_identity_type` by using old version plugin, then using az cli tool to update it, then check if all data is safe. 

We can use [az cli command](https://docs.microsoft.com/en-us/cli/azure/cosmosdb?view=azure-cli-latest#az_cosmosdb_update) to update account's default identity to default value, I think it will solve your problem, but again, a test is strongly recommended, only this cosmosdb is for test only.

**Comment by lonegunmanb** [comment] 2021-12-16 08:09
@Radamonas another tip, I've checked code, this `default_identty_type` was introduced into plugin in 2021/11/26, so any version prior this time should create account without it. Please do a test to verify all data will be safe, and good luck!

**Comment by Radamonas** [comment] 2021-12-16 11:57
@lonegunmanb ```az cosmosdb update``` isn't changing the situation, I've tested several times, even I defined ```az cosmosdb update -n cosmosacc -g RG --default-identity FirstPartyIdentity``` and I got default identity node in response for ```az cosmosdb show --name cosmosacc --resource-group RG```, the node remains empty string:

```
  ...
  "cors": [],
  "createMode": null,
  "databaseAccountOfferType": "Standard",
  "defaultIdentity": "",
  ...
```

Please also note, that: ```Argument '--default-identity' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus```

**Comment by lonegunmanb** [comment] 2021-12-16 12:02
Ok @Radamonas , I'll write a test to verify that if I used old plugin create one account and use new plugin to update it could fix it.

**Comment by lonegunmanb** [comment] 2021-12-16 12:20
@Radamonas unfortunately I've tried the old version(2.81.0, which do not support `default_identity_type` yet) and even this old version plugin created an account with default identity valued "FirstPartyIdentity". As you've tried azure cli and it cannot update this property either, I think it should be a service side bug. May I suggest you fire an Azure support ticket for this issue, because on my side I cannot create this kind of cosmosdb account without this property anymore. Meanwhile I'll ask the service team, but I think a support ticket may get response faster than I can.

**Comment by tombuildsstuff** [comment] 2021-12-16 13:43
@lonegunmanb whilst this is a server-side issue, unfortunately this behaviour is expected in the Azure API - so opening a support ticket won't solve this.

In short: resources are created at a given point in time in the Azure API - when new functionality is added after a resource has been created - the Azure API returns `null` for those new fields. However when creating a new resource on an older API version after the new functionality is enabled, the default value will be returned. Whilst the API design isn't great, unfortunately that's consistent across many Azure API's where there's an implied default value - as such we need to default those in the Read function within Terraform, which is the issue here.

Since this issue is being tracked in #14439, I'm going to close this in favour of that issue - but this'll need to be fixed by using the implied default value as the default value in the Read function, where the API doesn't return this value.

Thanks!

**Closed by tombuildsstuff** 2021-12-16 13:43 UTC
Labels: bug, service/cosmosdb

**Comment by lonegunmanb** [comment] 2021-12-16 14:01
@tombuildsstuff Thanks for the explanation, as for now the users cannot set this field to default value i. state file permanently due to this API behavior, do we need modify read function to set a default value when api return nil for this value? If so then I'd like to ask the honor to submit such a pull request.

**Comment by Socolin** [comment] 2021-12-21 19:13
Hello,

I still have a diff on cosmosdb with 2.90 that try to set  `default_identity_type                 = "FirstPartyIdentity"`

**Comment by fgarcia-cnb** [comment] 2022-01-12 23:46
same... on 2.91, still happening

**Comment by Philluxx** [comment] 2022-01-31 09:31
same... on 2.92

**Comment by Philluxx** [comment] 2022-01-31 09:35
in 2.92 also still happening
