### ISSUE TITLE
Azure backup Support for selective disk backup 

### ISSUE THREAD

**Issue by skoop22** [hashicorp/terraform-provider-azurerm#12840] opened 2021-08-04 09:24 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for selective disk backup.
https://docs.microsoft.com/en-us/azure/backup/selective-disk-backup-restore
https://docs.microsoft.com/en-us/azure/backup/backup-azure-arm-userestapi-backupazurevms#excluding-disks-in-azure-vm-backup
 

### New or Affected Resource(s)

* azurerm_backup_protected_vm

### Potential Terraform Configuration

```hcl
resource "azurerm_backup_protected_vm" "vm1" {
  resource_group_name = azurerm_resource_group.example.name
  recovery_vault_name = azurerm_recovery_services_vault.example.name
  source_vm_id        = azurerm_virtual_machine.example.id
  backup_policy_id    = azurerm_backup_policy_vm.example.id
  excluded_disks = [ list of lun id's  ]
}
```

### References

* #0000

**Comment by katbyte** [comment] 2024-12-16 19:47
duplicate of https://github.com/hashicorp/terraform-provider-azurerm/issues/13570

**Closed by katbyte** 2024-12-16 19:47 UTC
Labels: enhancement, service/backup
