### ISSUE TITLE
Terraform Trying To Create A Key Vault Multiple Times After Successfully Creating On Previous Run. PLEASE STOP CLOSING !!!

### ISSUE THREAD

**Issue by jfe7** [hashicorp/terraform-provider-azurerm#14808] opened 2022-01-05 13:23 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

Terraform v1.1.2
AzureRM v2.90.0

### Terraform Configuration Files

```hcl
resource "azurerm_key_vault" "example_kv" {
  name                = "example-kv"
  resource_group_name = azurerm_resource_group.example_rg.name
  location            = azurerm_resource_group.example_rg.location
  tenant_id           = data.azurerm_client_config.current.tenant_id

  sku_name = "standard"

  enabled_for_deployment          = true
  enabled_for_disk_encryption     = false
  enabled_for_template_deployment = false

  network_acls {
    default_action = "Deny"
    bypass         = "AzureServices"
  }
provider = azurerm
}

resource "azurerm_key_vault_access_policy" "example_ap" {
  key_vault_id = azurerm_key_vault.example_kv.id
  tenant_id    = data.azurerm_client_config.current.tenant_id
  object_id    = data.azurerm_client_config.current.object_id

  key_permissions         = ["Get", "List"]
  certificate_permissions = ["Get", "List"]
  secret_permissions      = ["Get", "List"]
  provider = azurerm
}
```

### Expected Behaviour

Terraform creates the Key Vault and Key Vault Policy successfully and on the next Terraform run, Terraform does not prompt that the resource has been deleted.

### Actual Behaviour
PLEASE READ FULLY THIS IS NOT A CONFIGURATION ISSUE.

Run #1: Terraform Successfully creates the Key Vault & Key Vault Access Policy, this is visible via the Portal, everything looks as it should do.

Run #2: Terraform reports that the Key Vault and Key Vault Access Policy have been deleted outside of Terraform, so Terraform wants to create the resources again. The Key Vault and Key Vault Access Policy HAVE NOT been deleted, this is clearly visible via the Portal. Terraform Apply reports the resources already exist and must be imported (as expected).

Resources Created Successfully:
```hcl
azurerm_key_vault.example_kv: Creating...
azurerm_key_vault.example_kv: Still creating... [10s elapsed]
azurerm_key_vault.example_kv: Still creating... [20s elapsed]
azurerm_key_vault.example_kv: Still creating... [30s elapsed]
azurerm_key_vault.example_kv: Still creating... [40s elapsed]
azurerm_key_vault.example_kv: Still creating... [50s elapsed]
azurerm_key_vault.example_kv: Still creating... [1m0s elapsed]
azurerm_key_vault.example_kv: Still creating... [1m10s elapsed]
azurerm_key_vault.example_kv: Still creating... [1m20s elapsed]
azurerm_key_vault.example_kv: Still creating... [1m30s elapsed]
azurerm_key_vault.example_kv: Still creating... [1m40s elapsed]
azurerm_key_vault.example_kv: Still creating... [1m50s elapsed]
azurerm_key_vault.example_kv: Still creating... [2m0s elapsed]
azurerm_key_vault.example_kv: Creation complete after 2m2s [id=/subscriptions/{SUBID}/resourceGroups/example-rg/providers/Microsoft.KeyVault/vaults/example_kv]
azurerm_key_vault_access_policy.example_ap: Creating...
azurerm_key_vault_access_policy.example_ap: Creation complete after 9s [id=/subscriptions/{SUBID}/resourceGroups/example-rg/providers/Microsoft.KeyVault/vaults/example_kv/objectId/{OBJECT_ID}]
```

Next RUN:

```hcl
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # azurerm_key_vault.example_kv has been deleted
  - resource "azurerm_key_vault" "example_kv" {
      - access_policy                   = [] -> null
      - enable_rbac_authorization       = false -> null
      - enabled_for_deployment          = true -> null
      - enabled_for_disk_encryption     = false -> null
      - enabled_for_template_deployment = false -> null
      - id                              = "/subscriptions/{SUBID}/resourceGroups/example-rg/providers/Microsoft.KeyVault/vaults/example-kv" -> null
      - location                        = "uksouth" -> null
      - name                            = "example-kv" -> null
      - purge_protection_enabled        = false -> null
      - resource_group_name             = "example-rg" -> null
      - sku_name                        = "standard" -> null
      - soft_delete_enabled             = true -> null
      - soft_delete_retention_days      = 90 -> null
      - tenant_id                       = "{TENANTID}" -> null
      - vault_uri                       = "https://example-kv.vault.azure.net/" -> null

      - network_acls {
          - bypass         = "AzureServices" -> null
          - default_action = "Deny" -> null
        }
    }

  # azurerm_key_vault_access_policy.example_ap has been deleted
  - resource "azurerm_key_vault_access_policy" "example_ap" {
      - certificate_permissions = [
          - "Get",
          - "List",
        ] -> null
      - id                      = "/subscriptions/{SUBID}/resourceGroups/example-rg/providers/Microsoft.KeyVault/vaults/example-kv/objectId/{OBJECT_ID}" -> null
      - key_permissions         = [
          - "Get",
          - "List",
        ] -> null
      - key_vault_id            = "/subscriptions/{SUBID}/resourceGroups/example-rg/providers/Microsoft.KeyVault/vaults/example-kv" -> null
      - object_id               = "{OBJECT_ID}" -> null
      - secret_permissions      = [
          - "Get",
          - "List",
        ] -> null
      - tenant_id               = "{TENANTID}" -> null
    }
```

### Steps to Reproduce

Terraform Plan
Terraform Apply

### Important Factoids

This is definitely a bug in the provider or something to do with the Azure API & Key Vault, all other resources work as expected.

I know this is a bug because I just run Terraform Plan 3 times in a row straight after creating the Key Vault. I got different results each time, for example, I just created a Key Vault, run the configuration again with the below results:

1st Run: Key Vault is recognised, Terraform Reports no changes to infrastructure.

2nd Run: Terraform Reports the Key Vault does not exist and wants to create it (Key Vault does exist, proven by checking Portal).

3rd Run: Terraform Reports the Key Vault does not exist and wants to create it (Key Vault does exist, proven by checking Portal).

From the DEBUG output I can see what the issue is, when Terraform is checking the Key Vault with GET, Terraform is randomly picking the subscription id of one of two providers in my configuration, even though I have explicitly stated the provider to use in the resource block as shown above! I shouldn't even need to do this because Terraform should use the provider block without an ALIAS by default anyway.

* #0000

**Comment by jfe7** [comment] 2022-01-05 14:26
More Information To Add:

If I target the Key Vault using **terraform plan -target="azurerm_key_vault.example_kv"**, Terraform recognises the resource and reports 'No Changes' every time, if I then remove the target, Terraform reports the Key Vault does not exist, again taking a look in the Debug logs, terraform picks up the subscription Id from the provider with an alias!

**Comment by tombuildsstuff** [comment] 2022-01-05 14:33
Duplicate of #14674 - as mentioned in that issue, unfortunately this is a configuration issue - not a bug in the Provider.

**Closed by tombuildsstuff** 2022-01-05 14:33 UTC

**Comment by jfe7** [comment] 2022-01-05 14:47
> Duplicate of #14674 - as mentioned in that issue, unfortunately this is a configuration issue - not a bug in the Provider.

Sorry can you please tell me how this is a configuration issue in my code? I have used the exact same code on multiple projects with no issues before in earlier versions of the Provider & Terraform?

I have provided enough information on what is causing the issue and all of the debugging steps I have taken, I am struggling to see how this isn't a bug, could you please provide more information on how this is a configuration issue?

**Comment by jfe7** [comment] 2022-01-05 15:18
I am being presented with different results from Terraform when running Terraform Plan 4 times in the space of 2 minutes, I believe this is a bug...

1st Run: Terraform Plan reports No Changes Required
2nd Run: Terraform Plan wants to create Key Vault again. I do not run Terraform Apply.
3rd Run: Terraform Plan wants to create Key Vault again. I do not run Terraform Apply.
4th Run: Terraform Plan reports No Changes Required.

Looking into Debug logs, the two runs which report no changes required are using the correct subscription in the GET command, the two that fail are using the incorrect subscription in the GET command, I have not changed anything configuration during the 4 runs.

**Comment by tombuildsstuff** [comment] 2022-01-05 15:21
@jfe7 unfortunately the nature of these configuration issues is that they're highly specific to your environment, for example if you're using the Azure CLI to authenticate and the default subscription is changed after (or even: during!) a `terraform apply` then these resources will become untracked, or if you're reusing build agents between different applies where a Subscription ID is being set in different configurations/runs.

A lot of this depends heavily on your setup - the open-ended nature of that situation means that we are unable to offer one-on-one support for configuration issues in this forum.

If you're a Terraform Enterprise customer, please reach out to our Enterprise Support team so they can dig in further. On GitHub, we are unable to to dig into individual configuration issues as this forum is focused on bugs and feature enhancements in the Provider, so as mentioned previously we redirect folks to [the Community Discuss Forum](https://discuss.hashicorp.com) for these types of issues where someone should be able to assist further otherwise.

Thanks!

**Comment by jfe7** [comment] 2022-01-05 15:29
> @jfe7 unfortunately the nature of these configuration issues is that they're highly specific to your environment, for example if you're using the Azure CLI to authenticate and the default subscription is changed after (or even: during!) a `terraform apply` then these resources will become untracked, or if you're reusing build agents between different applies where a Subscription ID is being set in different configurations/runs.
> 
> A lot of this depends heavily on your setup - the open-ended nature of that situation means that we are unable to offer one-on-one support for configuration issues in this forum.
> 
> If you're a Terraform Enterprise customer, please reach out to our Enterprise Support team so they can dig in further. On GitHub, we are unable to to dig into individual configuration issues as this forum is focused on bugs and feature enhancements in the Provider, so as mentioned previously we redirect folks to [the Community Discuss Forum](https://discuss.hashicorp.com) for these types of issues where someone should be able to assist further otherwise.
> 
> Thanks!

I am using environment variables to authenticate with a Service Principal from my local machine, I only provide ARM_TENANT_ID, ARM_CLIENT_ID, ARM_CLIENT_SECRET, I face the same issue on build servers as-well using the same method, I provide the subscription id's in the provider blocks.

Also, all other resources in my configuration are completely fine, for some reason it is only the resources related to Key Vault.

**Comment by brianwentz** [comment] 2022-01-12 14:52
I have the exact same problem.

**Comment by jfe7** [comment] 2022-01-12 14:58
> I have the exact same problem.

Yes, this is definitely a bug, do not see how it isn't. 

Anyway I found a workaround finally...

In my case I had two providers, one with no alias, another with an alias, I was creating a Key Vault with the provider without an alias (so the default provider).

What I had to do is create ANOTHER provider with an alias, this new provider still had the same subscription id as my default provider, then for all key vault resources, I added the provider input with the new provider.alias I created.

This fixed my issue.

**Comment by SavaDragos** [comment] 2022-01-12 15:16
Terraform 1.0.5 and AzureRM 2.85.0+ Version
Affected Resource(s)
*azurerm_key_vault

Terraform Configuration Files
resource "azurerm_key_vault" "x_key_vault" {
name = some_value
location = azurerm_resource_group.x_rg.location
resource_group_name = azurerm_resource_group.x_rg.name
tenant_id = data.azurerm_client_config.current.tenant_id

enabled_for_deployment = true
enabled_for_template_deployment = true
enable_rbac_authorization = true

sku_name = "standard"
}

data "azurerm_client_config" "current" {
}

and have more providers defined

Expected Behaviour
Create a keyvault for default azurerm provider that in subsequent 'pla' 'apply' 'destroy' is recognized

Actual Behaviour
This is intermittent sometimes it can get it sometimes it might not be able to do it.
If the keyvault is not there it will create it with the default provider (in the correct subscription).

But sometimes after the keyvault was created it will do this (other times it works):
azurerm_key_vault.x_key_vault: Refreshing state... [id=/subscriptions/aaaaaaaa-aaaa-aaaa-aaaaaa-aaaaaa/resourceGroups/x-rg/providers/Microsoft.KeyVault/vaults/namekeyvault]

...

retrieving Vault: (Name "namekeyvault" / Resource Group "x-rg"): keyvault.VaultsClient#Get: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client 'xxxxx-xxx-xx-xxxx' with object id 'xxxxx-xxx-xx-xxxx' does not have authorization to perform action 'Microsoft.KeyVault/vaults/read' over scope '/subscriptions/bbbbbbb-bbbb-bbbb-bbbbbb-bbbbbbbbbb/resourceGroups/x-rg_name/providers/Microsoft.KeyVault/vaults/namekeyvault' or the scope is invalid. If access was recently granted, please refresh your credentials."

It tries to read the keyvault as it belong to another subscription, even if it says it was wanting to refresh it from the correct subscription

Note: this happens sometimes.

**Comment by tombuildsstuff** [comment] 2022-01-12 17:10
Hi,

This forum is for Bugs and Feature Requests in the Azure Provider - unfortunately we're unable to assist with individual Configuration issues (as referred to above) in this forum - however please feel free to open an issue on [the Community Discuss forum](https://discuss.hashicorp.com) and someone should be able to take a look.

Thanks!
