### ISSUE TITLE
Reuploading changed source file does not work in `azurerm_storage_share_file`

### ISSUE THREAD

**Issue by pun-ky** [hashicorp/terraform-provider-azurerm#14591] opened 2021-12-13 11:58 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform 1.1.0
AzureRM Provider 2.88.1

### Affected Resource(s)

* `azurerm_storage_share_file`

### Terraform Configuration Files

```hcl
resource "azurerm_storage_share_file" "config_zip" {
  name = "config-zip"
  storage_share_id = /* ... */
  source = local.zip_path
  content_md5 = filemd5(local.zip_path)
}

```

### Expected Behaviour

Reuploading changed source file does not lead to 0 B / broken file uploaded and visible in Azure Portal.

![image](https://user-images.githubusercontent.com/10673561/145807768-84824386-da4e-455a-9bf5-ac6a7beb588b.png)

### Actual Behaviour

The source file is correctly uploaded only the first time. After changing file then rerunning TF apply command, TF ends successfully and sees content_md5 updated  however file actually uploaded to Azure has 0B.

### Other issues spotted

1) manual deletion of share file - leads to apply error instead of just removing it and creating again as it usually works for other resources:

```
│ Error: retrieving Storage Share "config" (File Share "xx-kp-config" / Account "yyy" / Resource Group "zzz"): directories.Client#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="The specified resource does not exist.\nRequestId:34cc098d-901a-009a-1e15-f00e14000000\nTime:2021-12-13T11:35:53.2587936Z"
│ 
```

2) double slashes in URL when no "path" parameter specified

![image](https://user-images.githubusercontent.com/10673561/145807573-42cef3ad-0da1-4fa2-bf11-4a8d6a351019.png)

**Comment by tombuildsstuff** [comment] 2021-12-13 12:18
hi @pun-ky 

Thanks for opening this issue.

Taking a look through this appears to be a duplicate of #11507 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #11507 for updates?

Thanks!

**Closed by tombuildsstuff** 2021-12-13 12:18 UTC

**Comment by pun-ky** [comment] 2021-12-13 13:25
yes, I tried to find it but somehow without effect ;) even so... how about other issues/improvements mentioned in the bottom?
