### ISSUE TITLE
Support for the option to decalre the default Azure Resource Group to use

### ISSUE THREAD

**Issue by shaked-develeap** [hashicorp/terraform-provider-azurerm#20147] opened 2023-01-21 20:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Its pretty redundant to declare in each resource what recourse_group you want it to be created under, similar to AWS's default region annotation.
I believe that there should be an option to declare the default RG to be used with a certain azurerm provider.
Two ways to work with the feature are:
- Overriding the default used with the provider by setting the `resource_group` parameter under a certain resource.
- Creating additional providers of azurerm with aliases for additional resource groups to use. 

### New or Affected Resource(s)/Data Source(s)

provider "azurerm"

### Potential Terraform Configuration

Might look something like this:

```hcl
provider "azurerm" {
  resource_group = '{main_resource_group}'
}

provider "azurerm" {
  alias = "my_second_resource_group"
  resource_group = '{additional_resource_group}'
}
```

**Comment by tombuildsstuff** [comment] 2023-01-26 09:50
hi @shaked-develeap 

Thanks for opening this issue.

Taking a look through here this appears to be a duplicate of #13776 - specifically [this comment explains the current status of a default `resource_group_name` field](https://github.com/hashicorp/terraform-provider-azurerm/issues/13776#issuecomment-1063187149) - as such I'm going to close this in favour of #13776, would you mind subscribing to that issue for updates?

Thanks!

**Closed by tombuildsstuff** 2023-01-26 09:50 UTC
Labels: duplicate

**Comment by shaked-tech** [comment] 2023-01-31 14:03
Hi @tombuildsstuff ,
Thanks a bunch for the replay, 
You are correct thats exatly what I proposed,
will keep track at it 🙏
