### ISSUE TITLE
Terraform azurerm 4.0.1 is expecting  docker_bridge_cidr for AKS module.

### ISSUE THREAD

**Issue by imran21** [hashicorp/terraform-provider-azurerm#27187] opened 2024-08-24 11:26 UTC
### Terraform azurerm 4.0.1 is expecting  docker_bridge_cidr for AKS module.

* When I am trying to deploy the Azure AKS through terraform azurerm 4.0.1 it is expecting  ***docker_bridge_cidr*** Actually it should not.
* When I am providing the  ***docker_bridge_cidr*** and it saying that It is not expecting to be there. 
Please refer the screenshot below.

### Terraform (and AzureRM Provider) Version

* Terraform Core version: [v1.9.5]
* AzureRM Provider version: [4.0.1]

### Affected Resource(s)/Data Source(s)
* Azure Kubernetes Services (AKS)

### Terraform Configuration Files

```hcl
module "aks" {
  source = "./modules/k8s-cluster"

  subscription_id = "1234567890"
  cluster_name        = "xyz-app-cluster"
  location            = USEAST
  resource_group_name =xyz
  dns_prefix          = "${module.dns.resource_group_id.name}"
  sku_tier            = "Free"
  kubernetes_version  = "1.27.9"
  
  node_count          = 2
  node_pool_name      = "default"
  node_vm_size        = "Standard_D2s_v3" #Standard_DS2_v2"
  network_plugin      = "azure"
  network_policy      = "azure"
  load_balancer_sku   = "standard"
  vnet_subnet_id      = tolist(module.vnet.vnet_outputs.subnet)[0].id
  private_cluster_enabled = "false"

  service_cidr        = "17.0.0.0/11"  # Adjust the Service CIDR to a non-overlapping range
  dns_service_ip      = "17.0.0.10"
  docker_bridge_cidr  = "172.17.0.1/11"



  tags = {
    environment = "Dev"
    owner       = "mohamedimran21"
    creator     = "t33f1"
  }
}

output "k8s_cluster_outputs" {
  value = module.aks.k8s_cluster_outputs
  sensitive = true

}
```
```hcl
resource "azurerm_kubernetes_cluster" "aks_cluster" {
  name                = var.cluster_name
  location            = var.location
  resource_group_name = var.resource_group_name
  dns_prefix          = var.dns_prefix
  sku_tier            = var.sku_tier
  private_cluster_enabled = var.private_cluster_enabled
  kubernetes_version  = var.kubernetes_version
  

  default_node_pool {
    name            = var.node_pool_name
    node_count      = var.node_count
    vm_size         = var.node_vm_size
    vnet_subnet_id  = var.vnet_subnet_id
    
    
  tags = var.tags
  }

  identity {
    type = "SystemAssigned"
  }
 
  network_profile {
    network_plugin = var.network_plugin
    network_policy = var.network_policy
    load_balancer_sku = var.load_balancer_sku

    service_cidr   = var.service_cidr  # Adjust the Service CIDR to a non-overlapping range
    dns_service_ip = var.dns_service_ip
    docker_bridge_cidr = var.docker_bridge_cidr
    
  }


 tags = var.tags
}
```
### References
![image](https://github.com/user-attachments/assets/2880da24-e071-47dc-9f2b-0b5764864ae4)

![image](https://github.com/user-attachments/assets/b067b8e3-4101-48e6-856a-a9e74c6e5586)

**Comment by stephybun** [comment] 2024-08-26 05:18
Thanks for raising this issue @imran21.

The `docker_cidr_bridge` argument was removed in v4.0 of the provider since it is no longer supported by the AKS API. The module you're using needs to be updated to have the argument removed.

I'm going to close this issue since this is neither a feature request nor a bug but a configuration error.

**Closed by stephybun** 2024-08-26 05:18 UTC
Labels: v4.0-beta

**Comment by imran21** [comment] 2024-08-26 09:13
> Thanks for raising this issue @imran21.
> 
> The `docker_cidr_bridge` argument was removed in v4.0 of the provider since it is no longer supported by the AKS API. The module you're using needs to be updated to have the argument removed.
> 
> I'm going to close this issue since this is neither a feature request nor a bug but a configuration error.

Could you please study the topic once again clearly. I am using the latest Azurerm 4.0.1 only. Still I am getting the above mentioned error when using azurerm 4.0.1

**Comment by aristosvo** [comment] 2024-08-26 20:05
Hi @imran21 👋 

Please remove line `docker_bridge_cidr = var.docker_bridge_cidr` in the module, that might solve the issue. The issue is in the module, not the provider.

🚀
