### ISSUE TITLE
recover_soft_deleted_api_managements not supported in azurem 3.14

### ISSUE THREAD

**Issue by jb68** [hashicorp/terraform-provider-azurerm#17662] opened 2022-07-18 15:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.3

### AzureRM Provider Version

3.14

### Affected Resource(s)/Data Source(s)

azurem api_management

### Terraform Configuration Files

```hcl
provider "azurerm" {
.......
api_management {
      purge_soft_delete_on_destroy         = true
      # next attribute exists only on docs
      # https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/features-block#api_management
      recover_soft_deleted_api_managements = true
    }
}
```
```


### Debug Output/Panic Output

```shell
tf plan
╷
│ Error: Unsupported argument
│
│   on 000-providers.tf line 37, in provider "azurerm":
│   37:       recover_soft_deleted_api_management = true
│
│ An argument named "recover_soft_deleted_api_management" is not expected here.
╵
```
```


### Expected Behaviour

show the plan

### Actual Behaviour

```
terraform plan
╷
│ Error: Unsupported argument
│
│   on 000-providers.tf line 37, in provider "azurerm":
│   37:       recover_soft_deleted_api_management = true
│
│ An argument named "recover_soft_deleted_api_management" is not expected here.
╵
```

### Steps to Reproduce

terraform plan

### Important Factoids

_No response_

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/features-block#api_management

While you have this attribute in documentation it looks like is not supported.

**Comment by rcskosir** [comment] 2024-09-11 17:54
Thanks for opening this issue. Since time has passed and the variable has since changed, I am going to mark this issue closed as “can’t reproduce”. The latest documentation (v4.1.0) shows a new name for this variable - [recover_soft_deleted](https://registry.terraform.io/providers/hashicorp/azurerm/4.1.0/docs/guides/features-block). If you are able to upgrade and provide more information to help us reproduce this issue we may re-open this issue or open a new issue, thanks!

**Closed by rcskosir** 2024-09-11 17:54 UTC
Labels: service/api-management
