### ISSUE TITLE
Behaviour of azurerm_virtual_desktop_host_pool has changed, token no longer available 

### ISSUE THREAD

**Issue by istairbn** [hashicorp/terraform-provider-azurerm#14972] opened 2022-01-14 16:37 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Issue first occurred in Provider 2.91.0

### Affected Resource(s)

* azurerm_virtual_desktop_host_pool

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "avd-test"
  location = "West Europe"
}

resource "time_offset" "time" {
    offset_days = 7
}

resource "azurerm_virtual_desktop_host_pool" "example" {
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  name                     = "pooleddepthfirst"
  friendly_name            = "pooleddepthfirst"
  validate_environment     = true
  start_vm_on_connect      = true
  custom_rdp_properties    = "audiocapturemode:i:1;audiomode:i:0;"
  description              = "Acceptance Test: A pooled host pool - pooleddepthfirst"
  type                     = "Pooled"
  maximum_sessions_allowed = 50
  load_balancer_type       = "DepthFirst"

  registration_info {
      expiration_date = resource.time_offset.time.rfc3339
  }
}

provider azurerm {
    features {}
}

#The use of the below resource is to expose the value of the token (which is not correct)
resource "azurerm_virtual_desktop_workspace" "workspace" {
  name                = "workspace"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  friendly_name = azurerm_virtual_desktop_host_pool.example.registration_info[0].token
  description   = "A description of my workspace"
}

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=2.91.0"
    }
  }
}
# Changing this to 2.90.0 shows the expected behaviour
```

### Expected Behaviour

The value of azurerm_virtual_desktop_host_pool.example.registration_info[0].token should be a valid registration token. 

### Actual Behaviour

│   on main.tf line 38, in resource "azurerm_virtual_desktop_workspace" "workspace":
│   38:   friendly_name = azurerm_virtual_desktop_host_pool.example.registration_info[0].token
│     ├────────────────
│     │ azurerm_virtual_desktop_host_pool.example.registration_info is empty list of object
│
│ The given key does not identify an element in this collection value: the collection has no elements.

### Steps to Reproduce

1. `terraform apply` - the token is no longer accessible

Without the token, we can't add hosts to the hostpool.
### References

* I suspect this is the source of the issue - https://github.com/hashicorp/terraform-provider-azurerm/issues/14188

**Comment by simaotwx** [comment] 2022-01-26 13:40
It looks like the root cause of this is that the Azure API has a bug that returns `null` for `registration_info` instead of the actual registration info.

Looking at the requests in the trace log, this is what I can see:

```
PUT /subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.DesktopVirtualization/hostPools/<redacted>?api-version=2021-09-03-preview HTTP/1.1
Host: management.azure.com

{"location":"westeurope","properties":{"customRdpProperty":"audiocapturemode:i:1;audiomode:i:0;targetisaadjoined:i:1;","description":"","friendlyName":"","hostPoolType":"Pooled","loadBalancerType":"DepthFirst","maxSessionLimit":1,"preferredAppGroupType":"Desktop","registrationInfo":{"expirationTime":"2022-01-30T10:44:36Z","registrationTokenOperation":"Update"},"startVMOnConnect":true,"validationEnvironment":false},"tags":{}}
```
(shortened for brevity)

It responds with:

```
HTTP/2.0 201 Created

{...skipped...,"registrationInfo":{"expirationTime":"2022-01-30T10:44:36Z","token":"<redacted>","registrationTokenOperation":"Update"},...skipped...}
```

After that, a GET request happens:

```
GET /subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.DesktopVirtualization/hostPools/<redacted>?api-version=2021-09-03-preview HTTP/1.1
Host: management.azure.com
```

Reply:

```
HTTP/2.0 200 OK

{...skipped...,"registrationInfo":null,...skipped...}
```

As you can see, the registration info is missing and Terraform complains about it:

```
Provider "provider[\"registry.terraform.io/hashicorp/azurerm\"]" produced an unexpected new value for azurerm_virtual_desktop_host_pool.HostPool, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .description: was null, but now cty.StringVal("")
      - .friendly_name: was null, but now cty.StringVal("")
      - .personal_desktop_assignment_type: was null, but now cty.StringVal("")
      - .registration_info: block count changed from 1 to 0
```
It says `.registration_info: block count changed from 1 to 0` which proves that the API is the issue.

Trying the request in Postman yields the same result, even though the documentation has a different output:

```
{...,"registrationInfo":null,"...}
```

![image](https://user-images.githubusercontent.com/80681087/151172953-3e9719c7-bf16-4a96-80ea-d45d0bcb6120.png)

@tombuildsstuff I think we need to report this to Microsoft as it is an issue with the API, not the provider.

Related: #13793 #14134 https://github.com/hashicorp/terraform-provider-azurerm/commit/16ce39b6b394ec38d8585938b7c2b81c022a531e #14330

**Comment by Theragus** [comment] 2022-01-31 13:26
@simaotwx seems to have been fixed with https://github.com/hashicorp/terraform-provider-azurerm/pull/14659 ?

**Comment by simaotwx** [comment] 2022-01-31 13:48
> @simaotwx seems to have been fixed with #14659 ?

I think it's unrelated to this issue.

**Comment by acapodil** [comment] 2022-02-04 16:49
Thanks for shedding some light on this. Any update regarding when the API can get resolved? I am running into the exact same thing.  this was working fine for me, up until a week or so ago!

**Comment by rbnmk** [comment] 2022-02-08 12:52
While the opening post of this is related to a Terraform script, I have the same problem with deploying hostpools and generating the registrationToken using Bicep to immediatly join session hosts to the pool, which have worked previously (as a charm).

**Comment by antanof** [comment] 2022-02-15 10:19
Same issue, it's very problematic :
```bash
Error: Invalid index
│
│   on vm.tf line 25, in module "virtual-machine-wvd-adds":
│   25:   hostpool_token    = azurerm_virtual_desktop_host_pool.avd-hp.registration_info[0].token # local.registration_token
│     ├────────────────
│     │ azurerm_virtual_desktop_host_pool.avd-hp.registration_info is empty list of object
│
│ The given key does not identify an element in this collection value: the collection has no elements.
```

**Closed** 2022-02-16 10:15 UTC
Labels: bug, service/virtual-desktops
