### ISSUE TITLE
Support for static IP configuration in azurerm_private_endpoint

### ISSUE THREAD

**Issue by t3mi** [hashicorp/terraform-provider-azurerm#13061] opened 2021-08-19 10:10 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Hi,

Since Private Link is crucial for accessing Azure PaaS Service from an on-premise environment, I would like to have the ability to set the IP assignment to "static" and have the ability to specify the IP directly.

### New or Affected Resource(s)

* azurerm_private_endpoint

### Potential Terraform Configuration

```hcl
resource "azurerm_private_endpoint" "my-sa-pe" {
  name                = "${replace(var.my_name,"-","")}_pe"
  location            = data.azurerm_resource_group.my-rg.location
  resource_group_name = data.azurerm_resource_group.my-rg.name

  private_service_connection {
    name = "${replace(var.my_name,"-","")}_psc"
    is_manual_connection = false
    private_connection_resource_id = azurerm_storage_account.my-sa.id
    subresource_names = ["blob"]
  }
  
    ip_configuration {
    name                          = "my-ip-config"
    subnet_id                     = data.azurerm_subnet.my-subnet.id
    private_ip_address_allocation = "static"
    private_ip_address            = var.my-pe-ip
  }
}
```

### References

* #5189

**Comment by favoretti** [comment] 2021-08-19 11:42
Hey @t3mi, thanks so much for re-opening this. Looking at the SDK I don't see an ability to force static IP allocation for a private endpoint unfortunately. That said, once a resource the connection refers to gets recreated - the endpoint will get recreated as well. Whilst the approach you suggest looks good to me, unfortunately I so far don't see a possibility to implement this.

**Comment by scott1138** [comment] 2022-03-14 21:39
The API now has support for this, but I am not sure about the Azure SDK for Go
https://docs.microsoft.com/en-us/rest/api/virtualnetwork/private-endpoints/create-or-update

**Comment by timja** [comment] 2022-05-11 08:54
I think it's possible in the SDK now.

https://github.com/Azure/azure-sdk-for-go/blob/221a5f6903e0bc18a3fe89ad57574fb4e4b21ae2/services/network/mgmt/2021-08-01/network/privateendpoints.go#L39

Model:
https://raw.githubusercontent.com/Azure/azure-sdk-for-go/main/services/network/mgmt/2021-08-01/network/models.go

Search `type PrivateEndpointIPConfigurationProperties`

**Comment by Noel-Jones** [comment] 2022-08-02 14:10
It does indeed appear to be in the SDK now. Let me know if someone knows otherwise! I am having a look at implementing. Will let you know how I get on. ip_configuration block would be as follows.

````
resource "azurerm_private_endpoint" "my-sa-pe" {
  name                = "${replace(var.my_name,"-","")}_pe"
  location            = data.azurerm_resource_group.my-rg.location
  resource_group_name = data.azurerm_resource_group.my-rg.name
  subnet_id           = data.azurerm_subnet.my-subnet.id

  private_service_connection {
    name = "${replace(var.my_name,"-","")}_psc"
    is_manual_connection = false
    private_connection_resource_id = azurerm_storage_account.my-sa.id
    subresource_names = ["blob"]
  }
  
  ip_configuration {
    name                          = "my-ip-config"
    group_id                      = "blob"
    member_name                   = "blob"
    private_ip_address            = var.my-pe-ip
  }
}
````
Debatable whether group_id and member_name are needed, implication is that subresource names can be a list with multiple IP adreeses for the various sub resources - in practice I haven't seen any PLE imlementation support more than one sub resource.

**Comment by Noel-Jones** [comment] 2022-08-02 18:42
Seems to work ok :-) Have tested without ip_configuration, with, and changing (forces recreate). Need to update the documentation and ready for PR I hope. Not much point in changing the data resource (of a slightly different name) since it already returns the ip address assigned to the nic. Don't know how to update test cases or whether I should since the ip_configuration is optional.

**Comment by shghildi** [comment] 2022-08-09 09:55
Hi,

i am trying to add static ip to my private end point however ip configuration block is not working for me . is it not supported ??

My Code:

data "azurerm_resource_group" "logicapp_rg" { 
  name     = "hbl-azure-ci-datalake-uat-transformation-rg"
 }

 
resource "azurerm_storage_account" "Logicapp_str" {

  name                     = "hblazurecidatalakelog"

  resource_group_name      = data.azurerm_resource_group.logicapp_rg.name

  location                 = data.azurerm_resource_group.logicapp_rg.location

  account_tier             = "Standard"

  account_replication_type = "LRS"

}

resource "azurerm_service_plan" "logicapp_uat_plan" {

  name                = "hblazurecidatalakeuatappplan"

  location            = data.azurerm_resource_group.logicapp_rg.location

  resource_group_name = data.azurerm_resource_group.logicapp_rg.name

  sku_name= "WS1"

  os_type = "Windows"

}

resource "azurerm_logic_app_standard" "Logicapp_uat" {

  name                       = "hbl-azure-ci-datalake-uat-logicapp"

  location                   = data.azurerm_resource_group.logicapp_rg.location

  resource_group_name        = data.azurerm_resource_group.logicapp_rg.name

  app_service_plan_id        = azurerm_service_plan.logicapp_uat_plan.id

  storage_account_name       = azurerm_storage_account.Logicapp_str.name

  storage_account_access_key = azurerm_storage_account.Logicapp_str.primary_access_key

}
data "azurerm_resource_group" "network_rgapp" {
  provider = azurerm.uatsubscription
  name     =var.networkrgname
 }

 data "azurerm_subnet" "network_subnetlapp" {

  provider = azurerm.uatsubscription
  name     = var.subnetname2

  virtual_network_name = var.vnetname

  resource_group_name  = data.azurerm_resource_group.network_rgapp.name

}
 
  resource "azurerm_private_endpoint" "Logicapp-pe" {

   provider            = azurerm.uatsubscription
   name                = "hbl-azure-ci-dl-uat-logicapp-pe"

   location            = data.azurerm_resource_group.logicapp_rg.location

  resource_group_name = data.azurerm_resource_group.logicapp_rg.name
   subnet_id           = data.azurerm_subnet.network_subnetlapp.id

   
   private_service_connection {
     name                           = "logicappconnection"
     private_connection_resource_id = azurerm_logic_app_standard.Logicapp_uat.id
     subresource_names              = ["sites"]
     is_manual_connection           = false

   }

   ip_configuration {
      name= "uatiplogicappconfig"
      private_ip_address_allocation= "static"
      subnet_id           = data.azurerm_subnet.network_subnetlapp.id
      private_ip_address= "10.105.2.4"
   }

  }

Error Message: Blocks of "ip configuration" are not expected here"

**Comment by Noel-Jones** [comment] 2022-08-09 10:22
@shghildi sorry, not yet. I created a Pull Request but it has not been added into Terraform yet. Fingers crossed it won't be too long but I don't know the workload on reviewers and so on.

**Comment by shghildi** [comment] 2022-08-09 10:26
Thanks a lot @ Noel Jones for quick response 😊. Wanted a confirmation on this to plan out project work accordingly.

**Comment by lmarkusl** [comment] 2022-08-22 15:10
@Noel-Jones we need this function also and build your Pull Request. https://github.com/hashicorp/terraform-provider-azurerm/pull/17864

On our side it didn't work because we are using a custom private link. Means we don't need to set the subresource_name.
Also the azure API allows to be empty. 

https://github.com/Noel-Jones/terraform-provider-azurerm/pull/1

So mayby you can add this into your branch.
Thx
Markus

**Comment by LukeHarjulin** [comment] 2022-09-09 16:23
Piggy backing onto this Issue as I've found an issue regarding the ip_configuration property.

The value provided to the ip_configuration.subresource_name property for the resource azurerm_private_endpoint sets both the GroupId and MemberName of the PrivateEndpointIPConfigurationProperties for the Private Endpoint. I believe this implementation is not correct due to the fact that the two properties GroupId and MemberName need to be independently settable.

See error message below:

Error: creating Private Endpoint "<pe-name>" (Resource Group "<rg-name>"): network.PrivateEndpointsClient#CreateOrUpdate: 
Failure sending request: StatusCode=400 -- Original Error: Code="PrivateEndpointIpConfigurationMissingMemberNamesRequiredByFps" Message="Private Endpoint /subscriptions/<subscription-id>/resourceGroups/<rg-name>/providers/Microsoft.Network/privateEndpoints/<pe-name> contains static ipconfigurations: 
[PrivateIPAddress: <private-ip-address>, GroupId: default, MemberName: default] and its missing these membernames/groupids requested by Private Link service [GroupId: vault, MemberName: default]. Private Endpoint needs to be reconfigured with missing memberNames." Details=[]


If @Noel-Jones's PR (allowing for the ip_configuration.subresource_name property to be optional ) solves this problem, then I would greatly appreciate the PR being looked at and pushed through as soon as possible, please!

Thanks
Luke

**Comment by Noel-Jones** [comment] 2022-09-20 11:42
Hi all, apologies for not responding earlier to queries. First off, I note that my PR was merged and is in v3.21 of the provider. I don't know why it is not referenced in the change log, I'm still new to how all this is managed.

Markus has a PR to make the subresource optional. It needs the automated testing resolving. Kudos to Markus for for adding it.

@LukeHarjulin - what endpoint are you creating? Code samples may assist to reproduce the issue. Microsoft documentation does indeed suggest that member name is specific to the resource and then shows an example where it is the same as the group id. https://learn.microsoft.com/en-us/azure/private-link/manage-private-endpoint?tabs=manage-private-link-powershell. Having digested that further I have now found a case in our subscription where the member name is different from the group id:

````
az network private-link-resource list -g xxx -n mongodb-xxx --type Microsoft.DocumentDB/databaseAccounts
Resource ID will be ignored since other three arguments have been provided.
[
  {
    "id": "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.DocumentDB/databaseAccounts/mongodb-xxx/privateLinkResources/MongoDB",
    "name": "MongoDB",
    "properties": {
      "groupId": "MongoDB",
      "requiredMembers": [
        "mongodb-xxx-uksouth",
        "mongodb-xxx"
      ],
      "requiredZoneNames": [
        "privatelink.mongo.cosmos.azure.com"
      ]
    },
    "resourceGroup": "xxx",
    "type": "Microsoft.DocumentDB/databaseAccounts/privateLinkResources"
  }
]
````

So I have to agree that the member name needs to be supplied independently to cover all cases. @katbyte not sure how we should manage this as Markus has a PR in progress. Would it be better to create a new issue?

**Comment by LukeHarjulin** [comment] 2022-09-20 15:59
Hi Noel, thanks for the response.

I was attempting to create private endpoint for a Key Vault with a static IP address. It appeared that the group id needed to be 'vault' and the member name needed to be 'default'. 
I suppose this is a bug within the new implementation, so it should probably be a new issue. I do hope this can be fixed and implemented soon, though.

**Comment by lmarkusl** [comment] 2022-09-22 13:21
Hi all, sorry being late answer. i'm in vacation.
Yes i wonder also why @Noel-Jones change was approved and already merged without tests.

But in the meantime i got feedback and i run the tests before i requested my PR.
It could be that some merge came to a problem now.

I will try it over the weekend. Till yet we ware working on our side with a self compiled version.

@LukeHarjulin if i can remember we had the same issue or message. And after having it optional it worked.

**Comment by LukeHarjulin** [comment] 2022-09-22 13:27
Hi @lmarkusl ,
I'm not sure how it slipped by either. Anyway, I think both the Group Id and the Member Name properties should be settable and (if your PR passes tests for the property to be optional) having them optional would be great too.
Thanks for the response.

**Comment by vinusorout** [comment] 2022-09-29 04:36
Hi, 

There are resources which need multiple membernames/groupids for the private link service. But you are allowing max one block for "ip_configuration". For example for COSMOS we get following error:

```
module.cosmosdb_pe["abc-testbed-eus-abcapp-cos-pe2"].azurerm_private_endpoint.pe: Creating...
╷
│ Error: creating Private Endpoint "abc-testbed-eus-abcapp-cos-pe2" (Resource Group "abc-testbed-eus-abcapp-rg"): network.PrivateEndpointsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="PrivateEndpointIpConfigurationMissingMemberNamesRequiredByFps" Message="Private Endpoint /subscriptions/subcriptionID/resourceGroups/abc-testbed-eus-abcapp-rg/providers/Microsoft.Network/privateEndpoints/abc-testbed-eus-abcapp-cos-pe2 contains static ipconfigurations: [PrivateIPAddress: 10.194.38.231, GroupId: Sql, MemberName: Sql] and its missing these membernames/groupids requested by Private Link service [GroupId: Sql, MemberName: abc-testbed-eus-abcapp-cos; GroupId: Sql, MemberName: abc-testbed-eus-abcapp-cos-eastus2; GroupId: Sql, MemberName: abc-testbed-eus-abcapp-cos-centralus]. Private Endpoint needs to be reconfigured with missing memberNames." Details=[]
│
│   with module.cosmosdb_pe["abc-testbed-eus-abcapp-cos-pe2"].azurerm_private_endpoint.pe,
│   on ..\templates-iac\privateendpoint\main.tf line 1, in resource "azurerm_private_endpoint" "pe":
│    1: resource "azurerm_private_endpoint" "pe" {
```

How we can implement when multiple static IPs are required by private endpoints?

**Comment by Noel-Jones** [comment] 2022-09-29 08:32
Hi @vinusorout, yes, as I showed in my previous example the COSMOS resource shows multiple required members. This was news to me since in our production infrastructure we only created one private linked endpoint (it does explain why we have to make direct connections). The point of explaining this is to highlight that the error you show is I believe saying that the member name is incorrect and it is helpfully listing the two member names, either of which would be accepted. With a solution to allow the member name to be specified it would then be a case of creating two distinct PLEs against the COSMOS account with each specifying one of the member names and each therefore able to specify the ip_configuration.

I'm going to try and find some time to progress this but it would be a couple of weeks at least. Thanks for the comment and useful error message.

**Closed** 2024-03-22 20:10 UTC
Labels: enhancement, service/private-link, sdk/not-yet-supported
