### ISSUE TITLE
azurerm_storage_account_network_rules can't set CIDR(*.*.*.*/32)

### ISSUE THREAD

**Issue by yoshiakimiyazaki** [hashicorp/terraform-provider-azurerm#5444] opened 2020-01-20 04:04 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
If you set the subnet mask and set it to ip_rules of azurerm_storage_account_network_rules, a 400 error will be returned. It can be set without a subnet mask.

### Terraform (and AzureRM Provider) Version

Terraform v0.12.18
- provider.azuread v0.7.0
- provider.azurerm v1.41.0
- provider.null v2.1.2
- provider.random v2.2.1

### Affected Resource(s)

* `azurerm_storage_account_network_rules`

### Terraform Configuration Files

```#--------------------------------------------------------------
# local
#--------------------------------------------------------------
locals {
  name = var.name_random ? "${replace("${var.name}", "/[^a-zA-Z0-9]/", "")}${random_id.this.dec}" : var.name
}

#--------------------------------------------------------------
# Create random id
#--------------------------------------------------------------
resource "random_id" "this" {
  byte_length = 4
}
#--------------------------------------------------------------
# Create Storage Account
#--------------------------------------------------------------
resource "azurerm_storage_account" "this" {
  name                     = local.name
  resource_group_name      = var.resource_group_name
  location                 = var.location
  account_kind             = var.account_kind
  account_tier             = var.account_tier
  account_replication_type = var.account_replication_type
  # access_tier can't set when account_kind sets "Storage".
  access_tier               = var.account_kind != "Storage" ? var.access_tier : null
  enable_blob_encryption    = var.enable_blob_encryption
  enable_file_encryption    = var.enable_file_encryption
  enable_https_traffic_only = var.enable_https_traffic_only
  is_hns_enabled            = var.is_hns_enabled
  account_encryption_source = var.account_encryption_source
  dynamic "custom_domain" {
    for_each = var.custom_domain
    content {
      name          = lookup(custom_domain.value, "name", null)
      use_subdomain = lookup(custom_domain.value, "use_subdomain", null)
    }
  }
  # enable_advanced_threat_protection = var.enable_advanced_threat_protection
  dynamic "identity" {
    for_each = var.identity
    content {
      type = lookup(identity.value, "type", null)
    }
  }
  dynamic "queue_properties" {
    for_each = var.queue_properties
    content {
      dynamic "cors_rule" {
        for_each = lookup(queue_properties.value, "cors_rule", [])
        content {
          allowed_headers    = lookup(cors_rule.value, "allowed_headers", null)
          allowed_methods    = lookup(cors_rule.value, "allowed_methods", null)
          allowed_origins    = lookup(cors_rule.value, "allowed_origins", null)
          exposed_headers    = lookup(cors_rule.value, "exposed_headers", null)
          max_age_in_seconds = lookup(cors_rule.value, "max_age_in_seconds", null)
        }
      }
      dynamic "logging" {
        for_each = lookup(queue_properties.value, "logging", [])
        content {
          delete                = lookup(logging.value, "delete", null)
          read                  = lookup(logging.value, "read", null)
          version               = lookup(logging.value, "version", null)
          write                 = lookup(logging.value, "write", null)
          retention_policy_days = lookup(logging.value, "retention_policy_days", null)
        }
      }
      dynamic "minute_metrics" {
        for_each = lookup(queue_properties.value, "minute_metrics", [])
        content {
          enabled               = lookup(minute_metrics.value, "enabled", null)
          version               = lookup(minute_metrics.value, "version", null)
          include_apis          = lookup(minute_metrics.value, "include_apis", null)
          retention_policy_days = lookup(minute_metrics.value, "retention_policy_days", null)
        }
      }
      dynamic "hour_metrics" {
        for_each = lookup(queue_properties.value, "hour_metrics", [])
        content {
          enabled               = lookup(hour_metrics.value, "enabled", null)
          version               = lookup(hour_metrics.value, "version", null)
          include_apis          = lookup(hour_metrics.value, "include_apis", null)
          retention_policy_days = lookup(hour_metrics.value, "retention_policy_days", null)
        }
      }
    }
  }
  dynamic "network_rules" {
    for_each = var.network_rules
    content {
      default_action             = lookup(network_rules.value, "default_action", "Allow")
      bypass                     = lookup(network_rules.value, "bypass", null)
      ip_rules                   = lookup(network_rules.value, "ip_rules", null)
      virtual_network_subnet_ids = lookup(network_rules.value, "virtual_network_subnet_ids", null)
    }
  }
  tags = var.tags
}
#--------------------------------------------------------------
# Create File Share
#--------------------------------------------------------------
resource "azurerm_storage_share" "this" {
  name                 = var.share_name
  storage_account_name = azurerm_storage_account.this.name
  dynamic "acl" {
    for_each = var.acl
    content {
      id = lookup(acl.value, "id", null)
      dynamic "access_policy" {
        for_each = lookup(acl.value, "access_policy", [])
        content {
          expiry      = lookup(access_policy.value, "expiry", null)
          permissions = lookup(access_policy.value, "permissions", null)
          start       = lookup(access_policy.value, "start", null)
        }
      }
    }
  }
  quota    = var.quota
  metadata = var.metadata
  # Optional/Deprecated
  # resource_group_name = var.resource_group_name
  depends_on = [
    azurerm_storage_account.this
  ]
}
#--------------------------------------------------------------
# Create Storage Account network rules
#--------------------------------------------------------------
resource "azurerm_storage_account_network_rules" "this" {
  storage_account_name       = azurerm_storage_account.this.name
  resource_group_name        = var.resource_group_name
  default_action             = var.default_action
  bypass                     = var.bypass
  ip_rules                   = var.ip_rules
  virtual_network_subnet_ids = var.virtual_network_subnet_ids
  depends_on = [
    azurerm_storage_account.this
  ]
}
```

### Debug Output

```
Terraform will perform the following actions:

  # module.storage_storage_account_share_file.azurerm_storage_account_network_rules.this will be updated in-place
  ~ resource "azurerm_storage_account_network_rules" "this" {
        bypass                     = [
            "Logging",
        ]
        default_action             = "Deny"
        id                         = "/subscriptions/xxxxxxxxx/resourceGroups/app-resource-group/providers/Microsoft.Storage/storageAccounts/xxxxxxx"
      ~ ip_rules                   = [
          - "111.111,111,111",
          + "111,111,111.111/32",
        ]
        resource_group_name        = "app-resource-group"
        storage_account_name       = "aaaaaaaaaaaa"
        virtual_network_subnet_ids = []
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes 

module.storage_storage_account_share_file.azurerm_storage_account_network_rules.this: Modifying... [id=/subscriptions/xxxxxx/resourceGroups/app-resource-group/providers/Microsoft.Storage/storageAccounts/xxxxxxx]

Error: Error updating Azure Storage Account Network Rules "xxxxxxxx" (Resource Group "app-resource-group"): storage.AccountsClient#Update: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidValuesForRequestParameters" Message="Values for request parameters are invalid: networkAcls.ipRule[*].value. For more information, see - https://aka.ms/storagenetworkruleset"

  on ../../modules/azure/recipes/storage/file_share/main.tf line 130, in resource "azurerm_storage_account_network_rules" "this":
 130: resource "azurerm_storage_account_network_rules" "this" {
```
### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by r0bnet** [comment] 2020-03-21 15:55
Hey @yoshiakimiyazaki,
a 400 means that the API does not allow those values. The only thing we could do is to allow those values in the Azure provider but cut the /32 but i don't see a good reason for that now.

Is that what you need? 

Unfortunately the APIs for all those network rules are different per resource.

**Comment by yoshiakimiyazaki** [comment] 2020-03-23 06:34
@r0bnet 
thank you for reply comment.
I have read the following document.
https://docs.microsoft.com/en-us/azure/storage/common/storage-network-security#grant-access-from-a-virtual-network
```
Small address ranges using "/31" or "/32" prefix sizes are not supported. These ranges should be configured using individual IP address rules.
```

Since it was specified that subnet masks such as / 31 and / 32 were not supported in the first place, 400 errors were expected.
So this does not need to be done by Azurerm Terraform Provider.
In the case of subnet mask such as / 31, it corresponds to specify individually.
I read this document, so API can't low range subnet mask

**Comment by philbal611** [comment] 2020-09-23 18:18
Recently ran into this. As @yoshiakimiyazaki pointed out, this is an Azure limitation. You cannot specify CIDR ranges with /32 or /31. I've verified that /30 and larger does work, and even validated via Terraform.

Although, to the point of the issue here, some more verbose documentation of this on the [ip_rules](https://www.terraform.io/docs/providers/azurerm/r/storage_account.html#ip_rules) definition would be extremely helpful.

**Comment by paulgear** [comment] 2020-10-22 03:07
I'm running into this issue as well.  I understand that it's a limitation of the Azure API, but it results in massive noise in our terraform plans every time we run a plan, because whilst the provider doesn't support specifying /32s, _it reports the existing values as /32s by default_!  Here's an example:

```
...
Terraform will perform the following actions:

  # azurerm_container_registry.module[0] will be updated in-place
  ~ resource "azurerm_container_registry" "module" {
        admin_enabled            = false
        georeplication_locations = [
            "australiasoutheast",
        ]
        id                       = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/example-rg/providers/Microsoft.ContainerRegistry/registries/example-registry"
        location                 = "australiaeast"
        login_server             = "exampleacrname.azurecr.io"
        name                     = "exampleacrname"
      ~ network_rule_set         = [
          ~ {
                default_action  = "Deny"
              ~ ip_rule         = [
                  + {
                      + action   = "Allow"
                      + ip_range = "192.0.2.1"
                    },
                  - {
                      - action   = "Allow"
                      - ip_range = "192.0.2.1/32"
                    },
...
```

At the very least, I think the provider should translate /32s to bare IP addresses on plan output.

Note for search bots in the hope of making this issue easier to find: the error message it produces when trying to use /32s is:
```
...

Error: "network_rules.0.ip_rules.3" must start with IPV4 address and/or slash, number of bits (0-30) as prefix. Example: 23.45.1.0/30.

  on main.tf line 264, in resource "azurerm_storage_account" "nonprod_state":
 264: resource "azurerm_storage_account" "nonprod_state" {



Error: "network_rules.0.ip_rules.5" must start with IPV4 address and/or slash, number of bits (0-30) as prefix. Example: 23.45.1.0/30.

  on main.tf line 264, in resource "azurerm_storage_account" "nonprod_state":
 264: resource "azurerm_storage_account" "nonprod_state" {


...
```
This appears to be produced by https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/storage/validate/storage_account.go#L30, which was the only current hit for the error message in Google when I started searching for this issue.

**Comment by ravi102465** [comment] 2021-08-05 13:15
@paulgear Did you get around the above error? 

Even I'm facing same issue while using /32 ip's for ip restriction. I'm using list of ips to whitelist on webapp, keyvault and storage account. When I remove /32 webapp reports saying ip should in CIDR format and if I add /32 storage account reports saying can be only used till /30.

**Comment by paulgear** [comment] 2021-08-05 21:10
@ravi102465 Unfortunately, I never found a solution.  I'm no longer working with Azure, so I can't confirm personally, but to my knowledge this behaviour has not changed.

**Comment by favoretti** [comment] 2021-08-19 07:51
@ravi102465 would you be so kind to provide some concise terraform code example to reproduce it? I'll try to have a look whether this can be fixed.

**Comment by ravi102465** [comment] 2021-08-20 10:51
@favoretti please find the link for code https://github.com/UKHO/exchange-set-service/tree/main/Deployment.

I'm passing list of allowed_ips and I'm adding those on network rules of webapp and storage account. Trouble is webapp need that on cidr format and if I pass /32 storage account complains and fails. I did some workaround to fix it but it would be better if storage account can take /32. I tried it on portal and I can add /32 from portal.

Let me know if you need any other details

**Comment by michelefa1988** [comment] 2021-11-14 16:31
Has this issue been fixed yet? Running into the same issue when passing a list of IPs to storage accounts. Any workarounds?

```
 network_rules.0.ip_rules.3 must start with IPV4 address and/or slash, number of bits (0-30) as prefix. Example: 23.45.1.0/30.
```

**Comment by m4r74** [comment] 2021-12-02 08:32
Same here. 

We have a list of addresses which require adding to allow our proxy in. Using a common config for that to allow into storage (if needed) and into key vault (if needed). 
If we don't include /32 in the config, then vault wants to be updated on the addresses. If we do, storage stops working. 

The only way around it is to either truncate the /32 in our storage module (that will then be a default /32), or append it in all other modules (i.e. key vault) if no size is defined, as maintaining two configs for the same addresses makes no sense in our case.

**Comment by 03c** [comment] 2023-01-24 11:58
Would it be possible to update the documentation around this area?

For example: 
[https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account#ip_rules](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account#ip_rules)
![image](https://user-images.githubusercontent.com/996720/214285833-824e383a-cf12-4d5f-b1d8-02e3cb31e758.png)

Maybe an extra note or an update to this wording to mention that /31 and /32 are not supported.

**Comment by jpmicrosoft** [comment] 2023-03-09 16:40
@03c  I created a PR to make the change.

https://github.com/hashicorp/terraform-provider-azurerm/pull/20870

**Comment by katbyte** [comment] 2023-07-19 16:44
closing this as per microsoft /31 and /31 are not supported and the documentation has been updated.

if this has been in error please do let us know by opening a new issue, thanks!

**Closed by katbyte** 2023-07-19 16:44 UTC
Labels: bug, service/storage, good first issue, v/1.x (legacy)
