### ISSUE TITLE
Application Gateway TLS certs error "Provider produced inconsistent final plan"

### ISSUE THREAD

**Issue by mdimovskihtec** [hashicorp/terraform-provider-azurerm#22359] opened 2023-07-03 12:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.6

### AzureRM Provider Version

3.63.0

### Affected Resource(s)/Data Source(s)

azurerm_application_gateway

### Terraform Configuration Files

```hcl
module "application_gateway" {
  source                         = "../../modules/application_gateway"
  name                           = local.dev_apgw_name
  location                       = var.location
  location_short                 = var.location_short
  rg_name                        = azurerm_resource_group.rg.name
  tags                           = local.tags
  ...
  ssl_certificates = [
    {
      name                = data.azurerm_key_vault_certificate.cert1.name
      key_vault_secret_id = data.azurerm_key_vault_certificate.cert1.secret_id
    },
    {
      name                = data.azurerm_key_vault_certificate.cert2.name
      key_vault_secret_id = data.azurerm_key_vault_certificate.cert2.secret_id
    }
  ]

----------------------------
resource "azurerm_application_gateway" "app_gw" {
  location            = var.location
  name                = var.name
  resource_group_name = var.rg_name
  
  dynamic "ssl_certificate" {
    for_each = var.ssl_certificates

    content {
      name                = ssl_certificate.value.name
      key_vault_secret_id = ssl_certificate.value.key_vault_secret_id
    }
  }
  ...
}
```

### Debug Output/Panic Output

```shell
Error: Provider produced inconsistent final plan
When expanding the plan for module.application_gateway.azurerm_application_gateway.app_gw to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/azurerm" produced an invalid new value for .ssl_certificate: planned set element cty.ObjectVal(map[string]cty.Value{"data":cty.StringVal(""), "id":cty.UnknownVal(cty.String), "key_vault_secret_id":cty.UnknownVal(cty.String), "name":cty.StringVal("cert1"), "password":cty.StringVal(""), "public_cert_data":cty.UnknownVal(cty.String)}) does not correlate with any element in actual.

This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

### Expected Behaviour

Whenever a new ssl certificate is added, the apply should pass. 

### Actual Behaviour

The error mentioned above occurs. Even when removing the newly added elements in the ssl_certificates array, the error still persists.

Tried upgrading/downgrading both terraform provider and versions, but nothing helped.

### References

#18263 has no answer.

**Comment by rcskosir** [comment] 2023-07-03 13:53
Thanks for taking the time to submit this issue. It looks like this is a duplicate of #18263. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of #18263. 
Please vote on #18263 by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. You can also add a comment with the updated version of the provider that you are using and any additional information, for example, replying to @ms-zhenhua's question on the issue regarding runnable configuration.

**Closed by rcskosir** 2023-07-03 13:53 UTC
Labels: duplicate, service/application-gateway
