### ISSUE TITLE
site_config -> vnet_route_all_enabled is ignored for app_slots configurations

### ISSUE THREAD

**Issue by cvallesi-kainos** [hashicorp/terraform-provider-azurerm#18701] opened 2022-10-11 10:50 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.2

### AzureRM Provider Version

3.26.0

### Affected Resource(s)/Data Source(s)

azurerm_linux_web_app, azurerm_linux_web_app_slot, azurerm_app_service, azurerm_web_app_active_slot, virtual_network_swift_connection

### Terraform Configuration Files

```hcl
A repo has been built and tested to reproduce this issue. Instructions in the readme.

https://github.com/cvallesi-kainos/azure-app-service-slot-vnet-integration
```

### Debug Output/Panic Output

```shell
No meaningful debug output to show
```

### Expected Behaviour

When specifying the attribute `vnet_route_all_enabled` in the `azurerm_linux_web_app_slot` I would expect that to be reflected in the deployed resource.

### Actual Behaviour

The `vnet_route_all_enabled` is not being respected when checking the deployed state for the `azurerm_linux_web_app_slot`.
However, it's respected for the `azurerm_linux_web_app` configuration block.

This can lead to some tricky behaviour in case the configuration also uses `azurerm_web_app_active_slot` as the "non production" slot will not have the vnet integration enabled and will be promoted as "production".  
Subsequentially every new iteration of the deployment will make it impossible to enable the vnet integration again as the "production" will have it turned off and the new slots will not pick up the attribute value anyway.

At that point, the only option is to destroy the resource and recreate it but also adding `overwrite_network_config` set to `false` in the `azurerm_web_app_active_slot` resource block.

### Steps to Reproduce

Please follow the readme instructions in the repo provided

**Comment by cvallesi-kainos** [comment] 2022-10-22 09:56
Possibily fixed here: https://github.com/hashicorp/terraform-provider-azurerm/pull/18738

**Comment by cvallesi-kainos** [comment] 2022-10-24 09:34
Tested with azurerm 3.28.0, issue still there.

**Comment by xiaxyi** [comment] 2023-06-01 09:03
@cvallesi-kainos Sorry for the late response, I tested the property and find out it's set exactly as what's defined in config. Can you help me to try the behavior using the latest provider and let me know if you are still seeing this issue? Let me know if you have any questions. Thanks.

**Comment by rcskosir** [comment] 2023-10-30 22:01
Thanks for taking the time to submit this issue. @xiaxyi was unable to reproduce this behavior with v3.59.0. We’re going to close this issue for now, but if you run into this again with the latest Terraform and Provider versions, please feel free to [open a new issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/new/choose).

**Closed by rcskosir** 2023-10-30 22:01 UTC
Labels: bug, waiting-response, service/web-app, v/3.x
