### ISSUE TITLE
Please implement client_certificate argument on the azurerm provider

### ISSUE THREAD

**Issue by kkizer** [hashicorp/terraform-provider-azurerm#17808] opened 2022-07-29 12:16 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The [azuread provider allows a client certificate to be specified using the client_certificate argument on the provider](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs#argument-reference) or by specifying it in the ARM_CLIENT_CERTIFICATE environment variable. The value is the client certificate base64 encoded. This would be very useful when using Terraform Cloud. The arguments for Azure providers should be consistent.

### New or Affected Resource(s)/Data Source(s)

All resources and data sources since it affects authentication to Azure

**Comment by tombuildsstuff** [comment] 2022-07-29 13:57
hi @kkizer 

Thanks for opening this issue.

Taking a look through this appears to be a duplicate of #17741 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #17741 for updates?

Thanks!

**Closed by tombuildsstuff** 2022-07-29 13:57 UTC
Labels: duplicate
