### ISSUE TITLE
Getting error: Provider produced inconsistent result after apply ini azurerm 2.93

### ISSUE THREAD

**Issue by ajay4engg** [hashicorp/terraform-provider-azurerm#15904] opened 2022-03-21 09:23 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by ajay4engg** [comment] 2022-03-21 09:24
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to
│ module.sqlserver.azurerm_key_vault_secret.azsqlsvr, provider
│ "provider[\"registry.terraform.io/hashicorp/azurerm\"]" produced an
│ unexpected new value: Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.

**Comment by tombuildsstuff** [comment] 2022-03-21 10:39
Duplicate of #11059

**Closed by tombuildsstuff** 2022-03-21 10:39 UTC
