### ISSUE TITLE
Error when using the Terragrunt mock_outputs feature with new Terraform resource azurerm_windows_function_app

### ISSUE THREAD

**Issue by bdorplatt** [hashicorp/terraform-provider-azurerm#17376] opened 2022-06-24 17:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.15.4

### AzureRM Provider Version

3.11.0

### Affected Resource(s)/Data Source(s)

azurerm_windows_function_app

### Terraform Configuration Files

```hcl
**Function App resource**
resource "azurerm_windows_function_app" "function_app" {
  app_settings                = var.fa_app_settings
  location                    = var.region
  name                        = "test-azf"
  resource_group_name         = var.resource_group_name
  service_plan_id             = var.fa_service_plan_id
}

**Dependency and Input in Terrarunt.hcl**
include {
  path = find_in_parent_folders()
}
dependency "app_service_plan01" {
  config_path  = "../../appserviceplan/appserviceplan01"
  mock_outputs = {
    asp_id  = "/subscriptions/11111111-1111-1111-1111-111111111111/resourceGroups/mockrg/providers/Microsoft.Web/serverfarms/mockasp"
  }
  mock_outputs_allowed_terraform_commands = ["validate", "plan"]
  mock_outputs_merge_strategy_with_state = "shallow"
}

inputs = {
  fa_service_plan_id       = dependency.app_service_plan01.outputs.asp_id
}

**Output from the App Service Plan module**
output "asp_id" {
  description = "ID of ASP"
  value       = module.asp.asp_id
}
```

### Debug Output/Panic Output

```shell
**Error: could not read new Service Plan to check tier Service Plan: (Serverfarm Name "mock-asp" / Resource Group "mock-rg"): web.AppServicePlansClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceGroupNotFound" Message="Resource group 'mock-rg' could not be found."**
```

### Expected Behaviour

The plan would run successfully, honoring the mock outputs.

### Actual Behaviour

Running a plan against the new **azurerm_windows_function_app** resource results in the error above and will not accept a mock output and continue. The exact same setup with the deprecated **azurerm_function_app** works as expected and honors the mock values. Based on the error details, it appears the new resource requires actually seeing what tier the service plan is on and it can't get that from a mock value. Both tests were performed using the new **azurerm_service_plan** resource for the app service plan.

### Steps to Reproduce

Run a Terragrunt Plan against an **azurerm_windows_function_app** resource using mock outputs from an **azurerm_service_plan** resource.

I realize this issue is specific to Terragrunt and it's mock output feature for dependencies and have raised the issue on the Gruntwork Github but wanted to raise it here as well since the change in behavior occurred with the introduction of the new function app resource and works with the deprecated resource.

**Comment by lonegunmanb** [comment] 2022-06-27 08:19
Hi @bdorplatt thanks for opening this issue. I believe this behavior is by design and not a bug.

The error you've seen is caused by the [CustomizeDiff function](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/appservice/windows_function_app_resource.go#L906). When `service_plan_id` has been changed(that's obviously true for a new function to be created), the provider needs run some custom schema checks based on service plan's configuration. The error you pasted was complaining that it cannot find the service plan resource, so it cannot finish this custom schema check.

Could you try to create an existing service plan resource for mock output only?

**Comment by lonegunmanb** [comment] 2022-07-04 00:36
Hello @bdorplatt , have you tried a stub service plan as the mock variable? Thanks.

**Comment by bdorplatt** [comment] 2022-07-07 15:46
When you say "stub service plan" do you mean putting in some thing for asp_id that actually exists in Azure as opposed to the generalized mock ID we are using?

**Comment by lonegunmanb** [comment] 2022-07-08 22:28
> When you say "stub service plan" do you mean putting in some thing for asp_id that actually exists in Azure as opposed to the generalized mock ID we are using?

Exactly! A real service plan for validation only, does that work for you?

**Comment by lonegunmanb** [comment] 2022-07-18 00:55
Hi @bdorplatt glad to hear that! Since we've got a workaround now, would you please close this issue? Thanks!

**Comment by lonegunmanb** [comment] 2022-07-25 01:39
Hi @bdorplatt , just a kindly ping, is there anything I can do for this issue? Thanks!

**Comment by tombuildsstuff** [comment] 2022-07-25 09:52
Closing since this out since this is specific to Terragrunt mocking and isn't a provider bug but an intentional behavioural feature - as mentioned above you should be able to workaround this by specifying a real App Service Plan ID here, since we need to look this up to validate it's configured correctly to ensure the plan will work, due to limitations within the Azure API.

**Closed by tombuildsstuff** 2022-07-25 09:52 UTC

**Comment by bdorplatt** [comment] 2022-07-25 16:05
Thanks for the assistance in finding the root cause and workaround. I will pursue this on the Terragrunt side where I have an issue already raised [https://github.com/gruntwork-io/terragrunt/issues/2163](url)
Since the whole point of mock outputs is to not have resources already existing, I imagine there will need to be an adjustment to how Terragrunt handles this resource type.
