### ISSUE TITLE
Support for Azure AD PIM Resource

### ISSUE THREAD

**Issue by ramyaradhakrishnan108** [hashicorp/terraform-provider-azurerm#19996] opened 2023-01-12 23:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be helpful to have a terraform resource for Azure Privileged Identity Management in azurerm provider.

### New or Affected Resource(s)/Data Source(s)

azurerm_privileged_identity_management

**Comment by tombuildsstuff** [comment] 2023-01-26 10:17
hey @ramyaradhakrishnan108 

Thanks for opening this issue.

Taking a look through here this appears to be a duplicate of [this issue on the AzureAD Provider](https://github.com/hashicorp/terraform-provider-azuread/issues/68) and as such rather than having multiple issues open tracking the same thing I'm going to close this issue [in favour of the upstream issue on the AzureAD Provider](https://github.com/hashicorp/terraform-provider-azuread/issues/68) - would you mind subscribing to that issue for updates?

Thanks!

**Closed by tombuildsstuff** 2023-01-26 10:17 UTC
