### ISSUE TITLE
Error: waiting for creation/update of "Custom Domain" on API MGMT

### ISSUE THREAD

**Issue by ValeruS** [hashicorp/terraform-provider-azurerm#18047] opened 2022-08-19 14:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.5

### AzureRM Provider Version

3.18.0/3.19.0

### Affected Resource(s)/Data Source(s)

azurerm_api_management_custom_domain

### Terraform Configuration Files

```hcl
data "azurerm_key_vault_secret" "cert" {
  name         = var.certificate_name
  key_vault_id = var.key_vault_id
}

resource "azurerm_api_management" "api" {
  name                = var.name
  location            = var.location
  resource_group_name = var.resource_group_name
  publisher_name      = var.publisher_name
  publisher_email     = var.publisher_email
  sku_name            = var.sku_name

  tenant_access {
    enabled = var.tenant_access_enabled
  }
  identity {
    type = "SystemAssigned"
  }
  protocols {
    enable_http2 = true
  }
  security {
    enable_backend_ssl30                                = false
    enable_backend_tls10                                = false
    enable_backend_tls11                                = false
    enable_frontend_ssl30                               = false
    enable_frontend_tls10                               = false
    enable_frontend_tls11                               = false
  }
}

resource "azurerm_key_vault_access_policy" "apim" {
  key_vault_id = var.key_vault_id
  tenant_id    = var.tenantID
  object_id    = azurerm_api_management.api.identity.0.principal_id

  secret_permissions = [
    "Get",
    "List"
  ]
}

resource "azurerm_api_management_custom_domain" "domain" {
  api_management_id = azurerm_api_management.api.id

  gateway {
    host_name           = var.host_name
    key_vault_id        = data.azurerm_key_vault_secret.cert.id
    default_ssl_binding = true
  }
}
```

### Debug Output/Panic Output

```shell
Error: waiting for creation/update of "Custom Domain: (Name \"default\" / Service Name \"NAME\" / Resource Group \"GROUP\")": Future#WaitForCompletion: context has been cancelled: StatusCode=202 -- Original Error: context deadline exceeded
```

### Expected Behaviour

Terraform should finish successfully

### Actual Behaviour

I got an error in terraform
but de facto a custom domain is created
can be seen in the Azure Portal
![image](https://user-images.githubusercontent.com/17497372/185643119-93191b8d-96ea-4c94-9362-0f2bc9cdc4ca.png)

FYI: Vault access policy is enabled on keyvault

### Steps to Reproduce

terraform apply

**Comment by sinbai** [comment] 2022-08-22 08:56
@ValeruS  thanks for opening this issue here. Per the [tf documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_custom_domain#key_vault_id), the gateway's `key_vault_id`  in the following configuration should contain the SSL Certificate, which must be should be of the type application/x-pkcs12. However, in the provided tf configuration, there is no definition of the `azurerm_key_vault_certificate`. Since the tf configuration below works fine for me, could you use the following tf configuration to see if it works  for you?

```
resource "azurerm_api_management_custom_domain" "domain" {
  api_management_id = azurerm_api_management.api.id

  gateway {
    host_name           = var.host_name
    key_vault_id        = data.azurerm_key_vault_secret.cert.id
    default_ssl_binding = true
  }
}

```
```
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.19.0"
    }
  }
}

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

data "azurerm_client_config" "current" {
}

resource "azurerm_api_management" "example" {
  name                = "example-apim-0822"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  publisher_name      = "pub1"
  publisher_email     = "pub1@email.com"
  sku_name            = "Developer_1"
  
  tenant_access {
    enabled = true
  }
  
  identity {
    type = "SystemAssigned"
  }
  
  protocols {
    enable_http2 = true
  }
  
  security {
    enable_backend_ssl30                                = false
    enable_backend_tls10                                = false
    enable_backend_tls11                                = false
    enable_frontend_ssl30                               = false
    enable_frontend_tls10                               = false
    enable_frontend_tls11                               = false
  }
}


resource "azurerm_key_vault" "example" {
  name                = "example-keyvault-0822"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  tenant_id           = data.azurerm_client_config.current.tenant_id

  sku_name = "standard"

  access_policy {
    tenant_id = data.azurerm_client_config.current.tenant_id
    object_id = data.azurerm_client_config.current.object_id

    certificate_permissions = [
      "Create",
      "Delete",
      "Get",
      "Update",
      "Purge",
    ]

    key_permissions = [
      "Create",
      "Get",
    ]

    secret_permissions = [
      "Get",
    ]
  }

  access_policy {
    tenant_id = data.azurerm_client_config.current.tenant_id
    object_id = azurerm_api_management.example.identity.0.principal_id

    certificate_permissions = [
      "Get",
    ]

    secret_permissions = [
      "Get",
    ]
  }
}

resource "azurerm_key_vault_certificate" "example" {
  name         = "example-certificate"
  key_vault_id = azurerm_key_vault.example.id

  certificate_policy {
    issuer_parameters {
      name = "Self"
    }

    key_properties {
      exportable = true
      key_size   = 2048
      key_type   = "RSA"
      reuse_key  = true
    }

    lifetime_action {
      action {
        action_type = "AutoRenew"
      }

      trigger {
        days_before_expiry = 30
      }
    }

    secret_properties {
      content_type = "application/x-pkcs12"
    }

    x509_certificate_properties {
      key_usage = [
        "cRLSign",
        "dataEncipherment",
        "digitalSignature",
        "keyAgreement",
        "keyCertSign",
        "keyEncipherment",
      ]

      subject            = "CN=api.example.com"
      validity_in_months = 12

      subject_alternative_names {
        dns_names = [
          "api.example.com",
          "portal.example.com",
        ]
      }
    }
  }
}

resource "azurerm_api_management_custom_domain" "example" {
  api_management_id = azurerm_api_management.example.id

  gateway {
    host_name    = "api.example.com"
    key_vault_id = azurerm_key_vault_certificate.example.secret_id
  }
}
```

**Comment by ValeruS** [comment] 2022-08-22 12:27
Hi @sinbai , thanks for replay

The difference I see between tf is only related to the certificate(method to read secret_id and permission)
I use the `data azurerm_key_vault_secret` to read the secret_id of the certificate (the certificate is managed by another "terraform state" and is imported into KV also by terraform). I will add Certificate permission(Get) on `azurerm_key_vault_access_policy` and will try to use the `data azurerm_key_vault_certificate` to read the secret_id to see if will be the same issue.

FYI, issue appear after ~45 min of deployment
azurerm_api_management_custom_domain.domain: Still creating... [44m13s elapsed]
azurerm_api_management_custom_domain.domain: Still creating... [44m23s elapsed]
azurerm_api_management_custom_domain.domain: Still creating... [44m33s elapsed]
azurerm_api_management_custom_domain.domain: Still creating... [44m43s elapsed]
azurerm_api_management_custom_domain.domain: Still creating... [44m53s elapsed]
│ Error: waiting for creation/update of "Custom Domain: ....."

However, even though terraform shows a deployment error, the custom domain is created and can be modified from the Azure Portal UI

**Comment by sinbai** [comment] 2022-08-23 02:20
Hi @ValeruS  thank you for your quick reply.

Per the error provided, it could be concluded that after Terraform sent the request to create `azurerm_api_management_custom_domain`, it timed out while waiting for the Azure API to return a status, since the timeout for creating `azurerm_api_management_custom_domain` in Terraform is set to 45 minutes. After testing, it takes about 41 minutes to create `azurerm_api_management_custom_domain` on my side. I am not sure if 45 minutes is not enough for you because of location or other reasons. Anyway, could you try changing the timeout to see if the problem is resolved? like this:

```
resource "azurerm_api_management_custom_domain" "example" {
  api_management_id = azurerm_api_management.example.id

  gateway {
    host_name    = "api.example.com"
    key_vault_id = azurerm_key_vault_certificate.example.secret_id
  }

    timeouts {
        create = "70m"
  }
}
```

**Comment by ValeruS** [comment] 2022-08-23 06:56
Hi @sinbai, I tried again without changing anything(the same tf  the same location)
deployment was successful
`azurerm_api_management_custom_domain` finished in 38 minutes

It seems that the problem is in time.
I will add timeouts on custom API creation
Thanks for the help

**Comment by sinbai** [comment] 2022-08-23 07:01
@ValeruS Thanks for your feedback. So are you okey if we close this issue?

**Comment by ValeruS** [comment] 2022-08-23 07:04
@sinbai sure, the ticket can be closed

Thanks

**Closed** 2022-08-23 10:45 UTC
