### ISSUE TITLE
terraform plan hangs for a long time with provider 1.44 and 2.10

### ISSUE THREAD

**Issue by guitmz** [hashicorp/terraform-provider-azurerm#6977] opened 2020-05-18 10:08 UTC
### Terraform (and AzureRM Provider) Version
- terraform **0.12.10**
- azurerm **2.10.0** (same problem with **1.44.0**)

### Affected Resource(s)

* `azurerm_storage_container`
* `azurerm_storage_account`

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "kafka" {
  name                     = replace("${terraform.workspace}kafka", "-", "")
  resource_group_name      = azurerm_resource_group.main.name
  location                 = azurerm_resource_group.main.location
  account_tier             = "Standard"
  account_replication_type = "ZRS"
}

resource "azurerm_storage_container" "kafka" {
  name                  = replace("${terraform.workspace}kafka", "-", "")
  storage_account_name  = azurerm_storage_account.kafka.name
  container_access_type = "private"
}
```

### Debug Output
This repeats for around 10 minutes
```
2020/05/18 11:55:17 [TRACE] dag/walk: vertex "azurerm_hdinsight_kafka_cluster.main" is waiting for "azurerm_storage_container.kafka"
2020/05/18 11:55:17 [TRACE] dag/walk: vertex "azurerm_storage_container.kafka" is waiting for "azurerm_storage_account.kafka"
2020/05/18 11:55:17 [TRACE] dag/walk: vertex "provider.azurerm (close)" is waiting for "azurerm_hdinsight_kafka_cluster.main"
2020/05/18 11:55:19 [TRACE] dag/walk: vertex "root" is waiting for "provider.azurerm (close)"
2020/05/18 11:55:22 [TRACE] dag/walk: vertex "azurerm_storage_container.kafka" is waiting for "azurerm_storage_account.kafka"
2020/05/18 11:55:22 [TRACE] dag/walk: vertex "azurerm_hdinsight_kafka_cluster.main" is waiting for "azurerm_storage_container.kafka"
2020/05/18 11:55:22 [TRACE] dag/walk: vertex "provider.azurerm (close)" is waiting for "azurerm_hdinsight_kafka_cluster.main"
2020/05/18 11:55:24 [TRACE] dag/walk: vertex "root" is waiting for "provider.azurerm (close)"
2020/05/18 11:55:27 [TRACE] dag/walk: vertex "azurerm_storage_container.kafka" is waiting for "azurerm_storage_account.kafka"
2020/05/18 11:55:27 [TRACE] dag/walk: vertex "azurerm_hdinsight_kafka_cluster.main" is waiting for "azurerm_storage_container.kafka"
2020/05/18 11:55:27 [TRACE] dag/walk: vertex "provider.azurerm (close)" is waiting for "azurerm_hdinsight_kafka_cluster.main"
2020/05/18 11:55:29 [TRACE] dag/walk: vertex "root" is waiting for "provider.azurerm (close)"
2020/05/18 11:55:32 [TRACE] dag/walk: vertex "azurerm_hdinsight_kafka_cluster.main" is waiting for "azurerm_storage_container.kafka"
2020/05/18 11:55:32 [TRACE] dag/walk: vertex "azurerm_storage_container.kafka" is waiting for "azurerm_storage_account.kafka"
2020/05/18 11:55:32 [TRACE] dag/walk: vertex "provider.azurerm (close)" is waiting for "azurerm_hdinsight_kafka_cluster.main"
2020/05/18 11:55:34 [TRACE] dag/walk: vertex "root" is waiting for "provider.azurerm (close)"
2020/05/18 11:55:37 [TRACE] dag/walk: vertex "azurerm_storage_container.kafka" is waiting for "azurerm_storage_account.kafka"
2020/05/18 11:55:37 [TRACE] dag/walk: vertex "azurerm_hdinsight_kafka_cluster.main" is waiting for "azurerm_storage_container.kafka"
2020/05/18 11:55:37 [TRACE] dag/walk: vertex "provider.azurerm (close)" is waiting for "azurerm_hdinsight_kafka_cluster.main"
2020/05/18 11:55:39 [TRACE] dag/walk: vertex "root" is waiting for "provider.azurerm (close)"
2020/05/18 11:55:42 [TRACE] dag/walk: vertex "azurerm_storage_container.kafka" is waiting for "azurerm_storage_account.kafka"
2020/05/18 11:55:42 [TRACE] dag/walk: vertex "azurerm_hdinsight_kafka_cluster.main" is waiting for "azurerm_storage_container.kafka"
2020/05/18 11:55:42 [TRACE] dag/walk: vertex "provider.azurerm (close)" is waiting for "azurerm_hdinsight_kafka_cluster.main"
2020/05/18 11:55:44 [TRACE] dag/walk: vertex "root" is waiting for "provider.azurerm (close)"
2020/05/18 11:55:47 [TRACE] dag/walk: vertex "azurerm_storage_container.kafka" is waiting for "azurerm_storage_account.kafka"
2020/05/18 11:55:47 [TRACE] dag/walk: vertex "azurerm_hdinsight_kafka_cluster.main" is waiting for "azurerm_storage_container.kafka"
2020/05/18 11:55:47 [TRACE] dag/walk: vertex "provider.azurerm (close)" is waiting for "azurerm_hdinsight_kafka_cluster.main"
2020/05/18 11:55:49 [TRACE] dag/walk: vertex "root" is waiting for "provider.azurerm (close)"
```

### Expected Behavior
Terraform plan should work, upgrade provider, apply necessary changes, etc. Works fine with **1.36.0**

### Actual Behavior
At some point, terraform plan just hangs forever with the above output, had to enable trace logs to be able to see it.

It seems to be affecting only `ZRS` storage accounts, this might be a hint for a bug.

### Steps to Reproduce
1. Update provider to 1.44.0 or 2.10.0
2. Run terraform plan

### References

We are having this issue for quite some time now. I've opened https://github.com/terraform-providers/terraform-provider-azurerm/issues/4986 to show this and it was marked as fixed a while ago. We never had the need to upgrade from 1.36 until today and when we did, we faced the same problem (we tried with 1.44 and 2.10).

**Comment by lrxtom2** [comment] 2020-05-19 15:00
@guitmz , Thanks for opening the issue!
Sorry for that I have tried but could not reproduce the issue at my local environment with terraform (v12.20, v12.10) and azurerm v2.10.0. Configuration attached below. Or could you please provide more information about that?

**TF Code**
```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-10102"
  location = "westeurope"
}

resource "azurerm_storage_account" "kafka" {
  name                     = replace("${terraform.workspace}kafka", "-", "")
  resource_group_name      = azurerm_resource_group.test.name
  location                 = azurerm_resource_group.test.location
  account_tier             = "Standard"
  account_replication_type = "ZRS"
}

resource "azurerm_storage_container" "kafka" {
  name                  = replace("${terraform.workspace}kafka", "-", "")
  storage_account_name  = azurerm_storage_account.kafka.name
  container_access_type = "private"
}
```

**Plan result**
![image](https://user-images.githubusercontent.com/20538091/82342550-53951200-9a24-11ea-99e8-0351f9df9699.png)

**Comment by skobzar** [comment] 2021-02-24 16:26
I have same issue:
Terraform v0.14.7
terraform-provider-azurerm_v2.48.0_x5

Terraform hangs for long time and ends up with error like this when I run plan / apply / destroy
`Error: Unable to list provider registration status, it is possible that this is due to invalid credentials or the service principal does not have permission to use the Resource Manager API, Azure error: resources.ProvidersClient#List: Failure sending request: StatusCode=0 -- Original Error: Get "https://management.azure.com/subscriptions/d87efa51-3d8e-4bcd-94c9-1e529e699139/providers?api-version=2016-02-01": dial tcp: lookup management.azure.com on [::1]:53: dial udp [::1]:53: socket: address family not supported by protocol`

or
`Error: Error building account: Error getting authenticated object ID: Error listing Service Principals: autorest.DetailedError{Original:(*errors.errorString)(0xc000f78310), PackageType:"azure.BearerAuthorizer", Method:"WithAuthorization", StatusCode:0, Message:"Failed to refresh the Token for request to https://graph.windows.net/3bcb9699-4adb-450f-b490-778162c70026/servicePrincipals?%24filter=appId+eq+%27d22276b6-4a34-44d9-8e27-438396f4a9d8%27&api-version=1.6", ServiceError:[]uint8(nil), Response:(*http.Response)(nil)}`

debug output:
`2021/02/24 18:10:34 [TRACE] dag/walk: vertex "azurerm_storage_account.tfstate (expand)" is waiting for "azurerm_resource_group.tfstate (expand)"
2021/02/24 18:10:34 [TRACE] dag/walk: vertex "output.tfstate_storage_account_name" is waiting for "azurerm_storage_account.tfstate (expand)"
2021/02/24 18:10:34 [TRACE] dag/walk: vertex "output.tfstate_storage_container_name" is waiting for "azurerm_storage_container.tfstate (expand)"
2021/02/24 18:10:39 [TRACE] dag/walk: vertex "meta.count-boundary (EachMode fixup)" is waiting for "output.tfstate_storage_account_name"
2021/02/24 18:10:39 [TRACE] dag/walk: vertex "output.tfstate_storage_container_name" is waiting for "azurerm_storage_container.tfstate (expand)"
2021/02/24 18:10:39 [TRACE] dag/walk: vertex "azurerm_storage_account.tfstate (expand)" is waiting for "azurerm_resource_group.tfstate (expand)"
2021/02/24 18:10:39 [TRACE] dag/walk: vertex "output.tfstate_storage_account_name" is waiting for "azurerm_storage_account.tfstate (expand)"
2021/02/24 18:10:39 [TRACE] dag/walk: vertex "output.tfstate_resource_group_name" is waiting for "azurerm_resource_group.tfstate (expand)"
2021/02/24 18:10:39 [TRACE] dag/walk: vertex "root" is waiting for "provider[\"registry.terraform.io/hashicorp/azurerm\"] (close)"
2021/02/24 18:10:39 [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/azurerm\"] (close)" is waiting for "azurerm_storage_container.tfstate (expand)"
`

It applies not for storage account only and happens in 90% cases. I tried to move state file to local computer but this did not help.

**Comment by varnav** [comment] 2021-03-24 19:05
Same problem.

Terraform v0.14.7
provider registry.terraform.io/hashicorp/azurerm v2.52.0

`[TRACE] dag/walk: vertex "output.share_name" is waiting for "azurerm_storage_share.main (expand)"` - takes forever

**Comment by skobzar** [comment] 2021-03-24 19:10
@varnav I realized that my issues was related to DNS. If you are on Linux please make sure /etc/resolv.conf has working DNS servers.

**Comment by favoretti** [comment] 2021-08-19 13:06
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.

**Closed by favoretti** 2021-08-19 13:06 UTC
Labels: bug, service/storage
