### ISSUE TITLE
Support for [thing]

### ISSUE THREAD

**Issue by gtkterraform** [hashicorp/terraform-provider-azurerm#13547] opened 2021-09-29 10:43 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* azurerm_XXXXX

### Potential Terraform Configuration

resource "azurerm_private_endpoint" "pep" {
  name                = "pep-name
  location            = eastus
  resource_group_name = xyz
  subnet_id = "someid"

  private_service_connection {
    is_manual_connection           = false
    name                           = "App Service Name "
    private_connection_resource_id = "someid"
    subresource_names              = ["sites"]
    private_ip_address_allocation = "static" ---> New Feature
    private_ip_address            = "10.0.0.1"   ---> New Feature for IP  (We need this feature  or else we have to make DNS changes each time we change logic "
  }
}

### References

* #0000

**Comment by tombuildsstuff** [comment] 2021-09-29 10:46
hi @gtkterraform 

Thanks for opening this issue

Taking a look through this appears to be a duplicate of #13061 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #13061 for updates?

Thanks!

**Closed by tombuildsstuff** 2021-09-29 10:46 UTC
Labels: duplicate, enhancement, service/private-link
