### ISSUE TITLE
azurerm_[linux|windows]_virtual_machine: Allow to specify OS disk for import (and make OS disk id an output)

### ISSUE THREAD

**Issue by hofmannma** [hashicorp/terraform-provider-azurerm#20343] opened 2023-02-07 06:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

azurerm_[linux|windows]_virtual_machine does not allow to specify OS disk for creation or import (after Azure site recovery).
The documentation says to use azurerm_virtual_machine instead. However this resource type is deprecated starting 3.x and there is no feature parity anymore.
So if you use a new 3.x feature and want to import a machine after ASR back into terraform it's broken. Cannot use terraform anymore.

### New or Affected Resource(s)/Data Source(s)

azurerm_[linux|windows]_virtual_machine

**Comment by myc2h6o** [comment] 2023-02-08 01:09
Hi @hofmannma this looks same as the feature request #8195, would you mind subscribing to it for update.

**Comment by tombuildsstuff** [comment] 2023-02-08 12:17
hi @hofmannma 

As @myc2h6o has mentioned, this has previously been requested in/is a duplicate of #8195, please subscribe to that issue for updates.

Thanks!

**Closed by tombuildsstuff** 2023-02-08 12:17 UTC
Labels: duplicate, service/virtual-machine
