### ISSUE TITLE
azurerm_pim_eligible_role_assignment 400 error when using null or empty schedule block

### ISSUE THREAD

**Issue by MohnJadden** [hashicorp/terraform-provider-azurerm#22766] opened 2023-08-01 18:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.3

### AzureRM Provider Version

3.67.0

### Affected Resource(s)/Data Source(s)

azurerm_pim_eligible_role_assignment

### Terraform Configuration Files

```hcl
variable "teams" {
  type = map(object({
    team_name            = string
    location             = string
    Owner                = string
    TechnicalContact     = string
    SecurityGroup        = string
    DepartmentName       = string
    City                 = string
    ApplicationGroupType = string
    ApplicationType      = string
    LoadBalancerType     = string
    VDIType = string
    MaximumSessions      = number
  }))
}

resource "azurerm_resource_group" "vdi-rg" {
  for_each = var.teams
  name     = "${each.value.team_name}-VDI"
  location = coalesce(each.value.location, each.key)
  tags = {
    Owner            = coalesce(each.value.Owner, each.key)
    TechnicalContact = coalesce(each.value.TechnicalContact, each.key)
    Location         = coalesce(each.value.City, each.key)
    DepartmentName   = coalesce(each.value.DepartmentName, each.key)
    TeamName         = coalesce(each.value.team_name, each.key)
  }
}

resource "azurerm_pim_eligible_role_assignment" "role-vdi-vmadminpim" {
    for_each             = var.teams
  scope                = "/subscriptions/3f51eae4-8db3-468d-a09d-cb67d67630b4/resourceGroups/${azurerm_resource_group.vdi-rg[each.key].name}"
  role_definition_id = "/subscriptions/3f51eae4-8db3-468d-a09d-cb67d67630b4/providers/Microsoft.Authorization/roleDefinitions/1c0163c0-47e6-4577-8991-ea5c82e286e4"
  principal_id       = coalesce(each.value.SecurityGroup, each.key)

  timeouts {
    create = "10m"
    delete = "10m"
  }
     lifecycle {
    ignore_changes = [
      # Ignore changes to the Schedule block.  It won't take nulls as inputs and we assume that these PIM assignments are meant to live as long as the VDI environment.
      schedule
    ]
  }
}
```

### Debug Output/Panic Output

```shell
{"error":{"code":"RoleAssignmentRequestPolicyValidationFailed","message":"The following policy rules failed: [\"ExpirationRule\"]"}}: timestamp=2023-08-01T14:39:22.604-0400
2023-08-01T14:39:22.604-0400 [ERROR] provider.terraform-provider-azurerm_v3.67.0_x5.exe: Response contains error diagnostic: tf_req_id=15f63ca5-4bae-bb46-8ed2-2225d57fce01 diagnostic_detail="waiting for Role Management Policy: (Principal Id "01b95094-3727-42de-9bfe-f1bd55734554" / Scope "/subscriptions/ourSubscriptionGUID/resourceGroups/rgName" / Role Definition Id "/subscriptions/ourSubscriptionGUID/providers/Microsoft.Authorization/roleDefinitions/1c0163c0-47e6-4577-8991-ea5c82e286e4") to be created: creating Scoped Role Eligibility Schedule Request (Scope: "/subscriptions/ourSubscriptionGUID/resourceGroups/rgName"
Role Eligibility Schedule Request Name: "596b4579-6944-e996-1f2b-e1b5fbdcb67a"): unexpected status 400 with error: RoleAssignmentRequestPolicyValidationFailed: The following policy rules failed: ["ExpirationRule"]" diagnostic_severity=ERROR tf_proto_version=5.3 tf_provider_addr=provider tf_resource_type=azurerm_pim_eligible_role_assignment tf_rpc=ApplyResourceChange @caller=github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/diag/diagnostics.go:55 @module=sdk.proto diagnostic_summary="waiting for Role Management Policy: (Principal Id "01b95094-3727-42de-9bfe-f1bd55734554" / Scope "/subscriptions/ourSubscriptionGUID/resourceGroups/rgName" / Role Definition Id "/subscriptions/ourSubscriptionGUID/providers/Microsoft.Authorization/roleDefinitions/1c0163c0-47e6-4577-8991-ea5c82e286e4") to be created: creating Scoped Role Eligibility Schedule Request (Scope: "/subscriptions/ourSubscriptionGUID/resourceGroups/rgName"
Role Eligibility Schedule Request Name: "596b4579-6944-e996-1f2b-e1b5fbdcb67a"): unexpected status 400 with error: RoleAssignmentRequestPolicyValidationFailed: The following policy rules failed: ["ExpirationRule"]" timestamp=2023-08-01T14:39:22.604-0400
2023-08-01T14:39:22.606-0400 [DEBUG] State storage *remote.State declined to persist a state snapshot
2023-08-01T14:39:22.606-0400 [ERROR] vertex "azurerm_pim_eligible_role_assignment.role-vdi-vmadminpim[\"Team12\"]" error: waiting for Role Management Policy: (Principal Id "01b95094-3727-42de-9bfe-f1bd55734554" / Scope "/subscriptions/ourSubscriptionGUID/resourceGroups/rgName" / Role Definition Id "/subscriptions/ourSubscriptionGUID/providers/Microsoft.Authorization/roleDefinitions/1c0163c0-47e6-4577-8991-ea5c82e286e4") to be created: creating Scoped Role Eligibility Schedule Request (Scope: "/subscriptions/ourSubscriptionGUID/resourceGroups/rgName"
Role Eligibility Schedule Request Name: "596b4579-6944-e996-1f2b-e1b5fbdcb67a"): unexpected status 400 with error: RoleAssignmentRequestPolicyValidationFailed: The following policy rules failed: ["ExpirationRule"]
2023-08-01T14:39:22.609-0400 [DEBUG] provider.terraform-provider-azurerm_v3.67.0_x5.exe: AzureRM Response for https://management.azure.com/subscriptions/ourSubscriptionGUID/resourceGroups/rgName/providers/Microsoft.DesktopVirtualization/workspaces/MTDJumpbox-workspace?api-version=2022-02-10-preview: 
HTTP/2.0 200 OK
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
Date: Tue, 01 Aug 2023 18:39:22 GMT
Expires: -1
Pragma: no-cache
Server: Microsoft-IIS/10.0
Set-Cookie: ARRAffinity=70e38c1ed72db5f7ffb204484a71ad78c423ea1a8a3bd749fefcc9c77560a9e4;Path=/;HttpOnly;Secure;Domain=rdarmprovider-g-us-r0.wvd.microsoft.com
Set-Cookie: ARRAffinitySameSite=70e38c1ed72db5f7ffb204484a71ad78c423ea1a8a3bd749fefcc9c77560a9e4;Path=/;HttpOnly;SameSite=None;Secure;Domain=rdarmprovider-g-us-r0.wvd.microsoft.com
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Accept-Encoding,Accept-Encoding
X-Content-Type-Options: nosniff
X-Ms-Correlation-Id: 1d896bed-0d5a-45f7-ae79-c4d750973911
X-Ms-Correlation-Request-Id: 659d0fb3-bdf6-95a8-8b49-f1a84a113662
X-Ms-Lamport-Ts: 4474978300
X-Ms-Opsarmpath64: L3N1YnNjcmlwdGlvbnMvM2Y1MWVhZTQtOGRiMy00NjhkLWEwOWQtY2I2N2Q2NzYzMGI0L3Jlc291cmNlR3JvdXBzL01UREp1bXBib3gtVkRJL3Byb3ZpZGVycy9NaWNyb3NvZnQuRGVza3RvcFZpcnR1YWxpemF0aW9uL3dvcmtzcGFjZXMvTVRESnVtcGJveC13b3Jrc3BhY2U=
X-Ms-Ratelimit-Remaining-Subscription-Reads: 11999
X-Ms-Request-Id: 15593fae-ccf4-4bc6-9040-2e4a9c4f28f8
X-Ms-Routing-Request-Id: EASTUS:20230801T183922Z:ec7d62d7-3fa1-45ab-bb1b-2d2983b2620c
X-Powered-By: ASP.NET
X-Rate-Limit-Limit: 0
X-Rate-Limit-Remaining: 9223372036854775807
X-Rate-Limit-Reset: 0
```

### Expected Behaviour

Terraform should create an Azure AD PIM eligible role with no expiration date/time.

### Actual Behaviour

Terraform throws an error: 
│ Role Eligibility Schedule Request Name: "596b4579-6944-e996-1f2b-e1b5fbdcb67a"): unexpected status 400 with error: RoleAssignmentRequestPolicyValidationFailed: The following policy rules failed: ["ExpirationRule"]
│
│   with azurerm_pim_eligible_role_assignment.role-vdi-vmadminpim["Team12"],
│   on AzureVDI.tf line 56, in resource "azurerm_pim_eligible_role_assignment" "role-vdi-vmadminpim":
│   56: resource "azurerm_pim_eligible_role_assignment" "role-vdi-vmadminpim" {
│
│ waiting for Role Management Policy: (Principal Id "01b95094-3727-42de-9bfe-f1bd55734554" / Scope "/subscriptions/ourSubscriptionGUID/resourceGroups/rgName" / Role Definition Id     
│ "/subscriptions/ourSubscriptionGUID/providers/Microsoft.Authorization/roleDefinitions/1c0163c0-47e6-4577-8991-ea5c82e286e4") to be created: creating Scoped Role Eligibility Schedule        
│ Request (Scope: "/subscriptions/ourSubscriptionGUID/resourceGroups/rgName"
│ Role Eligibility Schedule Request Name: "596b4579-6944-e996-1f2b-e1b5fbdcb67a"): unexpected status 400 with error: RoleAssignmentRequestPolicyValidationFailed: The following policy rules failed:
│ ["ExpirationRule"]

### Steps to Reproduce

1. Run terraform apply
2. Error occurs

### References

Possibly related to #22608 - that threw a 400 error but with different error text.

**Comment by MohnJadden** [comment] 2023-08-21 12:35
The issue is still occurring in 3.70.

**Comment by MohnJadden** [comment] 2023-09-07 15:49
Still occurring in 3.71.

**Comment by ZarakiKenpachi7** [comment] 2023-09-11 14:03
Hi - So I tried it like this : [ provider version : 3.72 ] 

Ignore the for_each loop

```
resource "azurerm_pim_eligible_role_assignment" "example" {
  for_each = { for item in local.pim_eligible : item.scope => item }

  scope              = each.value.scope
  role_definition_id = data.azurerm_role_definition.example[each.value.role].id
  principal_id       = each.value.principal_id

  schedule {
    start_date_time = time_static.example.rfc3339
    expiration {
      end_date_time = "2024-09-11T11:27:44Z"
      #duration_hours = each.value.expiration_duration
    }
  }

  justification = "Expiration Duration Set"

  ticket {
    number = "1"
    system = "example ticket system"
  }
}
```
I can see that on the [documentation ](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/pim_eligible_role_assignment)it says that I can use either of these in my expiration block : [duration_days](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/pim_eligible_role_assignment#duration_days), [duration_hours](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/pim_eligible_role_assignment#duration_hours), [end_date_time](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/pim_eligible_role_assignment#end_date_time).

Initially I just passed `duration_hours` and it worked fine. Then I commented out my `duration_hours` line and added in `end_date_time` now. The expected behaviour was that it should destroy my current PIM assignment and recreate one with updated "End Time".

When I reran my plan - it shows this :

```
  # azurerm_pim_eligible_role_assignment.example["/providers/Microsoft.Management/managementGroups/mg"] will be created
  + resource "azurerm_pim_eligible_role_assignment" "example" {
      + id                 = (known after apply)
      + justification      = "Expiration Duration Set"
      + principal_id       = "XXXXXXXXXXXXXXXXXXXXXXX"
      + principal_type     = (known after apply)
      + role_definition_id = "/providers/Microsoft.Authorization/roleDefinitions/acdd72a7-3385-48ef-bd42-f606fba81ae7"
      + scope              = "/providers/Microsoft.Management/managementGroups/mg"

      + schedule {
          + start_date_time = "2023-09-11T11:27:44Z"

          + expiration {
              + duration_days  = (known after apply)
              + duration_hours = (known after apply)
              + end_date_time  = "2024-09-11T11:27:44Z"
            }
        }

      + ticket {
          + number = "1"
          + system = "example ticket system"
        }
    }
```

But after running terraform apply - I get this :

```
│ Error: waiting for Role Management Policy: (Principal Id "XXXXXXXXXXXXXXXXX" / Scope "/providers/Microsoft.Management/managementGroups/mg" / Role Definition Id "/providers/Microsoft.Authorization/roleDefinitions/acdd72a7-3385-48ef-bd42-f606fba81ae7") to be created: creating Scoped Role Eligibility Schedule Request (Scope: "/providers/Microsoft.Management/managementGroups/mg"
│ Role Eligibility Schedule Request Name: "359e7b04-9745-97ea-617b-6cdf822fcc99"): unexpected status 400 with error: RoleAssignmentRequestPolicyValidationFailed: The following policy rules failed: ["ExpirationRule"]
│
│   with azurerm_pim_eligible_role_assignment.example["/providers/Microsoft.Management/managementGroups/shubhendu-mg"],
│   on main.tf line 3, in resource "azurerm_pim_eligible_role_assignment" "example":
│    3: resource "azurerm_pim_eligible_role_assignment" "example" {
│
│ waiting for Role Management Policy: (Principal Id "XXXXXXXXXXXXXXXXXXX" / Scope "/providers/Microsoft.Management/managementGroups/mg" / Role Definition Id   
│ "/providers/Microsoft.Authorization/roleDefinitions/acdd72a7-3385-48ef-bd42-f606fba81ae7") to be created: creating Scoped Role Eligibility Schedule Request (Scope:
│ "/providers/Microsoft.Management/managementGroups/mg"
│ Role Eligibility Schedule Request Name: "359e7b04-9745-97ea-617b-6cdf822fcc99"): unexpected status 400 with error: RoleAssignmentRequestPolicyValidationFailed: The following policy    
│ rules failed: ["ExpirationRule"]
```

**Comment by MohnJadden** [comment] 2023-09-12 14:59
Still occurring in 3.72.

**Comment by MohnJadden** [comment] 2023-09-19 14:31
Still occurring in 3.73.  @manicminer could I trouble you for a rough idea on when this will be worked on?

**Comment by IntergalacticBVBA** [comment] 2023-09-20 15:10
Hi @MohnJadden 
If you configure the PIM elegible assignment via the Azure Portal, you get the following restriction.
"Maximum allowed eligible duration is 1 year(s)."

**Comment by ynden** [comment] 2023-10-04 19:01
> @IntergalacticBVBA By default, it's 1 year, but in the settings for a scope, you can allow permanent membership. In our case, all the resource groups we're trying to have TF manage are already enabled for permanent membership - example of one below.
> 
> ![image](https://user-images.githubusercontent.com/26663320/269343314-f6313faf-5019-4591-a8e0-19c5004e94b0.png)

Hey @MohnJadden,

I think this is why you are experiencing this issue.
Reading your terraform code, I see that you are creating a resource group and then applying a PIM eligible assignment on that resource group.

What @IntergalacticBVBA was mentioning is true, and what you were showing in the screenshot is also true. The question is how could you still have the issue then?

What's happening is that you are creating a new resource group, and then try to apply a PIM on that scope. But that scope (i.e: resource group scope) doesn't have the "Permanent eligible assigment" enabled. What you were showing on your screenshot, was probably at the subscription level, but it should be at the resource group level.

If you go check on the PIM, filter by resource group, then you can check the "Allow permanent eligible" should be disabled, hence why the terraform is failing; because at the creation of the resource group, the option is not enabled.

Hope that makes sense, you can confirm once you check please.

Thanks

**Comment by MohnJadden** [comment] 2023-10-04 20:15
@ynden That nailed it on the head.  In the past I'd enabled permanent assignments for other resource groups, but the test RG did not have permanent assignment enabled.  

After enabling permanent assignment, the error did not persist, and the PIM eligible role assignment completed successfully.  

Unfortunately this reveals a bit of a flaw in that we now have to create the RG, navigate manually to it in the Azure portal (there is no support for this in the CLI as far as I can tell), enable permanent assignment, and then create the azurerm_pim_eligible_role.  Since the default maximum time limit is 1 year, we'd have to do something to configure the azurerm_pim_eligible_role schedule block to operate on an end date of current date + 364 days and have it update the role every time we run terraform apply, or configure some other form of automation to keep extending the renewal date.  

Would this be a separate issue to request the role settings eligibility to be added to TF or is this issue enough to cover it?

**Comment by ynden** [comment] 2023-10-04 20:36
> @ynden That nailed it on the head. In the past I'd enabled permanent assignments for other resource groups, but the test RG did not have permanent assignment enabled.
> 
> After enabling permanent assignment, the error did not persist, and the PIM eligible role assignment completed successfully.
> 
> Unfortunately this reveals a bit of a flaw in that we now have to create the RG, navigate manually to it in the Azure portal (there is no support for this in the CLI as far as I can tell), enable permanent assignment, and then create the azurerm_pim_eligible_role. Since the default maximum time limit is 1 year, we'd have to do something to configure the azurerm_pim_eligible_role schedule block to operate on an end date of current date + 364 days and have it update the role every time we run terraform apply, or configure some other form of automation to keep extending the renewal date.
> 
> Would this be a separate issue to request the role settings eligibility to be added to TF or is this issue enough to cover it?

Amazing, glad it worked!

Yeah this is true, there would be a need to do it manually for every scope. When we talk about subscription, it's ok, but at the resource group level, it's when it becomes problematic.

> Would this be a separate issue to request the role settings eligibility to be added to TF or is this issue enough to cover it?

I think it's another issue, because this needs to be done at a scope level, for a specific role. Like:
1. Create the resource group
2. Enable the permanent eligible for the resource group for a specific role
3. Enable PIM for resource group

**Comment by MohnJadden** [comment] 2023-10-05 18:54
@ynden You're right, this does merit having a separate TF resource.  I opened a request; hopefully it gets considered quickly.  

Failing that, @manicminer  - as a stopgap/bridge fix, would there possibly be a way to implement more clarification on the TF error for this issue?  The 400/ExpirationRule error doesn't say _why_ the expiration rule failed; maybe a generic error that says "please make sure you are assigning a PIM eligible role within the settings for the scope" or otherwise would help other folks that might get the issue in the future.

**Comment by Darkfogel** [comment] 2023-10-05 19:23
Doing some piggyback on what @MohnJadden is experiencing, we are currently doing our PIM assignements / enabling elligilibity through a null resource and api calls. For each PIM call, we check is the isExpirationRequired is configured, if not, we change it. Then we do the PIM assignment.

@ynden Can you explain why it'd be better to have a new ressource type for this? The way I see it, using the PIM assignment resource block, having a option block for the role/resource to configure the PIM policy would make sense. 

By seperating them, you would have to create multiple resource for each role configured for a particular resource and have the PIM assignment resource block depends on the specific PIMPolicy.

Example of a possible terraform resource block : 

```
resource "azurerm_pim_eligible_role_assignment" "role_rg_owner" {
  scope                = ## Scope
  role_definition_id   = ##ID of the owner role##
  principal_id         = ## Principal ID

  pim_policy_block {
    isExpirationRequired = false
  }
}
```

Additionals options from the API could be added if needed.

**Comment by MohnJadden** [comment] 2023-10-05 19:41
@Darkfogel I could see a situation where the same people who are setting PIM role settings aren't the same people creating PIM eligible role assignments.  I've been in megacorps where the decision/permission to change PIM settings for an Azure subscriptions rests with Team X, while Team Y has permissions to add new PIM users or groups to the subscription.  Team X's responsibility is risk management/security, Team Y is engineering, and it's logical in this case that Team Y shouldn't be dictating what happens to Team X's resources without approval.  

Team Y's accounts or TF service principals/app registrations/pipelines may not have User Access Administrator or equivalent rights to change settings (likely through some horrible custom role) or they may get flagged if they take actions which attempt to change the settings in logs.  Thus, if Terraform says "this PIM assignment needs to last for 3 years" and company policy is "max assignment length is 1 year with annual review", Team Y's TF would have a fixed assignment start/end which would need to be updated every year.  

It's a really awful use case and I can't stand that I'm advocating for it, but to me it makes sense to have separate TF resources for this: one that says what you can/cannot do with PIM as policy, and one that creates PIM assignments.

**Comment by NasoA** [comment] 2023-11-09 16:12
Still a problem, will this be fixed in any upcoming releases?

**Comment by rstewart89** [comment] 2023-11-22 15:05
> navigate manually to it in the Azure portal (there is no support for this in the CLI as far as I can tell)

Is there any other option to enable this other than manually navigating to the portal? you mentioned nothing in the CLI but is there any API calls we could use?

**Comment by MohnJadden** [comment] 2023-11-27 13:36
> Is there any other option to enable this other than manually navigating to the portal? you mentioned nothing in the CLI but is there any API calls we could use?

It's buried in here: https://learn.microsoft.com/en-us/graph/api/unifiedrolemanagementpolicy-update?view=graph-rest-1.0&tabs=http  Look for unifiedRoleManagementPolicyExpirationRule  

Now the trick is getting TF to do this using modules and not a hodgepodge of API calls.

**Comment by manicminer** [comment] 2023-11-28 20:55
> > Is there any other option to enable this other than manually navigating to the portal? you mentioned nothing in the CLI but is there any API calls we could use?
> 
> It's buried in here: https://learn.microsoft.com/en-us/graph/api/unifiedrolemanagementpolicy-update?view=graph-rest-1.0&tabs=http Look for unifiedRoleManagementPolicyExpirationRule
> 
> Now the trick is getting TF to do this using modules and not a hodgepodge of API calls.

This functionality would need to go into the AzureAD provider as it uses MS Graph.

**Comment by MohnJadden** [comment] 2023-12-04 13:44
@xuzhang3 The problem is there's no way to do that with Terraform yet.  If we're using PIM just for a resource group which is being created by Terraform, we have to create the RG, manually edit the role assignment policy at the RG scope, and then add the PIM role via Terraform.

**Comment by xuzhang3** [comment] 2023-12-06 07:14
@manicminer  you can submit a  feature requirement for role assign policies.

**Comment by drdamour** [comment] 2024-01-13 16:10
fwiw, IMO it seems like the issue reported here isn't actually an issue and its' working exactly as it should.  and this should probably be closed.

but the feature request spawned from this convo #23458 (so close to 23456 :D) def has merit and appears to have a proposed solution with #23295 

thanks for having this thread and being vigilant about it @MohnJadden it really caught me up with my ability to leverage PIM in our terraform only azure stuff which is as of now...a no u can't.

**Closed** 2024-06-13 21:10 UTC
Labels: service/authorization, v/3.x
