### ISSUE TITLE
Adding additional session hosts WVD - Error on Registration Token

### ISSUE THREAD

**Issue by jparr93** [hashicorp/terraform-provider-azurerm#10717] opened 2021-02-24 11:25 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/azurerm v2.48.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

### Affected Resource(s)

*azurerm_virtual_machine_extension
*azurerm_virtual_desktop_host_pool

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_desktop_host_pool" "pooled" {
  name                = var.hostpool_name
  location            = var.hostpool_region
  resource_group_name = var.resource_group_name
  type                = var.hostpool_type
  load_balancer_type  = var.hostpool_loadbalancer_type
  tags                = var.resource_tags

  registration_info {
    expiration_date = local.buildtime
  }
}
locals {
zones = [1,2,3]
regkey = "${azurerm_virtual_desktop_host_pool.pooled.registration_info[0].token}"
buildtime = timeadd("${local.image_build_time}", "5h")
}
resource "azurerm_virtual_machine_extension" "additional_session_host_dscextension" {
  count                      = var.rdsh_count
  name                       = "${var.vm_prefix}${count.index +1}-wvd_dsc"
  virtual_machine_id         = "${azurerm_virtual_machine.main.*.id[count.index]}"
  publisher                  = "Microsoft.Powershell"
  type                       = "DSC"
  type_handler_version       = "2.73"
  auto_upgrade_minor_version = true
  depends_on                 = ["azurerm_virtual_machine_extension.domainJoin"]

 settings = <<SETTINGS
        {
            "ModulesUrl":"https://wvdportalstorageblob.blob.core.windows.net/galleryartifacts/Configuration_7-20-2020.zip",
            "ConfigurationFunction":"Configuration.ps1\\AddSessionHost",
            "properties": {
                "hostPoolName": "${azurerm_virtual_desktop_host_pool.pooled.name}",
                "registrationInfoToken":"${local.regkey}"
            }
        }
    SETTINGS
```

### Expected Behaviour

Deploy an additional session host added to to the host pool

### Actual Behaviour

Error: Provider produced inconsistent final plan

When expanding the plan for
azurerm_virtual_machine_extension.additional_session_host_dscextension[1] to
include new values learned so far during apply, provider
"registry.terraform.io/hashicorp/azurerm" produced an invalid new value for
.settings: was cty.StringVal("        {\r\n
\"ModulesUrl\":\"https://wvdportalstorageblob.blob.core.windows.net/galleryartifacts/Configuration_7-20-2020.zip\",\r\n
\"ConfigurationFunction\":\"Configuration.ps1\\\\AddSessionHost\",\r\n
\"properties\": {\r\n                \"hostPoolName\": \"terrahpoolrk\",\r\n
\"registrationInfoToken\":\"eyJhbGciOiJSUzI1NiIsImtpZCI6IkU3MDE1QTU5NzU5N0Y3RDg1MjMyRTRBOTA3QTU0OTYyNzNBNEIxMjAiLCJ0eXAiOiJKV1QifQ.eyJSZWdpc3RyYXRpb25JZCI6ImEzMzhlYmM5LTMzYWItNDU2Mi1iZDk0LTNiMjRiZDU2Zjg4ZCIsIkJyb2tlclVyaSI6Imh0dHBzOi8vcmRicm9rZXItZy11cy1yMC53dmQubWljcm9zb2Z0LmNvbS8iLCJEaWFnbm9zdGljc1VyaSI6Imh0dHBzOi8vcmRkaWFnbm9zdGljcy1nLXVzLXIwLnd2ZC5taWNyb3NvZnQuY29tLyIsIkVuZHBvaW50UG9vbElkIjoiNjNkNzJjOWYtYmQzNC00YzUyLTg0MzctOGNjYjhhZjM1OTNjIiwiR2xvYmFsQnJva2VyVXJpIjoiaHR0cHM6Ly9yZGJyb2tlci53dmQubWljcm9zb2Z0LmNvbS8iLCJHZW9ncmFwaHkiOiJVUyIsIm5iZiI6MTYxNDE1ODc3NywiZXhwIjoxNjE0MTc2NzYxLCJpc3MiOiJSREluZnJhVG9rZW5NYW5hZ2VyIiwiYXVkIjoiUkRtaSJ9.Fv3FXEi_mhoxM5vXtPUxdjVjSB9Y2yrAocsWsc3POIIkyQ9B-LYmN9D3NElFJUUG-Vb3dlwg_kadqj-Z0VklolaikoqhWyoxdxrnKQstAmh2n26e2ux8EUVtqSADdCx1fN5Gk6JlZ0WVBVH7zaxMgZZtgsqerOqrXyuMJlm9ZxnxrN9y0rWyiI0MsS721SU2CNGy-Rpk2eptm3Qwgx71ilaUfiMeJIU7O_zgjoHa4g_5x_Gf1QoGQiRXncol3IEGIJ-ipCpEWntKDmirUzVWxHqIRQjOzaetflPsOP8Q18dHZMY1qygtY68Jq2sIwtJSRetfYw6JfDG6Mxd07Rk7qw\"\r\n
}\r\n        }\r\n"), but now cty.StringVal("        {\r\n
\"ModulesUrl\":\"https://wvdportalstorageblob.blob.core.windows.net/galleryartifacts/Configuration_7-20-2020.zip\",\r\n
\"ConfigurationFunction\":\"Configuration.ps1\\\\AddSessionHost\",\r\n
\"properties\": {\r\n                \"hostPoolName\": \"terrahpoolrk\",\r\n
\"registrationInfoToken\":\"eyJhbGciOiJSUzI1NiIsImtpZCI6IkU3MDE1QTU5NzU5N0Y3RDg1MjMyRTRBOTA3QTU0OTYyNzNBNEIxMjAiLCJ0eXAiOiJKV1QifQ.eyJSZWdpc3RyYXRpb25JZCI6IjcwZTE0ZTFmLWFhOWMtNGViNC05OTk1LWRhMmExNWQ1NjhiNiIsIkJyb2tlclVyaSI6Imh0dHBzOi8vcmRicm9rZXItZy11cy1yMC53dmQubWljcm9zb2Z0LmNvbS8iLCJEaWFnbm9zdGljc1VyaSI6Imh0dHBzOi8vcmRkaWFnbm9zdGljcy1nLXVzLXIwLnd2ZC5taWNyb3NvZnQuY29tLyIsIkVuZHBvaW50UG9vbElkIjoiNjNkNzJjOWYtYmQzNC00YzUyLTg0MzctOGNjYjhhZjM1OTNjIiwiR2xvYmFsQnJva2VyVXJpIjoiaHR0cHM6Ly9yZGJyb2tlci53dmQubWljcm9zb2Z0LmNvbS8iLCJHZW9ncmFwaHkiOiJVUyIsIm5iZiI6MTYxNDE1OTM1NSwiZXhwIjoxNjE0MTc3MzQ0LCJpc3MiOiJSREluZnJhVG9rZW5NYW5hZ2VyIiwiYXVkIjoiUkRtaSJ9.OoMRh5ILAavxb-Xpj8OC7UDrEQM_TPSf4v-1w1y4pLAyPkzqEHMobzHvQ6YOYx9XYr13MH3F6SuCMMJNhE8oPq-zTMdBcr01uJDUSwDDXWiIrZLWm5mUI8j5Qn2h-8HG4priD2WPhNi_f0hTFZNxsQPOmJtYgPm6klxObT3l4Y4fa6e06tEyFYp9V8Zr9FcnWmVLxuLbNYJc28ePwIKVg4GLY3DKP5mnfh4IsRIZ0JjZyCDns_rpxy0hBpWgH8q5YuOvI_OCEf09JhlccqsolFdlq0p0sicI0nfDx7UefPhBDrOT_QE2Btdiu48YQikCVYwJm765G3eXxLIeFgso2A\"\r\n
}\r\n        }\r\n").

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
### Description
This is after rerunning the terraform to add an additional host to the host pool. It takes the current date and time of the deployment to use as the registration token for the hostpool as they can only be up to 30 days and we potentially have clients that want to add additional hosts later down the line.
### Steps to Reproduce

1. `terraform apply`

* #0000

**Comment by nnellans-acts** [comment] 2021-03-02 13:43
A couple of things:

You need to ignore the "settings" on your DSC extension.  Add this to your DSC extension:

`lifecycle {
  ignore_changes = [ settings ]
}`

Like you said, the registration token is always changing, at least every 30 days.  You don't want existing Session Hosts to see a new registration token after they've already been registered with a Host Pool.  As long as the "count" on your DSC Extensions is changing, then it should trigger for new Session Hosts.

Second, be careful when using the timeadd() function.  This updates every minute, I believe.  So, you may run into an issue where your time changes between plan and apply.  Depends on how you're generating the 'local.image_build_time' local.  If that's static between plan and apply, you should be okay.

**Comment by tombuildsstuff** [comment] 2021-11-15 13:55
hi @Dirgo22 

Thanks for opening this issue.

Taking a look through this appears to be a duplicate of #13793 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #13793 for updates?

Thanks!

**Closed by tombuildsstuff** 2021-11-15 13:55 UTC
Labels: bug, service/virtual-desktops
