### ISSUE TITLE
Inconsistent final plan when a resource depends on 'azurerm_virtual_desktop_host_pool's 'registration_info'

### ISSUE THREAD

**Issue by Dirgo22** [hashicorp/terraform-provider-azurerm#14189] opened 2021-11-15 13:12 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform 1.0.7
AzureRM 2.76.0

### Affected Resource(s)

* `azurerm_virtual_desktop_host_pool`

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_desktop_host_pool" "redacted" {
  location            = azurerm_resource_group.redacted.location
  resource_group_name = azurerm_resource_group.redacted.name

  name          = "wvdwepredacted01"
  friendly_name = "wvdwepredacted01"
  type          = "Pooled"
  maximum_sessions_allowed = 5
  load_balancer_type       = "DepthFirst"
  preferred_app_group_type = "Desktop"
  registration_info {
    expiration_date = formatdate("YYYY-MM-DD'T'hh:mm:ssZ", timeadd(timestamp(), "120m"))
  }
}


resource "azurerm_availability_set" "redacted" {
  name                         = "${local.rdsh_prefix}availabilitySet-${azurerm_resource_group.redacted.location}"
  resource_group_name          = azurerm_resource_group.redacted.name
  location                     = azurerm_resource_group.redacted.location
  platform_update_domain_count = 5
  platform_fault_domain_count  = 2
  managed                      = true
}

resource "azurerm_network_interface" "redacted1" {
  name                = "${local.rdsh_prefix}1-nic"
  resource_group_name = azurerm_resource_group.redacted.name
  location            = azurerm_resource_group.redacted.location
  ip_configuration {
    name                          = "ipconfig"
    subnet_id                     = azurerm_subnet.redacted.id
    private_ip_address_allocation = "Dynamic"
  }
}
resource "azurerm_windows_virtual_machine" "redacted" {
  name                = "${local.rdsh_prefix}0"
  resource_group_name = azurerm_resource_group.redacted.name
  location            = azurerm_resource_group.redacted.location

  size                = "Standard_D4s_v3"
  availability_set_id = azurerm_availability_set.redacted.id
  computer_name       = "${local.rdsh_prefix}0"
  admin_username      = "redacted"
  admin_password      = "redacted"
  source_image_reference {
    publisher = "microsoftwindowsdesktop"
    offer     = "Windows-10"
    sku       = "20h2-evd"
    version   = "latest"
  }
  os_disk {
    caching              = "None" 
    storage_account_type = "StandardSSD_LRS"
  }
  network_interface_ids = [azurerm_network_interface.redacted.id]
  license_type          = "Windows_Client"
}

resource "azurerm_virtual_machine_extension" "redacted1_dsc" {
  name                       = "${local.rdsh_prefix}1-dscextension"
  virtual_machine_id         = azurerm_windows_virtual_machine.redacted.id
  publisher                  = "Microsoft.Powershell"
  type                       = "DSC"
  type_handler_version       = "2.73"
  auto_upgrade_minor_version = true
  settings                   = <<SETTINGS
    {
      "modulesUrl": "redacted",
      "configurationFunction": "redacted",
      "properties": {
        "hostPoolName": "${azurerm_virtual_desktop_host_pool.redacted.name}",
        "registrationInfoToken": "${azurerm_virtual_desktop_host_pool.redacted.registration_info[0].token}"
      }
    }
  SETTINGS
}   
```

### Expected Behaviour

The Terraform should be able to run as many times as desired and update any fields that reference the token

### Actual Behaviour

The first apply will run fine but all subsequent apply's will produce an inconsistent plan

```hcl
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the
following symbols:
  + create
  ~ update in-place

Terraform will perform the following actions:

  # azurerm_virtual_desktop_host_pool.redacted will be updated in-place
  ~ resource "azurerm_virtual_desktop_host_pool" "redacted" {
        id                       = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/RG-WE-P-VDIredacted-001/providers/Microsoft.DesktopVirtualization/hostPools/wvdwepredacted01"
        name                     = "wvdwepredacted01"
        tags                     = {}
        # (9 unchanged attributes hidden)

      ~ registration_info {
          ~ expiration_date = "2021-11-15T13:00:05Z" -> (known after apply)
            # (2 unchanged attributes hidden)
        }
    }

  # azurerm_virtual_machine_extension.redacted1_dsc will be created
  + resource "azurerm_virtual_machine_extension" "redacted1_dsc" {
      + auto_upgrade_minor_version = true
      + id                         = (known after apply)
      + name                       = "vmwepvredacted-1-dscextension"
      + settings                   = (sensitive)
      + type                       = "DSC"
      + type_handler_version       = "2.73"
      + virtual_machine_id         = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/RG-WE-P-VDIredacted-001/providers/Microsoft.Compute/virtualMachines/vmwepvredacted-1"
    }

Plan: 1 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

azurerm_virtual_desktop_host_pool.redacted: Modifying... [id=/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/RG-WE-P-VDIredacted-001/providers/Microsoft.DesktopVirtualization/hostPools/wvdwepredacted01]
azurerm_virtual_desktop_host_pool.redacted: Modifications complete after 1s [id=/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/RG-WE-P-VDIredacted-001/providers/Microsoft.DesktopVirtualization/hostPools/wvdwepredacted01]
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for azurerm_virtual_machine_extension.redacted1_dsc to include new values learned so far
│ during apply, provider "registry.terraform.io/hashicorp/azurerm" produced an invalid new value for .settings:
│ inconsistent values for sensitive attribute.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

A workaround I have used is to set the timestamp to midnight X number of days in the future but this isn't elegant as this results in at least one inconsistent plan a day

### References

* #0000

**Comment by tombuildsstuff** [comment] 2021-11-15 13:55
hi @Dirgo22 

Thanks for opening this issue.

Taking a look through this appears to be a duplicate of #13793 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #13793 for updates?

Thanks!

**Closed by tombuildsstuff** 2021-11-15 13:55 UTC
Labels: duplicate, service/virtual-desktops
