### ISSUE TITLE
autorest/azure: Service returned an error. │ Status=<nil> <nil>

### ISSUE THREAD

**Issue by thanos1983** [hashicorp/terraform-provider-azurerm#17319] opened 2022-06-21 10:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.3

### AzureRM Provider Version

3.10.0

### Affected Resource(s)/Data Source(s)

azurerm_service_plan

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_service_plan" "example" {
  name                = "example"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  os_type             = "Linux" # or Windows both return the same issue
  sku_name            = "I1"
}
```

### Debug Output/Panic Output

```shell
│ Error: creating Service Plan: (Serverfarm Name "example" / Resource Group "example-resources"): web.AppServicePlansClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> <nil>
│ 
│   with module.app_service_plan_linux_func.azurerm_service_plan.plan,
│   on .terraform/modules/app_service_plan_linux_func/AppServicePlan/main.tf line 11, in resource "azurerm_service_plan" "example":
│   11: resource "azurerm_service_plan" "example" {
│ 
│ creating Service Plan: (Serverfarm Name "example" /
│ Resource Group "rgpazewdmlns101dv-anc"):
│ web.AppServicePlansClient#CreateOrUpdate: Failure sending request:
│ StatusCode=0 -- Original Error: autorest/azure: Service returned an error.
│ Status=<nil> <nil>
╵
##[error]Error: The process '/opt/hostedtoolcache/terraform/1.2.3/x64/terraform' failed with exit code 1
```

### Expected Behaviour

Create the plan without failing. According to the official documentation this is how we suppose to use it [azurerm_service_plan](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/service_plan) 

### Actual Behaviour

Failing with the status error null. See std error above.

### Steps to Reproduce

terraform init -upgrade && terraform plan && terraform apply

### Important Factoids

The plan is running on Linux Webhosts.

### References

Not that I am aware of.

**Comment by tombuildsstuff** [comment] 2022-06-21 11:08
hey @thanos1983 

Taking a look through here this appears to be a duplicate of #10858 - where there's an error being returned from the API here but unfortunately the base layer used by the Azure SDK for Go can't parse it - which has previously been reported in #10858.

Whilst not ideal, in the interim it should be possible to find the error being returned from the API in the debug logs (running `TF_LOG=DEBUG terraform apply`) - but this'll ultimately be fixed in #10858 and as such I'm going to close this issue in favour of that one.

Thanks!

**Closed by tombuildsstuff** 2022-06-21 11:08 UTC
Labels: bug, duplicate, upstream-microsoft
