### ISSUE TITLE
`azurerm_kusto_cluster_customer_managed_key` - property not working.

### ISSUE THREAD

**Issue by liuwuliuyun** [hashicorp/terraform-provider-azurerm#18454] opened 2022-09-20 03:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.3

### AzureRM Provider Version

3.21.1

### Affected Resource(s)/Data Source(s)

azurerm_kusto_cluster_customer_managed_key

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {
    # key_vault {
    #   purge_soft_delete_on_destroy       = true
    #   purge_soft_deleted_keys_on_destroy = true
    # }
  }
}

data "azurerm_client_config" "current" {}

resource "azurerm_resource_group" "test" {
  name     = "yunliutest122"
  location = "east us"
}

resource "azurerm_user_assigned_identity" "test" {
  name                = "acctest"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location
}

resource "azurerm_kusto_cluster" "test" {
  name                = "acctestkc"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name

  sku {
    name     = "Dev(No SLA)_Standard_D11_v2"
    capacity = 1
  }

  identity {
    type         = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.test.id]
  }
}

resource "azurerm_key_vault" "test" {
  name                     = "acctestkvyunliu2235"
  location                 = azurerm_resource_group.test.location
  resource_group_name      = azurerm_resource_group.test.name
  tenant_id                = data.azurerm_client_config.current.tenant_id
  sku_name                 = "standard"
  purge_protection_enabled = true
}

resource "azurerm_key_vault_access_policy" "cluster" {
  key_vault_id = azurerm_key_vault.test.id
  tenant_id    = data.azurerm_client_config.current.tenant_id
  object_id    = azurerm_user_assigned_identity.test.principal_id

  key_permissions = ["Get", "UnwrapKey", "WrapKey"]
}

resource "azurerm_key_vault_access_policy" "client" {
  key_vault_id = azurerm_key_vault.test.id
  tenant_id    = data.azurerm_client_config.current.tenant_id
  object_id    = data.azurerm_client_config.current.object_id

  key_permissions = [
    "Create",
    "Delete",
    "Get",
    "List",
    "Purge",
    "Recover",
  ]
}

resource "azurerm_key_vault_key" "test" {
  name         = "test"
  key_vault_id = azurerm_key_vault.test.id
  key_type     = "RSA"
  key_size     = 2048
  key_opts     = ["decrypt", "encrypt", "sign", "unwrapKey", "verify", "wrapKey"]

  depends_on = [
    azurerm_key_vault_access_policy.client,
    azurerm_key_vault_access_policy.cluster,
  ]
}

resource "azurerm_kusto_cluster_customer_managed_key" "test" {
  cluster_id    = azurerm_kusto_cluster.test.id
  key_vault_id  = azurerm_key_vault.test.id
  key_name      = azurerm_key_vault_key.test.name
  key_version   = azurerm_key_vault_key.test.version
  user_identity = azurerm_user_assigned_identity.test.id
}
```

### Debug Output/Panic Output

```shell
Plan: 1 to add, 0 to change, 0 to destroy.
azurerm_kusto_cluster_customer_managed_key.test: Creating...
azurerm_kusto_cluster_customer_managed_key.test: Still creating... [10s elapsed]
azurerm_kusto_cluster_customer_managed_key.test: Still creating... [20s elapsed]
azurerm_kusto_cluster_customer_managed_key.test: Still creating... [30s elapsed]
╷
│ Error: waiting for completion of Kusto Cluster Update "acctestkc" (Resource Group "yunliutest122"): Code="Failed" Message="Internal Server Error"
│
│   with azurerm_kusto_cluster_customer_managed_key.test,
│   on test.tf line 84, in resource "azurerm_kusto_cluster_customer_managed_key" "test":
│   84: resource "azurerm_kusto_cluster_customer_managed_key" "test" {
│
╵
```

**Comment by liuwuliuyun** [comment] 2022-09-20 03:10
This is also related to accTestFailure TestAccKustoClusterCustomerManagedKey_userIdentity

**Comment by liuwuliuyun** [comment] 2022-09-20 03:12
For now, I could determain that root cause is property `key_vault_id` is misnamed and misused. This property should be `key_vault_uri` and in the test case the right config file should be 

resource "azurerm_kusto_cluster_customer_managed_key" "test" {
  cluster_id    = azurerm_kusto_cluster.test.id
  key_vault_id  = azurerm_key_vault.test.vault_uri
  key_name      = azurerm_key_vault_key.test.name
  key_version   = azurerm_key_vault_key.test.version
  user_identity = azurerm_user_assigned_identity.test.id
}

**Comment by liuwuliuyun** [comment] 2022-09-20 03:13
But after applying that, it gives error azurerm_key_vault_key.test: Refreshing state... [id=https://acctestkvyunliu2235.vault.azure.net/keys/test/xxxxxxx]
╷
│ Error: the number of path segments is not divisible by 2 in ""
│
│   with azurerm_kusto_cluster_customer_managed_key.test,
│   on test.tf line 86, in resource "azurerm_kusto_cluster_customer_managed_key" "test":
│   86:   key_vault_id  = azurerm_key_vault.test.vault_uri

**Comment by liuwuliuyun** [comment] 2022-09-20 03:15
So we should make an update to `key_vault_id` property and change it `key_vault_uri` to avoid mislead to users. If we do not change the name for compatibility concern, at least we could change the validation function to make it works.

**Comment by liuwuliuyun** [comment] 2022-09-21 02:33
Currently, I am able to determain that in a PATCH call to service, the server returns 202. But after the PATCH call, the server returns an "Internal Server Error" without any other message for the wait for completion async call.

**Comment by liuwuliuyun** [comment] 2022-09-21 02:37
Example REST call response caught in REST API call.
PATCH https://management.azure.com/subscriptions/xxxxxxxxx/resourceGroups/acctestRG-220921084043399667/providers/Microsoft.Kusto/clusters/acctestkcmwqgg?api-version=2022-02-01 HTTP/1.1

HTTP/1.1 202 Accepted

GET https://management.azure.com/subscriptions/xxxxxxxxx/providers/Microsoft.Kusto/locations/West%20Europe/operationResults/xxxxx?api-version=2022-02-01 HTTP/1.1

{"id":"/subscriptions/xxxxxxxxx/providers/Microsoft.Kusto/locations/West Europe/operationresults/xxxxx","name":"xxxx","status":"Failed","startTime":"2022-09-21T00:53:31.6614027Z","endTime":"2022-09-21T00:53:51.1147303Z","percentComplete":1.0,"properties":{"operationKind":"ServiceConfigurationAlter","provisioningState":"Failed","operationState":"Failed"},"error":{"code":"Failed","message":"Internal Server Error"}}

**Comment by Lucasjuv** [comment] 2022-10-12 01:05
Hi guys I found the same error on my end, the infrastructure is almost the same the only difference is that the cluster is inside a VNET. I also found a workaround using `SystemAssigned, UserAssigned` identity type on the cluster and giving access to the system assigned identity to the keyvault worked. I hope this can help the investigation on this issue. From the looks of it it seems like the problem is on the cluster implementation when using user assigned identities to access the keyvault.

**Comment by Lucasjuv** [comment] 2022-10-12 01:40
My workaround unfortunately create a cyclic dependency with the access policy and cluster system assigned identity and the destruction can't happen normaly.

**Comment by liuwuliuyun** [comment] 2022-10-26 08:16
This could be caused by the API underlying, will test this again once upgraded API is used.

**Comment by liuwuliuyun** [comment] 2022-11-14 02:51
This is a bug caused by underlying API and Microsoft Service Team is working on the fix.

**Comment by codersinthestorm** [comment] 2023-02-01 09:12
Does anyone have the link to an existing microsoft ticket/bug? Or a forum/ discussion thread?

**Comment by liuwuliuyun** [comment] 2023-02-02 06:01
Hi @codersinthestorm, here is the ICM ticket I raised [MS ICM (Internal Only)](https://portal.microsofticm.com/imp/v3/incidents/details/360179749/home) Kusto team said it was an issue with the manifest and will roll back. But the problem still exsits till now.

**Comment by codersinthestorm** [comment] 2023-02-02 06:14
Thanks a lot! We're also hitting this issue, and weirdly enough its with a System-Assigned identity for the cluster- which has worked fine for us in other similar clusters.

**Comment by codersinthestorm** [comment] 2023-02-15 07:18
Just to update here if anyone is still interested in the ticket, the product team deployed a new build apparently, and that has fixed the issue for us.

**Comment by rcskosir** [comment] 2023-06-02 16:35
@liuwuliuyun Thanks for taking the time to submit this issue. Have you been able to test again to see if you are still having this issue, or if it was resolved by the new build @codersinthestorm mentioned?

**Comment by liuwuliuyun** [comment] 2023-06-08 03:32
@rcskosir the issue still remains after I tested it. As well as TestAccKustoClusterCustomerManagedKey_userIdentity continue to fail. I will look again after api upgrade PR https://github.com/hashicorp/terraform-provider-azurerm/pull/21961 got merged.

**Closed** 2023-06-08 04:56 UTC
Labels: bug, upstream/microsoft, service/kusto
