### ISSUE TITLE
Azure store csi driver enablement support with terraform 

### ISSUE THREAD

**Issue by vidyasagarreddyc** [hashicorp/terraform-provider-azurerm#13386] opened 2021-09-16 17:26 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure supporting Storage CSI driver, but no way we can enable plugin/header with terraform

### New or Affected Resource(s)

 azurerm_kubernetes_cluster

### References

https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver

**Comment by favoretti** [comment] 2021-09-21 07:41
Hi there and thank you for reporting this. This appears to be a duplicate of an earlier reported issue #12783, so I'm going to close this one to keep the discussion concise.

**Closed by favoretti** 2021-09-21 07:41 UTC
