### ISSUE TITLE
azurerm_cdn_frontdoor_profile - missing identity block

### ISSUE THREAD

**Issue by Roddys** [hashicorp/terraform-provider-azurerm#23649] opened 2023-10-23 10:16 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

The azurerm_cdn_frontdoor_profile resource is missing the identity block.

There is already a freature request for this, but no one has answered for months:
https://github.com/hashicorp/terraform-provider-azurerm/issues/20289

### New or Affected Resource(s)/Data Source(s)

azurerm_cdn_frontdoor_profile

### Potential Terraform Configuration

```hcl
resource "azurerm_cdn_frontdoor_profile" "shared" {
  name = "fd-${local.app_name}"
  sku_name = "Premium_AzureFrontDoor"
  response_timeout_seconds = 30

  resource_group_name = azurerm_resource_group.shared.name

  identity {
    type = "SystemAssigned"
  }
}
```

**Comment by rcskosir** [comment] 2023-10-23 15:47
Thanks for taking the time to submit this issue. It looks like this is a duplicate of #20289. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of #20289.

**Closed by rcskosir** 2023-10-23 15:47 UTC
Labels: duplicate, enhancement, service/cdn
