### ISSUE TITLE
Error handling in azurerm_linux_function_app

### ISSUE THREAD

**Issue by cimnine** [hashicorp/terraform-provider-azurerm#15799] opened 2022-03-11 08:12 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Terraform (and AzureRM Provider) Version

* Terraform Core version: 1.1.7
* AzureRM Provider version: 2.98

### Terraform Configuration Files

```hcl
resource "azurerm_linux_function_app" "nxt_fn" {
  name                       = "nxtfn2212"
  resource_group_name        = azurerm_resource_group.nxt.name
  location                   = azurerm_resource_group.nxt.location
  service_plan_id            = azurerm_service_plan.app_service_plan.id
  storage_account_name       = azurerm_storage_account.nxt_fn.name
  storage_account_access_key = data.azurerm_storage_account.nxt_fn.primary_access_key

  https_only = true

  identity {
    type = "SystemAssigned"
  }

  auth_settings {
    enabled = false
  }

  app_settings = {
    DOCKER_ENABLE_CI = "true" # Configure Auto-Deployment

    Customer__Name            = var.customer_name
    Customer__DisplayName     = var.customer_display_name
    Customer__DefaultLanguage = var.default_locale

    WEBSITES_ENABLE_APP_SERVICE_STORAGE = false

    FUNCTIONS_EXTENSION_VERSION = "~3"
  }

  site_config {
    always_on          = true
    application_stack {
      docker {
        registry_url = azurerm_container_registry.nxt.login_server
        image_name   = "function"
        image_tag    = "latest"
      }
    }
  }
}
```

### Description / Feedback

During `apply` I got the following error:

```
╷
│ Error: creating Linux Function App: (Site Name "nxt-fn" / Resource Group "nxt-dev"): web.AppsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> <nil>
│
│   with module.nxt_customer["nxt"].azurerm_linux_function_app.nxt_fn,
│   on nxt_customer/fn.tf line 43, in resource "azurerm_linux_function_app" "nxt_fn":
│   43: resource "azurerm_linux_function_app" "nxt_fn" {
│
│ creating Linux Function App: (Site Name "nxt-fn" / Resource Group "nxt-dev"): web.AppsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> <nil>
╵
```

This was not very helpful. I had to enable `DEBUG` logging to get an idea what's going on:

```
{"Code":"Conflict","Message":"Parameter with name FUNCTIONS_EXTENSION_VERSION already exists.","Target":null,
"Details":[{"Message":"Parameter with name FUNCTIONS_EXTENSION_VERSION already exists."},
{"Code":"Conflict"},{"ErrorEntity":{"ExtendedCode":"01013","MessageTemplate":"Parameter with name {0} already exists.",
"Parameters":["FUNCTIONS_EXTENSION_VERSION"],"Code":"Conflict",
"Message":"Parameter with name FUNCTIONS_EXTENSION_VERSION already exists."}}],"Innererror":null}:
timestamp=2022-03-10T09:53:45.868+0100
```

_Line breaks added for better readability_

It would be great to get such errors with the regular error message, instead of what was returned.

### References

n/a

**Comment by tombuildsstuff** [comment] 2022-03-11 08:21
hi @cimnine 

Thanks for opening this issue.

Taking a look through this appears to be a duplicate of #10858 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #10858 for updates?

Thanks!

**Closed by tombuildsstuff** 2022-03-11 08:21 UTC
Labels: duplicate
