### ISSUE TITLE
Azure API Management Operation import crashes plugin

### ISSUE THREAD

**Issue by freddypage** [hashicorp/terraform-provider-azurerm#16020] opened 2022-03-24 15:42 UTC
Hello,

When trying to import an existing API Management operation from Azure into the tfstate, I am getting the following error:

╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-azurerm_v2.99.0_x5.exe plugin:

panic: interface conversion: interface {} is []interface {}, not string

goroutine 93 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/apimanagement/schemaz.FlattenApiManagementOperationParameterExampleContract(0x1ba859c0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/services/apimanagement/schemaz/api_management.go:426 +0x3ff
github.com/hashicorp/terraform-provider-azurerm/internal/services/apimanagement/schemaz.FlattenApiManagementOperationRepresentation(0x1ba9ec00)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/services/apimanagement/schemaz/api_management.go:200 +0x1d7
github.com/hashicorp/terraform-provider-azurerm/internal/services/apimanagement.flattenApiManagementOperationResponseContract(0x1ba9ebe0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/services/apimanagement/api_management_api_operation_resource.go:359 +0x24e
github.com/hashicorp/terraform-provider-azurerm/internal/services/apimanagement.resourceApiManagementApiOperationRead(0x1baa65a0, {0x49afda0, 0x1bc16380})
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/services/apimanagement/api_management_api_operation_resource.go:213 +0x7c5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x1af20310, {0x584be10, 0x1ba803c0}, 0x1baa65a0, {0x49afda0, 0x1bc16380})
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:346 +0x166
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0x1af20310, {0x584be10, 0x1ba803c0}, 0x1bab2a80, {0x49afda0, 0x1bc16380})
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:635 +0x331
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x1aef3bd0, {0x584be10, 0x1ba803c0}, 0x1ba842c0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:576 +0x58d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x1b83cd00, {0x584be70, 0x1b1720a8}, 0x1ba80090)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server/server.go:553 +0x3ac
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x4e50260, 0x1b83cd00}, {0x584be70, 0x1b1720a8}, 0x1ba80060, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x18a
google.golang.org/grpc.(*Server).processUnaryRPC(0x1b356b40, {0x58c60b4, 0x1ae30100}, 0x1ba2d0e0, 0x1b86d218, 0x951c988, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0xd11
google.golang.org/grpc.(*Server).handleStream(0x1b356b40, {0x58c60b4, 0x1ae30100}, 0x1ba2d0e0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1617 +0xa2d
google.golang.org/grpc.(*Server).serveStreams.func1.2(0x1b2225e0, 0x1b356b40, {0x58c60b4, 0x1ae30100}, 0x1ba2d0e0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:940 +0x92
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:938 +0x1a7

Error: The terraform-provider-azurerm_v2.99.0_x5.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by tombuildsstuff** [comment] 2022-03-24 16:06
hi @freddypage 

Thanks for opening this issue.

Taking a look through this appears to be a duplicate of #15810 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #15810 for updates?

Thanks!

**Closed by tombuildsstuff** 2022-03-24 16:06 UTC
Labels: bug, crash, service/api-management
