### ISSUE TITLE
New `enclave_type` does not support type "No" 

### ISSUE THREAD

**Issue by trungklam** [hashicorp/terraform-provider-azurerm#24195] opened 2023-12-12 08:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.3.7

### AzureRM Provider Version

3.84.0

### Affected Resource(s)/Data Source(s)

azurerm_mssql_database/azurerm_mssql_elasticpool

### Terraform Configuration Files

```hcl
resource "azurerm_mssql_database" "main" {
  name                = local.resource_name
  server_id           = local.database_server_id
  elastic_pool_id     = local.elastic_pool_id
  tags                = local.tags
}
```

### Debug Output/Panic Output

```shell
Database Name: "my-testing-db": performing CreateOrUpdate: unexpected status 400 with error: VBSEnclaveResourcePoolInvalidCombination: Adding a database with 'Default' preferredEnclaveType to an elastic pool 'testelasticpool' with 'No' preferredEnclaveType is not supported.
│ Before adding the database to the elastic pool, ensure that the preferredEnclaveType is the same for both the database and the elastic pool. More information can be found on https://aka.ms/AlwaysEncryptedEnableSecureEnclaves
```

### Expected Behaviour

The database created successfully

### Actual Behaviour

New database cannot be added to the elasticpool

### Steps to Reproduce

I executed the script to add a new database to the current elasticpool. Bases on the error, I think we need to specify the new `enclave_type` with `No` value but currently only `Default` and `VBS` was supported

Since the enclave features is still in beta so I don't want to enable it in my elastic pool

**Comment by toreamun** [comment] 2023-12-13 10:38
Version 3.83 is not affected by this issue. The preview future VBS is in practice required to be enable by version 3.84, and VBS must then also be enabled on the elastic pool. This sound more like a bug than an enhancement.

**Comment by WodansSon** [comment] 2023-12-13 21:23
Hi @trungklam, and thank you for opening this issue. The service teams error message is a bit confusing. What it is saying is that the `enclave_type` field is defined for the database, however the existing Elasticpool does not have a value for the `enclave_type` field. In order to add a database to an Elasticpool with the `v3.84.0` provider the database and the elasticpool must have the same value for the `enclave_type` field(e.g., `Default` for the database and `Default` for the Elasticpool in this case). I suspect that the elasticpool resource was created with an older API where the `enclave_type` field did not exist which is why it is missing the `enclave_type` fields value for this resource. If the Elasticpools configuration is in the same file as the database definition you can try running a `terraform refresh` command to pull the new value into the state which should remove that error message from being displayed.

@toreamun:
>  Version 3.83 is not affected by this issue. The preview future VBS is in practice required to be enable by version 3.84, and VBS must then also be enabled on the elastic pool. This sound more like a bug than an enhancement

I understand how it may appear that way to you, however this is due to an incompatibility issue introduced by the new API in `v3.84.0`. The `v3.83.0` provider is using the legacy API where the `enclave_type` field did not exist which is why mixing and matching these resources across two different released versions of the provider will not work.

**Comment by onybo** [comment] 2023-12-15 08:58
I had the same problem, but I was not able to run `terraform apply -refresh-only`
I got the following error message:
`│ Error: Apply not allowed for workspaces with a VCS connection
│
│ A workspace that is connected to a VCS requires the VCS-driven workflow to ensure that the VCS remains the single source of truth.`

I didn't want to start messing with disconnecting my VCS from the workspace etc 
What worked for me was to use Azure CLI to update the elastic pool that had been created earlier (using an older version of the azurerm provider).
Like this:
`
az sql elastic-pool update -n <name of elastic pool> -g <resource group name> --server <server name> --preferred-enclave-type Default
`
After having set the preferred enclave type on the elastic pool, I could run my terraform scripts to add new database to the pool.

**Comment by trungklam** [comment] 2023-12-20 08:34
Hi @WodansSon , I tried the `terraform refresh` but still got the same error. Instead, the solution proposed by onybo works like a charm :). Thank you all !

**Comment by WodansSon** [comment] 2024-01-09 21:09
As a workaround has been posted I am going to close this as resolved. Thanks @onybo for the workaround to this issue.

**Closed by WodansSon** 2024-01-09 21:09 UTC
Labels: enhancement, service/mssql, v/3.x

**Comment by ShortMVitesse** [comment] 2024-01-19 17:00
I dont know if this info makes this worth a re-opening or not. 

if you check the state of your pool before updating it  you'll get a preferredEnclaveType of [], but it shouldnt be that. before 3.83 proivider it was Default when not set in tf. 

```
az sql elastic-pool list --resource-group prd-uks-sqlserver-rg --server prd-uks-sqlserver --query '[].preferredEnclaveType'
[]
```

**Comment by pavlovmilen** [comment] 2024-03-28 14:46
Can this be reopened as an issue please? For those of us who have elastic pool deployments with older azurerm provider it is still a problem.

**Comment by AlreadyPicked** [comment] 2024-04-09 13:58
I think there's a regression. We applied the workaround in january but when adding new database last week, the problem is back. We tried to run the "az sql elastic-pool update" command again to no avail.

I just tried adding the attributes "enclave_type = "Default"" to the elastic pools and the databases but it also. didn't work.
