### ISSUE TITLE
The provider hashicorp/azurerm does not support data source "azurerm_media_services_account"

### ISSUE THREAD

**Issue by jaqw12** [hashicorp/terraform-provider-azurerm#15077] opened 2022-01-23 17:21 UTC
I am trying to use "azurerm_media_services_account" Terraform data source to retrieve the media service account info as below. 
However receiving "The provider hashicorp/azurerm does not support data source azurerm_media_services_account".. when running terraform plan

I even tried with upgrading to latest version of Terraform still getting the same error

Below is the sample code

data"azurerm_media_services_account""media_services_account"{
  name   =.  var.media_services_account_name
  resource_group_name =  var.resource_group_name
}

**Comment by tombuildsstuff** [comment] 2022-01-24 10:04
hi @jaqw12 

At this time there is no Data Source for the Media Services Account, as such it's not shown in the documentation:

<img width="539" alt="Screenshot 2022-01-24 at 11 02 58" src="https://user-images.githubusercontent.com/666005/150762158-8ac676b6-8967-4a82-a8cd-f0678ef19712.png">

As such I'm going to close this issue as working as intended - however if you'd like to open a Feature Request then please [open a new issue completing the Feature Request template](https://github.com/hashicorp/terraform-provider-azurerm/issues/new?assignees=&labels=&template=Feature_Request.md&title=Support+for+%5Bthing%5D).

Thanks!

**Closed by tombuildsstuff** 2022-01-24 10:04 UTC
