### ISSUE TITLE
Azurerm v3.49.0 bug with azurerm_linux_web_app

### ISSUE THREAD

**Issue by Zurina** [hashicorp/terraform-provider-azurerm#21181] opened 2023-03-29 11:48 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

.

### Terraform Version

1.39

### AzureRM Provider Version

3.49.0

### Affected Resource(s)/Data Source(s)

azurerm_linux_web_app

### Terraform Configuration Files

```hcl
Not relevant.
```

### Debug Output/Panic Output

```shell
╷
│ Error: Plugin did not respond
│ 
│   with module.application.azurerm_linux_web_app.backend,
│   on .terraform/modules/application/backend.tf line 319, in resource "azurerm_linux_web_app" "backend":
│  319: resource "azurerm_linux_web_app" "backend" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-azurerm_v3.49.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x49a99e6]

goroutine 142 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/appservice/helpers.expandAadAuthV2Settings({0xc002189960, 0x1, 0x0?})
        github.com/hashicorp/terraform-provider-azurerm/internal/services/appservice/helpers/auth_v2_schema.go:988 +0x606
github.com/hashicorp/terraform-provider-azurerm/internal/services/appservice/helpers.ExpandAuthV2Settings({0xc000d9b860, 0x1, 0x75b6c00?})
        github.com/hashicorp/terraform-provider-azurerm/internal/services/appservice/helpers/auth_v2_schema.go:2059 +0x12a
github.com/hashicorp/terraform-provider-azurerm/internal/services/appservice.LinuxWebAppResource.Update.func1({0x75c4168, 0xc0027978c0}, {0xc0027c0400, {0x75c4c90, 0xc000602c48}, 0xc0005b7680, 0x0, {0x75c60b0, 0xbb25668}})
        github.com/hashicorp/terraform-provider-azurerm/internal/services/appservice/linux_web_app_resource.go:804 +0x1a65
github.com/hashicorp/terraform-provider-azurerm/internal/sdk.(*ResourceWrapper).Resource.func7({0x75c4168, 0xc0027978c0}, 0x1a3185c41dc?, {0x617f780?, 0xc0027c0400?})
        github.com/hashicorp/terraform-provider-azurerm/internal/sdk/wrapper_resource.go:116 +0x15c
github.com/hashicorp/terraform-provider-azurerm/internal/sdk.diagnosticsWrapper.func1({0x75c4168, 0xc0027978c0}, 0x0?, {0x617f780, 0xc0027c0400})
        github.com/hashicorp/terraform-provider-azurerm/internal/sdk/wrapper_resource.go:185 +0xbe
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc0004600e0, {0x75c41a0, 0xc0015f5b90}, 0xd?, {0x617f780, 0xc0027c0400})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:741 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0004600e0, {0x75c41a0, 0xc0015f5b90}, 0xc002386a90, 0xc0005b7500, {0x617f780, 0xc0027c0400})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:847 +0x83a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc001bb09c0, {0x75c41a0?, 0xc0015f5a70?}, 0xc000617ae0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc00142a5a0, {0x75c41a0?, 0xc0015f51d0?}, 0xc000885570)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x68d1600?, 0xc00142a5a0}, {0x75c41a0, 0xc0015f51d0}, 0xc000885500, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00001c000, {0x75d43c0, 0xc0013816c0}, 0xc001d40480, 0xc001426ba0, 0xbae4da0, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1340 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc00001c000, {0x75d43c0, 0xc0013816c0}, 0xc001d40480, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1713 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.51.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.51.0/server.go:963 +0x28a

Error: The terraform-provider-azurerm_v3.49.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

Operation failed: failed running terraform apply (exit 1)

```

### Expected Behaviour

To apply successfully.

### Actual Behaviour

Fails the apply.

### Steps to Reproduce

1. Use azurerm version 3.49.0
2. Use resource of azurerm_linux_web_app
3. Terraform apply

**Comment by aristosvo** [comment] 2023-03-29 12:39
Hi @Zurina !

I think your issue is already covered, but I cannot confirm as not the whole stacktrace is posted. Could you add that part?

**Comment by Zurina** [comment] 2023-03-29 21:35
Hi @aristosvo, sure thing. I've updated the initial comment with the full stacktrace 👍

**Comment by aristosvo** [comment] 2023-03-30 04:56
This is indeed a duplicate of #21110, as such I'll close it for now.

**Closed** 2023-03-30 04:57 UTC
Labels: bug, crash
