### ISSUE TITLE
Cannot update value of Azure Keyvault certificate when purge protection is enabled

### ISSUE THREAD

**Issue by LP0101** [hashicorp/terraform-provider-azurerm#13120] opened 2021-08-24 13:35 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_keyvault_certificate`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behaviour

Updating the value of a certificate should update its value in keyvault rather than trying to recreate it

### Actual Behaviour

Terrraform will not try to just update the existing certificate object. Instead, Terraform will try and recreate the resource entirely. When Purge Protection is enabled, the deleted certificate cannot be purged, and Terraform will encounter a 403 error when purging it. The deleted but not purged certificate will then prevent any future apply from working, as the new cert can't be created with the same name as the deleted cert. Additionally, this behaviour also does not take advantage of the versioning built into AKV.

### Steps to Reproduce

1. Create a certificate in AKV
2. Enable purge-protection on the keyvault
3. Try updating the certificate's value

### References

* #13012

**Comment by tombuildsstuff** [comment] 2021-11-15 13:43
Duplicate of #13012

**Closed by tombuildsstuff** 2021-11-15 13:43 UTC
Labels: bug, service/keyvault
