### ISSUE TITLE
azure VPN gateway not working. Unable to find virtual hub even though it is there

### ISSUE THREAD

**Issue by ac185391** [hashicorp/terraform-provider-azurerm#17063] opened 2022-06-01 17:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.0.2

### AzureRM Provider Version

3.8.0

### Affected Resource(s)/Data Source(s)

azurerm_virtual_hub

### Terraform Configuration Files

```hcl
data "azurerm_virtual_hub" "vhubtest" {
  name                = "test-vhub"
  resource_group_name = "vhub-poc-test"
}

resource "azurerm_vpn_gateway" "vpng" {
  name                = var.vpng_name
  location            = var.vpng_location
  resource_group_name = var.vpng_resource_group_name
  virtual_hub_id      = data.azurerm_virtual_hub.vhubtest.id
  routing_preference  = var.routing_preference
  scale_unit          = var.scale_unit
  tags                = var.tags

  dynamic "bgp_settings" {
    for_each = var.set_bgp == true ? ["true"] : []
    content {
      asn         = var.asn
      peer_weight = var.peer_weight
      dynamic "instance_0_bgp_peering_address" {
        for_each = var.instance_0_custom_ips != null ? [true] : []
        content {
          custom_ips = var.instance_0_custom_ips
        }
      }
      dynamic "instance_0_bgp_peering_address" {
        for_each = var.instance_0_custom_ips != null ? [true] : []
        content {
          custom_ips = var.instance_1_custom_ips
        }

      }
    }
  }
}
```

### Debug Output/Panic Output

```shell
azurerm_vpn_gateway.vpng: Creating...
╷
│ Error: creating Vpn Gateway: (Name "vpng-poc-test" / Resource Group "vhub-poc-test"): network.VpnGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code="NotFound" Message="Resource /subscriptions/****/resourceGroups/vhub-poc-test/providers/Microsoft.Network/virtualHubs/test-vhub not found." Details=[]
│ 
│   with azurerm_vpn_gateway.vpng,
│   on main.tf line 42, in resource "azurerm_vpn_gateway" "vpng":
│   42: resource "azurerm_vpn_gateway" "vpng" {
```

### Expected Behaviour

vpn gateway should have been created

### Actual Behaviour

It is unable to find the Virtual hub even though the Resource Id is absolutely correct for the  virtual hub in the subscription.

### Steps to Reproduce

1. terraform apply

**Comment by neil-yechenwei** [comment] 2022-06-08 07:08
Thanks for raising this issue. Seems I cannot repro this issue with below tf config that is similar with yours. Could you try below tf config to see if the issue still exists?

```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-vpngw-test01"
  location = "eastus"
}

resource "azurerm_virtual_wan" "test" {
  name                = "acctestvwan-test01"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location
}

resource "azurerm_virtual_hub" "test" {
  name                = "acctestvh-test01"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location
  address_prefix      = "10.0.1.0/24"
  virtual_wan_id      = azurerm_virtual_wan.test.id
}

resource "azurerm_vpn_gateway" "test" {
  name                = "acctestVPNG-test01"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  virtual_hub_id      = azurerm_virtual_hub.test.id
  routing_preference  = "Internet"
  scale_unit          = 2

  bgp_settings {
    asn         = 65515
    peer_weight = 0

    instance_0_bgp_peering_address {
      custom_ips = ["169.254.21.5"]
    }

    instance_1_bgp_peering_address {
      custom_ips = ["169.254.21.10"]
    }
  }

  tags = {
      env = "test"
  }
}
```

**Comment by ac185391** [comment] 2022-06-13 17:01
This code works. But I want to run some tests. I will let you know how it goes

**Comment by rcskosir** [comment] 2023-07-20 15:52
Thanks for opening this issue. Since time has passed and @neil-yechenwei was not able to reproduce this issue and the code was able to work for you I am going to mark this issue closed as “can’t reproduce”. If you are able to provide more information regarding the tests you mentioned to help us reproduce this issue we may re-open this issue or open a new issue, thanks!

**Closed by rcskosir** 2023-07-20 15:52 UTC
Labels: bug, service/vpn, v/3.x
