### ISSUE TITLE
Support for not setting capacity for SKU, during an update action, when instances parameter for azurerm_linux_virtual_machine_scale_set is not set

### ISSUE THREAD

**Issue by hui-dai** [hashicorp/terraform-provider-azurerm#17989] opened 2022-08-14 18:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

#17836 made the `instances` field optional, and defaulted it to 0; This only addressed part of the request in #17821 and in effect made ```instances = 0``` implicit.

The semantics for not setting instances parameter need to be different for
`resourceLinuxVirtualMachineScaleSetCreate` and `resourceLinuxVirtualMachineScaleSetUpdate`

Create + not setting instances => default to 0

Update + not setting instances => Do not set the capacity for the SKU in the API call, see: https://docs.microsoft.com/en-us/rest/api/compute/virtual-machine-scale-sets/create-or-update?tabs=HTTP#sku

Use case:
- Ability to modify VMSS independently of its current scale size.

### New or Affected Resource(s)/Data Source(s)

azurerm_linux_virtual_machine_scale_set

**Comment by lonegunmanb** [comment] 2022-08-15 02:34
Hello @hui-dai , thanks for opening this issue. May I ask why shouldn't we update instances capacity in update?

**Comment by hui-dai** [comment] 2022-08-15 05:23
Hello @lonegunmanb , it's not that we shouldn't update the instance capacity in `update`, but that we should only update it if `instances` is specified.
1. If this is an update and the `instances` parameter exists, we update the capacity for the SKU
2. If this is an update and the `instances` parameter does not exist, omit the capacity for the SKU.

Without this feature, we would be forced to make one of two choices when updating a VMSS (let's say we are updating the startup-script):
1. reset the number of instances in the VMSS to whatever it was set before (or 0)
2. figure out (manually or via a custom data-source) what the existing capacity is and set that as the number of instances to avoid a sudden change in capacity

This tight coupling of the VMSS configuration and its current scale size makes deployments cumbersome.  The requested feature would present option 3:
3. Do not set the instances field, and this allows updates to the VMSS to happen independently of scaling.


For an equivalent feature in a different cloud platform, please see: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance_group_manager#target_size

```
[target_size](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance_group_manager#target_size) - (Optional) The target number of running instances for this managed instance group. This value should always be explicitly set unless this resource is attached to an autoscaler, in which case it should never be set
```
In GCP the instance group configuration can be decoupled from the size configuration for the instance group, allowing an autoscaler to modify the capacity independently of other updates to the instance group itself.

This feature request seeks to accomplish the same.

**Comment by lonegunmanb** [comment] 2022-08-15 12:13
Thanks @hui-dai for your explanation. We decided to set `0` as `instance`'s default is because if we omit this argument, the service side will set `0` for us.

If we do as you suggest, we can ignore all out-of-band changes made outside Terraform when we omit `instances` in the Terraform config code file, but that also means we lost ability of drift detection and I think it might violate Terraform's philosophy. Since I cannot determine whether we should do that I'll submit a pr but leave the decision to HashiCorp.

**Comment by lonegunmanb** [comment] 2022-08-15 14:11
An update @hui-dai , my attempt to compose a pr just failed. When we try to import an existing resource with `instances` greater than zero, the provider cannot read the desired status computed by the config file, in other words, the plugin will see an omitted `instances` no matter we'd set it or not. In this case the `terraform import` command will generate an incorrect tf state with `instances` as `0` since we won't set it if we think it has been omitted.

If we want to ignore changes from the service side, we should use `ignore_changes` to do so. I'll try other approach, but for now I cannot give a pr, sorry for that.

**Comment by hui-dai** [comment] 2022-09-16 07:24
Keeping this task alive, this is an important feature to have

**Comment by hui-dai** [comment] 2022-11-04 21:00
keeping this alive, this is still a very important feature to have.

**Comment by lonegunmanb** [comment] 2022-11-08 05:37
Hi @hui-dai sorry for the late reply. I've checked the [latest code](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/compute/linux_virtual_machine_scale_set_resource.go#L750-L766), in update method, the update request's `Sku` property would only be assigned in case we've changed `sku` or `instances` argument.

I've tried the following scenario:

1. Apply `azurerm_linux_virtual_machine_scale_set` without `instances` argument, which will use `0` as default value.
2. Set `disable_password_authentication` to `false`, which will trigger an update.

Since in step 2 I haven't changed `instances` argument, so the update request sent to API server has no `Sku` property at all. Does this behavior meet your requirement? If it doesn't, would you please provide me a minimum code sample with a simple instruction which can reproduce your issue so I can try it on my machine? Thanks!

**Comment by rcskosir** [comment] 2023-09-28 20:13
@hui-dai Thank you for taking the time to open this feature request. Please update to the latest provider to see the changes @lonegunmanb mentions above. I believe the behavior described in the comment above meets your feature request and as such I am going to close this issue. If you find that that is not the case, please provide a minimum code sample with a simple instruction which can reproduce your issue, and we can reopen this request.

**Closed by rcskosir** 2023-09-28 20:13 UTC
Labels: enhancement, waiting-response, service/virtual-machine
