### ISSUE TITLE
Container App Ingress - confusing documentation on traffic_weight

### ISSUE THREAD

**Issue by askaribragimov** [hashicorp/terraform-provider-azurerm#20694] opened 2023-02-28 10:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.8

### AzureRM Provider Version

3.45.0

### Affected Resource(s)/Data Source(s)

azurerm_container_app

### Terraform Configuration Files

```hcl
The documentation on https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/container_app#ingress is confusing.

It reads:

traffic_weight - (Required) A traffic_weight block as detailed below.
Note:
traffic_weight can only be specified when revision_mode is set to Multiple.

Furthermore, below:

A traffic_weight block supports the following:
Note:
This block only applies when revision_mode is set to Multiple.


You might think that traffic_weight is not needed when mode is Single. Yet it is Required indeed, and   when revision_mode is Single, you must add the block, which does not make sense as it is not used according to the docs. Documentation does not tell what to specify in such case at all. 

I have added for Single mode


   traffic_weight {
      latest_revision = true
      percentage      = 100
    }
```
and it worked for me, but it is a confusing omission.
```


### Debug Output/Panic Output

```shell
-
```

### Expected Behaviour

Either make traffic_weight block forbidden and NOT required for revision_mode Single (and assume correct values of 

   traffic_weight {
      latest_revision = true
      percentage      = 100
    }

behind the hood (that would make the most sense to me)

or clarify in documentation what to add to the block in case of revision_mode=Single (makes less sense since the input will not be user-configurable in any case).

**Comment by jtatum** [comment] 2023-07-06 16:44
This appears to be a dupe of #20537.

**Comment by rcskosir** [comment] 2023-07-07 17:42
Thanks for taking the time to submit this issue. And thank you @jtatum for noting the duplication. It looks like this is a duplicate of #20537. We like to try to keep discussions consolidated, so we’re going to close this newer issue in favor of #20537.

**Closed by rcskosir** 2023-07-07 17:42 UTC
Labels: duplicate, documentation, service/container-apps
