### ISSUE TITLE
setting 'secret': Invalid address to set: []string{"secret", "0", "expiration_date"}

### ISSUE THREAD

**Issue by ppatelmunich** [hashicorp/terraform-provider-azurerm#23245] opened 2023-09-12 13:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.3.6

### AzureRM Provider Version

3.59.0

### Affected Resource(s)/Data Source(s)

azurerm_cdn_frontdoor_secret

### Terraform Configuration Files

```hcl
#Front Door
data "azurerm_cdn_frontdoor_profile" "core" {
  name                = "fd-profile-${var.application_name}"
  resource_group_name = var.frontdoor_core.resource_group_name
}

data "azurerm_cdn_frontdoor_secret" "core" {
  name                = "dns-cert-${var.application_name}-secret"
  resource_group_name = var.frontdoor_core.resource_group_name
  profile_name        = data.azurerm_cdn_frontdoor_profile.core.name
}
```

### Debug Output/Panic Output

```shell
n/a
```

### Expected Behaviour

The command terraform plan should go through without any error and the azurerm_cdn_frontdoor_secret resources should be read with expiration_date exported

### Actual Behaviour

│ Error: setting 'secret': Invalid address to set: []string{"secret", "0", "expiration_date"}
│ .....in data "azurerm_cdn_frontdoor_secret" "core":

### Steps to Reproduce

terraform plan

### References

https://github.com/hashicorp/terraform-provider-azurerm/pull/21945

**Comment by rcskosir** [comment] 2023-09-12 14:36
@ppatelmunich Thanks for taking the time to submit this issue. It looks like this is a duplicate of #22124. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of #22124.

**Closed by rcskosir** 2023-09-12 14:36 UTC
Labels: service/cdn, v/3.x
