### ISSUE TITLE
Error: azurerm_eventhub_consumer_group

### ISSUE THREAD

**Issue by labuscpi** [hashicorp/terraform-provider-azurerm#14260] opened 2021-11-19 07:16 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_eventhub_consumer_group`
```
Initializing provider plugins...
- Finding latest version of hashicorp/random...
- Finding hashicorp/azurerm versions matching ">= 2.64.0"...
- Installing hashicorp/azurerm v2.86.0...
- Installed hashicorp/azurerm v2.86.0 (signed by HashiCorp)
- Installing hashicorp/random v3.1.0...
- Installed hashicorp/random v3.1.0 (signed by HashiCorp)
```

### Terraform Configuration Files

```yml
resource "azurerm_eventhub_consumer_group" "Processing-cg" {
  name                = "data"
  resource_group_name = azurerm_eventhub_namespace.namespace.resource_group_name
  namespace_name      = azurerm_eventhub_namespace.namespace.name
  eventhub_name       = azurerm_eventhub.Processing.name
}
```

### Debug Output

```sh
╷
│ Error: parsing "/subscriptions/***/resourceGroups/***/providers/Microsoft.EventHub/namespaces/***/eventhubs/***/consumergroups/***": parsing segment "staticConsumerGroups": expected the segment "consumergroups" to be "consumerGroups"
│ 
│   with module.eventhub.azurerm_eventhub_consumer_group.Processing-cg,
│   on modules/eventhub/02.main.tf line 50, in resource "azurerm_eventhub_consumer_group" "Processing-cg":
│   50: resource "azurerm_eventhub_consumer_group" "Processing-cg" {
│ 
│ parsing
│ "/subscriptions/***/resourceGroups/***/providers/Microsoft.EventHub/namespaces/***/eventhubs/***/consumergroups/***":
│ parsing segment "staticConsumerGroups": expected the segment
│ "consumergroups" to be "consumerGroups"
╵

```

### Expected Behaviour

```curl
"/subscriptions/***/resourceGroups/***/providers/Microsoft.EventHub/namespaces/***/eventhubs/***/consumerGroups/***"
```

### Actual Behaviour

```curl
"/subscriptions/***/resourceGroups/***/providers/Microsoft.EventHub/namespaces/***/eventhubs/***/consumergroups/***"
```
### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by labuscpi** [comment] 2021-11-19 07:19
Not sure if this was a change on the Microsoft Fluent SDK but the path /consumerGroups/ in the URI is case-sensitive from the error received.

**Comment by meizenga** [comment] 2021-11-19 08:13
I reverted to azurerm 2.85. and the issues has gone.

**Comment by labuscpi** [comment] 2021-11-19 08:15
> 
> 
> I reverted to azurerm 2.85. and the issues has gone.

Did the same. 
```
terraform {
  #Specify terraform version
  required_version = ">= 1.0.0"

  # Fix versions of providers. Avoid specifying "version" in "provider" block
  required_providers {
    azurerm = ">= 2.64.0, != 2.86.0"
  }
  backend "azurerm" {}
}
```

**Comment by anderius** [comment] 2021-11-19 11:14
Probably related to https://github.com/hashicorp/terraform-provider-azurerm/issues/14267.

**Comment by tombuildsstuff** [comment] 2021-11-19 11:49
Duplicate of #14266

**Closed by tombuildsstuff** 2021-11-19 11:49 UTC
Labels: bug, service/event-hubs
