### ISSUE TITLE
data source: azurerm_subscriptions limited to 50 subscriptions

### ISSUE THREAD

**Issue by mgismaco** [hashicorp/terraform-provider-azurerm#25219] opened 2024-03-12 15:37 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.0

### AzureRM Provider Version

3.9.4

### Affected Resource(s)/Data Source(s)

azurerm_subscriptions 

### Terraform Configuration Files

```hcl
data "azurerm_subscriptions" "available" {
}

output "name" {
  value = [ for sub in data.azurerm_subscriptions.available.subscriptions : sub.display_name ]
}
```

### Debug Output/Panic Output

```shell
Changes to Outputs:
  + name = [
      + "Azure subscription 1",
      + "sub-xxx",
      + "sub-xxx",
      + "sub-xxx",
      + "sub-xxx",
      + "sub-xxx",
      + "sub-xxx",
      + "sub-xxx",
      + "sub-xxx",
      + "sub-xxx",
      + "sub-xxx",
      + "sub-xxx",
      + "sub-xxx",
      + "sub-xxx",
      + "sub-xxx",
      + "sub-xxx",
      + "sub-xxx",
      + "sub-xxx",
      + "sub-xxx",
      + "sub-xxx",
      + "sub-xxx",
      + "sub-xxx",
      + "sub-xxx",
      + "sub-xxx",
      + "sub-xxx",
      + "sub-xxx",
      + "sub-xxx",
      + "sub-xxx",
      + "sub-xxx",
      + "sub-xxx",
      + "sub-xxx",
      + "sub-xxx",
      + "sub-xxx",
      + "sub-xxx",
      + "sub-xxx",
      + "sub-xxx",
      + "sub-xxx",
      + "sub-xxx",
      + "sub-xxx",
      + "sub-xxx",
      + "sub-xxx",
      + "sub-xxx",
      + "sub-xxx",
      + "sub-xxx",
      + "sub-xxx",
      + "sub-xxx",
      + "sub-xxx",
      + "sub-xxx",
      + "sub-xxx",
      + "sub-xxx"
      ]
```

### Expected Behaviour

Data source should find ALL subscriptions

### Actual Behaviour

Data source will not return more than 50 subscriptions.

**Comment by tombuildsstuff** [comment] 2024-03-12 16:37
hey @mgismaco 

Thanks for opening this issue.

Taking a look through here this appears to be a duplicate of https://github.com/hashicorp/terraform-provider-azurerm/issues/24948 - rather than having multiple issues open tracking the same thing I'm going to close this one in favour of https://github.com/hashicorp/terraform-provider-azurerm/issues/24948, would you mind subscribing to that issue for updates?

Thanks!

**Closed by tombuildsstuff** 2024-03-12 16:37 UTC
Labels: service/subscription, v/3.x
