### ISSUE TITLE
Terraform is not destroying Frontdoor resources in the correct order.

### ISSUE THREAD

**Issue by jasric89** [hashicorp/terraform-provider-azurerm#16744] opened 2022-05-11 10:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.4

### AzureRM Provider Version

2.95.0

### Affected Resource(s)/Data Source(s)

azurerm_frontdoor

### Terraform Configuration Files

```hcl
# Terraform Block
terraform {
  required_version = ">= 1.1.4" 
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 2.95.0"
      #version = ">= 2.86"
    }
    cloudflare = {
      source = "cloudflare/cloudflare"
      version = "~> 3.0"
    }
    random = {
      source  = "hashicorp/random"
      version = ">= 3.0"
    }
  }
  #Terraform State Storage Account
  backend "azurerm" {}
}

# Providers Block
provider "azurerm" {
  features {
    key_vault {
      purge_soft_delete_on_destroy = true
    }
  }
}
provider "azuread" {
  tenant_id     = "VALUE" 
  client_id     = "VALUE"  
  client_secret = "VALUE" 
 Variables per Subscription
}

provider "random" {}
provider "time" {}

provider "cloudflare" {
  api_token = "VALUE"
  email = "VALUE"
}
resource "cloudflare_record" "create_frontdoor_CNAME" {
  zone_id = "VALUE"
  name = "portal-staging.jason.website"
  type = "CNAME"
  ttl = 1
  proxied = false  
  value = "testingfrontdoor.azurefd.net"
}

resource "azurerm_frontdoor" "jccroutingrule" {
  depends_on = [
    cloudflare_record.create_frontdoor_CNAME,
    azurerm_key_vault.jctestingenv_keyvault,
    azurerm_key_vault_certificate.jcimportedcert
  ]
  name                = "testingfrontdoor"
  resource_group_name = azurerm_resource_group.Terraform.name
  #enforce_backend_pools_certificate_name_check = false
  routing_rule {
    name               = "jccroutingrule"
    accepted_protocols = ["Http", "Https"]
    patterns_to_match  = ["/*"]
    frontend_endpoints = ["jccfrontendendpoint","${local.frontendendpoint2}"]
    forwarding_configuration {
      forwarding_protocol = "MatchRequest"
      backend_pool_name   = "jccbackendpool"
    }
  }

  backend_pool_load_balancing {
    name                        = "jccloadbalancesettings"
    sample_size                 = 255
    successful_samples_required = 1
  }

  backend_pool_health_probe {
    name                = "jcchealthprobesettings"
    path                = "/health/probe"
    protocol            = "Https"
    interval_in_seconds = 240
}


  backend_pool {
    name = "jccbackendpool"
    backend {
      host_header = format("portal-staging-westeurope.jason.website")
      address     = format("portal-staging-westeurope.jason.website")
      http_port   = 80
      https_port  = 443
      weight      = 50
      priority    = 1
      enabled     = true
    }

    load_balancing_name = "jccloadbalancesettings"
    health_probe_name   = "jcchealthprobesettings"
  }

  frontend_endpoint {
    name      = "jccfrontendendpoint"
    host_name = format("testingfrontdoor.azurefd.net")
  }

  frontend_endpoint {
    name      = local.frontendendpoint2
    host_name = format("portal-staging.jason.website")
  }

}

resource "azurerm_frontdoor_custom_https_configuration" "portal_staging_https_config" {
  frontend_endpoint_id              = "${azurerm_frontdoor.jccroutingrule.id}/frontendEndpoints/${local.frontendendpoint2}"
  custom_https_provisioning_enabled = true

  custom_https_configuration {
    certificate_source                      = "AzureKeyVault"
    azure_key_vault_certificate_secret_name = "imported-cert"
    azure_key_vault_certificate_vault_id    = azurerm_key_vault.jctestingenv_keyvault.id
  }
}
```

### Debug Output/Panic Output

```shell
Front Door Name: "testingfrontdoor"): performing Delete: frontdoors.FrontDoorsClient#Delete: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="Conflict" Message="Cannot delete frontend endpoint \"portal-staging.jason.website\" because it is still directly or indirectly (using \"afdverify\" prefix) CNAMEd to front door \"testingfrontdoor.azurefd.net\". Please remove the DNS CNAME records and try again."
```

### Expected Behaviour

For Terraform to delete DNS Record before frontdoor, because of [Depends_On] Statement with frontdoor. 

### Actual Behaviour

Terraform errors because the Azure front door sees DNS CNAME. There is a separate issue with the CNAME (issue #11231) with front door but that should not affect terraform from deleting resources in the right order. There was a supposed fix for this issue in #11720 but that obviously has not worked because Terraform is still destroying things in the wrong order. 

### Steps to Reproduce

terraform destroy. 

### Important Factoids

none

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/11231
https://github.com/hashicorp/terraform-provider-azurerm/issues/11715#issuecomment-845582438

**Comment by WodansSon** [comment] 2022-05-18 00:39
@jasric89 thank you for opening this issue. The behavior you are seeing is by design due to the change in the Azure network API. I believe the reason it appears to not be honoring the `depends_on` tag in the parent resource is because you need to add the `depends_on` tag to the `azurerm_frontdoor_custom_https_configuration` resource as well. Since, under the covers, the `azurerm_frontdoor_custom_https_configuration` resource is just a slice of the functionality of the parent resource that has be implemented as an individual resource to make it easier to create in the config file for the Frontdoor. I am going to go ahead and close this issue since this is the expected behavior of the resource. 🚀

**Closed by WodansSon** 2022-05-18 00:39 UTC
Labels: upstream-microsoft
