### ISSUE TITLE
azurerm_storage_container - storage_account_name deprecated but cannot migrate to storage_account_id

### ISSUE THREAD

**Issue by dkirrane** [hashicorp/terraform-provider-azurerm#28053] opened 2024-11-18 12:36 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.8

### AzureRM Provider Version

4.9.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_container

### Terraform Configuration Files

```hcl
resource "azurerm_storage_container" "example" {
  name                  = "vhds"
  storage_account_name  = azurerm_storage_account.this.name
  storage_account_id    = azurerm_storage_account.this.id
  container_access_type = "private"
}
```

### Debug Output/Panic Output

The Terraform Plan shows `Forces replacement` of the container when I add `storage_account_id` and remove the deprecated `storage_account_name`

If it add both `storage_account_id` and `storage_account_name` I get `only one of storage_account_id,storage_account_name can be specified`

### Expected Behaviour

I should be able to migrate from `storage_account_id` and `storage_account_name`
There should be a migration path called out in https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/4.0-overview

### Actual Behaviour

Cannot remove deprecated `storage_account_name`.

### Steps to Reproduce

1. Create an `azurerm_storage_container` with `storage_account_name`
2. Try change it to using `storage_account_id`. Terraform Plan shows `Forces replacement`

### References

* `azurerm_storage_container` - support for the `storage_account_id` property ([#27733](https://github.com/hashicorp/terraform-provider-azurerm/issues/27733))

**Comment by mybayern1974** [comment] 2024-11-19 10:58
Duplicate with #27942

**Comment by rcskosir** [comment] 2024-11-19 14:34
Thanks for taking the time to submit this issue. It looks like this is a duplicate of #27942. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of #27942.

**Closed by rcskosir** 2024-11-19 14:34 UTC
Labels: duplicate, service/storage, v/4.x
