### ISSUE TITLE
Adding azurerm_key_vault key_permissions Rotation Policy Operations

### ISSUE THREAD

**Issue by HSoulat** [hashicorp/terraform-provider-azurerm#14473] opened 2021-12-03 14:55 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

azurerm_key_vault & azurerm_key_vault_access_policy key_permissions aren't supporting following permissions 
- Rotate
- GetRotationPolicy
- SetRotationPolicy

```
Error: expected access_policy.1.key_permissions.11 to be one of [Backup Create Decrypt Delete Encrypt Get Import List Purge Recover Restore Sign UnwrapKey Update Verify WrapKey], got Rotate
```

### New or Affected Resource(s)

* azurerm_key_vault
* azurerm_key_vault_access_policy

### Potential Terraform Configuration

```hcl
resource "azurerm_key_vault" "kv" {
  location = "location"
  name = "kv-name"
  resource_group_name   = "rg"
  sku_name  = "standard"
  tenant_id = "tenant_id"
  purge_protection_enabled = true

  access_policy {
    object_id = "object_id"
    tenant_id = "tenant_id"
    key_permissions = ["List", "Get", "Decrypt", "Encrypt", "Rotate", "GetRotationPolicy", "SetRotationPolicy"]
  }
}
```

### References
* #14473

**Comment by tombuildsstuff** [comment] 2021-12-03 16:04
hi @HSoulat 

Thanks for opening this issue.

Taking a look through this appears to be a duplicate of #14471 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #14471 for updates?

Thanks!

**Closed by tombuildsstuff** 2021-12-03 16:04 UTC
Labels: duplicate, enhancement, service/keyvault
