### ISSUE TITLE
Storage Account resource doesn't pikck up changes made to blob_properties

### ISSUE THREAD

**Issue by hamza-tumturk** [hashicorp/terraform-provider-azurerm#18031] opened 2022-08-18 14:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.5

### AzureRM Provider Version

3.18.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "storage" {
...
  blob_properties {
    delete_retention_policy {
      days = 30
    }
    container_delete_retention_policy {
      days = 30
    }
  }
}
```

### Debug Output/Panic Output

```shell
`No changes. Your infrastructure matches the configuration.`
```

### Expected Behaviour

Once `blob_properties` have been applied setting the data protection settings, no follow-up changes are picked up by terraform.
Even removing the `blob_properties` block doesn't seem to trigger terraform to delete the Data protection settings.

### Actual Behaviour

Terraform should have recognised the code changes  to `blob_properties` attributes `delete_retention_policy` and `container_delete_retention_policy` and show them in the plan/apply.

**Comment by magodo** [comment] 2022-08-19 03:41
@hamza-tumturk In order to disable those settings, you only need to remove them from `blob_properties` block, e.g. disable both `delete_retention_policy` and `container_delete_retention_policy` can be either:

```
blob_properties {}
```

or

```
blob_properties {
  delete_retention_policy           = null
  container_delete_retention_policy = null
}
```

Removing the whole `blob_properties` doesn't make a difference is by design, and the same behavior applies to the other `x_properties` of the `azurerm_storage_account`. The reason for this is to keep the service default when creating the storage account without explicitly specifying them.

**Comment by hamza-tumturk** [comment] 2022-08-19 11:22
@magodo 
I've applied the above to my tf and getting this error
```
│ Error: Unsupported argument
│ 
│   on [main.tf](http://main.tf/) line 45, in resource "azurerm_storage_account" "storage":
│   45:       delete_retention_policy           = null
│ 
│ An argument named "delete_retention_policy" is not expected here. Did you
│ mean to define a block of type "delete_retention_policy"?
```
and
```
│ Error: Unsupported argument
│ 
│   on [main.tf](http://main.tf/) line 46, in resource "azurerm_storage_account" "storage":
│   46:       container_delete_retention_policy = null
│ 
│ An argument named "container_delete_retention_policy" is not expected here.
│ Did you mean to define a block of type "container_delete_retention_policy"?
```

**Comment by magodo** [comment] 2022-08-19 11:37
@hamza-tumturk Sorry for the incorrect message, only the first form `blob_properties {}` works here as the inner properties are *block*, which is not able to be assigned to null.

**Comment by rcskosir** [comment] 2024-06-12 19:54
Thank you for taking the time to raise this! I am going to close this with @magodo‘s response as an answer. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).

**Closed by rcskosir** 2024-06-12 19:54 UTC
Labels: question, service/storage, v/3.x
