### ISSUE TITLE
Possible Error when changing a Runbook

### ISSUE THREAD

**Issue by HarryLeboeuf** [hashicorp/terraform-provider-azurerm#15961] opened 2022-03-23 09:01 UTC
Hello,

While trying to update a runbook I'm getting this error.

 Error: deleting job schedule Id listed by Runbook: 
 (Name "rbk-eu2-prd-edw-002-001-StopSynaps" 
 / Automation Account Name "aut-eu2-prd-edw-002" 
 / Resource Group "rg-prd-edw-001") 
 Job Schedule List:automation.JobScheduleClient#Delete: Failure responding to request: StatusCode=404 -- Original Error: 
 autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" 
 Message="The Resource 'Microsoft.Automation/automationAccounts/rbk-eu2-prd-edw-002-001-StopSynaps' under resource group 
 'rg-prd-edw-001' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"
│
│   with module.provision_aut[0].module.aut_create["aut-02"].module.create_runbooks["rbk-2-1"].azurerm_automation_runbook.rbk,
│   on _modules\general\aut\rbk_create\main.tf line 17, in resource "azurerm_automation_runbook" "rbk":
│   17: resource "azurerm_automation_runbook" "rbk" {

Off course I'm not sure what is wrong, the code itself or the error-reporting section.

But the Message shows that the system is using the runbook name to find the automation account.

Message="The Resource 'Microsoft.Automation/automationAccounts/rbk-eu2-prd-edw-002-001-StopSynaps' under resource group 
 'rg-prd-edw-001' was not found

This is the runbook path.

https://portal.azure.com/....../resourceGroups/rg-prd-edw-001/providers/Microsoft.Automation/automationAccounts/aut-eu2-prd-edw-002/runbooks/rbk-eu2-prd-edw-002-001-StopSynaps/

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

T:\_CommandLine>terraform -v
Terraform v1.0.8
on windows_amd64

Your version of Terraform is out of date! The latest version
is 1.1.7. You can update by downloading from https://www.terraform.io/downloads.html

**Comment by sinbai** [comment] 2022-03-25 09:17
@HarryLeboeuf thank you for opening this issue. Unfortunately, I could not repro the above error with the repro steps below. Could you repro this issue with tf config below? Also, could you provide your tf config and steps to help repro/troubleshooting?

Step1: Run `terrraform apply` with the tf config below.

```

provider "azurerm" {
  features {
   key_vault {
      purge_soft_delete_on_destroy = true
    }
	}
}

terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
	  version = "3.0.0"
    }
  }
}

resource "azurerm_resource_group" "test" {
  name     = "resource-group-sample"
  location = "eastus"
}

resource "azurerm_automation_account" "test" {
  name                = "automation-account-sample"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  sku_name            = "Basic"
}

resource "azurerm_automation_schedule" "test" {
  name                    = "acctestAS-sample"
  resource_group_name     = azurerm_resource_group.test.name
  automation_account_name = azurerm_automation_account.test.name
  frequency               = "Day"
  timezone                = "Etc/UTC"
}

resource "azurerm_automation_runbook" "test" {
  name                    = "Get-AzureVMTutorial"
  location                = azurerm_resource_group.test.location
  resource_group_name     = azurerm_resource_group.test.name
  automation_account_name = azurerm_automation_account.test.name

  log_verbose  = "true"
  log_progress = "true"
  description  = "This is a test runbook for terraform acceptance test"
  runbook_type = "PowerShell"

  content = <<CONTENT
# Some test content
# for Terraform acceptance test
CONTENT

  job_schedule {
    schedule_name = azurerm_automation_schedule.test.name
  }
} 
```

Step2 : Add another azurerm_automation_schedule( adding tf config below), then update schedule_name of `job_schedule`
 with "azurerm_automation_schedule.test1.name", run `terraform apply` command => no errors.

```
resource "azurerm_automation_schedule" "test1" {
  name                    = "acctestAS-sample-another"
  resource_group_name     = azurerm_resource_group.test.name
  automation_account_name = azurerm_automation_account.test.name
  frequency               = "Day"
  timezone                = "Etc/UTC"
}
```

```
 job_schedule {
    schedule_name = azurerm_automation_schedule.test1.name
 }
```

**Comment by rcskosir** [comment] 2023-07-26 19:37
Thanks for opening this issue. Since time has passed and @sinbai was not able to reproduce this issue, I am going to mark this issue closed as “can’t reproduce”. If you are able to provide more information to help us reproduce this issue we may re-open this issue or open a new issue, thanks!

**Closed by rcskosir** 2023-07-26 19:37 UTC
Labels: bug, waiting-response, service/automation
