### ISSUE TITLE
Terraform Trying To Create A Key Vault Multiple Times After Successfully Creating On Previous Run.

### ISSUE THREAD

**Issue by jfe7** [hashicorp/terraform-provider-azurerm#14674] opened 2021-12-20 13:26 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.1.2
AzureRM v2.90.0

### Affected Resource(s)

azurerm_key_vault

azurerm_key_vault_access_policy

### Terraform Configuration Files

```hcl
resource "azurerm_key_vault" "example_kv" {
  name                = "example-kv"
  resource_group_name = azurerm_resource_group.example_rg.name
  location            = azurerm_resource_group.example_rg.location
  tenant_id           = data.azurerm_client_config.current.tenant_id

  sku_name = "standard"

  enabled_for_deployment          = true
  enabled_for_disk_encryption     = false
  enabled_for_template_deployment = false

  network_acls {
    default_action = "Deny"
    bypass         = "AzureServices"
  }
}

resource "azurerm_key_vault_access_policy" "example_ap" {
  key_vault_id = azurerm_key_vault.example_kv.id
  tenant_id    = data.azurerm_client_config.current.tenant_id
  object_id    = data.azurerm_client_config.current.object_id

  key_permissions         = ["Get", "List"]
  certificate_permissions = ["Get", "List"]
  secret_permissions      = ["Get", "List"]
}
```
### Expected Behaviour

Terraform creates the Key Vault and Key Vault Policy successfully and on the next Terraform run, Terraform does not prompt that the resource has been deleted.

### Actual Behaviour

Run #1: Terraform Successfully creates the Key Vault & Key Vault Access Policy, this is visible via the Portal, everything looks as it should do.

Run #2: Terraform reports that the Key Vault and Key Vault Access Policy have been deleted outside of Terraform, so Terraform wants to create the resources again. The Key Vault and Key Vault Access Policy HAVE NOT been deleted, this is clearly visible via the Portal. Terraform Apply reports the resources already exist and must be imported (as expected).

Resources Created Successfully:
```
azurerm_key_vault.example_kv: Creating...
azurerm_key_vault.example_kv: Still creating... [10s elapsed]
azurerm_key_vault.example_kv: Still creating... [20s elapsed]
azurerm_key_vault.example_kv: Still creating... [30s elapsed]
azurerm_key_vault.example_kv: Still creating... [40s elapsed]
azurerm_key_vault.example_kv: Still creating... [50s elapsed]
azurerm_key_vault.example_kv: Still creating... [1m0s elapsed]
azurerm_key_vault.example_kv: Still creating... [1m10s elapsed]
azurerm_key_vault.example_kv: Still creating... [1m20s elapsed]
azurerm_key_vault.example_kv: Still creating... [1m30s elapsed]
azurerm_key_vault.example_kv: Still creating... [1m40s elapsed]
azurerm_key_vault.example_kv: Still creating... [1m50s elapsed]
azurerm_key_vault.example_kv: Still creating... [2m0s elapsed]
azurerm_key_vault.example_kv: Creation complete after 2m2s [id=/subscriptions/{SUBID}/resourceGroups/example-rg/providers/Microsoft.KeyVault/vaults/example_kv]
azurerm_key_vault_access_policy.example_ap: Creating...
azurerm_key_vault_access_policy.example_ap: Creation complete after 9s [id=/subscriptions/{SUBID}/resourceGroups/example-rg/providers/Microsoft.KeyVault/vaults/example_kv/objectId/{OBJECT_ID}]

```

Next Run:
```
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # azurerm_key_vault.example_kv has been deleted
  - resource "azurerm_key_vault" "example_kv" {
      - access_policy                   = [] -> null
      - enable_rbac_authorization       = false -> null
      - enabled_for_deployment          = true -> null
      - enabled_for_disk_encryption     = false -> null
      - enabled_for_template_deployment = false -> null
      - id                              = "/subscriptions/{SUBID}/resourceGroups/example-rg/providers/Microsoft.KeyVault/vaults/example-kv" -> null
      - location                        = "uksouth" -> null
      - name                            = "example-kv" -> null
      - purge_protection_enabled        = false -> null
      - resource_group_name             = "example-rg" -> null
      - sku_name                        = "standard" -> null
      - soft_delete_enabled             = true -> null
      - soft_delete_retention_days      = 90 -> null
      - tenant_id                       = "{TENANTID}" -> null
      - vault_uri                       = "https://example-kv.vault.azure.net/" -> null

      - network_acls {
          - bypass         = "AzureServices" -> null
          - default_action = "Deny" -> null
        }
    }

  # azurerm_key_vault_access_policy.example_ap has been deleted
  - resource "azurerm_key_vault_access_policy" "example_ap" {
      - certificate_permissions = [
          - "Get",
          - "List",
        ] -> null
      - id                      = "/subscriptions/{SUBID}/resourceGroups/example-rg/providers/Microsoft.KeyVault/vaults/example-kv/objectId/{OBJECT_ID}" -> null
      - key_permissions         = [
          - "Get",
          - "List",
        ] -> null
      - key_vault_id            = "/subscriptions/{SUBID}/resourceGroups/example-rg/providers/Microsoft.KeyVault/vaults/example-kv" -> null
      - object_id               = "{OBJECT_ID}" -> null
      - secret_permissions      = [
          - "Get",
          - "List",
        ] -> null
      - tenant_id               = "{TENANTID}" -> null
    }
```

### Steps to Reproduce
Terraform Plan
Terraform Apply
### Important Factoids

Nothing to report, all other resources are working as expected.

### References

* #0000

**Comment by jfe7** [comment] 2021-12-20 13:27
Also, I forgot to mention, I have tried deleting, then purging the Key Vault from the Portal, removing from the state, and then creating the Key Vault again, the same issue occurs again.

**Comment by jfe7** [comment] 2021-12-20 14:14
I have just enabled Debug logs & have found that for some reason, Terraform is running a GET on the Key Vault using the wrong subscription ID? 

It is using the subscription ID from a second azurerm provider block which has an alias, I have not specified this alias in the resource block as you can see above.

**Comment by olofspango-cg** [comment] 2021-12-20 15:21
I'm facing the exact same issue right now. Key vault creation successful, but upon next terraform plan, it says "keyvault has been deleted".

When I compare the resource ID in the terraform state with the Resource ID specified in the Azure Portal, they are identical.

**Comment by jfe7** [comment] 2021-12-21 09:16
> I'm facing the exact same issue right now. Key vault creation successful, but upon next terraform plan, it says "keyvault has been deleted".
> 
> When I compare the resource ID in the terraform state with the Resource ID specified in the Azure Portal, they are identical.
> 
> Workaround that seems to work is to specify provider explicitly for each keyvault resource...
> 
> ```
> resource "azurerm_key_vault" "qa" {  
>   name                = "kv-qa"
>   tenant_id           = data.azurerm_client_config.current.tenant_id
>   resource_group_name = data.azurerm_resource_group.common.name
>   location            = data.azurerm_resource_group.common.location
>   provider            = azurerm
> ```

I actually tried this as-well and it does not fix my issue, I still get the same, however, I did notice, it is very random.

I run terraform Plan twice in succession, the first one picked up the Key Vault had been created but the Access Policy hadn't, the next run didn't pick up either and wanted to create them both!

**Comment by tombuildsstuff** [comment] 2021-12-23 10:32
hi @jfe7 

Thanks for opening this issue.

Taking a look through here unfortunately this is a configuration question rather than a bug in the Provider - this forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Closed by tombuildsstuff** 2021-12-23 10:32 UTC
Labels: question, service/keyvault

**Comment by jfe7** [comment] 2021-12-23 10:49
> hi @jfe7
> 
> Thanks for opening this issue.
> 
> Taking a look through here unfortunately this is a configuration question rather than a bug in the Provider - this forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).
> 
> Thanks!

Hi,
This is not a configuration issue, this is a bug, multiple people seem to be having the same issue, can you reopen this please?

The above is just a workaround, which doesn't actually resolve the problem anyway.

Thanks

**Comment by tombuildsstuff** [comment] 2021-12-23 11:23
@jfe7 unfortunately, as mentioned above - this is a configuration issue and not a bug in the Azure Provider - as such unfortunately we won't be reopening this issue, since this isn't something we can fix in the Provider, but instead needs to be fixed in your Terraform Configuration.

Since this issue is only for tracking Bugs and Feature Requests in the Azure Provider - we ask instead that Configuration Questions are opened [on the Community Discuss forum](https://discuss.hashicorp.com) - so I'd suggest opening an issue there where someone should be able to take a look.

Thanks!
