### ISSUE TITLE
does azurerm_linux_web_app rersource create an azure container app

### ISSUE THREAD

**Issue by waylew-lexis** [hashicorp/terraform-provider-azurerm#14478] opened 2021-12-03 19:59 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

Is this resource for the new container app service? https://docs.microsoft.com/en-us/azure/container-apps/orwill there be separate resources for that?

**Comment by stephen-eidson-ignw** [comment] 2022-03-25 15:51
This is a potential duplicate of #14122

**Comment by katbyte** [comment] 2022-03-25 17:59
Thanks @stephen-eidson-ignw - this does seem to be a dup, as such i'm going to close this in favour of the older issue

**Closed by katbyte** 2022-03-25 17:59 UTC
Labels: question
