### ISSUE TITLE
Application Gateway not setting the correct default ssl policy

### ISSUE THREAD

**Issue by vmartinlantek** [hashicorp/terraform-provider-azurerm#22218] opened 2023-06-20 07:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.6

### AzureRM Provider Version

3.61.0

### Affected Resource(s)/Data Source(s)

azurerm_application_gateway

### Terraform Configuration Files

```hcl
resource "azurerm_application_gateway" "application_gateway" {
    name                = "agw-${var.product_alias}-${var.subscription_alias}-${var.region_alias}"
    resource_group_name = azurerm_resource_group.resource_group.name
    location            = azurerm_resource_group.resource_group.location

    ssl_policy {
        cipher_suites        = local.cipher_suites
        min_protocol_version = "TLSv1_2"
        policy_type          = "CustomV2"
    }
}
```

### Debug Output/Panic Output

```shell
https://gist.github.com/vmartinlantek/e6f862cc001d29420ca5f39c8492a9ad
```

### Expected Behaviour

The application gateway should be created with the general ssl policy CustomV2.

    ssl_policy {
        cipher_suites        = local.cipher_suites
        min_protocol_version = "TLSv1_2"
        policy_type          = "CustomV2"
    }

### Actual Behaviour

Instead it is provisioned with the default config (AppGwSslPolicy20150501 & Predefined), as it always tries to perform this update:

```
+ min_protocol_version = "TLSv1_2"
          - policy_name          = "AppGwSslPolicy20150501" -> null
          ~ policy_type          = "Predefined" -> "CustomV2"
            # (1 unchanged attribute hidden)
```

It apparently succeeds, but when you inspect the terraform state, it still shows the wrong values and the gateway ssl policy hasn't been set.

You need to manually set the policy with `az network application-gateway ssl-policy set` for it to work. Once manually set, if you run a terraform apply again, then the config is not overwritten to the default one (AppGwSslPolicy20150501 & Predefined). It seems like it is not applying it at at all.

### Steps to Reproduce

terrafom init

terraform apply

check the gateway ssl config with `az-network-application-gateway-ssl-policy-show`. Instead of CustomV2 ssl policy the gateway is using Predefined + AppGwSslPolicy20150501

### Important Factoids

nope

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/20135

**Comment by rcskosir** [comment] 2023-06-20 18:25
Thanks for taking the time to submit this issue. It looks like this is a duplicate of #20135. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of #20135. 
Please vote on that issue by adding a 👍 to the original issue to help the community and maintainers prioritize this request

**Closed by rcskosir** 2023-06-20 18:25 UTC
Labels: duplicate, service/application-gateway
