### ISSUE TITLE
Backward compatible issue since version 2.93.0

### ISSUE THREAD

**Issue by herquan-docusign** [hashicorp/terraform-provider-azurerm#18695] opened 2022-10-11 05:37 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

Azure "Resource and resource group names are case-insensitive unless specifically noted in the valid characters column." [(See document)](https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules) and data source in terraform can get exact information (including resource id) through arguments like resource name no matter what case the it is. However since version 2.93.0 instead of using API to query resource id the change concatenates resource id from argument values (like resource name and resource group name). As a result, if the case of argument value doesn't match the value in resource the resource id returned will be no longer correct and cause backward compatibility issue. We may need to keep the original functionality and if we really want to "guess" the resource id we could introduce new flag for this.

### Terraform Version

1.3.2

### AzureRM Provider Version

2.93.0

### Affected Resource(s)/Data Source(s)

azurerm_virtual_hub_connection

### Terraform Configuration Files

```hcl
data "azurerm_virtual_hub" "vhub" {
  # the name of this resource is "foo"
  name                = "fOo"
  resource_group_name = "rg_group"
}

output v1{
  value=data.azurerm_virtual_hub.vhub.id
}
```

### Debug Output/Panic Output

```shell
Changes to Outputs:
  + v1 = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg_group/providers/Microsoft.Network/virtualHubs/fOo"
```

### Expected Behaviour

v1="/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg_group/providers/Microsoft.Network/virtualHubs/foo"

### Actual Behaviour

v1="/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg_group/providers/Microsoft.Network/virtualHubs/fOo"

### Steps to Reproduce

1. Create a azurerm_virtual_hub_connection resource with name of "foo" in resource group "rg_group"
2. Run "terraform plan"

### References

- Could be related to [this fix](https://github.com/hashicorp/terraform-provider-azurerm/pull/14954/files#diff-163cb4b22cef0e7ceb0247e9958a1d427f2659881949b2c43561e6573480bea7)
- [Resource name is case insensitive](https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules)

**Comment by tombuildsstuff** [comment] 2022-10-11 19:01
hi @herquan-docusign 

Unfortunately the document you're referring too is slightly misleading - the ARM Team have confirmed that ARM Specification states that Resource ID Segment Values (as opposed to the Keys for each Segment) are case-insensitive in responses but case-sensitive in Requests - however different APIs implement this differently.

Since Terraform needs a consistent Resource ID to workaround these inconsistencies within the API, the Azure Provider now uses the users provided casing as the Resource ID - meaning that these will be consistent going forwards - however since this is working as intended unfortunately this isn't something we're planning to change. Over time we'll also be re-casing some of the Resource ID Segment Keys returned from the Azure API to workaround issues, for example fixing the Segment Key `resourcegroups` with `resourceGroups` (as is defined in the Swagger but is returned in a different casing from the API) - since per the ARM Team these are supposed to be `camelCased`).

As such at this point in time this is working as intended, and whilst I'd like to thank you for opening this issue - I'm going to close this issue for the moment, however if the recasing above is causing an issue in a specific field/resource then please let us know and we can look into fixing this per-above.

Thanks!

**Closed by tombuildsstuff** 2022-10-11 19:01 UTC
Labels: question
