### ISSUE TITLE
Plugin crash due to interface conversion panic when modifying azurerm_stream_analytics_output_blob

### ISSUE THREAD

**Issue by landalex** [hashicorp/terraform-provider-azurerm#19859] opened 2023-01-04 14:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.9

### AzureRM Provider Version

3.35.0

### Affected Resource(s)/Data Source(s)

azurerm_stream_analytics_output_blob

### Terraform Configuration Files

```hcl
resource "azurerm_stream_analytics_job" "example-job" {
  name                                     = "example-job"
  resource_group_name                      = "example-resource-group"
  location                                 = "West US"
  compatibility_level                      = "1.2"
  data_locale                              = "en-GB"
  output_error_policy                      = "Drop"
  streaming_units                          = 1
  events_late_arrival_max_delay_in_seconds = 5

  transformation_query = <<QUERY
    SELECT * 
    FROM [eventhub-input]
QUERY
}

resource "azurerm_eventhub_consumer_group" "example-consumer-group" {
  name                = "example-consumer-group"
  namespace_name      = "example-eventhub-namespace"
  eventhub_name       = azurerm_eventhub.eventhub.name
  resource_group_name = azurerm_resource_group.resource_group.name
}

resource "azurerm_stream_analytics_job_schedule" "example-schedule" {
  stream_analytics_job_id = azurerm_stream_analytics_job.example-job.id
  start_mode              = "JobStartTime"

  depends_on = [
    azurerm_stream_analytics_job.example-job,
    azurerm_stream_analytics_stream_input_eventhub.example-eventhub-input,
    azurerm_stream_analytics_output_blob.example-blob-output
  ]
}

resource "azurerm_eventhub_namespace" "example-eventhub-namespace" {
  name                = "example-eventhub-namespace"
  location            = "West US"
  resource_group_name = "example-resource-group"
  sku                 = "Standard"
  capacity            = 1
}

resource "azurerm_eventhub" "example-eventhub" {
  name                = "example-eventhub"
  namespace_name      = azurerm_eventhub_namespace.eventhub_namespace.name
  resource_group_name = azurerm_resource_group.resource_group.name
  partition_count     = 1
  message_retention   = 1
}

resource "azurerm_stream_analytics_stream_input_eventhub" "example-eventhub-input" {
  name                         = "example-input"
  stream_analytics_job_name    = azurerm_stream_analytics_job.example-job.name
  resource_group_name          = "example-resource-group"
  eventhub_name                = azurerm_eventhub.example-eventhub.name
  servicebus_namespace         = azurerm_eventhub_namespace.example-eventhub.name
  shared_access_policy_key     = azurerm_eventhub_namespace.example-eventhub.default_primary_key
  shared_access_policy_name    = "RootManageSharedAccessKey"
  eventhub_consumer_group_name = azurerm_eventhub_consumer_group.example-consumer-group.name

  authentication_mode = "ConnectionString"

  serialization {
    type     = "Json"
    encoding = "UTF8"
  }

  depends_on = [
    azurerm_stream_analytics_job.example-job
  ]
}

resource "azurerm_storage_account" "example-storage-account" {
  name                            = "example-storage-account"
  resource_group_name             = "example-resource-group"
  location                        = "West US"
  account_replication_type        = "LRS"
  account_tier                    = "Standard"
  account_kind                    = "StorageV2"
}

resource "azurerm_stream_analytics_output_blob" "example-blob-output" {
  name                      = "example-output"
  stream_analytics_job_name = azurerm_stream_analytics_job.example-job.name
  resource_group_name       = "example-resource-group"
  storage_account_name      = azurerm_storage_account.example-storage-account.name
  storage_account_key       = azurerm_storage_account.example-storage-account.primary_access_key
  storage_container_name    = "example-container"
  path_pattern              = "/"
  date_format               = "yyyy-MM-dd"
  time_format               = "HH"
  batch_max_wait_time       = "00:10:00"
  batch_min_rows            = 10000

  authentication_mode = "ConnectionString"

  serialization {
    type = "Parquet"
  }

  depends_on = [
    azurerm_stream_analytics_job.example-job
  ]
}
```

### Debug Output/Panic Output

```shell
Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The
│ plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The
│ plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The
│ plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The
│ plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with module.thecycle_azure.azurerm_stream_analytics_output_blob.bi-analytics-blob-output[0],
│   on ..\..\..\terraform-azure-backend-module\stream_analytics.tf line 124, in resource "azurerm_stream_analytics_output_blob" "bi-analytics-blob-output":
│  124: resource "azurerm_stream_analytics_output_blob" "bi-analytics-blob-output" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The
│ plugin logs may contain more details.
╵
Releasing state lock. This may take a few moments...

Stack trace from the terraform-provider-azurerm_v3.35.0_x5.exe plugin:

panic: interface conversion: interface {} is int, not int64

goroutine 169 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/streamanalytics.resourceStreamAnalyticsOutputBlobCreateUpdate(0xc002384c80, {0x6532300?, 0xc001e24000})
        github.com/hashicorp/terraform-provider-azurerm/internal/services/streamanalytics/stream_analytics_output_blob_resource.go:184 +0x1511
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x7746140?, {0x7746140?, 0xc0023906f0?}, 0xd?, {0x6532300?, 0xc001e24000?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:729 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc001af27e0, {0x7746140, 0xc0023906f0}, 0xc001f2f520, 0xc002384b00, {0x6532300, 0xc001e24000})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:847 +0x83a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0015cd2d8, {0x7746140?, 0xc0023905d0?}, 0xc001ffa3c0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0013d05a0, {0x7746140?, 0xc002085e30?}, 0xc0015270a0)
        github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x6bacba0?, 0xc0013d05a0}, {0x7746140, 0xc002085e30}, 0xc001527030, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00000e000, {0x7757d40, 0xc000c01380}, 0xc0006ae360, 0xc000653950, 0xb90f3c0, 0x0)
        google.golang.org/grpc@v1.50.1/server.go:1340 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc00000e000, {0x7757d40, 0xc000c01380}, 0xc0006ae360, 0x0)
        google.golang.org/grpc@v1.50.1/server.go:1713 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.50.1/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.50.1/server.go:963 +0x28a

Error: The terraform-provider-azurerm_v3.35.0_x5.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behaviour

The azurerm_stream_analytics_output_blob resource is modified correctly and the apply operation succeeds

### Actual Behaviour

The azurerm plugin crashed during the apply operation and the modification to the azurerm_stream_analytics_output_blob resource was not completed.

### Steps to Reproduce

1. terraform apply

**Comment by jiaweitao001** [comment] 2023-01-05 11:01
Hi @landalex , thanks for opening this issue! I'm trying to reproduce this on my side, but it looks fine so far. Could you please give some more context code here? Thanks.

**Comment by landalex** [comment] 2023-01-05 14:11
Apologies, I should have included more context in the original post. These resources (as seen in the example TF config) were applied and created successfully, then the `azurerm_stream_analytics_output_blob` was modified with a larger `batch_max_wait_time` (in my case it went from 00:02:00 to 00:10:00). When applying this modification, the crash occurred.

**Comment by jiaweitao001** [comment] 2023-01-06 07:29
Thanks @landalex, I'm now seeing errors from the API but not about the plugin though.  Since we are only developing Terraform providers based on service team provided APIs, I'll report the error I saw to the backend service team. Once they get back to me, I'll update here.

**Comment by landalex** [comment] 2023-02-22 09:41
I'm creating a new environment with the aforementioned Stream Analytics infrastructure (see TF example in original post), and it's now crashing even on creation. I believe the `panic: interface conversion: interface {} is int, not int64` error is specifically being hit on [line 184 of stream_analytics_output_blob_resource.go](https://github.com/hashicorp/terraform-provider-azurerm/blob/c39c4b23b22a30be2b4ea90302a0bf979413f726/internal/services/streamanalytics/stream_analytics_output_blob_resource.go#L184). Data validation checks that happen prior make sure that the `batch_min_rows` value is between 0 and 10000, and every value I've tried within that range fails with the crash. Since I'm using Parquet serialization, this property is required and cannot be left out. Given this information, I think the issue might be with data conversion in the Terraform provider and not due to an API error, but I'd love to hear other possibilities.

**Comment by tombuildsstuff** [comment] 2023-02-22 11:28
Taking a look through here I think [this is actually a bug on line 279](https://github.com/hashicorp/terraform-provider-azurerm/blob/c39c4b23b22a30be2b4ea90302a0bf979413f726/internal/services/streamanalytics/stream_analytics_output_blob_resource.go#L279) where this should be being saved into the state as an `int` rather than an `*int64`:

![Screenshot 2023-02-22 at 12 26 01](https://user-images.githubusercontent.com/666005/220606886-c6c96141-7c6b-4d9a-847e-d7a91cb2c009.png)

Meaning that deserializing this as an integer will fail, so by updating the Read function that should fix this

@landalex just to check, when you say this happens during Creation, does the resource get Created in the API (e.g. is there a second crash we need to look into here, or is the stack trace the same)?

**Comment by landalex** [comment] 2023-02-23 09:04
> When you say this happens during Creation, does the resource get Created in the API?
No resource is created, the crash happens before the API call to create the resource.

**Comment by wuxu92** [comment] 2023-03-28 05:37
> > When you say this happens during Creation, does the resource get Created in the API?
> 
> No resource is created, the crash happens before the API call to create the resource.

which azurerm version do you use? the `panic: interface conversion: interface {} is int, not int64`  seems has been fixed in #19732 last year.

**Comment by wuxu92** [comment] 2023-03-28 07:44
> 

have a look at the `d.Set` logic, this kind of set `*int64` to a `TypeInt` field should not cause panic in the `int` type conversion. because it will decode the value to `int` at last then convert to string to store into the result.

https://github.com/hashicorp/terraform-provider-azurerm/blob/60bf7a91575026661204e1c4e917de92d496e553/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/field_writer_map.go#L262-L267

> Taking a look through here I think [this is actually a bug on line 279](https://github.com/hashicorp/terraform-provider-azurerm/blob/c39c4b23b22a30be2b4ea90302a0bf979413f726/internal/services/streamanalytics/stream_analytics_output_blob_resource.go#L279) where this should be being saved into the state as an `int` rather than an `*int64`:
> 
> ![Screenshot 2023-02-22 at 12 26 01](https://user-images.githubusercontent.com/666005/220606886-c6c96141-7c6b-4d9a-847e-d7a91cb2c009.png)
> 
> Meaning that deserializing this as an integer will fail, so by updating the Read function that should fix this
> 
> @landalex just to check, when you say this happens during Creation, does the resource get Created in the API (e.g. is there a second crash we need to look into here, or is the stack trace the same)?

**Comment by wuxu92** [comment] 2023-03-28 07:57
@landalex yes, i do think so. could you please have try with the newer version and give a feedback then。

**Closed** 2023-10-31 14:47 UTC
Labels: bug, crash, waiting-response, service/stream-analytics, v/3.x
