### ISSUE TITLE
invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable

### ISSUE THREAD

**Issue by sohwaje** [hashicorp/terraform-provider-azurerm#20787] opened 2023-03-04 12:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

I configured the Azure AKS Cluster using Terraform. After configuration, some code modifications have occurred. Modifications to other parts worked normally, but when increasing or decreasing the number of pods in "default_node_pool", we encountered the following error.

In particular, the kubernetes provider problem seems to occur when increasing or decreasing "os_disk_size_gb, node_count" of default_node_pool.

I correctly specified the provider of kubernetes and helm on provider.tf as below, and there was no problem at first distribution.

The terrafrom refresh, terraform plan, and terraform application must operate normally.
                
Additional findings include: On provider.tf, read "/.Add and distribute "kube/config". This seems to work well. But what I want is "/.It should work well without specifying "kube/config".

As expected, when terraform plan, terraform refresh, terraform application, "data.azurm_kubernetes_cluster.credentials" can't I read this?

### Terraform Version

Terraform v1.3.7

### AzureRM Provider Version

3.46.0

### Affected Resource(s)/Data Source(s)

data.azurm_kubernetes_cluster.credentials

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "aks" {
  name                                = "${var.cluster_name}-aks"
  location                            = var.location
  resource_group_name                 = data.azurerm_resource_group.aks-rg.name 
  node_resource_group                 = "${var.rgname}-aksnode"  
  dns_prefix                          = "${var.cluster_name}-aks"
  kubernetes_version                  = var.aks_version
  private_cluster_enabled             = var.private_cluster_enabled
  private_cluster_public_fqdn_enabled = var.private_cluster_public_fqdn_enabled
  private_dns_zone_id                 = var.private_dns_zone_id

  default_node_pool {
    name                         = "syspool01"
    vm_size                      = "${var.agents_size}"
    os_disk_size_gb              = "${var.os_disk_size_gb}"
    node_count                   = "${var.agents_count}"
    vnet_subnet_id               = data.azurerm_subnet.subnet.id
    zones                        = [1, 2, 3]
    kubelet_disk_type            = "OS"
    os_sku                       = "Ubuntu"
    os_disk_type                 = "Managed"
    ultra_ssd_enabled            = "false"
    max_pods                     = "${var.max_pods}"
    only_critical_addons_enabled = "true"
    # enable_auto_scaling = true
    # max_count           = ${var.max_count}
    # min_count           = ${var.min_count}
  }


data "azurerm_kubernetes_cluster" "credentials" {
  name                = azurerm_kubernetes_cluster.aks.name
  resource_group_name = data.azurerm_resource_group.aks-rg.name
}

provider "kubernetes" {
  host                   = data.azurerm_kubernetes_cluster.credentials.kube_config[0].host
  username               = data.azurerm_kubernetes_cluster.credentials.kube_config[0].username
  password               = data.azurerm_kubernetes_cluster.credentials.kube_config[0].password
  client_certificate     = base64decode(data.azurerm_kubernetes_cluster.credentials.kube_config[0].client_certificate, )
  client_key             = base64decode(data.azurerm_kubernetes_cluster.credentials.kube_config[0].client_key, )
  cluster_ca_certificate = base64decode(data.azurerm_kubernetes_cluster.credentials.kube_config[0].cluster_ca_certificate, )
}

provider "helm" {
  kubernetes {
    host = data.azurerm_kubernetes_cluster.credentials.kube_config[0].host
    # username               = data.azurerm_kubernetes_cluster.credentials.kube_config[0].username
    # password               = data.azurerm_kubernetes_cluster.credentials.kube_config[0].password
    client_certificate     = base64decode(data.azurerm_kubernetes_cluster.credentials.kube_config[0].client_certificate, )
    client_key             = base64decode(data.azurerm_kubernetes_cluster.credentials.kube_config[0].client_key, )
    cluster_ca_certificate = base64decode(data.azurerm_kubernetes_cluster.credentials.kube_config[0].cluster_ca_certificate, )
  }
}

provider "kubernetes" {
  config_path            = "~/.kube/config". # <=== add this
  host                   = data.azurerm_kubernetes_cluster.credentials.kube_config[0].host
  username               = data.azurerm_kubernetes_cluster.credentials.kube_config[0].username
  password               = data.azurerm_kubernetes_cluster.credentials.kube_config[0].password
  client_certificate     = base64decode(data.azurerm_kubernetes_cluster.credentials.kube_config[0].client_certificate, )
  client_key             = base64decode(data.azurerm_kubernetes_cluster.credentials.kube_config[0].client_key, )
  cluster_ca_certificate = base64decode(data.azurerm_kubernetes_cluster.credentials.kube_config[0].cluster_ca_certificate, )
}
```

### Debug Output/Panic Output

```shell
Error: Kubernetes cluster unreachable: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable

Error: Get "http://localhost/api/v1/namespaces/devcluster-ns": dial tcp [::1]:80: connectex: No connection could be made because the target machine actively refused it.

Error: Get "http://localhost/api/v1/namespaces/devcluster-ns/secrets/devcluster-storage-secret": dial tcp [::1]:80: connectex: No connection could be made because the target machine actively refused it.
```

**Comment by stephybun** [comment] 2023-06-15 13:43
Thanks for raising this issue @sohwaje.

The error message provided doesn't appear to be coming from Azure or from the azurerm provider and it looks like the AKS cluster you're creating in your config is being provisioned correctly without any issue. My only guess is that the error message could be coming from one of the other providers specified in your configuration which are maintained by other teams.

Since the azurerm side appears to be working as intended and this is not a feature request I'm going to close this issue. For configuration related questions I'd refer you to the [Community Discuss forum](https://discuss.hashicorp.com/).

Thanks!

**Closed by stephybun** 2023-06-15 13:43 UTC
Labels: question, service/kubernetes-cluster
