### ISSUE TITLE
azurerm_windows_virtual_machine_scale_set plugin issue

### ISSUE THREAD

**Issue by basoyan7** [hashicorp/terraform-provider-azurerm#17848] opened 2022-08-02 14:31 UTC
Plan: 0 to add, 2 to change, 0 to destroy.
azurerm_windows_virtual_machine_scale_set.agent-pool-vmss: Modifying... [id=/subscriptions/9c2597a3-e391-4d3a-b644-8a9094188071/resourceGroups/wus2-dev-rg/providers/Microsoft.Compute/virtualMachineScaleSets/windows-build-agents-vmss]

azurerm_linux_virtual_machine_scale_set.agent-pool-vmss: Modifying... [id=/subscriptions/9c2597a3-e391-4d3a-b644-8a9094188071/resourceGroups/wus2-dev-rg/providers/Microsoft.Compute/virtualMachineScaleSets/ubuntu-build-agents-vmss]

azurerm_windows_virtual_machine_scale_set.agent-pool-vmss: Still modifying... [id=/subscriptions/9c2597a3-e391-4d3a-b644-...ineScaleSets/windows-build-agents-vmss, 10s elapsed]

azurerm_linux_virtual_machine_scale_set.agent-pool-vmss: Still modifying... [id=/subscriptions/9c2597a3-e391-4d3a-b644-...hineScaleSets/ubuntu-build-agents-vmss, 10s elapsed]

azurerm_linux_virtual_machine_scale_set.agent-pool-vmss: Modifications complete after 13s [id=/subscriptions/9c2597a3-e391-4d3a-b644-8a9094188071/resourceGroups/wus2-dev-rg/providers/Microsoft.Compute/virtualMachineScaleSets/ubuntu-build-agents-vmss]

azurerm_windows_virtual_machine_scale_set.agent-pool-vmss: Modifications complete after 13s [id=/subscriptions/9c2597a3-e391-4d3a-b644-8a9094188071/resourceGroups/wus2-dev-rg/providers/Microsoft.Compute/virtualMachineScaleSets/windows-build-agents-vmss]

Apply complete! Resources: 0 added, 2 changed, 0 destroyed.

Finishing: apply-virtual-machine-scale-set

**Comment by rcskosir** [comment] 2023-06-08 17:46
@basoyan7 Thank you for opening this issue. I am a little confused at what I am looking at. It looks like when you initially opened this issue, you had the standard issue format with the debug/panic output including the crash. Then you updated you issue to look the way it does above, which appears to be a successful apply. To clarify, are you no longer seeing the crash or issue?

**Comment by rcskosir** [comment] 2023-09-28 20:05
We are going to close this issue - if you would like to [open a new issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/new/choose) please make sure that you fill out all the requested information so that we can try to reproduce the problem.

**Closed by rcskosir** 2023-09-28 20:05 UTC
Labels: question, waiting-response, service/virtual-machine
