### ISSUE TITLE
Value for Postgres Flexible server's Private DNS Zone is being lowercased and causing Terraform to force a replacement

### ISSUE THREAD

**Issue by cybersmithio** [hashicorp/terraform-provider-azurerm#18313] opened 2022-09-09 00:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.9

### AzureRM Provider Version

3.21.1

### Affected Resource(s)/Data Source(s)

 azurerm_postgresql_flexible_server

### Terraform Configuration Files

```hcl
resource "azurerm_private_dns_zone" "NonProdPostgres" {
  name                = "xxxxxxxxxxxxxxxxxxxxxxx.private.postgres.database.azure.com"
  resource_group_name = azurerm_resource_group.NonProdPlatform.name
}

resource "azurerm_postgresql_flexible_server" "NonProd" {
  name                   = "xxxxxxxxxxxxxxxxxxxxxx"
  resource_group_name    = azurerm_resource_group.MyResourceGroupName.name
  location               = azurerm_resource_group.MyResourceGroupName.location
  version                = "14"
  delegated_subnet_id    = azurerm_subnet.PostgresqlPrivateEndpointSubnet.id
  private_dns_zone_id    = azurerm_private_dns_zone.NonProdPostgres.id
  administrator_login    = "pgadmin"
  administrator_password = "xxxxxxxxxx"
  zone                   = "1"

  storage_mb = 32768

  sku_name   = "B_Standard_B1ms"
  depends_on = [azurerm_private_dns_zone_virtual_network_link.NonProdPostgres]

}
```

### Debug Output/Panic Output

```shell
~ private_dns_zone_id           = "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx/resourceGroups/myresourcegroupname/providers/Microsoft.Network/privateDnsZones/xxxxxxxxxxxxxxxxxxxxxx.private.postgres.database.azure.com" -> "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx/resourceGroups/MyResourceGroupName/providers/Microsoft.Network/privateDnsZones/xxxxxxxxxxxxxxxxxxxxxx.private.postgres.database.azure.com" # forces replacement
```

### Expected Behaviour

The postgres server in question was created by the terraform script, so perfoming another terraform apply should not have anything happen.

### Actual Behaviour

The postgres server in question was created by the terraform script, but it does not seem to recognize it as the same object because of the difference in case for the resource groups.  So it tries to force a replacement.

### Steps to Reproduce

1. terraform apply

### Important Factoids

Running in Canada Central

**Comment by xchotard-talentsoft** [comment] 2022-09-16 10:01
I ran into the same issue somehow, unfortunately despite my efforts I don't know how to reproduce it :/ 

Terraform plans to destroy my Postgresql flexible instance because of a change in the Private DNS zone id related to case. It wants to replace `my-rg` by `My-RG`:
```
~ private_dns_zone_id = "/subscriptions/ffffffff-ffff-ffff-ffff-ffffffffffff/resourceGroups/my-rg/providers/Microsoft.Network/privateDnsZones/postgres.database.azure.com" -> "/subscriptions/ffffffff-ffff-ffff-ffff-ffffffffffff/resourceGroups/My-RG/providers/Microsoft.Network/privateDnsZones/postgres.database.azure.com" # forces replacement
```
However it is interesting to note that the `terraform state show` command shows that the ID already has `My-RG`:
```
private_dns_zone_id = "/subscriptions/ffffffff-ffff-ffff-ffff-ffffffffffff/resourceGroups/My-RG/providers/Microsoft.Network/privateDnsZones/postgres.database.azure.com"
```
From what I see there is no reason to trigger a replacement.

I'm still looking for a workaround because this is a blocking issue. It is impossible to apply any changes because that would destroy the Postgresql instance.

**Comment by dbuxo** [comment] 2022-10-24 16:25
We are also affected now by this case mismatch, not sure why, but after some changes on the private DNS zone (tags added by a policy), Terraform tries to destroy our posgresql instances.

The RG name is all uppercase.
In the Private DNS ID (view json), the id includes the RG in lower case. ( this was not created using terraform)
In the PosgreSQL the reference to the Private DNS ID has the RG in uppercase.

Even if we let terraform to recreate the PostgreSQL instance, the next plan will try to recreate again.

**Comment by mschirmacher** [comment] 2022-11-09 12:48
Is there any workaround yet? This is a real showstopper :-/

**Comment by bisk-e** [comment] 2023-01-25 05:17
Do we have an update regarding this? We're deploying azurerm_postgresql_flexible_server to a delegated subnet with private dns and this bug will cause data loss if deployed using Terraform.

**Comment by ThijsKoot** [comment] 2023-05-31 16:52
Same issue here...

**Comment by krisztiankocsis** [comment] 2023-09-27 08:46
Hi!

We're working in a big project in a big enterprise company and this bug is also limiting us. Ignoring the changes for private_dns_zone_id works as a workaround but then it relies on humans to known when this ID is actually changing, to have manual intervention.

Can you pls schedule a fix for this issue?

**Closed** 2023-10-25 22:44 UTC
Labels: bug, service/postgresql, v/3.x
