### ISSUE TITLE
azurerm_mssql_database - cannot import a "secondary" database

### ISSUE THREAD

**Issue by scott-doyland-burrows** [hashicorp/terraform-provider-azurerm#25444] opened 2024-03-27 15:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.5

### AzureRM Provider Version

3.93.0

### Affected Resource(s)/Data Source(s)

azurerm_mssql_database

### Terraform Configuration Files

```hcl
resource "azurerm_mssql_database" "mssql_database_secondary" {
  name                                = "test"
  server_id                           = "my_server_id"
  create_mode                         = "Secondary"
  creation_source_database_id         = "my_source_db_id"
}
```

```
import {
  to = azurerm_mssql_database.mssql_database_secondary
  id = "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Sql/servers/xxx/databases/xxx"
}
```
```


### Debug Output/Panic Output

```shell
Terraform will perform the following actions:

  # azurerm_mssql_database.mssql_database_secondarymust be replaced
  # (imported from "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Sql/servers/xxx/databases/xxx")
  # Warning: this will destroy the imported resource
-/+ resource "azurerm_mssql_database" "mssql_database_secondary" {
      ~ create_mode                                                = "Default" -> "Secondary" # forces replacement
      + creation_source_database_id                                = "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Sql/servers
```

### Expected Behaviour

I want to import a "secondary/failover" database.

This "secondary/failover" database was created manually via the portal using the portal's ability to setup a replicate database, hence it has a ```create_mode``` of ```Default```.

I want to import it in terraform as ```Secondary``` which will then allow me to destroy and recreate my infrastructure as and when needed.  If I import as ```Default``` without a ```creation_source_database_id``` then terraform will not recognise this is a "secondary/failover" database if I ever destroy and recreate my infrastructure.

I can do this using ```ignore_changes``` (set the ```create_mode``` and ```creation_source_database_id``` as required to b able to import and then ignore them).  Is this the correct way to do this, eg:

```
  lifecycle {
    ignore_changes = [create_mode, creation_source_database_id]
  }

  create_mode                          = "Secondary"
  creation_source_database_id = "xxx"
```

**Comment by sinbai** [comment] 2024-04-01 09:06
Hi @scott-doyland-burrows thanks for opening this issue. First, I would like to clarify that per [this ](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mssql_database#create_mode)documentation, we can see that the `import` property and the `create_mode` property are a set of mutually exclusive properties. This means that when specifying `import` property, you could not specify `create_mode`. From the config provided above, it seems that both attributes are specified at the same time. 

Besides, if you would like to ignore the re-creation caused by the change of `create_mode`, an example is as follows. For detailed usage of `ignore-changes`, please refer to [this ](https://developer.hashicorp.com/terraform/tutorials/state/resource-lifecycle#ignore-changes)documentation. 
```
resource "azurerm_mssql_database" "secondary" {
  name                        = "test"
  server_id                   = azurerm_mssql_server.test.id
  create_mode                 = "Secondary"
  secondary_type              = "Named"
  creation_source_database_id = azurerm_mssql_database.test.id

  lifecycle {
    ignore_changes = [create_mode]
  }
}

```

**Comment by scott-doyland-burrows** [comment] 2024-04-01 09:26
The docs re ```create_mode``` and ```import``` are not referring to an import of the resource into terraform state (which is what I am doing), they are referring to an import block allowed by the resource itself. 

I think how I have set the ignore lifecycle seems correct, and works. 

Just wanted clarification really. 

Thanks

**Comment by rcskosir** [comment] 2024-04-02 14:16
Thank you for taking the time to raise this! I am going to close this with @sinbai‘s response as an answer. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).

**Closed by rcskosir** 2024-04-02 14:16 UTC
Labels: service/mssql, v/3.x
