### ISSUE TITLE
Container insights - AKS Alert metrics 

### ISSUE THREAD

**Issue by ankur51206** [hashicorp/terraform-provider-azurerm#14743] opened 2021-12-28 17:49 UTC
I am trying to enable AKS alert metric using terraform latest provider. Still I am getting below error.

 insights.MetricAlertsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Couldn't find a metric named cpuUsagePercentage. Make sure the name is correct. If this metric hasn't been reported yet, use the -skipMetricValidation flag.

Namespace that I am using is below.. Which I followed from documents and also tried other keywords.

metric_namespace       = "Insights.container/nodes"
metric_name            = "cpuUsagePercentage"

Ref. https://docs.microsoft.com/en-us/azure/azure-monitor/containers/container-insights-update-metrics

Please help.

**Comment by mybayern1974** [comment] 2021-12-29 03:59
@ankur51206 , if you can provide your terraform configs then that would be helpful for troubleshooting.

**Comment by stephybun** [comment] 2022-02-15 15:11
Duplicate of #6996. Please subscribe to that issue for updates. Thanks!

**Closed by stephybun** 2022-02-15 15:11 UTC
Labels: question, service/kubernetes-cluster
