### ISSUE TITLE
aks image_cleaner applied incorrectly

### ISSUE THREAD

**Issue by lombardialess** [hashicorp/terraform-provider-azurerm#21039] opened 2023-03-20 14:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.9

### AzureRM Provider Version

3.48.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "aks-cluster" {
  name                = var.CLUSTER_NAME
  location            = var.LOCATION
  resource_group_name = var.RESOURCE_GROUP
  dns_prefix          = var.CLUSTER_NAME
  depends_on          = [azurerm_public_ip.aks-public-ip]
  kubernetes_version  = var.K8S_VERSION
  tags                = var.TAGS

  default_node_pool {
    name                = "ap${replace(lower(var.CLUSTER_NAME), "/[^a-z0-9]/", "")}"
    node_count          = var.NODE_COUNT
    vm_size             = var.NODE_SIZE
    enable_auto_scaling = false
    vnet_subnet_id = azurerm_subnet.subnet.id
    tags           = var.TAGS
  }

  azure_policy_enabled              = false
  http_application_routing_enabled  = false
  role_based_access_control_enabled = false

  linux_profile {
    admin_username = var.CLUSTER_ADMIN

    ssh_key {
      key_data = var.CLUSTER_PUBLIC_SSH
    }
  }

  network_profile {
    network_plugin    = "kubenet"
    load_balancer_sku = "standard"
    load_balancer_profile {
      outbound_ip_address_ids = [azurerm_public_ip.aks-public-ip.id]
    }
  }

  service_principal {
    client_id     = var.SERVICE_PRINCIPAL_CLIENT_ID
    client_secret = var.SERVICE_PRINCIPAL_SECRET
  }

  lifecycle {
    prevent_destroy = true
  }
}
```

### Debug Output/Panic Output

```shell
# module.aks.azurerm_kubernetes_cluster.aks-cluster will be updated in-place
  ~ resource "azurerm_kubernetes_cluster" "aks-cluster" {
        id                                  = "/subscriptions/.."
      + image_cleaner_enabled               = false
      + image_cleaner_interval_hours        = 48
        name                                = "k8s"
        tags                                = {
            "Product" = ".."
        }
        # (23 unchanged attributes hidden)

      ~ service_principal {
          + client_secret = (sensitive value)
            # (1 unchanged attribute hidden)
        }

        # (4 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Expected Behaviour

If not set in the code the image_cleaner option should be ignored because is optional

image_cleaner is also a preview feature on azure and I don't want to enable it also if the code try to set it to false by default

**Comment by stephybun** [comment] 2023-08-03 15:21
Closing since this is a duplicate of #19654. Please subscribe to #19654 for updates.

**Closed by stephybun** 2023-08-03 15:21 UTC
Labels: question, service/kubernetes-cluster, v/3.x
