### ISSUE TITLE
Unable to change azurerm_app_service app setting back to the empty string.

### ISSUE THREAD

**Issue by Cufeadir** [hashicorp/terraform-provider-azurerm#4298] opened 2019-09-10 20:31 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

* Terraform v0.12.8
* provider.azurerm v1.33.1

### Affected Resource(s)

* `azurerm_app_service`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  version = "~> 1.33"
}

locals {
  base_name = "example"
}

variable "some_setting" {
  type = "string"
  description = "A variable that is changed into an app setting."
  default = ""
}

resource "azurerm_resource_group" "example" {
  name = "${local.base_name}-rg"
  location = "North Central US"
}

resource "azurerm_app_service_plan" "example" {
  name = "${local.base_name}-plan"
  location = "${azurerm_resource_group.example.location}"
  resource_group_name = "${azurerm_resource_group.example.name}"
  kind = "Windows"
  sku {
    tier = "Basic"
    size = "B1"
  }
}

resource "azurerm_app_service" "example" {
  name = "${local.base_name}"
  location = "${azurerm_resource_group.example.location}"
  resource_group_name = "${azurerm_resource_group.example.name}"
  app_service_plan_id = "${azurerm_app_service_plan.example.id}"

  app_settings = {
    "SomeSetting" = "${var.some_setting}"
    "OtherSetting" = "Specific Value"
  }
}
```

### Expected Behavior

1. I create the resources with the above definition `terraform apply`. The app service has an app setting named SomeSetting with the empty string for a value. This behaves as expected.
2. I use a var file to change the `some_setting` variable to a different value (e.g. "asdf") and run `terraform apply --var-file values.tfvars`. The app service changes the SomeSetting app setting to the new value. This behaves as expected.
3. I can repeat that with a different value for the variable (e.g. "qwerty") and, as long as the value is not the empty string, it updates the SomeSetting app setting to the new value. This behaves as expected.
4. I want to change the value of the SomeSetting app setting to the empty string, so I run `terraform apply` with a var file that that contains `some_setting = ""`. I expect that this will update the SomeSetting app setting to have the empty string value, but it does not.

### Actual Behavior

For the last step described in the Expected Behavior section, the actual behavior is that it leaves the SomeSetting app setting with whatever value it had last and reports, "Apply complete! Resources: 0 added, 0 changed, 0 destroyed."

### Steps to Reproduce

As described in the Expected Behavior section.

### Important Factoids

In my usage scenario, I have multiple deployments that I would like to manage with a single terraform definition and different var files. Some deployments need a value for the "SomeSetting" app setting and others need the app setting to be the empty string or that app setting to not be present. I have other app settings (e.g. OtherSetting) that are needed in all deployments.

**Comment by amasover** [comment] 2020-12-15 22:23
I can confirm this behavior. Note that if I set the value of a setting to `null` rather than `""` then it updates correctly.

**Comment by Stolz** [comment] 2021-01-20 04:36
I can confirm this behavior with the Terraform v0.14.4 and Azure provider v2.43.0.

Steps to reproduce

- Set a non empty value for a app_settings variable and apply the changes
- Set an emptry value for the same variable and apply the changes
 
the variable will remains with the original non empty value instead of an empty value

**Comment by katbyte** [comment] 2023-07-19 17:22
I am going to close this because the `azurerm_app_service ` has been superseded by the `azurerm_linux_web_app` and `azurerm_windows_web_app` resources.

If this is still an issue with `v3.x` of the provider and the new resources do let us know by opening a new issue, thanks!

**Closed by katbyte** 2023-07-19 17:22 UTC
Labels: bug, good first issue, service/app-service, v/2.x (legacy), v/1.x (legacy)
