### ISSUE TITLE
allow_blob_public_access setting not working anymore with 3.0.1

### ISSUE THREAD

**Issue by RHooijer** [hashicorp/terraform-provider-azurerm#16047] opened 2022-03-25 08:35 UTC
While upgrading from 2.99.0 to 3.0.1 the allow blob public access is not working anymore. It gives the following error: 
╷
│ Error: Unsupported argument
│ 
│   on ../../modules/storage-account/main.tf line 8, in resource "azurerm_storage_account" "this":
│    8:   allow_blob_public_access  = var.allow_blob_public_access
│ 
│ An argument named "allow_blob_public_access" is not expected here.
╵
##[error]Error: Terraform Plan failed with exit code: 1

**Comment by christophernruud** [comment] 2022-03-25 09:05
duplicate of #16049

**Comment by stephybun** [comment] 2022-03-25 10:23
Hey @RHooijer,

Thanks for opening this issue.

As 3.0 is a major release a complete list of changes can be found [in the 3.0 upgrade guide](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/3.0-upgrade-guide) - which is [linked from the changelog since this is a major version](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/CHANGELOG.md#300-march-24-2022).

In this case this field has been renamed to allow_nested_items_to_be_public, however there maybe other changes you need to make to your Terraform Configuration to be compatible with v3.0 - we'd recommend consulting the upgrade guide.

We'd recommend pinning the version of the Azure Provider being used, for example to pin to 3.0.0:
```
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "=3.0.0"
    }
  }
}
```
You can also pin to the last 2.x release temporarily as shown below, however note that any future enhancements will ship in 3.x:
```
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "=2.99.0"
    }
  }
}
```
Thanks!

**Closed by stephybun** 2022-03-25 10:23 UTC
