### ISSUE TITLE
Unable to create Backup for Premium Storage Account with BlockBlobStorage configuration

### ISSUE THREAD

**Issue by slzmruepp** [hashicorp/terraform-provider-azurerm#20769] opened 2023-03-03 10:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.7

### AzureRM Provider Version

3.45.0

### Affected Resource(s)/Data Source(s)

azurerm_data_protection_backup_instance_blob_storage

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "storage_account" {
  name                = var.name
  resource_group_name = var.resource_group_name

  location                        = var.location
  account_kind                    = "BlockBlobStorage"
  account_tier                    = "Premium"
  account_replication_type        = "ZRS"
  is_hns_enabled                  = false
  tags                            = local.tags
  enable_https_traffic_only       = true
  shared_access_key_enabled       = true
  public_network_access_enabled   = true
  allow_nested_items_to_be_public = false
  

  network_rules {
    default_action             = "Allow"
    bypass                     = ["AzureServices"]
    ip_rules                   = var.ip_rules
    virtual_network_subnet_ids = var.virtual_network_subnet_ids
  }

  blob_properties {
    delete_retention_policy {
      days                        = 7
    }
#Restore Policy not supported with premium BlockBlob
/*    restore_policy {
      days                        = var.restore_policy
    }*/
    container_delete_retention_policy {
      days                        = 7
    }
    versioning_enabled            = true
    change_feed_enabled           = true
    change_feed_retention_in_days = 7
  }
}

###### Backup Settings
resource "azurerm_data_protection_backup_vault" "blob" {
  name                = "backup-vault"
  resource_group_name = data.azurerm_resource_group.rg.name
  location            = var.AZREGION
  datastore_type      = "VaultStore"
  redundancy          = "LocallyRedundant"
  tags                = local.tags
  identity {
    type = "SystemAssigned"
  }
}

resource "azurerm_role_assignment" "backup_role" {
  scope                = azurerm_storage_account.storage_account.id
  role_definition_name = "Storage Account Backup Contributor"
  principal_id         = azurerm_data_protection_backup_vault.blob.identity[0].principal_id
}

resource "azurerm_data_protection_backup_policy_blob_storage" "backup_policy" {
  name               = "backup-policy"
  vault_id           = azurerm_data_protection_backup_vault.blob.id
  retention_duration = "P30D"
}

resource "azurerm_data_protection_backup_instance_blob_storage" "backup_instance" {
  name               = "backup-instance"
  vault_id           = azurerm_data_protection_backup_vault.blob.id
  location           = var.AZREGION
  storage_account_id = azurerm_storage_account.storage_account.id
  backup_policy_id   = azurerm_data_protection_backup_policy_blob_storage.backup_policy.id

  depends_on = [azurerm_role_assignment.backup_role]
}
```

### Debug Output/Panic Output

```shell
│ Error: waiting for BackupInstance("Backup Instance (Subscription: \"60ec4723-77d3-44c8-b80e-39dccb661ab5\"\nResource Group Name: \"rg-oc-infra-master-int\"\nBackup Vault Name: \"oc-backup-vault\"\nBackup Instance Name: \"oc-backup-instance\")") policy protection to be completed: unexpected state 'ProtectionError', wanted target 'ProtectionConfigured'. last error: %!s(<nil>)
│ 
│   with azurerm_data_protection_backup_instance_blob_storage.oc_backup_instance,
│   on stor_acc.tf line 102, in resource "azurerm_data_protection_backup_instance_blob_storage" "oc_backup_instance":
│  102: resource "azurerm_data_protection_backup_instance_blob_storage" "oc_backup_instance" {
│ 
╵
##[error]Terraform command 'apply' failed with exit code '1'.
##[error]╷
```

### Expected Behaviour

The backup instance should be created and shown in the gui.

### Actual Behaviour

Instead apply fails. If apply runs again, the following error occurs:
`
│ Error: A resource with the ID "/subscriptions/60ec4723-77d3-44c8-b80e-39dccb661ab5/resourceGroups/rg-oc-infra-master-int/providers/Microsoft.DataProtection/backupVaults/oc-backup-vault/backupInstances/oc-backup-instance" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_data_protection_backup_instance_blob_storage" for more information.
│ 
│   with azurerm_data_protection_backup_instance_blob_storage.oc_backup_instance,
│   on stor_acc.tf line 102, in resource "azurerm_data_protection_backup_instance_blob_storage" "oc_backup_instance":
│  102: resource "azurerm_data_protection_backup_instance_blob_storage" "oc_backup_instance" {
│ 
╵
##[error]Terraform command 'apply' failed with exit code '1'.
##[error]╷
`

Also the instance AND policy are never shown in the Azure Gui under the backup vault configuration.
Deleting is only possible by using command line: `az resource delete --ids ...`

This is a blocker to create a backup vault for Premium Storage accounts

### Steps to Reproduce

Try to run the above config.

**Comment by magodo** [comment] 2023-03-06 04:08
@slzmruepp This is by design that the error message of the failed backup instance creation polling response just said: *The storage account type is not supported for backup.*

**Comment by karimch27** [comment] 2024-04-18 12:34
how can we backup a premium blob storage then ?

**Comment by tombuildsstuff** [comment] 2024-05-23 11:53
Per @magodo's message above - this appears to be a limitation of the Azure Service rather than something specific to the AzureRM Provider and as such I'm going to close this issue for the moment. That said when support for this functionality is available via the Azure API we can take another look into supporting this, but without support for this in the API there isn't much we can do.

Thanks!

**Closed by tombuildsstuff** 2024-05-23 11:53 UTC
Labels: question, service/data-protection, v/3.x
