### ISSUE TITLE
Support for [Virtual endpoints in Azure Database for PostgreSQL flexible server]

### ISSUE THREAD

**Issue by samydv10** [hashicorp/terraform-provider-azurerm#26268] opened 2024-06-07 10:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

I am writing to request that the product team consider adding a virtual endpoint feature to the Azure Database for PostgreSQL flexible server. This feature would greatly enhance the functionality of Azure Database for PostgreSQL and make it even more useful for our needs. I believe that this addition would be well received by many users and would be a valuable addition to the product. Thank you for considering this request and I look forward to hearing back from the team about the possibility of incorporating this feature.

### Description

I am writing to request that the product team consider adding a virtual endpoint feature to the Azure Database for PostgreSQL flexible server. This feature would greatly enhance the functionality of Azure Database for PostgreSQL and make it even more useful for our needs. I believe that this addition would be well received by many users and would be a valuable addition to the product. Thank you for considering this request and I look forward to hearing back from the team about the possibility of incorporating this feature.

### New or Affected Resource(s)/Data Source(s)

azurerm_postgresql_flexible_server

### References

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/169791897/56fda67e-d458-4a4d-8eae-fcbb0e9ac8f3)

**Comment by tombuildsstuff** [comment] 2024-06-12 09:30
hey @samydv10 

Thanks for opening this issue.

Taking a look through here this appears to be a duplicate of #25803, rather than having multiple issues open tracking the same thing I'm going to close this in favour of #25803 - would you mind subscribing to that issue for updates?

Thanks!

**Closed by tombuildsstuff** 2024-06-12 09:30 UTC
Labels: duplicate, enhancement, service/postgresql
