### ISSUE TITLE
Unable to resize vCore with per DB setting

### ISSUE THREAD

**Issue by tikicoder** [hashicorp/terraform-provider-azurerm#6728] opened 2020-05-01 01:50 UTC
Terraform Version
Terraform v0.12.23
provider.azurev2.5.0

We have created a gen 5 vCore elastic pool using the azurerm_mssql_elasticpool object with per db settings.

Example 
resource "azurerm_mssql_elasticpool" "elasticpool" {
  name                = "test-elastic-pool"
  resource_group_name = var.resourceGroup
  location            = ...
  server_name         = ...
  max_size_gb         = 50

  sku {
    name     = "GP_Gen5"
    tier     = "GeneralPurpose"
    family   = "Gen5"
    capacity = 4
  }

  per_database_settings {
    min_capacity = 0.25
    max_capacity = 2
  }
}

If someone manually increases the core to 8 and updates the per database settings TF is unable to adjust.

Debug Output
N/A

Crash Output
N/A

Expected Behavior
TF should be able to modify the system back, I can do it via the portal.

Actual Behavior
exception.

I went through the logs and all I get is
Error: Code="InternalServerError" Message="An unexpected error occured while processing the request. Tracking ID: '31f2b96f-1f72-4da7-80d9-bd0498da2335'"

  on data/data.tf line 62, in resource "azurerm_mssql_elasticpool" "elasticpool":
  62: resource "azurerm_mssql_elasticpool" "elasticpool" {

Steps to Reproduce
create a db with elastic pool, manually update the cores and per db setting and then have to try to update them back.

**Comment by yupwei68** [comment] 2020-05-06 06:37
Hi @tikicoder , Thanks for opening this issue. Could you specify which fields have you manually updated on portal, and what's the value of them? Because I need to reproduce it with more details.

**Comment by tikicoder** [comment] 2020-05-06 14:30
So in my example above it is a 4core elastic pool and .25 - 2 cores per db.

Change it to 16 cores and 2 to 16 cores per DB.

Really as long as you increase the number of cores and the per DB setting you should have the issue.

**Comment by yupwei68** [comment] 2020-05-07 02:48
hi @tikicoder ,sorry that I can't reproduce this error. Please correct me if I misunderstood the steps. 
1. Terraform apply the code above, which is 4 cores, and 0.25-2 cores per DB
2. Change the vcores to 16 cores, and change to 2-16 cores per DB on portal
3. Terraform apply the code again, get:
```
 # azurerm_mssql_elasticpool.elasticpool will be updated in-place
  ~ resource "azurerm_mssql_elasticpool" "elasticpool" {
        id                  = "/subscriptions/xxxx-xxxx/resourceGroups/yupserver/providers/Microsoft.Sql/servers/yupserver/elasticPools/test-elastic-pool"
        location            = "eastus"
        max_size_bytes      = 53687091200
        max_size_gb         = 50
        name                = "test-elastic-pool"
        resource_group_name = "yupserver"
        server_name         = "yupserver"
        tags                = {}
        zone_redundant      = false

      ~ per_database_settings {
          ~ max_capacity = 16 -> 2
          ~ min_capacity = 2 -> 0.25
        }

      ~ sku {
          ~ capacity = 16 -> 4
            family   = "Gen5"
            name     = "GP_Gen5"
            tier     = "GeneralPurpose"
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

**Comment by tikicoder** [comment] 2020-05-07 03:52
What provider version?

The only other difference is the database and elastic pools are in a foreach. 

resource "azurerm_sql_server" "server" {
  for_each                      = local.keys
  name                          = local.db_name[each.value]
  resource_group_name           = local.resource_group_name
  location                      = var.global_settings[each.value].location

  version                       = "12.0"
  administrator_login           = var.settings[each.value].sql_server_username
  administrator_login_password  = var.settings[each.value].sql_server_password

  tags = {
    environment = var.global_settings[each.value].environment
  }
}
resource "azurerm_mssql_elasticpool" "elasticpool" {
  for_each            = local.keys
  name                = local.enable_failover_group ? "${azurerm_sql_server.server[keys(azurerm_sql_server.server)[0]].name}-pool" : "${azurerm_sql_server.server[each.key].name}-pool"
  resource_group_name = azurerm_sql_server.server[each.key].resource_group_name
  location            = azurerm_sql_server.server[each.key].location
  server_name         = azurerm_sql_server.server[each.key].name
  max_size_gb         = var.settings[each.value].elastic_pool_max_db_size_gb

  sku {
    name     = var.settings[each.value].elastic_pool_sku_name
    tier     = var.settings[each.value].elastic_pool_sku_tier
    family   = var.settings[each.value].elastic_pool_sku_family
    capacity = var.settings[each.value].elastic_pool_sku_capacity
  }

  per_database_settings {
    min_capacity = var.settings[each.value].elastic_pool_per_database_settings_min
    max_capacity = var.settings[each.value].elastic_pool_per_database_settings_max
  }
}

**Comment by yupwei68** [comment] 2020-05-07 05:49
@tikicoder  I have tried in azurerm 2.8 and 2.5. Have you tried to reproduce the error, does it show up every time?

**Comment by tikicoder** [comment] 2020-05-07 19:36
I will have to revalidate.  I know we recently updated to rm 2.5 we we on 2.2 there for a bit.

**Comment by mybayern1974** [comment] 2020-05-08 16:33
@tikicoder , firstly hope your revalidation against your scenario would be smooth. In addition to that, I'd like to chime in a little bit that a practice of leveraging terraform to manage Azure resources is to always use terraform end to end, which helps make state things consistent and manageable. Managing resources by the mixing usage of terraform and non-terraform (say operate on portal) would be likely to incur unexpected inconsistency.

I'm raising up this comment is just to ensure your trying efforts in terms of mix-using Terraform and portal is based on we being at the same understanding page on the above point : )

**Comment by tikicoder** [comment] 2020-05-11 15:17
Mine still failed.  If you are saying there is no issue then I guess we can close the ticket, I just do not understand why we would have an issue but you wouldn't unless something with the upgrade.  We were originally on TF azure 1.38 (sound right).  I then changed it to 2.2 and not 2.5.

I, understand that if someone changed the Azure manually that is not ideal, and Terraform should be the main point of managing the resources.  However, in this case not sure why it would cause an issue.

The error is
Error: Code="InternalServerError" Message="An unexpected error occured while processing the request. Tracking ID: 'ecdd6baf-5a23-43c5-a0a0-b24f2decfe04'"

  on data/data.tf line 62, in resource "azurerm_mssql_elasticpool" "elasticpool":
  62: resource "azurerm_mssql_elasticpool" "elasticpool" {

Here is what the output of the plan is for the elastic pool.
All the"..." populated just find and is the previous information.
~ resource "azurerm_mssql_elasticpool" "elasticpool" {
        id                  = "..."
        location            = "..."
        max_size_bytes      = 53687091200
        max_size_gb         = 50
        name                = "..."
        resource_group_name = "..."
        server_name         ="..."
        tags                = {}
        zone_redundant      = false

      ~ per_database_settings {
          ~ max_capacity = 10 -> 2
          ~ min_capacity = 2 -> 0.25
        }

      ~ sku {
          ~ capacity = 10 -> 4
            family   = "Gen5"
            name     = "GP_Gen5"
            tier     = "GeneralPurpose"
        }
    }

**Comment by katbyte** [comment] 2020-06-15 17:55
Hi @tikicoder - i'm sorry for the confusion here, while @mybayern1974 is correct you should manage all resources e2e within terraform as any changes in the portal would not be recognized by terraform and thus overwritten on the next plan/apply. However it sounds like you are getting an error from terraform during the apply here? ie terraform errors out with
```
Error: Code="InternalServerError" Message="An unexpected error occured while processing the request. Tracking ID: 'ecdd6baf-5a23-43c5-a0a0-b24f2decfe04'"
```

Which is very much so a bug - and one in the API tbh. Could you place confirm this? At that point we can see if a workaround is possible in the provider/try and raise this to the service team.

Thanks!

**Comment by hugo-zhang-uipath** [comment] 2020-06-15 19:46
I meet the same issue also, I didnot change any terraform code except upgrading terraform from 1.36.0 to "~> 2.1.0"

**Comment by tikicoder** [comment] 2020-06-15 20:39
In some testing, it looks like I also got the error from the Azure Portal.  For some reason, it was trying to update the vCore before updating the Per DB setting.   So I had to do it in 2 steps for the servers having the issue regardless.  Outside of that things seem to work ok.

**Comment by favoretti** [comment] 2021-08-19 11:35
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.

**Closed by favoretti** 2021-08-19 11:35 UTC
Labels: bug, service/mssql
