### ISSUE TITLE
azurerm_iothub_route doesnt seem to be idempotent

### ISSUE THREAD

**Issue by corradocavalli** [hashicorp/terraform-provider-azurerm#12439] opened 2021-07-01 11:53 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

0.14.7

### Affected Resource(s)

* `azurerm_iothub_route`

### Expected Behaviour

After deploying an infrastructure, running Terraform Apply, if there are no changes, it should return in no changes applied. 

### Actual Behaviour

When i execute Terraform Apply the IoT Hub route gets removed and any successive Apply invocation results in "Route XYZ not present error"

### Steps to Reproduce

Deploy an infrastructure that includes this IoT hub route

resource "azurerm_iothub_route" "example" {
  resource_group_name = "my rg group"
  iothub_name         = "my iot hub name"
  name                = "demo-route"
  source              = "DeviceMessages"
  condition           = "true"
  endpoint_names      = [azurerm_iothub_endpoint_storage_container.sense.name]
  enabled             = true
}

Once deployed immediately run `terraform apply` again.

### References
Same issue has been reported in the past here https://github.com/terraform-providers/terraform-provider-azurerm/issues/11819

**Comment by EliiseS** [comment] 2021-07-14 12:19
@manicminer @tombuildsstuff The previous ticket for this was closed due to inactivity, could you take a sec to take a look at this bug? 😄

**Comment by MahrRah** [comment] 2021-07-21 14:21
I can reproduce the issue when mixing the two approaches (`azurerm_iothub` and `azurerm_iothub_route`) to create routes for the IoT Hub like in the sample below:
```terraform
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=2.65.0"
    }
  }
}

provider "azurerm" {
  features {
    key_vault {
      recover_soft_deleted_key_vaults = true
      purge_soft_delete_on_destroy    = true
    }
  }
}

locals {
  resource_prefix         = "ex"
  resource_group_name     = "azurerm-iot-example"
  resource_group_location = "westeurope"
}

resource "azurerm_resource_group" "example" {
  name     = local.resource_group_name
  location = local.resource_group_location
}

resource "azurerm_iothub" "example" {
  name                          = "${local.resource_prefix}-iot-hub"
  resource_group_name           = local.resource_group_name
  location                      = local.resource_group_location
  public_network_access_enabled = true

  sku {
    name     = "S1"
    capacity = "1"
  }

  route {
    name           = "defaultroute"
    source         = "DeviceMessages"
    condition      = "true"
    endpoint_names = ["events"]
    enabled        = true
  }
}

# Routes IoT Hub message to blob container for storage backup.
resource "azurerm_storage_account" "example" {
  name                     = "${local.resource_prefix}logsstorage"
  resource_group_name      = local.resource_group_name
  location                 = local.resource_group_location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_storage_container" "example" {
  name                  = "iot-hub-messages"
  storage_account_name  = azurerm_storage_account.example.name
  container_access_type = "private"
}

resource "azurerm_iothub_endpoint_storage_container" "example" {
  resource_group_name = local.resource_group_name
  iothub_name         = azurerm_iothub.example.name
  name                = "${local.resource_prefix}-logs-storage-endpoint"

  connection_string          = azurerm_storage_account.example.primary_blob_connection_string
  batch_frequency_in_seconds = 60
  max_chunk_size_in_bytes    = 10485760
  container_name             = azurerm_storage_container.example.name
  encoding                   = "JSON"
  file_name_format           = "{iothub}/{partition}_{YYYY}_{MM}_{DD}_{HH}_{mm}"
}

resource "azurerm_iothub_route" "example" {
  resource_group_name = local.resource_group_name
  iothub_name         = azurerm_iothub.example.name
  name                = "${local.resource_prefix}-logs-storage-route"
  source              = "DeviceMessages"
  condition           = "true"
  endpoint_names      = [azurerm_iothub_endpoint_storage_container.example.name]
  enabled             = true
}

```
If `terraform apply` is run after the initial creation of the infrastructure, the route defined using `azurerm_iothub_route` will be deleted. 


**Solution:** This however can be solved by using either one or the other approach

- Example using `azurerm_iothub_route`

```terraform
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=2.65.0"
    }
  }
}

provider "azurerm" {
  features {
    key_vault {
      recover_soft_deleted_key_vaults = true
      purge_soft_delete_on_destroy    = true
    }
  }
}

locals {
  resource_prefix         = "ex2"
  resource_group_name     = "azurerm-iot-example-test2"
  resource_group_location = "westeurope"
}

resource "azurerm_resource_group" "example" {
  name     = local.resource_group_name
  location = local.resource_group_location
}

resource "azurerm_iothub" "example" {
  name                          = "${local.resource_prefix}-iot-hub"
  resource_group_name           = local.resource_group_name
  location                      = local.resource_group_location
  public_network_access_enabled = true

  sku {
    name     = "S1"
    capacity = "1"
  }
}

# Routes IoT Hub message to blob container for storage backup.
resource "azurerm_storage_account" "example" {
  name                     = "${local.resource_prefix}logsstorage"
  resource_group_name      = local.resource_group_name
  location                 = local.resource_group_location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_storage_container" "example" {
  name                  = "iot-hub-messages"
  storage_account_name  = azurerm_storage_account.example.name
  container_access_type = "private"
}

resource "azurerm_iothub_endpoint_storage_container" "example" {
  resource_group_name = local.resource_group_name
  iothub_name         = azurerm_iothub.example.name
  name                = "${local.resource_prefix}-logs-storage-endpoint"

  connection_string          = azurerm_storage_account.example.primary_blob_connection_string
  batch_frequency_in_seconds = 60
  max_chunk_size_in_bytes    = 10485760
  container_name             = azurerm_storage_container.example.name
  encoding                   = "JSON"
  file_name_format           = "{iothub}/{partition}_{YYYY}_{MM}_{DD}_{HH}_{mm}"
}

resource "azurerm_iothub_route" "example" {
  resource_group_name = local.resource_group_name
  iothub_name         = azurerm_iothub.example.name
  name                = "${local.resource_prefix}-logs-storage-route"
  source              = "DeviceMessages"
  condition           = "true"
  endpoint_names      = [azurerm_iothub_endpoint_storage_container.example.name]
  enabled             = true
}

resource "azurerm_iothub_route" "example1" {
  resource_group_name = local.resource_group_name
  iothub_name         = azurerm_iothub.example.name
  name                = "defaultroute"
  source              = "DeviceMessages"
  condition           = "true"
  endpoint_names      = ["events"]
  enabled             = true
}

```

- Example using `azurerm_iothub`

```terraform
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=2.65.0"
    }
  }
}

provider "azurerm" {
  features {
    key_vault {
      recover_soft_deleted_key_vaults = true
      purge_soft_delete_on_destroy    = true
    }
  }
}

locals {
  resource_prefix         = "ex1"
  resource_group_name     = "azurerm-iot-example-test"
  resource_group_location = "westeurope"
}

resource "azurerm_resource_group" "example" {
  name     = local.resource_group_name
  location = local.resource_group_location
}

# Routes IoT Hub message to blob container for storage backup.
resource "azurerm_storage_account" "example" {
  name                     = "${local.resource_prefix}logsstorage"
  resource_group_name      = local.resource_group_name
  location                 = local.resource_group_location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_storage_container" "example" {
  name                  = "iot-hub-messages"
  storage_account_name  = azurerm_storage_account.example.name
  container_access_type = "private"
}

resource "azurerm_iothub" "example" {
  name                          = "${local.resource_prefix}-iot-hub"
  resource_group_name           = local.resource_group_name
  location                      = local.resource_group_location
  public_network_access_enabled = true

  sku {
    name     = "S1"
    capacity = "1"
  }

  endpoint {
    type                       = "AzureIotHub.StorageContainer"
    name                       = "${local.resource_prefix}-logs-storage-endpoint"
    connection_string          = azurerm_storage_account.example.primary_blob_connection_string
    batch_frequency_in_seconds = 60
    max_chunk_size_in_bytes    = 10485760
    container_name             = azurerm_storage_container.example.name
    encoding                   = "JSON"
    file_name_format           = "{iothub}/{partition}_{YYYY}_{MM}_{DD}_{HH}_{mm}"
  }

  route {
    name           = "defaultroute"
    source         = "DeviceMessages"
    condition      = "true"
    endpoint_names = ["events"]
    enabled        = true
  }

  route {
    name           = "${local.resource_prefix}-logs-storage-route"
    source         = "DeviceMessages"
    condition      = "true"
    endpoint_names = ["${local.resource_prefix}-logs-storage-endpoint"]
    enabled        = true
  }
}
```


I think unless there is a good reason to have to mix these two approaches (which the [docs](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/iothub) are strongly advising against), the issue can be closed :)

**Comment by catriona-m** [comment] 2022-02-22 11:59
Closing this as this issue now appears to be resolved.

**Closed by catriona-m** 2022-02-22 11:59 UTC
Labels: service/iot-hub
