### ISSUE TITLE
azurerm_api_management_api: allow set "Oauth" / link authorization server

### ISSUE THREAD

**Issue by markti** [hashicorp/terraform-provider-azurerm#6614] opened 2020-04-24 14:17 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

API Management allows you to create API definitions and OAuth / OIDC authorization servers that you can link to your APIs for user authorization.

### New or Affected Resource(s)

* azurerm_api_management_api
* azurerm_api_management_authorization_server

### Potential Terraform Configuration

```hcl
resource "azurerm_api_management_authorization_server" "my_oauth_server" {
  name                         = "test-server"
  api_management_name          = data.azurerm_api_management.example.name
  resource_group_name          = data.azurerm_api_management.example.resource_group_name
  display_name                 = "Test Server"
  authorization_endpoint       = "https://example.mydomain.com/client/authorize"
  client_id                    = "42424242-4242-4242-4242-424242424242"
  client_registration_endpoint = "https://example.mydomain.com/client/register"

  grant_types = [
    "authorizationCode",
  ]
}




resource "azurerm_api_management_api" "my_api" {
  name                = "example-api"
  resource_group_name = azurerm_resource_group.example.name
  api_management_name = azurerm_api_management.example.name
  revision            = "1"
  display_name        = "Example API"
  path                = "example"
  protocols           = ["https"]

  oauth2_authorization {
    authorization_server = azurerm_api_management_authorization_server.my_oauth_server.id
    scope_override = "foo"
  }
}
```

### References

* #0000
![image](https://user-images.githubusercontent.com/3155241/80222331-a7bef900-8614-11ea-89c5-d6ed7e0a9bfd.png)

**Comment by swapnilbjadhav** [comment] 2020-06-19 08:08
resource "azurerm_api_management_api" "my_api" {
  name                = "example-api"
  resource_group_name = azurerm_resource_group.example.name
  api_management_name = azurerm_api_management.example.name
  revision            = "1"
  display_name        = "Example API"
  path                = "example"
  protocols           = ["https"]

  oauth2_authorization {
    authorization_server = azurerm_api_management_authorization_server.my_oauth_server.id
    scope_override = "foo"
  }
}

Is the mentioned above feature available? of oauth2_authorization if yes how do we achieve it?

**Comment by sirlatrom** [comment] 2020-07-08 08:33
This is a duplicate of #3341 if I understand correctly.

**Comment by favoretti** [comment] 2021-08-19 11:31
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.

**Closed by favoretti** 2021-08-19 11:31 UTC
Labels: enhancement
