### ISSUE TITLE
Lacking documentation

### ISSUE THREAD

**Issue by lightpeak** [hashicorp/terraform-provider-azurerm#23097] opened 2023-08-28 07:44 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

In the latest documentation for azurerm, version 3.71.0, **/policies/policy** is missing in the import block:

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/31926380/c41ef202-15b6-4e84-b811-26e5a0f4fa64)

### New or Affected Resource(s)/Data Source(s)

azurerm_api_management_api_policy

### Potential Terraform Configuration

```hcl
terraform import azurerm_api_management_api_policy.example /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/group1/providers/Microsoft.ApiManagement/service/service1/apis/exampleId/policies/policy
```

### References

https://registry.terraform.io/providers/hashicorp/azurerm/3.71.0/docs/resources/api_management_api_policy

**Comment by sinbai** [comment] 2023-08-28 09:06
Hi @lightpeak thanks for opening this issue. The update to the documentation is by design, introduced by [this](https://github.com/hashicorp/terraform-provider-azurerm/pull/23008) PR. This is because the id of `azurerm_api_management_api_policy` has been updated to "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/group1/providers/Microsoft.ApiManagement/service/service1/apis/exampleId" in state file after  v3.70.0 of terraform provider.

**Comment by rcskosir** [comment] 2023-12-06 22:37
Thank you for taking the time to raise this! I am going to close this with @sinbai‘s response as an answer. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).

**Closed by rcskosir** 2023-12-06 22:37 UTC
Labels: documentation, waiting-response, service/api-management, v/3.x
