### ISSUE TITLE
data source azurerm_client_config has empty client_id and object_id when using msi

### ISSUE THREAD

**Issue by chinwobble** [hashicorp/terraform-provider-azurerm#11553] opened 2021-05-02 05:42 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform 0.15.1
AzureRM 2.57.0

### Affected Resource(s)

* `data azurerm_client_config`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=2.57.0"
    }
  }

  backend "azurerm" {
    container_name = "tfstate"
    key            = "shared.terraform.tfstate"
  }
}

data "azurerm_client_config" "current" {}

output "azurerm_client_config" {
   value = data.azurerm_client_config.current
}
```

### Expected Behaviour

Data should return object_id of the managed identity.

### Actual Behaviour

Data resource is missing object_id and client_id.
```
+ azurerm_config = {
      + client_id       = ""
      + id              = "2021-05-02 05:38:30.872363915 +0000 UTC"
      + object_id       = ""
      + subscription_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      + tenant_id       = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      + timeouts        = null
    }

```

### Steps to Reproduce

1. Create a terraform module with azurerm backend and providers and MSI authentication.
2. Create a linux azure VM with a system assigned identity
3. Run `terraform plan` and pass in all details required for msi authetnication.

### Important Factoids

- using azure global environment 
- When you use azure_cli authentication, you can see the `object_id`.

### References

* #0000

**Comment by Theragus** [comment] 2021-11-22 16:17
Possible duplicate of https://github.com/hashicorp/terraform-provider-azurerm/issues/7787

**Comment by Theragus** [comment] 2021-11-22 16:17
Duplicate of #7787

**Comment by tombuildsstuff** [comment] 2021-11-22 17:09
Duplicate of #7787 - thanks @Theragus

**Closed by tombuildsstuff** 2021-11-22 17:09 UTC
Labels: duplicate, question, provider
