### ISSUE TITLE
Not able to create AKS Kubernetes cluster: Feature Microsoft.ContainerService/AutoUpgradePreview is not enabled

### ISSUE THREAD

**Issue by tappoz** [hashicorp/terraform-provider-azurerm#11396] opened 2021-04-20 14:03 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

- Terraform 0.15.0 (latest at the time of writing)
- AzureRM 2.56.0 (latest at the time of writing)

### Affected Resource(s)

`azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "akc" {
  name                      = "${var.prefix}-${var.workspace}-${var.name}-akc"
  location                  = azurerm_resource_group.rg.location
  resource_group_name       = azurerm_resource_group.rg.name
  dns_prefix                = "${var.prefix}-${var.workspace}-${var.name}-akc"
  automatic_channel_upgrade = "stable"

  default_node_pool {
    name               = "${var.prefix}kn${var.workspace}pool"
    node_count         = 3
    vm_size            = "Standard_B2s"
  }

  # tried with / without the below 
  role_based_access_control {
    enabled = true
  }

  # I need a "Log Analytics Workspace" attached to this AKS, so I added the resource below: 
  addon_profile {
    oms_agent {
      enabled                    = true
      log_analytics_workspace_id = azurerm_log_analytics_workspace.law.id
    }
  }

  # tried with / without the below 
  linux_profile {
    admin_username = var.vm_user
    ssh_key {
      key_data = var.vm_user_pub_ssh_key
    }
  }

  # tried with / without the below (even with `identity`): same error
  service_principal {
    client_id = "XXX"
    client_secret = "XXX"
  }
}
```

### Panic Output

```
│ Error: creating Managed Kubernetes Cluster "XXX-akc" (Resource Group "XXX-rg"): 
containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- 
Original Error: Code="BadRequest" Message="Feature Microsoft.ContainerService/AutoUpgradePreview is not enabled. 
Please see https://aka.ms/aks/previews for how to enable features."
│ 
│   on aks.tf line 100, in resource "azurerm_kubernetes_cluster" "akc":
│  100: resource "azurerm_kubernetes_cluster" "akc" {
│ 
```

### Expected Behaviour

I am expecting to create an Azure Kubernetes Service via `azurerm_kubernetes_cluster` with a Log Analytics Workspace attached to it.

### Actual Behaviour

The `terraform apply` blocks and I cannot see the end of the process.

### Steps to Reproduce

1. `terraform apply`

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster

**Comment by tappoz** [comment] 2021-04-21 08:02
The issue has to do with `automatic_channel_upgrade = "stable"`. 

Some context is provided in the docs here: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#automatic_channel_upgrade

One note says:

> Cluster Auto-Upgrade only updates to GA versions of Kubernetes and will not update to Preview versions.

Which suggests that `stable` as a value for that `automatic_channel_upgrade` should be fine.

I am not sure if this is a bug, however I find it strange that the `terraform plan` does not show anything wrong with that piece of Terraform code. If I remove that statement completely, then the issue goes away and I am able to successfully run `terraform apply`.

**Comment by aristosvo** [comment] 2021-04-21 18:08
Hi!!

Good question, but in the docs is specified that this is a Preview feature. So I believe it's not a bug.

From the docs:
> Auto upgrade channel is in Public Preview - more information and details on how to opt into the Preview can be found in this article.

**Comment by heoelri** [comment] 2021-08-13 09:10
AKS AutoUpgrade feature is in public preview (August 2021) - the use of `automatic_upgrade_channel` requires you to register your Azure subscription for the AutoUpgradePreview first. See https://docs.microsoft.com/en-us/azure/aks/upgrade-cluster#set-auto-upgrade-channel.

```azurecli
az feature register --namespace Microsoft.ContainerService -n AutoUpgradePreview
```

The syntax is correct. There's no reason for `terraform plan` to complain. There's also a note in the docs explaining that:

![image](https://user-images.githubusercontent.com/17407022/129333914-00ed02c5-df93-43d1-83ff-d63a76b0156b.png)

**Comment by akazakou-incomm** [comment] 2021-10-01 09:05
I guess azurerm should add an additional option for `automatic_upgrade_channel` is `none`. It is presented in the [Microsoft documentation](https://docs.microsoft.com/en-us/azure/aks/upgrade-cluster#set-auto-upgrade-channel-preview) but [not available in terraform](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#automatic_channel_upgrade).

**Comment by DanielHajduk2-TomTom** [comment] 2021-10-01 10:43
Hi, Im using version: hashicorp/azurerm v2.79.0
And we still get:
"Feature Microsoft.ContainerService/AutoUpgradePreview is not enabled. Please see https://aka.ms/aks/previews for how to enable features."

When this parameter is not specified. Default value seems not to be None.

**Comment by AlastairHay** [comment] 2021-10-01 11:57
I believe @DanielHajduk2-TomTom's issue is caused by this change https://github.com/hashicorp/terraform-provider-azurerm/pull/13493 in v2.79.0 . Rolling back to v2.78.0 works for me.

Possibly when testing that change, it was not tested in an environment where the AutoUpgradePreview was not enabled.

**Comment by philwelz** [comment] 2021-10-03 10:49
> I guess azurerm should add an additional option for `automatic_upgrade_channel` is `none`. It is presented in the [Microsoft documentation](https://docs.microsoft.com/en-us/azure/aks/upgrade-cluster#set-auto-upgrade-channel-preview) but [not available in terraform](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#automatic_channel_upgrade).

Seems like the TF provider `2.79.0`sets it to `none`when you dont specifiy the options but you cant explicitly set `none` : `az aks show -n NAME -g NAME --query autoUpgradeProfile`

**Comment by tombuildsstuff** [comment] 2021-10-04 07:40
👋 

Whilst this is a change in Terraform, unfortunately this is an AKS bug - since submitting the default value to the API shouldn't require this preview feature to be enabled (as it's marked as the default value in the API, too). We've raised this with the AKS Team on Friday, but I'd suggest [opening an issue on the AKS Repository too](https://github.com/Azure/AKS/issues) where someone from that team should be able to take a look.

Thanks!

**Closed by tombuildsstuff** 2021-10-04 07:40 UTC
Labels: question, service/kubernetes-cluster
