### ISSUE TITLE
Support for azurerm_api_management_api missing Tag parameter

### ISSUE THREAD

**Issue by axk511** [hashicorp/terraform-provider-azurerm#13495] opened 2021-09-24 12:28 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In Azure API management, API's can have Tags attached to them to enable searching and grouping. The terraform azurerm_api_management_api resource does not provide a way to add/update tags on API's

### New or Affected Resource(s)

azurerm_api_management_api 

### Potential Terraform Configuration

```hcl

resource "azurerm_api_management_api" "example" {
  name                = "search-api"
  api_management_name = "search-api-management"
  resource_group_name = "search-service"
  revision            = "2"
  tags                = ["Internal", "Group1", "REST"]
}

```

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_api
Screenshot from APIM API option
![image](https://user-images.githubusercontent.com/78821488/134674408-cb36ffeb-7548-46ad-ba99-be032450957a.png)

* #0000

**Comment by tombuildsstuff** [comment] 2021-09-29 10:05
hi @axk511 

Thanks for opening this issue.

Taking a look through this appears to be a duplicate of #12580 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #12580 for updates?

Thanks!

**Closed by tombuildsstuff** 2021-09-29 10:05 UTC
Labels: duplicate, enhancement, service/api-management

**Comment by axk511** [comment] 2021-09-29 12:52
@tombuildsstuff  There are two different object here. 
What I requested was for azurerm_api_management_api. However #12580 is for azurerm_api_management_api_operation which is a different one. 
If #12580 covers both, then I am good with that. But does not look like it is
