### ISSUE TITLE
Conflict when destroying `azurerm_eventhub_consumer_group`

### ISSUE THREAD

**Issue by heoelri** [hashicorp/terraform-provider-azurerm#14535] opened 2021-12-08 09:10 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

* terraform 1.0.10
* hashicorp/azurerm 2.88.1

### Affected Resource(s)

* `azurerm_eventhub`
* `azurerm_eventhub_consumer_group`

### Terraform Configuration Files

```hcl
resource "azurerm_eventhub" "backendqueue" {
  name                = "backendqueue-eh"
  namespace_name      = azurerm_eventhub_namespace.stamp.name
  resource_group_name = azurerm_resource_group.stamp.name

  partition_count   = 32
  message_retention = 7
}

resource "azurerm_eventhub_consumer_group" "backendworker" {
  name                = "backendworker-cs"
  namespace_name      = azurerm_eventhub_namespace.stamp.name
  eventhub_name       = azurerm_eventhub.backendqueue.name
  resource_group_name = azurerm_resource_group.stamp.name
}
```

### Debug Output

* none

### Panic Output

* none

### Expected Behaviour

This is probably more an issue on the Azure side than on TF, but, would it make sense to implement a re-try in case of a 409 response? A re-run of `terraform destroy` usually solves this issue and successfully destroys the consumer group.

@tombuildsstuff general question is a retry based on a HTTP status code in `func (r ConsumerGroupResource) Delete()` ok or not?

### Actual Behaviour

```console
│ Error: deleting Consumer Group (Subscription: "********-****-****-****-cde33c0320a4"
│ Resource Group Name: "aoint098a-stamp-northeurope-rg"
│ Namespace Name: "aoint098a-northeuro-evhns"
│ Event Hub Name: "backendqueue-eh"
│ Consumer Group Name: "backendworker-cs"): consumergroups.ConsumerGroupsClient#Delete: Failure sending request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="Conflict" Message="Resource Conflict Occurred. Another conflicting operation may be in progress. If this is a retry for failed operation, background clean up is still pending. Try again later. To know more visit https://aka.ms/sbResourceMgrExceptions. . TrackingId:1b537053-8d97-433c-97e7-41bd4361f558_M9CH3_M9CH3_G1S1, SystemTracker:aoint098a-northeuro-evhns:EventHub:backendqueue-eh, Timestamp:2021-12-08T03:58:23 CorrelationId: 261eec31-da6f-6e33-fd77-e6a9904a016f"
│ 
│ deleting Consumer Group (Subscription: "********-****-****-****-cde33c0320a4"
│ Resource Group Name: "aoint098a-stamp-northeurope-rg"
│ Namespace Name: "aoint098a-northeuro-evhns"
│ Event Hub Name: "backendqueue-eh"
│ Consumer Group Name: "backendworker-cs"):
│ consumergroups.ConsumerGroupsClient#Delete: Failure sending request:
│ StatusCode=409 -- Original Error: autorest/azure: Service returned an
│ error. Status=<nil> Code="Conflict" Message="Resource Conflict Occurred.
│ Another conflicting operation may be in progress. If this is a retry for
│ failed operation, background clean up is still pending. Try again later. To
│ know more visit https://aka.ms/sbResourceMgrExceptions. .
│ TrackingId:1b537053-8d97-433c-97e7-41bd4361f558_M9CH3_M9CH3_G1S1,
│ SystemTracker:aoint098a-northeuro-evhns:EventHub:backendqueue-eh,
│ Timestamp:2021-12-08T03:58:23 CorrelationId: 261eec31-da6f-6e33-fd77-e6a9904a016f"
```

### Steps to Reproduce

This is hard to reproduce. We're running an end-to-end validation pipeline that spins up a multi-tier application with global and regional components, tests everything and destroys the infrastructure in the end completely. Every now and then is the destroy step failing due to a conflict.

1. `terraform destroy`

### Important Factoids

* none - happens in various regions in Azure Public

### References

* #0000

@sebader FYI

**Comment by xiaxyi** [comment] 2021-12-16 07:53
@heoelri I tried to reproduce the issue multiple times, unfortunately, the issue cannot be reproduced. Can you share more background details such as detailed config, environment with me?

**Comment by sebader** [comment] 2021-12-16 10:36
@xiaxyi you can see the TF definition here: https://github.com/Azure/AlwaysOn/blob/main/src/infra/workload/releaseunit/modules/stamp/eventhub.tf

as you can see, we already tried to put in a explicit depends_on but that didnt help so far

**Comment by xiaxyi** [comment] 2022-04-18 03:14
@sebader I still cannot reproduce the issue with the same configuration, can I confirm with you to see if you are still hitting the error?

**Comment by rcskosir** [comment] 2023-07-26 20:19
Thanks for opening this issue. Since time has passed and @xiaxyi was not able to reproduce this issue, I am going to mark this issue closed as “can’t reproduce”. If you are able to provide more information to help us reproduce this issue we may re-open this issue or open a new issue, thanks!

**Closed by rcskosir** 2023-07-26 20:19 UTC
Labels: bug, waiting-response, service/event-hubs
