### ISSUE TITLE
incorrect documentation

### ISSUE THREAD

**Issue by tradosh** [hashicorp/terraform-provider-azurerm#13418] opened 2021-09-20 13:13 UTC
the example presented here:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/data_protection_backup_instance_blob_storage
is incorrect, attempt to run it as is generate multiple errors

**Comment by favoretti** [comment] 2021-09-21 08:17
Hi there and thank you for reporting this. This appears to be a duplicate of #13403, therefore I'm going to close this one to keep the discussion concise.

**Closed by favoretti** 2021-09-21 08:17 UTC
