### ISSUE TITLE
Resource must be replaced. azurerm_linux_virtual_machine must be replaced

### ISSUE THREAD

**Issue by TheUnixRoot** [hashicorp/terraform-provider-azurerm#8311] opened 2020-09-01 09:38 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.24
+ provider.azurerm v2.25.0
+ provider.template v2.1.2
+ provider.tls v2.2.0

I'm not using 0.13 yet because of this issue which blocks the terrafrom apply required.

### Affected Resource(s)

* `azurerm_linux_virtual_machine`

### Terraform Configuration Files

```hcl
data "azurerm_subnet" "private" {
  name                 = "private"
  resource_group_name  = "gitlab-${var.environment}"
  virtual_network_name = data.azurerm_virtual_network.default.name
}

resource "azurerm_network_interface" "runner" {
  for_each = var.runners

  name                = "${local.prefix}-${each.key}"
  location            = azurerm_resource_group.runner.location
  resource_group_name = azurerm_resource_group.runner.name

  ip_configuration {
    name                          = "ipconfig"
    subnet_id                     = data.azurerm_subnet.private.id
    private_ip_address_allocation = "Dynamic"
  }
}


variable "runners" {
  type = map(object({
    vm_size  = string
    tag_list = string
  }))
}
runners = {
  "standard-1" = {
    vm_size  = "Standard_F2"
    tag_list = "high-memory"
  }
}
resource "azurerm_linux_virtual_machine" "runner" {
  for_each = var.runners

  name                  = "${local.prefix}-${each.key}"
  location              = azurerm_resource_group.runner.location
  resource_group_name   = azurerm_resource_group.runner.name
  size                  = each.value.vm_size
  network_interface_ids = [azurerm_network_interface.runner[each.key].id]
  admin_username        = var.admin_username
  custom_data           = data.template_cloudinit_config.server[each.key].rendered

  admin_ssh_key {
    username   = var.admin_username
    public_key = tls_private_key.ssh_keypair.public_key_openssh
  }

  source_image_reference {
    offer     = var.os_image.offer
    publisher = var.os_image.publisher
    sku       = var.os_image.sku
    version   = var.os_image.version
  }

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
  }
}
```

### Expected Behavior

Nothing to change.

### Actual Behavior
```
  # azurerm_linux_virtual_machine.runner["standard-1"] must be replaced
-/+ resource "azurerm_linux_virtual_machine" "runner" {
        admin_username                  = "admin"
        allow_extension_operations      = true
      ~ computer_name                   = "gitlab-prod-runner-standard-1" -> (known after apply)
      ~ custom_data                     = (sensitive value)
        disable_password_authentication = true
      ~ id                              = "/subscriptions/aaaa0000-aa00-aa00-aa00-aaa000aaa000/resourceGroups/gitlab-prod-runner/providers/Microsoft.Compute/virtualMachines/gitlab-prod-runner-standard-1" -> (known after apply)
        location                        = "switzerlandnorth"
        max_bid_price                   = -1
        name                            = "gitlab-prod-runner-standard-1"
        network_interface_ids           = [
            "/subscriptions/aaaa0000-aa00-aa00-aa00-aaa000aaa000/resourceGroups/gitlab-prod-runner/providers/Microsoft.Network/networkInterfaces/gitlab-prod-runner-standard-1",
        ]
        priority                        = "Regular"
      ~ private_ip_address              = "10.2.0.9" -> (known after apply)
      ~ private_ip_addresses            = [
          - "10.2.0.9",
        ] -> (known after apply)
        provision_vm_agent              = true
      + public_ip_address               = (known after apply)
      ~ public_ip_addresses             = [] -> (known after apply)
        resource_group_name             = "gitlab-prod-runner"
        size                            = "Standard_F2"
      - tags                            = {} -> null
      ~ virtual_machine_id              = "aaaa0000-aa00-aa00-aa00-aaa000aaa000" -> (known after apply)
      + zone                            = (known after apply)

        admin_ssh_key {
            public_key = <<~EOT
                ssh-rsa SOME-KEY
            EOT
            username   = "admin"
        }

      ~ os_disk {
            caching                   = "ReadWrite"
          ~ disk_size_gb              = 30 -> (known after apply)
          ~ name                      = "gitlab-prod-runner-standard-1_OsDisk_1_00000a0cb00b45f7b2b1f7754ecf23d4" -> (known after apply)
            storage_account_type      = "Standard_LRS"
            write_accelerator_enabled = false
        }

        source_image_reference {
            offer     = "UbuntuServer"
            publisher = "Canonical"
            sku       = "18.04-LTS"
            version   = "latest"
        }
    }
```
Plan: 1 to add, 0 to change, 1 to destroy.

### Steps to Reproduce

1. `terraform apply` for creating the vm
2. `terraform plan` for the replace

### Important Factoids
It is running in Switzerland North without Availability Zones

So why is this resource being replaced without any taint nor change which implies recreation.

**Comment by jamesbannan** [comment] 2020-11-19 02:39
I'm seeing the same behaviour, but it's inconsistent. Sometimes the Terraform plan indicates that the VM should be replaced, other times it flags no infrastructure changes necessary.

Deployment is in Australia East, using AzureRM provider version `2.33.0`. Plan shows the same changes needed with version `2.36.0`

The properties which appear to be causing Terraform to flag the resource change are:
```
encryption_at_host_enabled = false -> null
private_ip_addresses = ["IP_ADDRESS"] -> (known after apply)
identity_ids = [] -> null
```

**Comment by jamesbannan** [comment] 2020-11-19 03:49
Further to this, I have tried setting `encryption_at_host_enabled = false` in the VM configuration (even though it's meant to be optional and defaults to `false` anyway). This change removed that particular line from the Terraform plan, but the VM was still flagged to be replaced.

The `identity_ids` block shouldn't be flagged at all as the VM is configured to use a `SystemAssigned` identity, and `identity_ids` is supposed to only be for `UserAssigned`. As a test I tried adding `identity_ids = []` to the `identity` block, but the Terraform plan still contained `identity_ids = [] -> null`.

Like the issue author, there's nothing to indicate why this resource is being replaced.

**Comment by jeromewaibel** [comment] 2020-11-27 11:38
Your plan says it wants to add a "zone". This parameter is optonal, yet leaving it empty seems to force an unnecessary recreation.

zone - (Optional) The Zone in which this Virtual Machine should be created. Changing this forces a new resource to be created.

**Comment by geekzter** [comment] 2021-03-10 19:10
I had the same issues as described here. In my case it happened when VM's were in a deallocated state. This is a broader problem (VM extensions need the VM to be running as well). I have a wrapper script in which I now start VM's and I have not run into the issue since.

**Comment by bernardmaltais** [comment] 2021-04-16 12:20
Any one has found a solution? I also have a VM with the exact problem. It want to be replaced because it report a change with the `private_ip_addredded` being changed... which is not the case.
![image](https://user-images.githubusercontent.com/25299479/115023257-8a6de500-9e8c-11eb-88c2-c810e803625b.png)

**Comment by egorchabala** [comment] 2021-04-16 17:47
Same issue on my side, but window virtual machines. Terraform doesn't show exactly what triggers the redeployment. Still not fixed on my end.

**Comment by bernardmaltais** [comment] 2021-04-16 20:02
@egorchabala I think I found the issue. There is a security policy applied at the tenant level that deploy two server extensions. Linux Agent and Dependency Agent. As long as those are not deployed terraform is happy and will not try to rebuild. As soon as they are installed terraform want to rebuild the VM. I now have taken to install both extensions "pre-emptively" on the VM using terraform code and so far things are holding up!

Maybe you have the same issue on your side?

**Comment by egorchabala** [comment] 2021-04-17 02:50
> @egorchabala I think I found the issue. There is a security policy applied at the tenant level that deploy two server extensions. Linux Agent and Dependency Agent. As long as those are not deployed terraform is happy and will not try to rebuild. As soon as they are installed terraform want to rebuild the VM. I now have taken to install both extensions "pre-emptively" on the VM using terraform code and so far things are holding up!
> 
> Maybe you have the same issue on your side?
> 
> Here is the code I use for the OMS Agent install: https://github.com/canada-ca-terraform-modules/terraform-azurerm-caf-linux_virtual_machine/blob/master/option-40-OmsAgentForLinux.tf
> 
> You can look at the other terraform files in the module repo for code to install the DA Agent also.
> 
> I am also using terraform 0.14.10 and the latest azurerm provider.

I assume that might be the case, but can't find any suspicious extensions. May I ask you to share how you have detected that the issue is in extension?

**Comment by bernardmaltais** [comment] 2021-04-17 11:11
@egorchabala Right after creating the VM I used

https://resources.azure.com/

to look at my VM and swa it had no extensions deployed. After a few hours, when terraform wanted to rebuild, it showed that two extensions were added. Something you could probably do is capture the resource json code in resource explorer after the deployment and compare it with diff after terraform want to replace it to find the code difference that might trigger this.

**Comment by HannesHil** [comment] 2021-05-03 13:54
Hi everyone, we had a quite similar problem. At least for us, it was a problem with the tf planner and the sensitive values of the VM.
The issue should be fixed with the next tf version. https://github.com/hashicorp/terraform/issues/28540#issuecomment-831264982

**Comment by achevalet** [comment] 2021-05-04 18:24
Same issue here:
```
      + public_ip_address               = (known after apply)
      ~ public_ip_addresses             = [] -> (known after apply)
      + zone                            = (known after apply)
```
It looks to be a generic issue when other attributes change.
In my case the trigger appears to be a change in `custom_data` (spotted in the output). When I add this:
```
  lifecycle {
    ignore_changes = [
      custom_data,
    ]
  }
  ```
then it runs fine.

**Comment by HannesHil** [comment] 2021-05-04 18:43
@achevalet Just take a look at https://github.com/hashicorp/terraform/issues/28540 will be fixed in 0.15.2

**Comment by egorchabala** [comment] 2021-05-04 20:25
In my case it was `admin_password`. Adding it to the ignore changes helped.

**Comment by favoretti** [comment] 2021-08-25 10:09
Hi there. Thank you for reporting this issue. Since this issue doesn't seem to have anything to do with provider internals, I'm going to close it, but feel free to re-open it if you feel that this has been closed erroneously.

**Closed by favoretti** 2021-08-25 10:09 UTC
Labels: service/virtual-machine
