### ISSUE TITLE
Support for attaching data disks during booting time of  "azurerm_linux_virtual_machine"

### ISSUE THREAD

**Issue by mazen423** [hashicorp/terraform-provider-azurerm#14168] opened 2021-11-12 14:04 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently the new resource "azurerm_linux_virtual_machine" doesn't support attaching managed data disks while creating the resource but the attachment can only happen with a separate resource  "azurerm_virtual_machine_data_disk_attachment". That behavior leads to the failure of any Cloudinit scripts that are used as "custom_data" to mount and use these during the VM booting while the disks are not attached to the machines yet.

### New or Affected Resource(s)

* azurerm_linux_virtual_machine

### Potential Terraform Configuration

```hcl
resource "azurerm_linux_virtual_machine" "main" {
  name = "xxx"
  ]))
  resource_group_name = "xxx"
  location            = "xx"

  data_disk {
    managed_disk_id= azurerm_managed_disk.main.id, azurerm_managed_disk.secondary.id
   lun                       = "10"
   caching                = "ReadWrite" 

  data_disk {
    managed_disk_id= azurerm_managed_disk.main.id, azurerm_managed_disk.secondary.id
   lun                       = "20"
   caching                = "ReadWrite" 
 
  }
```

**Comment by tombuildsstuff** [comment] 2021-11-12 14:06
hi @mazen423 

Thanks for opening this issue.

Taking a look through this appears to be a duplicate of #6117 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #6117 for updates?

Thanks!

**Closed by tombuildsstuff** 2021-11-12 14:06 UTC
Labels: duplicate, enhancement, service/virtual-machine
