### ISSUE TITLE
pollingTrackerBase#baseCheckForErrors: missing status property in Azure-AsyncOperation response body: StatusCode=0

### ISSUE THREAD

**Issue by jayendranmathaiyan** [hashicorp/terraform-provider-azurerm#22771] opened 2023-08-02 01:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.3.9, 1.5.0

### AzureRM Provider Version

3.67.0

### Affected Resource(s)/Data Source(s)

azurerm_api_management_api

### Terraform Configuration Files

```hcl
resource "azurerm_api_management_api" "apimapi" {
  name                 = "mock-proxy-api"
  resource_group_name  = "apim-rsg"
  api_management_name  = "apim-01"
  revision             = "1"
  revision_description = "Revision 1"
  display_name         = "Mock health check API"
  protocols            = ["https"]
  description          = "Mock health check API"
  version              = "v1"
  version_set_id = (
    var.reuse_existing_version_set ?
    data.azurerm_api_management_api_version_set.apiversionSet[0].id :
    azurerm_api_management_api_version_set.apiversionSet[0].id
  )
  version_description   = "Version 1"
  path                  = "mockapi"
  subscription_required = true

  import {
    content_format = "openapi"
    content_value  = file("${path.root}/api/mockapi.yaml")
  }
}

resource "azurerm_api_management_api_version_set" "apiversionSet" {
  count               = var.reuse_existing_version_set ? 0 : 1
  name                = "mockHealthcheckVersionSet"
  resource_group_name = "apim-rsg"
  api_management_name = "apim-01"
  display_name        = "Mock health check API"
  versioning_scheme   = "Segment"
}


data "azurerm_api_management_api_version_set" "apiversionSet" {
  count               = var.reuse_existing_version_set ? 1 : 0
  name                = "mockHealthcheckVersionSet"
  resource_group_name = "apim-rsg"
  api_management_name = "apim-01"
}
```

### Debug Output/Panic Output

```shell
Error: waiting on creating/updating Api: (Name "mock-proxy-api" / Service Name "apim-01" / Resource Group "apim-rsg"): pollingTrackerBase#baseCheckForErrors: missing status property in Azure-AsyncOperation response body: StatusCode=0
with module.apim-proxydeploy.azurerm_api_management_api.apimapi
on .terraform/modules/apim-proxydeploy/api-deploy.tf line 53, in resource "azurerm_api_management_api" "apimapi":
resource "azurerm_api_management_api" "apimapi" {
```

### Expected Behaviour

The APIM resource azurerm_api_management_api should apply and deploy the API

### Actual Behaviour

Error: waiting on creating/updating Api: (Name "mock-proxy-api" / Service Name "apim-01" / Resource Group "apim-rsg"): pollingTrackerBase#baseCheckForErrors: missing status property in Azure-AsyncOperation response body: StatusCode=0
with module.apim-proxydeploy.azurerm_api_management_api.apimapi
on .terraform/modules/apim-proxydeploy/api-deploy.tf line 53, in resource "azurerm_api_management_api" "apimapi":
resource "azurerm_api_management_api" "apimapi" {

tried different azurerm versions and provides same error

### Steps to Reproduce

terraform apply

### Important Factoids

Same API deployed multiple time before and working fine, these error occurring from last one week . I have tried for most of the last 5 azurerm versions and getting same error.

**Comment by jamesyoung-lbg** [comment] 2023-08-02 10:02
The issue appears to be caused by a change in the API response for `GET /tenant/operationResults` that the azurerm provider is calling to check the status of the long-running operation.

This is an excerpt from a Terraform apply run with `TF_LOG=trace`, showing the HTTP request that is triggering the Azure-AsyncOperation error:

```
2023-07-31T14:29:00.722Z [DEBUG] provider.terraform-provider-azurerm_v3.48.0_x5: AzureRM Request: 
GET /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/resource-group-name/providers/Microsoft.ApiManagement/service/apim-service-name/tenant/operationResults/64c7c459217d2015f86716c7?api-version=2021-08-01 HTTP/1.1
Host: management.azure.com
User-Agent: Go/go1.19.3 (amd64-linux) go-autorest/v14.2.1 Azure-SDK-For-Go/v66.0.0 apimanagement/2021-08-01 HashiCorp Terraform/1.3.7 (+https://www.terraform.io) Terraform Plugin SDK/2.10.1 terraform-provider-azurerm/dev pid-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
X-Ms-Correlation-Request-Id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
Accept-Encoding: gzip: timestamp=2023-07-31T14:29:00.722Z
2023-07-31T14:29:00.873Z [DEBUG] provider.terraform-provider-azurerm_v3.48.0_x5: AzureRM Response for https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/resource-group-name/providers/Microsoft.ApiManagement/service/apim-service-name/tenant/operationResults/64c7c459217d2015f86716c7?api-version=2021-08-01: 
HTTP/2.0 200 OK
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
Date: Mon, 31 Jul 2023 14:29:00 GMT
Expires: -1
Pragma: no-cache
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Ms-Correlation-Request-Id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
X-Ms-Request-Id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
X-Ms-Routing-Request-Id: EASTUS:20230731T142900Z:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

{'value':[]}: timestamp=2023-07-31T14:29:00.873Z
```

So it appears the azurerm provider (or the Azure SDK for Go) is expecting to see a "value" array returned to it, but isn't seeing it.

Poking about with the API directly shows something interesting:

`az rest --method get --url https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/resource-group-name/providers/Microsoft.ApiManagement/service/apim-service-name/tenant/operationResults?api-version=2021-08-01`

(i.e. the "list all results" version of the API call) returns:

```
{
  'count': 138,
  'nextLink': 'https://management.azure.com:443/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/resource-group-name/providers/Microsoft.ApiManagement/service/apim-service-name/tenant/operationResults?api-version=2021-08-01&%24skip=100',
  'value': [
    {
      'status': 'Succeeded'
    },
    {
      'status': 'Succeeded'
    },
    {
      'status': 'Succeeded'
    },
  // Skipped a bunch of results for brevity
  ]
}
```

whereas the "get single result" version of the call:

`az rest --method get --url https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/resource-group-name/providers/Microsoft.ApiManagement/service/apim-service-name/tenant/operationResults/64c90557217d2015f86716e2?api-version=2021-08-01`

returns:
```
{
  'status': 'Succeeded'
}
```
rather than returning something like this, which is what the azurerm provider/go SDK appears to expect:
```
{
  'value': [
    {
      'status': 'Succeeded'
    }
  ]
}
```

So I surmise that a new release of the Microsoft.ApiManagement resource provider has unintentionally changed the API contract.

**Comment by jayendranmathaiyan** [comment] 2023-08-02 10:15
@sinbai pls check above analysis given by @jamesyoung-lbg

**Comment by jamesyoung-lbg** [comment] 2023-08-02 10:45
The same thing happens with the very latest version of the AzureRM provider:

```
2023-08-02T10:34:33.724Z [DEBUG] provider.terraform-provider-azurerm_v3.67.0_x5: AzureRM Response for https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/resource-group-name/providers/Microsoft.ApiManagement/service/apim-service-name/tenant/operationResults/64ca3064217d2015f86718e5?api-version=2021-08-01:
HTTP/2.0 200 OK
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
Date: Wed, 02 Aug 2023 10:34:33 GMT
Expires: -1
Pragma: no-cache
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Ms-Correlation-Request-Id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
X-Ms-Request-Id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
X-Ms-Routing-Request-Id: SOUTHCENTRALUS:20230802T103433Z:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

{"value":[]}: timestamp=2023-08-02T10:34:33.724Z
2023-08-02T10:34:33.725Z [ERROR] provider.terraform-provider-azurerm_v3.67.0_x5: Response contains error diagnostic: @module=sdk.proto diagnostic_summary="waiting on creating/updating Api: (Name "api-name" / Service Name "apim-service-name" / Resource Group "resource-group-name"): pollingTrackerBase#baseCheckForErrors: missing status property in Azure-AsyncOperation response body: StatusCode=0" @caller=github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/diag/diagnostics.go:55 diagnostic_detail= diagnostic_severity=ERROR tf_proto_version=5.3 tf_provider_addr=provider tf_req_id=11bf2c1f-f953-b5c7-ea05-8e1ef2fc0111 tf_resource_type=azurerm_api_management_api tf_rpc=ApplyResourceChange timestamp=2023-08-02T10:34:33.724Z
2023-08-02T10:34:33.728Z [ERROR] vertex "module.api.azurerm_api_management_api.apimapi" error: waiting on creating/updating Api: (Name "api-name" / Service Name "apim-service-name" / Resource Group "resource-group-name"): pollingTrackerBase#baseCheckForErrors: missing status property in Azure-AsyncOperation response body: StatusCode=0
```

**Comment by jayendranmathaiyan** [comment] 2023-08-02 11:47
@sinbai  - can you please which terraform version you are using it?. We are using api management location = "uksouth" and can you please try it.

**Comment by sinbai** [comment] 2023-08-03 08:37
Since all API management terraform resources are being refactored to use hashicorp/go-azure-sdk, could you please wait for this change to be released and try to see if the issue is resolved? See [PR](https://github.com/hashicorp/terraform-provider-azurerm/pull/22783) for more updates.

**Comment by jayendranmathaiyan** [comment] 2023-08-03 18:12
Thanks for the update. 
I hope the refactored Terraform azurerm will handle both HTTP status code as well as 
azurerm single result call GET /tenant/operationResults/**xxxxxxxx**?api-version=2021-08-01 with empty response scenario 
{
  'value': []
}

When will be new version released?

**Comment by tombuildsstuff** [comment] 2023-08-15 11:51
The API version has been updated in #22783, which'll ship in this weeks release - since that should fix this issue I'm going to close this issue for the moment, but please let us know if this is still an issue with this weeks release and we'll take another look

**Closed by tombuildsstuff** 2023-08-15 11:51 UTC
Labels: service/api-management, v/3.x
