### ISSUE TITLE
Management group returns invalid id

### ISSUE THREAD

**Issue by klemmchr** [hashicorp/terraform-provider-azurerm#27470] opened 2024-09-23 21:18 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.6

### AzureRM Provider Version

4.3.0

### Affected Resource(s)/Data Source(s)

azurerm_management_group

### Terraform Configuration Files

```hcl
{
  "//": {
    "metadata": {
      "backend": "azurerm",
      "stackName": "management",
      "version": "0.20.8"
    }
  },
  "data": {
    "azurerm_subscription": {
      "subscription-foo": {
        "//": {
          "metadata": {
            "path": "management/subscription-foo",
            "uniqueId": "subscription-foo"
          }
        },
        "subscription_id": "xxxxxxxx"
      }
    }
  },
  "provider": {
    "azuread": [
      {
        "tenant_id": "xxxxxxxx"
      }
    ],
    "azurerm": [
      {
        "features": [
          {
          }
        ],
        "resource_provider_registrations": "none",
        "storage_use_azuread": true,
        "subscription_id": "xxxxxxxx",
        "tenant_id": "xxxxxxxx",
        "use_cli": true
      }
    ]
  },
  "resource": {
    "azurerm_management_group": {
      "mngmt-management-group-Internal": {
        "//": {
          "metadata": {
            "path": "management/mngmt-management-group-Internal",
            "uniqueId": "mngmt-management-group-Internal"
          }
        },
        "display_name": "Internal",
        "name": "internal",
        "parent_management_group_id": "${data.azurerm_management_group.mngmt-management-group-root.id}"
      }
    },
    "azurerm_management_group_subscription_association": {
      "mngmt-subscription-foo-assoc-internal": {
        "//": {
          "metadata": {
            "path": "management/mngmt-subscription-foo-assoc-internal",
            "uniqueId": "mngmt-subscription-foo-assoc-internal"
          }
        },
        "management_group_id": "${azurerm_management_group.mngmt-management-group-Internal.id}",
        "subscription_id": "${data.azurerm_subscription.subscription-foo.id}"
      }
    }
  },
  "terraform": {
    "required_providers": {
      "azuread": {
        "source": "hashicorp/azuread",
        "version": "2.53.1"
      },
      "azurerm": {
        "source": "azurerm",
        "version": "4.3.0"
      }
    }
  }
}
```

### Debug Output/Panic Output

```shell
Error: parsing "/managementGroup/internal/subscription/xxxxxxxx": parsing the Subscription ID: the number of segments didn't match

Expected a Subscription ID that matched (containing 6 segments):

> /providers/Microsoft.Management/managementGroups/groupIdValue/subscriptions/12345678-1234-9876-4563-123456789012

However this value was provided (which was parsed into 0 segments):

> /managementGroup/internal/subscription/xxxxxxxx

The following Segments are expected:

* Segment 0 - this should be the literal value "providers"
* Segment 1 - this should be the name of the Resource Provider [for example 'Microsoft.Management']
* Segment 2 - this should be the literal value "managementGroups"
* Segment 3 - this should be the user specified value for this groupId [for example "groupIdValue"]
* Segment 4 - this should be the literal value "subscriptions"
* Segment 5 - this should be the UUID of the Azure Subscription

The following Segments were parsed:

* Segment 0 - not found
* Segment 1 - not found
* Segment 2 - not found
* Segment 3 - not found
* Segment 4 - not found
* Segment 5 - not found


  with azurerm_management_group_subscription_association.mngmt-subscription-foo-assoc-internal,
  on cdk.tf.json line 218, in resource.azurerm_management_group_subscription_association.mngmt-subscription-foo-assoc-internal:
 218:       },
```

### Expected Behaviour

In 3.x the provided configuration worked fine. In 4.x it breaks because the id output of the management group is malformed. I'm not sure whether this is a breaking change that is not documented or if this is an actual bug.

**Comment by jgresc** [comment] 2024-09-24 05:55
Same here. The issue occurs in 4.3, no issues in 4.2

**Comment by ms-zhenhua** [comment] 2024-09-25 02:55
@jgresc , @rcskosir , yes, it's a duplicated issue and the PR will fix it.

**Comment by rcskosir** [comment] 2024-09-25 15:02
Thanks! As such, I am going to mark this as a duplicate of #27449 and close it, please follow that discussion and PR #27461 for the resolution.

**Closed by rcskosir** 2024-09-25 15:02 UTC
Labels: bug, duplicate, service/management-groups, v/4.x
