### ISSUE TITLE
azurerm_storage_account list_keys not gracefully degrading

### ISSUE THREAD

**Issue by abassett-nh** [hashicorp/terraform-provider-azurerm#11994] opened 2021-05-27 19:36 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.15.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.58.0

### Affected Resource(s)

* `azurerm_storage_account`

### Debug Output

```
Error: Error listing Keys for Storage Account "snip" (Resource Group "snip"): storage.AccountsClient#ListKeys: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client 'snip' with object id 'snip' does not have authorization to perform action 'Microsoft.Storage/storageAccounts/listKeys/action' over scope '/subscriptions/snip/resourceGroups/snip/providers/Microsoft.Storage/storageAccounts/snip' or the scope is invalid. If access was recently granted, please refresh your credentials."
````

### Expected Behaviour

I am using terraform against a subscription for which I have `Reader` role and a storage account for which I have `Storage Blob Data Reader` access. When running terraform plan against this storage account, I receive the above error for access denied to list keys. Per #4248,  #4138 and 6de6c92 this should gracefully degrade by leaving the keys blank rather than error.

### Actual Behaviour

Received an error instead of blank keys.

### Steps to Reproduce

attempt to run `terraform plan` with an `azurerm_storage_account` pointed at astorage account for which you only have `Storage Blob Data Reader` in a subscription for which you only have `Reader` access.

### Important Factoids

It looks like the orignal fixed allowed status code 401, but I'm receiving a 403, maybe the api changed?
### References

* #4248
* #4138
* 6de6c92

**Comment by tombuildsstuff** [comment] 2021-11-17 10:42
hi @abassett-nh 

Thanks for opening this issue - apologies for the delayed reply here.

Resources and Data Sources in Terraform take a different approach to graceful degradation of permissions, since Resources go through the full CRUD lifecycle, we assume that we have access to all of these (since we'll need these to be able to query all of the API's as necessary to be able to perform a Plan). Data Sources on the other hand assume we have direct access to the Resource (e.g. the Storage Account) and any optional resources within it, however when listing access keys we (as a general rule, there may be some exceptions) list the Access Keys and then gracefully degrade into outputting these as empty strings.

In the case of Storage it's unfortunately a little more complicated for a couple of reasons:

1. A large portion of the Storage functionality is Data-Plane only (e.g. the functionality isn't available in Resource Manager, or isn't available without a breaking change in permissions) which we need to look up the Plan
2. The `ListKeys` operation for a Storage Account returns a 403 when there's a `ReadOnly` Management Lock on the Storage Account since listing the Access Keys is marked as a Write operation in the API (which is arguably an API bug, but a practicality today).

The first point there's the main challenge, whilst some functionality may be available within the Resource Manager API - since these two aren't feature-compatible - and where they are, there's a different in permissions - particularly where the `Contributor` role assignment is involved, and older `Contributor` role assignments don't include the `Storage Contributor` permission, but newer ones do, and telling the difference is non-trivial.

Since we need to be able to reach out to the Data Plane API for the Plan, as mentioned above the Terraform Resource assumes that we have access to both List the Keys (via the Resource Manager API) and then access the Data Plane API to be able to determine if there's any changes to the configuration.

There's an issue tracking support for moving the Storage Resources (#2977) over to using the Resource Manager API where possible, but the Data Plane API itself will still be required for other Resources where the Service Team have no plans to port this functionality over the Resource Manager API.

As such unfortunately this is currently by design since the API requires us to reach out to the Data Plane API - however I believe this'll ultimately be solved by #2977 where we use the Resource Manager API where possible. As such rather than having multiple issues open tracking the same thing, I'm going to close this issue for the moment - but would you mind subscribing to #2977 for updates?

Thanks!

**Closed by tombuildsstuff** 2021-11-17 10:42 UTC
Labels: service/storage
