### ISSUE TITLE
"azurerm_cognitive_deployment" scale settings of account deployment is deprecated since API version '2023-05-01', please use 'sku' instead 

### ISSUE THREAD

**Issue by jayendranarumugam** [hashicorp/terraform-provider-azurerm#22377] opened 2023-07-05 12:16 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.0

### AzureRM Provider Version

3.63.0

### Affected Resource(s)/Data Source(s)

azurerm_cognitive_deployment

### Terraform Configuration Files

```hcl
resource "azurerm_cognitive_deployment" "example" {
  name                 = "example-cd"
  cognitive_account_id = azurerm_cognitive_account.example.id
  model {
    format  = "OpenAI"
    name    = "gpt-35-turbo"
    version = "0613"
  }

  scale {
    type = "Standard"
  }
}
```

### Debug Output/Panic Output

```shell
Deployment Name: "gpt-35-turbo-deployment"): performing CreateOrUpdate: unexpected status 400 with error: InvalidResourceProperties: The specified scale type 'Standard' of account deployment is not supported by the model 'gpt-35-turbo'.
```

### Expected Behaviour

As per the [doc](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cognitive_deployment) 

> A scale block supports the following:
> 
> type - (Required) Deployment scale type. Possible value is Standard. Changing this forces a new resource to be created.
> 

However, the newer models like `gpt-4` , `gpt-4-32k`,`gpt-35-turbo (version 0613)` and `gpt-35-turbo-16k (version 0613)` have a empty or null sclae_types and they deprecate the scale for sku from `2023-05-01` version

### Actual Behaviour

Terraform should migrate to the new version `2023-05-01` with `sku` property instead of `scale`

```
  "sku": {
    "name": "Standard"
    "capacity": 120
  }
```

### Important Factoids

Currently GO SDK does not support this version . So i have created an issue to include that https://github.com/Azure/azure-sdk-for-go/issues/21103

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/22169#issuecomment-1621228564

https://techcommunity.microsoft.com/t5/ai-cognitive-services-blog/introducing-new-and-updated-models-to-azure-openai-service/bc-p/3865647/highlight/true#M510

**Comment by tombuildsstuff** [comment] 2023-07-06 10:55
hey @jayendranarumugam 

This new API Version is available in `hashicorp/go-azure-sdk` - as such https://github.com/hashicorp/terraform-provider-azurerm/pull/22223 is working through migrating to that SDK instead, which'll ultimately fix #22198 (which I believe this issue is a duplicate of).

As such whilst I'd like to thank you for opening this issue, since #22198 is tracking supporting the `sku` block (which is being worked through in #22223) - I'm going to close this issue in favour of #22198, would you mind subscribing to that issue for updates?

Thanks!

**Closed by tombuildsstuff** 2023-07-06 10:55 UTC
Labels: duplicate, enhancement, service/cognitive-services

**Comment by RyanRogersMicrosoft** [comment] 2023-09-01 18:28
Has anyone seen this error:
Message: The specified scale type 'Standard' of account deployment is not supported by the model 'gpt-35-turbo'.
from these configs:

openai.api_version = "2023-05-15"
model_name = "gpt-35-turbo"
deployment_name = "gpt-35-turbo"
model_version = "0613"
For ref:
    deployment = client.deployments.begin_create_or_update( resource_group_name=cog_rg, account_name=openai_instance_name, deployment_name=deployment_name, content_type = 'application/json', deployment={ "properties": { "model": { "format": "OpenAI", "name": model, "version": model_version }, "scaleSettings": { "scaleType": "Standard" } }, "sku": { "capacity": 1 } } )
And when I remove the scaleSettings section above I get:
Code: InvalidResourceProperties
Message: The scale settings of account deployment is invalid.

**Comment by janaka** [comment] 2023-10-26 16:42
@RyanRogersMicrosoft I do but via ARM. I get it when trying to deploy to `uk south` but not `east us`. Note: my version config are different.
