### ISSUE TITLE
Virtual Machine Scale Set incorrectly updates os_disk parameters

### ISSUE THREAD

**Issue by justinhopper** [hashicorp/terraform-provider-azurerm#10626] opened 2021-02-17 23:38 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

terraform: v0.13 (because we are locked into a version for this project)
azurerm provider: v2.47.0_x5 (latest as of this writing)

### Affected Resource(s)

azurerm_linux_virtual_machine_scale_set

### Terraform Configuration Files

```hcl
  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "Premium_LRS"
    disk_size_gb         = var.volume_size
  }
```

### Debug Output

I know the guide says to make a link to a gist, but this is a very short and sweet debug output that cuts straight to the issue:

```2021-02-17T14:52:29.632-0800 [DEBUG] plugin.terraform-provider-azurerm_v2.47.0_x5: }
2021/02/17 14:52:29 [WARN] Provider "registry.terraform.io/hashicorp/azurerm" produced an unexpected new value for module.poc-azure-w2-jhop1-cluster.module.worker_ss["pool1"].azurerm_linux_virtual_machine_scale_set.work_ss, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .os_disk[0].disk_size_gb: was cty.NumberIntVal(150), but now cty.NumberIntVal(30)
      - .os_disk[0].storage_account_type: was cty.StringVal("Premium_LRS"), but now cty.StringVal("Standard_LRS")
```

### Panic Output

No panic

### Expected Behaviour

I updated only the source_image_id field of the virtual machine scale set and expect only that value to change.

### Actual Behaviour

When TerraForm runs, it alters the os_disk fields as well, just as the WARN above spells out.

### Steps to Reproduce

Create a VMSS, update the source_image_id field, run `terraform apply` and it will change the os_disk parameters of the VMSS when you made no changes to those fields..

### Important Factoids

Not sure if it's related, but we have enabled the following feature:

```hcl
  features {
    virtual_machine_scale_set {
      roll_instances_when_required = false
    }
  }
```

Our objective was to update just the source_image_id of the VMSS and not have any automatic node updates take place.

### References

No other references at this time.

**Comment by ssemyan** [comment] 2021-02-24 21:50
More info and a repro case: 

Changing a Standard storage base image in a VMSS that is using Premium storage will cause this error when “roll_instances_when_required = false” and the apply happens twice. The first apply will update the source ID but does not update the instances (they are marked as old but still exist). In the second apply, Terraform is force updating the instances to the new version (because it thinks they are using Standard storage). 
 
Repro: 
1.	Create two managed images, both in standard storage. I created an Ubuntu VM, generalized it and created the images like so: 
az image create -g tfbug -n bugimgstd1 --source ubun_OsDisk_1_id --storage-sku Standard_LRS --os-type Linux
az image create -g tfbug -n bugimgstd2 --source ubun_OsDisk_1_id --storage-sku Standard_LRS --os-type Linux
2.	Create the VMSS (tf apply) using the value bugimgstd1 for the source image (use files below)
3.	Change the value of the source image to bugimgstd2 and apply the change
4.	Without changing anything, do a terraform plan
 
Result: terraform thinks the OS disk needs to be updated (it must be ignoring the roll_instances_when_required = false setting in this case)
 
Expected result: terraform should know that the source image is the proper source image and the plan should indicate there is nothing to do. 
 
Here is the output from the plan (note the os_disk section):
``` 
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement
 
Terraform will perform the following actions:
 
  # azurerm_linux_virtual_machine_scale_set.work_ss must be replaced
-/+ resource "azurerm_linux_virtual_machine_scale_set" "work_ss" {
        admin_username                                    = "scottse"
      ~ computer_name_prefix                              = "bugscaleset" -> (known after apply)
        disable_password_authentication                   = true
        do_not_run_extensions_on_overprovisioned_machines = false
      - encryption_at_host_enabled                        = false -> null
        extensions_time_budget                            = "PT1H30M"
      ~ id                                                = "/subscriptions/subscriptionid/resourceGroups/tfbug3/providers/Microsoft.Compute/virtualMachineScaleSets/bugscaleset" -> (known after apply)
        instances                                         = 2
        location                                          = "westus2"
        max_bid_price                                     = -1
        name                                              = "bugscaleset"
        overprovision                                     = false
      ~ platform_fault_domain_count                       = 0 -> (known after apply)
        priority                                          = "Regular"
        provision_vm_agent                                = true
        resource_group_name                               = "tfbug3"
        scale_in_policy                                   = "Default"
        single_placement_group                            = true
        sku                                               = "Standard_DS1_v2"
        source_image_id                                   = "/subscriptions/subscriptionid/resourceGroups/tfbug/providers/Microsoft.Compute/images/bugimgstd2"
      - tags                                              = {} -> null
      ~ unique_id                                         = "fb5e8457-b35c-4140-9247-da832055bc34" -> (known after apply)
        upgrade_mode                                      = "Manual"
        zone_balance                                      = false
      - zones                                             = [] -> null
 
        admin_ssh_key {
            public_key = <<~EOT
                ssh-rsa xxx
            EOT
            username   = "adminuser"
        }
 
      ~ automatic_instance_repair {
          ~ enabled      = false -> (known after apply)
          ~ grace_period = "PT30M" -> (known after apply)
        }
 
     + extension {
          + auto_upgrade_minor_version = (known after apply)
          + force_update_tag           = (known after apply)
          + name                       = (known after apply)
          + protected_settings         = (sensitive value)
          + provision_after_extensions = (known after apply)
          + publisher                  = (known after apply)
          + settings                   = (known after apply)
          + type                       = (known after apply)
          + type_handler_version       = (known after apply)
        }
 
      ~ network_interface {
          - dns_servers                   = [] -> null
            enable_accelerated_networking = false
            enable_ip_forwarding          = false
            name                          = "bugnic"
            network_security_group_id     = "/subscriptions/subscriptionid/resourceGroups/tfbug/providers/Microsoft.Network/networkSecurityGroups/bugnsg"
            primary                       = true
 
          ~ ip_configuration {
              - application_gateway_backend_address_pool_ids = [] -> null
              - application_security_group_ids               = [] -> null
              - load_balancer_backend_address_pool_ids       = [] -> null
              - load_balancer_inbound_nat_rules_ids          = [] -> null
                name                                         = "internal"
                primary                                      = true
                subnet_id                                    = "/subscriptions/subscriptionid/resourceGroups/tfbug/providers/Microsoft.Network/virtualNetworks/bugnet/subnets/bugsubnet"
                version                                      = "IPv4"
            }
        }
 
      ~ os_disk {
          ~ caching                   = "None" -> "ReadWrite"
            disk_size_gb              = 30
          ~ storage_account_type      = "Standard_LRS" -> "Premium_LRS" # forces replacement
            write_accelerator_enabled = false
        }
 
     + terminate_notification {
          + enabled = (known after apply)
          + timeout = (known after apply)
        }
    }
 
Plan: 1 to add, 0 to change, 1 to destroy.
```

vmss.tf 
```
provider "azurerm" {
  version = "=2.47.0"
  features {
    virtual_machine_scale_set {
      roll_instances_when_required = false
    }
  }
}

# Get resource group for shared resources
data "azurerm_resource_group" "shared_group" {
  name     = var.shared_resource_group
}

# Create a new resource group
resource "azurerm_resource_group" "bug_group" {
  name     = var.vmss_resource_group
  location = data.azurerm_resource_group.shared_group.location
}

# Get the ID of the image (from another resource group)
data "azurerm_image" "worker_ss_image" {
  name                = var.vmss_image_name
  resource_group_name = data.azurerm_resource_group.shared_group.name
}

# Get the ID of the subnet
data "azurerm_subnet" "bug_subnet" {
  name                 = var.subnet_name
  virtual_network_name = var.vnet_name
  resource_group_name  = data.azurerm_resource_group.shared_group.name
}

# Get the NSG
data "azurerm_network_security_group" "bug_nsg" {
  name                = var.nsg_name
  resource_group_name = data.azurerm_resource_group.shared_group.name
}

# Create the vmss
resource "azurerm_linux_virtual_machine_scale_set" "work_ss" { 
  lifecycle {
    ignore_changes = [
      network_interface, instances, tags
    ]
  }
 
  name                = var.vmss_name
  resource_group_name = azurerm_resource_group.bug_group.name
  location            = azurerm_resource_group.bug_group.location
  sku                 = "Standard_DS1_v2"
  instances           = 2
  admin_username      = var.vmss_admin
 
  admin_ssh_key {
    username          = var.vmss_admin
    public_key        = file("~/.ssh/id_rsa.pub")
  }

  overprovision       = false
  source_image_id     = data.azurerm_image.worker_ss_image.id
 
  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "Premium_LRS"
    disk_size_gb         = 30
  }
 
  network_interface {
    name    = "bugnic"
    primary = true
    network_security_group_id = data.azurerm_network_security_group.bug_nsg.id
 
    ip_configuration {
      name       = "internal"
      subnet_id  = data.azurerm_subnet.bug_subnet.id
      primary    = true
    }
  }
}
```
vars.tf
```
variable "shared_resource_group" {
}

variable "region" {
}

variable "vmss_resource_group" {
}

variable "vmss_image_name" {
}

variable "vnet_name" {
}

variable "subnet_name" {
}

variable "nsg_name" {
}

variable "vmss_name" {
}

variable "vmss_admin" {
}
```
common.tfvars
```
shared_resource_group = "tfbug"
vmss_resource_group   = "tfbug3"
region                = "westus2"
vmss_image_name       = "bugimgstd2"
vnet_name             = "bugnet"
subnet_name           = "bugsubnet"
nsg_name              = "bugnsg"
vmss_name             = "bugscaleset"
vmss_admin            = "adminuser"
```

**Comment by ArcturusZhang** [comment] 2021-02-25 07:02
Hi @justinhopper thanks for opening this issue!

This should be an upstream issue (I have created one here https://github.com/Azure/azure-rest-api-specs/issues/13164) after I reproduced this and examined the terraform log.

**Comment by ssemyan** [comment] 2021-02-26 19:44
A more serious aspect of this issue (and likely more common) is when a user has Auto Update turned on. In this case, changing the source image ID will reset the disk size and storage type of all instances to the size and type of the source image. I have verified this is what happens. 

I assume it is common to generate small source images and store them in cheaper Standard storage (when not using a Shared Image Gallery), and to make the disks larger and use Premium storage when using them in a VMSS.

**Comment by rcskosir** [comment] 2024-03-15 19:41
Based on the upstream issue being resolved with a fix rolled out, I am going to mark this issue as closed. If you are using the latest version of the provider and still experiencing this issue, please do let us know by opening a new issue, thanks!

https://github.com/Azure/azure-rest-api-specs/issues/13164

**Closed by rcskosir** 2024-03-15 19:41 UTC
Labels: bug, service/vmss, upstream/microsoft, v/2.x (legacy)
