### ISSUE TITLE
azurerm_firewall_network_rule_collection - Terraform plan shows all rules in a rulecollection will be dropped and recreated, when just 1 rule is modified. Makes it very difficult to read plans when a few rules are there in the collection.

### ISSUE THREAD

**Issue by miniGweek** [hashicorp/terraform-provider-azurerm#11181] opened 2021-03-31 21:53 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.14.9
azurerm = {
      source  = "hashicorp/azurerm"
      version = "2.49.0"
    }
```

### Affected Resource(s)

- `azurerm_firewall_network_rule_collection`

### Terraform Configuration Files

```hcl
locals {
  location      = "australiaeast"
  resourcegroup = "rg-mssqlvm"
}

terraform {
  backend "local"{}
}

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "2.49.0"
    }
  }
}

provider "azurerm" {
  tenant_id                  = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  skip_provider_registration = true
  features {}
}

resource "azurerm_resource_group" "resourcegroup" {
  name     = local.resourcegroup
  location = local.location
}

resource "azurerm_virtual_network" "vnet" {
  name                = "vnet-mssql"
  resource_group_name = azurerm_resource_group.resourcegroup.name
  location            = local.location
  address_space       = ["10.0.0.0/24"]
}

resource "azurerm_subnet" "subnet" {
  name                 = "snet-mssql"
  virtual_network_name = azurerm_virtual_network.vnet.name
  resource_group_name  = azurerm_resource_group.resourcegroup.name
  address_prefixes     = ["10.0.0.0/26"]
}

resource "azurerm_subnet" "azurefirewall_subnet" {
  name                 = "AzureFirewallSubnet"
  virtual_network_name = azurerm_virtual_network.vnet.name
  resource_group_name  = azurerm_resource_group.resourcegroup.name
  address_prefixes     = ["10.0.0.64/26"]
}

resource "azurerm_firewall" "example" {
  name                = "afw-mssql"
  location            = local.location
  resource_group_name = azurerm_resource_group.resourcegroup.name
  ip_configuration {
    name                 = "configuration"
    subnet_id            = azurerm_subnet.azurefirewall_subnet.id
    public_ip_address_id = azurerm_public_ip.azure_firewall_pip.id
  }
}


resource "azurerm_public_ip" "azure_firewall_pip" {
  name                = "afw-mssql-pip"
  sku                 = "Standard"
  location            = local.location
  resource_group_name = azurerm_resource_group.resourcegroup.name
  allocation_method   = "Static"
}


resource "azurerm_firewall_network_rule_collection" "example-rule" {
  depends_on = [azurerm_firewall.example]

  name                = "Example-RuleCollection"
  azure_firewall_name = azurerm_firewall.example.name
  resource_group_name = azurerm_resource_group.resourcegroup.name
  priority            = 201
  action              = "Allow"

  rule {
    name                  = "Allow_From_SomeSource_TCP_01"
    source_addresses      = ["10.0.0.5"]
    destination_addresses = ["10.0.0.128"]
    destination_ports     = ["80", "443"]
    protocols             = ["TCP"]
  }

  rule {
    name                  = "Allow_From_SomeSource_TCP_02"
    source_addresses      = ["10.0.0.6"]
    destination_addresses = ["10.0.0.128"]
    destination_ports     = ["3000","445"]
    protocols             = ["TCP"]
  }
}

```

### Debug Output

[Terraform Plan Trace log](https://gist.github.com/miniGweek/fbaadb4fad8b26e20895005ddb8a6889)

### Expected Behaviour

Rule `Allow_From_SomeSource_TCP_01` was modified by adding 1 additional port to the `destination_ports` argument. 
`destination_ports     = ["80", "443"]`
was modified to
`destination_ports     = ["22", "80", "443"]` and then plan was run.

Expected `terraform plan` to show that :
- The rule `Allow_From_SomeSource_TCP_01` as getting modified
- Only port `22` port was being added. 
- The rule `Allow_From_SomeSource_TCP_02` is unmodified.

### Actual Behaviour
Plan shows that all the rules in the collection will be dropped, and recreated.
This makes it very hard to read the plan where quite a few rules are there in the rule collection.

Actual `terraform plan -no-color` output
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # azurerm_firewall_network_rule_collection.example-rule will be updated in-place
  ~ resource "azurerm_firewall_network_rule_collection" "example-rule" {
        id                  = "/subscriptions/e20188c8-8f88-4d61-9a57-49937d29af39/resourceGroups/rg-mssqlvm/providers/Microsoft.Network/azureFirewalls/afw-mssql/networkRuleCollections/Example-RuleCollection"
        name                = "Example-RuleCollection"
        # (4 unchanged attributes hidden)

      + rule {
          + destination_addresses = [
              + "10.0.0.128",
            ]
          + destination_fqdns     = []
          + destination_ip_groups = []
          + destination_ports     = [
              + "22",
              + "443",
              + "80",
            ]
          + name                  = "Allow_From_SomeSource_TCP_01"
          + protocols             = [
              + "TCP",
            ]
          + source_addresses      = [
              + "10.0.0.5",
            ]
          + source_ip_groups      = []
        }
      - rule {
          - destination_addresses = [
              - "10.0.0.128",
            ] -> null
          - destination_fqdns     = [] -> null
          - destination_ip_groups = [] -> null
          - destination_ports     = [
              - "3000",
              - "445",
            ] -> null
          - name                  = "Allow_From_SomeSource_TCP_02" -> null
          - protocols             = [
              - "TCP",
            ] -> null
          - source_addresses      = [
              - "10.0.0.6",
            ] -> null
          - source_ip_groups      = [] -> null
        }
      - rule {
          - destination_addresses = [
              - "10.0.0.128",
            ] -> null
          - destination_fqdns     = [] -> null
          - destination_ip_groups = [] -> null
          - destination_ports     = [
              - "443",
              - "80",
            ] -> null
          - name                  = "Allow_From_SomeSource_TCP_01" -> null
          - protocols             = [
              - "TCP",
            ] -> null
          - source_addresses      = [
              - "10.0.0.5",
            ] -> null
          - source_ip_groups      = [] -> null
        }
      + rule {
          + destination_addresses = [
              + "10.0.0.128",
            ]
          + destination_fqdns     = []
          + destination_ip_groups = []
          + destination_ports     = [
              + "3000",
              + "445",
            ]
          + name                  = "Allow_From_SomeSource_TCP_02"
          + protocols             = [
              + "TCP",
            ]
          + source_addresses      = [
              + "10.0.0.6",
            ]
          + source_ip_groups      = []
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.
```

### Steps to Reproduce

1. Run the apply on the above configuration `terrafrom apply`
2. Add/Delete a port  from `destination_ports` from any rule.
3. Run `terrafom plan`

### Important Factoids

N/A

### References

N/A

- #0000

**Comment by lflint** [comment] 2021-04-01 01:58
Also happening for v2.53 of the AzureRM Provider.

**Comment by crawfs** [comment] 2021-05-03 00:47
Did some investigation on this seeing the same issue in my own deployments, funnily enough the issue does not occur for the `azurerm_firewall_application_rule_collection` resource, as the application rule collection resource correctly modifies the attributes in the `rule` block rather than triggering a redeployment of the rules as happens with the network collection resource:

```
  ~ resource "azurerm_firewall_application_rule_collection" "management_rules" {
        id                  = "/subscriptions/***/resourceGroups/***/providers/Microsoft.Network/azureFirewalls/***/applicationRuleCollections/management"
        name                = "management"
        # (4 unchanged attributes hidden)

      ~ rule {
          ~ name             = "AllowAKSAccess" -> "AllowAKSAccess-"
            # (4 unchanged attributes hidden)

            # (1 unchanged block hidden)
        }
        # (6 unchanged blocks hidden)
    }
```

Whereas the same change (modifying the rule name) would trigger a recreation of the rule as shown in the original post of issue.

**Comment by kahawai-sre** [comment] 2021-05-14 01:02
We have tested this as well with the same results. I see this is tagged as an enhancement/feature. Should this not be considered a bug?
It is a major constraint for us in the context of large scale deployments where destroy and recreate of all rules in a collection/policy simply will not scale or allow us to keep SLA. 

Any priority that can be put on resolving this would be greatly appreciated 👍

**Comment by gotojeffray** [comment] 2021-05-16 23:43
Hi there, we have the same issue too. it's very hard to read or find out the change when we have dozens of rules.   Hope this issue can be resolved soon.

**Comment by adamday2** [comment] 2021-06-16 15:37
I believe this ticket may be related as the symptom is the same https://github.com/terraform-providers/terraform-provider-azurerm/issues/10083

Essentially, using a `azurerm_firewall_policy_rule_collection_group` causes the same problem

**Comment by 93420** [comment] 2021-07-06 14:27
Same thing here.
Each deployment impacts production, when all the rules are recreated for a single modification. It doesn't make sense.
:-/

**Comment by davetustin** [comment] 2021-08-10 13:57
Just like to add that we are experiencing the same, so we are unable to apply rule config changes during working hours. Hopefully there will be a fix soon for this.

**Comment by abkrrc** [comment] 2021-08-10 14:27
Well this is almost cause for not using terraform to manage AZ firewall - are anyone from HashiCorp focused on this?

**Comment by PlanetWilson** [comment] 2021-08-11 08:48
Same issue here, it means that when we have used web categories (which aren't even supported in this), each run of TF wants to drop and recreate the entire rule collection. I can't really manage the firewall with this.

**Comment by adamday2** [comment] 2021-09-10 18:05
@gro1m FYI - I believe the recent changes to support premium have inadvertently made this issue worse.

Previously, updates would force the recreation of a singular `application_rule_collection` or `newtork_rule_collection`, but after upgrading to 2.76 (from 2.65), it now it forces the recreation of all rule collections in the `azurerm_firewall_policy_rule_collection_group`

**Comment by gro1m** [comment] 2021-09-10 20:29
@adamday2 I do not think so: https://github.com/hashicorp/terraform-provider-azurerm/issues/10083
I thought about looking into this, but I did not see any obvious mistake right away and I am also not part of the maintainers. Would hope that this issue could be addressed by someone but unfortunately I am probably not part of the solution here.

**Comment by adamday2** [comment] 2021-09-12 20:41
@gro1m Yeah looking over your MR, I don't think it could have been the specific cause of any new issues. I'll have to dig a little deeper to see if there's any specific differences in the output between 2.76 and 2.75, but my guess is that whatever is incorrectly triggering all the rules to be created in the first place may be affected by the addition of the new fields when a change in one of the rules occurs.

**Comment by MoritzSchuermann** [comment] 2021-10-05 14:59
Another problem is that this is an "old" resource for the Azure firewall. It is not possible to use it with the "new" policy approach. What we would need is a dedicated resource like azurerm_firewall_network_rule or azurerm_firewall_application_rule like there is for a route table or network security group!

**Comment by Dilergore** [comment] 2022-01-03 11:57
> Another problem is that this is an "old" resource for the Azure firewall. It is not possible to use it with the "new" policy approach. What we would need is a dedicated resource like azurerm_firewall_network_rule or azurerm_firewall_application_rule like there is for a route table or network security group!

I completely agree. The approach should be that every rule in the collection is handled separately like what you can do with NSGs. This is a major bug IMO, it would be better not to support this in its current form until it gets fixed. With the current way since the plan is not readable it is very easy to make a mistake, moreover it looks like that the entire collection gets recreated which according to [this comment](https://github.com/hashicorp/terraform-provider-azurerm/issues/10083#issuecomment-934492168) is not the case.

This must get some attention.

**Comment by JayDoubleu** [comment] 2022-01-03 12:22
It would be great to have some news regarding this and other issues.
Recently usage of terraform has become the main source of technical debt in most projects I've been working on.
We spend more time troubleshooting and creating workarounds around terraform rather than infrastructure itself to a point where we're more and more in need of terraform engineers with experience of fixing and troubleshooting problems with terraform rather than experience with cloud providers on it's own. 

This is not sustainable.

**Comment by magodo** [comment] 2022-01-04 02:57
The issue is due to [the `rule` block is of type **set**](https://github.com/hashicorp/terraform-provider-azurerm/blob/d6b935f75fc0b4818783ff90e5bd4d4465903c75/internal/services/firewall/firewall_network_rule_collection_resource.go#L73) for `azurerm_firewall_network_rule_collection`, while it is of type **list** for `azurerm_firewall_application_rule_collection`.

There are typically two reasons to use the **set** type:

1. It allows users to reorder the elements inside the array, without getting a plan diff
2. Some API will return the elements without honoring its original order, in which case we have to use the **set**

It turns out the first benefit is not more valuable than a readable plan. I'll contact with the Azure firewall team to confirm whether the rule order is reserved in turns of API. If that is the case, I can further change the types to list then.

**Closed** 2022-03-22 04:26 UTC
Labels: enhancement, service/firewall
