### ISSUE TITLE
azure automation runbook doesn't support parameter block

### ISSUE THREAD

**Issue by dpk09** [hashicorp/terraform-provider-azurerm#19116] opened 2022-11-03 06:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

I'm creating an autoamtion runbook as described here in the official documentation https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/automation_runbook. This doesn't support the parameter block type.

my expectaion is that when you declare the parameters here it should be picked in the runbook

### Terraform Version

1.3.4

### AzureRM Provider Version

3.12.0

### Affected Resource(s)/Data Source(s)

azurerm_automation_runbook

### Terraform Configuration Files

```hcl
Below is my code:

resource "azurerm_automation_runbook" "aks_stop" {  
  resource_group_name     = azurerm_resource_group.platform_rg.name
  name                    = "aks-stop"
  location                = azurerm_resource_group.platform_rg.location
  automation_account_name = azurerm_automation_account.automation_account.name
  log_verbose             = "true"
  log_progress            = "true"
  description             = "Tagetik AKS Stop"
  runbook_type            = "PowerShell"
  content                 = file("../runbooks/scripts/stop_AKS.ps1")

  tags = {
    Product = var.product_name
  } 
 
  parameter = [
   {
    key = "subscriptionid"
    default_value = data.azurerm_client_config.current.subscription_id
  },
   {
    key = "aksresourcegroupname"
    default_value = data.azurerm_resource_group.aks.name
  }
]
}
```

### Debug Output/Panic Output

```shell
--- error---

 parameter = [

An argument named "parameter" is not expected here.
```

### Expected Behaviour

to be able to create a runbook with parameters

### Actual Behaviour

--- error---

 parameter = [

An argument named "parameter" is not expected here.

### Steps to Reproduce

Below is my code:

resource "azurerm_automation_runbook" "aks_stop" {  
  resource_group_name     = azurerm_resource_group.platform_rg.name
  name                    = "aks-stop"
  location                = azurerm_resource_group.platform_rg.location
  automation_account_name = azurerm_automation_account.automation_account.name
  log_verbose             = "true"
  log_progress            = "true"
  description             = "Tagetik AKS Stop"
  runbook_type            = "PowerShell"
  content                 = file("../runbooks/scripts/stop_AKS.ps1")

  tags = {
    Product = var.product_name
  } 
 
  parameter = [
   {
    key = "subscriptionid"
    default_value = data.azurerm_client_config.current.subscription_id
  },
   {
    key = "aksresourcegroupname"
    default_value = data.azurerm_resource_group.aks.name
  }
]
}

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/automation_runbook

**Comment by wuxu92** [comment] 2022-11-04 08:37
hi @dpk09  thanks for your feedback, the runbook resource does not support `parameter` in top-level properties, there is a `parameter` under the `draft` block as the API defined in swagger: https://github.com/Azure/azure-rest-api-specs/blob/4047b23b6e1a6bf2203d20db86d2f5eab43f7340/specification/automation/resource-manager/Microsoft.Automation/stable/2019-06-01/runbook.json#L1291

**Comment by Amier3** [comment] 2022-11-07 18:02
Closing this as it's been adressed and is not a bug.

**Closed by Amier3** 2022-11-07 18:02 UTC
