### ISSUE TITLE
azurerm_linux_virtual_machine_scale_set won't take non-gallery image

### ISSUE THREAD

**Issue by cochrasc** [hashicorp/terraform-provider-azurerm#17529] opened 2022-07-06 11:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.3

### AzureRM Provider Version

3.10.0

### Affected Resource(s)/Data Source(s)

azurerm_linux_virtual_machine_scale_set

### Terraform Configuration Files

```hcl
resource "azurerm_linux_virtual_machine_scale_set" "this" {
  name                            = "terraform-enterprise-vmss"
  resource_group_name             = data.azurerm_resource_group.main.name
  location                        = data.azurerm_resource_group.main.location
  sku                             = "Standard_D4_v4"
  instances                       = 1
  admin_username                  = "tfeadmin"
  admin_password                  = data.azurerm_key_vault_secret.administrator_password.value
  disable_password_authentication = false

  source_image_id = "/subscriptions/{redacted}/resourcegroups/prod-terraform-enterprise-centralus-rg/providers/Microsoft.Compute/images/tfe-image-test-image-20220705"
)
```

### Debug Output/Panic Output

```shell
azurerm_linux_virtual_machine_scale_set.this: Modifying... [id=/subscriptions/{redacted}/prod-terraform-enterprise-centralus-rg/providers/Microsoft.Compute/virtualMachineScaleSets/terraform-enterprise-vmss]
╷
│ Error: updating Linux Virtual Machine Scale Set "terraform-enterprise-vmss" (Resource Group "prod-terraform-enterprise-centralus-rg"): compute.VirtualMachineScaleSetsClient#Update: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameter" Message="The resource id '/subscriptions/{redacted}/resourcegroups/prod-terraform-enterprise-centralus-rg/providers/Microsoft.Compute/images/tfe-image-test-image-20220705' is not a valid gallery image reference. A gallery image reference should be a valid resource identifier, of the format: '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/galleries/{galleryName}/images/{imageName}/versions/{version}'." Target="imageReference"
│ 
│   with azurerm_linux_virtual_machine_scale_set.this,
│   on main.tf line 309, in resource "azurerm_linux_virtual_machine_scale_set" "this":
│  309: resource "azurerm_linux_virtual_machine_scale_set" "this" {
```

### Expected Behaviour

I created a custom image from a VM and stored it in my resource group.  I can use it to create a VMSS via the GUI, but the terraform resource will not accept it as a valid image because it's not in an image gallery.  
The resource should accept a valid image from any location, not just an image gallery.

### Actual Behaviour

The resource modification failed because the image is not stored in an image gallery

### Steps to Reproduce

1. Create a VM from any image. 
2. Using "Capture", create an image from that VM
  a. During creation, for "Share image to Azure compute gallery", choose "No, capture only a managed image"
3. Use that image ID as source_image_id in the Linux VMSS code
4. terraform apply

**Comment by myc2h6o** [comment] 2022-10-12 05:29
Hi @cochrasc thanks for opening the issue! I've tried on v3.10.0 and the latest version v3.26.0 and I'm able to create/update the VMSS with a standalone image. Below is my test config. Would you mind give it another try? And there may be some change at Azure end as well, if the issue still happens, I would suggest set the environment `TF_LOG` to `DEBUG` as described [here](https://www.terraform.io/internals/debugging) to get the API request details to see if there is anything wrong in the requests.

```hcl

resource "azurerm_linux_virtual_machine_scale_set" "test" {
  name                = "vmss"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location
  sku                 = "Standard_F2"
  instances           = 1
  admin_username      = "adminuser"
  admin_password      = "P@ssword1234!"

  disable_password_authentication = false

// Updating from gallery image to standalone image
//source_image_id = "/subscriptions/***/resourceGroups/test/providers/Microsoft.Compute/galleries/test/images/test/versions/1.0.0"
  source_image_id = "/subscriptions/***/resourceGroups/test/providers/Microsoft.Compute/images/image-0"

  os_disk {
    storage_account_type = "Standard_LRS"
    caching              = "ReadWrite"
  }

  network_interface {
    name    = "example"
    primary = true

    ip_configuration {
      name      = "ipConfiguration1"
      primary   = true
      subnet_id = azurerm_subnet.internal.id
      public_ip_address {
        name = "publicIpAddress1"
      }
    }
  }
}

```

**Comment by rcskosir** [comment] 2023-08-25 17:03
Thanks for taking the time to submit this issue. @myc2h6o was unable to reproduce this behavior. We’re going to close this issue for now, but if you run into this again with the latest Terraform and Provider versions, please feel free to [open a new issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/new/choose).

**Closed by rcskosir** 2023-08-25 17:03 UTC
Labels: waiting-response, service/virtual-machine, v/3.x
