### ISSUE TITLE
Can't upgrade `azurerm_postgres_flexible_server` to version 16

### ISSUE THREAD

**Issue by mclacore** [hashicorp/terraform-provider-azurerm#24349] opened 2023-12-27 22:28 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.3.4

### AzureRM Provider Version

3.85.0

### Affected Resource(s)/Data Source(s)

azurerm_postgres_flexible_server

### Terraform Configuration Files

```hcl
resource "azurerm_postgresql_flexible_server" "main" {
  name = var.name
  resource_group_name = azurerm_resource_group.main.name
  location = var.region
  version = "16"
  create_mode = "Update"
}
```

### Debug Output/Panic Output

```shell
updating Flexible Server (Subscription: "" Resource Group Name: "" Flexible Server Name: ""): performing Update: unexpected status 400 with error: ParameterOutOfRange: The value of the 'Version' should be in: []. Verify that the specified parameter value is correct.
```

### Expected Behaviour

The postgres server updates to version 16, like it is capable of for other versions.

### Actual Behaviour

Cannot upgrade to 16, but you can fresh deploy to 16.

### Steps to Reproduce

1. Deploy postgres server to version 15 or older
2. Set `create_mode` to `Update`
3. Set version to `"16"`
4. Redeploy

### References

https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-supported-versions#postgresql-version-16

**Comment by mclacore** [comment] 2023-12-28 07:30
I actually think this is an issue with Azure's API:

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/8037512/9bd1ae98-22d5-4b7d-a78b-f29ee05724bf)

**Comment by neil-yechenwei** [comment] 2023-12-29 05:48
Thanks for raising this issue. It's expected behavior. Service team confirmed that upgrading the version from older version to 16 isn't supported by service API for now.

**Comment by sebastiansterk** [comment] 2024-01-17 13:23
> Thanks for raising this issue. It's expected behavior. Service team confirmed that upgrading the version from older version to 16 isn't supported by service API for now.

Is it planned to support in the near future an upgrade from 15 to 16?

**Comment by sebastiansterk** [comment] 2024-01-18 13:03
I got the info from the Azure Support, that the Upgrade from 15 to 16 is planned. The expected GA is Q1 FY 2024.

**Comment by rcskosir** [comment] 2024-02-09 21:44
Thanks for taking the time to open this issue. It looks like the behavior you requested is not supported by the underlying Azure API so I am going to label this issue as such and close it for now. When it gets added if anything is needed from our side, we can reopen this request or you can create a new one.

**Closed by rcskosir** 2024-02-09 21:44 UTC
Labels: service/postgresql, v/3.x, upstream/microsoft/needs-support-on-azure-api
