### ISSUE TITLE
azurerm_automation_software_update_configuration does not accept a subscription id for scope in azure_query block

### ISSUE THREAD

**Issue by daisy-timms-xlab** [hashicorp/terraform-provider-azurerm#18594] opened 2022-09-30 10:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.14.5

### AzureRM Provider Version

3.25.0

### Affected Resource(s)/Data Source(s)

azurerm_automation_software_update_configuration

### Terraform Configuration Files

```hcl
resource "azurerm_automation_software_update_configuration" "example" {

  name                  = "example"
  automation_account_id = azurerm_automation_account.example_account.id
  operating_system      = "Linux"

  linux {
    classification_included = "Critical"
    reboot                  = "IfRequired"
  }

  duration = "PT2H"
  target {
    azure_query {
      scope      = [data.azurerm_subscription.current.id]
      tag_filter = "All"
      tags {
        tag    = "Example"
        values = ["example tag"]
      }
    }
  }
}
```

### Debug Output/Panic Output

```shell
Error: ID was missing the 'resourceGroups' element 
September 29th 2022 17:58:17Error
  on patching.tf line 46, in resource "azurerm_automation_software_update_configuration" "example": 
September 29th 2022 17:58:17Error
  46:       scope      = [data.azurerm_subscription.current.id]
```

### Expected Behaviour

Expected to be able to apply `azurerm_automation_software_update_configuration` with subscription id provided for the scope of the azure_query block rather than resourceGroup ids 

### Actual Behaviour

"Error: ID was missing the 'resourceGroups' element" when attempting to apply `azurerm_automation_software_update_configuration` with subscription id provided for the scope of the azure_query block

**Comment by nickwb** [comment] 2022-10-20 00:17
Looks like there might be a fix for this on the way: https://github.com/hashicorp/terraform-provider-azurerm/commit/7553745b1f8aa181553ddb0f1dde65e20ac8a6ba

Thanks @wuxu92

**Comment by wuxu92** [comment] 2022-10-20 01:52
@nickwb Yes this is duplicated with #18835. @daisy-timms-xlab could you please close this issue for it has been fixed?

**Comment by rcskosir** [comment] 2023-06-01 20:49
@daisy-timms-xlab Thanks for taking the time to submit this issue. It looks like this is a duplicate of #18835 which has been resolved. I am going to go ahead and close this issue.

For further feature requests or bug reports with this functionality, please create a [new GitHub issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/new/choose) following the template. Thank you!

**Closed by rcskosir** 2023-06-01 20:49 UTC
