### ISSUE TITLE
azurerm_public_ip creates public IP in three zones when only two are specified in the terraform code

### ISSUE THREAD

**Issue by scott-doyland-burrows** [hashicorp/terraform-provider-azurerm#16470] opened 2022-04-20 15:48 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.9

### AzureRM Provider Version

3.2.0

### Affected Resource(s)/Data Source(s)

azurerm_public_ip

### Config file and issue

The following creates a public IP in North Europe.
Statefile shows Zone 1,2 as expected.
Azure Web UI shows Zone 1,2,3 - ***NOT expected***.

```hcl
resource "azurerm_public_ip" "azurerm_public_ip" {
  name                = "test-ip"
  resource_group_name = "rg-vpn-dev"
  location            = "northeurope"
  allocation_method   = "Static"
  sku                 = "Standard"
  zones               = [1, 2]
}
```

A subsequent apply wants to destroy the public IP resource and recreate

```hcl
  # azurerm_public_ip.azurerm_public_ip must be replaced
-/+ resource "azurerm_public_ip" "azurerm_public_ip" {
      + fqdn                    = (known after apply)
      ~ id                      = "/subscriptions/[redacted]/resourceGroups/rg-vpn-dev/providers/Microsoft.Network/publicIPAddresses/test-ip" -> (known after apply)
      ~ ip_address              = "20.67.195.88" -> (known after apply)
      - ip_tags                 = {} -> null
        name                    = "test-ip"
      - tags                    = {} -> null
      ~ zones                   = [ # forces replacement
          - "3",
            # (2 unchanged elements hidden)
        ]
        # (7 unchanged attributes hidden)
    }
```

Running similar tests shows that selecting ONE zone or ALL zones (1,2,3) in the terraform code, works as expected.

Selecting just two zones out of the three available, causes the issue where Azure thinks all zones have been selected.

### Expected Behaviour

Terraform should create the public IP resource in just the zones specified (not three zones when only two are selected).

### Steps to Reproduce

```terraform apply``` using above test code.

**Comment by tombuildsstuff** [comment] 2022-04-21 07:53
hi @scott-doyland-burrows 

Thanks for opening this issue.

Azure allows the provisioning of a Public IP in one of three states:

1. No Zone
2. In a Single Zone
3. Across all Zones within a given Region

Given that different Azure Regions support Zones differently - insofar as some support 2 and others support 3 Availability Zones, it appears this is an attempt for the API to workaround these differences internally. From Terraform's side whilst we're sending only Zones 1 and 2 (in your example above) - the API's returning all 3 Zones since that Azure Region supports 3 Zones, as such all 3 would need to be specified to avoid this diff.

Whilst I agree with you that this resource should only be provisioned in the Zones that you're requesting, unfortunately since this is the behaviour of the Azure API I don't think there's much we can do to workaround this - and as such I'm going to close this issue for the moment since this is working as intended - however since behaviour should be fixed within the Azure API I'd recommend opening a ticket with Azure Support who should be able to pass this onto the Service Team.

Thanks!

**Closed by tombuildsstuff** 2022-04-21 07:53 UTC
Labels: question

**Comment by scott-doyland-burrows** [comment] 2022-04-21 08:21
I wasn't aware Azure worked in that way regarding it either being one zone or all zones.  But it becomes obvious when looking at the Web UI.

Maybe the easiest way to handle this is to just document the behaviour in the terraform documentation - just telling the user to either list one zone or list all zones.

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/public_ip

Alternatively is it possible to workaround this at the terraform end, so rather than ```zones``` accepting a list, it could accept:

```zones = 1``` (or whichever zone is chosen)
or
```zones = All``` (or ```Zone-redundant``` to tie into the Web UI)

and then terraform converts ```All``` to the actual list of all zones for that region.

Or is there a way on subsequent applies for terraform to NOT destroy and recreate the resource, but to show the differences and then just update the state, eg so the state is updated with ```[1, 2, 3]```.

Although - updating the documentation is probably easiest.

**Comment by tombuildsstuff** [comment] 2022-04-21 08:45
@scott-doyland-burrows we've actually just gone through the process of making the Zones behaviours consistent across the provider from using that approach ("Zone-Redundant") - see [behavioural updates](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/3.0-upgrade-guide#behavioural-updates. Unfortunately Azure doesn't expose an automated means of determining which Azure Region supports which Availability Zones so this isn't something we can expose to guide users/use internally here (it does on a per-resource level, but it's not helpful insofar as each resource gets it's own "zones" which don't necessarily match across resources, from what we can tell).

Unfortunately due to the way the Azure API behaves, it's possible for the behaviour of `zones` to change over time - as such this isn't something we'd necessarily want to document against each resource (just due to the sheer number of places this'd need to be updated if/when it changes) - but perhaps this'd be a good candidate for a "common behaviours" page which detailed some of these behaviours.

I appreciate that's probably not the answer you're looking for here, I wouldn't be surprised if in time Azure allowed provisioning resources in the explicitly defined zones only (as you were expecting above) for new resources, as they have with certain other of these types of changes - so I'm hesitant to document that behaviour for the moment lest users rely on it. On the flip side, I agree with you this isn't particularly clear right now - whilst it's good that the Terraform Plan is highlighting the diff it's an unexpected change for users unfamiliar with how Azure implements Zones - as such I believe the best way to document this would be to include this "common behaviours" page (and link to that as needed), as we do with [the features block](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/features-block).

WDYT?

**Comment by scott-doyland-burrows** [comment] 2022-04-21 09:11
The behavioural updates link you posted does indeed mention the behaviour of the zones parameter, perhaps just a link to that page from the ```zones``` section in https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/public_ip page is the way to go as this would seem the most relevant documentation to refer to.
