### ISSUE TITLE
Some properties of azurerm_cosmosdb_postgresql_cluster are optional for the read replica (administrator_login_password and coordinator_storage_quota_in_mb),  and they should not trigger modification if there is no change(null)

### ISSUE THREAD

**Issue by leilifremont** [hashicorp/terraform-provider-azurerm#24058] opened 2023-11-29 00:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.5

### AzureRM Provider Version

3.82.0

### Affected Resource(s)/Data Source(s)

azurerm_cosmosdb_postgresql_cluster

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "rg" {
  name     = "testrg"
  location = "eastus"
}

resource "random_password" "cosmosdb_postgresql_passwords" {
  length           = 24
  min_upper        = 6
  min_lower        = 4
  min_numeric      = 6
  special          = false

  depends_on = [
    resource.azurerm_resource_group.rg
  ]
}

resource "azurerm_cosmosdb_postgresql_cluster" "primary_replica" {
  name                            = "primary"
  location                        = "eastus"
  resource_group_name             = azurerm_resource_group.rg.name
  administrator_login_password    = random_password.cosmosdb_postgresql_passwords.result
  coordinator_storage_quota_in_mb = 528244
  coordinator_vcore_count         = 2
  coordinator_server_edition      = "GeneralPurpose"
  node_count                      = 2
  node_storage_quota_in_mb        = 528244
  node_vcores                     = 2
  node_server_edition             = "MemoryOptimized"

  coordinator_public_ip_access_enabled = false
  citus_version                        = "12.1"
  sql_version                          = "16"

  depends_on = [
    random_password.cosmosdb_postgresql_passwords
  ]
}

resource "time_sleep" "wait_20_minutes" {
  create_duration = "1200s"
  triggers = {
    postgresql_cluster_id  = azurerm_cosmosdb_postgresql_cluster.primary_replica.id
  }
}

resource "azurerm_cosmosdb_postgresql_cluster" "read_replica" {
  name                            = "secondary"
  resource_group_name             = azurerm_resource_group.rg.name
  location                        = "westus3"
  source_location      = azurerm_cosmosdb_postgresql_cluster.primary_replica.location
  source_resource_id   = azurerm_cosmosdb_postgresql_cluster.primary_replica.id
  node_count                      = 2
  node_server_edition             = "MemoryOptimized"

  coordinator_public_ip_access_enabled = false
  citus_version                        = "12.1"
  sql_version                          = "16"

  depends_on = [
    time_sleep.wait_20_minutes
  ]
}
```

### Debug Output/Panic Output

Previously I opened two issues:
https://github.com/hashicorp/terraform-provider-azurerm/issues/23734
https://github.com/hashicorp/terraform-provider-azurerm/issues/23923

When I tried to verify the fixes, I found the issues were solved, but there is a new problem now.
 
I created the CosmosDB PostgreSQL cluster with both primary replica and read replica (for read replica, I didn't set the optional properties, such as administrator_login_password, coordinator_storage_quota_in_mb and coordinator_vcore_count), the terraform plan could be applied successfully. The plan was like this,  

```shell
  # module.cosmosdb-postgresql[0].azurerm_cosmosdb_postgresql_cluster.cosmosdb_postgresql_read_replica["devdb"] will be created
  + resource "azurerm_cosmosdb_postgresql_cluster" "cosmosdb_postgresql_read_replica" {
      + citus_version                        = (known after apply)
      + coordinator_public_ip_access_enabled = false
      + coordinator_server_edition           = "GeneralPurpose"
      + earliest_restore_time                = (known after apply)
      + ha_enabled                           = false
      + id                                   = (known after apply)
      + location                             = "eastus"
      + name                                 = "devdb"
      + node_count                           = 2
      + node_public_ip_access_enabled        = false
      + node_server_edition                  = "MemoryOptimized"
      + node_storage_quota_in_mb             = (known after apply)
      + node_vcores                          = (known after apply)
      + resource_group_name                  = "MsfSmpUssDev"
      + shards_on_coordinator_enabled        = (known after apply)
      + source_location                      = "westus3"
      + source_resource_id                   = (known after apply)
      + sql_version                          = (known after apply)
      + tags                                 = {
          + "service"             = "dev"
        }
    }
```

First of all, I noticed that some optional parameters appeared in this plan (although I didn't set them for read replica), but some others didn't (for example, administrator_login_password, coordinator_storage_quota_in_mb and coordinator_vcore_count).

Then I ran "terraform plan" another time (I didn't change any terraform code), I would get a plan which somehow seemed reading the values of these properties (administrator_login_password, coordinator_storage_quota_in_mb and coordinator_vcore_count) from Azure. As a result, the read replica modification would be triggered. The modification plan would look like this.

```shell
  # module.cosmosdb-postgresql[0].azurerm_cosmosdb_postgresql_cluster.cosmosdb_postgresql_read_replica["devdb"] will be updated in-place
  ~ resource "azurerm_cosmosdb_postgresql_cluster" "cosmosdb_postgresql_read_replica" {
      - coordinator_storage_quota_in_mb      = 524288 -> null
      - coordinator_vcore_count              = 2 -> null
```

I tried to apply this modification plan, it would fail with this error,

```shell
unexpected status 400 with error: bad_request: The property '#/properties/administratorLoginPassword' Password must be between 8 & 256 characters, and contain 3 of the following kinds of characters: lower case, upper case, numeric, symbolic
│ The property '#/properties/coordinatorStorageQuotaInMb' 0 is not a valid disk size in schema 58e853d5-d434-5547-9e8e-0e8a37a0d15f
```

### Expected Behaviour

Some properties of azurerm_cosmosdb_postgresql_cluster are optional for the read replica (administrator_login_password and coordinator_storage_quota_in_mb),  and they should not trigger modification

It seems for other similar optional properties, such as node_storage_quota_in_mb, node_vcores, etc, didn't have this issue.

### Actual Behaviour

Should not trigger modification for the unchanged code.

**Comment by neil-yechenwei** [comment] 2023-11-29 09:04
Thanks for raising this issue. It's by TF design. As these properties are automatically set by the backend service for read replica, so you have to use [ignore_changes](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#ignore_changes) to ignore them.

**Comment by leilifremont** [comment] 2023-11-29 17:25
Hi @neil-yechenwei, thank you for looking into this. As I mentioned in the original post, it seems for other similar optional properties, such as node_storage_quota_in_mb, node_vcores, etc, they didn't have this issue, so could you take a closer look? Is it possible to eliminate using the "ignore changes" on the user's ends? It's strange in our code if we ignore some of them but not all similar properties, the code like this will be hard to be understood and maintained, especially there is no document about which property should be ignored, in addition, this may cause confusion for future users of this resource. Thanks!

**Comment by leilifremont** [comment] 2023-11-29 23:42
Hi @neil-yechenwei, I verified that the "ignore_changes" can solve the issue.

**Comment by rcskosir** [comment] 2024-02-14 18:45
Thanks for taking the time to submit this issue. On review, we’ve determined that the described behavior is TF by design. Whilst I'd like to thank you for opening this issue as we have no plans to support this functionality I'm going to close this issue for the moment, I am glad the ignore_changes was able to help you workaround this issue.

**Closed by rcskosir** 2024-02-14 18:45 UTC
Labels: service/cosmosdb, v/3.x
