### ISSUE TITLE
Unable to add storage account network rules to some storage accounts

### ISSUE THREAD

**Issue by AndreasFrangopoulos** [hashicorp/terraform-provider-azurerm#14129] opened 2021-11-10 15:50 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
1.0.10

### Affected Resource(s)

* `azurerm_XXXXX`
v2.84.0
### Terraform Configuration Files

```hcl
resource "azurerm_storage_account_network_rules" "storage" {
  for_each = azurerm_storage_account.this

  resource_group_name  = var.resource_group
  storage_account_name = each.value.name

  default_action = "Deny"
  ip_rules       = local.global_variables.paas_whitelisted_ip_cidrs
  bypass         = ["Metrics", "Logging", "AzureServices"]

  virtual_network_subnet_ids = concat(
    local.sids[each.value.location],
    local.sids[local.global_variables.location_dr[each.value.location]]
  )
}
```

### Debug Output
https://gist.github.com/AndreasFrangopoulos/de0407c2677fec60451d5dbce7777cf4

### Expected Behaviour

Storage Network Rules created on storage account

### Actual Behaviour
Adding rules to some stroage accounts fail despite having no rules defined.

### Steps to Reproduce
Add rule to storage account, delete rule, remove any trace of previous rule. Run apply.

1. `terraform apply`

### Important Factoids

Azure Public cloud
### References

Appears to be similar to
* #13640
but in our case we are trying to delete all remnants of the resource prior to deployment. We have confirmed with the Portal and the CLI that no rules exist, that the default is allow, that bypass rules are not set.
The import process is much too slow for the number of resources we have, it is faster to delete the existing (virtual resource) to allow a new one to be created by Terraform but so far we have been unable to do so.

**Comment by tombuildsstuff** [comment] 2021-11-10 16:00
hi @AndreasFrangopoulos 

Taking a look through here this appears to be because the resource already exists (in this case, as non-default network rules are configured on the Storage Account):

> A resource with the ID "/subscriptions/00000000...00000000/resourceGroups/00000000/providers/Microsoft.Storage/storageAccounts/00000000" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_storage_account_network_rule" for more information

As such this is working as intended - since Terraform checks for the presence of an existing resource prior to creating it, as such you'd need to import any existing resource into the state to be able to manage this in Terraform. As mentioned in the error message, more information on how to import resources can be found in the documentation: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account_network_rules#import

Since this is a question rather than a bug in Terraform I'm going to close this issue for the moment - however should you have further questions I'd point you in the direction of [the Community Discuss forum](https://discuss.hashicorp.com).

Thanks!

**Closed by tombuildsstuff** 2021-11-10 16:00 UTC
Labels: question

**Comment by AndreasFrangopoulos** [comment] 2021-11-10 16:03
HI @tombuildsstuff ,

As mentioned, I appreciate that IF the rules exist that will need to be imported. Perhaps I could rephrase the problem, the resource does not exist, but is being detected as existing - incorrectly.
