### ISSUE TITLE
azurerm_monitor_metric_alert produced an invalid new value for action: planned set element

### ISSUE THREAD

**Issue by Cavanaughjohnson** [hashicorp/terraform-provider-azurerm#22829] opened 2023-08-04 19:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.4

### AzureRM Provider Version

3.67.0

### Affected Resource(s)/Data Source(s)

azurerm_monitor_metric_alert

### Terraform Configuration Files

```hcl
resource "azurerm_monitor_action_group" "action_group" {
  name                = "${local.app_service_name}-webapp-monitor-group"
  resource_group_name = var.app_resource_group_name
  short_name          = "webapp-mtr"

  dynamic "email_receiver" {
    for_each = var.email_receiver_list
    content {
      name          = "${email_receiver.value}-email-alert"
      email_address = email_receiver.value
    }
  }
}

resource "azurerm_monitor_metric_alert" "metric_alert" {
  name                = "${local.app_service_name}-webapp-monitor-alert"
  resource_group_name = var.app_resource_group_name
  scopes              = [azurerm_windows_web_app.web_app.id] # list of resource IDs
  description         = "Alerts maintainers when App Service Health Check is failing"
  frequency           = var.app_service_monitor_frequency
  window_size         = var.app_service_monitor_window_size

  criteria {
    metric_namespace = "microsoft.web/sites"
    metric_name      = "HealthCheckStatus"
    aggregation      = "Average"
    operator         = "LessThanOrEqual"
    threshold        = var.app_service_monitor_alert_threshold # 50
  }

  action {
    action_group_id = azurerm_monitor_action_group.action_group.id
  }
}
```

### Debug Output/Panic Output

```shell
Error: Provider produced inconsistent final plan
 
When expanding the plan for azurerm_monitor_metric_alert.metric_alert to
include new values learned so far during apply, provider
"registry.terraform.io/hashicorp/azurerm" produced an invalid new value for
.action: planned set element
cty.ObjectVal(map[string]cty.Value{"action_group_id":cty.UnknownVal(cty.String),
"webhook_properties":cty.NullVal(cty.Map(cty.String))}) does not correlate
with any element in actual.

This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

### Expected Behaviour

The alert should be created

### Actual Behaviour

Release build fails in Terrform Apply with output listed above

### Steps to Reproduce

Terraform Apply

### Important Factoids

Running in Azure Gov - VA location

**Comment by Cavanaughjohnson** [comment] 2023-08-04 19:41
Running 3.38.0 works fine.

**Comment by rcskosir** [comment] 2023-12-06 22:19
Thanks for taking the time to submit this issue. @teowa was unable to reproduce this behavior. We’re going to close this issue for now, but if you run into this again with the latest Terraform and Provider versions, please feel free to [open a new issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/new/choose).

**Closed by rcskosir** 2023-12-06 22:19 UTC
Labels: waiting-response, service/monitor, v/3.x
