### ISSUE TITLE
Hope azurerm_cdn_endpoint resource support Azure China environment

### ISSUE THREAD

**Issue by muncleben** [hashicorp/terraform-provider-azurerm#8671] opened 2020-09-29 06:47 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'm trying to create CDN Endpoint with Terraform on Azure China, but when I'm referring the document file ([azurerm_cdn_endpoint doc link](https://www.terraform.io/docs/providers/azurerm/r/cdn_endpoint.html) ), I found it's not possible to create CDN Endpoint with Terraform on Azure China as the CDN Endpoint creation process is different between Azure China and Azure Global. 

On Azure China, if you want to create CDN Endpoint, you have to provide below information:
- Custom domain *
- ICP number *
- Acceleration type*
- Origin domain type
- Origin domain *
- Origin host header

[More detailed information about CDN on Azure China](https://docs.azure.cn/en-us/cdn/cdn-how-to-use#step-3-create-a-new-cdn-endpoint-node)

Is it possible to make **azurerm_cdn_endpoint** resource support Azure China environment? Or is any plan to have this feature on Azure China environment?

### New or Affected Resource(s)

* azurerm_cdn_endpoint

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* [CDN Configuration document on Azure China](https://docs.azure.cn/en-us/cdn/cdn-how-to-use#step-3-create-a-new-cdn-endpoint-node)
* [azurerm_cdn_endpoint doc link](https://www.terraform.io/docs/providers/azurerm/r/cdn_endpoint.html)

**Comment by romeomorcia-wipro** [comment] 2021-05-03 11:54
Any news regarding this?

**Comment by favoretti** [comment] 2021-09-01 10:21
Hi there and thank you for reporting this issue. This appears to be a duplicate of #5193, so I'm going to close this one to keep the discussion concise.

**Closed by favoretti** 2021-09-01 10:21 UTC
Labels: question, azure/china
