### ISSUE TITLE
Enabling diagnostics settings on SQL Server master database

### ISSUE THREAD

**Issue by tomazmla** [hashicorp/terraform-provider-azurerm#11756] opened 2021-05-18 06:08 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

While deploying SQL Server we want to enable diagnostics settings for the master database. Although this is now possible using SQL Database data source, Terraform destroys and re-creates the diagnostics settings on every run. That is annoying causing additional operational steps.

### New or Affected Resource(s)

* azurerm_mssql_server

### Potential Terraform Configuration

```hcl
resource "azurerm_monitor_diagnostic_setting" "sql_audit" {
  name                       = "example"
  target_resource_id         = azurerm_mssql_server.mssql.master_database_id
  log_analytics_workspace_id = var.logAnalyticsId
  storage_account_id         = var.storageAccountId

  log {
    category = "SQLSecurityAuditEvents"
  ...
  }
}
```

### References

* #0000

**Comment by tombuildsstuff** [comment] 2022-03-21 10:10
Taking a look through here this appears to be a duplicate of an issue which has since been fixed, please upgrade to the latest version of the AzureRM Provider (2.99 at the time of writing).

**Closed by tombuildsstuff** 2022-03-21 10:10 UTC
Labels: bug, service/mssql
