### ISSUE TITLE
unexpected new value for module.azure-redis.azurerm_redis_cache.redis - help to create without warnings

### ISSUE THREAD

**Issue by jimusbobus** [hashicorp/terraform-provider-azurerm#6592] opened 2020-04-23 07:36 UTC
Hi there,

I'm writing terratest tests for our IaC, we have a section where i create a redis instance,  i've been working on clearing all WARN from the logs (Ignoring [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.)

It seems that I cannot "clean" these up as the different setting contradict each other;

```
16:18:14  TestSpringSIRedis 2020-04-22T16:18:13+01:00 command.go:158: 2020/04/22 16:18:13 [WARN] Provider "registry.terraform.io/-/azurerm" produced an unexpected new value for module.azure-redis.azurerm_redis_cache.redis, but we are tolerating it because it is using the legacy plugin SDK.
16:18:14  TestSpringSIRedis 2020-04-22T16:18:13+01:00 command.go:158:     The following problems may be the cause of any confusing errors from downstream operations:
16:18:14  TestSpringSIRedis 2020-04-22T16:18:13+01:00 command.go:158:       - .redis_configuration[0].aof_storage_connection_string_0: inconsistent values for sensitive attribute
16:18:14  TestSpringSIRedis 2020-04-22T16:18:13+01:00 command.go:158:       - .redis_configuration[0].notify_keyspace_events: was null, but now cty.StringVal("")
16:18:14  TestSpringSIRedis 2020-04-22T16:18:13+01:00 command.go:158:       - .redis_configuration[0].rdb_storage_connection_string: inconsistent values for sensitive attribute
16:18:14  TestSpringSIRedis 2020-04-22T16:18:13+01:00 command.go:158:       - .redis_configuration[0].aof_storage_connection_string_1: inconsistent values for sensitive attribute
16:18:14  TestSpringSIRedis 2020-04-22T16:18:13+01:00 command.go:158:       - .redis_configuration[0].rdb_backup_frequency: was null, but now cty.NumberIntVal(0)
16:18:14  TestSpringSIRedis 2020-04-22T16:18:13+01:00 command.go:158:       - .redis_configuration[0].rdb_backup_max_snapshot_count: was null, but now cty.NumberIntVal(0)
16:18:14  TestSpringSIRedis 2020-04-22T16:18:14+01:00 command.go:158: 
```
I am creating a standard redis instance for example i have set
```
rdb_backup_enabled = false
```

This throws other rdb warnings so I try to fix by setting;
```
rdb_backup_frequency=15
```
But then i get the error;
```
Error: Error issuing create request for Redis Cache bnngmtftestredis1gtolf (resource group bnngmtf-terratest-tf-module-azure-redis-1gTOlF-RG): redis.Client#Create: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="Feature properties.redisConfiguration.rdb-backup-frequency requires a Premium sku to be set.\r\nRequestID=a8d496bb-9d49-44f7-b301-0c1e06f93132"
```
It seems that the settings are contradicting each other, if i set rdb_backup_enabled = false then i should be able to either not set the other values or set them to be empty and ignored.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform version: 0.12.24
"azurerm" (hashicorp/azurerm) 2.6.0...

### Affected Resource(s)

* `azurerm_redis_cache`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  version = "~> 2.2"
  features {}
}

data "azurerm_resource_group" "resource_group" {
  name = "ExistingResourceGroup"
}

resource "azurerm_redis_cache" "redis" {
  name     = "anyName"
  location = data.azurerm_resource_group.resource_group.location
  tags     = data.azurerm_resource_group.resource_group.tags

  resource_group_name = data.azurerm_resource_group.resource_group.name

  capacity            = 2
  family              = "C"
  sku_name            = "Standard"
  enable_non_ssl_port = true
  minimum_tls_version = "1.2"
  subnet_id = ""

  redis_configuration {
    enable_authentication = true
    maxmemory_policy   = "volatile-lru"
    rdb_backup_enabled = false
    aof_backup_enabled = false
  }
}
```

### Debug Output

```
16:18:14  TestSpringSIRedis 2020-04-22T16:18:13+01:00 command.go:158: 2020/04/22 16:18:13 [WARN] Provider "registry.terraform.io/-/azurerm" produced an unexpected new value for module.azure-redis.azurerm_redis_cache.redis, but we are tolerating it because it is using the legacy plugin SDK.
16:18:14  TestSpringSIRedis 2020-04-22T16:18:13+01:00 command.go:158:     The following problems may be the cause of any confusing errors from downstream operations:
16:18:14  TestSpringSIRedis 2020-04-22T16:18:13+01:00 command.go:158:       - .redis_configuration[0].aof_storage_connection_string_0: inconsistent values for sensitive attribute
16:18:14  TestSpringSIRedis 2020-04-22T16:18:13+01:00 command.go:158:       - .redis_configuration[0].notify_keyspace_events: was null, but now cty.StringVal("")
16:18:14  TestSpringSIRedis 2020-04-22T16:18:13+01:00 command.go:158:       - .redis_configuration[0].rdb_storage_connection_string: inconsistent values for sensitive attribute
16:18:14  TestSpringSIRedis 2020-04-22T16:18:13+01:00 command.go:158:       - .redis_configuration[0].aof_storage_connection_string_1: inconsistent values for sensitive attribute
16:18:14  TestSpringSIRedis 2020-04-22T16:18:13+01:00 command.go:158:       - .redis_configuration[0].rdb_backup_frequency: was null, but now cty.NumberIntVal(0)
16:18:14  TestSpringSIRedis 2020-04-22T16:18:13+01:00 command.go:158:       - .redis_configuration[0].rdb_backup_max_snapshot_count: was null, but now cty.NumberIntVal(0)
16:18:14  TestSpringSIRedis 2020-04-22T16:18:14+01:00 command.go:158: 
```
### Expected Behavior

The resource created without warnings.

### Actual Behavior

Warnings created for attributes even though the feature is set to false e.g.

    rdb_backup_enabled = false
    aof_backup_enabled = false

An example of setting one of the issues;
    rdb_backup_frequency = 15

then you get the following error
```
08:20:14  TestRedis 2020-04-23T08:20:13+01:00 command.go:158: Error: Error issuing create request for Redis Cache bnngmtftestredissg3zgh (resource group bnngmtf-terratest-tf-module-azure-redis-Sg3zGh-RG): redis.Client#Create: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="Feature properties.redisConfiguration.rdb-backup-frequency requires a Premium sku to be set.\r\nRequestID=5a6898e2-ea76-48ed-b36d-c7b6e5ee2817"
```
So again even though we have set "standard" sku we are stuck with warnings requiring values ot be set for features that cannot be used.

### Steps to Reproduce

1. `terraform apply`

### References

https://www.terraform.io/docs/providers/azurerm/r/redis_cache.html#redis_configuration

**Comment by ArcturusZhang** [comment] 2020-04-27 02:36
Hi @jimusbobus thanks for this issue.
For the warning part, I could reproduce the warnings and this does need a fix.
But following that warning I did not quite get the point. Based on the error message, it should be a service issue rather than an issue of terraform provider. Could you please give more context or explanation for the errors raised following the warnings?

**Comment by jimusbobus** [comment] 2020-04-27 07:59
Hi @ArcturusZhang 
Hopefully this will help clear things up!

```
provider "azurerm" {
  version = "~> 2.2"
  features {}
}

data "azurerm_resource_group" "resource_group" {
  name = "ExistingResourceGroup"
}

resource "azurerm_redis_cache" "redis" {
  name     = "anyName"
  location = data.azurerm_resource_group.resource_group.location
  tags     = data.azurerm_resource_group.resource_group.tags

  resource_group_name = data.azurerm_resource_group.resource_group.name

  capacity            = 2
  family              = "C"
  sku_name            = "Standard"
  enable_non_ssl_port = true
  minimum_tls_version = "1.2"
  subnet_id = ""

  redis_configuration {
    enable_authentication = true
    maxmemory_policy   = "volatile-lru"
    rdb_backup_enabled = false
    rdb_backup_frequency = 15
    aof_backup_enabled = false
  }
}
```
This then throws the error
```
2020/04/27 08:54:54 [ERROR] <root>: eval: *terraform.EvalApplyPost, err: Error issuing create request for Redis Cache jrobinson-qa-redis2 (resource group jrobinson-qa-rg): redis.Client#Create: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="Feature properties.redisConfiguration.rdb-backup-frequency requires a Premium sku to be set.\r\nRequestID=fcba0931-f99f-4dbb-9c60-6da702e85474"
2020/04/27 08:54:54 [ERROR] <root>: eval: *terraform.EvalSequence, err: Error issuing create request for Redis Cache jrobinson-qa-redis2 (resource group jrobinson-qa-rg): redis.Client#Create: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="Feature properties.redisConfiguration.rdb-backup-frequency requires a Premium sku to be set.\r\nRequestID=fcba0931-f99f-4dbb-9c60-6da702e85474"

Error: Error issuing create request for Redis Cache jrobinson-qa-redis2 (resource group jrobinson-qa-rg): redis.Client#Create: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="Feature properties.redisConfiguration.rdb-backup-frequency requires a Premium sku to be set.\r\nRequestID=fcba0931-f99f-4dbb-9c60-6da702e85474"

  on main.tf line 10, in resource "azurerm_redis_cache" "redis":
  10: resource "azurerm_redis_cache" "redis" {
```
This was just expanding on the issue that Even when i added defaults to remove the warning thi should fail because the sku was Standard, If the fix to remove the warnings means i do not need to set a default then this does not matter, If we have to set a default then if you use Standard sku then "rdb_backup_frequency" and other settings cannot be set.

**Comment by ArcturusZhang** [comment] 2020-04-27 08:25
Hi @jimusbobus I will try something to clear the warnings... and hopefully provide a fix for this.
But as for the following errors' part, based on my understanding, these warnings should be irrelevant with the following errors. The error is actually kind of straight forward that claims you must have a Premium sku to assign a `rdb_backup_frequency`

**Comment by favoretti** [comment] 2021-08-19 11:31
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.

**Closed by favoretti** 2021-08-19 11:31 UTC
Labels: service/redis
