### ISSUE TITLE
Related to #343 - Error: building AzureRM Client: obtain subscription() from Azure CLI: parsing json result from the Azure CLI: waiting for the Azure CLI: exit status 1: ERROR: Please run 'az login' to setup account.

### ISSUE THREAD

**Issue by ravensorb** [hashicorp/terraform-provider-azurerm#17120] opened 2022-06-06 01:36 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

Ubuntu 20.04
erraform v1.2.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.0.1
+ provider registry.terraform.io/hashicorp/azurerm v2.99.0
+ provider registry.terraform.io/hashicorp/random v3.2.0

### Terraform Configuration Files

```hcl
provider "azurerm" {    
  features {}

  subscription_id = var.azure_subscription_id
  tenant_id       = var.azure_tenant_id
  client_id       = var.azure_client_id
  client_secret   = var.azure_client_secret
}
```

### Debug Output

Creating Terraform Apply Plan
╷
│ Error: building AzureRM Client: obtain subscription() from Azure CLI: parsing json result from the Azure CLI: waiting for the Azure CLI: exit status 1: ERROR: Please run 'az login' to setup account.
│ 
│   with module.vnet-hub.provider["registry.terraform.io/hashicorp/azurerm"],
│   on .terraform/modules/vnet-hub/versions.tf line 14, in provider "azurerm":
│   14: provider "azurerm" {
│ 
╵
Last Error Code: 1

### Expected Behavior

Expect the azurerm to use the provided connection information

### Actual Behavior

Would expect the variables to work.  I confirmed using terraform console that they are loading, so it seems the provider is not using them from the header.

### Steps to Reproduce

Create a main.tf file on a linux machine, add the provider information for a specific subscription, and execute a terraform plan

Note: this is on Ubuntu 20,04

### References

* hashicorp/terraform-provider-azuread#343

**Comment by vishalmamidi** [comment] 2022-07-28 21:41
@manicminer 
facing the same issue when trying to authenticate using Azure CLI 
I am facing Issue with 2.38.0, 2.37.0, 2.36.0

could fix that temporarily by installing 2.30.0

uninstall existing version 
```
sudo apt-get remove -y azure-cli
```
install 2.30.3 using pip3 as apt repository doesn't have old versions below 2.36.0
```
pip3 install azure-cli==2.30.0
```

**Comment by DanielHabenicht** [comment] 2022-08-02 21:11
I can confirm this on a Windows 10 machine: 

```
2022-08-02T20:54:10.9018025Z Error: building AzureRM Client: obtain subscription(00000000-0000-0000-0000-000000000000) from Azure CLI: parsing json result from the Azure CLI: waiting for the Azure CLI: exit status 1: ERROR: Please run 'az login' to setup account.
2022-08-02T20:54:10.9027189Z 
2022-08-02T20:54:10.9038812Z with provider["registry.terraform.io/hashicorp/azurerm"],
2022-08-02T20:54:10.9041841Z on main.tf line 13, in provider "azurerm":
2022-08-02T20:54:10.9043118Z 13: provider "azurerm"
2022-08-02T20:54:10.9043708Z 
```

with version az-cli version:
```
PS C:\Users\user> az --version
azure-cli                         2.39.0

core                                2.39.0
telemetry                        1.0.6 *

Dependencies:
msal                                         1.18.0b1
azure-mgmt-resource             21.1.0b1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\user\.azure\cliextensions'

Python (Windows) 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 15:58:59) [MSC v.1929 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


You have 1 updates available.

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
```

Downgrading azure cli (to 2.30.0) did not work.

**Comment by cam3ron2** [comment] 2022-08-04 16:41
Experiencing this same issue. Environment:
- Terraform 1.2.6
- AZ CLI 2.19.1
- Debian Buster 

Provider Config: 
```
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">=3.0.0"
    }
    azuread = {
      source  = "hashicorp/azuread"
      version = ">= 1.0"
    }
  }
}

provider "azurerm" {
  features {}
  subscription_id = var.subscription_id
  tenant_id       = var.tenant_id
  client_id       = var.client_id
  client_secret   = var.client_secret
}

provider "azuread" {
  subscription_id = var.subscription_id
  tenant_id       = var.tenant_id
  client_id       = var.client_id
  client_secret   = var.client_secret
}
```

Terraform Init:
```
+ terragrunt init -no-color

Initializing the backend...

Warning: "use_microsoft_graph": [DEPRECATED] This field now defaults to `true` and will be removed in v1.3 of Terraform Core due to the deprecation of ADAL by Microsoft.



Error: Error building ARM Config: obtain subscription() from Azure CLI: parsing json result from the Azure CLI: waiting for the Azure CLI: exit status 1: ERROR: Please run 'az login' to setup account.


time=2022-08-04T14:12:16Z level=error msg=Terraform invocation failed in /home/jenkins/workspace/_architecture-sample_cam_changes/appconfig
time=2022-08-04T14:12:16Z level=error msg=1 error occurred:
	* exit status 1
```

I can confirm though that we see the same issue with az-cli 2.30.0 unlike @vishalmamidi

Debug Log: 
```
+ export TF_VAR_client_id=****
+ TF_VAR_client_id=****
+ export TF_VAR_client_secret=****
+ TF_VAR_client_secret=****
+ export TF_VAR_tenant_id=****
+ TF_VAR_tenant_id=****
+ export TF_VAR_subscription_id=****
+ TF_VAR_subscription_id=****
+ export TF_VAR_AZURE_SUBSCRIPTION_ID=****
+ TF_VAR_AZURE_SUBSCRIPTION_ID=****
+ export TF_LOG=DEBUG
+ TF_LOG=DEBUG
+ az login --service-principal -u **** -p **** --tenant ****
... (redacted)
+ az vm list-sizes --location westus
[
  {
    "maxDataDiskCount": 2,
    "memoryInMb": 512,
    "name": "Standard_B1ls",
    "numberOfCores": 1,
    "osDiskSizeInMb": 1047552,
    "resourceDiskSizeInMb": 4096
  },
  {
    "maxDataDiskCount": 2,
    "memoryInMb": 2048,
    "name": "Standard_B1ms",
    "numberOfCores": 1,
    "osDiskSizeInMb": 1047552,
    "resourceDiskSizeInMb": 4096
  },
... (truncated)
2022-08-04T16:30:04.170Z [INFO]  Terraform version: 1.2.6
2022-08-04T16:30:04.170Z [DEBUG] using github.com/hashicorp/go-tfe v1.0.0
2022-08-04T16:30:04.170Z [DEBUG] using github.com/hashicorp/hcl/v2 v2.12.0
2022-08-04T16:30:04.170Z [DEBUG] using github.com/hashicorp/terraform-config-inspect v0.0.0-20210209133302-4fd17a0faac2
2022-08-04T16:30:04.170Z [DEBUG] using github.com/hashicorp/terraform-svchost v0.0.0-20200729002733-f050f53b9734
2022-08-04T16:30:04.170Z [DEBUG] using github.com/zclconf/go-cty v1.10.0
2022-08-04T16:30:04.170Z [INFO]  Go runtime version: go1.18.1
2022-08-04T16:30:04.170Z [INFO]  CLI args: []string{"terraform", "init", "-no-color"}
2022-08-04T16:30:04.170Z [DEBUG] Attempting to open CLI config file: /root/.terraformrc
2022-08-04T16:30:04.170Z [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2022-08-04T16:30:04.170Z [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2022-08-04T16:30:04.170Z [DEBUG] ignoring non-existing provider search directory /root/.terraform.d/plugins
2022-08-04T16:30:04.170Z [DEBUG] ignoring non-existing provider search directory /root/.local/share/terraform/plugins
2022-08-04T16:30:04.170Z [DEBUG] ignoring non-existing provider search directory /usr/local/share/terraform/plugins
2022-08-04T16:30:04.170Z [DEBUG] ignoring non-existing provider search directory /usr/share/terraform/plugins
2022-08-04T16:30:04.171Z [INFO]  CLI command args: []string{"init", "-no-color"}

Initializing the backend...
2022-08-04T16:30:04.173Z [DEBUG] New state was assigned lineage "***"
2022-08-04T16:30:04.173Z [DEBUG] checking for provisioner in "."
2022-08-04T16:30:04.174Z [DEBUG] checking for provisioner in "/usr/local/bin"
2022-08-04T16:30:04.175Z [INFO]  Testing if Service Principal / Client Certificate is applicable for Authentication..
2022-08-04T16:30:04.175Z [INFO]  Testing if Multi Tenant Service Principal / Client Secret is applicable for Authentication..
2022-08-04T16:30:04.175Z [INFO]  Testing if Service Principal / Client Secret is applicable for Authentication..
2022-08-04T16:30:04.175Z [INFO]  Testing if OIDC is applicable for Authentication..
2022-08-04T16:30:04.175Z [INFO]  Testing if Managed Service Identity is applicable for Authentication..
2022-08-04T16:30:04.175Z [INFO]  Testing if Obtaining a Multi-tenant token from the Azure CLI is applicable for Authentication..
2022-08-04T16:30:04.175Z [INFO]  Testing if Obtaining a token from the Azure CLI is applicable for Authentication..
2022-08-04T16:30:04.175Z [INFO]  Using Obtaining a token from the Azure CLI for Authentication

Warning: "use_microsoft_graph": [DEPRECATED] This field now defaults to `true` and will be removed in v1.3 of Terraform Core due to the deprecation of ADAL by Microsoft.



Error: Error building ARM Config: obtain subscription() from Azure CLI: parsing json result from the Azure CLI: waiting for the Azure CLI: exit status 1: ERROR: Please run 'az login' to setup account.


time=2022-08-04T16:30:05Z level=error msg=Terraform invocation failed in ***
time=2022-08-04T16:30:05Z level=error msg=1 error occurred:
	* exit status 1
```

As you can see in this example, we have also tested the credentials being passed via `az login` and they work, so its not falling back to az-cli because credentials are incorrect or missing.

**Comment by manicminer** [comment] 2022-08-05 02:28
@cam3ron2 In your config snippet, you also appear to be using service principal authentication and not Azure CLI auth. Additionally, the AzureRM provider does not support authenticating Azure CLI with a service principal - you must authenticate as a user. Please can you try to reproduce with a config that doesn't specify `client_id` or `client_secret` / `client_certificate_path`.

**Comment by manicminer** [comment] 2022-08-05 02:30
> @manicminer facing the same issue when trying to authenticate using Azure CLI I am facing Issue with 2.38.0, 2.37.0, 2.36.0
> 
> could fix that temporarily by installing 2.30.0
> 
> uninstall existing version
> 
> ```
> sudo apt-get remove -y azure-cli
> ```
> 
> install 2.30.3 using pip3 as apt repository doesn't have old versions below 2.36.0
> 
> ```
> pip3 install azure-cli==2.30.0
> ```

@vishalmamidi Thanks, I'll try to reproduce with Azure CLI 2.36.0 and above.

**Comment by cam3ron2** [comment] 2022-08-05 14:10
> 

I don't want to authenticate via Azure CLI. I _want_ to authenticate as a service principal, and I have no idea why its attempting to authenticate via CLI if I have provided SP credentials.

**Comment by cam3ron2** [comment] 2022-08-09 12:26
So it seems that there is separation between the config values for the azurerm provider and backend which is not made clear by the [documentation](https://www.terraform.io/language/settings/backends/azurerm#example-configuration). You need to provide separate credentials for both the provider and the backend otherwise the backend will just fallback to azcli auth. To get the backend and provider to use SP credentials I made use of the `ARM_` environment variables which they both read. 

I think that the documentation should be more explicit and state the backend requires separate auth config unless using environment variables to save others time.

**Comment by ted-repo** [comment] 2022-11-23 09:38
Hi Cam3ron2

Please can you provide more guidance? I am having a similar problem. I am using Github actions with terraform to deploy Azure resources.

All secrets in github are in these format (e.g. ARM_CLIENT_ID) with "ARM_"

Full Error: Error building ARM Config: obtain subscription() from Azure CLI: Error parsing json result from the Azure CLI: Error waiting for the Azure CLI: exit status 1: ERROR: Please run 'az login' to setup account.

**example of a section of the terraform config file:**
    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      id: init
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
        STORAGE_ACCOUNT: ${{ secrets.STORAGE_ACCOUNT }}
        CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
      run: terraform init -backend-config="storage_account_name=$STORAGE_ACCOUNT" -backend-config="container_name=$CONTAINER_NAME" -backend-config="resource_group_name=$RESOURCE_GROUP"

**Comment by hkarthik7** [comment] 2023-02-17 05:45
The issue is resolved after setting the environment variables -> `ARM_SUBSCRIPTION_ID`, `ARM_TENANT_ID`, `ARM_CLIENT_ID` and `ARM_CLIENT_SECRET`.

**Comment by manicminer** [comment] 2023-02-21 12:51
As there are a number of issues being unintentionally conflated here, and because the original report is no longer relevant now that we have updated to a new authentication library, I'm going to close this one out as resolved.

If you encounter any authentication bugs using the latest version of the AzureRM provider, please feel free to open a new issue using the provided template. Please provide as much detail about your configuration to help a maintainer reproduce your issue. Thanks!

**Closed by manicminer** 2023-02-21 12:51 UTC
Labels: question, authentication
