### ISSUE TITLE
Support all subnet properties within azurerm_virtual_network resource

### ISSUE THREAD

**Issue by octavian-wpp** [hashicorp/terraform-provider-azurerm#23651] opened 2023-10-23 10:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Issue description:
Currently azurerm_virtual_network resource is not supporting all the the subnets properties that are available for azurerm_subnet.
The azurerm_virtual_network subnet property is supporting only name, address_prefix and security_group. The following properties are missing: 

- service_endpoints
- delegation
- private_endpoint_network_policies_enabled
- private_link_service_network_policies_enabled

Additionally these properties are surfaced in the microsoft virtual network arm template "Microsoft.Network/virtualNetworks@2023-04-01"

**Blocker issue:**
Unable to all subnets properties within terraform if we have Deny-Subnet-Without-Nsg policy in place as this will fail.

**Workaround** 
One workaround would be to handle subnet properties via azapi_resource call but this comes with challenges. 

### New or Affected Resource(s)/Data Source(s)

azurerm_virtual_network

### Potential Terraform Configuration

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_network_security_group" "example" {
  name                = "example-security-group"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
}

resource "azurerm_virtual_network" "example" {
  name                = "example-network"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  address_space       = ["10.0.0.0/16"]
  dns_servers         = ["10.0.0.4", "10.0.0.5"]

  subnet {
    name           = "subnet1"
    address_prefix = "10.0.1.0/24"
  }

  subnet {
    name           = "subnet2"
    address_prefix = "10.0.2.0/24"
    security_group = azurerm_network_security_group.example.id
  }

  tags = {
    environment = "Production"
  }
  #added values
  delegation {
    name = "delegation"
    service_delegation {
      name    = "Microsoft.ContainerInstance/containerGroups"
      actions = ["Microsoft.Network/virtualNetworks/subnets/join/action", "Microsoft.Network/virtualNetworks/subnets/prepareNetworkPolicies/action"]
    }
  }
  private_endpoint_network_policies_enabled     = true
  private_link_service_network_policies_enabled = true
  service_endpoints                             = ["Microsoft.AzureActiveDirectory", "Microsoft.AzureCosmosDB"]
}
```

### References

Deny-Subnet-Without-Nsg policy: 
https://github.com/Azure/Enterprise-Scale/blob/main/src/resources/Microsoft.Authorization/policyDefinitions/Deny-Subnet-Without-Nsg.json

Virtual network arm template / azapi_resource call
https://learn.microsoft.com/en-us/azure/templates/microsoft.network/virtualnetworks?pivots=deployment-language-arm-template

**Comment by rcskosir** [comment] 2023-10-23 15:09
@octavian-wpp Thank you for taking the time to open this feature request!

**Comment by octavian-wpp** [comment] 2023-10-24 06:12
> @octavian-wpp Thank you for taking the time to open this feature request!

@rcskosir Thank you for looking into this! :)

**Comment by tombuildsstuff** [comment] 2023-11-08 16:18
hi @octavian-wpp 

Thanks for opening this issue.

Taking a look through this appears to be a duplicate of https://github.com/hashicorp/terraform-provider-azurerm/issues/3917 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to https://github.com/hashicorp/terraform-provider-azurerm/issues/3917 for updates?

Thanks!

**Closed by tombuildsstuff** 2023-11-08 16:18 UTC
Labels: duplicate, enhancement, service/network
