### ISSUE TITLE
azurerm_automation_job_schedule dependecy not working as expected

### ISSUE THREAD

**Issue by renanaraujo** [hashicorp/terraform-provider-azurerm#4851] opened 2019-11-11 14:14 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.13
+ provider.azurerm v1.36.0
+ provider.local v1.4.0
+ provider.template v2.1.2

### Affected Resource(s)

* `azurerm_automation_job_schedule`

### Terraform Configuration Files

Variables (modules/runbooks/variables.tf):

```
variable "config_timezone" {
  default = "E. South America Standard Time"
}

variable "runbook_configuration" {
  default = {
    credential = ""
    rg_name = ""
    name = ""
    description = ""
    powershell_path = ""
    schedule = [{
        sc_name = ""
        frequency = ""
        interval = 1
        week_days = []
        start_time = ""
        description = ""
        parameters  = {} 
    }]
  }
}

```

Module  (modules/runbooks/runbook.tf):
```hcl

resource "azurerm_automation_runbook" "automation_runbook" {
  name                = var.runbook_configuration.name
  location            = data.azurerm_resource_group.rg.location
  resource_group_name = data.azurerm_resource_group.rg.name
  account_name        = azurerm_automation_account.automation_account.name
  log_verbose         = "true"
  log_progress        = "true"
  description         = var.runbook_configuration.description
  runbook_type        = "PowerShellWorkflow"
  content             = data.local_file.powershell_file.content

  # The Azure API requires a publish_content_link to be supplied even when specifying your own content
  publish_content_link {
    uri = " "
  }
}

resource "azurerm_automation_schedule" "automation_schedule" {
  count                   = length(var.runbook_configuration.schedule)
  name                    = element(var.runbook_configuration.schedule, count.index).sc_name
  resource_group_name     = data.azurerm_resource_group.rg.name
  automation_account_name = azurerm_automation_account.automation_account.name
  frequency               = element(var.runbook_configuration.schedule, count.index).frequency
  interval                = element(var.runbook_configuration.schedule, count.index).interval
  week_days               = element(var.runbook_configuration.schedule, count.index).week_days
  timezone                = var.config_timezone
  start_time              = element(var.runbook_configuration.schedule, count.index).start_time
  description             = element(var.runbook_configuration.schedule, count.index).description
}

resource "azurerm_automation_job_schedule" "automation_job_schedule" {
  count                   = length(var.runbook_configuration.schedule)
  resource_group_name     = data.azurerm_resource_group.rg.name
  automation_account_name = azurerm_automation_account.automation_account.name
  runbook_name            = azurerm_automation_runbook.automation_runbook.name
  schedule_name           = element(azurerm_automation_schedule.automation_schedule.*.name, count.index)
  parameters              = element(var.runbook_configuration.schedule, count.index).parameters
  
  depends_on              = ["azurerm_automation_schedule.automation_schedule", "azurerm_automation_runbook.automation_runbook"]
}
```

Module usage (runbook_example.tf):

```

locals {
  credential        = "my-automation-account"
  subscriptionId    = "xxxxxxxxx"
  weekDays          = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
  officeHoursStart  = "06:00"
  officeHoursEnd    = "23:00"
  resourceGroupList = [
    "my-rg"
  ]
}

# Runbook para ligar e desligar as vms conforme horario do expediente
module "dc-runbook-stopstartvm" {
  source      = "modules/runbooks"
  runbook_configuration = {
    rg_name  = "my-rg"
    credential      = local.credential
    name            = "dc-runbook-stopstartvm"
    description     = "Start/Stop VMs following the office hours"
    powershell_path  = "../../Path/To/PowershellFile.ps1"
    schedule        = [
      {
        sc_name        = "officehoursstart"
        frequency   = "Week"
        interval    = 1
        week_days   = local.weekDays
        start_time  = "${formatdate("YYYY-MM-DD", timeadd(timestamp(), "24h"))}T${local.officeHoursStart}:00Z"
        description = "Starting the office hours"
        parameters  = {
          credential      = local.credential,
          subscription_id  = local.subscriptionId,
          rg_list          = join(",", local.resourceGroupList),
          action          = "Start"
        }
      },
      {
        sc_name = "officehoursend"
        frequency   = "Week"
        interval    = 1
        week_days   = local.weekDays
        start_time  = "${formatdate("YYYY-MM-DD", timeadd(timestamp(), "24h"))}T${local.officeHoursEnd}:00Z"
        description = "Ending the office hours"
        parameters  = {
          credential      = local.credential,
          subscription_id  = local.subscriptionId,
          rg_list          = join(",", local.resourceGroupList),
          action          = "Stop"
        }
      },
    ]
  }
}
```

### Expected Behavior

```
  # module.dc-runbook-stopstartvm.azurerm_automation_account.automation_account will be created
  + resource "azurerm_automation_account" "automation_account" {
      + dsc_primary_access_key   = (known after apply)
      + dsc_secondary_access_key = (known after apply)
      + dsc_server_endpoint      = (known after apply)
      + id                       = (known after apply)
      + location                 = "eastus2"
      + name                     = "dc-automation-account"
      + resource_group_name      = "my-rg"
      + sku_name                 = "Basic"
      + tags                     = (known after apply)

      + sku {
          + name = (known after apply)
        }
    }

  # module.dc-runbook-stopstartvm.azurerm_automation_runbook.automation_runbook will be created
  + resource "azurerm_automation_runbook" "automation_runbook" {
      + account_name        = "dc-automation-account"
      + content             = "Workflow Stop-Start-AzureVM \r\n{ \r\n    Param \r\n    (    \r\n        [Parameter(Mandatory=$true)][ValidateNotNullOrEmpty()] \r\n        [String] \r\n        $credential,\r\n        [Parameter(Mandatory=$true)][ValidateNotNullOrEmpty()] \r\n        [String] \r\n        $subscriptionId, \r\n        [Parameter(Mandatory=$true)][ValidateNotNullOrEmpty()] \r\n        [String] \r\n        $rgList, \r\n        [Parameter(Mandatory=$true)][ValidateSet(\"Start\",\"Stop\")] \r\n        [String] \r\n        $action \r\n    ) \r\n     \r\n    $azCredential = Get-AutomationPSCredential -Name $credential \r\n    Login-AzureRmAccount -Credential $azCredential \r\n    Select-AzureRmSubscription
-SubscriptionId $subscriptionId \r\n\r\n    [System.Collections.ArrayList]$AzureRGsToHandle = $rgList.Split(\",\")\r\n \r\n    if($action -eq \"Stop\") \r\n    { \r\n        Write-Output \"Stopping VMs\"; \r\n        foreach -parallel ($rg in $AzureRGsToHandle) \r\n        { \r\n            Get-AzureRmVM | ? {$_.ResourceGroupName -eq $rg} | Stop-AzureRmVM -Force \r\n        } \r\n    } \r\n    else \r\n    { \r\n        Write-Output \"Starting VMs\"; \r\n        foreach -parallel ($rg in $AzureVMsToHandle) \r\n        { \r\n            Get-AzureRmVM | ? {$_.ResourceGroupName -eq $rg} | Start-AzureRmVM \r\n        } \r\n    } \r\n}"
      + description         = "Start/Stop VMs following the office hours"
      + id                  = (known after apply)
      + location            = "eastus2"
      + log_progress        = true
      + log_verbose         = true
      + name                = "dc-runbook-stopstartvm"
      + resource_group_name = "my-rg"
      + runbook_type        = "PowerShellWorkflow"
      + tags                = (known after apply)

      + publish_content_link {
          + uri = " "
        }
    }

  # module.dc-runbook-stopstartvm.azurerm_automation_schedule.automation_schedule[0] will be created
  + resource "azurerm_automation_schedule" "automation_schedule" {
      + account_name            = (known after apply)
      + automation_account_name = "dc-automation-account"
      + description             = "Starting the office hours"
      + expiry_time             = (known after apply)
      + frequency               = "Week"
      + id                      = (known after apply)
      + interval                = 1
      + name                    = "dc-qa-schedule-officehoursstart"
      + resource_group_name     = "my-rg"
      + start_time              = (known after apply)
      + timezone                = "E. South America Standard Time"
      + week_days               = [
          + "Friday",
          + "Monday",
          + "Thursday",
          + "Tuesday",
          + "Wednesday",
        ]
    }

  # module.dc-runbook-stopstartvm.azurerm_automation_schedule.automation_schedule[1] will be created
  + resource "azurerm_automation_schedule" "automation_schedule" {
      + account_name            = (known after apply)
      + automation_account_name = "dc-automation-account"
      + description             = "Ending the office hours"
      + expiry_time             = (known after apply)
      + frequency               = "Week"
      + id                      = (known after apply)
      + interval                = 1
      + name                    = "dc-qa-schedule-officehoursend"
      + resource_group_name     = "my-rg"
      + start_time              = (known after apply)
      + timezone                = "E. South America Standard Time"
      + week_days               = [
          + "Friday",
          + "Monday",
          + "Thursday",
          + "Tuesday",
          + "Wednesday",
        ]
    }

  # module.dc-runbook-stopstartvm.azurerm_automation_job_schedule.automation_job_schedule[0] will be created
  + resource "azurerm_automation_job_schedule" "automation_job_schedule" {
      + automation_account_name = "dc-automation-account"
      + id                      = (known after apply)
      + job_schedule_id         = (known after apply)
      + parameters              = {
          + "action"          = "Start"
          + "credential"      = "dc-automation-account"
          + "rg_list"         = "my-rg"
          + "subscription_id" = "10ddf338-69ec-4102-b770-9029eb3d2ef9"
        }
      + resource_group_name     = "mya-rg"
      + runbook_name            = "dc-runbook-stopstartvm"
      + schedule_name           = "dc-qa-schedule-officehoursstart"
    }

  # module.dc-runbook-stopstartvm.azurerm_automation_job_schedule.automation_job_schedule[1] will be created
  + resource "azurerm_automation_job_schedule" "automation_job_schedule" {
      + automation_account_name = "dc-automation-account"
      + id                      = (known after apply)
      + job_schedule_id         = (known after apply)
      + parameters              = {
          + "action"          = "Stop"
          + "credential"      = "dc-automation-account"
          + "rg_list"         = "my-rg"
          + "subscription_id" = "10ddf338-69ec-4102-b770-9029eb3d2ef9"
        }
      + resource_group_name     = "my-rg"
      + runbook_name            = "dc-runbook-stopstartvm"
      + schedule_name           = "dc-qa-schedule-officehoursend"
    }


```

### Actual Behavior

```
  # module.dc-runbook-stopstartvm.azurerm_automation_account.automation_account will be created
  + resource "azurerm_automation_account" "automation_account" {
      + dsc_primary_access_key   = (known after apply)
      + dsc_secondary_access_key = (known after apply)
      + dsc_server_endpoint      = (known after apply)
      + id                       = (known after apply)
      + location                 = "eastus2"
      + name                     = "dc-automation-account"
      + resource_group_name      = "my-rg"
      + sku_name                 = "Basic"
      + tags                     = (known after apply)

      + sku {
          + name = (known after apply)
        }
    }

  # module.dc-runbook-stopstartvm.azurerm_automation_job_schedule.automation_job_schedule[0] will be created
  + resource "azurerm_automation_job_schedule" "automation_job_schedule" {
      + automation_account_name = "dc-automation-account"
      + id                      = (known after apply)
      + job_schedule_id         = (known after apply)
      + parameters              = {
          + "action"          = "Start"
          + "credential"      = "dc-automation-account"
          + "rg_list"         = "my-rg"
          + "subscription_id" = "10ddf338-69ec-4102-b770-9029eb3d2ef9"
        }
      + resource_group_name     = "my-rg"
      + runbook_name            = "dc-runbook-stopstartvm"
      + schedule_name           = "dc-qa-schedule-officehoursstart"
    }

  # module.dc-runbook-stopstartvm.azurerm_automation_job_schedule.automation_job_schedule[1] will be created
  + resource "azurerm_automation_job_schedule" "automation_job_schedule" {
      + automation_account_name = "dc-automation-account"
      + id                      = (known after apply)
      + job_schedule_id         = (known after apply)
      + parameters              = {
          + "action"          = "Stop"
          + "credential"      = "dc-automation-account"
          + "rg_list"         = "my-rg"
          + "subscription_id" = "10ddf338-69ec-4102-b770-9029eb3d2ef9"
        }
      + resource_group_name     = "my-rg"
      + runbook_name            = "dc-runbook-stopstartvm"
      + schedule_name           = "dc-qa-schedule-officehoursend"
    }

  # module.dc-runbook-stopstartvm.azurerm_automation_runbook.automation_runbook will be created
  + resource "azurerm_automation_runbook" "automation_runbook" {
      + account_name        = "dc-automation-account"
      + content             = "Workflow Stop-Start-AzureVM \r\n{ \r\n    Param \r\n    (    \r\n        [Parameter(Mandatory=$true)][ValidateNotNullOrEmpty()] \r\n        [String] \r\n        $credential,\r\n        [Parameter(Mandatory=$true)][ValidateNotNullOrEmpty()] \r\n        [String] \r\n        $subscriptionId, \r\n        [Parameter(Mandatory=$true)][ValidateNotNullOrEmpty()] \r\n        [String] \r\n        $rgList, \r\n        [Parameter(Mandatory=$true)][ValidateSet(\"Start\",\"Stop\")] \r\n        [String] \r\n        $action \r\n    ) \r\n     \r\n    $azCredential = Get-AutomationPSCredential -Name $credential \r\n    Login-AzureRmAccount -Credential $azCredential \r\n    Select-AzureRmSubscription
-SubscriptionId $subscriptionId \r\n\r\n    [System.Collections.ArrayList]$AzureRGsToHandle = $rgList.Split(\",\")\r\n \r\n    if($action -eq \"Stop\") \r\n    { \r\n        Write-Output \"Stopping VMs\"; \r\n        foreach -parallel ($rg in $AzureRGsToHandle) \r\n        { \r\n            Get-AzureRmVM | ? {$_.ResourceGroupName -eq $rg} | Stop-AzureRmVM -Force \r\n        } \r\n    } \r\n    else \r\n    { \r\n        Write-Output \"Starting VMs\"; \r\n        foreach -parallel ($rg in $AzureVMsToHandle) \r\n        { \r\n            Get-AzureRmVM | ? {$_.ResourceGroupName -eq $rg} | Start-AzureRmVM \r\n        } \r\n    } \r\n}"
      + description         = "Start/Stop VMs following the office hours"
      + id                  = (known after apply)
      + location            = "eastus2"
      + log_progress        = true
      + log_verbose         = true
      + name                = "dc-runbook-stopstartvm"
      + resource_group_name = "my-rg"
      + runbook_type        = "PowerShellWorkflow"
      + tags                = (known after apply)

      + publish_content_link {
          + uri = " "
        }
    }

  # module.dc-runbook-stopstartvm.azurerm_automation_schedule.automation_schedule[0] will be created
  + resource "azurerm_automation_schedule" "automation_schedule" {
      + account_name            = (known after apply)
      + automation_account_name = "dc-automation-account"
      + description             = "Starting the office hours"
      + expiry_time             = (known after apply)
      + frequency               = "Week"
      + id                      = (known after apply)
      + interval                = 1
      + name                    = "dc-qa-schedule-officehoursstart"
      + resource_group_name     = "my-rg"
      + start_time              = (known after apply)
      + timezone                = "E. South America Standard Time"
      + week_days               = [
          + "Friday",
          + "Monday",
          + "Thursday",
          + "Tuesday",
          + "Wednesday",
        ]
    }

  # module.dc-runbook-stopstartvm.azurerm_automation_schedule.automation_schedule[1] will be created
  + resource "azurerm_automation_schedule" "automation_schedule" {
      + account_name            = (known after apply)
      + automation_account_name = "dc-automation-account"
      + description             = "Ending the office hours"
      + expiry_time             = (known after apply)
      + frequency               = "Week"
      + id                      = (known after apply)
      + interval                = 1
      + name                    = "dc-qa-schedule-officehoursend"
      + resource_group_name     = "my-rg"
      + start_time              = (known after apply)
      + timezone                = "E. South America Standard Time"
      + week_days               = [
          + "Friday",
          + "Monday",
          + "Thursday",
          + "Tuesday",
          + "Wednesday",
        ]
    }
```

### Steps to Reproduce

1. Create variables.tf and runbook.tf on the folder yourFolder/modules/runbooks
2. Create runbook_example.tf on yourFolder/ 
3. `terraform plan` on yourFolder/

### References

* #3386

**Comment by JFolberth** [comment] 2021-01-23 02:35
Confirmed that this issue is still occurring.  Worked arounds this by calling out depends_on in the azurerm_automation_job_schedule resource

**Comment by favoretti** [comment] 2021-08-19 07:02
Since this issue seems to have been addressed in the latest versions of the provider (or a valid workaround was provided) - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.

**Closed by favoretti** 2021-08-19 07:02 UTC
Labels: bug, service/automation

**Comment by Ryukx** [comment] 2021-09-14 08:40
This problem is still occuring 

Terraform v0.12.3
provider.azurerm v2.43.0

The destruction is not working as expected, i guess it returns before checking if the resource is completely removed.
