### ISSUE TITLE
Support vnetRouteAllEnabled as a site_config arg for azurerm_app_service

### ISSUE THREAD

**Issue by skylaro** [hashicorp/terraform-provider-azurerm#13068] opened 2021-08-19 18:47 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

azurerm_app_service
* `azurerm_XXXXX`

### Terraform Configuration Files
N/A

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output
The legacy app setting 'WEBSITE_VNET_ROUTE_ALL' is being overridden by the vnetRouteAllEnabled configuration setting.

### Expected Behaviour

Successful creation of app service WITH vnet_route_all enabled.

### Actual Behaviour
Successful creation of app service without vnet_route_all enabled.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment] 2021-08-20 06:42
Duplicate of #12860

**Closed by tombuildsstuff** 2021-08-20 06:42 UTC
