### ISSUE TITLE
azurerm_data_factory_pipeline keeps modifying compressionProperties from null to null

### ISSUE THREAD

**Issue by Pravez** [hashicorp/terraform-provider-azurerm#16844] opened 2022-05-18 10:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.0.5

### AzureRM Provider Version

2.88.0

### Affected Resource(s)/Data Source(s)

azurerm_data_factory_pipeline

### Terraform Configuration Files

```hcl
I have a definition for a generic pipeline in Terraform :


resource "azurerm_data_factory_pipeline" "XXX_pipeline" {
  resource_group_name = var.resource_group
  data_factory_name   = azurerm_data_factory.XXX.name
  parameters          = { FILE_NAME = "", FOLDER_PATH = "", XXX = "" }
  folder              = "XXX"

  name            = "XXX-pipeline"
  activities_json = templatefile("${path.module}/XXX/XXX_pipeline.json.tmpl", {
    raw_dataset_name        = azurerm_data_factory_dataset_azure_blob.generic_raw_dataset.name
    raw_csv_dataset_name    = azurerm_data_factory_dataset_delimited_text.generic_csv_dataset.name
    datasink_table_name     = azurerm_data_factory_dataset_sql_server_table.generic_table_indicator_datasink.name
    databricks_link_name    = azurerm_data_factory_linked_service_azure_databricks.databricks_link.name
    datawarehouse_link_name = azurerm_data_factory_linked_service_azure_sql_database.datawarehouse_link.name
  })
}
```

which uses an ARM for the concerned pipeline, with activities like :
```json
[
    {
        "name": "XXX",
        "type": "SqlServerStoredProcedure",
        "dependsOn": [
            {
                "activity": "XXX",
                "dependencyConditions": [
                    "Succeeded"
                ]
            }
        ],
        "policy": {
            "timeout": "7.00:00:00",
            "retry": 0,
            "retryIntervalInSeconds": 30,
            "secureOutput": false,
            "secureInput": false
        },
        "userProperties": [],
        "typeProperties": {
            "storedProcedureName": "XXX",
            "storedProcedureParameters": {
                "IndicatorName": {
                    "value": {
                        "value": "@pipeline().parameters.XXX",
                        "type": "Expression"
                    },
                    "type": "String"
                }
            }
        },
        "linkedServiceName": {
            "referenceName": "${datawarehouse_link_name}",
            "type": "LinkedServiceReference"
        }
    }
]
```

### Debug Output/Panic Output

It is not a real bug, but more something of a strange/bad behavior linked to the plan.

```
~ resource "azurerm_data_factory_pipeline" "XXX_pipeline" {
      ~ activities_json     = jsonencode(
          ~ [
              ~ {
                  ~ typeProperties = {
                      ~ source  = {
                          ~ formatSettings = {
                              - compressionProperties = null -> null
                                # (1 unchanged element hidden)
                            }
                            # (2 unchanged elements hidden)
                        }
                        # (1 unchanged element hidden)
                    }
                    # (5 unchanged elements hidden)
                },
                ...
              ~ {
                  ~ typeProperties = {
                      ~ source        = {
                          ~ formatSettings = {
                              - compressionProperties = null -> null
                                # (1 unchanged element hidden)
                            }
                            # (2 unchanged elements hidden)
                        }
                        # (2 unchanged elements hidden)
                    }
                    # (7 unchanged elements hidden)
                },
                # (3 unchanged elements hidden)
            ]
        )
    }
```

### Expected Behaviour

No modification was applied to the Pipeline's ARM definition, so the plan should not contain any update on this resource.

### Actual Behaviour

I do not really understand why Terraform needs to update the `compressionProperties`, for a value which won't change anyway (from `null` to `null`). This produces constant noise in the `tf plan`, as I have multiple pipelines which are created this way. This, even if I am not updating any of these pipelines files/resources (even on the Data Factory side, nothing changed).

### Important Factoids

Nothing special

**Comment by ms-henglu** [comment] 2022-05-23 05:24
Hi @Pravez ,

Thank you for taking time to report this issue!

I think the cause is `activities_json` is actually one string field of `azurerm_data_factory_pipeline`, so terraform compares them in config and state as strings. A fix for this is to remove `compressionProperties` from "${path.module}/XXX/XXX_pipeline.json.tmpl".

**Comment by Pravez** [comment] 2022-06-08 09:05
Hi @ms-henglu, thank you for your answer ! And sorry for the delay.
Actually, my template file `XXX_pipeline.json.tmpl` contains no field named compressionProperties. That's the exact problem, I do not declare anything related to this field in any of my JSON templates ...

**Comment by ms-henglu** [comment] 2022-06-08 09:07
Hi @Pravez - Got it! So the `compressionProperties=null` is returned by default, I think you can add it into the  `XXX_pipeline.json.tmpl`, then the config and state will be matched.

**Comment by Pravez** [comment] 2022-06-13 14:34
Hi @ms-henglu,

After some testing, I realized that this problem only occurs on references to "DelimitedTextSource" type of dataset source. So to fix this behavior, I have to indeed include `"compressionProperties": null` every time I have a `typeProperties` that uses this kind of source. For instance :

```json
"typeProperties": {
    "source": {
        "type": "DelimitedTextSource",
        "storeSettings": {
            "type": "AzureBlobStorageReadSettings",
            "recursive": false,
            "enablePartitionDiscovery": false
        },
        "formatSettings": {
            "type": "DelimitedTextReadSettings",
            "compressionProperties": null
        }
    },
    "sink": {
        "type": "SqlServerSink"
    },
    "enableStaging": false
}
```

**Closed** 2022-06-13 14:35 UTC
Labels: bug, service/data-factory
