### ISSUE TITLE
azurerm_api_management Error parsing Resource ID. Unexpected segment "policies/policy"

### ISSUE THREAD

**Issue by ryaison** [hashicorp/terraform-provider-azurerm#23036] opened 2023-08-22 12:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.5

### AzureRM Provider Version

3.70.0

### Affected Resource(s)/Data Source(s)

azurerm_api_management_policy

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      version = "=3.69"
    }
  }
}
provider azurerm {
  features {}
}

resource "azurerm_api_management" "example" {
  name                = "hcp-example-apim"
  location            = "eastus"
  resource_group_name = "rg-name"
  publisher_name      = "hcp_apim"
  publisher_email     = "company@terraform.io"

  sku_name = "Developer_1"
}

resource "azurerm_api_management_policy" "example" {

  api_management_id = azurerm_api_management.example.id
  xml_content       = <<EOT
    <policies>
      <inbound>
      </inbound>
      <backend>
          <forward-request />
      </backend>
      <outbound />
      <on-error />
    </policies>
  EOT
}
```

### Debug Output/Panic Output

```shell
"id":"/tenant/access","principalId":"integration","primaryKey":"<primary-key>,"secondaryKey":"<secondary-key>","enabled":false}: timestamp=2023-08-22T12:21:12.742Z
2023-08-22T12:21:12.785Z [WARN]  Provider "registry.terraform.io/hashicorp/azurerm" produced an unexpected new value for azurerm_api_management.example during refresh.
      - .policy[0].xml_content: was cty.StringVal("<!--\r\n    IMPORTANT:\r\n    - Policy elements can appear only within the <inbound>, <outbound>, <backend> section elements.\r\n    - Only the <forward-request> policy element can appear within the <backend> section element.\r\n    - To apply a policy to the incoming request (before it is forwarded to the backend service), place a corresponding policy element within the <inbound> section element.\r\n    - To apply a policy to the outgoing response (before it is sent back to the caller), place a corresponding policy element within the <outbound> section element.\r\n    - To add a policy position the cursor at the desired insertion point and click on the round button associated with the policy.\r\n    - To remove a policy, delete the corresponding policy statement from the policy document.\r\n    - Policies are applied in the order of their appearance, from the top down.\r\n-->\r\n<policies>\r\n\t<inbound />\r\n\t<backend>\r\n\t\t<forward-request />\r\n\t</backend>\r\n\t<outbound />\r\n</policies>"), but now cty.StringVal("<policies>\r\n\t<inbound></inbound>\r\n\t<backend>\r\n\t\t<forward-request />\r\n\t</backend>\r\n\t<outbound />\r\n\t<on-error />\r\n</policies>")
      - .zones: was null, but now cty.SetValEmpty(cty.String)
      - .tags: was null, but now cty.MapValEmpty(cty.String)
2023-08-22T12:21:12.853Z [WARN]  Provider "registry.terraform.io/hashicorp/azurerm" produced an invalid plan for azurerm_api_management.example, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .client_certificate_enabled: planned value cty.False for a non-computed attribute
      - .gateway_disabled: planned value cty.False for a non-computed attribute
      - .public_network_access_enabled: planned value cty.True for a non-computed attribute
      - .tags: planned value cty.MapValEmpty(cty.String) for a non-computed attribute
      - .min_api_version: planned value cty.StringVal("") for a non-computed attribute
      - .virtual_network_type: planned value cty.StringVal("None") for a non-computed attribute
      - .public_ip_address_id: planned value cty.StringVal("") for a non-computed attribute
      - .zones: planned value cty.SetValEmpty(cty.String) for a non-computed attribute
      - .delegation: block count in plan (1) disagrees with count in config (0)
      - .hostname_configuration: block count in plan (1) disagrees with count in config (0)
      - .security: block count in plan (1) disagrees with count in config (0)
      - .tenant_access: block count in plan (1) disagrees with count in config (0)
      - .protocols: block count in plan (1) disagrees with count in config (0)
      - .sign_in: block count in plan (1) disagrees with count in config (0)
      - .sign_up: block count in plan (1) disagrees with count in config (0)
2023-08-22T12:21:12.862Z [DEBUG] ReferenceTransformer: "azurerm_api_management_policy.example" references: []
2023-08-22T12:21:12.866Z [DEBUG] provider.terraform-provider-azurerm_v3.70.0_x5: Updating ID from "/subscriptions/<subscription-id>/resourceGroups/<rg-name>/providers/Microsoft.ApiManagement/service/hcp-example-apim/policies/policy" to "/subscriptions/<subscription-id>/resourceGroups/<rg-name>/providers/Microsoft.ApiManagement/service/hcp-example-apim/policies/policy": timestamp=2023-08-22T12:21:12.865Z
2023-08-22T12:21:12.871Z [ERROR] provider.terraform-provider-azurerm_v3.70.0_x5: Response contains error diagnostic: tf_provider_addr=provider tf_req_id=8fb2a2c5-6060-ca47-1f2d-60564ae9785a @module=sdk.proto diagnostic_severity=ERROR diagnostic_summary="parsing "/subscriptions/<subscription-id>/resourceGroups/<rg-name>/providers/Microsoft.ApiManagement/service/hcp-example-apim/policies/policy": unexpected segment "policies/policy" present at the end of the URI (input "/subscriptions/<subscription-id>/resourceGroups/<rg-name>/providers/Microsoft.ApiManagement/service/hcp-example-apim/policies/policy")" tf_proto_version=5.3 tf_resource_type=azurerm_api_management_policy tf_rpc=ReadResource @caller=github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/diag/diagnostics.go:55 diagnostic_detail= timestamp=2023-08-22T12:21:12.871Z
2023-08-22T12:21:12.874Z [ERROR] vertex "azurerm_api_management_policy.example" error: parsing "/subscriptions/<subscription-id>/resourceGroups/<rg-name>/providers/Microsoft.ApiManagement/service/hcp-example-apim/policies/policy": unexpected segment "policies/policy" present at the end of the URI (input "/subscriptions/<subscription-id>/resourceGroups/<rg-name>/providers/Microsoft.ApiManagement/service/hcp-example-apim/policies/policy")
2023-08-22T12:21:12.875Z [ERROR] vertex "azurerm_api_management_policy.example (expand)" error: parsing "/subscriptions/<subscription-id>/resourceGroups/<rg-name>/providers/Microsoft.ApiManagement/service/hcp-example-apim/policies/policy": unexpected segment "policies/policy" present at the end of the URI (input "/subscriptions/<subscription-id>/resourceGroups/<rg-name>/providers/Microsoft.ApiManagement/service/hcp-example-apim/policies/policy")
2023-08-22T12:21:12.885Z [INFO]  backend/local: plan operation completed
2023-08-22T12:21:12.965Z [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
2023-08-22T12:21:13.003Z [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/azurerm/3.70.0/linux_amd64/terraform-provider-azurerm_v3.70.0_x5 pid=75280
2023-08-22T12:21:13.003Z [DEBUG] provider: plugin exited
```

### Expected Behaviour

After applying with AzureRM provider v3.69, upgrading to v3.70 and running `terraform plan` should successfully plan.

NOTE: Initial creation with v3.70 does not fail to plan on subsequent attempts. Issue is only present when upgrading the provider and planning against an existing resource & record in state created with an earlier version of the provider.

### Actual Behaviour

```
Planning failed. Terraform encountered an error while generating this plan.

│ Error: parsing "/subscriptions/<subscription-id>/resourceGroups/<rg-name>/providers/Microsoft.ApiManagement/service/hcp-example-apim/policies/policy": unexpected segment "policies/policy" present at the end of the URI (input "/subscriptions/<subscription-id>/resourceGroups/<rg-name>/providers/Microsoft.ApiManagement/service/hcp-example-apim/policies/policy")
│ 
│   with azurerm_api_management_policy.example,
│   on main.tf line 22, in resource "azurerm_api_management_policy" "example":
│   22: resource "azurerm_api_management_policy" "example" {
│ 
```

### Steps to Reproduce

1. `terraform apply`
2. Change
```
terraform {
  required_providers {
    azurerm = {
      version = "=3.69"
    }
  }
}
```
to
```
terraform {
  required_providers {
    azurerm = {
      version = "=3.70"
    }
  }
}
```
3. `terraform plan`

**Comment by stephybun** [comment] 2023-08-22 13:06
Thanks for raising this issue @ryaison.

This is a duplicate of #23015 and will be fixed in v3.71.0 of the provider. 

Since this is already resolved I'm going to go ahead and close this. Thanks!

**Closed by stephybun** 2023-08-22 13:06 UTC
Labels: service/api-management, v/3.x

**Comment by tanmoy007-ghosh** [comment] 2023-08-24 09:50
When the v3.71.0 will come?

**Comment by michelefa1988** [comment] 2023-08-25 09:06
I still get this error @stephybun , even after using v.3.71.0
