### ISSUE TITLE
Replacing deprecated "storage_account_name" with "storage_account_id" results in destruction of shares and containers

### ISSUE THREAD

**Issue by bandarr** [hashicorp/terraform-provider-azurerm#28169] opened 2024-12-03 19:03 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.10.0

### AzureRM Provider Version

4.12.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_share, azurerm_storage_container

### Terraform Configuration Files

```hcl
# azurerm_storage_share.nunya-business-data must be replaced
-/+ resource "azurerm_storage_share" "nunya-business-data" {
      ~ id                   = "https://nunya.file.core.windows.net/nunya-business-data" -> (known after apply)
      ~ metadata             = {} -> (known after apply)
        name                 = "nunya-business-data"
      ~ resource_manager_id  = "/subscriptions/nnnnnnnn-nnnn-nnnn-nnnn-nnnnnnnnnnnn/resourceGroups/rg-Nunya/providers/Microsoft.Storage/storageAccounts/nunya/fileServices/default/fileshares/nunya-business-data" -> (known after apply)
      + storage_account_id   = "/subscriptions/nnnnnnnn-nnnn-nnnn-nnnn-nnnnnnnnnnnn/resourceGroups/rg-Nunya/providers/Microsoft.Storage/storageAccounts/nunya" # forces replacement
      - storage_account_name = "nunya" -> null # forces replacement
      ~ url                  = "https://nunya.file.core.windows.net/nunya-business-data" -> (known after apply)
        # (3 unchanged attributes hidden)
    }
```

### Debug Output/Panic Output

```shell
# azurerm_storage_share.nunya-business-data must be replaced
```

### Expected Behaviour

Replacing a deprecated value should not result in recreation of the resource.

### Actual Behaviour

Terraform, as usual, wants to destroy resources indiscriminately. 

### Steps to Reproduce

terraform plan

**Comment by bandarr** [comment] 2024-12-03 19:14
Specifying both, in hopes of alleviating the problem, results in this:

"storage_account_name": only one of `storage_account_id,storage_account_name` can be specified, but `storage_account_id,storage_account_name` were specified.

**Comment by rcskosir** [comment] 2024-12-03 23:59
Thanks for taking the time to submit this issue. It looks like this is a duplicate of #27942. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of #27942.

**Closed by rcskosir** 2024-12-03 23:59 UTC
Labels: duplicate, service/storage, v/4.x
