### ISSUE TITLE
After upgrade to 4.0.X Traffic Manager Endpoint Priority is set the same for all endpoints when using Weight causing failure

### ISSUE THREAD

**Issue by Axlecrime** [hashicorp/terraform-provider-azurerm#27275] opened 2024-09-04 09:50 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.5

### AzureRM Provider Version

4.0.1

### Affected Resource(s)/Data Source(s)

azurerm_traffic_manager_external_endpoint

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      version = "3.116.0" # Update to 4.0.1 after creating resources
    }
  }
}

provider "azurerm" {
  subscription_id            = "<azure-subscription-id>"
  features {}
}

locals {
  tags = {
    createdby = "<username>"
  }
}

resource "azurerm_resource_group" "traffic_manager_test" {
  name     = "traffic_manager_test"
  location = "westeurope"
  tags     = local.tags
}

resource "azurerm_public_ip" "traffic_manager_test_enpoint_ip1" {
  name                = "trafficmanagertestip1"
  allocation_method   = "Static"
  sku                 = "Standard"
  resource_group_name = azurerm_resource_group.traffic_manager_test.name
  location            = azurerm_resource_group.traffic_manager_test.location
}

resource "azurerm_public_ip" "traffic_manager_test_enpoint_ip2" {
  name                = "trafficmanagertestip2"
  sku                 = "Standard"
  allocation_method   = "Static"
  resource_group_name = azurerm_resource_group.traffic_manager_test.name
  location            = azurerm_resource_group.traffic_manager_test.location
}

resource "azurerm_traffic_manager_profile" "traffic_manager_test" {
  name                   = "trafficmanagertest"
  resource_group_name    = azurerm_resource_group.traffic_manager_test.name
  traffic_routing_method = "Weighted"
  traffic_view_enabled   = "true"

  dns_config {
    relative_name = "tftrafficmantest"
    ttl           = 60
  }

  monitor_config {
    protocol                     = "HTTPS"
    port                         = 443
    path                         = "/"
    interval_in_seconds          = 10
    timeout_in_seconds           = 9
    tolerated_number_of_failures = 3
  }

  tags = local.tags
}

resource "azurerm_traffic_manager_external_endpoint" "traffic_manager_test_endpoint1" {
  name       = "testendpoint1"
  profile_id = azurerm_traffic_manager_profile.traffic_manager_test.id
  target     = azurerm_public_ip.traffic_manager_test_enpoint_ip1.ip_address
  weight     = 10
}

resource "azurerm_traffic_manager_external_endpoint" "traffic_manager_test_endpoint2" {
  name       = "testendpoint2"
  profile_id = azurerm_traffic_manager_profile.traffic_manager_test.id
  target     = azurerm_public_ip.traffic_manager_test_enpoint_ip2.ip_address
  weight     = 10
}
```

### Debug Output/Panic Output

```shell
PS C:\Terraform> terraform plan   
2024-09-04T09:37:15.319+0100 [INFO]  Terraform version: 1.9.5
2024-09-04T09:37:15.320+0100 [INFO]  Go runtime version: go1.22.5
2024-09-04T09:37:15.320+0100 [INFO]  CLI args: []string{"C:\\Users\\<username>\\.Terraform\\terraform.exe", "plan"}
2024-09-04T09:37:15.325+0100 [INFO]  CLI command args: []string{"plan"}
2024-09-04T09:37:15.502+0100 [INFO]  backend/local: starting Plan operation
2024-09-04T09:37:17.804+0100 [INFO]  provider: configuring client automatic mTLS
2024-09-04T09:37:17.882+0100 [INFO]  provider.terraform-provider-azurerm_v4.0.1_x5.exe: configuring server automatic mTLS: timestamp="2024-09-04T09:37:17.882+0100"
2024-09-04T09:37:18.021+0100 [INFO]  provider: plugin process exited: plugin=.terraform/providers/registry.terraform.io/hashicorp/azurerm/4.0.1/windows_amd64/terraform-provider-azurerm_v4.0.1_x5.exe id=26068
2024-09-04T09:37:18.022+0100 [INFO]  provider: configuring client automatic mTLS
2024-09-04T09:37:18.094+0100 [INFO]  provider.terraform-provider-azurerm_v4.0.1_x5.exe: configuring server automatic mTLS: timestamp="2024-09-04T09:37:18.093+0100"
2024-09-04T09:37:18.142+0100 [INFO]  provider: plugin process exited: plugin=.terraform/providers/registry.terraform.io/hashicorp/azurerm/4.0.1/windows_amd64/terraform-provider-azurerm_v4.0.1_x5.exe id=28772
2024-09-04T09:37:18.142+0100 [INFO]  backend/local: plan calling Plan
2024-09-04T09:37:18.143+0100 [INFO]  provider: configuring client automatic mTLS
2024-09-04T09:37:18.215+0100 [INFO]  provider.terraform-provider-azurerm_v4.0.1_x5.exe: configuring server automatic mTLS: timestamp="2024-09-04T09:37:18.215+0100"
azurerm_resource_group.traffic_manager_test: Refreshing state... [id=/subscriptions/<azure-subscription-id>/resourceGroups/traffic_manager_test]
2024-09-04T09:37:22.527+0100 [WARN]  Provider "registry.terraform.io/hashicorp/azurerm" produced an invalid plan for azurerm_resource_group.traffic_manager_test, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .managed_by: planned value cty.StringVal("") for a non-computed attribute
azurerm_public_ip.traffic_manager_test_enpoint_ip2: Refreshing state... [id=/subscriptions/<azure-subscription-id>/resourceGroups/traffic_manager_test/providers/Microsoft.Network/publicIPAddresses/trafficmanagertestip2]
azurerm_traffic_manager_profile.traffic_manager_test: Refreshing state... [id=/subscriptions/<azure-subscription-id>/resourceGroups/traffic_manager_test/providers/Microsoft.Network/trafficManagerProfiles/trafficmanagertest]
azurerm_public_ip.traffic_manager_test_enpoint_ip1: Refreshing state... [id=/subscriptions/<azure-subscription-id>/resourceGroups/traffic_manager_test/providers/Microsoft.Network/publicIPAddresses/trafficmanagertestip1]
2024-09-04T09:37:22.756+0100 [WARN]  Provider "registry.terraform.io/hashicorp/azurerm" produced an unexpected new value for azurerm_public_ip.traffic_manager_test_enpoint_ip1 during refresh.
      - .zones: was null, but now cty.SetValEmpty(cty.String)
      - .tags: was null, but now cty.MapValEmpty(cty.String)
      - .ip_tags: was null, but now cty.MapValEmpty(cty.String)
2024-09-04T09:37:22.759+0100 [WARN]  Provider "registry.terraform.io/hashicorp/azurerm" produced an invalid plan for azurerm_public_ip.traffic_manager_test_enpoint_ip1, but we are tolerating it because it is 
using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .ip_tags: planned value cty.MapValEmpty(cty.String) for a non-computed attribute
      - .tags: planned value cty.MapValEmpty(cty.String) for a non-computed attribute
      - .ddos_protection_mode: planned value cty.StringVal("VirtualNetworkInherited") for a non-computed attribute
      - .ip_version: planned value cty.StringVal("IPv4") for a non-computed attribute
      - .idle_timeout_in_minutes: planned value cty.NumberIntVal(4) for a non-computed attribute
      - .sku_tier: planned value cty.StringVal("Regional") for a non-computed attribute
      - .zones: planned value cty.SetValEmpty(cty.String) for a non-computed attribute
      - .edge_zone: planned value cty.StringVal("") for a non-computed attribute
2024-09-04T09:37:22.771+0100 [WARN]  Provider "registry.terraform.io/hashicorp/azurerm" produced an unexpected new value for azurerm_public_ip.traffic_manager_test_enpoint_ip2 during refresh.
      - .zones: was null, but now cty.SetValEmpty(cty.String)
      - .tags: was null, but now cty.MapValEmpty(cty.String)
      - .ip_tags: was null, but now cty.MapValEmpty(cty.String)
2024-09-04T09:37:22.773+0100 [WARN]  Provider "registry.terraform.io/hashicorp/azurerm" produced an invalid plan for azurerm_public_ip.traffic_manager_test_enpoint_ip2, but we are tolerating it because it is 
using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .ddos_protection_mode: planned value cty.StringVal("VirtualNetworkInherited") for a non-computed attribute
      - .idle_timeout_in_minutes: planned value cty.NumberIntVal(4) for a non-computed attribute
      - .ip_version: planned value cty.StringVal("IPv4") for a non-computed attribute
      - .edge_zone: planned value cty.StringVal("") for a non-computed attribute
      - .sku_tier: planned value cty.StringVal("Regional") for a non-computed attribute
      - .zones: planned value cty.SetValEmpty(cty.String) for a non-computed attribute
      - .ip_tags: planned value cty.MapValEmpty(cty.String) for a non-computed attribute
      - .tags: planned value cty.MapValEmpty(cty.String) for a non-computed attribute
2024-09-04T09:37:22.938+0100 [WARN]  Provider "registry.terraform.io/hashicorp/azurerm" produced an unexpected new value for azurerm_traffic_manager_profile.traffic_manager_test during refresh.
      - .monitor_config[0].expected_status_code_ranges: was null, but now cty.ListValEmpty(cty.String)
2024-09-04T09:37:22.942+0100 [WARN]  Provider "registry.terraform.io/hashicorp/azurerm" produced an invalid plan for azurerm_traffic_manager_profile.traffic_manager_test, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .profile_status: planned value cty.StringVal("Enabled") for a non-computed attribute
      - .max_return: planned value cty.NumberIntVal(0) for a non-computed attribute
      - .monitor_config[0].expected_status_code_ranges: planned value cty.ListValEmpty(cty.String) for a non-computed attribute
azurerm_traffic_manager_external_endpoint.traffic_manager_test_endpoint1: Refreshing state... [id=/subscriptions/<azure-subscription-id>/resourceGroups/traffic_manager_test/providers/Microsoft.Network/trafficManagerProfiles/trafficmanagertest/ExternalEndpoints/testendpoint1]
azurerm_traffic_manager_external_endpoint.traffic_manager_test_endpoint2: Refreshing state... [id=/subscriptions/<azure-subscription-id>/resourceGroups/traffic_manager_test/providers/Microsoft.Network/trafficManagerProfiles/trafficmanagertest/ExternalEndpoints/testendpoint2]
2024-09-04T09:37:23.282+0100 [WARN]  Provider "registry.terraform.io/hashicorp/azurerm" produced an unexpected new value for azurerm_traffic_manager_external_endpoint.traffic_manager_test_endpoint2 during refresh.
      - .geo_mappings: was null, but now cty.ListValEmpty(cty.String)
2024-09-04T09:37:23.284+0100 [WARN]  Provider "registry.terraform.io/hashicorp/azurerm" produced an invalid plan for azurerm_traffic_manager_external_endpoint.traffic_manager_test_endpoint2, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .priority: planned value cty.NumberIntVal(1) for a non-computed attribute
      - .always_serve_enabled: planned value cty.False for a non-computed attribute
      - .enabled: planned value cty.True for a non-computed attribute
      - .geo_mappings: planned value cty.ListValEmpty(cty.String) for a non-computed attribute
2024-09-04T09:37:44.035+0100 [WARN]  Provider "registry.terraform.io/hashicorp/azurerm" produced an unexpected new value for azurerm_traffic_manager_external_endpoint.traffic_manager_test_endpoint1 during refresh.
      - .geo_mappings: was null, but now cty.ListValEmpty(cty.String)
2024-09-04T09:37:44.038+0100 [WARN]  Provider "registry.terraform.io/hashicorp/azurerm" produced an invalid plan for azurerm_traffic_manager_external_endpoint.traffic_manager_test_endpoint1, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .geo_mappings: planned value cty.ListValEmpty(cty.String) for a non-computed attribute
      - .always_serve_enabled: planned value cty.False for a non-computed attribute
      - .enabled: planned value cty.True for a non-computed attribute
      - .priority: planned value cty.NumberIntVal(1) for a non-computed attribute
2024-09-04T09:37:44.054+0100 [INFO]  provider: plugin process exited: plugin=.terraform/providers/registry.terraform.io/hashicorp/azurerm/4.0.1/windows_amd64/terraform-provider-azurerm_v4.0.1_x5.exe id=32784 
2024-09-04T09:37:44.057+0100 [INFO]  backend/local: plan operation completed

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # azurerm_traffic_manager_external_endpoint.traffic_manager_test_endpoint1 will be updated in-place
  ~ resource "azurerm_traffic_manager_external_endpoint" "traffic_manager_test_endpoint1" {
        id                   = "/subscriptions/<azure-subscription-id>/resourceGroups/traffic_manager_test/providers/Microsoft.Network/trafficManagerProfiles/trafficmanagertest/ExternalEndpoints/testendpoint1"
        name                 = "testendpoint1"
      ~ priority             = 2 -> 1
        # (7 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Expected Behaviour

The plan should not show any changes after updating the AzureRM provider from 3.116.0 to 4.0.1 when no other changes have been made.

### Actual Behaviour

The `Priority` on all the endpoints is changed to `1` and the apply fails due to all endpoints having the same priority.

### Steps to Reproduce

1. Set the provider version to `3.116.0`
2. Run `terraform init`
3. Run `terraform apply -auto-approve` to create the resources
4. Update the provider version to `4.0.1`
5. Run `terraform init -upgrade`
6. Run `terraform plan` and observe the planned change of the `Priority` from `2` to `1`

### References

This looks to be caused by the `Priority` defaulting to `1` when it isn't specified:
[Provider docs for version 4.0.1](https://registry.terraform.io/providers/hashicorp/azurerm/4.0.1/docs/resources/traffic_manager_external_endpoint#priority)

[Provider docs for version 3.116.0](https://registry.terraform.io/providers/hashicorp/azurerm/3.116.0/docs/resources/traffic_manager_external_endpoint#priority)

**Comment by sinbai** [comment] 2024-09-06 09:19
Hi @Axlecrime thanks for raising this issue. This symptom is introduced by [PR](https://github.com/hashicorp/terraform-provider-azurerm/pull/26329). I assume that this is by design since version 4.0 of the Azure Provider is a major release and includes breaking changes. See [here ](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/4.0-upgrade-guide#azurerm_traffic_manager_external_endpoint)for details. To solve this issue, it is recommended using `ignore_changes` as follows or specifying the priority value explicitly in the config. 

 ```
 lifecycle {
    ignore_changes = [priority]
  }
```

**Comment by bethforsyth** [comment] 2024-11-07 16:17
This change, unless I'm missing something, makes it very difficult to dynamically create multiple endpoints on the same traffic manager profile if they're not managed by the same terraform instance (as we would need to be able to configure unique priorities). 

Given that, as @Axelcrime mentions, priority should be optional unless the Traffic Manager Profile is configured to do priority routing, I think this is fairly straightforwardly a bug that has been introduced.

**Comment by bethforsyth** [comment] 2024-11-07 16:48
It would be really useful to understand the context behind the move away from computed values - the PR linked doesn't provide any background. Tagging @stephybun in the hope that they may be able to explain why this function has been removed?

**Comment by stephybun** [comment] 2024-11-08 06:25
Hey @bethforsyth

Thanks for tagging me on this. One of the initiatives for 4.0 was to review all existing properties that are `Optional` and `Computed` in the provider and to remove `Computed` on them if possible. In case you haven't perused our contributor guidelines, we have a section in there explaining the [problematic behaviour of `Optional`+`Computed`](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/topics/best-practices.md#setting-properties-to-optional--computed) on properties. 

If the API returns a default for a property, that is typically a signal for us that `Computed` can be removed and replaced by setting the `Default` value on the property in the schema instead, I unfortunately see that our test cases for this resource are extremely basic and didn't catch the fact that the value assigned to priority is dynamic and the effect that this removal would have on the behaviour of the resource.

This is definitely a case where `Computed` should remain on the property. I will open a PR next week to revert this back to `Computed` as well as add a more involved test case to catch any future regression here.

**Comment by bethforsyth** [comment] 2024-11-08 08:58
@stephybun  Thanks so much for the quick response, and for the context on the push to remove Computed values where possible. I agree that in this case it sounds like Computed should remain on the property - thanks for offering to open a PR to revert this, that would be really helpful!

**Closed** 2024-11-12 09:01 UTC
Labels: bug, service/traffic-manager, v/4.x

**Comment by bethforsyth** [comment] 2024-11-12 09:52
Thanks for resolving this so quickly @stephybun , it's greatly appreciated!
