### ISSUE TITLE
Import of azurerm_app_service_plan fails due to incorrect case in resource_id

### ISSUE THREAD

**Issue by sGrindvoll** [hashicorp/terraform-provider-azurerm#13361] opened 2021-09-15 11:39 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version 
Terraform version 0.14.7 (not relevant, provider related issue)
Azurerm provider version 2.76.0

### Affected Resource(s)

* `azurerm_app_service_plan`

### Terraform Configuration Files

```
terraform import azurerm_app_service_plan.instance1 /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/mygroup1/providers/Microsoft.Web/serverFarms/instance1
```

### Expected Behaviour

The resource should have been imported successfully

### Actual Behaviour

Import fails due to a parcing error:
```
Error: parsing Resoruce ID "terraform import azurerm_app_service_plan.instance1 /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/mygroup1/providers/Microsoft.Web/serverFarms/instance1": ID is missing the 'serverfarms' element
```

### Steps to Reproduce

1. Copy the resource ID of a azurerm_app_service_plan from the Azure Portal
2. Run the Terraform import command as shown above in "Terraform Configuration Files"
3. Get the parsing error described above in "What actually happend?"

### References

This issue have been raised and closed before in another issue, but not fixed in the code:
https://github.com/hashicorp/terraform-provider-azurerm/issues/2991

* #0000

**Comment by tombuildsstuff** [comment] 2021-09-15 15:03
hi @sGrindvoll 

As [per the documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service_plan#import) the casing for this needs to be `serverfarms` rather than `serverFarms` - so this is working as intended (and is highlighting which segment is missing) - as such to fix this you can update the casing on this segment which'll fix this at import time.

Since this will be fixed by updating the casing as mentioned in the error message, I'm going to close this issue for the moment.

Thanks!

**Closed by tombuildsstuff** 2021-09-15 15:03 UTC
Labels: question
