### ISSUE TITLE
Expected a Workspace ID that matched

### ISSUE THREAD

**Issue by mounikakandagadda29** [hashicorp/terraform-provider-azurerm#26159] opened 2024-05-30 17:50 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

0.13.5

### AzureRM Provider Version

3.105.0

### Affected Resource(s)/Data Source(s)

azurerm

### Terraform Configuration Files

```hcl
resource "azurerm_sentinel_automation_rule" "send_incident_to_soc" {
  name                    = "ebd13114-37d9-46dc-af18-08bda8d09e91"
  log_analytics_workspace_id = "/subscriptions/ebd13114-37d9-46dc-af18-08bda8d09e91/resourceGroups/rg-informationsecurity-production-eastus2-sentinel/providers/Microsoft.Logic/workflows/Roy-Send-Incident"
```

### Debug Output/Panic Output

```shell
parsing "/subscriptions/ebd13114-37d9-46dc-af18-08bda8d09e91/resourceGroups/rg-informationsecurity-production-eastus2-sentinel/providers/Microsoft.Logic/workflows/Roy-Send-Incident": parsing segment "staticMicrosoftOperationalInsights": parsing the Workspace ID: the segment at position 5 didn't match

Expected a Workspace ID that matched:

> /subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/example-resource-group/providers/Microsoft.OperationalInsights/workspaces/workspaceValue

However this value was provided:

> /subscriptions/ebd13114-37d9-46dc-af18-08bda8d09e91/resourceGroups/rg-informationsecurity-production-eastus2-sentinel/providers/Microsoft.Logic/workflows/Roy-Send-Incident

The parsed Resource ID was missing a value for the segment at position 5
(which should be the name of the Resource Provider [for example 'Microsoft.OperationalInsights']).



  on sl-audit-log-cleared-linux.tf line 57, in resource "azurerm_sentinel_automation_rule" "send_incident_to_soc":
  57:   log_analytics_workspace_id = "/subscriptions/ebd13114-37d9-46dc-af18-08bda8d09e91/resourceGroups/rg-informationsecurity-production-eastus2-sentinel/providers/Microsoft.Logic/workflows/Roy-Send-Incident"
```

### Expected Behaviour

i only have microsoft.logic in my workspace id, but it asking me for microsoft operationalInsights

### Actual Behaviour

it is giving an error. 

### Steps to Reproduce

resource "azurerm_sentinel_automation_rule" "send_incident_to_soc" {
  name                    = "ebd13114-37d9-46dc-af18-08bda8d09e91"
  log_analytics_workspace_id = "/subscriptions/ebd13114-37d9-46dc-af18-08bda8d09e91/resourceGroups/rg-informationsecurity-production-eastus2-sentinel/providers/Microsoft.Logic/workflows/Roy-Send-Incident"

**Comment by rkapoz-tech** [comment] 2024-05-31 10:05
Hi, 
I have the same problem by using azurerm_monitor_workspace object.

Expected a Workspace ID that matched:
│ 
│ > /subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/example-resource-group/providers/Microsoft.OperationalInsights/workspaces/workspaceValue
│ 
│ However this value was provided:
│ 
│ > /subscriptions/..../resourceGroups/...../providers/Microsoft.Monitor/accounts/azure-monitor-ws-infra
│ 
│ The parsed Resource ID was missing a value for the segment at position 5
│ (which should be the name of the Resource Provider [for example 'Microsoft.OperationalInsights']).

**Comment by magodo** [comment] 2024-06-04 05:39
@mounikakandagadda29 By definition, the `log_analytics_workspace_id` wants a [log analytics workspace](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/log_analytics_workspace).

**Comment by tombuildsstuff** [comment] 2024-06-10 10:20
Closing since per @magodo's comment above, this is expected behaviour as we're expecting a Log Analytics Workspace ID to be provided for this field, but a Logic App Workflow is being specified here instead - and as such this can be fixed by specifying the Log Analytics Workspace to use.

Thanks!

**Closed by tombuildsstuff** 2024-06-10 10:20 UTC
Labels: question, waiting-response, service/sentinel, v/3.x
