### ISSUE TITLE
Creating Data Lake Storage with terraform says datalakestore.Client#GetProperties even though It has full permissions

### ISSUE THREAD

**Issue by onenessboy** [hashicorp/terraform-provider-azurerm#17502] opened 2022-07-05 10:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.1

### AzureRM Provider Version

2.83

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "syn_st" {
   name                     = "st${var.prefix}${var.postfix}"
   resource_group_name      = var.rg_name
   location                 = var.location
   account_tier             = var.storage_account_tier
   account_replication_type = var.storage_account_replication_type
   account_kind             = var.storage_account_kind
   is_hns_enabled           = var.hns_enabled
 }
    
 resource "azurerm_role_assignment" "st_role_admin_c" {
   scope                = azurerm_storage_account.syn_st.id
   role_definition_name = "Contributor"
   principal_id         = data.azurerm_client_config.current.object_id
 }
    
 resource "azurerm_role_assignment" "st_role_admin_sbdc" {
   scope                = azurerm_storage_account.syn_st.id
   role_definition_name = "Storage Blob Data Contributor"
   principal_id         = data.azurerm_client_config.current.object_id
 }
    
 resource "azurerm_storage_data_lake_gen2_filesystem" "st_adls" {
   name               = "default"
   storage_account_id = azurerm_storage_account.syn_st.id
    
   depends_on = [
     azurerm_role_assignment.st_role_admin_sbdc
   ]
 }
```

### Debug Output/Panic Output

```shell
Error: checking for existence of existing File System "default" (Account "xxxxxxxxx"): datalakestore.Client#GetProperties: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: error response cannot be parsed: "" error: EOF
│ 
│   with module.storage_account.azurerm_storage_data_lake_gen2_filesystem.st_adls,
│   on ../modules/storage-account/main.tf line 37, in resource "azurerm_storage_data_lake_gen2_filesystem" "st_adls":
│   37: resource "azurerm_storage_data_lake_gen2_filesystem" "st_adls" {
```

### Expected Behaviour

Created file system successfully

### Actual Behaviour

Erroor

Error: checking for existence of existing File System "default" (Account "xxxxxxx"): datalakestore.Client#GetProperties: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: error response cannot be parsed: "" error: EOF
│ 
│   with module.storage_account.azurerm_storage_data_lake_gen2_filesystem.st_adls,
│   on ../modules/storage-account/main.tf line 37, in resource "azurerm_storage_data_lake_gen2_filesystem" "st_adls":
│   37: resource "azurerm_storage_data_lake_gen2_filesystem" "st_adls" {

### Steps to Reproduce

Terraform apply

### Important Factoids

My current service principal which used to create resources have all permission over storage

![image](https://user-images.githubusercontent.com/37249391/177307213-05ed0631-2e14-44b9-9adb-a1666e56a0d0.png)

and also I created a custom role to grant full permission on storage and assigned this role as well to my service principal
![image](https://user-images.githubusercontent.com/37249391/177307610-ebd2ab8f-47e8-4303-a11a-990be17b0fef.png)

**Comment by magodo** [comment] 2022-07-07 01:59
@onenessboy I've tested with below config and everything works fine, with a SP that has "owner" role:

```
provider "azurerm" {
  features {}
}
resource "azurerm_resource_group" "test" {
  name     = "acctestRG-220225134402688321"
  location = "West Europe"
}
resource "azurerm_storage_account" "test" {
  name                     = "acctestaccb1kwg"
  resource_group_name      = azurerm_resource_group.test.name
  location                 = azurerm_resource_group.test.location
  account_kind             = "BlobStorage"
  account_tier             = "Standard"
  account_replication_type = "LRS"
  is_hns_enabled           = true
}

data "azurerm_client_config" "current" {}

resource "azurerm_role_assignment" "storageAccountRoleAssignment" {
  scope                = azurerm_storage_account.test.id
  role_definition_name = "Storage Blob Data Contributor"
  principal_id         = data.azurerm_client_config.current.object_id
}

resource "azurerm_storage_data_lake_gen2_filesystem" "test" {
  name               = "default"
  storage_account_id = azurerm_storage_account.test.id
  depends_on = [
    azurerm_role_assignment.storageAccountRoleAssignment
  ]
}
``` 

By reviewing your config, presumably you shall also add `azurerm_role_assignment.st_role_admin_c` to the `depends_on` list?

The role assignment has known time gap, so I'd like to confirm the issue stll exists with a retry? To further investigate this, would you please provide the values of the input variables, and the provider debug log?

**Comment by rcskosir** [comment] 2023-08-25 16:02
Thanks for opening this issue. Since time has passed and @magodo  was not able to reproduce this issue, I am going to mark this issue closed as “can’t reproduce”. If you are able to provide more information to help us reproduce this issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!

**Closed by rcskosir** 2023-08-25 16:02 UTC
Labels: question, waiting-response, service/data-lake, v/2.x (legacy)

**Comment by codermrrob** [comment] 2024-01-04 08:13
I have the exact same problem. I am not using a Service Principle I am using my login (az login) and I have Owner privilege and Storage Blob Data Contributor. `terraform plan` executes as exepected. `terraform apply` shows the correct plan, but during the actual apply I get :

```
 Error: checking for existence of existing File System "tv-iac-state" in Storage Account (Subscription: "xxxxxxxxxxxxxxxxxxxxxx"
│ Resource Group Name: "tv-iac-rg"
│ Storage Account Name: "xxxxxxxx"): datalakestore.Client#GetProperties: Failure sending request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=<nil> <nil>
│
│   with azurerm_storage_data_lake_gen2_filesystem.iac_fs,
│   on state.storage.tf line 34, in resource "azurerm_storage_data_lake_gen2_filesystem" "iac_fs":
│   34: resource "azurerm_storage_data_lake_gen2_filesystem" "iac_fs" {
```

**Comment by codermrrob** [comment] 2024-01-04 08:26
I had the same problem.... until I realized ` is_hns_enabled = false`  was set.... :/
