### ISSUE TITLE
azurerm_private_endpoint forces recreate if casing of resource group casing of subnet differs

### ISSUE THREAD

**Issue by rickardp** [hashicorp/terraform-provider-azurerm#13819] opened 2021-10-21 07:35 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

 ```
!terraform -v
Terraform v1.0.8
on linux_amd64

azurerm = {
      source  = "hashicorp/azurerm"
      version = "2.81.0"
    }
```

### Affected Resource(s)

* `azurerm_private_endpoint`

### Terraform Configuration Files

example of the resource
```hcl
resource "azurerm_private_endpoint" "storage_private_endpoint_primary" {
  ...
  subnet_id           = var.private_link_subnet_primary
  private_service_connection {
    name                           = "${var.name}-primary-service-connection"
    private_connection_resource_id = azurerm_storage_account.storage.id
    subresource_names              = ["blob"]
    is_manual_connection           = false
  }
  private_dns_zone_group {
    name                 = "privatelink.blob.core.windows.net"
    private_dns_zone_ids = [var.private_dns_zone_id]
  }
}

```

The subnet ID (`private_link_subnet_primary`) contains the subnet, but the resource group is lowercase instead of as it was created, with PascalCase.

### Expected Behaviour

Since resource groups are case insensitive, a "plan" following a "deploy" yields no change.

https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules#microsoftresources

Most Azure resource names are case insensitive and Terraform must respect this, since some of the APIs will not return the existing IDs in their canonical form (as in the example of the private link service lowercasing the resource group). I did not investigate if the casing of the other components of the ID causes similar issue, but I suspect so.

Also note that just lowercasing the string will not work as the service type etc are not lowercased.

### Actual Behaviour

The plan wants to recreate the resource, indicating that a change in subnet ID mandates force recreate. The diff between the old and the new string is just the casing of the resource group nae,s.

The problem is made worse by the fact that extracting the resource ID from a data resource. So it looks like this happens anytime I use non-lowercase resource group names unless I miss something.

Example output

```
# module.client_storage.azurerm_private_endpoint.storage_private_endpoint_primary must be replaced
    -/+ resource "azurerm_private_endpoint" "storage_private_endpoint_primary" {
   ...
~ subnet_id                = "/subscriptions/xxx/resourceGroups/my-resource-group/providers/Microsoft.Network/virtualNetworks/yyy/subnets/zzz" -> "/subscriptions/xxx/resourceGroups/My-ResourceGroup/providers/Microsoft.Network/virtualNetworks/yyy/subnets/zzz" # forces replacement
```

Working around this by setting

```
subnet_id           = replace(var.private_link_subnet_primary, ""My-ResourceGroup, "my-resource-group")
```
makes "terraform plan" work as expected (but this workaround is obviously very ugly to have in my .tf files)

### Steps to Reproduce

1. Create a `azurerm_private_endpoint` with an explicit subnet ID, deliberately altering the casing of the resource group.
2. terraform apply
3. terraform plan

Observe that "terraform plan" shows the resource has to be recreated.

**Comment by tombuildsstuff** [comment] 2021-10-21 08:13
Duplicate of #12184

**Closed by tombuildsstuff** 2021-10-21 08:13 UTC
Labels: question, upstream-microsoft
