### ISSUE TITLE
Add techniques to the alert rule scheduled in addition to tactics from the mitre att&ck framework (azurerm_sentinel_alert_rule_scheduled)

### ISSUE THREAD

**Issue by Thz4UQgy** [hashicorp/terraform-provider-azurerm#16265] opened 2022-04-06 05:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

(https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/sentinel_alert_rule_scheduled) we need the possibility to add techniques to the alert rule scheduled in addition to tactics from the mitre att&ck framework. This is possible via ARM but not yet via Terraform

### New or Affected Resource(s)/Data Source(s)

azurerm_sentinel_alert_rule_scheduled

### Potential Terraform Configuration

```hcl
resource "azurerm_sentinel_alert_rule_scheduled" "sample_analyticsrule" {
  name                       = "sample_analyticsrule"
  log_analytics_workspace_id = data.azurerm_log_analytics_workspace.samplelaw.id
  display_name               = "sample_analyticsrule"
  description                = <<-EOT
  Sample Description
  EOT

  severity        = "High"
  enabled         = "true"
  query_frequency = "PT5M"
  query_period    = "PT5M"
  tactics         = ["DefenseEvasion"]
  techniques      = ["TXXXX"] #New Setting
  #alert_rule_template_guid = ""
  event_grouping {
    aggregation_method = "AlertPerResult"
  }
  incident_configuration {
    create_incident = "true"
    grouping {
      enabled                = "true"
      lookback_duration      = "P1D"
      entity_matching_method = "AllEntities"
    }
  }

  query = <<QUERY
SampleEvent
| where EventID == xxxx
QUERY
alert_details_override {
  description_format
}

  #Mappings based on KQL_Query
  entity_mapping {
    #ref: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/sentinel_alert_rule_scheduled#entity_type
    entity_type = "Host"
    field_mapping {
      identifier  = "HostName"
      column_name = "Computer"
    }
    field_mapping {
      identifier  = "NTDomain"
      column_name = "DomainName"
    }
  }
}
```

**Comment by riyadmurad** [comment] 2022-04-06 06:29
Please add this feature. We are deploying Sentinel as a Code and It would be very helpful to have this feature

**Comment by magodo** [comment] 2022-04-07 09:06
Blocked by https://github.com/Azure/azure-sdk-for-go/issues/17470

**Comment by Thz4UQgy** [comment] 2022-04-13 11:09
Hi, could you give me a status update of this feature request? Kind regards

**Comment by luke-iseger91** [comment] 2022-06-22 08:49
It seems the issue with the Azure SDK that was blocking this feature has been solved. Is there already some branch where we can contribute to solve this one?

**Comment by magodo** [comment] 2022-06-22 09:22
Though the PR is merged, the issue is still opened as the SDK is not released yet.

**Comment by chrisjaimon2012** [comment] 2022-08-16 08:14
Related issue > https://github.com/hashicorp/terraform-provider-azurerm/issues/17910

**Comment by PCNZ** [comment] 2022-09-19 00:25
Looks like the go sdk which was blocking was released June 23rd? The day after the last discussions on this.
Is there another blocker?

**Closed** 2022-09-21 00:58 UTC
Labels: enhancement, sdk/requires-newer-api-version, service/sentinel
