### ISSUE TITLE
azurerm_chaos_studio_experiment destroy operation times out

### ISSUE THREAD

**Issue by luisfeliz79** [hashicorp/terraform-provider-azurerm#25462] opened 2024-03-28 19:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.75

### AzureRM Provider Version

3.97.1

### Affected Resource(s)/Data Source(s)

azurerm_chaos_studio_experiment

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = ">=3.97.1"
    }
  }
}

provider "azurerm" {
  features {}
}

# Define some local variables
locals {
  prefix_name="chaos-azurem-test"
  location="eastus"
}

# Create a resource group 
resource "azurerm_resource_group" "rg" {
  name     = "${local.prefix_name}-rg"
  location = local.location
}

# Create an NSG
resource "azurerm_network_security_group" "test_nsg" { 
    name                        = "chaos-controlled-nsg"
    resource_group_name = azurerm_resource_group.rg.name
    location            = azurerm_resource_group.rg.location
}

# Onboard the NSG as a Chaos Studio target
resource "azurerm_chaos_studio_target" "nsg" {
  location           = azurerm_resource_group.rg.location
  target_resource_id = azurerm_network_security_group.test_nsg.id
  target_type        = "Microsoft-NetworkSecurityGroup"

}

# Create a very simple experiment
# It doesnt actually do anything other to run through a delay
# this is just for illustration purposes for the issue
resource "azurerm_chaos_studio_experiment" "example" {
  location            = azurerm_resource_group.rg.location
  name                = "${local.prefix_name}-simple-experiment"
  resource_group_name = azurerm_resource_group.rg.name

  selectors {
    name                    = "Selector1"    
    chaos_studio_target_ids = [azurerm_chaos_studio_target.nsg.id]
  }

 steps {
    name = "Step 2 - Wait 10 minutes"
    branch {
      name = "Branch 1"
      actions {
        urn           = "urn:csci:microsoft:chaosStudio:timedDelay/1.0"
        # Ref - https://learn.microsoft.com/en-us/azure/chaos-studio/chaos-studio-fault-library#sample-json
        
        action_type   = "delay"
        duration      = "PT10M"  # ISO 8601 time format
      }
    }
  }


}

# Some output information
output experiment_id {
  value = azurerm_chaos_studio_experiment.example.id
}
```

### Debug Output/Panic Output

```shell
https://gist.github.com/luisfeliz79/bc85cd104b69810a1f95851c651d463a
```

### Expected Behaviour

The experiment is destroyed and the terraform destroy operation completes successfully.

### Actual Behaviour

the terraform destroy operation runs for 30 minutes, then throws this error:

azurerm_chaos_studio_experiment.example: Still destroying... [id=/subscriptions/e31e07c8-2d2c-4c74-9886-...ts/chaos-azurem-test-simple-experiment, 29m51s elapsed]
╷
│ Error: deleting Experiment (Subscription: "xxxxxxxxxxxxxxxxx"
│ Resource Group Name: "chaos-azurem-test-rg"
│ Experiment Name: "chaos-azurem-test-simple-experiment"): polling after Delete: context deadline exceeded
│
│ deleting Experiment (Subscription: "xxxxxxxxxxxxxxxxx"
│ Resource Group Name: "chaos-azurem-test-rg"
│ Experiment Name: "chaos-azurem-test-simple-experiment"): polling after Delete: context deadline exceeded
╵

### Steps to Reproduce

terraform init
terraform plan -out my.plan
terraform apply my.plan

terraform destroy --auto-approve

### References

If I use the Azure Portal or make an Azure REST API call directly to delete the experiment, using the specific API version below, it experiment deletes properly.

Example:
#powershell
$experiment_id='/subscriptions/xxxx-2d2c-xxxx-xxxx-e6fxxxx646/resourceGroups/chaos-azurem-test-rg/providers/Microsoft.Chaos/experiments/chaos-azurem-test-simple-experiment'
az rest --method DELETE --uri "[https://management.azure.com$($experiment_id)?api-version=2023-04-15-preview](https://management.azure.com$($experiment_id)/?api-version=2023-04-15-preview)"

**Comment by MasterRyd3l** [comment] 2024-03-28 23:57
we recently updated provisionState for 2023-11-01 API. This likely caused the timeout. Can someone at hashicorp look into this?

**Comment by tombuildsstuff** [comment] 2024-04-02 09:17
@MasterRyd3l would you mind elaborating on how the `ProvisioningState` has changed? Checking the API Definition (and the log above) the values for `ProvisioningState` look pretty standard - however per the debug log above it appears the API is no longer returning a 404 once this resource has been deleted, which would be an issue?

**Comment by MasterRyd3l** [comment] 2024-05-14 20:58
because delete has become long running. you would need to poll the the location header that gets returned from DELETE call to get either a 200 or 404

**Comment by tombuildsstuff** [comment] 2024-05-15 09:42
@MasterRyd3l FWIW [we're already polling on the LRO](https://github.com/hashicorp/terraform-provider-azurerm/blob/8bacadd5fca6ff08a7a777102690334ce12795a0/internal/services/chaosstudio/chaos_studio_experiment_resource.go#L312-L314), so it appears there's potentially something else needed here, is the service using a custom value for the `provisioningState` field?

**Comment by MasterRyd3l** [comment] 2024-05-16 05:23
I think our implementation is standard. azure portal is able to recognize our header and poll successfully. Do you have any logs? Any logs from the DeleteAndThenPoll method would help. Or can you point me to the source of that method?

**Comment by tombuildsstuff** [comment] 2024-05-16 12:32
@MasterRyd3l checking the HTTP responses, what's happening is we:

1. Call the DELETE endpoint (i.e. `DELETE /subscriptions/XXX/resourceGroups/acctestrg-240516141437412099/providers/Microsoft.Chaos/experiments/acctestcse-mewns?api-version=2023-11-01`) which returns an LRO
2. We then query the LRO (i.e. `GET
:path: /subscriptions/XXX/providers/Microsoft.Chaos/locations/westeurope/operationStatuses/d8f9d5f8-f842-487e-ab02-d2be26a2e9c7?api-version=2023-11-01&t=XXX&c=XXX`) which returns both a Location header (for the original resource URI from 1 - and `"status": "succeeded"` in the API response)
3. We then query the original Resource URI (i.e. `GET /subscriptions/XXX/resourceGroups/acctestrg-240516141437412099/providers/Microsoft.Chaos/experiments/acctestcse-mewns?api-version=2023-11-01`) to ensure it's actually deleted - but the API returns a 200 OK (so we have to assume it's still around) - whereas other APIs return a 404. We do this because some APIs return that a resource is deleted before it's fully deleted, so this ensures we only mark the resource as deleted when it's actually deleted in Azure)

(all of this is done automatically by `DeleteThenPoll`)

We ultimately time out since the API continues returning a 200 OK for a deleted resource, rather than a 404 (like other APIs do) which we're polling for. As such this looks to be an API bug where the API is returning 200 rather than a 404 when the resource no longer exists? From our side the resource is gone at the highlighted request (the one above deletes the resource), so provided the API returns a 404 this should work as expected:

![Screenshot 2024-05-16 at 14 27 34](https://github.com/hashicorp/terraform-provider-azurerm/assets/666005/28628303-cd4b-453f-87c2-bdc9b7f0b4ca)

**Comment by MasterRyd3l** [comment] 2024-05-16 22:39
I see, thanks. I get the picture now. We'll need to follow up with ARM to understand the expected behavior.

**Comment by MasterRyd3l** [comment] 2024-05-16 22:50
### here is the guidance for a regular delete (non-lro)
The resource provider can return 200 (OK) or 204 (NoContent) to indicate that the operation completed successfully. A 200 (OK) should be returned if the object exists and was deleted successfully; and a 204 (NoContent) should be used if the resource does not exist and the request is well formed.
202 (Accepted) can be returned to indicate that the operation will complete asynchronously
If the resource group does not exist, 404 (NotFound) will be returned by the proxy layer and will not reach the resource provider. 412 (PreconditionFailed) and other normal REST codes are acceptable as long as they match the REST guidelines.
### now here is the guidance for async delete (lro)
The API flow should be to
Respond to the initial DELETE request with a 202 Accepted
The response headers MUST include a Location header that points to a URL where the ongoing operation can be monitored
Optional: The response headers may include an Azure-AsyncOperation header pointing to an Operation resource
If a provisioningState property is used for the resource, it MUST transition to a non-terminal state like "Deleting"
If the DELETE completes successfully, the URL that was returned in the Location header MUST now return a 200 OK or 204 NoContent to indicate success and the resource MUST disappear.
I am pretty sure we are implementing to the new standard. I think on your side you need to start anticipating both pattern as more and more team will likely migrate to the new pattern in newer version of their API as well

**Comment by tombuildsstuff** [comment] 2024-05-17 06:35
@MasterRyd3l thanks for the updated information, AFAIK we do support both of those scenarios, but per the last component there:

> the resource MUST disappear

Per [my comment above](https://github.com/hashicorp/terraform-provider-azurerm/issues/25462#issuecomment-2115129048) the resource is deleted (as confirmed by polling on the LRO) at the highlighted (red) line, however this is continuing to kick around - as such I don't believe the API is correctly implementing this behaviour?

Based on the guidance in your comment, once a resource has been deleted (that is either via a LRO/polling on the Location header, or as a regular delete) - doing a GET on the resource that's been deleted should return a 404, whereas right now the API is returning a 200 OK (with no body).

**Comment by MasterRyd3l** [comment] 2024-05-17 21:13
ah I see what you mean. I misread your previous post. I verified the bug. We'll work on a fix. I'll post back when it's resolved

**Comment by tombuildsstuff** [comment] 2024-05-21 07:47
Awesome, thanks @MasterRyd3l :)

**Comment by MasterRyd3l** [comment] 2024-06-10 18:28
Hi @tombuildsstuff, the fix is expected to complete on Thursday 6/13

**Comment by MasterRyd3l** [comment] 2024-06-19 23:47
Hi @tombuildsstuff, the fix had been rolled out. Can you please confirm if this scenario in question is fixed on your end or not?

**Comment by rcskosir** [comment] 2024-10-04 14:38
@luisfeliz79 Thanks for taking the time to submit this issue. It looks like this has been resolved upstream. As such, I am going to mark this issue as closed. If that is not the case, please provide additional information including the version in which you are still experiencing this issue, thanks!

**Closed by rcskosir** 2024-10-04 14:38 UTC
Labels: bug, v/3.x, service/chaos-studio, upstream/microsoft/waiting-on-service-team
