### ISSUE TITLE
azurerm v2.93.1 is crashing for unknown reasons in existing setup

### ISSUE THREAD

**Issue by jimmoods** [hashicorp/terraform-provider-azurerm#15136] opened 2022-01-27 04:35 UTC
We are receiving this stack trace when running 'terraform plan -out plan.out'. 

Stack trace from the terraform-provider-azurerm_v2.93.1 plugin:

[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x51a01fd]

goroutine 1375 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/network.resourceBastionHostRead(0xc0007c3080, {0x6199600, 0xc0009ac000})
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/internal/services/network/bastion_host_resource.go:255 +0x5dd
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x6a75907, {0x717e878, 0xc0000a5740}, 0x24, {0x6199600, 0xc0009ac000})
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:346 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc00114bea0, {0x717e878, 0xc0000a5740}, 0xc001a045b0, {0x6199600, 0xc0009ac000})
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:635 +0x35b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0006984c8, {0x717e878, 0xc0000a5740}, 0xc0000a57c0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:576 +0x534
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0000cf480, {0x717e920, 0xc00096c300}, 0xc00078c4e0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server/server.go:553 +0x3b0
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x66da660, 0xc0000cf480}, {0x717e920, 0xc00096c300}, 0xc00078c480, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000051180, {0x71ccfc8, 0xc0014a2000}, 0xc002754120, 0xc00141d8f0, 0xb735a30, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0xc6f
google.golang.org/grpc.(*Server).handleStream(0xc000051180, {0x71ccfc8, 0xc0014a2000}, 0xc002754120, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1617 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:940 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:938 +0x294

Error: The terraform-provider-azurerm_v2.93.1_x5 plugin crashed!

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* azurerm_private_endpoint
* azurerm_bastion_host

Is this related to #15058?

**Comment by lonegunmanb** [comment] 2022-01-27 05:01
Hi @jimmoods , I think this issue could be duplicated with #15074 which has been fixed but not released yet.

**Comment by jimmoods** [comment] 2022-01-27 05:03
Hi @lonegunmanb  thanks for the response, we reverted to 2.92 and were able to apply our changes. 
Do you know when 2.94 will be released?

**Comment by tombuildsstuff** [comment] 2022-01-27 09:13
Duplicate of #15058 which has been fixed by #15074 / will ship in 2.92

**Closed by tombuildsstuff** 2022-01-27 09:13 UTC
