### ISSUE TITLE
Support for azurerm_key_vault_secret using data plan access_policies only

### ISSUE THREAD

**Issue by jonathan-kaufman-by** [hashicorp/terraform-provider-azurerm#11451] opened 2021-04-23 14:07 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The azurerm_key_vault_secret requires the account have read access to the Azure Key Vault in addition to a  data plane access policy that provides access.  In our company we are provided with an SPN that has data plane access (API), but not Azure Resource access.   The azurerm_key_vault_secret resource does not work in this instance, so I am forced to work around the issue (like using Azure CLI to set the secret using the SPN).

### New or Affected Resource(s)

* azurerm_key_vault_secret 

### Potential Terraform Configuration

```hcl
provider "azurerm" {
  alias = "myprovider"
  features {}
  client_id                  = var.MY_CLIENT_ID
  client_secret              = var.MY_CLIENT_SECRET
  tenant_id                  = var.MY_TENANT_ID
  subscription_id            = var.MY_SUBSCRIPTION_ID
  skip_provider_registration = true
}
resource "azurerm_key_vault_secret" "servicebus_queue_secondary_key" {
   provider            = azurerm.myprovider
   name         = "${local.mylocalvar}-sb-queue-secondary-key"
   value        = module.servicebus_queue_authorization_rule["ar01"].servicebus_queue_authorization_rule_object.secondary_key
   key_vault_id = "/subscriptions/00000000-0000-0000-0000-00000000/resourceGroups/myresourcegroup/providers/Microsoft.KeyVault/vaults/mykeyvault"
 }
```

### References

* #0000

**Comment by tombuildsstuff** [comment] 2021-11-15 13:51
hi @jonathan-kaufman-by 

Ultimately this is a duplicate of #9738 - since that'd involve accessing this conditionally over either Data Plane or Resource Manager - however unfortunately the two API's aren't feature-compatible at this time as such we're blocked waiting for them to become so.

Rather than having multiple issues open tracking the same thing I'm going to close this in favour of #9738, would you mind subscribing to that issue for updates?

Thanks!

**Closed by tombuildsstuff** 2021-11-15 13:51 UTC
Labels: enhancement, service/keyvault
