### ISSUE TITLE
azurerm_monitor_diagnostic_setting with dynamic always updates resource

### ISSUE THREAD

**Issue by Rsimk** [hashicorp/terraform-provider-azurerm#13915] opened 2021-10-27 07:38 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.0.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.7.0
+ provider registry.terraform.io/hashicorp/azurerm v2.82.0
+ provider registry.terraform.io/hashicorp/null v3.1.0

### Affected Resource(s)

* `azurerm_monitor_diagnostic_setting`

### Terraform Configuration Files

```hcl
resource "azurerm_monitor_diagnostic_setting" "mlw_diag_logging" {
  name                       = "diag-mlw-log"
  target_resource_id         = azurerm_machine_learning_workspace.analytics.id
  log_analytics_workspace_id = azurerm_log_analytics_workspace.logs.id
  storage_account_id         = azurerm_storage_account.logs.id

  dynamic "log" {
    iterator = log_category
    for_each = data.azurerm_monitor_diagnostic_categories.mlw.logs

    content {
      category = log_category.value
      enabled  = true

      retention_policy {
        enabled = true
        days    = 30
      }
    }
  }

  dynamic "metric" {
    iterator = metric_category
    for_each = data.azurerm_monitor_diagnostic_categories.mlw.metrics

    content {
      category = metric_category.value
      enabled  = true

      retention_policy {
        enabled = true
        days    = 30
      }
    }
  }
}
```

### Debug Output

```hcl
    azurerm_monitor_diagnostic_setting.mlw_diag_logging will be updated in-place
  ~ resource "azurerm_monitor_diagnostic_setting" "mlw_diag_logging" {
        id                         = "/subscriptions/[removed]/resourceGroups/[removed]/providers/Microsoft.MachineLearningServices/workspaces/[removed]|diag-mlw-log"
        name                       = "diag-mlw-log"
         (3 unchanged attributes hidden)

      - log {
          - category = "AmlComputeClusterEvent" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 30 -> null
              - enabled = true -> null
            }
        }
      - log {
          - category = "AmlComputeClusterNodeEvent" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 30 -> null
              - enabled = true -> null
            }
        }
      - log {
          - category = "AmlComputeCpuGpuUtilization" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 30 -> null
              - enabled = true -> null
            }
        }
      - log {
          - category = "AmlComputeJobEvent" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 30 -> null
              - enabled = true -> null
            }
        }
      - log {
          - category = "AmlRunStatusChangedEvent" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 30 -> null
              - enabled = true -> null
            }
        }
      - log {
          - category = "ComputeInstanceEvent" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 30 -> null
              - enabled = true -> null
            }
        }
      - log {
          - category = "DataLabelChangeEvent" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 30 -> null
              - enabled = true -> null
            }
        }
      - log {
          - category = "DataLabelReadEvent" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 30 -> null
              - enabled = true -> null
            }
        }
      - log {
          - category = "DataSetChangeEvent" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 30 -> null
              - enabled = true -> null
            }
        }
      - log {
          - category = "DataSetReadEvent" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 30 -> null
              - enabled = true -> null
            }
        }
      - log {
          - category = "DataStoreChangeEvent" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 30 -> null
              - enabled = true -> null
            }
        }
      - log {
          - category = "DataStoreReadEvent" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 30 -> null
              - enabled = true -> null
            }
        }
      - log {
          - category = "DeploymentEventACI" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 30 -> null
              - enabled = true -> null
            }
        }
      - log {
          - category = "DeploymentEventAKS" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 30 -> null
              - enabled = true -> null
            }
        }
      - log {
          - category = "DeploymentReadEvent" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 30 -> null
              - enabled = true -> null
            }
        }
      - log {
          - category = "EnvironmentChangeEvent" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 30 -> null
              - enabled = true -> null
            }
        }
      - log {
          - category = "EnvironmentReadEvent" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 30 -> null
              - enabled = true -> null
            }
        }
      - log {
          - category = "InferencingOperationACI" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 30 -> null
              - enabled = true -> null
            }
        }
      - log {
          - category = "InferencingOperationAKS" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 30 -> null
              - enabled = true -> null
            }
        }
      - log {
          - category = "ModelsActionEvent" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 30 -> null
              - enabled = true -> null
            }
        }
      - log {
          - category = "ModelsChangeEvent" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 30 -> null
              - enabled = true -> null
            }
        }
      - log {
          - category = "ModelsReadEvent" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 30 -> null
              - enabled = true -> null
            }
        }
      - log {
          - category = "PipelineChangeEvent" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 30 -> null
              - enabled = true -> null
            }
        }
      - log {
          - category = "PipelineReadEvent" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 30 -> null
              - enabled = true -> null
            }
        }
      - log {
          - category = "RunEvent" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 30 -> null
              - enabled = true -> null
            }
        }
      - log {
          - category = "RunReadEvent" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 30 -> null
              - enabled = true -> null
            }
        }
      + log {
          + category = (known after apply)
          + enabled  = (known after apply)

          + retention_policy {
              + days    = (known after apply)
              + enabled = (known after apply)
            }
        }

      - metric {
          - category = "AllMetrics" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 30 -> null
              - enabled = true -> null
            }
        }
      + metric {
          + category = (known after apply)
          + enabled  = (known after apply)

          + retention_policy {
              + days    = (known after apply)
              + enabled = (known after apply)
            }
        }
    }

```

### Expected Behaviour

Azure Machine Learning Workspace diagnostic settings should not be update everytime apply command is run.

### Actual Behaviour

Each time apply command is run the resource will be changed.

**Comment by flmmartins** [comment] 2021-11-30 10:26
I am having the same issue:

```
# Variable:

diagnostic_settings = {
  "kube-weu-audit" = {
    target               = "/subscriptions/redacted_id/resourceGroups/redacted_rg/providers/Microsoft.ContainerService/managedClusters/kube-weu"
    eventhub_name        = "kube-weu-audit"
    eventhub_policy_name = "cluster"
    logs = [{
      category = "kube-audit"
      enabled  = true
      },
      {
        category = "kube-audit-admin"
        enabled  = true
      }]
  }
  "activity-monitor-audit" = {
    target                 = "/subscriptions/redacted_id"
    eventhub_name        = "activity-monitor-audit"
    eventhub_policy_name = "activitymonitor"
    logs = [{
      category = "Security"
      enabled  = true
      }]
  }
}

resource "azurerm_monitor_diagnostic_setting" "this" {
  for_each = var.diagnostic_settings

  name               = each.key
  target_resource_id = each.value.target
  eventhub_name      = each.value.eventhub_name
  eventhub_authorization_rule_id = module.monitoring_eventhub.namespace_policy_ids[each.value.eventhub_policy_name]

  dynamic "log" {
    for_each = toset(each.value.logs)
    content {
      category = log.value.category
      enabled  = log.value.enabled
    }
  }
}

```

The result is:

```
Terraform will perform the following actions:

  # azurerm_monitor_diagnostic_setting.this["activity-monitor-audit"] will be updated in-place
  ~ resource "azurerm_monitor_diagnostic_setting" "this" {
        id                             = "/subscriptions/redatec_id|activity-monitor-audit"
        name                           = "activity-monitor-audit"
        # (3 unchanged attributes hidden)

      - log {
          - category = "Alert" -> null
          - enabled  = false -> null
        }
      - log {
          - category = "Autoscale" -> null
          - enabled  = false -> null
        }
      - log {
          - category = "Recommendation" -> null
          - enabled  = false -> null
        }
      - log {
          - category = "ResourceHealth" -> null
          - enabled  = false -> null
        }
      - log {
          - category = "ServiceHealth" -> null
          - enabled  = false -> null
        }
        # (3 unchanged blocks hidden)
    }

  # azurerm_monitor_diagnostic_setting.this["kube-weu-audit"] will be updated in-place
  ~ resource "azurerm_monitor_diagnostic_setting" "this" {
        id                             = "/subscriptions/redatec_id/resourceGroups/redacted_rg/providers/Microsoft.ContainerService/managedClusters/kube-weu|kube-weu-audit"
        name                           = "kube-weu-audit"
        # (3 unchanged attributes hidden)

      - log {
          - category = "cloud-controller-manager" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      - log {
          - category = "cluster-autoscaler" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      - log {
          - category = "guard" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      - log {
          - category = "kube-apiserver" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      - log {
          - category = "kube-audit" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      + log {
          + category = "kube-audit"
          + enabled  = true
        }
      - log {
          - category = "kube-audit-admin" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      + log {
          + category = "kube-audit-admin"
          + enabled  = true
        }
      - log {
          - category = "kube-controller-manager" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      - log {
          - category = "kube-scheduler" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }

      - metric {
          - category = "AllMetrics" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
    }
```

I tried to solve this issue by using data azurerm_monitor_diagnostic_categories but that seems a workaround and also doesn't work for activity logs.

**Comment by rscottwatson** [comment] 2022-01-12 20:53
Any update on this as I am seeing similar issues with statically defined log resources for my AKS cluster.  For example I have the following and I am using the latest provider version v2.91.0

`resource "azurerm_monitor_diagnostic_setting" "diag-la-aks-01" {
  name               = "diag-la-aks-01"
  target_resource_id = var.aksid
  log_analytics_workspace_id = azurerm_log_analytics_workspace.primary.id 


  log {
    category = "kube-apiserver"
    enabled  = true

    retention_policy {
      enabled = false
    }
  }

  log {
    category = "kube-audit"
    enabled  = false

    retention_policy {
      enabled = false
    }
  }

  log {
    category = "kube-audit-admin"
    enabled  = false

    retention_policy {
      enabled = false
    }
  }
  ...`
  
  And each time I run the plan it says it will updated in place 
  
  `  # module.log-analytics.azurerm_monitor_diagnostic_setting.diag-la-aks-01 will be updated in-place

  ~ resource "azurerm_monitor_diagnostic_setting" "diag-la-aks-01" {

        id                         = "/subscriptions/****/resourceGroups/***/providers/Microsoft.ContainerService/managedClusters/***|diag-la-aks-01"

        name                       = "diag-la-aks-01"

        # (2 unchanged attributes hidden)



      - log {

          - category = "cloud-controller-manager" -> null

          - enabled  = false -> null



          - retention_policy {

              - days    = 0 -> null

              - enabled = false -> null

            }

        }
        ...`

**Comment by mortenn** [comment] 2022-01-31 13:09
I've set up log analytics for automation purposes in Azure;
```
resource "azurerm_monitor_diagnostic_setting" "aa_diags_logs" {
  name                       = "LogsToLogAnalytics"
  target_resource_id         = azurerm_automation_account.default.id
  log_analytics_workspace_id = azurerm_log_analytics_workspace.norway_east.id

  log {
    category = "AuditEvent"
    enabled = false

    retention_policy {
      days    = 0
      enabled = false
    }
  }
  ...
}
```
and get changes every time;
```
~ resource "azurerm_monitor_diagnostic_setting" "aa_diags_metrics" {
        id                         = "/subscriptions/.../resourceGroups/.../providers/Microsoft.Automation/automationAccounts/...|MetricsToLogAnalytics"
        name                       = "MetricsToLogAnalytics"
        # (2 unchanged attributes hidden)

      - log {
          - category = "AuditEvent" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      - log {
          - category = "DscNodeStatus" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      + log {
          + category = "DscNodeStatus"
          + enabled  = false

          + retention_policy {
              + enabled = false
            }
        }
...
        # (1 unchanged block hidden)
    }
```

**Comment by joshschmitter** [comment] 2022-01-31 16:51
Still happening for me:
```
Terraform v1.0.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.67.0
```

Anyone have a workaround until the bug is fixed?
Any word from Microsoft on fixing the bug?  Would be nice to know that a fix is in progress.

**Comment by mortenn** [comment] 2022-01-31 17:14
By the way, I am running the latest version;
```
Terraform v1.1.4
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.94.0
```

**Comment by daniel-anova** [comment] 2022-02-11 13:33
Duplicate or related to https://github.com/hashicorp/terraform-provider-azurerm/issues/10388 ?

**Comment by Lunik** [comment] 2022-02-25 13:29
> Duplicate or related to #10388 ?

Duplicate

**Comment by tombuildsstuff** [comment] 2022-03-21 10:43
As @daniel-anova has mentioned, this is a duplicate of https://github.com/hashicorp/terraform-provider-azurerm/issues/10388 - please subscribe to that issue for updates.

**Closed by tombuildsstuff** 2022-03-21 10:43 UTC
Labels: bug, service/monitor
