### ISSUE TITLE
Adding tags (and no other changes) to frontdoor causes unrelated error

### ISSUE THREAD

**Issue by markti** [hashicorp/terraform-provider-azurerm#6828] opened 2020-05-08 12:39 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.18
+ provider.azuread v0.6.0
+ provider.azurerm v2.6.0
+ provider.random v2.2.0

### Affected Resource(s)

* `azurerm_frontdoor`

### Terraform Configuration Files

```hcl
resource "azurerm_frontdoor" "frontdoor" {
  name                                         = var.name
  resource_group_name                          = var.resource_group_name

  enforce_backend_pools_certificate_name_check = false

  routing_rule {
    name               = "PrimaryRoutingRules"
    accepted_protocols = [ "Https" ]
    patterns_to_match  = [ "/*" ]
    frontend_endpoints = [ "PrimaryEndpoint" ]
    forwarding_configuration {
      forwarding_protocol = "MatchRequest"
      backend_pool_name   = "PrimaryBackend"
    }
  }

  backend_pool_load_balancing {
    name = "baseline"
    additional_latency_milliseconds = 1000
  }

  backend_pool_health_probe {
    name      = "baseline"
    protocol  = "Https"
    path      = var.backend_healthprobe_path
  }

  backend_pool {
    name = "PrimaryBackend"
    backend {
      host_header = var.backend_host_header
      address     = var.backend_fqdn
      http_port   = 80
      https_port  = 443
    }

    load_balancing_name = "baseline"
    health_probe_name   = "baseline"
  }

  frontend_endpoint {
    name                              = "PrimaryEndpoint"
    host_name                         = var.frontend_hostname
    custom_https_provisioning_enabled = true

    custom_https_configuration {
      certificate_source    = "FrontDoor"
    }
  }

}
```

then add tag block...

```hcl
  tags = {
    app = var.app_name
    env = var.env_name
  }
```

### Panic Output

Error: creating Front Door "foo" (Resource Group "fizz"): frontdoor.FrontDoorsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="Front door must always contain the default associated frontend endpoint: 'foo.azurefd.net'."

### Expected Behavior

It should add tags to the already successfully deployed azure front door...

### Actual Behavior

it gave an error and did not add the tags...

### Steps to Reproduce

1. setup CNAME for azure frontdoor frontend
1. `terraform apply` with front door as configured above but NO tags block
2. `terraform apply` with front door after adding tag blocks

### References

* #0000

**Comment by athempel** [comment] 2020-06-05 12:52
It looks like this might be caused by a breaking change in the Front Door API. It affects new Front Doors, not just updates to existing Front Doors.

The API now seems to require explicit configuration of a front-end endpoint for the default `frontdoorname.azurefd.net` domain name.

You can provide this by adding a section like the following to your `azurerm_frontdoor` resource:

```
  frontend_endpoint {
    name = "default"
    host_name = "${var.frontdoor_name}.azurefd.net"
    custom_https_provisioning_enabled = false
  }

```

**Comment by favoretti** [comment] 2021-08-19 13:00
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.

**Closed by favoretti** 2021-08-19 13:00 UTC
Labels: service/frontdoor
