### ISSUE TITLE
azurerm_monitor_metric_alert target_resource_location northeurope is not a valid region name for Microsoft.RecoveryServices/vaults resource type

### ISSUE THREAD

**Issue by mpjtaylor** [hashicorp/terraform-provider-azurerm#21260] opened 2023-04-03 09:02 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.7

### AzureRM Provider Version

3.50.0

### Affected Resource(s)/Data Source(s)

azurerm_monitor_metric_alert

### Terraform Configuration Files

```hcl
resource "azurerm_monitor_metric_alert" "backup_health" {
  name                     = "Backup Health Alert"
  resource_group_name      = data.azurerm_resource_group.support.name
  scopes                   = [data.azurerm_resource_group.support.id]
  description              = "Alert on Backup Health Events"
  target_resource_location = var.location
  target_resource_type     = "Microsoft.RecoveryServices/vaults"
  auto_mitigate            = true
  frequency                = "PT1H"
  window_size              = "P1D"

  criteria {
    metric_namespace = "Microsoft.RecoveryServices/vaults"
    metric_name      = "BackupHealthEvent"
    aggregation      = "Count"
    operator         = "GreaterThan"
    threshold        = "0"

    dimension {
      name     = "dataSourceURL"
      operator = "Include"
      values = [
        "*"
      ]
    }

    dimension {
      name     = "healthStatus"
      operator = "Exclude"
      values   = ["Healthy"]
    }
  }
  action {
    action_group_id    = azurerm_monitor_action_group.supportalerts[0].id
    webhook_properties = {}
  }
}
```

### Debug Output/Panic Output

```shell
Error: creating or updating Monitor Metric Alert: (Name "Backup Health Alert" / Resource Group "resourcegroup1"): insights.MetricAlertsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="northeurope is not a valid region name for Microsoft.RecoveryServices/vaults resource type. Activity ID: 063dc270-d51a-43dc-bc61-7bf702c04b26."
```

### Expected Behaviour

Alert should have been configured with correct resource group scope and resource type

### Actual Behaviour

Failed to deploy

### Steps to Reproduce

terraform plan

**Comment by ziyeqf** [comment] 2023-04-07 05:49
Hi @mpjtaylor, thanks for reporting. It should be caused by the Azure service instead of azurerm provider.  

I tried the same configuration on Portal and get the same error.  I personally suggest to open a support ticket on Portal.

For any further questions, please leave comments.
Thanks!

**Comment by manicminer** [comment] 2023-04-24 22:29
Hi @mpjtaylor, thanks for reporting this. As @ziyeqf mentioned, this is a service isue, most likely the region/location is not supported or there is some other upstream problem with this location. As this is not a provider issue, I'm going to close this one out for now and recommend that you raise an Azure support ticket for this issue. Thanks!

**Closed by manicminer** 2023-04-24 22:29 UTC
Labels: service/monitor, upstream/microsoft
