### ISSUE TITLE
Cannot set capabilities on Cosmos account

### ISSUE THREAD

**Issue by sstone1** [hashicorp/terraform-provider-azurerm#19192] opened 2022-11-08 13:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.5

### AzureRM Provider Version

3.23.0

### Affected Resource(s)/Data Source(s)

azurerm_cosmosdb_account

### Terraform Configuration Files

```hcl
resource "azurerm_cosmosdb_account" "db" {
  name                = "tfex-cosmos-db-${random_integer.ri.result}"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  offer_type          = "Standard"
  kind                = "MongoDB"

  enable_automatic_failover = true

  capabilities {
    name = "EnableAggregationPipeline"
  }

  capabilities {
    name = "mongoEnableDocLevelTTL"
  }

  capabilities {
    name = "MongoDBv3.4"
  }

  capabilities {
    name = "EnableMongo"
  }

  capabilities {
    name = "EnableUniqueCompoundNestedDocs"
  }
}
```

### Debug Output/Panic Output

```shell
Error: expected capabilities.1.name to be one of [EnableAggregationPipeline EnableCassandra EnableGremlin EnableTable EnableServerless EnableMongo MongoDBv3.4 mongoEnableDocLevelTTL DisableRateLimitingResponses AllowSelfServeUpgradeToMongo36], got EnableUniqueCompoundNestedDocs
```

### Expected Behaviour

I should be able to enable the capability EnableUniqueCompoundNestedDocs as per https://learn.microsoft.com/en-us/azure/cosmos-db/mongodb/how-to-configure-capabilities#available-capabilities

### Actual Behaviour

I cannot enable the capability EnableUniqueCompoundNestedDocs as per https://learn.microsoft.com/en-us/azure/cosmos-db/mongodb/how-to-configure-capabilities#available-capabilities

### Steps to Reproduce

terraform plan

**Comment by CorrenSoft** [comment] 2022-11-11 17:54
@sstone1 I've created a PR to add the requested capability; however, it seems not to been properly working yet since I am getting a rejection from Azure, even using AZ CLI:
`(BadRequest) Invalid capability EnableUniqueCompoundNestedDocs.`

If you know something else that is not included is the Docs and can help me to unblock this, please let me know. Otherwise, I will retry later.

**Comment by sstone1** [comment] 2022-11-14 10:18
@CorrenSoft I have just checked in the Azure console and I cannot see a way to turn this on - it doesn't show up in the list there. I am wondering if this is a docs issue. I will raise an Azure support ticket and ask Microsoft if the option actually exists or not! Thanks for taking a look.

**Comment by CorrenSoft** [comment] 2022-11-16 20:06
I forgot to link the issue that I raised myself until was too late.
It is a confirmed bug, they suggested opening a support ticket if you have rush to implement this functionality.

**Comment by favoretti** [comment] 2022-11-20 10:33
Reached out to my MSFT contacts to see if this might be an easy fix on their side.

**Comment by CorrenSoft** [comment] 2022-12-07 17:18
Just for awareness, this capability is back in the Docs but still not working :(

**Comment by favoretti** [comment] 2022-12-07 17:39
Sorry, I thought I posted MSFT's reply...
```
Hi Vladimir,
 
Nice to meet you over email. Regarding the capability "EnableUniqueCompoundNestedDocs" in the Mongo API- this was a miss on our part. We documented this feature ahead of its release and the docs were pushed out too quickly. We've pulled the docs and will re-introduce them when "EnableUniqueCompoundNestedDocs" becomes available in a few months. BTW- I'm not seeing it in the Azure Portal but let me know if I'm mistaken. Sorry for the confusion and I hope this clears it up.
 
Thanks,
```

This reply was dated 22 November 2022, so I wouldn't hold my breath just yet for the actual implementation.

**Comment by xaviergxf** [comment] 2023-02-01 12:11
Other capabilities such as EnableMongoRetryableWrites do not work as well.

**Comment by CorrenSoft** [comment] 2023-02-01 13:49
> Other capabilities such as EnableMongoRetryableWrites do not work as well.

That was also added to the related PR, which was already merged and should be available in the next release.

**Comment by truonghongtrieu** [comment] 2023-10-31 05:39
I think this issue has been resolved.
I had the issue with v3.6, my DB account now has the `EnableUniqueCompoundNestedDocs` capabilities after upgrading Terraform to v3.78 (https://github.com/hashicorp/terraform-provider-azurerm/blob/v3.78.0/CHANGELOG.md)

**Closed** 2023-11-19 11:43 UTC
Labels: bug, service/cosmosdb, upstream/microsoft, v/3.x
