### ISSUE TITLE
azurerm_function_app_function doesn't upload files

### ISSUE THREAD

**Issue by YoavbhGit** [hashicorp/terraform-provider-azurerm#20984] opened 2023-03-16 13:19 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Hello,

### Terraform Version

1.3.7

### AzureRM Provider Version

3.47.0

### Affected Resource(s)/Data Source(s)

azurerm_function_app_function

### Terraform Configuration Files

```hcl
provider "azurerm" {
  subscription_id = var.subscription_id
  features {
  }
}

variable "azurerm_resource_group" {
  type = string
  description = "Enter the target Azure Resource Group"
  validation {
    condition = can(regex("^[\\w\\(\\)\\-\\.]{0,89}[^\\.!#$%^&*]$", var.azurerm_resource_group))
    error_message = "An Azure resource group name must be Between 1 and 90 characters long, contain Alphanumerics, underscores, parentheses, hyphens, periods and can't end with period."
  }
}

variable "subscription_id" {
  type = string
  description = "Enter the target Azure Subscription ID"
  validation {
    condition = can(regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$", var.subscription_id))
    error_message = "Make sure that this is a vaild subscrition id."
  }
}

variable "timezone" {
  type = string
  description = "Select the desired timezone for all deployed instances"
}

variable "region" {
  type = string
  description = "Enter the target region for all regional resources"
  validation {
    condition = can(regex("^(?:\\b\\w+\\b[\\s\\r\\n]*){1,3}$", var.region))
    error_message = "Must consist of lowercase or Upper letters (a-zA-Z), numbers, and hyphens."
  }
}
variable "deployment_name" {
  type = string
  description = "Enter a deployment identifier. This identifier will be a prefix for all deployed resources"
  validation {
    condition = can(regex("^[a-z][-a-z0-9]*[a-z0-9]$", var.deployment_name))
    error_message = "Must consist of lowercase letters (a-z), numbers, and hyphens."
  }
}

resource "azurerm_service_plan" "termination_service_plan" {
  name = "${var.deployment_name}-termination-service-plan"
  resource_group_name = var.azurerm_resource_group
  location = var.region
  os_type = "Linux"
  sku_name = "Y1"
}

resource "azurerm_storage_account" "termination_function_app_storage" {
  name                     = "${var.deployment_name}sa"
  resource_group_name = var.azurerm_resource_group
  location = var.region
  account_tier             = "Standard"
  account_replication_type = "LRS"
}
resource "azurerm_linux_function_app" "termination_function_app" {
  name = "${var.deployment_name}-termination-function-app"
  resource_group_name = var.azurerm_resource_group
  location = var.region
  service_plan_id = azurerm_service_plan.termination_service_plan.id
  storage_account_name = azurerm_storage_account.termination_function_app_storage.name
  storage_account_access_key = azurerm_storage_account.termination_function_app_storage.primary_access_key
  site_config {
    application_stack {
      python_version = "3.10"
    }
  }
}

resource "azurerm_function_app_function" "termination_function_app_function" {
  name = "${var.deployment_name}-termination-function-app-function"
  function_app_id = azurerm_linux_function_app.termination_function_app.id
  language = "Python"
  file {
    name = "main.py"
    content = file("main.py")
  } 
  file {
    name = "requirements.txt"
    content = file("requirements.txt")
  }
  config_json = jsonencode({
    "bindings" = [
      {
        "authLevel" = "function"
        "direction" = "in"
        "methods" = [
          "get", 
          "post"
        ]
        "name" = "req"
        "type" = "httpTrigger"
      }, 
      {
        "direction" = "out"
        "name" = "$return"
        "type" = "http"
      }
    ]
  })
  
}
```

### Debug Output/Panic Output

```shell
The terrafrom works fine but looks like the resources are broken.
```

### Expected Behaviour

Files appear inside the function "Code + Test".

### Actual Behaviour

In the "Code + Test" tab of the function in my function app there are no files.

### Steps to Reproduce

just us the same code i provided and try to upload a main.py and requirements.txt in the file section of the azurerm_function_app_function resource.

**Comment by rcskosir** [comment] 2023-07-18 15:48
Thanks for taking the time to submit this issue. It looks like this is a duplicate of #20852. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of #20852.

**Closed by rcskosir** 2023-07-18 15:48 UTC
Labels: bug, duplicate, service/functions
