### ISSUE TITLE
State Not Always Saved When It Should Be

### ISSUE THREAD

**Issue by ekristen** [hashicorp/terraform-provider-azurerm#22862] opened 2023-08-08 14:24 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.1

### AzureRM Provider Version

3.68.0

### Affected Resource(s)/Data Source(s)

azurerm_*

### Terraform Configuration Files

```hcl
--
```

### Debug Output/Panic Output

```shell
I fully acknowledge that the Azure SDK is terrible and so is the API. 

I'm beyond frustrated with this provider and I know a lot of it has to do with Azure itself, but the provider should be helping more.

For example, yesterday, azure functions returned status of 'running' which the provider took as an error, and did not save state, so all subsequent runs it kept trying to create, and then would fail because the resource already existed. It should 100% have saved something when it got the initial response back.

Principally the provider often doesn't save state when it should which is the whole point of terraform. 


I have provided a search and at least one issue as a reference, I'll continue adding more as I find them.

Azure is a predictable resource ID system but this provider does not always save state when it should, to the point that I hit it almost weekly if not daily, and that's because I run a LOT of terraform. I've hit this on at least 5-10 different resource types.

This provider should **ABSOLUTELY** stub the resource state on any partial success or partial failure simply because it should, but also because of the predictable resource ID system that Azure employs. On subsequent plans the read then will start to stub the state and help determine what changes need to be made.
```

### Expected Behaviour

The provider should always save state when there is a partial success or error that occurs with the API, especially because Azure uses predictable ID naming.

### Actual Behaviour

The provider often does not save state when it should.

### Steps to Reproduce

--

### References

- https://github.com/hashicorp/terraform-provider-azurerm/issues/22714
- https://github.com/hashicorp/terraform-provider-azurerm/issues?q=is%3Aissue+is%3Aopen+%22already+exists+-+to+be+managed%22

**Comment by tombuildsstuff** [comment] 2023-08-11 09:22
hi @ekristen

Thanks for opening this issue.

As mentioned previously in [this comment/issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/17565#issuecomment-1187663325) - ultimately these are fundamental limitations of the Azure API and not something we can trivially resolve within the Provider.

Unfortunately there's no source for the possible errors that an API can return (with/without any information about which are recoverable) - and unfortunately the API behaviour can differ per _subscription_ and subscription type (e.g. DevTest) and billing account type (EA vs not), in addition to the SKU being used in a given request payload - ultimately there isn't a programmatic manner for us to infer when a resource is recoverable verses when it's not.

At first glance automatically retrying all `RetryableError`'s may seem obvious - but unfortunately in some cases doing so can _considerably_ worsen an outage, for example the Virtual Network Gateway resource supports Connections, performing any action on the Virtual Network Gateway can trigger a reset of those connections. If we're retrying that automatically, we'll be unintentionally causing _unobvious_ reliability issues into customers environments - with all that's visible from the Terraform CLI being "creating/updating X".

I appreciate this situation isn't ideal, and as you've mentioned there's a number of fundamental limitations which are play here. Whilst we're moving away from the Azure SDK in favour of [our own SDK which treats Resource IDs as first-class citizens](https://github.com/hashicorp/go-azure-sdk) - which means that we're defining what the Resource IDs are on Terraform's side (which in time will also solve some other issues) - the limiting factor of the API behaves.

From our side, unfortunately this isn't something we plan to implement at this point in time because of the limitations of the API:

1. The `provisioningState` of a resource can be `Failed` but the resource can be perfectly operational (VMSS, AKS, App Service, HDInsight ..) - and so _should not be marked as tainted_. For example, consider where a VMSS doesn't have any remaining quota to be able to scale - or the `sharedKey` for a VPN connection is incorrect.
2. The `provisioningState` of a resource can be `Failed` which means this Resource will _never_ recover (period) or without human intervention (for example, where the cluster creation/update fails for HDInsights/Kusto etc).
3. In some API's, resources that fail during creation are automatically removed. In others, they're not - which in combination with the above means that we have absolutely no means of knowing programatically when a resource will recover and when it won't. There are going to be means of doing that, but those will _always_ be unique to the configuration which is being deployed.

In addition, automatically tracking the resource from the start of the Create method _could_ make sense, unfortunately many Create methods are currently shared with the Update use-case due to the way the Azure API behaves (where the same API is used for both, although we are working through splitting those). As such doing this would mean that we'd end up tainting the resource during an _update_ - which (combined with the issues above) and given some users opt to run Terraform via `--auto-approve` / without viewing the plan would cause serious issues for users in those environments.

I appreciate this is frustrating, but ultimately the limiting factor here is the Azure API - whilst it appears at first glance that each API has a common set of status codes and messages we retry on, unfortunately the implementation details vary wildly.

This means that each Endpoint, API Version, Region, Subscription and Environment can behave differently - and in-fact we have many cases within the Provider where we have to handle those differences ([example](https://github.com/hashicorp/terraform-provider-azurerm/blob/8b1d29dc60814b4ef477566cf42638fcdf02729b/internal/services/containers/kubernetes_addons.go#L34-L47), where Azure China and Azure US Government behave fundamentally differently) - but those limitations that we're working around are now documented by the AKS Team, so we can work to them.

The fundamental difference is that the error codes aren't properly standardised ([for example, see this list of extra status codes that APIs can return, when there's supposed to be 4 possible values](https://github.com/hashicorp/go-azure-sdk/blob/f0fed548b7662d950af6ad54c466db9c53254a51/sdk/client/resourcemanager/poller_lro.go#L157-L188)). In particular for something like AKS/HDInsights/Kusto which deploys an ARM Template behind the scenes, whilst the API may behave one way in Azure Public/West Europe/API Version X-Y-Z - that's not the same in Azure US Government or even Azure Public in South East Asia.

As such, whilst I appreciate your enthusiasm for getting this issue resolved - ultimately we're fundamentally limited on the lack of amount of information available here.

At this point in time we support nearly 1000 different resources using a myriad of different API versions - whilst Microsoft have made some strides towards making the request/response payloads uniform - the API behaviour still differs substantially (and in undocumented manners).

Since this isn't something we're able to fix given the constraints of the Azure Platform - unfortunately I'm going to have to close this out as working as intended. The reason for this is that an API failure can mean radically different things in different environments - so whilst one approach (retrying) might be perfectly fine for some users, in others it could be a far larger issue (for example a regulated environment).

As such whilst I'd like to thank you for opening this issue, and I appreciate the enthusiasm around getting this issue resolved - unfortunately I'm going to close this issue for the moment as not planned. However should Microsoft make the information we need available in a programatic manner then we can look into doing something with this at some point in the future.

Thanks!

**Closed by tombuildsstuff** 2023-08-11 09:22 UTC
Labels: v/3.x

**Comment by ekristen** [comment] 2023-08-11 14:30
Hi @tombuildsstuff. I appreciate you taking the time to go into that much depth.

Basically the answer is azure is terrible which I've known for a very long time now. If I wasn't required to use Azure, I wouldn't. 

I've been keeping an eye on all the internal SDK work as Azure keeps on decided to change their go sdk and making it less complete. 🤦 

My biggest pain point is the state save thing, which sounds like you are making strives to address with the internal sdk with making the id a more first class citizen so I'm looking forward to this.

I have tooling internally that does all my runs and it's very hard to recover when it actually creates something but doesn't save state then on next run throws an error about needing to be imported.

Is there light at the end of the tunnel for the state stuff with the ResourceID and an estimated timeline or is it more it'll get done at some point as things progress naturally.

**Comment by tombuildsstuff** [comment] 2023-08-15 09:12
@ekristen 

> My biggest pain point is the state save thing, which sounds like you are making strives to address with the internal sdk with making the id a more first class citizen so I'm looking forward to this.

To clarify, the design of the Azure API means it's not possible to us to determine whether a resource is healthy (and will recover/requires human intervention) or is unhealthy (and will kick around indefinitely until it's manually cleaned up / fixed) or is unhealthly (and will be cleaned up automatically).

As such the "state save" problem that you're referring to is a fundamental issue with the Azure Platform and isn't something the Provider can fix at this point in time.

Should Microsoft surface the information we need, then we can take a look into doing so, but (to be frank) I think that's pretty unlikely given how many places that'd need to be made (across every Resource Provider across every API Version). Unfortunately we can't only do this for a subset of resources either [due to the limitations defined above](https://github.com/hashicorp/terraform-provider-azurerm/issues/22862#issuecomment-1674447963) - so the fundamental limitation needs to be fixed in order for us to do something about this.

Whilst I appreciate that this situation isn't ideal and we'd like to fix this - but ultimately the Azure API is the limiting factor here. The only way that we could discover that information today would be to sink a _considerable_ amount of time into researching/tracking each API's failure mode in each environment with each subscription type on an ongoing basis, which would be a huge drag on resources to both discover and then maintain.

Given there's many consumers of the Azure APIs, to be honest it'd make more sense for the Service Teams/ARM Team to publish that information in some (programatically) consumable manner so that consumers can determine how to proceed - however without that I don't see a means of implementing this functionality any time soon.

We're open to re-evaluating this should that information become available, but to be honest I don't see how we can support that functionality without impacting other areas of the provider (such as the development of new resources/fields etc) given the amount of time that would take to decipher.

Thanks!

**Comment by ekristen** [comment] 2023-08-15 18:08
@tombuildsstuff I appreciate all the detailed explanations. 

As a reluctant user of the Azure APIs along with the use of terraform for Azure I fully understand the pain. The API is wholly inconsistent and frustrating. 

If I understand you correctly, the problem is there's no global way to determine if a resource has been created when error conditions happen?

What I'm struggling with is why not stub the resource id into state even upon error? Or maybe add a provider feature to do this as Opt in? 

That way on subsequent runs it won't fail hard with resource exists, you must import first.

From my perspective if an error occurs and only the resource id is put in state, on the next plan you'd get a delta of what doesn't match and state will get updated if calls are successful. 

If the resource ID is in state and the resource doesn't exist, it'll just want to create thinking the remote deleted it.

I don't see a downside?

I appreciate the discussion.
