### ISSUE TITLE
public_network_access_enabled does not really work in azurerm_synapse_workspace

### ISSUE THREAD

**Issue by chaoqi** [hashicorp/terraform-provider-azurerm#14712] opened 2021-12-22 15:13 UTC
Hey Everyone, I have problems using `public_network_access_enabled`  to create Azure Synapse Workspace via Terraform. it seems like this parameter only works for the first run, afterwards, we are not able to change this parameter anymore.

besides this, this parameter acts very differently with the manual behavior on azure portal, for example, if this parameter is disabled, Terraform will not allow any firewall rules to be added in the workspace, but in the azure portal, you can have the possibilities to have the firewall rules being added in the workspace while public network access is disabled, even though in this case, the firewall rules will not be applied.

Do you guys also have the same issues? Can you also please explain why once this `public_network_access_enabled` is set, we can NOT change it anymore?

Thank you very much for the support and look forward to an answer.
 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform Version: 1.0.11, azurerm version: 2.88.1, have also tested in 2.90.0

### Affected Resource(s)

* `azurerm_synapse_workspace`

### Terraform Configuration Files

change from
```hcl
public_network_access_enabled   =  true
```
to 
```hcl
public_network_access_enabled   =  false
```

### Expected Behaviour
Expected; after deployment, public network access for deployed Synapse will be disabled

### Actual Behaviour
Nothing changes, public network access is still enabled, terraform apply runs without any problems

change from
```hcl
public_network_access_enabled   =  false
```
to 
```hcl
public_network_access_enabled   =  true
```

### Expected Behaviour
Expected; after deployment, public network access for deployed Synapse will be enabled

### Actual Behaviour
Terraform apply failed with error:

Message: Unable to create or modify firewall rules when public
| network interface for the Synapse Workspace is disabled. To
| manage firewall rules, please enable the public network
| access.

### Steps to Reproduce

1. run first time, with `public_network_access_enabled   =  true`, then change its value from true to false.
2. run first time, with `public_network_access_enabled   =  false`, then change its value from false to true.

### Important Factoids

in our case, we also use `azurerm_synapse_firewall_rule` to add some basic IP firewall rules for the Synapse workspace.

### References

* [PR13817](https://github.com/hashicorp/terraform-provider-azurerm/pull/13817/files)

**Comment by tombuildsstuff** [comment] 2021-12-23 10:28
hi @chaoqi 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Closed by tombuildsstuff** 2021-12-23 10:28 UTC
Labels: question

**Comment by ekhaydarov** [comment] 2022-01-18 09:25
Im sorry is this not a bug?

This exact same parameter `public_network_access_enabled` fully bricks the databricks providers that are using service principals for auth. It also forces a replacement on these resources because its trying to enforce this "optional" parameter
```
azurerm_storage_data_lake_gen2_path
azurerm_monitor_diagnostic_setting
azurerm_databricks_workspace
```
Would you be happy to reopen this issue? Would we need to open another issue to describe the buggy behaviour of this parameter?
