### ISSUE TITLE
invalid character when creating an 'azurerm_aadb2c_directory' resource

### ISSUE THREAD

**Issue by CyberGremlin** [hashicorp/terraform-provider-azurerm#15151] opened 2022-01-27 16:39 UTC
When trying to create a B2C Tenant. We are getting the following error:

_Error: performing Create: pollingTrackerBase#updateRawBody: failed to unmarshal response body: StatusCode=0 -- Original Error: invalid character 'Y' looking for beginning of value
│
│   with azurerm_aadb2c_directory.b2c_tenant,
│   on b2c_tenant.tf line 11, in resource "azurerm_aadb2c_directory" "b2c_tenant":
│   11: resource "azurerm_aadb2c_directory" "b2c_tenant" {
│
│ performing Create: pollingTrackerBase#updateRawBody: failed to unmarshal response body: StatusCode=0 -- Original Error: invalid character 'Y' looking for beginning of value_

Our code is as follows:
```
resource "azurerm_aadb2c_directory" "b2c_tenant" {
  country_code            = "US"
  data_residency_location = "United States"
  display_name            = "cgexample-b2c-tenant"
  domain_name             = "cgexampleb2ctenant.onmicrosoft.com"
  resource_group_name     = "rgb2c"
  sku_name                = "PremiumP1"
}
```

**Comment by tombuildsstuff** [comment] 2022-01-27 16:55
hi @CyberGremlin 

Thanks for opening this issue.

Taking a look through this appears to be a duplicate of #14941 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #14941 for updates?

Thanks!

**Closed by tombuildsstuff** 2022-01-27 16:55 UTC
