### ISSUE TITLE
Support for network_access_policy in azurerm_linux_virtual_machine

### ISSUE THREAD

**Issue by ChechuJA** [hashicorp/terraform-provider-azurerm#15568] opened 2022-02-23 09:21 UTC
Hi, If possible I would like you to add the network_access_policy function to the os_disk

### Description

Hi, If possible I would like you to add the network_access_policy function to the os_disk of azurerm_linux_virtual_machine and azurerm_windows_virtual_machine because on these resources you can't attach an OS disk.

The azurerm_managed_disk resource does have the function network_access_policy - Policy for accessing the disk via network. Allowed values are AllowAll, AllowPrivate, and DenyAll.

### New or Affected Resource(s)

* azurerm_linux_virtual_machine
* azurerm_windows_virtual_machine

### References

* #0000

**Comment by tombuildsstuff** [comment] 2022-02-23 18:29
hi @ChechuJA 

Thanks for opening this issue.

Taking a look through this appears to be a duplicate of #14756 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #14756 for updates?

Thanks!

**Closed by tombuildsstuff** 2022-02-23 18:29 UTC
