### ISSUE TITLE
Support for vnet_route_all_enabled on azurerm_function_app

### ISSUE THREAD

**Issue by iugastefan922** [hashicorp/terraform-provider-azurerm#13391] opened 2021-09-17 00:17 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As the WEBSITE_VNET_ROUTE_ALL application setting is overrident by vnetRouteAll configuration in the vnet integration menu, it would be helpful to have it available in the azurerm_function_app: https://docs.microsoft.com/en-us/azure/app-service/web-sites-integrate-with-vnet

Worth mentioning that the azurerm_app_service already has it available: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service

### New or Affected Resource(s)

azurerm_function_app

### Potential Terraform Configuration

```hcl
resource "azurerm_function_app" "example" {
  name                       = "test-azure-functions"
  location                   = azurerm_resource_group.example.location
  resource_group_name        = azurerm_resource_group.example.name
  app_service_plan_id        = azurerm_app_service_plan.example.id
  storage_account_name       = azurerm_storage_account.example.name
  storage_account_access_key = azurerm_storage_account.example.primary_access_key
  os_type                    = "linux"
  site_config  { 
                        
    }
}```

**Comment by aristosvo** [comment] 2021-09-17 12:40
@iugastefan922 This seems a duplicate of #13259

**Comment by jackofallops** [comment] 2021-09-20 05:10
Closing in favour of earlier issue, please subscribe to that for updates.

**Closed by jackofallops** 2021-09-20 05:10 UTC
