### ISSUE TITLE
 Cannnot register providers: Microsoft.StoragePool with azurerm provider set to 2.86.0

### ISSUE THREAD

**Issue by Remi-Faydide** [hashicorp/terraform-provider-azurerm#14303] opened 2021-11-23 12:42 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

- terraform version: `1.0.5`
- azurerm version: `2.86.0`

### Affected Resource(s)

* `azurerm_XXXXX`

### Terraform Configuration Files

My provider configuration was set as below

```
terraform {
  required_version = "~> 1.0.0"

  backend "azurerm" {
    resource_group_name  = "{rg-name}"
    storage_account_name = "{storage-account-name}"
    container_name       = "tfstates"
    key                  = "{key-name}.tfstate"
  }

  required_providers {
    azurerm = {
      version = ">= 2.76.0"
    }
  }
}
```

### Actual Behaviour

My provider configuration was set as below

```
    azurerm = {
      version = ">= 2.76.0"
    }
```

When my pipeline ran, it faced the following issue

```
╷
│ Error: Error ensuring Resource Providers are registered.
│ 
│ Terraform automatically attempts to register the Resource Providers it supports to
│ ensure it's able to provision resources.
│ 
│ If you don't have permission to register Resource Providers you may wish to use the
│ "skip_provider_registration" flag in the Provider block to disable this functionality.
│ 
│ Please note that if you opt out of Resource Provider Registration and Terraform tries
│ to provision a resource from a Resource Provider which is unregistered, then the errors
│ may appear misleading - for example:
│ 
│ > API version 2019-XX-XX was not found for Microsoft.Foo
│ 
│ Could indicate either that the Resource Provider "Microsoft.Foo" requires registration,
│ but this could also indicate that this Azure Region doesn't support this API version.
│ 
│ More information on the "skip_provider_registration" flag can be found here:
│ https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#skip_provider_registration
│ 
│ Original Error: Cannnot register providers: Microsoft.StoragePool. Errors were: Cannot register provider Microsoft.StoragePool with Azure Resource Manager: resources.ProvidersClient#Register: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '{sp-object-id}' with object id '{sp-object-id}' does not have authorization to perform action 'Microsoft.StoragePool/register/action' over scope '/subscriptions/{subscription-id' or the scope is invalid. If access was recently granted, please refresh your credentials.".
│ 
│   with provider["registry.terraform.io/hashicorp/azurerm"].hub,
│   on provider.tf line 29, in provider "azurerm":
│   29: provider "azurerm" {
```

If I set the constraint version to '`2.85.0`' it does not fail anymore

I found the following [Azure documentation](https://docs.microsoft.com/en-us/azure/azure-resource-manager/troubleshooting/error-register-resource-provider?tabs=azure-cli) but it does not help me so much to solve the issue

### Steps to Reproduce

1. Set the 'azurerm' constraint version as '`~> 2.86.0`'
2. perform the following commands
  1. `terraform init`
  2. `terraform plan`

### References

* #0000

**Comment by aristosvo** [comment] 2021-11-23 13:19
Hi @Remi-Faydide! Thanks for opening this issue.

Have you read the information in the [error message about the provider registration](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#skip_provider_registration) yet? It should clarify how to solve it. 

By default, Terraform will attempt to register any Resource Providers that it supports in Azure, even if they're not used in your configurations to be able to display more helpful error messages. If you're running in an environment with restricted permissions, or wish to manage Resource Provider Registration outside of Terraform you may wish to disable this flag; however, please note that the error messages returned from Azure may be confusing as a result (example: API version 2019-01-01 was not found for Microsoft.Foo).

Since this is working as intended I'm going to close this issue for the moment - but please let us know if disabling this functionality doesn't work for you and we'll take another look.

**Closed by aristosvo** 2021-11-23 13:19 UTC

**Comment by Remi-Faydide** [comment] 2021-11-23 15:38
Hello @aristosvo 
Thank you for your reply.

However I do not understand why you're saying that it is working as expected since the issue is not occuring when I use a constraint version prior to 2.86.0.

If my environment was running with restricted permissions, wouldn't I have the issue with the prior versions ?

Also what does this mean exactly ?
Because I certainly have restricted permissions in my environment but what are the permissions needed and on which scope ?

Thank you for your reply

**Comment by daviddob** [comment] 2021-11-23 16:17
Id also like some additional clarification on what permissions/scopes are required with the 2.86.0 upgrade. I have tried assigning `Microsoft.StoragePool/register/action` on the subscription as it is the permission and scope called out in the error, however the error still persists with the same message.

**Comment by bigbrozer** [comment] 2021-11-23 16:20
I can reproduce similar error only when using provider version >= 2.86, reverting back to 2.85 is okay. The account running terraform has the permission to register new providers at subs level.

**Comment by link-webcreations** [comment] 2021-11-23 16:21
I confirm the issue (working fine in 2.85.x, it seems that there is a breaking change (or a bug?) in 2.86.x.

**Comment by bigbrozer** [comment] 2021-11-23 16:28
> I can reproduce similar error only when using provider version >= 2.86, reverting back to 2.85 is okay. The account running terraform has the permission to register new providers at subs level.

My bad... I'm using a second provider with an account which does not have the same permission. The error is correct, the StoragePool provider is not registered in the target subs and the SPN does not have needed permission. Sorry for the noise...

**Comment by aristosvo** [comment] 2021-11-23 17:00
> Hello @aristosvo 
> 
> Thank you for your reply.
> 
> 
> 
> However I do not understand why you're saying that it is working as expected since the issue is not occuring when I use a constraint version prior to 2.86.0.
> 
> 
> 
> If my environment was running with restricted permissions, wouldn't I have the issue with the prior versions ?
> 
> 
> 
> Also what does this mean exactly ?
> 
> Because I certainly have restricted permissions in my environment but what are the permissions needed and on which scope ?
> 
> 
> 
> Thank you for your reply

@Remi-Faydide The previous version upgrades didn't contain new providers, or not one that was disabled on your subscription. Or, you used a different SP with the right permissions.

By not opting out of registering new providers, you have this issue now and then when not giving the permissions to register them.

Permissions to register a resource provider are on Subscription level. The Subscription Contributor or Owner role is required for this operation.

**Comment by daviddob** [comment] 2021-11-23 17:40
Following up - it looks like adding the above permission in my previous comment to the subscription via a custom role did resolve the issue. It just took >15mins to propagate and start working properly for our users.
