### ISSUE TITLE
v3.0.1: azurerm_key_vault: Cannot read the ressource with KeyVault: keyvault.BaseClient#GetCertificateContacts

### ISSUE THREAD

**Issue by uncycler** [hashicorp/terraform-provider-azurerm#16052] opened 2022-03-25 10:34 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.1.7
azurerm v3.0.1

### Affected Resource(s)

* `azurerm_key_vault`

### Expected Behaviour

No error

### Actual Behaviour

Cannot read the ressource with `KeyVault: keyvault.BaseClient#GetCertificateContacts: Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded

### Steps to Reproduce

1. Create a keyvault with v2:
```
resource "azurerm_key_vault" "mykeyvault" {
  name                = "mykeyvault"
  sku_name            = "standard"
  location            = "myloc"
  resource_group_name = "myrg"
  tenant_id           = "mytenant"
  purge_protection_enabled = true
}
```
2. with v3, do a terraform plan

### Important Factoids

Since v3, azurerm is trying to fetch "contact" from KeyVault and for some reason, the access is timing out. I've tried adding ManagedContacts permission but no luck.

Using same credentials, I can access the API without isuse.
```
az rest --method GET --uri "https://mykeyvault.vault.azure.net/certificates/contacts?api-version=7.1" --resource "https://vault.azure.net"
Not Found({"error":{"code":"ContactsNotFound","message":"Contacts not found"}})
```

* #0000

**Comment by noiano** [comment] 2022-03-25 11:00
I have a similar issue. Simply referencing a certificate in a key vault causes the plan to fail

```yaml
`data "azurerm_key_vault" "keyVault" {
  name                = "XXX"
  resource_group_name = "YYY"
}

# Get ID for latest certificate version in KV
data "azurerm_key_vault_secret" "certificate" {
  name         = "ZZZ"
  key_vault_id = data.azurerm_key_vault.keyVault.id
}
```

The plan command fails (after a long while) with the following error:

```bash

╷
│ Error: making Read request on Azure KeyVault Secret <name redacted>: autorest/Client#Do: Preparing request failed: StatusCode=0 -- Original Error: authorizer was not an auth.CachedAuthorizer for https://vault.azure.net
│ 
│   with data.azurerm_key_vault_secret.certificate,
│   on subscription.tf line 13, in data "azurerm_key_vault_secret" "certificate":
│   13: data "azurerm_key_vault_secret" "certificate" {
│ 
╵
Releasing state lock. This may take a few moments...
```

**Comment by kovaliovsg** [comment] 2022-03-25 11:24
I have these both issues as well. Had to roll back to provider 2.99.0

**Comment by cmendible** [comment] 2022-03-25 11:52
Just hit this one... 

Terraform 1.1.7
azurerm 3.0.1

**Comment by manicminer** [comment] 2022-03-25 14:22
Hi, thanks for reporting this. I'm looking at each report in this issue in turn and trying to reproduce across the authentication methods we support, however it would help greatly if anyone getting a timeout or "context deadline exceeded" error, were able to post a debug log (via gist) whilst this is happening.

You can do this by setting the `TF_LOG` environment variable to `debug`, for example with bash-compatibles:

```shellsession
TF_LOG=debug terraform apply
```

**Comment by SimonGasparKentico** [comment] 2022-03-25 14:40
I got another error
`Error: retrieving "contact" for KeyVault: autorest/Client#Do: Preparing request failed: StatusCode=0 -- Original Error: authorizer was not an auth.CachedAuthorizer for https://vault.azure.net`
I'm not sure if this is related to this problem or if the problem is on my side :)

**Comment by manicminer** [comment] 2022-03-25 15:01
@SimonGasparKentico, @noiano I believe I may have found an issue with Azure CLI authentication and Key Vault.

**Comment by manicminer** [comment] 2022-03-25 15:07
@djryanj If you wish to encrypt your log, please use the public key for the "terraform" Keybase user. Thanks!

**Comment by djryanj** [comment] 2022-03-25 15:12
@manicminer here you are: https://gist.github.com/djryanj/2a0f0b13e2eb9891af850a0b4fdacd69

**Comment by manicminer** [comment] 2022-03-25 15:54
@djryanj Many thanks, I'm having some trouble accessing that privkey at the moment - in the interest of expedience would you be able to re-encrypt with my [personal key](https://keyserver.ubuntu.com/pks/lookup?search=0xf91221961d5ce85cb25b7b0f6343ce10f70c3d21&fingerprint=on&op=index)?

**Comment by manicminer** [comment] 2022-03-25 16:09
@uncycler, @kovaliovsg, @cmendible, @nbjohnson Would you be able to share a debug log for when you're seeing the "context deadline exceeded" for a Key Vault related resource? Thanks!

**Comment by djryanj** [comment] 2022-03-25 16:12
@manicminer glad you found the key, I promptly broke my terraform config after hitting this bug (developing something else, this was non-blocking for the moment) and also (like an idiot) deleted the debug log so couldn't reproduce quickly enough.

I am using Azure CLI authentication.

**Comment by cmendible** [comment] 2022-03-25 16:30
Sorry no logs since I reverted back.

I'm also using Azure CLI authentication

**Comment by eoly** [comment] 2022-03-25 17:08
@manicminer 

Here are my TF_DEBUG logs. I have the `context deadline exceeded` issue too.

Using Azure CLI auth.

https://gist.github.com/eoly/702d9e6da370cd946372bce3677db830

**Comment by derekwilliamsliquidx** [comment] 2022-03-25 19:44
I am hitting this error as well

Terraform version 1.1.6
Azure CLI Version 2.26.1
AzureRM Provider Version = 3.0.1

Reverting back to 2.99 corrected the issue.

**Comment by manicminer** [comment] 2022-03-25 20:49
@eoly Thanks for the logs, that's super helpful 👍 

Anyone else, please refrain from posting +1 comments and instead upvote the issue. Debug logs are always happily received!

**Comment by noiano** [comment] 2022-03-27 17:33
I'm actually using a service principal to authenticate all actions against my subscription ...

**Comment by nbjohnson** [comment] 2022-03-28 16:10
Even after upgrading to v3.0.2, I am still getting a similar, but not exactly the same error. I am attempting to do a data source lookup for a key vault secret. This works on versions < 3.0.0, but is now just broken. If there is a breaking change that I am missing that could be affecting this let me know, or is this a bug related to the other errors users are reporting?

```
:51:05.293Z [ERROR] vertex "module.storage_account[\"<storage account name>\"].azurerm_key_vault_key.this" error: keyvault.BaseClient#GetKey: Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded
:51:05.294Z [ERROR] vertex "module.storage_account[\"<storage account name>\"].azurerm_key_vault_key.this" error: keyvault.BaseClient#GetKey: Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded
:51:05.294Z [ERROR] vertex "module.storage_account.azurerm_key_vault_key.this (expand)" error: keyvault.BaseClient#GetKey: Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded
:53:35.590Z [ERROR] vertex "data.azurerm_key_vault_secret.lookups[\"<secret local var name>\"]" error: making Read request on Azure KeyVault Secret <secret name>: autorest/Client#Do: Preparing request failed: StatusCode=0 -- Original Error: failed to acquire MSAL token for <vault url>
:53:35.590Z [ERROR] vertex "data.azurerm_key_vault_secret.lookups" error: making Read request on Azure KeyVault Secret <secret name>: autorest/Client#Do: Preparing request failed: StatusCode=0 -- Original Error: failed to acquire MSAL token for <vault url>
:53:35.591Z [ERROR] vertex "data.azurerm_key_vault_secret.lookups (expand)" error: making Read request on Azure KeyVault Secret <secret name>: autorest/Client#Do: Preparing request failed: StatusCode=0 -- Original Error: failed to acquire MSAL token for <vault url>
```

For initial Azure auth I am using CLI

**Comment by djryanj** [comment] 2022-03-28 17:30
@nbjohnson - try doing an `az logout` and `az login`. I didn't see a `context deadline exceeded` like in your error but did get something related to failing to get an MSAL token this morning, and this fixed it. Note my error may not have been the same as yours, but it's worth a try.

**Comment by nbjohnson** [comment] 2022-03-28 19:15
@djryanj Thanks for the suggestion, but unfortunately that didn't fix my issue. Still keep getting `failed to acquire MSAL token` for at least key_vault_key creation and key_vault_secret data resource

**Comment by manicminer** [comment] 2022-03-29 11:37
@nbjohnson Thanks for the feedback. I've been unable to reproduce that error, which is related to a failure invoking az-cli to acquire an access token. I would suggest upgrading to the latest version of Azure CLI, and deleting your `~/.azure` directory before signing in again. I will look at ways we can improve the error reporting here.

**Comment by mark-strasser-nnl** [comment] 2022-04-11 22:06
With USGovernment environment, the [example key vault](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault) fails to get created or read from state, even with the latest versions of Terraform or azurerm.

```
│ Error: retrieving `contact` for KeyVault: keyvault.BaseClient#GetCertificateContacts: Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded
│
│   with azurerm_key_vault.example,
│   on main.tf line 15, in resource "azurerm_key_vault" "example":
│   15: resource "azurerm_key_vault" "example" {
```

See [relevant gist](https://gist.github.com/mark-strasser-nnl/d7c101226c57541d11664631bd9d1015).

Terraform versions: 

```
$ terraform version
Terraform v1.1.8
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v3.1.0
```

**Comment by bgrainger** [comment] 2022-04-12 20:34
I believe this issue may be related to `use_msal = true` (which is now on by default in azurerm >= 3.0).

## Works: v2.99 with `use_msal= false`

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "2.99"
    }
  }
}

provider "azurerm" {
  features {}

  use_msal = false
}

data "azurerm_client_config" "current" {}

resource "azurerm_resource_group" "this" {
  name     = "V299ADAL"
  location = "westus2"
}

resource "azurerm_key_vault" "this" {
  name                = "v299adal-kv"
  location            = resource.azurerm_resource_group.this.location
  resource_group_name = azurerm_resource_group.this.name
  tenant_id           = data.azurerm_client_config.current.tenant_id
  sku_name            = "standard"
}
```

Output:

```
azurerm_key_vault.this: Still creating... [2m30s elapsed]
azurerm_key_vault.this: Creation complete after 2m34s [id=/subscriptions/***/resourceGroups/V299ADAL/providers/Microsoft.KeyVault/vaults/v299adal-kv]
```

## Fails: v2.99 with `use_msal = true`

```
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "2.99"
    }
  }
}

provider "azurerm" {
  features {}

  use_msal = true
}

data "azurerm_client_config" "current" {}

resource "azurerm_resource_group" "this" {
  name     = "V299MSAL"
  location = "westus2"
}

resource "azurerm_key_vault" "this" {
  name                = "v299msal-kv"
  location            = resource.azurerm_resource_group.this.location
  resource_group_name = azurerm_resource_group.this.name
  tenant_id           = data.azurerm_client_config.current.tenant_id
  sku_name            = "standard"
}
```

Output:

```
azurerm_key_vault.this: Still creating... [7m30s elapsed]
╷
│ Error: retrieving `contact` for KeyVault: keyvault.BaseClient#GetCertificateContacts: Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded
│
│   with azurerm_key_vault.this,
│   on main.tf line 23, in resource "azurerm_key_vault" "this":
│   23: resource "azurerm_key_vault" "this" {
│
╵
```

FWIW, I'm not getting a failure to create this key_vault with azurerm 3.1.0. However, I wanted to paste my findings above since it seemed to be the exact same error message from the OP, and in case it provides a clue to where the problem may be.

**Comment by manicminer** [comment] 2022-04-14 21:03
There is a related issue #16291 which affects USGovernment users when managing Key Vaults (or any resource that uses the Key Vault API). This will be fixed in next week's release.

Is anyone here _**not**_ using the USGovernment cloud and experiencing a `context deadline exceeded` error when trying to manage or reference a Key Vault?

**Comment by xinity** [comment] 2022-04-18 09:20
@manicminer i do and i'm pretty sure i'm not the only one.

**Comment by mkemmerz** [comment] 2022-05-11 11:57
Any update on this? Same error with AzureRm 3.1 on our side.

**Closed** 2022-05-11 12:02 UTC
Labels: bug, service/key-vault, authentication

**Comment by mkemmerz** [comment] 2022-05-12 06:10
@tombuildsstuff thanks for the reply. We are having this issue on the global Azure cloud so maybe this issue doesn't really fit for me because it is only for the USGov Cloud. As we are using a Private Endpoint for the connection it seems more related to https://github.com/hashicorp/terraform-provider-azurerm/issues/9738

**Comment by AndyLonghurstHESA** [comment] 2022-05-16 14:54
Just come across this issue in v3.5.0

**Comment by kevinwedwards** [comment] 2022-06-08 16:18
We too are having this issue on AzureRM 3.7.  global azure cloud (non USGov).

**Comment by elongstreet88** [comment] 2022-06-27 21:59
Same, seems like our general performance of terraform/arm provider have drastically reduced lately and we are seeing the context deadline issues as well.
