### ISSUE TITLE
azurerm_site_recovery_replicated_vm tries to recreate every time due to inconsistent text upper/lowercase

### ISSUE THREAD

**Issue by cub10s1ty** [hashicorp/terraform-provider-azurerm#8416] opened 2020-09-10 08:18 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

0.12.24

### Affected Resource(s)

* `azurerm_site_recovery_replicated_vm`

### Terraform Configuration Files

```hcl
resource "azurerm_site_recovery_replicated_vm" "this" {
  name                                      = "${var.name}-site-recovery-replication"
  resource_group_name                       = local.subscription_context.business_continuity.resource_group.name
  recovery_vault_name                       = local.subscription_context.business_continuity.recovery_services_vaults[var.region].name
  source_recovery_fabric_name               = local.subscription_context.business_continuity.recovery_fabrics.primary[var.region].name
  source_vm_id                              = azurerm_windows_virtual_machine.this.id
  recovery_replication_policy_id            = local.subscription_context.business_continuity.site_recovery_policies.virtual_machines[var.region].id
  source_recovery_protection_container_name = local.subscription_context.business_continuity.protection_containers.primary[var.region].name

  target_resource_group_id                = local.subscription_context.business_continuity.recovery_resource_groups[var.region].id
  target_recovery_fabric_id               = local.subscription_context.business_continuity.recovery_fabrics.secondary[var.region].id
  target_recovery_protection_container_id = local.subscription_context.business_continuity.protection_containers.secondary[var.region].id

  managed_disk {
    disk_id                    = data.azurerm_managed_disk.os_disk.id
    staging_storage_account_id = local.subscription_context.business_continuity.storage_accounts.primary[var.region].id
    target_resource_group_id   = local.subscription_context.business_continuity.recovery_resource_groups[var.region].id
    target_disk_type           = var.use_premium_storage_for_os ? "Premium_LRS" : "StandardSSD_LRS"
    target_replica_disk_type   = var.use_premium_storage_for_os ? "Premium_LRS" : "StandardSSD_LRS"
  }

  dynamic "managed_disk" {
    for_each = { for disk in var.data_disks : disk.index => disk }
    content {
      disk_id                    = azurerm_managed_disk.data_disk[managed_disk.key].id
      staging_storage_account_id = local.subscription_context.business_continuity.storage_accounts.primary[var.region].id
      target_resource_group_id   = local.subscription_context.business_continuity.recovery_resource_groups[var.region].id
      target_disk_type           = managed_disk.value.use_premium_storage ? "Premium_LRS" : "StandardSSD_LRS"
      target_replica_disk_type   = managed_disk.value.use_premium_storage ? "Premium_LRS" : "StandardSSD_LRS"
    }
  }

  network_interface {
    source_network_interface_id = azurerm_network_interface.this.id
  }

  timeouts {
    create = "3h"
    update = "3h"
  }

  depends_on = [
    azurerm_backup_protected_vm.this
  ]
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

The plan should have shown no resources to change (idempotent) after queueing post-apply

### Actual Behavior

Terraform wants to destroy and re-create the resource due to text strings for IDs being stored in different (mixed) case. I am including the actual terraform plan here.

```hcl
# module.s122-cmm-windowsvm-12.module.base.azurerm_site_recovery_replicated_vm.this must be replaced
-/+ resource "azurerm_site_recovery_replicated_vm" "this" {
      ~ id                                        = "/subscriptions/<redacted>/resourceGroups/daz1eu-s122-sub-rg01/providers/Microsoft.RecoveryServices/vaults/daz1eu-s122-sub-bcdr01-rsv01/replicationFabrics/daz1eu-s122-sub-asrf01/replicationProtectionContainers/daz1eu-s122-sub-asrpc01/replicationProtectedItems/daz1eu-cmm12-site-recovery-replication" -> (known after apply)
      ~ managed_disk                              = [ # forces replacement
          + {
              + disk_id                    = "/subscriptions/<redacted>/resourceGroups/daz1eu-s122-cmm-rg01/providers/Microsoft.Compute/disks/daz1eu-cmm12-datadisk01"
              + staging_storage_account_id = "/subscriptions/<redacted>/resourceGroups/daz1eu-s122-sub-rg01/providers/Microsoft.Storage/storageAccounts/<redacted>"
              + target_disk_type           = "Premium_LRS"
              + target_replica_disk_type   = "Premium_LRS"
              + target_resource_group_id   = "/subscriptions/<redacted>/resourceGroups/daz2eu-s122-asr-rg01"
            },
          - {
              - disk_id                    = "/subscriptions/<redacted>/resourcegroups/daz1eu-s122-cmm-rg01/providers/microsoft.compute/disks/daz1eu-cmm12-datadisk01"
              - staging_storage_account_id = "/subscriptions/<redacted>/resourceGroups/daz1eu-s122-sub-rg01/providers/Microsoft.Storage/storageAccounts/<redacted>"
              - target_disk_type           = "Premium_LRS"
              - target_replica_disk_type   = "Premium_LRS"
              - target_resource_group_id   = "/subscriptions/<redacted>/resourceGroups/daz2eu-s122-asr-rg01"
            },
          - {
              - disk_id                    = "/subscriptions/<redacted>/resourcegroups/daz1eu-s122-cmm-rg01/providers/microsoft.compute/disks/daz1eu-cmm12-osdisk01"
              - staging_storage_account_id = "/subscriptions/<redacted>/resourceGroups/daz1eu-s122-sub-rg01/providers/Microsoft.Storage/storageAccounts/<redacted>"
              - target_disk_type           = "Premium_LRS"
              - target_replica_disk_type   = "Premium_LRS"
              - target_resource_group_id   = "/subscriptions/<redacted>/resourceGroups/daz2eu-s122-asr-rg01"
            },
            {
                disk_id                    = (known after apply)
                staging_storage_account_id = "/subscriptions/<redacted>/resourceGroups/daz1eu-s122-sub-rg01/providers/Microsoft.Storage/storageAccounts/<redacted>"
                target_disk_type           = "Premium_LRS"
                target_replica_disk_type   = "Premium_LRS"
                target_resource_group_id   = "/subscriptions/<redacted>/resourceGroups/daz2eu-s122-asr-rg01"
            },
        ]
        name                                      = "daz1eu-cmm12-site-recovery-replication"
      ~ recovery_replication_policy_id            = "/Subscriptions/<redacted>/resourceGroups/daz1eu-s122-sub-rg01/providers/Microsoft.RecoveryServices/vaults/daz1eu-s122-sub-bcdr01-rsv01/replicationPolicies/daz1eu-s122-sub-bcdr02-hourly" -> "/subscriptions/<redacted>/resourceGroups/daz1eu-s122-sub-rg01/providers/Microsoft.RecoveryServices/vaults/daz1eu-s122-sub-bcdr01-rsv01/replicationPolicies/daz1eu-s122-sub-bcdr02-hourly"
        recovery_vault_name                       = "daz1eu-s122-sub-bcdr01-rsv01"
        resource_group_name                       = "daz1eu-s122-sub-rg01"
        source_recovery_fabric_name               = "daz1eu-s122-sub-asrf01"
        source_recovery_protection_container_name = "daz1eu-s122-sub-asrpc01"
      ~ source_vm_id                              = "/subscriptions/<redacted>/resourcegroups/daz1eu-s122-cmm-rg01/providers/microsoft.compute/virtualmachines/daz1eu-cmm12" -> "/subscriptions/<redacted>/resourceGroups/daz1eu-s122-cmm-rg01/providers/Microsoft.Compute/virtualMachines/daz1eu-cmm12"
      ~ target_network_id                         = "/subscriptions/<redacted>/resourcegroups/daz1eu-s122-sub-rg01/providers/microsoft.network/virtualnetworks/daz2eu-s122-sub-vnet01" -> (known after apply)
      ~ target_recovery_fabric_id                 = "/Subscriptions/<redacted>/resourceGroups/daz1eu-s122-sub-rg01/providers/Microsoft.RecoveryServices/vaults/daz1eu-s122-sub-bcdr01-rsv01/replicationFabrics/daz1eu-s122-sub-asrf02" -> "/subscriptions/<redacted>/resourceGroups/daz1eu-s122-sub-rg01/providers/Microsoft.RecoveryServices/vaults/daz1eu-s122-sub-bcdr01-rsv01/replicationFabrics/daz1eu-s122-sub-asrf02"
      ~ target_recovery_protection_container_id   = "/Subscriptions/<redacted>/resourceGroups/daz1eu-s122-sub-rg01/providers/Microsoft.RecoveryServices/vaults/daz1eu-s122-sub-bcdr01-rsv01/replicationFabrics/daz1eu-s122-sub-asrf02/replicationProtectionContainers/daz2eu-s122-sub-asrpc02" -> "/subscriptions/<redacted>/resourceGroups/daz1eu-s122-sub-rg01/providers/Microsoft.RecoveryServices/vaults/daz1eu-s122-sub-bcdr01-rsv01/replicationFabrics/daz1eu-s122-sub-asrf02/replicationProtectionContainers/daz2eu-s122-sub-asrpc02"
        target_resource_group_id                  = "/subscriptions/<redacted>/resourceGroups/daz2eu-s122-asr-rg01"

        timeouts {
            create = "3h"
            update = "3h"
        }
    }
```

If you look closely, you can see that no real changes have occured. Instead, the ID for `recovery_replication_policy_id`, `target_recovery_protection_container_id` and `target_recovery_fabric_id` was stored with a capital S in '/Subscriptions/...', and everywhere else 'Microsoft.Compute' was lower-cased to 'microsoft.compute' when it was stored. None of the IDs are being provided hard-coded, all references you see here are passed from the outputs of other resources.

### Steps to Reproduce

1. Create an azurerm_site_recovery_replicated_vm
2. Run a second plan

### Important Factoids

N/A

### References

N/A

**Comment by njuCZ** [comment] 2020-09-15 03:22
@cub10s1ty I am sorry that I could not reproduce this issue, could you please provide more detail scripts?

**Comment by max-mayrhofer** [comment] 2020-09-15 07:52
@njuCZ thanks for replying! That is really strange.. it might be related to the other resources instead and the latest buggy patch to the azurerm provider affecting the output of the site recovery resources, etc. Below you can see the actual resource creation for each of the source resources, as well as the relevant extract of versions.tf. Please let me know how else I can help.

**versions.tf**
```
provider "azurerm" {
  version         = "~>2.3"
  client_id       = var.aad_client_id
  client_secret   = var.aad_client_secret
  tenant_id       = var.aad_tenant_id
  subscription_id = var.aad_subscription_id
  features {}
}
```

**site recovery resources**
```
resource "azurerm_site_recovery_replication_policy" "business_continuity" {
  for_each = toset(local.regions)

  name                = "${local.resource_name_prefixes[each.value].name}-bcdr02-hourly"
  resource_group_name = local.resource_group.name
  recovery_vault_name = azurerm_recovery_services_vault.business_continuity[each.value].name

  recovery_point_retention_in_minutes = 1 * 24 * 60 // 1 day (premium SSD limitation)

  application_consistent_snapshot_frequency_in_minutes = {
    d = 12 * 60 // twice daily
    t = 12 * 60 // twice daily
    p = 1 * 60  // hourly
  }[local.environment]
}

resource "azurerm_site_recovery_fabric" "business_continuity_primary" {
  for_each = toset(local.regions)

  name                = "${local.resource_name_prefixes[each.value].name}-asrf01"
  resource_group_name = local.resource_group.name
  recovery_vault_name = azurerm_recovery_services_vault.business_continuity[each.value].name
  location            = each.value
}

resource "azurerm_site_recovery_fabric" "business_continuity_secondary" {
  for_each = toset(local.regions)

  name                = "${local.resource_name_prefixes[each.value].name}-asrf02"
  resource_group_name = local.resource_group.name
  recovery_vault_name = azurerm_recovery_services_vault.business_continuity[each.value].name
  location            = local.global_variables.location_dr[each.value]
}

resource "azurerm_site_recovery_protection_container" "business_continuity_primary" {
  for_each = azurerm_site_recovery_fabric.business_continuity_primary

  name                 = "${local.resource_name_prefixes[each.value.location].name}-asrpc01"
  resource_group_name  = each.value.resource_group_name
  recovery_vault_name  = each.value.recovery_vault_name
  recovery_fabric_name = each.value.name
}

resource "azurerm_site_recovery_protection_container" "business_continuity_secondary" {
  for_each = azurerm_site_recovery_fabric.business_continuity_secondary

  name                 = "${local.resource_name_prefixes[each.value.location].name}-asrpc02"
  resource_group_name  = each.value.resource_group_name
  recovery_vault_name  = each.value.recovery_vault_name
  recovery_fabric_name = each.value.name
}

resource "azurerm_site_recovery_protection_container_mapping" "business_continuity" {
  for_each = azurerm_site_recovery_fabric.business_continuity_primary

  name                                      = "${local.resource_name_prefixes[each.value.location].name}-asrpcm01"
  resource_group_name                       = each.value.resource_group_name
  recovery_vault_name                       = each.value.recovery_vault_name
  recovery_fabric_name                      = each.value.name
  recovery_source_protection_container_name = azurerm_site_recovery_protection_container.business_continuity_primary[each.value.location].name
  recovery_target_protection_container_id   = azurerm_site_recovery_protection_container.business_continuity_secondary[each.value.location].id
  recovery_replication_policy_id            = azurerm_site_recovery_replication_policy.business_continuity[each.value.location].id
}

resource "azurerm_site_recovery_network_mapping" "business_continuity" {
  for_each = azurerm_virtual_network.this

  name                        = "${local.resource_name_prefixes[each.value.location].name}-asrnm01"
  resource_group_name         = local.resource_group.name
  recovery_vault_name         = azurerm_recovery_services_vault.business_continuity[each.value.location].name
  source_recovery_fabric_name = azurerm_site_recovery_fabric.business_continuity_primary[each.value.location].name
  target_recovery_fabric_name = azurerm_site_recovery_fabric.business_continuity_secondary[each.value.location].name
  source_network_id           = each.value.id
  target_network_id           = azurerm_virtual_network.this[local.global_variables.location_dr[each.value.location]].id
}
```

**other module resources**
```
resource "azurerm_network_interface" "this" {
  name                = "${var.name}-nic01"
  location            = var.region
  resource_group_name = var.resource_group_name
  dns_servers         = local.global_variables.dns_servers[var.region]
  ip_configuration {
    name                          = "${var.name}-nic01-ipcfg"
    subnet_id                     = local.subscription_context.networking.subnets[var.region].id
    private_ip_address_allocation = "Dynamic"
  }
}

resource "azurerm_windows_virtual_machine" "this" {
  name                  = var.name
  location              = var.region
  resource_group_name   = var.resource_group_name
  network_interface_ids = [azurerm_network_interface.this.id]
  admin_username        = local.admin_user
  admin_password        = random_password.admin_password.result
  size                  = var.size
  tags                  = local.tags
  license_type          = "Windows_Server"

  source_image_reference {
    publisher = var.operating_system.publisher
    offer     = var.operating_system.offer
    sku       = var.operating_system.sku
    version   = var.operating_system.version
  }

  os_disk {
    name                 = "${var.name}-osdisk01"
    caching              = "ReadWrite"
    storage_account_type = var.use_premium_storage_for_os ? "Premium_LRS" : "StandardSSD_LRS"
  }
}

resource "azurerm_managed_disk" "data_disk" {
  for_each = { for disk in var.data_disks : disk.index => disk }

  name                 = format("%s-datadisk%02d", var.name, each.value.index)
  location             = var.region
  resource_group_name  = var.resource_group_name
  storage_account_type = each.value.use_premium_storage ? "Premium_LRS" : "StandardSSD_LRS"
  create_option        = "Empty"
  disk_size_gb         = each.value.disk_size_in_gb
}

resource "azurerm_virtual_machine_data_disk_attachment" "data_disk" {
  for_each = { for disk in var.data_disks : disk.index => disk }

  managed_disk_id    = azurerm_managed_disk.data_disk[each.key].id
  virtual_machine_id = azurerm_windows_virtual_machine.this.id
  lun                = each.value.lun
  caching            = "ReadWrite"

  depends_on = [
    azurerm_managed_disk.data_disk,
    azurerm_windows_virtual_machine.this
  ]
}

# All attached disks must be mounted, formatted, and be assigned drive letters for the site recovery replication agent to discover them correctly
resource "azurerm_virtual_machine_extension" "disk_formatter" {
  name                 = "${var.name}-diskformatter"
  virtual_machine_id   = azurerm_windows_virtual_machine.this.id
  publisher            = "Microsoft.Compute"
  type                 = "CustomScriptExtension"
  type_handler_version = "1.10"
  # Invoke-Command -ScriptBlock { $disks = @( Get-Disk | Where-Object PartitionStyle -eq "RAW" ); for ($i = 0; $i -lt $disks.Count; $i++) { $disknum = $disks[$i].Number; $volume = Get-Disk $disknum | Initialize-Disk -PartitionStyle GPT -PassThru | New-Partition -AssignDriveLetter -UseMaximumSize; Format-Volume -DriveLetter $volume.Driveletter -FileSystem ReFS -NewFileSystemLabel "Data $($disknum.ToString().PadLeft(2, "0"))" -Confirm:$false } } 
  protected_settings = <<-PROTECTED_SETTINGS
  {
    "commandToExecute": "powershell -EncodedCommand \"SQBuAHYAbwBrAGUALQBDAG8AbQBtAGEAbgBkACAALQBTAGMAcgBpAHAAdABCAGwAbwBjAGsAIAB7ACAAJABkAGkAcwBrAHMAIAA9ACAAQAAoACAARwBlAHQALQBEAGkAcwBrACAAfAAgAFcAaABlAHIAZQAtAE8AYgBqAGUAYwB0ACAAUABhAHIAdABpAHQAaQBvAG4AUwB0AHkAbABlACAALQBlAHEAIAAiAFIAQQBXACIAIAApADsAIABmAG8AcgAgACgAJABpACAAPQAgADAAOwAgACQAaQAgAC0AbAB0ACAAJABkAGkAcwBrAHMALgBDAG8AdQBuAHQAOwAgACQAaQArACsAKQAgAHsAIAAkAGQAaQBzAGsAbgB1AG0AIAA9ACAAJABkAGkAcwBrAHMAWwAkAGkAXQAuAE4AdQBtAGIAZQByADsAIAAkAHYAbwBsAHUAbQBlACAAPQAgAEcAZQB0AC0ARABpAHMAawAgACQAZABpAHMAawBuAHUAbQAgAHwAIABJAG4AaQB0AGkAYQBsAGkAegBlAC0ARABpAHMAawAgAC0AUABhAHIAdABpAHQAaQBvAG4AUwB0AHkAbABlACAARwBQAFQAIAAtAFAAYQBzAHMAVABoAHIAdQAgAHwAIABOAGUAdwAtAFAAYQByAHQAaQB0AGkAbwBuACAALQBBAHMAcwBpAGcAbgBEAHIAaQB2AGUATABlAHQAdABlAHIAIAAtAFUAcwBlAE0AYQB4AGkAbQB1AG0AUwBpAHoAZQA7ACAARgBvAHIAbQBhAHQALQBWAG8AbAB1AG0AZQAgAC0ARAByAGkAdgBlAEwAZQB0AHQAZQByACAAJAB2AG8AbAB1AG0AZQAuAEQAcgBpAHYAZQBsAGUAdAB0AGUAcgAgAC0ARgBpAGwAZQBTAHkAcwB0AGUAbQAgAFIAZQBGAFMAIAAtAE4AZQB3AEYAaQBsAGUAUwB5AHMAdABlAG0ATABhAGIAZQBsACAAIgBEAGEAdABhACAAJAAoACQAZABpAHMAawBuAHUAbQAuAFQAbwBTAHQAcgBpAG4AZwAoACkALgBQAGEAZABMAGUAZgB0ACgAMgAsACAAIgAwACIAKQApACIAIAAtAEMAbwBuAGYAaQByAG0AOgAkAGYAYQBsAHMAZQAgAH0AIAB9AA==\""
  }
  PROTECTED_SETTINGS

  depends_on = [
    azurerm_virtual_machine_data_disk_attachment.data_disk
  ]
}

data "azurerm_managed_disk" "os_disk" {
  name                = "${var.name}-osdisk01"
  resource_group_name = var.resource_group_name

  depends_on = [
    azurerm_virtual_machine_data_disk_attachment.data_disk
  ]
}
```

**Comment by MitchDrage** [comment] 2020-10-11 05:16
This looks to be caused by the managed_disk id being converted to lowercase and not having the case ignored when running a plan or apply.
The ToLower is being done on line 513 of resource_arm_site_recovery_replicated_vm.go and I believe the suppression of the case difference is supposed to be happening on line 128 of the same file.

The workaround that I'm using is to wrap the disk reference in lower(<diskID>).

**Comment by favoretti** [comment] 2021-09-01 10:04
Thanks for opening this issue! Since this issue has been reported a long time ago and relates to an older version of provider - I'm going to close it. If this is still relevant and occurring on the latest version of terraform and provider please do open a new issue!

**Closed by favoretti** 2021-09-01 10:04 UTC
Labels: question, service/recovery-services
