### ISSUE TITLE
Recovery Service Vault in Azure doesn't have parameter for setting the backup confirma

### ISSUE THREAD

**Issue by janapb** [hashicorp/terraform-provider-azurerm#13469] opened 2021-09-23 07:54 UTC
azurerm_recovery_services_vault provider doesn't have the parameter to configure backup properties. By default the backup storage redundancy is set to GeoRedundant. This should be passed as parameter to choose between the available options

**Comment by jeffwmiles** [comment] 2021-09-23 16:59
This is a duplicate of https://github.com/hashicorp/terraform-provider-azurerm/issues/8709

For what its worth, I perform this function with an ARM template in Terraform:

```
resource "azurerm_resource_group_template_deployment" "client-lrs-rsv-config" {
  # ARM template to disable GRS protection on primary vault
  name                = "${var.clientcode}-backup-lrs-rsv-config"
  resource_group_name = azurerm_resource_group.srv-rg.name
  deployment_mode = "Incremental"
  depends_on      = [azurerm_recovery_services_vault.client-backup-lrs-rsv]

  parameters_content = jsonencode({
    "clientcode" = {
      value = var.clientcode
    }
  })

  template_content       = <<TEMPLATE
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "clientcode": {
            "type": "String",
            "metadata": {
                "description": "The client code in use"
            }
        }
    },
    "variables": {
      "vaults_rsv_name": "[concat('cc-',parameters('clientcode'),'-backup-lrs-rsv')]"
    },
    "resources": [
        {
            "type": "Microsoft.RecoveryServices/vaults/backupstorageconfig",
            "name": "[concat(variables('vaults_rsv_name'), '/vaultstorageconfig')]",
            "apiVersion": "2018-01-10",
            "properties": {
                "StorageModelType": "LocallyRedundant"
            }
        }
    ]
}
  TEMPLATE
}
```

**Comment by katbyte** [comment] 2022-01-10 05:17
CLosing as duplicate of #8709

**Closed by katbyte** 2022-01-10 05:17 UTC
Labels: enhancement, service/recovery-services
