### ISSUE TITLE
Eventhub Namespace should have Zone Redundancy enabled no way to enable

### ISSUE THREAD

**Issue by krisrmgua** [hashicorp/terraform-provider-azurerm#28209] opened 2024-12-06 20:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.10.0

### AzureRM Provider Version

4.6.0.

### Affected Resource(s)/Data Source(s)

azurerm_eventhub_namespace

### Terraform Configuration Files

```hcl
resource "azurerm_eventhub_namespace" "example" {
  name                = "example-namespace"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  sku                 = "Standard"
  capacity            = 2

  tags = {
    environment = "Production"
  }
}
```

### Debug Output/Panic Output

```shell
n/a
```

### Expected Behaviour

When creating Namespace using the UI zone redundancy is enabled. And it should do the same in terraform.

### Actual Behaviour

When creating in terraform Zone Redundancy for the namespace is not enabled

### Steps to Reproduce

Im creating in US-East-2

In the UI create a namespace and you will see zone redudancy is enable when you create it.

With terraform:

resource "azurerm_eventhub_namespace" "example" {
  name                = "example-namespace"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  sku                 = "Standard"
  capacity            = 2

  tags = {
    environment = "Production"
  }
}

You will see it will not be enabled.

**Comment by rcskosir** [comment] 2024-12-07 01:40
Thanks for taking the time to submit this issue. It looks like this is a duplicate of #27239. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of #27239.

**Closed by rcskosir** 2024-12-07 01:40 UTC
Labels: service/event-hubs, v/4.x
