### ISSUE TITLE
data_factor_name is now required argument for azurerm_data_factory_linked_service_azure_sql_database resource

### ISSUE THREAD

**Issue by gauravbatta** [hashicorp/terraform-provider-azurerm#14633] opened 2021-12-15 16:53 UTC
data_factor_name is now required argument for azurerm_data_factory_linked_service_azure_sql_database resource

Per https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/data_factory_linked_service_azure_sql_database it is shown as optional

Error:

43: resource "azurerm_data_factory_linked_service_azure_sql_database" "example" {
│
│ The argument "data_factory_name" is required, but no definition was found.

Also - data_factory_id is Unsupported argument now

43: resource "azurerm_data_factory_linked_service_azure_sql_database" "example" {
│
│ The argument "data_factory_name" is required, but no definition was found.

**Comment by stephybun** [comment] 2021-12-16 12:08
Hi @gauravbatta,

Thanks for raising this issue. `data_factory_name` was deprecated and `data_factory_id` was introduced in version 2.89.0 of the provider. You can upgrade to v2.89.0 or higher or you can view documentation for older versions of the provider on the registry. Since this is not a bug or a feature request I am going to close this issue.

Thanks!

**Closed by stephybun** 2021-12-16 12:08 UTC
Labels: question, service/data-factory
