### ISSUE TITLE
terraform apply fails on creating azurerm_key_vault_secret, resource is created but not in the state

### ISSUE THREAD

**Issue by tplive** [hashicorp/terraform-provider-azurerm#13494] opened 2021-09-24 11:09 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v1.0.7
azurerm v2.78.0

### Affected Resource(s)

* `azurerm_key_vault_secret`

### Terraform Configuration Files

```hcl
resource "azurerm_key_vault_secret" "t-domain-join-user" {
  name         = "domain-join-user"
  value        = azuread_user.aadds_admin.user_principal_name
  key_vault_id = module.test_systemXXX.key_vault_id
}

resource "azurerm_key_vault_secret" "t-domain-join-password" {
  name         = "domain-join-password"
  value        = random_password.aadds_admin_password.result
  key_vault_id = module.test_systemXXX.key_vault_id
}
```

### Debug Output
This is part of a larger deployment, and the debug log is > 200k lines. 

### Actual Behaviour
Key Vault secrets are created in Azure, but the apply session fails. The resources are NOT added to terraform state, so the next run also fails, saying that the resource already exists and needs to be imported.

Terraform output first run: https://gist.github.com/tplive/2fa710e2953248abf678178263fef8a1

Terraform output second run: https://gist.github.com/tplive/bf3861a858a073e1f77d0763bb023874

### Steps to Reproduce
1. `terraform apply`
2. `terraform apply`again

### Important Factoids
Key Vault was created earlier, running a pipeline using a different SP.

### References
Same issue, closed with azurerm version 2.46:
* #11059

**Comment by tombuildsstuff** [comment] 2021-11-15 13:21
Duplicate of #11059

**Closed by tombuildsstuff** 2021-11-15 13:21 UTC
Labels: bug, service/keyvault
