### ISSUE TITLE
"Request Entity Too Large" error from API when trying to deploy large azurerm_container_group

### ISSUE THREAD

**Issue by phoehnel** [hashicorp/terraform-provider-azurerm#23481] opened 2023-10-09 05:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

v1.4.5

### AzureRM Provider Version

3.75.0

### Affected Resource(s)/Data Source(s)

azurerm_container_group

### Terraform Configuration Files

```hcl
Plan here - actual configuration contains a lot of intenal modules which i can't share here. 
Nevertheless, deploying any container group with a large enough container config should do.


  # module.workload.module.aci[0].azurerm_container_group.this will be created
  + resource "azurerm_container_group" "this" {
      + dns_name_label_reuse_policy = "Unsecure"
      + exposed_port                = [
          + {
              + port     = 3000
              + protocol = "TCP"
            },
          + {
              + port     = 80
              + protocol = "TCP"
            },
        ]
      + fqdn                        = (known after apply)
      + id                          = (known after apply)
      + ip_address                  = (known after apply)
      + ip_address_type             = "Private"
      + location                    = "westeurope"
      + name                        = "aci-xxxx-lab"
      + network_profile_id          = (known after apply)
      + os_type                     = "Linux"
      + resource_group_name         = "rg-xxxxxxxx-lab"
      + restart_policy              = "OnFailure"
      + sku                         = "Standard"
      + subnet_ids                  = [
          + "/subscriptions/123sub123/resourceGroups/rg-spoke_we1_xxxxxxxxx-lab/providers/Microsoft.Network/virtualNetworks/vnet-spoke_we1_xxxxxxxxx-lab/subnets/snet-xxxxxxxxx_we1_xxxxxxxxx-lab",
        ]
      + tags                        = {
          + "AzCosts"               = "xxxxxxxxx/Team/xxxxxxxxx"
          + "compliance_GDPR"       = "false"
          + "compliance_HGB"        = "false"
          + "department_owner"      = "xxxxxxxxx/Team/xxxxxxxxx"
          + "department_tech"       = "xxxxxxxxx/Team/xxxxxxxxx"
          + "environment_business"  = "LAB"
          + "environment_cap"       = "LAB"
          + "level_of_availability" = "0999"
          + "level_of_criticality"  = "1_low"
          + "level_of_encryption"   = "optional"
          + "version_tag_schema"    = "1.0"
        }

      + container {
          + commands              = (known after apply)
          + cpu                   = 0.7
          + environment_variables = {
              + "GF_AUTH_AZUREAD_ALLOWED_GROUPS"             = "xxxxxxxxx"
              + "GF_AUTH_AZUREAD_ALLOW_ASSIGN_xxxxxxxxx_ADMIN" = "false"
              + "GF_AUTH_AZUREAD_ALLOW_SIGN_UP"              = "true"
              + "GF_AUTH_AZUREAD_AUTH_URL"                   = "https://login.windows.net/xxxxxxxxx/oauth2/authorize"
              + "GF_AUTH_AZUREAD_AUTO_LOGIN"                 = "false"
              + "GF_AUTH_AZUREAD_CLIENT_ID"                  = (sensitive value)
              + "GF_AUTH_AZUREAD_CLIENT_SECRET"              = (sensitive value)
              + "GF_AUTH_AZUREAD_ENABLED"                    = "true"
              + "GF_AUTH_AZUREAD_NAME"                       = "Azure AD"
              + "GF_AUTH_AZUREAD_SCOPES"                     = "openid email profile"
              + "GF_AUTH_AZUREAD_TOKEN_URL"                  = "https://login.windows.net/xxxxxxxxx/oauth2/token"
              + "GF_DATABASE_HOST"                           = "psql-xxxxxxxxxcostspsqldk-lab.postgres.database.azure.com:5432"
              + "GF_DATABASE_NAME"                           = "xxxxxxxxx"
              + "GF_DATABASE_PASSWORD"                       = (sensitive value)
              + "GF_DATABASE_SSL_MODE"                       = "require"
              + "GF_DATABASE_TYPE"                           = "postgres"
              + "GF_DATABASE_USER"                           = "xxxxxxxxx"
              + "GF_INSTALL_PLUGINS"                         = "xxxxxxxxx-azure-monitor-datasource"
              + "GF_SECURITY_ADMIN_PASSWORD"                 = (sensitive value)
              + "GF_SERVER_HTTP_PORT"                        = "3000"
              + "GF_SERVER_ROOT_URL"                         = "https://xxxxxxxxx.we1.lab.xxxxxxxxx.azr.gothaer.de"
            }
          + image                 = "xxxxxxxxx.azurecr.io/xxxxxxxxx:10.0.5-ubuntu"
          + memory                = 1.5
          + name                  = "xxxxxxxxx-lab"

          + ports {
              + port     = 3000
              + protocol = "TCP"
            }

          + volume {
              + empty_dir  = false
              + mount_path = "/etc/ssl/certs"
              + name       = "xxxxxxxxx-ca-crts-xxxxxxxxx"
              + read_only  = false
              + secret     = (sensitive value)
            }
        }
      + container {
          + commands = (known after apply)
          + cpu      = 0.2
          + image    = "xxxxxxxxx.azurecr.io/nginx:1-alpine"
          + memory   = 0.3
          + name     = "nginx-for-xxxxxxxxx-lab"

          + ports {
              + port     = 80
              + protocol = "TCP"
            }

          + volume {
              + empty_dir  = false
              + mount_path = "/etc/nginx/templates"
              + name       = "nginx-conf"
              + read_only  = false
              + secret     = (sensitive value)
            }
          + volume {
              + empty_dir  = false
              + mount_path = "/ssl-certs"
              + name       = "ssl-crts-nginx"
              + read_only  = false
              + secret     = (sensitive value)
            }
        }
      + container {
          + commands = [
              + "pwsh",
              + "-File",
              + "/dns-sidecar-script/run.ps1",
            ]
          + cpu      = 0.1
          + image    = "xxxxxxxxx.azurecr.io/azure-powershell:10.4.1-alpine-3.14"
          + memory   = 0.2
          + name     = "dns-script-for-xxxxxxxxx-lab"

          + volume {
              + empty_dir  = false
              + mount_path = "/dns-sidecar-script"
              + name       = "dns-sidecar-script"
              + read_only  = false
              + secret     = (sensitive value)
            }
          + volume {
              + empty_dir  = false
              + mount_path = "/etc/ssl/certs"
              + name       = "xxxxxxxxx-ca-certs-sidecar"
              + read_only  = false
              + secret     = (sensitive value)
            }
        }

      + dns_config {
          + nameservers = [
              + "10.xx.0.xxx",
            ]
        }

      + identity {
          + identity_ids = [
              + "/subscriptions/xxxxxxxxx/resourceGroups/xxxxxxxxxxxxxxx/providers/Microsoft.ManagedIdentity/userAssignedIdentities/xxxxxxxxxxxxxxxxxxx",
              + "/subscriptions/123sub123/resourceGroups/rg-xxxxxxxxxcosts-xxxxxxxxx-lab/providers/Microsoft.ManagedIdentity/userAssignedIdentities/tu-xxxxxxxxxxx-xxxxxxxxxcosts-ml-lab",
            ]
          + principal_id = (known after apply)
          + tenant_id    = (known after apply)
          + type         = "SystemAssigned, UserAssigned"
        }

      + image_registry_credential {
          + server                    = "xxxxxxxxx.azurecr.io"
          + user_assigned_identity_id = "/subscriptions/xxxxxxxxx/resourceGroups/rg-xxxxxxxxxxxxx-prd/providers/Microsoft.ManagedIdentity/userAssignedIdentities/tu-xxxxxxxxxxxxxxxxx-prd"
        }
    }
```

### Debug Output/Panic Output

```shell
2023-10-09T07:39:22.920+0200 [DEBUG] provider.terraform-provider-azurerm_v3.75.0_x5: AzureRM Response for https://management.azure.com/subscriptions/xxxxxxxxx/resourceGroups/xxxxxxxxx/providers/Microsoft.ContainerInstance/containerGroups/xxxxxxxxx?api-version=2023-05-01: 
HTTP/1.1 413 Request Entity Too Large
Content-Length: 0
Cache-Control: no-cache
Date: Mon, 09 Oct 2023 05:39:22 GMT
Expires: -1
Pragma: no-cache
Server: Microsoft-IIS/10.0
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Ms-Correlation-Request-Id: 71ce6b98-3e30-0f26-12d6-43c0e015fc5b
X-Ms-Ratelimit-Remaining-Subscription-Writes: 1199
X-Ms-Request-Id: 439f747c-c02e-483d-b2df-84aee125307d
X-Ms-Routing-Request-Id: FRANCESOUTH:20231009T053922Z:439f747c-c02e-483d-b2df-84aee125307d: timestamp=2023-10-09T07:39:22.919+0200
2023-10-09T07:39:22.920+0200 [DEBUG] provider.terraform-provider-azurerm_v3.75.0_x5: Unlocking "/subscriptions/xxxxxxxxx/resourceGroups/xxxxxxxxx/providers/Microsoft.Network/virtualNetworks/vnet-xxxxxxxxx/subnets/snet-xxxxxxxxx": timestamp=2023-10-09T07:39:22.920+0200
2023-10-09T07:39:22.920+0200 [DEBUG] provider.terraform-provider-azurerm_v3.75.0_x5: Unlocked "/subscriptions/xxxxxxxxx/resourceGroups/xxxxxxxxx/providers/Microsoft.Network/virtualNetworks/vnet-xxxxxxxxx/subnets/snet-xxxxxxxxx": timestamp=2023-10-09T07:39:22.920+0200
2023-10-09T07:39:22.920+0200 [TRACE] provider.terraform-provider-azurerm_v3.75.0_x5: Called downstream: @caller=github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:910 @module=sdk.helper_schema tf_provider_addr=provider tf_resource_type=azurerm_container_group tf_rpc=ApplyResourceChange tf_req_id=f3874a5e-5cf5-3721-3801-e6d61e09cd20 timestamp=2023-10-09T07:39:22.920+0200
2023-10-09T07:39:22.920+0200 [TRACE] provider.terraform-provider-azurerm_v3.75.0_x5: Received downstream response: @module=sdk.proto diagnostic_warning_count=0 tf_req_duration_ms=3632 tf_resource_type=azurerm_container_group @caller=github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/tf5serverlogging/downstream_request.go:40 tf_proto_version=5.4 tf_provider_addr=provider tf_req_id=f3874a5e-5cf5-3721-3801-e6d61e09cd20 tf_rpc=ApplyResourceChange diagnostic_error_count=1 timestamp=2023-10-09T07:39:22.920+0200
2023-10-09T07:39:22.920+0200 [ERROR] provider.terraform-provider-azurerm_v3.75.0_x5: Response contains error diagnostic: tf_req_id=f3874a5e-5cf5-3721-3801-e6d61e09cd20 diagnostic_detail= diagnostic_summary="creating Container Group (Subscription: "xxxxxxxxx"
Resource Group Name: "xxxxxxxxx"
Container Group Name: "xxxxxxxxx"): performing ContainerGroupsCreateOrUpdate: containerinstance.ContainerInstanceClient#ContainerGroupsCreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="Failed" Message="The async operation failed."" tf_proto_version=5.4 tf_provider_addr=provider @caller=github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/diag/diagnostics.go:58 @module=sdk.proto diagnostic_severity=ERROR tf_resource_type=azurerm_container_group tf_rpc=ApplyResourceChange timestamp=2023-10-09T07:39:22.920+0200
2023-10-09T07:39:22.920+0200 [TRACE] provider.terraform-provider-azurerm_v3.75.0_x5: Served request: tf_proto_version=5.4 tf_req_id=f3874a5e-5cf5-3721-3801-e6d61e09cd20 tf_resource_type=azurerm_container_group tf_rpc=ApplyResourceChange @module=sdk.proto tf_provider_addr=provider @caller=github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/tf5server/server.go:872 timestamp=2023-10-09T07:39:22.920+0200
╷
│ Error: creating Container Group (Subscription: "xxxxxxxxx"
│ Resource Group Name: "xxxxxxxxx"
│ Container Group Name: "xxxxxxxxx"): performing ContainerGroupsCreateOrUpdate: containerinstance.ContainerInstanceClient#ContainerGroupsCreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="Failed" Message="The async operation failed."
│ 
│   with module.workload.module.aci[0].azurerm_container_group.this,
│   on .terraform/modules/workload.aci/main.tf line 24, in resource "azurerm_container_group" "this":
│   24: resource "azurerm_container_group" "this" {
│ 
╵
2023-10-09T07:39:22.960+0200 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
2023-10-09T07:39:22.964+0200 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/azurerm/3.75.0/linux_amd64/terraform-provider-azurerm_v3.75.0_x5 pid=2756609
2023-10-09T07:39:22.964+0200 [DEBUG] provider: plugin exited
make: *** [apply] Error 1
```

### Expected Behaviour

- The size limit of the configuration should be documented
- The error message should point to the configuration beeing to long

### Actual Behaviour

- Error message: "The async operation failed."
- Real error can only be optained in output when setting TF_LOG_PROVIDER=TRACE 

### Steps to Reproduce

1. Deploy an AzureRM Container Group
2. Enlarge the configuration by using secret volumes which e.g. contain an base64encoded certificate chain
3. As soon as your configuration goes over a certain length, you'll see "The async operation failed."

**Comment by sinbai** [comment] 2023-10-10 06:54
Hi @phoehnel thanks for opening this issue. For `Enlarge the configuration by using secret volumes which e.g. contain an base64encoded certificate chain` in `Steps to Reproduce`, is it possible to provide a relational terraform configuration to help reproduce and troubleshooting?

**Comment by rcskosir** [comment] 2024-02-09 18:34
Thanks for opening this issue. Since time has passed and @sinbai was not able to reproduce this issue, I am going to mark this issue closed as “can’t reproduce”. If you are able to provide more information to help us reproduce this issue we may re-open this issue or open a new issue, thanks!

**Closed by rcskosir** 2024-02-09 18:34 UTC
Labels: waiting-response, service/container-group, v/3.x
