### ISSUE TITLE
Azure Instance Metadata Service API for ARC servers returns invalid API Version

### ISSUE THREAD

**Issue by ABCodeMonkey** [hashicorp/terraform-provider-azurerm#21240] opened 2023-03-31 17:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.9

### AzureRM Provider Version

v3.40.0

### Affected Resource(s)/Data Source(s)

Azure Instance Metadata Service on ARC servers

### Terraform Configuration Files

```hcl
MAIN.TF
# you will need to here if not using MSI in backend block
# PS C:\foo\test> $env:ARM_USE_MSI = "true"
# you will need this for ARC Identity
# PS C:\foo\test> $env:ARM_MSI_ENDPOINT = "http://localhost:40342/metadata/identity/oauth2/token"
#
#

terraform {
  backend "azurerm" {
    resource_group_name  = "TFSTATE-RG"
    storage_account_name = "TFSTATE-STG"
    container_name       = "TFSTATE-CON"
    key                  = "tfstate.your.terraform.tfstate"
    subscription_id      = "584e21d4-f437-4g88-82de-7a8161e890d6"  #terraform sub
    tenant_id            = "f7a215fe-6900-4713-aec6-ac56fdca7048"  #tenant_id
    use_msi = true
  }
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3"
    }
  }
}
```

### Debug Output/Panic Output

```shell
PS C:\foo\test> $env:TF_LOG = "TRACE"
PS C:\foo\test> terraform init
2023-03-31T10:44:54.520-0700 [INFO]  Terraform version: 1.2.3
2023-03-31T10:44:54.521-0700 [DEBUG] using github.com/hashicorp/go-tfe v1.0.0
2023-03-31T10:44:54.522-0700 [DEBUG] using github.com/hashicorp/hcl/v2 v2.12.0
2023-03-31T10:44:54.523-0700 [DEBUG] using github.com/hashicorp/terraform-config-inspect v0.0.0-20210209133302-4fd17a0faac2
2023-03-31T10:44:54.523-0700 [DEBUG] using github.com/hashicorp/terraform-svchost v0.0.0-20200729002733-f050f53b9734
2023-03-31T10:44:54.523-0700 [DEBUG] using github.com/zclconf/go-cty v1.10.0
2023-03-31T10:44:54.524-0700 [INFO]  Go runtime version: go1.18.1
2023-03-31T10:44:54.525-0700 [INFO]  CLI args: []string{"C:\\ProgramData\\chocolatey\\lib\\terraform\\tools\\terraform.exe", "init"}
2023-03-31T10:44:54.526-0700 [TRACE] Stdout is a terminal of width 120
2023-03-31T10:44:54.526-0700 [TRACE] Stderr is a terminal of width 120
2023-03-31T10:44:54.527-0700 [TRACE] Stdin is a terminal
2023-03-31T10:44:54.528-0700 [DEBUG] Attempting to open CLI config file: C:\Users\mgadmin\AppData\Roaming\terraform.rc
2023-03-31T10:44:54.528-0700 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2023-03-31T10:44:54.529-0700 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2023-03-31T10:44:54.529-0700 [DEBUG] ignoring non-existing provider search directory C:\Users\mgadmin\AppData\Roaming\terraform.d\plugins
2023-03-31T10:44:54.531-0700 [DEBUG] ignoring non-existing provider search directory C:\Users\mgadmin\AppData\Roaming\HashiCorp\Terraform\plugins
2023-03-31T10:44:54.532-0700 [INFO]  CLI command args: []string{"init"}

Initializing the backend...
2023-03-31T10:44:54.535-0700 [TRACE] Meta.Backend: built configuration for "azurerm" backend with hash value 2197453331
2023-03-31T10:44:54.536-0700 [TRACE] Meta.Backend: backend has not previously been initialized in this working directory2023-03-31T10:44:54.536-0700 [DEBUG] New state was assigned lineage "0af1782b-8480-91e4-93f1-742b0b313c8b"
2023-03-31T10:44:54.537-0700 [TRACE] Meta.Backend: moving from default local state only to "azurerm" backend
2023-03-31T10:44:54.537-0700 [DEBUG] checking for provisioner in "."
2023-03-31T10:44:54.537-0700 [DEBUG] checking for provisioner in "C:\\ProgramData\\chocolatey\\lib\\terraform\\tools"
2023-03-31T10:44:54.538-0700 [TRACE] backend/local: state manager for workspace "default" will:
 - read initial snapshot from terraform.tfstate
 - write new snapshots to terraform.tfstate
 - create any backup at terraform.tfstate.backup
2023-03-31T10:44:54.538-0700 [TRACE] statemgr.Filesystem: reading initial snapshot from terraform.tfstate
2023-03-31T10:44:54.539-0700 [TRACE] statemgr.Filesystem: snapshot file has nil snapshot, but that's okay
2023-03-31T10:44:54.539-0700 [TRACE] statemgr.Filesystem: read nil snapshot
2023-03-31T10:44:54.540-0700 [TRACE] Meta.Backend: ignoring local "default" workspace because its state is empty
2023-03-31T10:44:54.543-0700 [INFO]  Testing if Service Principal / Client Certificate is applicable for Authentication..
2023-03-31T10:44:54.543-0700 [INFO]  Testing if Multi Tenant Service Principal / Client Secret is applicable for Authentication..
2023-03-31T10:44:54.543-0700 [INFO]  Testing if Service Principal / Client Secret is applicable for Authentication..
2023-03-31T10:44:54.544-0700 [INFO]  Testing if OIDC is applicable for Authentication..
2023-03-31T10:44:54.544-0700 [INFO]  Testing if Managed Service Identity is applicable for Authentication..
2023-03-31T10:44:54.545-0700 [INFO]  Using Managed Service Identity for Authentication
2023-03-31T10:44:54.545-0700 [DEBUG] Using MSI msiEndpoint "http://localhost:40342/metadata/identity/oauth2/token"
2023-03-31T10:44:54.545-0700 [INFO]  Getting OAuth config for endpoint https://login.microsoftonline.com/ with  tenant f1a215ee-6910-4213-aec6-ac36fdca6048
2023-03-31T10:44:54.546-0700 [DEBUG] Obtaining an MSAL / Microsoft Graph token for Resource Manager..
2023-03-31T10:44:54.546-0700 [DEBUG] getADALToken with MSI msiEndpoint "http://localhost:40342/metadata/identity/oauth2/token", ClientID "" for msiEndpoint "https://management.azure.com/"
2023-03-31T10:44:54.566-0700 [DEBUG] New state was assigned lineage "ba3c1bec-70e6-647a-d67c-01f13947042e"
2023-03-31T10:44:54.567-0700 [DEBUG] Building the Container Client from an Access Token (using user credentials)
2023-03-31T10:44:54.568-0700 [DEBUG] backend/remote-state/azure Request:
POST /metadata/identity/oauth2/token HTTP/1.1
Host: localhost:40342
User-Agent: Go/go1.18.1 (amd64-windows) go-autorest/adal/v1.0.0
Transfer-Encoding: chunked
Content-Type: application/x-www-form-urlencoded
Metadata: true
Accept-Encoding: gzip

2e
resource=https%3A%2F%2Fmanagement.azure.com%2F
0
2023-03-31T10:44:54.571-0700 [DEBUG] backend/remote-state/azure Response for http://localhost:40342/metadata/identity/oauth2/token:
HTTP/1.1 405 Method Not Allowed
Content-Length: 0
Date: Fri, 31 Mar 2023 17:44:54 GMT
╷
│ Warning: "use_microsoft_graph": [DEPRECATED] This field now defaults to `true` and will be removed in v1.3 of Terraform Core due to the deprecation of ADAL by Microsoft.
│
│
╵

╷
│ Error: Failed to get existing workspaces: Error retrieving keys for Storage Account "azwu2itstfstate": azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/584ee1d4-f487-4c88-80de-7a8161e880d6/resourceGroups/AZWU2-ITS-TFSTATE/providers/Microsoft.Storage/storageAccounts/azwu2itstfstate/listKeys?api-version=2021-01-01: StatusCode=405 -- Original Error: adal: Refresh request failed. Status Code = '405'. Response body:  Endpoint http://localhost:40342/metadata/identity/oauth2/token
│
│
╵
```

### Expected Behaviour

The identity of the ARC enabled server is authenticated and the state file is accessed.

### Actual Behaviour

Failure is returned, 400 in the pipeline, 405 on the machine and no access to the state file is obtained

### Steps to Reproduce

1. Have an ARC enabled server
2. Provide the identity of the arc enabled server access to the azure blob storage containing your state
3. configure your environment to use the MSI Identity  and local identity endpoint
  $env:ARM_USE_MSI = "true"
  $env:ARM_MSI_ENDPOINT = "http://localhost:40342/metadata/identity/oauth2/token"
4. perform terraform init
  terraform init

### Important Factoids

This is attempting to use the Managed Identity of an Azure ARC server runing in vmware

### References

[azure-docs/managed-identity-authentication.md at main · MicrosoftDocs/azure-docs (github.com)](https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fazure-docs%2Fblob%2Fmain%2Farticles%2Fazure-arc%2Fservers%2Fmanaged-identity-authentication.md&data=05%7C01%7Cmarcogreen%40lithia.com%7Cc38be63a682d46e7466a08db31fdcda5%7Cf1a215ee69104213aec6ac36fdca6048%7C0%7C0%7C638158738402740568%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=WucTP48pW36gOSXDlw5WDx%2BwsxOVgZ1Wp5j6Elt7WX8%3D&reserved=0)
[https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/managed_service_identity](https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fregistry.terraform.io%2Fproviders%2Fhashicorp%2Fazurerm%2Flatest%2Fdocs%2Fguides%2Fmanaged_service_identity&data=05%7C01%7Cmarcogreen%40lithia.com%7Cc38be63a682d46e7466a08db31fdcda5%7Cf1a215ee69104213aec6ac36fdca6048%7C0%7C0%7C638158738402740568%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=CdD2O4A%2FciaRUz06mxT0pKXOyjipFGykR7dDITfQozg%3D&reserved=0)

**Comment by ABCodeMonkey** [comment] 2023-03-31 18:20
should add the error from the pipeline

Initializing the backend...


Error: Failed to get existing workspaces: Error retrieving keys for Storage Account "azwu2itstfstate": azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to [https://management.azure.com/subscriptions/584ee1d4-f487-4c88-80de-7a8161e880d6/resourceGroups/AZWU2-ITS-TFSTATE/providers/Microsoft.Storage/storageAccounts/azwu2itstfstate/listKeys?api-version=2021-01-01](https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmanagement.azure.com%2Fsubscriptions%2F584ee1d4-f487-4c88-80de-7a8161e880d6%2FresourceGroups%2FAZWU2-ITS-TFSTATE%2Fproviders%2FMicrosoft.Storage%2FstorageAccounts%2Fazwu2itstfstate%2FlistKeys%3Fapi-version%3D2021-01-01&data=05%7C01%7CMarcoGreen%40lithia.com%7C5482da12f0a0421e6b9a08db321174a0%7Cf1a215ee69104213aec6ac36fdca6048%7C0%7C0%7C638158822889925809%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=2f%2F2rlF0WPjlC6UdG075o5cqfEWQRaxLLRdJ7EzkSwk%3D&reserved=0): StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"The api-version '2018-02-01' could not be found. Supported are 2020-06-01 2019-11-01 2019-08-15","error_codes":[404],"timestamp":"2023-03-27 13:21:44.9865305 -0700 PDT m=+381203.321106201","trace_id":"","correlation_id":"bb98b726-eb27-473f-8d72-55cee9dee97d"}
Warning: "use_microsoft_graph": [DEPRECATED] This field now defaults to `true` and will be removed in v1.3 of Terraform Core due to the deprecation of ADAL by Microsoft.

Endpoint http://localhost:40342/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fmanagement.azure.com%2F

**Comment by tombuildsstuff** [comment] 2023-04-03 08:34
hi @ABCodeMonkey 

Thanks for opening this issue.

There's several different types of the Instance Metadata Service (when running in a VM, within AKS, within App Service, within CloudShell and within Azure Arc) - unfortunately each of these behaves rather differently, with the available API versions (as in this case), API behaviours and request/response payloads being inconsistent across them.

Whilst it's possible to use a Managed Identity in these places, at this point in time we support using a Managed Identity with Terraform when running inside of CloudShell/a Container/Virtual Machine running in (regular) Azure rather than Azure Arc - and as such unfortunately this is working as intended at this point in time.

Since we don't currently support using a Managed Identity within Azure Arc, I'm going to close this issue for the moment - however if you'd like to see support for this added then please feel free to open a new Feature Request for this.

Thanks!

**Closed by tombuildsstuff** 2023-04-03 08:34 UTC
Labels: question, authentication
