### ISSUE TITLE
DataLake provisioning - Error 403

### ISSUE THREAD

**Issue by nathanpinotti** [hashicorp/terraform-provider-azurerm#16958] opened 2022-05-25 19:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.1

### AzureRM Provider Version

3.7.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_data_lake_gen2_filesystem

### Terraform Configuration Files

```hcl
'm trying to create 3 datalakes using terraform by I'm getting a 403 error.

I'm using a admin account with owner roler. I also tried to create an SP and set Blob Reader Role.

Below find my code and the errror

Terraform v1.2.1 on windows_amd64

provider registry.terraform.io/hashicorp/azuread v2.22.0
provider registry.terraform.io/hashicorp/azurerm v3.7.0

`resource "azurerm_storage_data_lake_gen2_filesystem" "stg-datalake" {
for_each = toset(["bronze", "silver", "gold"])
name = each.value
storage_account_id = azurerm_storage_account.stg-datalake.id

ace {
scope = "access"
type = "user"
id = azurerm_data_factory.adf.identity[0].principal_id
permissions = "rwx"
}
}
`

Error: Error: checking for existence of existing File System "gold" (Account "stgaclientteste"): datalakestore.Client#GetProperties: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: error response cannot be parsed: {"" '\x00' '\x00'} error: EOF

Since there's no info regarding permissions needed to create a datalake I'd like to get any help to solve it

Regards
```

### Debug Output/Panic Output

```shell
No debug
```

### Expected Behaviour

Creation of the datalake stgs

### Actual Behaviour

Error 403

### Steps to Reproduce

terraform apply

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_data_lake_gen2_filesystem

**Comment by jiaweitao001** [comment] 2022-05-26 10:10
Hi @nathanpinotti, could you please paste your entire TF code block here? I cannot reproduce this error on my side.

**Comment by deBFM** [comment] 2023-02-07 13:44
The original example from https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_data_lake_gen2_filesystem
isn`t working at all.

`│ Error: checking for existence of existing File System "example" (Account "hsds2storageacc"): datalakestore.Client#GetProperties: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: error response cannot be parsed: {"" '\x00' '\x00'} error: EOF
`

Why was the bug Tag removed? This seems quite a bug to me.

**Comment by rcskosir** [comment] 2023-08-25 15:39
Thanks for taking the time to submit this issue. Unfortunately we aren’t able to investigate this without the relevant portions of your Terraform configuration file(s). We are going to close this issue - if you would like to [open a new issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/new/choose) please make sure that you fill out all the requested information so that we can try to reproduce the problem.

**Closed by rcskosir** 2023-08-25 15:39 UTC
Labels: waiting-response, service/data-lake, v/3.x
