### ISSUE TITLE
creation_source_database_id forces replacement even if not changed

### ISSUE THREAD

**Issue by elia-zakeke** [hashicorp/terraform-provider-azurerm#22407] opened 2023-07-07 13:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.5.2

### AzureRM Provider Version

3.64.0

### Affected Resource(s)/Data Source(s)

azurerm_mssql_database

### Terraform Configuration Files

```hcl
data "azurerm_mssql_database" "database" {
  name      = local.db_name
  server_id = var.sql_server_id
}


resource "azurerm_mssql_database" "failover" {
  name               = var.db_name
  server_id          = var.failover_sql_server_id
  collation          = local.db_collation
  license_type       = local.db_license_type
  sku_name           = local.db_sku_name

  create_mode                 = "Secondary"
  creation_source_database_id = data.azurerm_mssql_database.database.id
}
```

### Debug Output/Panic Output

```shell
module.image_service.azurerm_mssql_database.failover[0] must be replaced
-/+ resource "azurerm_mssql_database" "failover" {
      ~ creation_source_database_id         = "/subscriptions/xxxx/resourceGroups/xxx/providers/Microsoft.Sql/servers/xxxx/databases/xxxx" # forces replacement -> (known after apply) # forces replacement
            # (2 unchanged blocks hidden)
    }
```

### Expected Behaviour

No replacement should be triggered for azurerm_mssql_database.failover when data.azurerm_mssql_database.database.id is not changed.

### Actual Behaviour

Every time I run terraform plan/apply a replacement is planned/applied for azurerm_mssql_database.failover.

**Comment by sinbai** [comment] 2023-07-10 08:06
@elia-zakeke thanks for opening this issue. For `var.sql_server_id` and ` var.failover_sql_server_id`, those two are not the same server, right? Since the following tf configuration works fine on my side, could you please compare the difference with yours? Is it possible to provide the complete tf config to help repro/troubleshoot?

```

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
	  version = "3.64.0"
    }
  }
}


provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "test-0710"
  location = "eastus"
}

resource "azurerm_mssql_server" "test" {
  name                         = "acctest-sqlserver-0710"
  resource_group_name          = azurerm_resource_group.test.name
  location                     = azurerm_resource_group.test.location
  version                      = "12.0"
  administrator_login          = "mradministrator"
  administrator_login_password = "thisIsDog11"
}

resource "azurerm_mssql_database" "test" {
  name         = "acctest-db-0710"
  server_id    = azurerm_mssql_server.test.id
  collation    = "SQL_AltDiction_CP850_CI_AI"
  license_type = "BasePrice"
  max_size_gb  = 10
  sample_name  = "AdventureWorksLT"
  sku_name     = "GP_Gen5_2"

  storage_account_type = "Local"

  tags = {
    ENV = "Test"
  }
}

resource "azurerm_mssql_server" "test2" {
  name                         = "acctest-sqlserver-0710-2"
  resource_group_name          = azurerm_resource_group.test.name
  location                     = azurerm_resource_group.test.location
  version                      = "12.0"
  administrator_login          = "mradministrator"
  administrator_login_password = "thisIsDog11"
}


data "azurerm_mssql_database" "test" {
  name      = "acctest-db-0710"
  server_id = azurerm_mssql_server.test.id
}


resource "azurerm_mssql_database" "secondary" {
  name               = "acctest-secondary-0710"
  server_id          = azurerm_mssql_server.test2.id
  collation          = "SQL_AltDiction_CP850_CI_AI"
  license_type       = "BasePrice"
  sku_name           = "GP_Gen5_2"

  create_mode                 = "Secondary"
  creation_source_database_id = data.azurerm_mssql_database.test.id
}
```

**Comment by rcskosir** [comment] 2023-12-06 20:59
Thanks for opening this issue. Since time has passed and @sinbai was not able to reproduce this issue, I am going to mark this issue closed as “can’t reproduce”. If you are able to provide more information to help us reproduce this issue we may re-open this issue or open a new issue, thanks!

**Closed by rcskosir** 2023-12-06 20:59 UTC
Labels: waiting-response, service/mssql, v/3.x
