### ISSUE TITLE
Federation usage

### ISSUE THREAD

**Issue by Simondebb** [hashicorp/terraform-provider-azurerm#20623] opened 2023-02-23 11:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.1

### AzureRM Provider Version

3.44.1

### Affected Resource(s)/Data Source(s)

x

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: building account: could not acquire access token to parse claims: clientCredentialsToken: received HTTP status 400 with response: {"error":"unauthorized_client","error_description":"AADSTS700016: Application with identifier '***' was not found in the directory 'mydirectory'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.\r\nTrace ID: 37c28d1f-664c-43ee-b793-60eec36f2c00\r\nCorrelation ID: 0466990b-12a9-4d11-99d9-ad0d864bbc32\r\nTimestamp: 2023-02-21 14:42:29Z","error_codes":[700016],"timestamp":"2023-02-21 14:42:29Z","trace_id":"37c28d1f-664c-43ee-b793-60eec36f2c00","correlation_id":"0466990b-12a9-4d11-99d9-ad0d864bbc32","error_uri":"https://login.microsoftonline.com/error?code=700016"}
│ 
│   with provider["registry.terraform.io/hashicorp/azurerm"],
│   on provider.tf line 2, in provider "azurerm":
│    2: provider "azurerm" {
│ 
╵
```

**Comment by tombuildsstuff** [comment] 2023-02-23 17:04
hey @Simondebb 

Thanks for opening this issue.

Taking a look through here this appears to be a duplicate of #20546, which has been fixed via https://github.com/hashicorp/go-azure-sdk/pull/323 and incorporated into the provider via #20610 and will ship in `v3.45.0` of the Azure Provider - as such I've tagged this issue with the milestone so a comment will be left when this is released, but I'm going to close this issue for the moment.

Thanks!

**Closed by tombuildsstuff** 2023-02-23 17:04 UTC
Labels: bug, duplicate, authentication
