### ISSUE TITLE
azurerm_app_configuration_key responce can't be parsed \x00

### ISSUE THREAD

**Issue by sanderobdeijn** [hashicorp/terraform-provider-azurerm#16980] opened 2022-05-26 21:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.9

### AzureRM Provider Version

3.7.0

### Affected Resource(s)/Data Source(s)

azurerm_app_configuration_key

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "rg" {
  name     = "${var.project-name}-${terraform.workspace}"
  location = var.location
}

resource "azurerm_app_configuration" "appconf" {
  name                = "${var.prefix}-${terraform.workspace}-appconfiguration"
  resource_group_name = azurerm_resource_group.rg.name
  location            = var.location
  sku                 = "standard"
}

resource "azurerm_role_assignment" "appconf_dataowner" {
  scope                = azurerm_app_configuration.appconf.id
  role_definition_name = "App Configuration Data Owner"
  principal_id         = data.azurerm_client_config.current.object_id
}

resource "azurerm_app_configuration_key" "blob-Storage-config-assets-container-name" {
  configuration_store_id = azurerm_app_configuration.appconf.id
  key                    = "BlobStorageConfig:AssetsContainerName"
  value                  = "files"

  depends_on = [
    azurerm_role_assignment.appconf_dataowner
  ]
}
```

### Debug Output/Panic Output

```shell
https://gist.github.com/sanderobdeijn/38cb44c29547bce46027869498e75395
```

### Expected Behaviour

After performing terraform plan show current azurerm_app_configuration_key.

### Actual Behaviour

terraform can't seem to read current existence of a azurerm_app_configuration_key.
It returns a Original Error: autorest/azure: error response cannot be parsed: {"" '\x00' '\x00'} error: EOF

### Steps to Reproduce

1. Create a azurerm_app_configuration_key with terraform in an azure devops pipeline
2. Run terraform plan from a windows dev machine.

This might be a windows vs linux issue. The devops build agent runs on linux my local machine runs on windows.
the \x00 character seems to be a line ending character.

**Comment by sinbai** [comment] 2022-05-30 06:16
@sanderobdeijn thank you for opening this issue here. Unfortunately, I could not reproduce this error with the following `terraform configuration 1`. I am not sure if the error is caused by the role assignment not yet working when the `azurerm_app_configuration_key` is created due to the following screenshot mentioned in the [documentation](https://docs.microsoft.com/en-us/azure/azure-app-configuration/concept-enable-rbac#azure-built-in-roles-for-azure-app-configuration).  Could you try adding the role assignment to the `azurerm_resource_group` resource to see if the error goes away with `terraform configuration 2`?

![image](https://user-images.githubusercontent.com/39109137/170926463-602ededb-4d09-4b0a-a691-a2567e354181.png)


**terraform configuration 1:** 
```

provider "azurerm" {
  features {}
}

terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
	   version = "3.7.0"
    }
  }
}
resource "azurerm_resource_group" "test" {
  name     = "appconfig-sample"
  location = "eastus"
}

data "azurerm_client_config" "test" {
}

resource "azurerm_app_configuration" "test" {
  name                = "appconf-sample"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location
  sku                 = "standard"
}

resource "azurerm_role_assignment" "appconf_dataowner" {
  scope                = azurerm_app_configuration.test.id
  role_definition_name = "App Configuration Data Owner"
  principal_id         = data.azurerm_client_config.test.object_id
}

resource "azurerm_app_configuration_key" "test" {
  configuration_store_id = azurerm_app_configuration.test.id
  key                    = "acctest-ackey-01"
  label                  = "acctest-ackeylabel-01"
  value                  = "a test"
  
  depends_on = [
    azurerm_role_assignment.appconf_dataowner
  ]
}
```

**terraform configuration 2:** 
```
provider "azurerm" {
  features {}
}

terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
	   version = "3.7.0"
    }
  }
}
resource "azurerm_resource_group" "test" {
  name     = "appconfig-sample"
  location = "eastus"
}

data "azurerm_client_config" "test" {
}

resource "azurerm_role_assignment" "appconf_dataowner" {
  scope                = azurerm_resource_group.test.id
  role_definition_name = "App Configuration Data Owner"
  principal_id         = data.azurerm_client_config.test.object_id
}

resource "azurerm_app_configuration" "test" {
  name                = "appconf-sample"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location
  sku                 = "standard"
   depends_on = [
    azurerm_role_assignment.appconf_dataowner
  ]
}

resource "azurerm_app_configuration_key" "test" {
  configuration_store_id = azurerm_app_configuration.test.id
  key                    = "acctest-ackey-01"
  label                  = "acctest-ackeylabel-01"
  value                  = "a test"
}
```

**Comment by tombuildsstuff** [comment] 2022-05-30 06:48
This is a HTTP 403 which isn't being parsed correctly (which is tracked in #10858) - but this is a permissions issue where the Service Principal/User being used has access to the AppConfiguration via Resource Manager but doesn't have access to it's values via Data Plane (which is a separate permission):

```
GET /kv/BlobStorageConfig%3AAssetsContainerName?api-version=1.0 HTTP/1.1
Host: XXX.azconfig.io
User-Agent: Go/go1.18.1 (amd64-windows) go-autorest/v14.2.1 Azure-SDK-For-Go/0.0.0 appconfiguration/1.0 HashiCorp Terraform/1.1.9 (+https://www.terraform.io) Terraform Plugin SDK/2.10.1 terraform-provider-azurerm/dev pid-222c6c49-1b0a-5959-a213-6608f9eb8820
X-Ms-Correlation-Request-Id: c96ef33f-43bb-535a-40f5-9496c55d728a
Accept-Encoding: gzip: timestamp=2022-05-26T23:40:19.554+0200
2022-05-26T23:40:19.633+0200 [DEBUG] provider.terraform-provider-azurerm_v3.6.0_x5.exe: AzureRM Response for https://XXX.azconfig.io/kv/BlobStorageConfig%3AAssetsContainerName?api-version=1.0:
HTTP/2.0 403 Forbidden
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: DNT, X-CustomHeader, Keep-Alive, User-Agent, X-Requested-With, If-Modified-Since, Cache-Control, Content-Type, Authorization, x-ms-client-request-id, x-ms-useragent, x-ms-content-sha256, x-ms-date, host, Accept, Accept-Datetime, Date, If-Match, If-None-Match, Sync-Token, x-ms-return-client-request-id, ETag, Last-Modified, Link, Memento-Datetime, retry-after-ms, x-ms-request-id, x-ms-client-session-id, x-ms-effective-locale, WWW-Authenticate, traceparent, tracestate
Date: Thu, 26 May 2022 21:40:19 GMT
Server: openresty/1.17.8.2
Strict-Transport-Security: max-age=15724800; includeSubDomains
X-Ms-Correlation-Request-Id: c96ef33f-43bb-535a-40f5-9496c55d728a
X-Ms-Request-Id: d80036de-8331-4e94-9ec1-5e4d76f36c6b
Content-Length: 0: timestamp=2022-05-26T23:40:19.633+0200
2022-05-26T23:40:19.634+0200 [ERROR] vertex "azurerm_app_configuration_key.blob-Storage-config-assets-container-name" error: while checking for key's "BlobStorageConfig:AssetsContainerName" existence: appconfiguration.BaseClient#GetKeyValue: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: error response cannot be parsed: {"" '\x00' '\x00'} error: EOF
2022-05-26T23:40:19.635+0200 [ERROR] vertex "azurerm_app_configuration_key.blob-Storage-config-assets-container-name" error: while checking for key's "BlobStorageConfig:AssetsContainerName" existence: appconfiguration.BaseClient#GetKeyValue: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: error response cannot be parsed: {"" '\x00' '\x00'} error: EOF
2022-05-26T23:40:19.635+0200 [ERROR] vertex "azurerm_app_configuration_key.blob-Storage-config-assets-container-name (expand)" error: while checking for key's "BlobStorageConfig:AssetsContainerName" existence: appconfiguration.BaseClient#GetKeyValue: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: error response cannot be parsed: {"" '\x00' '\x00'} error: EOF
2022-05-26T23:40:19.637+0200 [INFO]  backend/local: plan operation completed
```

**Comment by tombuildsstuff** [comment] 2022-05-31 11:01
@sanderobdeijn 

Yeah #10858 is tracking correctly parsing these out of the base layer, which'll ensure that these errors are correctly raised as errors in the future as appropriate.

Since the root-cause of this is a permissions problem I'm going to close this out for the moment in favour of #10858 which will make this more visible - however you should be able to fix this by adding the permissions required for Data Plane (I believe the role is `App Configuration Data Owner`).

Thanks!

**Closed by tombuildsstuff** 2022-05-31 11:01 UTC
