### ISSUE TITLE
Rule swap in azure firewall

### ISSUE THREAD

**Issue by gregbaleyy** [hashicorp/terraform-provider-azurerm#25171] opened 2024-03-07 09:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.4

### AzureRM Provider Version

3.75.0

### Affected Resource(s)/Data Source(s)

azurerm_firewall_network_rule_collection, azurerm_firewall_application_rule_collection

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_virtual_network" "example" {
  name                = "testvnet"
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
}

resource "azurerm_subnet" "example" {
  name                 = "AzureFirewallSubnet"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefixes     = ["10.0.1.0/24"]
}

resource "azurerm_public_ip" "example" {
  name                = "testpip"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  allocation_method   = "Static"
  sku                 = "Standard"
}

resource "azurerm_firewall" "example" {
  name                = "testfirewall"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  sku_name            = "AZFW_VNet"
  sku_tier            = "Standard"

  ip_configuration {
    name                 = "configuration"
    subnet_id            = azurerm_subnet.example.id
    public_ip_address_id = azurerm_public_ip.example.id
  }
}

resource "azurerm_firewall_network_rule_collection" "example" {
  name                = "testcollection"
  azure_firewall_name = azurerm_firewall.example.name
  resource_group_name = azurerm_resource_group.example.name
  priority            = 100
  action              = "Allow"

  rule {
    name = "testrule"

    source_addresses = [
      "10.0.0.0/16",
    ]

    destination_ports = [
      "53",
    ]

    destination_addresses = [
      "8.8.8.8",
      "8.8.4.4",
    ]

    protocols = [
      "TCP",
      "UDP",
    ]
  }
  rule {
    name = "testrule2"

    source_addresses = [
      "10.5.0.0/16",
    ]

    destination_ports = [
      "53",
    ]

    destination_addresses = [
      "8.8.8.8",
      "8.8.4.4",
    ]

    protocols = [
      "TCP",
      "UDP",
    ]
  }
}
```

### Debug Output/Panic Output

```shell
No panic output

Since this week when I perform a Terraform plan against my Azure Firewall, rules are listed in random order in the rule collection and the same goes for rule parameters. If I apply this plan, real changes are done against the firewall which last more than 1 hour. 

What was previously detected as coherent between Terraform and reality now appears as a change.
```

### Expected Behaviour

```shell
No change
```

### Actual Behaviour

```hcl
# azurerm_firewall_network_rule_collection.rule["example"] will be updated in-place
  ~ resource "azurerm_firewall_network_rule_collection" "rule" {
        id                  = "..."
        name                = "testcollection"
        # (4 unchanged attributes hidden)

      ~ rule {
          ~ name                  = "testrule2" -> "testrule"
          ~ protocols             = [
              - "TCP",
                 "UDP",
              + "TCP",
            ]
          ~ source_addresses      = [
              - "10.5.0.0/16",
              + "10.0.0.0/16",
            ]
            # (5 unchanged attributes hidden)
        }
      ~ rule {
          ~ name                  = "testrule" -> "testrule2"
          ~ protocols             = [
              - "TCP",
                 "UDP",
              + "TCP",
            ]
          ~ source_addresses      = [
              - "10.0.0.0/16",
              + "10.5.0.0/16",
            ]
            # (5 unchanged attributes hidden)
        }
    }
```

**Comment by gregbaleyy** [comment] 2024-03-11 14:10
Hi, sorry I couldn't  reproduce this issue. I guess it's random.

**Comment by rcskosir** [comment] 2024-03-19 21:47
Thanks for taking the time to submit this issue. @wuxu92 was unable to reproduce this behavior. We’re going to close this issue for now, but if you run into this again with the latest Terraform and Provider versions please feel free to update the issue if you find any additional information that could help us replicate the scenario

**Closed by rcskosir** 2024-03-19 21:47 UTC
Labels: service/firewall, v/3.x
