### ISSUE TITLE
Support for Origin Groups with azurerm_cdn_endpoint

### ISSUE THREAD

**Issue by baileyn** [hashicorp/terraform-provider-azurerm#12699] opened 2021-07-22 15:07 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It seems that I am unable to configure the "DefaultOriginGroup" when creating multiple origins in an [azurerm_cdn_endpoint](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cdn_endpoint). I have imported existing resources and my plan is correct, but deploying to a new environment results in the following error:

```In order to enable Multi-Origin on this endpoint, please set DefaultOriginGroup.```

### New or Affected Resource(s)

* azurerm_cdn_endpoint

### Potential Terraform Configuration

```hcl
resource "azurerm_cdn_endpoint" "dynamic" {
  name = "${var.prefix}-cdn-${var.suffix}"
  resource_group_name = azurerm_resource_group.this.name
  location = "global"

  profile_name = azurerm_cdn_profile.this.name
  is_http_allowed = true
  is_https_allowed = true
  optimization_type = "GeneralWebDelivery"

  global_delivery_rule {
    cache_expiration_action {
      behavior = "BypassCache"
    }
  }

  delivery_rule {
    name = "RedirectToAuth"
    order = 1

    url_path_condition {
      match_values = [
        "/auth",
      ]
      operator = "BeginsWith"
    }
  }

  origin_host_header = substr(azurerm_api_management.this.gateway_url, 8, -1)
  origin {
    name = "default"
    host_name = substr(azurerm_api_management.this.gateway_url, 8, -1)
  }

  origin {
    name = "auth"
    host_name = var.sso_app_host_name
  }

  tags = {
    Owner = var.owner
    Product = var.app_name
  }
}

```

### Relevant Information

I have read through the [azurerm_cdn_endpoint documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cdn_endpoint), but I don't see any references to origin groups.

Additionally, I didn't notice until matching with the ARM template, but it seems that there's also not an `origin_group_override_action` or equivalent for my `delivery_rule` block.

**Comment by apeeters** [comment] 2021-08-24 10:04
This is a duplicate of #10771.

**Comment by WodansSon** [comment] 2024-04-25 04:17
Closed as duplicate.

**Closed by WodansSon** 2024-04-25 04:17 UTC
Labels: enhancement, service/cdn
