### ISSUE TITLE
Support for automatic key rotation in azurerm_mssql_server

### ISSUE THREAD

**Issue by white-james** [hashicorp/terraform-provider-azurerm#23667] opened 2023-10-24 09:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

I am writing a module to create a MS SQL Server with transparent data encryption with customer managed keys. I noticed there is no option to enable automatic key rotation. It seem this can only be done when enabling TDE after the server is created by setting auto_rotation_enabled to true in azurerm_mssql_server_transparent_data_encryption.

I think it would be better to enable key rotation at server creation time than try to change it after 

### New or Affected Resource(s)/Data Source(s)

azurerm_mssql_server

### Potential Terraform Configuration

```hcl
resource "azurerm_mssql_server" "example" {
  name                         = "example-resource"
  resource_group_name          = azurerm_resource_group.example.name
  location                     = azurerm_resource_group.example.location
  version                      = "12.0"
  administrator_login          = "Example-Administrator"
  administrator_login_password = "Example_Password!"
  minimum_tls_version          = "1.2"

  azuread_administrator {
    login_username = azurerm_user_assigned_identity.example.name
    object_id      = azurerm_user_assigned_identity.example.principal_id
  }

  identity {
    type         = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.example.id]
  }

  primary_user_assigned_identity_id            = azurerm_user_assigned_identity.example.id
  transparent_data_encryption_key_vault_key_id = azurerm_key_vault_key.example.id
  auto_rotation_enabled                        = "true"
}
```

**Comment by rcskosir** [comment] 2023-10-24 16:28
@white-james Thank you for taking the time to open this feature request!

**Comment by katbyte** [comment] 2024-10-31 15:18
I'm going to close this as it is a duplicate of #25632 and that issue has more detail/links to documentation, please follow that issue for updates - thanks!

**Closed by katbyte** 2024-10-31 15:18 UTC
Labels: enhancement, service/mssql
