### ISSUE TITLE
Error: Expected ID to be in the format `{scope}/providers/Microsoft.Authorization/locks/{name} - got 1 segments

### ISSUE THREAD

**Issue by mpjtaylor** [hashicorp/terraform-provider-azurerm#14536] opened 2021-12-08 09:15 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform 1.0.9
AzureRM 2.88.0 / 2.88.1

### Affected Resource(s)

Error: parsing "network_interface_lock": parsing scope prefix: unable to find the scope prefix from the value "network_interface_lock" with the regex "^((.){1,})/providers/Microsoft.Authorization/locks/(.){1,}"
Trying to roll back to 2.85
Error: Expected ID to be in the format `{scope}/providers/Microsoft.Authorization/locks/{name} - got 1 segments

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```
resource "azurerm_management_lock" "network_interface" {
  name       = "network_interface_lock"
  scope      = azurerm_network_interface.virtualmachine.id
  lock_level = "CanNotDelete"
  notes      = "Locked because it's managed by Terraform"
  depends_on = [
    azurerm_network_interface.virtualmachine
  ]
}
### Expected Behaviour

VMs should have removed or added the lock to the NIC
### Actual Behaviour
Plan errored

Plan errored
### Steps to Reproduce

1. `terraform plan`

**Comment by patrickjahns** [comment] 2021-12-08 15:38
Maybe a duplicate of https://github.com/hashicorp/terraform-provider-azurerm/issues/14495 ?

**Comment by stephybun** [comment] 2021-12-09 09:20
Duplicate of #14495, please subscribe to that issue for updates.

**Closed by stephybun** 2021-12-09 09:20 UTC
