### ISSUE TITLE
When updated terraform version from 1.3.5 to 1.5.5, alert for azure are not triggering with log V2

### ISSUE THREAD

**Issue by sgrmisra23** [hashicorp/terraform-provider-azurerm#23556] opened 2023-10-13 12:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.5

### AzureRM Provider Version

3.35.0

### Affected Resource(s)/Data Source(s)

azure alerts

### Terraform Configuration Files

```hcl
azurerm_monitor_scheduled_query_rules_alert_v2
```

### Debug Output/Panic Output

```shell
Can't produce debug due to client restriction
```

### Expected Behaviour

Alert should trigger when windows vm is stopped, when created from azure portal it is working fine, issue started occuring since I updated terraform version from 1.3.5 to 1.5.5

### Actual Behaviour

Alerts do not trigger when condition is met for heartbeat down issue

### Steps to Reproduce

terraform apply

**Comment by teowa** [comment] 2023-10-17 10:57
Hi @sgrmisra23 , thanks for submitting this issue.
Usually the terraform version should not affect the resource properties created, and the created resource should have the same properties as specified in the config. Could you please provide the TF config or reproduce the issue?

**Comment by rcskosir** [comment] 2024-02-09 18:35
Thanks for opening this issue. Since time has passed and @teowa was not able to reproduce this issue, I am going to mark this issue closed as “can’t reproduce”. If you are able to provide more information to help us reproduce this issue we may re-open this issue or open a new issue, thanks!

**Closed by rcskosir** 2024-02-09 18:35 UTC
Labels: waiting-response, service/monitor, v/3.x
