### ISSUE TITLE
Feature request - Provide a way to look up list of private dns zones linked to a given VNET, OR, private DNS zone created by AKS

### ISSUE THREAD

**Issue by eehret** [hashicorp/terraform-provider-azurerm#9097] opened 2020-10-30 01:05 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I've run into a use case where I need to be able to look up a list of private DNS zones that have been linked to a given VNET.  There doesn't seem to be a way to retrieve that information currently using the `azurerm_virtual_network` data provider.  Someone please correct me if I'm wrong about that.

A little more context:
I created a private AKS cluster.  When you do that, the azurerm_kubernetes_cluster provider appears to create a randomly named private DNS zone for the private endpoint.  Unfortunately the azurerm_kubernetes_cluster data provider doesn't seem to expose the name of that private DNS zone, so I can't look it up that way either.
I need this information because in a later step of my build process I need to link that zone to another pre-existing VNET.

For my immediate use case an attribute on `azurerm_kubernetes_cluster` exposing the name of the private DNS zone that it created would possibly do the job.   However, I feel like ideally there should be a way to look this up independently using the `azurerm_virtual_network` and/or the `azurerm_private_dns_zone` data providers would be a more flexible and non-kubernetes specific, possibly addressing other similar use cases.

### New or Affected Resource(s)
* `azurerm_kubernetes_cluster`
* `azurerm_private_dns_zone`
* `azurerm_virtual_network`

### References

* #0000

**Comment by stephybun** [comment] 2022-02-15 15:24
Hi @eehret,

Thanks for raising this issue. Since it has been possible to set and retrieve the `private_dns_zone_id` from the `azurerm_kubernetes_cluster` resource since **v2.47.0** of the provider I am going to close this issue. Thanks!

**Closed by stephybun** 2022-02-15 15:24 UTC
Labels: enhancement, service/kubernetes-cluster

**Comment by eehret** [comment] 2022-02-15 21:59
Unfortunately this does not meet my requirements because, as you can see here https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/private_dns_zone_virtual_network_link,  you cannot create a VNET link to a private DNS zone using its resource ID.   Only the private DNS zone name and resource group name are supported.

The really crucial part of my issue description is:
"I need this information because in a later step of my build process I need to link that zone to another pre-existing VNET."

If it was possible to do it using the resource ID only, then I would not have a problem.

Sorry if it was not clear from what I wrote... can you please reopen, now that you have more context?

**Comment by stephybun** [comment] 2022-02-16 07:45
@eehret, thank you for the additional context. If I understand correctly your issue would be resolved if the resource `azurerm_private_dns_zone_virtual_network_link` could take the DNS zone ID as an argument, if that change were made then there would be no further change required in the Kubernetes cluster resource. In which case I would consider this issue a duplicate of #13503 but perhaps I am still missing something here?

**Comment by eehret** [comment] 2022-02-18 02:09
@stephybun ,
Fair point.  I suppose the question is, which issue would get resolved first?  :)

If the other feature request does get implemented then yes, this one would no longer be required.


Thanks


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
