### ISSUE TITLE
Azure Storage dns_endpoint_type -> forces replacement

### ISSUE THREAD

**Issue by sai-gunaranjan** [hashicorp/terraform-provider-azurerm#25424] opened 2024-03-27 00:04 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.3.9

### AzureRM Provider Version

3.97.1

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
In AzureRM Storage account by setting `dns_endpoint_type` to `null` its forcing redeployment resulting in deleting and recreation of storage accounts
```

### Debug Output/Panic Output

```shell
resource "azurerm_storage_account" "sa" {
      + dns_endpoint_type                  = "Standard" # forces replacement
      ~ id                                 = "/subscriptions/1234455/resourceGroups/somergname/providers/Microsoft.Storage/storageAccounts/accountname" -> (known after apply)
      + large_file_share_enabled           = (known after apply)
        name                               = "accountname"
```

### Expected Behaviour

no change as that field was not defined.

### Actual Behaviour

terraform delete and recreated the accounts during the Terraform apply stage. however running Terraform plan it did not show these accounts were going to be recreated

### Steps to Reproduce

Terraform Apply using 1.3.9 and AzureRM provider 3.97.1

**Comment by sai-gunaranjan** [comment] 2024-03-27 00:05
https://github.com/hashicorp/terraform-provider-azurerm/pull/25367

**Comment by magodo** [comment] 2024-03-27 06:45
@sai-gunaranjan Can you please elaborate more about the reproduce steps, as I assume this issue has been resolved by #25367 already?

**Comment by sai-gunaranjan** [comment] 2024-03-28 00:29
@manicminer @magodo we are also having trouble reproducing the issue now in our environments. 
these were very old storage accounts created back on 2020 (Provider version 2.x) TF only deleted storage accounts of with `account_kind="StorageV2"` and `account_tier                   = "Standard"` I can share screenshots privately if needed. I will try a few more combinations and let you know.
cc: @aharden

**Comment by robbert-nlo** [comment] 2024-04-02 11:38
Hi!

I'm seeing this behaviour too when attempting to upgrade from 3.94.0 to 3.97.1 (never used/tried 3.97.0):

Plan snippet:
```
  # module.hub["westeurope"].azurerm_storage_account.nw must be replaced
-/+ resource "azurerm_storage_account" "nw" {
      ~ access_tier                        = "Hot" -> (known after apply)
      + dns_endpoint_type                  = "Standard" # forces replacement
      ~ id                                 = "/subscriptions/11111111-900a-46fa-a0d9-111111111111/resourceGroups/rg-app-hub-stg-we/providers/Microsoft.Storage/storageAccounts/stappnwstgwe" -> (known after apply)
      + large_file_share_enabled           = (known after apply)
        name                               = "stappnwstgwe"

(...)
```

Code snippets:

```
module "hub" {
  source = "../modules/hub"

  for_each = { for cfg in module.var.conf_by_app.app : cfg.location => cfg }

  application     = each.value.app
  environment     = each.value.environment
  location        = each.key
  address_space   = each.value.address_space
  resource_groups = module.sb.azurerm_resource_group
```

../modules/hub:
```
resource "azurerm_storage_account" "nw" {
  name                = "st${var.application}nw${var.environment}${local.location_table[var.location]}"
  location            = var.location
  resource_group_name = var.resource_groups["${local.module_name}-${local.location_table[var.location]}"].name

  account_tier                     = "Standard"
  account_replication_type         = "LRS"
  allow_nested_items_to_be_public  = false
  cross_tenant_replication_enabled = false
  min_tls_version                  = "TLS1_2"

  lifecycle { ignore_changes = [tags] }
}
```

**Comment by tombuildsstuff** [comment] 2024-04-02 13:27
@robbert-nlo @sai-gunaranjan out of interest are you running `terraform plan` / `terraform apply` with `-refresh=false` by any chance? If so, can you try running a `terraform plan` without `-refresh=false` and let us know if that's any different? If not, would you mind providing the output from `terraform version`?

Thanks!

**Comment by KenSpur** [comment] 2024-04-02 13:36
I have the same issue when running a plan on version `3.97`, switching back to `3.96` removes the replace action on the storage account.

Running an apply on version `3.96` and then planning version `3.97` adds back the replace action on the storage account because of:

```
+ dns_endpoint_type                  = "Standard" # forces replacement
```

**Comment by sai-gunaranjan** [comment] 2024-04-02 23:13
@tombuildsstuff yes. in this instance we did have in `terraform Apply` we have `-refresh=false` 
TF version when the incident occurred was `1.3.9`

**Comment by sai-gunaranjan** [comment] 2024-04-02 23:43
I am able to reproduce the issue now, earlier in our test envi we did not use `-refresh=false`
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/16096792/64534c73-9dd6-42d4-a044-c925fdfa0bc1)

**Comment by tombuildsstuff** [comment] 2024-04-03 06:52
@sai-gunaranjan per [the Terraform docs](https://developer.hashicorp.com/terraform/cli/commands/plan#planning-options):

> Disables the default behavior of synchronizing the Terraform state with remote objects before checking for configuration changes. This can make the planning operation faster by reducing the number of remote API requests. However, setting refresh=false causes Terraform to ignore external changes, which could result in an incomplete or incorrect plan.

Which is what's happening here - as such you'll need to do a `terraform apply` without `-refresh=false` here in order to pick up this change. As a general rule `-refresh=false` isn't intended to be used for daily usage since it doesn't track changes made outside of Terraform (such as this one, where the API has introduced a new value for this field) - and as such bug fixes to workaround incorrect API responses (as is happening here) won't be picked up with `-refresh=false` set.

Since this issue is specific to using `-refresh=false` and so removing that will fix this issue, I'm going to go ahead and close this one out as resolved.

Thanks!

**Closed by tombuildsstuff** 2024-04-03 06:52 UTC
Labels: question, service/storage, v/3.x
