### ISSUE TITLE
[3.114.0][azurerm_redis_cache] Changing enable_non_ssl_port to non_ssl_port_enabled.

### ISSUE THREAD

**Issue by veerasuraj** [hashicorp/terraform-provider-azurerm#27145] opened 2024-08-22 14:48 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.3.10

### AzureRM Provider Version

3.114.0

### Affected Resource(s)/Data Source(s)

azurerm_redis_cache

### Terraform Configuration Files

```hcl
resource "azurerm_redis_cache" "main" {
  name                 = "idpe-${var.cluster_name}"
  location             = var.location
  resource_group_name  = local.resource_group
  capacity             = var.capacity
  family               = "P"
  sku_name             = "Premium"
  non_ssl_port_enabled = true
  minimum_tls_version  = "1.2"
  subnet_id            = azurerm_subnet.main.id
  redis_configuration {
    authentication_enabled = false

  }
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

  # module.redis.azurerm_redis_cache.main will be updated in-place
  ~ resource "azurerm_redis_cache" "main" {
      ~ enable_non_ssl_port           = true -> false

    
    Pls note that even after replacing this argument with non_ssl_port_enabled, terraform plan is throwing a warning pointing out still to enable_non_ssl_port and applying a change in value, even after not doing so. 
    
    Also, we did update the azurerm version to 3.116.0 to test, but the issue remains the same. Hope to get a fix for this at your availability.

![Screenshot 2024-08-22 at 9 45 15 AM](https://github.com/user-attachments/assets/898c74f0-e3fd-4fed-bc50-3b678e3da85d)

**Comment by stephybun** [comment] 2024-08-22 16:05
Duplicate of #26943, please subscribe to #26943 for updates

**Closed by stephybun** 2024-08-22 16:05 UTC
Labels: service/redis, v/3.x
