### ISSUE TITLE
os_disk tags do not update when tags block is updated.

### ISSUE THREAD

**Issue by Jeff8247** [hashicorp/terraform-provider-azurerm#18981] opened 2022-10-25 23:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.3

### AzureRM Provider Version

3.28.0

### Affected Resource(s)/Data Source(s)

azurerm_linux_virtual_machine

### Terraform Configuration Files

```hcl
#Create VM
resource "azurerm_linux_virtual_machine" "linux" {
  name                  = "CLD${random_integer.this.result}"
  location              = data.azurerm_resource_group.resource_group_id.location
  resource_group_name   = data.azurerm_resource_group.resource_group_id.name
  network_interface_ids = [azurerm_network_interface.linux.id]
  size                  = "Standard_B1ms"
  provision_vm_agent    = true

  os_disk {
    name                 = "CLD${random_integer.this.result}-OsDisk"
    caching              = "ReadWrite"
    storage_account_type = "StandardSSD_LRS"
    disk_size_gb         = "30"
  }

  source_image_reference {
    publisher = "Canonical"
    offer     = "0001-com-ubuntu-server-focal"
    sku       = "20_04-lts-gen2"
    version   = "latest"
  }

  lifecycle {
    ignore_changes = [source_image_reference]
  }

  computer_name                   = "CLD${random_integer.this.result}"
  admin_username                  = "nswhadm"
  admin_password                  = azurerm_key_vault_secret.this.value
  disable_password_authentication = false

  admin_ssh_key {
    username   = "nswhadm"
    public_key = "ssh-rsa MYKEY"
  }

  boot_diagnostics {
    storage_account_uri = "https://MYBLOB.blob.core.windows.net/"
  }

  tags = {
    Environment = "DEV"
    Name        = "CLD${random_integer.this.result}"
    Thisis      = "Test"
  }
}
```

### Debug Output/Panic Output

```shell
No error per se. However whenever the tags block is updated post deploy the os_disk tags do not get updated to the same
```

### Expected Behaviour

Tags for VM shell and secondary disks all get updated and I expect the os_disk gets updated with the same tags as well

### Actual Behaviour

os_disk tags do not get updated

### Steps to Reproduce

1) Deploy VM with appropriate tags.
2) Make amendments to existing tags and adding new tags to the VM block
3) Run terraform apply again and all tags get updated with the exception of the os_disk

**Comment by myc2h6o** [comment] 2022-10-26 02:34
Hi @Jeff8247 This is currently by design due to api design. There is a same issue #8162 open for discussion, would you mind subscribing to it for update

**Comment by tombuildsstuff** [comment] 2022-10-26 12:20
As @myc2h6o has mentioned this is by design in the Azure API and there's a feature request tracking this in #8162, as such I'm going to close this in favour of #8162, would you mind subscribing to that issue for updates? Thanks!

**Closed by tombuildsstuff** 2022-10-26 12:20 UTC
