### ISSUE TITLE
azurerm_app_service transient error - "RepoUrl VSTSRM is not supported"

### ISSUE THREAD

**Issue by devedse** [hashicorp/terraform-provider-azurerm#9007] opened 2020-10-23 13:23 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform version: `0.13.4`

### Affected Resource(s)

azurerm: `version = "=2.30.0"`

### Terraform Configuration Files

```
resource "azurerm_function_app" "azureblobfunction" {
  name                       = "${module.global_variables.applicationName}-azureblobfunction-${var.environment}"
  location                   = azurerm_resource_group.resourcegroup.location
  resource_group_name        = azurerm_resource_group.resourcegroup.name
  app_service_plan_id        = azurerm_app_service_plan.plan.id
  #storage_connection_string = azurerm_storage_account.azureblobfunction_storage.primary_connection_string
  storage_account_name       = azurerm_storage_account.azureblobfunction_storage.name
  storage_account_access_key = azurerm_storage_account.azureblobfunction_storage.primary_access_key
  
  os_type                    = "linux"
  version                    = "~3"

  site_config {
    always_on                = true
    
    ftps_state = "Disabled"
  }

  app_settings = {
    "FUNCTIONS_WORKER_RUNTIME"              = "dotnet"
    "WEBSITE_RUN_FROM_PACKAGE"              = "1"
    "WEBSITES_ENABLE_APP_SERVICE_STORAGE"   = "true"
    "WEBSITE_ENABLE_SYNC_UPDATE_SITE"       = "true"
    "WEBSITE_NODE_DEFAULT_VERSION"          = "10.14.1"
    "APPINSIGHTS_INSTRUMENTATIONKEY"        = ""
    "azuresearch_storage_connectionstring"  = azurerm_storage_account.azuresearch_storage.primary_blob_connection_string
    "ApiKey"                                = var.*******
    "BaseUrl"                               = "https://${azurerm_app_service.*******.default_site_hostname}"
  }

  https_only = true
  identity {
    type = "SystemAssigned"
  }
}
```

### Debug Output

```
Error: failed to create App Service Source Control for "*******-azureblobfunction-dev" (Resource Group ""*******-dev"): web.AppsClient#CreateOrUpdateSourceControl: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="Operation not supported: RepoUrl VSTSRM is not supported." Details=[{"Message":"Operation not supported: RepoUrl VSTSRM is not supported."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","ExtendedCode":"51024","Message":"Operation not supported: RepoUrl VSTSRM is not supported.","MessageTemplate":"Operation not supported: {0}","Parameters":["RepoUrl VSTSRM is not supported."]}}]

  on azurefunction.tf line 51, in resource "azurerm_function_app" "azureblobfunction":
  51: resource "azurerm_function_app" "azureblobfunction" {
```

### Panic Output

N/A

### Expected Behavior

I would expect the deployment to succeed.

### Actual Behavior

The deployment did not succeed

### Steps to Reproduce

1. `terraform apply`
2. Deploy an Azure blob function with the following Azure DevOps task:
```
        - task: AzureFunctionApp@1
          displayName: 'Azure functions app deploy'
          inputs:
            azureSubscription: '${{ parameters.AZURESUBSCRIPTION }}'
            appType: functionApp
            appName: '${{ parameters.PREFIX }}"*******-azureblobfunction-${{ parameters.ENVIRONMENT }}'
            package: '$(System.ArtifactsDirectory)/dropAzureBlobFunction/blob$(Build.BuildId).zip'
```

### Important Factoids

Deploying to Azure West Europe

### References

The following issue is about the same problem:
https://github.com/terraform-providers/terraform-provider-azurerm/issues/8171

This topic contains a lot more information on this subject.

**Comment by devedse** [comment] 2020-10-27 12:37
Hi @tombuildsstuff ,

As you asked I created the issue above :).

The strange thing is that this happens sometimes and sometimes it simply works without any code changes. I've been running into this issue when deploying an AppService and an Azure Function.

**Comment by ruankr** [comment] 2020-11-03 10:24
We are also getting this constantly. I've tried a combination of the suggested fixes none seem to work, the issue just keeps happening.

Tried adding below, no affect:

    lifecycle {
      ignore_changes = [
        app_settings["WEBSITE_RUN_FROM_PACKAGE"],
        app_settings["MSDEPLOY_RENAME_LOCKED_FILES"],
        site_config["scm_type"],
        source_control,
      ]

Also, tried adding source-control block, still no affect:

        source_control {
            branch             = "master"
            manual_integration = false
            repo_url           = "VSTSRM"
            rollback_enabled   = false
            use_mercurial      = false
        }

Strangely, running terraform for a second time causes it to succeed. Issue, is we have several function apps in the same terraform plan, so it will fail at the first function on the first run, fail on the second function on the second run etc. So have to run terraform across our environments several times just for a single run to succeed. Only happening after upgrading to 2.31 provider, might consider downgrading back to 2.22.

**Comment by csi-lund** [comment] 2020-11-24 12:57
I also see this behaviour on function deployment on provider 2.36. A simple re-run of the step work. Did the downgrade to 2.22 work? It quite annoying having to usher the release out.

**Comment by devedse** [comment] 2020-11-27 15:14
Just leaving a comment here so the bot doesn't close the issue.

**Comment by devedse** [comment] 2020-11-27 15:22
@katbyte @tombuildsstuff , guys I know you're busy with a lot of things but could one of you maybe take a look at this issue? Lately there's a lot of issues being created with actual underlying bugs that never get resolved.

**Comment by jeanpaulsmit** [comment] 2020-11-27 15:35
+1 on 2.37 and a redeploy solves the issue, but it would be really nice if this can be fixed.

**Comment by jornbeyers** [comment] 2020-12-15 11:29
+1 on 2.39. Redeployment usually solves the issue but not always.

**Comment by dwoldo** [comment] 2021-01-05 22:09
Got this too. Any update? This causes CI/CD issues.

**Comment by romeomorcia** [comment] 2021-01-06 10:45
I'm having the same issues and after few testing on development, it looks like that this error appears ONCE every n hours.
What i mean is that if the last time you applied the changes it was a day ago, it will for sure trigger this error.
If after first error you deploy, you will not have the error. Same if you try 2 hours after.

I did not make testing on a day scale but looks like it depends after how much you try to redeploy using the same state file.

PS: State file on azure storage.

**Comment by jeanpaulsmit** [comment] 2021-01-06 11:09
Having the same approach regarding tfstate file, but I cannot confirm it happening every once so many hours. I've seen it happen within 15 minutes again, and also not showing up when deploying exactly the same stuff to a different region (using Azure DevOps).
Feels quite random to me, although there must be some pattern/reason.

**Comment by mattduguid** [comment] 2021-01-12 22:05
We are using Azure DevOps to release the code and had the same issue where every 2nd run it would fail on resource "azurerm_function_app" with error "...RepoUrl VSTSRM is not supported..."

We using terraform v0.13.4 with hashicorp/azurerm v2.31.1 and followed suggestions in this article https://github.com/terraform-providers/terraform-provider-azurerm/issues/8171 to add ***all** of the following and problem resolved for us,

resource "azurerm_function_app" "abc" {
  ...
  site_config {
    ...
    scm_type = "VSTSRM"
    ...
  }
  ...
  lifecycle {
    ignore_changes = [
      app_settings["WEBSITE_RUN_FROM_PACKAGE"],
      site_config["scm_type"] 
    ] 
  }
  ...
}

**Comment by pauska** [comment] 2021-01-27 18:16
This still happens, with Terraform 0.14.5 and AzureRM 2.44.0. The workaround provided by @mattduguid works for us, but I really do not enjoy having ignore_changes present as it could lead to config going out of sync.

**Comment by Jsoconno** [comment] 2021-02-23 00:32
I can confirm that this is still happening with terraform version 0.12.x and azurerm provider 2.44.0 as well.

My issue was solved by waiting and redeploying the same exact artifact to the same environment under the same conditions.

**Comment by jeanpaulsmit** [comment] 2021-02-23 08:53
I haven't had this issue since I moved to `TF 0.14.6` and `azurrm 2.47`.
So it seems it's not an azurerm thing, but a Terraform engine thing?

**Comment by ruankr** [comment] 2021-07-02 08:13
On version 5.13/1 of terraform and 2.44 of the Azure provider and still seeing this issue. Is there no solution planned for this?

**Comment by StefanSchoof** [comment] 2021-08-30 09:33
I upgraded my azurerm to 2.74 and in my case the error is now gone.

**Comment by ruankr** [comment] 2021-08-31 07:12
> I upgraded my azurerm to 2.74 and in my case the error is now gone.

What happens if you make a change (outside of terraform) to the function and then run terraform again? Issue we found is subsequent runs work, however as we deploy code from Azure Devops this changes something around the scm_type which we cannot control. Running terraform again then implies there is a change and then it fails on the first run. Re-running terraform a second time will work and as long as no other changes are made, continue to do so. I have not upgraded to a later provider yet, but will attempt to do this at some point in hope it really is fixed.

**Comment by StefanSchoof** [comment] 2021-08-31 07:35
I have also a DevOps Deployment for the function. Since the system is now live, I can not do this tests. But I can be right and I did have not this case after the upgrade. (On the side note, I also upgraded tf to 1.0.5). Will try to test this when I can.

**Comment by erbeh77** [comment] 2021-12-01 19:09
Same issue with the latest version 2.87.0 azurerm:
    scm_type                    = "VSTSRM"

**Comment by tombuildsstuff** [comment] 2021-12-01 20:29
👋 

The upcoming version 3.0 of the Azure Provider introduces new resources covering App Service to better represent the Service in Terraform. These new resources are now available as an opt-in Beta ([more information can be found here](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/3.0-app-service-beta)) - we'd encourage you to try these new resources out and give feedback.

As these resources are superseding the existing `azurerm_app_service` resource, we'll be deprecating that resource in v3.0 of the Azure Provider (whilst it'll remain available, it'll be feature-frozen) - as such we'd encourage you to try out the new resources and provide feedback where possible (including on if this is fixed in the newer resources) to ensure that this is correctly captured in the new resources.

Thanks!

**Comment by rcskosir** [comment] 2023-08-03 14:50
Thanks again for opening this issue. As noted above, the azurerm_app_service resource is deprecated and will be removed in v4.0 - so we suggest moving to the azurerm_linux_web_app and azurerm_windows_web_app resources instead.
If this is still an issue with the 3.x version of the provider for azurerm_linux_web_app and azurerm_windows_web_app resources please do let us know by opening a new issue, thanks!

**Closed by rcskosir** 2023-08-03 14:50 UTC
Labels: bug, service/app-service
