### ISSUE TITLE
 terraform-provider-azurerm_v2.93.1_x5 crash

### ISSUE THREAD

**Issue by tikicoder** [hashicorp/terraform-provider-azurerm#15149] opened 2022-01-27 14:32 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

terrafor
m -v
Terraform v1.1.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.15.0
+ provider registry.terraform.io/hashicorp/azurerm v2.93.1
+ provider registry.terraform.io/hashicorp/random v3.1.0

### Affected Resource(s)

resource "azurerm_bastion_host" "this" {
  name                = "${var.bastion_vnet}-bastion"
  tags                = var.tags
  location            = data.azurerm_resource_group.this_rg.location
  resource_group_name = data.azurerm_resource_group.this_rg.name
  
  sku = "Standard" # Standard is required for Bastion AAD

  ip_configuration {
    name                 = "configuration"
    subnet_id            = azurerm_subnet.this_subnet.id
    public_ip_address_id = azurerm_public_ip.this_publicip.id
  }
}

Error: Plugin did not respond
│
│   with module.bastion.azurerm_bastion_host.this,
│   on ../../../../modules/networking/bastion/main.tf line 138, in resource "azurerm_bastion_host" "this":
│  138: resource "azurerm_bastion_host" "this" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with module.base_subscription.module.bastion.azurerm_bastion_host.this,
│   on ../../../../modules/networking/bastion/main.tf line 138, in resource "azurerm_bastion_host" "this":
│  138: resource "azurerm_bastion_host" "this" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

Stack trace from the terraform-provider-azurerm_v2.93.1_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x45a1c7d]

goroutine 1414 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/network.resourceBastionHostRead(0xc001f5ac00, {0x559a880, 0xc000cac380})
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/internal/services/network/bastion_host_resource.go:255 +0x5dd
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x5e760e3, {0x657f318, 0xc002ade300}, 0x24, {0x559a880, 0xc000cac380})
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:346 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000f15500, {0x657f318, 0xc002ade300}, 0xc0010eb2b0, {0x559a880, 0xc000cac380})
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:635 +0x35b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc000110588, {0x657f318, 0xc002ade300}, 0xc002ade380)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:576 +0x534
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0001a6700, {0x657f3c0, 0xc001d36270}, 0xc00144c1e0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server/server.go:553 +0x3b0
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x5adac20, 0xc0001a6700}, {0x657f3c0, 0xc001d36270}, 0xc00144c180, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00027f340, {0x65cdac8, 0xc0001fe000}, 0xc000944120, 0xc00101f440, 0xab31910, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0xc6f
google.golang.org/grpc.(*Server).handleStream(0xc00027f340, {0x65cdac8, 0xc0001fe000}, 0xc000944120, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1617 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:940 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:938 +0x294

Error: The terraform-provider-azurerm_v2.93.1_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Steps to Reproduce

1. I terraform init my existing environment to upgrade from 2.92 to 2.93.1 
2. terraform plan --var-file var.tfvars

The bastion is existing and is already set to standard with native preview enabled.

**Comment by tombuildsstuff** [comment] 2022-01-27 16:54
Duplicate of #15058 which has been fixed by #15074 / will ship in 2.92

**Closed by tombuildsstuff** 2022-01-27 16:54 UTC
Labels: bug, crash
