### ISSUE TITLE
Please implement Easy Auth - Support Auth v2 as soon as possible

### ISSUE THREAD

**Issue by dr-dolittle** [hashicorp/terraform-provider-azurerm#14201] opened 2021-11-16 08:03 UTC
As the support for Easy Auth v1 will soon be removed (December) please implement https://github.com/hashicorp/terraform-provider-azurerm/issues/12928 as soon as possible. This is now open for over three months and will soon cause issues if not resolved.

Thanks,
Johannes

**Comment by aristosvo** [comment] 2021-11-16 08:34
Hi Johannes, @dr-dolittle,

I'll take a closer look this week to see what I can do to fix the current generation `web apps`, for a more detailed explanation of your (future) options see #12928.

As this is a duplicate of mentioned #12928, I'll close this issue.

**Closed by aristosvo** 2021-11-16 08:34 UTC
