### ISSUE TITLE
azurerm_api_management resource does not support deploying standardv2 SKU

### ISSUE THREAD

**Issue by thenukasandeepa** [hashicorp/terraform-provider-azurerm#26362] opened 2024-06-18 03:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.7

### AzureRM Provider Version

3.108.0

### Affected Resource(s)/Data Source(s)

azurerm_api_management

### Terraform Configuration Files

```hcl
I have encountered an issue where the azurerm_api_management resource in the Terraform Azure Provider does not support the standardv2 SKU. This limitation is causing problems in our infrastructure deployment, as we need to utilize the standardv2 SKU for our API Management resources.

Suggested Solution:
Please add support for the standardv2 SKU in the azurerm_api_management resource within the Terraform Azure Provider.

Thank you for addressing this issue. If more information or clarification is needed, please let me know.
```

### Debug Output/Panic Output

```shell
│ Error: invalid value for sku_name (This is not a valid Api Management sku name.)
│ 
│   with module.apim.azurerm_api_management.apim,
│   on ../../modules/terraform-module-azure-api-mgt/r-api-management.tf line 8, in resource "azurerm_api_management" "apim":
│    8:   sku_name        = var.sku_name
```

### Expected Behaviour

The azurerm_api_management resource should successfully create an API Management instance with the standardv2 SKU.

### Actual Behaviour

│ Error: invalid value for sku_name (This is not a valid Api Management sku name.)
│ 
│   with module.apim.azurerm_api_management.apim,
│   on ../../modules/terraform-module-azure-api-mgt/r-api-management.tf line 8, in resource "azurerm_api_management" "apim":
│    8:   sku_name        = var.sku_name

### Steps to Reproduce

Define an azurerm_api_management resource with the standardv2 SKU in a Terraform configuration file:

hcl
Copy code
resource "azurerm_api_management" "example" {
  name                = "example-apim"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  publisher_name      = "Example"
  publisher_email     = "example@example.com"
  sku_name            = "standardv2" # The problematic SKU
}

Run terraform apply.

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management

**Comment by stephybun** [comment] 2024-06-18 05:15
Duplicate of #25445

**Closed by stephybun** 2024-06-18 05:15 UTC
Labels: enhancement, service/api-management, v/3.x
