### ISSUE TITLE
azurerm_mysql_flexible_server internal server error with delegated_subnet_id 

### ISSUE THREAD

**Issue by Ashu2229** [hashicorp/terraform-provider-azurerm#22894] opened 2023-08-10 09:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.3.2

### AzureRM Provider Version

3.25.0

### Affected Resource(s)/Data Source(s)

azurerm_mysql_flexbile_server

### Terraform Configuration Files

```hcl
provider "azurerm" {
    features {}
  }
  
  resource "azurerm_resource_group" "example" {
    name     = "example-resources"
    location = "West Europe"
  }
  
  resource "azurerm_virtual_network" "example" {
    name                            = "example-vn"
    location                        = azurerm_resource_group.example.location
    resource_group_name = azurerm_resource_group.example.name
    address_space              = ["10.0.0.0/16"]
  }
  
  resource "azurerm_subnet" "example" {
    name                            = "example-sn"
    resource_group_name = azurerm_resource_group.example.name
    virtual_network_name  = azurerm_virtual_network.example.name
    address_prefixes          = ["10.0.2.0/24"]
    service_endpoints        = ["Microsoft.Storage"]
    delegation {
      name = "fs"
      service_delegation {
        name    = "Microsoft.DBforMySQL/flexibleServers"
        actions = [
          "Microsoft.Network/virtualNetworks/subnets/join/action",
        ]
      }
    }
  }
  
  resource "azurerm_private_dns_zone" "example" {
    name                           = "example.mysql.database.azure.com"
    resource_group_name = azurerm_resource_group.example.name
  }
  
  resource "azurerm_private_dns_zone_virtual_network_link" "example" {
    name                              = "exampleVnetZone.com"
    private_dns_zone_name = azurerm_private_dns_zone.example.name
    virtual_network_id          = azurerm_virtual_network.example.id
    resource_group_name   = azurerm_resource_group.example.name
  }
  
  resource "azurerm_mysql_flexible_server" "example" {
    name                               = "example-fs"
    resource_group_name    = azurerm_resource_group.example.name
    location                           = azurerm_resource_group.example.location
    administrator_login         = "psqladmin"
    administrator_password  = "H@Sh1CoR3!"
    backup_retention_days   = 7
    delegated_subnet_id       = azurerm_subnet.example.id
    private_dns_zone_id        = azurerm_private_dns_zone.example.id
    sku_name                        = "GP_Standard_D2ds_v4"
  
    depends_on = [azurerm_private_dns_zone_virtual_network_link.example]
  }
```

### Debug Output/Panic Output

```shell
Error: waiting for creation of Flexible Server
Resource Group Name: "$RG_NAME"
Flexible Server Name: "$SERVER_NAME"): Code="InternalServerError" Message="An unexpected error occured while processing the request. Tracking ID: '$TRACKING_ID'"

with module.mysql_flexible_server.azurerm_mysql_flexible_server.main,
│   on ..\..\..\..\services\db\mysql\flexible\server\main.tf line 1, in resource "azurerm_mysql_flexible_server" "main":
│    1: resource "azurerm_mysql_flexible_server" "main" {
```

### Expected Behaviour

When provided delegated subnet id. terraform provider should create flexible server with subnet but it is throwing internal server error.

### Steps to Reproduce

terraform apply with delegated subnet id (delegated_subnet_id block)

### Important Factoids

No

### References

No response

**Comment by neil-yechenwei** [comment] 2023-08-11 05:36
Thanks for raising this issue. Seems I can't repro this issue with below tf config that is similar with yours. Could you try below tf config and latest azurerm provider to see if the issue still exists? Thanks.

tf config:
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-mysql-test0123"
  location = "westeurope"
}

resource "azurerm_virtual_network" "test" {
  name                = "acctest-vn-test0123"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  address_space       = ["10.0.0.0/16"]
}

resource "azurerm_subnet" "test" {
  name                 = "acctest-sn-test0123"
  resource_group_name  = azurerm_resource_group.test.name
  virtual_network_name = azurerm_virtual_network.test.name
  address_prefixes     = ["10.0.2.0/24"]
  service_endpoints    = ["Microsoft.Storage"]

  delegation {
    name = "fs"

    service_delegation {
      name = "Microsoft.DBforMySQL/flexibleServers"

      actions = [
        "Microsoft.Network/virtualNetworks/subnets/join/action",
      ]
    }
  }
}

resource "azurerm_private_dns_zone" "test" {
  name                = "acctest0123.mysql.database.azure.com"
  resource_group_name = azurerm_resource_group.test.name
}

resource "azurerm_private_dns_zone_virtual_network_link" "test" {
  name                  = "acctestVnetZonetest0123.com"
  private_dns_zone_name = azurerm_private_dns_zone.test.name
  virtual_network_id    = azurerm_virtual_network.test.id
  resource_group_name   = azurerm_resource_group.test.name
}

resource "azurerm_mysql_flexible_server" "test" {
  name                         = "acctest-fs-test0123"
  resource_group_name          = azurerm_resource_group.test.name
  location                     = azurerm_resource_group.test.location
  administrator_login          = "adminTerraform"
  administrator_password       = "123wsxQAZ"
  backup_retention_days        = 7

  delegated_subnet_id = azurerm_subnet.test.id
  private_dns_zone_id = azurerm_private_dns_zone.test.id
  sku_name            = "GP_Standard_D2ds_v4"

  depends_on = [azurerm_private_dns_zone_virtual_network_link.test]
}
```

**Comment by rcskosir** [comment] 2023-12-06 22:24
Thanks for taking the time to submit this issue. @neil-yechenwei was unable to reproduce this behavior. We’re going to close this issue for now, but if you run into this again with the latest Terraform and Provider versions, please feel free to [open a new issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/new/choose).

**Closed by rcskosir** 2023-12-06 22:24 UTC
Labels: waiting-response, service/mysql, v/3.x
