### ISSUE TITLE
3.63.0 Breaking azurerm_key_vault_managed_storage_account

### ISSUE THREAD

**Issue by Divya1388** [hashicorp/terraform-provider-azurerm#22757] opened 2023-07-31 18:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.3.0

### AzureRM Provider Version

3.63.0

### Affected Resource(s)/Data Source(s)

azurerm_key_vault_managed_storage_account

### Terraform Configuration Files

```hcl
resource "azurerm_key_vault_managed_storage_account" "gmf-sa-keys" {
  for_each            = toset(var.enable_key_rotation ? local.keys_to_rotate : [])
  name                = "msa${var.unique_id}${each.value}"
  key_vault_id        = var.key_vault_id
  storage_account_id  = azurerm_storage_account.gmf.id
  storage_account_key = each.value

  regenerate_key_automatically = var.regenerate_key_automatically
  regeneration_period          = var.regeneration_period

  depends_on = [azurerm_role_assignment.key_rotation_role, azurerm_key_vault_access_policy.storage]
}
```

### Debug Output/Panic Output

```shell
Error: key vault 'NestedItemType' should be one of: keys, secrets, certificates, got "storage"
```

### Expected Behaviour

The above is an exisiting resource and no changes should have been detected.

### Actual Behaviour

The resource has been present without any errors in the state. The above resource is working fin with version 2.62.0. But when we are trying to upgrade the provider to 3.63 we see the following error

 Error: key vault 'NestedItemType' should be one of: keys, secrets, certificates, got "storage"

However there has been no changes to config and the resource was already created. And the releases do not mention about this resource change https://github.com/hashicorp/terraform-provider-azurerm/releases but may be any of the dependencies broke the resource?

### Steps to Reproduce

terraform apply with v3.62.0 
terraform apply with v3.63.0

**Comment by rcskosir** [comment] 2023-08-01 13:23
Thanks for taking the time to submit this issue. It looks like this is a duplicate of #22694. We like to try to keep discussions consolidated, so I ask that you please follow the other issue for updates.

**Closed by rcskosir** 2023-08-01 13:23 UTC
Labels: service/key-vault, v/3.x
