### ISSUE TITLE
Support for Attaching OSDisk of azurerm_windows_virtual_machine/azurerm_linux_virtual_machine

### ISSUE THREAD

**Issue by ofbjansen** [hashicorp/terraform-provider-azurerm#15879] opened 2022-03-18 08:51 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We would like to have a way to attach an OS Disk to a VM resource. This is currently only possible with azurerm_virtual_machine. For now we can work with that resources, but the resource is not available anymore after version 2.x of azurerm.

### New or Affected Resource(s)

* azurerm_windows_virtual_machine
* azurerm_linux_virtual_machine

### Potential Terraform Configuration

```hcl
os_disk {
     managed_disk_id = <managed_disk_id>
}
```

### References

* #0000

**Comment by tombuildsstuff** [comment] 2022-03-18 10:20
Duplicate of #8195

**Closed by tombuildsstuff** 2022-03-18 10:20 UTC
Labels: duplicate, enhancement, service/virtual-machine
