### ISSUE TITLE
azurerm_pim_eligible_role_assignment attempts to recreate after circa 45 days - error "already exists"

### ISSUE THREAD

**Issue by J0F3** [hashicorp/terraform-provider-azurerm#25811] opened 2024-04-30 08:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.2

### AzureRM Provider Version

3.99.0

### Affected Resource(s)/Data Source(s)

azurerm_pim_eligible_role_assignment

### Terraform Configuration Files

```hcl
resource "time_static" "now" {}

resource "azurerm_pim_eligible_role_assignment" "contributor" {
  scope              = data.azurerm_subscription.current.id
  role_definition_id = "${data.azurerm_subscription.current.id}${data.azurerm_role_definition.contributor.id}"
  principal_id       = var.contributor_pim_group

  schedule {
    start_date_time = time_static.now.rfc3339
    expiration {
      duration_hours = 0
    }
  }
}
```

### Debug Output/Panic Output

```shell
Error: A resource with the ID "/subscriptions/xxxxxxx|/subscriptions/xxxxxxx/providers/Microsoft.Authorization/roleDefinitions//b24988ac-6180-42a0-ab88-20f7382dd24c|yyyyyyy" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_pim_eligible_role_assignment" for more information.
│ 
│   with azurerm_pim_eligible_role_assignment.contributor,
│   on main.tf line 549, in resource "azurerm_pim_eligible_role_assignment" "contributor":
│  549: resource "azurerm_pim_eligible_role_assignment" "contributor" {
│ 
│ A resource with the ID
│ "/subscriptions/xxxxxxx|/subscriptions/xxxxxxx/providers/Microsoft.Authorization/roleDefinitions//b24988ac-6180-42a0-ab88-20f7382dd24c|yyyyyyy8"
│ already exists - to be managed via Terraform this resource needs to be
│ imported into the State. Please see the resource documentation for
│ "azurerm_pim_eligible_role_assignment" for more information.
```

### Expected Behaviour

Terraform should not loose the existing PIM eligible role assignment from it state and should not try to recreate it despite the role assignment still exists in Azure. The state of Terraform must be always the as the state in Azure it self. 

### Actual Behaviour

After a period of time, circa 45 days Terraform removes the roles assignment form the TF state and therefore wants to recreate the role assignment. But the create fails then obviously because the role assignment is still there in Azure. 

### Steps to Reproduce

- Update PIM settings to allow permanent role assignments.
- Create a PIM Role assignment without expiry.
- Wait circa 45 days, reapply terraform config.
- Terraform remove the role assignment from its state and wants to re-create it. -> Error.

### References

It was presumed it is fixed in: https://github.com/hashicorp/terraform-provider-azurerm/issues/24118 but it is actually not. The root cause seems to be still exist. 

https://github.com/hashicorp/terraform-provider-azurerm/issues/23111 seems to have the same root cause. Which make importing a an existing `azurerm_pim_eligible_role_assignment` resource impossible which makes this issue even more annoying. Because normally such errors could be fixed with a `terraform import` but this is not possibile in this case because Terraform thinks the ressource does no exist in Azure (wich is not true and a bug in the azurerm provider).

**Comment by J0F3** [comment] 2024-04-30 09:19
I did quite some troubleshooting around this issue yesterday which leads me to the conclusion that the information which is saved in the terraform state is based on the wrong Azure resource. The relevant code was already reference from @TeamDman in https://github.com/hashicorp/terraform-provider-azurerm/issues/23111 :


https://github.com/hashicorp/terraform-provider-azurerm/blob/dcf32586e80a12a20b5f979a934dcf1dc60eecf5/internal/services/authorization/pim_eligible_role_assignment_resource.go#L284-L304

There are basically two Azure  resources for PIM eligible role assignments:
- roleEligibilityScheduleRequests: API / resource to send request which makes Azure to create or delete the corresponding `roleEligibilitySchedules` object / resource. But roleEligibilityScheduleRequests does not represent the actual PIM role assignment resource or any other long-lived Azure resource at all. It is more for logging/auditing purpose and is therefore also cleaned up by azure after some time (presumably 45 days).
- roleEligibilitySchedules: This is the actual Azure resource of the PIM eligible role assignment which keeps existent and which is also shown in the Azure Portal as the PIM role assignment. This is the only resource which Terraform should reference in it its state. Because this it the actual representation of `azurerm_pim_eligible_role_assignment` in Azure.

**Comment by J0F3** [comment] 2024-05-16 06:27
@manicminer Then this probably also fixed with #25956 ?

**Comment by manicminer** [comment] 2024-05-16 09:24
@J0F3 Thanks! Yes this will be fixed with that PR 🙂

I believe this is actually a duplicate of #24118, which was closed prematurely so I understand why this issue was opened.

**Closed by manicminer** 2024-05-16 09:24 UTC
Labels: bug, service/authorization, v/3.x

**Comment by J0F3** [comment] 2024-05-17 05:19
@manicminer thank you! Yes I (re)created this issue because https://github.com/hashicorp/terraform-provider-azurerm/issues/24118 was closed because the problem was supposedly solved. But it showed now that it was actually not.
