### ISSUE TITLE
Support for Azure Active Directory Authentication with PostgreSQL Flexible Server

### ISSUE THREAD

**Issue by t3mi** [hashicorp/terraform-provider-azurerm#18969] opened 2022-10-25 12:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please add support for Azure Active Directory Authentication options with PostgreSQL Flexible server as its now in preview.

### New or Affected Resource(s)/Data Source(s)

azurerm_postgresql_flexible_active_directory_administrator

### Potential Terraform Configuration

Similar to PostgreSQL Single server [azurerm_postgresql_active_directory_administrator](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/postgresql_active_directory_administrator) and/or MySQL implementations [azurerm_mysql_active_directory_administrator](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mysql_active_directory_administrator) and `azuread_administrator` block in [azurerm_mssql_server](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mssql_server)

### References
https://azure.microsoft.com/en-us/updates/public-preview-azure-active-directory-for-azure-database-for-postgresql-flexible-server/
https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-azure-ad-authentication

**Comment by mybayern1974** [comment] 2022-10-26 03:06
Thank you @t3mi for opening this issue.

Taking a look through this appears to be a duplicate of #18838. Rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #18838 for updates? Or feel free to reopen if you believe these two issues are not talking about the same thing.

Thanks!

**Closed by mybayern1974** 2022-10-26 03:06 UTC
Labels: duplicate
