### ISSUE TITLE
Can't create Azure Cache for redis Basic or Standard

### ISSUE THREAD

**Issue by txetxuvel** [hashicorp/terraform-provider-azurerm#11430] opened 2021-04-22 07:40 UTC
When creating an instance of sku Basic and Standard of Azure Cache for Redis you can't define subnet_id as it's explained in the documentation because it can be defined only for sku Premium. So this code should work:

```
resource "azurerm_redis_cache" "test_redis" {
  name  = "testredis"
  location = local.resource_group_location
  resource_group_name = local.resource_group_name
  capacity = 2
  family = "C"
  sku_name = "Basic"

  private_static_ip_address = local.redis_ip_address
  public_network_access_enabled = false
}
```

But when executing it returns this error:

Error: creating Redis Cache "testredis" (Resource Group "testrg"): redis.Client#Create: Failure sending request: StatusCode=0 -- Original Error: Code="InvalidRequestBody" Message="The value of the parameter 'properties.subnetId' is invalid.\r\nRequestID=XXXX"

Fixing the subnet_id with a dedicated subnet for Azure Cache for redis:

```
resource "azurerm_redis_cache" "test_redis" {
  name = "testredis"
  location = local.resource_group_location
  resource_group_name = local.resource_group_name
  capacity  = 2
  family = "C"
  sku_name = "Basic"

  private_static_ip_address = local.redis_ip_address
  public_network_access_enabled = false
  subnet_id = local.cache_subnet_id
}
```

And it returns the expected error about subnet_id can not be fixed for Standard and Basic families:

Error: creating Redis Cache "testredis" (Resource Group "testrg"): redis.Client#Create: Failure sending request: StatusCode=0 -- Original Error: Code="BadRequest" Message="Feature properties.subnetId requires a Premium sku to be set.\r\nRequestID=XXXXX"

I tried to fix subnet_id to null but the first error persists and then I tried with sku Premium and fixing subnet_id and in this case it works.

Terraform Version: 0.14.9
Provider azurerm version: 2.53.0

**Comment by DXCanas** [comment] 2021-11-13 02:06
Same issue here. Can only get this working using the Premium tier.

**Comment by tombuildsstuff** [comment] 2021-11-15 11:22
hi @txetxuvel 

Thanks for opening this issue.

Private Network Access being set to Disabled requires that this exists on a Subnet, which is only available in the higher SKU's by design in Azure unfortunately - as such it appears that this is working as intended based on the current API/Service behaviour.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Closed by tombuildsstuff** 2021-11-15 11:22 UTC
Labels: bug, service/redis
