### ISSUE TITLE
storage_account: terraform plan fails when read-only user unable to generate plan due to missing permissions

### ISSUE THREAD

**Issue by edoyon90** [hashicorp/terraform-provider-azurerm#20188] opened 2023-01-26 18:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.9

### AzureRM Provider Version

3.26.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "boot_diagnostics_cc" {
  name = "bootdiagccgh4535"

  # Locally redundant storage, spinning plates
  account_tier             = "Standard"
  account_replication_type = "LRS"
  resource_group_name      = "logging"
  location                 = "canadacentral"

  min_tls_version = "TLS1_2"

  cross_tenant_replication_enabled  = false
  allow_nested_items_to_be_public   = false

  tags = {
    environment = "global"
  }
}

output "azurerm_storage_account_cc_boot_diag_endpoint" {
  value     = azurerm_storage_account.boot_diagnostics_cc.primary_blob_endpoint
  sensitive = true
}
```

### Debug Output/Panic Output

```shell
Error: listing Keys for Storage Account: (Name "bootdiagccgh4535" / Resource Group "logging"): storage.AccountsClient#ListKeys: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client 'xxxxxxxxxxxxx' with object id 'xxxxxxxxxxxxx' does not have authorization to perform action 'Microsoft.Storage/storageAccounts/listKeys/action' over scope '/subscriptions/xxxxxxxxxxxxxxxx/resourceGroups/logging/providers/Microsoft.Storage/storageAccounts/bootdiagccgh4535' or the scope is invalid. If access was recently granted, please refresh your credentials."
```

### Expected Behaviour

A read-only user running a plan is supposed to degrade the fields from the ListKeys endpoints into empty values, rather than outright failing.

### Actual Behaviour

The service principal created with 'Reader' roles on the subscription is unable to list keys. We do not want it to be able to list keys as it will be used as part of a github action to add the terraform plan as a comment on pull requests. 

### Steps to Reproduce

terraform plan

### References

According to https://github.com/hashicorp/terraform-provider-azurerm/issues/4138 this issue has been resolved but it is definitely still occurring for me.
Also see https://github.com/hashicorp/terraform-provider-azurerm/pull/4248 where it was fixed

**Comment by tombuildsstuff** [comment] 2023-01-27 13:48
hey @edoyon90 

Thanks for opening this issue.

Whilst Data Sources support retrieving information about an existing resource with limited permissions - since Resources manage the full lifecycle of a resource, we require CRUD permissions for the resource in question (which, given how permissions are scoped for this resource, includes permission to list the keys of the Storage Account).

Since the Resource is being used in the Terraform Configuration above, the AzureRM Provider is working as intended here - however it should be possible to achieve what you're looking for using the Data Source instead to look up information about an existing Storage Account, either directly (using [the `azurerm_storage_account` Data Source](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/storage_account)) or [Terraform's `remote_state` Data Source](https://developer.hashicorp.com/terraform/language/state/remote-state-data) to look up the information from the Terraform State where the storage account is being provisioned from.

As the Resource is working as intended (since we require CRUD permissions when using the Resource), I'm going to close this issue at the moment - however as mentioned above using the Data Source should allow you to access information about the Storage Account using limited permissions.

Thanks!

**Closed by tombuildsstuff** 2023-01-27 13:48 UTC
