### ISSUE TITLE
Support for ACCSGXDevicePlugin in addonProfiles

### ISSUE THREAD

**Issue by foxnix** [hashicorp/terraform-provider-azurerm#10507] opened 2021-02-09 03:56 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support SGX addon profile:
```
"addonProfiles": {
    "ACCSGXDevicePlugin": {
        "enabled": false
    }
}
```

### New or Affected Resource(s)

* azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
"addonProfiles": {
    "ACCSGXDevicePlugin": {
        "enabled": true
    }
}
```

**Comment by stephybun** [comment] 2021-12-08 15:33
Duplicate of #10689

**Closed by stephybun** 2021-12-08 15:33 UTC
Labels: enhancement, service/kubernetes-cluster
