### ISSUE TITLE
[azurerm_storage_account] Adding dns_endpoint_type property with new azurerm version forces new resource creation

### ISSUE THREAD

**Issue by babuga365** [hashicorp/terraform-provider-azurerm#25374] opened 2024-03-22 10:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.5

### AzureRM Provider Version

3.97.0

### Affected Resource(s)/Data Source(s)

azurerm_3.97.0

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "example" {
  name                = "storageaccountname"
  resource_group_name = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  dns_endpoint_type         = "Standard"

  network_rules {
    default_action             = "Deny"
    ip_rules                   = ["100.0.0.1"]
    virtual_network_subnet_ids = [azurerm_subnet.example.id]
  }

  tags = {
    environment = "staging"
  }
}
```

### Debug Output/Panic Output

```shell
Based on the terraform plan, I could see that storage account is trying to recreate based on new parameter addition on latest azurerm version(v3.97.0)

 # module.emea-weu-s100-inf-d-tfstate-storage.azurerm_storage_account.main must be replaced
-/+ resource "azurerm_storage_account" "main" {
      + dns_endpoint_type                  = "Standard" # forces replacement
```

### Expected Behaviour

As per terraform provider documentation, this property is Optional one. So it shouldn't trigger any recreation operation with storage account. If its triggering recreation all the details stored in storage account will be lost

[dns_endpoint_type](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account#dns_endpoint_type) - (**Optional**) Specifies which DNS endpoint type to use. Possible values are Standard and AzureDnsZone. Defaults to Standard. Changing this forces a new resource to be created.

### Actual Behaviour

Adding [dns_endpoint_type](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account#dns_endpoint_type) property forces a resource recreation.
  
```
  # module.emea-weu-s100-inf-d-tfstate-storage.azurerm_storage_account.main must be replaced
-/+ resource "azurerm_storage_account" "main" {
      + dns_endpoint_type                  = "Standard" # forces replacement
```
      
      
     Is this the expected behaviour? then please check and let me know whether I can use ignore_changes block to avoid resource recreation as its optional parameter. 

  lifecycle {
    ignore_changes = [dns_endpoint_type]
  }

### Important Factoids

Resources were created at WestEurope Location

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account#dns_endpoint_type

**Comment by tombuildsstuff** [comment] 2024-03-22 10:25
hey @babuga365 

Thanks for opening this issue.

Taking a look through here this is a duplicate of #25364 which was fixed by https://github.com/hashicorp/terraform-provider-azurerm/pull/25367 - please update to `v3.97.1` of the AzureRM Provider which includes a fix for this issue.

Thanks!

**Closed by tombuildsstuff** 2024-03-22 10:25 UTC
Labels: v/3.x

**Comment by babuga365** [comment] 2024-03-22 10:28
Thanks for your information. I didn't found any open case thats why I raised this one. Will close it now
