### ISSUE TITLE
Fail to reapply storage account code when lock exist in ReadOnly level

### ISSUE THREAD

**Issue by rpuserh** [hashicorp/terraform-provider-azurerm#13234] opened 2021-09-03 22:16 UTC
Hi,

To reproduce create tf file (replace name and resource group name)

```
resource "azurerm_storage_account" "example" {
  name                     = "<REDUCTED>"
  resource_group_name      = "<REDUCTED>"
  location                 = "westus"
  account_tier             = "Standard"
  account_replication_type = "GRS"
  tags = {
    environment = "staging"
  }
}
resource "azurerm_management_lock" "lock" {
  name       = "lock-test"
  scope      = azurerm_storage_account.example.id
  lock_level = "ReadOnly"
  notes      = "lock do not delete"
}
```
On first apply it will create storage account and lock 

If I try to do plan or apply it will error
```
 Error: building Queues Client: retrieving Account Key: Listing Keys for Storage Account "<REDUCTED>" (Resource Group "<REDUCTED>"): storage.AccountsClient#ListKeys: Failure responding to request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error.Status=409 Code="ScopeLocked" Message="The scope '/subscriptions/<REDUCTED>/resourceGroups/<REDUCTED>/providers/Microsoft.Storage/storageAccounts/<REDUCTED>' cannot perform write operation because following scope(s) are locked: '/subscriptions/<REDUCTED>/resourceGroups/<REDUCTED>/providers/Microsoft.Storage/storageAccounts/<REDUCTED>'. Please remove the lock and try again."
```

I need to keep lock level on ReadOnly. And need terraform to be able to plan apply as i have other resources in my module.

Terraform version :
```
terraform  version
Terraform v1.0.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.75.0
```

Please advise.

**Comment by rpuserh** [comment] 2021-09-28 21:41
Is there any update workaround ?

**Comment by tombuildsstuff** [comment] 2021-09-29 11:34
hi @rpuserh 

Taking a look through here unfortunately this is due to the design of Locks within Azure - where a ReadOnly lock will prevent any changes taking effect. As such you'd either need to change this to be a `DoNotDelete` lock or remove this lock prior to modifying / re-add this lock post-modifying resources under this scope.

Since this behaviour is by design due to how ReadOnly Locks work in Azure, I'm going to close this issue for the moment, but hopefully that helps as a workaround for your setup.

Thanks!

**Closed by tombuildsstuff** 2021-09-29 11:34 UTC
Labels: question, service/storage, upstream-microsoft
