### ISSUE TITLE
azurerm_firewall does not disassociate Public IP before deleting public IP

### ISSUE THREAD

**Issue by picardsrcd** [hashicorp/terraform-provider-azurerm#9602] opened 2020-12-01 17:34 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/azurerm v2.38.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

### Affected Resource(s)

* `azurerm_firewall`
* `azurerm_public_ip`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp

# Fine when going  2 --> 4
# Fails when reducing # of public ips such as going from 4 --> 2
locals {
  # when used in for_each, the indexes must be strings.
  # also, for_each expects a set or map.
  # Change 4 to 2 after deploy
  public_loop_indexes = toset([for s in range(0,4) : tostring(s)])
}


# Naming
# Firewall Naming
module "naming_firewall" {
  source              = "git@github.com:ghorg/terraform-azurerm-naming.git//modules/az/firewall"
  user_defined_string = var.user_defined_string

  department_code = var.department_code
  environment     = var.environment
  location        = var.location
}

# PIP Naming
module "naming_public_ip" {
  for_each = local.public_loop_indexes

  source          = "git@github.com:ghorg/terraform-azurerm-naming.git//modules/az/public_ip"
  parent_resource = module.naming_firewall.result_without_type
  number_suffix = each.key
}


# Public IP
resource "azurerm_public_ip" "pip" {
  for_each = local.public_loop_indexes

  name                = module.naming_public_ip[each.key].result
  location            = var.location
  resource_group_name = var.existing_resource_group_name
  allocation_method   = "Static"
  sku                 = "Standard"

  tags = var.tags
}

# Firewall
resource "azurerm_firewall" "fw" {
  name                = module.naming_firewall.result
  location            = var.location
  resource_group_name = var.existing_resource_group_name

  sku_name = "AZFW_VNet"
  sku_tier = "Standard"

  # Operational Opinion - Enforce AZ's where available
  # Crude implementation assuming 2 regions
  zones = var.location == "canadacentral" ? [1, 2] : null

  # Security Opinion - Start with Alert mode. Allow to bump up to Deny using a variable.
  threat_intel_mode = var.threat_intel_mode

  dynamic "ip_configuration" {
    for_each = local.public_loop_indexes
    content {
      name                 = "configuration-${ip_configuration.key}"
      # only one configuration is allowed to have the subnet_id defined. The index is a string; must use string comparison.
      subnet_id            = ip_configuration.key == "0" ? var.fw_subnet_id : null 
      public_ip_address_id = azurerm_public_ip.pip[ip_configuration.key].id
    }
  }

  tags = var.tags
}

```

### Debug Output

https://gist.github.com/picardsrcd/f9040c2ea8fab01d99c139b184db22a7

### Panic Output

No panic

### Expected Behaviour

During  reduction of public IPs, the FW configuration should remove the relevant `ip_configuration` blocks, then remove the public ip

### Actual Behaviour

Terraform goes straight into deleting the public ip's while they are still assigned to the azurerm_firewall

### Steps to Reproduce

1. `terraform apply` (with 4 public_ips)
2. `terraform apply` (with 2 public_ips, thus triggering a deletion of 2 PIP and updating the FW to remove 2 ip_configuration)

The plan between 1 and 2 should look as follows:
```hcl
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place
  - destroy

Terraform will perform the following actions:

  # module.fw.azurerm_firewall.fw will be updated in-place
  ~ resource "azurerm_firewall" "fw" {
        dns_servers         = []
        id                  = "/subscriptions/xxxxxxxx-9b01-4988-be58-4438263a88ba/resourceGroups/azfw2-rg/providers/Microsoft.Network/azureFirewalls/ScPcFWL-egress_fw-azfw"
        location            = "canadacentral"
        name                = "ScPcFWL-egress_fw-azfw"
        resource_group_name = "azfw2-rg"
        sku_name            = "AZFW_VNet"
        sku_tier            = "Standard"
        tags                = {
            "test" = "true"
        }
        threat_intel_mode   = "Alert"
        zones               = [
            "1",
            "2",
        ]

        ip_configuration {
            name                 = "configuration-0"
            private_ip_address   = "10.0.0.4"
            public_ip_address_id = "/subscriptions/xxxxxxxx-9b01-4988-be58-4438263a88ba/resourceGroups/azfw2-rg/providers/Microsoft.Network/publicIPAddresses/ScPcFWL-egress_fw-pip0"
            subnet_id            = "/subscriptions/xxxxxxxx-9b01-4988-be58-4438263a88ba/resourceGroups/azfw2-rg/providers/Microsoft.Network/virtualNetworks/hub-vnet/subnets/AzureFirewallSubnet"
        }
        ip_configuration {
            name                 = "configuration-1"
            public_ip_address_id = "/subscriptions/xxxxxxxx-9b01-4988-be58-4438263a88ba/resourceGroups/azfw2-rg/providers/Microsoft.Network/publicIPAddresses/ScPcFWL-egress_fw-pip1"
        }
      - ip_configuration {
          - name                 = "configuration-2" -> null
          - public_ip_address_id = "/subscriptions/xxxxxxxx-9b01-4988-be58-4438263a88ba/resourceGroups/azfw2-rg/providers/Microsoft.Network/publicIPAddresses/ScPcFWL-egress_fw-pip2" -> null
        }
      - ip_configuration {
          - name                 = "configuration-3" -> null
          - public_ip_address_id = "/subscriptions/xxxxxxxx-9b01-4988-be58-4438263a88ba/resourceGroups/azfw2-rg/providers/Microsoft.Network/publicIPAddresses/ScPcFWL-egress_fw-pip3" -> null
        }
    }

  # module.fw.azurerm_public_ip.pip["2"] will be destroyed
  - resource "azurerm_public_ip" "pip" {
      - allocation_method       = "Static" -> null
      - id                      = "/subscriptions/xxxxxxxx-9b01-4988-be58-4438263a88ba/resourceGroups/azfw2-rg/providers/Microsoft.Network/publicIPAddresses/ScPcFWL-egress_fw-pip2" -> null
      - idle_timeout_in_minutes = 4 -> null
      - ip_address              = "52.228.112.247" -> null
      - ip_version              = "IPv4" -> null
      - location                = "canadacentral" -> null
      - name                    = "ScPcFWL-egress_fw-pip2" -> null
      - resource_group_name     = "azfw2-rg" -> null
      - sku                     = "Standard" -> null
      - tags                    = {
          - "test" = "true"
        } -> null
      - zones                   = [] -> null
    }

  # module.fw.azurerm_public_ip.pip["3"] will be destroyed
  - resource "azurerm_public_ip" "pip" {
      - allocation_method       = "Static" -> null
      - id                      = "/subscriptions/xxxxxxxx-9b01-4988-be58-4438263a88ba/resourceGroups/azfw2-rg/providers/Microsoft.Network/publicIPAddresses/ScPcFWL-egress_fw-pip3" -> null
      - idle_timeout_in_minutes = 4 -> null
      - ip_address              = "52.228.112.179" -> null
      - ip_version              = "IPv4" -> null
      - location                = "canadacentral" -> null
      - name                    = "ScPcFWL-egress_fw-pip3" -> null
      - resource_group_name     = "azfw2-rg" -> null
      - sku                     = "Standard" -> null
      - tags                    = {
          - "test" = "true"
        } -> null
      - zones                   = [] -> null
    }

Plan: 0 to add, 1 to change, 2 to destroy.
```

The following output occurs:
```go
module.fw.azurerm_public_ip.pip["3"]: Destroying... [id=/subscriptions/xxxx-9b01-4988-be58-4438263a88ba/resourceGroups/azfw2-rg/providers/Microsoft.Network/publicIPAddresses/ScPcFWL-egress_fw-pip3]
module.fw.azurerm_public_ip.pip["2"]: Destroying... [id=/subscriptions/xxxx-9b01-4988-be58-4438263a88ba/resourceGroups/azfw2-rg/providers/Microsoft.Network/publicIPAddresses/ScPcFWL-egress_fw-pip2]

Error: Error deleting Public IP "ScPcFWL-egress_fw-pip3" (Resource Group "azfw2-rg"): network.PublicIPAddressesClient#Delete: Failure sending request: StatusCode=400 -- Original Error: Code="PublicIPAddressCannotBeDeleted" Message="Public IP address /subscriptions/xxxxxxxx-9b01-4988-be58-4438263a88ba/resourceGroups/azfw2-rg/providers/Microsoft.Network/publicIPAddresses/ScPcFWL-egress_fw-pip3 can not be deleted since it is still allocated to resource /subscriptions/xxxxxxxx-9b01-4988-be58-4438263a88ba/resourceGroups/azfw2-rg/providers/Microsoft.Network/azureFirewalls/ScPcFWL-egress_fw-azfw/azureFirewallIpConfigurations/configuration-3. In order to delete the public IP, disassociate/detach the Public IP address from the resource.  To learn how to do this, see aka.ms/deletepublicip." Details=[]

Error: Error deleting Public IP "ScPcFWL-egress_fw-pip2" (Resource Group "azfw2-rg"): network.PublicIPAddressesClient#Delete: Failure sending request: StatusCode=400 -- Original Error: Code="PublicIPAddressCannotBeDeleted" Message="Public IP address /subscriptions/xxxxxxxx-9b01-4988-be58-4438263a88ba/resourceGroups/azfw2-rg/providers/Microsoft.Network/publicIPAddresses/ScPcFWL-egress_fw-pip2 can not be deleted since it is still allocated to resource /subscriptions/xxxxxxxx-9b01-4988-be58-4438263a88ba/resourceGroups/azfw2-rg/providers/Microsoft.Network/azureFirewalls/ScPcFWL-egress_fw-azfw/azureFirewallIpConfigurations/configuration-2. In order to delete the public IP, disassociate/detach the Public IP address from the resource.  To learn how to do this, see aka.ms/deletepublicip." Details=[]
```
### Important Factoids

None

### References

This issue seems to be prevalent with other Azure resources such as VM. 
https://github.com/Azure/terraform-azurerm-compute/issues/107
https://github.com/hashicorp/terraform/issues/25993
* #0000

**Comment by lonegunmanb** [comment] 2022-11-25 09:01
For who's still interested in [Azure/terraform-azurerm-compute#107](https://github.com/Azure/terraform-azurerm-compute/issues/107), I've submitted a pull request and I believe it could solve this issue by declaring a `create_before_destroy = true` on the public ip resource.

This is not a terraform-azurerm-provider's bug but by design of Terraform core. I believe we could just close this issue since we have a mature workaround for this issue. @katbyte just FYI.

**Comment by rcskosir** [comment] 2023-08-02 17:10
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!

**Closed by rcskosir** 2023-08-02 17:10 UTC
Labels: bug, service/public-ip, service/firewall, v/2.x (legacy)
