### ISSUE TITLE
Managed Storage Account File Shares / Containers Azure Resource Manager

### ISSUE THREAD

**Issue by jkroepke** [hashicorp/terraform-provider-azurerm#26542] opened 2024-07-04 15:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

azurerm_storage_share is using data plane REST API for setup and configure shares.

This causes issues, if firewall rules are active on a storage account.

Azure additionally provides a Azure Resource Manager API for manage File Share inside a storage Account. It would be great if the AzureRM APIs can be used instead the Data plane API.

If single properties are not availible via Azure Resource Manager, then it maybe split it out on a dedicated resources (like AWS Provider does it for S3 Buckets)

### New or Affected Resource(s)/Data Source(s)

azurerm_storage_share

### References

* https://learn.microsoft.com/en-us/rest/api/storagerp/file-shares?view=rest-storagerp-2023-05-01
* https://learn.microsoft.com/en-us/rest/api/storagerp/blob-containers?view=rest-storagerp-2023-05-01

**Comment by tombuildsstuff** [comment] 2024-07-04 15:50
hey @jkroepke 

Taking a look through here, this issue is ultimately a duplicate of #2977 - where unfortunately the Resource Manager functionality doesn't expose the functionality available in the Data Plane API, which the Service Team have previously committed to adding. Whilst we may look to split the Data Plane functionality out to a separate resource in the future, unfortunately doing so breaks some scenarios (for example, guaranteeing that there's no static website configured, which would need to be done within the main `azurerm_storage_account` resource).

Since this issue is ultimately a duplicate of #2977, whilst I'd like to thank you for opening this issue I'm going to close this in favour of that issue - so would you mind subscribing to that issue for updates?

Thanks!

**Closed by tombuildsstuff** 2024-07-04 15:50 UTC
Labels: duplicate, service/storage
