### ISSUE TITLE
Error: `vnet_image_pull_enabled` cannot be disabled for app running in an app service environment

### ISSUE THREAD

**Issue by TaylorN15** [hashicorp/terraform-provider-azurerm#27157] opened 2024-08-23 01:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.1

### AzureRM Provider Version

4.0.0

### Affected Resource(s)/Data Source(s)

azurerm_linux_function_app

### Terraform Configuration Files

```hcl
resource "azurerm_linux_function_app" "functionapp" {
  name                          = var.functionAppName
  location                      = azurerm_resource_group.rg.location
  resource_group_name           = azurerm_resource_group.rg.name
  service_plan_id               = azurerm_service_plan.appservlinplan02.id
  storage_account_name          = azurerm_storage_account.storage.name
  storage_account_access_key    = azurerm_storage_account.storage.primary_access_key
  https_only                    = true
  public_network_access_enabled = true

  site_config {
    application_stack {
      python_version = "3.10"
    }
    
    always_on                         = true
    http2_enabled                     = true
    scm_ip_restriction_default_action = "Deny"
  }

  identity {
    type = "SystemAssigned"
  }

  app_settings = {
    ...
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

Nothing, there is no change to make. The vnet_image_pull_enabled was not set in state before, but is now set to true, therefore no change is required.

### Actual Behaviour

Plan/Apply fails with error `Error: vnet_image_pull_enabled cannot be disabled for app running in an app service environment`

**Comment by TaylorN15** [comment] 2024-08-23 02:05
If I explicitly set `vnet_image_pull_enabled` to true on the function app in the TF then it works. I assume with it not being set, TF is attempting to change it from its current state of `true` to null or false?

**Comment by stephybun** [comment] 2024-08-23 07:09
Hey @TaylorN15

Since this is a major version release there will be breaking changes when upgrading. This happens to be one of them and is mentioned in the [4.0 upgrade guide](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/4.0-upgrade-guide#azurerm_linux_function_app). 

The change you will have to make to your config you have already done, which is to set `vnet_image_pull_enabled` to `true`.

I'm going to close this issue since it's neither a bug nor a feature request but expected behaviour when upgrading to v4.0 for function apps running in an app service environment.

**Closed by stephybun** 2024-08-23 07:09 UTC

**Comment by carnei-ro** [comment] 2024-08-26 17:46
the flag is not documented here https://registry.terraform.io/providers/hashicorp/azurerm/4.0.1/docs/resources/windows_function_app
