### ISSUE TITLE
[Bug] - Terraform plan going into walk/dag loop and fixing on its own

### ISSUE THREAD

**Issue by thanos-kataras** [hashicorp/terraform-provider-azurerm#25097] opened 2024-02-29 13:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.7

### AzureRM Provider Version

3.93.0

### Affected Resource(s)/Data Source(s)

azurerm_resource_group

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "sdlc" {
  name     = local.infrastructure_rg_name
  location = local.rg_location
}

provider "azurerm" {
  features {}
  use_oidc = true
  oidc_token_file_path = "xxxxxxx"
}

terraform {
  required_version = ">= 1.5.7"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~>3.0"
    }
  }
}
locals {
  infrastructure_rg_name = "xxxxxxx"
  rg_location            = "East US"
}
```

### Debug Output/Panic Output

```shell
2024-02-29T12:56:25.043Z [TRACE] dag/walk: vertex "azurerm_resource_group.sdlc (expand)" is waiting for "provider[\"registry.terraform.io/hashicorp/azurerm\"]"
2024-02-29T12:56:25.043Z [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/azurerm\"] (close)" is waiting for "azurerm_resource_group.sdlc (expand)"
2024-02-29T12:56:25.043Z [TRACE] dag/walk: vertex "root" is waiting for "provider[\"registry.terraform.io/hashicorp/azurerm\"] (close)"
2024-02-29T12:56:30.046Z [TRACE] dag/walk: vertex "root" is waiting for "provider[\"registry.terraform.io/hashicorp/azurerm\"] (close)"
2024-02-29T12:56:30.046Z [TRACE] dag/walk: vertex "azurerm_resource_group.sdlc (expand)" is waiting for "provider[\"registry.terraform.io/hashicorp/azurerm\"]"
2024-02-29T12:56:30.047Z [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/azurerm\"] (close)" is waiting for "azurerm_resource_group.sdlc (expand)"
2024-02-29T12:56:30.296Z [DEBUG] provider.terraform-provider-azurerm_v3.93.0_x5: AzureRM Request: 
GET /subscriptions/*****/providers/Microsoft.Web?api-version=2022-09-01 HTTP/1.1
Host: management.azure.com
User-Agent: HashiCorp/go-azure-sdk (Go-http-Client/1.1 providers/2022-09-01) HashiCorp Terraform/1.5.7 (+https://www.terraform.io) Terraform Plugin SDK/2.10.1 terraform-provider-azurerm/3.93.0 pid-222c6c49-1b0a-5959-a213-6608f9eb8820
Accept: application/json; charset=utf-8; IEEE754Compatible=false
Content-Type: application/json; charset=utf-8
Odata-Maxversion: 4.0
Odata-Version: 4.0
X-Ms-Correlation-Request-Id: ff2cacca-b10d-24c8-55ef-f9d394e0e28c
Accept-Encoding: gzip: timestamp=2024-02-29T12:56:30.295Z
2024-02-29T12:56:30.296Z [DEBUG] provider.terraform-provider-azurerm_v3.93.0_x5: GET https://management.azure.com/subscriptions/*****/providers/Microsoft.Web?api-version=2022-09-01: timestamp=2024-02-29T12:56:30.296Z
2024-02-29T12:56:30.453Z [DEBUG] provider.terraform-provider-azurerm_v3.93.0_x5: {"@level":"debug","@message":"AzureRM Response for https://management.azure.com/subscriptions/*****/providers/Microsoft.Web?api-version=2022-09-01: \nHTTP/2.0 200
```

### Expected Behaviour

A new resource group to be created.

### Actual Behaviour

For the last couple of days, the log enters in an infinite loop. Then suddenly and with no changes (it is literally this code) it suddenly started working

### References

#24114 - Seems like a similar case with no real resolution.

**Comment by thanos-kataras** [comment] 2024-02-29 14:00
I can see in the logs re-appearing all the time:

>
>Waiting for Subscription Provider (Subscription: "*****"
> Provider Name: "Microsoft.Web") to finish registering
>

Assuming that this was an issue?

**Comment by rcskosir** [comment] 2024-06-04 16:00
Thanks for taking the time to submit this issue. @wuxu92 was unable to reproduce this behavior. We’re going to close this issue for now, but if you run into this again with the latest Terraform and Provider versions, please feel free to [open a new issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/new/choose).

**Closed by rcskosir** 2024-06-04 16:00 UTC
Labels: waiting-response, service/resources, v/3.x
