### ISSUE TITLE
Support for API Management Features for APIM Workspaces

### ISSUE THREAD

**Issue by JackBruceShell** [hashicorp/terraform-provider-azurerm#27937] opened 2024-11-07 14:16 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Any timeline on implementing azurerm features for API Management Workspaces and all of the inner workings of Workspaces?

### New or Affected Resource(s)/Data Source(s)

azurerm_api_management_api

### Potential Terraform Configuration

```hcl
resource "azurerm_api_management_workspace"
resource "azurerm_api_management_workspace_api"
resource "azurerm_api_management_workspace_api_operation"
etc...
```

**Comment by JackBruceShell** [comment] 2024-11-08 07:51
#21109 

Waiting for this features since the referenced ticket. This is much needed now since APIM Workspaces are now GA.

Thanks.

**Comment by rcskosir** [comment] 2024-11-08 15:35
Thanks for taking the time to submit this issue. This is a duplicate of #21109. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of #21109.

**Closed by rcskosir** 2024-11-08 15:35 UTC
Labels: duplicate, enhancement, service/api-management
