### ISSUE TITLE
Support for integrating LogicApps (API) within Azure APIM

### ISSUE THREAD

**Issue by avineshwar** [hashicorp/terraform-provider-azurerm#10476] opened 2021-02-04 16:59 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
At the moment, it is not possible to integrate LogicApps as an API within Azure APIM. The only possible options are either LogicApps provided URIs, or, manually configure the APIM and use the produced/exported template file.

### Potential Terraform Configuration
A new value inside `content_format` and other relevant attributes
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_api#content_format

**Comment by oWretch** [comment] 2021-12-02 23:53
Duplicate of #3982

**Comment by tombuildsstuff** [comment] 2021-12-10 22:44
Thanks @oWretch - duplicate of #3982, please subscribe to that issue for updates.

**Closed by tombuildsstuff** 2021-12-10 22:44 UTC
Labels: service/api-management, service/logic
