### ISSUE TITLE
Support for Zones on App Service Environments

### ISSUE THREAD

**Issue by timlharrison** [hashicorp/terraform-provider-azurerm#7829] opened 2020-07-21 15:09 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Please add support for Availability Zones for App Service Environments (ASEs).

### New or Affected Resource(s)

* azurerm_app_service_environment

### Potential Terraform Configuration

```hcl
resource "azurerm_app_service_environment" "example" {
  name = "example-ase"
  subnet_id = azurerm_subnet.ase.id
  pricing_tier = "I2"
  front_end_scale_factor = 10
  internal_load_balancing_mode = "Web, Publishing"
  allowed_user_ip_cidrs = ["11.22.33.44/32", "55.66.77.0/24"]
  zones = ["1","2"]
}
```

### References

* https://azure.github.io/AppService/2019/12/12/App-Service-Environment-Support-for-Availability-Zones.html

**Comment by neil-yechenwei** [comment] 2020-07-22 05:20
Thanks for opening this issue. After checked the [rest api spec](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/web/resource-manager/Microsoft.Web/stable/2020-06-01/AppServiceEnvironments.json), seems it hasn't been supported by app service environment api. And I also go through the doc you provided, I assume this feature is only supported by arm template currently. So I assume you can use azurerm_template_deployment resource to implement it.

**Comment by LaurentLesle** [comment] 2020-08-20 00:52
The rest api spec documentation is not updated. I can confirm it is working when using the following ARM code:

{
            "apiVersion": "2019-08-01",
            "type": "Microsoft.Web/hostingEnvironments",
            "name": "[parameters('aseName')]",
            "kind": "[parameters('kind')]",
            "location": "[parameters('location')]",
            "zones": "[if(empty(parameters('zone')),json('null'),array(parameters('zone')))]",
            "properties": {
                "name": "[parameters('aseName')]",
                "location": "[parameters('location')]",
                "internalLoadBalancingMode": "[parameters('internalLoadBalancingMode')]",
                "multiSize": "[parameters('frontEndSize')]",
                "multiRoleCount": "[parameters('frontEndCount')]",
                "virtualNetwork": {
                    "id": "[parameters('subnet_id')]",
                    "subnet": "[parameters('subnet_name')]"
                }
            }
        }

**Comment by venura9** [comment] 2020-11-30 03:44
This is a key requirement, Would Microsoft get notified about this requirement or do you expect the users to create another ticket?

**Comment by tombuildsstuff** [comment] 2024-03-28 13:10
Support for this is available in [`azurerm_app_service_environment_v3`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service_environment_v3#zone_redundant) - the older versions of App Service Environment [are deprecated and will be retired on 31/08/2024](https://azure.microsoft.com/en-gb/updates/app-service-environment-version-1-and-version-2-will-be-retired-on-31-august-2024-2/) - as such I'm going to close this feature out since this is available in the V3 resource.

Thanks!

**Closed by tombuildsstuff** 2024-03-28 13:10 UTC
Labels: enhancement, service/app-service
