### ISSUE TITLE
azurerm_storage_management_policy -> storage_account_id shows being updated every time in Terraform plan after initial creation

### ISSUE THREAD

**Issue by tsatardekar-deloitte** [hashicorp/terraform-provider-azurerm#20938] opened 2023-03-14 15:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.0

### AzureRM Provider Version

3.47.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_management_policy

### Terraform Configuration Files

```hcl
resource "azurerm_storage_management_policy" "apim_backup" {
  storage_account_id = azurerm_storage_account.apim_backup.id

  rule {
    name    = "Delete30DaysOldBackups"
    enabled = true
    filters {
      prefix_match = ["apimbackups"]
      blob_types   = ["blockBlob"]
    }
    actions {
      base_blob {
        delete_after_days_since_modification_greater_than = 30
      }
    }
  }

  depends_on = [
    azurerm_storage_account.apim_backup
  ]
}
```

### Debug Output/Panic Output

```shell
# azurerm_storage_management_policy.apim_backup must be replaced
-/+ resource "azurerm_storage_management_policy" "apim_backup" ***
      ~ id                 = "/subscriptions/XXX/resourceGroups/marketplace-qa/providers/Microsoft.Storage/storageAccounts/marketplaceapimbackupqa/managementPolicies/default" -> (known after apply)
      ~ storage_account_id = "/subscriptions/XXX/resourceGroups/marketplace-qa/providers/Microsoft.Storage/storageAccounts/marketplaceapimbackupqa" -> "/subscriptions/XXX/resourcegroups/marketplace-qa/providers/Microsoft.Storage/storageAccounts/marketplaceapimbackupqa" # forces replacement
```

### Expected Behaviour

storage_account_id hasn't changed, so it shouldn't be shown in the Terraform plan. The resourceID string shouldn't be case sensitive for resourceGroups :  "/subscriptions/XXX/**resourceGroups**/marketplace-qa/providers/Microsoft.Storage/storageAccounts/marketplaceapimbackupqa" 

"resourceGroups" in the resourceID url should be treated the same as "resourcegroups"

### Actual Behaviour

# azurerm_storage_management_policy.apim_backup must be replaced
-/+ resource "azurerm_storage_management_policy" "apim_backup" ***
      ~ id                 = "/subscriptions/XXX/resourceGroups/marketplace-qa/providers/Microsoft.Storage/storageAccounts/marketplaceapimbackupqa/managementPolicies/default" -> (known after apply)
      ~ storage_account_id = "/subscriptions/XXX/resourceGroups/marketplace-qa/providers/Microsoft.Storage/storageAccounts/marketplaceapimbackupqa" -> "/subscriptions/XXX/resourcegroups/marketplace-qa/providers/Microsoft.Storage/storageAccounts/marketplaceapimbackupqa" # forces replacement

**Comment by magodo** [comment] 2023-03-15 06:13
@tsatardekar-deloitte Thank you for submitting this! This provider is enforcing case sensitive for all the properties, including the resource id. The issue you are encountered will not occur if the resource is created by the provider, as in that case the id will always have the correct casing. Presumably you are importing the storage account, in that case please ensure the id in the import command conforms to the correct casing, i.e. **resourceGroups**.

**Comment by tsatardekar-deloitte** [comment] 2023-03-15 08:20
@magodo, thank you for your response. I'm creating the resource (storage account -  azurerm_storage_account.apim_backup) via terraform. After that I also create the   azurerm_storage_management_policy via terraform. Here, I fetch the storage ID via 

storage_account_id = azurerm_storage_account.apim_backup.id 
(which is referencing the storage account created by terraform). 

Unfortunately, I don't have the possibility to change the case of the resource ID here.

**Comment by magodo** [comment] 2023-03-15 08:37
@tsatardekar-deloitte I've locally verified following config works fine for `terraform apply` then `terraform plan` (no diff):

```hcl
provider "azurerm" {
  features {}
}
resource "azurerm_resource_group" "test" {
  name     = "acctestRG-storage-220215133126908401"
  location = "West Europe"
}
resource "azurerm_storage_account" "test" {
  name                     = "unlikely23exst3acctzw0ly"
  resource_group_name      = azurerm_resource_group.test.name
  location                 = azurerm_resource_group.test.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  account_kind             = "BlobStorage"
  blob_properties {
  }
}
resource "azurerm_storage_management_policy" "test" {
  storage_account_id = azurerm_storage_account.test.id
  rule {
    name    = "rule1"
    enabled = true
    filters {
      prefix_match = ["container1/prefix1"]
      blob_types   = ["blockBlob"]
    }
    actions {
      base_blob {
        tier_to_cool_after_days_since_modification_greater_than    = 10
        tier_to_archive_after_days_since_modification_greater_than = 50
      }
      snapshot {
        delete_after_days_since_creation_greater_than = 30
      }
    }
  }
}
```
Did you mean you were creating all these two resources at a single terraform run? Rather than creating the storage account in other workspace, but importing it to this workspace? If that is the case, hmm, I currently can't figure out how could that happen 🤔

**Comment by tsatardekar-deloitte** [comment] 2023-03-15 08:47
@magodo, you need to go one step further. So, complete terraform plan and apply. After the resource is created in Azure, try terraform plan again. In this TF plan, it should show you that azurerm_storage_management_policy will be modified.

**Comment by magodo** [comment] 2023-03-15 09:00
@tsatardekar-deloitte I indeed did that:

> I've locally verified following config works fine for terraform apply then terraform plan (no diff):

**Comment by tsatardekar-deloitte** [comment] 2023-03-15 09:06
😟 I cannot deny your results. We have 3 environments. I don't see any problem in dev. Only in QA & Prod environment, the TF plan shows the modification. Don't know what could be causing this as I use the same terraform file to deploy the resources to all 3 environments

**Comment by magodo** [comment] 2023-03-15 09:19
Would you mind share the minimalized config that can reproduce this issue?

**Comment by myc2h6o** [comment] 2023-03-15 09:36
@tsatardekar-deloitte from the diff, looks like `azurerm_storage_account.test.id` has the `resourcegroups` segment instead of `resourceGroups`, which should not happen when the `azurerm_storage_account.test` is created by Terraform itself without importing or manually modifying the state file. The ID is generated from https://github.com/hashicorp/terraform-provider-azurerm/blob/v3.47.0/internal/services/storage/parse/storage_account.go#L36 with hardcoded `resourceGroups`. Would you mind also checking the `id` property of `azurerm_storage_account` from the state file and see if it's in the correct case?

**Comment by myc2h6o** [comment] 2023-03-15 09:58
I found release v2.74.0 contains a change #13014 which changes the set ID on creation from the ID returned by the service to the ID composed by the provider itself. This may be the cause as well because the service might returned an ID with `resourcegroups` earlier. @tsatardekar-deloitte did you remember with which provider version you created the storage account?
And as a mitigation, you can fix the ID by removing the storage account from the state with `terraform state rm`(https://developer.hashicorp.com/terraform/cli/commands/state/rm) and re-import it with the correct ID.

**Comment by tsatardekar-deloitte** [comment] 2023-03-15 10:38
Thank you @myc2h6o, that indeed was the problem! I checked the TF state files. The env where it is working properly, the state file contains the resourceID with "resourceGroups". And for the ones complaining, the resourceID is in lowercase. The resources were created 4 months ago via terraform. I can try the fix you mentioned to remove and import the resource into TF state. Though the question still remains why it worked for one environment and not for the other 2.

**Comment by rcskosir** [comment] 2024-06-11 19:08
Thank you for taking the time to raise this! I am going to close this with @myc2h6o‘s response as an answer. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).

**Closed by rcskosir** 2024-06-11 19:08 UTC
Labels: question, service/storage, v/3.x
