### ISSUE TITLE
azurerm_storage_blob resource creation fails when file is roughly larger than 2GB - "(*GRPCProvider).ApplyResourceChange request was cancelled."

### ISSUE THREAD

**Issue by LMG-Deloitte** [hashicorp/terraform-provider-azurerm#23074] opened 2023-08-24 14:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.3.7

### AzureRM Provider Version

3.2.1

### Affected Resource(s)/Data Source(s)

azurerm_storage_blob

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "<3.0.0" 
    }
  }
}

resource "azurerm_storage_blob" "example" {
  name                   = "example"
  storage_account_name   = var.storage_account_name
  storage_container_name = var.container_name
  source                 = file #2.25GB in size for example
  type                   = "Block"
  content_md5            = filemd5(file) #content_md5 field is used in this context, may not be relevant
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: Request cancelled
│ 
│   with azurerm_storage_blob.test_data_package["../data/datasets/example3gb.bin"],
│   on main.tf line 2, in resource "azurerm_storage_blob" "test_data_package":
│    2: resource "azurerm_storage_blob" "test_data_package" {
│ 
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵
##[error]Script failed with exit code: 1
```

### Expected Behaviour

Blob should have been created in target container

### Actual Behaviour

Above error is thrown

### Steps to Reproduce

terraform apply

### Important Factoids

None of note, fails on multiple file types (CSV and bin tested)

**Comment by magodo** [comment] 2023-08-25 03:10
@LMG-Deloitte Looks like the context is cancelled for some reason. Are you running this in some agent or locally? How long it takes from started creation till the error raised?

**Comment by LMG-Deloitte** [comment] 2023-08-25 07:51
I am running this on an agent. I can provide details if needed. The task is failing after around 30-40 seconds. I have added 60 minute timeouts to the terraform resource block with no effect

**Comment by magodo** [comment] 2023-08-25 08:20
Yes, please provide the log via a gist link.

**Comment by magodo** [comment] 2023-08-28 01:27
I didn't see any error message, but a warning complaining you were defining the empty provider block in a non-root module? Probably you can follow up [this](https://developer.hashicorp.com/terraform/internals/debugging) and provide the debug log?

**Comment by LMG-Deloitte** [comment] 2023-08-28 06:40
The error was provided in the original issue report, I assumed you did not want it twice. See updated logs.

`Starting: Terraform Apply
Task : Azure CLI
Description : Run Azure CLI commands against an Azure subscription in a PowerShell Core/Shell script when running on Linux agent or PowerShell/PowerShell Core/Batch script when running on Windows agent.
Version : 2.225.0
Author : Microsoft Corporation
Help : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-cli
/usr/bin/az --version
WARNING: You have 3 update(s) available. Consider updating your CLI installation with 'az upgrade'
azure-cli 2.43.0 *

core 2.43.0 *
telemetry 1.0.8 *

Extensions:
azure-firewall 0.14.4
log-analytics-solution 0.1.1
portal 0.1.3
application-insights 0.1.17
front-door 1.0.17
azure-devops 0.25.0

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1

Python location '/opt/az/bin/python3'
Extensions directory '/usr/local/azurecliextensions'

Python (Linux) 3.10.8 (main, Dec 2 2022, 06:07:45) [GCC 9.4.0]

Legal docs and information: aka.ms/AzureCliLegal...azurerm_storage_blob.test_data_package["../data/datasets/example3gb.bin"]: Creating...
azurerm_storage_blob.test_data_package["../data/datasets/example3gb.bin"]: Still creating... [10s elapsed]
azurerm_storage_blob.test_data_package["../data/datasets/example3gb.bin"]: Still creating... [20s elapsed]
azurerm_storage_blob.test_data_package["../data/datasets/example3gb.bin"]: Still creating... [30s elapsed]
╷
│ Warning: Redundant empty provider block
│
│ on .terraform/modules/common_names/src/providers.tf line 1:
│ 1: provider "azurerm" {
│
│ Earlier versions of Terraform used empty provider blocks ("proxy provider
│ configurations") for child modules to declare their need to be passed a
│ provider configuration by their callers. That approach was ambiguous and is
│ now deprecated.
│
│ If you control this module, you can migrate to the new declaration syntax
│ by removing all of the empty provider "azurerm" blocks and then adding or
│ updating an entry like the following to the required_providers block of
│ module.common_names:
│ azurerm = {
│ source = "hashicorp/azurerm"
│ configuration_aliases = [
│ azurerm,
╷
│ Error: Request cancelled
│ 
│   with azurerm_storage_blob.test_data_package["../data/datasets/example3gb.bin"],
│   on main.tf line 2, in resource "azurerm_storage_blob" "test_data_package":
│    2: resource "azurerm_storage_blob" "test_data_package" {
│ 
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵
##[error]Script failed with exit code: 1

**Comment by LMG-Deloitte** [comment] 2023-08-28 06:41
> I didn't see any error message, but a warning complaining you were defining the empty provider block in a non-root module? Probably you can follow up [this](https://developer.hashicorp.com/terraform/internals/debugging) and provide the debug log?

I will try and provide a debugging log if the above is no help

**Comment by magodo** [comment] 2023-08-29 01:29
Yeah, please help provide the debug log.

**Comment by rcskosir** [comment] 2023-12-06 22:36
Thanks for taking the time to submit this issue. Unfortunately, we don't have the debug log. Please update this issue with the debug log for the error you are experiencing so that contributors can verify they are reproducing the same issue correctly, or that other users can identify if they are seeing the same error. In the mean time I am going to close this issue, I can reopen once updated with the debug log.

**Closed by rcskosir** 2023-12-06 22:36 UTC
Labels: question, waiting-response, service/storage, v/3.x
