### ISSUE TITLE
azurerm_servicebus_subscription resources are missing if azurerm_servicebus_topic is recreated

### ISSUE THREAD

**Issue by levvko** [hashicorp/terraform-provider-azurerm#4710] opened 2019-10-24 15:34 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.12
+ provider.azuread v0.6.0
+ provider.azurerm v1.35.0

### Affected Resource(s)

* `azurerm_servicebus_topic`
* `azurerm_servicebus_subscription`

### Terraform Configuration Files

```hcl
resource "azurerm_servicebus_topic" "sb-topic" {
  name                = "topic-common"
  resource_group_name = data.azurerm_resource_group.resource_group.name
  namespace_name      = azurerm_servicebus_namespace.sb.name
  enable_partitioning = false
  requires_duplicate_detection = true
  duplicate_detection_history_time_window = "PT30S"
}

resource "azurerm_servicebus_subscription" "sb-subscription" {
  name                = "subscription"
  resource_group_name = data.azurerm_resource_group.resource_group.name
  namespace_name      = azurerm_servicebus_namespace.sb.name
  topic_name          = azurerm_servicebus_topic.sb-topic.name
  max_delivery_count  = 10
}
```

### Expected Behavior

If the topic has to be replaced, the subscription is also replaced.

### Actual Behavior

Both resources were already in place. There was a change as described below

```
-/+ resource "azurerm_servicebus_topic" "morf-sb-topic" {
        ~ auto_delete_on_idle                     = "..." -> (known after apply)
        ~ default_message_ttl                     = "..." -> (known after apply)
        ~ duplicate_detection_history_time_window = "PT10M" -> "PT30S"
        - enable_batched_operations               = false -> null
        - enable_express                          = false -> null
          enable_partitioning                     = false
        ~ id                                      = "..." -> (known after apply)
        ~ max_size_in_megabytes                   = 5120 -> (known after apply)
          name                                    = "topic-common"
          namespace_name                          = "sb"
        ~ requires_duplicate_detection            = false -> true # forces replacement
          resource_group_name                     = "..."
          status                                  = "Active"
        - support_ordering                        = false -> null
    }
```

After applying, the topic is in place with new configuration. Subscription is missing. When running apply for the second time without changing anything, it is detected that the subscription is missing and it is created.

### Steps to Reproduce

1. create terraform  configuration for topic with `requires_duplicate_detection = false` and a subscription
2. `terraform apply`
3. notice both topic and subscription created
4. set `requires_duplicate_detection = true`
5. `terraform apply`
6. notice subscription missing

**Comment by neil-yechenwei** [comment] 2020-05-08 04:22
Thanks for opening this issue. I think it's by design since `requires_duplicate_detection` is not the reference property in the `azurerm_servicebus_subscription` resource. If you want to update `azurerm_servicebus_subscription` while updating `requires_duplicate_detection`, maybe you need to also update `name` property of `azurerm_servicebus_topic`.

**Comment by levvko** [comment] 2020-05-18 19:42
Thanks for looking into this. The problem is that subscription depends on topic, but this dependency is not reflected properly in the provider. 

So in the example above topic has to be replaced ("-/+" in plan) . When topic is deleted, child subscriptions are also deleted, but this doesn't get noticed by terraform. We end up without subscriptions. State also doesn't get updated and it lists non-existing subscriptions.

**Comment by neil-yechenwei** [comment] 2020-05-19 03:14
Thanks for clarification. After investigated, seems the root cause is `azurerm_servicebus_subscription` is also deleted after deleted `azurerm_servicebus_topic`. And terraform doesn't detect the diff by name of `azurerm_servicebus_topic` for `azurerm_servicebus_subscription` so that `azurerm_servicebus_subscription` isn't updated in state. The workaround is run `tf apply` again after recreated `azurerm_servicebus_topic`.

![image](https://user-images.githubusercontent.com/19754191/82279845-1008bc80-99c0-11ea-81d5-955202d2d662.png)

Abstracts this issue. Assumes `property_d` would reference `A` by `name` in `A`. When performs recreation on `A` by updating `property_c`, terraform would delete `A`. However, `B` is associated with `A` so that `B` is also deleted. And terraform doesn't detect `B` has been deleted, so `B` is updated yet in stat file.
```
resource "A" "test" {
  name       = "testnameA"
  property_c = true // It's optional and forcenew attribute.
}

resource "B" "test" {
  name                = "testnameB"
  property_d          = A.test.name // It's a required attribute.
}
```

**Comment by levvko** [comment] 2020-05-20 00:44
Yes, I have described the workaround in the "actual behaviour" section of the issue. Sorry if I wasn't clear.

**Comment by theadzik** [comment] 2020-09-25 12:53
Is there any update on the issue? I encountered the same:

Terraform v0.13.3
+ provider registry.terraform.io/hashicorp/azurerm v2.16.0

**Comment by pierrenoronha** [comment] 2021-02-10 12:35
Hello, 

currently we're using the versions listed bellow and this bug still happening. 
    * terraform v0.14.2
    * azurerm 2.27.0

Does anyone has prevision to this solution be incorporated to the Provider Azurerm???

**Comment by favoretti** [comment] 2021-08-19 07:00
Since this issue seems to have been addressed in the latest versions of the provider (or a valid workaround was provided) - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.

**Closed by favoretti** 2021-08-19 07:00 UTC
Labels: bug, upstream-terraform, service/service-bus
