### ISSUE TITLE
App Service Plan Resource ID Should use `serverFarms` instead of `serverfarms`

### ISSUE THREAD

**Issue by jerrodmartin** [hashicorp/terraform-provider-azurerm#16511] opened 2022-04-22 19:44 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.8

### AzureRM Provider Version

3.0.2

### Affected Resource(s)/Data Source(s)

azurerm_service_plan

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_service_plan" "example" {
  name                = "example"
  resource_group_name = azurerm_resource_group.example.name
  location            = "West Europe"
  os_type             = "Linux"
  sku_name            = "P1v2"
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: parsing Resource ID
"/subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/example-resources/providers/Microsoft.Web/serverFarms/example":
ID was missing the `serverfarms` element
```

### Expected Behaviour

The import should have completed successfully.

### Actual Behaviour

The import failed because the provider is looking for `serverfarms` in the ID instead of `serverFarms`.

### Steps to Reproduce

`terraform import 'azurerm_service_plan.example' '/subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/example-resources/providers/Microsoft.Web/serverFarms/example'`

**Comment by lonegunmanb** [comment] 2022-04-25 02:59
Hello @jerrodmartin , thanks for opening this issue. I've checked the [doc](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/service_plan#import) for the import statement:

>terraform import azurerm_service_plan.example /subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/resGroup1/providers/Microsoft.Web/serverfarms/farm1

According to the [code](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/web/parse/app_service_plan.go#L28), the author regarded `Serverfarm` as a whole word so no camel case here.

**Comment by lonegunmanb** [comment] 2022-05-08 23:40
Hello @jerrodmartin , is there any further question?

**Comment by Qooooo** [comment] 2022-05-09 01:23
@lonegunmanb, you mean it's a Terraform doc vs Terraform code issue?
In Azure, when you copy the resource ID, it gives you "serverFarms" by default, not "serverfarms". It is a minor inconvenience to Terraform users, but I would think that Terraform code should adopt the differences, no?

**Comment by tombuildsstuff** [comment] 2022-05-09 06:08
@Qooooo unfortunately the Azure Portal has changed the casing for this several times over the years (from `serverFarms` -> `serverfarms` -> `serverFarms`) - whilst at this point in time this probably _should_ be `serverFarms` (to match other resources) - to be honest making this change at this point would be disruptive and as such isn't something we're planning to do at this time.

Instead as @lonegunmanb has mentioned above, the documentation for each resource highlights the specific casing that we're looking for - as such whilst I'd like to thank you for opening this issue, I'm going to close this out as working as intended at this point in time.

Thanks!

**Closed by tombuildsstuff** 2022-05-09 06:08 UTC
