### ISSUE TITLE
azurerm_key_vault_secret timesout at about 2 minutes by default during recovery.

### ISSUE THREAD

**Issue by vermacodes** [hashicorp/terraform-provider-azurerm#12432] opened 2021-06-30 21:48 UTC
When trying to create a secret or key in key vault, if the key/secret already exists terraform recovers that. In this issue, terraform starts the recovery process but if the secret/key takes more than ~2 minutes to recover terraform times out. As per the documents [here](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault_secret#timeouts) it should default to 30 minutes but that's not happening. 

I tried adding timeouts block to the code but it doesn't have any effect either. 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

* `Terraform Version - 1.0.1`
* `AzureRM Version - 2.65.0`
* `Azure Region - easeus2`

### Affected Resource(s)

* `azurerm_2.65.0`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  version = "=2.20.0"
  features {}
}

terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "2.65.0"
    }
  }
}

provider "azurerm" {
  features {}
}

data "azurerm_key_vault" "example" {
  name                = "myKeyVault"
  resource_group_name = "myResourceGroup"
}

resource "azurerm_key_vault_secret" "example" {
  timeouts {
    create = "10m"
  }
  name         = "secret-sauce"
  value        = "szechuan"
  key_vault_id = data.azurerm_key_vault.example.id
}
```

### Debug Output

{"error":{"code":"Conflict","message":"Secret secret-sauce is currently in a deleted but recoverable state, and its name cannot be reused; in this state, the secret can only be recovered or purged.","innererror":{"code":"ObjectIsDeletedButRecoverable"}}}: timestamp=2021-06-30T15:55:44.148-0400
2021-06-30T15:55:44.149-0400 [DEBUG] provider.terraform-provider-azurerm_v2.65.0_x5: AzureRM Request:
POST /deletedsecrets/secret-sauce/recover?api-version=7.1 HTTP/1.1
Host: myKeyVault.vault.azure.net
User-Agent: Go/go1.16.3 (amd64-linux) go-autorest/v14.2.1 Azure-SDK-For-Go/v55.3.0 keyvault/7.1 HashiCorp Terraform/1.0.1 (+https://www.terraform.io) Terraform Plugin SDK/2.6.1 terraform-provider-azurerm/2.65.0 pid-222c6c49-1b0a-5959-a213-6608f9eb8820
Content-Length: 0
Accept-Encoding: gzip: timestamp=2021-06-30T15:55:44.148-0400
2021-06-30T15:55:44.207-0400 [DEBUG] provider.terraform-provider-azurerm_v2.65.0_x5: AzureRM Response for https://myKeyVault.vault.azure.net/deletedsecrets/secret-sauce/recover?api-version=7.1:
HTTP/2.0 401 Unauthorized
Content-Length: 97
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
Date: Wed, 30 Jun 2021 19:55:42 GMT
Expires: -1
Pragma: no-cache
Strict-Transport-Security: max-age=31536000;includeSubDomains
Www-Authenticate: Bearer authorization="https://login.windows.net/e741d71c-c6b6-47b0-803c-0f3b32b07556", resource="https://vault.azure.net"
X-Content-Type-Options: nosniff
X-Ms-Keyvault-Network-Info: conn_type=Ipv4;addr=144.160.228.102;act_addr_fam=InterNetwork;
X-Ms-Keyvault-Region: eastus2
X-Ms-Keyvault-Service-Version: 1.9.12.0
X-Ms-Request-Id: ecffebde-4283-487f-8261-6ac0ce9c7062
X-Powered-By: ASP.NET

{"error":{"code":"Unauthorized","message":"AKV10000: Request is missing a Bearer or PoP token."}}: timestamp=2021-06-30T15:55:44.207-0400
2021-06-30T15:55:45.905-0400 [DEBUG] provider.terraform-provider-azurerm_v2.65.0_x5: AzureRM Request:
POST /deletedsecrets/secret-sauce/recover?api-version=7.1 HTTP/1.1
Host: myKeyVault.vault.azure.net
User-Agent: Go/go1.16.3 (amd64-linux) go-autorest/v14.2.1 Azure-SDK-For-Go/v55.3.0 keyvault/7.1 HashiCorp Terraform/1.0.1 (+https://www.terraform.io) Terraform Plugin SDK/2.6.1 terraform-provider-azurerm/2.65.0 pid-222c6c49-1b0a-5959-a213-6608f9eb8820
Content-Length: 0
X-Ms-Correlation-Request-Id: 0a385f18-ebb3-d305-bf57-37aec498660a
Accept-Encoding: gzip: timestamp=2021-06-30T15:55:45.905-0400
2021-06-30T15:55:46.066-0400 [DEBUG] provider.terraform-provider-azurerm_v2.65.0_x5: AzureRM Response for https://myKeyVault.vault.azure.net/deletedsecrets/secret-sauce/recover?api-version=7.1:
HTTP/2.0 200 OK
Content-Length: 259
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
Date: Wed, 30 Jun 2021 19:55:44 GMT
Expires: -1
Pragma: no-cache
Strict-Transport-Security: max-age=31536000;includeSubDomains
X-Content-Type-Options: nosniff
X-Ms-Keyvault-Network-Info: conn_type=Ipv4;addr=144.160.228.102;act_addr_fam=InterNetwork;
X-Ms-Keyvault-Region: eastus2
X-Ms-Keyvault-Service-Version: 1.9.12.0
X-Ms-Request-Id: f9191700-0014-4822-9654-2e0501ace630
X-Powered-By: ASP.NET

{"contentType":"","id":"https://myKeyVault.vault.azure.net/secrets/secret-sauce/bb5bc3025e064e7ebff26d789301ea75","attributes":{"enabled":true,"created":1625077679,"updated":1625077679,"recoveryLevel":"Recoverable","recoverableDays":90},"tags":{}}: timestamp=2021-06-30T15:55:46.066-0400
2021-06-30T15:55:46.066-0400 [DEBUG] provider.terraform-provider-azurerm_v2.65.0_x5: Recovering Secret "secret-sauce" with ID: "https://myKeyVault.vault.azure.net/secrets/secret-sauce/bb5bc3025e064e7ebff26d789301ea75": timestamp=2021-06-30T15:55:46.066-0400
2021-06-30T15:55:46.066-0400 [DEBUG] provider.terraform-provider-azurerm_v2.65.0_x5: Waiting for state to become: [available]: timestamp=2021-06-30T15:55:46.066-0400
azurerm_key_vault_secret.example: Still creating... [10s elapsed]
azurerm_key_vault_secret.example: Still creating... [20s elapsed]
azurerm_key_vault_secret.example: Still creating... [30s elapsed]
2021-06-30T15:56:16.067-0400 [DEBUG] provider.terraform-provider-azurerm_v2.65.0_x5: Checking to see if KeyVault Secret "https://myKeyVault.vault.azure.net/secrets/secret-sauce/bb5bc3025e064e7ebff26d789301ea75" is available..: timestamp=2021-06-30T15:56:16.066-0400
2021-06-30T15:56:16.422-0400 [DEBUG] provider.terraform-provider-azurerm_v2.65.0_x5: Found KeyVault Secret "https://myKeyVault.vault.azure.net/secrets/secret-sauce/bb5bc3025e064e7ebff26d789301ea75": timestamp=2021-06-30T15:56:16.422-0400
azurerm_key_vault_secret.example: Still creating... [40s elapsed]
2021-06-30T15:56:26.423-0400 [DEBUG] provider.terraform-provider-azurerm_v2.65.0_x5: Checking to see if KeyVault Secret "https://myKeyVault.vault.azure.net/secrets/secret-sauce/bb5bc3025e064e7ebff26d789301ea75" is available..: timestamp=2021-06-30T15:56:26.423-0400
azurerm_key_vault_secret.example: Still creating... [50s elapsed]
2021-06-30T15:56:26.730-0400 [DEBUG] provider.terraform-provider-azurerm_v2.65.0_x5: Found KeyVault Secret "https://myKeyVault.vault.azure.net/secrets/secret-sauce/bb5bc3025e064e7ebff26d789301ea75": timestamp=2021-06-30T15:56:26.730-0400
azurerm_key_vault_secret.example: Still creating... [1m0s elapsed]
2021-06-30T15:56:36.731-0400 [DEBUG] provider.terraform-provider-azurerm_v2.65.0_x5: Checking to see if KeyVault Secret "https://myKeyVault.vault.azure.net/secrets/secret-sauce/bb5bc3025e064e7ebff26d789301ea75" is available..: timestamp=2021-06-30T15:56:36.730-0400
2021-06-30T15:56:37.018-0400 [DEBUG] provider.terraform-provider-azurerm_v2.65.0_x5: Found KeyVault Secret "https://myKeyVault.vault.azure.net/secrets/secret-sauce/bb5bc3025e064e7ebff26d789301ea75": timestamp=2021-06-30T15:56:37.018-0400
azurerm_key_vault_secret.example: Still creating... [1m10s elapsed]
2021-06-30T15:56:47.021-0400 [DEBUG] provider.terraform-provider-azurerm_v2.65.0_x5: Checking to see if KeyVault Secret "https://myKeyVault.vault.azure.net/secrets/secret-sauce/bb5bc3025e064e7ebff26d789301ea75" is available..: timestamp=2021-06-30T15:56:47.020-0400
2021-06-30T15:56:47.652-0400 [DEBUG] provider.terraform-provider-azurerm_v2.65.0_x5: Found KeyVault Secret "https://myKeyVault.vault.azure.net/secrets/secret-sauce/bb5bc3025e064e7ebff26d789301ea75": timestamp=2021-06-30T15:56:47.652-0400
azurerm_key_vault_secret.example: Still creating... [1m20s elapsed]
2021-06-30T15:56:57.653-0400 [DEBUG] provider.terraform-provider-azurerm_v2.65.0_x5: Checking to see if KeyVault Secret "https://myKeyVault.vault.azure.net/secrets/secret-sauce/bb5bc3025e064e7ebff26d789301ea75" is available..: timestamp=2021-06-30T15:56:57.653-0400
2021-06-30T15:56:57.954-0400 [DEBUG] provider.terraform-provider-azurerm_v2.65.0_x5: Found KeyVault Secret "https://myKeyVault.vault.azure.net/secrets/secret-sauce/bb5bc3025e064e7ebff26d789301ea75": timestamp=2021-06-30T15:56:57.954-0400
azurerm_key_vault_secret.example: Still creating... [1m30s elapsed]
2021-06-30T15:57:07.956-0400 [DEBUG] provider.terraform-provider-azurerm_v2.65.0_x5: Checking to see if KeyVault Secret "https://myKeyVault.vault.azure.net/secrets/secret-sauce/bb5bc3025e064e7ebff26d789301ea75" is available..: timestamp=2021-06-30T15:57:07.956-0400
2021-06-30T15:57:08.359-0400 [DEBUG] provider.terraform-provider-azurerm_v2.65.0_x5: Found KeyVault Secret "https://myKeyVault.vault.azure.net/secrets/secret-sauce/bb5bc3025e064e7ebff26d789301ea75": timestamp=2021-06-30T15:57:08.359-0400
azurerm_key_vault_secret.example: Still creating... [1m40s elapsed]
2021-06-30T15:57:18.360-0400 [DEBUG] provider.terraform-provider-azurerm_v2.65.0_x5: Checking to see if KeyVault Secret "https://myKeyVault.vault.azure.net/secrets/secret-sauce/bb5bc3025e064e7ebff26d789301ea75" is available..: timestamp=2021-06-30T15:57:18.360-0400
2021-06-30T15:57:18.855-0400 [DEBUG] provider.terraform-provider-azurerm_v2.65.0_x5: Found KeyVault Secret "https://myKeyVault.vault.azure.net/secrets/secret-sauce/bb5bc3025e064e7ebff26d789301ea75": timestamp=2021-06-30T15:57:18.855-0400
azurerm_key_vault_secret.example: Still creating... [1m50s elapsed]
2021-06-30T15:57:28.856-0400 [DEBUG] provider.terraform-provider-azurerm_v2.65.0_x5: Checking to see if KeyVault Secret "https://myKeyVault.vault.azure.net/secrets/secret-sauce/bb5bc3025e064e7ebff26d789301ea75" is available..: timestamp=2021-06-30T15:57:28.856-0400
2021-06-30T15:57:29.279-0400 [DEBUG] provider.terraform-provider-azurerm_v2.65.0_x5: Found KeyVault Secret "https://myKeyVault.vault.azure.net/secrets/secret-sauce/bb5bc3025e064e7ebff26d789301ea75": timestamp=2021-06-30T15:57:29.279-0400
azurerm_key_vault_secret.example: Still creating... [2m0s elapsed]
2021-06-30T15:57:39.279-0400 [DEBUG] provider.terraform-provider-azurerm_v2.65.0_x5: Checking to see if KeyVault Secret "https://myKeyVault.vault.azure.net/secrets/secret-sauce/bb5bc3025e064e7ebff26d789301ea75" is available..: timestamp=2021-06-30T15:57:39.279-0400
2021-06-30T15:57:39.509-0400 [DEBUG] provider.terraform-provider-azurerm_v2.65.0_x5: Found KeyVault Secret "https://myKeyVault.vault.azure.net/secrets/secret-sauce/bb5bc3025e064e7ebff26d789301ea75": timestamp=2021-06-30T15:57:39.509-0400
azurerm_key_vault_secret.example: Still creating... [2m10s elapsed]
2021-06-30T15:57:49.510-0400 [DEBUG] provider.terraform-provider-azurerm_v2.65.0_x5: Checking to see if KeyVault Secret "https://myKeyVault.vault.azure.net/secrets/secret-sauce/bb5bc3025e064e7ebff26d789301ea75" is available..: timestamp=2021-06-30T15:57:49.509-0400
2021-06-30T15:57:50.212-0400 [DEBUG] provider.terraform-provider-azurerm_v2.65.0_x5: Found KeyVault Secret "https://myKeyVault.vault.azure.net/secrets/secret-sauce/bb5bc3025e064e7ebff26d789301ea75": timestamp=2021-06-30T15:57:50.212-0400
2021-06-30T15:57:50.212-0400 [DEBUG] provider.terraform-provider-azurerm_v2.65.0_x5: Secret "secret-sauce" recovered with ID: "https://myKeyVault.vault.azure.net/secrets/secret-sauce/bb5bc3025e064e7ebff26d789301ea75": timestamp=2021-06-30T15:57:50.212-0400
2021-06-30T15:57:50.212-0400 [DEBUG] provider.terraform-provider-azurerm_v2.65.0_x5: AzureRM Request:
PUT /secrets/secret-sauce?api-version=7.1 HTTP/1.1
Host: myKeyVault.vault.azure.net
User-Agent: Go/go1.16.3 (amd64-linux) go-autorest/v14.2.1 Azure-SDK-For-Go/v55.3.0 keyvault/7.1 HashiCorp Terraform/1.0.1 (+https://www.terraform.io) Terraform Plugin SDK/2.6.1 terraform-provider-azurerm/2.65.0 pid-222c6c49-1b0a-5959-a213-6608f9eb8820
Content-Length: 0
Content-Type: application/json; charset=utf-8
Accept-Encoding: gzip: timestamp=2021-06-30T15:57:50.212-0400
2021-06-30T15:57:50.291-0400 [DEBUG] provider.terraform-provider-azurerm_v2.65.0_x5: AzureRM Response for https://myKeyVault.vault.azure.net/secrets/secret-sauce?api-version=7.1:
HTTP/2.0 401 Unauthorized
Content-Length: 97
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
Date: Wed, 30 Jun 2021 19:57:48 GMT
Expires: -1
Pragma: no-cache
Strict-Transport-Security: max-age=31536000;includeSubDomains
Www-Authenticate: Bearer authorization="https://login.windows.net/e741d71c-c6b6-47b0-803c-0f3b32b07556", resource="https://vault.azure.net"
X-Content-Type-Options: nosniff
X-Ms-Keyvault-Network-Info: conn_type=Ipv4;addr=144.160.228.102;act_addr_fam=InterNetwork;
X-Ms-Keyvault-Region: eastus2
X-Ms-Keyvault-Service-Version: 1.9.12.0
X-Ms-Request-Id: 661a6c5c-5c49-420c-aa28-d5dfc4ed049f
X-Powered-By: ASP.NET

{"error":{"code":"Unauthorized","message":"AKV10000: Request is missing a Bearer or PoP token."}}: timestamp=2021-06-30T15:57:50.291-0400
2021-06-30T15:57:52.122-0400 [DEBUG] provider.terraform-provider-azurerm_v2.65.0_x5: AzureRM Request:
PUT /secrets/secret-sauce?api-version=7.1 HTTP/1.1
Host: myKeyVault.vault.azure.net
User-Agent: Go/go1.16.3 (amd64-linux) go-autorest/v14.2.1 Azure-SDK-For-Go/v55.3.0 keyvault/7.1 HashiCorp Terraform/1.0.1 (+https://www.terraform.io) Terraform Plugin SDK/2.6.1 terraform-provider-azurerm/2.65.0 pid-222c6c49-1b0a-5959-a213-6608f9eb8820
Content-Length: 63
Content-Type: application/json; charset=utf-8
X-Ms-Correlation-Request-Id: 0a385f18-ebb3-d305-bf57-37aec498660a
Accept-Encoding: gzip

{"attributes":{},"contentType":"","tags":{},"value":"szechuan"}: timestamp=2021-06-30T15:57:52.122-0400
2021-06-30T15:57:52.580-0400 [DEBUG] provider.terraform-provider-azurerm_v2.65.0_x5: AzureRM Response for https://myKeyVault.vault.azure.net/secrets/secret-sauce?api-version=7.1:
HTTP/2.0 409 Conflict
Content-Length: 176
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
Date: Wed, 30 Jun 2021 19:57:50 GMT
Expires: -1
Pragma: no-cache
Strict-Transport-Security: max-age=31536000;includeSubDomains
X-Content-Type-Options: nosniff
X-Ms-Keyvault-Network-Info: conn_type=Ipv4;addr=144.160.228.102;act_addr_fam=InterNetwork;
X-Ms-Keyvault-Region: eastus2
X-Ms-Keyvault-Service-Version: 1.9.12.0
X-Ms-Request-Id: b1c6683d-909d-4ee5-8dab-7f21051e24a2
X-Powered-By: ASP.NET

{"error":{"code":"Conflict","message":"Secret secret-sauce is currently being recovered and cannot be re-created; retry later.","innererror":{"code":"ObjectIsBeingRecovered"}}}: timestamp=2021-06-30T15:57:52.580-0400
╷
│ Error: keyvault.BaseClient#SetSecret: Failure responding to request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=409 Code="Conflict" Message="Secret secret-sauce is currently being recovered and cannot be re-created; retry later." InnerError={"code":"ObjectIsBeingRecovered"}
│
│   with azurerm_key_vault_secret.example,
│   on main.tf line 52, in resource "azurerm_key_vault_secret" "example":
│   52: resource "azurerm_key_vault_secret" "example" {
│
╵
2021-06-30T15:57:52.600-0400 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-06-30T15:57:52.610-0400 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/azurerm/2.65.0/linux_amd64/terraform-provider-azurerm_v2.65.0_x5 pid=25850
2021-06-30T15:57:52.611-0400 [DEBUG] provider: plugin exited

### Expected Behaviour

Should be able to wait for recovery to complete.

### Actual Behaviour

Timout

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

The issue is intermittent can only be produced if key vault takes time to recover the deleted secert/key. This is currently happening in eastus2 region.

**Comment by dvob** [comment] 2021-07-08 08:39
This looks like a duplicate of #12285

**Comment by tombuildsstuff** [comment] 2021-09-16 05:51
Duplicate of #12285

**Closed by tombuildsstuff** 2021-09-16 05:51 UTC
Labels: bug, service/keyvault
