### ISSUE TITLE
Improve validation for azurerm_firewall_network_rule_collection protocols argument

### ISSUE THREAD

**Issue by crawfs** [hashicorp/terraform-provider-azurerm#13558] opened 2021-09-30 00:39 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently the azurerm provider does not appear to perform a full validation of values for the protocols argument in the azurerm_firewall_network_rule_collection resource, so if an invalid value is provided (such as "*") terraform plan and terraform validate will appear correct however the apply stage will fail. Any chance we can get improved validation for this?

Currently using azurerm version 2.63 but looking through the changelogs there should be no changes relevant to this in future patches

### New or Affected Resource(s)

* azurerm_firewall_network_rule_collection 

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by stephybun** [comment] 2021-10-04 08:49
Hi @crawfs, thanks for raising this. Could you please provide the terraform config that caused this issue? I tried reproducing it but any invalid arguments were flagged correctly in the plan stage.
```
$ terraform plan

│ Error: expected rule.0.protocols.0 to be one of [Any ICMP TCP UDP], got *
│ 
│   with azurerm_firewall_network_rule_collection.example,
│   on main.tf line 55, in resource "azurerm_firewall_network_rule_collection" "example":
│   55: resource "azurerm_firewall_network_rule_collection" "example" {
```

**Comment by crawfs** [comment] 2021-10-04 22:51
Ah, fair enough yeah our setup is a little bit different and I didn't test with more common usage examples, our configuration uses a dynamic block for the "rule" attribute block as shown:

```
locals {
network_rules = [
        {
            "name"  = "rule1"
            "source_addresses" = [
                "10.0.0.0/24"
            ]
            "destination_addresses" = [
               "10.1.0.0/24"
            ]
            "destination_ports" = "22"
            "protocols" = "TCP"
        },
        {
            "name"  = "rule2"
            "source_addresses" = [
                "10.1.0.0/24"
            ]
            "destination_addresses" = [
               "10.2.0.0/24"
            ]
            "destination_ports" = "443"
            "protocols" = "TCP"
        },
}

resource "azurerm_firewall_network_rule_collection" "rules" {
  name                = "rules"
  azure_firewall_name = azurerm_firewall.firewall.name
  resource_group_name = azurerm_resource_group.vnet_rg.name
  priority            = 100
  action              = "Allow"

  dynamic "rule" {
    for_each = [for r in local.network_rules: {
      name                  = r.name
      description           = lookup(r, "description", null)
      source_addresses      = lookup(r, "source_addresses", null)
      source_ip_groups      = lookup(r, "source_ip_groups", null)
      destination_addresses = lookup(r, "destination_addresses", null)
      destination_ip_groups = lookup(r, "destination_ip_groups", null)
      destination_fqdns     = lookup(r, "destination_fqdns", null)
      destination_ports     = lookup(r, "destination_ports", null)
      protocols             = r.protocols
    }]
    content {
      name                  = rule.value.name
      description           = rule.value.description
      source_addresses      = rule.value.source_addresses == null ? [] : flatten([rule.value.source_addresses])
      source_ip_groups      = rule.value.source_ip_groups == null ? [] : flatten([rule.value.source_ip_groups])
      destination_addresses = rule.value.destination_addresses == null ? [] : flatten([rule.value.destination_addresses])
      destination_ip_groups = rule.value.destination_ip_groups == null ? [] : flatten([rule.value.destination_ip_groups])
      destination_fqdns     = rule.value.destination_fqdns == null ? [] : flatten([rule.value.destination_fqdns])
      destination_ports     = rule.value.destination_ports == null ? [] : flatten([rule.value.destination_ports])
      protocols             = rule.value.protocols == null ? [] : flatten([rule.value.protocols])
    }
  }

}
```

Effectively I pass in a list of maps (local.network_rules) and convert it to an object to handle all of the optional attributes so that all rules can be handled in a locals variable, I'm open to being told that there's a better way of implementing this but apart from slightly broken validation it works fairly well as far as the deployment itself goes

**Comment by jackofallops** [comment] 2021-10-08 07:40
Hi @crawfs - Since we're unable to reproduce this issue, and the validation is configured correctly to disallow `*`, I'm going to close this for the time being. If there's additional information can be provided to help us with the problem you're experiencing we can re-open it.

My only additional thought would be to check if any of the values in your rules map are interpolated from elsewhere. Specifically, if your `rule.5` entry could somehow be considered `Computed` by the plan, at which point Terraform is unable to perform plan-time validation for that value.

**Closed by jackofallops** 2021-10-08 07:40 UTC
Labels: enhancement, good first issue, service/firewall
