### ISSUE TITLE
when azurerm version upgraded due to latest features, it complain my old terraform state file is not valid, how to fix this issue

### ISSUE THREAD

**Issue by onenessboy** [hashicorp/terraform-provider-azurerm#18373] opened 2022-09-13 17:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.1

### AzureRM Provider Version

3.21.1

### Affected Resource(s)/Data Source(s)

azuerm_storage

### Terraform Configuration Files

```hcl
In 3.21.1
resource "azurerm_storage_account_network_rules" "example" {
  storage_account_id = azurerm_storage_account.example.id

  default_action             = "Allow"
  ip_rules                   = ["127.0.0.1"]
  virtual_network_subnet_ids = [azurerm_subnet.example.id]
  bypass                     = ["Metrics"]
}

In old Version of azure rm: 2.99
resource "azurerm_storage_account_network_rules" "firewall_rules" {
  resource_group_name  = var.rg_name
  storage_account_name = azurerm_storage_account.syn_st.name
  default_action             = "Allow"
  ip_rules                   = [data.http.ip.body]
}
```

### Debug Output/Panic Output

```shell
Error: Failed to decode resource from state
│ 
│ Error decoding "azurerm_public_ip.vpn-gateway-ip-vpn" from previous state: unsupported attribute "availability_zone"
╵
╷
Error: Failed to decode resource from state
│ 
│ Error decoding "azurerm_storage_account.storeacc" from previous state: unsupported attribute "allow_blob_public_access"
```

### Expected Behaviour

Expectation is Terraform should not complain that  resources created with old version of azurerm cannot be readable by new azurerm modules (syntax differences)

### Actual Behaviour

It has to refresh state and create resources accordingly

### Steps to Reproduce

Terraform apply,

Created resources with azurerm 2.99

5 days later I had upgrade my azurerm version to 3.21 due to vpn gateway tunnel type parameter passing

Now, it complains my old state file is not working which was created with 2.99 version , it cannot identify resources created with 2.99 version of azurerm

**Comment by magodo** [comment] 2022-09-16 02:45
@onenessboy Thanks for opening this issue!

This is an expected behavior as from v2.99 to v3.21.1 is a major version bump. Please follow the migration guide [here](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/3.0-upgrade-guide#migrating-to-new--renamed-resources). Additionally, you can checkout http://github.com/azure/aztfy, which makes the importing and constructing HCL a lot easier.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - I'm gonna close this issue for now so that we can keep this forum focused on that we instead ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community.html).

**Closed by magodo** 2022-09-16 02:45 UTC
