### ISSUE TITLE
case sensitivity in function serverfarm/serverFarm segment 

### ISSUE THREAD

**Issue by DamonStamper** [hashicorp/terraform-provider-azurerm#25447] opened 2024-03-27 18:04 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

I can't reopen but found https://github.com/hashicorp/terraform-provider-azurerm/issues/24727 which had similar issues.

Still seeing this issue on AzureRM 3.97.1.

Error: parsing "/subscriptions/*ID*/resourceGroups/*RG*/providers/Microsoft.Web/serverfarms/*name*": parsing segment "staticServerFarms": parsing the AppServicePlan ID: the segment at position 6 didn't match

Expected a AppServicePlan ID that matched:

> /subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/example-resource-group/providers/Microsoft.Web/serverFarms/serverFarmValue

However this value was provided:

> /subscriptions/*ID*/resourceGroups/*RG*/providers/Microsoft.Web/serverfarms/*name*
I looked up https://github.com/search?q=repo%3Ahashicorp%2Fgo-azure-helpers%20staticServerFarms&type=code but can't tell how it's supposed to be case insensitive.

### Terraform Version

0.13

### AzureRM Provider Version

3.97.1

### Affected Resource(s)/Data Source(s)

/subscriptions/*ID*/resourceGroups/*RG*/providers/Microsoft.Web/serverfarms/*name*

### Terraform Configuration Files

```hcl
confidential
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

Case insensitive.

### Actual Behaviour

Case sensitive

### Steps to Reproduce

Create an azure function. Modify the statefile so serverfarm/serverFarm is the opposite of what was created (which is how it was recorded in previous versions of the provider), rerun, watch fail.

**Comment by tombuildsstuff** [comment] 2024-04-03 07:52
hey @DamonStamper 

Resource ID Segments are supposed to be `camelCased` and as such the AzureRM Provider validates that this segment is `serverFarms` rather than `serverfarms` - as such if a different casing is provided then you'll get the error you're seeing here.

This validation is used both when importing resources and when validating the input for fields - and as such the Steps to Reproduce for this issue would workaround all of this validation - meaning that (as you're seeing) the internal parsing would fail.

As such unfortunately this behaviour is expected since an invalid value is being provided - but you can fix this issue by updating the value being provided - either by changing the Terraform Configuration and/or by using `terraform state rm` and `terraform import` to remove the incorrect resource from your state, and then re-import it with the correct Resource ID.

Since this issue will be fixed by updating the value being provided here, I'm going to close this issue for the moment - but should you have further questions I'd direct you towards [the Community Discuss forums](https://discuss.hashicorp.com).

Thanks!

**Closed by tombuildsstuff** 2024-04-03 07:52 UTC
Labels: question, service/app-service, v/3.x

**Comment by DamonStamper** [comment] 2024-04-03 14:38
So what's the point of the caseInsensitive functions? What happens when Azure changes the standard again?

I'd like a solution that is future proof.

**Comment by tombuildsstuff** [comment] 2024-04-03 15:20
@DamonStamper 

> What happens when Azure changes the standard again?

The ARM Team have decided that all Resource Types (eg. `serverFarms`) should be camelCased going forwards.

One of the key design choices about `hashicorp/go-azure-sdk` was to define a type for each Resource ID - and so we're now camelCasing the Key component of the Resource ID in order to keep a consistent casing, as per the Microsoft requirements.

> So what's the point of the caseInsensitive functions?

Unfortunately the Azure APIs/CLIs/Portal have a myriad of different behaviours around casing - with some returning these in all UPPER, others as provided and others in all lower. Ultimately Services are _supposed_ to parse Resource IDs case-insensitively and return these case-sensitively (that is, support `serverfarms` or `serverFarms` - but always return `serverFarms`) - but it depends on the Resource Provider, Resource Type, API Version and even the Azure Environment you're deploying to as to what the behaviour is.

Ultimately the case-insensitive functions allow us to handle the API returning data in any form (`serverfarms`, `ServerFarms`, `serverFarms`) and normalise the value back to `serverFarms` - meaning that the Key component can be treated case-sensitively to ensure resources provision consistently. Unfortunately we've seen a number of APIs which will allow provisioning a resource with the incorrect casing, but the resource in question ends up unusable (e.g. you can provision a cluster but can't login to it); therefore having these defined consistently allows us to resolve those issues whilst having a consistent casing for users to work with.

As such we parse all User input (e.g. fields, IDs at import time) case-sensitively, to ensure that the input data is consistent - and then parse the values returned from the API case-insensitively to normalise them back to what the users specified.
