### ISSUE TITLE
import APIM operation update fails on 2.90, passes on 2.88

### ISSUE THREAD

**Issue by ismasensei** [hashicorp/terraform-provider-azurerm#14735] opened 2021-12-27 13:34 UTC
Reporting the crash, will revert to 2.88. Hopefully the below provides enough detail
Command:
`
terraform state rm azurerm_api_management_api_operation.myfancyop
`
Error output:
```
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵


Stack trace from the terraform-provider-azurerm_v2.90.0_x5 plugin:

panic: interface conversion: interface {} is map[string]interface {}, not string

goroutine 88 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/apimanagement/schemaz.FlattenApiManagementOperationParameterExampleContract(0xc001acd590)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/services/apimanagement/schemaz/api_management.go:423 +0x3fc
github.com/hashicorp/terraform-provider-azurerm/internal/services/apimanagement/schemaz.FlattenApiManagementOperationRepresentation(0xc001ade4e0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/services/apimanagement/schemaz/api_management.go:196 +0x1db
github.com/hashicorp/terraform-provider-azurerm/internal/services/apimanagement.flattenApiManagementOperationRequestContract(0xc001c860a0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/services/apimanagement/api_management_api_operation_resource.go:300 +0x174
github.com/hashicorp/terraform-provider-azurerm/internal/services/apimanagement.resourceApiManagementApiOperationRead(0xc001492a00, {0x54f0ae0, 0xc0012d3880})
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/services/apimanagement/api_management_api_operation_resource.go:208 +0x5ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x5dbcd00, {0x64bf8b8, 0xc0015fc9c0}, 0x24, {0x54f0ae0, 0xc0012d3880})
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:346 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0004b27e0, {0x64bf8b8, 0xc0015fc9c0}, 0xc00151a9c0, {0x54f0ae0, 0xc0012d3880})
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:635 +0x35b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00016e150, {0x64bf8b8, 0xc0015fc9c0}, 0xc0015fca40)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:576 +0x534
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0001b8f80, {0x64bf960, 0xc0019bfa10}, 0xc001500900)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server/server.go:553 +0x3b0
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x5a25520, 0xc0001b8f80}, {0x64bf960, 0xc0019bfa10}, 0xc0015008a0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000235340, {0x650d868, 0xc000193200}, 0xc001512d80, 0xc000c5a390, 0xaa17350, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0xc6f
google.golang.org/grpc.(*Server).handleStream(0xc000235340, {0x650d868, 0xc000193200}, 0xc001512d80, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1617 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:940 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:938 +0x294

Error: The terraform-provider-azurerm_v2.90.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by MarioArriaga92** [comment] 2022-01-04 22:04
Also happened to me:
```
│ Error: Request cancelled
│ 
│   with azurerm_role_assignment.ado_terraform_role,
│   on main.tf line 53, in resource "azurerm_role_assignment" "ado_terraform_role":
│   53: resource "azurerm_role_assignment" "ado_terraform_role" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│ 
│   with azurerm_role_assignment.ihealth_ad_group_role,
│   on main.tf line 59, in resource "azurerm_role_assignment" "ihealth_ad_group_role":
│   59: resource "azurerm_role_assignment" "ihealth_ad_group_role" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
Error: Plugin did not respond
│ 
│   with azurerm_storage_account.main_storage,
│   on main.tf line 176, in resource "azurerm_storage_account" "main_storage":
│  176: resource "azurerm_storage_account" "main_storage" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.
... (several other similar error output for different resources)

created by github.com/hashicorp/go-plugin.newGRPCStdioServer
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/go-plugin/grpc_stdio.go:37 +0xfa

goroutine 21 [IO wait]:
internal/poll.runtime_pollWait(0x7f03b6ed14d8, 0x72)
	/opt/goenv/versions/1.17.3/src/runtime/netpoll.go:234 +0x89
internal/poll.(*pollDesc).wait(0xc0010ca6c0, 0xc00030e000, 0x1)
	/opt/goenv/versions/1.17.3/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/opt/goenv/versions/1.17.3/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc0010ca6c0, {0xc00030e000, 0x1000, 0x1000})
	/opt/goenv/versions/1.17.3/src/internal/poll/fd_unix.go:167 +0x25a
os.(*File).read(...)
	/opt/goenv/versions/1.17.3/src/os/file_posix.go:32
os.(*File).Read(0xc00012ae70, {0xc00030e000, 0x400, 0x53ea1c0})
	/opt/goenv/versions/1.17.3/src/os/file.go:119 +0x5e
bufio.(*Reader).Read(0xc000073740, {0xc00030b000, 0x400, 0x0})
	/opt/goenv/versions/1.17.3/src/bufio/bufio.go:227 +0x1b4
github.com/hashicorp/go-plugin.copyChan({0x6698d10, 0xc0000cea00}, 0x0, {0x6470100, 0xc00012ae70})
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/go-plugin/grpc_stdio.go:181 +0x1f6
created by github.com/hashicorp/go-plugin.newGRPCStdioServer
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/go-plugin/grpc_stdio.go:38 +0x188

goroutine 23 [syscall]:
os/signal.signal_recv()
	/opt/goenv/versions/1.17.3/src/runtime/sigqueue.go:169 +0x98
os/signal.loop()
	/opt/goenv/versions/1.17.3/src/os/signal/signal_unix.go:24 +0x19
created by os/signal.Notify.func1.1
	/opt/goenv/versions/1.17.3/src/os/signal/signal.go:151 +0x2c

goroutine 24 [chan receive]:
github.com/hashicorp/go-plugin.Serve.func3()
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/go-plugin/server.go:434 +0x75
created by github.com/hashicorp/go-plugin.Serve
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/go-plugin/server.go:431 +0x1251

Error: The terraform-provider-azurerm_v2.90.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by MarioArriaga92** [comment] 2022-01-04 22:06
Here's full log outpu
[crash-terraform-provider-azurerm_v2.90.0_x5-plugin.txt](https://github.com/hashicorp/terraform-provider-azurerm/files/7810652/crash-terraform-provider-azurerm_v2.90.0_x5-plugin.txt)
t:

**Comment by xuzhang3** [comment] 2022-01-06 06:46
@MarioArriaga92   This issue is about APIM service, your error is `azurerm_storage_account`, you should open a new issue

**Comment by xuzhang3** [comment] 2022-01-06 09:16
Duplicate with #14707

**Comment by tombuildsstuff** [comment] 2022-01-17 11:05
Duplicate of #14707, thanks @xuzhang3

**Closed by tombuildsstuff** 2022-01-17 11:05 UTC
Labels: bug, crash, service/api-management
