### ISSUE TITLE
Bug in azurerm_resource_group_template_deployment

### ISSUE THREAD

**Issue by lundatic** [hashicorp/terraform-provider-azurerm#14379] opened 2021-11-29 17:08 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Output of `terraform -v`
```Terraform v1.0.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.86.0
```

### Affected Resource(s)

* `azurerm_group_template_deployment`

### Terraform Configuration Files

Terraform code

```
data "azurerm_client_config" "current" {}

resource "azurerm_resource_group" "resource_group_api" {
  name     = "rg-example-api-connections"
  location = "West Europe"

  lifecycle {
    prevent_destroy = true
  }
}

resource "azurerm_resource_group" "resource_group_la" {
  name     = "rg-example-log-analytics"
  location = "West Europe"

  lifecycle {
    prevent_destroy = true
  }
}


resource "azurerm_log_analytics_workspace" "log_analytics_workspace" {
  name                       = "Example-la"
  location                   = azurerm_resource_group.resource_group_la.location
  resource_group_name        = azurerm_resource_group.resource_group_la.name
  sku                        = "PerGB2018"
  retention_in_days          = 90
  daily_quota_gb             = -1 
  internet_ingestion_enabled = true
  internet_query_enabled     = true

  lifecycle {
    prevent_destroy = true
  }
}

resource "azurerm_resource_group_template_deployment" "api_connections" {
  name                             = "test-api-connections"
  resource_group_name = azurerm_resource_group.resource_group_api.name
  deployment_mode       = "Incremental"
  parameters_content    = jsonencode({
    log_analytics_workspace_id = {
      type  = "String"
      value = azurerm_log_analytics_workspace.log_analytics_workspace.workspace_id
    },
    log_analytics_workspace_key = {
      type  = "SecureString"
      value = azurerm_log_analytics_workspace.log_analytics_workspace.primary_shared_key
    },
    storage_account_name = {
      type  = "String"
      value = var.storage_account_name
    },
    storage_account_primary_key = {
      type  = "SecureString"
      value = var.storage_account_primary_key
    }
  })

  template_content = templatefile("${path.module}/modules/api-connections/api-connections.json", {
    location_long    = lower(replace("West Europe", " ", ""))
    location_short  = weu
    env                    = test
    subscription_id = data.azurerm_client_config.current.subscription_id
  })
}
```
Azure ARM template file (for reference):
```
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "location_long": {
      "type": "String",
      "defaultValue": "${location_long}"
    },
    "location_short": {
      "type": "String",
      "defaultValue": "${location_short}"
    },
    "log_analytics_connection_name": {
      "type": "String",
      "defaultValue": "azure_loganalytics_connection_${env}_${location_short}"
    },
    "log_analytics_connection_display_name": {
      "type": "String",
      "defaultValue": "Log_Analytics_Connection_${env}_${location_short}"
    },
    "log_analytics_workspace_id": {
      "type": "String",
      "defaultValue": ""
    },
    "log_analytics_workspace_key": {
      "type": "SecureString",
      "defaultValue": ""
    },
    "storage_account_name": {
      "type": "String",
      "defaultValue": "storage_account_name"
    },
    "storage_account_blobstore_connection_name": {
      "type": "String",
      "defaultValue": "azure_storageaccount_blobstore_connection_${env}_${location_short}"
    },
    "storage_account_blobstore_connection_display_name": {
      "type": "String",
      "defaultValue": "Storage_Account_Blob_Store_Connection_${env}_${location_short}"
    },
    "storage_account_fileshare_connection_name": {
      "type": "String",
      "defaultValue": "azure_storageaccount_fileshare_connection_${env}_${location_short}"
    },
    "storage_account_fileshare_connection_display_name": {
      "type": "String",
      "defaultValue": "Storage_Account_File_Share_Connection_${env}_${location_short}"
    },
    "storage_account_primary_key": {
      "type": "SecureString",
      "defaultValue": ""
    }
  },
  "variables": {},
  "resources": [
    {
      "type": "Microsoft.Web/connections",
      "name": "[parameters('log_analytics_connection_name')]",
      "apiVersion": "2016-06-01",
      "location": "[parameters('location_long')]",
      "properties": {
        "displayName": "[parameters('log_analytics_connection_display_name')]",
        "parameterValues": {
          "username": "[parameters('log_analytics_workspace_id')]",
          "password": "[parameters('log_analytics_workspace_key')]"
        },
        "api": {
          "id": "[concat('/subscriptions/','${subscription_id}', '/providers/Microsoft.Web/locations/', replace(toLower(parameters('location_long')), ' ', ''), '/managedApis/azureloganalyticsdatacollector')]"
        }
      },
      "dependsOn": []
    },
    {
      "type": "Microsoft.Web/connections",
      "name": "[parameters('storage_account_blobstore_connection_name')]",
      "apiVersion": "2016-06-01",
      "location": "[parameters('location_long')]",
      "properties": {
        "displayName": "[parameters('storage_account_blobstore_connection_display_name')]",
        "parameterValues": {
          "accessKey": "[parameters('storage_account_primary_key')]",
          "accountName": "[parameters('storage_account_name')]"
        },
        "api": {
          "id": "[concat('/subscriptions/','${subscription_id}', '/providers/Microsoft.Web/locations/', replace(toLower(parameters('location_long')), ' ', ''), '/managedApis/azureblob')]"
        }
      },
      "dependsOn": []
    },
    {
      "type": "Microsoft.Web/connections",
      "name": "[parameters('storage_account_fileshare_connection_name')]",
      "apiVersion": "2016-06-01",
      "location": "[parameters('location_long')]",
      "properties": {
        "displayName": "[parameters('storage_account_fileshare_connection_display_name')]",
        "parameterValues": {
          "accessKey": "[parameters('storage_account_primary_key')]",
          "accountName": "[parameters('storage_account_name')]"
        },
        "api": {
          "id": "[concat('/subscriptions/','${subscription_id}', '/providers/Microsoft.Web/locations/', replace(toLower(parameters('location_long')), ' ', ''), '/managedApis/azurefile')]"
        }
      },
      "dependsOn": []
    }
  ],
  "outputs": {
    "api_connection_loganalytics_datacollector_name": {
      "type": "String",
      "value": "[parameters('log_analytics_connection_name')]"
    }
  }
}
```

### Expected Behaviour

Two cases, depending on if `parameters_content` in `azurerm_resource_group_template_deployment.api_connections` should include type for each parameter or not:
* If it should, then `terraform apply` should complete successfully
* If it should not, then `terraform plan` should not change the api connection deployment every time a `terraform plan` is run (even when no changes have been made).

### Actual Behaviour

The two mentioned cases:
* When type is added for each parameter in `parameters_content`, terraform apply fails with:
```
Error: validating Template Deployment "test-api-connections" (Resource Group "rg-example-api-connections"): requesting validating: resources.DeploymentsClient#Validate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidDeploymentParameterType" Message="The type of deployment parameter 'log_analytics_workspace_id' should not be specified. Please see https://aka.ms/resource-manager-parameter-files for details."
│
│   with module.example.azurerm_resource_group_template_deployment.api_connections,
│   on modules/example/main.tf line 233, in resource "azurerm_resource_group_template_deployment" "api_connections":
│  233: resource "azurerm_resource_group_template_deployment" "api_connections" {
```

* When type is not added, `terraform plan`is saying that the api connection deployments needs to be changed every time (even when no changes to code has been made)

### Steps to Reproduce

Run the above example.

1. `terraform plan`
2. `terraform apply`

### Important Factoids

None.

### References

N/A

**Comment by tombuildsstuff** [comment] 2021-11-29 20:02
hi @lundatic 

Thanks for opening this issue.

Taking a look through here this error is coming back from the Azure ARM Templates API during validation - as such unfortunately this is by design within Azure, and isn't specific to Terraform - however I believe that in this instance you should be able to specify the Type and omit the default value (or set this to an empty string).

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but should you have further questions you should able to get an answer for this [on the Community Discuss forum](https://discuss.hashicorp.com).

Thanks!

**Closed by tombuildsstuff** 2021-11-29 20:02 UTC
Labels: question, service/template

**Comment by lundatic** [comment] 2021-11-30 09:54
Hi @tombuildsstuff. Thanks for the quick reply!

So then we obviously can't set type in `parameters_content` in the terraform code. Should the provider not then be updated to not say that the resource should be change every time you run a plan? Even if no updates/changes to the code has been made since the last apply?

Seems strange to me that terraform should want to change the resource every time, even when no change is actually happening. 

For reference, her is parts of the plan output when running it straight after a apply with no changes to the code
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.azure_sentinel_test.azurerm_resource_group_template_deployment.api_connections_eno will be updated in-place
  ~ resource "azurerm_resource_group_template_deployment" "api_connections_eno" {
        id                       = "/subscriptions/[REDACTED]/resourceGroups/[REDACTED]/providers/Microsoft.Resources/deployments/test-api-connections-eno"
        name                     = "test-api-connections-eno"
      ~ parameters_content       = (sensitive)
        # (6 unchanged attributes hidden)
    }

  # module.azure_sentinel_test.azurerm_resource_group_template_deployment.api_connections_weu will be updated in-place
  ~ resource "azurerm_resource_group_template_deployment" "api_connections_weu" {
        id                       = "/subscriptions/[REDACTED]/resourceGroups/[REDACTED]/providers/Microsoft.Resources/deployments/test-api-connections-weu"
        name                     = "test-api-connections-weu"
      ~ parameters_content       = (sensitive)
        # (6 unchanged attributes hidden)
    }

Plan: 0 to add, 2 to change, 0 to destroy.
```
