### ISSUE TITLE
CosmosDB Account default identity type issue

### ISSUE THREAD

**Issue by lukipro** [hashicorp/terraform-provider-azurerm#14439] opened 2021-12-02 10:56 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Running terraform plan against an imported CosmosDB Account shows:
```
  # azurerm_cosmosdb_account.beta will be updated in-place
  ~ resource "azurerm_cosmosdb_account" "beta" {
      + default_identity_type                 = "FirstPartyIdentity"
        id                                    = "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.DocumentDB/databaseAccounts/beta"
        name                                  = "beta"
        tags                                  = {
            "env"            = "beta"
            "heritage"       = "tfm/tg"
        }
        # (26 unchanged attributes hidden)



        # (5 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

If I run apply, it passes green. However subsequent plans show that update is needed again.

**Comment by lonegunmanb** [comment] 2021-12-06 03:13
Hello @lukipro , I'd like to reproduce this issue with the following procedures (with plugin 2.88.1):

1. `terraform apply -auto-approve` the following code:

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "rg" {
  name     = "zjhe-f14439"
  location = "eastus"
}

resource "azurerm_cosmosdb_account" "db" {
  name                = "zjhe-f14439"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  offer_type          = "Standard"
  kind                = "MongoDB"

  enable_automatic_failover = true

  capabilities {
    name = "EnableAggregationPipeline"
  }

  capabilities {
    name = "mongoEnableDocLevelTTL"
  }

  capabilities {
    name = "MongoDBv3.4"
  }

  capabilities {
    name = "EnableMongo"
  }

  consistency_policy {
    consistency_level       = "BoundedStaleness"
    max_interval_in_seconds = 300
    max_staleness_prefix    = 100000
  }

  geo_location {
    location          = "westus"
    failover_priority = 1
  }

  geo_location {
    location          = azurerm_resource_group.rg.location
    failover_priority = 0
  }
}
```

2. execute following commands:

```powershell
> terraform console
> azurerm_cosmosdb_account.db.default_identity_type
"FirstPartyIdentity"
```

As we can see, new provisioned cosmosdb's `default_identity_type` was `FirstPartyIdentity`, as we expected.

3. Copy tf code only to another new folder, and import cosmosdb by id:

```powershell
> terraform import azurerm_cosmosdb_account.db /subscriptions/############/resourceGroups/zjhe-f14439/p
roviders/Microsoft.DocumentDB/databaseAccounts/zjhe-f14439
```

4. Executing plan:

```powershell
terraform plan
azurerm_resource_group.rg: Refreshing state... [id=/subscriptions/############/resourceGroups/zjhe-f14439]
azurerm_cosmosdb_account.db: Refreshing state... [id=/subscriptions/############/resourceGroups/zjhe-f14439/providers/Microsoft.
DocumentDB/databaseAccounts/zjhe-f14439]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.
```

Would you please tell me how your cosmosdb account instance been created? I guess it was created outside Terraform right?

**Comment by lukipro** [comment] 2021-12-06 08:47
Hello @lonegunmanb ,

Thanks for looking into the issue.
You are right, the resource was created outside Terraform.

I happen to have that same resource in two environments. Both created outside Terraform, but one is showing "nothing to change" and the other one shows changes will be made.

Please see the JSON representation diff below (pulled from management.azure.com):
![image](https://user-images.githubusercontent.com/20760377/144814898-e8c09628-f7c2-4315-8b0c-f50f935d34be.png)

The one on the left shows no changes after importing, the one on the right shows changes required even after I apply them.
The only difference is that in the `defaultIdentity` property.

**Comment by lonegunmanb** [comment] 2021-12-06 11:55
Hi @lukipro , thanks for your reply. The Terraform philosophy as far as I know is, if you manage infra via Terraform, you should manage all infras via Terraform.

The `defaultIdentity` has a default value `FirstPartyIdentity`, when Terraform generated a plan, it read resource's state from API then diff with the state that local code described. In this case, if `defaultIdentity` was absent, then Terraform would consider it should be `FirstPartyIdentity` because it's default value. Your left side code has the very same value so "nothing to change" but right side code would caused a diff. When a field has  a default value, we left this field absent does the same effect as set it to `null`, caused Terraform set it to default value, so I personally think the drift you met is inevitable unless you apply this plan. Is there any specific reason you must set it as `null`?

**Comment by lukipro** [comment] 2021-12-06 12:54
Hello @lonegunmanb 

Yes, I would like Terraform to set that field to `FirstPartyIdentity`. The problem is that it doesn't :)

If I apply the plan, it finishes fine, all green etc.
But subsequent plan tells me that Terraform wants to set that field to `FirstPartiIdentity` again...

**Comment by lonegunmanb** [comment] 2021-12-06 13:46
Hi @lukipro , I would try to reproduce this issue on my site. I'll update here if I've got any progress.

**Comment by lonegunmanb** [comment] 2021-12-07 03:05
Hi @lukipro , I cannot reproduce this issue on my machine, here's my procedures:

1. Modify provider code, remove default value and validate function for `default_identity_type` in cosmosdb_account_resource.go file:

```go
"default_identity_type": {
				Type:     pluginsdk.TypeString,
				Optional: true,
				//Default:  "FirstPartyIdentity",
				//ValidateFunc: validation.Any(
				//	validation.StringMatch(regexp.MustCompile(`^UserAssignedIdentity(.)+$`), "It may start with `UserAssignedIdentity`"),
				//	validation.StringInSlice([]string{
				//		"FirstPartyIdentity",
				//		"SystemAssignedIdentity",
				//	}, false),
				//),
			},
```

2. Use this modified plugin to create an `azurerm_cosmosdb_account` instance without `default_identity_type`:

```hcl
resource "azurerm_cosmosdb_account" "db" {
  name                = "zjhe-f14439"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  offer_type          = "Standard"
  kind                = "MongoDB"

  enable_automatic_failover = true
  capabilities {
    name = "EnableAggregationPipeline"
  }

  capabilities {
    name = "mongoEnableDocLevelTTL"
  }

  capabilities {
    name = "MongoDBv3.4"
  }

  capabilities {
    name = "EnableMongo"
  }

  consistency_policy {
    consistency_level       = "BoundedStaleness"
    max_interval_in_seconds = 300
    max_staleness_prefix    = 100000
  }

  geo_location {
    location          = "westus"
    failover_priority = 1
  }

  geo_location {
    location          = azurerm_resource_group.rg.location
    failover_priority = 0
  }
}
```

3. `terraform apply -auto-approve`, then check `default_identity_type`:

```powershell
> terraform console
> azurerm_cosmosdb_account.db.default_identity_type
"FirstPartyIdentity"
```

4. Re-run `terraform apply -auto-approve` and check the plan:

```powershell
> terraform apply -auto-approve
azurerm_resource_group.rg: Refreshing state... [id=/subscriptions/#################/resourceGroups/zjhe-f14439]
azurerm_cosmosdb_account.db: Refreshing state... [id=/subscriptions/#################/resourceGroups/zjhe-f14439/providers/Microsoft.
DocumentDB/databaseAccounts/zjhe-f14439]

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # azurerm_cosmosdb_account.db has been changed
  ~ resource "azurerm_cosmosdb_account" "db" {
        id                                    = "/subscriptions/#################/resourceGroups/zjhe-f14439/providers/Microsoft.Docu
mentDB/databaseAccounts/zjhe-f14439"
        name                                  = "zjhe-f14439"
      + network_acl_bypass_ids                = []
      + tags                                  = {}
        # (27 unchanged attributes hidden)





        # (9 unchanged blocks hidden)
    }
  # azurerm_resource_group.rg has been changed
  ~ resource "azurerm_resource_group" "rg" {
        id       = "/subscriptions/#################/resourceGroups/zjhe-f14439"
        name     = "zjhe-f14439"
      + tags     = {}
        # (1 unchanged attribute hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include  
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── 

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # azurerm_cosmosdb_account.db will be updated in-place
  ~ resource "azurerm_cosmosdb_account" "db" {
      - default_identity_type                 = "FirstPartyIdentity" -> null
        id                                    = "/subscriptions/#################/resourceGroups/zjhe-f14439/providers/Microsoft.Docu
mentDB/databaseAccounts/zjhe-f14439"
        name                                  = "zjhe-f14439"
        tags                                  = {}
        # (27 unchanged attributes hidden)





        # (9 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
azurerm_cosmosdb_account.db: Modifying... [id=/subscriptions/#################/resourceGroups/zjhe-f14439/providers/Microsoft.Documen
tDB/databaseAccounts/zjhe-f14439]
azurerm_cosmosdb_account.db: Still modifying... [id=/subscriptions/#################-...ocumentDB/databaseAccounts/zjhe-f14439, 10s elapsed]

```

As you can see, Terraform did try to set `default_identity_type` to null, but after apply, I still read `FirstPartyIdentity` in the state, and this value must be set in service side, I think from Terraform side we got nothing to do about it.

As Terraform create and modify this cosmosdb account via the sdk, and the sdk is nothing more than a simple wrap of Azure rest api, I felt confused on how to creating an account with null `default_identity_type`, would you give me some clue so I can give it a try? Thanks!

**Comment by lukipro** [comment] 2021-12-07 08:22
Thanks a lot @lonegunmanb 🍻 

Perhaps a good way to reproduce this issue is to create the CosmosDB Account with an ARM Template.
That ARM Template should have the `defaultIdentity` set to `""`.

Then running a plan/apply against such a created resource should show the behavior I observed.

**Comment by lonegunmanb** [comment] 2021-12-07 09:24
Ok @lukipro , thanks for your tip, I'll try when I got time.

**Comment by lonegunmanb** [comment] 2021-12-16 08:13
@lukipro , I've figure out why you've encountered this issue. Please do check my comment in #14630 and do some test to verify your data will be safe, after that, you can update your cosmosdb account by azure cli tool.

**Comment by tombuildsstuff** [comment] 2021-12-16 13:44
👋 

As mentioned [in this comment](https://github.com/hashicorp/terraform-provider-azurerm/issues/14630#issuecomment-995830318) this is an Azure API issue where there's an implied default value which isn't populated in the API response for older resources. Whilst it's (sometimes) possible to workaround this by adding a tag (or similar) to the resource - Terraform should instead be defaulting this implied default value in the Read function where this isn't returned from the API - as such this'll also need to be fixed in Terraform.

Thanks!

**Comment by allenhumphreys** [comment] 2021-12-16 14:46
While I 100% agree this is a provider bug, I personally wanted this to go away sooner. If you're not using the identities system for anything like me, you can _consider_ my work around to get rid of the null value from the API:

```
az cosmosdb identity assign -g <rg> -n <cosmosdb>
az cosmosdb update -g <rg> -n <cosmosdb> --default-identity SystemAssignedIdentity
az cosmosdb update -g <rg> -n <cosmosdb> --default-identity FirstPartyIdentity
az cosmosdb identity remove -g <rg> -n <cosmosdb>
```

In my situation, I have found this to get rid of the constant attempts to change Cosmos.

**Closed** 2021-12-16 20:06 UTC
Labels: bug, service/cosmosdb

**Comment by fgarcia-cnb** [comment] 2022-01-13 18:45
still having an issue in v2.91 of the provider. every run/apply keep trying to update the field:

```hcl
 ~ resource "azurerm_cosmosdb_account" "db" {
      + default_identity_type                 = "FirstPartyIdentity"
```

**Comment by reketen** [comment] 2022-01-14 12:22
also still have this issue. Azurerm provider v.2.90

**Comment by fgarcia-cnb** [comment] 2022-01-26 10:06
can we please get this fixed soon? this is preventing clean runs... and it seems like low hanging fruit...

**Comment by lonegunmanb** [comment] 2022-01-27 04:47
I cannot reproduce the issue on my side so please forgive me. Please backup your state file then try this:

1. `terraform apply -refresh-only`
2. `terraform plan`

Would TF tried to add `default_identity_type` again?

**Comment by lonegunmanb** [comment] 2022-01-27 04:50
I cannot reproduce the issue on my side so please forgive me. Please backup your state file then try this:

1. `terraform plan -refresh-only`
2. `terraform plan`

Would TF tried to add `default_identity_type` again?

**Comment by lonegunmanb** [comment] 2022-01-27 04:55
I cannot reproduce the issue on my side so please forgive me. Please backup your state file then try this:

1. `terraform apply -refresh-only`
2. `terraform plan`

Would TF tried to add `default_identity_type` again?

**Comment by fgarcia-cnb** [comment] 2022-01-27 10:08
it only happens on cosmosdb resourices that were deployed a while ago (probably before API changes). New cosmosdb resources wont have the issue. Luckily the fix mentioned by @allenhumphreys does the trick
