### ISSUE TITLE
Upstream Azure API error unable to create azurerm_recovery_services_vault with immutability locked

### ISSUE THREAD

**Issue by davepattie** [hashicorp/terraform-provider-azurerm#23792] opened 2023-11-06 20:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.7

### AzureRM Provider Version

3.77

### Affected Resource(s)/Data Source(s)

azurerm_recovery_services_vault

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

locals {
  location  = "eastus"
  name      = "backup-test"
}

resource "azurerm_resource_group" "resource_group" {
  location = local.location
  name     = format("rg-%s", local.name)
}

resource "azurerm_recovery_services_vault" "recovery_vault" {
  name                = format("rsv-%s", local.name)
  location            = local.location
  resource_group_name = azurerm_resource_group.resource_group.name
  immutability        = "Locked"
  sku                 = "Standard"
}
```

### Debug Output/Panic Output

```shell
Vault Name: "rsv-backup-test"): performing CreateOrUpdate: unexpected status 400 with error: UserErrorUnsupportedVaultImmutabilityStateChange: The immutable vault property for this vault is locked, hence, this setting cannot be disabled. The vault has its immutable vault property enabled and locked, and it can no longer be reverted to a non-immutable vault. Refer to the documentation to learn more: https://aka.ms/AB-ImmutableVaults-States
```

### Expected Behaviour

Recovery Vault is created

### Actual Behaviour

No vault is created and error is thrown

### Steps to Reproduce

terraform init
terraform apply

It is not a terraform issue but one of the Azure CLI.  It can also be reproduced running the command: 
`az backup vault create --location eastus --name rsv-backup-test --resource-group rg-backup-test --immutability-state Locked`

The workaround is to create the vault first unlocked and then reapply the configuration with the vault locked.  Documenting here so it can be linked to a Microsoft API issue, thank

**Comment by ziyeqf** [comment] 2023-11-07 11:13
Hi @davepattie, thanks for reporting.

per tesing, the `immutability` can not be directly set to `Locked` from `Disabled`, and it acts as same as Portal, which I personally assume it's by design. I have submiteed a PR to let terraform manage this correctly (https://github.com/hashicorp/terraform-provider-azurerm/compare/main...ziyeqf:tengzh/issue/vault_immutability?expand=1). Once it merged it should work fine.

Thanks!

**Closed** 2024-01-04 03:23 UTC
Labels: enhancement, service/recovery-services, v/3.x
