### ISSUE TITLE
Support for user-assigned managed identity in resource synapse_workspace

### ISSUE THREAD

**Issue by cookieofcode** [hashicorp/terraform-provider-azurerm#14761] opened 2021-12-31 11:02 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

While creating or updating a synapse workspace, in addition to the automatically created system-assigned identity, a user-assigned managed identity can be configured on the synapse workspace. Currently, "synapse_workspace_resource" does not allow to specify an identity. It is possible to add a user-assigned identity in the Azure Synapse Workspace manually, after the workspace has been activated.

### New or Affected Resource(s)

* azurerm_synapse_workspace_resource

### Potential Terraform Configuration

```hcl
resource "azurerm_user_assigned_identity" "uai" {
  name                = "example"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
}

resource "azurerm_synapse_workspace" "synapse" {
  name                                 = "example"
  resource_group_name                  = azurerm_resource_group.rg.name
  location                             = azurerm_resource_group.rg.location
  storage_data_lake_gen2_filesystem_id = azurerm_storage_data_lake_gen2_filesystem.filesystem.id
  sql_administrator_login              = "sqladminuser"
  sql_administrator_login_password     = "example"

  identity = azurerm_user_assigned_identity.uai.principal_id
}
```

### References

* https://docs.microsoft.com/en-us/rest/api/synapse/workspaces/create-or-update#request-body
* https://docs.microsoft.com/en-us/azure/data-factory/data-factory-service-identity?tabs=data-factory

**Comment by si-te** [comment] 2022-01-07 15:37
This would also apply to service/data-factory label. #14856 is a prerequisite for this issue.

**Comment by aristosvo** [comment] 2022-03-21 12:52
This is a duplicate of #13752 - please subscribe to that issue for updates.

**Closed by aristosvo** 2022-03-21 12:52 UTC
Labels: enhancement, service/synapse
