### ISSUE TITLE
Cannot create or import Linux azurerm_linux_web_app_slot

### ISSUE THREAD

**Issue by vanmash** [hashicorp/terraform-provider-azurerm#19411] opened 2022-11-23 15:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

v1.3.5

### AzureRM Provider Version

v3.32.0

### Affected Resource(s)/Data Source(s)

azurerm_linux_web_app_slot

### Terraform Configuration Files

```hcl
resource "azurerm_linux_web_app_slot" "slotlx" {
  name           = "QA"
  app_service_id = azurerm_service_plan.planlx.id

  site_config {}
}
```

### Debug Output/Panic Output

```shell
2022-11-23T16:17:30.052+0100 [ERROR] vertex "azurerm_linux_web_app_slot.slotlx" error: ID was missing the `sites` element
2022-11-23T16:17:30.052+0100 [ERROR] vertex "azurerm_linux_web_app_slot.slotlx (expand)" error: ID was missing the `sites` element
2022-11-23T16:17:30.052+0100 [ERROR] provider.terraform-provider-azurerm_v3.32.0_x5: Response contains error diagnostic: @module=sdk.proto diagnostic_summary="ID was missing the `sites` element" tf_rpc=ValidateResourceTypeConfig tf_req_id=494a2e11-69b3-35c4-6cc9-6a962b2fcfb6 tf_resource_type=azurerm_linux_web_app_slot @caller=github.com/hashicorp/terraform-plugin-go@v0.10.0/tfprotov5/internal/diag/diagnostics.go:56 diagnostic_severity=ERROR diagnostic_attribute=AttributeName("app_service_id") diagnostic_detail= tf_proto_version=5.2 tf_provider_addr=provider timestamp=2022-11-23T16:17:30.051+0100

Error: ID was missing the `sites` element

  with azurerm_linux_web_app_slot.slotlx,
  on main.tf line 410, in resource "azurerm_linux_web_app_slot" "slotlx":
 410:   app_service_id = azurerm_service_plan.planlx.id
```

### Expected Behaviour

Create a slot

### Actual Behaviour

fails

### Steps to Reproduce

terraform plan

**Comment by tombuildsstuff** [comment] 2022-11-24 16:39
hi @vanmash 

Thanks for opening this issue.

Taking a look through here the issue is that you're specifying the ID of the App Service Plan where we're expecting the ID of the App Service, as such it should be possible to fix this by updating:

>   app_service_id = azurerm_service_plan.planlx.id

to (presuming [a `azuerm_windows_web_app` resource](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_web_app) with the label `myapp` exists):

>  app_service_id = azurerm_windows_web_app.myapp.id

The error message being returned from Terraform indicates that the Resource ID we're expecting should include the `sites` key (e.g. `/subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/resGroup1/providers/Microsoft.Web/sites/site1`) - as such updating the value being provided here should fix this.

Since this will be fixed by updating the Terraform Configuration being used I'm going to close this issue for the moment, but should you have further usage questions I'd [direct you towards the Community Discuss forum](https://discuss.hashicorp.com).

Thanks!

**Closed by tombuildsstuff** 2022-11-24 16:39 UTC
Labels: question

**Comment by vanmash** [comment] 2022-11-24 20:13
Hey Tom @tombuildsstuff 

you're absolutely right! Silly of me 🤦
It worked just after referencing the correct resource.

I must say the error code might have been a bit clearer, though. 

Thanks!
