### ISSUE TITLE
Key Vault creation failing with SubnetsHaveNoServiceEndpointsConfigured

### ISSUE THREAD

**Issue by thrubovc** [hashicorp/terraform-provider-azurerm#11759] opened 2021-05-18 07:25 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_v2.59.0`
* `azurerm_key_vault`

### Terraform Configuration Files

```hcl
resource "azurerm_key_vault" "kv" {
  name                        = "kv-${var.project}-${var.location}-${var.environment_type}"
  location                    = var.location
  resource_group_name         = azurerm_resource_group.app_resource_group.name
  tenant_id                   = data.azurerm_client_config.current.tenant_id
  sku_name                    = "premium"
  purge_protection_enabled    = true
  network_acls {
    default_action             = "Deny"
    bypass                     = "AzureServices"
    virtual_network_subnet_ids = [data.terraform_remote_state.azure_spoke.outputs.subnets.snet-app-gateway.id]
  }
}

resource "azurerm_private_endpoint" "kv" {
  name                = "${azurerm_key_vault.kv.name}-private-endpoint"
  location            = var.location
  resource_group_name = azurerm_resource_group.app_resource_group.name
  subnet_id           = data.terraform_remote_state.azure_spoke.outputs.subnets.snet-private.id
  private_service_connection {
    name                           = "${azurerm_key_vault.kv.name}-private-endpoint"
    private_connection_resource_id = azurerm_key_vault.kv.id
    is_manual_connection           = false
    subresource_names = ["vault"]
  }
   private_dns_zone_group {
    name = "${azurerm_key_vault.kv.name}-private-zone"
    private_dns_zone_ids = [ data.terraform_remote_state.connectivity.outputs.private_endpoint_dns_zones.key_vault.id ]
  }
}
```

### Expected Behaviour

network ACLs are configured properly (the app gateway subnet is allowed and a private endpoint is set up)

### Actual Behaviour

terraform apply fails with an error saying:
```
Error: updating Vault: (Name "xyz" / Resource Group "xyz"): keyvault.VaultsClient#Update: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="VirtualNetworkNotValid" Message="Operation on Virtual Network could not be performed. StatusCode: 400 (BadRequest). Error Code: SubnetsHaveNoServiceEndpointsConfigured. Error Message: Subnets snet-app-gateway of virtual network /subscriptions/xyz/resourceGroups/rgxyz/providers/Microsoft.Network/virtualNetworks/xyz do not have ServiceEndpoints for Microsoft.KeyVault resources configured. Add Microsoft.KeyVault to subnet's ServiceEndpoints collection before trying to ACL Microsoft.KeyVault resources to these subnets.."

```

### Steps to Reproduce

* `terraform apply`

### Important Factoids

setup:
* application gateway using the key vault for certificates
* key vault is set up with a private endpoint
* in the key vault network ACLs, Microsoft trusted services are allowed and only the app gateway subnet is allowed

What I believe is happening is that terraform expects a service endpoint to be configured for the app gateway subnet in order to allow the subnet in the key vault network ACLs (which is not required when setting things up in Azure portal), since there is no private endpoint created yet.
EDIT:
I'll just add that once the key vault (or the private endpoint) is created manually and imported to terraform state, terraform apply works and leaves the correct setup in place

**Comment by favoretti** [comment] 2021-05-18 08:34
Hi and thank you for reporting this. Just guessing here, but I think it's not related to the private endpoint per se, but rather to the KV ACL, that states `bypass                     = "AzureServices"`. I think AzureServices require a Service Endpoint for KeyVault to be added to the subnet/vnet, rather than a private endpoint.

**Comment by thrubovc** [comment] 2021-05-18 09:19
I don't think so because in a different environment, we have the same setup created manually over the portal and the service endpoint is not necessary. there's an option not to configure the service endpoint - see the screenshot
![image](https://user-images.githubusercontent.com/34124990/118625987-c61d0700-b7ca-11eb-9f52-f88d6752a98b.png)

**Comment by favoretti** [comment] 2021-05-18 15:00
I see, and when you've selected that option - it was still created successfully? (Sorry, I should run some tests of my own I guess, but if you can help me out with more information here - would help to eventually fix the code if at all possible).

**Comment by thrubovc** [comment] 2021-05-18 15:03
Correct, if you tick that option, the key vault is created successfully, and the service endpoint isn't created at all.

**Comment by tombuildsstuff** [comment] 2021-11-15 13:38
👋 

Reading through here, this'll be using an older version of the API where that functionality isn't available - as such this appears to be working as intended in the latest API Version (since newer API versions validate that this exists)?

However for the moment since this appears to be working as intended (as it's required in newer versions of the API) - I'm going to close this issue for the moment.

Thanks!

**Closed by tombuildsstuff** 2021-11-15 13:38 UTC
Labels: question, service/keyvault
