### ISSUE TITLE
VMSS creation fails with Code="RetryableError" Message="A retryable error occurred."

### ISSUE THREAD

**Issue by uty** [hashicorp/terraform-provider-azurerm#8052] opened 2020-08-07 18:41 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

2.0

### Affected Resource(s)

* `azurerm_linux_virtual_machine_scale_set `

### Panic Output

```
Error: Error waiting for creation of Linux Virtual Machine Scale Set "test-master-1-scale" (Resource Group "test-resource-group"): Code="RetryableError" Message="A retryable error occurred."

  on master.tf line 72, in resource "azurerm_linux_virtual_machine_scale_set" "master_scale":
  72: resource "azurerm_linux_virtual_machine_scale_set" "master_scale" {
```

### Expected Behavior

The VMSS is created successfully.

### Actual Behavior

Terraform fails with given error

### Steps to Reproduce

1. Create a stack with several VMSS, loadbalancer, and vnet resources.
2. Run `terraform apply`

### Additional information

We have an automated job to create test infrastructure for K8S cluster that is being run every day. Sometimes the creation fails with the error provided above. Digging through this and talking to Azure Support we found that the Terraform provider doesn't retry errors on VMSS creation that were caused by a retriable errors from resources a VMSS depends on.

A quote from Azure Support:

>After doing further research, we found that the load balancer and the vnet peering were still in an updating state when the VMSS deployment script was trying to make changes. The error in all 4 instances  says that the resources were in an updating state because of a ‘putsubnetoperation’. Looking into the logs, we could see that there was a ‘putvirtualnetworkoperation’ which in turn started a ‘putsubnetoperation’ with the same correlation ID from the put VMSS event. This operation had showed that it completed, before the eventual PUT operation on the subnet began by the script but the load balancer and the vnet peering were still updating. This looks to be indicative of a timing issue with the script. The script is attempting to make further changes while the VNet resources are still in an updating state from a previous PUT operation.

How the error looks in Azure events (non-relevant fields omitted):
```
{
    ...
    "eventName": {
        "value": "EndRequest",
        "localizedValue": "End request"
    },
    "category": {
        "value": "Administrative",
        "localizedValue": "Administrative"
    },
    "eventTimestamp": "2020-08-02T16:23:16.2601059Z",
    "level": "Error",
    "operationName": {
        "value": "Microsoft.Compute/virtualMachineScaleSets/write",
        "localizedValue": "Create or Update Virtual Machine Scale Set"
    },
    "status": {
        "value": "Failed",
        "localizedValue": "Failed"
    },
    "subStatus": {
        "value": "",
        "localizedValue": ""
    },
    "submissionTimestamp": "2020-08-02T16:24:58.1015218Z",
    "properties": {
        "statusMessage": "{\"status\":\"Failed\",\"error\":{\"code\":\"ResourceOperationFailure\",\"message\":\"The resource operation completed with terminal provisioning state 'Failed'.\",\"details\":[{\"code\":\"RetryableError\",\"message\":\"A retryable error occurred.\"}]}}",
        "eventCategory": "Administrative"
    }
}
```

* #0000

**Comment by ArcturusZhang** [comment] 2020-12-21 08:48
Hi @uty thanks for this issue and sorry for the delay of response. 
Could you provide some more concrete information about the reproduction steps? Such as a config as example.
I used  a config with one VMSS and one load balancer and cannot reproduce this issue.

**Comment by favoretti** [comment] 2021-08-20 11:53
Thanks for opening this issue! Since this issue has been reported a long time ago and relates to an older version of provider - I'm going to close it. If this is still relevant and occurring on the latest version of terraform and provider please do open a new issue!

**Closed by favoretti** 2021-08-20 11:53 UTC
Labels: bug, service/vmss
