### ISSUE TITLE
Change to iothub_endpoint_eventhub showed in the Plan but was not applied during the Apply

### ISSUE THREAD

**Issue by GuyCarmy** [hashicorp/terraform-provider-azurerm#25373] opened 2024-03-22 09:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.3.9

### AzureRM Provider Version

3.55.0

### Affected Resource(s)/Data Source(s)

azurerm_iothub_endpoint_eventhub

### Terraform Configuration Files

```hcl
resource "azurerm_eventhub_authorization_rule" "senders_xx" {
  name                = "yy"
  namespace_name      = local.eventhub_namespace_name
  eventhub_name       = azurerm_eventhub.eventhub_name.name
  resource_group_name = data.azurerm_resource_group.resource_group.name
  listen              = false
  send                = true
  manage              = false
}

resource "azurerm_iothub_endpoint_eventhub" "iothub_endpoint_eventhub_xx" {
  resource_group_name = data.azurerm_resource_group.resource_group.name
  iothub_id           = azurerm_iothub.iothub.id
  name                = "xx"

  connection_string = azurerm_eventhub_authorization_rule.senders_xx.primary_connection_string
}
```

### Debug Output/Panic Output

```shell
-
```

### Expected Behaviour

I have re-created the azurerm_eventhub_authorization_rule (it was removed in a previous apply), and the change of the connection string in the azurerm_iothub_endpoint_eventhub showed on the terraform plan stage. I was expecting it to be updated on apply.

on plan it was: 1 to add, 1 to change, 0 to destroy

### Actual Behaviour

the change was not applied at all. on the apply it was: Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

the execution is part of CI flow and the apply is of the output file of the plan, so there was no changes in between.

### Steps to Reproduce

1. create a azurerm_eventhub_authorization_rule
2. create a azurerm_iothub_endpoint_eventhub using the connection string from above
3. recreate (change name for example which force replacement) the azurerm_eventhub_authorization_rule
4. the azurerm_iothub_endpoint_eventhub is not being updated.

**Comment by ziyeqf** [comment] 2024-03-29 02:33
Hi @GuyCarmy, thanks for opening the issue.

I tried with ` azureRM provider v3.97.1` and `Terraform v1.7.4`, while I can not reproduce the issue.Could you please upgrade your provider and Terraform to latest version, then give it another try?

Thanks!

**Comment by rcskosir** [comment] 2024-06-03 18:21
Thanks for taking the time to submit this issue. @ziyeqf was unable to reproduce this behavior. We’re going to close this issue for now, but if you run into this again with the latest Terraform and Provider versions, please feel free to [open a new issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/new/choose).

**Closed by rcskosir** 2024-06-03 18:21 UTC
Labels: waiting-response, service/iot-hub, v/3.x
