### ISSUE TITLE
Key Vault Access Policies Seem to Already Exists Even After Previous Manual Deletion of Key Vault and Everything Else

### ISSUE THREAD

**Issue by byteknacker** [hashicorp/terraform-provider-azurerm#16943] opened 2022-05-25 08:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.6

### AzureRM Provider Version

3.6.0

### Affected Resource(s)/Data Source(s)

azurerm_key_vault_access_policy

### Terraform Configuration Files

```hcl
resource "azurerm_key_vault_access_policy" "kvpolicy_tf" {
  key_vault_id = azurerm_key_vault.kv.id
  tenant_id    = data.azurerm_client_config.current.tenant_id
  object_id    = data.azurerm_client_config.current.object_id

  secret_permissions = ["Delete", "Get", "List", "Purge", "Set"]

  certificate_permissions = ["Get", "List", "Create", "Delete", "Update"]
}
```

### Debug Output/Panic Output

```shell
Error: A resource with the ID "data.azurerm_client_config.current.object_id" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_key_vault_access_policy" for more information.
│ 
│   with module.hub.azurerm_key_vault_access_policy.kvpolicy_hub_tf,
│   on .terraform/modules/hub/private_modules/hub/main.tf line 141, in resource "azurerm_key_vault_access_policy" "kvpolicy_hub_tf":
│  141: resource "azurerm_key_vault_access_policy" "kvpolicy_hub_tf" {
```

### Expected Behaviour

It should not error out with already exists as I deleted manually everything that the infra had. After the manual deletion of the Key Vault, all associated Key Vault access policies should be also deleted. 

### Actual Behaviour

Terraform errors out with already exists and needs to be imported. 

It could be that the error is referring to the service principal used for the Terraform agent itself. This service principal was generated manually and independently from any Terraform code. I did it prior to applying the Terraform configuration. Maybe I need to also configure this service principal within the same Terraform module. But I wish to do this manually since IAM is something I wish to control myself.

### Steps to Reproduce

1. terraform apply
2. terraform destroy
3. terraform apply: errors out

### Important Factoids

Running on self-hosted Gitlab Runner VM which is hosted on a VM on Azure

**Comment by sinbai** [comment] 2022-05-26 05:41
@byteknacker thank you for opening this issue here. I could not repro this issue with the following tf config and the above "Steps to Reproduce". Could you reproduce it with the tf config below and the repro steps?

```
provider "azurerm" {
  features {}
}

terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
	   version = "3.6.0"
    }
  }
}

data "azurerm_client_config" "current" {
}

resource "azurerm_resource_group" "test" {
  name     = "accessPolicy-example"
  location = "eastus"
}

resource "azurerm_key_vault" "test" {
  name                = "kv-example-0526"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  tenant_id           = data.azurerm_client_config.current.tenant_id
  sku_name            = "standard"
}

resource "azurerm_key_vault_access_policy" "test" {
  key_vault_id = azurerm_key_vault.test.id
  tenant_id    = data.azurerm_client_config.current.tenant_id
  object_id    = data.azurerm_client_config.current.object_id

  secret_permissions = ["Delete", "Get", "List", "Purge", "Set"]

  certificate_permissions = ["Get", "List", "Create", "Delete", "Update"]
}
```

**Comment by byteknacker** [comment] 2022-05-30 07:45
Your code is pretty much like mine. Now, can you try these steps:

1. Apply your code, this will run through successfully
2. Manually delete The resource group. Do not delete the key vault nor the key vault access policy individually. Just delete the rg. 
3. Delete the TF statefile
4. Reapply the TF code, this should give you my error. 

Can you also try the same procedure except this time without deleting the TF statefile? Everything else stays the same.

Make sure that the service principal for the azurerm_key_vault_access_policy.object_id is made by you manually in Azure AD prior to applying the code. This is not part of the TF configuration. 

Let me know.

**Comment by simon-an** [comment] 2022-05-31 08:23
We have the same issue. RG, Keyvault and Policies are created, still we get 
"already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_key_vault_access_policy" for more information."

Seams like the provider does not sets the policies in the state early enough. Deleting the affected policies and rerunning the apply works.

Same issue exists for secrets as well.

**Comment by bsladania** [comment] 2022-06-01 14:02
I'm using 3.7.0 azurerm providers' version and experiencing the same issue as @byteknacker mentioned earlier. Even it can be produced by just following the first two steps.

"1. Apply your code, this will run through successfully
2. Manually delete The resource group. Do not delete the key vault nor the key vault access policy individually. Just delete the rg."

**Comment by sinbai** [comment] 2022-06-02 08:13
Per the [doc](https://docs.microsoft.com/en-us/azure/key-vault/general/soft-delete-overview#soft-delete-behavior), when creating a new key vault, soft-delete is on by default. Manually delete the resource group, the key vault is not permanently deleted. So the error is expected. The keyvault could be permanently deleted by setting [purge_soft_delete_on_destroy = true in terraform feature block](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/features-block#purge_soft_delete_on_destroy ).

**Comment by sinbai** [comment] 2022-06-14 09:05
@byteknacker thank you for your reply. For the above context, are you okey if I close this issue?

**Comment by uvwildos** [comment] 2023-05-17 18:24
i wish it was so easy. I am getting slowed down sinced weeks by this......

**Comment by rcskosir** [comment] 2023-06-08 18:56
Ready to close per the Author, so I am going to mark this issue as closed. Thank you all for the collaboration.

**Closed by rcskosir** 2023-06-08 18:56 UTC

**Comment by dana23746** [comment] 2023-09-12 07:25
> Per the [doc](https://docs.microsoft.com/en-us/azure/key-vault/general/soft-delete-overview#soft-delete-behavior), when creating a new key vault, soft-delete is on by default. Manually delete the resource group, the key vault is not permanently deleted. So the error is expected. The keyvault could be permanently deleted by setting [purge_soft_delete_on_destroy = true in terraform feature block](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/features-block#purge_soft_delete_on_destroy).

Thanks a lot for the tip :)

**Comment by Laasya-07** [comment] 2024-02-27 06:10
I agree with kind of cleaning up the state file or deleting rg and stuff. But this isnt going to work when it comes to managing multiple environments that are live and running. We need a permanent solution. My soft delete is off and I am trying to create access policy from terraform itself. When I run terraform plan the second time, why is it adding the creation step of access policy again? I dont understand. Can someone help with a permanent workaround for this?

**Comment by inaun** [comment] 2024-04-21 02:17
There seems to be an underlying Terraform issue at play. I have this problem, and have *not* deleted the resource group. I did make an update to the Access Policy in my Terraform code then ran apply to deploy the update. I get the error stating access policy is not in my state file.
