### ISSUE TITLE
azurerm_log_analytics_solution - Failure responding to request: StatusCode=404 ... error: invalid character 'S' looking for beginning of value

### ISSUE THREAD

**Issue by rhollins** [hashicorp/terraform-provider-azurerm#1775] opened 2018-08-15 14:58 UTC
### Terraform Version

Terraform v0.11.7
+ provider.azurerm v1.12.0

### Affected Resource(s)

azurerm_log_analytics_solution

### Terraform Configuration Files

```
resource "azurerm_resource_group" "monitor_rg" {
  name     = "acctestRG-01"
  location = "NorthEurope"
  provider = "azurerm.default"
}

resource "azurerm_log_analytics_workspace" "acctest_la" {
  name                = "acctest-01"
  sku                 = "Free"
  location            = "westeurope"
  resource_group_name = "${azurerm_resource_group.monitor_rg.name}"
  provider            = "azurerm.default"
}

resource "azurerm_log_analytics_solution" "aks_s" {
  solution_name         = "Containers"
  workspace_resource_id = "${azurerm_log_analytics_workspace.acctest_la.id}"
  workspace_name        = "${azurerm_log_analytics_workspace.acctest_la.name}"
  location              = "westeurope"
  resource_group_name   = "${azurerm_resource_group.monitor_rg.name}"
  provider              = "azurerm.default"

  plan {
    publisher = "Microsoft"
    product   = "OMSGallery/Containers"
  }
}
```

### Debug Output

C:\Temp\aitest> terraform apply --var-file=".\terraform.tfvars"

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + azurerm_log_analytics_solution.aks_s
      id:                    <computed>
      location:              "westeurope"
      plan.#:                "1"
      plan.0.name:           <computed>
      plan.0.product:        "OMSGallery/Containers"
      plan.0.publisher:      "Microsoft"
      resource_group_name:   "acctestRG-01"
      solution_name:         "Containers"
      workspace_name:        "acctest-01"
      workspace_resource_id: "${azurerm_log_analytics_workspace.acctest_la.id}"

  + azurerm_log_analytics_workspace.acctest_la
      id:                    <computed>
      location:              "westeurope"
      name:                  "acctest-01"
      portal_url:            <computed>
      primary_shared_key:    <computed>
      resource_group_name:   "acctestRG-01"
      retention_in_days:     <computed>
      secondary_shared_key:  <computed>
      sku:                   "Free"
      tags.%:                <computed>
      workspace_id:          <computed>

  + azurerm_resource_group.monitor_rg
      id:                    <computed>
      location:              "northeurope"
      name:                  "acctestRG-01"
      tags.%:                <computed>

Plan: 3 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

azurerm_resource_group.monitor_rg: Creating...
  location: "" => "northeurope"
  name:     "" => "acctestRG-01"
  tags.%:   "" => "<computed>"
azurerm_resource_group.monitor_rg: Creation complete after 0s (ID: /subscriptions/<...>/resourceGroups/acctestRG-01)
azurerm_log_analytics_workspace.acctest_la: Creating...
  location:             "" => "westeurope"
  name:                 "" => "acctest-01"
  portal_url:           "" => "<computed>"
  primary_shared_key:   "<sensitive>" => "<sensitive>"
  resource_group_name:  "" => "acctestRG-01"
  retention_in_days:    "" => "<computed>"
  secondary_shared_key: "<sensitive>" => "<sensitive>"
  sku:                  "" => "Free"
  tags.%:               "" => "<computed>"
  workspace_id:         "" => "<computed>"
azurerm_log_analytics_workspace.acctest_la: Still creating... (10s elapsed)
azurerm_log_analytics_workspace.acctest_la: Still creating... (20s elapsed)
azurerm_log_analytics_workspace.acctest_la: Still creating... (30s elapsed)
azurerm_log_analytics_workspace.acctest_la: Still creating... (40s elapsed)
azurerm_log_analytics_workspace.acctest_la: Still creating... (50s elapsed)
azurerm_log_analytics_workspace.acctest_la: Still creating... (1m0s elapsed)
azurerm_log_analytics_workspace.acctest_la: Creation complete after 1m5s (ID: /subscriptions/<...>-...rationalinsights/workspaces/acctest-01)
azurerm_log_analytics_solution.aks_s: Creating...
  location:              "" => "westeurope"
  plan.#:                "" => "1"
  plan.0.name:           "" => "<computed>"
  plan.0.product:        "" => "OMSGallery/Containers"
  plan.0.publisher:      "" => "Microsoft"
  resource_group_name:   "" => "acctestRG-01"
  solution_name:         "" => "Containers"
  workspace_name:        "" => "acctest-01"
  workspace_resource_id: "" => "/subscriptions/<...>/resourcegroups/acctestrg-01/providers/microsoft.operationalinsights/workspaces/acctest-01"

Error: Error applying plan:

1 error(s) occurred:

* azurerm_log_analytics_solution.aks_s: 1 error(s) occurred:

* azurerm_log_analytics_solution.aks_s: Error retrieving Log Analytics Solution "Containers(acctest-01)" (Resource Group "acctestRG-01"): operationsmanagement.SolutionsClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: error response cannot be parsed: "Solution Not Found : solutionType Containers, workspace acctest-01" error: invalid character 'S' looking for beginning of value

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

### Expected Behavior

Solution should be assigned to existing log-analytics account

### Actual Behavior

Solution deployment fails

### Steps to Reproduce

run provided configuration

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by dcfsc** [comment] 2019-01-29 16:14
```
Terraform v0.11.11
+ provider.azurerm v1.21.0
```
Ours is a different error character "W" and is  `Error creating/updating` instead of `Error retrieving`

```
* azurerm_log_analytics_solution.akslaw: 1 error(s) occurred:

* azurerm_log_analytics_solution.akslaw: Error creating/updating Log Analytics Solution 
"ContainerInsights(prduse-xxx-law)" 
(Workspace "/subscriptions/xxxxxxx-xxxx-xxxx-xxxx-0eb53147bb93/resourcegroups/prduse-xxx-la-rg/providers/microsoft.operationalinsights/workspaces/prduse-xxx-law" 
/ Resource Group "prduse2xxxxxrg"): pollingTrackerBase#updateRawBody: 
failed to unmarshal response body: 
StatusCode=0 -- Original Error: invalid character 'W' looking for beginning of value
```

**Comment by dcfsc** [comment] 2019-01-29 16:24
> ```
> Terraform v0.11.11
> + provider.azurerm v1.21.0
> ```
> Ours is a different error character "W" and is `Error creating/updating` instead of `Error retrieving`
> 
> ```
> * azurerm_log_analytics_solution.akslaw: 1 error(s) occurred:
> 
> * azurerm_log_analytics_solution.akslaw: Error creating/updating Log Analytics Solution 
> "ContainerInsights(prduse-xxx-law)" 
> (Workspace "/subscriptions/xxxxxxx-xxxx-xxxx-xxxx-0eb53147bb93/resourcegroups/prduse-xxx-la-rg/providers/microsoft.operationalinsights/workspaces/prduse-xxx-law" 
> / Resource Group "prduse2xxxxxrg"): pollingTrackerBase#updateRawBody: 
> failed to unmarshal response body: 
> StatusCode=0 -- Original Error: invalid character 'W' looking for beginning of value
> ```

I tried again with the resource group matching the workspace resource group and it succeeded. Perhaps we could use some better error messages? Or we are not parsing them correctly...

**Comment by daniellima** [comment] 2019-02-08 19:40
Seeing the same error as dcfsc, on the same versions. Having the same resource name on the workspace and the solution don't help.

**Comment by yuretz** [comment] 2019-06-18 08:26
What solved the issue for me was setting `solution_name` to match the `plan.product`, which in my case was just `ContainerInsights`. I figured out the solution by enabling the debug log and inspecting raw API responses, so better error messages would be nice, indeed

**Comment by loopfish** [comment] 2019-10-31 14:47
Same issue as @dcfsc . Running Terraform v0.12.12 and provider.azurerm v1.36.1.

In our instance, our Log Analytics workspace is not in the same RG as the rest of the infrastructure, so we're using an aliased azurerm provider, 'azurerm.log'. Here is the script:

`data "azurerm_log_analytics_workspace" "log_analytics" {
  provider            = "azurerm.log"
  name                = var.log_analytics_name
  resource_group_name = "RG_Core_Infrastructure"
}


/* Create Azure SQL Analytics solution */

// Azure SQL Analytics
resource "azurerm_log_analytics_solution" "azure_sql_analytics" {
  provider            = "azurerm.log"
  location            = data.azurerm_log_analytics_workspace.log_analytics.location
  resource_group_name = data.azurerm_log_analytics_workspace.log_analytics.resource_group_name
  plan {
    product           = "OMSGallery/AzureSQLAnalytics"
    publisher         = "Microsoft"
  }
  solution_name         = "AzureSQLAnalytics"
  workspace_name        = data.azurerm_log_analytics_workspace.log_analytics.name
  workspace_resource_id = data.azurerm_log_analytics_workspace.log_analytics.workspace_id
}
`
Here is the result of Apply:

`2019-10-31T14:07:38.7164714Z Error: Error creating/updating Log Analytics Solution "AzureSQLAnalytics(sranonprod-loganalyrics)" (Workspace "c13b1e9b-a6c6-47a0-9c83-a863acfdf132" / Resource Group "rg_core_infrastructure"): pollingTrackerBase#updateRawBody: failed to unmarshal response body: StatusCode=0 -- Original Error: invalid character 'W' looking for beginning of value
2019-10-31T14:07:38.7164934Z 
2019-10-31T14:07:38.7166167Z   on main.tf line 51, in resource "azurerm_log_analytics_solution" "azure_sql_analytics":
2019-10-31T14:07:38.7167992Z   51: resource "azurerm_log_analytics_solution" "azure_sql_analytics" {`

**Comment by tomarv2** [comment] 2020-01-10 18:56
In our case the character is 'F':

```Error: Error creating/updating Log Analytics Solution (Workspace "/subscriptions/xxxxxxxxx/resourcegroups/xxxxx/providers/microsoft.operationalinsights/workspaces/security-xxxxxxx" / Resource Group "c7n-aks"): pollingTrackerBase#updateRawBody: failed to unmarshal response body: StatusCode=0 -- Original Error: invalid character 'F' looking for beginning of value```

**Comment by AshwinNikam** [comment] 2020-03-13 10:08
> In our case the character is 'F':
> 
> `Error: Error creating/updating Log Analytics Solution (Workspace "/subscriptions/xxxxxxxxx/resourcegroups/xxxxx/providers/microsoft.operationalinsights/workspaces/security-xxxxxxx" / Resource Group "c7n-aks"): pollingTrackerBase#updateRawBody: failed to unmarshal response body: StatusCode=0 -- Original Error: invalid character 'F' looking for beginning of value`
> 
> what worked for us is just using:
> 
> ` solution_name = "ContainerInsights`

Changing the name to "ContainerInsights` worked for us as well. Debugging terraform you can see that with other names you get a 400 bad request error for the underlying API
The reason for this seems to be the name passed to the API adds the name of workspace to it like so -
test1233ContainerInsights(test1233-workspace-**********)

Seems like an issue with the API and a good error message will really help.

API in question is - https://management.azure.com/subscriptions/*****/resourcegroups/******/providers/Microsoft.OperationsManagement/solutions/*******?api-version=2015-11-01-preview

**Comment by neil-yechenwei** [comment] 2020-06-02 07:45
Seems LogAnalytics.Solutions API failed to unmarshal response body when it failed to create solution. So raised an issue on Azure/azure-rest-api-specs#9672

**Comment by picardsrcd** [comment] 2020-09-29 02:17
perhaps a related issue. I got this error...then re-applied and was good..

```
Error: Error retrieving Log Analytics Solution "ADReplication(la-operations-vjhywhmlbmndfroveecsjfkilkkkwswrkoyyggulnwpcaxdni)" (Resource Group "rg-operations-wtimbuguxbymiqeqyngmpxudjxquvpqejjji"): operationsmanagement.SolutionsClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: error response cannot be parsed: "\"Solution Not Found : solutionType ADReplication, workspace la-operations-vjhywhmlbmndfroveecsjfkilkkkwswrkoyyggulnwpcaxdni\"" error: json: cannot unmarshal string into Go value of type azure.RequestError
```

**Comment by iarovyi** [comment] 2021-01-14 21:41
As well(
```
Error: Error creating/updating Log Analytics Solution "AzureAppGatewayAnalytics(.........)" (Workspace "........" / Resource Group "......."): pollingTrackerBase#updateRawBody: failed to unmarshal response body: StatusCode=0 -- Original Error: invalid character 'W' looking for beginning of value
01:19:56
```
```terraform
resource "azurerm_log_analytics_solution" "agw" {
  solution_name         = "AzureAppGatewayAnalytics"
  ...
  plan {
    publisher = "Microsoft"
    product   = "OMSGallery/AzureAppGatewayAnalytics"
  }
}
```

**Comment by dhensby** [comment] 2021-09-27 11:13
I've come up against this problem and looked through the debug logs to see what is going on.

When trying to create a log solution like so:

```hcl
resource "azurerm_log_analytics_solution" "log_analytics" {
  solution_name         = "VMInsights"
  location              = var.location
  resource_group_name   = var.rg_name
  workspace_resource_id = var.workspace_resource_id
  workspace_name        = var.workspace_name

  plan {
    product   = "Microsoft"
    publisher = "OMSGallery/VMInsights"
  }
}
```

I can see the following request sent:

```
plugin.terraform-provider-azurerm_v2.51.0_x5: [DEBUG] AzureRM Request:
plugin.terraform-provider-azurerm_v2.51.0_x5: PUT /subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/resource-group/providers/Microsoft.OperationsManagement/solutions/VMInsights%28log-analytics-workspace%29?api-version=2015-11-01-preview HTTP/1.1
plugin.terraform-provider-azurerm_v2.51.0_x5: Host: management.azure.com
plugin.terraform-provider-azurerm_v2.51.0_x5: User-Agent: Go/go1.16 (amd64-darwin) go-autorest/v14.2.1 Azure-SDK-For-Go/v52.3.0 operationsmanagement/2015-11-01-preview HashiCorp Terraform/0.14.8 (+https://www.terraform.io) Terraform Plugin SDK/1.16.0 terraform-provider-azurerm/dev pid-00000000-0000-0000-0000-000000000000
plugin.terraform-provider-azurerm_v2.51.0_x5: Content-Length: 359
plugin.terraform-provider-azurerm_v2.51.0_x5: Content-Type: application/json; charset=utf-8
plugin.terraform-provider-azurerm_v2.51.0_x5: X-Ms-Correlation-Request-Id: 00000000-0000-0000-0000-000000000000
plugin.terraform-provider-azurerm_v2.51.0_x5: Accept-Encoding: gzip
plugin.terraform-provider-azurerm_v2.51.0_x5:
plugin.terraform-provider-azurerm_v2.51.0_x5: {"location":"westeurope","plan":{"name":"VMInsights(log-analytics-workspace)","publisher":"OMSGallery/VMInsights","promotionCode":"","product":"Microsoft"},"properties":{"workspaceResourceId":"/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/resource-group/providers/Microsoft.OperationalInsights/workspaces/log-analytics-workspace"},"tags":{}}
...
plugin.terraform-provider-azurerm_v2.51.0_x5: [DEBUG] AzureRM Response for https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/resource-group/providers/Microsoft.OperationsManagement/solutions/VMInsights%28log-analytics-workspace%29?api-version=2015-11-01-preview:
plugin.terraform-provider-azurerm_v2.51.0_x5: HTTP/2.0 400 Bad Request
plugin.terraform-provider-azurerm_v2.51.0_x5: Content-Length: 238
plugin.terraform-provider-azurerm_v2.51.0_x5: Cache-Control: no-cache
plugin.terraform-provider-azurerm_v2.51.0_x5: Cachecontrol: no-cache
plugin.terraform-provider-azurerm_v2.51.0_x5: Content-Type: application/json; charset=utf-8
plugin.terraform-provider-azurerm_v2.51.0_x5: Date: Fri, 24 Sep 2021 13:09:45 GMT
plugin.terraform-provider-azurerm_v2.51.0_x5: Expires: -1
plugin.terraform-provider-azurerm_v2.51.0_x5: Pragma: no-cache
plugin.terraform-provider-azurerm_v2.51.0_x5: Server: Microsoft-IIS/10.0
plugin.terraform-provider-azurerm_v2.51.0_x5: Server: Microsoft-IIS/10.0
plugin.terraform-provider-azurerm_v2.51.0_x5: Strict-Transport-Security: max-age=31536000; includeSubDomains
plugin.terraform-provider-azurerm_v2.51.0_x5: X-Ams-Apiversion: WebAPI1.0
plugin.terraform-provider-azurerm_v2.51.0_x5: X-Content-Type-Options: nosniff
plugin.terraform-provider-azurerm_v2.51.0_x5: X-Ms-Correlation-Request-Id: 00000000-0000-0000-0000-000000000000
plugin.terraform-provider-azurerm_v2.51.0_x5: X-Ms-Ratelimit-Remaining-Subscription-Writes: 1197
plugin.terraform-provider-azurerm_v2.51.0_x5: X-Ms-Request-Id: 00000000-0000-0000-0000-000000000000
plugin.terraform-provider-azurerm_v2.51.0_x5: X-Ms-Routing-Request-Id: REDACTED:REDACTED:00000000-0000-0000-0000-000000000000
plugin.terraform-provider-azurerm_v2.51.0_x5: X-Powered-By: ASP.NET
plugin.terraform-provider-azurerm_v2.51.0_x5: X-Powered-By: ASP.NET
plugin.terraform-provider-azurerm_v2.51.0_x5:
plugin.terraform-provider-azurerm_v2.51.0_x5: For first party solution, the solution name has to be convention of solutionType(workspaceName), and the product has to be OMSGallery/solutionType.  For example, product OMSGallery/ChangeTracking, solution name ChangeTracking(myworkspace)
```

Note the last line is what is causing the reported errors (it is not a JSON payload so the go SDK fails to parse it successfully.

But we're being told the name is being formatted incorrectly, so if we try to update the name format in terraform like so:

```diff
resource "azurerm_log_analytics_solution" "log_analytics" {
-  solution_name         = "VMInsights"
+  solution_name         = "VMInsights(${var.workspace_name})"
  location              = var.location
  resource_group_name   = var.rg_name
  workspace_resource_id = var.workspace_resource_id
  workspace_name        = var.workspace_name

  plan {
    product   = "Microsoft"
    publisher = "OMSGallery/VMInsights"
  }
}
```

This results in a successful resource creation but yet we get (what appears to be) an application error from Terraform of `Error: Expected "VMInsights(log-analytics-workspace)(log-analytics-workspace)" to match 'Solution(WorkspaceName)'`. Debug logs:

```
plugin.terraform-provider-azurerm_v2.51.0_x5: PUT /subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/resource-group/providers/Microsoft.OperationsManagement/solutions/VMInsights%28log-analytics-workspace%29%28log-analytics-workspace%29?api-version=2015-11-01-preview HTTP/1.1
plugin.terraform-provider-azurerm_v2.51.0_x5: Host: management.azure.com
plugin.terraform-provider-azurerm_v2.51.0_x5: User-Agent: Go/go1.16 (amd64-darwin) go-autorest/v14.2.1 Azure-SDK-For-Go/v52.3.0 operationsmanagement/2015-11-01-preview HashiCorp Terraform/0.14.8 (+https://www.terraform.io) Terraform Plugin SDK/1.16.0 terraform-provider-azurerm/dev pid-00000000-0000-0000-0000-000000000000
plugin.terraform-provider-azurerm_v2.51.0_x5: Content-Length: 382
plugin.terraform-provider-azurerm_v2.51.0_x5: Content-Type: application/json; charset=utf-8
plugin.terraform-provider-azurerm_v2.51.0_x5: X-Ms-Correlation-Request-Id: 00000000-0000-0000-0000-000000000000
plugin.terraform-provider-azurerm_v2.51.0_x5: Accept-Encoding: gzip
plugin.terraform-provider-azurerm_v2.51.0_x5:
plugin.terraform-provider-azurerm_v2.51.0_x5: {"location":"westeurope","plan":{"name":"VMInsights(log-analytics-workspace)(log-analytics-workspace)","publisher":"OMSGallery/VMInsights","promotionCode":"","product":"Microsoft"},"properties":{"workspaceResourceId":"/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/resource-group/providers/Microsoft.OperationalInsights/workspaces/log-analytics-workspace"},"tags":{}}
plugin.terraform-provider-azurerm_v2.51.0_x5: [DEBUG] AzureRM Response for https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/resource-group/providers/Microsoft.OperationsManagement/solutions/VMInsights%28log-analytics-workspace%29%28log-analytics-workspace%29?api-version=2015-11-01-preview:
plugin.terraform-provider-azurerm_v2.51.0_x5: HTTP/2.0 201 Created
plugin.terraform-provider-azurerm_v2.51.0_x5: Content-Length: 1098
plugin.terraform-provider-azurerm_v2.51.0_x5: Cache-Control: no-cache
plugin.terraform-provider-azurerm_v2.51.0_x5: Cachecontrol: no-cache
plugin.terraform-provider-azurerm_v2.51.0_x5: Content-Type: application/json; charset=utf-8
plugin.terraform-provider-azurerm_v2.51.0_x5: Date: Fri, 24 Sep 2021 14:45:18 GMT
plugin.terraform-provider-azurerm_v2.51.0_x5: Expires: -1
plugin.terraform-provider-azurerm_v2.51.0_x5: Pragma: no-cache
plugin.terraform-provider-azurerm_v2.51.0_x5: Server: Microsoft-IIS/10.0
plugin.terraform-provider-azurerm_v2.51.0_x5: Server: Microsoft-IIS/10.0
plugin.terraform-provider-azurerm_v2.51.0_x5: Strict-Transport-Security: max-age=31536000; includeSubDomains
plugin.terraform-provider-azurerm_v2.51.0_x5: X-Ams-Apiversion: WebAPI1.0
plugin.terraform-provider-azurerm_v2.51.0_x5: X-Content-Type-Options: nosniff
plugin.terraform-provider-azurerm_v2.51.0_x5: X-Ms-Correlation-Request-Id: 00000000-0000-0000-0000-000000000000
plugin.terraform-provider-azurerm_v2.51.0_x5: X-Ms-Ratelimit-Remaining-Subscription-Writes: 1198
plugin.terraform-provider-azurerm_v2.51.0_x5: X-Ms-Request-Id: 00000000-0000-0000-0000-000000000000
plugin.terraform-provider-azurerm_v2.51.0_x5: X-Ms-Routing-Request-Id: REDACTED:REDACTED:00000000-0000-0000-0000-000000000000
plugin.terraform-provider-azurerm_v2.51.0_x5: X-Powered-By: ASP.NET
plugin.terraform-provider-azurerm_v2.51.0_x5: X-Powered-By: ASP.NET
plugin.terraform-provider-azurerm_v2.51.0_x5:
plugin.terraform-provider-azurerm_v2.51.0_x5: {
plugin.terraform-provider-azurerm_v2.51.0_x5:   "plan": {
plugin.terraform-provider-azurerm_v2.51.0_x5:     "name": "VMInsights(log-analytics-workspace)(log-analytics-workspace)",
plugin.terraform-provider-azurerm_v2.51.0_x5:     "publisher": "OMSGallery/VMInsights",
plugin.terraform-provider-azurerm_v2.51.0_x5:     "promotionCode": "",
plugin.terraform-provider-azurerm_v2.51.0_x5:     "product": "Microsoft"
plugin.terraform-provider-azurerm_v2.51.0_x5:   },
plugin.terraform-provider-azurerm_v2.51.0_x5:   "properties": {
plugin.terraform-provider-azurerm_v2.51.0_x5:     "workspaceResourceId": "/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/resource-group/providers/Microsoft.OperationalInsights/workspaces/log-analytics-workspace",
plugin.terraform-provider-azurerm_v2.51.0_x5:     "provisioningState": "Succeeded",
plugin.terraform-provider-azurerm_v2.51.0_x5:     "creationTime": "Fri, 24 Sep 2021 14:45:17 GMT",
plugin.terraform-provider-azurerm_v2.51.0_x5:     "lastModifiedTime": "Fri, 24 Sep 2021 14:45:17 GMT",
plugin.terraform-provider-azurerm_v2.51.0_x5:     "containedResources": [],
plugin.terraform-provider-azurerm_v2.51.0_x5:     "referencedResources": []
plugin.terraform-provider-azurerm_v2.51.0_x5:   },
plugin.terraform-provider-azurerm_v2.51.0_x5:   "id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/resource-group/providers/Microsoft.OperationsManagement/solutions/VMInsights(log-analytics-workspace)(log-analytics-workspace)",
plugin.terraform-provider-azurerm_v2.51.0_x5:   "name": "VMInsights(log-analytics-workspace)(log-analytics-workspace)",
plugin.terraform-provider-azurerm_v2.51.0_x5:   "type": "Microsoft.OperationsManagement/solutions",
plugin.terraform-provider-azurerm_v2.51.0_x5:   "location": "West Europe",
plugin.terraform-provider-azurerm_v2.51.0_x5:   "tags": {
plugin.terraform-provider-azurerm_v2.51.0_x5:     "environment": "dev",
plugin.terraform-provider-azurerm_v2.51.0_x5:     "last-review": "2020-10-29",
plugin.terraform-provider-azurerm_v2.51.0_x5:     "owner": "team-digital-legitimering"
plugin.terraform-provider-azurerm_v2.51.0_x5:   }
plugin.terraform-provider-azurerm_v2.51.0_x5: }
```

I'll do some digging into the provider code to see if there's some faulty validation logic, but this does seem a strange one as the initial requests look ok but we are seeing error responses from the azure api

**Comment by dhensby** [comment] 2021-09-27 13:50
To being my investigations I've first tried to make the raw API calls myself and the process is a bit confusing, however it seems that the `solution_name` is being used to perform too many tasks.

To create the Log Analytics Solution a PUT request is made to the Azure backend like so:

```http
PUT /subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.OperationsManagement/solutions/{resourceName}?api-version=2015-11-01-preview
Host: management.azure.com
Authorization: Bearer {token}

{"location":"{location}","plan":{"name":"VMInsights({logApplicationWorkspaceName})","publisher":"OMSGallery/VMInsights","promotionCode":"","product":"Microsoft"},"properties":{"workspaceResourceId":"/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.OperationalInsights/workspaces/{workspaceName}"},"tags":{}}
```

At the moment, the terraform provider is using `solutionName` to populate the plan name in the body of the request and to populate the resouceName in the URL. However, these don't need to be the same and even look like they should not be the name.

For example, using a resourceName of `vm-logging` works fine and a resource is created.

<img width="833" alt="Screenshot 2021-09-27 at 14 48 16" src="https://user-images.githubusercontent.com/563596/134921407-1352668b-254d-402a-a49c-d3d04d00b82e.png">

As such I think there are two fixes to be made here:

1. The internal logic that checks the name format matches `type(workspacename)` format needs to be less brittle
2. There should be a way to specify the resource name instead of the internals of the provider trying to construct it (incorrectly)

**Comment by manicminer** [comment] 2021-12-07 14:26
@dhensby I tried to reproduce this by sending a PUT request to create a log analytics solution having a custom resource name (as specified in the URL / resource ID) but keeping the convention of `plan(workspace)` for the plan name, but I still get the same 400 response with the [malformed] error `For first party solution, the solution name has to be convention of solutionType(workspaceName), and the product has to be OMSGallery/solutionType.  For example, product OMSGallery/ChangeTracking, solution name ChangeTracking(myworkspace)`

Here's an example of one that I tried:

```http
PUT /subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/acctestRG-211207141554848787/providers/Microsoft.OperationsManagement/solutions/acctest-Custom-f1o7q?api-version=2015-11-01-preview HTTP/1.1
Host: management.azure.com
Content-Length: 388
Authorization: Bearer <redacted>
Content-Type: application/json; charset=utf-8
X-Ms-Correlation-Request-Id: 00000000-0000-0000-0000-000000000000
Accept-Encoding: gzip

{
  "location": "westeurope",
  "plan": {
    "name": "VMInsights(acctestLAW-211207141554848787)",
    "publisher": "Microsoft",
    "promotionCode": "",
    "product": "OMSGallery/VMInsights"
  },
  "properties": {
    "workspaceResourceId": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/acctestRG-211207141554848787/providers/Microsoft.OperationalInsights/workspaces/acctestLAW-211207141554848787"
  },
  "tags": {}
}
```

Whilst this seems to have worked for you, I have not been able to reproduce. Perhaps I have misinterpreted your observations, but at this time it looks like the API is simply not reliable enough for us to offer this customization.

**Comment by pinaki-accenture** [comment] 2022-07-21 12:27
I used s`olution_name = "VMInsights"` and it worked perfectly for me.

```
azurerm = { version = "= 3.6.0" }
```

**Comment by katbyte** [comment] 2023-07-19 16:47
I am going to close this as it was opened for `v1.x` of the provider (2 major versions ago) which is no longer actively maintained and it appears both that there was a workaround and @manicminer was unable to reproduce it.

If this is still an issue with `v3.x` of the provider please do let us know by opening a new issue, thanks!

**Closed by katbyte** 2023-07-19 16:47 UTC
Labels: bug, upstream/microsoft, service/oms, v/1.x (legacy)
