### ISSUE TITLE
azurerm_public_ip doesn't set domain_name_label

### ISSUE THREAD

**Issue by Bessonov** [hashicorp/terraform-provider-azurerm#5633] opened 2020-02-06 22:15 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
Terraform v0.12.20
+ provider.azuread v0.7.0
+ provider.azurerm v1.43.0
+ provider.external v1.2.0
+ provider.null v2.1.2
+ provider.random v2.2.1
```

### Affected Resource(s)

* `azurerm_public_ip`

### Terraform Configuration Files

```hcl
resource "azurerm_public_ip" "aks_gw" {
	name                = "${var.env}_aks_gw"
	location            = local.var.location
	resource_group_name = "${local.var.resource_group_prefix}_aks_node"
	allocation_method   = "Static"
	sku                 = "Standard"
	domain_name_label   = replace(var.env, "_", "-")

	tags = {
		environment = var.env
	}

	depends_on = [
		azurerm_kubernetes_cluster.aks
	]
}

output "public_ip" {
	value = azurerm_public_ip.aks_gw.ip_address
}

output "public_fqdn" {
	value = azurerm_public_ip.aks_gw.fqdn
}
```

### Expected Behavior

DNS name should be set.

### Actual Behavior

Terraform produce correct output:
![image](https://user-images.githubusercontent.com/182451/73982893-71d37800-4935-11ea-92d1-ce84ec140446.png)

But the DNS label isn't set:

![image](https://user-images.githubusercontent.com/182451/73982703-0d181d80-4935-11ea-93bc-f0bec6b47b8e.png)

![image](https://user-images.githubusercontent.com/182451/73982793-418bd980-4935-11ea-8065-516c65e857d6.png)

No DNS resolution:
```bash
$ ping XXX.northeurope.cloudapp.azure.com
ping: XXX.northeurope.cloudapp.azure.com: Name or service not known

$ dig XXX.northeurope.cloudapp.azure.com

; <<>> DiG 9.11.3-1ubuntu1.11-Ubuntu <<>> XXX.northeurope.cloudapp.azure.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 46154
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
XXX.northeurope.cloudapp.azure.com. IN A

;; Query time: 62 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Thu Feb 06 22:11:10 UTC 2020
;; MSG SIZE  rcvd: 76

$ dig @8.8.8.8 XXX.northeurope.cloudapp.azure.com

; <<>> DiG 9.11.3-1ubuntu1.11-Ubuntu <<>> @8.8.8.8 XXX.northeurope.cloudapp.azure.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 21893
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;XXX.northeurope.cloudapp.azure.com. IN A

;; AUTHORITY SECTION:
northeurope.cloudapp.azure.com.	59 IN	SOA	prd1.azuredns-cloud.net. msnhst.microsoft.com. 10001 900 300 604800 60

;; Query time: 65 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Thu Feb 06 22:11:58 UTC 2020
;; MSG SIZE  rcvd: 152

```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

One time the label was set correctly and DNS resolution was working.

### References

Maybe related:
* https://github.com/hashicorp/terraform/issues/20472
* https://github.com/terraform-providers/terraform-provider-azurerm/issues/2964
* https://github.com/terraform-providers/terraform-provider-azurerm/issues/2956

**Comment by njuCZ** [comment] 2020-02-24 03:52
hello @Bessonov, I can reproduce this bug. I tested using the snippet, dns name was set correctly and dns resolution is correct. Could you give more details about how to reproduce it ?

**Comment by alexeyklots** [comment] 2020-02-26 15:10
Have the same issue. To workaround this just change the domain_name_label to something temporary run terraform apply you will see that DNS is set, finally use needed domain_name_label and rerun terraform.

**Comment by Bessonov** [comment] 2020-03-16 15:30
@njuCZ it seems that it doesn't happens the first time. It seems like if cluster was destroyed and setup again with same parameters, the public ip is the same, but DNS doesn't work anymore.

**Comment by favoretti** [comment] 2021-08-19 09:16
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.

**Closed by favoretti** 2021-08-19 09:16 UTC
Labels: bug, service/public-ip
