### ISSUE TITLE
value of tag_filter in configuration is not passed to the filterOperator value in the API

### ISSUE THREAD

**Issue by davelee212** [hashicorp/terraform-provider-azurerm#18914] opened 2022-10-21 10:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.3

### AzureRM Provider Version

3.28.0

### Affected Resource(s)/Data Source(s)

azurerm_automation_software_update_configuration

### Terraform Configuration Files

```hcl
resource "azurerm_automation_software_update_configuration" "patch_group_1" {
  name                  = "Windows - Patch Group 1"
  automation_account_id = module.automation_account.id
  operating_system      = "Windows"

  windows {
    classifications_included = ["Security", "Critical"]
    reboot = "IfRequired"
  }

  schedule {
    is_enabled = true
    frequency = "Month"
    interval = 1
    time_zone = "UTC"
    start_time = timeadd(timestamp(), "60m")
    expiry_time = timeadd(timestamp(), "87600h")
    monthly_occurrence {
      day = "Wednesday"
      occurrence = 2
    }
  }  

  target {

    azure_query {
      scope = [ "${data.azurerm_subscription.current.id}" ]
      tag_filter = "All"
      tags {
        tag = "updatemgmt"
        values = [ "Patch Group 1"]
      }
    }
  }
}
```

### Debug Output/Panic Output

```shell
│ Error: retreiving Software Update Configuration: (Name "Windows - Patch Group 1" / Automation Account Name "aa-itservices-prod-uksouth-001" / Resource Group "rg-itservices-prod-uksouth-management-001"): automation.SoftwareUpdateConfigurationsClient#GetByName: Failure responding to request: StatusCode=200 -- Original Error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal number into Go struct field TagSettingsProperties.updateConfiguration.targets.azureQueries.tagSettings.filterOperator of type automation.TagOperators' JSON = '{"id":"/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/rg-itservices-prod-uksouth-management-001/providers/Microsoft.Automation/automationAccounts/aa-itservices-prod-uksouth-001/softwareUpdateConfigurations/Windows - Patch Group 1","name":"Windows - Patch Group 1","type":null,"properties":{"updateConfiguration":{"operatingSystem":"Windows","windows":{"includedUpdateClassifications":"Critical, Security","excludedKbNumbers":[],"includedKbNumbers":[],"rebootSetting":"IfRequired"},"linux":null,"targets":{"azureQueries":[{"scope":["/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"],"tagSettings":{"tags":{"updatemgmt":["Patch Group 1"]},"filterOperator":0},"locations":[]}],"nonAzureQueries":null},"duration":"PT2H2M2S","azureVirtualMachines":null,"nonAzureComputerNames":null},"scheduleInfo":{"description":"","startTime":"2022-10-21T10:27:00+00:00","startTimeOffsetMinutes":0.0,"expiryTime":"2032-10-18T09:27:00+00:00","expiryTimeOffsetMinutes":0.0,"isEnabled":true,"nextRun":"2022-11-09T10:27:00+00:00","nextRunOffsetMinutes":0.0,"interval":1,"frequency":"Month","creationTime":"2022-10-21T09:27:00.17+00:00","lastModifiedTime":"2022-10-21T09:27:00.17+00:00","timeZone":"Etc/UTC","advancedSchedule":{"monthDays":null,"monthlyOccurrences":[{"day":"Wednesday","occurrence":2}],"weekDays":null}},"provisioningState":"Succeeded","createdBy":"{scrubbed}","error":null,"tasks":{"preTask":null,"postTask":null},"creationTime":"2022-10-21T09:27:00.1733333+00:00","lastModifiedBy":null,"lastModifiedTime":"2022-10-21T09:27:00.1966667+00:00"}}'
│
│   with azurerm_automation_software_update_configuration.patch_group_1,
│   on main.tf line 300, in resource "azurerm_automation_software_update_configuration" "patch_group_1":
│  300: resource "azurerm_automation_software_update_configuration" "patch_group_1" {
│
│ retreiving Software Update Configuration: (Name "Windows - Patch Group 1" / Automation Account Name
│ "aa-itservices-prod-uksouth-001" / Resource Group "rg-itservices-prod-uksouth-management-001"):
│ automation.SoftwareUpdateConfigurationsClient#GetByName: Failure responding to request: StatusCode=200 -- Original
│ Error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal number into Go struct field
│ TagSettingsProperties.updateConfiguration.targets.azureQueries.tagSettings.filterOperator of type
│ automation.TagOperators' JSON =
│ '{"id":"/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/rg-itservices-prod-uksouth-management-001/providers/Microsoft.Automation/automationAccounts/aa-itservices-prod-uksouth-001/softwareUpdateConfigurations/Windows
│ - Patch Group 1","name":"Windows - Patch Group
│ 1","type":null,"properties":{"updateConfiguration":{"operatingSystem":"Windows","windows":{"includedUpdateClassifications":"Critical,
│ Security","excludedKbNumbers":[],"includedKbNumbers":[],"rebootSetting":"IfRequired"},"linux":null,"targets":{"azureQueries":[{"scope":["/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"],"tagSettings":{"tags":{"updatemgmt":["Patch
│ Group
│ 1"]},"filterOperator":0},"locations":[]}],"nonAzureQueries":null},"duration":"PT2H2M2S","azureVirtualMachines":null,"nonAzureComputerNames":null},"scheduleInfo":{"description":"","startTime":"2022-10-21T10:27:00+00:00","startTimeOffsetMinutes":0.0,"expiryTime":"2032-10-18T09:27:00+00:00","expiryTimeOffsetMinutes":0.0,"isEnabled":true,"nextRun":"2022-11-09T10:27:00+00:00","nextRunOffsetMinutes":0.0,"interval":1,"frequency":"Month","creationTime":"2022-10-21T09:27:00.17+00:00","lastModifiedTime":"2022-10-21T09:27:00.17+00:00","timeZone":"Etc/UTC","advancedSchedule":{"monthDays":null,"monthlyOccurrences":[{"day":"Wednesday","occurrence":2}],"weekDays":null}},"provisioningState":"Succeeded","createdBy":"{scrubbed}","error":null,"tasks":{"preTask":null,"postTask":null},"creationTime":"2022-10-21T09:27:00.1733333+00:00","lastModifiedBy":null,"lastModifiedTime":"2022-10-21T09:27:00.1966667+00:00"}}'
```

### Expected Behaviour

Expected to be able to create a schedule for windows server updates targeted at a specific tag.

### Actual Behaviour

It fails with this error:

```
cannot unmarshal number into Go struct field
│ TagSettingsProperties.updateConfiguration.targets.azureQueries.tagSettings.filterOperator
```

Formatting the JSON in the error output, I can see that the "filterOperator" value is 0.

```
    {
                "azureQueries":[
                    {
                        "scope": [
                            "/subscriptions/dd8c83e8-5614-43a6-b49c-9d1673724aa4"
                        ],
                        "tagSettings":{
                            "tags":{
                                "updatemgmt":["Patch Group 2"]
                            },
                            "filterOperator":0
                        },
                        "locations":[]
                    }
                ],
                "nonAzureQueries":null
            },
```

I believe this should contain the value that I provided in the tag_filter attribute in the azure_query block.  I have this set to "Any" within my configuration but the value the Azure API is being sent appears to be 0.

### Steps to Reproduce

terraform apply

**Comment by wuxu92** [comment] 2022-10-24 07:22
Hi, @davelee212 thanks for your feedback. It looks like JSON's unmarshal result from the Service response raises this error which means the Server side does not honor the API definition. I wonder if this error happens only when updating the `tag_filter` property from `Any` to `All`? because I cannot reproduce it locally. and is this error happened randomly or persist?

**Comment by rcskosir** [comment] 2023-10-30 22:07
Thanks for taking the time to submit this issue. @wuxu92 was unable to reproduce this behavior. We’re going to close this issue for now, but if you run into this again with the latest Terraform and Provider versions, please feel free to [open a new issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/new/choose)

**Closed by rcskosir** 2023-10-30 22:07 UTC
Labels: waiting-response, service/automation, v/3.x
