### ISSUE TITLE
Modification of Azure Cache for Redis results in GatewayTimeout

### ISSUE THREAD

**Issue by laugmanuel** [hashicorp/terraform-provider-azurerm#8169] opened 2020-08-19 09:50 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

```
Terraform v0.13.0
+ provider registry.terraform.io/hashicorp/azurerm v2.23.0
```
The problem also occured with Terraform v0.12.28.

### Terraform Configuration Files

```hcl
[...]

resource "azurerm_resource_group" "redis" {
  name     = "redis"
  location = "germanywestcentral"
}

resource "azurerm_redis_cache" "redis" {
  name                = "redis-${local.resource-suffix}"
  location            = azurerm_resource_group.redis.location
  resource_group_name = azurerm_resource_group.redis.name
  capacity            = 1
  family              = "P"
  sku_name            = "Premium"
  enable_non_ssl_port = false
  minimum_tls_version = "1.2"
  subnet_id           = azurerm_subnet.redis-private.id
  shard_count         = 1
  redis_configuration {
    enable_authentication = true
  }

  patch_schedule {
    day_of_week    = "Saturday"
    start_hour_utc = "0"
  }
}
```

### Debug Output

```
azurerm_redis_cache.redis: Still modifying... [id=/subscriptions/11111111-2222-3333-4444-....Cache/Redis/redis-abcdefghij, 11m20s elapsed]
2020-08-19T12:02:30.349+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5: [DEBUG] AzureRM Response for https://management.azure.com/subscriptions/11111111-2222-3333-4444-555555555555/resourceGroups/redis/providers/Microsoft.Cache/Redis/redis-abcdefghij?api-version=2018-03-01:
2020-08-19T12:02:30.349+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5: HTTP/2.0 504 Gateway Timeout
2020-08-19T12:02:30.349+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5: Content-Length: 143
2020-08-19T12:02:30.349+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5: Cache-Control: no-cache
2020-08-19T12:02:30.349+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5: Content-Type: application/json; charset=utf-8
2020-08-19T12:02:30.349+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5: Date: Wed, 19 Aug 2020 10:02:29 GMT
2020-08-19T12:02:30.349+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5: Expires: -1
2020-08-19T12:02:30.349+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5: Pragma: no-cache
2020-08-19T12:02:30.349+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5: Strict-Transport-Security: max-age=31536000; includeSubDomains
2020-08-19T12:02:30.349+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5: X-Content-Type-Options: nosniff
2020-08-19T12:02:30.349+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5: X-Ms-Correlation-Request-Id: 28565455-2b76-96ca-bbcd-6b0689d5a6f8
2020-08-19T12:02:30.349+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5: X-Ms-Failure-Cause: service
2020-08-19T12:02:30.349+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5: X-Ms-Request-Id: b3cb7c64-5eb2-4517-997c-42cd1fcec8c0
2020-08-19T12:02:30.349+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5: X-Ms-Routing-Request-Id: GERMANYWESTCENTRAL:20200819T100230Z:b3cb7c64-5eb2-4517-997c-42cd1fcec8c0
2020-08-19T12:02:30.349+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5:
2020-08-19T12:02:30.349+0200 [DEBUG] plugin.terraform-provider-azurerm_v2.23.0_x5: {"error":{"code":"GatewayTimeout","message":"The gateway did not receive a response from 'Microsoft.Cache' within the specified time period."}}
azurerm_redis_cache.redis: Still modifying... [id=/subscriptions/11111111-2222-3333-4444-....Cache/Redis/redis-abcdefghij, 11m30s elapsed]
```

### Expected Behavior

The resource should be modified and Terraform should succeed it's apply run.

### Actual Behavior

The resource gets modified on Azure side, however Terraform throws a `GatewayTimeout` after about 11m30s:
```
azurerm_redis_cache.redis: Still modifying... [id=/subscriptions/11111111-2222-3333-4444-....Cache/Redis/redis-abcdefghij, 11m20s elapsed]
azurerm_redis_cache.redis: Still modifying... [id=/subscriptions/11111111-2222-3333-4444-....Cache/Redis/redis-abcdefghij, 11m30s elapsed]

Error: redis.Client#Update: Failure responding to request: StatusCode=504 -- Original Error: autorest/azure: Service returned an error. Status=504 Code="GatewayTimeout" Message="The gateway did not receive a response from 'Microsoft.Cache' within the specified time period."
```
The Azure portal shows the resource in state "Running" and the change is applied.

### Steps to Reproduce

1. `terraform apply` of above code
2. Change some parameters which result in the resource being modified:
```hcl
[...]
 redis_configuration {
    enable_authentication         = true
    rdb_backup_enabled            = true
    rdb_storage_connection_string = "whatever block storage string"
    rdb_backup_frequency          = 15
  }
[...]
```

### References

* #0000

**Comment by njuCZ** [comment] 2020-08-24 03:04
@laugmanuel May I know is this issue occured once or regularly? I just had a try following your step in my local (create and then update), everything is fine. For now, I could not diagnose whether it's network issue or backend service issue. Could you have a try once more?

**Comment by tombuildsstuff** [comment] 2020-08-24 04:45
@njuCZ we've got an API issue open for this: https://github.com/Azure/azure-rest-api-specs/issues/1499

**Comment by laugmanuel** [comment] 2020-08-24 06:01
@njuCZ for me this happens every time. But because the resource takes ages to create and also to hit the timeout on modification, it's quite tedious to test this.
But I'm here if you need me to test some specific things.

**Comment by tombuildsstuff** [comment] 2020-08-24 06:16
@laugmanuel to give a fuller explanation into this issue: Terraform's sending a HTTP Request to Azure's API, which is then forwarding that onto the internal API which handles Redis - what's happening is the Azure API isn't getting a response back from the Redis API here, so the Azure API returns a "504 Gateway Timeout" (which is what's tracked in Azure/azure-rest-api-specs#1499).

Since the Azure API team appear to need detailed (non-user facing) logs from their side to investigate this, I'd suggest the best path forward would be to open a Azure Support ticket, referencing the specific Resources/Subscription being deployed so they can identify these - referencing both this issue and Azure/azure-rest-api-specs#1499.

In the case of Azure/azure-rest-api-specs#1499, the Redis API isn't able to find a newly-created Storage Account via DNS (although the Storage API returns it's available, and we're able to look it up several times), unfortunately this isn't something we can fix from Terraform and needs to be fixed in the API (to poll as appropriate). I can't confirm if this is the same underlying root cause - but the Azure API team should be able to confirm this is the case & fix this based on these logs.

Thanks!

**Comment by laugmanuel** [comment] 2020-08-24 06:26
@tombuildsstuff thank's for the answer. I'll get in contact with Azure support and see what the response will look like

**Comment by wasfree** [comment] 2021-06-22 15:48
@laugmanuel I'm curious what was the outcome with Azure Support. Could you please share this information with us?

**Comment by laugmanuel** [comment] 2021-06-23 06:20
@wasfree to be completely honest, I stopped using this resource. If I recall correctly, the support did not provide any useful information. However, I would encourage you to open a ticket yourself.

**Comment by bgarcial** [comment] 2021-06-25 10:57
I have been discussing this with Microsoft service about this issue, even pointing out this and other Github issues links. They required from me the logs I am getting. Basically I was getting as a first message that one related to the `StatusCode=504`:

```
Error: waiting for the create of Redis Cache "rhd-spec-ttst-redis-zfgpda1p1jkt7" (Resource Group "rhd-spec-ttst-main-rx0k0ku02ajg0"): Future#WaitForCompletion: the number of retries has been exceeded: StatusCode=504 -- Original Error: Code="GatewayTimeout" Message="The gateway did not receive a response from 'Microsoft.Cache' within the specified time period."
607TestSpeckle 2021-06-23T11:00:28Z logger.go:66:
608TestSpeckle 2021-06-23T11:00:28Z logger.go:66:   on redis-cache.tf line 14, in resource "azurerm_redis_cache" "main_redis":
609TestSpeckle 2021-06-23T11:00:28Z logger.go:66:   14: resource "azurerm_redis_cache" "main_redis" ***
610TestSpeckle 2021-06-23T11:00:28Z logger.go:66:
611TestSpeckle 2021-06-23T11:00:28Z logger.go:66:
612TestSpeckle 2021-06-23T11:00:28Z retry.go:99: Returning due to fatal error: FatalError***Underlying: error while running command: exit status 1;
613Error: waiting for the create of Redis Cache "rhd-spec-ttst-redis-zfgpda1p1jkt7" (Resource Group "rhd-spec-ttst-main-rx0k0ku02ajg0"): Future#WaitForCompletion: the number of retries has been exceeded: StatusCode=504 -- Original Error: Code="GatewayTimeout" Message="The gateway did not receive a response from 'Microsoft.Cache' within the specified time period."
614
```

Then I tried to set a time out from my terraform azure Redis cache configuration [such as the documentation says](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/redis_cache#timeouts) and then I got a slightly different error:

```
TestSpeckle 2021-06-25T09:48:08Z logger.go:66: Error: waiting for the create of Redis Cache "rhd-spec-ttst-redis-69vo25yvkbzl5" (Resource Group "rhd-spec-ttst-main-ws5p5ygvqi6bo"): Future#WaitForCompletion: the number of retries has been exceeded: StatusCode=200
925TestSpeckle 2021-06-25T09:48:08Z logger.go:66:
926TestSpeckle 2021-06-25T09:48:08Z logger.go:66:   on redis-cache.tf line 14, in resource "azurerm_redis_cache" "main_redis":
927TestSpeckle 2021-06-25T09:48:08Z logger.go:66:   14: resource "azurerm_redis_cache" "main_redis" ***
928TestSpeckle 2021-06-25T09:48:08Z logger.go:66:
929TestSpeckle 2021-06-25T09:48:08Z logger.go:66:
930TestSpeckle 2021-06-25T09:48:08Z retry.go:99: Returning due to fatal error: FatalError***Underlying: error while running command: exit status 1;
931Error: waiting for the create of Redis Cache "rhd-spec-ttst-redis-69vo25yvkbzl5" (Resource Group "rhd-spec-ttst-main-ws5p5ygvqi6bo"): Future#WaitForCompletion: the number of retries has been exceeded: StatusCode=200
932
933  on redis-cache.tf line 14, in resource "azurerm_redis_cache" "main_redis":
934  14: resource "azurerm_redis_cache" "main_redis" ***
935
```

But both errors above are related to the fact terraform is not getting an answer from Azure Redis API because the internal API that handles Redis on azure is not giving back an answer to Azure API and subsequently to terraform in our pipeline.

Microsoft support is checking those logs and looking for some sort of solution to this right now.

**Comment by markti** [comment] 2021-07-06 01:28
@bgarcial any word from MSFT? We are planning on adding redis to one of our projects and have been hamstrung with this 504 issue!

**Comment by bgarcial** [comment] 2021-07-06 08:28
Hi @markti 
It seems they manage to fix it (at least in the West Europe region) but what they did was a manual fix. They reboot manually the resource provider (I ignore what it mean for us - anyway - ) and now that `StatusCode=504 -- Original Error: Code="GatewayTimeout" Message="The gateway did not receive a response from 'Microsoft.Cache' within the specified time period."` they said it was mitigated.

Due to such as @laugmanuel point out above, in a first attempt Microsoft support was not providing useful insights and info about what they could do with this situation, I also had to insist by telling them it is something to be analyzed from the Microsoft side and not terraform side. 
After I managed to show them my logs and the information provider from all of you here and in other related issues, they started to proceed with further investigation, and they found that many clients reported this error after an outage in the West Europe region.

It was the final message I got:

>Thank you for the confirmation.
Our Product Group team is currently working to deploy a permanent fix on this.
Please let me know if you have any further questions about this service request.
Apologies for the inconvenience caused. 

Accordingly, I managed to create the Redis instance from my pipeline:

![image](https://user-images.githubusercontent.com/1211088/124567230-1a944880-de44-11eb-8f07-ab440e50ab88.png)


But this is a kind of ephemeral error since it has been appearing from time to time or frequently all this time along I was in touch with them. I would suggest raising a ticket on the Azure portal about this and provide things like logs information, timestamps, and the context. They should be able to solve this issue for others subscriptions/tenants/regions as well.

**Comment by wasfree** [comment] 2021-07-06 15:04
Hi @bgarcial , @markti 

here is the final RCA, we don't see any issues in west europe region since end of last week.

> We have narrowed down the root cause to code defects on the Resource Provider infrastructure which led to a spike in CPU and hence throttled incoming requests. We have a mitigation path when this issue occurs, and we have been proactively mitigating this as they occur. Right now, we are in the process of deploying a permanent fix. Rest assured; this only affects a small percentage of management operations for West Europe region. Caches are expected to function without any issues.”

**Comment by favoretti** [comment] 2021-08-20 12:15
Hi there. Since there's really little we can do from the provider side about this - can this issue be closed? Thanks!

**Comment by favoretti** [comment] 2021-08-25 09:45
Thanks for opening this issue! Since this issue has been reported a long time ago and relates to an older version of provider - I'm going to close it. If this is still relevant and occurring on the latest version of terraform and provider please do open a new issue!

**Closed by favoretti** 2021-08-25 09:45 UTC
Labels: upstream-microsoft, service/redis
