### ISSUE TITLE
azurerm_storage_account v3.96.0 plugin did not respond

### ISSUE THREAD

**Issue by murphanoodle** [hashicorp/terraform-provider-azurerm#25341] opened 2024-03-20 21:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.5

### AzureRM Provider Version

3.96.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "stor" {
  name                             = var.stor_account_name
  resource_group_name              = var.stor_resource_group_name
  location                         = var.stor_region
  account_tier                     = var.stor_tier
  account_kind                     = var.stor_account_kind
  account_replication_type         = var.stor_repl_type
  is_hns_enabled                   = var.stor_hns_enabled
  cross_tenant_replication_enabled = var.stor_cross_tenant_replication_enabled
  access_tier                      = var.stor_access_tier
  enable_https_traffic_only        = var.stor_enable_https_traffic_only
  min_tls_version                  = var.stor_min_tls_version
  shared_access_key_enabled        = var.stor_shared_access_key_enabled # setting this value to false will disallow azure files
  public_network_access_enabled    = var.stor_public_network_access_enabled
  allow_nested_items_to_be_public  = var.stor_allow_nested_items_to_be_public
  default_to_oauth_authentication  = var.stor_default_to_oauth_authentication
  nfsv3_enabled                    = var.stor_nfsv3_enabled
  allowed_copy_scope               = var.stor_allowed_copy_scope
  identity {
    type = var.stor_identity_type
  }
  network_rules {
    default_action             = var.stor_network_rules_default_action
    bypass                     = var.stor_network_rules_bypass
    virtual_network_subnet_ids = var.stor_network_rules_virtual_network_subnet_ids
    ip_rules                   = var.stor_network_rules_ip_rules
    dynamic "private_link_access" {
      for_each = var.stor_network_rules_private_link_access_endpoint_resource_id != null ? [0] : []
      content {
        endpoint_resource_id = var.stor_network_rules_private_link_access_endpoint_resource_id
        endpoint_tenant_id   = data.azurerm_client_config.current.tenant_id
      }
    }
  }
  blob_properties {
    delete_retention_policy {
      days = var.stor_blob_properties_delete_retention_policy
    }
    container_delete_retention_policy {
      days = var.stor_blob_properties_delete_retention_policy
    }
  }

  dynamic "azure_files_authentication" {
    for_each = var.include_ad_authentication ? [1] : []
    content {
      directory_type = var.stor_azure_files_directory_type
      active_directory {
        domain_name         = var.stor_azure_files_domain_name
        domain_guid         = var.stor_azure_files_domain_guid
        domain_sid          = var.stor_azure_files_domain_sid
        storage_sid         = var.stor_azure_files_storage_sid
        forest_name         = var.stor_azure_files_forest_name
        netbios_domain_name = var.stor_azure_files_netbios_domain_name
      }
    }
  }


  lifecycle {
    ignore_changes = [tags]
  }
}
```

### Debug Output/Panic Output

```shell
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Plugin did not respond
│
│   with module.stor.azurerm_storage_account.stor,
│   on ..\..\bhs_storage_account.tf line 23, in resource "azurerm_storage_account" "stor":
│   23: resource "azurerm_storage_account" "stor" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-azurerm_v3.96.0_x5.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x38 pc=0xb1f8cf]

goroutine 233 [running]:
github.com/hashicorp/go-azure-sdk/sdk/client.(*Response).Unmarshal(0xc002e8c510, {0x72ba7a0, 0xc0021a0940?})
        github.com/hashicorp/go-azure-sdk/sdk@v0.20240314.1083835/client/client.go:171 +0x4f
github.com/tombuildsstuff/giovanni/storage/2023-11-03/blob/accounts.Client.GetServiceProperties({0xc002093e40?}, {0x8f8fb68, 0xc001cab180}, {0xc0027126c7?, 0x14})
        github.com/tombuildsstuff/giovanni@v0.25.1/storage/2023-11-03/blob/accounts/get_service_properties.go:42 +0x235
github.com/hashicorp/terraform-provider-azurerm/internal/services/storage.resourceStorageAccountRead(0xc001fde800, {0x7762900?, 0xc001a48900})
        github.com/hashicorp/terraform-provider-azurerm/internal/services/storage/storage_account_resource.go:2333 +0x2c2f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x8f8fac0?, {0x8f8fac0?, 0xc002c18fc0?}, 0xd?, {0x7762900?, 0xc001a48900?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:783 +0x163
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc001a05880, {0x8f8fac0, 0xc002c18fc0}, 0xc0010a65b0, {0x7762900, 0xc001a48900})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:1089 +0x552
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc000a131b8, {0x8f8fac0?, 0xc002c18ed0?}, 0xc00209c780)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/grpc_provider.go:649 +0x48a
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc001a990e0, {0x8f8fac0?, 0xc002c18720?}, 0xc00273be60)
        github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/tf5server/server.go:789 +0x48b
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x836ed60?, 0xc001a990e0}, {0x8f8fac0, 0xc002c18720}, 0xc001caab60, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:431 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002e81e0, {0x8fb72c0, 0xc001cda000}, 0xc002c166c0, 0xc001b802d0, 0xe8e0d08, 0x0)
        google.golang.org/grpc@v1.58.3/server.go:1374 +0xde7
google.golang.org/grpc.(*Server).handleStream(0xc0002e81e0, {0x8fb72c0, 0xc001cda000}, 0xc002c166c0, 0x0)
        google.golang.org/grpc@v1.58.3/server.go:1751 +0x9e7
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.58.3/server.go:986 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 100
        google.golang.org/grpc@v1.58.3/server.go:997 +0x145

Error: The terraform-provider-azurerm_v3.96.0_x5.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by tombuildsstuff** [comment] 2024-03-21 07:26
hey @murphanoodle 

Thanks for opening this issue.

Taking a look through here this appears to be a duplicate of #25314 which'll be fixed by https://github.com/hashicorp/terraform-provider-azurerm/pull/25332 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of #25314, would you mind subscribing to that issue for updates?

Thanks!

**Closed by tombuildsstuff** 2024-03-21 07:26 UTC
Labels: bug, crash, service/storage, v/3.x

**Comment by Joseluismantilla** [comment] 2024-03-27 15:40
Guys, I', using the 3.97.1 version and I'm getting...
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/2237623/9d507968-a68b-4a00-b178-8d01c22d73e7)

My Storage account has private endpoints for blob, file, queue, and table. This error started appearing after creating all of them with static IPs, any ideas?
