### ISSUE TITLE
azurerm_storage_share fails to trigger Activity Log Operation Name : Put File Share ("action": "Microsoft.Storage/storageAccounts/fileServices/shares/write")

### ISSUE THREAD

**Issue by sayandaw** [hashicorp/terraform-provider-azurerm#15963] opened 2022-03-23 09:17 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_storage_share`

### Terraform Configuration Files

```hcl
# Get the details of the current logged in client config.
data "azurerm_client_config" "current" {}
 
# Get the details of the Azure Key Vault to use for the CMK. 
data "azurerm_key_vault" "encryption_vault" {
  name                = var.key_vault_name
  resource_group_name = var.key_vault_resource_group
}
 
# Get the details of the encryption key to use as the CMK. 
data "azurerm_key_vault_key" "storage_cmk" {
  name         = var.encryption_key_name
  key_vault_id = data.azurerm_key_vault.encryption_vault.id
}
 
# Get the details of the Subnet to use for the Private Endpoint.
data "azurerm_subnet" "subnet" {
  name                 = var.subnet_name
  virtual_network_name = var.vnet_name
  resource_group_name  = var.vnet_rg_name
}
 
# Create/Update the Azure Storage Account. 
resource "azurerm_storage_account" "storage_account" {
  name                = var.storage_account_name
  resource_group_name = var.resource_group_name
 
  location                 = var.location
  account_kind             = var.account_kind
  account_tier             = var.account_tier
  account_replication_type = var.account_replication_type
 
  enable_https_traffic_only = true
  min_tls_version           = "TLS1_2"
  allow_blob_public_access  = false
  is_hns_enabled            = var.enable_hns
 
  identity {
    type = "SystemAssigned"
  }
 
  network_rules {
    default_action             = "Deny"
    bypass                     = ["AzureServices"]
    virtual_network_subnet_ids = [data.azurerm_subnet.subnet.id]
  }
 
  lifecycle {
    ignore_changes = [
      tags,
    ]
  }
}
 
# Create/Update the Private Endpoint for the Storage Account based on provided subresources. 
resource "azurerm_private_endpoint" "private_endpoint" {
  for_each = toset(var.private_endpoint_subresources)
 
  name                = join("-", [var.storage_account_name, "pvtendpt", each.value])
  location            = var.location
  resource_group_name = var.resource_group_name
  subnet_id           = data.azurerm_subnet.subnet.id
 
  private_service_connection {
    name                           = join("-", [var.storage_account_name, "pvtsvcconn", each.value])
    is_manual_connection           = false
    private_connection_resource_id = azurerm_storage_account.storage_account.id
    subresource_names              = tolist([each.value])
  }
 
  lifecycle {
    ignore_changes = [
      tags,
    ]
  }
}
 
resource "null_resource" "wait_5_minutes" {
  provisioner "local-exec" {
  command = "sleep 300"
  }
  # triggers = {
  #  "before" = "${azurerm_private_endpoint.private_endpoint}"
  # }
  depends_on = [azurerm_private_endpoint.private_endpoint]
}
 
resource "azurerm_storage_share" "fileshare" {
  count                = length(var.file_shares)
  name                 = var.file_shares[count.index].name
  storage_account_name = azurerm_storage_account.storage_account.name
  quota                = var.file_shares[count.index].quota
  depends_on = [null_resource.wait_5_minutes]
}
 
# Create/Update the Key Vault Access Policy - required for the Storage Account to get the CMK. 
resource "azurerm_key_vault_access_policy" "storage_keyvault_accesspolicy" {
  key_vault_id = data.azurerm_key_vault.encryption_vault.id
  tenant_id    = data.azurerm_client_config.current.tenant_id
  object_id    = azurerm_storage_account.storage_account.identity.0.principal_id
 
  key_permissions = ["get", "list", "unwrapkey", "wrapkey"]
}
 
# Create/Update the CMK encryption setting on the Storage Account. 
resource "azurerm_storage_account_customer_managed_key" "storage_account_cmk" {
  storage_account_id = azurerm_storage_account.storage_account.id
  key_vault_id       = data.azurerm_key_vault.encryption_vault.id
  key_name           = data.azurerm_key_vault_key.storage_cmk.name
 
  depends_on = [
    azurerm_key_vault_access_policy.storage_keyvault_accesspolicy
  ]
}
```

### Debug Output

https://gist.github.com/sayandaw/6d4865bb158a48bef8a1d4f1835d673a

### Expected Behaviour

When the File Share was created by "azurerm_storage_share" expected to see in the Activity Log  
Operation Name : Put File Share ("action": "Microsoft.Storage/storageAccounts/fileServices/shares/write")

### Actual Behaviour

There is no Activity Log (Operation Name : Put File Share ("action": "Microsoft.Storage/storageAccounts/fileServices/shares/write")) when the share is created.  
However when you create a share using the portal it works  
### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment] 2022-03-23 09:21
hi @sayandaw 

Thanks for opening this issue.

Taking a look through this appears to be a duplicate of #10765 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #10765 for updates?

Thanks!

**Closed by tombuildsstuff** 2022-03-23 09:21 UTC
Labels: duplicate, enhancement, service/storage, upstream-microsoft
