### ISSUE TITLE
azurerm_data_protection_backup_vault cannot be deleted

### ISSUE THREAD

**Issue by rdvansloten** [hashicorp/terraform-provider-azurerm#25142] opened 2024-03-04 22:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.55

### AzureRM Provider Version

3.94.0

### Affected Resource(s)/Data Source(s)

azurerm_data_protection_backup_vault

### Terraform Configuration Files

```hcl
resource "azurerm_data_protection_backup_vault" "example" {
  name                = "example-backup-vault"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  datastore_type      = "VaultStore"
  redundancy          = "LocallyRedundant"
  soft_delete         = "Off"
}
```

### Debug Output/Panic Output

```shell
Cannot delete the Backup vault as there are existing backup instances or backup policies in the vault.
```

### Expected Behaviour

The Vault should have been deleted, I have strictly stated that I do not want Soft Deletes (which it did not take)

I expect to be able to e2e test my module for backups, but this resource makes deleting through Terraform actually impossible.

### Actual Behaviour

The Vault did not want to delete until I manually deleted all items (which were not Soft Delete-protected FYI)

**Comment by sinbai** [comment] 2024-03-05 06:11
Hi @rdvansloten thanks for opening this issue. Per the provided information, I assume that after the `azurerm_data_protection_backup_vault` is created via Terraform, it is applied to the backup instance (e.g. corresponding to the Terraform resources `azurerm_data_protection_backup_instance_postgresql`/`azurerm_data_protection_backup_instance_disk`...) or to the backup policy (e.g. corresponding to the Terraform resources `azurerm_data_protection_backup_policy_postgresql`/`azurerm_data_protection_backup_policy_disk`...) , right?

If so, and they are all managed via TF, could you please provide minimally complete Terraform configuration and reproduction steps to help with reproduction/troubleshooting? If not, then the above symptoms are by design. You could use the terraform import command to import backup instances or backup policies to achieve unified CRUD management.

**Comment by rcskosir** [comment] 2024-06-04 16:17
Thank you for taking the time to raise this! I am going to close this with @sinbai‘s response as an answer. If that is not the case, please provide additional information including the version in which you are still experiencing this issue, thanks!

**Closed by rcskosir** 2024-06-04 16:17 UTC
Labels: waiting-response, service/data-protection, v/3.x
