### ISSUE TITLE
`azurerm_kubernetes_cluster`, error if deprecated property `managed` is omit

### ISSUE THREAD

**Issue by jkroepke** [hashicorp/terraform-provider-azurerm#25795] opened 2024-04-29 15:02 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.0

### AzureRM Provider Version

3.101.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "this" {
  azure_active_directory_role_based_access_control {
    // managed            = true
    azure_rbac_enabled = true
    tenant_id          = var.aks_rbac_tenant_id

    admin_group_object_ids = var.aks_admin_group_object_ids
  }

}
```

### Debug Output/Panic Output

```shell
module.opsstack.azurerm_kubernetes_cluster.this: Modifying... [id=/subscriptions/***/resourceGroups/rg-opsstack-westeurope-001/providers/Microsoft.ContainerService/managedClusters/aks-opsstack-westeurope-001]
╷
│ Error: can't specify admin_group_object_ids when using managed aad rbac (managed = false)
│ 
│   with module.opsstack.azurerm_kubernetes_cluster.this,
│   on ../../terraform/modules/azure_opsstack/aks.tf line 1, in resource "azurerm_kubernetes_cluster" "this":
│    1: resource "azurerm_kubernetes_cluster" "this" {
│ 
╵
Releasing state lock. This may take a few moments...
```

### Expected Behaviour

it works

### Actual Behaviour

apply fail

**Comment by stephybun** [comment] 2024-04-30 07:50
Thanks for raising this issue @jkroepke.

Please read the explanation over in #25707 for information. Closing since this is a duplicate of #25707

**Closed by stephybun** 2024-04-30 07:50 UTC
Labels: v/3.x
