### ISSUE TITLE
Support for Automation account Settings in azurerm_site_recovery_replicated_vm

### ISSUE THREAD

**Issue by mpjtaylor** [hashicorp/terraform-provider-azurerm#19691] opened 2022-12-15 08:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add the ability for the agent extension to be managed by an atomation account

### New or Affected Resource(s)/Data Source(s)

azurerm_site_recovery_replicated_vm

### Potential Terraform Configuration

```hcl
resource "azurerm_site_recovery_replicated_vm" "protected_vm_tf" {
automation_account_id = var.automation_account_id
}
```

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/19535

**Comment by mybayern1974** [comment] 2022-12-16 06:01
Thanks @mpjtaylor for opening this issue. Taking a look through this appears to be a duplicate of #19407. Rather than having multiple issues open tracking the same thing I'm going to close this issue in favor of that one; would you mind subscribing to #19407 for updates? Or feel free to reopen if you believe these two issues are not talking about the same thing.

Thanks!

**Closed** 2023-01-30 19:57 UTC
Labels: duplicate
