### ISSUE TITLE
Error: Provider produced inconsistent final plan in azurerm_template_deployment/azurerm_virtual_desktop_host_pool 

### ISSUE THREAD

**Issue by oyb1n** [hashicorp/terraform-provider-azurerm#11086] opened 2021-03-23 13:19 UTC
### Terraform (and AzureRM Provider) Version
Terraform v0.14.8.
provider.azurerm v2.52.0

### Affected Resource(s)
azurerm_virtual_desktop_host_pool
azurerm_template_deployment

### Terraform Configuration Files

```
resource "azurerm_virtual_desktop_host_pool" "wvd" {
  for_each                          = var.services
  name                              = "dev-${each.value.name}-${each.value.service}-hp"
  location                          = azurerm_resource_group.wvd[each.value.name].location
  resource_group_name               = azurerm_resource_group.wvd[each.value.name].name
  type                              = "Personal"
  personal_desktop_assignment_type  = "Direct"
  preferred_app_group_type          = "Desktop"
  load_balancer_type                = "Persistent"
  provider                          = azurerm.ai-dev
  registration_info {
    expiration_date = timeadd(timestamp(), "720h")
  }

   tags = {
    Costcenter  = "Ai-Dev"
    Service = each.value.service
    Vendor = each.value.name
  }
}

resource "azurerm_template_deployment" "Formulas" {
  name                = "dev-sop-tje-formula"
  provider            = azurerm.ai-dev
  resource_group_name = azurerm_resource_group.wvd["sop"].name
  template_body       = file("ARM/Formula.json")
  deployment_mode = "Incremental"
  depends_on = [
    azurerm_resource_group.wvd,
    azurerm_virtual_desktop_host_pool.wvd
  ]

  parameters = {
    "vendor"          = "sop"
    "service"         = "tje"
    "HostPoolRegistrationkey" = azurerm_virtual_desktop_host_pool.wvd["sop-tje"].registration_info[0].token
  }
}
```

### Debug Output

Error: Provider produced inconsistent final plan

When expanding the plan for azurerm_template_deployment.Formulas to include
new values learned so far during apply, provider
"registry.terraform.io/hashicorp/azurerm" produced an invalid new value for
.parameters["HostPoolRegistrationkey"]: was
cty.StringVal("xxxxx-WiePi94U9Hhw"),
but now
cty.StringVal("xxxxx-UMcacMyvQ").

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

### Steps to reproduce
`Terraform Apply`

**Comment by oyb1n** [comment] 2021-03-24 12:24
Tried updating the formula resource to loop in the same manner as the wvd resource with no luck: 
`resource "azurerm_template_deployment" "Formulas" {
  for_each            = var.services
  name                = "tdev-${each.value.name}-${each.value.service}-formula"
  provider            = azurerm.ai-dev
  resource_group_name = azurerm_resource_group.wvd[each.value.name].name
  template_body       = file("../ARM/Add_Formula.json")
  deployment_mode = "Incremental"
  depends_on = [
    azurerm_resource_group.wvd,
    azurerm_virtual_desktop_host_pool.wvd
  ]

  parameters = {
    "vendor"          = each.value.name
    "service"         = each.value.service
    "HostPoolRegistrationkey" = azurerm_virtual_desktop_host_pool.wvd[each.key].registration_info[0].token
  }
}`

**Comment by tombuildsstuff** [comment] 2021-11-15 13:55
hi @Dirgo22 

Thanks for opening this issue.

Taking a look through this appears to be a duplicate of #13793 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #13793 for updates?

Thanks!

**Closed by tombuildsstuff** 2021-11-15 13:55 UTC
Labels: bug, service/template
