### ISSUE TITLE
azurerm_monitor_activity_log_alert.criteria.status doesn't support multiple selection

### ISSUE THREAD

**Issue by atdheekurteshi** [hashicorp/terraform-provider-azurerm#23903] opened 2023-11-15 09:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.3

### AzureRM Provider Version

3.80

### Affected Resource(s)/Data Source(s)

azurerm_monitor_activity_log_alert

### Terraform Configuration Files

```hcl
resource "azurerm_monitor_activity_log_alert" "Create_or_Update_Application_Gateway" {
  enabled             = true
  name                = "PROD Azure Resources - Create or Update Application Gateway"
  resource_group_name = azurerm_resource_group.rg-common-prod.name
  scopes              = [
      "/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxx",
  ]

  action {
    action_group_id    = azurerm_monitor_action_group.INFRA-EMAIL-ALERT.id
    webhook_properties = {}
  }

  criteria {
    category       = "Administrative"
    operation_name = "Microsoft.Network/applicationGateways/write"
    statuses         = ["Failed, Succeeded"]
  }
}
```

### Debug Output/Panic Output

```shell
StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="UnsupportedCondition" scope must have at least one additional filtering condition.
```

### Expected Behaviour

-

### Actual Behaviour

StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="UnsupportedCondition" scope must have at least one additional filtering condition.

### Steps to Reproduce

resource "azurerm_monitor_activity_log_alert" "Create_or_Update_Application_Gateway" {
  enabled             = true
  name                = "PROD Azure Resources - Create or Update Application Gateway"
  resource_group_name = azurerm_resource_group.rg-common-prod.name
  scopes              = [
      "/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxx",
  ]

  action {
    action_group_id    = azurerm_monitor_action_group.INFRA-EMAIL-ALERT.id
    webhook_properties = {}
  }

  criteria {
    category       = "Administrative"
    operation_name = "Microsoft.Network/applicationGateways/write"
    statuses         = ["Failed, Succeeded"]
  }
}

### Important Factoids

-

### References

-

**Comment by teowa** [comment] 2023-11-16 04:21
Hi @atdheekurteshi , I tried to reproduce the given error but seems I cannot with below config, my apply will finish without error. Can you please modify and reproduce the issue with below config?  From error message I guess it might ask for more filters, can you also try adding a `resource_type = "Microsoft.Network/applicationGateways"` filter which might fix the error.

Thanks.

<details>

<summary> tf config </summary>

```hcl
provider "azurerm" {
  features {}
}
resource "azurerm_resource_group" "rg" {
  name     = "test-rg"
  location = "westus"
}
data "azurerm_subscription" "current" {
}
resource "azurerm_monitor_action_group" "example" {
  name                = "CriticalAlertsAction"
  resource_group_name = azurerm_resource_group.rg.name
  short_name          = "p0action"
}
resource "azurerm_monitor_activity_log_alert" "Create_or_Update_Application_Gateway" {
  enabled             = true
  name                = "PROD Azure Resources - Create or Update Application Gateway"
  resource_group_name = azurerm_resource_group.rg.name
  scopes = [
    data.azurerm_subscription.current.id
  ]

  action {
    action_group_id    = azurerm_monitor_action_group.example.id
    webhook_properties = {}
  }

  criteria {
    category       = "Administrative"
    operation_name = "Microsoft.Network/applicationGateways/write"
    statuses       = ["Failed, Succeeded"]
  }
}
```
</details>

**Comment by rcskosir** [comment] 2024-01-23 20:47
Thanks for taking the time to submit this issue. @teowa was unable to reproduce this behavior. We’re going to close this issue for now, but if you run into this again with the latest Terraform and Provider versions and @teowa's suggestions don't help, please feel free to [open a new issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/new/choose).

**Closed by rcskosir** 2024-01-23 20:47 UTC
Labels: waiting-response, service/monitor, v/3.x
