### ISSUE TITLE
azurerm_resource_group and multiple subscriptions couldn't find the needed resouce group

### ISSUE THREAD

**Issue by teksaport** [hashicorp/terraform-provider-azurerm#16716] opened 2022-05-09 22:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.9 and lower

### AzureRM Provider Version

2.30

### Affected Resource(s)/Data Source(s)

azurerm_resource_group

### Terraform Configuration Files

```hcl
data "azurerm_resource_group" "existing_rg" {
    name = "default"
}
```

### Debug Output/Panic Output

```shell
[client]# terraform plan

 Error: Error: Resource Group "default" was not found

   with data.azurerm_resource_group.existing_rg,
   on main.tf line 8, in data "azurerm_resource_group" "existing_rg":
    8: data "azurerm_resource_group" "existing_rg" {
```

### Expected Behaviour

I would expect it to either search the subscriptions that I have access to, or allow me to enter the subscription id that this resource group is in.  Instead it just complains that it cannot find the RG.

After a lot of confusion, I realized that I have access to several subscriptions in my org.  I had to tell the azure login to set the subscription with this resource group as the default and then the TF worked as I needed it to.

az account subscription list
az account set --subscription "sub1"

Is there a way to specify the exact subscription to find the RG in?  Currently there isn't a field to specify which subscription to find this RG in and so it was only reading the "isDefault" subscription.
"isDefault": true,

### Actual Behaviour

[client]# terraform plan

 Error: Error: Resource Group "default" was not found

   with data.azurerm_resource_group.existing_rg,
   on main.tf line 8, in data "azurerm_resource_group" "existing_rg":
    8: data "azurerm_resource_group" "existing_rg" {

### Steps to Reproduce

You need more than 1 subscription with the same login credentials, then set the default "az login" subscription as the default that does not have this resource group and login via the command line.

**Comment by mybayern1974** [comment] 2022-05-10 08:21
@teksaport , thank you for openning this issue. Re the Expected Behavior "_or allow me to enter the subscription id that this resource group is in_", this is supported and indeed is a prerequisite of having Terraform AzureRM provider interact with Azure backend. There are multiple authentication options for Terraform AzureRM provider and all of them contains information on how to specify a subscription id at the beginning (for example [Use Az CLI ](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/azure_cli#logging-into-the-azure-cli)and [Use Azure Service Principle](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_secret#configuring-the-service-principal-in-terraform))

If the above understanding maps this issue, I may suggest you post this issue to one of the [Community Resources](https://www.terraform.io/community.html) because this forum is intended to be more for feature enhancements and bug reports in the Azure Provider than practices of provider usage, so hope you could get further help from there if the above suggestion does not help.

**Comment by teksaport** [comment] 2022-05-10 17:06
@mybayern1974 thank you for the reply.  If I use your suggestion, how would I change the subscription when running in a pipeline?  For instance if I wanted to use a resource group from subscription1 and then wanted to use one from subscription2 in the same pipeline, how would I specify the subscription each resource group was in? 



> @teksaport , thank you for openning this issue. Re the Expected Behavior "_or allow me to enter the subscription id that this resource group is in_", this is supported and indeed is a prerequisite of having Terraform AzureRM provider interact with Azure backend. There are multiple authentication options for Terraform AzureRM provider and all of them contains information on how to specify a subscription id at the beginning (for example [Use Az CLI ](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/azure_cli#logging-into-the-azure-cli)and [Use Azure Service Principle](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_secret#configuring-the-service-principal-in-terraform))
> 
> If the above understanding maps this issue, I may suggest you post this issue to one of the [Community Resources](https://www.terraform.io/community.html) because this forum is intended to be more for feature enhancements and bug reports in the Azure Provider than practices of provider usage, so hope you could get further help from there if the above suggestion does not help.

**Comment by magodo** [comment] 2022-05-11 05:36
@teksaport You can use multiple provider aliases, each with the expected subscription id set. Note that each provider is designed to work for a single subscription by design.

A example config is as below:

```hcl
provider "azurerm" {
  subscription_id = "<sub id 1>"
  features {}
  alias = "sub1"
}
provider "azurerm" {
  subscription_id = "<sub id 2>"
  features {}
  alias = "sub2"
}

data "azurerm_resource_group" "test1" {
  provider = azurerm.sub1
  name     = "foo"
}
data "azurerm_resource_group" "test2" {
  provider = azurerm.sub2
  name     = "bar"
}
```

For more info about provider alias, checkout: https://www.terraform.io/language/providers/configuration.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community.html), I'm goona to close this issue. Please feel free to open issues for other problems.

**Closed by magodo** 2022-05-11 05:36 UTC
Labels: question

**Comment by teksaport** [comment] 2022-05-11 14:11
@magodo that is what I am missing and was hoping to find.  Thank you so much, I haven't used multiple of the same provider.  I think that will do what I want and will try it out.  Thank you!
