### ISSUE TITLE
Wrong error message returned at plan time when creating a storage account with resource provider 'Microsoft.Storage' in NotRegistered state

### ISSUE THREAD

**Issue by LaurentLesle** [hashicorp/terraform-provider-azurerm#24104] opened 2023-12-04 10:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

Currently if you try to deploy a storage account in a subscription that has the resource provider 'Microsoft.Storage' set to NotRegistered, the deployment will fail with a false error message while trying to verify the name of the storage account at planned time.

This error message is wrong saying the SubscriptionNotFound while the root cause is azurerm_storage_account calling checkNameAvailability while the resource provider is in NotRegistered state.

One possible option to address that issue is to add a parameter to skip the name verification in that scenario. If the name already exists it will fail at apply time.

### Terraform Version

1.6.3

### AzureRM Provider Version

3.83

### Affected Resource(s)/Data Source(s)

azurerm_storage_accounts

### Terraform Configuration Files

```hcl
provider "azurerm" {
  skip_provider_registration = true
  features {}

}

resource "azurerm_resource_provider_registration" "microsoft.storage" {
  name = "Microsoft.Storage"
}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_storage_account" "example" {
  name                     = "stg3324jkjndek434" # make sure you put a name that does not exist
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "GRS"

  tags = {
    environment = "staging"
  }

  depends_on = [
   azurerm_resource_provider_registration["microsoft.storage"]
  ]
}
```

### Debug Output/Panic Output

```shell
│ Error: 1 error occurred:
│       * storage.AccountsClient#CheckNameAvailability: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="SubscriptionNotFound" Message="Subscription xxxxxx-xxxx-xxx-xxxx-xxxxxx was not found."
│ 
│ 
│ 
│   with module.azurerm_storage_accounts["nsg_flow_logs"].azurerm_storage_account.this,
│   on ../../azurerm/terraform-azurerm-storage-account/storage_account.tf line 1, in resource "azurerm_storage_account" "this":
│    1: resource "azurerm_storage_account" "this" {
│ 
```
```


### Expected Behaviour

- this scenario should work and allow to register the provider and create a storage account within the same operation.
- Add an attribute on the storage account to skip the verification name as the provider will be registered part of the deployment activity, allowing the registration and the storage account to be deployed part of the same operation.





### Actual Behaviour

azurerm_storage_account always checks if the name exist, even if the Microsoft.Storage resource provider is not registered, leading to a false error message saying SubscriptionNotFound.

### Steps to Reproduce

Stage 1
1. Unregister the resource provider 'Microsoft.Storage'
2. execute the code above

Plan should provide the error in the debug section above

Stage 2
1. Comment the storage account and redeploy that code (it will register the provider and create the resource group)
2. Apply

Stage 3
1. Uncomment the storage account
2. apply and the storage account got created


### Important Factoids

_No response_

### References

Request:

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/4702224/09004daa-ac82-4892-b119-dce9c281530f)
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/4702224/38bd1860-32cd-40a0-9335-e60f9e34cdae)


Response:

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/4702224/3047c418-33d3-4b33-896b-f00f6ae16434)

**Comment by magodo** [comment] 2023-12-05 08:02
Hi @LaurentLesle,

I've tried to unregister the `Microsoft.Storage` RP, then try to `terraform plan` with either a valid and an already taken name, both works fine for me:

```shell
tf-config/storageaccount/name_validate via 💠 default took 2s
💤  az provider show -n Microsoft.Storage | jq .registrationState
"Unregistered"

tf-config/storageaccount/name_validate via 💠 default took 2s
💤  tf plan
╷
│ Warning: Provider development overrides are in effect
│
│ The following provider development overrides are set in the CLI configuration:
│  - magodo/restful in /home/magodo/go/bin
│  - azure/azapi in /home/magodo/go/bin
│  - hashicorp/azurerm in /home/magodo/go/bin
│
│ The behavior may therefore not match any released version of the provider and applying changes may cause the state to become incompatible with published releases.
╵

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform planned the following actions, but then encountered a problem:

  # azurerm_resource_group.example will be created
  + resource "azurerm_resource_group" "example" {
      + id       = (known after apply)
      + location = "westeurope"
      + name     = "example-resources-mgd"
    }

Plan: 1 to add, 0 to change, 0 to destroy.
╷
│ Error: 1 error occurred:
│       * `name` is not available: [AlreadyExists] The storage account named storageaccountnamemgd123 is already taken.
│
│
│
│   with azurerm_storage_account.example,
│   on main.tf line 10, in resource "azurerm_storage_account" "example":
│   10: resource "azurerm_storage_account" "example" {
│
╵
```

I can also confirm that the subscription of the principal is actually the same one for the `az` command and `terraform` command.

**Comment by rcskosir** [comment] 2024-02-09 18:51
Thanks for taking the time to submit this issue. @magodo was unable to reproduce this behavior. We’re going to close this issue for now, but if you run into this again with the latest Terraform and Provider versions, please feel free to [open a new issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/new/choose).

**Closed by rcskosir** 2024-02-09 18:51 UTC
Labels: question, waiting-response, service/resources, v/3.x
