### ISSUE TITLE
Multiple services require access to resources' data plane

### ISSUE THREAD

**Issue by edoboker** [hashicorp/terraform-provider-azurerm#14106] opened 2021-11-09 12:49 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version 

 - Terraform v1.0.10 on windows_amd64
 - AzureRM provider version 2.80

### Affected Resource(s)

* `azurerm_storage_account`
* `azurerm_storage_queue`
* `azurerm_key_vault`

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "stg" {
  name                     = "globalyuniquestorageaccount"
  resource_group_name      = azurerm_resource_group.storage_rg.name
  location                 = azurerm_resource_group.storage_rg.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  account_kind            = "StorageV2"
  access_tier                = "Cool"
}

resource "azurerm_storage_queue" "queue" {
  name                 = "mysamplequeue"
  storage_account_name = azurerm_storage_account.stg.name
}
```

### Debug Output

> Error: reading queue properties for AzureRM Storage Account
> "[AccountName]": queues.Client#GetServiceProperties: Failure sending
> request: StatusCode=0 -- Original Error: context deadline exceeded

### Expected Behaviour

Terraform should create resources via ARM and management APIs, and report their status according to those APIs - regardless of the data plane status of the services. It is not Terraform's job to validate the data plane availability of the resources, only create them.

### Actual Behaviour

It seems that terraform attempts to connect to the actual resource (verified via the debug output, DNS queries it generates and other means; I could not find the exact line in the code which generates this requst - perhaps [this](https://github.com/hashicorp/terraform-provider-azurerm/blob/2220906a9dcce124e628f06173ca44292b89ae7b/vendor/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2021-01-01/storage/queueservices.go#L104)?)

I have seen similar behaviour with Azure Key Vault - which explicitly tries to access the key vault (in order to retrieve the contacts list, as detailed [here](https://github.com/hashicorp/terraform-provider-azurerm/blob/65e37e28a2cf55f56e7dbc5f9c97044b3aa3ea14/azurerm/internal/services/keyvault/key_vault_resource.go#L671)) - and it also fails in my environment, giving the error specified in the code (`Error retrieving contact for KeyVault [Name]...`)

### Steps to Reproduce

1. Block all egress traffic from the machine running terraform except those required for ARM (or, specifically, deny traffic to `*.blob.core.windows.net` or `*.vault.azure.net`)
2. `terraform apply`

### Important Factoids

I am running in an environment where all traffic is filtered carefully, and no internet access is available. I can only access ARM and ARM-related FQDNs (AAD, trafficmanager, Azure Portal etc.)

**Comment by tombuildsstuff** [comment] 2021-11-09 13:08
hi @edoboker 

Thanks for opening this issue.

Due to the nature of the Azure API, different resources have to communicate with different Azure API's to be able to track changes to them and (in some cases) confirm provisioning is successful since the ARM API's don't report that correctly. For example, for Storage and Key Vault some functionality is only available via the Data Plane API's - as such we need to be able to communicate with them to be able to both provision and subsequently track changes to those resources.

Unfortunately there's plenty of reasons for the need to access both Resource Manager and Data Plane API's - certain Azure Services (such as in the case of Key Vault and Storage) also require reaching out to Data Plane API's since functionality isn't available in, or isn't comparatively available within the Resource Manager API's themselves. Whilst there's some open issues to track moving some of these over to using Resource Manager, certain Azure functionality by design will never be available through the Resource Manager API's (for example, the Storage Blob API's) - as such these will always be a dependency within Terraform for us to be able to both provision and track changes to those resources.

The particular issue your referring to is being tracked in https://github.com/hashicorp/terraform-provider-azurerm/issues/9738 - which rather than having multiple issues tracking the same thing for, I'm going to close this issue in favour of - would you mind subscribing to that issue for updates?

Thanks!

**Closed by tombuildsstuff** 2021-11-09 13:08 UTC
Labels: question

**Comment by tombuildsstuff** [comment] 2021-11-09 14:40
@edoboker Terraform resources go one of the lifecycles:

- Create: `Create` (sometimes `Update`, if some properties can only be set that way) then `Read`
- Update: `Update` and then `Read`
- Refresh / Plan / Apply: `Read`
- Delete: `Read` then `Delete`
- Import: `Read`

The Read function there's important since it's used to get the latest representation of the resource to be able to determine if there's any changes to it (which is ultimately how Terraform determines if there's things to change in the plan). Taking Storage Accounts as an example, whilst you may not be provisioning fields which use the Data Plane API during the `Create`, since we support those fields we need to be able to track changes to them, meaning during the `Read` functions we need to reach out to those API's here.

Your specific example there about the Queue Properties is since those are only available in the Data Plane API (either entirely, or without extra permissions, I forget which) - so we have to check that to be able to display that diff: https://github.com/hashicorp/terraform-provider-azurerm/blob/74759b2fd355f82e6e6c01e964b75f3f2dcd2468/internal/services/storage/storage_account_resource.go#L1743-L1759. Storage in particular is awkward there since the Data Plane and Resource Manager API's aren't feature-compatible - and even when they are require slightly different permissions based on when the Role Assignments for your users were created (e.g. Role Assignments created 2+ years ago behave differently to new Role Assignments, and determining the difference is non-trivial).

Another example there is Key Vault, whilst the ARM API states that provisioning has succeeded - to be able to use dependent resources within Terraform we have to wait for the DNS to finish replicating (which, since there's no other approach of polling for) meaning we end up polling from the users local machine (with no cache), it's not ideal/perfect but it means most cases will be successful. As mentioned above Private Link has unfortunately changed this slightly where some functionality is now only available over the Resource Manager API which complicates things here - which if the API's were feature-compatible would be fine - but unfortunately they're not (and so we can't just switch Data Plane for Resource Manager without losing functionality).

Unfortunately we don't have a list of those Resources (and to be honest, I don't think that's something we're likely to add anytime soon due to the amount of work it'd be) - however that's something we could look at in the longer term. The Permissions required to deploy Resources are similar here - it's something we'd like to display on the Resource Documentation itself however at the moment that'd be a huge task both to start with and from an ongoing perspective with how things currently work, however this is something we're thinking about in the longer-term.

As a general rule, Data Sources in this Provider assume we have limited permissions (e.g. perhaps I can retrieve the AKS Cluster, but I may not have permissions to retrieve it's Kuberneres credentials) - whereas for Resources we assume we have CRUD access to all required API's (Resource Manager / Data Plane as needed) - whilst there's downsides to that (as in this case) unfortunately it's required to be able to accurately track changes to resources (which is a key feature of Terraform). There are a handful of exceptions to this to workaround API issues, for example the `ListKeys` API for a Storage Account is a `GET` operation which requires Write permissions - which will fail when there's a Lock on a Storage Account - as such [we have specific logic for this](https://github.com/hashicorp/terraform-provider-azurerm/blob/74759b2fd355f82e6e6c01e964b75f3f2dcd2468/internal/services/storage/storage_account_resource.go#L1547-L1559) but as a general rule Data Sources/Resources should follow that pattern.

Hope that helps explain the why there, moving to use the Resource Manager API where possible is certainly one approach there - but that's only possible where the API's are both feature-compatible and (in the case of requiring new permissions) are something users can easily identify as an issue, as described above.
