### ISSUE TITLE
azurerm_storage_queue fails to apply in 3.96.0 version

### ISSUE THREAD

**Issue by ditost** [hashicorp/terraform-provider-azurerm#25337] opened 2024-03-20 17:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.3.10

### AzureRM Provider Version

3.96.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_queue

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_storage_account" "example" {
  name                     = "examplestorageacc"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_storage_queue" "example" {
  name                 = "mysamplequeue"
  storage_account_name = azurerm_storage_account.example.name
}
```

### Debug Output/Panic Output

```shell
│ Error: expected the subdomain type to be "queue" but got "table"
│ 
│   with azurerm_storage_queue.example,
│   on main.tf line 14, in resource "azurerm_storage_queue" "example":
│  14: resource "azurerm_storage_queue" "example" {
│
```

### Expected Behaviour

```
azurerm_storage_queue.example: Creation complete after 0s [id=https://************.queue.core.windows.net/mysamplequeue]
```

### Actual Behaviour

It failed with the error output that I've shown, however, rolling back to azurerm version 3.95.0 fixes this issue.

### Steps to Reproduce

terraform apply

### Important Factoids

Reverting to 3.95.0 fixes the issue.

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_queue

**Comment by tombuildsstuff** [comment] 2024-03-20 17:21
hey @ditost 

Thanks for opening this issue.

Taking a look through here this appears to be a duplicate of #25261 which has been fixed by #25262 and will ship in the enxt release. In the interim you should be able to pin to `v3.95.0` as you've mentioned, but this fix will ship in the next release - however since a fix for this has already been merged I'm going to close this issue for the moment, but the bot will comment on this issue once the release is available.

Thanks!

**Closed by tombuildsstuff** 2024-03-20 17:21 UTC
Labels: bug, duplicate, service/storage, v/3.x
