### ISSUE TITLE
apply azurerm_sql_failover_group doesn't update settings on secondary server

### ISSUE THREAD

**Issue by erniebilling** [hashicorp/terraform-provider-azurerm#8040] opened 2020-08-06 21:56 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform 0.12.29
AzureRM provider 2.20.0

### Affected Resource(s)

* `azurerm_sql_failover_group`

### Terraform Configuration Files

```hcl
variable primary_server_name { type = string }
variable secondary_server_name { type = string }
variable resource_group { type = string }


provider "azurerm" {
  version = "~> 2.20.0"  
  features {}

}

data "azurerm_sql_server" "primary_sql_db_server" {
  name                         = var.primary_server_name
  resource_group_name          = var.resource_group
}

data "azurerm_sql_server" "secondary_sql_db_server" {
  name                         = var.secondary_server_name
  resource_group_name          = var.resource_group
}


resource "azurerm_sql_database" "azure_sql_db_primary" {
  name                = "test-db"
  resource_group_name = var.resource_group
  location            = data.azurerm_sql_server.primary_sql_db_server.location
  server_name         = data.azurerm_sql_server.primary_sql_db_server.name
  requested_service_objective_name = "GP_Gen5_2"
  max_size_bytes      = 10 * 1024 * 1024 * 1024
}

resource "azurerm_sql_failover_group" "failover_group" {
  name                = "a-test-failover-group"
  resource_group_name = var.resource_group
  server_name         = data.azurerm_sql_server.primary_sql_db_server.name
  databases           = [azurerm_sql_database.azure_sql_db_primary.id]
  partner_servers {
    id = data.azurerm_sql_server.secondary_sql_db_server.id
  }

  read_write_endpoint_failover_policy {
    mode          = "Automatic"
    grace_minutes = 5
  }
}
```

### Expected Behavior

`terraform apply` successfully creates the database and failover group. A replica database gets created on the secondary server. Both databases have `requested_service_objective_name` = `GP_Gen5_2`

Modify `requested_service_objective_name` to `GP_Gen5_8` and `terraform apply` again. Expect both primary and secondary databases to be `GP_Gen5_8`

### Actual Behavior

Only the primary database is `GP_Gen5_8`, the secondary is still `GP_Gen5_2`

### Steps to Reproduce

- Create a primary and secondary SQL servers (via tarraform or other means)
- Use server names and resource group as inputs for this terraform file and `terraform apply`
- Change value of `requested_service_objective_name` to `GP_Gen5_8`
- Run `terrafrom apply` again
- Notice only primary DB is `GP_Gen5_8`

### References

I believe this is related to https://github.com/terraform-providers/terraform-provider-azurerm/issues/7938. In a failover group, actions on the primary DB should be propagated to secondary (including deleting the secondary.)

**Comment by yupwei68** [comment] 2020-08-10 07:47
Hi @erniebilling , thanks for opening this issue. I could confirm the steps to reproduce. Since this is a feature which is not supported from the service api, would you mind opening an issue https://github.com/Azure/azure-rest-api-specs/issues to suggest this feature to the service team.

**Comment by erniebilling** [comment] 2020-08-10 18:41
@yupwei68 I would be happy to. Can you help with some details about which API or API group this should be targeted at? Which API is lacking the required support?

**Comment by yupwei68** [comment] 2020-08-11 05:36
Hi @erniebilling It is this api https://github.com/Azure/azure-rest-api-specs/blob/master/specification/sql/resource-manager/Microsoft.Sql/preview/2015-05-01-preview/failoverGroups.json#L19.

**Comment by favoretti** [comment] 2021-08-25 09:37
Hi @erniebilling, thank you for reporting this issue. As far as I can see from the answers of product team, this is "by design", so since we can not do anything at the moment and it's blocked upstream I'm going to close this issue. You're welcome to raise this with your MSFT representatives and if this is going to change - reopen this issue or open a new one.

**Closed by favoretti** 2021-08-25 09:37 UTC
Labels: service/mssql, upstream-microsoft
