### ISSUE TITLE
Not able to disable the authorized Ip ranges in AKS API server using Terraform. 

### ISSUE THREAD

**Issue by selvanayaki678** [hashicorp/terraform-provider-azurerm#23317] opened 2023-09-19 10:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

0.15.5

### AzureRM Provider Version

3.59.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "akstest"
		name = "test-aks"
		resource_group_name = "test-rg"
		location = "East US 2"		
		kubernetes_version = "1.25.11"
		api_server_access_profile {
			authorized_ip_ranges = [somepublicips]
		}

		network_profile {
			network_plugin = "azure"
			network_policy = "azure"
            load_balancer_sku = "standard"
			outbound_type ="userDefinedRouting" 
		}
		default_node_pool {
			name = "default"
			type = "VirtualMachineScaleSets"
			orchestrator_version = "1.25.11
			temporary_name_for_rotation = "systemtest"
			enable_host_encryption = true
			node_count = 2
			vm_size = "Standard_D8s_v5"
			os_disk_size_gb = 100
			max_pods = 30		
			vnet_subnet_id 	= "subnetid"
			enable_node_public_ip = false
			enable_auto_scaling = true
			min_count = 2
			max_count =3
		}		
	
		identity {
			type = "SystemAssigned"
		}

		azure_active_directory_role_based_access_control {
			managed  = true
		}
		tags = {
			environment = var.basic.envrnmt
		}
		
		lifecycle {
			ignore_changes = [tags ]
		}
    }
```

### Debug Output/Panic Output

```shell
In the aks cluster, it enables the Authorized IP ranges with some IPs whatever specified in this block
	api_server_access_profile {
			authorized_ip_ranges = [somepublicips]
		}

After making the authorized_ip_ranges is empty. Its not disabling the authorized ip ranges in aks.
```

### Expected Behaviour

Not able to disable the authorized_ip_ranges feature in AKS using terraform.

### Actual Behaviour

Need a terraform configuration to disable to authorized_ip_ranges feature in AKS

**Comment by stephybun** [comment] 2023-09-19 11:46
Thanks for raising this issue @selvanayaki678.

Since this is duplicate of #20085 I'm going to close this issue to make sure discussions remain in a centralised place. Please subscribe to #20085 for updates. Thanks!

**Closed by stephybun** 2023-09-19 11:46 UTC
Labels: duplicate, service/kubernetes-cluster, v/3.x

**Comment by selvanayaki678** [comment] 2023-09-19 14:01
@stephybun When we will get the resolution for the above issue. Please respond

**Comment by mloskot** [comment] 2023-11-23 23:15
This is quite an issue that Terraform has no way to achieve the officially supported `az aks update --api-server-authorized-ip-ranges=""`, see my https://github.com/hashicorp/terraform-provider-azurerm/issues/20085#issuecomment-1824986938
