### ISSUE TITLE
Container App Ingress - clarify better how developer can get main Application Url

### ISSUE THREAD

**Issue by askaribragimov** [hashicorp/terraform-provider-azurerm#20696] opened 2023-02-28 13:24 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.8

### AzureRM Provider Version

3.45.0

### Affected Resource(s)/Data Source(s)

azurerm_container_app

### Terraform Configuration Files

```hcl
Documentation specifies that you can get latest_revision_fqdn.

However, this changes all the time and not equal to the Application URL found in the Overview tab of Azure Portal of a container app.
This URL is the most crucial to expose.

It seems that it is located in **azurerm_container_app.app.ingress[0].fqdn**
```

### Debug Output/Panic Output

```shell
ADDITIONALLY IT IS A BUGGY BEHAVIOR WHEN YOU TRY TO REUSE LAST REVISION FQDN:

My last revision uses suffix `    revision_suffix = formatdate("YYYYMMDDhhmmss", timestamp())` so everytime I run terraform it is changed. 

When I try to use "last_revision_fqdn" elsewhere, I get 



│ When expanding the plan for module.<my-module>.azurerm_api_management_api.apim_api to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/azurerm" produced an invalid new value for .service_url: was
│ cty.StringVal("https://<older last-revision-fqdn>.westeurope.azurecontainerapps.io"), but now cty.StringVal("https://<lates last-revision-fqdn>.westeurope.azurecontainerapps.io").
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

### Expected Behaviour

Documentation clarifies better how to obtain Application URL. Either it should be mentioned in Attributes section as a Note or 
provided as an additional output field.

**Comment by lonegunmanb** [comment] 2023-05-06 03:23
Hi @askaribragimov , I can reproduce this issue by the following steps.

## Apply the following config:

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "zjhe-container-app"
  location = "West Europe"
}

resource "azurerm_log_analytics_workspace" "example" {
  name                = "acctest-01"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  sku                 = "PerGB2018"
  retention_in_days   = 30
}

resource "azurerm_container_app_environment" "example" {
  name                       = "Example-Environment"
  location                   = azurerm_resource_group.example.location
  resource_group_name        = azurerm_resource_group.example.name
  log_analytics_workspace_id = azurerm_log_analytics_workspace.example.id
}

resource "azurerm_container_app" "example" {
  name                         = "example-app"
  container_app_environment_id = azurerm_container_app_environment.example.id
  resource_group_name          = azurerm_resource_group.example.name
  revision_mode                = "Single"

  template {
    container {
      name   = "examplecontainerapp"
      image  = "mcr.microsoft.com/azuredocs/containerapps-helloworld:latest"
      cpu    = 0.25
      memory = "0.5Gi"
    }
  }

  ingress {
    external_enabled = true
    transport        = "http"
    target_port      = 80
    traffic_weight {
      percentage      = 100
      latest_revision = true
    }
  }
}

resource "azurerm_container_app" "example2" {
  name                         = "example-app2"
  container_app_environment_id = azurerm_container_app_environment.example.id
  resource_group_name          = azurerm_resource_group.example.name
  revision_mode                = "Single"
  template {
    container {
      name   = "examplecontainerapp"
      image  = "hashicorp/http-echo"
      cpu    = 0.25
      memory = "0.5Gi"
      args   = [
        "-listen=:80",
        "-text=Hello World!",
      ]
      env {
        name = "APP_URL"
        value = "https://${azurerm_container_app.example.latest_revision_fqdn}"
      }
    }
  }
}
```

## Step 2, change image for both apps

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "zjhe-container-app"
  location = "West Europe"
}

resource "azurerm_log_analytics_workspace" "example" {
  name                = "acctest-01"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  sku                 = "PerGB2018"
  retention_in_days   = 30
}

resource "azurerm_container_app_environment" "example" {
  name                       = "Example-Environment"
  location                   = azurerm_resource_group.example.location
  resource_group_name        = azurerm_resource_group.example.name
  log_analytics_workspace_id = azurerm_log_analytics_workspace.example.id
}

resource "azurerm_container_app" "example" {
  name                         = "example-app"
  container_app_environment_id = azurerm_container_app_environment.example.id
  resource_group_name          = azurerm_resource_group.example.name
  revision_mode                = "Single"

  template {
    container {
      name   = "examplecontainerapp"
      image  = "hashicorp/http-echo"
      cpu    = 0.25
      memory = "0.5Gi"
      args   = [
        "-listen=:80",
        "-text=Hello World!",
      ]
    }
  }

  ingress {
    external_enabled = true
    transport        = "http"
    target_port      = 80
    traffic_weight {
      percentage      = 100
      latest_revision = true
    }
  }
}

resource "azurerm_container_app" "example2" {
  name                         = "example-app2"
  container_app_environment_id = azurerm_container_app_environment.example.id
  resource_group_name          = azurerm_resource_group.example.name
  revision_mode                = "Single"
  template {
    container {
      name   = "examplecontainerapp"
      image  = "mcr.microsoft.com/azuredocs/containerapps-helloworld:latest"
      cpu    = 0.25
      memory = "0.5Gi"
      env {
        name = "APP_URL"
        value = "https://${azurerm_container_app.example.latest_revision_fqdn}"
      }
    }
  }
}
```

The modification on image caused the change on fqdn, but the fqdn was modified from the service side, so during the Terraform plan Terraform cannot realize that the fqdn would be changed. Because we changed both apps, when we try to update app2, Terraform detect that app1’s fqdn has been changed and the original Terraform plan is obsolete, so you’ll see the error.

## The workaround

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "zjhe-container-app"
  location = "West Europe"
}

resource "azurerm_log_analytics_workspace" "example" {
  name                = "acctest-01"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  sku                 = "PerGB2018"
  retention_in_days   = 30
}

resource "azurerm_container_app_environment" "example" {
  name                       = "Example-Environment"
  location                   = azurerm_resource_group.example.location
  resource_group_name        = azurerm_resource_group.example.name
  log_analytics_workspace_id = azurerm_log_analytics_workspace.example.id
}

resource "azurerm_container_app" "example" {
  name                         = "example-app"
  container_app_environment_id = azurerm_container_app_environment.example.id
  resource_group_name          = azurerm_resource_group.example.name
  revision_mode                = "Single"

  template {
    container {
      name   = "examplecontainerapp"
      image  = "mcr.microsoft.com/azuredocs/containerapps-helloworld:latest"
      cpu    = 0.25
      memory = "0.5Gi"
    }
  }

  ingress {
    external_enabled = true
    transport        = "http"
    target_port      = 80
    traffic_weight {
      percentage      = 100
      latest_revision = true
    }
  }
}

data null_data_source "app_url" {
  inputs = {
    app_url = azurerm_container_app.example.latest_revision_fqdn
  }
}

resource "azurerm_container_app" "example2" {
  name                         = "example-app2"
  container_app_environment_id = azurerm_container_app_environment.example.id
  resource_group_name          = azurerm_resource_group.example.name
  revision_mode                = "Single"
  template {
    container {
      name   = "examplecontainerapp"
      image  = "hashicorp/http-echo"
      cpu    = 0.25
      memory = "0.5Gi"
      args   = [
        "-listen=:80",
        "-text=Hello World!",
      ]
      env {
        name = "APP_URL"
        value = "https://${data.null_data_source.app_url.outputs.app_url}"
      }
    }
  }
}
```

The `null_data_source` wrapped fqdn is now a `known after apply` value, the generated plan would be:

```text
               ~ env {
                    name  = "APP_URL"
                  ~ value = https://example-app--2kwvw5s.kindbay-2af48d4a.westeurope.azurecontainerapps.io/ -> (known after apply)
                }
```

That would solve your issue.

**Comment by lonegunmanb** [comment] 2023-05-17 02:34
Hi @askaribragimov just a kindly ping, could this workaround solve your issue? Please let us know if you have any further questions, thanks!

**Comment by matt-lethargic** [comment] 2023-06-05 13:52
The work around seems to have been deprecated https://github.com/hashicorp/terraform-provider-null/issues/86
Is there an example of this using `terraform_data`?

**Comment by matt-lethargic** [comment] 2023-06-06 08:49
@lonegunmanb For me this doesn't solve the main issue that the OP reported. The `latest_revision_fqdn` is the url for the latest version / container and changes with each new deployment/revision. The Application Url is fixed and doesn't change. If you're wanting to assign 50% traffic to one revision and 50% to the other you need the Application Url not the revision fqdn.

**Comment by lonegunmanb** [comment] 2023-06-06 09:38
Hi @matt-lethargic I don't think the url returned by `null_data_source` is fixed. The reason why I use this data source is to force Terraform to refresh `latest_revision_fqdn` returned by the `resource` **after** its update. Have you tried this workaround and confirmed that the application url returned by `null_data_source` is not latest version? If that is the case, would you please give me a minimum example code that could reproduce your issue along with the steps you've taken so I can have a try? Thanks!

**Comment by lonegunmanb** [comment] 2023-06-06 10:13
Hi @matt-lethargic I think I've got your point, here's another workaround:

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "zjhe-container-app"
  location = "West Europe"
}

resource "azurerm_log_analytics_workspace" "example" {
  name                = "acctest-01"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  sku                 = "PerGB2018"
  retention_in_days   = 30
}

resource "azurerm_container_app_environment" "example" {
  name                       = "Example-Environment"
  location                   = azurerm_resource_group.example.location
  resource_group_name        = azurerm_resource_group.example.name
  log_analytics_workspace_id = azurerm_log_analytics_workspace.example.id
}

locals {
  app_name_0  = "example-app"
  container_0 = {
    name   = "examplecontainerapp"
    image  = "mcr.microsoft.com/azuredocs/containerapps-helloworld:latest"
    cpu    = 0.25
    memory = "0.5Gi"
  }
}

resource "null_resource" "example_container_0" {
  triggers = {
    name      = local.app_name_0
    container = jsonencode(local.container_0)
  }
}

resource "azurerm_container_app" "example" {
  name                         = "${local.app_name_0}-${substr(md5(jsonencode(local.container_0)), 0, 4)}"
  container_app_environment_id = azurerm_container_app_environment.example.id
  resource_group_name          = azurerm_resource_group.example.name
  revision_mode                = "Single"

  template {
    container {
      name   = local.container_0.name
      image  = local.container_0.image
      cpu    = local.container_0.cpu
      memory = local.container_0.memory
    }
  }

  ingress {
    external_enabled = true
    transport        = "http"
    target_port      = 80
    traffic_weight {
      percentage      = 100
      latest_revision = true
    }
  }

  lifecycle {
    create_before_destroy = true
    replace_triggered_by  = [null_resource.example_container_0]
    ignore_changes        = [name]
  }
}

resource "azurerm_container_app" "example2" {
  name                         = "example-app2"
  container_app_environment_id = azurerm_container_app_environment.example.id
  resource_group_name          = azurerm_resource_group.example.name
  revision_mode                = "Single"
  template {
    container {
      name   = "examplecontainerapp"
      image  = "hashicorp/http-echo"
      cpu    = 0.25
      memory = "0.5Gi"
      args   = [
        "-listen=:80",
        "-text=Hello World!",
      ]
      env {
        name  = "APP_URL"
        value = "https://${azurerm_container_app.example.latest_revision_fqdn}"
      }
    }
  }
}
```

The key point is, to capture all arguments that could trigger a refresh on `latest_revision_fqdn` into a local object, then bind this object with `null_resource` with `triggers`, and link this `null_resource` to your container app resource, once one of these arguments has been changed, the `null_resource` would be recreated, and along with the container app resource, then your `latest_revision_fqdn` would be refreshed.

**Comment by matt-lethargic** [comment] 2023-06-06 11:39
I understand about the trigger. My point was how do I get the Application URL which is the actual first part of the original question:

> Documentation specifies that you can get latest_revision_fqdn.
> 
> However, this changes all the time and not equal to the Application URL found in the Overview tab of Azure Portal of a container app.
> This URL is the most crucial to expose.
> 
> It seems that it is located in **azurerm_container_app.app.ingress[0].fqdn**
> ```
> 
> ### Expected Behaviour
> Documentation clarifies better how to obtain Application URL. Either it should be mentioned in Attributes section as a Note or provided as an additional output field.

For me the answer was right there `azurerm_container_app.app.ingress[0].fqdn` I just missed it!

**Comment by Praneethvvs** [comment] 2023-07-12 20:26
Hi, we have two containers(frontend and backend). Wondering if there would be a way to get the fqdn of backend container to the front end container if we are using for_each to create containers. It would be really helpful if we can access the container app fqdn with container app name  (just like kubernetes).

`resource "azurerm_container_app" "container-app" {
  for_each = { for unique_app_name, app in var.container_apps : app.container_app_name => app }


  name                         = each.value.container_app_name
  container_app_environment_id = azurerm_container_app_environment.container-app-env.id
  resource_group_name          = azurerm_resource_group.container-app-resource-group.name
  revision_mode                = "Single"
  ingress {
    external_enabled = each.value.ingress_config.external_enabled
    target_port      = each.value.ingress_config.target_port
    traffic_weight {
      percentage      = 100
      latest_revision = true
    }
  }

  template {

    container {
      name   = each.value.container_template_config.container_name
      image  = each.value.container_template_config.image_name
      cpu    = each.value.container_template_config.cpu
      memory = each.value.container_template_config.memory
    }

  }`

**Comment by lonegunmanb** [comment] 2023-07-13 01:11
Hi @Praneethvvs, we have a working [example](https://github.com/Azure/terraform-azure-container-apps/blob/main/examples/startup/main.tf) in our container apps module, could this example help you?

**Comment by Praneethvvs** [comment] 2023-07-13 13:16
@lonegunmanb this is brilliant. Thanks for the example. Will try it out. Figured its hard/nearly impossible to have for_each to create resources and also have dependency between them.

**Comment by qeba** [comment] 2023-10-18 06:06
Just curious why not, just make the `Attributes Reference` available for the `fqdn`?. 

For example, we can use something like: `azurerm_container_app.container-app.fqdn`,

Then I can use that ( `azurerm_container_app.container-app.fqdn` ) and pass this value to Azure Application Gateway.

Now the issues if I'm using - **latest_revision_fqdn** `azurerm_container_app.container-app.latest_revision_fqdn`, if im point the IP of the application gateway to my domain, then the app becomes not accessible, since the last revision is being removed on me update the revision for example for app update. then i think i need to use `fqdn`, it a bit confusing deploying using terraform, as i need to manually modify it back as it does not supports the fqdn only .

**Comment by wesleychaid** [comment] 2023-11-08 04:10
@askaribragimov thanks for that, was having some trouble to get the **fdqn** of my app and was getting the same error using **latest_revision_fqdn**

**Comment by rcskosir** [comment] 2024-06-11 19:23
Thank you for taking the time to raise this! I am going to close this with @lonegunmanb‘s response as an answer. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).

**Closed by rcskosir** 2024-06-11 19:23 UTC
Labels: question, service/container-apps, v/3.x
