### ISSUE TITLE
`azurerm_log_analytics_storage_insights.tags` still has changes after apply

### ISSUE THREAD

**Issue by heiazuo** [hashicorp/terraform-provider-azurerm#15369] opened 2022-02-11 02:17 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

* `terraform v1.1.2 on windows_amd64`
*  `azurerm v2.90.0`

### Affected Resource(s)
* `azurerm_log_analytics_storage_insights.tags`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-la-4322"
  location = "West Europe"
}

resource "azurerm_log_analytics_workspace" "test" {
  name                = "acctestLAW-4322"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  sku                 = "PerGB2018"
  retention_in_days   = 30
}

resource "azurerm_storage_account" "test" {
  name                = "acctestsadssada"
  resource_group_name = azurerm_resource_group.test.name

  location                 = azurerm_resource_group.test.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_log_analytics_storage_insights" "test" {
  name                = "acctest-LA-4322"
  resource_group_name = azurerm_resource_group.test.name
  workspace_id        = azurerm_log_analytics_workspace.test.id

  blob_container_names = ["wad-iis-logfiles"]
  table_names          = ["WADWindowsEventLogsTable", "LinuxSyslogVer2v0"]

  storage_account_id  = azurerm_storage_account.test.id
  storage_account_key = azurerm_storage_account.test.primary_access_key

  tags = {
    ENV = "Test"
  }
}
```

### Debug Output
![image](https://user-images.githubusercontent.com/46072066/153376900-2f197004-a132-4075-be29-0c4b06b11522.png)

### Expected Behaviour

do plan after apply dones have no changes

### Actual Behaviour

do plan after apply done still have changes

### Steps to Reproduce

1.`terraform init`
2.`terraform plan`
3.`terraform apply`
4.`terraform paln`

### References

* #0000

**Comment by krowlandson** [comment] 2022-02-11 13:23
- Duplicate of #15357 ?

**Comment by myc2h6o** [comment] 2022-02-14 07:45
Tag is not supported for this resource per below document
https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/tag-support#microsoftoperationalinsights
![image](https://user-images.githubusercontent.com/10579712/153821235-ca7a3ca5-83ee-4359-a961-17329e78d58c.png)

**Closed** 2022-03-23 05:32 UTC
Labels: bug, upstream-microsoft, service/log-analytics
