### ISSUE TITLE
Support for Azure Functions output for Stream Analytics

### ISSUE THREAD

**Issue by Avalaxy** [hashicorp/terraform-provider-azurerm#15147] opened 2022-01-27 11:26 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi, in Stream Analytics we are using a Azure Functions output. Right now, this is not possible with terraform, so we have to use ARM templates unfortunately. We would like to have an Azure Function output in Terraform.

### New or Affected Resource(s)

* azurerm_stream_analytics_job

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by tombuildsstuff** [comment] 2022-01-27 16:55
hi @Avalaxy 

Thanks for opening this issue.

Taking a look through this appears to be a duplicate of #11981 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #11981 for updates?

Thanks!

**Closed by tombuildsstuff** 2022-01-27 16:55 UTC
Labels: duplicate, new-resource, service/stream-analytics
