### ISSUE TITLE
Azure Frontdoor Route Configuration of Compression without content types

### ISSUE THREAD

**Issue by faisaleem-na** [hashicorp/terraform-provider-azurerm#22595] opened 2023-07-19 08:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.3

### AzureRM Provider Version

3.65.0

### Affected Resource(s)/Data Source(s)

azurerm_cdn_frontdoor_route

### Terraform Configuration Files

```hcl
resource "azurerm_cdn_frontdoor_route" "fd_route" {
  for_each                      = var.fd_route
  name                          = each.value.name
  cdn_frontdoor_endpoint_id     = azurerm_cdn_frontdoor_endpoint.endpoint[each.value["endpoint_key"]].id
  cdn_frontdoor_origin_group_id = azurerm_cdn_frontdoor_origin_group.origingroup[each.value["origingroup_key"]].id
  cdn_frontdoor_origin_ids      = [azurerm_cdn_frontdoor_origin.origin[each.value["origin_key"]].id]
  cdn_frontdoor_rule_set_ids    = [azurerm_cdn_frontdoor_rule_set.rule_set[each.value["ruleset_key"]].id]
  enabled                       = each.value.enabled

  forwarding_protocol    = each.value.forwarding_protocol
  https_redirect_enabled = lookup(each.value, "https_redirect_enabled", true)
  patterns_to_match      = each.value.patterns_to_match
  supported_protocols    = each.value.https_redirect_enabled == true ? ["Http", "Https"] : each.value.supported_protocols

  cdn_frontdoor_custom_domain_ids = [azurerm_cdn_frontdoor_custom_domain.customDomain[each.value["customdomain_key"]].id]
  link_to_default_domain          = false

  cache {
    query_string_caching_behavior = each.value.query_string_caching_behavior
    query_strings                 = each.value.query_strings != null ? each.value.query_strings : null
    compression_enabled           = each.value.compression_enabled
    #content_types_to_compress     = each.value.content_types_to_compress != null ? each.value.content_types_to_compress : null
  }

  cdn_frontdoor_origin_path = lookup(each.value, "cdn_frontdoor_origin_path", null)
}
```

### Debug Output/Panic Output

```shell
Error: updating Front Door Route: (Route Name "A-EAHK-RUT-ROME-N1" / Afd Endpoint Name "A-EAHK-FDR-END-ROME-N1" / Profile Name "A-EAHK-FDR-ROME-N1" / Resource Group "A-EAHK-RGP-ROME-N1"): cdn.RoutesClient#Update: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="Compression cannot be enabled when content type to compress is empty."

  on .terraform/modules/frontdoor_profiles/module/main.tf line 454, in resource "azurerm_cdn_frontdoor_route" "fd_route":
 454: resource "azurerm_cdn_frontdoor_route" "fd_route" {
```

### Expected Behaviour

expected behavior is for the compression to be enabled for all content types without having to specify all content types as is via the resource manager api

### Actual Behaviour

apply fails with the above error, 'cannot enable compression when content types is empty'

### Steps to Reproduce

terraform apply

**Comment by WodansSon** [comment] 2023-07-20 20:34
@faisaleem-na, thank you for opening this issue. This error is not coming from the Terraform provider, the error is being returned from the service itself. IIRC the front door service does support compression without defining all of the file types you wish to compress in your configuration. I will check with the service team to see if my memory is correct or not. 🚀

**Comment by faisaleem-na** [comment] 2023-07-21 07:42
its possible to enable compression on the route in the portal without specifying content type! so i assumed that this means that its possible with the resource manager api hence raising the issue.
will wait for your confirmation, thanks

**Comment by WodansSon** [comment] 2023-07-21 19:17
@faisaleem-na, I have head back from the service team and they confirmed that the current behavior is correct, per the service team `the error message is the right behavior. Customer has to define content type to enable compression`. The reason you are able to just check enable compression in the Azure Portal is because when you do it automatically injects the below `content_types_to_compress` field into the Front Door configuration for you. If we were to mirror this same behavior in the provider it would cause issues because it would create a diff in the next `plan`/`apply` of the configuration since the values would exist in Azure but not in the configuration file.

```hcl
content_types_to_compress     = [
 "application/eot",
 "application/font",
 "application/font-sfnt",
 "application/javascript",
 "application/json",
 "application/opentype",
 "application/otf",
 "application/pkcs7-mime",
 "application/truetype",
 "application/ttf",
 "application/vnd.ms-fontobject",
 "application/xhtml+xml",
 "application/xml",
 "application/xml+rss",
 "application/x-font-opentype",
 "application/x-font-truetype",
 "application/x-font-ttf",
 "application/x-httpd-cgi",
 "application/x-javascript",
 "application/x-mpegurl",
 "application/x-opentype",
 "application/x-otf",
 "application/x-perl",
 "application/x-ttf",
 "font/eot",
 "font/ttf",
 "font/otf",
 "font/opentype",
 "image/svg+xml",
 "text/css",
 "text/csv",
 "text/html",
 "text/javascript",
 "text/js",
 "text/plain",
 "text/richtext",
 "text/tab-separated-values",
 "text/xml",
 "text/x-script",
 "text/x-component",
 "text/x-java-source",
]
```

**Comment by faisaleem-na** [comment] 2023-07-24 09:22
ok understood, thats unfortunate.

**Comment by WodansSon** [comment] 2023-07-25 02:05
@faisaleem-na, indeed, sorry I was unable to help, but on the bright side you now know why/how it works in the portal. With that I am going to go ahead and close this issue, thanks again for raising it! 🚀

**Closed by WodansSon** 2023-07-25 02:05 UTC
Labels: upstream/microsoft, service/cdn, v/3.x
