### ISSUE TITLE
Support for disk network access policy setting should be available in azurerm_linux/windows_virtual_machine

### ISSUE THREAD

**Issue by tomsri01** [hashicorp/terraform-provider-azurerm#15352] opened 2022-02-10 03:48 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As part of the os_disk settings in azurerm_linux_virtual_machine and azurerm_windows_virtual_machine add the ability to disable/control network_access_policy setting.

### New or Affected Resource(s)

* azurerm_*

### Potential Terraform Configuration

```hcl
os_disk {
    caching = "ReadWrite"
    storage_account_type = "Standard_LRS"
    network_access_policy = "denyAll"
  }
```

* #0000

**Comment by myc2h6o** [comment] 2022-02-10 04:47
Hi @tomsri01 There is an existing issue tracking the `network_access_policy` in `os_disk` of the `azurerm_linux_virtual_machine` and `azurerm_windows_virtual_machine`, would you mind subscribe to #15156 for update?
To give a brief summary from that issue, currently Azure API layer doesn't support configuring this directly from the vm os_disk block, we may need a workaround or ask API team to support it.

**Comment by mybayern1974** [comment] 2022-02-10 04:56
@tomsri01 would you mind if we close this issue for duplicate and instead you can subscribe to #15156 ?

**Comment by tombuildsstuff** [comment] 2022-02-10 12:55
Duplicate of #15156

**Closed by tombuildsstuff** 2022-02-10 12:55 UTC
Labels: duplicate
