### ISSUE TITLE
azurerm_builtin_role_definition  Incorrectly destroys and creates a role assignment (forces new resource) instead of noop.

### ISSUE THREAD

**Issue by asubmani** [hashicorp/terraform-provider-azurerm#1726] opened 2018-08-06 04:35 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
v.0.11.7

### Affected Resource(s)

* azurerm_role_assignment

### Terraform Configuration Files

main.tf

```hcl
resource "azurerm_resource_group" "aks-kubedev-shared-rg" {
  name     = "aks-kubedev-shared-rg"
  location = "westus"
}
data "azurerm_builtin_role_definition" "ManiOwner" {
  name = "Owner"
}

resource "azurerm_role_assignment" "aks-Owner" {
  scope              = "${azurerm_resource_group.aks-kubedev-shared-rg.id}"
 # role_definition_name = "Owner" 
  role_definition_id = "${data.azurerm_builtin_role_definition.ManiOwner.id}" 
  principal_id       = "a9eae191-1c79-4341-a5bc-321a4c124db6"
}

```

### Expected Behavior

`terraform plan` should do a **noop** right after a terraform apply (i.e config ==state==reality)
### Actual Behavior

terraform plan does a (forces new resource) with:
Plan: 1 to add, 0 to change and 1 to destroy.

The issue occurs only while using *role_definition_id*  i.e.
 ```hcl
${data.azurerm_builtin_role_definition<name>.id}
```

terraform apply destroys the role assignment and then adds it again.

### Steps to Reproduce

1. `terraform plan`
2. `terraform apply`
3. `terraform plan`

### Important Factoids

uncomment the line `role_definition_name = "Owner"` and comment out the line with:
`role_definition_id = "${data.azurerm_builtin_role_definition.ManiOwner.id}" `
and the issue does not affect if one uses role_definition_name

### References
[azurerm_builtin_role_definition](https://www.terraform.io/docs/providers/azurerm/d/builtin_role_definition.html)

* #0000

**Comment by reddyed** [comment] 2018-08-09 16:09
Hello,

i had faced similar issue. Instead of using role_definition_id, i used role_definition_name and it did work fine. please try that solution. Thanks.

**Comment by asubmani** [comment] 2018-08-19 19:09
@reddyed > Yes, I am aware of the workaround. I opened the bug as my customer has a lot of code with role_definition_id in them. Not a biggie but opened the bug in case others are affected by it too.

**Comment by boillodmanuel** [comment] 2020-09-01 15:59
I suggest the same workaround here: https://github.com/terraform-providers/terraform-provider-azurerm/issues/4847#issuecomment-684956114

**Comment by favoretti** [comment] 2021-08-18 12:17
Since #4847 has a more recent version of provider the issue is reported against and a more active discussion, I'm going to close this issue to keep the topic condensed to one issue. Any feedback/suggestions can be kept in #4847. Thank you.

**Closed by favoretti** 2021-08-18 12:17 UTC
Labels: bug
