### ISSUE TITLE
Terraform plan can't read azurerm_app_configuration_key when using key vault reference

### ISSUE THREAD

**Issue by danielnyari** [hashicorp/terraform-provider-azurerm#24719] opened 2024-01-31 06:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.7

### AzureRM Provider Version

3.89

### Affected Resource(s)/Data Source(s)

azurerm_app_configuration_key

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.8"
    }

    azuread = {
      source  = "hashicorp/azuread"
      version = "~> 2.47.0"
    }

    null = {
      source = "hashicorp/null"
    version = "~> 3.1.0" }
  }
  backend "azurerm" {

  }

}

provider "azurerm" {
  features {}

}

resource "random_string" "main" {
  length  = 6
  special = false
  upper   = false
}

data "azurerm_client_config" "this" {}

resource "azurerm_resource_group" "this" {
  location = "westeurope"
  name     = "myresourcegroup"
}

resource "azurerm_key_vault" "this" {
  name                        = "mykeyvault-we"
  location                    = azurerm_resource_group.this.location
  resource_group_name         = azurerm_resource_group.this.name
  enabled_for_disk_encryption = true
  sku_name                    = "standard"
  soft_delete_retention_days  = 7

  access_policy {
    tenant_id = data.azurerm_client_config.this.tenant_id
    object_id = azurerm_app_configuration.this.identity[0].principal_id
    secret_permissions = ["Get", "List"]
  }
}

resource "azurerm_key_vault_secret" "mysecret" {
  name         = "mysecret"
  key_vault_id = azurerm_key_vault.this.id
  value        = random_string.main.result

}

resource "azurerm_app_configuration" "this" {
    name = "myapp-config"
    location = azurerm_resource_group.this.location
    resource_group_name = azurerm_resource_group.this.name
  
    identity {
        type = "SystemAssigned"
    }

}

resource "azurerm_app_configuration_key" "mysecret" {
    configuration_store_id = azurerm_app_configuration.this.id
    key = "mysecret"
    type = "vault"
    vault_key_reference = azurerm_key_vault_secret.mysecret.versionless_id
  
}
```

### Debug Output/Panic Output

```shell
Error: while validating attribute 'value' (""): unexpected end of JSON input

  with azurerm_app_configuration_key.tool_host_token,
  on config.tf line 92, in resource "azurerm_app_configuration_key" "tool_host_token":
  92: resource "azurerm_app_configuration_key" "tool_host_token" {
```

### Expected Behaviour

When running terraform plan with vault type azurerm_app_configuration_key already in place, it produces the error. The first run (when there is no such resource in state) both plan and apply are successful and the resource is created.

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/87807446/6fa88792-22d4-4ac4-be0f-5d4ccdb4c17a)

### Actual Behaviour

Azurerm provider should be able to read the already existing resource from the state during terraform plan

### Steps to Reproduce

1. terraform init
2. terraform plan
3. terraform apply
4. wait for deployment
5. terraform plan again - this produces the error

**Comment by CorrenSoft** [comment] 2024-01-31 21:00
Same as #24639 
You can get more info there.

**Comment by rcskosir** [comment] 2024-01-31 23:38
@danielnyari Thank you for taking the time to open this issue, as @CorrenSoft mentioned, this is a duplicate of issue #24639, which has closed with a PR that just merged. Please take a look there for a workaround that might work for you in the mean time before the merged PR goes out with the next release.

**Closed** 2024-01-31 23:38 UTC
Labels: duplicate, service/app-configuration, v/3.x
