### ISSUE TITLE
Support for load blob content instead of local file

### ISSUE THREAD

**Issue by alex-3sr** [hashicorp/terraform-provider-azurerm#12798] opened 2021-07-30 23:20 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Hi all,

I think it's a limitation, or maybe I don't found a way to do what I need. In fact, I want to upload a file to Azure Storage as blob of file share, but I already have the content in local variable and not loca files. I would like to not write temporay the file locally and create it on the fly and upload to Azure Storage.

I think that **source** argument for **azurerm_storage_share_file** and **azurerm_storage_blob** need really a local file, correct ?

### New or Affected Resource(s)
azurerm_storage_share_file
azurerm_storage_blob

### Potential Terraform Configuration
For example below, I create somme SSH keys with tls_private_key resources and I want to upload it on a azure storage share file. The only way that I found is to use an interlmediate local_file resource
```hcl
resource "local_file" "file_ssh_keys" {
  for_each = toset(var.sftp_users)
  content  = tls_private_key.ssh_keys[each.key].public_key_openssh
  filename = "sshkey-${each.key}.pub"
}
resource "azurerm_storage_share_file" "file_ssh_keys" {
  for_each         = toset(var.sftp_users)
  name             = local_file.file_ssh_keys[each.key].filename
  storage_share_id = azurerm_storage_share.stor_share_sftp_keys[each.key].id
  source           = local_file.file_ssh_keys[each.key].filename
}
```

I really need to reach this goal to not write it locally by for example -->
```hcl
resource "azurerm_storage_share_file" "file_ssh_keys" {
  for_each         = toset(var.sftp_users)
  name             = local_file.file_ssh_keys[each.key].filename
  storage_share_id = azurerm_storage_share.stor_share_sftp_keys[each.key].id
  source           = rendered(local_file.file_ssh_keys[each.key].filename)
}
```

Thanks for your help and wish all a good day
Regards
Alex

**Comment by tombuildsstuff** [comment] 2021-08-10 15:01
Duplicate of #9927

**Closed by tombuildsstuff** 2021-08-10 15:01 UTC
Labels: question, service/storage
