### ISSUE TITLE
known-issue: parsing the App Service Plan ID using `v3.88.0`

### ISSUE THREAD

**Issue by latusekpiotr** [hashicorp/terraform-provider-azurerm#24560] opened 2024-01-19 09:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

not 100% sure but I think the latest, required_version defined as ">= 1.0"

### AzureRM Provider Version

3.88 (same code works fine in 3.87 though)

### Affected Resource(s)/Data Source(s)

azurerm_app_service_plan, azurerm_windows_function_app

### Terraform Configuration Files

```hcl
resource "azurerm_app_service_plan" "app_service_plan" {
  name                = "my-app-service-plan"
  location            = "northeurope"
  resource_group_name = "my-resource-group"
  kind                = "elastic"
  reserved            = false
  maximum_elastic_worker_count = 2
  per_site_scaling             = true
  sku {
    tier     = "ElasticPremium"
    size     = "EP1"
    capacity = 1
  }
}

resource "azurerm_windows_function_app" "function_app" {
  name                        = "function_name"
  location                    = "northeurope"
  resource_group_name         = "my-resource-group"
  service_plan_id             = azurerm_app_service_plan.app_service_plan.id
  
  (...other properties that don't seem to matter)
}
```

### Debug Output/Panic Output

```shell
Error: parsing "/subscriptions/***/resourceGroups/<our resource group name>/providers/Microsoft.Web/serverfarms/<our app service plan name>": parsing segment "staticServerFarms": parsing the AppServicePlan ID: the segment at position 6 didn't match
Expected a AppServicePlan ID that matched: /subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/example-resource-group/providers/Microsoft.Web/serverFarms/serverFarmValue
However this value was provided: /subscriptions/***/resourceGroups/<our resource group name>/providers/Microsoft.Web/serverfarms/<our app service plan name>

The parsed Resource ID was missing a value for the segment at position 6 (which should be the literal value "serverFarms").

with module.dtc.azurerm_windows_function_app.function_app (...) in resource "azurerm_windows_function_app" "function_app": service_plan_id = var.app_service_plan_id
```

### Expected Behaviour

App Service Plan gets created successfully but Function App should get created too.

### Actual Behaviour

App Service Plan gets created successfully and creating Function App fails with the error message above. Terraform Plan executes successfully, it only fails on Terraform Apply.

### Steps to Reproduce

Run terraform apply for the resources listed in "Terraform Configuration Files" section

**Comment by nilleb** [comment] 2024-01-19 09:04
Apart from [migrating resources](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/migrating-from-deprecated-resources), what other solution/workaround do we have?

**Comment by jackofallops** [comment] 2024-01-19 09:22
Hi @latusekpiotr 
Your config there is using the deprecated `azurerm_app_service_plan` rather than the updated `azurerm_service_plan`, are you able to update to use the current resource? This will resolve your issue here.

**Comment by latusekpiotr** [comment] 2024-01-19 09:32
Updating to use azurerm_service_plan is our long term plan but short term we just had to pin azurerm to 3.87 for now since the issue occurs in a few of our pipelines that run daily so updating them will take some time.

**Comment by crypto-ralph** [comment] 2024-01-19 09:34
We encounter the same issue with resource `azurerm_service_plan`.

**Comment by diogonborges** [comment] 2024-01-19 09:51
Likely related to this
https://github.com/hashicorp/terraform-provider-azurerm/pull/24483

**Comment by tombuildsstuff** [comment] 2024-01-19 09:53
@crypto-ralph @diogonborges @latusekpiotr just to isolate this one given the code snippet above (`service_plan_id = var.app_service_plan_id`) - is this value being provided from a variable, or from the `id` attribute of the `azurerm_app_service_plan` / `azurerm_service_plan` resource?

**Comment by crypto-ralph** [comment] 2024-01-19 09:59
in our case it comes from id attribute:

```
    {
      key : "workload.service_plan_id"
      value : azurerm_service_plan.service_plan.id
      label = "${var.workload.name}.${var.env}"
    },
```

**Comment by nilleb** [comment] 2024-01-19 10:15
@tombuildsstuff 

```
resource "azurerm_app_service_plan" "this" {
  name                = "asp-${local.defaults.app}-${var.defaults.env}-${var.region.nickname}"
[..]
}

resource "azurerm_linux_web_app" "this" {
  name                = "as-${local.defaults.app}-${var.defaults.env}-${var.region.nickname}"
[..]
  service_plan_id           = azurerm_app_service_plan.this.id
```

**Comment by tombuildsstuff** [comment] 2024-01-19 11:02
:wave: hey folks

Thanks for the reporting this / for the feedback above.

Firstly, apologies for the inconvenience/impact here - if you’re affected by this then we’d recommend pinning to the previous version of the Provider for the moment, which can be done using the `required_providers` block:

```terraform
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=3.87.0"
    }
  }
}
```

Discussing this internally, whilst we’re planning to roll out a fix for this one, this’ll come in the next release.

---

Some background on the context for this change:

Different parts of Azure treat Resource ID Segments differently - however the latest guidance is that Resource ID Segments should be `camelCased` rather than `lowercased` or `UPPERCASED`.

Whilst Azure APIs are _supposed_ to be _case-insensitive_ in Requests and _case-sensitive_ in Responses - given the differing guidance for Resource ID handling over the years, the behaviour of the API differs depending on the Resource Provider, API Version and Resource Type.

As a part of migrating resources from `Azure/azure-sdk-for-go` to `hashicorp/go-azure-sdk`, we’re working through and updating any Resource IDs which don’t use `camelCase` - as is the case here with the `serverfarms` segment now being `serverFarms`.

Whilst we’ve tested the upgrade path for the newer App Service resources, it appears that we’ve missed a couple of scenarios with the older resources here - and whilst we’re planning to fix that - it’s worth noting that the older App Service resources are deprecated and will be removed in the future - and as such if you can we’d recommend migrating towards the new resources.

The other issue at play here is that the Resource ID being returned from the Azure API isn’t being normalized in the Read function for (at least) the Logic App Standard resource (to ensure that we’re consistently storing `serverFarms` in the state) - as such we’re going to fix that and double-check the other usages as a part of the next release.

---

As mentioned above - if you’re affected by this issue we’d recommend pinning to the last version of the Provider at this point - however our intention is to ship a fix for this in the next version of the provider - and as such I’m going to assign this issue to the next milestone.

Thanks!

**Comment by MartinPronk67** [comment] 2024-01-19 13:11
Can it be that this is not version related, as I am using version ~>=3.48 still and the issue came up between yesterday evening and this morning. So, i raised a case with Microsoft as I noticed the camelCase notation. 

MS came with this:

From the information available, it seems that the AzureRM provider is designed to be case sensitive for resource IDs. This means that the segment needs to be in a specific case format, which in your case is `serverfarms`. However, this contrasts with the Azure Portal and Azure APIs, which may have different casing conventions that can change over time. For instance, Azure may move towards using camelCasing (like `serverFarms`) for segment names.

**Comment by MartinPronk67** [comment] 2024-01-19 15:01
> > Can it be that this is not version related, as I am using version ~>=3.48 still and the issue came up between yesterday evening and this morning.
> 
> It is. `~>=3.48` means you got 3.88. Check https://developer.hashicorp.com/terraform/language/expressions/version-constraints

Yep, you are right, my bad..

**Closed** 2024-01-23 15:19 UTC
Labels: service/app-service, v/3.x

**Comment by brtj** [comment] 2024-01-25 14:14
Issue still persist on 3.89.0

**Comment by bdorplatt** [comment] 2024-01-25 15:39
This appears to still be a problem with the 3.89 provider using the resource azurerm_service_plan

`- Using hashicorp/azurerm v3.89.0 from the shared cache directory`

```
Error: parsing "/subscriptions/11111111-1111-1111-1111-111111111111/resourceGroups/test-rg/providers/Microsoft.Web/serverfarms/test-asp": parsing segment "staticServerFarms": parsing the AppServicePlan ID: the segment at position 6 didn't match
│ 
│ Expected a AppServicePlan ID that matched:
│ 
│ > /subscriptions/11111111-1111-1111-1111-111111111111/resourceGroups/example-resource-group/providers/Microsoft.Web/serverFarms/serverFarmValue
│ 
│ However this value was provided:
│ 
│ > /subscriptions/11111111-1111-1111-1111-111111111111/resourceGroups/test-rg/providers/Microsoft.Web/serverfarms/test-asp
```

```
resource "azurerm_service_plan" "asp" {
  name                = "${var.tenant}-${var.region_abbr}-${var.subscription}-${var.asp_name_short}-asp"
  location            = var.region
  os_type             = var.asp_os_type
  resource_group_name = var.resource_group_name
  sku_name            = var.asp_sku_name
}
```

**Comment by tombuildsstuff** [comment] 2024-01-26 16:25
@fishfacemcgee would you mind opening a new issue to track the issue with `azurerm_monitor_autoscale_setting` - whilst that's a related issue it'd be good to separate these out, so that we can track the root causes.

---

@bdorplatt so that we can look further into that issue, would you mind showing the (sanitised) output of `terraform state show azurerm_service_plan.asp`? This would allow us to isolate where that's coming from.

Thanks!

**Comment by bdorplatt** [comment] 2024-01-26 18:21
Sorry, I referenced the incorrect resdource earlier. The issue we are seeing is with the "azurerm_windows_function_app" referencing the Service Plan's resource ID.

The parsed Resource ID was missing a value for the segment at position 6
│ (which should be the literal value "serverFarms").
│   with module.function_app.azurerm_windows_function_app.function_app,
│   on .terraform\modules\function_app\main.tf line 19, in resource "azurerm_windows_function_app" "function_app":
│   19:   service_plan_id             = var.fa_service_plan_id

**Comment by bdorplatt** [comment] 2024-01-26 19:16
In the above example,  var.fa_service_plan_id is coming from a variable file where the casing is set as "serverfarms." Prior to the 3.88 update, it had to be this way or the build would fail.
Changing the set variable to reflect "serverFarms" with the 3.89 provider works. Are we to start using camelCase as below now when referencing a Service Plan or is this going to get reverted back to the previous behavior?

`fa_service_plan_id = "/subscriptions/11111111-1111-1111-1111-111111111111/resourceGroups/test-rg/providers/Microsoft.Web/serverFarms/test-asp"`

**Comment by mxrss2** [comment] 2024-01-27 01:01
See this as well in .89 as well reverted to an older version worked without incident. 

```

           azurerm_dns_cname_record.dns-leretapay: Refreshing state... [id=/subscriptions/000000-0000-000-000-0000/resourceGroups/rg-tax-network-prod/providers/Microsoft.Network/dnsZones/example.com/CNAME/qa]
app-stack  azurerm_app_service_custom_hostname_binding.host-binding: Refreshing state... [id=/subscriptions/0000-000-000-000-0000/resourceGroups/resougetestscrub/providers/Microsoft.Web/sites/site/hostNameBindings/example.com]
app-stack  ╷
           │ Error: ID was missing the `hostNameBindings` element
           │ 
           │   with azurerm_app_service_certificate_binding.cert-binding-managed-cert (cert-binding-managed-cert),
           │   on cdk.tf.json line 70, in resource.azurerm_app_service_certificate_binding.cert-binding-managed-cert (cert-binding-managed-cert):
           │   70:         "hostname_binding_id": "${lower(azurerm_app_service_custom_hostname_binding.host-binding (host-binding).id)}",


```

**Comment by lra** [comment] 2024-02-01 14:21
Just to balance some comment, 3.89.0 fixed the issue we had with 3.88.0, so the new comments might be related to a new issue.

**Comment by stevekurutzpm** [comment] 2024-02-19 19:58
Just spitballing here . . . since we've seen Azure behave inconsistently in casing ids for app service plans and other resources, how about if the provider acts less case-sensitively?  This is an echo of the same problem occurring with VMs, virtual networks, and so on.  The casing issue in app services/app service plans has been around for some time as well - we'd see it with importing resources, for instance.  Perhaps the provider can just be a little more flexible, knowing that Azure spits out unpredictably-formatted output and doesn't seem to be stopping any time soon.

**Comment by rmxuser** [comment] 2024-02-22 21:26
> We encounter the same issue with resource `azurerm_service_plan`.

Mine is the same resource, and after running a terraform apply on the service plan, it updated the app service plan ID output to the new pattern, which is:

/providers/Microsoft.Web/serverFarms

instead of the old version that has lower 'f' in 'farms':

/providers/Microsoft.Web/serverfarms
