### ISSUE TITLE
Azure Automation - azurerm_automation_dsc_configuration unmarshalling JSON Error

### ISSUE THREAD

**Issue by KISMIDEV** [hashicorp/terraform-provider-azurerm#15452] opened 2022-02-16 08:22 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Terraform (and AzureRM Provider) Version

* Terraform Core version: v1.0.5
* AzureRM Provider version: v2.70.0

### Terraform Configuration Files

```hcl
# DSC Configuration - main.tf
resource "azurerm_automation_dsc_configuration" "dsc" {
  for_each = {
    for configuration in flatten([
      for configuration_key, configuration_value in var.automation_account : [
        for key, value in configuration_value.configuration : {
          configuration_name      = key
          content_embedded        = value.content_embedded
          automation_account_name = configuration_key
        }
      ] 
    ]) : "${configuration.configuration_name}" => configuration
  }

  name                    = each.value.configuration_name
  resource_group_name     = azurerm_resource_group.dsc.name
  location                = azurerm_resource_group.dsc.location
  automation_account_name = azurerm_automation_account.dsc[each.value.automation_account_name].name
  content_embedded        = each.value.content_embedded
}

# DSC Configuration - variables.tf 
variables "automation_account " {
  type = ...
  default = {
   ...
      "configuration" = {
        "default" = {
          "content_embedded" = "configuration default {}",
        }
      },
   ...
  }
}
```

### Description / Feedback

Hi!
I'm testing azurerm_automation_dsc_configuration using Terraform.
When the value in the Terraform Registry was tested in the local enviroment, the DSC Configuration was created normally.
An error occurred when `terraform apply` combined with other Azure Services.
The error message  and combined resource list is as below.
 * virtual network
 * subnet
 * virtual network peering
 * network security group
 * key vault
 * storage account
 * automation account

![image](https://user-images.githubusercontent.com/70998863/154222089-49c50352-813f-4108-a924-87402f6c4d32.png)

If  anyone knows how to fix that error, please let me know how.
Thank you!

**Comment by tombuildsstuff** [comment] 2022-02-16 11:49
Duplicate of https://github.com/hashicorp/terraform-provider-azurerm/issues/10858

**Closed by tombuildsstuff** 2022-02-16 11:49 UTC
