### ISSUE TITLE
Terraform import of TME nested endpoints

### ISSUE THREAD

**Issue by EppO** [hashicorp/terraform-provider-azurerm#16588] opened 2022-04-28 14:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.0.2

### AzureRM Provider Version

3.3.0

### Affected Resource(s)/Data Source(s)

azurerm_traffice_manager_external_endpoint

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "myRGP" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_public_ip" "example" {
  name                = "example-publicip"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  allocation_method   = "Static"
  domain_name_label   = "example-pip"
}


resource "azurerm_traffic_manager_profile" "myTM" {
  name                   = "parent-profile"
  resource_group_name    = azurerm_resource_group.example.myRGP
  traffic_routing_method = "Weighted"

  dns_config {
    relative_name = "parent-profile"
    ttl           = 100
  }

  monitor_config {
    protocol                     = "http"
    port                         = 80
    path                         = "/"
    interval_in_seconds          = 30
    timeout_in_seconds           = 9
    tolerated_number_of_failures = 3
  }

  tags = {
    environment = "Production"
  }
}

resource "azurerm_traffic_manager_profile" "nested" {
  name                   = "nested-profile"
  resource_group_name    = azurerm_resource_group.myRGP.name
  traffic_routing_method = "Priority"

  dns_config {
    relative_name = "nested-profile"
    ttl           = 30
  }

  monitor_config {
    protocol = "https"
    port     = 443
    path     = "/"
  }
}

resource "azurerm_traffic_manager_nested_endpoint" "externalEndpoint1" {
  name                = "externalEndpoint1"
  target_resource_id  = azurerm_traffic_manager_profile.nested.id
  priority            = 1
  profile_id          = azurerm_traffic_manager_profile.myTM.id
  min_child_endpoints = 5
}
```

### Debug Output/Panic Output

```shell
terraform import "azurerm_traffic_manager_nested_endpoint.tme_name_primary" "/subscriptions/<subId>/resourceGroups/myRGP/providers/Microsoft.Network/trafficManagerProfiles/myTM/nestedEndpoints/externalEndpoint1"
azurerm_traffic_manager_nested_endpoint.tme_name_primary: Importing from ID "/subscriptions/<subId>/resourceGroups/myRGP/providers/Microsoft.Network/trafficManagerProfiles/myTM/nestedEndpoints/externalEndpoint1"...
╷
│ Error: parsing Resource ID "/subscriptions/<subId>/resourceGroups/myRGP/providers/Microsoft.Network/trafficManagerProfiles/myTM/nestedEndpoints/externalEndpoint1": parsing "/subscriptions/<subId>/resourceGroups/myRGP/providers/Microsoft.Network/trafficManagerProfiles/myTM/nestedEndpoints/externalEndpoint1": parsing segment "endpointType": expected the segment "endpointType" to match one of the values "AzureEndpoints, ExternalEndpoints, NestedEndpoints" but got "nestedEndpoints"
```

### Expected Behaviour

Ids of the traffic manager external endpoints in Azure are using `nestedEndpoints`: 
```json
"id": "/subscriptions/<subId>resourceGroups/myRGP/providers/Microsoft.Network/trafficManagerProfiles/myTM/nestedEndpoints/externalEndpoint1"
```

Type in the resource JSON is also `nestedEndpoints`: 
```json
"type": "Microsoft.Network/trafficManagerProfiles/nestedEndpoints",
```

so import should be able to use `nestedEndpoints`, not `NestedEndpoints`

### Actual Behaviour

Imports needs to be done using `NestedEndpoints` in order to pass. 

### Steps to Reproduce

```bash
terraform import "azurerm_traffic_manager_nested_endpoint.tme_name_primary" "/subscriptions/<subId>/resourceGroups/myRGP/providers/Microsoft.Network/trafficManagerProfiles/myTM/nestedEndpoints/externalEndpoint1"
```

**Comment by EppO** [comment] 2022-05-18 15:36
@tombuildsstuff: I really don't think this is a question, the inconsistency between Azure Portal/AzureRM API and the AzureRM Terraform provider should be treated as a bug IMHO

**Comment by tombuildsstuff** [comment] 2022-05-18 15:53
@EppO unfortunately this isn't a bug - the Azure Portal changes it's casing at random intervals - as such whilst it generally matches we follow the ARM convention here that the Portal should be following (that is, camelCase) _except_ for when the value defined in the Swagger (as in this case) is in TitleCase - which is what's happening here.

The Resource ID that Terraform is expecting [can be found in the Import section of the documentation for that resource](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/traffic_manager_nested_endpoint#import) - in this case [due to the casing of the Constants within the Swagger](https://github.com/Azure/azure-rest-api-specs/pull/16472) we're requiring this to be in TitleCase, as whilst we originally submitted this PR in camelCase, the Azure ARM Team have decided this has to be in TitleCase instead (although unfortunately the comments now appear to be gone).

Since this is working as intended (and we're correctly raising the expected casing here `expected the segment "endpointType" to match one of the values "AzureEndpoints, ExternalEndpoints, NestedEndpoints" but got "nestedEndpoints"`) - I'm going to close this issue for the moment, but as mentioned above the casing expected at import time can be found in the `Import` section of each Resource within the documentation.

Thanks!

**Closed by tombuildsstuff** 2022-05-18 15:53 UTC
Labels: question

**Comment by EppO** [comment] 2022-05-18 15:59
Alright I get that, thanks a lot for this detailed explanation 🙏
