### ISSUE TITLE
azurerm_storage_management_policy: Terraform plans successfully but fails to apply

### ISSUE THREAD

**Issue by mohd-faraz** [hashicorp/terraform-provider-azurerm#22004] opened 2023-06-01 13:04 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.0

### AzureRM Provider Version

3.55 , 3.58

### Affected Resource(s)/Data Source(s)

azurerm_storage_management_policy

### Terraform Configuration Files

I created a lifecycle rule on blockblob and appendblob with actions set on baseblob snapshot and version. I use a variable to define the configuration for setting the rule. 
By default the value i set is -1 , ideally it should also allow to set -1 as value since that is default value but the argument only takes between 0 and 9999. This is creating issues. 
I have already used this rule but before I set values for all the declared configuration parameters in the rule but this time I set only for 1 configuration parameter. The other 2 configuration parameters is set to null which is taken as -1 in planning and apply stage but if I set -1 it fails as it cannot take this value( in principle this is the default value and should be taken as an argument)

```hcl
```

### Debug Output/Panic Output

```shell
Error: creating Storage Account Management Policy: xxxxxx : Failure responding to request: StatusClde = 400 -- Original Error: Autorest/azure: Service returned an error. Status= 400 Code= "InvalidManagementPolicyRule" Message="ManagementPolicy rule Blob lifecycle rule is invalid. Invalid value for parameter : basebBlob
```

### Expected Behaviour

It should allow to set default value of -1 . Currently it doesn't accept -1 to create the lifecycle rule on storage account 

### Actual Behaviour

Throwing error as described above

**Comment by mohd-faraz** [comment] 2023-06-01 15:15
Why can't I set -1 as default value , it doesn't make sense , I am creating a library for configuring my storage account and by default I want to set -1 for the configuration, please allow -1 as argument value

**Comment by magodo** [comment] 2023-06-02 07:00
@mohd-faraz Would you please provide a minimal configuration that can reproduce this issue?

**Comment by mohd-faraz** [comment] 2023-06-02 07:25
> @mohd-faraz Would you please provide a minimal configuration that can reproduce this issue?
Here in this code I assign the values of the configuration to a variable which i declare as follows: I set default to -1 as well also instead of null, throws error as it cannot take -1 as argument value. Also, in terraform plan everything looks fine when I enter a positive integer value, when I don't specify a value for one of these configuration , it throws error only in terraform apply, the error is stated above in issue.
Note: the variables are declared in variable.tf and the resource in main.tf. There was no error when all variables are declared some value, error occurred only when I don't declare the value. Also in the code if you check the value allowed is between 0 and 99999 but -1 is not accepted even though it is default value
```
variable "delete_day" {
  type        = number
  description = "The age in days after creation to delete the blob version"
  default     = null
}
resource "azurerm_storage_management_policy" "example" {
  count = var.abc? 1 : 0
  storage_account_id = azurerm_storage_account.example.id

  rule {
    name    = "rule1"
    enabled = true
    filters {
      blob_types   = ["blockBlob", "appendBlob"]
    }
    actions {
      base_blob {
        delete_after_days_since_modification_greater_than  =  var.delete_day
      }
      snapshot {
        delete_after_days_since_creation_greater_than = var.xyz
      }
      version {
        delete_after_days_since_creation_greater_than = var.xyzabc
      }
    }
  }

**Comment by magodo** [comment] 2023-06-02 07:58
@mohd-faraz Thank you for providing this! Would you please kindly expand the variables to using their concrete values so I can reproduce it in my local?

**Comment by mohd-faraz** [comment] 2023-06-02 08:06
This throws error as -1 cannot be taken as argument even though it is default value, i don't want to set days only for version and leave others to default, also I want to keep these configurations in my library and adapt the values as per my requirements
```
resource "azurerm_storage_management_policy" "example" {
  count = var.abc? 1 : 0
  storage_account_id = azurerm_storage_account.example.id

  rule {
    name    = "rule1"
    enabled = true
    filters {
      blob_types   = ["blockBlob", "appendBlob"]
    }
    actions {
      base_blob {
        delete_after_days_since_modification_greater_than  =  -1
      }
      snapshot {
        delete_after_days_since_creation_greater_than = -1
      }
      version {
        delete_after_days_since_creation_greater_than = 7
    }
  }
}

**Comment by magodo** [comment] 2023-06-02 10:07
@mohd-faraz Thanks! The problem is that you have to specify at least one *enabled* condition in each action (e.g. within the `base_blob`). Setting `-1` to the condition indicates to disable that condition. The value `-1` is used here because `0` is a valid value for these condition properties, while we need another value to imply "disabled".

Arguably we should raise this validation error in plan time, whilst it is a bit complicated in terms of implementation, since these values can be interpolated, resulting into unknown values in plan time.

For your specific use case, you probably want to define these `action`(s) as input variable, and define some [custom conditions](https://developer.hashicorp.com/terraform/language/expressions/custom-conditions) to ensure one condition is specified and *enabled*. Though, I believe this won't help too much if these variables are referencing values known only at apply time.

**Comment by mohd-faraz** [comment] 2023-06-02 10:24
> @mohd-faraz Thanks! The problem is that you have to specify at least one _enabled_ condition in each action (e.g. within the `base_blob`). Setting `-1` to the condition indicates to disable that condition. The value `-1` is used here because `0` is a valid value for these condition properties, while we need another value to imply "disabled".
> 
> Arguably we should raise this validation error in plan time, whilst it is a bit complicated in terms of implementation, since these values can be interpolated, resulting into unknown values in plan time.
> 
> For your specific use case, you probably want to define these `action`(s) as input variable, and define some [custom conditions](https://developer.hashicorp.com/terraform/language/expressions/custom-conditions) to ensure one condition is specified and _enabled_. Though, I believe this won't help too much if these variables are referencing values known only at apply time.

can the actions(s) be specified as dynamic block so if there is no value enabled in the action block f.e. base_blob, then it doesn't consider base_blob?

**Comment by rcskosir** [comment] 2024-06-06 17:44
Thank you for taking the time to raise this! I am going to close this with @magodo‘s response as an answer. We use Issues in this repository to track feature enhancements and bugs in the Azure Provider. So that we can maintain focus on that, if you have further questions we ask that questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).

**Closed by rcskosir** 2024-06-06 17:44 UTC
Labels: question, service/storage, v/3.x
