### ISSUE TITLE
Azure VM launch fails with specialized image because of osProfile

### ISSUE THREAD

**Issue by franklsf95** [hashicorp/terraform-provider-azurerm#14549] opened 2021-12-08 22:20 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.88.1
```

### Affected Resource(s)

* `azurerm_linux_virtual_machine_scale_set`
* `azurerm_shared_image` (related)

### Terraform Configuration Files

```hcl
resource "azurerm_linux_virtual_machine_scale_set" "app" {
  name                = "raysort-ncus"
  resource_group_name = azurerm_resource_group.app.name
  location            = azurerm_resource_group.app.location
  sku                 = "Standard_E8s_v5"
  instances           = 2
  admin_username      = "azureuser"
  source_image_id     = data.azurerm_shared_image.image.id

  admin_ssh_key {
    public_key = file("~/.ssh/authorized_keys")
    username   = "azureuser"
  }

  os_disk {
    storage_account_type = "Premium_LRS"
    caching              = "ReadWrite"
  }

  data_disk {
    storage_account_type = "Premium_LRS"
    caching              = "None"
    disk_size_gb         = 8192
    lun                  = 0
  }

  network_interface {
    name    = "primary"
    primary = true

    ip_configuration {
      name      = "primary"
      primary   = true
      subnet_id = azurerm_subnet.app.id
    }
  }
}
```

### Debug Output

https://gist.github.com/franklsf95/ec0a4a266eaa4d9d19686146ece1090f

### Panic Output

n/a

### Expected Behaviour

Should create VMSS.

### Actual Behaviour

```
{
  "error": {
    "code": "InvalidParameter",
    "message": "Parameter 'osProfile' is not allowed.",
    "target": "osProfile"
  }
}
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

The reason is that the image that I supplied is a specialized image, and creating a VM with a specialized image cannot take an osProfile` parameter; it should be removed completely (I compared the JSON templates downloaded from Azure portal and found this difference between creating VM from a generalized image vs. a specialized image).

I can currently work around this by making the image a generalized one, but it would be great if this can be fixed. Basically the provider needs to figure out if the image is specialized, and if so, remove the `osProfile` block.

### References

* #0000

**Comment by tombuildsstuff** [comment] 2021-12-10 23:02
hi @franklsf95 

Thanks for opening this issue.

Taking a look through this appears to be a duplicate of #7772 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #7772 for updates?

Thanks!

**Closed by tombuildsstuff** 2021-12-10 23:02 UTC
Labels: duplicate, service/vmss
