### ISSUE TITLE
When changing VM sizes in HDInsight the cluster is removed and the provider fails

### ISSUE THREAD

**Issue by cicorias** [hashicorp/terraform-provider-azurerm#5103] opened 2019-12-07 20:25 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
provider "azurerm" {
  version         = "~> 1.37.0"
```

Terraform v0.12.17

### Affected Resource(s)

* `azurerm_hdinsight_hadoop_cluster`

### Terraform Configuration Files

```hcl
data "azurerm_resource_group" "hdpcluster" {
  name = "${var.prefix}-hdp-cluster"
}


data "azurerm_storage_account" "hdpcluster" {
  name                = "${var.prefix}hdinsightstor"
  resource_group_name = data.azurerm_resource_group.hdpcluster.name
}


resource "azurerm_hdinsight_hadoop_cluster" "hdpcluster" {
  name                = "${var.prefix}hdicluster"
  resource_group_name = data.azurerm_resource_group.hdpcluster.name
  location            = data.azurerm_resource_group.hdpcluster.location
  cluster_version     = var.hdp_version.cluster_version
  tier                = var.hdp_version.tier

  component_version {
    hadoop = var.hdp_version.component_version
  }

  gateway {
    enabled  = true
    username = var.creds_gateway.username
    password = var.creds_gateway.password
  }

  storage_account {
    storage_container_id = "${data.azurerm_storage_account.hdpcluster.primary_blob_endpoint}hdinsight"
    storage_account_key = data.azurerm_storage_account.hdpcluster.primary_access_key
    is_default          = true
  }

  roles {
    head_node {
      vm_size  = var.hdp_version.head_vmsize
      username = var.creds_headnode.username
      password = var.creds_headnode.password
    }

    worker_node {
      vm_size               = var.hdp_version.worker_vmsize
      username              = var.creds_worker.username
      password              = var.creds_worker.password
      target_instance_count = var.hdp_worker_count
    }

    zookeeper_node {
      vm_size  = var.hdp_version.zoo_vmsize
      username = var.creds_zookeeper.username
      password = var.creds_zookeeper.password
    }
  }
}


```
```
variable "hdp_version" {
  type = object({
    cluster_version   = string
    component_version = string
    tier              = string
    head_vmsize       = string
    worker_vmsize     = string
    zoo_vmsize        = string
  })
  default = {
    cluster_version   = "4.0"
    component_version = "3.1"
    tier              = "Standard"
    head_vmsize       = "Standard_D3_V2"
    worker_vmsize     = "Standard_D3_V2"
    zoo_vmsize        = "Standard_D3_V2"
  }
}

```

### Expected Behavior

when changing VM sizes for the HDInsight cluster the cluster should remain and Terraform not error out.

### Actual Behavior

During apply, the error appears:
```
Error: Error waiting for creation of HDInsight Hadoop Cluster "scicoriahdicluster" (Resource Group "scicoria-hdp-cluster"): Future#WaitForCompletion: the number of retries has been 
exceeded: StatusCode=404 -- Original Error: Code="ResourceNotFound" 
Message="The Resource 'Microsoft.HDInsight/clusters/scicoriahdicluster'
 under resource group 'scicoria-hdp-cluster' was not found."
```
### Steps to Reproduce

1. create an HDInsight cluster via apply
1. Change the VM size for all the different nodes
1. run apply

**Comment by ArcturusZhang** [comment] 2019-12-09 07:21
Hi @cicorias I tried your script but I did not reproduce your issue.
Here is what I do when trying to reproduce this issue:
1. I go to this [page](https://www.terraform.io/docs/providers/azurerm/r/hdinsight_hadoop_cluster.html) and wrote a deployment script (with a little tweaking, names etc) for this scenario.
1. I deleted the script I wrote in the first step, and erased my `terraform.tfstate`
1. I made a new file filled with your script.
1. `terraform refresh` and import the existed `azurerm_hdinsight_hadoop_cluster`
1. `terraform apply`
After all this steps, no error pops up. The `azurerm_hdinsight_hadoop_cluster` gets destroyed and then created again, since the `vm_size` has a `ForceNew` attribute with it.

Could you please add more context of this issue? For instance, you can set two environment variables
`TF_LOG=DEBUG` and `TF_LOG_PATH=~/terraformlog.log` to show debug log.

Thanks!

**Comment by cicorias** [comment] 2019-12-09 13:52
I’ll repro today, but I had changed just VM size for all the nodes which does force a destroy and create.

**Comment by ArcturusZhang** [comment] 2019-12-23 02:29
> Thanks for looking at this:
> 
> I have a repro of the situation with the two env variables set and the Log file output.
> This is under Windows 10 - PowerShell is the cmd processor.
> I also recorded the screen to mp4.
> 
> The log file (stripped of passwords) is here: https://scicoriahdinsightstor.blob.core.windows.net/public/terraformlog.log
> 
> A mp4 is here: https://scicoriahdinsightstor.blob.core.windows.net/public/terraform-hdinsight.mp4
> 
> The steps were:
> 
> ```
>  9 cd .\deploy\az
>   10 ll
>   11 dir
>   12 rm .\.terraform\
>   13 rm .\terraform.tfstate*
>   14 dir
>   15 $env:TF_LOG="DEBUG"
>   16 $env:TF_LOG_PATH="c:/temp/terraformlog.log"
>   17 code ..\..
>   18 terraform apply -auto-accept
>   19 terraform apply -auto-approve
>   20 terraform init
>   21 terraform apply -auto-approve
>   22 code-insiders.cmd .
>   23 terraform apply
> ```
> 
> The TF scripts are here: https://github.com/cicorias/njit-bd-mr-project/tree/master/deploy/az
> There are overrides used for the variables - pasword, etc.

Sorry for being late, I am occupied elsewhere... But the links of logs and video seems to get staled. Would you please put the logs back? I think logs would be sufficient for this. Thanks!

And I have some questions about the steps you posted above. What does command 18 and 19 do? Without `terraform init`, those `terraform apply` will just produce an error (or that is intentional?).
And just checking my memory, these steps are 
1. apply with vm-size1 (corresponding to command 21)
1. change the vm-size by command (corresponding to command 22)
1. apply with the new vm-size
1. error pops out
Is this correct?

**Comment by favoretti** [comment] 2021-08-19 07:22
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.

**Closed by favoretti** 2021-08-19 07:22 UTC
Labels: bug, service/hdinsight
