### ISSUE TITLE
Deleting keyvault+certificate+policy deletes policy first, then fails to delete certificate and secrets

### ISSUE THREAD

**Issue by orlandokellystantec** [hashicorp/terraform-provider-azurerm#25478] opened 2024-04-01 23:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1,7.5

### AzureRM Provider Version

3.85.0

### Affected Resource(s)/Data Source(s)

azurerm_key_vault. , azurerm_key_vault_access_policy

### Terraform Configuration Files

```hcl
resource "azurerm_key_vault" "kv" {
  name                = var.kv_name
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
  tenant_id           = data.azurerm_client_config.current.tenant_id

  sku_name = "standard"
  soft_delete_retention_days  = 90
  purge_protection_enabled    = true

  network_acls{
    bypass = "AzureServices"
    default_action = "Deny"
  }
  }

resource "azurerm_key_vault_access_policy" "neomkvpolicy1" {
  key_vault_id = azurerm_key_vault.kv.id
  tenant_id    = data.azurerm_client_config.current.tenant_id
  object_id    = data.azurerm_client_config.current.object_id

  key_permissions = [
                                "Get",
                                "List",
                                "Update",
                                "Create",
                                "Import",
                                "Delete",
                                "Recover",
                                "Backup",
                                "Restore"
                            ]
    secret_permissions = [
                                "Get",
                                "List",
                                "Set",
                                "Delete",
                                "Recover",
                                "Backup",
                                "Restore"
                            ]
    certificate_permissions = [
                                "Get",
                                "List",
                                "Update",
                                "Create",
                                "Import",
                                "Delete",
                                "Recover",
                                "Backup",
                                "Restore",
                                "ManageContacts",
                                "ManageIssuers",
                                "GetIssuers",
                                "ListIssuers",
                                "SetIssuers",
                                "DeleteIssuers"
                            ]
    storage_permissions = [
      "Get",
    ]
  }

## Policy for TFC Agent
  resource "azurerm_key_vault_access_policy" "policy2" {
  key_vault_id = azurerm_key_vault.kv.id
  tenant_id    = data.azurerm_client_config.current.tenant_id
  object_id    = "hidden"

  key_permissions = [
                                "Get",
                                "List",
                                "Update",
                                "Create",
                                "Import",
                                "Delete",
                                "Recover",
                                "Backup",
                                "Restore"
                            ]
    secret_permissions = [
                                "Get",
                                "List",
                                "Set",
                                "Delete",
                                "Recover",
                                "Backup",
                                "Restore"
                            ]
    certificate_permissions = [
                                "Get",
                                "List",
                                "Update",
                                "Create",
                                "Import",
                                "Delete",
                                "Recover",
                                "Backup",
                                "Restore",
                                "ManageContacts",
                                "ManageIssuers",
                                "GetIssuers",
                                "ListIssuers",
                                "SetIssuers",
                                "DeleteIssuers"
                            ]
    storage_permissions = [
      "Get",
    ]
  }
```

### Debug Output/Panic Output

```shell
n/a
```

### Expected Behaviour

Terraform should delete the secrets and certs first before deleting access policy, 

### Actual Behaviour

Terraform deletes the keyvault access policy first, resulting in an error when trying to delete a secret and the keyvault, as the access is now lost

### Steps to Reproduce

terraform destroy

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/3160

**Comment by tombuildsstuff** [comment] 2024-04-02 10:16
@orlandokellystantec as @wuxu92 (and [this comment in #3160](https://github.com/hashicorp/terraform-provider-azurerm/issues/3160#issuecomment-485912552)) have mentioned this is an issue with the Terraform Configuration being used, not a bug in the Provider (and this isn't something the Provider can control, since the dependency graph is involved by Terraform Core, based on the Terraform Configuration).

As such you would either need to define the access policies inline within the `azurerm_key_vault` resource - or add a `depends_on` to ensure the Secret is dependent on the Access Policy, so that the create order is `Key Vault -> Access Policy -> Secret` and the delete order is `Secret -> Access Policy -> Key Vault`.

However since this is a configuration issue (and a duplicate of #3160) which can be fixed by updating the Terraform Configuration being used - I'm going to close this issue for the moment.

Thanks!

**Closed by tombuildsstuff** 2024-04-02 10:16 UTC
Labels: question, service/key-vault, v/3.x
