### ISSUE TITLE
vnet_route_all_enabled not used on azurerm_linux_function_app + azurerm_windows_function_app

### ISSUE THREAD

**Issue by hribeiro-msft** [hashicorp/terraform-provider-azurerm#22212] opened 2023-06-19 17:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.0.11

### AzureRM Provider Version

3.61.0

### Affected Resource(s)/Data Source(s)

azurerm_linux_function_app, azurerm_windows_function_app

### Terraform Configuration Files

```hcl
terraform {

  required_version = ">=0.12"
  
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "~>3.24"
    }
  }
}

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "hsr-test-resources4"
  location = "westeurope"
}

resource "azurerm_service_plan" "ASP-hsr-Linux" {
  name                = "ASP-hsr-Linux"
  location         = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  os_type             = "Linux"
  sku_name            = "P1v2"
}

resource "azurerm_virtual_network" "example" {
  name                = "example-vnet4"
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
}

resource "azurerm_subnet" "example" {
  name                 = "example-subnet4-1"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefixes     = ["10.0.2.0/24"]
  service_endpoints    = ["Microsoft.Storage"]
}

resource "azurerm_subnet" "example2" {
  name                 = "example-subnet4-2"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefixes     = ["10.0.3.0/24"]
    delegation {
        name = "delegation"

        service_delegation {
            name    = "Microsoft.Web/serverFarms"
            actions = ["Microsoft.Network/virtualNetworks/subnets/join/action", "Microsoft.Network/virtualNetworks/subnets/prepareNetworkPolicies/action"]
        }
    }
}

resource "azurerm_storage_account" "example" {
  name                     = "hsrlxfunctionappsa4"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "LRS"

  tags = {
    environment = "staging"
  }
}

resource "azurerm_storage_account_network_rules" "example" {
  storage_account_id = azurerm_storage_account.example.id

  default_action             = "Allow"
  ip_rules                   = ["127.0.0.1"]
  virtual_network_subnet_ids = [azurerm_subnet.example.id]
  bypass                     = ["Metrics"]
}


resource "azurerm_linux_function_app" "hsr-linux-app" {
  name                = "hsr-linux-app4"
  location         = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  service_plan_id     = azurerm_service_plan.ASP-hsr-Linux.id

  storage_account_name       = azurerm_storage_account.example.name
  storage_account_access_key = azurerm_storage_account.example.primary_access_key

  virtual_network_subnet_id = azurerm_subnet.example2.id

  site_config {
    vnet_route_all_enabled = false
  }
}
```

### Debug Output/Panic Output

```shell
2023-06-19T18:23:21.716+0100 [DEBUG] provider.terraform-provider-azurerm_v3.61.0_x5.exe: AzureRM Request: 
PUT /subscriptions/<SUBID>/resourceGroups/hsr-test-resources4/providers/Microsoft.Web/sites/hsr-linux-app4?api-version=2021-03-01 HTTP/1.1
Host: management.azure.com
User-Agent: Go/go1.19.3 (386-windows) go-autorest/v14.2.1 Azure-SDK-For-Go/v66.0.0 web/2021-03-01 HashiCorp Terraform/1.0.11 (+https://www.terraform.io) Terraform Plugin SDK/2.10.1 terraform-provider-azurerm/dev pid-222c6c49-1b0a-5959-a213-6608f9eb8820
Content-Length: 1329
Content-Type: application/json; charset=utf-8
X-Ms-Correlation-Request-Id: e82d3220-d553-a22c-1714-bbbb9fa217ab
Accept-Encoding: gzip

{"identity":{"type":"None"},"kind":"functionapp,linux","location":"westeurope","properties":{"clientCertEnabled":false,"clientCertMode":"Optional","dailyMemoryTimeQuota":0,"enabled":true,"httpsOnly":false,"serverFarmId":"/subscriptions/<SUBID>/resourceGroups/hsr-test-resources4/providers/Microsoft.Web/serverfarms/ASP-hsr-Linux","siteConfig":{"alwaysOn":false,"appSettings":[{"name":"FUNCTIONS_EXTENSION_VERSION","value":"~4"},{"name":"AzureWebJobsStorage","value":"DefaultEndpointsProtocol=https;AccountName=hsrlxfunctionappsa4;AccountKey=Z+2aU0FfSqShFyUaSvTvWd6TU4KGpaDSW4zXF7Cg8/pj5o5sfxketWtWlzIXRXc5KU3mM2NEX6Lt+AStfPIOnQ==;EndpointSuffix=core.windows.net"},{"name":"AzureWebJobsDashboard","value":"DefaultEndpointsProtocol=https;AccountName=hsrlxfunctionappsa4;AccountKey=Z+2aU0FfSqShFyUaSvTvWd6TU4KGpaDSW4zXF7Cg8/pj5o5sfxketWtWlzIXRXc5KU3mM2NEX6Lt+AStfPIOnQ==;EndpointSuffix=core.windows.net"}],"ftpsState":"Disabled","linuxFxVersion":"","loadBalancing":"LeastRequests","managedPipelineMode":"Integrated","minTlsVersion":"1.2","scmMinTlsVersion":"1.2","use32BitWorkerProcess":false},"virtualNetworkSubnetId":"/subscriptions/<SUBID>/resourceGroups/hsr-test-resources4/providers/Microsoft.Network/virtualNetworks/example-vnet4/subnets/example-subnet4-2"},"tags":{}}: timestamp=2023-06-19T18:23:21.716+0100


The json payload formated:
{
    "identity": {
        "type": "None"
    },
    "kind": "functionapp,linux",
    "location": "westeurope",
    "properties": {
        "clientCertEnabled": false,
        "clientCertMode": "Optional",
        "dailyMemoryTimeQuota": 0,
        "enabled": true,
        "httpsOnly": false,
        "serverFarmId": "/subscriptions/<SUBID>/resourceGroups/hsr-test-resources4/providers/Microsoft.Web/serverfarms/ASP-hsr-Linux",
        "siteConfig": {
            "alwaysOn": false,
            "appSettings": [
                {
                    "name": "FUNCTIONS_EXTENSION_VERSION",
                    "value": "~4"
                },
                {
                    "name": "AzureWebJobsStorage",
                    "value": "DefaultEndpointsProtocol=https;AccountName=hsrlxfunctionappsa4;AccountKey=Z+2aU0FfSqShFyUaSvTvWd6TU4KGpaDSW4zXF7Cg8/pj5o5sfxketWtWlzIXRXc5KU3mM2NEX6Lt+AStfPIOnQ==;EndpointSuffix=core.windows.net"
                },
                {
                    "name": "AzureWebJobsDashboard",
                    "value": "DefaultEndpointsProtocol=https;AccountName=hsrlxfunctionappsa4;AccountKey=Z+2aU0FfSqShFyUaSvTvWd6TU4KGpaDSW4zXF7Cg8/pj5o5sfxketWtWlzIXRXc5KU3mM2NEX6Lt+AStfPIOnQ==;EndpointSuffix=core.windows.net"
                }
            ],
            "ftpsState": "Disabled",
            "linuxFxVersion": "",
            "loadBalancing": "LeastRequests",
            "managedPipelineMode": "Integrated",
            "minTlsVersion": "1.2",
            "scmMinTlsVersion": "1.2",
            "use32BitWorkerProcess": false
        },
        "virtualNetworkSubnetId": "/subscriptions/<SUBID>/resourceGroups/hsr-test-resources4/providers/Microsoft.Network/virtualNetworks/example-vnet4/subnets/example-subnet4-2"
    },
    "tags": {}
}
```

### Expected Behaviour

The payload sent to create the App should include the vnet_route_all_enabled property in the siteConfigs and it doesn't which means that property isn't doing anything.

From the code of this file https://[github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/appservice/linux_function_app_resource.go](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/appservice/linux_function_app_resource.go)

It seems that the property is filtered out on purpose for some reason.

And this seems to also be the same for windows_function_app

https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/appservice/windows_function_app_resource.go

At least these 2 have this problem

### Actual Behaviour

The payload doesn't include the property.

### Steps to Reproduce

1. Terraform apply

### References

Similar to this https://github.com/hashicorp/terraform-provider-azurerm/issues/18701 I would say

**Comment by myc2h6o** [comment] 2023-06-20 07:19
@hribeiro-msft This is by design. There are multiple API requests during the update of this resource, `vnet_route_all_enabled` is updated with a PATCH request with below code:
https://github.com/hashicorp/terraform-provider-azurerm/blob/f70fe79ef6f7464b191c9cbb3aa46ab064089560/internal/services/appservice/linux_function_app_resource.go#L980-L982

There shall be a request like below in the log:
`PATCH /subscriptions/***/resourceGroups/***/providers/Microsoft.Web/sites/***/config/web?api-version=2021-03-01` which contains the `vnetRouteAllEnabled` property

**Comment by rcskosir** [comment] 2024-06-06 16:20
Thank you for taking the time to raise this! I am going to close this with @myc2h6o‘s response as an answer. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).

**Closed by rcskosir** 2024-06-06 16:20 UTC
Labels: question, service/functions, v/3.x
