### ISSUE TITLE
azurerm_role_assignment forced replacement with no changes

### ISSUE THREAD

**Issue by srvrguy** [hashicorp/terraform-provider-azurerm#20142] opened 2023-01-20 20:24 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.7

### AzureRM Provider Version

3.30.0

### Affected Resource(s)/Data Source(s)

azurerm_role_assignment

### Terraform Configuration Files

```hcl
# Assign the Function App as a DNS contributor to the zone
resource "azurerm_role_assignment" "acmebot" {
  scope                = azurerm_dns_zone.sample.id
  role_definition_name = "DNS Zone Contributor"
  principal_id         = module.keyvault-acmebot.functionapp_id
}
```

### Debug Output/Panic Output

```shell
The following output was lightly redacted to remove sensitive information.

  # azurerm_role_assignment.acmebot must be replaced
-/+ resource "azurerm_role_assignment" "acmebot" {
      ~ id                               = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-myexample-common-westus/providers/Microsoft.Network/dnszones/zone.example.com/providers/Microsoft.Authorization/roleAssignments/d7b0000f-0000-0000-0000-ad9ghk05027d" -> (known after apply)
      ~ name                             = "d7b0000f-0000-0000-0000-ad9ghk05027d" -> (known after apply)
      ~ principal_type                   = "ServicePrincipal" -> (known after apply)
      ~ role_definition_id               = "/subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Authorization/roleDefinitions/befefa01-0000-0000-0000-272ff33ce314" -> (known after apply)
      ~ scope                            = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-myexample-common-westus/providers/Microsoft.Network/dnszones/zone.example.com" -> "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-myexample-common-westus/providers/Microsoft.Network/dnsZones/zone.example.com" # forces replacement
      + skip_service_principal_aad_check = (known after apply)
        # (2 unchanged attributes hidden)
    }
```

### Expected Behaviour

No change should have been made.

### Actual Behaviour

Terraform requires replacement of the resource.

It appears the change it detects that forces replacement is that the scope path has a change from "dnszones" to "dnsZones".

### Steps to Reproduce

Create resource on version 3.26.0 or lower (down to 3.22.0) of the provider. Update provider to 3.27.0 or later and run a plan.

The change that caused this issue appears to have happened between 3.26.0 and 3.27.0 and the issue persists in the latest version of the provider.

**Comment by manicminer** [comment] 2023-01-30 19:58
Duplicate of #15557

**Closed by manicminer** 2023-01-30 19:58 UTC
