### ISSUE TITLE
Deploying an AKS cluster fails on 2.79 but works on 2.78

### ISSUE THREAD

**Issue by SimonGurney** [hashicorp/terraform-provider-azurerm#13585] opened 2021-10-01 18:11 UTC
Deploying an AKS cluster fails on 2.79 but works on 2.78

### Terraform (and AzureRM Provider) Version

1.0.7 with 2.79.0

### Affected Resource(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
terraform {
  required_version = "=1.0.7"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=2.79.0"
    }
    azuread = {
      source  = "hashicorp/azuread"
      version = "=2.5.0"
    }
  }
}

provider "azurerm" {
  features {}
  subscription_id = var.subscription_id
  tenant_id = var.tenant_id
  client_id = var.client_id
  client_secret = var.client_secret
  skip_provider_registration = true
}

provider "azuread" {
  tenant_id = var.tenant_id
  client_id = var.client_id
  client_secret = var.client_secret
}


data "azurerm_resource_group" "RG" {
  name     = var.rg_name
}

resource "azurerm_virtual_network" "VNet" {
  name                = "${var.prefix}-vnet"
  address_space       = ["10.0.0.0/8"]
  location            = data.azurerm_resource_group.RG.location
  resource_group_name = data.azurerm_resource_group.RG.name
}

resource "azurerm_subnet" "K8S" {
  name                                           = "${var.prefix}-subnet-k8s"
  address_prefixes                               = ["10.12.0.0/16"]
  resource_group_name                            = var.rg_name
  virtual_network_name                           = "${var.prefix}-vnet"
  enforce_private_link_endpoint_network_policies = true
}

data "azuread_group" "aks_cluster_admins" {
  display_name = var.ad_group_name
}

resource "azurerm_kubernetes_cluster" "main" {
  name                    = var.cluster_name
  kubernetes_version      = var.cluster_kubernetes_version
  location                = data.azurerm_resource_group.RG.location
  resource_group_name     = data.azurerm_resource_group.RG.name
  dns_prefix              = var.prefix
  sku_tier                = "Free"
  private_cluster_enabled = true
  #checkov:skip=CKV_AZURE_6:This is a private K8s so we do not use source IP restrictions
  default_node_pool {
    name                  = "agentpool"
    orchestrator_version  = var.cluster_kubernetes_version
    node_count            = var.cluster_node_count
    vm_size               = var.node_size
    os_disk_size_gb       = 40
    vnet_subnet_id        = azurerm_subnet.K8S.id
    enable_auto_scaling   = false
    max_count             = null
    min_count             = null
    enable_node_public_ip = false
    availability_zones    = ["1", "2", "3"]
    type                  = "VirtualMachineScaleSets"
    max_pods              = 55
  }

  // comment this lifecycle in or out to scale the default nodeset etc without killing the cluster
  lifecycle {
    ignore_changes = [
      default_node_pool
    ]
  }

  identity {
    type = "SystemAssigned"
  }

  addon_profile {
    azure_policy {
      enabled = true
    }
    http_application_routing {
      enabled = false
    }

    oms_agent {
      enabled                    = true
      log_analytics_workspace_id = azurerm_log_analytics_workspace.main[0].id
    }
  }

  role_based_access_control {
    enabled = true

    azure_active_directory {
      managed                = true
      admin_group_object_ids = [data.azuread_group.aks_cluster_admins.id]
    }
  }

  network_profile {
    network_plugin     = "azure"
    network_policy     = "azure"
    dns_service_ip     = "10.13.0.12"
    docker_bridge_cidr = "172.17.0.1/16"
    outbound_type      = "loadBalancer"
    service_cidr       = "10.13.0.0/16"
  }
}

resource "azurerm_log_analytics_workspace" "main" {
  depends_on = [
    data.azurerm_resource_group.RG
  ]
  count               = 1
  name                = "${var.prefix}-k8s-workspace"
  location            = data.azurerm_resource_group.RG.location
  resource_group_name = data.azurerm_resource_group.RG.name
  sku                 = "pergb2018"
  retention_in_days   = 30
}

resource "azurerm_log_analytics_solution" "main" {

  count                 = 1
  solution_name         = "ContainerInsights"
  location              = data.azurerm_resource_group.RG.location
  resource_group_name   = data.azurerm_resource_group.RG.name
  workspace_resource_id = azurerm_log_analytics_workspace.main[0].id
  workspace_name        = azurerm_log_analytics_workspace.main[0].name

  plan {
    publisher = "Microsoft"
    product   = "OMSGallery/ContainerInsights"
  }
}
```

### Debug Output

```bash
Plan: 1 to add, 0 to change, 0 to destroy.
azurerm_kubernetes_cluster.main: Creating...
╷
│ Error: creating Managed Kubernetes Cluster "SDCP-Staging-AKS" (Resource Group "kubernetes-prod"): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="BadRequest" Message="Feature Microsoft.ContainerService/AutoUpgradePreview is not enabled. Please see https://aka.ms/aks/previews for how to enable features."
│
│   with azurerm_kubernetes_cluster.main,
│   40: resource "azurerm_kubernetes_cluster" "main" {
│
```

### Expected Behaviour

Cluster created

### Actual Behaviour

Error above and fails

### Steps to Reproduce

1. `terraform apply`

**Comment by tombuildsstuff** [comment] 2021-10-04 06:59
hi @SimonGurney 

Thanks for opening this issue.

Taking a look through this appears to be a duplicate of #11396 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #11396 for updates?

Thanks!

**Closed by tombuildsstuff** 2021-10-04 06:59 UTC
Labels: duplicate, service/kubernetes-cluster

**Comment by wyarde** [comment] 2021-10-04 12:09
@tombuildsstuff #11396 is actually an older issue dating from April to which @DanielHajduk2-TomTom has replied mentioning this new issue. It might be better though to track the new issue separately instead of re-using #11396?

**Comment by skobzar** [comment] 2021-10-05 11:26
I have exactly same issue. 2.78 works fine. It is new bug definitely.

**Comment by tombuildsstuff** [comment] 2021-10-05 11:38
Upstream AKS issue: https://github.com/Azure/AKS/issues/2584

**Comment by nerddtvg** [comment] 2021-10-05 20:44
FYI, downgrading to `2.78.0` works to create the cluster, but it still fails to update. It looks like on a refresh of the state (`terraform plan --out=plan.out`), the property is added into the state as `unspecified`. Then the null value gets pushed to the API to try and clear it. Upgrading to `2.79.1` did not resolve this issue.

```plain
  # azurerm_kubernetes_cluster.kube will be updated in-place
  ~ resource "azurerm_kubernetes_cluster" "kube" {
      - automatic_channel_upgrade           = "unspecified" -> null
```
