### ISSUE TITLE
Support for delete NIC and data disk when VM is deleted on azurerm_linux_virtual_machine and azurerm_windows_virtual_machine

### ISSUE THREAD

**Issue by suchipalem** [hashicorp/terraform-provider-azurerm#17550] opened 2022-07-07 20:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

feature request to delete NIC and data disk when VM is deleted on azurerm_linux_virtual_machine and azurerm_windows_virtual_machine

### New or Affected Resource(s)/Data Source(s)

Support for delete NIC and data disk when VM is deleted on azurerm_linux_virtual_machine and azurerm_windows_virtual_machine

**Comment by myc2h6o** [comment] 2022-07-09 04:30
Hi @suchipalem thanks for opening the issue! Unfortunately, it is by design that `azurerm_linux_virtual_machine` or `azurerm_windows_virtual_machine` doesn't delete NIC or Data Disk on destroy. For these two virtual machine resources, their NIC and Data Disk are managed by below separate resources:
Lifecycle of NIC is managed by [azurerm_network_interface](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/network_interface) and used by [network_interface_ids](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_virtual_machine#network_interface_ids).
Lifecycle of Data Disk is managed by [azurerm_virtual_machine_data_disk_attachment](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_machine_data_disk_attachment)

**Comment by rcskosir** [comment] 2023-06-06 18:49
@suchipalem Thanks for taking the time to submit this issue. On review, we’ve determined that the described behavior is by design.
Whilst I'd like to thank you for opening this issue as we have no plans to support this functionality I'm going to close this issue for the moment.

**Closed by rcskosir** 2023-06-06 18:49 UTC
Labels: enhancement, service/virtual-machine
