### ISSUE TITLE
No Solution for Subnet creation with NSG, Organization Policy requires this.

### ISSUE THREAD

**Issue by dangerousCoderC** [hashicorp/terraform-provider-azurerm#15599] opened 2022-02-25 07:13 UTC
Hey guys,

I know this issue has been coming up A LOT, but we are wondering if there is any plan on finding a solution for this..
We need to create subnets together with the NSG Policy, Security is a MUST here, and SOC will not let us work otherwise with this.
I know that there is a workaround by creating vNets together with the subnet blocks, THAT IS NOT A SOLUTION.

How would you configure vNET integration for example, if you need service delegation to be configured (a requirement for using the swift connection resource). There is a loop of issues here, that need to be resolved, we have searched the internet with no luck in finding any "out-of-the-box" answer. Meaning that we need to go back to creating everything manually..

**Comment by tombuildsstuff** [comment] 2022-02-25 09:21
hi @dangerousCoderC 

Thanks for opening this issue.

Taking a look through this will be fixed by / is a duplicate of #9022 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #9022 for updates?

Thanks!

**Closed by tombuildsstuff** 2022-02-25 09:21 UTC

**Comment by dangerousCoderC** [comment] 2022-02-25 09:41
Thank you, I have subscribed
