### ISSUE TITLE
Need support for Enable Live tracing feature block Support for Azure SignalR service

### ISSUE THREAD

**Issue by prakash1097** [hashicorp/terraform-provider-azurerm#13551] opened 2021-09-29 12:46 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Also Need support for Enable Live tracing feature block Support for Azure SignalR service

### New or Affected Resource(s)

azurerm_signalr_service

### Potential Terraform Configuration

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/signalr_service#features

**Comment by tombuildsstuff** [comment] 2021-09-29 15:29
hi @prakash1097 

Thanks for opening this issue

Taking a look through this appears to be a duplicate of #11353 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #11353 for updates?

Thanks!

**Closed by tombuildsstuff** 2021-09-29 15:29 UTC
