### ISSUE TITLE
Support for [API Connection]

### ISSUE THREAD

**Issue by wiliambuzatto** [hashicorp/terraform-provider-azurerm#7200] opened 2020-06-03 20:57 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Would be nice to create an Api Connection using terraform.

### References

https://docs.microsoft.com/en-us/azure/templates/microsoft.web/2016-06-01/connections

**Comment by oWretch** [comment] 2021-12-13 21:06
Duplicate of #1691

**Comment by tombuildsstuff** [comment] 2021-12-15 11:52
Thanks @oWretch - duplicate of #1691

**Closed by tombuildsstuff** 2021-12-15 11:52 UTC
Labels: new-resource
