### ISSUE TITLE
Application gateway TLSv1_3 support with azurerm 3.40.0 is broken

### ISSUE THREAD

**Issue by maxburke** [hashicorp/terraform-provider-azurerm#20143] opened 2023-01-20 21:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.7

### AzureRM Provider Version

3.40.0

### Affected Resource(s)/Data Source(s)

azurerm_application_gateway

### Terraform Configuration Files

```hcl
resource "azurerm_application_gateway" "ag_centralca_stage_ulgate_v2" {
  name                = "ag_centralca_stage_ulgate_v2"
  location            = azurerm_resource_group.grp_centralca_stage_lb_ulgate.location
  resource_group_name = azurerm_resource_group.grp_centralca_stage_lb_ulgate.name

  sku {
    name     = "Standard_v2"
    tier     = "Standard_v2"
    capacity = 1
  }

  gateway_ip_configuration {
    name      = "ag_centralca_stage_ulgate_v2_gateway_ip_config"
    subnet_id = azurerm_subnet.vn_centralca_stage_subnet_appgateway_ulgate_v2.id
  }

  frontend_port {
    name = "ag_centralca_stage_ulgate_v2_frontend_port_https"
    port = "443"
  }

  frontend_port {
    name = "ag_centralca_stage_ulgate_v2_frontend_port_http"
    port = "80"
  }

  frontend_ip_configuration {
    name                 = "ag_centralca_stage_ulgate_v2_frontend_ip_config"
    public_ip_address_id = azurerm_public_ip.pi_centralca_stage_ulgate_v2.id
  }

  backend_address_pool {
    name = "ag_centralca_stage_ulgate_v2_backend_address_pool"
    ip_addresses = ["10.73.0.235"]
  }

  backend_http_settings {
    name                  = "ag_centralca_stage_ulgate_v2_backend_http_settings"
    port                  = 8079
    protocol              = "Http"
    cookie_based_affinity = "Disabled"
    request_timeout       = 900
    probe_name            = "ag_centralca_stage_ulgate_v2_probe"
  }

  backend_http_settings {
    name                  = "ag_centralca_stage_ulgate_v2_backend_insecure_http_settings"
    port                  = 8080
    protocol              = "Http"
    cookie_based_affinity = "Disabled"
    request_timeout       = 900
    probe_name            = "ag_centralca_stage_ulgate_v2_probe"
  }

  http_listener {
    name                           = "ag_centralca_stage_ulgate_v2_http_listener"
    frontend_ip_configuration_name = "ag_centralca_stage_ulgate_v2_frontend_ip_config"
    frontend_port_name             = "ag_centralca_stage_ulgate_v2_frontend_port_https"
    protocol                       = "Https"
    ssl_certificate_name           = "ssl_centralca_stage_ulgate_v2_cert"
  }

  http_listener {
    name                           = "ag_centralca_stage_ulgate_v2_insecure_http_listener"
    frontend_ip_configuration_name = "ag_centralca_stage_ulgate_v2_frontend_ip_config"
    frontend_port_name             = "ag_centralca_stage_ulgate_v2_frontend_port_http"
    protocol                       = "Http"
  }

  probe {
    name                = "ag_centralca_stage_ulgate_v2_probe"
    protocol            = "Http"
    path                = "/v1/healthcheck/"
    host                = "127.0.0.1"
    interval            = 30
    timeout             = 30
    unhealthy_threshold = 5
  }

  request_routing_rule {
    name                       = "ag_centralca_stage_ulgate_v2_request_routing_rule"
    rule_type                  = "Basic"
    http_listener_name         = "ag_centralca_stage_ulgate_v2_http_listener"
    backend_address_pool_name  = "ag_centralca_stage_ulgate_v2_backend_address_pool"
    backend_http_settings_name = "ag_centralca_stage_ulgate_v2_backend_http_settings"
    priority                   = 1
  }

  request_routing_rule {
    name                       = "ag_centralca_stage_ulgate_v2_request_routing_rule_http"
    rule_type                  = "Basic"
    http_listener_name         = "ag_centralca_stage_ulgate_v2_insecure_http_listener"
    backend_address_pool_name  = "ag_centralca_stage_ulgate_v2_backend_address_pool"
    backend_http_settings_name = "ag_centralca_stage_ulgate_v2_backend_insecure_http_settings"
    priority                   = 2
  }

  ssl_certificate {
    name     = "ssl_centralca_stage_ulgate_v2_cert"
    data     = file("stage.urbanlogiq.ca.pfx.b64")
    password = var.api_stage_urbanlogiq_ca_cert_key
  }

  ssl_policy {
    disabled_protocols   = []
    policy_type          = "CustomV2"
    min_protocol_version = "TLSv1_3"
  }

  enable_http2 = true
}
```

### Debug Output/Panic Output

```shell
https://gist.github.com/maxburke/d40ae35d9f8bdebe7e4a4cdbc98a7238
```

### Expected Behaviour

If I look at the resource in the Azure portal, the selected SSL policy should be "CustomV2" and the min protocol version should be "TLSv1_3"

I should also be able to set the cipher suites parameter to the TLSv1_3 supported cipher suites (`TLS_AES_128_GCM_SHA256` and `TLS_AES_256_GCM_SHA384`)

### Actual Behaviour

The selected SSL policy is "Predefined" (policy is "AppGwSslPolicy20150501") and the min protocol version is "TLSv1_0"

Also, if I set the cipher suites to the TLSv1_3 supported values (`TLS_AES_128_GCM_SHA256` and `TLS_AES_256_GCM_SHA384`), I receive the error message: 

```
│ Error: expected ssl_policy.0.cipher_suites.1 to be one of [TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA TLS_DHE_DSS_WITH_AES_128_CBC_SHA TLS_DHE_DSS_WITH_AES_128_CBC_SHA256 TLS_DHE_DSS_WITH_AES_256_CBC_SHA TLS_DHE_DSS_WITH_AES_256_CBC_SHA256 TLS_DHE_RSA_WITH_AES_128_CBC_SHA TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 TLS_DHE_RSA_WITH_AES_256_CBC_SHA TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 TLS_RSA_WITH_3DES_EDE_CBC_SHA TLS_RSA_WITH_AES_128_CBC_SHA TLS_RSA_WITH_AES_128_CBC_SHA256 TLS_RSA_WITH_AES_128_GCM_SHA256 TLS_RSA_WITH_AES_256_CBC_SHA TLS_RSA_WITH_AES_256_CBC_SHA256 TLS_RSA_WITH_AES_256_GCM_SHA384], got TLS_AES_256_GCM_SHA384```

### Steps to Reproduce

Run terraform apply on an application gateway resource with the following ssl policy:

```
  ssl_policy {
    disabled_protocols   = []
    policy_type          = "CustomV2"
    min_protocol_version = "TLSv1_3"
  }
```

### Important Factoids

_No response_

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/17484

**Comment by manicminer** [comment] 2023-01-30 19:59
Duplicate of #20135

**Closed by manicminer** 2023-01-30 19:59 UTC
