### ISSUE TITLE
Provider produced inconsistent final plan 

### ISSUE THREAD

**Issue by vervynckt** [hashicorp/terraform-provider-azurerm#5159] opened 2019-12-13 12:46 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.17
+ provider.azurerm v1.35.0

### Affected Resource(s)

* `azurerm_app_service`

### Terraform Configuration Files

main.tf
```hcl
module "admin" {
  source               = "./modules/azure-webapp"
  environment          = var.environment
  appname              = "admin"
  aspid                = module.asp.aspid
  ipwhitelist          = "0.0.0.0"
  mask                 = "0.0.0.0"
  generalcontainerdata = var.containerdata.general
  appcontainerdata     = var.containerdata.admin
  extrawhitelist       = var.extrawhitelist
}
module "path" {
  source               = "./modules/azure-webapp"
  environment          = var.environment
  appname              = "path"
  aspid                = module.asp.aspid
  ipwhitelist          = module.admin.outboundip
  mask                 = "255.255.255.255"
  generalcontainerdata = var.containerdata.general
  appcontainerdata     = var.containerdata.admin
  extrawhitelist       = var.extrawhitelist
}
```
modules/azure-webapp/main.tf:
```hcl
resource "azurerm_app_service" "as" {
  name                = "${var.environment}-${var.appname}-as"
  location            = var.location
  resource_group_name = azurerm_resource_group.rg.name
  app_service_plan_id = var.aspid
  https_only          = true
  app_settings = merge(var.generalcontainerdata, var.appcontainerdata)
  identity {
    type = "SystemAssigned"
  }
  logs {
    http_logs {
      file_system {
        retention_in_days = "30"
        retention_in_mb   = "32"

      }
    }
  }
  storage_account {
    name         = "${var.appname}-volume"
    type         = "AzureBlob"
    account_name = var.storageaccount_name
    share_name   = var.appname
    access_key   = var.storageaccount_key
    mount_path   = "/data/files"
  }
  site_config {
    always_on                 = true
    app_command_line          = ""
    linux_fx_version          = "DOCKER|${var.generalcontainerdata.DOCKER_REGISTRY}/${var.appcontainerdata.DOCKER_NAME}:${var.appcontainerdata.DOCKER_TAG}"
    use_32_bit_worker_process = true
    
      dynamic "ip_restriction" {
        for_each = split(",", join(",",[var.ipwhitelist],[var.extrawhitelist]))
       content {
          ip_address  = ip_restriction.value
          subnet_mask = var.mask
        }
  }
}
}
output "outboundip" {
  value = azurerm_app_service.as.possible_outbound_ip_addresses
}

```

### Debug Output
```
Error: Provider produced inconsistent final plan

When expanding the plan for module.path.azurerm_app_service.as to include new
values learned so far during apply, provider "azurerm" produced an invalid new
value for .site_config[0].ip_restriction: new element 1 has appeared.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.


Error: Provider produced inconsistent final plan

When expanding the plan for module.path.azurerm_app_service.as to include new
values learned so far during apply, provider "azurerm" produced an invalid new
value for .site_config[0].ip_restriction: new element 2 has appeared.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.


Error: Provider produced inconsistent final plan

When expanding the plan for module.path.azurerm_app_service.as to include new
values learned so far during apply, provider "azurerm" produced an invalid new
value for .site_config[0].ip_restriction: new element 3 has appeared.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.


Error: Provider produced inconsistent final plan

When expanding the plan for module.path.azurerm_app_service.as to include new
values learned so far during apply, provider "azurerm" produced an invalid new
value for .site_config[0].ip_restriction: new element 4 has appeared.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

### Expected Behavior
There are 4 app services that are deployed with the same module. The first app service outputs his 'possible_outbound_ip_addresses' tot the 3 other app services to be white-listed.
Loop through the list of ip's and white-list them on the app service.

### Actual Behavior

'var.extrawhitelist' ip's are white-listed on the app-service but the output(possible_outbound_ip_addresses) ip's are not added.
After I do a second `terraform apply` all ip's are correctly white-listed.
### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by ie-zero** [comment] 2020-05-16 18:39
I received the same error message using 

Terraform v0.12.24
+ provider.azurerm v2.10.0

**Comment by ie-zero** [comment] 2020-05-16 18:45
I noticed that when I supply a plan i.e.  `terraform apply .\tf.plan` it always fails and I cannot recover from it.

If instead I use `terraform apply` it will still fail but I can re-run `terraform apply` and it will succeed. This obviously is a sub-optimal solution but it might help someone else who is stuck because of this issue.

**Comment by thecodetinker** [comment] 2020-09-09 14:52
Hello dev team - I am having this exact issue. Given all the great work that has been going on I was hoping it might have got resolved with the latest versions. However I've just checked with Terraform 0.13 and azure_rm 2.25.0 but sadly still getting the inconsistent final plan error. Is there a possible plan to fix it, or a workaround? Thanks!

**Comment by favoretti** [comment] 2021-08-19 07:26
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.

**Closed by favoretti** 2021-08-19 07:26 UTC
Labels: bug, upstream-terraform, service/app-service

**Comment by BJSS-Brian** [comment] 2021-09-03 08:29
> Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.

Where is the new ticket? We still have this issue.

**Comment by favoretti** [comment] 2021-09-03 10:32
@BJSS-Brian Would you mind opening a new one with updated output/reproduction scenario/config please? Thank you!
