### ISSUE TITLE
Application Gateway Bug request routing rule always recreated

### ISSUE THREAD

**Issue by faisaleem-na** [hashicorp/terraform-provider-azurerm#18422] opened 2022-09-17 12:44 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.14.7

### AzureRM Provider Version

3.12.0

### Affected Resource(s)/Data Source(s)

azurerm_application_gateway

### Terraform Configuration Files

```hcl
dynamic "request_routing_rule" {
    for_each = var.gateway[each.key].request_routing_rule
    content {
      name                       = "${lookup(request_routing_rule.value, "name", null)}-rqrt"
      rule_type                  = lookup(request_routing_rule.value, "rule_type", null)
      priority                   = lookup(request_routing_rule.value, "priority", 1)
      http_listener_name         = lookup(request_routing_rule.value, "lsnrname", null) != null ? "${lookup(request_routing_rule.value, "lsnrname")}-httplstn" : "${lookup(request_routing_rule.value, "name", null)}-httplstn"
      backend_address_pool_name  = lookup(request_routing_rule.value, "beapname", null) != null ? "${lookup(request_routing_rule.value, "beapname")}-beap" : null
      backend_http_settings_name = lookup(request_routing_rule.value, "behtstname", null) != null ? "${lookup(request_routing_rule.value, "behtstname")}-be-htst" : lookup(request_routing_rule.value, "rdrcfgname", null) != null ? null : lookup(request_routing_rule.value, "rule_type") == "Basic" ? "${lookup(request_routing_rule.value, "name", null)}-be-htst" : null
      redirect_configuration_name= lookup(request_routing_rule.value, "rdrcfgname", null) != null ? "${lookup(request_routing_rule.value, "rdrcfgname", null)}-rdrcfg" : null
      rewrite_rule_set_name      = lookup(request_routing_rule.value, "rwrstname", null) != null ? "${lookup(request_routing_rule.value, "rwrstname", null)}-rwrst" : null
      url_path_map_name          = lookup(request_routing_rule.value, "rule_type") == "PathBasedRouting" ? lookup(request_routing_rule.value, "url_path_map_name") : null
    }
  }
```

### Debug Output/Panic Output

```shell
gist coming soon
```

### Expected Behaviour

no configuration changes required

### Actual Behaviour

https://gist.github.com/faisaleem-na/377f850bf238482bf6dde88be9cc417b

### Steps to Reproduce

terraform plan

**Comment by ms-zhenhua** [comment] 2022-09-20 06:51
Hi @faisaleem-na, thank you for reaching out. 
It is a little difficult to confirm this issue through the configuration snippet you provided. Could you kindly help provide a runnable configuration (You can first remove all sensitive information from it) for this issue ? Then we can do more investigation on it. 
You can compress all the configuration files into a .zip file and attach it in this GH issue.
Thanks.

**Comment by faisaleem-na** [comment] 2022-09-20 09:30
Hi @ms-zhenhua,

ok no problem, i will do that, will just need a day or so as currently quite busy. will aim to have it here by COB thursday
thanks

**Comment by rolandjohann** [comment] 2022-11-08 15:54
Seems to hit this bug #16136

**Comment by faisaleem-na** [comment] 2022-11-08 16:55
> Seems to hit this bug #16136

yep spot on, should have known it was already reported but this is the exact issue. bit concerned that the fix is way off though :(

**Comment by rcskosir** [comment] 2023-06-02 16:45
@faisaleem-na Thanks for taking the time to submit this issue. It looks like this is a duplicate of #16136. We like to try to keep discussions consolidated, so we’re going to close this newer issue in favor of #16136.

**Closed by rcskosir** 2023-06-02 16:45 UTC
Labels: duplicate, service/application-gateway
