### ISSUE TITLE
azurerm_key_vault: keyvault.BaseClient#GetCertificateContacts: Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded

### ISSUE THREAD

**Issue by rhysduck** [hashicorp/terraform-provider-azurerm#23907] opened 2023-11-15 12:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.3

### AzureRM Provider Version

3.80.0

### Affected Resource(s)/Data Source(s)

azurerm_key_vault

### Terraform Configuration Files

```hcl
# this is the current config for azure access
# we use this to access tenant id, subs id etc.
data "azurerm_client_config" "current_arm_config" {}

# resource "random_string" "log_analytics_suffix" {
#   length      = 4
#   special     = false
#   upper       = false
# }

resource "azurerm_key_vault" "key_vault" {
  name                              = var.key_vault_name
  location                          = var.azure_region
  resource_group_name               = var.resource_group_name
  tenant_id                         = data.azurerm_client_config.current_arm_config.tenant_id
  sku_name                          = "standard"
  tags                              = var.tags

  enabled_for_deployment            = "true"
  enabled_for_disk_encryption       = "false"
  enabled_for_template_deployment   = "true"

  soft_delete_retention_days        = var.key_vault_soft_delete_retention_days

  network_acls {
    default_action                  = "Deny"
    # if using private endpoints, we don't want other azure services to access our key vault
    bypass                          = var.private_endpoints_flag ? "AzureServices" : "AzureServices"
    ip_rules                        = [for ip in var.key_vault_ip_whitelist : ip]
    #virtual_network_subnet_ids      = [for subnet_key, subnet_id in var.key_vault_virtual_network_subnet_ids : subnet_id]
    virtual_network_subnet_ids      = toset(concat([for subnet_key, subnet_id in var.key_vault_virtual_network_subnet_ids : subnet_id], ["/subscriptions/subID/resourceGroups/rgName/providers/Microsoft.Network/virtualNetworks/vnet/subnets/snet"]))

  }

  lifecycle {
    ignore_changes = [
      contact,
      tags
    ]

  } 
}

resource "azurerm_private_endpoint" "key_vault_endpoint" {
  count                             = var.private_endpoints_flag ? 1 : 0
  name                              = var.key_vault_pe_name
  location                          = var.azure_region
  resource_group_name               = var.resource_group_name
  tags                              = var.tags
  subnet_id                         = var.key_vault_pe_subnet_id

  private_service_connection {
    name                            = var.key_vault_pe_link_name
    private_connection_resource_id  = azurerm_key_vault.key_vault.id
    subresource_names               = ["vault"]
    is_manual_connection            = false
  }

  lifecycle {
    ignore_changes = [
      tags
    ]
  } 

  depends_on                        = [azurerm_key_vault.key_vault]
}


resource "azurerm_key_vault_access_policy" "terraform_sp_kv_policy" {
  key_vault_id                      = azurerm_key_vault.key_vault.id
  tenant_id                         = data.azurerm_client_config.current_arm_config.tenant_id
  object_id                         = data.azurerm_client_config.current_arm_config.object_id
  secret_permissions                = ["Set", "Get", "List", "Delete", "Recover", "Backup", "Restore"]
  key_permissions                   = ["Create", "Get", "Decrypt", "Encrypt", "Sign", "UnwrapKey", "Verify", "WrapKey", "Delete"]
  certificate_permissions           = ["Create", "Get", "List", "Update", "Delete"]
  depends_on                        = [azurerm_key_vault.key_vault]
}

resource "azurerm_monitor_diagnostic_setting" "key_vault_monitor" {
  name                              = "${var.key_vault_name}-logging" #-${random_string.log_analytics_suffix.result}
  target_resource_id                = azurerm_key_vault.key_vault.id
  log_analytics_workspace_id        = var.log_analytics_id
  storage_account_id                = var.logging_storage_account_id

  dynamic "enabled_log" {
    for_each                        = ["AuditEvent", "AzurePolicyEvaluationDetails"]
    content {
      category = enabled_log.value

      retention_policy {
        enabled = true
        days    = 0
      }
    }
  }

  dynamic "metric" {
    for_each                        = ["AllMetrics"]
    content {
      category = metric.value

      retention_policy {
        enabled = true
        days    = 0
      }
    }
  }
  depends_on                        = [azurerm_key_vault.key_vault]
}
```

### Debug Output/Panic Output

```shell
2023-11-15T11:24:22.4408465Z 2023-11-15T11:24:22.438Z [ERROR] provider.terraform-provider-azurerm_v3.80.0_x5.exe: Response contains error diagnostic: @caller=github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/diag/diagnostics.go:58 diagnostic_summary="retrieving `contact` for KeyVault: keyvault.BaseClient#GetCertificateContacts: Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded" tf_resource_type=azurerm_key_vault tf_provider_addr=provider tf_req_id=baac4de5-f784-b998-c4c3-6a80ef35bf3c tf_rpc=ReadResource diagnostic_detail="" diagnostic_severity=ERROR tf_proto_version=5.4 @module=sdk.proto timestamp=2023-11-15T11:24:22.438Z
2023-11-15T11:24:22.4421919Z 2023-11-15T11:24:22.439Z [ERROR] vertex "module.keyvault.azurerm_key_vault.key_vault" error: retrieving `contact` for KeyVault: keyvault.BaseClient#GetCertificateContacts: Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded
2023-11-15T11:24:22.4430782Z 2023-11-15T11:24:22.439Z [ERROR] vertex "module.keyvault.azurerm_key_vault.key_vault (expand)" error: retrieving `contact` for KeyVault: keyvault.BaseClient#GetCertificateContacts: Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded
2023-11-15T11:24:22.4437094Z 2023-11-15T11:24:22.439Z [DEBUG] created provider logger: level=debug
```

### Expected Behaviour

The full infrastructure deployment should execute successfully on the first attempt.
Incremental changes to the environment should also complete successfully when the pipeline is run subsequently.

### Actual Behaviour

Currently, Terraform does not progress beyond the planning stage.

##[error]Terraform command 'plan' failed with exit code '1'.:  retrieving `contact` for KeyVault: keyvault.BaseClient#GetCertificateContacts: Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded

Services allowed on the subnet.
Microsoft.Storage
Microsoft.KeyVault
Microsoft.EventHub

### Steps to Reproduce

terraform plan

### Important Factoids

Running in UK. Resources have Private endpoints with DNS servers on the VNet rather than private DNS zones. Running from Self-Hosted Agent. 

### References

#17863 - Similar issue but NSG solution did not fix the issue
#16052 - Closed with no clear resolution
#9738 - Open since 2020 with no resolution.

**Comment by rhysduck** [comment] 2023-11-16 14:39
Hello, yes that is correct.

**Comment by rhysduck** [comment] 2023-11-17 09:43
Hi @wuxu92 

Unfortunately #10501 has no meaningful resolution and it was closed linking to #9738 that's been open without an answer since 2020 I've checked everything I can from my side. I need a bit of expert help to understand whats happening and if there is a workaround.

Thanks, 

Rhys

**Comment by nealrowan** [comment] 2023-11-19 22:13
> Hi @wuxu92
> 
> Unfortunately #10501 has no meaningful resolution and it was closed linking to #9738 that's been open without an answer since 2020 I've checked everything I can from my side. I need a bit of expert help to understand whats happening and if there is a workaround.
> 
> Thanks,
> 
> Rhys

It seems to known issue which no one seams to want to fix.
I have spend time trying different methods which I found which said worked for them but not for me,  but as someone mention in https://github.com/hashicorp/terraform-provider-azurerm/issues/9738
I resorted to going down point of using azapi_resource over azurerm_key_vault due to this issue, being a show stopper for us, and our requirement of needing private endpoint usage 

resource "azapi_resource" "vault" {
  type      = "Microsoft.KeyVault/vaults@2022-07-01"
  parent_id = data.azurerm_resource_group.this.id
  name      = var.name
  location  = var.location
  tags      = var.tags
  body = jsonencode({
    properties = {
      
      enableRbacAuthorization      = var.enable_rbac_authorization
      enablePurgeProtection        = var.purge_protection_enabled
      enableSoftDelete             = var.enable_soft_delete
      enabledForDeployment         = false
      enabledForDiskEncryption     = false
      enabledForTemplateDeployment = false
      publicNetworkAccess          = var.public_network_access
      sku = {
        family = "A"
        name   = var.sku_name
      }
      softDeleteRetentionInDays = var.soft_delete_retention_days
      tenantId                  =  data.azurerm_client_config.current.tenant_id
      networkAcls: {
        bypass = var.network_rules_bypass
        defaultAction = var.network_rules_action
        virtualNetworkRules = var.virtualNetworkRules   
        ipRules  = var.ipRules
      }
    }
  })
}

#require for azapi output 
data "azurerm_key_vault" "this" {
  depends_on = [ 
    azapi_resource.vault
  ]
  name                = var.name
  resource_group_name = var.resource_group_name
}

**Comment by rhysduck** [comment] 2023-11-20 16:22
Thanks both for your replies and thanks @nealrowan  I think I'll have to give your method a go. Its a shame no fix is available thus far.

**Comment by rcskosir** [comment] 2023-11-30 21:50
Thanks for taking the time to submit this issue. It looks like this is a duplicate of #9738. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of #9738. I hope that methods above are able to help you while #9738 remains open.

**Closed by rcskosir** 2023-11-30 21:50 UTC
Labels: duplicate, service/key-vault, v/3.x
