### ISSUE TITLE
Azurerm subnet address_prefix change does not happen correctly - deployment fails

### ISSUE THREAD

**Issue by Ivasan7** [hashicorp/terraform-provider-azurerm#5498] opened 2020-01-23 14:13 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.19
+ provider.azurerm v1.41.0
+ provider.random v2.2.1
```

### Affected Resource(s)

* `azurerm_virtual_network`
* `azurerm_subnet`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "general-rg" {
  location = var.azure-region
  name     = "${var.cust}-${var.app-name}-${var.environment}-rg"
  tags = var.default_tags
}

resource "azurerm_virtual_network" "workspace" {
  name                = "${var.app-name}-${var.environment}-vnet"
  location            = azurerm_resource_group.general-rg.location
  resource_group_name = azurerm_resource_group.general-rg.name
  address_space       = ["10.${var.addr-space}.0.0/16"]
  count               = var.workspace_var

  tags =  var.default_tags
}

resource "azurerm_subnet" "workspace_default_subnet" {
  name                  = "${var.app-name}-${var.environment}-default-subnet"
  resource_group_name   = azurerm_resource_group.general-rg.name
  virtual_network_name  = azurerm_virtual_network.workspace[count.index].name
  address_prefix        = "10.${var.addr-space}.0.0/24"
  count                 = var.workspace_var
}

resource "azurerm_subnet" "workspace_workload_subnet" {
  name                  = "${var.app-name}-${var.environment}-workload-subnet"
  resource_group_name   = azurerm_resource_group.general-rg.name
  virtual_network_name  = azurerm_virtual_network.workspace[count.index].name
  address_prefix        = "10.${var.addr-space}.1.0/24"
  count                 = var.workspace_var

```

### Expected Behavior

The CIDR ranges for VNET and SUBNETS are changed.

### Actual Behavior
Terraform plan out put
```hcl
  # module.workspace-general.azurerm_subnet.workspace_default_subnet[0] will be updated in-place
  ~ resource "azurerm_subnet" "workspace_default_subnet" {
      ~ address_prefix                                = "10.12.0.0/24" -> "10.15.0.0/24"
        enforce_private_link_service_network_policies = false
        id                                            = "/subscriptions/subscrpID/resourceGroups/pbl-EU-EMS-d-rg/providers/Microsoft.Network/virtualNetworks/EU-EMS-d-vnet/subnets/EU-EMS-d-default-subnet"
        ip_configurations                             = []
        name                                          = "EU-EMS-d-default-subnet"
        resource_group_name                           = "pbl-EU-EMS-d-rg"
        service_endpoints                             = []
        virtual_network_name                          = "EU-EMS-d-vnet"
    }

  # module.workspace-general.azurerm_subnet.workspace_workload_subnet[0] will be updated in-place
  ~ resource "azurerm_subnet" "workspace_workload_subnet" {
      ~ address_prefix                                = "10.12.1.0/24" -> "10.15.1.0/24"
        enforce_private_link_service_network_policies = false
        id                                            = "/subscriptions/subscrpID/resourceGroups/pbl-EU-EMS-d-rg/providers/Microsoft.Network/virtualNetworks/EU-EMS-d-vnet/subnets/EU-EMS-d-workload-subnet"
        ip_configurations                             = [
            "/subscriptions/subscrpID/resourceGroups/pbl-EU-EMS-d-rg/providers/Microsoft.Network/networkInterfaces/EU-EMS-d-nic/ipConfigurations/pbl-windowsgeneral-nic",
        ]
        name                                          = "EU-EMS-d-workload-subnet"
        resource_group_name                           = "pbl-EU-EMS-d-rg"
        service_endpoints                             = []
        virtual_network_name                          = "EU-EMS-d-vnet"
    }

  # module.workspace-general.azurerm_virtual_network.workspace[0] will be updated in-place
  ~ resource "azurerm_virtual_network" "workspace" {
      ~ address_space       = [
          - "10.12.0.0/16",
          + "10.15.0.0/16",
        ]
        dns_servers         = []
        id                  = "/subscriptions/subscrpID/resourceGroups/pbl-EU-EMS-d-rg/providers/Microsoft.Network/virtualNetworks/EU-EMS-d-vnet"
        location            = "westeurope"
        name                = "EU-EMS-d-vnet"
        resource_group_name = "pbl-EU-EMS-d-rg"
        tags                = {
            "ApplicationManager" = "PBL"
            "Environment"        = "Development"
            "Owner"              = "Name Name"
            "Project"            = "EU-EMS"
        }

        subnet {
            address_prefix = "10.12.0.0/24"
            id             = "/subscriptions/subscrpID/resourceGroups/pbl-EU-EMS-d-rg/providers/Microsoft.Network/virtualNetworks/EU-EMS-d-vnet/subnets/EU-EMS-d-default-subnet"
            name           = "EU-EMS-d-default-subnet"
        }
        subnet {
            address_prefix = "10.12.1.0/24"
            id             = "/subscriptions/subscrpID/resourceGroups/pbl-EU-EMS-d-rg/providers/Microsoft.Network/virtualNetworks/EU-EMS-d-vnet/subnets/EU-EMS-d-workload-subnet"
            name           = "EU-EMS-d-workload-subnet"
        }
    }

```
It show that at the separate resource 
`module.workspace-general.azurerm_subnet.workspace_workload_subnet[0]` correctly applies the change with id:
```
"/subscriptions/subscrpID/resourceGroups/pbl-EU-EMS-d-rg/providers/Microsoft.Network/virtualNetworks/EU-EMS-d-vnet/subnets/EU-EMS-d-workload-subnet"
```
but if you check under the vnet you would see this:
```
subnet {
            address_prefix = "10.12.1.0/24"
            id             = "/subscriptions/subscrpID/resourceGroups/pbl-EU-EMS-d-rg/providers/Microsoft.Network/virtualNetworks/EU-EMS-d-vnet/subnets/EU-EMS-d-workload-subnet"
```
Subsequently apply fails
### Steps to Reproduce

1. `terraform plan` -> problem shows
2. `terraform apply` -> Failure

**Comment by magodo** [comment] 2020-10-28 03:02
@Ivasan7 Thank you for submitting this!

Would you please provide the complete terraform config to help me reproduce it on my side? Especially how the variables are defined.

**Comment by Ivasan7** [comment] 2020-10-28 08:08
@magodo I am not working on this project any more for a while, but the variables are just string:
in the var.tf
```hcl

provider "azurerm" {
  version = "1.41"
}

module "workspace-general" {
  source = "/general"

cust = "pbl"
azure-region = "westeurope"
environment="production"
addr-space=12 -> 15

```

Don't think you need more to reproduce it, all the other variables which were used are project related and can be omitted. Like tags etc ...

**Comment by magodo** [comment] 2020-10-28 08:16
I realized that this update/apply should fail as is reported in #5235. For that issue, I have submit a PR #9049 trying to fix it.

**Comment by Ivasan7** [comment] 2020-10-28 08:46
@magodo cool , if that is fixed let me know, we can re-test this and close.

**Comment by favoretti** [comment] 2021-08-19 07:55
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.

**Closed by favoretti** 2021-08-19 07:55 UTC
Labels: bug, service/subnets, service/virtual-networks
