### ISSUE TITLE
Rulestack commit happens for every rule

### ISSUE THREAD

**Issue by shankar-bala** [hashicorp/terraform-provider-azurerm#23471] opened 2023-10-06 22:44 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

v1.3.7

### AzureRM Provider Version

3.69.0

### Affected Resource(s)/Data Source(s)

azurerm_palo_alto_local_rulestack_rule

### Terraform Configuration Files

```hcl
# create resource group
resource azurerm_resource_group "rg" {
    name = "rg-${var.resource_suffix}"
    location = var.location
    tags = var.tags
} 

# create vnet/subnets

resource "azurerm_virtual_network" "vnet" {
  name                = "vnet-fw-${var.resource_suffix}"
  address_space       = [var.vnet_cidr]
  location            = var.location

  resource_group_name = azurerm_resource_group.rg.name

  tags = {
    Purpose = "terraform testing"
  }
}

# create localrulestack
resource azurerm_palo_alto_local_rulestack "lrs1" {
    name = "lrs-${var.resource_suffix}-1"
    resource_group_name = azurerm_resource_group.rg.name
    location = var.location
    description = "rulestack1"
}

resource azurerm_palo_alto_local_rulestack "lrs2" {
    name = "lrs-${var.resource_suffix}-2"
    resource_group_name = azurerm_resource_group.rg.name
    location = var.location
    description = "rulestack2"
}

# create prefix list
resource "azurerm_palo_alto_local_rulestack_prefix_list" "prefix" {
  name         = "prefix-${var.resource_suffix}"
  prefix_list  = [ "10.0.2.0/26" ]
  rulestack_id = azurerm_palo_alto_local_rulestack.lrs1.id
  description = "prefixlist1"

  depends_on = [ azurerm_palo_alto_local_rulestack.lrs1 ]
}

# create fqdn list
resource azurerm_palo_alto_local_rulestack_fqdn_list "fqdn" {
  name = "fqdn-${var.resource_suffix}"
  rulestack_id = azurerm_palo_alto_local_rulestack.lrs1.id
  fully_qualified_domain_names = ["www.defnews.com"]
  depends_on = [ azurerm_palo_alto_local_rulestack.lrs1 ]
}

# create certificate (self signed)
resource "azurerm_palo_alto_local_rulestack_certificate" "cert" {
  name         = "cert-${var.resource_suffix}"
  rulestack_id = azurerm_palo_alto_local_rulestack.lrs1.id
  self_signed = true
  # key_vault_certificate_id  = "https://kvtesting456.vault.azure.net/certificates/kvtesting"
  depends_on = [ azurerm_palo_alto_local_rulestack.lrs1 ]
}

# creare local rulestack rule
resource "azurerm_palo_alto_local_rulestack_rule" "localrule" {
  name          = "rule-${var.resource_suffix}"
  rulestack_id = azurerm_palo_alto_local_rulestack.lrs1.id
  priority      = 1000
  
  applications  = ["any"]

  source {
    cidrs = ["192.168.16.0/24"]
  }
  destination {
    cidrs = ["192.168.16.0/24"]
  }
  action = "Allow"

  depends_on = [ azurerm_palo_alto_local_rulestack.lrs1 ]
  tags = var.tags
}

# create localrulestack rule2
resource "azurerm_palo_alto_local_rulestack_rule" "localrule2" {
  name          = "rule2-${var.resource_suffix}"
  rulestack_id = azurerm_palo_alto_local_rulestack.lrs1.id
  priority      = 1001
  
  applications  = ["any"]

  source {
    cidrs = ["192.168.16.0/25"]
  }
  destination {
    cidrs = ["192.168.16.0/25"]
  }
  action = "Allow"

  depends_on = [ azurerm_palo_alto_local_rulestack.lrs1 ]
  tags = var.tags
}

resource "azurerm_palo_alto_local_rulestack_rule" "localrule3" {
  name          = "rule3-${var.resource_suffix}"
  rulestack_id = azurerm_palo_alto_local_rulestack.lrs1.id
  priority      = 1002
  
  applications  = ["any"]

  source {
    cidrs = ["192.168.16.0/25"]
  }
  destination {
    cidrs = ["192.168.16.0/25"]
  }
  action = "Allow"

  depends_on = [ azurerm_palo_alto_local_rulestack.lrs1 ]
  tags = var.tags
}

resource "azurerm_palo_alto_local_rulestack_rule" "localrule5" {
  name          = "rule5-${var.resource_suffix}"
  rulestack_id = azurerm_palo_alto_local_rulestack.lrs1.id
  priority      = 1003
  
  applications  = ["any"]

  source {
    cidrs = ["192.168.16.0/25"]
  }
  destination {
    cidrs = ["192.168.16.0/25"]
  }
  action = "Allow"

  depends_on = [ azurerm_palo_alto_local_rulestack.lrs1 ]
  tags = var.tags
}

resource "azurerm_palo_alto_local_rulestack_rule" "localrule4" {
  name          = "rule4-${var.resource_suffix}"
  rulestack_id = azurerm_palo_alto_local_rulestack.lrs1.id
  priority      = 1004
  
  applications  = ["any"]

  source {
    cidrs = ["192.168.16.0/25"]
  }
  destination {
    cidrs = ["192.168.16.0/25"]
  }
  action = "Allow"

  depends_on = [ azurerm_palo_alto_local_rulestack.lrs1 ]
  tags = var.tags
}
```

### Debug Output/Panic Output

```shell
azurerm_palo_alto_local_rulestack_rule.localrule3: Still creating... [2m10s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule5: Creation complete after 2m11s [id=/subscriptions/5b06bdb3-3a0c-4c26-a14d-7a5322b21f07/resourceGroups/rg-tfTest01/providers/PaloAltoNetworks.Cloudngfw/localRulestacks/lrs-tfTest01-1/localRules/1003]
azurerm_palo_alto_local_rulestack_rule.localrule4: Still creating... [2m20s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule3: Still creating... [2m20s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule4: Still creating... [2m30s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule3: Still creating... [2m30s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule3: Still creating... [2m40s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule4: Still creating... [2m40s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule3: Still creating... [2m50s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule4: Still creating... [2m50s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule4: Still creating... [3m0s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule3: Still creating... [3m0s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule4: Still creating... [3m10s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule3: Still creating... [3m10s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule4: Still creating... [3m20s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule3: Still creating... [3m20s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule4: Still creating... [3m30s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule3: Still creating... [3m30s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule3: Still creating... [3m40s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule4: Still creating... [3m40s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule4: Still creating... [3m50s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule3: Still creating... [3m50s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule3: Still creating... [4m0s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule4: Still creating... [4m0s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule3: Still creating... [4m10s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule4: Still creating... [4m10s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule3: Creation complete after 4m10s [id=/subscriptions/5b06bdb3-3a0c-4c26-a14d-7a5322b21f07/resourceGroups/rg-tfTest01/providers/PaloAltoNetworks.Cloudngfw/localRulestacks/lrs-tfTest01-1/localRules/1002]
azurerm_palo_alto_local_rulestack_rule.localrule4: Still creating... [4m20s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule4: Still creating... [4m30s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule4: Still creating... [4m40s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule4: Still creating... [4m50s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule4: Still creating... [5m0s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule4: Still creating... [5m10s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule4: Still creating... [5m20s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule4: Still creating... [5m30s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule4: Still creating... [5m40s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule4: Still creating... [5m50s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule4: Still creating... [6m0s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule4: Creation complete after 6m8s [id=/subscriptions/5b06bdb3-3a0c-4c26-a14d-7a5322b21f07/resourceGroups/rg-tfTest01/providers/PaloAltoNetworks.Cloudngfw/localRulestacks/lrs-tfTest01-1/localRules/1004]
```

### Expected Behaviour

We would like to perform rulestack commit once after all the rules are created. Instead we are noticing commit happening for every rule which is not correct.

### Actual Behaviour

Perform final rulestack commit only once after all other rulestack related operations are done.

### Steps to Reproduce

1. Set the environment variables to communicate with azure cloud.
2. Run terraform apply.
3. Add more rules., you should see rulestack commit happening for every rule.

**Comment by neil-yechenwei** [comment] 2023-10-08 04:40
Thanks for raising this issue. I assume it's by TF design and I didn't find any API that accepts a list of rules.

**Comment by jackofallops** [comment] 2023-10-09 12:15
Hi @shankar-bala - Thanks for this issue. Unfortunately this commit needs to happen every time we modify a rulestack as Terraform cannot know when the last operation is completed due to the parallel nature of terraform.

Since this is the intended behaviour, I'm going to close this for now.

**Closed by jackofallops** 2023-10-09 12:15 UTC
Labels: v/3.x, service/paloalto
