### ISSUE TITLE
Issue with CMK while creating log analytics cluster through azurerm_log_analytics_cluster_customer_managed_key 

### ISSUE THREAD

**Issue by niks-singh** [hashicorp/terraform-provider-azurerm#17933] opened 2022-08-09 08:37 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

We are trying to deploy the log analytics cluster with CMK using terraform ( [https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/log_analytics_cluster_customer_managed_key](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fregistry.terraform.io%2Fproviders%2Fhashicorp%2Fazurerm%2Flatest%2Fdocs%2Fresources%2Flog_analytics_cluster_customer_managed_key&data=05%7C01%7CNikhil.Singh%40microsoft.com%7Cf1f31044e9b348859e4c08da7523e77b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637951094390382349%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=bZHmjoB0xhFgjg%2BiNe%2FG7eBtOzaDWe0OB%2F1xecEjX%2BE%3D&reserved=0)). We are seeing a strange behaviour after running the module
 
1.	While applying CMK encryption , the module gets below error with statusCode=202.
 
Error: updating Customer Managed Key for Log Analytics Cluster: (Cluster Name "log-cls-ncus-dev-cluster-msft-01" / Resource Group "rg-ncus-dev-cluster-msft-01-68"): operationalinsights.ClustersClient#Update: Failure responding to request: StatusCode=202 -- Original Error: autorest/azure: error response cannot be parsed: {"" '\x00' '\x00'} error: EOF
│
│   with module.wf_test_law_cluster.azurerm_log_analytics_cluster_customer_managed_key.this,
│   on ..\..\terraform-azurerm-wf-log-analytics-cluster\main.tf line 122, in resource "azurerm_log_analytics_cluster_customer_managed_key" "this":
│  122: resource "azurerm_log_analytics_cluster_customer_managed_key" "this"

### Terraform Version

1.2.6

### AzureRM Provider Version

3.1.17

### Affected Resource(s)/Data Source(s)

azurerm_log_analytics_cluster_customer_managed_key

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

data "azurerm_client_config" "current" {
}

resource "azurerm_log_analytics_cluster" "example" {
  name                = "example-cluster"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  identity {
    type = "SystemAssigned"
  }
}

resource "azurerm_key_vault" "example" {
  name                = "keyvaultkeyexample"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  tenant_id           = data.azurerm_client_config.current.tenant_id

  sku_name = "premium"

  access_policy {
    tenant_id = data.azurerm_client_config.current.tenant_id
    object_id = data.azurerm_client_config.current.object_id

    key_permissions = [
      "Create",
      "Get",
    ]

    secret_permissions = [
      "Set",
    ]
  }

  tags = {
    environment = "Production"
  }

  access_policy {
    tenant_id = azurerm_log_analytics_cluster.example.identity.0.tenant_id
    object_id = azurerm_log_analytics_cluster.example.identity.0.principal_id

    key_permissions = [
      "Get",
      "Unwrapkey",
      "Wrapkey",
    ]
  }

}

resource "azurerm_key_vault_key" "example" {
  name         = "generated-certificate"
  key_vault_id = azurerm_key_vault.example.id
  key_type     = "RSA"
  key_size     = 2048

  key_opts = [
    "decrypt",
    "encrypt",
    "sign",
    "unwrapKey",
    "verify",
    "wrapKey",
  ]
}

resource "azurerm_log_analytics_cluster_customer_managed_key" "example" {
  log_analytics_cluster_id = azurerm_log_analytics_cluster.example.id
  key_vault_key_id         = azurerm_key_vault_key.example.id
}
```

### Debug Output/Panic Output

```shell
Error: updating Customer Managed Key for Log Analytics Cluster: (Cluster Name "log-cls-ncus-dev-cluster-msft-01" / Resource Group "rg-ncus-dev-cluster-msft-01-68"): operationalinsights.ClustersClient#Update: Failure responding to request: StatusCode=202 -- Original Error: autorest/azure: error response cannot be parsed: {"" '\x00' '\x00'} error: EOF
│
│   with module.wf_test_law_cluster.azurerm_log_analytics_cluster_customer_managed_key.this,
│   on ..\..\terraform-azurerm-wf-log-analytics-cluster\main.tf line 122, in resource "azurerm_log_analytics_cluster_customer_managed_key" "this":
│  122: resource "azurerm_log_analytics_cluster_customer_managed_key" "this"
```

### Expected Behaviour

It should be succeeded without error.

### Actual Behaviour

Error

### Steps to Reproduce

terraform apply

### Important Factoids

no

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/log_analytics_cluster_customer_managed_key

**Comment by WodansSon** [comment] 2022-08-25 08:10
This appears to be a service issue, as the error is being raised by autorest and bubbled up through Terraform...
```
autorest/azure: error response cannot be parsed: {"" '\x00' '\x00'}
```

**Comment by WodansSon** [comment] 2022-08-29 20:46
@niks-singh, after debugging this issue this is indeed a service issue with the swagger and is currently being fix. The observed behavior is by design and is working as it was intended to do. I am going to go ahead and close this issue since this isn't actually a Terraform issue. Thank you for opening this and helping us get to the bottom of the problem. 🚀

**Closed by WodansSon** 2022-08-29 20:46 UTC
Labels: service/log-analytics
