### ISSUE TITLE
azurerm_site_recovery_replication_recovery_plan resorts recovery_groups on every run although there are no changes

### ISSUE THREAD

**Issue by viewegchris** [hashicorp/terraform-provider-azurerm#22258] opened 2023-06-23 09:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.4

### AzureRM Provider Version

3.62.0

### Affected Resource(s)/Data Source(s)

azurerm_site_recovery_replication_recovery_plan 

### Terraform Configuration Files

```hcl
resource "azurerm_site_recovery_replication_recovery_plan" "recovery_plan" {
  name                      = "example-recovery-plan"
  recovery_vault_id         = data.azurerm_recovery_services_vault.asr-vault.id
  source_recovery_fabric_id = data.azurerm_site_recovery_fabric.asr-recovery-fabric.id
  target_recovery_fabric_id = data.azurerm_site_recovery_fabric.asr-recovery-fabric.id

  recovery_group {
    type                       = "Shutdown"
    replicated_protected_items = local.all_replication_protected_items

    pre_action {
      name            = "some-pre-action"
      type            = "AutomationRunbookActionDetails"
      fabric_location = "Primary"

      fail_over_directions = [
        "PrimaryToRecovery", "RecoveryToPrimary"
      ]
      fail_over_types = [
        "TestFailover", "PlannedFailover", "UnplannedFailover"
      ]
      runbook_id = module.asr-dr-runbooks.automation-runbook-some-pre-action-id
    }

    pre_action {
      name            = "stop-applications"
      type            = "AutomationRunbookActionDetails"
      fabric_location = "Primary"

      fail_over_directions = [
        "PrimaryToRecovery", "RecoveryToPrimary"
      ]
      fail_over_types = [
        "TestFailover", "PlannedFailover", "UnplannedFailover"
      ]
      runbook_id = module.asr-dr-runbooks.automation-runbook-stop-apps-id
    }
 }   

  recovery_group {
    type = "Failover"
  }

  recovery_group {
    type                       = "Boot"
    replicated_protected_items = local.replication_protected_db_items

    post_action {
      name            = "db-health-check"
      type            = "AutomationRunbookActionDetails"
      fabric_location = "Primary"

      fail_over_directions = [
        "PrimaryToRecovery", "RecoveryToPrimary"
      ]
      fail_over_types = [
        "TestFailover", "PlannedFailover", "UnplannedFailover"
      ]
      runbook_id = module.asr-dr-runbooks.automation-runbook-db-health-check-id
    }
  }

  recovery_group {
    type = "Boot"
    replicated_protected_items = local.replication_protected_app_items

    post_action {
      name            = "test"
      type            = "AutomationRunbookActionDetails"
      fabric_location = "Primary"

      fail_over_directions = [
        "PrimaryToRecovery", "RecoveryToPrimary"
      ]
      fail_over_types = [
        "TestFailover", "PlannedFailover", "UnplannedFailover"
      ]
      runbook_id = module.asr-dr-runbooks.automation-runbook-test-id
    }
  }

  azure_to_azure_settings {
    primary_zone  = local.source_zone
    recovery_zone = local.target_zone
  }
}
```

### Debug Output/Panic Output

```shell
{"id":"/Subscriptions/xxxxxxx/resourceGroups/xxxxxxx/providers/Microsoft.RecoveryServices/vaults/zacha9999pr01ns1rsv90/replicationRecoveryPlans/example-recovery-plan","name":"example-recovery-plan","type":"Microsoft.RecoveryServices/vaults/replicationRecoveryPlans","properties":{"friendlyName":"example-recovery-plan","primaryFabricId":"/Subscriptions/xxxxxxx/resourceGroups/xxxxxxx/providers/Microsoft.RecoveryServices/vaults/zacha9999pr01ns1rsv90/replicationFabrics/primary-fabric","primaryFabricFriendlyName":"Switzerland North","recoveryFabricId":"/Subscriptions/xxxxxxx/resourceGroups/xxxxxxx/providers/Microsoft.RecoveryServices/vaults/zacha9999pr01ns1rsv90/replicationFabrics/primary-fabric","recoveryFabricFriendlyName":"Switzerland North","failoverDeploymentModel":"ResourceManager","replicationProviders":["A2A"],"allowedOperations":["UnplannedFailover","TestFailover"],"currentScenario":{"scenarioName":"UnplannedFailover","jobId":"/Subscriptions/xxxxxxx/resourceGroups/xxxxxxx/providers/Microsoft.RecoveryServices/vaults/zacha9999pr01ns1rsv90/replicationJobs/c272de86-fd6a-4032-93ed-ee3e8cbe5623","startTime":"2023-06-23T05:30:06.1067293Z"},"currentScenarioStatus":"Cancelled","currentScenarioStatusDescription":"Cancelled","groups":[{"groupType":"Shutdown","replicationProtectedItems":[],"startGroupActions":[{"actionName":"some-pre-action","failoverTypes":["PlannedFailover","UnplannedFailover","TestFailover"],"failoverDirections":["PrimaryToRecovery","RecoveryToPrimary"],"customDetails":{"instanceType":"AutomationRunbookActionDetails","runbookId":"/subscriptions/xxxxxxx/resourceGroups/xxxxxxx/providers/Microsoft.Automation/automationAccounts/test/runbooks/some-runbook","fabricLocation":"Primary","canWrite":false,"canRead":true}},{"actionName":"stop-applications","failoverTypes":["PlannedFailover","UnplannedFailover","TestFailover"],"failoverDirections":["PrimaryToRecovery","RecoveryToPrimary"],"customDetails":{"instanceType":"AutomationRunbookActionDetails","runbookId":"/subscriptions/xxxxxxx/resourceGroups/xxxxxxx/providers/Microsoft.Automation/automationAccounts/test/runbooks/Stop-Applications","fabricLocation":"Primary","canWrite":false,"canRead":true}}],"endGroupActions":[]},{"groupType":"Failover","replicationProtectedItems":[],"startGroupActions":[],"endGroupActions":[]},{"groupType":"Boot","replicationProtectedItems":[{"id":"/Subscriptions/xxxxxxx/resourceGroups/xxxxxxx/providers/Microsoft.RecoveryServices/vaults/zacha9999pr01ns1rsv90/replicationFabrics/primary-fabric/replicationProtectionContainers/primary-protection-container/replicationProtectedItems/zachadevtestpr01008","virtualMachineId":"055d5a72-a050-5823-bffb-1c264f4bfadb"}],"startGroupActions":[],"endGroupActions":[{"actionName":"db-health-check","failoverTypes":["PlannedFailover","UnplannedFailover","TestFailover"],"failoverDirections":["PrimaryToRecovery","RecoveryToPrimary"],"customDetails":{"instanceType":"AutomationRunbookActionDetails","runbookId":"/subscriptions/xxxxxxx/resourceGroups/xxxxxxx/providers/Microsoft.Automation/automationAccounts/test/runbooks/DB-Health-Check","fabricLocation":"Primary","canWrite":false,"canRead":true}}]},{"groupType":"Boot","replicationProtectedItems":[],"startGroupActions":[],"endGroupActions":[{"actionName":"test","failoverTypes":["PlannedFailover","UnplannedFailover","TestFailover"],"failoverDirections":["PrimaryToRecovery","RecoveryToPrimary"],"customDetails":{"instanceType":"AutomationRunbookActionDetails","runbookId":"/subscriptions/xxxxxxx/resourceGroups/xxxxxxx/providers/Microsoft.Automation/automationAccounts/test/runbooks/runbook-test","fabricLocation":"Primary","canWrite":false,"canRead":true}}]}],"providerSpecificDetails":[{"instanceType":"A2A","primaryZone":"1","recoveryZone":"2","primaryExtendedLocation":null,"recoveryExtendedLocation":null}]}}:"timestamp=2023-06-23T08":"48":32.128Z
2023-06-23T08:48:32.139Z [WARN]  Provider "registry.terraform.io/hashicorp/azurerm" produced an unexpected new value for azurerm_site_recovery_replication_recovery_plan.recovery_plan_az1 during refresh.
- .recovery_group: planned set element cty.ObjectVal(map[string]cty.Value{"post_action":cty.ListVal([]cty.Value{cty.ObjectVal(map[string]cty.Value{"fabric_location":cty.StringVal("Primary"), "fail_over_directions":cty.SetVal([]cty.Value{cty.StringVal("PrimaryToRecovery"), cty.StringVal("RecoveryToPrimary")}), "fail_over_types":cty.SetVal([]cty.Value{cty.StringVal("PlannedFailover"), cty.StringVal("TestFailover"), cty.StringVal("UnplannedFailover")}), "manual_action_instruction":cty.NullVal(cty.String), "name":cty.StringVal("db-health-check"), "runbook_id":cty.StringVal("/subscriptions/xxxxxxx/resourceGroups/xxxxxxx/providers/Microsoft.Automation/automationAccounts/zacha9999pr01ns1asr01/runbooks/DB-Health-Check"), "script_path":cty.NullVal(cty.String), "type":cty.StringVal("AutomationRunbookActionDetails")})}), "pre_action":cty.ListValEmpty(cty.Object(map[string]cty.Type{"fabric_location":cty.String, "fail_over_directions":cty.Set(cty.String), "fail_over_types":cty.Set(cty.String), "manual_action_instruction":cty.String, "name":cty.String, "runbook_id":cty.String, "script_path":cty.String, "type":cty.String})), "replicated_protected_items":cty.ListVal([]cty.Value{cty.StringVal("/subscriptions/xxxxxxx/resourceGroups/xxxxxxx/providers/Microsoft.RecoveryServices/vaults/zacha9999pr01ns1rsv90/replicationFabrics/primary-fabric/replicationProtectionContainers/primary-protection-container/replicationProtectedItems/zachadevtestpr01008")}), "type":cty.StringVal("Boot")}) does not correlate with any element in actual
- .recovery_group: planned set element cty.ObjectVal(map[string]cty.Value{"post_action":cty.ListVal([]cty.Value{cty.ObjectVal(map[string]cty.Value{"fabric_location":cty.StringVal("Primary"), "fail_over_directions":cty.SetVal([]cty.Value{cty.StringVal("PrimaryToRecovery"), cty.StringVal("RecoveryToPrimary")}), "fail_over_types":cty.SetVal([]cty.Value{cty.StringVal("PlannedFailover"), cty.StringVal("TestFailover"), cty.StringVal("UnplannedFailover")}), "manual_action_instruction":cty.NullVal(cty.String), "name":cty.StringVal("restart-preprod-at-failback"), "runbook_id":cty.StringVal("/subscriptions/xxxxxxx/resourceGroups/xxxxxxx/providers/Microsoft.Automation/automationAccounts/zacha9999pr01ns1asr01/runbooks/Failback-PreProd-Restart"), "script_path":cty.NullVal(cty.String), "type":cty.StringVal("AutomationRunbookActionDetails")}), cty.ObjectVal(map[string]cty.Value{"fabric_location":cty.StringVal("Primary"), "fail_over_directions":cty.SetVal([]cty.Value{cty.StringVal("PrimaryToRecovery"), cty.StringVal("RecoveryToPrimary")}), "fail_over_types":cty.SetVal([]cty.Value{cty.StringVal("PlannedFailover"), cty.StringVal("TestFailover"), cty.StringVal("UnplannedFailover")}), "manual_action_instruction":cty.NullVal(cty.String), "name":cty.StringVal("commit-recovery-plan"), "runbook_id":cty.StringVal("/subscriptions/xxxxxxx/resourceGroups/xxxxxxx/providers/Microsoft.Automation/automationAccounts/zacha9999pr01ns1asr01/runbooks/some-pre-action"), "script_path":cty.NullVal(cty.String), "type":cty.StringVal("AutomationRunbookActionDetails")})}), "pre_action":cty.ListValEmpty(cty.Object(map[string]cty.Type{"fabric_location":cty.String, "fail_over_directions":cty.Set(cty.String), "fail_over_types":cty.Set(cty.String), "manual_action_instruction":cty.String, "name":cty.String, "runbook_id":cty.String, "script_path":cty.String, "type":cty.String})), "replicated_protected_items":cty.ListValEmpty(cty.String), "type":cty.StringVal("Boot")}) does not correlate with any element in actual
- .recovery_group: planned set element cty.ObjectVal(map[string]cty.Value{"post_action":cty.ListValEmpty(cty.Object(map[string]cty.Type{"fabric_location":cty.String, "fail_over_directions":cty.Set(cty.String), "fail_over_types":cty.Set(cty.String), "manual_action_instruction":cty.String, "name":cty.String, "runbook_id":cty.String, "script_path":cty.String, "type":cty.String})), "pre_action":cty.ListVal([]cty.Value{cty.ObjectVal(map[string]cty.Value{"fabric_location":cty.StringVal("Primary"), "fail_over_directions":cty.SetVal([]cty.Value{cty.StringVal("PrimaryToRecovery"), cty.StringVal("RecoveryToPrimary")}), "fail_over_types":cty.SetVal([]cty.Value{cty.StringVal("PlannedFailover"), cty.StringVal("TestFailover"), cty.StringVal("UnplannedFailover")}), "manual_action_instruction":cty.StringVal(""), "name":cty.StringVal("free-up-crg-at-failover"), "runbook_id":cty.StringVal("/subscriptions/xxxxxxx/resourceGroups/xxxxxxx/providers/Microsoft.Automation/automationAccounts/zacha9999pr01ns1asr01/runbooks/Free-Up-CRG"), "script_path":cty.StringVal(""), "type":cty.StringVal("AutomationRunbookActionDetails")}), cty.ObjectVal(map[string]cty.Value{"fabric_location":cty.StringVal("Primary"), "fail_over_directions":cty.SetVal([]cty.Value{cty.StringVal("PrimaryToRecovery"), cty.StringVal("RecoveryToPrimary")}), "fail_over_types":cty.SetVal([]cty.Value{cty.StringVal("PlannedFailover"), cty.StringVal("TestFailover"), cty.StringVal("UnplannedFailover")}), "manual_action_instruction":cty.StringVal(""), "name":cty.StringVal("stop-applications"), "runbook_id":cty.StringVal("/subscriptions/xxxxxxx/resourceGroups/xxxxxxx/providers/Microsoft.Automation/automationAccounts/zacha9999pr01ns1asr01/runbooks/Stop-Applications"), "script_path":cty.StringVal(""), "type":cty.StringVal("AutomationRunbookActionDetails")}), cty.ObjectVal(map[string]cty.Value{"fabric_location":cty.StringVal("Primary"), "fail_over_directions":cty.SetVal([]cty.Value{cty.StringVal("PrimaryToRecovery"), cty.StringVal("RecoveryToPrimary")}), "fail_over_types":cty.SetVal([]cty.Value{cty.StringVal("PlannedFailover"), cty.StringVal("TestFailover"), cty.StringVal("UnplannedFailover")}), "manual_action_instruction":cty.StringVal(""), "name":cty.StringVal("stop-dbs"), "runbook_id":cty.StringVal("/subscriptions/xxxxxxx/resourceGroups/xxxxxxx/providers/Microsoft.Automation/automationAccounts/zacha9999pr01ns1asr01/runbooks/Stop-Databases"), "script_path":cty.StringVal(""), "type":cty.StringVal("AutomationRunbookActionDetails")}), cty.ObjectVal(map[string]cty.Value{"fabric_location":cty.StringVal("Primary"), "fail_over_directions":cty.SetVal([]cty.Value{cty.StringVal("PrimaryToRecovery"), cty.StringVal("RecoveryToPrimary")}), "fail_over_types":cty.SetVal([]cty.Value{cty.StringVal("PlannedFailover"), cty.StringVal("TestFailover"), cty.StringVal("UnplannedFailover")}), "manual_action_instruction":cty.StringVal("Please check if all scrips run successfully"), "name":cty.StringVal("approval-gate"), "runbook_id":cty.StringVal(""), "script_path":cty.StringVal(""), "type":cty.StringVal("ManualActionDetails")})}), "replicated_protected_items":cty.ListVal([]cty.Value{cty.StringVal("/subscriptions/xxxxxxx/resourceGroups/xxxxxxx/providers/Microsoft.RecoveryServices/vaults/zacha9999pr01ns1rsv90/replicationFabrics/primary-fabric/replicationProtectionContainers/primary-protection-container/replicationProtectedItems/zachadevtestpr01008")}), "type":cty.StringVal("Shutdown")}) does not correlate with any element in actual
2023-06-23T08:48:32.167Z [WARN]  Provider "registry.terraform.io/hashicorp/azurerm" produced an invalid plan for azurerm_site_recovery_replication_recovery_plan.recovery_plan_az1, but we are tolerating it because it is using the legacy plugin SDK.
The following problems may be the cause of any confusing errors from downstream operations:
- .azure_to_azure_settings[0].primary_edge_zone: planned value cty.StringVal("") for a non-computed attribute
- .azure_to_azure_settings[0].recovery_edge_zone: planned value cty.StringVal("") for a non-computed attribute
2023-06-23T08:48:32.306Z [DEBUG] provider.terraform-provider-azurerm_v3.61.0_x5: AzureRM Response for https://management.azure.com/subscriptions/xxxxxxx/resourceGroups/xxxxxxx/providers/Microsoft.Web/sites/overall-dr-function-app/config/slotConfigNames?api-version=2021-03-01:
HTTP/2.0 200 OK
Cache-Control: no-cache
Content-Type: application/json
Date: Fri, 23 Jun 2023 08:48:32 GMT
Expires: -1
Pragma: no-cache
Server: Microsoft-IIS/10.0
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Accept-Encoding
X-Aspnet-Version: 4.0.30319
X-Content-Type-Options: nosniff
X-Ms-Correlation-Request-Id: 7369947b-3c6e-be1a-3760-978555942bb6
X-Ms-Ratelimit-Remaining-Subscription-Reads: 11965
X-Ms-Request-Id: 2a61caa7-d6f5-415d-961c-6c1d963043d2
X-Ms-Routing-Request-Id: SWITZERLANDWEST:20230623T084832Z:795a30e3-ba05-4e4b-8a70-9c5505fa7201
X-Powered-By: ASP.NET
```

### Expected Behaviour

`recovery_group` order should be the same as defined in terraform file to keep order on state validation 

### Actual Behaviour

`recovery_group`s will be listed as changed on each terraform plan regardless of actual changes 

### Steps to Reproduce

`terraform plan`

**Comment by ziyeqf** [comment] 2023-06-26 07:08
Hi @viewegchris, thanks for opening this issue.

Per my test it happens when `replicated_protected_items` is specified in `Shutdown` type `recovery_group`. The service actually does not support specifying it for `Shutdown` group, I have submitted a PR (https://github.com/hashicorp/terraform-provider-azurerm/pull/22281) to limit it, once it merged and released it should be fixed. before the PR got merged could you please remove that line and give it a try if the issue is gone? 

For any further questions please leave comments.
Thanks.

**Comment by viewegchris** [comment] 2023-06-28 05:20
Hi @ziyeqf thanks for handling the issue. 

Unfortunately leaving  `replicated_protected_items ` empty or removing the Attribute completely does not have an effect on the plan. The Attribute is always added as an empty array 

```
 + recovery_group {
        + replicated_protected_items = []
        + type                       = "Shutdown"

        + pre_action {
            + fabric_location      = "Primary"
            + fail_over_directions = [
                + "PrimaryToRecovery",
....                  
```  

I would guess there is maybe a null or empty array check missing. 

Thank you 
Chris

**Comment by ziyeqf** [comment] 2023-06-28 05:52
Thanks @viewegchris, I tried another time with your config and I can not reproduce the diff when `replicated_protected_items` of `Shutdown` type is empty, do you mind checking the recovery plan on Portal if it's completely match the Terraform config?

**Comment by viewegchris** [comment] 2023-06-28 07:34
@ziyeqf Unfortunately, the protal is secured behind a proxy. But I found out that the problem seems to be a manual approval action. After removing this `pre_action` and the `replicated_protected_items ` it works for me. 

```hcl
  pre_action {
    name            = "approval-gate"
    type            = "ManualActionDetails"
    fabric_location = "Primary"

    fail_over_directions = [
      "PrimaryToRecovery", "RecoveryToPrimary"
    ]
    fail_over_types = [
      "TestFailover", "PlannedFailover", "UnplannedFailover"
    ]
    manual_action_instruction = "Please check if all scrips run successfully"
  }
```

Maybe you can try to reproduce it with this config 

```hcl
resource "azurerm_site_recovery_replication_recovery_plan" "test_recovery_plan" {
  name                      = "test-recovery-plan"
  recovery_vault_id         = data.azurerm_recovery_services_vault.asr-vault.id
  source_recovery_fabric_id = data.azurerm_site_recovery_fabric.asr-recovery-fabric.id
  target_recovery_fabric_id = data.azurerm_site_recovery_fabric.asr-recovery-fabric.id

  recovery_group {
    type = "Shutdown"

    pre_action {
      name            = "approval-gate"
      type            = "ManualActionDetails"
      fabric_location = "Primary"

      fail_over_directions = [
        "PrimaryToRecovery", "RecoveryToPrimary"
      ]
      fail_over_types = [
        "TestFailover", "PlannedFailover", "UnplannedFailover"
      ]
      manual_action_instruction = "Please check if all scrips run successfully"
    }
  }

  recovery_group {
    type = "Failover"
  }

  recovery_group {
    type                       = "Boot"
    replicated_protected_items = local.replication_protected_db_items
  }

  recovery_group {
    type = "Boot"
    replicated_protected_items = local.replication_protected_app_items

    post_action {
      name            = "restart-preprod-at-failback"
      type            = "AutomationRunbookActionDetails"
      fabric_location = "Primary"

      fail_over_directions = [
        "PrimaryToRecovery", "RecoveryToPrimary"
      ]
      fail_over_types = [
        "TestFailover", "PlannedFailover", "UnplannedFailover"
      ]
      runbook_id = module.dr-runbooks.automation-runbook-failback-pp-restart-id
    }
  }

  azure_to_azure_settings {
    primary_zone  = local.source_zone
    recovery_zone = local.target_zone
  }
}
```

**Comment by ziyeqf** [comment] 2023-06-28 08:58
Thanks @viewegchris, I did reproduce the issue.

The point is `fabric_location` is not applied to `ManualActionDetails` type action but the service just accept the request and ignore it, which caused the diff. Will be fixed in the above PR together and please give it a try to remove it from your config.

**Closed** 2023-06-29 07:56 UTC
Labels: bug, service/recovery-services

**Comment by BrokeAssChewbacca** [comment] 2023-07-07 00:14
> Hi @viewegchris, thanks for opening this issue.
> 
> Per my test it happens when `replicated_protected_items` is specified in `Shutdown` type `recovery_group`. The service actually does not support specifying it for `Shutdown` group, I have submitted a PR (#22281) to limit it, once it merged and released it should be fixed. before the PR got merged could you please remove that line and give it a try if the issue is gone?
> 
> For any further questions please leave comments. Thanks.

Hey @ziyeqf, is this the same case for `recovery_group`s of type `Failover`? I found this issue earlier when looking into the behavior described here, but I was  also seeing the same bahavior for a `recovery_group` of type `Failover`. After removing the `replicated_protected_items` argument from the `recovery_group` it cleared up the issue.

If so, I suppose changes similar to the ones in https://github.com/hashicorp/terraform-provider-azurerm/pull/22281 should be made for `Failover` `recovery_group`s.

Thanks!

**Comment by ziyeqf** [comment] 2023-07-07 02:17
Hi @BrokeAssChewbacca, thanks for reporting. It will be updated on https://github.com/hashicorp/terraform-provider-azurerm/pull/22348
