### ISSUE TITLE
azurerm_cdn_frontdoor_origin should allow more values in private_link.target_type to support App Service Slot origins

### ISSUE THREAD

**Issue by matt-byrne** [hashicorp/terraform-provider-azurerm#22261] opened 2023-06-23 10:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.5.1

### AzureRM Provider Version

3.50.0

### Affected Resource(s)/Data Source(s)

azurerm_cdn_frontdoor_origin

### Terraform Configuration Files

```hcl
resource "azurerm_cdn_frontdoor_origin" "frontdoor-origin" {
  for_each = {
    for origin in var.origins :
    coalesce(try(origin.name, ""), try("${origin.naming_prefix}-fdo", "")) => origin
  }

  name                           = each.key
  cdn_frontdoor_origin_group_id  = azurerm_cdn_frontdoor_origin_group.frontdoor-origingroup[each.value.origin_group_name].id
  enabled                        = true
  certificate_name_check_enabled = each.value.certificate_name_check_enabled
  host_name                      = each.value.host_name
  origin_host_header             = each.value.origin_host_header
  http_port                      = each.value.http_port
  https_port                     = each.value.https_port
  priority                       = each.value.priority
  weight                         = each.value.weight

  private_link {
    location               = var.location
    private_link_target_id = each.value.private_link.private_link_target_id
    target_type            = "sites-staging"
  }
}
```

### Debug Output/Panic Output

```shell
Error: expected private_link.0.target_type to be one of [blob blob_secondary sites web], got sites-staging
with module.frontdoor.azurerm_cdn_frontdoor_origin.frontdoor-origin["AE-T-WEB-FDO-UAT-STAGING"]
on .terraform/modules/frontdoor/main.tf line 89, in resource "azurerm_cdn_frontdoor_origin" "frontdoor-origin":
    target_type            = each.value.private_link.target_type
```

### Expected Behaviour

`sites-*` should be an accepted value, to support App Service Slot origins. 

The REST API docs indicate that the `groupId` parameter of `properties.sharedPrivateLinkResource` just needs to be a string, not a match a specific list.

### Actual Behaviour

The resource only accepts a small list of private endpoint subresource types.

### References

https://learn.microsoft.com/en-us/rest/api/frontdoor/azurefrontdoorstandardpremium/afd-origins/create#sharedprivatelinkresourceproperties

**Comment by WodansSon** [comment] 2023-09-06 20:03
Hi @matt-byrne, I have spoken with the service team about the inclusion of `sites-*` and they said that "...App Service Slot is not currently supported with Azure Front Door but it is in the roadmap, however an ETA isn’t finalized yet." As this isn't a support feature in the resource, I am going to close this issue as `by design`.

**Closed by WodansSon** 2023-09-06 20:03 UTC
Labels: service/cdn, v/3.x
