### ISSUE TITLE
Azure Cognitive Deployment: Configure Token Per Minute Quota

### ISSUE THREAD

**Issue by efiedle6** [hashicorp/terraform-provider-azurerm#22195] opened 2023-06-16 15:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When deploying an Azure Cognitive Deployment via terraform I don't see an option to adjust the quota for the allowed Tokens Per Minute (TPM) of a given model as I am deploying. The impact of this is that it is deploying with a TPM of 120K by default (using model: text-embedding-ada-002 as an example), while my OpenAI Account only allows for a quota of 240K for that model. I have multiple teams working within that OpenAI account, and so because of this quota only 2 deployments of the same model are able to be made. After that, deployments will fail as it sees there is not 120K available to enable provisioning. As a work around we are able to slide the quota limit down for a particular model and free up quota space. However, this is undesirable as every time we do a CI/CD it is resetting the quota back to 120K, and our models need no where close to 120K TPM, our business cases would suffice with much smaller amounts between 1-2K TPM, so it really is a unnecessary to have it provisioned by default with 120K TPM, orders of magnitude above what we require.

I am requesting that the allowed Tokens Per Minute quota be configurable via terraform in the azurerm_cognitive_deployment resource.

Here is the error I am trying to address by allowing the rate limit to be adjusted prior to deployment:
Deployment Name: "<private_appname>-text-embedding-ada-002"): performing CreateOrUpdate: unexpected status 400 with error: InsufficientQuota: The specified capacity '120' of account deployment is bigger than available capacity '0' for UsageName 'Tokens Per Minute (thousands) - Text-Embedding-Ada-002'.

### New or Affected Resource(s)/Data Source(s)

azurerm_cognitive_deployment 

### Potential Terraform Configuration

```hcl
resource "azurerm_cognitive_deployment" "example" {
  name                 = "example-cd"
  cognitive_account_id = azurerm_cognitive_account.example.id
  model {
    format  = "OpenAI"
    name    = "text-curie-001"
    version = "1"
    quota_capacity = "120"
  }
}

    quota_capacity = "120" > being able to range between integer values from 0 - X, with X changing based on the model chosen as some models have different maximum limits. Must always be a positive integer value.
```

**Comment by slynickel** [comment] 2023-06-16 15:58
This appears to be duplicate of https://github.com/hashicorp/terraform-provider-azurerm/issues/22135 
But I could be wrong.

**Comment by rcskosir** [comment] 2023-06-16 16:11
Yes this does appear to be a duplicate. @efiedle6 Thank you for opening this issue, I ask that you please follow #22135 and 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) it so that we can track interest. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of #22135.

**Closed by rcskosir** 2023-06-16 16:11 UTC
