### ISSUE TITLE
The 'azurerm_windows_function_app' resource crash when 'WEBSITE_CONTENTOVERVNET' app setting is set

### ISSUE THREAD

**Issue by KenticoMartinS** [hashicorp/terraform-provider-azurerm#16301] opened 2022-04-08 11:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.7

### AzureRM Provider Version

3.1.0

### Affected Resource(s)/Data Source(s)

azurerm_windows_function_app

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "group" {
  location = "West Europe"
  name     = "testing-rg01"
}

resource "azurerm_service_plan" "service_plan" {
  name = "testing-plan01"

  location            = azurerm_resource_group.group.location
  resource_group_name = azurerm_resource_group.group.name

  os_type  = "Windows"
  sku_name = "EP1"

  maximum_elastic_worker_count = 5
}

resource "azurerm_storage_account" "storage_account" {
  name = "testingaccnt01"

  resource_group_name = azurerm_resource_group.group.name
  location            = azurerm_resource_group.group.location

  account_kind             = "StorageV2"
  account_tier             = "Standard"
  access_tier              = "Hot"
  account_replication_type = "GRS"
}

resource "azurerm_windows_function_app" "windows_function_app" {
  name = "testing-fc-01"

  location            = azurerm_resource_group.group.location
  resource_group_name = azurerm_resource_group.group.name

  service_plan_id = azurerm_service_plan.service_plan.id

  storage_account_name       = azurerm_storage_account.storage_account.name
  storage_account_access_key = azurerm_storage_account.storage_account.primary_access_key

  site_config {}

  functions_extension_version = "~4"

  app_settings = {
    WEBSITE_CONTENTOVERVNET = 1
  }
}
```

### Debug Output/Panic Output

```shell
azurerm_windows_function_app.windows_function_app: Still creating... [11m11s elapsed]
╷
│ Error: reading logs configuration for Windows Function App: (Site Name "testing-fc-01" / Resource Group "testing-rg01"): web.AppsClient#GetDiagnosticLogsConfiguration: Failure responding to request: StatusCode=503 -- Original Error: autorest/azure: Service returned an error. Status=503 Code="ServiceUnavailable" Message="The operation timed out and could not be completed. Please retry the action or try again later." Details=[{"Message":"The operation timed out and could not be completed. Please retry the action or try again later."},{"Code":"ServiceUnavailable"},{"ErrorEntity":{"Code":"ServiceUnavailable","ExtendedCode":"51007","Message":"The operation timed out and could not be completed. Please retry the action or try again later.","MessageTemplate":"The operation timed out and could not be completed. Please retry the action or try again later."}}]
│
│   with azurerm_windows_function_app.windows_function_app,
│   on test.tf line 34, in resource "azurerm_windows_function_app" "windows_function_app":
│   34: resource "azurerm_windows_function_app" "windows_function_app" {
│
│ reading logs configuration for Windows Function App: (Site Name "testing-fc-01" / Resource Group "testing-rg01"):
│ web.AppsClient#GetDiagnosticLogsConfiguration: Failure responding to request: StatusCode=503 -- Original Error: autorest/azure: Service
│ returned an error. Status=503 Code="ServiceUnavailable" Message="The operation timed out and could not be completed. Please retry the action
│ or try again later." Details=[{"Message":"The operation timed out and could not be completed. Please retry the action or try again
│ later."},{"Code":"ServiceUnavailable"},{"ErrorEntity":{"Code":"ServiceUnavailable","ExtendedCode":"51007","Message":"The operation timed out
│ and could not be completed. Please retry the action or try again later.","MessageTemplate":"The operation timed out and could not be
│ completed. Please retry the action or try again later."}}]
╵
```

### Expected Behaviour

Terraform won't crash and Azure Function is created correctly.

### Actual Behaviour

When creating Windows Function App with the `WEBSITE_CONTENTOVERVNET = 1` app setting, the Function App is created but terraform is stuck for 10 minutes. Then it crashes. The next apply/plan won't be even able to refresh the state. 

When I run `terraform apply` again with `TF_LOG = "debug"` I found out it was accessing logs on the Azure Function

```
{"Code":"ServiceUnavailable","Message":"The operation timed out and could not be completed. Please retry the action or try again later.","Target":null,"Details":[{"Message":"The operation timed out and could not be completed. Please retry the action or try again later."},{"Code":"ServiceUnavailable"},{"ErrorEntity":{"ExtendedCode":"51007","MessageTemplate":"The operation timed out and could not be completed. Please retry the action or try again later.","Code":"ServiceUnavailable","Message":"The operation timed out and could not be completed. Please retry the action or try again later."}}],"Innererror":null}: timestamp=2022-04-08T13:23:20.892+0200

[DEBUG] provider.terraform-provider-azurerm_v3.1.0_x5.exe: AzureRM Request:
GET /subscriptions/<subscription_id>/resourceGroups/testing-rg01/providers/Microsoft.Web/sites/testing-fc-01/config/logs?api-version=2021-02-01 HTTP/1.1
```

This is the minimal configuration I found, where it won't work. Of course, we have VNet around our storage and functions.

**Comment by lslifierz** [comment] 2022-05-30 11:52
I have the same issue for azurerm_linux_function_app resource with "WEBSITE_CONTENTOVERVNET = 1" in app settings. Storage account's (AzureWebJobStorage) Blob, File, Table and Queue sub-resources are accessible via privateendpoints.


### Debug Output/Panic Output
```
│ Error: reading logs configuration for Linux Function App: (Site Name "funcapp-name" / Resource Group "rg-name"): web.AppsClient#GetDiagnosticLogsConfiguration: Failure responding to request: StatusCode=500 -- Original Error: autorest/azure: Service returned an error. Status=500 Code="Unknown" Message="Unknown service error" Details=[{"Code":"InternalServerError","Details":[{"Message":null},{"Code":"InternalServerError"},{"ErrorEntity":{"Code":"InternalServerError","Message":null}}],"Innererror":null,"Message":null,"Target":null}]
│ 
│   with module.funcapp["key-name"].azurerm_linux_function_app.funcapp,
│   on main.tf line 20, in resource "azurerm_linux_function_app" "funcapp":
│   20: resource "azurerm_linux_function_app" "funcapp" {
│ 
│ reading logs configuration for Linux Function App: (Site Name
│ "funcapp-name" / Resource Group
│ "rg-name"): web.AppsClient#GetDiagnosticLogsConfiguration:
│ Failure responding to request: StatusCode=500 -- Original Error:
│ autorest/azure: Service returned an error. Status=500 Code="Unknown"
│ Message="Unknown service error"
│ Details=[{"Code":"InternalServerError","Details":[{"Message":null},{"Code":"InternalServerError"},{"ErrorEntity":{"Code":"InternalServerError","Message":null}}],"Innererror":null,"Message":null,"Target":null}]

```

**Comment by Dmitrinjo** [comment] 2022-05-31 22:17
Same issue here, still not resolved.

**Comment by xiaxyi** [comment] 2022-07-28 07:15
Thanks guys for raising the issue, we are trying to figure out the dependency between log configuration and the property `WEBSITE_CONTENTOVERVNET `. 

Based on our investigation so far, the storage file share won't be created automatically by specifying this property and this may cause the log reading timeout, but we are not sure about the direct relationship between these two features yet. The workaround is to create the storage file share manually and assign to the key `WEBSITE_CONTENTSHARE` in app setting

**Comment by ddmitrovic** [comment] 2022-07-28 07:22
Classification: Span_Confidential

Hi,

Thank you for the input.

The other workaround that I found is to not use that key in Terraform and add it through azure cli as the latest step (calling azure cli with local-exec in terraform).

The main fix for the whole issue would be the ability to add app_settings for function / web apps later on with a separate resource.

Something like resource "azurerm_windows_function_app_settings" {}

Lijep pozdrav / Kind Regards,

Danijel Dmitrović | Span <https://www.google.com/maps/preview#!q=kotura%C5%A1ka+47%2C+zagreb%2C+croatia&data=!4m10!1m9!4m8!1m3!1d52163205!2d-95.677068!3d37.0625!3m2!1i1024!2i768!4f13.1>
***@***.******@***.***> | M +385914120478

**Comment by xiaxyi** [comment] 2022-07-28 08:25
@ddmitrovic I don't think it's worth to separate the app_setting from the resource, besides, you can specify the app_setting in the function app resource by adding the block, right? The reason why we are not able to modify the app_setting is log-reading timeout so we don't get a chance to update the app_setting when updating the function app. if you try to add the KVP in app_setting via azure portal then get back to terraform, everything will work fine.

**Comment by ddmitrovic** [comment] 2022-07-28 08:28
Classification: Span_Confidential

The problem is that WEBSITE_CONTENTOVERVNET key applies while creating the function app, and the function app doesn't yet have private endpoints (private endpoint resource is of course created after the function app), so that key needs to be added after the private endpoint in order for the function app to work.

Thats why it works when I use azure cli command through terraform after creating both the function app, storage account and the private endpoint.

Lijep pozdrav / Kind Regards,

Danijel Dmitrović | Span <https://www.google.com/maps/preview#!q=kotura%C5%A1ka+47%2C+zagreb%2C+croatia&data=!4m10!1m9!4m8!1m3!1d52163205!2d-95.677068!3d37.0625!3m2!1i1024!2i768!4f13.1>
***@***.******@***.***> | M +385914120478

**Comment by xiaxyi** [comment] 2022-07-28 08:43
@ddmitrovic have you ever tried to add the key post function app creation via terraform? Based on my test, WEBSITE_CONTENTOVERVNET will not be added if user doesn't specify it in app_setting during function app creation.

**Comment by ddmitrovic** [comment] 2022-07-28 08:58
Classification: Span_Confidential

If I specifiy it during creation I get the error and the shares are not created.

If I don't specify it during creation everything is fine but the private endpoint communication doesn't work.

If I add it later as an app setting via terraform it gets applied and everything works fine. The reason I don't like this is because I have to run my pipeline twice. First time I need to comment out the code for that app setting, run the pipeline to apply, then uncomment and run it again.

If I add it immediately as azure cli local-exec null resource and set the depends_on after the storage account, function app and private endpoints have already been created it works and I only need to run the pipeline once.

Lijep pozdrav / Kind Regards,

Danijel Dmitrović | Span <https://www.google.com/maps/preview#!q=kotura%C5%A1ka+47%2C+zagreb%2C+croatia&data=!4m10!1m9!4m8!1m3!1d52163205!2d-95.677068!3d37.0625!3m2!1i1024!2i768!4f13.1>
***@***.******@***.***> | M +385914120478

**Comment by xiaxyi** [comment] 2022-07-28 09:19
@ddmitrovic I see your painpoint, as I mentioned before, the issue of adding the WEBSITE_CONTENTOVERVNET during function app creation is the storage content share won't be created automatically (at least based on my findings so far), so if you try below script together with your private endpoint resource, it should work fine:
```
resource "azurerm_windows_function_app" "windows_function_app" {
  name = "xiaxintest-wfa"


  location            = azurerm_resource_group.group.location
  resource_group_name = azurerm_resource_group.group.name


  service_plan_id = azurerm_service_plan.service_plan.id


  storage_account_name       = azurerm_storage_account.storage_account.name
  storage_account_access_key = azurerm_storage_account.storage_account.primary_access_key


  site_config {
    runtime_scale_monitoring_enabled = true
    vnet_route_all_enabled = true
  }

 app_settings = {
    WEBSITE_CONTENTSHARE = azurerm_storage_share.test.name
    WEBSITE_CONTENTAZUREFILECONNECTIONSTRING = azurerm_storage_account.storage_account.primary_connection_string
    WEBSITE_CONTENTOVERVNET = 1
  }
}
```

**Closed** 2022-08-18 22:27 UTC
Labels: bug, service/app-service

**Comment by ddmitrovic** [comment] 2022-08-19 05:59
Classification: Span_Confidential

Thank you!

Lijep pozdrav / Kind Regards,

Danijel Dmitrović | Span
***@***.******@***.***> | M +385914120478
