### ISSUE TITLE
azurerm_virtual_desktop_host_pool - Unable to access registration token to enroll VM in pool

### ISSUE THREAD

**Issue by pedroivotavares** [hashicorp/terraform-provider-azurerm#15117] opened 2022-01-25 22:16 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v1.1.4
on windows_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.15.0
+ provider registry.terraform.io/hashicorp/azurerm v2.93.1
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/time v0.7.2
```

### Affected Resource(s)

* `azurerm_virtual_desktop_host_pool`
* `azurerm_virtual_machine_extension`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">=2.93.1"
    }
    random = {
      source = "hashicorp/random"
    }
    time = {
      source = "hashicorp/time"
    }
  }
}

provider "azurerm" {
  skip_provider_registration = true
  subscription_id            = "1839425a-562d-434c-8c07-32d787f1e24d"
  features {}
}

resource "azurerm_resource_group" "rg" {
  name     = "rg-test"
  location = "eastus2"
}

resource "time_rotating" "avd_token" {
  rotation_days = 27
}

resource "azurerm_virtual_desktop_host_pool" "hostpool" {
  name                             = "vdpool-test"
  resource_group_name              = azurerm_resource_group.rg.name
  location                         = azurerm_resource_group.rg.location
  type                             = "Pooled"
  load_balancer_type               = "DepthFirst"
  personal_desktop_assignment_type = "Automatic"
  maximum_sessions_allowed         = 8

  registration_info {
    expiration_date = time_rotating.avd_token.rotation_rfc3339
  }
}

resource "azurerm_network_interface" "avd_vm_nic" {
  name                          = "nic-test"
  resource_group_name           = azurerm_resource_group.rg.name
  location                      = azurerm_resource_group.rg.location
  enable_accelerated_networking = true

  ip_configuration {
    name                          = "nic-test-config"
    subnet_id                     = azurerm_subnet.hostpool_subnet.id
    private_ip_address_allocation = "dynamic"
  }
}

resource "azurerm_virtual_network" "vnet" {
  name                = "vnet"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
  address_space       = ["10.0.0.0/24"]
}

resource "azurerm_subnet" "hostpool_subnet" {
  name                 = "hostpool-subnet"
  resource_group_name  = azurerm_resource_group.rg.name
  address_prefixes     = ["10.0.0.0/25"]
  virtual_network_name = azurerm_virtual_network.vnet.name
}

resource "random_password" "AVD_local_password" {
  length           = 16
  special          = true
  lower            = true
  upper            = true
  number           = true
  override_special = "*()#$-?![]"
}

resource "azurerm_windows_virtual_machine" "avd_vm" {
  name                  = "testvm"
  resource_group_name   = azurerm_resource_group.rg.name
  location              = azurerm_resource_group.rg.location
  size                  = "Standard_D8s_v3"
  network_interface_ids = [azurerm_network_interface.avd_vm_nic.id]
  provision_vm_agent    = true
  admin_username        = "vmadmin"
  admin_password        = random_password.AVD_local_password.result

  os_disk {
    name                 = "testdisk"
    caching              = "ReadWrite"
    storage_account_type = "StandardSSD_LRS"
  }
  source_image_reference {
    publisher = "MicrosoftWindowsServer"
    offer     = "WindowsServer"
    sku       = "2022-Datacenter"
    version   = "latest"
  }
}

resource "azurerm_virtual_machine_extension" "vmext_addtohostpool" {
  name                       = "avd_addtohostpool"
  virtual_machine_id         = azurerm_windows_virtual_machine.avd_vm.id
  publisher                  = "Microsoft.Powershell"
  type                       = "DSC"
  type_handler_version       = "2.82"
  auto_upgrade_minor_version = true

  settings = <<-SETTINGS
    {
      "modulesUrl": "https://wvdportalstorageblob.blob.core.windows.net/galleryartifacts/Configuration.zip",
      "configurationFunction": "Configuration.ps1\\AddSessionHost",
      "properties": {
        "hostPoolName":"${azurerm_virtual_desktop_host_pool.hostpool.name}"
      }
    }
SETTINGS

  protected_settings = <<PROTECTED_SETTINGS
  {
    "properties": {
      "RegistrationInfoToken":"${azurerm_virtual_desktop_host_pool.hostpool.registration_info[0].token}"
    }
  }
PROTECTED_SETTINGS

  lifecycle {
    ignore_changes = [settings, protected_settings]
  }
}
```

### Expected Behaviour

Until version 2.90.0 of the azurerm provider, the token field in the registration_info map was not marked as sensitive, so it could be used as input for template interpolation. The VM extension was properly created using the registration token for the AVD host pool.

### Actual Behaviour

Since version 2.91.0 of the azurerm provider, attempts to read the host pool registration token cause an error as it is now marked as sensitive. Using the nonsensitive() function to try to access it return null, with the following error message:

```
│ Error: Invalid template interpolation value
│
│   on pool\extensions.tf line 63, in resource "azurerm_virtual_machine_extension" "vmext_addtohostpool":
│   60:   protected_settings = <<PROTECTED_SETTINGS
│   61:   {
│   62:     "properties": {
│   63:       "RegistrationInfoToken":"${azurerm_virtual_desktop_host_pool.hostpool.registration_info[0].token}"
│   64:     }
│   65:   }
│   66: PROTECTED_SETTINGS
│     ├────────────────
│     │ azurerm_virtual_desktop_host_pool.hostpool.registration_info[0].token has a sensitive value
│
│ The expression result is null. Cannot include a null value in a string template.
```

### Steps to Reproduce

1. `terraform apply`
When trying to apply the configuration the registration token is not available and the VM extension can't be created.

**Comment by tombuildsstuff** [comment] 2022-01-26 08:41
hi @pedroivotavares 

Thanks for opening this issue.

Taking a look through this appears to be a duplicate of #14972 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #14972 for updates?

Thanks!

**Closed by tombuildsstuff** 2022-01-26 08:41 UTC
Labels: bug, duplicate, service/virtual-desktops

**Comment by pedroivotavares** [comment] 2022-01-26 12:01
I did not find #14972 during my research! Thank you for pointing that out, I'll subscribe to it.
