### ISSUE TITLE
azurerm_data_factory_linked_service_azure_blob_storage connection string is stored differently

### ISSUE THREAD

**Issue by dadasami** [hashicorp/terraform-provider-azurerm#14358] opened 2021-11-26 11:28 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

* Terraform Core version: 1.0.5
* AzureRM Provider version: 2.85.0

### Affected Resource(s)

- `azurerm_data_factory_linked_service_azure_blob_storage`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "data-factory" {
  location = var.LOCATION
  name = "rg"
}

resource "azurerm_data_factory" "ingester" {
  name = "data-factory"
  location = azurerm_resource_group.data-factory.location
  resource_group_name = azurerm_resource_group.data-factory.name
}

resource "azurerm_data_factory_linked_service_azure_blob_storage" "ingester" {
  name = "blob-storage"
  resource_group_name = azurerm_resource_group.data-factory.name
  data_factory_name = azurerm_data_factory.ingester.name
  connection_string = azurerm_storage_account.ingestion.primary_connection_string
}
```

### Expected Behaviour

Create a linked service and store the typeProperties in the format (<value> represents the value, which has not been added as sensitive).

```
{
  "connectionString": "<value>",
  "encryptedCredential": "<value>"
}
```

### Actual Behaviour

It set the connectionString as a secure string. This means that although the connections work for anything created by Terraform, if a developer wishes to add something into Azure manually (I know, but it's what we have to do) then it's not able to get the data.

```
{
  "connectionString": {
    "type": "SecureString",
    "value": "**********"
  },
   "encryptedCredential": "<value>"
}
```

For example, when creating a Wrangling Data Flow, we get the error:

DataFormat.Error: The supplied URL must be a valid 'http:' or 'https:' URL.Detailshttps://**********.blob.core.windows.net/raw/filename.csv

When I manually edit the linked data set in Azure (which changes the underlying JSON), it works fine. Specifically, note how the URL is `*****` - I suspect this is because the SecureString isn't able to be decrypted by Azure

NB There is also a documentation error in the docs - the connection string param makes references to
account_endpoint, account_key and database, which appear to have been copied and pasted from the CosmoDB page. If this is correct, these need further elucidation.

### Steps to Reproduce

- terraform apply
- Go to data factory
- Go to author and monitor
- Go to manage
- Go to blob-storage linked service
- View the JSON

### References

* #8099

**Comment by dadasami** [comment] 2021-11-26 11:31
Since I could not reopen #8099, I made a new copy of the issue since everything was already well explained. I am running to the very same issue, after more than a year that the bug was originally reported; perhaps on a newer terraform core version and azurerm provider version.

**Comment by tombuildsstuff** [comment] 2021-11-29 20:17
hi @dadasami 

Thanks for opening this issue.

Given that Connection Strings by design contain sensitive information (credentials) - Terraform appears to be doing the correct thing here by submitting these to the API's as a SecureString rather than a plain-text string.

Based on the bug report unfortunately this appears to be an issue with the Azure Portal (which shouldn't be sending these values) rather than Terraform - as such I'm going to close this issue since I believe this needs to be fixed by the Azure Portal team instead, and I'd recommend reaching out to Azure Support about this.

Thanks!

**Closed by tombuildsstuff** 2021-11-29 20:17 UTC
Labels: question, service/data-factory
