### ISSUE TITLE
azurerm_linux_web_app should have an argument for to block public network access

### ISSUE THREAD

**Issue by foo-bar-foo** [hashicorp/terraform-provider-azurerm#22355] opened 2023-07-03 08:58 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As of provider 3.63.0, there is no argument that sets public network access to false. This exists in the ARM template definition https://learn.microsoft.com/en-us/azure/templates/microsoft.web/sites?pivots=deployment-language-arm-template#arm-template-resource-definition as _publicNetworkAccess_ .

### New or Affected Resource(s)/Data Source(s)

azurerm_linux_web_app

### Potential Terraform Configuration

```hcl
resource "azurerm_linux_web_app" "example" {
  name                = "example"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_service_plan.example.location
  service_plan_id     = azurerm_service_plan.example.id
  public_network_access = false
  site_config {}
}
```

### References

https://learn.microsoft.com/en-us/azure/templates/microsoft.web/sites?pivots=deployment-language-arm-template#arm-template-resource-definition
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_web_app

**Comment by rcskosir** [comment] 2023-07-03 13:46
Thanks for taking the time to submit this issue. It looks like this is a duplicate of #20415. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of #20415.
This is also being worked on in the following PR: 22352.

**Closed by rcskosir** 2023-07-03 13:46 UTC
Labels: duplicate, enhancement, service/web-app
