### ISSUE TITLE
azurerm_servicebus_queue no longer works in any version above 3.39.0 (with .NET 7 support)

### ISSUE THREAD

**Issue by PetteriPertola** [hashicorp/terraform-provider-azurerm#20779] opened 2023-03-03 13:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.9

### AzureRM Provider Version

3.46.0

### Affected Resource(s)/Data Source(s)

azurerm_servicebus_queue

### Terraform Configuration Files

```hcl
resource "azurerm_servicebus_namespace" "service_bus" {
  name = "my-service-bus"
  location = "North Europe"
  resource_group_name = "my-resource-group"
  sku = "Premium"
  capacity = 1
}

resource "azurerm_servicebus_queue" "my_queue" {
  name                = "my-test-queue"
  namespace_id = azurerm_servicebus_namespace.service_bus.id
  max_size_in_megabytes = 1024
}
```

### Debug Output/Panic Output

```shell
Error: parsing "/subscriptions/<YOUR-SUBSCRIPTION>/resourceGroups/my-resource-group/providers/microsoft.servicebus/namespaces/my-service-bus/queues/my-test-queue": parsing segment "staticMicrosoftServiceBus": expected the segment "microsoft.servicebus" to be "Microsoft.ServiceBus"
│ 
│   with azurerm_servicebus_queue.my_queue in resource "azurerm_servicebus_queue" "my_queue"
```

### Expected Behaviour

The terraform plan step should pass.

### Actual Behaviour

Terraform plan step fails with the above error message

### Steps to Reproduce

1. Add a new service bus queue into an existing service bus configuration
2. Run terraform plan step

**Comment by xiaxyi** [comment] 2023-03-06 02:18
Thanks @PetteriPertola for raising this issue, can you let me know the value of the servicebus namespace id in your state?

**Comment by PetteriPertola** [comment] 2023-03-06 09:33
> Thanks @PetteriPertola for raising this issue, can you let me know the value of the servicebus namespace id in your state?

Hi,

Sure, this is the id (I have anonymized subscription id, and our resource group names): 

/subscriptions/<SUBSCRIPTION_ID>/resourceGroups/my-resource-group/providers/Microsoft.ServiceBus/namespaces/my-service-bus

It looks like this classic CapitalLetters problem in Microsoft.ServiceBus vs microsoft.servicebus

**Comment by xiaxyi** [comment] 2023-03-07 05:19
@PetteriPertola I can't reproduce this issue, the Microsft.ServiceBus is behaving as expected using 3.46 provider.

Checking the provider source code in 3.46 provider, we are using namespace id + queue name to provision the queue id, the Microsft.ServiceBus is extracted from servicebus namespace id. Can you share the whole story with me, for example, when did the namespace created?

**Comment by PetteriPertola** [comment] 2023-03-07 11:10
> @PetteriPertola I can't reproduce this issue, the Microsft.ServiceBus is behaving as expected using 3.46 provider.
> 
> Checking the provider source code in 3.46 provider, we are using namespace id + queue name to provision the queue id, the Microsft.ServiceBus is extracted from servicebus namespace id. Can you share the whole story with me, for example, when did the namespace created?

Interesting. Our ServiceBus was created on 9 Feb 2021 and last updated 10 June 2022 according to Azure portal. Pretty sure the latter date is when I first imported the existing one into our terraform state, and then subsequently updated some tags or similar on it. 

If I look at the Resource JSON on Azure portal, I also notice that the id is:
"id": "/subscriptions/<SUBSCRIPTION_ID>/resourceGroups/my-resource-group/providers/Microsoft.ServiceBus/namespaces/my-service-bus",

Does this imply that I should somehow refresh the state in my Terraform file? Any suggestions on how to achieve that?

**Comment by tombuildsstuff** [comment] 2023-03-07 11:52
@PetteriPertola 

> Interesting. Our ServiceBus was created on 9 Feb 2021 and last updated 10 June 2022 according to Azure portal. Pretty sure the latter date is when I first imported the existing one into our terraform state, and then subsequently updated some tags or similar on it.

Sounds like this resource has been imported using the incorrect Resource ID casing, which would match the error message being returned here:

> Error: parsing "/subscriptions/<YOUR-SUBSCRIPTION>/resourceGroups/my-resource-group/providers/microsoft.servicebus/namespaces/my-service-bus/queues/my-test-queue": parsing segment "staticMicrosoftServiceBus": expected the segment "microsoft.servicebus" to be "Microsoft.ServiceBus"

The Resource ID format for each Resource can be found in the `import` documentation, for [example for the `azurerm_servicebus_queue` resource](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/servicebus_queue#import):

> terraform import azurerm_servicebus_queue.example /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/mygroup1/providers/Microsoft.ServiceBus/namespaces/sbns1/queues/snqueue1

However the error message above is signifying that the `Microsoft.ServiceBus` segment is being specified as `microsoft.servicebus` - whilst older versions of the Provider didn't validate the casing of this segment (which allowed this resource to be imported in the wrong casing) - newer versions expect this to match. As such you'll need to update the Resource ID casing being used here to unblock this - the easiest way to do that is via `terraform state rm azurerm_servicebus_queue.[name]` and then `terraform import azurerm_servicebus_queue.[name] [ID (in the casing per above)]` - at which point `terraform plan` should run as expected.

Whilst I appreciate this error message isn't as clear as it could be, we're working to improve the error message that's returned from the ID parser here, and [that's being tracked in this Pull Request](https://github.com/hashicorp/go-azure-helpers/pull/155) which should hopefully make this clearer in the future.

Since this issue will be fixed by updating the Resource ID for this Resource I'm going to close this issue for the moment, but if that doesn't work for you then please let us know and we'll take another look.

Thanks!

**Closed by tombuildsstuff** 2023-03-07 11:52 UTC
Labels: question, service/service-bus

**Comment by PetteriPertola** [comment] 2023-03-07 14:25
Thanks, it worked after re-importing the state.
