### ISSUE TITLE
Error: The terraform-provider-azurerm_v3.96.0_x5 plugin crashed!

### ISSUE THREAD

**Issue by jrdevops1** [hashicorp/terraform-provider-azurerm#26285] opened 2024-06-10 14:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.5

### AzureRM Provider Version

3.96.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "example-storage-account" {
  name                            = "contosostorage"
  resource_group_name             = "contoso-rg"
  location                        = "West Europe"
  account_tier                    = "Standard"
  account_kind                    = "StorageV2"
  account_replication_type        = "GRS"
  enable_https_traffic_only       = true
  allow_nested_items_to_be_public = false
  public_network_access_enabled   = true
  min_tls_version                 = "TLS1_2"

  network_rules {
    default_action             = "Deny"
    bypass                     = ["AzureServices", "Logging", "Metrics"]
    ip_rules                   = []
    virtual_network_subnet_ids = []
  }

  blob_properties {
    delete_retention_policy {
      days = 30
    }
    container_delete_retention_policy {
      days = 30
    }
  }
  lifecycle {
    ignore_changes = [network_rules[0].private_link_access]
  }
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: Request cancelled
│ 
│   with azurerm_storage_account.example-storage-account,
│   on storage.tf line 5, in resource "azurerm_storage_account" "example-storage-account":
│    5: resource "azurerm_storage_account" "example-storage-account" {
│ 
│ The plugin.(*GRPCProvider).ReadResource request was cancelled.

Stack trace from the terraform-provider-azurerm_v3.96.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0xbe50ef]

goroutine 201 [running]:
github.com/hashicorp/go-azure-sdk/sdk/client.(*Response).Unmarshal(0xc001781ba0, {0x737ec40, 0xc002748b40?})
	github.com/hashicorp/go-azure-sdk/sdk@v0.20240314.1083835/client/client.go:171 +0x4f
github.com/tombuildsstuff/giovanni/storage/2023-11-03/blob/accounts.Client.GetServiceProperties({0xc001770840?}, {0x904d1c8, 0xc001c81f10}, {0xc0017c9a5c?, 0xf})
	github.com/tombuildsstuff/giovanni@v0.25.1/storage/2023-11-03/blob/accounts/get_service_properties.go:42 +0x235
github.com/hashicorp/terraform-provider-azurerm/internal/services/storage.resourceStorageAccountRead(0xc001fddb80, {0x7826420?, 0xc000640d80})
	github.com/hashicorp/terraform-provider-azurerm/internal/services/storage/storage_account_resource.go:2333 +0x2c2f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x904d120?, {0x904d120?, 0xc002520570?}, 0xd?, {0x7826420?, 0xc000640d80?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:783 +0x163
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0019f35e0, {0x904d120, 0xc002520570}, 0xc00138c410, {0x7826420, 0xc000640d80})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:1089 +0x552
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00081b5a8, {0x904d120?, 0xc002520480?}, 0xc002628fc0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/grpc_provider.go:649 +0x48a
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc001a84e60, {0x904d120?, 0xc00247bcb0?}, 0xc002518cc0)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/tf5server/server.go:789 +0x48b
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x8430e20?, 0xc001a84e60}, {0x904d120, 0xc00247bcb0}, 0xc001c818f0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:431 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003441e0, {0x9074920, 0xc001c44000}, 0xc0024799e0, 0xc001b3d5c0, 0xe988c68, 0x0)
	google.golang.org/grpc@v1.58.3/server.go:1374 +0xde7
google.golang.org/grpc.(*Server).handleStream(0xc0003441e0, {0x9074920, 0xc001c44000}, 0xc0024799e0, 0x0)
	google.golang.org/grpc@v1.58.3/server.go:1751 +0x9e7
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.58.3/server.go:986 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 39
	google.golang.org/grpc@v1.58.3/server.go:997 +0x145

Error: The terraform-provider-azurerm_v3.96.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.


##[error]Bash exited with code '1'.
```

### Expected Behaviour

When running a terraform plan in the azure devops pipeline, there should not be an error with the storage account. I ran the plan under a different folder to where the storage account configuration is located and the error has occurred.

### Actual Behaviour

Panic Output above, the terraform plan errors out

### Steps to Reproduce

1. `terraform plan`

**Comment by rcskosir** [comment] 2024-06-10 17:01
@jrdevops1 Thanks for taking the time to open this issue. This looks like it is a duplicate of an older issue that has already been resolved. Please see issue #25314 and the linked merged PRs that should have resolved this issue in more recent versions of the provider. As such, I recommend upgrading to the latest version of the provider and I am going to mark this issue as a duplicate and close it. If you find after upgrading that you are still seeing this crash, please let us know! Thanks

**Closed by rcskosir** 2024-06-10 17:01 UTC
Labels: bug, duplicate, crash, service/storage, v/3.x
