### ISSUE TITLE
identity block not implemented in azurerm_app_service_environment_v3

### ISSUE THREAD

**Issue by Dragonsbane** [hashicorp/terraform-provider-azurerm#18417] opened 2022-09-16 19:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.8

### AzureRM Provider Version

3.21.1

### Affected Resource(s)/Data Source(s)

azurerm_app_service_environment_v3

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "exampleRG1"
  location = "West Europe"
}

resource "azurerm_virtual_network" "example" {
  name                = "example-vnet"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  address_space       = ["10.0.0.0/16"]
}

resource "azurerm_subnet" "example" {
  name                 = "example-subnet"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefixes     = ["10.0.2.0/24"]

  delegation {
    name = "Microsoft.Web.hostingEnvironments"
    service_delegation {
      name    = "Microsoft.Web/hostingEnvironments"
      actions = ["Microsoft.Network/virtualNetworks/subnets/action"]
    }
  }
}

resource "azurerm_user_assigned_identity" "example" {
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  name = "exampleid"
}

resource "azurerm_app_service_environment_v3" "example" {
  name                = "example-asev3"
  resource_group_name = azurerm_resource_group.example.name
  subnet_id           = azurerm_subnet.example.id
  internal_load_balancing_mode = "Web, Publishing"

  cluster_setting {
    name  = "DisableTls1.0"
    value = "1"
  }

  cluster_setting {
    name  = "InternalEncryption"
    value = "true"
  }

  cluster_setting {
    name  = "FrontEndSSLCipherSuiteOrder"
    value = "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
  }

  identity {
    identity_ids = [azurerm_user_assigned_identity.example.id]
    type = "UserAssigned"
  }
}
```

### Debug Output/Panic Output

```shell
Its not related to the provider misbehaving.
```

### Expected Behaviour

The resource to be created with the assigned identity.

### Actual Behaviour

│ Error: Unsupported block type
│
│   on main.tf line 55, in resource "azurerm_app_service_environment_v3" "example":
│   55: identity {
│
│ Blocks of type "identity" are not expected here.

### Steps to Reproduce

Just try to apply the configuration.

**Comment by fa-bwilliams** [comment] 2022-12-06 20:24
Same issue here. Seems like this got dropped.

**Comment by rubenaster** [comment] 2022-12-07 06:30
I hope not, since this is more or less a general feature of many Azure services and mainly works the same for all of them.

We currently use user-assigned identities as a workaround but still, system-assigned would be more feature-complete.

**Comment by fa-bwilliams** [comment] 2022-12-07 13:49
I think this might be more of a Microsoft issue because I tried to instead use azapi_update_resource and could not get that to work either. It seems that "Identity" is not even a valid configurable property on 'Microsoft.Web/hostingEnvironments@2022-03-01'. 

I had the same thought about using a user identity as a workaround instead and you confirmed that with your previous statement. Going to try that path today.

**Comment by tombuildsstuff** [comment] 2022-12-07 14:20
👋  hey @Dragonsbane @rubenaster @fa-bwilliams 

Thanks for opening this issue.

Taking a look through here as @fa-bwilliams has mentioned unfortunately this appears to be more of an API limitation that anything we can look to support in Terraform - since this also [doesn't exist within the Swagger definition for App Service Environments](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/web/resource-manager/Microsoft.Web/stable/2022-03-01/AppServiceEnvironments.json#LL1).

As such I'd [recommend opening an issue on the `Azure/azure-rest-api-specs` repository](https://github.com/Azure/azure-rest-api-specs/issues) where someone from the Service Team should be able to look into adding support for this feature - once that's available in the Azure API (and the associated Swagger definitions) then we can take a look into supporting this in Terraform.

However since this is currently blocked on the lack of functionality within the Azure API I'm going to close this issue for the moment - but feel free to cross-link this issue and we can take a look into supporting it once this becomes available within the Azure API.

Thanks!

**Closed by tombuildsstuff** 2022-12-07 14:20 UTC
Labels: question, service/app-service, upstream/microsoft
