### ISSUE TITLE
azurerm_virtual_machine_data_disk_attachment failing to attach disk to VMSS instance

### ISSUE THREAD

**Issue by anujtechnet** [hashicorp/terraform-provider-azurerm#14580] opened 2021-12-10 22:12 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem description
We would like to use terraform for attaching managed data disks to VMSS instances outside of scale-set model so that in case of a disaster or vertical scaling we can safely detach them and attach to new VMSS instances. We have tried  azurerm_virtual_machine_data_disk_attachment resource which worked fine with a standalone VM but failed to attach disk to a VMSS instance. Not sure if its a bug or azurerm_virtual_machine_data_disk_attachment is not intended to perform operations on VMSS?  

Terraform apply successfully created the disk but failed to attach it to the VMSS instance with below error :- 
```hcl
azurerm_managed_disk.example: Creating...
azurerm_managed_disk.example: Creation complete after 6s [id=/subscriptions/xxxxxxxxx/resourceGroups/xxxxxxxxx/providers/Microsoft.Compute/disks/datadisktest01]
azurerm_virtual_machine_data_disk_attachment.example: Creating...
╷
│ Error: Plugin did not respond
│
│   with azurerm_virtual_machine_data_disk_attachment.example,
│   on main.tf line 25, in resource "azurerm_virtual_machine_data_disk_attachment" "example":
│   25: resource "azurerm_virtual_machine_data_disk_attachment" "example" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
```

### Terraform (and AzureRM Provider) Version
* `Terraform v1.0.5 on darwin_amd64/azurerm ~> 2.83`

### Affected Resource(s)

* `azurerm_virtual_machine_data_disk_attachment`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
terraform {
  required_providers {
      azurerm = {
          source = "hashicorp/azurerm"
          version = "~> 2.83"
      }
  }
}

provider "azurerm" {
    features {}
}

resource "azurerm_managed_disk" "example" {
  name                 = "datadisktest01"
  location             = "East US"
  resource_group_name  = "rg-xxxxxxx
  storage_account_type = "Premium_LRS"
  create_option        = "Empty"
  disk_size_gb         = 512
}

resource "azurerm_virtual_machine_data_disk_attachment" "example" {
  managed_disk_id    = azurerm_managed_disk.example.id
  virtual_machine_id = "/subscriptions/xxxxxxxxx/resourceGroups/xxxxxxxx/providers/Microsoft.Compute/virtualMachineScaleSets/XXXXXXXX/virtualMachines/XXXXXXXXXX"
  lun                = "10"
  caching            = "ReadWrite"
}
```

### Panic Output

Stack trace from the terraform-provider-azurerm_v2.83.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5a2bb29]

goroutine 159 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/compute.resourceVirtualMachineDataDiskAttachmentCreateUpdate(0xc001875b00, 0x6a4a1a0, 0xc0013c3880, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/services/compute/virtual_machine_data_disk_attachment_resource.go:101 +0x169
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0008c5880, 0x7b1ce28, 0xc001be6b00, 0xc001875b00, 0x6a4a1a0, 0xc0013c3880, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:318 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0008c5880, 0x7b1ce28, 0xc001be6b00, 0xc0000ec2a0, 0xc001b53e00, 0x6a4a1a0, 0xc0013c3880, 0x0, 0x0, 0x0, ...)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:456 +0x67b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000bed9c8, 0x7b1ce28, 0xc001be6b00, 0xc001d97b30, 0xc001be6b00, 0x6f7ac40, 0xc000860200)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:955 +0x8ef
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc0010fc740, 0x7b1ced0, 0xc001be6b00, 0xc0000ec150, 0xc0010fc740, 0xc0008602a0, 0xc001181ba0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/server/server.go:332 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x6f7ac40, 0xc0010fc740, 0x7b1ced0, 0xc0008602a0, 0xc001bd6600, 0x0, 0x7b1ced0, 0xc0008602a0, 0xc001b82f00, 0x4bb)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000234a80, 0x7b705b8, 0xc0004b1200, 0xc001c90000, 0xc0015c24e0, 0xb872ac0, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000234a80, 0x7b705b8, 0xc0004b1200, 0xc001c90000, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1617 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0014cae20, 0xc000234a80, 0x7b705b8, 0xc0004b1200, 0xc001c90000)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:940 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:938 +0x1fd

Error: The terraform-provider-azurerm_v2.83.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment] 2021-12-10 22:22
hi @anujtechnet 

Thanks for opening this issue.

This resource is intended to be used with a Virtual Machine rather than a VM within a VMSS - as such whilst this is crashing (which should be fixed, and is tracked in another issue) this is unfortunately working as intended at this time - and as such I'm going to close this issue for the moment.

Thanks!

**Closed by tombuildsstuff** 2021-12-10 22:22 UTC
Labels: question, service/vmss

**Comment by anujtechnet** [comment] 2021-12-11 01:43
Hi @tombuildsstuff,

Thanks for the response. Is there any plan to release resource for performing data disk operations on VMSS uniform api? 

Thanks,
Anuj

**Comment by tombuildsstuff** [comment] 2021-12-13 17:14
@anujtechnet we've not got plans to do so at this time, but if you'd like to open a feature request it's something we could consider (as a separate resource) in the future.

**Comment by anujtechnet** [comment] 2021-12-14 17:28
Hi @tombuildsstuff,

Thanks, I have opened a feature request for this:- https://github.com/wagtail/wagtail/issues/7784 

Thanks,
Anuj
