### ISSUE TITLE
regression - azurerm_lb - manually adding frontend_ip_configurations to an existing LB results in perpetual diffs

### ISSUE THREAD

**Issue by faust64** [hashicorp/terraform-provider-azurerm#17841] opened 2022-08-02 08:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.0.7

### AzureRM Provider Version

3.16

### Affected Resource(s)/Data Source(s)

azurerm_lb

### Terraform Configuration Files

```hcl
variable "frontends" {
  type = map(
    object({
      # ...
      subnet_id = string
    })
  )
}

resource "azurerm_lb" "loadbalancer" {
  name                = "my-lb"
  location            = "northeurope"
  resource_group_name = "some-resourcegroup"
  sku                 = "Standard"

  dynamic "frontend_ip_configuration" {
    for_each = var.frontends
    content {
      name = frontend_ip_configuration.key
      subnet_id = frontend_ip_configuration.value.subnet_id
      private_ip_address_allocation = "Dynamic"
      public_ip_address_id = null
      zones = [ "1", "2", "3" ]
    }
  }
}
```

### Debug Output/Panic Output

```shell
# module.xxx.azurerm_lb.loadbalancer will be updated in-place
  ~ resource "azurerm_lb" "loadbalancer" {
        id                   = "/subscriptions/xxx/resourceGroups/some-resourcegroup/providers/Microsoft.Network/loadBalancers/my-lb"
        name                 = "my-lb"

      ~ frontend_ip_configuration {
            id                            = "/subscriptions/xxx/resourceGroups/some-resourcegroup/providers/Microsoft.Network/loadBalancers/my-lb/frontendIPConfigurations/prod"
          ~ name                          = "prod" -> "preprod"
          ~ subnet_id                     = "/subscriptions/xxx/resourceGroups/some-resourcegroup/providers/Microsoft.Network/virtualNetworks/my-vnet/subnets/subnet-prod" -> (known after apply)
            # (8 unchanged attributes hidden)
        }
      ~ frontend_ip_configuration {
            id                            = "/subscriptions/xxx/resourceGroups/some-resourcegroup/providers/Microsoft.Network/loadBalancers/my-lb/frontendIPConfigurations/preprod"
          ~ name                          = "preprod" -> "prod"
          ~ subnet_id                     = "/subscriptions/xxx/resourceGroups/some-resourcegroup/providers/Microsoft.Network/virtualNetworks/my-vnet/subnets/subnet-preprod" -> (known after apply)
            # (8 unchanged attributes hidden)
        }
    }
```

### Expected Behaviour

Following up on a case I previously filed here: https://github.com/hashicorp/terraform-provider-azurerm/issues/17818
Since azurerm-3 introduces a regression, that prevents me from either adding or removing frontend_ip_configurations from existing azurerm_lb programatically .... Then I wanted to proceed with my changes manually, from Azure portal, before aligning terraform state.

When I add my frontend ip configuration manually, then align my code with this change, the next terraform plan will show me a diff, switching frontend ip names/subnet_ids.
As reported earlier, this is something we would see with azurerm-2 as well: https://github.com/hashicorp/terraform-provider-azurerm/issues/17809
Although with azurerm-2: you would see that diff once. You apply this, and next plan won't show anything changing.

### Actual Behaviour

As of azurerm-3, when I apply the diff above: nothing changes.
Terraform apply output suggests it's done reconfiguring my loadbalancers. Frontend didn't move in Azure, same subnets, names, same IPs, ...
Now, I would run another terraform plan. Only to realize: nothing happened. I'm stuck with that diff.

Which is kind of problematic. As I would then re-use azurerm_lb outputs setting up DNS records.
azurerm_lb lists my frontend IPs in the order that "should" have been configured, according to my diff. Thus, with the sample shared here: my preprod DNS record would point to the prod IP, and the prod DNS record would point to the preprod record.

### Steps to Reproduce

1. Deploy an azurerm_lb, with at least one frontend_ip_configuration.
2. Once applied: try to add a frontend_ip_configuration
3. At that stage, note that terraform plan would force-recreate that LB: don't do this (another regression, see https://github.com/hashicorp/terraform-provider-azurerm/issues/17818)
4. Since azurerm-3 can't add that frontend without recreating the LB: login to azure portal, locate your LB: add a new frontend_ip_configuration
5. align your code with that change
6. terraform plan would show a diff, swapping frontend ip configurations (looks like frontends are alphabetically sorted)
7. apply that diff.
8. Re-run terraform plan. Notice that nothing changed. Same diff. We can repeat steps 6-7 indefinitely: nothing would happend, despite plan diff suggesting otherwise

**Comment by faust64** [comment] 2022-10-31 06:40
still no news
still a regression
that was introducing upgrading from azurerm-2, to azurerm-3
I am aware of https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/3.0-upgrade-guide#behavioural-updates
Which is just wrong, when using dynamic frontends

**Comment by tombuildsstuff** [comment] 2022-10-31 08:14
Duplicate of #17818, consolidating this into that issue.

**Closed by tombuildsstuff** 2022-10-31 08:14 UTC
Labels: duplicate, question
