### ISSUE TITLE
Cannot add to ARM based WVD with Terraform and backend deployment

### ISSUE THREAD

**Issue by jparr93** [hashicorp/terraform-provider-azurerm#9361] opened 2020-11-17 15:08 UTC
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Latest

### Affected Resource(s)

azurerm_virtual_desktop_host_pool
azurerm_virtual_machine_extension

### Terraform Configuration Files

```hcl

resource "azurerm_virtual_desktop_host_pool" "pooled" {
  name                = var.hostpool_name
  location            = var.hostpool_region
  resource_group_name = var.resource_group_name
  type                = var.hostpool_type
  load_balancer_type  = var.hostpool_loadbalancer_type
  tags                = var.resource_tags

  registration_info {
    expiration_date = timeadd("${local.image_build_time}", "5h")
  }
}
resource "azurerm_virtual_machine_extension" "additional_session_host_dscextension" {
  count                      = var.rdsh_count
  name                       = "${var.vm_prefix}${count.index +1}-wvd_dsc"
  virtual_machine_id         = "${azurerm_virtual_machine.main.*.id[count.index]}"
  publisher                  = "Microsoft.Powershell"
  type                       = "DSC"
  type_handler_version       = "2.73"
  auto_upgrade_minor_version = true
  depends_on                 = ["azurerm_virtual_machine_extension.domainJoin"]

 settings = <<SETTINGS
        {
            "ModulesUrl":"https://wvdportalstorageblob.blob.core.windows.net/galleryartifacts/Configuration_7-20-2020.zip",
            "ConfigurationFunction":"Configuration.ps1\\AddSessionHost",
            "properties": {
                "hostPoolName": "${azurerm_virtual_desktop_host_pool.pooled.name}",
                "registrationInfoToken": "${azurerm_virtual_desktop_host_pool.pooled.registration_info[0].token}"
            }
        }
    SETTINGS
}
```

### Expected Behaviour

To add additional session hosts to the existing hostpool by creating a new token.

### Actual Behaviour

2020-11-17T14:49:28.0752799Z [1m[31mError: [0m[0m[1mProvider produced inconsistent final plan[0m
2020-11-17T14:49:28.0753085Z 
2020-11-17T14:49:28.0755676Z [0mWhen expanding the plan for
2020-11-17T14:49:28.0756061Z azurerm_virtual_machine_extension.additional_session_host_dscextension[3] to
2020-11-17T14:49:28.0756548Z include new values learned so far during apply, provider
2020-11-17T14:49:28.0756975Z "registry.terraform.io/hashicorp/azurerm" produced an invalid new value for
2020-11-17T14:49:28.0757424Z .settings: was cty.StringVal("        {\r\n
2020-11-17T14:49:28.0757804Z \"ModulesUrl\":\"https://wvdportalstorageblob.blob.core.windows.net/galleryartifacts/Configuration_7-20-2020.zip\",\r\n
2020-11-17T14:49:28.0758238Z \"ConfigurationFunction\":\"Configuration.ps1\\\\AddSessionHost\",\r\n
2020-11-17T14:49:28.0758596Z \"properties\": {\r\n                \"hostPoolName\": \"terra-hostpool\",\r\n
2020-11-17T14:49:28.0758920Z \"registrationInfoToken\":
2020-11-17T14:49:28.0760386Z \"eyJhbGciOiJSUzI1NiIsImtpZCI6IjVGRjc0N0JFODhCREFCMjQ0ODU1NkFGQjQwRTk3MkUyQUVGNjM2ODciLCJ0eXAiOiJKV1QifQ.eyJSZWdpc3RyYXRpb25JZCI6IjNhNTM5M2M4LWI2NDctNDk1Ni05OGZjLWQyMDRhYWJmMjhiMyIsIkJyb2tlclVyaSI6Imh0dHBzOi8vcmRicm9rZXItZy11cy1yMC53dmQubWljcm9zb2Z0LmNvbS8iLCJEaWFnbm9zdGljc1VyaSI6Imh0dHBzOi8vcmRkaWFnbm9zdGljcy1nLXVzLXIwLnd2ZC5taWNyb3NvZnQuY29tLyIsIkVuZHBvaW50UG9vbElkIjoiMGYxN2I0MDMtMDdjNS00MGUzLWI1M2MtY2YwNTBkMDVlMTQ0IiwiR2xvYmFsQnJva2VyVXJpIjoiaHR0cHM6Ly9yZGJyb2tlci53dmQubWljcm9zb2Z0LmNvbS8iLCJHZW9ncmFwaHkiOiJVUyIsIm5iZiI6MTYwNTYyMjQ5MiwiZXhwIjoxNjA1NjQwNDg2LCJpc3MiOiJSREluZnJhVG9rZW5NYW5hZ2VyIiwiYXVkIjoiUkRtaSJ9.wafKACZNcMt-Npdmrp7D-DbS9YNJzgFWSyCuc21HTE9xdXi_v6eTK9owUdjwNf0rnPsbaoTJmgqrHR7yW8iWrYpREk3b32rFn1JfV6cVxsc_1ZgaRhRC2erNsJFBUJMBoClRunQr25wCGaZm93GB9hcilVy_0i4Smu00_SS4ZDm6ctRM3mHBs6kwsripyWltpAkD0Xd6iwRRpNw5ZiyRDku95noCl2XcgexK1fCa4aM6dYrOlFmFtmn6BN0gy4UaHx2eXnyOEdIxb9mBVqMvOrPxPhHVKJ_rUd8QsxtKUhEraFCA3zZ9KyHA5RGvpsOdKHT6AG4QPKiVsGJHGFQSmg\"\r\n
2020-11-17T14:49:28.0762204Z }\r\n        }\r\n"), but now cty.StringVal("        {\r\n
2020-11-17T14:49:28.0762634Z \"ModulesUrl\":\"https://wvdportalstorageblob.blob.core.windows.net/galleryartifacts/Configuration_7-20-2020.zip\",\r\n
2020-11-17T14:49:28.0763035Z \"ConfigurationFunction\":\"Configuration.ps1\\\\AddSessionHost\",\r\n
2020-11-17T14:49:28.0763428Z \"properties\": {\r\n                \"hostPoolName\": \"terra-hostpool\",\r\n
2020-11-17T14:49:28.0763715Z \"registrationInfoToken\":
2020-11-17T14:49:28.0765264Z \"eyJhbGciOiJSUzI1NiIsImtpZCI6IjVGRjc0N0JFODhCREFCMjQ0ODU1NkFGQjQwRTk3MkUyQUVGNjM2ODciLCJ0eXAiOiJKV1QifQ.eyJSZWdpc3RyYXRpb25JZCI6IjBjZWQ0YzA2LTU1ZjgtNGMyMS1hYTdmLTc3MmYwYTc0MzI4OSIsIkJyb2tlclVyaSI6Imh0dHBzOi8vcmRicm9rZXItZy11cy1yMC53dmQubWljcm9zb2Z0LmNvbS8iLCJEaWFnbm9zdGljc1VyaSI6Imh0dHBzOi8vcmRkaWFnbm9zdGljcy1nLXVzLXIwLnd2ZC5taWNyb3NvZnQuY29tLyIsIkVuZHBvaW50UG9vbElkIjoiMGYxN2I0MDMtMDdjNS00MGUzLWI1M2MtY2YwNTBkMDVlMTQ0IiwiR2xvYmFsQnJva2VyVXJpIjoiaHR0cHM6Ly9yZGJyb2tlci53dmQubWljcm9zb2Z0LmNvbS8iLCJHZW9ncmFwaHkiOiJVUyIsIm5iZiI6MTYwNTYyNDMxMCwiZXhwIjoxNjA1NjQyMzA3LCJpc3MiOiJSREluZnJhVG9rZW5NYW5hZ2VyIiwiYXVkIjoiUkRtaSJ9.omstYsENpgTxGjyfT6djphrqPJnsDKoJ-DTZ09e1ZQ17PfWp5bIata4AesCamP-1wyekmG0g1WEEUa4XztzfABY98U1AunosVpaHVkjPD9RIUO8YfclKBXvGjDHRWAlVFd-y-8ynEIOYDO_d9BwZeIfYRmZa61qLr_CcMYx_QejvSrUuAlO50BZ-QOli_BUeBRhb8K-5aVLn4auccf_8j7gtdc6TSDIJoXxL5QddnGIpL85fSoO940dsrz4GN-hd64Vrf3gAUr4zQSo5yWVtTo4qPn4LHs3Yuj7MHsXcytuAwJtnFjAgF67D5klMFW4_7eeDCvmJPxGN_Qkf9okRow\"\r\n
2020-11-17T14:49:28.0766758Z }\r\n        }\r\n").
2020-11-17T14:49:28.0766878Z 
2020-11-17T14:49:28.0767132Z This is a bug in the provider, which should be reported in the provider's own
2020-11-17T14:49:28.0767551Z issue tracker.

### Steps to Reproduce

Create a hostpool and virtual machine deployment with an Terraform backend.

* #0000

**Comment by tormath1** [comment] 2020-11-24 16:07
Hi @jparr93,

If your `local.image_build_time` is based on a `timestamp`, you'll get a get a different value between each run which leads to an inconsistent plan since your resource `additional_session_host_dscextension` relies on this value.

To circumvent this issue, you can apply this Terraform lifecycle policy on the `pooled` resource :

```diff
+  lifecycle {
+    ignore_changes = [
+      registration_info,
+    ]
+  }
```

**Comment by jparr93** [comment] 2020-11-25 15:37
Hi @tormath1 , how will that work though, if i run the code now and then in the months time, the registration info would have expired?

**Comment by justin-ldn** [comment] 2021-01-06 20:08
@jparr93 fwiw this works less noisily..:

```
resource "time_rotating" "wvd_token" {
  rotation_days = 30
}
```
...
```
  registration_info {
    expiration_date = time_rotating.wvd_token.rotation_rfc3339
  }
```

**Comment by jparr93** [comment] 2021-01-15 09:28
@justin-ldn does this work in a CI/CD environment, so lets say I spun up 2 vms, then 4 days later, decided to add another. In my testing i have found that the tfstate file complains about the reg token changing?

**Comment by justin-ldn** [comment] 2021-01-15 09:32
@jparr93 Yes we are using it in a CI/CD. The token when using time_rotating would change when your run ticks over the 30 days - the expiration_date is set to a fixed point in time (initial/expired run + 30d) as the time_rotating resource will change on that cadence, so you'd get up to 12 token changes/state drifts a year.

**Comment by jparr93** [comment] 2021-01-15 09:36
@justin-ldn Okay, that's good to hear, does your tfstate file not complain after 30days when the token changes?

**Comment by justin-ldn** [comment] 2021-01-15 10:33
@jparr93 The time_rotating resource will change, but ignore_changes covers the registration_info block, which is a bit messy (I guess hence your request for an upstream fix?).. I guess the core issue is if increasing count, then earlier hosts will have a different token for their setup than subsequent, which I haven't tested.

**Comment by Glennoste** [comment] 2021-06-03 19:04
@jparr93 and @justin-ldn have you guys tested adding a new host after the 30 days have expired? In my scenario it does not work, by using the ignore changes it does not update/produce a new token after those 30 days. :/ Adding new hosts will work fine during those 30 days, but afterwards it always fails.

My current workaround is as follows when the 30 days have expired:
1) remove the ignore changes
2) do a plan + apply (which will fail, but this will update the id of the rotating token)
3) add the ignore changes again
4) again a plan + apply (which will work again now for 30 days)

**Comment by Blankf** [comment] 2021-08-24 10:09
Any update maybe on this topic? running into the same issues now.

**Comment by tombuildsstuff** [comment] 2021-11-15 13:57
hi @jparr93 @Glenno92 @Blankf 

Thanks for opening this issue.

Taking a look through this appears to be a duplicate of #13793 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #13793 for updates?

Thanks!

**Closed by tombuildsstuff** 2021-11-15 13:57 UTC
Labels: bug, service/virtual-desktops
