### ISSUE TITLE
On enabling Work load identity the client secret and client key is not generating

### ISSUE THREAD

**Issue by prajwaldc600** [hashicorp/terraform-provider-azurerm#24786] opened 2024-02-05 18:16 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.2

### AzureRM Provider Version

3.90

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
resource "tls_private_key" "k8s_ssh_key" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "azurerm_kubernetes_cluster" "k8s" {
  name                = "test-aks-cluster"
  location            = "westus3"
  resource_group_name = "test-rg"
  dns_prefix          = "test-aks-cluster"
  role_based_access_control_enabled = true
  
  oidc_issuer_enabled = true
  workload_identity_enabled = true
  local_account_disabled = true

  linux_profile {
    admin_username = "testuser"
    ssh_key {
      key_data = tls_private_key.k8s_ssh_key.public_key_openssh
    }
  }

  default_node_pool {
    name       = "default"
    node_count = 3
    vm_size    = "Standard_D2_v2"
    os_sku = "AzureLinux"
    temporary_name_for_rotation = "temp"
  }

  identity {
    type = "SystemAssigned"
  }
}
```

### Debug Output/Panic Output

```shell
"kube_config": [
          {
            "client_certificate": "",
            "client_key": "",
            "cluster_ca_certificate": "<Client_CA_Cert_Value>",
            "host": "<Host>",
            "password": "",
            "username": "clusterUser_test-aks-cluster"
          }
        ]
```

### Expected Behaviour

Client Key, and Client Certificate should not be blank as ssh key is provided in the inputs.

### Actual Behaviour

Client Key, and Client Certificate are coming as blank values.
This issue is happening only when work load identity is enabled.

### Steps to Reproduce

1. terraform apply
2. Verify the kube_config section in the output.

**Comment by stephybun** [comment] 2024-02-27 08:20
Thanks for raising this issue @prajwaldc600.

I was unable to reproduce this behaviour by toggling the `workload_identity_enabled` property alone. Looking at the config the property `local_account_disabled` is what's causing the absence of the client key and certificate. According to the [MSFT docs](https://learn.microsoft.com/en-us/azure/aks/manage-local-accounts-managed-azure-ad#disable-local-accounts) this is expected behaviour as well.

I'm going to close this issue since the workload identity property is working as expected. If you have questions regarding configuration please take a look at our [Community Discuss forum](https://discuss.hashicorp.com/).

**Closed by stephybun** 2024-02-27 08:20 UTC
Labels: service/kubernetes-cluster, v/3.x
