### ISSUE TITLE
Support for Azure API Management Basic v2	 & Standard v2 SKUs

### ISSUE THREAD

**Issue by IvanJosipovic** [hashicorp/terraform-provider-azurerm#23443] opened 2023-10-03 20:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

API Management supports a new pricing model which is substantially cheaper.
New SKUS: Basic v2	 & Standard v2

### New or Affected Resource(s)/Data Source(s)

azurerm_api_management

### References

https://azure.microsoft.com/en-ca/pricing/details/api-management/#pricing

**Comment by noderat** [comment] 2023-10-25 21:05
Related to #20939

**Comment by aw230012** [comment] 2023-12-05 20:41
Just also want to add that Azure will no longer support single tenant Basic and Standard v1 August 31, 2024. We'd like to test our dev environment which is Terraformed, but can't until this feature is completed.

**Comment by kewalaka** [comment] 2023-12-08 23:24
> Just also want to add that Azure will no longer support single tenant Basic and Standard v1 August 31, 2024. We'd like to test our environment switch to v2 but cannot until this feature is completed.

hi @aw230012 - your comment relates to the retirement of the stv1 platform, i.e. [this announcement](https://learn.microsoft.com/en-us/azure/api-management/breaking-changes/stv1-platform-retirement-august-2024).   It is already possible to deploy using the stv2 platform.

One thing to be aware of, when deploying within your own vnet you need to make sure you follow the pre-reqs here (counter-intuitively, it requires a public IP, otherwise the stv1 version is deployed).

for reference, see: https://techcommunity.microsoft.com/t5/azure-paas-blog/compute-platform-versions-for-azure-api-management-service/ba-p/2836971

(I can confirm this works, we're using the azurerm API management provider to deploy compute resource stv2.

This particular issue relates to the new pricing SKUs which are in preview, i.e. this announcement:
https://learn.microsoft.com/en-us/azure/api-management/v2-service-tiers-overview

As for the relationship between these two matters - they're unrelated, as per the FAQ in the above announcement, and directly linked here:
https://learn.microsoft.com/en-us/azure/api-management/v2-service-tiers-overview#q-whats-the-relationship-between-the-stv2-compute-platform-and-the-v2-tiers

**Comment by sven5** [comment] 2024-02-01 07:52
I also created an [issue for this requirement](https://github.com/hashicorp/terraform-provider-azurerm/issues/24377) and link it.

**Comment by tombuildsstuff** [comment] 2024-03-19 12:31
Duplicate of https://github.com/hashicorp/terraform-provider-azurerm/issues/24377 - since that issue was opened first I'm going to close this issue in favour of that one, would you mind subscribing to that issue for updates?

Thanks!

**Closed by tombuildsstuff** 2024-03-19 12:31 UTC
Labels: enhancement, service/api-management
