### ISSUE TITLE
Feature request: azurerm_app_service_settings separate resource.

### ISSUE THREAD

**Issue by glenjamin** [hashicorp/terraform-provider-azurerm#1212] opened 2018-05-07 22:05 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I found myself in a bit of a dependecy cycle just now that I couldn't break. I've hit a similar scenario a few times in the past too.

I created an `azurerm_app_service` app with managed service identity.
I then created a key vault with this app service identity in an access policy
I then needed to tell the app which key vault URI to use.

This creates a cycle, in this case I broke it by deriving the key vault URI from the name, but ideally I'd like to do this "properly".

When I used to use ARM template_deploy resources to do this I would split app creation and app config into two distinct resources.

This way I could create the application itself, then wire up the dependencies, then feed the config back in.

Is this something that could be added?

**Comment by StefanSchoof** [comment] 2019-09-16 08:09
I had a similar issue and solved it with [azurerm_key_vault_access_policy ](https://www.terraform.io/docs/providers/azurerm/r/key_vault_access_policy.html).

**Comment by syedhassaanahmed** [comment] 2020-05-14 09:15
In my case the issue wasn't solved by using a separate `azurerm_key_vault_access_policy`. [Here](https://github.com/syedhassaanahmed/tf-kv-appservice/blob/master/main.tf) is my template for repro.

**Comment by jochenrichter** [comment] 2021-05-17 14:38
Are there any news? The issue is open since 3 years now.
Microsoft describes in the 
[Key Vault reference](https://docs.microsoft.com/en-us/azure/app-service/app-service-key-vault-references#azure-resource-manager-deployment) documentation that you should seperate resources.

I'm running into the same issue as @syedhassaanahmed

**Comment by favoretti** [comment] 2021-08-18 10:20
Hi there and thank you for reporting this. Would using a custom identity not help in this case? I.e. create an identity, then create a keyvault that would have proper rights for this identity and then create an app with that identity.

IMO that's a better approach than externalizing `app_settings` into a separate resource, WDYT?

**Comment by t3mi** [comment] 2021-08-19 10:31
Support for using user assigned managed identities for Key Vault references was introduced only [recently](https://azure.microsoft.com/en-us/updates/general-availability-updates-to-secrets-configuration-options-in-app-service-and-azure-functions/) and it could be leveraged unless someone requires the use of system assigned managed identity only.

**Comment by favoretti** [comment] 2021-08-19 11:38
Good to close this one then?

**Comment by catriona-m** [comment] 2022-11-24 11:15
It looks like this issue has now been resolved by the use of identities so I will close this. However, feel free to reopen if you are still experiencing problems or there are other use cases for this. Thanks!

**Closed by catriona-m** 2022-11-24 11:15 UTC
Labels: new-resource, service/app-service
