### ISSUE TITLE
Extra `frontend_ip_configuration` block in `azurerm_application_gateway` cannot be detected

### ISSUE THREAD

**Issue by snowsky** [hashicorp/terraform-provider-azurerm#23252] opened 2023-09-13 03:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.5

### AzureRM Provider Version

3.70.0

### Affected Resource(s)/Data Source(s)

azurerm_application_gateway

### Terraform Configuration Files

```hcl
First I created a public IP configuration with private ip settings:


  frontend_ip_configuration {
    name                 = "public"
    public_ip_address_id = azurerm_public_ip.appgw.id
  }
```

The AGW can be created successfully and then I added private IP settings:

```
  frontend_ip_configuration {
    name                          = "private"
    subnet_id                     = data.azurerm_subnet.appgwsubnet.id
    private_ip_address            = "192.168.1.100"
    private_ip_address_allocation = "Static"
  }
```

No change was found. If I created both public and private IP settings together, it can work.
```


### Debug Output/Panic Output

```shell
No change was found.
```

### Expected Behaviour

Private IP address `192.168.1.100` will be added to AGW

### Actual Behaviour

Private IP address `192.168.1.100` was not added to AGW and only public IP is set as before.

### Steps to Reproduce

First create AGW with public IP only and add private IP configuration as above. The private IP cannot be added.

**Comment by rcskosir** [comment] 2023-09-13 18:03
Thanks for taking the time to submit this issue. Can you provide some more information around the issue that you are experiencing, like the expected behavior, actual behavior and the steps to reproduce?

**Comment by teowa** [comment] 2023-09-18 09:40
Hi @snowsky ,  I tried to reproduce the issue but seems I cannot with below config. The second `frontend_ip_configuration` can be provisioned successfully. Could you please provide more details about your config? Thanks.

<details>

<summary> tf config</summary>

```hcl
terraform {
  required_providers {
    azurerm = {
      version = "=3.70.0"
    }
  }
}
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "test-appgw"
  location = "West Europe"
}

resource "azurerm_virtual_network" "test" {
  name                = "test-network1"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location
  address_space       = ["10.254.0.0/16"]
}

resource "azurerm_subnet" "frontend" {
  name                 = "frontend"
  resource_group_name  = azurerm_resource_group.test.name
  virtual_network_name = azurerm_virtual_network.test.name
  address_prefixes     = ["10.254.0.0/24"]
}

resource "azurerm_subnet" "backend" {
  name                 = "backend"
  resource_group_name  = azurerm_resource_group.test.name
  virtual_network_name = azurerm_virtual_network.test.name
  address_prefixes     = ["10.254.2.0/24"]
}

resource "azurerm_public_ip" "test" {
  name                = "test-pip"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location
  allocation_method   = "Static"
  sku                 = "Standard"
}

locals {
  backend_address_pool_name = "${azurerm_virtual_network.test.name}-beap"
  frontend_port_name        = "${azurerm_virtual_network.test.name}-feport"
  #frontend_ip_configuration_name  = "${azurerm_virtual_network.test.name}-feip"
  frontend_ip_configuration_name  = "public"
  frontend_ip_configuration_name2 = "private"
  http_setting_name               = "${azurerm_virtual_network.test.name}-be-htst"
  listener_name                   = "${azurerm_virtual_network.test.name}-httplstn"
  request_routing_rule_name       = "${azurerm_virtual_network.test.name}-rqrt"
  redirect_configuration_name     = "${azurerm_virtual_network.test.name}-rdrcfg"
}

resource "azurerm_application_gateway" "network" {
  name                = "test-appgateway"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location

  sku {
    name = "Standard_v2"
    tier = "Standard_v2"
    capacity = 2
  }

  gateway_ip_configuration {
    name      = "my-gateway-ip-configuration"
    subnet_id = azurerm_subnet.frontend.id
  }

  frontend_port {
    name = local.frontend_port_name
    port = 80
  }

  frontend_ip_configuration {
    name                 = local.frontend_ip_configuration_name
    public_ip_address_id = azurerm_public_ip.test.id
  }

  frontend_ip_configuration {
    name                          = local.frontend_ip_configuration_name2
    subnet_id                     = azurerm_subnet.frontend.id
    private_ip_address            = "10.254.0.100"
    private_ip_address_allocation = "Static"
  }

  backend_address_pool {
    name = local.backend_address_pool_name
  }

  backend_http_settings {
    name                  = local.http_setting_name
    cookie_based_affinity = "Disabled"
    path                  = "/path1/"
    port                  = 80
    protocol              = "Http"
    request_timeout       = 60
  }

  http_listener {
    name                           = local.listener_name
    frontend_ip_configuration_name = local.frontend_ip_configuration_name
    frontend_port_name             = local.frontend_port_name
    protocol                       = "Http"
  }

  request_routing_rule {
    name                       = local.request_routing_rule_name
    priority                   = 10
    rule_type                  = "Basic"
    http_listener_name         = local.listener_name
    backend_address_pool_name  = local.backend_address_pool_name
    backend_http_settings_name = local.http_setting_name
  }
}
```

</details>

**Comment by rcskosir** [comment] 2023-12-06 22:41
Thanks for taking the time to submit this issue. @teowa was unable to reproduce this behavior. We’re going to close this issue for now, but if you can provide more details about your config, we can reopen.

**Closed by rcskosir** 2023-12-06 22:41 UTC
Labels: waiting-response, service/network, v/3.x
