### ISSUE TITLE
Subnets get deleted after multiple "terraform deploy" runs

### ISSUE THREAD

**Issue by zadigus** [hashicorp/terraform-provider-azurerm#21156] opened 2023-03-28 08:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.9

### AzureRM Provider Version

3.49.0

### Affected Resource(s)/Data Source(s)

azurerm_subnet

### Terraform Configuration Files

```hcl
https://github.com/zadigus/terraform_azurerm_subnet_issue
```

### Debug Output/Panic Output

```shell
https://gist.github.com/zadigus/02913e58894a8148beb23894f4d15e85#file-terraform-subnet-isse
```

### Expected Behaviour

I expect none of my subnets to get permanently destroyed. Moreover, I don't expect any change to my subnet at all. Apparently, those subnets that are kept get deleted and recreated.

### Actual Behaviour

All the subnets created with resource `azurerm_subnet` get permanently deleted the second time I run the `terraform deploy` command. The other subnets get deleted and re-created.

### Steps to Reproduce

1. terraform apply --> everything gets deployed with success
2. terraform apply --> deployment is successful, however some subnets got removed and some others got removed and recreated

**Comment by tombuildsstuff** [comment] 2023-03-28 08:44
hi @zadigus 

Subnets can either be defined inline within the `azurerm_virtual_network` resource or using the `azurerm_subnet` resource, see this note in [the documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/subnet):

<img width="586" alt="Screenshot 2023-03-28 at 09 37 58" src="https://user-images.githubusercontent.com/666005/228179024-38d17412-bee5-4dd9-88af-b5199d17f488.png">

As such unfortunately this behaviour is expected at this point in time, you'll either need to define all of the subnets within the `azurerm_virtual_network` resource (to say "only these should exist"), or define all of the subnets using the `azurerm_subnet` resource (to say "just create/manage this subnet") - however since this appears to be working as intended I'm going to close this issue for the moment.

Thanks!

**Closed by tombuildsstuff** 2023-03-28 08:44 UTC
Labels: question
