### ISSUE TITLE
Suport for Kind property in the azure machine learning workspace 

### ISSUE THREAD

**Issue by Nepomuceno** [hashicorp/terraform-provider-azurerm#26323] opened 2024-06-13 12:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Azure machine leasnint workspace has the property kind that is currently not exposed by the azurerm provide this would allow this property to be exposed.

https://github.com/hashicorp/go-azure-sdk/blob/main/resource-manager/machinelearningservices/2024-04-01/workspaces/model_workspace.go#L14

### New or Affected Resource(s)/Data Source(s)

azurerm_machine_learning_workspace

### Potential Terraform Configuration

```hcl
resource "azurerm_machine_learning_workspace" "example" {
  name                    = "example-workspace"
  location                = azurerm_resource_group.example.location
  resource_group_name     = azurerm_resource_group.example.name
  application_insights_id = azurerm_application_insights.example.id
  key_vault_id            = azurerm_key_vault.example.id
  storage_account_id      = azurerm_storage_account.example.id
  kind                    = "hub"

  identity {
    type = "SystemAssigned"
  }
}
```

**Comment by tombuildsstuff** [comment] 2024-06-13 14:17
hey @Nepomuceno 

Thanks for opening this issue.

Whilst the API supports `kind`, we typically don't expose it as a field (and instead expose these as different resources) since the behaviour (and payload/validation/etc) typically varies substantially - as such would you mind providing a little more details on what `hub` is doing here, is this a different type of resource?

Thanks!

**Comment by xuzhang3** [comment] 2024-06-14 02:27
@tombuildsstuff  In Machine Learning Workspaces `v2024-04-01`, two new types were added to `kind`: `Hub` and `Project`. I have a branch working on this features

**Comment by Nepomuceno** [comment] 2024-06-14 03:11
Oh ok I was working on adding those 2 new types I did phrase incorrectly it is about adding the new types not creating the property

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by stephybun** [comment] 2024-06-14 05:48
Duplicate of https://github.com/hashicorp/terraform-provider-azurerm/issues/25859, please subscribe to #25859 for updates.

**Closed by stephybun** 2024-06-14 05:48 UTC
Labels: enhancement, service/machine-learning
