### ISSUE TITLE
azurerm_purview_account - "unexpected status 400 with error: 1001: PrincipalId is required"

### ISSUE THREAD

**Issue by Tommy-Ten** [hashicorp/terraform-provider-azurerm#25101] opened 2024-02-29 15:16 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.2

### AzureRM Provider Version

3.93.0

### Affected Resource(s)/Data Source(s)

azurerm_purview_account

### Terraform Configuration Files

```hcl
main.tf:

module "xxx-xxx-xxx" {
  source = "./infra/modules/xxx-xxx-xxx/"

  identity_ids                    = [module.xxx-xxx-identity.purview_identity_id]
  location                        = var.primary_location
  name                            = "pview-${join("-", var.company_prefix)}"
  resource_group_name             = module.xxx-xxx-resource-groups.management_resource_group_names["${module.naming_style.resource_group.name}-governance"]
  private_endpoint_name           = "${module.naming_style.private_endpoint.name}-pview"
  private_dns_zone_group_name     = "${module.naming_style.private_dns_zone_group.name}-pview"
  private_dns_zone_ids            = [module.cog-res-private-dns.private_dns_zones[1].id]
  private_service_connection_name = "${module.naming_style.private_service_connection.name}-pview"
  subnet_id                       = module.avm-res-network-virtualnetwork.subnets[keys(module.avm-res-network-virtualnetwork.subnets)[0]].id
}

variables.tf:

variable "identity_ids" {
  description = "The IDs of the user-assigned identities for the Purview account"
  type        = list(string)
}

resource.tf:

resource "azurerm_purview_account" "purview_account" {
  name                   = var.name
  resource_group_name    = var.resource_group_name
  location               = var.location
  public_network_enabled = false

  identity {
    type         = "UserAssigned"
    identity_ids = var.identity_ids
  }
}

Identity module output:

output "purview_identity_id" {
  description = "The ID of the user-assigned identity for Purview"
  value       = azurerm_user_assigned_identity.uami_purview.id
}
```

### Debug Output/Panic Output

```shell
https://gist.github.com/Tommy-Ten/ef361e4431d0d73212e55ef743ab27eb
```

### Expected Behaviour

User-assigned managed identity added/associated with the Purview account.

### Actual Behaviour

"│ Error: creating/updating Account (Subscription: "xxx-xxx-xxx"
│ Resource Group Name: "rg-cog-dev-uks-governance"
│ Account Name: "pview-cog-dev-uks"): performing CreateOrUpdate: unexpected status 400 with error: 1001: PrincipalId is required
│ 
│   with module.cog-res-governance.azurerm_purview_account.purview_account,
│   on infra/modules/cog-res-governance/governance.tf line 1, in resource "azurerm_purview_account" "purview_account":
│    1: resource "azurerm_purview_account" "purview_account" {"

**And when defining principal_id as an output from identity module getting the following error:**

 Error: parsing "xxxxxx": parsing the UserAssignedIdentity ID: the number of segments didn't match
│ 
│ Expected a UserAssignedIdentity ID that matched (containing 8 segments):
│ 
│ > /subscriptions/xxxxx2/resourceGroups/example-resource-group/providers/Microsoft.ManagedIdentity/userAssignedIdentities/userAssignedIdentityValue
│ 
│ However this value was provided (which was parsed into 0 segments):
│ 
│ > xxxxxxxx
│ 
│ The following Segments are expected:
│ 
│ * Segment 0 - this should be the literal value "subscriptions"
│ * Segment 1 - this should be the UUID of the Azure Subscription
│ * Segment 2 - this should be the literal value "resourceGroups"
│ * Segment 3 - this should be the name of the Resource Group
│ * Segment 4 - this should be the literal value "providers"
│ * Segment 5 - this should be the name of the Resource Provider [for example 'Microsoft.ManagedIdentity']
│ * Segment 6 - this should be the literal value "userAssignedIdentities"
│ * Segment 7 - this should be the user specified value for this userAssignedIdentity [for example "userAssignedIdentityValue"]
│ 
│ The following Segments were parsed:
│ 
│ * Segment 0 - not found
│ * Segment 1 - not found
│ * Segment 2 - not found
│ * Segment 3 - not found
│ * Segment 4 - not found
│ * Segment 5 - not found
│ * Segment 6 - not found
│ * Segment 7 - not found
│ 
│ 
│   with module.avm-res-containerregistry-registry.azurerm_container_registry.this,
│   on .terraform/modules/avm-res-containerregistry-registry/main.tf line 7, in resource "azurerm_container_registry" "this":
│    7: resource "azurerm_container_registry" "this" {

### Steps to Reproduce

terraform plan
terraform apply

**Comment by ms-henglu** [comment] 2024-03-01 06:29
Hi @Tommy-Ten ,

Thank you for taking time to open this issue!

The value set in the `identity_ids`, should be a list of user assigned identity's IDs. The format looks like `/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/{userAssignedIdentityName}`

**Comment by Tommy-Ten** [comment] 2024-03-01 10:30
Hi @ms-henglu , 

Thanks very much for your reply.

When I output the resource ID of the UAMI, it indeed gives the format you defined above. However, I get an API response saying the following:

"performing CreateOrUpdate: unexpected status 400 with error: 1001: PrincipalId is required"

**Comment by Tommy-Ten** [comment] 2024-03-12 10:52
Can this be looked at, please?

**Comment by marciobarbato** [comment] 2024-03-13 11:07
@ms-henglu  I can confirm @Tommy-Ten  error's, I'm facing the same issue on provider 3.95

Appreciate any feedback

**Comment by ms-henglu** [comment] 2024-03-14 02:57
This issue is also reported here: https://github.com/hashicorp/terraform-provider-azurerm/issues/20043

The upstream API issue is: https://github.com/Azure/azure-rest-api-specs/issues/22257

**Comment by rcskosir** [comment] 2024-03-25 20:08
Thanks for taking the time to submit this issue. It looks like this is a duplicate of #20043. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of #20043.

**Closed by rcskosir** 2024-03-25 20:08 UTC
Labels: duplicate, service/purview, v/3.x
