### ISSUE TITLE
Support for Azure Resource PIM Provider

### ISSUE THREAD

**Issue by pbeckendorf-gkgab** [hashicorp/terraform-provider-azurerm#14800] opened 2022-01-05 06:44 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I often came around the Point that a Customer uses PIM for Azure AD Roles, but there is no chance to put it in Place, managed with Terraform, when there is a Terraform based LZ Concept in Place. It would be great to have a Provider for managing Azure Roles PIM with Terraform as well.

### New or Affected Resource(s)

* azurerm_privileged_identity_management     ?!?

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by tombuildsstuff** [comment] 2022-01-05 08:35
hi @pbeckendorf-gkgab 

Thanks for opening this issue.

Taking a look through this appears to be a duplicate of https://github.com/hashicorp/terraform-provider-azuread/issues/68 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to https://github.com/hashicorp/terraform-provider-azuread/issues/68 for updates?

Thanks!

**Closed by tombuildsstuff** 2022-01-05 08:35 UTC
Labels: duplicate

**Comment by anarsen** [comment] 2022-01-24 05:54
@tombuildsstuff Wouldn't it make sense to actually track Azure RM and Azure AD PIM separately seeing as they're using the Azure REST API and MS Graph API respectively?
