### ISSUE TITLE
Add support for Storage Account -> Diagnostic settings (classic) -> Blob Properties -> Logging

### ISSUE THREAD

**Issue by lotaezhao** [hashicorp/terraform-provider-azurerm#5909] opened 2020-02-26 11:01 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support for 'Storage Account -> Diagnostic settings (classic) -> Blob Properties -> Logging' is missing. Under issue #3346 it was specified that support for this is provided via the azurerm_monitor_diagnostic_setting resource, however this is not the case. That resource appears to configure the 'microsoft.insights/diagnosticsettingpreview' feature, which is not the same thing as Diagnostic settings (classic). Also you can't even use that feature unless your subscription has been whitelisted for the preview.

Please add support to enable configuration of Storage Account -> Diagnostic settings (classic) -> Logging.

### New or Affected Resource(s)

azurerm_storage_account

### Potential Terraform Configuration

Similar to the 'queue_properties' block within azurerm_storage_account, the 'blob_properties' block could be expanded to support a 'logging' block as below.

```hcl
resource "azurerm_storage_account" "example" {
  name = "storageaccountname"
  resource_group_name = azurerm_resource_group.example.name

  location = azurerm_resource_group.example.location
  account_tier = "Standard"
  account_replication_type = "LRS"

  blob_properties {
    logging {
      delete = true
      read = true
      version = "2.0"
      write = true
      retention_policy_days = 30
    }
  }

  tags = {
    environment = "staging"
  }
}
```

### References

This is the same configuration as provided by the Az Cli command 'az storage logging update' which is what I currently have to use in order to configure this setting:
https://docs.microsoft.com/en-us/cli/azure/storage/logging?view=azure-cli-latest

* #0000

**Comment by vinoth12988** [comment] 2020-03-13 06:55
@tracypholmes Any Idea when this will be available for BLOB as it beacame a basic setting for any SA logging in azure

**Comment by amasover** [comment] 2020-05-14 22:50
It would be really nice to get - in addition to blob properties - file, table, and queue properties taken care of as well when implementing this. All these properties seem to have a very similar structure.

Should we have new issue(s) to track adding those other properties, or just use this issue?

**Comment by amasover** [comment] 2020-05-14 23:06
Actually, after searching a bit more through open issues I think this might be a dupe of #3581

**Comment by favoretti** [comment] 2021-08-19 09:25
Closing this in favor of #3581

**Closed by favoretti** 2021-08-19 09:25 UTC
Labels: enhancement, service/storage
