### ISSUE TITLE
Please add  Microsoft Default Rule Set 2.1 to waf_configuration

### ISSUE THREAD

**Issue by ArtworkStu** [hashicorp/terraform-provider-azurerm#23891] opened 2023-11-14 16:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Hello,

We are trying to improve our security for our application and at the moment the best option for default rule set in application gateway waf configuration is OWASP3.2  which is fairly out of date.

Microsoft Default Rule Set 2.1 would address this issue but it is not an option to configure, it has to be a OWASP ruleset, can we please add this as an option, I can't be the only one looking to upgrade their security of the WAFv2 on the application gateway.

Thanks,
Stuart 

### New or Affected Resource(s)/Data Source(s)

azurerm_application_gateway

**Comment by rcskosir** [comment] 2023-11-16 20:00
Thank you for taking the time to open this issue. This is a duplicate of #23802 which has PR #23818 created to add support, please subscribe to the other issue or PR to track completion of this feature request, thanks!

**Closed by rcskosir** 2023-11-16 20:00 UTC
Labels: duplicate, enhancement, service/application-gateway, service/network
