### ISSUE TITLE
Support for routing configuration action in azure front door rule engine

### ISSUE THREAD

**Issue by Christophe69003** [hashicorp/terraform-provider-azurerm#15121] opened 2022-01-26 10:11 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi,

Today we have only two choices in module azurerm_rule_engine for action (request_header and response_header). 
In Azure portal we have a third choices : routing configuration. 

It is possible to add it to terraform ?

### New or Affected Resource(s)

(https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/frontdoor_rules_engine)

Regards
Christophe

**Comment by tombuildsstuff** [comment] 2022-01-27 09:21
hi @Christophe69003 

Thanks for opening this issue.

Taking a look through this appears to be a duplicate of #14884 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #14884 for updates?

Thanks!

**Closed by tombuildsstuff** 2022-01-27 09:21 UTC
Labels: duplicate, enhancement, service/frontdoor
