### ISSUE TITLE
Support for deploying azurerm_*_virtual_machine from existing managed disk 

### ISSUE THREAD

**Issue by MMollyy** [hashicorp/terraform-provider-azurerm#12943] opened 2021-08-11 08:15 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In the previous azurerm_virtual_machine there was the capability to deploy a VM from an existing managed disk. (both a managed disk imported to the state or one that isn't)
However the new resources don't seem to support this. I'm unsure if that is intentional or not?

### New or Affected Resource(s)

* azurerm_windows_virtual_machine
* azurerm_linux_virtual_machine

### Previous Terraform Configuration

```hcl
resource "azurerm_virtual_machine" "VM1" {
  resource_group_name = azurerm_resource_group.rg.name
  name                = "VM1"
  delete_os_disk_on_termination = true

  network_interface_ids = [azurerm_network_interface.VM1-nic1.id]
  location              = var.azure-region

  storage_os_disk {
    name = "VM1-restored-osdisk-20210810-132929"
    create_option = "Attach"
    caching = "None"
    os_type = "Windows"
    managed_disk_id = "/subscriptions/1234/resourceGroups/rg/providers/Microsoft.Compute/disks/VM1-restored-osdisk-20210810-132929"
  }

  vm_size                       = "Standard_A2_v2"

  os_profile_windows_config {}
}
```

**Comment by tombuildsstuff** [comment] 2021-08-11 08:33
hi @MMollyy 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #8195 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #8195 for updates?

Thanks!

**Closed by tombuildsstuff** 2021-08-11 08:33 UTC
Labels: duplicate, enhancement, service/virtual-machine
