### ISSUE TITLE
RequestDisallowedByPolicy while policy is met

### ISSUE THREAD

**Issue by dsfrederic** [hashicorp/terraform-provider-azurerm#14207] opened 2021-11-16 12:44 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v1.0.11
on windows_amd64
```

### Affected Resource(s)

- azurerm_storage_account

### Expected Behaviour

1. Add tag to Azure Resources in terraform files 
2. Apply to resources

### Actual Behaviour

1. Add tag to Azure resources in terraform files 
2. Apply is being blocked because of `RequestDisallowedByPolicy` while the apply contains the required tag. 

![image](https://user-images.githubusercontent.com/28486949/141987259-ee27244a-27bb-4caa-9d44-3cd883c70f23.png)

Only the azurerm_storage_account is being blocked. I was able to perform the same action on SQL database, data factory, ...

### Important Factoids

- There's a simple Azure Policy enabled to make sure every resource has the "PROJECT" tag.

**Comment by tombuildsstuff** [comment] 2021-11-16 13:03
hi @dsfrederic 

Thanks for opening this issue.

Taking a look through here the root cause appears to be #13884 where individual requests are sent to update the fields for a Storage Account given how the Storage Account resource is split across Data Plane and Resource Manager API calls. As such rather than having multiple issues open tracking the same thing, since this'll be fixed by #13884 would you mind subscribing to that issue for updates?

Thanks!

**Closed by tombuildsstuff** 2021-11-16 13:03 UTC
Labels: duplicate, enhancement, service/storage
