### ISSUE TITLE
azurerm_role_assignment: migrating from storage_account_name to storage_account_id forces replacement 

### ISSUE THREAD

**Issue by enorlando** [hashicorp/terraform-provider-azurerm#28023] opened 2024-11-14 22:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.8

### AzureRM Provider Version

4.9.0

### Affected Resource(s)/Data Source(s)

azurerm_role_assignment

### Terraform Configuration Files

```hcl
resource "azurerm_role_assignment" "xx" {
  scope                = azurerm_storage_share.xx.resource_manager_id
  role_definition_name = "Storage File Data SMB Share Contributor"
  principal_id         = var.azure-group-object-id["xx"]
}
```

### Debug Output/Panic Output

```shell
# azurerm_role_assignment.xx must be replaced
-/+ resource "azurerm_role_assignment" "xx" {
      ~ id                                     = "/subscriptions/11111111-1111-1111-1111-11111111111/resourceGroups/xx/providers/Microsoft.Storage/storageAccounts/scgstgcctvarchivestorage/fileServices/default/fileshares/xx/providers/Microsoft.Authorization/roleAssignments/11111111-1111-1111-1111-11111111111" -> (known after apply)
      ~ name                                   = "11111111-1111-1111-1111-11111111111" -> (known after apply)
      ~ principal_type                         = "Group" -> (known after apply)
      ~ role_definition_id                     = "/subscriptions/11111111-1111-1111-1111-11111111111/providers/Microsoft.Authorization/roleDefinitions/11111111-1111-1111-1111-11111111111" -> (known after apply)
      ~ scope                                  = "/subscriptions/11111111-1111-1111-1111-11111111111/resourceGroups/xx/providers/Microsoft.Storage/storageAccounts/xx/fileServices/default/fileshares/x" -> "/subscriptions/9ec969d8-5026-4f1c-8268-8556c632020c/resourceGroups/xx/providers/Microsoft.Storage/storageAccounts/xx/fileServices/default/shares/xx" # forces replacement
      + skip_service_principal_aad_check       = (known after apply)
        # (6 unchanged attributes hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

### Expected Behaviour

No changes to be made to the resource

### Actual Behaviour

It wants to recreate the resource

When we change the `azurerm_storage_share` resources to use `storage_account_id` argument, after running a terraform plan, it wants to recreate all the associated `azurerm_role_assignment` resources

We have to hard code the scope to avoid recreation

```hcl
resource "azurerm_role_assignment" "xx" {
  scope                = "/subscriptions/11111111-1111-1111-1111-11111111111/resourceGroups/xx/providers/Microsoft.Storage/storageAccounts/xx/fileServices/default/fileshares/xx"
  role_definition_name = "Storage File Data SMB Share Contributor"
  principal_id         = var.azure-group-object-id["xx"]
}
```

### Steps to Reproduce

Terraform plan

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/27942
https://github.com/hashicorp/terraform-provider-azurerm/pull/27733

**Comment by WodansSon** [comment] 2024-11-16 00:06
Closing as duplicate of #27942, while the parent resources do differ (e.g. `azurerm_role_assignment` vs. `azurerm_storage_container` to root cause is the same.

**Closed by WodansSon** 2024-11-16 00:06 UTC
Labels: duplicate, service/authorization, v/4.x
