### ISSUE TITLE
Case mismatch with route table associations causing them to be recreateda

### ISSUE THREAD

**Issue by jf781** [hashicorp/terraform-provider-azurerm#7049] opened 2020-05-22 09:45 UTC
Hi all - I recently noticed an issue with when attempting to import route table associations into Terraform.  It has worked fine when the resource group was all lower case, but when part of the resource group is capitalized then it throws an error (sometimes).    When there is a mismatch in the case then Terraform wants to replace the resource. 

```terraform
  # module.gwroutetable.azurerm_subnet_route_table_association.rtas must be replaced
-/+ resource "azurerm_subnet_route_table_association" "rtas" {
      ~ id             = "/subscriptions/xxx/resourceGroups/NAME-rg/providers/Microsoft.Network/virtualNetworks/vnet/subnets/GatewaySubnet" -> (known after apply)
      ~ route_table_id = "/subscriptions/xxx/resourceGroups/name-rg/providers/Microsoft.Network/routeTables/gateway-udr" -> "/subscriptions/xxx/resourceGroups/NAME-rg/providers/Microsoft.Network/routeTables/gateway-udr" # forces replacement
        subnet_id      = "/subscriptions/xxx/resourceGroups/NAME-rg/providers/Microsoft.Network/virtualNetworks/vnet/subnets/GatewaySubnet"
```

When running 'Terraform State Show' for the route table and the route table association you can see the mismatch. 

```bash
terraform state show module.gwroutetable.azurerm_route_table.rt
# module.gwroutetable.azurerm_route_table.rt:
resource "azurerm_route_table" "rt" {
    disable_bgp_route_propagation = false
    id                            = "/subscriptions/xxx/resourceGroups/NAME-rg/providers/Microsoft.Network/routeTables/gateway-udr"
    location                      = "centralus"
    name                          = "gateway-udr"
    resource_group_name           = "NAME-rg"
```

```bash
terraform state show module.gwroutetable.azurerm_subnet_route_table_association.rtas
# module.gwroutetable.azurerm_subnet_route_table_association.rtas:
resource "azurerm_subnet_route_table_association" "rtas" {
    id             = "/subscriptions/xxx/resourceGroups/NAME-rg/providers/Microsoft.Network/virtualNetworks/vnet/subnets/GatewaySubnet"
    route_table_id = "/subscriptions/xxx/resourceGroups/name-rg/providers/Microsoft.Network/routeTables/gateway-udr"
    subnet_id      = "/subscriptions/xxx/resourceGroups/NAME-rg/providers/Microsoft.Network/virtualNetworks/vnet/subnets/GatewaySubnet"
```

I have tried to remove the both states from the state file and then reimport them ensuring that I have the resource group case set correctly.   It still shows 'route_table_id' in the association as lower case.  

The odd part is I have done this 12 times for this specific subscription using various route tables and subnet associations and it has only happened 4 times.  With those 4 it plays out exactly as above.  The others do not have an issue and their resource group also has upper and lower case characters. 

### Terraform (and AzureRM Provider) Version

Terraform v0.12.24
+ provider.azurerm v2.9.0. (I tried switching to v2.11.0 but no change in behavior)

### Affected Resource(s)

azurerm_subnet_route_table_association
azurerm_route_table

### Terraform Configuration Files

```hcl
data "azurerm_resource_group" "rg" {
  name     = var.rgName
}

data "azurerm_subnet" "gwSubnet" {
    name                    = "GatewaySubnet"
    virtual_network_name    = var.vnetName
    resource_group_name     = data.azurerm_resource_group.rg.name
}


data "azurerm_virtual_network" "vnet" {
    name                    = var.vnetName
    resource_group_name     = data.azurerm_resource_group.rg.name
}

resource "azurerm_route_table" "rt" {
  name                = var.gatewayRtName
  location            = data.azurerm_resource_group.rg.location
  resource_group_name = data.azurerm_resource_group.rg.name
  tags                = var.gatewayRtTags
  disable_bgp_route_propagation = false
}

resource "azurerm_route" "peers" {
    count                  = length(var.gatewaySubnetPeerList)
    name                   = lookup(var.gatewaySubnetPeerList[count.index], "subnetName")
    resource_group_name    = data.azurerm_resource_group.rg.name
    route_table_name       = var.gatewayRtName
    address_prefix         = lookup(var.gatewaySubnetPeerList[count.index], "prefix")
    next_hop_type          = "VirtualAppliance"
    next_hop_in_ip_address = var.gatewayLBip
    depends_on             = [azurerm_route_table.rt]
resource "azurerm_subnet_route_table_association" "rtas" {
  subnet_id      = data.azurerm_subnet.gwSubnet.id
  route_table_id = azurerm_route_table.rt.id
  depends_on              = [azurerm_route_table.rt]
```

### Expected Behavior

When importing the resource I would expect it to save the case of the resource ID as it is entered rather than changing it in the state file. 

### Actual Behavior

It is changing the case of the resource group to all lower case in the state file.  

### Steps to Reproduce

```bash
terraform import module.gwroutetable.azurerm_route_table.rt /subscriptions/xxx/resourceGroups/NAME-rg/providers/Microsoft.Network/routeTables/gateway-udr

terraform import module.gwroutetable.azurerm_subnet_route_table_association.rtas /subscriptions/xxx/resourceGroups/NAME-rg/providers/Microsoft.Network/virtualNetworks/vnet/subnets/GatewaySubnet

terraform plan
```

### References

A co-worker found a similar issue in the past regarding that mentioned the data provided from the APIs can cause this.  [Issue #6433](https://github.com/hashicorp/terraform/issues/6433)

**Comment by njuCZ** [comment] 2020-05-27 03:30
@jf781 I am sorry I could not reproduce this error. If there is anything wrong with my reproduce steps, please point it out.

```
provider "azurerm" {
  features {}
}

resource "azurerm_route_table" "test" {
  name                = "rt"
  location            = "Southeast Asia"
  resource_group_name = "RG"
}

resource "azurerm_subnet_route_table_association" "test" {
  subnet_id       = "/subscriptions/000/resourceGroups/RG/providers/Microsoft.Network/virtualNetworks/vnet/subnets/sub"
  route_table_id = azurerm_route_table.test.id
}
```

I use the above script, and execute
```
terraform import azurerm_route_table.test "/subscriptions/000/resourceGroups/RG/providers/Microsoft.Network/routeTables/rt"
terraform import azurerm_subnet_route_table_association.test "/subscriptions/000/resourceGroups/RG/providers/Microsoft.Network/virtualNetworks/vnet/subnets/sub"
terraform plan
```

there seems everything fine.

**Comment by jf781** [comment] 2020-05-27 13:13
@njuCZ - Thanks for taking a look.  Those steps appear to be accurate.   The odd part is it is happening intermittently (just happened again this morning in a different subscription).  

Not sure how the best way to troubleshoot?  Any suggestions?

**Comment by jf781** [comment] 2020-05-27 14:28
So this may be a perfect example.  This is the code to create the route table and the route table associations.   It loops through iteratively so they should all be the same.  

```terraform
resource "azurerm_route_table" "rt" {
  name                            = var.defaultRtName
  location                        = var.location
  resource_group_name             = var.rgName
  tags                            = var.azureTags
  disable_bgp_route_propagation   = true

  route {
    name                   = "DefaultRoute"
    address_prefix         = "0.0.0.0/0"
    next_hop_type          = "VirtualAppliance"
    next_hop_in_ip_address = var.LBip
  }
}



resource "azurerm_subnet_route_table_association" "rtas" {
  count                       = length(var.subnetList)
  subnet_id                   = azurerm_subnet.subnets.*.id[count.index]
  route_table_id              = azurerm_route_table.rt.id
  depends_on                  = [azurerm_subnet.subnets]
}
```

I import all of the resources with the case as it is in Azure (copying and pasting the ID's) which has the first letter of the resource group capitalized.  Then I run "terraform plan" and see that one is good and the other 2 need to be recreated. 

Looking closer at the output, one of the route table ID's matches the case in Azure, the other 2 have the resource group all lower case within the route table ID and says the associations need to be recreated.

**Comment by njuCZ** [comment] 2020-06-11 09:11
@jf781 according to https://www.terraform.io/docs/providers/azurerm/r/subnet.html#name-2, "Microsoft.Web/serverfarms" is actually an invalid option.
I tried to import "azurerm_subnet",  the value for `name` is `Microsoft.Web/serverFarms`. I guess there might be some gap between us. Could you please give more detail about your operation?

**Comment by jf781** [comment] 2020-06-11 14:24
@njuCZ - Thanks for taking a look.  I agree that the documentation shows that it should be `Microsoft.Web/serverFarms`.   However, when I ran the TF plan I received the information above where it was reading the current delegation as `Microsoft.Web/serverfarms`.  

I added it here to show another example of when running TF the information being provided about the current infrastructure is having some case mismatches.

**Comment by njuCZ** [comment] 2020-06-12 03:19
@jf781 do you mean you have a config for example:
```
resource "azurerm_subnet" "example" {
  name                            = "xxx"
  resource_group_name  = "xxx"
  virtual_network_name   = "xxx"
  address_prefixes            = ["xxx"]

  delegation {
    name = "xxx"

    service_delegation {
      name    = "Microsoft.Web/serverFarms"
      actions = ["Microsoft.Network/virtualNetworks/subnets/action"]
    }
  }
}
```
and execute `terraform import` first, and then execute `terraform plan`, it will show case diff of service_delegation `name` ?
I am sorry I tried again in my local and there seems everything ok with me.

If your steps are different, Could you please tell me with more detail about how to reproduce it

**Comment by dpbustos** [comment] 2020-07-23 05:33
I've noticed this exact issue. I checked the state file and the casing matched the casing I could see in the portal for the route table id. After I applied the change, it re-created the subnet<->rt association and then the issue went away. I then looked at the state file and it looked exactly the same as before.
Sorry I can't provide more details, just that I came across this and I can no longer re-produce...

**Comment by dduleep** [comment] 2021-02-15 06:48
I have noticed the same issue as above reported, the route table created as **abc-rt** with TF state of **abc-rt**, if you check resource id return by azure fabric it is showing as **/subscriptions/xxx/resourceGroups/name-rg/providers/Microsoft.Network/routeTables/ABC-RT** for **abc-rt**. I suggested that in the case of the following, Terraform ignore the route table change/update.

~/subscriptions/xxx/resourceGroups/name-rg/providers/Microsoft.Network/routeTables/ABC-RT -> /subscriptions/xxx/resourceGroups/name-rg/providers/Microsoft.Network/routeTables/abc-rt

**Comment by favoretti** [comment] 2021-08-20 08:22
Thanks for opening this issue! Since this issue has been reported a long time ago and relates to an older version of provider - I'm going to close it. If this is still relevant and occurring on the latest version of terraform and provider please do open a new issue!

**Closed by favoretti** 2021-08-20 08:22 UTC
Labels: question, service/route-tables
