### ISSUE TITLE
azurerm_sql_firewall_rule and azurerm_sql_virtual_network_rule

### ISSUE THREAD

**Issue by TPPWC** [hashicorp/terraform-provider-azurerm#8625] opened 2020-09-25 06:51 UTC
Hi there,

it looks like the azurerm-sql resources are moved to azurerm-mssql. How about azurerm_sql_firewall_rule and azurerm_sql_virtual_network_rule, will these moved to azurerm-mssql as well?

kr

tom

**Comment by yupwei68** [comment] 2020-10-09 08:53
Hi @TPPWC , thanks for opening this issue. We'll create new resources for `azurerm_mssql_firewall_rule` and `azurerm_mssql_virtual_network_rule` when there is a service version upgrade.  Currently, there is no version upgrade for these two service. And you could use the resources in `mssql` and `sql` in mixed.

**Comment by ilmax** [comment] 2020-10-09 09:49
it would also be nice to include the ability to remove the firewall rule that allows access to all azure resources, my current workaround for it is via local-exec + az cli command but it would be way better to be able to express in terraform terms.

**Comment by yupwei68** [comment] 2020-10-10 06:15
@ilmax You could remove the firewall rule by importing an existing `azurerm_sql_firewall_rule` by its resource id, then destroy this resource. The import command is like:

> terraform import azurerm_sql_firewall_rule.rule1 /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/myresourcegroup/providers/Microsoft.Sql/servers/myserver/firewallRules/rule1

**Comment by kevinmatthews-kpmg** [comment] 2021-04-01 09:28
So this looks like its in place in terraform 2.53 however when using the resource as intended:

```
resource "azurerm_mssql_virtual_network_rule" "example" {
  name      = "sql-vnet-rule"
  server_id = azurerm_mssql_server.example.id
  subnet_id = azurerm_subnet.example.id
}
```

I get the error:

```
Error: ID was missing the `servers` element
```

This is obviously different from the sql (non mssql) version which expects a server name and resource group

```
resource "azurerm_sql_virtual_network_rule" "sqlvnetrule" {
  name                = "sql-vnet-rule"
  resource_group_name = azurerm_resource_group.example.name
  server_name         = azurerm_sql_server.sqlserver.name
  subnet_id           = azurerm_subnet.subnet.id
}
```

Am i missing something?

**Comment by favoretti** [comment] 2021-09-01 10:19
Thanks for opening this issue! Since this issue seems to have been addressed in the latest versions of the provider (or a valid workaround was provided) - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.

**Closed by favoretti** 2021-09-01 10:19 UTC
Labels: question, service/mssql
