### ISSUE TITLE
Azure Front Door location field incorrectly defined as of 2.94.0

### ISSUE THREAD

**Issue by cpressland** [hashicorp/terraform-provider-azurerm#15215] opened 2022-02-01 17:26 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```shell
$ terraform version
Terraform v1.1.4
on darwin_arm64
+ provider registry.terraform.io/hashicorp/azurerm v2.94.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/terrycain/chef v0.3.2
+ provider registry.terraform.io/terrycain/commandpersistence v1.1.0
```

### Affected Resource(s)

* `azurerm_frontdoor`

### Terraform Configuration Files

```hcl
resource "azurerm_frontdoor" "frontdoor" {
    name = "bink-frontdoor"
    resource_group_name = azurerm_resource_group.rg.name
    enforce_backend_pools_certificate_name_check = true
    backend_pools_send_receive_timeout_seconds = 120

    tags = var.tags

   ......config snipped

}
```

### Expected Behaviour

Front Door to be managed inside of Terraform

### Actual Behaviour

Terraform detects the `resource_group_name` as the `location`, resulting in error:
```
│ Error: "frontdoor" was not found in the list of supported Azure Locations: "westus,westus2,eastus,centralus,centraluseuap,southcentralus,northcentralus,westcentralus,eastus2,eastus2euap,brazilsouth,brazilus,northeurope,westeurope,eastasia,southeastasia,japanwest,japaneast,koreacentral,koreasouth,southindia,westindia,centralindia,australiaeast,australiasoutheast,canadacentral,canadaeast,uksouth,ukwest,francecentral,francesouth,australiacentral,australiacentral2,uaecentral,uaenorth,southafricanorth,southafricawest,switzerlandnorth,switzerlandwest,germanynorth,germanywestcentral,norwayeast,norwaywest,brazilsoutheast,westus3,swedencentral,swedensouth"
│ 
│   with module.uksouth-frontdoor.azurerm_frontdoor.frontdoor,
│   on uksouth/frontdoor/main.tf line 62, in resource "azurerm_frontdoor" "frontdoor":
│   62:     resource_group_name = azurerm_resource_group.rg.name
```

In the above example, `azurerm_resource_group.rg.name` == `frontdoor`.

This stopped working in `2.94.0`, but worked fine in `2.93.1`.

**Comment by tombuildsstuff** [comment] 2022-02-02 07:32
Duplicate of #15164 which has been fixed in #15174 / will ship in v2.95.0

**Closed by tombuildsstuff** 2022-02-02 07:32 UTC
Labels: bug, duplicate, regression, service/frontdoor
