### ISSUE TITLE
Plugin crash when trying to import an azurerm_linux_function_app into the state

### ISSUE THREAD

**Issue by uzoltan** [hashicorp/terraform-provider-azurerm#14812] opened 2022-01-05 15:32 UTC
The error message I got asked me nicely to share the error here, so here it is :)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.1.2
on linux_amd64
    
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=2.90.0"
    }

### Affected Resource(s)

* `azurerm_linux_function_app`

### Panic Output

https://gist.github.com/uzoltan/36a80e50349f624b0dbe040f20a86270

### Steps to Reproduce

1. Have a terraform setup + an azure subscription with a valid function app already existing

2. `terraform import azurerm_linux_function_app.<Resource Label> <Azure Resource ID>`

**Comment by lonegunmanb** [comment] 2022-01-07 00:25
Hello @uzoltan , it looks like the provider's code didn't check the `site_config`'s length, so I guess in your config the `site_config` is an empty block like below right?

```hcl
site_config {}
```

Anyway I will try to reproduce this issue.

**Comment by lonegunmanb** [comment] 2022-01-07 03:33
I was not able to reproduce this issue on my side but I think the code in provider DO missed the length check, other `ApplicationStack` usages had length check, but at the line that caused panic there was no length check, so I think a simple patch will fix this issue. Anyway, since I don't know how to reproduce this issue, @uzoltan would you please try the latest version plugin once the pr has been merged and a new version has been released? Thanks!

**Comment by jackofallops** [comment] 2022-01-17 07:07
Hi @uzoltan - Could I ask what process you were doing to get this error?  The potential fix from @lonegunmanb should guard against the problem, but I'd like to understand how we got there since I also cannot find a way to reproduce and I want to make sure there are no other problems further along the same journey?  Was this an import of an existing function app into the new Beta resource?

**Closed** 2022-01-17 13:51 UTC
Labels: crash, service/app-service

**Comment by uzoltan** [comment] 2022-01-19 17:15
Hi @lonegunmanb and @jackofallops!

Sorry for the late response, I didn't get any email notification for this thread and we moved away from this beta feature (replaced it with azurerm_function_app), so our issue was solved by avoiding the use of this resource. 

But to answer all the questions in chronological order...

> so I guess in your config the site_config is an empty block like below right?

No, I looked back in the git history, and we had this for site_config:
```terraform
  site_config {
    always_on                                     = false
    container_registry_use_managed_identity       = true
    container_registry_managed_identity_client_id = data.azurerm_user_assigned_identity.features_mlops.client_id
    application_insights_key                      = azurerm_application_insights.features_mlops.instrumentation_key
    application_insights_connection_string        = azurerm_application_insights.features_mlops.connection_string
    application_stack {
      docker {
        registry_url = data.azurerm_container_registry.turbine.login_server
        image_name   = "features/turbine-features-dataprocessing"
        image_tag    = "volatile-azurefunctions3"
      }
    }
    cors {
      allowed_origins = ["https://portal.azure.com"]
    }
    app_service_logs {
      disk_quota_mb         = 35
      retention_period_days = 30
    }
```

> @uzoltan would you please try the latest version plugin once the pr has been merged and a new version has been released? 
Can't promise I can dedicate the time for it to go back and the resource again, I just opened this issue because the crash log asked me so nicely, but I kinda forget about it afterwards ^^

> Hi @uzoltan - Could I ask what process you were doing to get this error? 
I'm not a 100% sure to be honest. This was a new function app we haven't released to production yet, and it was the first project where we started using terraform to deploy our new Azure resources. We tried using azurerm_linux_function_app from the start, since we deploy linux based docker images to the function. After some changes we made to our terraform file, we just noticed that the function app disappeared from our shared state (we store this in GitLab), and all the terraform plans wanted to create the function app from scratch, even though the function app was still there in Azure. So to fix this issue, I learned about terraform import, and this is when I got the crash. We didn't investigate how the shared state got out of sync with the actual cloud resources, since the function was not supported in production yet, we just recreated everything from scratch without beta features.
