### ISSUE TITLE
azurerm_media_transform does not reliably create the resource it should

### ISSUE THREAD

**Issue by zc-hmcts** [hashicorp/terraform-provider-azurerm#20196] opened 2023-01-27 16:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.5

### AzureRM Provider Version

3.33.0

### Affected Resource(s)/Data Source(s)

azurerm_media_transform

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "rg" {
  name     = local.resource_group_name
  location = var.location
  tags     = var.common_tags
}

module "finalsa_storage_account" {
  source                          = "git@github.com:hmcts/cnp-module-storage-account?ref=master"
  env                             = var.env
  storage_account_name            = replace("${var.product}finalsa${var.env}", "-", "")
  resource_group_name             = azurerm_resource_group.rg.name
  location                        = var.location #"UKWest" #As recommended by MS
  account_kind                    = "StorageV2"
  account_tier                    = var.sa_account_tier
  account_replication_type        = var.sa_replication_type
  sa_subnets                      = concat([data.azurerm_subnet.jenkins_subnet.id], [azurerm_subnet.endpoint_subnet.id], [azurerm_subnet.datagateway_subnet.id], [azurerm_subnet.videoeditvm_subnet.id])
  allow_nested_items_to_be_public = false
  ip_rules                        = var.ip_rules
  default_action                  = "Deny"
  enable_data_protection          = true

  cors_rules = var.cors_rules

  common_tags = var.common_tags
  depends_on  = [module.key-vault]
}

module "ingestsa_storage_account" {
  source                          = "git@github.com:hmcts/cnp-module-storage-account?ref=master"
  env                             = var.env
  storage_account_name            = replace("${var.product}ingestsa${var.env}", "-", "")
  resource_group_name             = azurerm_resource_group.rg.name
  location                        = var.location #"UKWest" #As recommended by MS azurerm_resource_group.rg.location
  account_kind                    = "StorageV2"
  account_tier                    = var.sa_account_tier
  account_replication_type        = var.sa_replication_type
  sa_subnets                      = concat([data.azurerm_subnet.jenkins_subnet.id], [azurerm_subnet.endpoint_subnet.id], [azurerm_subnet.datagateway_subnet.id], [azurerm_subnet.videoeditvm_subnet.id])
  allow_nested_items_to_be_public = false
  ip_rules                        = var.ip_rules
  default_action                  = "Deny"
  enable_data_protection          = true

  depends_on  = [module.key-vault]
  common_tags = var.common_tags
}


resource "azurerm_media_services_account" "ams" {
  name                = "${var.product}ams${var.env}"
  location            = var.location #"UKwest"
  resource_group_name = azurerm_resource_group.rg.name

  identity {
    type = "SystemAssigned"
  }


  storage_account {
    id         = module.ingestsa_storage_account.storageaccount_id
    is_primary = true
  }

  storage_account {
    id         = module.finalsa_storage_account.storageaccount_id
    is_primary = false
  }

  tags = var.common_tags
}

resource "azurerm_media_transform" "analysevideo" {
  name                        = "AnalyseVideo"
  resource_group_name         = azurerm_resource_group.rg.name
  media_services_account_name = azurerm_media_services_account.ams.name

  description = "Analyse Video"

  output {
    relative_priority = "Normal"
    on_error_action   = "ContinueJob"
    builtin_preset {
      preset_name = "H264SingleBitrate1080p"
    }
  }
}

resource "azurerm_media_transform" "EncodeToMP4" {
  name                        = "EncodeToMP4"
  resource_group_name         = azurerm_resource_group.rg.name
  media_services_account_name = azurerm_media_services_account.ams.name


  description = "Encode To MP4"

  output {
    relative_priority = "Normal"
    on_error_action   = "ContinueJob"
    builtin_preset {
      preset_name = "H264SingleBitrate1080p"
    }
  }
}
```

### Debug Output/Panic Output

```shell
[2023-01-27T12:40:06.535Z]   # azurerm_media_transform.analysevideo will be created

[2023-01-27T12:40:06.535Z]   + resource "azurerm_media_transform" "analysevideo" {

[2023-01-27T12:40:06.536Z]       + description                 = "Analyse Video"

[2023-01-27T12:40:06.536Z]       + id                          = (known after apply)

[2023-01-27T12:40:06.536Z]       + media_services_account_name = "preamssbox"

[2023-01-27T12:40:06.536Z]       + name                        = "AnalyseVideo"

[2023-01-27T12:40:06.536Z]       + resource_group_name         = "pre-sbox"

[2023-01-27T12:40:06.536Z] 

[2023-01-27T12:40:06.536Z]       + output {

[2023-01-27T12:40:06.536Z]           + on_error_action   = "ContinueJob"

[2023-01-27T12:40:06.536Z]           + relative_priority = "Normal"

[2023-01-27T12:40:06.536Z] 

[2023-01-27T12:40:06.536Z]           + builtin_preset {

[2023-01-27T12:40:06.536Z]               + preset_name = "H264SingleBitrate1080p"

[2023-01-27T12:40:06.536Z]             }

[2023-01-27T12:40:06.536Z]         }

[2023-01-27T12:40:06.536Z]     }
```

### Expected Behaviour

The resource should be created in Azure.

### Actual Behaviour

Resource is not realised in Azure, I tried retrieving in the portal and via Azure CLI (az ams transform list --account-name preamssbox --resource-group pre-sbox)

### Steps to Reproduce

1. `terraform apply` - success, but the transforms do not show up on Azure.
All other resources I declare are created successfully. Only the transforms do not always get created. I've also had one transform get created but the other does not but the plan will claim to create both. Sometimes, they are created successfully.

The usual "fix" to trigger the resource to even come up in the plan is to change something in the code block eg change `resource "azurerm_media_transform" "EncodeToMP4`" to `resource "azurerm_media_transform" "EncodeToMP4_1"`
otherwise, often the state will refresh and not recognise that what is in Azure does not match what is declared in code.

### Important Factoids

Our infrastructure is based in UK South and UK West

**Comment by teowa** [comment] 2023-01-29 08:35
Hi @zc-hmcts , thanks for submitting the issue!
I tried this with azurerm version 3.40.0 and it can work well. Note that we have updated the Media API version in [3.36.0](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/CHANGELOG.md#3360-december-15-2022). Could you please try with azurerm 3.36.0 or later version?

**Comment by rcskosir** [comment] 2023-10-31 14:56
@zc-hmcts Thanks for taking the time to submit this issue. @teowa was unable to reproduce this behavior, and it looks like there was an update in v3.36. We’re going to close this issue for now, but if you run into this again with the latest Terraform and Provider versions, please feel free to [open a new issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/new/choose).

**Closed by rcskosir** 2023-10-31 14:56 UTC
Labels: waiting-response, service/media, v/3.x
