### ISSUE TITLE
Error: The terraform-provider-azurerm_v3.35.0_x5 plugin crashed!

### ISSUE THREAD

**Issue by nanirover** [hashicorp/terraform-provider-azurerm#23745] opened 2023-10-31 20:48 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.3.6

### AzureRM Provider Version

3.35.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
NA
```

### Debug Output/Panic Output

```shell
Stack trace from the terraform-provider-azurerm_v3.35.0_x5 plugin:
2023-10-31T19:00:03.1491466Z 
2023-10-31T19:00:03.1491852Z panic: runtime error: invalid memory address or nil pointer dereference
2023-10-31T19:00:03.1492529Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4a7c602]
2023-10-31T19:00:03.1492977Z 
2023-10-31T19:00:03.1493213Z goroutine 135 [running]:
2023-10-31T19:00:03.1494316Z github.com/hashicorp/terraform-provider-azurerm/internal/services/containers.resourceKubernetesClusterRead(0xc0000d5e80, {0x5aeacc0?, 0xc002059400})
2023-10-31T19:00:03.1496045Z 	github.com/hashicorp/terraform-provider-azurerm/internal/services/containers/kubernetes_cluster_resource.go:2018 +0x902
2023-10-31T19:00:03.1497720Z github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x6cf85c0?, {0x6cf85c0?, 0xc001f0f410?}, 0xd?, {0x5aeacc0?, 0xc002059400?})
2023-10-31T19:00:03.1499137Z 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:712 +0x178
2023-10-31T19:00:03.1500861Z github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000af8c40, {0x6cf85c0, 0xc001f0f410}, 0xc001f43a00, {0x5aeacc0, 0xc002059400})
2023-10-31T19:00:03.1502432Z 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:1015 +0x585
2023-10-31T19:00:03.1503916Z github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0015ef368, {0x6cf85c0?, 0xc001f0f2f0?}, 0xc001eea680)
2023-10-31T19:00:03.1505376Z 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:613 +0x4a5
2023-10-31T19:00:03.1506946Z github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc001687cc0, {0x6cf85c0?, 0xc001f0eb10?}, 0xc001cd4660)
2023-10-31T19:00:03.1508305Z 	github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/tf5server/server.go:748 +0x4b1
2023-10-31T19:00:03.1510007Z github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x61641e0?, 0xc001687cc0}, {0x6cf85c0, 0xc001f0eb10}, 0xc0016f8000, 0x0)
2023-10-31T19:00:03.1512724Z 	github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
2023-10-31T19:00:03.1514060Z google.golang.org/grpc.(*Server).processUnaryRPC(0xc00044a000, {0x6d0a1c0, 0xc00131e340}, 0xc001ee06c0, 0xc000e880c0, 0xaeb8390, 0x0)
2023-10-31T19:00:03.1514953Z 	google.golang.org/grpc@v1.50.1/server.go:1340 +0xd23
2023-10-31T19:00:03.1515656Z google.golang.org/grpc.(*Server).handleStream(0xc00044a000, {0x6d0a1c0, 0xc00131e340}, 0xc001ee06c0, 0x0)
2023-10-31T19:00:03.1517165Z 	google.golang.org/grpc@v1.50.1/server.go:1713 +0xa2f
2023-10-31T19:00:03.1517622Z google.golang.org/grpc.(*Server).serveStreams.func1.2()
2023-10-31T19:00:03.1518065Z 	google.golang.org/grpc@v1.50.1/server.go:965 +0x98
2023-10-31T19:00:03.1518541Z created by google.golang.org/grpc.(*Server).serveStreams.func1
2023-10-31T19:00:03.1519014Z 	google.golang.org/grpc@v1.50.1/server.go:963 +0x28a
2023-10-31T19:00:03.1519307Z 
2023-10-31T19:00:03.1520343Z Error: The terraform-provider-azurerm_v3.35.0_x5 plugin crashed!
2023-10-31T19:00:03.1520709Z 
2023-10-31T19:00:03.1521020Z This is always indicative of a bug within the plugin. It would be immensely
2023-10-31T19:00:03.1521776Z helpful if you could report the crash with the plugin's maintainers so that it
2023-10-31T19:00:03.1522389Z can be fixed. The output above should help diagnose the issue.
```

### Expected Behaviour

Upgrading the aks cluster from 1.25.6 to 1.26.6
System pool is upgraded is 1.26.6
The general pool is not upgraded and failed with the above error message. General pool current version is 1.25.6
Pipeline failed but the cluster is in a healthy state and showing the version as 1.26.6

### Steps to Reproduce

Try repeating what happened under Actual Behaviour with the same provider versions.

**Comment by lonegunmanb** [comment] 2023-10-31 23:54
Hello @nanirover thanks for reporting this issue.

>2023-10-31T19:00:03.1494316Z github.com/hashicorp/terraform-provider-azurerm/internal/services/containers.resourceKubernetesClusterRead(0xc0000d5e80, {0x5aeacc0?, 0xc002059400})
>2023-10-31T19:00:03.1496045Z 	github.com/hashicorp/terraform-provider-azurerm/internal/services/containers/kubernetes_cluster_resource.go:2018 +0x902

I've checked [line 2018 in `v3.35.0`](https://github.com/hashicorp/terraform-provider-azurerm/blob/v3.35.0/internal/services/containers/kubernetes_cluster_resource.go#L2018-L2020):

```go
if profile := props.AutoUpgradeProfile; profile != nil && *profile.UpgradeChannel != managedclusters.UpgradeChannelNone {
			upgradeChannel = string(*profile.UpgradeChannel)
}
```

The nil panic you've seen must be caused by a nil `profile.UpgradeChannel`, but in the latest version of this provider:

```go
if profile := props.AutoUpgradeProfile; profile != nil {
				if profile.UpgradeChannel != nil && *profile.UpgradeChannel != managedclusters.UpgradeChannelNone {
					upgradeChannel = string(*profile.UpgradeChannel)
				}
				if profile.NodeOSUpgradeChannel != nil {
					nodeOSUpgradeChannel = string(*profile.NodeOSUpgradeChannel)
				}
}
```

I believe this issue has already been fixed, would you please tried the latest version of provider? Thanks.

**Comment by nanirover** [comment] 2023-11-01 02:20
After changing the AzureRM Provider Version to 3.65.0, the Issue was resolved for me.

**Comment by stephybun** [comment] 2023-11-01 06:47
Thanks for raising this issue @nanirover and thanks for helping troubleshoot @lonegunmanb!

Since this has already been resolved I'm going to close this issue.

**Closed by stephybun** 2023-11-01 06:47 UTC
Labels: bug, crash, service/kubernetes-cluster, v/3.x
