### ISSUE TITLE
Unable to provision APIM service via Terraform

### ISSUE THREAD

**Issue by RobertBoseanu** [hashicorp/terraform-provider-azurerm#25438] opened 2024-03-27 13:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.5

### AzureRM Provider Version

3.95.0

### Affected Resource(s)/Data Source(s)

azurerm_api_management

### Terraform Configuration Files

```hcl
resource "azurerm_api_management" "apim" {
  name                = "logicapp-apim-${var.environment}"
  location            = var.region
  resource_group_name = data.azurerm_resource_group.paystrax-rg.name
  publisher_name      = "publisher"
  publisher_email     = "user@email.com"

  sku_name = "Consumption_0"
  identity {
    type = "UserAssigned"
    identity_ids = [data.azurerm_user_assigned_identity.apim-identity.id]
  }
}
```

### Debug Output/Panic Output

```shell
Service Name: "logicapp-apim-dev"): polling after CreateOrUpdate: polling failed: the Azure API returned the following error:
│ 
│ Status: "ActivationFailed"
│ Code: ""
│ Message: "Unable to activate API service at this time. This could be temporary issue in the region. Please check https://aka.ms/azurestatus for any issues. If the issue persists after retry, please open a support case for your API management service using the Azure portal.Please provide correlationId 14fefa3d-728d-f31f-8e74-66e27236bbd3 and TimeStamp 3/27/2024 12:26:41 PM."
│ Activity Id: ""
│ 
│ ---
│ 
│ API Response:
│ 
│ ----[start]----
│ {"status":"Failed","error":{"code":"ActivationFailed","message":"Unable to activate API service at this time. This could be temporary issue in the region. Please check https://aka.ms/azurestatus for any issues. If the issue persists after retry, please open a support case for your API management service using the Azure portal.Please provide correlationId 14fefa3d-728d-f31f-8e74-66e27236bbd3 and TimeStamp 3/27/2024 12:26:41 PM."}}
│ -----[end]-----
│ 
│ 
│   with azurerm_api_management.apim,
│   on apimanagement.tf line 1, in resource "azurerm_api_management" "apim":
│    1: resource "azurerm_api_management" "apim" {
│ 
╵
Releasing state lock. This may take a few moments...
```

### Expected Behaviour

We expect the APIM resources + the APIs (2) + Operations + backends to be deployed without any issue on `terraform apply`.

### Actual Behaviour

The error above is received. We tried to deploy to different regions (West Europe & North Europe) without any luck. We were able to manually provision the resource using the Azure Portal. The same setup worked perfectly until yesterday (26th of March at 16:30 PM GMT+2). Also posted a question on Microsoft's Q&A regarding any maintenance that could be interfering with our deployments, but they didn't have any outages or maintenance ongoing.

**Comment by sinbai** [comment] 2024-04-01 08:22
Hi @RobertBoseanu thanks for opening this issue. Unfortunately, I could not reproduce the mentioned issue with the following TF config. Could you please try it with the config below to see if it could be reproduced?
```
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "3.95.0"
    }
  }
}


provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "testRG-0401"
  location = "West Europe"
}

resource "azurerm_user_assigned_identity" "test" {
  name                = "acctestUAI-0401"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
}

resource "azurerm_api_management" "test" {
  depends_on          = [azurerm_user_assigned_identity.test]
  name                = "acctestAM-0401"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  publisher_name      = "pub1"
  publisher_email     = "pub1@email.com"

  sku_name = "Consumption_0"

  identity {
    type = "UserAssigned"
    identity_ids = [
      azurerm_user_assigned_identity.test.id,
    ]
  }
}
```
Actual: 
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/39109137/36f15acf-5bd7-4473-a18f-9df1120a519b)

**Comment by RobertBoseanu** [comment] 2024-04-04 12:02
Hi @sinbai. We resumed deployments the following day and it went smoothly. Our best guess is that some sort of quota was met on how many times you can provision an APIM type resource and Azure wasn't very transparent about it (we were testing the scripts failover, deploying and then destroying the resource a couple of times a day). You can close this issue now, thanks.

**Comment by rcskosir** [comment] 2024-04-05 15:55
@RobertBoseanu Thank you for taking the time to open this issue, closing based on your comment above.

**Closed by rcskosir** 2024-04-05 15:55 UTC
Labels: service/api-management, v/3.x
