### ISSUE TITLE
Support for generating and outputting password of ACR token

### ISSUE THREAD

**Issue by LP0101** [hashicorp/terraform-provider-azurerm#12810] opened 2021-08-02 16:08 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, the ACR token resource only supports the creation of the token object, but it cannot generate or read "password1" and "password2." This is essential for automating the deployment of a token and storing it into a keyvault.

### New or Affected Resource(s)

* azurerm_container_registry_token

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```
The only configuration changes would be an optional parameter to generate password1 and/or password2, as well as the outputs for them to programatically use them in other resources.

### References

* #0000

**Comment by wasfree** [comment] 2021-08-03 13:31
Hi @LP0101,

this seems to be a duplicate of #11566 and there is good explanation why it's not a good candidate in context of Terraform.

**Comment by jkroepke** [comment] 2021-09-13 13:11
HI @wasfree 

from #11566

> IIRC the password is only available at the first time users generate it (via the generateCredentials POST operation), which can't be retrieved later. This means Terraform has no way to get the password on following provisions.

Please keep in mind, there are other provides and resources that supporting such scenarios, too. 

Here is an example:

- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_user_login_profile

The resource is handling user login including passwords. Terraform is unable to gain the passwords after initial creation, too. I guess this scenario is the same like with the ACR tokens.

**Comment by dawsonar802** [comment] 2021-11-23 19:57
Is there currently an ETA on when this functionality will be available?

**Comment by dawsonar802** [comment] 2021-12-13 11:38
In the linked PR when the fix is added and then removed from the milestones, does that just mean it failed to be added to the newly released version of the provider?  Is there any update on when this may be expected into the provider?  Thanks.

**Comment by ksaffarian** [comment] 2022-02-05 02:43
Hi
Is there any plan to release this? 
@magodo  
@katbyte 
Thanks

**Comment by avinashpancham** [comment] 2022-02-27 07:55
@tombuildsstuff @katbyte do you have any updates on this issue?

Without knowing all details, it seems like PR #13782 solves this issue. But that has been in and out of scope for some releases now. If that PR is good enough could you then approve and merge it?


Thanks!

**Comment by dawsonar802** [comment] 2022-05-10 12:29
Is there any update on the status of this issue?  This functionality would be a great help for us.  Thanks.

**Comment by MalouNetlight** [comment] 2022-08-12 11:51
Hey, This would indeed be a good feature to have. The referred other issue and answer why it should not be in terraform only make sense for a scenario where the passwords can be created by the user. But if the user needs to be provided by a password, then creating the password should be the responsibility of the provider, hence of terraform. 
Any updates on that @tombuildsstuff @katbyte?

**Closed** 2022-09-09 00:39 UTC
Labels: enhancement, good first issue, service/container-registry
