### ISSUE TITLE
Azure Key Vault cannot be created when public access is disabled eventhough Private Endpoint / DNS is configured

### ISSUE THREAD

**Issue by martinvoegeli** [hashicorp/terraform-provider-azurerm#21087] opened 2023-03-22 16:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.0

### AzureRM Provider Version

3.47.0

### Affected Resource(s)/Data Source(s)

azurerm_key_vault

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source                = "hashicorp/azurerm"
      version               = ">= 3.47.0"
      configuration_aliases = [azurerm.xxxxx, azurerm.xxxxx]
    }
  }
}

resource "azurerm_key_vault" "kv" {
  for_each                        = var.Stage
  provider                    = azurerm.xxxx
  name                        = "${each.value}-kev-${var.Prefix}-01"
  location                    = var.LocationName
  resource_group_name         = var.RessourceGroupName
  enabled_for_disk_encryption = true
  enabled_for_deployment = true
  enabled_for_template_deployment = true
  enable_rbac_authorization = true
  tenant_id                   = var.TenantID
  soft_delete_retention_days  = 7
   public_network_access_enabled = false
  purge_protection_enabled    = false
  sku_name                    = "premium"
  
   

network_acls {
    default_action = "Allow"
    bypass         = "AzureServices"
  }

   
  tags = var.tags
}


# *******************************************
#End Point 
# *******************************************
resource "azurerm_private_endpoint" "cs_kev_log_ep" {
 
  for_each            = var.Stage
  name                = "${each.value}-pe-${var.Prefix}-${azurerm_key_vault.kv[each.key].name}"
  provider            = azurerm.xxxxxx
  resource_group_name = var.RessourceGroupName
  location            = var.LocationName
  subnet_id           = var.SubnetID
  private_service_connection {
    name                           = "${each.value}-psc-${var.Prefix}-${azurerm_key_vault.kv[each.key].name}"
    private_connection_resource_id = azurerm_key_vault.kv[each.key].id
    is_manual_connection           = false
    subresource_names              = ["vault"]
  }
  tags = var.tags
}

resource "azurerm_private_dns_a_record" "kev_a_log" {

  for_each            = var.Stage
  name                = "${azurerm_key_vault.kv[each.key].name}"
  provider            = azurerm.xxxx
  zone_name           = var.DNSZoneVaultcoreName
  resource_group_name = var.xxxxxRessourceGroup
  ttl                 = 300
  records             = [azurerm_private_endpoint.cs_kev_log_ep[each.key].private_service_connection.0.private_ip_address]
tags = var.tags

}
```

### Debug Output/Panic Output

```shell
Error: waiting for Vault: (Name "i-kev-xxxx" / Resource Group "i-rgr-xxxxx") to become available: connecting to "https://i-kev-xxxx.vault.azure.net/": Get "https://i-kev-xxxx.vault.azure.net/": dial tcp: lookup i-kev-xxxxx.vault.azure.net: no such host
```

### Expected Behaviour

The Key Vaults are created with no public access and activated end points, the dns entry is ok

### Actual Behaviour

The keyvault fails creating - because it seems to try to reach the key vault over https: on its public address. Before the according network configurationis finished

### Important Factoids

We are building in a fully protected network environment - so outside connections are not allowed. The above pattern is working fine for e.g. the data factory part only the key vault has this problem

**Comment by magodo** [comment] 2023-03-23 04:02
@martinvoegeli This issue duplicates to #9738. The reason why key vault waits for its data plane endpoint to become available during creation is because there is a property [contact](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault#contact) which is only retrievable via its data plane API.

**Comment by tombuildsstuff** [comment] 2023-05-22 13:42
Duplicate of #https://github.com/hashicorp/terraform-provider-azurerm/issues/9738 - closing in favour of that issue

**Closed by tombuildsstuff** 2023-05-22 13:42 UTC
Labels: duplicate, service/key-vault
