### ISSUE TITLE
Azure devops pipeline plan crash

### ISSUE THREAD

**Issue by katiebrudos** [hashicorp/terraform-provider-azurerm#15091] opened 2022-01-24 17:28 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
TF: 1.1.3
azurerm provider: 2.93.0 & 2.93.1

### Affected Resource(s)

* `azurerm_2.93.0' and 2.93.1--> causes Terraform Plan error, issue resolved using 2.92.0
* recently added resources include azurerm_log_analytics_workspace and azurerm_automation_account

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output
https://gist.github.com/katiebrudos/6a6b5f78fc6db4772084121d0b9aba0b

### Panic Output

(https://gist.github.com/katiebrudos/6a6b5f78fc6db4772084121d0b9aba0b)

### Expected Behaviour
pipeline runs and either errors with a user coded error or succeeds

### Actual Behaviour

pipeline failed with the attached error of "plugin did not respond or request cancelled"

### Steps to Reproduce

1. `terraform plan, (plan failed with an error, I fixed the variables reference and then next pipeline run it failed). 

### Important Factoids
added log analytics workspace and automation accounts to pipeline IaC and then i get the panic output and failure. 

### References

* #0000

**Comment by tombuildsstuff** [comment] 2022-01-24 17:37
hey @katiebrudos 

Thanks for opening this issue.

Taking a look through here this appears to be a duplicate of #15058 which will be fixed by https://github.com/hashicorp/terraform-provider-azurerm/pull/15074 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of #15058, would you mind subscribing to that issue for updates?

Thanks!

**Closed by tombuildsstuff** 2022-01-24 17:37 UTC
Labels: bug, duplicate, regression, service/bastion
