### ISSUE TITLE
azurerm_windows_virtual_machine can be created with underscores in name

### ISSUE THREAD

**Issue by stimms** [hashicorp/terraform-provider-azurerm#19158] opened 2022-11-06 15:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.4

### AzureRM Provider Version

3.3.0

### Affected Resource(s)/Data Source(s)

azurerm_windows_virtual_machine

### Terraform Configuration Files

```hcl
resource "azurerm_windows_virtual_machine" "vm" {
  name                = "some_name_here"
  size                = var.vm_size
  location            = var.location
  resource_group_name = var.resource_group_name

  source_image_reference {
    publisher = "MicrosoftWindowsServer"
    offer     = "WindowsServer"
    sku       = "2022-datacenter-azure-edition"
    version   = "latest"
  }

  identity {
    type = "SystemAssigned"
  }

  os_disk {
    name                 = "${local.vm_name}-OS"
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
    disk_size_gb         = 128
  }

  admin_password = var.admin_password
  admin_username = var.admin_username
}
```

### Debug Output/Panic Output

```shell
None
```

### Expected Behaviour

Azure VMs created via the portal cannot be created with underscores in their names. 

<img width="700" alt="image" src="https://user-images.githubusercontent.com/153912/200179962-31676b5d-4220-4fc2-aad7-800bbf728fe1.png">

However, the Azure APIs allow for creation of VMs named with underscores. There have been certain assumptions made on inside of Azure teams based on VMs not having underscores in their names. For instance VM backups appear to function correctly however restoring files from these backups is impossible if the VM has an underscore in its name. 

While it shouldn't really be terraform's responsibility to prevent this issue it would be a good user experience if it did. 

### Actual Behaviour

VMs created with underscores in their names correctly created but silent failures in subsequent things like backup restoration lead to a poor experience. 

### References

Code allowing _ in the VM name validation

https://github.com/hashicorp/terraform-provider-azurerm/blob/132368d102afa63a3a4056d38546582876af9a22/internal/services/compute/validate/virtual_machine_name.go#L28

Azure docs on which characters are illegal - note the presence of `_`

**Comment by myc2h6o** [comment] 2022-11-07 14:29
Hi @stimms thanks for opening the issue! After looking at the document and the error from REST API, I think the API is correct and the issue is because of the lacking feature on Azure Portal for specifying two different values for resource name and computer name.
According to the `Note` part under the table in section `Microsoft.Compute` from [this document](https://learn.microsoft.com/azure/azure-resource-manager/management/resource-name-rules#microsoftcompute):
> Azure virtual machines have two distinct names: resource name and host name. When you create a virtual machine in the portal, the same value is used for both names. The restrictions in the preceding table are for the host name.

Since Azure Portal only allows specifying one value for both resource name (`name` in terraform) and host name (`computer_name` in terraform), on Portal, the value uses restrictions from both of them.

The restriction doesn't mix together when using REST API, with detailed error below:
```
{
    "error": {
        "details": [],
        "code": "InvalidResourceName",
        "message": "Resource name <redacted> is invalid. The name can be up to 80 characters long. It must begin with a word character, and it must end with a word character or with '_'. The name may contain word characters or '.', '-', '_'."
    }
}

{
    "error": {
        "code": "InvalidParameter",
        "message": "Windows computer name cannot be more than 15 characters long, be entirely numeric, or contain the following characters: ` ~ ! @ # $ % ^ & * ( ) = + _ [ ] { } \\ | ; : . ' \" , < > / ?.",
        "target": "computerName"
    }
}
```

For restriction of `computer_name`, it could be found at:
https://github.com/hashicorp/terraform-provider-azurerm/blob/66e50ca3d72a5c0e7f95317b35d457d106596777/internal/services/compute/validate/windows_computer_name.go#L9
https://github.com/hashicorp/terraform-provider-azurerm/blob/b0c897055329438be6a3a159f6ffac4e1ce958f2/internal/services/compute/validate/linux_computer_name.go#L8

**Comment by rcskosir** [comment] 2024-03-06 22:35
Thanks for taking the time to open this issue. Based on the answer above by @myc2h6o, the lacking feature on Azure Portal for specifying two different values for resource name and computer name is not supported by the underlying Azure API so I am going to label this issue as such and close it for now. If you create a request on [Azure/azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs), feel free to add the link here.

**Closed by rcskosir** 2024-03-06 22:35 UTC
Labels: bug, service/virtual-machine, upstream/microsoft, v/3.x
