### ISSUE TITLE
azurerm_hdinsight_hadoop_cluster fails with "capability ENABLE_GENEVA_LOG_ANALYTICS_MONITORING is not supported"

### ISSUE THREAD

**Issue by azrael-lu** [hashicorp/terraform-provider-azurerm#18528] opened 2022-09-26 08:16 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.8

### AzureRM Provider Version

3.24.0

### Affected Resource(s)/Data Source(s)

azurerm_hdinsight_hadoop_cluster

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.23.0"
    }
  }
}
terraform {
}

provider "azurerm" {
  features {}
}

resource "azurerm_hdinsight_hadoop_cluster" "example" {
  name                = "hdi-test"
  resource_group_name = "hdi-test-rg"
  location            = "chinanorth3"
  cluster_version     = "4.0"
  tier                = "Standard"

  component_version {
    hadoop = "3.1"
  }

  gateway {
    username = "acctestusrgw"
    password = "TerrAform123!"
  }

  storage_account {
    storage_container_id = azurerm_storage_container.example.id
    storage_account_key  = azurerm_storage_account.example.primary_access_key
    is_default           = true
  }

  roles {
    head_node {
      vm_size  = "Standard_D3_V2"
      username = "acctestusrvm"
      password = "AccTestvdSC4daf986!"
    }

    worker_node {
      vm_size               = "Standard_D4_V2"
      username              = "acctestusrvm"
      password              = "AccTestvdSC4daf986!"
      target_instance_count = 3
    }

    zookeeper_node {
      vm_size  = "Standard_D3_V2"
      username = "acctestusrvm"
      password = "AccTestvdSC4daf986!"
    }
  }
}
```

### Debug Output/Panic Output

```shell
Error: hdinsight.ExtensionsClient#EnableAzureMonitor: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="capability ENABLE_GENEVA_LOG_ANALYTICS_MONITORING is not supported for this subscription"
```

### Expected Behaviour

In Terraform document of azurerm_hdinsight_hadoop_cluster, block **monitor** is Optional.
Without defining it, Terraform should not create a default monitor for HDInsight Cluster.

### Actual Behaviour

Whatever I defined or not defined a block **monitor**.
Terraform will give me the error of "**capability ENABLE_GENEVA_LOG_ANALYTICS_MONITORING is not supported for this subscription**".
I have talked with Microsoft support engineer and confirmed "Geneva Log Analytics monitoring is currently in early public preview state. So far we enabled this feature in only two regions: East US and West Europe".
![3c021b13af7673c80b06952e17c6aaf](https://user-images.githubusercontent.com/12929345/192226339-839bb62b-058a-458d-8d74-229121d59482.png)

Terraform Azurerm provider should not create Geneva Log Analytics monitoring for all regions by default.

**Comment by aristosvo** [comment] 2022-09-26 10:45
@jiaweitao001 Could you take a look at how to fix this? It seems APIs are called too easily, which brakes behaviour in the other regions

**Comment by liuwuliuyun** [comment] 2022-09-27 06:45
I have looked into this and this could because of  https://github.com/hashicorp/terraform-provider-azurerm/pull/17846/files#diff-333e1fa936025892209f64b2a618ac5f21f084e74d395c54a3df903ff43e8038R388-R393.

**Comment by jiaweitao001** [comment] 2022-10-08 03:31
Hi @azrael-lu , thanks for raising the issue. I have tried to reproduce this with the provided configuration, but failed. BTW, I noticed that you're using `chinanorth3` in the location field, I'm not sure if it's a location specific issue, since I was trying with `centralus` and `chinanorth3` is not an option for us.

**Comment by rcskosir** [comment] 2023-07-19 18:55
Thanks for opening this issue. Since time has passed and @jiaweitao001 was not able to reproduce this issue, I am going to mark this issue closed as “can’t reproduce”. If you are able to provide more information to help us reproduce this issue we may re-open this issue or open a new issue, thanks!

**Closed by rcskosir** 2023-07-19 18:55 UTC
Labels: bug, service/hdinsight, preview
