### ISSUE TITLE
azurerm_gallery_application_version: Ressource not in state, if errored

### ISSUE THREAD

**Issue by jkroepke** [hashicorp/terraform-provider-azurerm#22923] opened 2023-08-12 10:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.4

### AzureRM Provider Version

3.67.0

### Affected Resource(s)/Data Source(s)

azurerm_gallery_application_version

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-rg"
  location = "West Europe"
}

resource "azurerm_shared_image_gallery" "example" {
  name                = "examplegallery"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
}

resource "azurerm_gallery_application" "example" {
  name              = "example-app"
  gallery_id        = azurerm_shared_image_gallery.example.id
  location          = azurerm_resource_group.example.location
  supported_os_type = "Linux"
}

resource "azurerm_storage_account" "example" {
  name                     = "examplestorage"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_storage_container" "example" {
  name                  = "example-container"
  storage_account_name  = azurerm_storage_account.example.name
  container_access_type = "blob"
}

resource "azurerm_storage_blob" "example" {
  name                   = "scripts"
  storage_account_name   = azurerm_storage_account.example.name
  storage_container_name = azurerm_storage_container.example.name
  type                   = "Block"
  source_content         = "[scripts file content]"
}

resource "azurerm_gallery_application_version" "example" {
  name                   = "0.0.1"
  gallery_application_id = azurerm_gallery_application.example.id
  location               = azurerm_gallery_application.example.location

  manage_action {
    install = "[install command]"
    remove  = "[remove command]"
  }

  source {
    media_link = azurerm_storage_blob.example.id
  }

  target_region {
    name                   = azurerm_gallery_application.example.location
    regional_replica_count = 1
  }
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: creating Application Version (Subscription: "81ae40e4-a73e-49ed-ae42-ad441988dd01"
│ Resource Group Name: "rg-dev-opsstack-westeurope-001"
│ Gallery Name: "DEV_GAL_OPSSTACK_WESTEUROPE_001"
│ Application Name: "opsstack-agent-linux"
│ Version Name: "1.0.2"): polling after CreateOrUpdate: Code="GalleryApplicationVersionInternalError" Message="{\r\n  \"error\": {\r\n    \"innererror\": {},\r\n    \"code\": \"InternalExecutionError\",\r\n    \"message\": \"An internal execution error occurred. Please retry later.\"\r\n  }\r\n}"
│ 
│   with module.opsstack.azurerm_gallery_application_version.linux["1.0.2"],
│   on ../../terraform/modules/azure_opsstack/agent_gallery_application.tf line 27, in resource "azurerm_gallery_application_version" "linux":
│   27: resource "azurerm_gallery_application_version" "linux" {
│ 
│ creating Application Version (Subscription: "81ae40e4-a73e-49ed-ae42-ad441988dd01"
│ Resource Group Name: "rg-dev-opsstack-westeurope-001"
│ Gallery Name: "DEV_GAL_OPSSTACK_WESTEUROPE_001"
│ Application Name: "opsstack-agent-linux"
│ Version Name: "1.0.2"): polling after CreateOrUpdate: Code="GalleryApplicationVersionInternalError" Message="{\r\n  \"error\": {\r\n    \"innererror\": {},\r\n    \"code\": \"InternalExecutionError\",\r\n
│ \"message\": \"An internal execution error occurred. Please retry later.\"\r\n  }\r\n}"
╵

```

and next plan

```
│ Error: A resource with the ID "/subscriptions/xxx/resourceGroups/rg-dev-opsstack-westeurope-001/providers/Microsoft.Compute/galleries/DEV_GAL_OPSSTACK_WESTEUROPE_001/applications/opsstack-agent-linux/versions/1.0.2" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_gallery_application_version" for more information.
│ 
│   with module.opsstack.azurerm_gallery_application_version.linux["1.0.2"],
│   on ../../terraform/modules/azure_opsstack/agent_gallery_application.tf line 27, in resource "azurerm_gallery_application_version" "linux":
│   27: resource "azurerm_gallery_application_version" "linux" {
│ 
│ A resource with the ID
│ "/subscriptions/xxx/resourceGroups/rg-dev-opsstack-westeurope-001/providers/Microsoft.Compute/galleries/DEV_GAL_OPSSTACK_WESTEUROPE_001/applications/opsstack-agent-linux/versions/1.0.2"
│ already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_gallery_application_version" for more information.
╵
```

### Expected Behaviour

If resource should be imported into state except on BadRequest errors, since the resource exists on Azure, but in failed state. It would be great, if the resource would be marked as tainted, if errored.

Here is a screenshot of an existing application:

<img width="1201" alt="image" src="https://github.com/hashicorp/terraform-provider-azurerm/assets/1560587/86f72cf0-287b-41ac-b9fa-4d44f66fb4b6">

### Actual Behaviour

If the creation of the resource randomly fails, terraform doesn't know about the new resource. On next run, terraform want to create the application version again, but it fails, since it exists. in Azure.

After import the failed version, terraform remains nothing. A manual taint is required to resolve the issue. Since the provisioning state is not exposed, any post check could not be used here.

### Steps to Reproduce

The error is not easy to reproduce. 

1. terraform apply
2. terraform taint azurerm_storage_blob.example
3. terraform apply

**Comment by myc2h6o** [comment] 2023-08-14 08:16
@jkroepke thanks for opening the issue! It is by design that a resource is only put into the state when it is functional, so whenever API returns response code other than 2xx, the create operation is failed and the resource is not put into the state.

As for the entry created in Azure even in a failure, unfortunately, this may not be something that could be resolved in the provider. To resolve this in the provider, it would require an extra check for the Provisioning State in the Create, to delete the failed instance, which sounds risky, I'll leave this topic as an open discussion here.

**Comment by jkroepke** [comment] 2023-08-14 08:54
@myc2h6o I'm aware of this design and I see this on a lot resources like AKS, VM Extension, too. It's always a pain and requires a manual resolution.

> To resolve this in the provider, it would require an extra check for the Provisioning State in the Create, to delete the failed instance, which sounds risky

It fine for me to keep the failed instance just inside the state. If the resource is present in Azure, I except the resource in the state, too.

An other way to archive this would be the import block with (https://github.com/hashicorp/terraform/issues/33228) which may resolve the issue. Lucky, Azure Resource IDs are predictive.

However, in this situation, the taint detection based on the Provisioning State is still missing.

**Comment by tombuildsstuff** [comment] 2023-08-14 10:18
hey @jkroepke 

Thanks for opening this issue.

Taking a look through here this appears to be a similar request to #22862, [this comment on that issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/22862#issuecomment-1674447963) summarises the issue - however in short we're not doing this at this point in time due to the behaviour of the `provisioningState` field being misleading (insofar as `Failed` can mean `Succeeded`, `Failed` can also mean `will recover in the background`, `will be cleaned-up automatically` and/or `will sit around indefinitely`).

Since the design of the Azure API is the limiting factor here, whilst I'd like to thank you for opening this issue - I'm going to have to close this out as working as intended at this point-in-time - however as mentioned in #22862, should the information on how to recover resources become available in a programatic fashion, we can take another look into this.

Thanks!

**Closed by tombuildsstuff** 2023-08-14 10:18 UTC
Labels: v/3.x

**Comment by jkroepke** [comment] 2023-08-14 11:20
Hi @tombuildsstuff 

I would really interrest into a recover resources in a programatic fashion as you mention it.

I understand, that from provider point of view seems like impossible to decide what todo when provisioningState is not Success. I'm aware that each resource is too unique here to make a general decision.

I'm also interrest into a user-controlled solution. But for this, something needs to be done on terraform side. Like a lifecycle propertiy similiar to replace_by_trigger, like taint_by_condition.

The recovery into the state could be already archived with the import block in the next terraform version.

**Comment by tombuildsstuff** [comment] 2023-08-14 12:28
@jkroepke the lack of information would mean we couldn't offer a feature-toggle for this in any meaningful way (since we'd need to thread multiple sets of conditional logic into every Resource, which would need knowledge of the internal implementation details from each API/API Version (and to be updated every time we updated an API Version) - as such unfortunately that's not technically feasible at this point in time.

In addition, the lifecycle properties are managed entirely by Terraform Core (which has no context of what the Resource ID would be for a given Resource) - as such it's not possible for Terraform Core to do much to help here either.

Whilst other Terraform Providers can opt to take a different approach here - ultimately the limiting factor is the inconsistent/undocumented behaviour of the Azure API, so whilst I appreciate this isn't a great user experience when something goes wrong - without additional context unfortunately there's not a great deal we can do in this at this point in time.
