### ISSUE TITLE
Support for storage_data_disk in azurerm_linux_virtual_machine

### ISSUE THREAD

**Issue by djryanj** [hashicorp/terraform-provider-azurerm#17373] opened 2022-06-24 15:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, `storage_data_disk` is not an attribute that `azurerm_linux_virtual_machine` or `azurerm_windows_virtual_machine` supports and we are forced to use a secondary `azurerm_managed_disk` and `azurerm_virtual_machine_data_disk_attachment`. While on the surface, this doesn't seem like a big deal, in some cases this can cause problems.

Issues with not being able to use a `storage_data_disk` in an `azurerm_linux_virtual_machine` specifically:

- If using a `cloud-init`/`user_data`/`custom_data` script that mounts a disk to a specific location, it's very likely that the disk won't actually be created or attached when the script runs in the VM. Therefore the script fails.
- In line with above, if we are creating a VM from a custom image that requires either a snapshotted data disk to exist to be mounted at a specific location, that's not possible either at the moment (or it will cause a bunch of errors in the VM when it boots up, presuming the disk mounts to the right spot in the end).

As it stands, if we want to leverage that kind of functionality, we have to revert to using the (soon to be deprecated) `azurerm_virtual_machine` resource.

### New or Affected Resource(s)/Data Source(s)

`azurerm_linux_virtual_machine`, `azurerm_windows_virtual_machine`

### Potential Terraform Configuration

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_virtual_network" "example" {
  name                = "example-network"
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
}

resource "azurerm_subnet" "example" {
  name                 = "internal"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefixes     = ["10.0.2.0/24"]
}

resource "azurerm_network_interface" "example" {
  name                = "example-nic"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  ip_configuration {
    name                          = "internal"
    subnet_id                     = azurerm_subnet.example.id
    private_ip_address_allocation = "Dynamic"
  }
}

resource "azurerm_linux_virtual_machine" "example" {
  name                = "example-machine"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  size                = "Standard_F2"
  admin_username      = "adminuser"
  network_interface_ids = [
    azurerm_network_interface.example.id,
  ]

  admin_ssh_key {
    username   = "adminuser"
    public_key = file("~/.ssh/id_rsa.pub")
  }

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
  }

  source_image_reference {
    publisher = "Canonical"
    offer     = "UbuntuServer"
    sku       = "16.04-LTS"
    version   = "latest"
  }

  storage_data_disk {
    name          = "datadisk-1"
    lun           = 1
    create_option = "Empty"
  }
}
```

### References

https://stackoverflow.com/questions/61085490/using-cloud-init-on-an-azure-vm-to-mount-a-data-disk-fails

**Comment by tombuildsstuff** [comment] 2022-06-24 16:22
hi @djryanj 

Thanks for opening this issue.

Taking a look through this appears to be a duplicate of #6117 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #6117 for updates?

Thanks!

**Closed by tombuildsstuff** 2022-06-24 16:22 UTC
Labels: duplicate, enhancement, service/virtual-machine
