### ISSUE TITLE
azurerm_network_interface.spoke_vm1_vnic1.ip_configuration.name update in-place not possible!

### ISSUE THREAD

**Issue by ko5tas** [hashicorp/terraform-provider-azurerm#19369] opened 2022-11-20 17:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.5

### AzureRM Provider Version

3.31.0

### Affected Resource(s)/Data Source(s)

zurerm_network_interface

### Terraform Configuration Files

```hcl
resource "azurerm_network_interface" "spoke_vm1_vnic1" {
  name                = "spoke_vm1_vnic1"
  resource_group_name = azurerm_resource_group.netpoc_rg.name
  location            = var.vnet_location
  ip_configuration {
    name = "spoke_vm1_vnic1_ipconfig1"
    # Private IP attributes.
    subnet_id                     = azurerm_subnet.spoke_vms.id
    private_ip_address_allocation = "Dynamic"
    private_ip_address_version    = "IPv4"
  }
}
```

### Debug Output/Panic Output

```shell
Terraform will perform the following actions:

  # azurerm_network_interface.spoke_vm1_vnic1 will be updated in-place
  ~ resource "azurerm_network_interface" "spoke_vm1_vnic1" {
        id                            = "/subscriptions/<ommitted>resourceGroups/netpoc_rg/providers/Microsoft.Network/networkInterfaces/spoke_vm1_vnic1"
        name                          = "spoke_vm1_vnic1"
        tags                          = {}
        # (11 unchanged attributes hidden)

      ~ ip_configuration {
          ~ name                          = "somename_vm1_vnic1_ipconfig1" -> "spoke_vm1_vnic1_ipconfig1"
            # (5 unchanged attributes hidden)
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
azurerm_network_interface.spoke_vm1_vnic1: Modifying... [id=/subscriptions/<ommitted>resourceGroups/netpoc_rg/providers/Microsoft.Network/networkInterfaces/spoke_vm1_vnic1]
╷
│ Error: updating Network Interface: (Name "spoke_vm1_vnic1" / Resource Group "netpoc_rg"): network.InterfacesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="IpConfigDeleteNotSupported" Message="IP Configuration spoke_vm1_vnic1_ipconfig1 cannot be deleted. Deletion and renaming of primary IP Configuration is not supported" Details=[]
│
│   with azurerm_network_interface.spoke_vm1_vnic1,
│   on 004_vm.tf line 271, in resource "azurerm_network_interface" "spoke_vm1_vnic1":
│  271: resource "azurerm_network_interface" "spoke_vm1_vnic1" {
│
╵
```

### Expected Behaviour

The expected behaviour was to do an in-place replacement when updating ip_configuration {} name, not delete and re-create the resource withouth even giving a notice during terraform plan. 

### Actual Behaviour

Resource was not allowed to even be deleted and re-created. Had to track down the correct order of destroying resources and/or do a destroy and apply to everything as a faster workaround because that was a lab environment. 

That option would not be possible on a production environment. 

### Steps to Reproduce

Change azurerm_network_interface.spoke_vm1_vnic1.ip_configuration.name, 
terrraform apply

**Comment by wuxu92** [comment] 2022-11-22 06:25
Hi, @ko5tas thanks for your feedback. i wonder if the configuration content you provided in the description is the full-content version? i have tried it and it applies success with an update in place.

```
Terraform will perform the following actions:

  # azurerm_network_interface.spoke_vm1_vnic1 will be updated in-place
  ~ resource "azurerm_network_interface" "spoke_vm1_vnic1" {
        id                            = "/subscriptions/xxx/resourceGroups/xuwu1-rg/providers/Microsoft.Network/networkInterfaces/spoke_vm1_foo"
        name                          = "spoke_vm1_foo"
        tags                          = {}
        # (9 unchanged attributes hidden)

      ~ ip_configuration {
          ~ name                          = "spoke_vm1_vnic1_foo" -> "spoke_vm1_vnic1_bar"
            # (5 unchanged attributes hidden)
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

azurerm_network_interface.spoke_vm1_vnic1: Modifying... [id=/subscriptions/xxx/resourceGroups/xuwu1-rg/providers/Microsoft.Network/networkInterfaces/spoke_vm1_foo]
azurerm_network_interface.spoke_vm1_vnic1: Modifications complete after 8s [id=/subscriptions/xxx/resourceGroups/xuwu1-rg/providers/Microsoft.Network/networkInterfaces/spoke_vm1_foo]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

```

**Comment by rcskosir** [comment] 2023-09-28 20:28
Thanks for opening this issue. Since time has passed and @wuxu92  was not able to reproduce this issue, I am going to mark this issue closed as “can’t reproduce”. If you are able to provide more information to help us reproduce this issue we may re-open this issue or open a new issue, thanks!

**Closed by rcskosir** 2023-09-28 20:28 UTC
Labels: waiting-response, service/network-interfaces, v/3.x
