### ISSUE TITLE
`allow_blob_public_access` is not reflecting while upgrading provider version 1.44 to 2.23

### ISSUE THREAD

**Issue by jibinpb** [hashicorp/terraform-provider-azurerm#8187] opened 2020-08-20 11:36 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.28
+ provider.azurerm v2.23.0
```

### Affected Resource(s)

* `azurerm_storage_account`

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "example" {
  name                     = "teststoragexxx"
  resource_group_name      = data.azurerm_resource_group.example.name
  location                 = data.azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "LRS"

  enable_https_traffic_only = true
  ## ADDED
  allow_blob_public_access  = false

  network_rules {
    default_action = "Deny"
    bypass         = ["AzureServices"]
  }
}
```

### Debug Output

Nothing.
### Panic Output

Nothing.
### Expected Behavior
The property `allow_blob_public_access` should `disable` the configuration property `Allow Blob public access` of storage account

### Actual Behavior
Provision a storage account using AzureRm provider version `1.44` and property `allow_blob_public_access` is not available in that version. Then change the provider version to above `2.20` and set `false` for `allow_blob_public_access` explicitly.

The plan generated with `allow_blob_public_access` as `false` and no change, even though the portal shows *Enabled*. 

This is the generated plan for updating Storage with new provider on **Step Number `4`**
![allow_blob_public_access-update_plan](https://gist.githubusercontent.com/jibinpb/1fc9ec28e95bd1ccfa48a2e32b91f8cc/raw/d134be452e6c312064038a9b7d7df5c76b1414c7/allow_blob_public_access-update_plan.png)

After the applying the plan **Step Number `5`** it did not made any change to configuration property `Allow Blob public access`, but Account Kind is changed as per the plan. 
![allow_blob_public_access-azure_portal](https://gist.githubusercontent.com/jibinpb/1fc9ec28e95bd1ccfa48a2e32b91f8cc/raw/d134be452e6c312064038a9b7d7df5c76b1414c7/allow_blob_public_access-azure_portal.png)

### Steps to Reproduce

1. Create storage account using AzureRm provider version `1.44`
    ```hcl
    terraform {
        required_version = ">= 0.11"
        required_providers {
            azurerm = "~> 1.44"
        }
    }

    provider "azurerm" {
    features {}
    }

    data "azurerm_resource_group" "example" {
    name     = "test-rg"
    }

    resource "azurerm_storage_account" "example" {
    name                     = "teststoragexxx"
    resource_group_name      = data.azurerm_resource_group.example.name
    location                 = data.azurerm_resource_group.example.location
    account_tier             = "Standard"
    account_replication_type = "LRS"

    enable_https_traffic_only = true

    network_rules {
        default_action = "Deny"
        bypass         = ["AzureServices"]
    }
    }
    ```
2. `terraform apply`
3. Change AzureRm provider version to `~> 2.20` and set `false` for `allow_blob_public_access`.
    ```hcl
    terraform {
        required_version = ">= 0.11"
        required_providers {
            azurerm = "~> 2.20"
        }
    }

    provider "azurerm" {
    features {}
    }

    data "azurerm_resource_group" "example" {
    name     = "test-rg"
    }

    resource "azurerm_storage_account" "example" {
    name                     = "teststoragexxx"
    resource_group_name      = data.azurerm_resource_group.example.name
    location                 = data.azurerm_resource_group.example.location
    account_tier             = "Standard"
    account_replication_type = "LRS"

    enable_https_traffic_only = true
    ## ADDED
    allow_blob_public_access  = false

    network_rules {
        default_action = "Deny"
        bypass         = ["AzureServices"]
    }
    }
    ```
4. `terraform plan`
5. `terraform apply`

### Important Factoids

Nothing.
### References

* [allow_blob_public_access](https://www.terraform.io/docs/providers/azurerm/r/storage_account.html#allow_blob_public_access)

**Comment by neil-yechenwei** [comment] 2020-08-24 07:35
Thanks for opening this issue. After investigated, seems api returns nil while not specifying the value of allow_blob_public_access. So terraform should return the default status. And I also found the default value for this property from api side should be true not false. So I submit a [PR](https://github.com/terraform-providers/terraform-provider-azurerm/pull/8216) to fix the issue.

**Comment by jibinpb** [comment] 2020-08-24 08:58
Thank you so much @neil-yechenwei , will use PowerShell as interim fix

**Comment by smitp11** [comment] 2020-12-02 22:55
Having the exact same issue on:
Terraform v0.12.24
+ provider.azurerm v2.23.0

@jibinpb - could you share a PowerShell example of your interim fix?

**Comment by jibinpb** [comment] 2020-12-07 11:01
Here is the script, applied manually.

```powershell
# Install-Module -Name Az.ResourceGraph
# Install-Module -Name Az.Storage

$Subscription = "YOUR-SUBSCRIPTION-ID"
$StorageAccounts = Search-AzGraph -Query "
Resources 
    | where type =~ 'Microsoft.Storage/storageAccounts' 
        and isempty(properties.allowBlobPublicAccess)" -Subscription $Subscription
foreach ($StorageAccount in $StorageAccounts) {
    Write-Host "$($StorageAccount.resourceGroup) / $($StorageAccount.name)"    
    Set-AzStorageAccount  -ResourceGroupName $StorageAccount.resourceGroup -AccountName $StorageAccount.name -AllowBlobPublicAccess $false
}
```

**Comment by kevinmatthews-kpmg** [comment] 2021-01-04 14:54
is there any progress on this? Manually disabling public access on everything is going to be quite a large task to do.

**Comment by AnishJS** [comment] 2021-02-15 16:17
Considering it's a thing which gets flagged on Azure Advisor, it really needs a push (please)

**Comment by Miouge1** [comment] 2021-02-22 11:24
I ran into this as well, I was able to narrow things down to: [v2.19.0](https://github.com/terraform-providers/terraform-provider-azurerm/releases/tag/v2.19.0), [v2.20.0](https://github.com/terraform-providers/terraform-provider-azurerm/releases/tag/v2.20.0),  #7739 and #7784.

I have been testing with TF v0.14.6

You can reproduce with the following snippet:
```terraform
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "= 2.18.0" # step 1
      #version = "= 2.19.0" # step 2
    }
  }
  required_version = ">= 0.13"
}
provider "azurerm" {
  features {}
}
resource "azurerm_resource_group" "this" {
  name     = "test-8187"
  location = "westeurope"
}
resource "azurerm_storage_account" "this" {
  depends_on                = [azurerm_resource_group.this]
  name                      = "test8187"
  resource_group_name       = azurerm_resource_group.this.name
  location                  = azurerm_resource_group.this.location
  account_tier              = "Standard"
  account_replication_type  = "LRS"
  enable_https_traffic_only = true
  account_kind              = "StorageV2"
  # allow_blob_public_access use default
}

```

```shell
$ terraform init -upgrade
Terraform has been successfully initialized!
$ terraform apply
Apply complete! Resources: 2 added, 0 changed, 0 destroyed.
```

Now check in the portal you will see: `Allow Blob public access: Enabled`, as is default in Azure.

Then you upgrade to v2.19 (uncomment the version requirements):
```shell
$ terraform init -upgrade
Terraform has been successfully initialized!
$ terraform apply
Terraform will perform the following actions:

  # azurerm_storage_account.this will be updated in-place
  ~ resource "azurerm_storage_account" "this" {
      ~ allow_blob_public_access       = false -> true
Plan: 0 to add, 1 to change, 0 to destroy.
```

Then finally you upgrade to v2.20 (uncomment the version requirements):

```
$ terraform init -upgrade
Terraform has been successfully initialized!

$ terraform apply
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

Therefore if you create a storage account with v2.18 (or older) and upgrade to v2.20 (or newer), then the storage account is stuck with the old defaults (enabled/true), but probably expect the new defaults to take effect (disabled/false).

One work around is to set `allow_blob_public_access` to `true`, apply, then remove it and you are out of this weird situation.

**Comment by severity1** [comment] 2021-03-01 06:03
Just bumped into this issue, will be trying out @Miouge1's solution

**Comment by kgrvamsi** [comment] 2021-04-05 17:01
I did the same what @Miouge1  said but this scenario is really weird and looks like it should have defaults to true and then change to false

### One work around is to set allow_blob_public_access to true, apply, then remove it and you are out of this weird situation.

**Comment by surlypants** [comment] 2021-05-14 13:45
ouch. infosec is mad

**Comment by favoretti** [comment] 2021-08-25 09:47
Thanks for opening this issue! Since this issue has been reported a long time ago and relates to an older version of provider - I'm going to close it. If this is still relevant and occurring on the latest version of terraform and provider please do open a new issue!

**Closed by favoretti** 2021-08-25 09:47 UTC
Labels: service/storage
