### ISSUE TITLE
Error: #Crash #Plugin -  Plugin Crashed did not respond on terraform apply

### ISSUE THREAD

**Issue by dharanidhar-m** [hashicorp/terraform-provider-azurerm#13375] opened 2021-09-16 07:58 UTC
On Terraform apply, getting "Plugin did not respond and request cancelled errors"

Terraform Version: 1.0.2
Azure RM provider: 2.75.0

The error is as follows:
Error: Plugin did not respond
│ 
│   with azurerm_log_analytics_workspace.azlogws,
│   on baseinfra.tf line 644, in resource "azurerm_log_analytics_workspace" "azlogws":
│  644: resource "azurerm_log_analytics_workspace" "azlogws" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.

 Error: Request cancelled
│ 
│   with azurerm_mssql_firewall_rule.mssql-fw,
│   on baseinfra.tf line 481, in resource "azurerm_mssql_firewall_rule" "mssql-fw":
│  481: resource "azurerm_mssql_firewall_rule" "mssql-fw" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.

github.com/hashicorp/terraform-provider-azurerm/internal/services/cosmos.resourceCosmosDbAccountRead(0xc001891480, 0x5935640, 0xc0013eb880, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/services/cosmos/cosmosdb_account_resource.go:841 +0x2173
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000787880, 0x69098e8, 0xc002c10040, 0xc001891480, 0x5935640, 0xc0013eb880, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:335 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000787880, 0x69098e8, 0xc002c10040, 0xc0008c2a80, 0x5935640, 0xc0013eb880, 0xc00151d230, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00117a600, 0x69098e8, 0xc002c10040, 0xc002c10080, 0xc002c10040, 0x40b965, 0x5c655e0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:575 +0x43b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc001cc75a0, 0x6909990, 0xc002c10040, 0xc001a143c0, 0xc001cc75a0, 0xc000c84de0, 0xc0012a6ba0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x5e29060, 0xc001cc75a0, 0x6909990, 0xc000c84de0, 0xc001a14360, 0x0, 0x6909990, 0xc000c84de0, 0xc001a21600, 0xcfb)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003fe700, 0x6958398, 0xc001b46480, 0xc002159d40, 0xc000ea04e0, 0x9fa22b0, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0003fe700, 0x6958398, 0xc001b46480, 0xc002159d40, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1617 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000d44200, 0xc0003fe700, 0x6958398, 0xc001b46480, 0xc002159d40)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:940 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:938 +0x1fd

Error: The terraform-provider-azurerm_v2.75.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue

Please help me in resolving the issue !

**Comment by dharanidhar-m** [comment] 2021-09-17 07:13
I have tried with latest Azure RM provider 2.77  still I see the same issue

**Comment by stephybun** [comment] 2021-09-29 11:37
Hi @dharanidhar-m, thanks for reporting this crash. From the issue history it seems that this is a duplicate of #13414. Before I close this one could you please confirm whether the fix in #13432 which was released in 2.78.0 solved this issue?

**Comment by mbfrahry** [comment] 2021-12-14 16:17
This looks to be closed in #13432! Thanks for hunting that down @stephybun. Feel free to reopen this issue if you continue to this issue @dharanidhar-m

**Closed by mbfrahry** 2021-12-14 16:17 UTC
Labels: crash, service/cosmosdb
