### ISSUE TITLE
Bug Report: Mismatch in reboot Values for azurerm_maintenance_configuration

### ISSUE THREAD

**Issue by morbendor** [hashicorp/terraform-provider-azurerm#26395] opened 2024-06-19 12:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.0

### AzureRM Provider Version

3.108.0

### Affected Resource(s)/Data Source(s)

azurerm_maintenance_configuration

### Terraform Configuration Files

```hcl
resource "azurerm_maintenance_configuration" "windows" {
  name                     = "windows-mc"
  resource_group_name      = module.rg.resource_group_name
  location                 = module.rg.location
  scope                    = "InGuestPatch"
  in_guest_user_patch_mode = "User"
  install_patches {
    reboot = "Never"
    windows {
      classifications_to_include = ["Critical", "Security"]
    }
  }
  window {
    start_date_time = "2024-06-18 00:00"
    time_zone       = "UTC-11"
    recur_every     = "Week"
    duration        = "01:30"
  }

  tags = {
    Env = "dev"
  }
}

resource "azurerm_maintenance_assignment_virtual_machine" "windows" {
  location                     = module.rg.location
  maintenance_configuration_id = azurerm_maintenance_configuration.windows.id
  virtual_machine_id           = module.windows.vm_id
}
```

### Debug Output/Panic Output

```shell
# module.azure_update_manager_linux.azurerm_maintenance_configuration.config[0] will be updated in-place
  ~ resource "azurerm_maintenance_configuration" "config" {
        id                       = "/subscriptions/6f5500a0-ded2-4f21-b5fe-95276272403c/resourceGroups/rg-patch-test-dev1/providers/Microsoft.Maintenance/maintenanceConfigurations/linux-mc"
        name                     = "linux-mc"
        tags                     = {}
        # (6 unchanged attributes hidden)

      ~ install_patches {
          ~ reboot = "NeverReboot" -> "Never"

            # (1 unchanged block hidden)
        }

        # (1 unchanged block hidden)
    }
```

### Expected Behaviour

The reboot attribute should align between the Terraform provider and the Azure API, ensuring no changes are detected if the configuration remains the same.

### Actual Behaviour

I am using the install_patches block under the azurerm_maintenance_configuration resource in my Terraform configuration. According to the [Terraform Registry documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/maintenance_configuration#kb_numbers_to_exclude), the reboot attribute within install_patches should accept the following values:

- Always
- IfRequired
- Never

However, the Azure API always returns NeverReboot for this attribute, leading to a persistent mismatch between my Terraform configuration and the Azure API response.

### Steps to Reproduce

terraform apply -auto-approve
terraform apply -auto-approve

**Comment by nnstt1** [comment] 2024-06-20 14:48
Probably a duplicate of #24511

**Comment by rcskosir** [comment] 2024-06-20 19:04
Thanks for taking the time to open this issue. Upon review, I agree with @nnstt1 that this appears to be a duplicate. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of #24511.

**Closed by rcskosir** 2024-06-20 19:04 UTC
Labels: duplicate, service/maintenance, v/3.x
