### ISSUE TITLE
r/application_insights_web_test: application_insights_id should be normalized

### ISSUE THREAD

**Issue by ppanyukov** [hashicorp/terraform-provider-azurerm#12184] opened 2021-06-11 12:22 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.14.4
+ provider registry.terraform.io/hashicorp/azurerm v2.62.1
```

### Affected Resource(s)

* `azurerm_monitor_metric_alert`
* possibly many others!

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "test-import-bug"
  location = "West Europe"
}

resource "azurerm_application_insights" "example" {
  name                = "test-import-bug"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  application_type    = "web"
}

# This is an existing resource, and needs to be imported.
resource "azurerm_monitor_metric_alert" "example" {
  name                = "test-import-bug"
  resource_group_name = azurerm_resource_group.example.name
  scopes              = [azurerm_application_insights.example.id]

  severity = 3
  target_resource_type = "microsoft.insights/components"

  dynamic_criteria {
    metric_namespace = "microsoft.insights/components"
    metric_name = "requests/failed"
    aggregation = "Count"
    operator = "GreaterThan"
    alert_sensitivity = "Medium"
    evaluation_total_count = 4
    evaluation_failure_count = 4
  }
}
```

### Bug summary

When doing `terraform import` the operation succeeds but the state file can be botched and  not populated with real values if you used wrong case sensitivity in your resource ID. The effect is the resource is completely unusable.

Examples:

```bash
# BOTCHED.
# 
# I copied the resource ID form my existing alert from Portal.
# Produces BOTCHED state.
terraform import \
    azurerm_monitor_metric_alert.example \
    /subscriptions/REDACTED/resourceGroups/test-import-bug/providers/Microsoft.Insights/metricalerts/test-import-bug  
```

```bash
# WORKS.
# 
# Change 'metricalerts' => 'metricAlerts'.
# 
terraform import \
    azurerm_monitor_metric_alert.example \
    /subscriptions/REDACTED/resourceGroups/test-import-bug/providers/Microsoft.Insights/metricAlerts/test-import-bug  
```

### Root cause

Caused by case-sensitivy bug in `monitor_metric_alert_resource.go`

```go
// monitor_metric_alert_resource.go
// https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/monitor/monitor_metric_alert_resource.go#L496
func resourceMonitorMetricAlertRead(d *pluginsdk.ResourceData, meta interface{}) error {
  // ...
	name := id.Path["metricAlerts"]  // <== here!
  // ...
```

So the resource ID must have exactly `metricAlerts` in it, with exact case. This is the reason the import with ID copied from Portal didn't quite work.

And the further cause of this the `ResourceID` type. The member `Path` here is a `map` which is case-sensitive.

```go
// resourceid.go
// https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/helpers/azure/resourceid.go#L18
type ResourceID struct {
	SubscriptionID string
	ResourceGroup  string
	Provider       string
	Path           map[string]string
}
```

### How the state gets BOTCHED

When using the "wrong" case, we get "empty" state:

```json
{
  "mode": "managed",
  "type": "azurerm_monitor_metric_alert",
  "name": "example",
  "provider": "provider[\"registry.terraform.io/hashicorp/azurerm\"]",
  "instances": [
    {
      "schema_version": 0,
      "attributes": {
        "action": [],
        "application_insights_web_test_location_availability_criteria": [],
        "auto_mitigate": null,
        "criteria": [],
        "description": null,
        "dynamic_criteria": [],
        "enabled": null,
        "frequency": null,
        "id": "/subscriptions/REDACTED/resourceGroups/test-import-bug/providers/Microsoft.Insights/metricalerts/test-import-bug",
        "name": "",
        "resource_group_name": "test-import-bug",
        "scopes": null,
        "severity": null,
        "tags": {},
        "target_resource_location": null,
        "target_resource_type": null,
        "timeouts": {
          "create": null,
          "delete": null,
          "read": null,
          "update": null
        },
        "window_size": null
      },
      "sensitive_attributes": [],
      "private": "REDACTED"
    }
  ]
}
```

### The effect of this

When trying to do terraform plan it says it wants to replace the resource.

When trying to actually apply this, we get error from Azure RM API.

```hcl
  # azurerm_monitor_metric_alert.example must be replaced
-/+ resource "azurerm_monitor_metric_alert" "example" {
      + auto_mitigate            = true
      + enabled                  = true
      + frequency                = "PT1M"
      ~ id                       = "/subscriptions/REDACTED/resourceGroups/test-import-bug/providers/Microsoft.Insights/metricalerts/test-import-bug" -> (known after apply)
      + name                     = "test-import-bug" # forces replacement
```

### Other affected areas

I can see this `ResourceID.Path` is used quite a lot elsewhere, e.g.

```go
func resourceApplicationInsightsAPIKeyRead(d *schema.ResourceData, meta interface{}) error {
	appInsightsName := id.Path["components"]
	keyID := id.Path["apikeys"]
}

func resourceDedicatedHostGroupRead(d *schema.ResourceData, meta interface{}) error {
	resourceGroupName := id.ResourceGroup
	name := id.Path["hostGroups"]
}

// etc
```

### Expected Behaviour

* Differences in case should not affect import.
* If Azure RM API treats Resource IDs in case-insensitive way, then so should `azurerm` provider.
* If case **is** important, and user supplies wrong case, import should fail.
* Copying `ResourceID` form Portal and using it for `import` should always work.

### Potential Fix

Not being an expert, but it feels the `ResourceID` type is at fault here. It's just too raw and does not encapsulate IDs in "canonical" and comparable form.

In fact, this type probably shouldn't the the resposibility of `azurerm` provider, it should be supplied by `Azure SDK for Go` as its best positioned to know what the canonical IDs are, and how to deal with them.

But anyway, for example, the components map could use case-insensitive keys, e.g. convert to lower-case. And then instead of having raw `map` as a field, have a method `Path()` instead, e.g.

```go
type ResourceID struct {
	SubscriptionID string
	ResourceGroup  string
	Provider       string
	// private implementation
	path           map[string]string
}

func (r *ResourceID) Path(key string) (result string, found bool) {
	keyLower := strings.ToLower(key)
	result, found = r.path[keyLower]
	return
}
```

This type looks quite full of these case-related issues. Just looking at this code:

```go
	if resourceGroup, ok := componentMap["resourceGroups"]; ok {
		idObj.ResourceGroup = resourceGroup
		delete(componentMap, "resourceGroups")
	} else if resourceGroup, ok := componentMap["resourcegroups"]; ok {
		// Some Azure APIs are weird and provide things in lower case...
		// However it's not clear whether the casing of other elements in the URI
		// matter, so we explicitly look for that case here.
		idObj.ResourceGroup = resourceGroup
		delete(componentMap, "resourcegroups")
	}
```

What if my resource ID string has `ResouRceGroups` in it? :) 

I'm sure the maintainers here will be in a much better position to decide on the course of action than I can think of though :) 

----

PS. I actually also have my own `ResourceID` type which I also, sadly, had to implement, and I have this (it's not without issues as well):

```go
type ResourceID struct {
	ID string
	SubscriptionID string
	ResourceGroup string
	Provider string
	Name string
}

// Canonical returns resource ID in canonical format, with all values
// converted to lower case, making them directly comparable and usable as maps keys etc.
func (id *ResourceID) Canonical() *ResourceID {
	return &ResourceID{
		ID:             strings.ToLower(id.ID),
		SubscriptionID: strings.ToLower(id.SubscriptionID),
		ResourceGroup:  strings.ToLower(id.ResourceGroup),
		Provider:       strings.ToLower(id.Provider),
		Name:           strings.ToLower(id.Name),
	}
}


// IsSameID returns true if this ID is the same as another ID, ignoring case.
func (r *ResourceID) IsSameID(id string) bool {
	return IsSameID(r.ID, id)
}

// IsSameIDPtr returns true if this ID is the same as another ID, ignoring case.
func (r *ResourceID) IsSameIDPtr(id *string) bool {
	return IsSameID(r.ID, to.String(id))
}

// IsSame returns true if this ID is the same as another ID, ignoring case.
func (r *ResourceID) IsSame(id *ResourceID) bool {
	return IsSameID(r.ID, id.ID)
}

// IsSameName returns true if this ID has the same name as the argument, ignoring case.
func (r *ResourceID) IsSameName(name string) bool {
	return strings.EqualFold(r.Name, name)
}

// IsSameResourceGroup returns true if this ID has the same resource group name as the argument, ignoring case.
func (r *ResourceID) IsSameResourceGroup(resourceGroup string) bool {
	return strings.EqualFold(r.ResourceGroup, resourceGroup)
}

// IsSameNameAndRg returns true if this ID has the same resource group name and name as the arguments, ignoring case.
func (r *ResourceID) IsSameNameAndRg(resourceGroup string, name string) bool {
	return r.IsSameResourceGroup(resourceGroup) && r.IsSameName(name)
}

// IsSameID returns true if two IDs refer to the same resource, ignoring case.
func IsSameID(id1 string, id2 string) bool {
	return strings.EqualFold(id1, id2)
}
```

**Comment by sonofhammer** [comment] 2021-11-04 22:04
Microsoft docs on case sensitivity in azure: https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules

A couple of things of interest from the docs:

> Resource names are case-insensitive unless noted in the valid characters column.

and

>  When retrieving resource names using various APIs, returned values may display different case values than what is listed in the valid characters table.

It looks like azurerm provider treats some resources as case-sensitive when Azure itself doesn't.

( I personally ran into this issue with resource group names and storage accounts after upgrading from v.138 to v v1.40 of the provider and running into [this change](https://github.com/hashicorp/terraform-provider-azurerm/pull/5289). v2.82 still exhibits the issue)

**Comment by ppanyukov** [comment] 2021-11-15 14:54
And here is the same issue again. Updating from 2.70.0 to 2.85.0 version of provider:

```hcl
-/+ resource "azurerm_application_insights_web_test" "availability_test" {
      ~ application_insights_id = 
          "/subscriptions/REDACTED/resourceGroups/REDACTED/providers/microsoft.insights/components/REDACTED" 
       -> "/subscriptions/REDACTED/resourceGroups/REDACTED/providers/Microsoft.Insights/components/REDACTED" # forces replacement
```

Was `microsoft.insights` now `Microsoft.Insights`. :(

**Comment by tombuildsstuff** [comment] 2021-11-15 17:29
hi @ppanyukov

Having chatted extensively with the Azure ARM Team about this - Azure API's are supposed to be case-insensitive during Requests but case-sensitive in responses. Unfortunately different Azure Service Teams have interpreted this in slightly different manners - with some following this, others assuming that Resource ID's are fully case-insensitive.

This also extends to fields in the API, where whilst the API may accept these case-insensitively - however the provisioned resources don't behave correctly behind the scenes. One such example of this that affected the Kusto Cluster resource was where it was possible to provision a Cluster but you can't actually login to it unless the Sku casing matched exactly. These issues exist across the Azure API's - and whilst it's possible to treat Resource ID's as case insensitive in some scenarios - this breaks others (including any third-party tooling, since most tooling is case-sensitive) - unfortunately if everything isn't case-insensitive then it has to be treated as case-sensitive.

By design in Terraform the ID for a given Resource has to match exactly (byte-for-byte) - as should all of the fields within it. The ARM Specification itself defines the segments of a Resource ID (for example `components`) as camelCased (so for example `virtualnetworks` should be `virtualNetwork`) - and Resource Providers (e.g. `microsoft.insights`) are supposed to be TitleCase (e.g. `Microsoft.Insights`).

To ensure we can handle both scenarios, Terraform now defines the Resource ID based on the values the Azure API is expecting - which we also validate at Import time to ensure these are consistent with what we're expecting to be able to parse. In cases where we know what the Resource ID is, we can then normalise this (by parsing the Resource ID case-insensitively and formatting as expected) to workaround API issues.

At this point in time the majority of Resource ID's used in the Provider are now defined and validated in Terraform (based on what the Azure API is expecting) - and we'll be closing the gaps as we spot them, including normalising them if the API returns this data incorrectly where necessary.

In this instance I'm going to update this issue to refer to this bug in the `azurerm_application_insights_web_test` resource, since this needs to be fixed there (by normalising this field coming back from Azure).

Thanks!

**Comment by rickardp** [comment] 2021-11-22 07:19
@tombuildsstuff Please also see #13819 where there is an example of a case that will trigger a recreate every time (due to different casing in response).

**Comment by tombuildsstuff** [comment] 2021-11-22 13:50
@rickardp yeah it's the same problem as above unfortunately

**Comment by rickardp** [comment] 2021-11-22 13:52
@tombuildsstuff Yes, I think your suggested approach (to treat them one by one) is the only feasible one, from looking at how the APIs work. How should these be reported? Are they all handled in this issue?

**Comment by bm77525-kr** [comment] 2021-12-14 22:09
> How should these be reported? Are they all handled in this issue?

@tombuildsstuff  I'd also like to know this. I recently tried to upgrade from 2.74 to 2.89 and ran into a bunch of resources wanting to be replaced because the casing seemed to change in the resource ID's, mostly around azure monitor related resources.

**Comment by tgolly** [comment] 2022-03-23 05:37
@tombuildsstuff  Is there any kind of workaround for when you hit this issue?   

Right now I'm working on a small change that's going to inadvertently force recreation of vnet and private endpoint resources (back to the same state they are in now) and I'd prefer not to do this if I can (in Prod at least).

**Comment by tbertenshaw** [comment] 2023-01-30 11:02
Is there any update on this issue? Fix or workaround? i have just encountered it and spotted after stepping one version at a time that it is 2.83 which causes this issue, prior to that my plan didnt want to destroy and recreate the `azurerm_application_insights_web_test`s.

**Comment by ReySka91** [comment] 2023-05-11 10:38
Anu update, fix or workaround for this?

**Comment by esdccs1** [comment] 2023-05-18 17:14
@tombuildsstuff 
also encountered this issue with the terraform resource `azurerm_private_endpoint`
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/private_endpoint

resource "azurerm_private_endpoint" "example" {
  ...
  private_dns_zone_group {
    name                 = "example-dns-zone-group"
    private_dns_zone_ids = [azurerm_private_dns_zone.example.id]  # <---- case-sensitive bug revealed here
  }
}

In a terraform plan, an unexpected diff was as follows:
```
- /subscriptions/***/resourceGroups/mycasesensitivename/providers/Microsoft.Network/...
+ /subscriptions/***/resourceGroups/MyCaseSensitiveName/providers/Microsoft.Network/...
```

**Comment by myc2h6o** [comment] 2023-05-19 03:14
@esdccs1 the normalization is for static segment like `Microsoft.Network` only, as for user-specified segments like resource group name, it is considered case-sensitive currently.

**Closed** 2023-05-22 16:22 UTC
Labels: bug, service/application-insights

**Comment by myc2h6o** [comment] 2023-05-24 05:07
@esdccs1 for the resource group name the issue is trickier, so more thinking would be needed before it could be fixed. As such, feel free to open a new issue regarding to the issue you met.
