### ISSUE TITLE
Cannot destroy stopped VM if a VM extension is attached, created from a module

### ISSUE THREAD

**Issue by jamescrowley** [hashicorp/terraform-provider-azurerm#17251] opened 2022-06-14 17:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.2

### AzureRM Provider Version

3.10.0

### Affected Resource(s)/Data Source(s)

azurerm_virtual_machine_extension

### Terraform Configuration Files

```hcl
*** main.tf:
module "lin-vm" {
  source  = "../modules/lin-vm"
  vm-name = "mycoolvm"
  vm-location = "westus"
  vm-rsg = "mycoolrg"
  vm-size = "Standard_E2s_v3"
  vm-subnet_id = "${module.network.subnet_ids[2]}"
}

*** modules/lin-vm/main.tf:
resource "azurerm_network_interface" "nic" {
  name                = "${var.vm-name}-nic"
  location            = "${var.vm-location}"
  resource_group_name = "${var.vm-rsg}"

  ip_configuration {
    name                          = "${var.vm-name}-ipc"
    subnet_id                     = "${var.vm-subnet_id}"
    private_ip_address_allocation = "dynamic"
  }
}

resource "azurerm_virtual_machine" "vm" {
  name                             = "${var.vm-name}"
  location                         = "${var.vm-location}"
  resource_group_name              = "${var.vm-rsg}"
  network_interface_ids            = ["${azurerm_network_interface.nic.id}"]
  vm_size                          = "${var.vm-size}"
  delete_os_disk_on_termination    = true
  delete_data_disks_on_termination = true

  storage_image_reference {
    publisher = "Canonical"
    offer     = "UbuntuServer"
    sku       = "16.04-LTS"
    version   = "latest"
  }

  storage_os_disk {
    name              = "${var.vm-name}-osdisk"
    caching           = "ReadWrite"
    create_option     = "FromImage"
    managed_disk_type = "Standard_LRS"
  }

  os_profile {
    computer_name  = "${var.vm-name}"
    admin_username = "${var.vm-username}"
    admin_password = "${var.vm-password}"
  }

  os_profile_linux_config {
    disable_password_authentication = false
  }
}

resource "azurerm_virtual_machine_extension" "network-watcher" {
  name                    = "${var.vm-name}-la-ext"
  location                = "${var.vm-location}"
  resource_group_name     = "${var.vm-rsg}"
  virtual_machine_name    = "${azurerm_virtual_machine.vm.name}"
  publisher               = "Microsoft.Azure.NetworkWatcher"
  type                    = "NetworkWatcherAgentLinux"
  type_handler_version      = "1.4"
  auto_upgrade_minor_version = "true"
}

*** modules/lin-vm/variables.tf:
variable "vm-name" {
    description = "Name of the virtual machine"
}
variable "vm-location" {
    description = "Location to deploy virtual machine"
}
variable "vm-rsg" {
    description = "Resource group for the virtual machine"
}
variable "vm-size" {
    description = "VM Sku size"
}
variable "vm-username" {
    description = "Username"
}
variable "vm-password" {
    description = "Password"
}
variable "vm-subnet_id" {
    description = "Subnet ID for the virtual machine"
}
```

### Debug Output/Panic Output

```shell
compute.VirtualMachineExtensionsClient#Delete: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="OperationNotAllowed" Message="Cannot modify extensions in the VM when the VM is not running.
```

### Expected Behaviour

It should be able to delete the VM and the corresponding extension whilst stopped.

### Steps to Reproduce

Create a module that deploys both extension and a VM, apply, shutdown VM then destroy.

### References

This is essentially a special case of - https://github.com/hashicorp/terraform-provider-azurerm/issues/6098 - but in the deletion case as noted in the comment https://github.com/hashicorp/terraform-provider-azurerm/issues/6098#issuecomment-1054411399, surely we can just continue with deletion of the VM? 

Also, https://github.com/hashicorp/terraform-provider-azurerm/issues/477 which was closed but wasn't actually fixed, at least in the module case.

**Comment by tombuildsstuff** [comment] 2022-06-15 06:36
Duplicate of #6098

**Closed by tombuildsstuff** 2022-06-15 06:36 UTC
