### ISSUE TITLE
Add support for Policy fragments in azure api managment 

### ISSUE THREAD

**Issue by liorklein** [hashicorp/terraform-provider-azurerm#20213] opened 2023-01-30 09:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

add support in terraform for azure apim policy fragment

### New or Affected Resource(s)/Data Source(s)

azure api management policy fragment

**Comment by manicminer** [comment] 2023-01-30 21:09
Duplicate of #17016

**Closed by manicminer** 2023-01-30 21:09 UTC
