### ISSUE TITLE
App Configuration disable public network access

### ISSUE THREAD

**Issue by PaulCardus** [hashicorp/terraform-provider-azurerm#17249] opened 2022-06-14 16:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In the Azure portal there are options to disable and enable public network access, just like the sql azurerm features, we should be able to pass in a flag to choose our options.

### New or Affected Resource(s)/Data Source(s)

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_configuration

### Potential Terraform Configuration

```hcl
variable "appconfig_public_network_access_enabled" {
  type    = bool
  default = true
}
```

### References

https://docs.microsoft.com/en-us/azure/azure-app-configuration/howto-disable-public-access?tabs=azure-portal

**Comment by sioakim** [comment] 2022-07-05 14:21
The default behaviour when you create the resource from TF is to use Automatic which would enable the Public Endpoint and then as a second step when you enable a Private Endpoint it will switch it off.

_Scenario:_
If a Deny policy exists that doesn't allow "the Public Access" then it is not possible to create the resource as the first step (App Configuration creation) will fail.

So ideally, we would need to have an option from TF to create it with "Access Options: Disabled" and then attach the Private Access resource.

**Comment by CorrenSoft** [comment] 2022-07-07 13:57
I think that is duplicated of #12876

**Comment by tombuildsstuff** [comment] 2022-07-13 14:42
Duplicate of #12876 - thanks @CorrenSoft

**Closed by tombuildsstuff** 2022-07-13 14:42 UTC
Labels: enhancement, service/app-configuration
