### ISSUE TITLE
skip_provider_registration doesn't work and still tries to register the provider.

### ISSUE THREAD

**Issue by rahtr** [hashicorp/terraform-provider-azurerm#14727] opened 2021-12-23 19:59 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.0.2
on windows_amd64

### Affected Resource(s)

* `azurerm_XXXXX`

### Expected Behaviour
TF should skip the provider registration

### Actual Behaviour
Here is my provider configuration:
`provider.tf`
```
provider "azurerm" {

  features {}

        subscription_id = "${var.azure.AzureSubscriptionId}"

        client_id       = "${var.azure.AzureClientId}"

        client_secret   = "${var.azure.AzureClientSecret}"

        tenant_id       = "${var.azure.AzureTenantId}"

        skip_provider_registration = true

}

provider "aws" {

        region     = "${var.aws.AwsRegion}"

        access_key = "${var.aws.AwsAccessKey}"

        secret_key = "${var.aws.AwsSecretKey}"

}
```
and this is how my root module is configured:
`root.tf`

```
module "aws_bootstrap_vm" {

      count = var.CloudProvider == "aws" ? 1 : 0
      source = "./modules/aws/bootstrap_vm"
}

module "azure_bootstrap_vm" {

      count = var.CloudProvider == "azure" ? 1 : 0
      source = "./modules/azure/bootstrap_vm"
}
```
and this is how I call the root module:

`call.tf`

```
module "test" {
source = "C:\\root.tf"
CloudProvider = "aws"
aws_creds = {
access_key = "sadsad"
access_secret = "dasdasd"
region = "us-west-2"
}

azure_cred = {
    # AzureSubscriptionId     = "3c994c41-79sdadasdadas"
    # AzureClientId           = "ee5sadasda74-82fasdasd1579dbcfc"
    # AzureClientSecret       = "a3Esadsad_l.lEa4Hc5asdasd8nJtx"
    # AzureTenantId           = "b391asdasdsdasd"
}
}
```

Currently I need to provide the credentials for both aws & azure to get this to work or else I get this error when I only want to use the AWS module:

```
 Error: building AzureRM Client: 1 error occurred:
│       * A Subscription ID must be configured when authenticating as a Service Principal using a Client Secret.
│
```

My folder structure looks like this:

    ├───modules
    │   ├───aws
    │   │   ├───prepare_cloud
    │   │   │   ├───config
    │   │   │   └───templates
    │   │   ├───virtual_network
    │   └───azure
    │       ├───prepare_cloud
    │       │   └───config
    │       ├───virtual_network
    └───main

I would have expected that `skip_provider_registration ` flag  would skip the Azure registration.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by favoretti** [comment] 2021-12-24 07:53
Hi there and thank you for reporting this issue. 

From the problem statement I have assumed you are expecting the `azurerm` provider to not to be initialized at all if you set that flag.

There's a bit of confusion here. Azure itself has a concept of "Resource Providers", groups of resources that a subscription supports. Some of these resources must be registered with the subscription in order to be created.

The flag you're setting, `skip_provider_registration` refers to Azure Resource Providers and not to `azurerm` terraform provider. 

If you declare a terraform provider in terraform configuration is has to be configured as it will be initialized all the time.

**Comment by tombuildsstuff** [comment] 2022-01-04 08:38
hi @rahtr 

Thanks for opening this issue.

As @favoretti has mentioned above unfortunately this is working as intended - since the Client Secret is being specified, it must be a valid value since we use it for connecting to Azure.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Closed by tombuildsstuff** 2022-01-04 08:38 UTC
Labels: question, waiting-response
