### ISSUE TITLE
This is similar to issue mentioned in #15012.

### ISSUE THREAD

**Issue by kdmenghani13** [hashicorp/terraform-provider-azurerm#16950] opened 2022-05-25 12:44 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.7

### AzureRM Provider Version

2.99.0

### Affected Resource(s)/Data Source(s)

azurerm_data_factory_integration_runtime_self_hosted

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "datafactoryrg" {
  name     = "datafactoryrg"
  location = "West Europe"
}

resource "azurerm_data_factory" "datafactory" {
  name                = "devdatafactory"
  location            = azurerm_resource_group.datafactoryrg.location
  resource_group_name = azurerm_resource_group.datafactoryrg.name
  identity {
    type = "SystemAssigned"
  }
  vsts_configuration {
    account_name = "Datafactory"
    branch_name = "master"
    project_name = "datafactoryplatform"
    repository_name = "datafactory"
    root_folder = "/"
    tenant_id = "xxxx.xxxxx.xxxx.xxxx"
  }
}

resource "azurerm_data_factory_integration_runtime_azure" "runtimeintegration" {
  name            = "runtimeintegration"
  data_factory_id = azurerm_data_factory.datafactory.id
  location        = azurerm_resource_group.datafactoryrg.location
  resource_group_name = azurerm_resource_group.datafactoryrg.name
}
```

### Debug Output/Panic Output

```shell
**
```

### Expected Behaviour

The integration runtime is visible and usable in the datafactory

### Actual Behaviour

Integration runtime is created in Azure but not displayed in the datafactory, thus unusable.

### Steps to Reproduce

Have a data factory git backed : "df-linked"
Use the above code
Go to the linked df : Manage -> integration runtimes.
See your integration runtime "I-am-linked" not here
Try to create Author -> Dataset -> New -> Linked -> New -> Connect via integration runtime : The "I-am-linked" is not there

**Comment by tombuildsstuff** [comment] 2022-05-25 14:07
Duplicate of #15012

**Closed by tombuildsstuff** 2022-05-25 14:07 UTC
