### ISSUE TITLE
terraform-provider-azurerm_v3.113.0_x5.exe plugin crashed!

### ISSUE THREAD

**Issue by pedro-carvalho-BHS** [hashicorp/terraform-provider-azurerm#26886] opened 2024-07-31 09:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.0.1

### AzureRM Provider Version

3.113.0

### Affected Resource(s)/Data Source(s)

all

### Terraform Configuration Files

```hcl
resource "azurerm_network_security_rule" "vmsinbound" {
  name                        = "bhs_allow_inbound_ports"
  priority                    = 100
  direction                   = "Inbound"
  access                      = "Allow"
  protocol                    = "Tcp"
  source_port_range           = "*"
  destination_port_ranges     = var.bhs_ports_inbound
  source_address_prefix       = "VirtualNetwork"
  destination_address_prefix  = "*"
  resource_group_name         = azurerm_resource_group.DefaultRG.name
  network_security_group_name = azurerm_network_security_group.vms.name
  description                 = "NSG Inbound rules for Servers within the VNet"
```

### Debug Output/Panic Output

```shell
Stack trace from the terraform-provider-azurerm_v3.113.0_x5.exe plugin:

panic: interface conversion: interface {} is string, not *schema.Set

goroutine 276 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/network.resourceNetworkSecurityRuleUpdate(0xc002b15700, {0x78e1800?, 0xc00146bb00?})
        github.com/hashicorp/terraform-provider-azurerm/internal/services/network/network_security_rule_resource.go:323 +0x1b56
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x90f81e0?, {0x90f81e0?, 0xc00133aba0?}, 0xd?, {0x78e1800?, 0xc00146bb00?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:800 +0x163
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00163f500, {0x90f81e0, 0xc00133aba0}, 0xc0008c24e0, 0xc002b15580, {0x78e1800, 0xc00146bb00})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:919 +0x83a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000c83668, {0x90f81e0?, 0xc00133aab0?}, 0xc0018149b0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/grpc_provider.go:1060 +0xdbc
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc001ac7e00, {0x90f81e0?, 0xc00133a2a0?}, 0xc001974930)
        github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/tf5server/server.go:859 +0x56b
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x8576fa0?, 0xc001ac7e00}, {0x90f81e0, 0xc00133a2a0}, 0xc0019748c0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:467 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000018000, {0x9122ee0, 0xc001d24ea0}, 0xc001a88480, 0xc001d539b0, 0xe73a818, 0x0)
        google.golang.org/grpc@v1.58.3/server.go:1374 +0xde7
google.golang.org/grpc.(*Server).handleStream(0xc000018000, {0x9122ee0, 0xc001d24ea0}, 0xc001a88480, 0x0)
        google.golang.org/grpc@v1.58.3/server.go:1751 +0x9e7
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.58.3/server.go:986 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 16
        google.golang.org/grpc@v1.58.3/server.go:997 +0x145

Error: The terraform-provider-azurerm_v3.113.0_x5.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behaviour

Update the NSG rule

### Actual Behaviour

crashed

### Steps to Reproduce

terraform apply

**Comment by stephybun** [comment] 2024-07-31 11:32
Thanks for reporting this @pedro-carvalho-BHS. This is duplicate of #26881 which has been resolved with the fix going out in this week's release.

**Closed by stephybun** 2024-07-31 11:32 UTC
Labels: bug, crash, v/3.x
