### ISSUE TITLE
Azure storage container resources return container's URL for an ID

### ISSUE THREAD

**Issue by camilo-s** [hashicorp/terraform-provider-azurerm#20936] opened 2023-03-14 13:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.9

### AzureRM Provider Version

3.46.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_data_lake_gen2_filesystem, azurerm_storage_container

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "this" {

  name                            = "sttest23u4i2h"
  resource_group_name             = "rgtest"
  location                        = "westeurope"
  account_tier                    = "Standard"
  account_replication_type        = "LRS"
  allow_nested_items_to_be_public = false
  is_hns_enabled                  = true
}

data "azurerm_client_config" "client" {}

resource "azurerm_role_assignment" "account" {
  scope                = azurerm_storage_account.this.id
  role_definition_name = "Storage Blob Data Contributor"
  principal_id         = data.azurerm_client_config.client.object_id
  description          = "Read, write, and delete data inside the container."
}

resource "azurerm_storage_data_lake_gen2_filesystem" "this" {
  name               = "container1"
  storage_account_id = azurerm_storage_account.this.id
}

resource "azurerm_storage_container" "this" {
  name                  = "container2"
  storage_account_name  = azurerm_storage_account.this.name
  container_access_type = "private"
}

resource "azurerm_role_assignment" "container1" {
  scope                = azurerm_storage_data_lake_gen2_filesystem.this.id
  role_definition_name = "Storage Blob Data Contributor"
  principal_id         = data.azurerm_client_config.client.object_id
  description          = "Read, write, and delete data inside the container."
}

output "filesystem_id" {
  value = azurerm_storage_data_lake_gen2_filesystem.this.id
}

output "container_id" {
  value = azurerm_storage_container.this.id
}
```

### Debug Output/Panic Output

```shell
│ Error: expected scope to be one of [/providers/Microsoft.Subscription], got https://sttest23u4i2h.dfs.core.windows.net/container1
│ 
│   with azurerm_role_assignment.this,
│   on main.tf line 44, in resource "azurerm_role_assignment" "this":
│   44:   scope                            = azurerm_storage_data_lake_gen2_filesystem.this.id
│ 
╵
╷
│ Error: The number of path segments is not divisible by 2 in "container1"
│ 
│   with azurerm_role_assignment.this,
│   on main.tf line 44, in resource "azurerm_role_assignment" "this":
│   44:   scope                            = azurerm_storage_data_lake_gen2_filesystem.this.id
│ 
╵
╷
│ Error: parsing "https://sttest23u4i2h.dfs.core.windows.net/container1": parsing segment "providers": expected the segment "https:" to be "providers"
│ 
│   with azurerm_role_assignment.this,
│   on main.tf line 44, in resource "azurerm_role_assignment" "this":
│   44:   scope                            = azurerm_storage_data_lake_gen2_filesystem.this.id
│ 
╵
╷
│ Error: parsing "https://sttest23u4i2h.dfs.core.windows.net/container1": parsing segment "subscriptions": expected the segment "https:" to be "subscriptions"
│ 
│   with azurerm_role_assignment.this,
│   on main.tf line 44, in resource "azurerm_role_assignment" "this":
│   44:   scope                            = azurerm_storage_data_lake_gen2_filesystem.this.id
│ 
╵
╷
│ Error: parsing "https://sttest23u4i2h.dfs.core.windows.net/container1": parsing segment "subscriptions": expected the segment "https:" to be "subscriptions"
│ 
│   with azurerm_role_assignment.this,
│   on main.tf line 44, in resource "azurerm_role_assignment" "this":
│   44:   scope                            = azurerm_storage_data_lake_gen2_filesystem.this.id
│ 
╵
╷
│ Error: Can not parse "scope" as a resource id: The number of path segments is not divisible by 2 in "container1"
│ 
│   with azurerm_role_assignment.this,
│   on main.tf line 44, in resource "azurerm_role_assignment" "this":
│   44:   scope                            = azurerm_storage_data_lake_gen2_filesystem.this.id
```

### Expected Behaviour

The outputs `filesystem_id` and `container_id` return the actual Azure resource IDs, which can be used e.g. for role assignments.

The actual resource IDs can be cooked up like:
```
"${azurerm_storage_account.this.id}/blobServices/default/containers/${azurerm_storage_data_lake_gen2_filesystem.this.name}"
```
but this is off the point.

### Actual Behaviour

The outputs `filesystem_id` and `container_id` return instead the containers URLs, and can't therefore be uses whenever the corresponding resources should be referenced by id.

### Steps to Reproduce

1. `terraform init`
2. `terraform validate`
3. `terraform plan`
4. `terraform apply`

### Important Factoids

I haven't tried importing [`azurerm_storage_data_lake_gen2_filesystem`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_data_lake_gen2_filesystem#import) or [`azurerm_storage_container`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_container#import) as indicated in the documentation, but I'd assume it'd fail by the same reason as above.

**Comment by tombuildsstuff** [comment] 2023-03-14 14:55
hi @camilo-s 

Thanks for opening this issue.

This is by design, the Resource IDs that the Azure Provider uses are defined in the `import` section of the documentation for each resource, ([for example, for `azurerm_storage_data_lake_gen2_filesystem`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_data_lake_gen2_filesystem#import)) - which has been done in this case since these operations are performed against the Data Plane API rather than the Resource Manager API.

Whilst these resources are accessible as Storage Containers which are accessible via Resource Manager IDs, the Primary Resource IDs for these [are the ones used in the Data Plane API](https://learn.microsoft.com/en-us/rest/api/storageservices/datalakestoragegen2/filesystem/create) - and as such these are the Resource ID's we've opted to use here (and isn't something we generally change, since this can impact user-configs). Generally speaking the associated Resource Manager ID's are exposed via separate fields on these resources, for example `azurerm_storage_container` exposes a `resource_manager_id` field, but unfortunately this doesn't appear to be available for this resource.

Since this is behaving by design, I'm going to close this issue at the moment, however if you'd like to see the Resource Manager IDs exported for these resources via a `resource_manager_id` field, then please feel free to open a new feature request and we can take a look.

Thanks!

**Closed by tombuildsstuff** 2023-03-14 14:55 UTC
Labels: question

**Comment by camilo-s** [comment] 2023-03-14 16:48
Hi @tombuildsstuff, this clarifies many things, thanks for your great response!

I must confess i overlooked the `resource_manager_id` attribute of the `azurerm_storage_container` resource. 

For parity reasons, it would be great to expose that property correspondingly for the [azurerm_storage_data_lake_gen2_filesystem](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_data_lake_gen2_filesystem#import) resource, so I'll open a feature request as soon as I can.
