### ISSUE TITLE
Cannot create or modify azurerm_monitor_diagnostic_setting

### ISSUE THREAD

**Issue by hobbesuk** [hashicorp/terraform-provider-azurerm#15046] opened 2022-01-20 14:59 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_monitor_diagnostic_setting`

### Terraform Configuration Files

```hcl
resource "azurerm_monitor_diagnostic_setting" "apim" {
  count                      = length(local.locations)
  name                       = "xxxx"
  target_resource_id         = azurerm_api_management.apim[count.index].id
  log_analytics_workspace_id = var.LogAnalyticsWorkspace
  log_analytics_destination_type = "AzureDiagnostics"

  log {
    category = "GatewayLogs"
    enabled = false
    retention_policy {
      days = 30
      enabled = false
    }
  }

  metric {
    category = "AllMetrics"
    retention_policy {
      days = 30
      enabled = false
    }
  }
}
```

### Expected Behaviour

Resource created

### Actual Behaviour

`Error: creating Monitor Diagnostics Setting "xxxx" for Resource "/subscriptions/xxxx/resourceGroups/xxxx/providers/Microsoft.ApiManagement/service/xxxx-westeurope": insights.DiagnosticSettingsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Invalid API Verion used to modify log category group enabled setting: xxxx, please use version post: 2021-05-01-preview"`

### Steps to Reproduce

1. `terraform apply`

**Comment by hobbesuk** [comment] 2022-01-20 15:02
Maybe related to #14333

**Comment by tombuildsstuff** [comment] 2022-01-20 17:12
@hobbesuk just to confirm, is this an existing resource which has been imported into Terraform (which is using Log Category Groups) - or a new resource?

Thanks!

**Comment by hobbesuk** [comment] 2022-01-20 17:19
Both, I've tried updating an existing resource that was already in my state file and also trying to create a new one, both fail. I'm not trying to use log category groups.

**Comment by hobbesuk** [comment] 2022-02-04 15:28
If it helps this is what the plan is trying to do:
```

# azurerm_monitor_diagnostic_setting.apim[0] will be updated in-place
  ~ resource "azurerm_monitor_diagnostic_setting" "apim" {
        id                             = "/subscriptions/xxxx/resourceGroups/xxxx/providers/Microsoft.ApiManagement/service/canary-westeurope|Monitoring"
        log_analytics_destination_type = "AzureDiagnostics"
      ~ log_analytics_workspace_id     = "/subscriptions/xxxx/resourceGroups/xxxx/providers/Microsoft.OperationalInsights/workspaces/analytics-canary" -> "/subscriptions/xxxxx/resourcegroups/xxxx/providers/Microsoft.OperationalInsights/workspaces/analytics-canary"
        name                           = "Monitoring"
        target_resource_id             = "/subscriptions/xxxx/resourceGroups/xxxx/providers/Microsoft.ApiManagement/service/canary-westeurope"

      - log {
          - category = "GatewayLogs" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      + log {
          + category = "GatewayLogs"
          + enabled  = false

          + retention_policy {
              + days    = 30
              + enabled = false
            }
        }
      - log {
          - category = "WebSocketConnectionLogs" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }

```

**Comment by hobbesuk** [comment] 2022-02-04 16:36
I'm more convinced this is a problem because azure have enabled APIM diagnostic settings to use category groups, so we're a bit stuck with tf atm.
![image](https://user-images.githubusercontent.com/33954261/152567031-0fe745b1-e0e0-4388-b888-70088be9b07e.png)

**Comment by tombuildsstuff** [comment] 2022-03-21 10:09
Duplicate of #10388, please subscribe to that issue for updates.

**Closed by tombuildsstuff** 2022-03-21 10:09 UTC
Labels: question, service/monitor
