### ISSUE TITLE
Cannot disable all storage account bypass exceptions

### ISSUE THREAD

**Issue by miroslavkohutik** [hashicorp/terraform-provider-azurerm#22002] opened 2023-06-01 12:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.6

### AzureRM Provider Version

3.58.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "this" {
  name                     = var.name
  resource_group_name      = var.resource_group_name
  location                 = var.location
  account_kind             = var.kind
  account_tier             = var.tier
  account_replication_type = var.replication_type
  is_hns_enabled           = var.is_hns_enabled
  tags                     = local.data_tags
  allow_nested_items_to_be_public = false

  identity {
    type = "SystemAssigned"
  }

  network_rules {
    default_action             = var.network_rules_default_action
    bypass                     = var.network_rules_bypass
    ip_rules                   = []
    virtual_network_subnet_ids = []
  }
}
```

### Debug Output/Panic Output

```shell
not applicable
```

### Expected Behaviour

Storage account created with no exceptions 

### Actual Behaviour

Storage account created with an Exception for Azure services

**Comment by rcskosir** [comment] 2023-06-01 18:01
@miroslavkohutik Thanks for taking the time to submit this issue. Unfortunately, it looks like you did not provide the error/exception you are receiving. Please update this issue with the error/exception you are experiencing so that contributors can verify they are reproducing the same issue correctly, or that other users can identify if they are seeing the same error.

**Comment by magodo** [comment] 2023-06-02 06:58
@miroslavkohutik Seems you didn't specify any of `ip_rules` or `virtual_network_subnet_ids`. There is a [NOTE](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account#:~:text=as%20defined%20below.-,Note%3A,-If%20specifying%20network_rules) in the document, saying:

> If specifying network_rules, one of either `ip_rules` or `virtual_network_subnet_ids` must be specified and `default_action` must be set to Deny.

Since this is a question rather than an issue in the Azure Provider I'm going to close this issue for the moment, but should you have further usage questions [I'd direct you towards the Community Discuss forum](https://discuss.hashicorp.com).

**Closed by magodo** 2023-06-02 06:58 UTC
Labels: service/storage

**Comment by miroslavkohutik** [comment] 2023-06-05 09:40
My actual mistake was using `[]` as the value for `var.network_rules_bypass` when the correct value should be `["None"]`
