### ISSUE TITLE
Support for AKS CSI Storage Driver

### ISSUE THREAD

**Issue by philwinder** [hashicorp/terraform-provider-azurerm#12826] opened 2021-08-03 12:54 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add the feature flags necessary to enable CSI driver support: https://docs.microsoft.com/en-us/azure/aks/csi-storage-drivers

### New or Affected Resource(s)

* azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
{
...
  azure_csi_driver {
    enabled = true
  }
}
```

### References

* https://docs.microsoft.com/en-us/azure/aks/csi-storage-drivers

**Comment by crstin** [comment] 2021-08-06 08:21
This is important because it seems you can't enable this on an existing cluster with `az aks update`. This renders terraform approaches useless when you want to have things like volume snapshots. Correct me if wrong, please.

**Comment by poddm** [comment] 2021-08-23 23:19
> This is important because it seems you can't enable this on an existing cluster with `az aks update`. This renders terraform approaches useless when you want to have things like volume snapshots. Correct me if wrong, please.

I see this covered in the docs here: https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver#upgrade-an-existing-aks-cluster-with-secrets-store-csi-driver-support

> To upgrade an existing AKS cluster with Secrets Store CSI Driver capability, use the az aks enable-addons command with the addon azure-keyvault-secrets-provider:
> 
> az aks enable-addons --addons azure-keyvault-secrets-provider --name myAKSCluster --resource-group myResourceGroup
> 
> As stated above, the addon creates a user-assigned managed identity that can be used to authenticate to Azure Key Vault.

**Comment by primeroz** [comment] 2021-08-24 07:38
I think the request is more about enabling CSI in general on the cluster, and as specified here https://docs.microsoft.com/en-us/azure/aks/csi-storage-drivers#limitations it can't be done other than at cluster creation time. 

I _think_ that the addon you are referencing will require the CSI to be enabled in the first place , then the addon can be installed.

**Comment by favoretti** [comment] 2021-09-21 07:41
Hi there and thank you for reporting this. This appears to be a duplicate of an earlier reported issue #12783, so I'm going to close this one to keep the discussion concise.

**Comment by primeroz** [comment] 2021-09-21 08:11
@favoretti i might be wrong but i don't think they are duplicate. 

This request is about enabling the CSI addon which is a pre-requisite of enabling the secrets one in #12783.

**Comment by favoretti** [comment] 2021-09-21 08:49
@primeroz from what I understand those will be addon parameters, so will need to be tackled/implemented in one go, WDYT?

**Comment by favoretti** [comment] 2021-09-21 12:59
@primeroz re-opened, let's see when someone gets to it. That said, since it's a preview feature, as you can see it changes quite often still, so I'm not sure we can expect sensible API support for it soon. But I'm interested in this one as well, so I'll try to dive into it.

**Comment by primeroz** [comment] 2021-09-21 13:22
:+1: i think csi is finally GA on azure since it will be default soon

**Comment by avinashpancham** [comment] 2021-09-28 20:33
@favoretti I can understand that it might not be worthwhile to add this preview feature to `azurerm` as it might change in the future. 

For users that still want to activate this preview feature on their AKS cluster a solution for now would be installing it via the [Secrets Store CSI Driver Helm chart](https://azure.github.io/secrets-store-csi-driver-provider-azure/getting-started/installation/). 

```
resource "helm_release" "csi-secrets-store-provider-azure" {
  name       = "csi-secrets-store-provider-azure"
  repository = "https://raw.githubusercontent.com/Azure/secrets-store-csi-driver-provider-azure/master/charts"
  chart      = "csi-secrets-store-provider-azure"
  version    = "0.2.1"  # latest version at the time of writing
}
```
A Helm chart is available for other preview features as well, such as Azure Pod Identity. See https://github.com/hashicorp/terraform-provider-azurerm/issues/9885#issuecomment-929590126 for how I got that working.

**Comment by thy143** [comment] 2021-10-01 08:56
I took a quick look at implementing the --addons azure-keyvault-secrets-provider function, however, as it’s preview unless your subscription has it enabled it cause terraform to fail as the api reports you need to enable it.

I new at TF code, so not sure how I make the configuration option only present in the api request if you have declared it in your ti code.

**Comment by DrewRomanyk** [comment] 2021-10-02 15:48
@favoretti As far as I can tell this feature has been GA since July 25th according to this [issue](https://github.com/Azure/AKS/issues/1757), but it [requires](https://docs.microsoft.com/en-us/azure/aks/csi-storage-drivers) setting this property `EnableAzureDiskFileCSIDriver` to `true` on the request header when creating the cluster, which can likely be done generically for other custom header values with this [terraform provider azurerm issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/6793). So if anything we can close this as a duplicate to that issue.

I posted in that provider issue what I think might be a solution to do it, but I'm not well versed in terraform provider source code. Happy to try to fix this if given the proper guidance, but also happy to let someone more experienced fix this faster.

**Comment by aristosvo** [comment] 2021-11-12 10:37
Starting in Kubernetes version 1.21, Kubernetes will use CSI drivers only and by default. These drivers are the future of storage support in Kubernetes.

With 1.21 being GA for a while, this header is only useful for current supported version 1.19 and 1.20. These [being out of support Nov 2021 (1.19) and Feb 2022 (1.20)](https://docs.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli#aks-kubernetes-release-calendar), I'm going to close this issue.

Custom header support can still be tracked in https://github.com/hashicorp/terraform-provider-azurerm/issues/6793, which (if properly implemented) would also support this use-case.

**Closed by aristosvo** 2021-11-12 10:37 UTC
Labels: enhancement, service/kubernetes-cluster
