### ISSUE TITLE
zone_redundant property is missing in azurerm_service_plan

### ISSUE THREAD

**Issue by Divya1388** [hashicorp/terraform-provider-azurerm#16202] opened 2022-04-01 01:37 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.7

### AzureRM Provider Version

3.0.2

### Affected Resource(s)/Data Source(s)

azurerm_service_plan

### Terraform Configuration Files

```hcl
resource "azurerm_service_plan" "app_plan" {
  count                        = var.create_app_service_plan ? 1 : 0
  name                         = var.app_plan_name
  resource_group_name          = var.resource_group_name
  location                     = var.location
  os_type                      = var.os_type
  maximum_elastic_worker_count = var.maximum_elastic_worker_count
  sku_name                     = var.sku_name
  app_service_environment_id   = var.app_service_environemet_id
  worker_count                 = var.worker_count
  per_site_scaling_enabled     = var.per_site_scaling_enabled
  tags                         = local.all_tags
  lifecycle {
    ignore_changes = [
      # The no of workers might change out of terraform. So ignoring that change.
      maximum_elastic_worker_count,
      worker_count,
      tags
    ]
  }
}
```

### Debug Output/Panic Output

```shell
This creates the app plan but it does not enable zone redundancy on the plan.

And currently we can enable zone redundancy on when creating a service plan.
```

### Expected Behaviour

have an argument to specify zone redundancy

### Actual Behaviour

zone redundancy cannot be enabled

### Important Factoids

currently we can enable zone redundancy on when creating a service plan and there is no way to specify this

**Comment by sebader** [comment] 2022-04-01 09:16
should be fixed by https://github.com/hashicorp/terraform-provider-azurerm/pull/16156

**Comment by Divya1388** [comment] 2022-04-01 12:46
thanks @sebader do we have a timeframe of when this will be fixed?

**Comment by sebader** [comment] 2022-04-01 13:04
I'm not involved in that PR. But given that it was already approved, I'd expect it will be merged soon

**Comment by jackofallops** [comment] 2022-04-04 05:02
Closing as duplicate of #16095, please follow that issue for updates.

Thanks!

**Closed by jackofallops** 2022-04-04 05:02 UTC
