### ISSUE TITLE
provider panics

### ISSUE THREAD

**Issue by davidkarlsen** [hashicorp/terraform-provider-azurerm#15078] opened 2022-01-23 17:44 UTC
### Panic Output

```
Error: Plugin did not respond
│ 
│   with module.bastion.azurerm_bastion_host.bastion_host,
│   on modules/bastion/bastion.tf line 16, in resource "azurerm_bastion_host" "bastion_host":
│   16: resource "azurerm_bastion_host" "bastion_host" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.
╵
Releasing state lock. This may take a few moments...

Stack trace from the terraform-provider-azurerm_v2.93.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x45a1c7d]

goroutine 2673 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/network.resourceBastionHostRead(0xc00122df80, {0x559a880, 0xc000e67180})
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/services/network/bastion_host_resource.go:255 +0x5dd
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x5e760e3, {0x657f318, 0xc0016ffa80}, 0x24, {0x559a880, 0xc000e67180})
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:346 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000f5a8c0, {0x657f318, 0xc0016ffa80}, 0xc000de8750, {0x559a880, 0xc000e67180})
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:635 +0x35b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc000a82480, {0x657f318, 0xc0016ffa80}, 0xc0016ffb00)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:576 +0x534
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc000229500, {0x657f3c0, 0xc001e3e810}, 0xc003261200)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server/server.go:553 +0x3b0
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x5adac20, 0xc000229500}, {0x657f3c0, 0xc001e3e810}, 0xc0032611a0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000218fc0, {0x65cdac8, 0xc000313800}, 0xc00151dd40, 0xc000df21b0, 0xab3d910, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0xc6f
google.golang.org/grpc.(*Server).handleStream(0xc000218fc0, {0x65cdac8, 0xc000313800}, 0xc00151dd40, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1617 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:940 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:938 +0x294

Error: The terraform-provider-azurerm_v2.93.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

Error: Terraform exited with code 1.
Error: Process completed with exit code 1.
```

terraform -v
Terraform v1.1.4
on darwin_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.7.0
+ provider registry.terraform.io/hashicorp/azurerm v2.93.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/time v0.7.2

### Expected Behaviour

Should not crash

### Actual Behaviour

Crashes

**Comment by aristosvo** [comment] 2022-01-23 18:16
Hi @davidkarlsen! Thanks for raising this. After a quick lookup I found this to be a duplicate of #15058. As such I'll close this issue.

#15058 has already a related PR which probably fixes the problem.

**Closed** 2022-01-23 18:17 UTC
Labels: bug, crash
