### ISSUE TITLE
Support for enabling/disabling network public access for postgres flexibleServer

### ISSUE THREAD

**Issue by akata72** [hashicorp/terraform-provider-azurerm#25768] opened 2024-04-26 08:24 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Expose the *publicNetworkAccess* attribute to terraform making it possible to enable/disable network public access. 

### New or Affected Resource(s)/Data Source(s)

azurerm_postgresql_flexible_server

**Comment by rodmhgl** [comment] 2024-05-10 15:19
Is this a duplicate of #14989?

**Comment by akata72** [comment] 2024-05-11 06:12
Closing this as a duplicate.

**Closed** 2024-05-11 06:12 UTC
Labels: enhancement, service/postgresql
