### ISSUE TITLE
SignalR features block missing EnableLiveTrace

### ISSUE THREAD

**Issue by LukasGibb** [hashicorp/terraform-provider-azurerm#12000] opened 2021-05-28 04:10 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.15.4
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.61.0

### Affected Resource(s)

* `azurerm_signalr_service`

### Terraform Configuration Files

```hcl
resource "azurerm_signalr_service" "sigr" {
  name                = "tfex-signalr"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name

  sku {
    name     = "Free_F1"
    capacity = 1
  }

  cors {
    allowed_origins = ["http://www.example.com"]
  }

  features {
    flag  = "ServiceMode"
    value = "Default"
  }
  features {
    flag  = "EnableConnectivityLogs"
    value = "False"
  }
  features {
    flag = "EnableMessagingLogs"
    value = "False"
  }
  features {
    flag  = "EnableLiveTrace"
    value = "False"
  }
}
```

### Expected Behaviour

Running `terraform plan` should not report any changes directly after a `terraform apply`

### Actual Behaviour

Without the EnableLiveTrace features block:

Running `terraform plan` reports changes directly after a `terraform apply`... ie:

```
      - features {
          - flag  = "EnableLiveTrace" -> null
          - value = "False" -> null
        }
```

With the EnableLiveTrace features block present an error is received:

```
│ Error: expected features.1.flag to be one of [EnableMessagingLogs EnableConnectivityLogs ServiceMode], got EnableLiveTrace
│
│   with azurerm_signalr_service.sigr,
│   on main.tf line 15, in resource "azurerm_signalr_service" "sigr":
│   15: resource "azurerm_signalr_service" "sigr" {
```

### Steps to Reproduce

1. `terraform apply`
2. `terraform plan`

### References

Similar to this issue:
https://github.com/terraform-providers/terraform-provider-azurerm/issues/7025

**Comment by narendarchandha** [comment] 2021-06-25 10:14
I am also facing same error.  How to ignore a specific feature in lifecyle?  I want to ignore changes for only to EnableLiveTrace feature.
We are using azurerm provider 2.56.0, cannot upgrade until next 4 to 5 months, due to other reasons.

**Comment by LukasGibb** [comment] 2021-06-29 00:44
> 
> 
> I am also facing same error. How to ignore a specific feature in lifecyle? I want to ignore changes for only to EnableLiveTrace feature.
> We are using azurerm provider 2.56.0, cannot upgrade until next 4 to 5 months, due to other reasons.

The way I currently use terraform, it is fine for this go cause a change each time we do an apply. ie.. it just sets it to null each time it runs. I have a note in our config as a reminder. Not ideal but we don't make changes to this configuration often.

I think the best you can do is ignore_changes for _all_ features but unfortunately this will mean that any changes to other features will not be applied:

```
  lifecycle {
    ignore_changes = [
      # Ignore changes to the features, because EnableLiveTrace is not yet supported in the provider.
      features,
    ]
  }
```

I did try googling a bit to see if there was a way to ignore_changes for only the specific feature object that has flag = "EnableLiveTrace" but I don't think there is a way to do this currently in terraform. If there is then I wasn't able to figure it out. The closest thing I could dream up was something like this (but it throws an error):

```
  lifecycle {
    ignore_changes = [
      # Ignore changes to the EnableLiveTrace feature, because it is not yet supported in the provider.
      [for feature in features : feature if feature.flag == "EnableLiveTrace"],
    ]
  }
```

```
terraform plan
╷
│ Error: Invalid expression
│
│   on main.tf line 32, in resource "azurerm_signalr_service" "sigr":
│   32:       [for feature in features : feature if feature.flag == "EnableLiveTrace"],
│
│ A single static variable reference is required: only attribute access and indexing with constant keys. No calculations, function calls, template expressions, etc are allowed here.
```

Let me know if you work out a way to do it.

**Comment by DeltaOffset** [comment] 2021-09-23 15:51
Hello all, 

We are currently having the same issue with our signalr resource.

Will this have any update soon? this issue was opened in may, 2021

**Comment by drdamour** [comment] 2021-09-24 21:58
dupe of #11353

**Comment by tombuildsstuff** [comment] 2021-09-27 08:57
Duplicate of #11353 - thanks @drdamour

**Closed by tombuildsstuff** 2021-09-27 08:57 UTC
Labels: enhancement, service/signalr
