### ISSUE TITLE
azurerm_servicebus_namespace_authorization_rule Terraform Import Documentation Has Incorrect Capitalization

### ISSUE THREAD

**Issue by tylernuss-aya** [hashicorp/terraform-provider-azurerm#21826] opened 2023-05-17 18:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/servicebus_namespace_authorization_rule

The "a" in the "/authorizationRules/" section of the Terraform Import documentation needs to be capitalized. When this is lowercase, you get an error saying that it is expecting "/AuthorizationRules/".

### Terraform Version

3.0.0

### AzureRM Provider Version

3.4.0

### Affected Resource(s)/Data Source(s)

azurerm_servicebus_namespace_authorization_rule

### Terraform Configuration Files

```hcl
NA
```

### Debug Output/Panic Output

```shell
Error: parsing Resource ID <ID> : ID was missing the `AuthorizationRules` element
```

**Comment by tombuildsstuff** [comment] 2023-05-17 19:47
hi @tylernuss-aya 

Thanks for opening this issue.

You're referencing the latest version of the AzureRM provider documentation above, but using an older version of the Provider (3.4.0), so the import reference maybe different for this version of the Provider - I'd recommend checking the documentation for that resource when using an older version of the Provider, since it's possible for these to change over time, such as in this case to fix an older incorrect casing (using TitleCase when this should be in camelCase, per the ARM Specification). For example when looking at the import documentation for 3.4.0, [the `import` example references the TitleCased segment as mentioned in the error message](https://registry.terraform.io/providers/hashicorp/azurerm/3.4.0/docs/resources/servicebus_namespace_authorization_rule#import) - so this matches what we're expecting here.

It's worth noting that when a Resource ID does get updated to fix these bugs, we do this via a State Migration, meaning that we'll automatically update the Resource within Terraform's state to account for this - so whilst the Resource ID being used should be stable, we're working through to remove any instances where the incorrect casing is being specified (for example where TitleCase is being used instead of camelCase for segment values).

Since the Resource ID for this Resource has been updated to account for this casing error, and the documentation is correct both for the latest version of the Provider (which uses camelCase for this segment) - and the older version of the provider, whilst I'd like to thank you for opening this issue I'm going to close this as working as intended, but I'd recommend updating to the latest version of the Provider if you can, since 3.56.0 is the latest version of the Provider at the time of writing.

Thanks!

**Closed by tombuildsstuff** 2023-05-17 19:47 UTC
Labels: question, documentation, service/service-bus
