### ISSUE TITLE
azurerm_servicebus_namespace_authorization_rule errors

### ISSUE THREAD

**Issue by WotAGuy** [hashicorp/terraform-provider-azurerm#17791] opened 2022-07-28 14:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.6

### AzureRM Provider Version

3.3.2

### Affected Resource(s)/Data Source(s)

azurerm_servicebus_namespace_authorization_rule

### Terraform Configuration Files

```hcl
When I upgraded the azure provider from 3.12.0 (where a terraform plan ran clean) to 3.15.1 where terraform plan errors with the details given below.
```

### Debug Output/Panic Output

```shell
azurerm_servicebus_queue_authorization_rule.Service-Bus-001-Queue-authorisation-Rule: Refreshing state... [id=/subscriptions/57bee057-ba0d-46f8-bc6d-c4358a6f7ffb/resourceGroups/EPM-Services-ImportProfile-DEV-1.00-001-rg/providers/Microsoft.ServiceBus/namespaces/EPM-Services-DEV-1-00-001-sbns-001/queues/EPM-Services-DEV-1-00-001-sbq-001-bettaprofileload/authorizationRules/EPM-Services-DEV-1-00-001-sbq-001-rule-001]
╷
│ Error: parsing "/subscriptions/57bee057-ba0d-46f8-bc6d-c4358a6f7ffb/resourceGroups/EPM-Services-ImportProfile-DEV-1.00-001-rg/providers/Microsoft.ServiceBus/namespaces/EPM-Services-DEV-1-00-001-sbns-001/AuthorizationRules/EPM-Services-DEV-1-00-001-sbns-001-ar-001": parsing segment "staticAuthorizationRules": expected the segment "AuthorizationRules" to be "authorizationRules"
│
│   with azurerm_servicebus_namespace_authorization_rule.Service-Bus-001-NameSpace-Authorisation-Rule,
│   on Service-Bus.tf line 22, in resource "azurerm_servicebus_namespace_authorization_rule" "Service-Bus-001-NameSpace-Authorisation-Rule":
│   22: resource "azurerm_servicebus_namespace_authorization_rule" "Service-Bus-001-NameSpace-Authorisation-Rule" {
│
```

### Expected Behaviour

terraform plan should give:

No changes. Your infrastructure matches the configuration.**

### Actual Behaviour

terraform plan errors with:

 Error: parsing "/subscriptions/57bee057-ba0d-46f8-bc6d-c4358a6f7ffb/resourceGroups/EPM-Services-ImportProfile-DEV-1.00-001-rg/providers/Microsoft.ServiceBus/namespaces/EPM-Services-DEV-1-00-001-sbns-001/AuthorizationRules/EPM-Services-DEV-1-00-001-sbns-001-ar-001": parsing segment "staticAuthorizationRules": expected the segment "AuthorizationRules" to be "authorizationRules"
│
│   with azurerm_servicebus_namespace_authorization_rule.Service-Bus-001-NameSpace-Authorisation-Rule,
│   on Service-Bus.tf line 22, in resource "azurerm_servicebus_namespace_authorization_rule" "Service-Bus-001-NameSpace-Authorisation-Rule":
│   22: resource "azurerm_servicebus_namespace_authorization_rule" "Service-Bus-001-NameSpace-Authorisation-Rule" {

### Steps to Reproduce

Once terraform has been applied and it goes clean then a run of terraform plan should also go clean.

resource "azurerm_servicebus_namespace" "Service-Bus-001-NameSpace" {
    name                = replace(join("-", [azurerm_resource_group.serviceResourceGroup.tags.uNamePrefix, "sbns", "001"]), ".", "-")
    location            = azurerm_resource_group.ImportProfileResourceGroup.location
    resource_group_name = azurerm_resource_group.ImportProfileResourceGroup.name
    sku                 = "Basic"
    capacity            = 0

  tags = {
    BillingInfo         = join(";", [var.uDirectorate, var.uCostCentre, var.uIRNumber])
    Data_Classification = var.uDataClassification
    ComponentVersion    = "1.00"
    BusinessUnit        = var.uDirectorate
    LifeCycleStatus     = var.uLifeCycleStatus
    ServiceHours        = var.uServiceHours
    SupportInfo         = var.uSupportInfo
    AppCriticality      = var.uAppCriticallity
  }
}

resource "azurerm_servicebus_namespace_authorization_rule" "Service-Bus-001-NameSpace-Authorisation-Rule" {
  name         = replace(join("-", [azurerm_resource_group.serviceResourceGroup.tags.uNamePrefix, "sbns", "001", "ar", "001"]), ".", "-")
  namespace_id = azurerm_servicebus_namespace.Service-Bus-001-NameSpace.id

  listen = true
  send   = true
  manage = false
}

**Comment by Marcus-James-Adams** [comment] 2022-07-29 09:39
Duplicate of #17759

**Comment by xiaxyi** [comment] 2022-08-01 07:34
Thanks @Marcus-James-Adams , the fix is submitted in pr: https://github.com/hashicorp/terraform-provider-azurerm/pull/17824.

Also, since this is duplicate to https://github.com/hashicorp/terraform-provider-azurerm/issues/17720, do you mind closing this one and track the issue there?

**Comment by mybayern1974** [comment] 2022-08-12 06:59
@WotAGuy , thank you for opening this issue. Per xiaxyi's suggest, I'm closing this issue and please subscribe to #17720 that indicates the similar symptom, or feel free to suggest if you prefer to keep this issue open if this issue contains extra info that's not in #17720

**Closed by mybayern1974** 2022-08-12 06:59 UTC
