### ISSUE TITLE
Error parsing segment "staticAuthorizationRules": expected the segment "AuthorizationRules" to be "authorizationRules"

### ISSUE THREAD

**Issue by vi-malii** [hashicorp/terraform-provider-azurerm#17759] opened 2022-07-26 07:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.0.0

### AzureRM Provider Version

3.15.1

### Affected Resource(s)/Data Source(s)

azurerm_servicebus_namespace_authorization_rule

### Terraform Configuration Files

```hcl
resource "azurerm_servicebus_namespace_authorization_rule" "servicebus_namespace_authorization_send_rule" {
  name                = "{env}-{client}-send-rule"
  namespace_id        = azurerm_servicebus_namespace.servicebus_namespace.id

  listen = false
  send   = true
  manage = false
}

resource "azurerm_servicebus_namespace_authorization_rule" "servicebus_namespace_authorization_manage_rule" {
  name                = "{env}-{client}-manage-rule"
  namespace_id        = azurerm_servicebus_namespace.servicebus_namespace.id

  listen = true
  send   = true
  manage = true
}
```

### Debug Output/Panic Output

```shell
Error: parsing "/subscriptions/.../providers/Microsoft.ServiceBus/namespaces/...-servicebus-namespace/AuthorizationRules/...-send-rule": parsing segment "staticAuthorizationRules": expected the segment "AuthorizationRules" to be "authorizationRules"
10:09:05  │ 
with azurerm_servicebus_namespace_authorization_rule.servicebus_namespace_authorization_send_rule,
on servicebus.tf line 23, in resource "azurerm_servicebus_namespace_authorization_rule" "servicebus_namespace_authorization_send_rule":
23: resource "azurerm_servicebus_namespace_authorization_rule" "servicebus_namespace_authorization_send_rule" {
10:09:05  │ 
10:09:05  ╵
10:09:05  ╷
10:09:05  │ 
Error: parsing "/subscriptions/.../providers/Microsoft.ServiceBus/namespaces/...-servicebus-namespace/AuthorizationRules/...-manage-rule": parsing segment "staticAuthorizationRules": expected the segment "AuthorizationRules" to be "authorizationRules"
with azurerm_servicebus_namespace_authorization_rule.servicebus_namespace_authorization_manage_rule,
on servicebus.tf line 32, in resource "azurerm_servicebus_namespace_authorization_rule" "servicebus_namespace_authorization_manage_rule":
32: resource "azurerm_servicebus_namespace_authorization_rule" "servicebus_namespace_authorization_manage_rule" {
```

### Expected Behaviour

I try to perform terraform plan to see how infrastructure has changed.

**Comment by vi-malii** [comment] 2022-07-26 08:11
I've found workaround simply changing this parameters in tfstate, but I'd like to find the way without changing tfstate by hand

**Comment by bigglesuk69** [comment] 2022-07-27 09:08
There was a similar issue with another resource a while back (#15549) and it was caused when the SDK was changed. I know the SDK on the Servicebus resources was changed recently so could be related.

**Comment by bigglesuk69** [comment] 2022-07-27 09:10
Duplicate of #17720

**Comment by xiaxyi** [comment] 2022-08-01 06:54
Thanks Guys for raising this issue, I'm working on the state upgrade, will update later.

**Comment by xiaxyi** [comment] 2022-08-01 07:35
Hi Guys, the fix is submitted in the mentioned pr, feel free to check it. Meanwhile, since this is duplicate to #17720 , do you mind closing this thread and track the status there? Thanks

**Comment by vi-malii** [comment] 2022-08-01 09:13
Duplicate of https://github.com/hashicorp/terraform-provider-azurerm/issues/17720

**Closed** 2022-08-01 09:12 UTC
