### ISSUE TITLE
logic apps managed identity id doesn't appear when terraform output.

### ISSUE THREAD

**Issue by aman-w-kumar** [hashicorp/terraform-provider-azurerm#14774] opened 2022-01-03 16:54 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

azureuser@Azure:~/la$ terraform -v
Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.90.0

### Affected Resource(s)

* `azurerm_logic_app_workflow`

### Terraform Configuration Files

data "azurerm_logic_app_workflow" "example" {
  name                = "my_logic_app"
  resource_group_name = "my_logic_app_rg"
}

output "la_app_outputs" {
value = data.azurerm_logic_app_workflow.example.identity[*]
}

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output
╷
│ Error: Unsupported attribute
│
│   on main.tf line 11, in output "la_app_outputs":
│   11: value = data.azurerm_logic_app_workflow.example.identity[*]
│
│ This object has no argument, nested block, or exported attribute named "identity".

### Expected Behaviour

As per documentation, it is mentioned that identity can be exported. link below. more information in identity section.

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/logic_app_workflow

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment] 2022-01-04 10:54
hi @aman-w-kumar 

Thanks for opening this issue.

In the example code above your making use of the Data Source but are referencing the documentation for the Resource - which has different properties. The [documentation for the Data Source can be found here](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/logic_app_workflow), which at this time doesn't include the `identity` block, as such this is currently working as intended (since we don't support this property).

Since this issue is related to the documentation I'm going to close this issue for the moment, but if you'd like to see the `identity` block supported on the Logic Apps Workflow Data Source then please feel free to open a Feature Request and someone can take a look.

Thanks!

**Closed by tombuildsstuff** 2022-01-04 10:54 UTC
Labels: question, service/logic
