### ISSUE TITLE
GRPCProvider.GetProviderSchema: Error while dialing tcp 127.0.0.1:10000 

### ISSUE THREAD

**Issue by ackris** [hashicorp/terraform-provider-azurerm#16821] opened 2022-05-17 09:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

While applying terraform plan, we are getting error logs as highlighted in panic output box. It has been working very well on multiple terraform plan, apply and destroy. 

And, we are unable to make a meaningful summary of this error. We have even searched in stackoverflow and github issues forums. Yet, none matched what we are facing. They even didn't closely match.  

### Terraform Version

1.1.8

### AzureRM Provider Version

3.3.0

### Affected Resource(s)/Data Source(s)

azurerm

### Terraform Configuration Files

```hcl
terraform {
  required providers {
   azurerm = {
    source = "hashicorp/azurerm"
    version = "=3.3.0"
  }
 }
 backend "azurerm" {
  resource_group_name = "abcd"
  storage_account_name = "tfstate30303"
  container_name = "tfstate"
  key = "terraform.tfstate"
  access_key = "abcdsample....."
 }
}

provider "azurerm" {
 features {}
 skip_provider_registration = true
}
```

### Debug Output/Panic Output

```shell
Getting the below error on `terraform plan`


Error: Failed to load plugin schemas

Error while loading loading schemas for plugin components: Failed to obtain provider schema: Could not load the schema for provider registry.terraform.io/hashicorp/azurerm: Plugin did not respond. The plugin encountered an error, and failed to respond to the plugin. (*GRPCProvider).getProviderSchema call. The plugin logs might contain more details.
```

**GRPC Error details from TF_LOG=TRACE**

`[ERROR] plugin (*GRPCProvider).getProviderSchema: error="rpc error: code=Unavailable desc = connection error: desc = "transport:error while dialing: dial tcp 127.0.0.1:10000: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. [WARN]: plugin failed to exit gracefully`
```


### Expected Behaviour

`terraform plan` must have shown an output of deployment plan. 

### Actual Behaviour

`terraform plan` failing with above mentioned error. It is not showing deployment plan output. 

### Steps to Reproduce

`terraform plan`

### Important Factoids

Azure in Central India. Was working fine till yesterday. And, we are working in an airgapped environment. Hence, plugins are downloaded manually and placed in plugin-dir of code folder. 

### References

_No response_

**Comment by tombuildsstuff** [comment] 2022-05-17 10:19
hi @ackris 

Thanks for opening this issue.

Unfortunately this appears to be an issue specific to your environment, likely an anti-virus or proxy interfering with Terraform Core being able to communicate with the AzureRM Provider Binary.

Since this is Environment specific unfortunately we're unable to assist further here, but I'd recommend checking your systems logs to determine if any new policies have been applied which would cause this - however as this issue is specific to your environment and not a bug in the Provider I'm going to close this issue for the moment.

Thanks!

**Closed by tombuildsstuff** 2022-05-17 10:19 UTC
Labels: question

**Comment by ackris** [comment] 2022-05-17 11:39
@tombuildsstuff 

How are you so sure that this is an environmental issue, but not terraform.

PS: It is a windows instance where terraform is installed and yes, trend micro is installed in it.

**Comment by ackris** [comment] 2022-05-19 06:03
A simple reboot of machine did the trick. Now terraform commands on my machine are working fine.
