### ISSUE TITLE
Support for creating datastore in the Azure ML provider

### ISSUE THREAD

**Issue by vermegi** [hashicorp/terraform-provider-azurerm#16807] opened 2022-05-16 12:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently the creation of datastores in an Azure ML workspace is not supported by the azurerm provider. This is needed in case you want to fully template a Azure ML setup. 
See https://docs.microsoft.com/en-us/azure/machine-learning/concept-azure-machine-learning-architecture for more info on datastores and linked services. 

### New or Affected Resource(s)/Data Source(s)

azurerm_machine_learning

### Potential Terraform Configuration

```hcl
Similar config in Bicep:
https://docs.microsoft.com/en-us/azure/templates/microsoft.machinelearningservices/workspaces/datastores?tabs=bicep
```

**Comment by stephybun** [comment] 2022-05-23 11:00
Duplicate of #14701

**Closed by stephybun** 2022-05-23 11:00 UTC
Labels: duplicate, service/machine-learning
