### ISSUE TITLE
Terraform 2.93.x breaks with "the number of path segments is not divisible by 2"

### ISSUE THREAD

**Issue by irigon** [hashicorp/terraform-provider-azurerm#15106] opened 2022-01-25 11:51 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v1.1.4
on linux_amd64
+ provider registry.terraform.io/aliyun/alicloud v1.153.0
+ provider registry.terraform.io/hashicorp/aws v3.73.0
+ provider registry.terraform.io/hashicorp/azurerm v2.93.1
+ provider registry.terraform.io/hashicorp/github v4.4.0
+ provider registry.terraform.io/hashicorp/google v4.8.0
+ provider registry.terraform.io/hashicorp/google-beta v4.8.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0
+ provider registry.terraform.io/kirillmeleshko/restapi v1.16.0

### Affected Resource(s)

* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

As we run this code in a private repository, I can't provide a Github gist.

### Expected Behaviour

Terraform plan should run without errors (as it has ran over the last weeks) in the pipeline.

### Actual Behaviour

│```
 Error: the number of path segments is not divisible by 2 in "subscriptions/4007afb9-3bbc-4b9a-86ed-185b81caa50e/resourceGroups/rg-s4-azr0201-cr/providers/Microsoft.Compute/images"
│
│   with module.cis-azure.module.native-docker[0].azurerm_linux_virtual_machine.monitoring,
│   on modules/cis_azure/native-docker/compute_monitoring.tf line 318, in resource "azurerm_linux_virtual_machine" "monitoring":
│  318:   source_image_id                 = var.os_image
│
```
### Steps to Reproduce

<!--- Please list the steps required to reproduce the issue. --->

1. `terraform plan`

### Important Factoids

The same code works again, as soon as I set the version back to 2.92.0

### References

<!---
Information about referencing Github Issues: https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests

Are there any other GitHub issues (open or closed) or pull requests that should be linked here? Such as vendor documentation?
--->

* #0000

**Comment by tombuildsstuff** [comment] 2022-01-25 11:58
hi @irigon 

As Terraform is reporting here, the Image ID being specified (presumably in `var.os_image`) isn't valid, as it's missing the name (and a slash at the start):

> Error: the number of path segments is not divisible by 2 in "subscriptions/4007afb9-3bbc-4b9a-86ed-185b81caa50e/resourceGroups/rg-s4-azr0201-cr/providers/Microsoft.Compute/images"

You should be able to fix this by updating this value to:

> /subscriptions/4007afb9-3bbc-4b9a-86ed-185b81caa50e/resourceGroups/rg-s4-azr0201-cr/providers/Microsoft.Compute/images/{imageName}

Since this is a configuration issue rather than a bug in the Azure Provider I'm going to close this issue for the moment - but if that doesn't work for you then I'd recommend [opening an issue on the Community Discuss forum](https://discuss.hashicorp.com) where someone should be able to take a look.

Thanks!

**Comment by arcastaneda** [comment] 2022-01-25 17:16
Hi @tombuildsstuff , 

I think this may be a regression issue. I have the same error using 2.93.x when doing something similar with the linux vm resource. Our deployment was working previously, but is not after the change. No changes made to our deployment between versions. 

setup:

>variable "name_regex" {
  type    = string
  default = "^rhel-7-image-[0-9]{4}\\.[0-9]{2}\\.[0-9]{2}\\.rc[0-9]{4}$"
}

> data "azurerm_image" "example" {
  name_regex          = var.name_regex
  resource_group_name = var.rg_name
  sort_descending     = true
}

>resource "azurerm_linux_virtual_machine" "linux_vm" {
  name                  = var.vm_name
  location              = var.location
  resource_group_name   = var.rg_name
  ...
  source_image_id = data.azurerm_image.example.id
  ...
}

This code was working previously, something has since changed with 2.93.x that it gives the parsing error. Rolling back to 2,80.0 this deployment works just fine. I'm not savvy enough to look into the API call itself (if you could point me in the right direction I can try to figure it out) but this does look like where the error is being thrown during validation https://github.com/hashicorp/terraform-provider-azurerm/search?q=number+of+path+segments+is+not+divisible+by+2

**Comment by tombuildsstuff** [comment] 2022-01-25 18:10
@irigon apologies, digging into this your right this is a regression when using `name_regex` is used - the ID is pre-computed off of the `name` field which isn't specified - so this needs to be taken into account when generating the ID (and name) within the Image data source

**Closed** 2022-01-26 15:52 UTC
Labels: bug, regression, service/images
