### ISSUE TITLE
Adding new SessionHosts  produced an invalid new value for .settings

### ISSUE THREAD

**Issue by mdlister** [hashicorp/terraform-provider-azurerm#11808] opened 2021-05-20 15:16 UTC
I have been writing terraform to create a new hostpool and add a virtual machine to the pool, When then adding a second machine to the hostpool i get the following error. 

Error: Provider produced inconsistent final plan

```
When expanding the plan for
module.wvdhost["DDat-Operations"].azurerm_virtual_machine_extension.additional_session_host_dscextension[1]
to include new values learned so far during apply, provider
"registry.terraform.io/hashicorp/azurerm" produced an invalid new value for
.settings: was cty.StringVal("{\r\n    \"modulesURL\":
\"https://raw.githubusercontent.com/Azure/RDS-Templates/master/ARM-wvd-templates/DSC/Configuration.zip\",\r\n
\"configurationFunction\": \"Configuration.ps1\\\\AddSessionHost\",\r\n
\"properties\": {\r\n        \"HostPoolName\":\"DDat-Operations\",\r\n
\"RegistrationInfoToken\":\"***Redacted***BGbAGFLhnLKJ2OG6qOr8bgKzEtCo_LEVA4MdUFo7Dj7dI0ndE0jpg\"\r\n
}\r\n}\r\n"), but now cty.StringVal("{\r\n    \"modulesURL\":
\"https://raw.githubusercontent.com/Azure/RDS-Templates/master/ARM-wvd-templates/DSC/Configuration.zip\",\r\n
\"configurationFunction\": \"Configuration.ps1\\\\AddSessionHost\",\r\n
\"properties\": {\r\n        \"HostPoolName\":\"DDat-Operations\",\r\n
\"RegistrationInfoToken\":\"***Redacted**xTIdIVhhLgdBq6_3ZGhd4ZMJ8b_63xnS0P7QYu6ul3rXO8E3A\"\r\n
}\r\n}\r\n").

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

My hostpool block is 

```
resource "azurerm_virtual_desktop_host_pool" "main" {
  friendly_name            = var.friendly_name
  load_balancer_type       = var.load_balancer_type
  location                 = var.hostpool_metalocation
  maximum_sessions_allowed = var.hostpool_max_sessions
  name                     = var.prefix
  resource_group_name      = azurerm_resource_group.main.name
  type                     = var.hostpool_type
  validate_environment     = false
  registration_info {
    expiration_date = timeadd (timestamp(), "24h")
  }
}
```

I used to use the timeoffset function to generate a time for the expiration_date but found that it never updated in the state file and when it expired machines weren't being created.

**Comment by mdlister** [comment] 2021-05-25 07:43
for reference it was created and tested on 

Terraform v0.15.4
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.59.0

**Comment by tombuildsstuff** [comment] 2021-11-15 13:56
hi @mdlister 

Thanks for opening this issue.

Taking a look through this appears to be a duplicate of #13793 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #13793 for updates?

Thanks!

**Closed by tombuildsstuff** 2021-11-15 13:56 UTC
Labels: bug, service/virtual-machine-extensions
