### ISSUE TITLE
Support for property_columns in azurerm_stream_analytics_output_servicebus_topic

### ISSUE THREAD

**Issue by PseudoCoding** [hashicorp/terraform-provider-azurerm#13614] opened 2021-10-04 17:40 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for property_columns in azurerm_stream_analytics_output_servicebus_topic. Currently we have to manually add these fields to our output

It was added to `azurerm_stream_analytics_output_eventhub` with the `property_columns` being a string. Unsure if array or string makes more sense. 

### New or Affected Resource(s)

* azurerm_stream_analytics_output_servicebus_topic

### Potential Terraform Configuration

```hcl
resource "azurerm_stream_analytics_output_servicebus_topic" "example" {
  name = "service-bus-topic-output"
  stream_analytics_job_name = data.azurerm_stream_analytics_job.example.name
  resource_group_name = data.azurerm_stream_analytics_job.example.resource_group_name
  topic_name = azurerm_servicebus_topic.example.name
  servicebus_namespace = azurerm_servicebus_namespace.example.name
  shared_access_policy_key = azurerm_servicebus_namespace.example.default_primary_key
  shared_access_policy_name = "RootManageSharedAccessKey"
  property_columns = ["column1","column2","column1"]

  serialization {
    format = "Avro"
  }
}
```

or

```hcl
resource "azurerm_stream_analytics_output_servicebus_topic" "example" {
  name = "service-bus-topic-output"
  stream_analytics_job_name = data.azurerm_stream_analytics_job.example.name
  resource_group_name = data.azurerm_stream_analytics_job.example.resource_group_name
  topic_name = azurerm_servicebus_topic.example.name
  servicebus_namespace = azurerm_servicebus_namespace.example.name
  shared_access_policy_key = azurerm_servicebus_namespace.example.default_primary_key
  shared_access_policy_name = "RootManageSharedAccessKey"
  property_columns = "column1,column2,column1"

  serialization {
    format = "Avro"
  }
}
```

### References

* #10805

**Comment by tombuildsstuff** [comment] 2021-10-05 09:11
Duplicate of #10805 - please subscribe to that issue for updates

**Closed** 2021-11-19 00:56 UTC
Labels: enhancement, service/stream-analytics
