### ISSUE TITLE
Support for adding Soft DeleteRetentionInDays and Purge Protection enablement in app config terraform module

### ISSUE THREAD

**Issue by AbhishekPattnaik04** [hashicorp/terraform-provider-azurerm#17621] opened 2022-07-13 12:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There is no option to support Soft DeleteRetentionInDays and Purge Protection enablement currently in the app configuration terraform module, Please add it

### New or Affected Resource(s)/Data Source(s)

azurerm_app_configuration

### Potential Terraform Configuration

```hcl
resource "azurerm_app_configuration" "appconf" {
  name                = "appConf1"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  soft_delete_retention_days      = 7
  purge_protection_enabled        = true
}
}
```

**Comment by tombuildsstuff** [comment] 2022-07-13 14:41
Duplicate of #16915

**Closed by tombuildsstuff** 2022-07-13 14:41 UTC
Labels: duplicate, service/app-configuration
