### ISSUE TITLE
Azure Container Registry - unsupported attribute "virtual_network"

### ISSUE THREAD

**Issue by cpressland** [hashicorp/terraform-provider-azurerm#18241] opened 2022-09-02 16:12 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.8

### AzureRM Provider Version

3.21.0

### Affected Resource(s)/Data Source(s)

resource.azurerm_container_registry

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "rg" {
    name = "uksouth-core"
    location = "uksouth"
}

resource "azurerm_container_registry" "binkcore" {
    name = "binkcore"
    resource_group_name = azurerm_resource_group.rg.name
    location = azurerm_resource_group.rg.location
    sku = "Premium"
    admin_enabled = true
    georeplications {
        location = "ukwest"
    }
}
```

### Debug Output/Panic Output

```shell
│ Error: Failed to decode resource from state
│ 
│ Error decoding "module.uksouth-storage.azurerm_container_registry.binkops" from previous state: unsupported attribute "virtual_network"
```
```


### Expected Behaviour

Resource is refreshed correctly

### Actual Behaviour

Resource is not refreshed correctly

### Steps to Reproduce

1. `terraform plan -out=out -target="module.uksouth-core.azurerm_container_registry.binkcore"`

All of our existing Container Registries fail this way, so this should be fairly easily to pick up on any `plan`, note: resources were originally created on the 1.x providers and have been migrated all the way through.

### Important Factoids

_No response_

### References

#17926 - Appears to remove many references to `virtual_network`'s.

**Comment by tombuildsstuff** [comment] 2022-09-02 16:15
hey @cpressland 

Thanks for opening this issue / apologies for this regression.

Taking a look through here this appears to be a duplicate of #18232 which is an (unintentional) regression - the fix for which will be shipping in a patch release (`v3.21.1`) shortly.

Since this issue is a duplicate of #18232 which has since been fixed by #18239 which is shipping shortly, I'm going to close this issue for the moment - but as mentioned above this'll be released in a hotfix shortly.

Thanks!

**Closed by tombuildsstuff** 2022-09-02 16:15 UTC
Labels: bug, duplicate, regression, service/container-registry
