### ISSUE TITLE
azurerm_role_management_policy resource creation with require_approval = false, wants to modify after apply and delete approvall_stage{}

### ISSUE THREAD

**Issue by nazirakz** [hashicorp/terraform-provider-azurerm#26600] opened 2024-07-11 12:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.6

### AzureRM Provider Version

3.111

### Affected Resource(s)/Data Source(s)

azurerm_role_management_policy

### Terraform Configuration Files

```hcl
I've used the last version of AzureRM to create Pim assignments and azurerm_role_management_policy. An activation_rules block of resource has the attribute require_approval if the approval is required for activation an approval_stage block true must be provided. In my case require_approval is false. But after applying, it tries to modify and remove the empty approval_stage block.
```

### Debug Output/Panic Output

```shell
~ activation rules {
    - approval stage{
    }
}
```

### Expected Behaviour

Should not modify this block after apply

### Actual Behaviour

Tries to delete the empty approval_stage block.

### Steps to Reproduce

FIx the issue

**Comment by OQCDoe** [comment] 2024-07-16 10:33
Probably dupliacte of https://github.com/hashicorp/terraform-provider-azurerm/issues/26377

**Comment by rcskosir** [comment] 2024-08-07 19:28
Thanks for taking the time to submit this issue. I agree that this looks like this is a duplicate of #26377. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of #26377.

**Closed by rcskosir** 2024-08-07 19:28 UTC
Labels: service/authorization, v/3.x
