### ISSUE TITLE
azurerm_windows_function_app - cannot use Plan Type "Functions Premium"

### ISSUE THREAD

**Issue by Romiko** [hashicorp/terraform-provider-azurerm#16978] opened 2022-05-26 10:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.7

### AzureRM Provider Version

3.7.0

### Affected Resource(s)/Data Source(s)

azurerm_windows_function_app

### Terraform Configuration Files

```hcl
resource "azurerm_service_plan" "function_plan" {
  name                = "plan-${local.resource_id}-func"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
  os_type             = "Windows"
  # SKU can no longer be EP1 etc. Terraform needs a Premium Function app type. 
  # Azure no longer allows elastic at Service plan level.
  # Need to find a solution for elastic function apps.
  sku_name            = var.app_plan.function_plan_size
  tags                = local.tags
}

# Bug default_hostheader not output
resource "azurerm_windows_function_app" "function" {
  name                        = "func-${local.resource_id}"
  resource_group_name         = azurerm_resource_group.rg.name
  location                    = azurerm_resource_group.rg.location
  service_plan_id             = azurerm_service_plan.function_plan.id
```

### Debug Output/Panic Output

```shell
Terraform states that the resource is not supported in my region. However app service plans can no longer be configured as elastic (EP1)
```

### Expected Behaviour

We should be able to create a Function App that is Premium SKU e.g. EP1 EP2 EP3 using the azurerm_windows_function_app

This means we need a reference to a Function Premium and not a azurerm_service_plan.

In the azure portal there is now a difference between app service plan and functions premium.

### Actual Behaviour

The EP1 etc is no longer working as a service plan. So terraform will state the resource is not supported in my region.

### Steps to Reproduce

resource "azurerm_service_plan" "function_plan" {
  name                = "plan-${local.resource_id}-func"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
  os_type             = "Windows"
  # SKU can no longer be EP1 etc. Terraform needs a Premium Function app type. 
  # Azure no longer allows elastic at Service plan level.
  # Need to find a solution for elastic function apps.
  sku_name            = var.app_plan.function_plan_size
  tags                = local.tags
}

# Bug default_hostheader not output
resource "azurerm_windows_function_app" "function" {
  name                        = "func-${local.resource_id}"
  resource_group_name         = azurerm_resource_group.rg.name
  location                    = azurerm_resource_group.rg.location
  service_plan_id             = azurerm_service_plan.function_plan.id
  storage_account_name        = azurerm_storage_account.function_st_account.name
  storage_account_access_key  = azurerm_storage_account.function_st_account.primary_access_key
  functions_extension_version = "~3"

  app_settings = {
    "WEBSITE_RUN_FROM_PACKAGE" = "",
    "FUNCTIONS_WORKER_RUNTIME" = "node",
    "WEBSITE_NODE_DEFAULT_VERSION" = "~12",
    "APPINSIGHTS_INSTRUMENTATIONKEY" = var.app_insights_instrumentation_key
  }
  site_config {
    cors {
      allowed_origins = ["*"]
    }
    use_32_bit_worker = true
  }
  lifecycle {
    ignore_changes = [
      app_settings["AzureWebJobsStorage"],
      app_settings["WEBSITE_RUN_FROM_PACKAGE"],
      app_settings["FUNCTIONS_WORKER_RUNTIME"],
      app_settings["ENV"],
      app_settings["DB_USERNAME"],
      app_settings["POSTGRES_USER_STRING"],
      app_settings["MYSQL_USER_STRING"],
      app_settings["MYSQL_HOST"],
      app_settings["POSTGRES_HOST"],
      app_settings["POSTGRES_PASSWORD"],
      app_settings["MYSQL_PASSWORD"],
      app_settings["DATABASE_MAIN"],
      app_settings["SCHEMA_LOCATIONS"],
      app_settings["HAPIKEY"],
      app_settings["WEBSITE_ENABLE_SYNC_UPDATE_SITE"]
    ]
  }
  tags = local.tags
}

**Comment by xiaxyi** [comment] 2023-05-30 08:30
Hey @Romiko, long time no see. Can I follow up with you to see if you are able to set the EP1 service plan now? Let me know if you meet any issue using it. thanks!

**Comment by rcskosir** [comment] 2023-08-25 15:43
Thanks for taking the time to submit this issue. @xiaxyi was unable to reproduce this behavior. We’re going to close this issue for now, but if you run into this again with the latest Terraform and Provider versions, please feel free to [open a new issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/new/choose).

**Closed by rcskosir** 2023-08-25 15:43 UTC
Labels: waiting-response, service/functions, v/3.x
