### ISSUE TITLE
Plan and Apply after deploy removes Keyvault Access Keys

### ISSUE THREAD

**Issue by grierdavid** [hashicorp/terraform-provider-azurerm#14822] opened 2022-01-05 23:30 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

terraform 1.1.0

* `azurerm_2.85.0`

### Terraform Configuration Files

```keyvault
variable "environment" {}
variable "geo_location" {}
variable "deployment" {}

variable "app_resource_group" {}

locals {
  geo = "${upper(var.geo_location)}"
  env = "${upper(var.environment)}"
  geo_lower = "${lower(var.geo_location)}"
  env_lower = "${lower(var.environment)}"
}

locals {
  app_resource_group_name = "${var.deployment}-${local.env_lower}-dataops"
  key_vault_name          = "${local.geo_lower}-kvlt-${local.env_lower}"
}

data "azurerm_client_config" "current" {}

data "azuread_service_principal" "example" {
  display_name = "Azure Machine Learning Services"
}

resource "azurerm_key_vault" "app" {
  name                        = "${local.key_vault_name}"
  location                    = local.geo_lower
  resource_group_name         = var.app_resource_group
  enabled_for_disk_encryption = true
  enabled_for_deployment      = true
  tenant_id                   = data.azurerm_client_config.current.tenant_id
  purge_protection_enabled    = false

  access_policy {
    tenant_id = data.azurerm_client_config.current.tenant_id
    object_id = data.azurerm_client_config.current.object_id

    certificate_permissions = [
      "create",
      "delete",
      "deleteissuers",
      "get",
      "getissuers",
      "import",
      "list",
      "listissuers",
      "managecontacts",
      "manageissuers",
      "setissuers",
      "update",
    ]

    key_permissions = [
      "backup",
      "create",
      "decrypt",
      "delete",
      "encrypt",
      "get",
      "import",
      "list",
      "purge",
      "recover",
      "restore",
      "sign",
      "unwrapKey",
      "update",
      "verify",
      "wrapKey",
    ]

    secret_permissions = [
      "backup",
      "delete",
      "get",
      "list",
      "purge",
      "recover",
      "restore",
      "set",
    ]

    storage_permissions = [
      "Get",
      "List",
      "Set",
      "SetSAS",
      "GetSAS",
      "DeleteSAS",
      "Update",
      "RegenerateKey"
    ]
  }

  sku_name = "standard"
}

output "key_vault_id" {
  value = azurerm_key_vault.app.id
}

output "key_vault_name" {
  value = "${local.geo_lower}-kvlt-${local.env_lower}"
}
```
```azure ml
variable "environment" {}
variable "geo_location" {}
variable "deployment" {}

variable "key_vault_id" {}
variable "app_resource_group" {}
variable "storage_account" {}
variable "app_resource_group_location" {}

locals {
  geo       = "${upper(var.geo_location)}"
  env       = "${upper(var.environment)}"
  geo_lower = "${lower(var.geo_location)}"
  env_lower = "${lower(var.environment)}"
}

data "azurerm_client_config" "current" {}

resource "azurerm_application_insights" "web" {
  name                = "${var.deployment}-${local.env_lower}-appinsights"
  location            = var.app_resource_group_location
  resource_group_name = var.app_resource_group
  application_type    = "web"
}

resource "azurerm_machine_learning_workspace" "this" {
  name                    = "${var.deployment}-${local.env_lower}-mlws"
  location                = var.app_resource_group_location
  application_insights_id = azurerm_application_insights.web.id
  resource_group_name     = var.app_resource_group
  key_vault_id            = var.key_vault_id
  storage_account_id      = var.storage_account
  identity {
    type = "SystemAssigned"
  }
}

resource "azurerm_container_registry" "aml" {
  name                     = "${var.deployment}${local.env_lower}acr"
  resource_group_name      = var.app_resource_group
  location                 = var.app_resource_group_location
  sku                      = "Standard"
  admin_enabled            = true
}

resource "azurerm_machine_learning_compute_cluster" "this" {
  name                          = "${var.deployment}-${local.env_lower}-cl"
  location                      = var.app_resource_group_location
  vm_priority                   = "LowPriority"
  vm_size                       = "STANDARD_DS2_V2"
  machine_learning_workspace_id = azurerm_machine_learning_workspace.this.id

  scale_settings {
    min_node_count                       = 0
    max_node_count                       = 2
    scale_down_nodes_after_idle_duration = "PT30S" # 30 seconds
  }

  identity {
    type = "SystemAssigned"
  }

  tags = {
    env = local.env_lower
  }
}

output "workspace_id" {
  value = azurerm_machine_learning_workspace.this.id
}

output "workspace_name" {
  value = "${var.deployment}-${local.env_lower}-mlws"
}

output "aml_compute_cluster" {
  value = "${var.deployment}-${local.env_lower}-cl"
}
```
azure storage
```
variable "environment" {}
variable "geo_location" {}
variable "deployment" {}

variable "app_resource_group" {}
variable "app_resource_group_location" {}
variable "key_vault_id" {}
variable "key_vault_name" {}

locals {
  geo       = "${upper(var.geo_location)}"
  env       = "${upper(var.environment)}"
  geo_lower = "${lower(var.geo_location)}"
  env_lower = "${lower(var.environment)}"
}

locals {
  app_resource_storage_name = "${local.geo_lower}adls01${local.env_lower}"
}

data "azurerm_client_config" "current" {}

resource "azurerm_storage_account" "app" {
  name                     = local.app_resource_storage_name
  resource_group_name      = var.app_resource_group
  location                 = var.app_resource_group_location
  account_kind             = "StorageV2"
  account_tier             = "Standard"
  account_replication_type = "LRS"
  
  identity {
    type = "SystemAssigned"
  }

  tags = {
    environment = "${local.env}"
  }
}

locals {
  key_permissions         = ["get", "create", "list", "restore", "recover", "unwrapkey", "wrapkey", "purge", "encrypt", "decrypt", "sign", "verify"]
  secret_permissions      = ["all"]
  certificate_permissions = ["all"]
  storage_permissions     = ["all"]
}

resource "azurerm_key_vault_access_policy" "storage" {
  key_vault_id = var.key_vault_id
  tenant_id    = data.azurerm_client_config.current.tenant_id
  object_id    = azurerm_storage_account.app.identity.0.principal_id

  key_permissions    = ["get", "create", "list", "restore", "recover", "unwrapkey", "wrapkey", "purge", "encrypt", "decrypt", "sign", "verify"]
  secret_permissions = ["backup", "delete", "get", "list", "purge", "recover", "restore", "set"]
  storage_permissions = [
    "get", 
    "list", 
    "delete",
    "set",
    "update",
    "regeneratekey",
    "getsas",
    "listsas",
    "deletesas",
    "setsas",
    "recover",
    "backup",
    "restore",
    "purge"
    ]
}

output "storage_account_id" {
  value = azurerm_storage_account.app.id
}

output "storage_account_name" {
  value = local.app_resource_storage_name
}

output "storage_account_conn_str" {
  value = azurerm_storage_account.app.primary_connection_string
}
```
storage key
```
variable "environment" {}
variable "geo_location" {}
variable "deployment" {}

variable "app_resource_group" {}
variable "app_resource_group_location" {}
variable "key_vault_id" {}

variable "storage_account" {}
variable "storage_account_conn_str" {}
variable "storage_account_name" {}


locals {
  geo       = "${upper(var.geo_location)}"
  env       = "${upper(var.environment)}"
  geo_lower = "${lower(var.geo_location)}"
  env_lower = "${lower(var.environment)}"
}

data "azurerm_client_config" "current" {}

data "azurerm_storage_account_sas" "this" {
  connection_string = var.storage_account_conn_str
  https_only        = true

  resource_types {
    service   = true
    container = false
    object    = false
  }

  services {
    blob  = true
    queue = false
    table = false
    file  = false
  }

  start  = "2021-04-30T00:00:00Z"
  expiry = "2023-04-30T00:00:00Z"

  permissions {
    read    = true
    write   = true
    delete  = true
    list    = true
    add     = true
    create  = true
    update  = true
    process = true
  }
}

resource "azurerm_key_vault_managed_storage_account" "this" {
  name                         = var.storage_account_name
  key_vault_id                 = var.key_vault_id
  storage_account_id           = var.storage_account
  storage_account_key          = "key1"
  regenerate_key_automatically = false
  regeneration_period          = "P1D"
}

resource "azurerm_key_vault_managed_storage_account_sas_token_definition" "this" {
  name                       = "${var.deployment}${local.env_lower}def"
  validity_period            = "P1D"
  managed_storage_account_id = azurerm_key_vault_managed_storage_account.this.id
  sas_template_uri           = data.azurerm_storage_account_sas.this.sas
  sas_type                   = "account"
}

resource "azurerm_storage_encryption_scope" "app" {
  name               = "${var.deployment}${local.env_lower}storage"
  storage_account_id = var.storage_account
  source             = "Microsoft.Storage"
}
```

### Debug Output

Plan shows change although there is no changes to the TF configuration and no changes to the state

```
Terraform will perform the following actions:

  # module.key_vault["dev"].azurerm_key_vault.app will be updated in-place
  ~ resource "azurerm_key_vault" "app" {
      ~ access_policy                   = [
            {
                application_id          = ""
                certificate_permissions = [
                    "Create",
                    "Delete",
                    "DeleteIssuers",
                    "Get",
                    "GetIssuers",
                    "Import",
                    "List",
                    "ListIssuers",
                    "ManageContacts",
                    "ManageIssuers",
                    "SetIssuers",
                    "Update",
                ]
                key_permissions         = [
                    "Backup",
                    "Create",
                    "Decrypt",
                    "Delete",
                    "Encrypt",
                    "Get",
                    "Import",
                    "List",
                    "Purge",
                    "Recover",
                    "Restore",
                    "Sign",
                    "UnwrapKey",
                    "Update",
                    "Verify",
                    "WrapKey",
                ]
                object_id               = "xxxxxxxxxxxxxxxxxxxxx"
                secret_permissions      = [
                    "Backup",
                    "Delete",
                    "Get",
                    "List",
                    "Purge",
                    "Recover",
                    "Restore",
                    "Set",
                ]
                storage_permissions     = [
                    "Get",
                    "List",
                    "Set",
                    "SetSAS",
                    "GetSAS",
                    "DeleteSAS",
                    "Update",
                    "RegenerateKey",
                ]
                tenant_id               = "xxxxxxxxxxxxxxxxxxxxx"
            },
          - {
              - application_id          = ""
              - certificate_permissions = []
              - key_permissions         = [
                  - "Get",
                  - "Create",
                  - "List",
                  - "Restore",
                  - "Recover",
                  - "UnwrapKey",
                  - "WrapKey",
                  - "Purge",
                  - "Encrypt",
                  - "Decrypt",
                  - "Sign",
                  - "Verify",
                ]
              - object_id               = "xxxxxxxxxxxxxxxxxxxxx"
              - secret_permissions      = [
                  - "Backup",
                  - "Delete",
                  - "Get",
                  - "List",
                  - "Purge",
                  - "Recover",
                  - "Restore",
                  - "Set",
                ]
              - storage_permissions     = [
                  - "Get",
                  - "List",
                  - "Delete",
                  - "Set",
                  - "Update",
                  - "RegenerateKey",
                  - "GetSAS",
                  - "ListSAS",
                  - "DeleteSAS",
                  - "SetSAS",
                  - "Recover",
                  - "Backup",
                  - "Restore",
                  - "Purge",
                ]
              - tenant_id               = "xxxxxxxxxxxxxxxxxxxxx"
            },
          - {
              - application_id          = ""
              - certificate_permissions = [
                  - "all",
                ]
              - key_permissions         = [
                  - "all",
                ]
              - object_id               = "xxxxxxxxxxxxxxxxxxxxx"
              - secret_permissions      = [
                  - "all",
                ]
              - storage_permissions     = []
              - tenant_id               = "xxxxxxxxxxxxxxxxxxxxx"
            },
        ]
        id                              = "/subscriptions/xxxxxxxxxxxxxxxx/resourceGroups/rprclnc-dev-dataops/providers/Microsoft.KeyVault/vaults/westus2-kvlt-dev"
        name                            = "westus2-kvlt-dev"
        tags                            = {}
        # (12 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.



### Panic Output


### Expected Behaviour
No changes should be queued

### Actual Behaviour

Changes are queued and implemented on apply. Apply removes ml workspace access key or storage access key or both, on each new plan/apply

In the most recent test the above plan was executed and removed both the storage access key and the ml workspace access key.

### Steps to Reproduce

deploy storage account with keyvault and sas along with ml workspace using vault for storage access, run apply, plan, apply repeatedly

1. `terraform apply`

### Important Factoids



### References


* #0000

**Comment by tombuildsstuff** [comment] 2022-01-06 10:43
hi @seraphin 

Thanks for opening this issue.

Presumably the Access Policy which is being added is for the Storage Account, via the `azurerm_key_vault_managed_storage_account` resource? As such [the same Disclaimer would apply](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault#disclaimers) when managing these using the internal `access_policies` block and this separate resource - which would make this a docs bug - would you be able to confirm if the Access Policy which is being added is for the (Managed) Storage Account, or something unrelated?

Thanks!

**Comment by seraphin** [comment] 2022-01-06 16:08
Hi @tombuildsstuff,

Yes this is the issue. The issue is 2 part, I am creating a policy within the key vault for access and also I was creating the storage account access independently, since I was under the impression that was required. I can see now that storage access is already provided by the `azurerm_key_vault_managed_storage_account` resource.

**Comment by mybayern1974** [comment] 2022-12-27 04:10
@grierdavid , with assuming this issue has been resolved, I'm closing this issue. Feel free to suggest to reactivate it if there are further questions. Thank you.

**Closed by mybayern1974** 2022-12-27 04:10 UTC
Labels: question, service/key-vault
