### ISSUE TITLE
performing CreateOrUpdate: workspaces.WorkspacesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error.

### ISSUE THREAD

**Issue by fangjian0423** [hashicorp/terraform-provider-azurerm#20197] opened 2023-01-27 17:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.5

### AzureRM Provider Version

3.41.0

### Affected Resource(s)/Data Source(s)

azurerm_log_analytics_workspace

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      version = "~>3.41.0"
      source  = "hashicorp/azurerm"
    }
    azurecaf = {
      source  = "aztfmod/azurecaf"
      version = "~>1.2.15"
    }
  }
}

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "rg" {
  name     = "jimmy-rg-test"
  location = "eastus"
}

resource "azurerm_log_analytics_workspace" "example" {
  name                = "acctest-01"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  sku                 = "PerGB2018"
  retention_in_days   = 30
}
```

### Debug Output/Panic Output

```shell
azurerm_resource_group.rg: Creating...
azurerm_resource_group.rg: Creation complete after 5s [id=/subscriptions/xxxxxxx/resourceGroups/jimmy-rg-test]
azurerm_log_analytics_workspace.example: Creating...
╷
│ Error: performing CreateOrUpdate: workspaces.WorkspacesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="InvalidPolicyParameters" Message="A function or parameter in policy assignment 'acat-custom-policy-set-assignment' associated with the policy definition 'log-analytics-workspace-retention' could not be validated. Please either fix the policy or remove the policy assignment to unblock. If using template functions, try following the tips in: https://aka.ms/policy-avoiding-template-failures. The inner error is 'The template language function 'length' expects its parameter to be an array, object, or a string. The provided value is of type 'Integer'. Please see https://aka.ms/arm-template-expressions/#length for usage details.'."
│ 
│   with azurerm_log_analytics_workspace.example,
│   on main.tf line 6, in resource "azurerm_log_analytics_workspace" "example":
│    6: resource "azurerm_log_analytics_workspace" "example" {
```

### Expected Behaviour

Log Analytics workspace create successfully.

### Actual Behaviour

 Error: performing CreateOrUpdate: workspaces.WorkspacesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="InvalidPolicyParameters" Message="A function or parameter in policy assignment 'acat-custom-policy-set-assignment' associated with the policy definition 'log-analytics-workspace-retention' could not be validated. Please either fix the policy or remove the policy assignment to unblock. If using template functions, try following the tips in: https://aka.ms/policy-avoiding-template-failures. The inner error is 'The template language function 'length' expects its parameter to be an array, object, or a string. The provided value is of type 'Integer'. Please see https://aka.ms/arm-template-expressions/#length for usage details.'."

**Comment by aristosvo** [comment] 2023-01-28 10:15
Hi @fangjian0423! The error is caused by a policy on your subscription, based on the interpretation of the error message.

As such this is not something which can or should be resolved at the `azurerm` side, but within a policy set (acat) on your Azure subscription. I'll close this issue for now.

**Closed** 2023-01-28 10:16 UTC

**Comment by fangjian0423** [comment] 2023-01-29 15:49
Thank you @aristosvo , do you know how to set the policy on my Azure subscription?

**Comment by fangjian0423** [comment] 2023-01-30 12:55
I know how to set policy, thanks ❤️
