### ISSUE TITLE
Terraform 3.3.0 tries to refresh secret state BEFORE applying all access policies

### ISSUE THREAD

**Issue by Pumkko** [hashicorp/terraform-provider-azurerm#16618] opened 2022-05-02 13:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.9

### AzureRM Provider Version

3.3.0

### Affected Resource(s)/Data Source(s)

azurerm_key_vault

### Terraform Configuration Files

```hcl
data "azurerm_client_config" "current" {}

resource "azurerm_key_vault" "myKeyVault" {
  name                       = "keyvault"
  location                   = azurerm_resource_group.resourceGroup.location
  resource_group_name        = azurerm_resource_group.resourceGroup.name
  tenant_id                  = data.azurerm_client_config.current.tenant_id
  sku_name                   = "standard"
  soft_delete_retention_days = 7
}


resource "azurerm_key_vault_access_policy" "pipelineAccessPolicy" {
  key_vault_id = azurerm_key_vault.myKeyVault.id
  tenant_id    = data.azurerm_client_config.current.tenant_id
  object_id    = var.AZURE_SUBSCRIPTION_OID

  secret_permissions = [
    "Get",
    "List",
    "Set",
    "Delete",
    "Purge",
    "Recover",
    "Backup",
    "Restore"
  ]
}

resource "azurerm_key_vault_secret" "secretOne" {
  name         = "Secret1"
  value        = ""
  key_vault_id = azurerm_key_vault.myKeyVault.id
}


resource "azurerm_key_vault_secret" "secretTwo" {
  name         = "Secret2"
  value        = ""
  key_vault_id = azurerm_key_vault.myKeyVault.id
}
```

### Debug Output/Panic Output

```shell
[0m[1mazurerm_key_vault_secret.secretOne: Refreshing state... 
[0m[1mazurerm_key_vault_secret.secretOne: Refreshing state... 
making Read request on Azure KeyVault Secret secretOne: keyvault.BaseClient#GetSecret: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="The user, group or application does not have secrets get permission on key vault 'keyvault;location=eastus'.
```

### Expected Behaviour

I expected terraform to apply access policies before trying to refresh everything it knows about the secrets/keys/certificates 

### Actual Behaviour

Terraform apply fails before trying to apply the policy that will allow the azure pipelline to work, if i do set the access policy manually using Azure it works fine but fails at a later point because Terraform complains that the policy that it is trying to set already exists. 

### Steps to Reproduce

This issue arises when updating the keyvault access policies, when creating the keyvault from scratch it works fine

**Comment by tombuildsstuff** [comment] 2022-05-03 07:43
hi @Pumkko 

Thanks for opening this issue.

This is by design, Terraform needs access to the resources it's provisioning (or has previously provisioned) - if a unique service principal is being used to run Terraform every time, then you'll need to ensure it has access to the Key Vault prior to running Terraform (or generate a new secret per apply, rather than an entirely new service principal).

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Closed by tombuildsstuff** 2022-05-03 07:43 UTC
Labels: question
