### ISSUE TITLE
Unable to determine the Resource ID for the Key Vault at URL when destroying secret

### ISSUE THREAD

**Issue by dobrzyn2** [hashicorp/terraform-provider-azurerm#11557] opened 2021-05-02 20:39 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Tested on terraform {0.14.10, 0.15.0, 0.15.1}
Azurerm version "2.56.0"
### Affected Resource(s)

* `azurerm_key_vault`
* `azurerm_key_vault_secret`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "2.56.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "3.0.0"
    }
    http = {
      source  = "hashicorp/http"
      version = "2.0.0"
    }
  }
}

provider "azurerm" {
  features {
    key_vault {
      # do not attempt to purge secrets since we don't enable that on our kvs
      purge_soft_delete_on_destroy = false
    }
  }
  skip_provider_registration = true
}

data "azurerm_client_config" "current" {}

locals {
  prefix = var.basename
}

data "azurerm_resource_group" "rg" {
  name = var.resourcegroup
}
# https://www.terraform.io/docs/providers/azurerm/r/key_vault.html
resource "azurerm_key_vault" "kv" {
  name                = format("%s-kv", local.prefix)
  location            = var.location
  resource_group_name = data.azurerm_resource_group.rg.name
  tenant_id           = data.azurerm_client_config.current.tenant_id
  sku_name            = "standard"
}

# https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault_access_policy
resource "azurerm_key_vault_access_policy" "sp-manage" {
  key_vault_id       = azurerm_key_vault.kv.id
  tenant_id          = data.azurerm_client_config.current.tenant_id
  object_id          = data.azurerm_client_config.current.object_id
  secret_permissions = ["set", "delete", "get", "list"]
}

# https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault_access_policy
resource "azurerm_key_vault_access_policy" "app-kv-get" {
  count              = length(local.apps)
  key_vault_id       = azurerm_key_vault.kv.id
  tenant_id          = data.azurerm_client_config.current.tenant_id
  object_id          = local.apps[count.index].identity.0.principal_id
  secret_permissions = ["get"]
}
# https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault_secret
resource "azurerm_key_vault_secret" "db-connection-string" {
  for_each     = var.tenants
  depends_on   = [azurerm_key_vault_access_policy.sp-manage]
  key_vault_id = azurerm_key_vault.kv.id
  name         = format("db-connection-string-%s", each.key)
  value        = "fake-string"
}

```

### Debug Output

https://gist.github.com/dobrzyn2/33090662f2514b2b2e11efd70b049c76
### Panic Output

N/A
### Expected Behaviour

All resources should have been deleted, include secrets and keyvault
### Actual Behaviour

Destory errors out with the following error
`Error: Unable to determine the Resource ID for the Key Vault at URL `
### Steps to Reproduce

1. `terraform apply`
2. `terraform destroy`
### Important Factoids

The issue is easily reproducible on azure pipeline vms running images for `ubuntu-latest` 
### References

N/A

**Comment by AurimasNav** [comment] 2021-09-08 11:39
I am getting the same error in a situation where I am trying to refer to azurerm_key_vault_secret data source from another subscription:
```hcl
data "azurerm_key_vault" "this" {
  name                = "management-kv"
  resource_group_name = "mgmt-rg"
  provider            = azurerm.management
}

data "azurerm_key_vault_certificate" "this" {
  name         = "star-domain-com"
  key_vault_id = data.azurerm_key_vault.this.id
  provider     = azurerm.management
}

resource "azurerm_app_service_certificate" "app_cert" {
  name                = var.name
  resource_group_name = var.group_name
  location            = var.location
  key_vault_secret_id = data.azurerm_key_vault_certificate.this.secret_id
}
```
I am also using the same certificate from same key vault and same data source approach in another terraform  
deployment for app gateway cert configuration and that one does not generate this error.

│ Error: Unable to determine the Resource ID for the Key Vault at URL "https://fake-management-kv.vault.azure.net/"
│
│   with module.app_service_opsai.azurerm_app_service_certificate.app_cert[0],
│   on .terraform\modules\app_service_opsai\main.tf line 445, in resource "azurerm_app_service_certificate" "app_cert":
│  445: resource "azurerm_app_service_certificate" "app_cert" {
│

**Comment by tombuildsstuff** [comment] 2021-11-15 13:30
hi @dobrzyn2 

Reading through I believe this is (now) a duplicate of one of the two issues in #11059, where the Azure API is responding with a `429 Too Many Requests` however the Azure SDK for Go isn't accounting for this when making Data Plane calls. Rather than having multiple issues open tracking the same thing I'm going to close this in favour of #11059, would you mind subscribing to that issue for updates?

Thanks!

**Closed by tombuildsstuff** 2021-11-15 13:30 UTC
Labels: bug, duplicate, service/keyvault
