### ISSUE TITLE
Can't set scale rules with AzApi, when `azurerm_container_app` is managed by AzureRm

### ISSUE THREAD

**Issue by Zizico2** [hashicorp/terraform-provider-azurerm#20631] opened 2023-02-23 13:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.9

### AzureRM Provider Version

3.43.0

### Affected Resource(s)/Data Source(s)

azurerm_container_app

### Terraform Configuration Files

```hcl
resource "azurerm_container_app" "example" {
  name                         = "example"
  container_app_environment_id = azurerm_container_app_environment.example.id
  resource_group_name          = azurerm_resource_group.example.name
  revision_mode                = "Single"
  template {
    min_replicas = 1
    max_replicas = 10
    container {
      name   = "gateway"
      image  = "example.azurecr.io/example:latest"
      cpu    = 2
      memory = "4Gi"
    }
  }
}

resource "azapi_update_resource" "example" {
  type        = "Microsoft.App/containerApps@2022-10-01"
  resource_id = azurerm_container_app.example.id
  body = jsonencode(
    {
      properties = {
        configuration = {
          secrets = [
            {
              name  = "example"
              value = azurerm_servicebus_namespace.example.default_primary_connection_string
            }
          ]
        }
        template = {
          scale = {
            rules = [
              {
                name = "example"
                custom = {
                  type = "azure-servicebus"
                  auth = [
                    {
                      secretRef        = "example"
                      triggerParameter = "connection"
                    }
                  ]
                  metadata = {
                    messageCount     = "10"
                    namespace        = azurerm_servicebus_namespace.example.name
                    subscriptionName = azurerm_servicebus_subscription.example.name
                    topicName        = azurerm_servicebus_topic.example.name
                  }
                }
              }
            ]
          }
        }
      }
    }
  )
}
```

### Debug Output/Panic Output

```shell
There's no error. Just very inconsistent behavior.
```

### Expected Behaviour

Deploy the container app and set the scale rules.

### Actual Behaviour

The container app gets deployed and the scale rules don't get applied. Or get applied and then deleted on a following deployment.

### References

This comment https://github.com/hashicorp/terraform-provider-azurerm/issues/20535#issuecomment-1441608202 reports a bug that seems somewhat related.

**Comment by tombuildsstuff** [comment] 2023-02-24 10:35
hi @Zizico2

Unfortunately this is a known limitation when patching existing resources managed by the Azure Provider outside of Terraform - either through the Azure CLI, an ARM Template, the Azure Portal or indeed the `azapi_*` resources.

Whilst there's some commonalities across the different Azure APIs, how each of the APIs handles updates can differ substantially, as such it's possible to end up in situations like this when patching resources managed by Terraform.

Whilst patching existing resources is convenient, unfortunately it's a double-edged sword since it requires a deep understanding of the Azure APIs themselves. This is even more pronounced when a resource is provisioned on one API version and then patched in another (as is happening here) since different Azure APIs handle patch updates differently - and there can also be breaking behavioural changes behind the scenes (for example, API Version `2020-05-01` for Network).

In this instance Terraform is retrieving the Container App from the Azure API and then patching the updated values across - however we're doing so using API version `2022-03-01` which doesn't support these fields. In the `azapi` template above, the API version `2022-10-01` is being used, which presumably does - meaning that since the update is applied using an older API version, these rules are ultimately being removed by the Azure API rather than the Provider.

Whilst I appreciate that hearing this is an intentional design limitation probably isn't great - unfortunately since the behaviour of the Azure API can change based on the Resource, API Version and even Location (depending on which version of an API has been deployed) - this is by design within the Azure Platform.

In this case if you're looking to take advantage of Scale Rules, I'd probably recommend provisioning the `azurerm_container_app` resource using either an ARM Template or the `azapi_resource` for now - and then (once this new field is supported) I'd recommend switching back to the `azurerm_container_app` resource.

---

As such whilst I'd like to thank you for opening this issue, I'm going to close this issue in favour of #20629 which is tracking supporting Scale Rules within the `azurerm_container_app` resource.

Thanks!

**Closed by tombuildsstuff** 2023-02-24 10:35 UTC
Labels: question, service/container-apps
