### ISSUE TITLE
azurerm_storage_share_file crashed

### ISSUE THREAD

**Issue by tanvp112** [hashicorp/terraform-provider-azurerm#14507] opened 2021-12-07 07:01 UTC
This happens when using the module to upload files to Azure File. Checking on the portal the file was uploaded successful but somehow it crashed.

> Stack trace from the terraform-provider-azurerm_v2.88.1_x5 plugin:
> 
> panic: sync: negative WaitGroup counter
> 
> goroutine 1636 [running]:
> sync.(*WaitGroup).Add(0x664e400, 0xc000556100)
> /opt/goenv/versions/1.17.3/src/sync/waitgroup.go:74 +0x105
> sync.(*WaitGroup).Done(...)
> /opt/goenv/versions/1.17.3/src/sync/waitgroup.go:99
> github.com/tombuildsstuff/giovanni/storage/2020-08-04/file/files.Client.PutFile.func1(0x1)
> /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/github.com/tombuildsstuff/giovanni/storage/2020-08-04/file/files/range_put_file.go:56 +0x2c5
> created by github.com/tombuildsstuff/giovanni/storage/2020-08-04/file/files.Client.PutFile
> /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-azurerm/vendor/github.com/tombuildsstuff/giovanni/storage/2020-08-04/file/files/range_put_file.go:40 +0x23e
> 
> Error: The terraform-provider-azurerm_v2.88.1_x5 plugin crashed!
> 
> This is always indicative of a bug within the plugin. It would be immensely
> helpful if you could report the crash with the plugin's maintainers so that it
> can be fixed. The output above should help diagnose the issue.

**Comment by tombuildsstuff** [comment] 2021-12-13 12:19
hi @tanvp112 

Thanks for opening this issue.

Taking a look through this appears to be a duplicate of #12925 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #12925 for updates?

Thanks!

**Closed by tombuildsstuff** 2021-12-13 12:19 UTC
Labels: bug, crash
