### ISSUE TITLE
Azure CDN delivery rule "order" argument description is wrong in documentation

### ISSUE THREAD

**Issue by aaronswainonset** [hashicorp/terraform-provider-azurerm#14050] opened 2021-11-05 05:49 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_cdn_endpoint`

### Terraform Configuration Files

```hcl
resource "azurerm_cdn_endpoint" "cdn" {
  name                      = var.cdn_name
  resource_group_name       = azurerm_resource_group.rg.name
  location                  = azurerm_resource_group.rg.location
  #....

  delivery_rule {
    name ="rule1"
    order = 2
    #....
  }
}
```

### Actual Behaviour

The Terraform documentation says:

> order - (Required) The order used for this rule, which must be larger than 1.

When no rules exist, and using the delivery_rule block shown above, Terraform gives the error:

> The delivery rules order values must start from 0 (if using a base rule) or 1.

### Steps to Reproduce

1. `terraform apply` using the delivery_rule block above.

### References

* https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cdn_endpoint#delivery_rule

**Comment by secustor** [comment] 2021-11-16 22:24
I think this is a duplicate of #11806

**Comment by aaronswainonset** [comment] 2021-11-16 22:34
> 
> 
> I think this is a duplicate of #11806

I agree, I'm happy to close this issue.

**Comment by katbyte** [comment] 2022-01-10 05:23
closing as duplicate of #11806

**Closed by katbyte** 2022-01-10 05:23 UTC
Labels: documentation, good first issue, service/cdn
