### ISSUE TITLE
improperly formatted Object ID for Principal object without dashes

### ISSUE THREAD

**Issue by nani2ratna** [hashicorp/terraform-provider-azurerm#19932] opened 2023-01-10 04:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.9

### AzureRM Provider Version

2.90.0

### Affected Resource(s)/Data Source(s)

azurerm_linuxamd64

### Terraform Configuration Files

```hcl
data "azurerm_client_config" "current" {}

resource "azurerm_role_assignment" "appconf_dataowner" {
  scope                = azurerm_app_configuration.default.id
  role_definition_name = "App Configuration Data Owner"
  principal_id         = data.azurerm_client_config.current.object_id
}
```

### Debug Output/Panic Output

```shell
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create
 <= read (data resources)

Terraform will perform the following actions:

  # module.core_app_configuration.azurerm_role_assignment.appconf_dataowner will be created
  + resource "azurerm_role_assignment" "appconf_dataowner" {
      + id                               = (known after apply)
      + name                             = (known after apply)
      + principal_id                     = "04b07795-8ddb-461a-bbee-02f9e1bf7b46"
      + principal_type                   = (known after apply)
      + role_definition_id               = "/subscriptions/9c2412c7-d8d9-40ff-9fa1-a2827388f0e0/providers/Microsoft.Authorization/roleDefinitions/5ae67dd6-50cb-40e7-96ff-dc2bfa4b606b"
      + role_definition_name             = (known after apply)
      + scope                            = "/subscriptions/9c2412c7-d8d9-40ff-9fa1-a2827388f0e0/resourceGroups/bancx-core-rg-dev/providers/Microsoft.AppConfiguration/configurationStores/bancx-core-app-configs"
      + skip_service_principal_aad_check = (known after apply)
    }



module.core_app_configuration.azurerm_role_assignment.appconf_dataowner: Still creating... [30m0s elapsed]
╷
│ Error: authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="PrincipalNotFound" Message="Principal 04b077958ddb461abbee02f9e1bf7b46 does not exist in the directory a95ee07a-efa5-4fc0-9e41-b6522df67ecd. Check that you have the correct principal ID. If you are creating this principal and then immediately assigning a role, this error might be related to a replication delay. In this case, set the role assignment principalType property to a value, such as ServicePrincipal, User, or Group.  See https://aka.ms/docs-principaltype"
│ 
│   with module.core_app_configuration.azurerm_role_assignment.appconf_dataowner,
│   on modules/app-configuration/role-assignment.tf line 11, in resource "azurerm_role_assignment" "appconf_dataowner":
│   11: resource "azurerm_role_assignment" "appconf_dataowner" {
│ 
╵
```

### Expected Behaviour

Should assign role 

### Actual Behaviour

throwing out error

### Steps to Reproduce

1. terraform init
2. terraform plan
3. terraform apply -auto-approve

**Comment by liuwuliuyun** [comment] 2023-01-12 02:56
Hi @nani2ratna, thanks for raising this issue. I have tried following config with the same provider version and it works fine. The object_id is also in the same format as yours with dashes. So, I am guessing your principal id could be changed and does not exist in remote. You could check whether the id is the same by portal, like https://cloudsight.zendesk.com/hc/en-us/articles/360016785598-Azure-finding-your-service-principal-object-ID.

```
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "2.99.0"
    }
  }
}

provider "azurerm" {
  features {
  }
}

data "azurerm_subscription" "primary" {
}

data "azurerm_client_config" "example" {
}

resource "azurerm_role_assignment" "example" {
  scope                = data.azurerm_subscription.primary.id
  role_definition_name = "Reader"
  principal_id         = data.azurerm_client_config.example.object_id
}
```

**Comment by manicminer** [comment] 2023-01-30 14:37
Thanks for reporting this @nani2ratna. I believe the absence of dashes in the error message is just semantic and doesn't reflect the value Terraform is sending. I'm not sure what the cause of the message would be in this case, since there are no known bugs with the `azurerm_client_config` data source implementation, but it's possible this is just a transient service error. As we've not yet heard back from you regarding this, I'm going to assume this issue cleared itself up and will close this issue. If however you're still experiencing this error, please reply, posting a debug log if possible, and someone will be happy to investigate further. Thanks!

**Closed by manicminer** 2023-01-30 14:37 UTC
