### ISSUE TITLE
Support for Azure Database for MySQL flexible server Auto scale IOPS

### ISSUE THREAD

**Issue by thomeu** [hashicorp/terraform-provider-azurerm#19424] opened 2022-11-24 11:02 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Autoscale IOPS is one new feature we are adding to Azure Database for MySQL – Flexible Server as part of our continuous work to provide customers with a MySQL server tuned readily with an optimal and cost-effective out-of-the-box performance.

### New or Affected Resource(s)/Data Source(s)

azurerm_mysql_flexible_server

### References

https://techcommunity.microsoft.com/t5/azure-database-for-mysql-blog/announcing-autoscale-iops-public-preview-for-azure-database-for/ba-p/3649089

**Comment by aristosvo** [comment] 2022-11-24 16:50
Hi @thomeu 👋 

This seems a duplicate of #19125, as such I'll close it for now.

**Closed** 2022-11-24 16:51 UTC
