### ISSUE TITLE
Support for file content instead of source file path in azurerm_storage_share_file

### ISSUE THREAD

**Issue by hterik** [hashicorp/terraform-provider-azurerm#13376] opened 2021-09-16 08:14 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

azurerm_storage_share_file only allows the source-file to be upload to be specified as a file path in the [source](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_share_file#source)-attribute:  

For some use cases the contents of the file need to be generated dynamically (for example using **templatefile**), it would be more flexibile if the raw content to upload could be specified instead of the path. Terraform provides the [file](https://www.terraform.io/docs/language/functions/file.html) function to read contents from a path making both use cases equally easy.

Today the only way to insert dynamic content is to use a tempfile workaround. Which is not 100% supported by the terraform, see https://github.com/hashicorp/terraform/issues/17008#issuecomment-920222911 and https://github.com/hashicorp/terraform/issues/21308. The recommendation there is that all providers prefer data over path on such attributes.

### New or Affected Resource(s)

* azurerm_storage_share_file

**Comment by tombuildsstuff** [comment] 2021-09-16 08:16
hi @hterik 

Thanks for opening this issue

Taking a look through this appears to be a duplicate of #9927 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #9927 for updates?

Thanks!

**Closed by tombuildsstuff** 2021-09-16 08:16 UTC
Labels: duplicate, enhancement, service/storage
