### ISSUE TITLE
two runs needed to add new app service to AD group

### ISSUE THREAD

**Issue by fgarcia-cnb** [hashicorp/terraform-provider-azurerm#21632] opened 2023-05-03 00:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.0.7

### AzureRM Provider Version

3.50.0

### Affected Resource(s)/Data Source(s)

azurerm_linux_web_app, azurerm_windows_web_app

### Terraform Configuration Files

We have a module that builds app services for linux and windows. the relevant outputs look like this:
```hcl
output "webapp_ids" {
  value = var.is_linux ? azurerm_linux_web_app.webapp_linux[*].id : azurerm_windows_web_app.webapp_windows[*].id
}

output "webapp_managed_identities" {
  value = var.is_linux ? azurerm_linux_web_app.webapp_linux[*].identity[0].principal_id : azurerm_windows_web_app.webapp_windows[*].identity[0].principal_id
}
```
These outputs are fed into another module with azuread_group resources (using `var.object_ids`):
```hcl
resource "azuread_group" "group" {
  count            = var.resource_count > 0 ? 1 : 0
  display_name     = "g_${var.location}-${var.environment}${var.env_suffix}-${var.appname}-${var.name_suffix}"
  members          = var.object_ids
  security_enabled = true
}
```
### Debug Output/Panic Output

```shell
n/a
```

### Expected Behaviour

when an additional app service is created with count, terraform should know the output of the module will change, and thus the group members of the AD group will also change. 

### Actual Behaviour

the additional app service creation and adding it to the ad_group member should all happen within 1 run, but it takes 2 runs... the first run creates the app service, and the AD group wont see the generated principal id until the second run

am i misunderstanding something?

**Comment by fgarcia-cnb** [comment] 2023-05-03 00:21
is this related to https://github.com/hashicorp/terraform-provider-azurerm/issues/13490 ??

**Comment by xiaxyi** [comment] 2023-05-05 03:27
Thanks @fgarcia-cnb for raising this issue, may I know if you are able to output the app service identity information using below example:
```
output "appservice-msi" {
    value = azurerm_linux_web_app.noauth.identity[0].principal_id
}
```

**Comment by xiaxyi** [comment] 2023-05-05 05:22
> is this related to #13490 ??

The issue is about managed identity not being recognized by kv access policy if the msi is not enabled during the resource creation. 

As I can tell, you enabled the managed identity during creation. am I correct?

**Comment by fgarcia-cnb** [comment] 2023-05-05 05:49
well its a bit similar. you are correct, the managed identitiy is being created at web app creation. the principal id is an output of the module. that output is fed into the azuread_group members parameter, but it doesnt happen on the run it that creates the app service. its not added until the second run.

```hcl
resource "azurerm_linux_web_app" "webapp_linux" {
  count               = var.is_linux ? var.webapp_count : 0
  name                = "${var.group_prefix}webapp${count.index}"
  resource_group_name = var.resource_group_name

  location = local.region[var.location]
  tags     = local.tags

  client_certificate_mode = var.webapp_client_cert_mode
  https_only              = var.webapp_https_only
  service_plan_id         = var.app_service_plan_id

  app_settings = merge({
    "WEBSITE_VNET_ROUTE_ALL" = "1"
  }, var.additional_webapp_settings)

  identity {
    type = "SystemAssigned"
  }

  site_config {
    always_on              = var.webapp_always_on
    vnet_route_all_enabled = true
    ftps_state             = "FtpsOnly"
    http2_enabled          = true
  }

  lifecycle {
    ignore_changes = [
      app_settings,
      auth_settings,
      backup,
      client_affinity_enabled,
      client_certificate_enabled,
      connection_string,
      site_config,
      sticky_settings,
      virtual_network_subnet_id,
    ]
  }
}

output "webapp_managed_identities" {
  value = var.is_linux ? azurerm_linux_web_app.webapp_linux[*].identity[0].principal_id : azurerm_windows_web_app.webapp_windows[*].identity[0].principal_id
}
```

**Comment by fgarcia-cnb** [comment] 2023-05-05 06:09
maybe its related to this? https://github.com/hashicorp/terraform-provider-azuread/issues/431

**Comment by xiaxyi** [comment] 2023-05-05 06:35
@fgarcia-cnb I'm not sure about the current behavior of the inconsistence of the azure ad graph api given the issue was opened 2 years ago...

I tried to reproduce the issue from my side, unfortunately, I can't get the same result. Everything works fine from my end, the only difference is I didn't use module but just the simplest RP block.

```
resource "azurerm_linux_web_app" "noauth" {
  name = "tftestlwa-msi-733"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  service_plan_id = azurerm_service_plan.linux.id
  https_only = true
  
  site_config {}

  identity {
    type = "SystemAssigned"
  }
}


resource "azuread_group" "group" {
  display_name             = "${azurerm_linux_web_app.noauth.name}-group"
  security_enabled = true
  
  members = [
    azurerm_linux_web_app.noauth.identity[0].principal_id,
  ]
}

```

The member is added successfully to the azure ad group.

One thing I do noticed is that you are using `name` instead of `display_name` in `azuread_group`. https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/group#display_name

Can you get the config ran successfully by using an undefined property as I was getting this error:
![image](https://user-images.githubusercontent.com/92154856/236391172-1920fb15-8e9f-48e5-8bac-7ae1e18cbf10.png)

**Comment by fgarcia-cnb** [comment] 2023-05-05 06:52
yea sorry i accidentally used outdated code... display_name is the correct parameter. i fixed the code in my comments above. could you try a cooue more things for me?

-add a count to the app service. then go from 1->2. does the AD group update correctly?
-if that works, would you mind putthing your code in modules? and then rebuild, and go from 1->2 again

**Comment by xiaxyi** [comment] 2023-05-05 07:03
How did you pass the object_id to azuread_group?

```
resource "azuread_group" "group" {
  count            = var.resource_count > 0 ? 1 : 0
  display_name     = "g_${var.location}-${var.environment}${var.env_suffix}-${var.appname}-${var.name_suffix}"
  members          = var.object_ids
  security_enabled = true
}
```

**Comment by fgarcia-cnb** [comment] 2023-05-05 07:12
its in my code above... adding here again (the object_ids parameter):

```hcl
module "webapp_msigroup" {
  source         = "localterraform.com/bats/aadgroup/azurerm"
  version        = "~> 4.0.0"
  resource_count = var.webapp_count > 0 ? 1 : 0
  location       = var.location
  environment    = var.environment
  env_suffix     = var.env_suffix
  appname        = var.appname
  name_suffix    = "webapp-msi"
  object_ids     = module.webapp.webapp_managed_identities

###module content
resource "azuread_group" "group" {
  count            = var.resource_count > 0 ? 1 : 0
  display_name     = "g_${var.location}-${var.environment}${var.env_suffix}-${var.appname}-${var.name_suffix}"
  members          = var.object_ids
  security_enabled = true
}
'''

**Comment by xiaxyi** [comment] 2023-05-05 07:29
the app services are added to the member list as expected, even i set the count to 5...

I noticed that you mentioned "When i increase the web app count from 5->6 i see the following resources being added, but no changes to the azure AD group until i apply and do a 2nd plan"

are you suggesting that it worked if the web app count is 2？

**Comment by fgarcia-cnb** [comment] 2023-05-05 08:22
after a lot of testing, i found the issue. i previously cleaned up my posted code for simplicity, but i ended up accidentally removing the cause of the issue. i was actually passing the following to the ad group module:
```hcl
object_ids     = compact(concat(module.webapp.webapp_managed_identities, data.azuread_group.dr_webapp_msigroup[*].id))
```
for some reason, the compact function prevents changes. so in your example, try this:
```hcl
members          = compact(concat(azurerm_linux_web_app.noauth[*].identity[0].principal_id, []))
```
youll see the behavior im describing then increasing the web app count. if you remove compact and use
```hcl
members          = concat(azurerm_linux_web_app.noauth[*].identity[0].principal_id, [])
```
everything works again. can you confirm this bevavior?

**Comment by fgarcia-cnb** [comment] 2023-05-05 08:45
the bottom half of this [post ](https://github.com/hashicorp/terraform/issues/29799#issuecomment-951001994) describes the behavior of compact on "known after apply" values.

**Comment by xiaxyi** [comment] 2023-05-05 08:52
Ah, if I use compact function, I can reproduce the issue....

**Comment by xiaxyi** [comment] 2023-05-05 08:53
maybe we can use foreach, for example:
```
locals {
    webapp_managed_identities = azurerm_linux_web_app.noauth[*].identity[0].principal_id
}

resource "azuread_group" "group" {
  display_name             = "lwa-group"
  security_enabled = true

  //members = compact(concat(azurerm_linux_web_app.noauth[*].identity[0].principal_id, []))

  members = [for i in local.webapp_managed_identities : i] 
}
```

**Comment by fgarcia-cnb** [comment] 2023-05-05 16:14
i just removed compact... its not really necessary, it was just precautionary. thanks for the help. this ticket can be closed

**Comment by xiaxyi** [comment] 2023-05-06 01:33
No problems @fgarcia-cnb , glad to see the issue is resolved. Would you mind closing this issue from your side? Thanks!

**Closed** 2023-05-06 01:37 UTC
