### ISSUE TITLE
Support for existing os disk virtual machine

### ISSUE THREAD

**Issue by cveld** [hashicorp/terraform-provider-azurerm#22842] opened 2023-08-07 10:12 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

We would like to be able to import an existing os disk. Today this is not possible with the `azurerm_linux_virtual_machine` and `azurerm_windows_virtual_machine` resources.

### New or Affected Resource(s)/Data Source(s)

azurerm_linux_virtual_machine, azurerm_windows_virtual_machine

### Potential Terraform Configuration

```hcl
os_disk {
    name = "osdisk"
    #create_option = "FromImage"
    create_option   = "Attach"
    managed_disk_id = data.azurerm_managed_disk.source.id
}
```

**Comment by tombuildsstuff** [comment] 2023-08-07 10:23
hi @cveld 

Thanks for opening this issue.

Taking a look through this appears to be a duplicate of #8794 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #8794 for updates?

Thanks!

**Closed by tombuildsstuff** 2023-08-07 10:23 UTC
Labels: duplicate, service/virtual-machine

**Comment by etaham** [comment] 2023-08-16 18:38
@tombuildsstuff This is a little different that #8794 - That item is asking to import into an embedded disk inside the Linux/Windows_virtual_machine. This is focus on an attach option to an independent disk serving as the OK disk. This would cover my teams' needs - the import is not important.
