### ISSUE TITLE
azurerm_databricks_workspace failed to set storage_account_sku_name = "Standard_ZRS"

### ISSUE THREAD

**Issue by isasnovich** [hashicorp/terraform-provider-azurerm#20440] opened 2023-02-13 17:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.0

### AzureRM Provider Version

3.31.0

### Affected Resource(s)/Data Source(s)

azurerm_databricks_workspace

### Terraform Configuration Files

```hcl
resource "azurerm_databricks_workspace" "databricks_ws" {
  name                        = "test-sku"
  resource_group_name         = azurerm_resource_group.databricks_rg.name
  location                    = "eastus2"
  sku                         = "premium"
  managed_resource_group_name = "test"
  custom_parameters {
    storage_account_sku_name = "Standard_ZRS"
  }
}
```

### Debug Output/Panic Output

```shell
azurerm_databricks_workspace.databricks_ws: Creating...
azurerm_databricks_workspace.databricks_ws: Still creating... [10s elapsed]
azurerm_databricks_workspace.databricks_ws: Still creating... [20s elapsed]
azurerm_databricks_workspace.databricks_ws: Still creating... [30s elapsed]
azurerm_databricks_workspace.databricks_ws: Still creating... [40s elapsed]
azurerm_databricks_workspace.databricks_ws: Still creating... [50s elapsed]
azurerm_databricks_workspace.databricks_ws: Still creating... [1m0s elapsed]
azurerm_databricks_workspace.databricks_ws: Still creating... [1m10s elapsed]
azurerm_databricks_workspace.databricks_ws: Still creating... [1m20s elapsed]
azurerm_databricks_workspace.databricks_ws: Still creating... [1m30s elapsed]
azurerm_databricks_workspace.databricks_ws: Creation complete after 1m35s
```

### Expected Behaviour

Create databricks resource with storage_account_sku_name = "Standard_ZRS"

### Actual Behaviour

Resource created in terraform but not working in azure 

 
![image](https://user-images.githubusercontent.com/55707707/218524613-113f6074-41d1-4e61-85ae-2113d1353c4a.png)

"{\"status\":\"Failed\",\"error\":{\"code\":\"ResourceOperationFailure\",\"message\":\"The resource operation completed with terminal provisioning state 'Failed'.\",\"details\":[{\"code\":\"ApplianceDeploymentFailed\",\"message\":\"The operation to create appliance failed. Please check operations of deployment 'igorstest-adb123' under resource group '/subscriptions/8095de8a-6abb-445c-b400-47519fe7865e/resourceGroups/igorstest-adb-manage123'. Error message: 'At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.'\",\"details\":[{\"code\":\"BadRequest\",\"message\":\"{\\r\\n  \\\"error\\\": {\\r\\n    \\\"code\\\": \\\"InvalidValuesForRequestParameters\\\",\\r\\n    \\\"message\\\": \\\"Values for request parameters are invalid: kind, sku. For more information, see - https://aka.ms/storageaccounttypes\\\"\\r\\n  }\\r\\n}\"}]}]}}

**Comment by isasnovich** [comment] 2023-02-13 17:17
only Standard_LRS is working.

**Comment by WodansSon** [comment] 2023-02-14 23:09
@isasnovich, thank you for opening this issue! This is currently by design as the `Standard_ZRS` sku is not supported by the service. 

The supported `storage_account_sku_name` values are:

* `Standard_LRS`
* `Standard_GRS`
* `Standard_RAGRS`

I believe the service team is planning to add support for the `Standard_ZRS` sku in the near future, but as of right now, the only supported `storage_account_sku_name` values are as listed above. Since this behavior is currently by design I am going to go ahead and close this issue. Thanks again and I hope you find this helpful! 🚀

**Closed by WodansSon** 2023-02-14 23:09 UTC
Labels: question, service/databricks
