### ISSUE TITLE
azurerm_policy_assignment for "Configure backup on VMs..." | Empty Parameter - Backup Policy

### ISSUE THREAD

**Issue by Geartrixy** [hashicorp/terraform-provider-azurerm#6829] opened 2020-05-08 14:08 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.23
+ provider.azurerm v2.8.0

### Affected Resource(s)

* `azurerm_policy_assignment`

### Terraform Configuration Files

```hcl
resource "azurerm_policy_assignment" "blah" {
  name     = "blah"
  scope                = "/subscriptions/12345678-1234-1234-1234-12345678901"
  policy_definition_id = "/providers/Microsoft.Authorization/policyDefinitions/09ce66bc-1220-4153-8104-e3f51c936913"
  display_name = "blah - Configure backup on VMs of a location to an existing central Vault in the same location"
  location     = "westeurope"
  not_scopes   = []
  identity {
    type = "SystemAssigned"
  }

  parameters = <<PARAMETERS
{
  "vaultLocation": {
      "value": "westeurope"
  },
  "backupPolicyId" : {
          "value": "/subscriptions/12345678-1234-1234-1234-12345678901/resourcegroups/rg-my-vault/providers/microsoft.recoveryservices/vaults/my-vault/backuppolicies/default-vm"
  },
  "effect" : {
      "value" : "deployIfNotExists"
  }

}
PARAMETERS
}
```

### Expected Behavior

The assignment happens successfully.

### Actual Behavior

Under parameters the "Backup Policy" section remains empty...

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

If the backup policy is then selected within the portal manually (subscription + recovery services vault + recovery services backup policy) and saved. And terraform apply run again, there are no changes required.

### References

* #0000

**Comment by ArcturusZhang** [comment] 2020-05-11 06:29
Hi @Geartrixy thanks for the issue!
Given the natural of this issue, it would be not quite applicable for me to exactly reproduce this (it relates with another resource). But could you please post the log of the problematic log during the apply? And probably the `terraform.state` after that apply. Thanks a lot!

**Comment by ArcturusZhang** [comment] 2020-05-12 05:17
Hi @Geartrixy I just checked the definition of policy `/providers/Microsoft.Authorization/policyDefinitions/09ce66bc-1220-4153-8104-e3f51c936913`, it has a strong type of `Microsoft.RecoveryServices/vaults/backupPolicies`. I am not quite sure whether the backup policy IDs are case-sensitive or not, could you please try making your backupPolicyId value with proper casing like this?
```
/subscriptions/<SubscriptionId>/resourceGroups/<resourceGroupName>/providers
/Microsoft.RecoveryServices/vaults/<VaultName>/backupPolicies/<BackupPolicyName>
```

**Comment by Geartrixy** [comment] 2020-05-12 09:26
Hi @ArcturusZhang ,

I changed the backup policy ID to the following (sub ID is amended to a dummy for posting):

`/subscriptions/12345678-1234-1234-1234-12345678901/resourceGroups/rg-my-vault/providers/Microsoft.RecoveryServices/vaults/my-vault/backupPolicies/default-vm`

But the outcome is the same:
![image](https://user-images.githubusercontent.com/29755594/81667110-2b654c00-9443-11ea-970c-6827e2243d4f.png)

I will try and replicate the issue in a sandbox subscription later so I can post some logs for you.

Thanks for the fast replies
Geartrixy

**Comment by ArcturusZhang** [comment] 2020-05-13 03:44
Sure, thanks!
And I am suspecting this may relates with #6843 about the api-version of policy SDK terraform is using. In the new version of SDK, the service team slightly changed there body structure. This may be related, and may be the root cause (but I am not sure about this, only a hypothesis).

**Comment by Geartrixy** [comment] 2020-05-17 18:36
Hi  @ArcturusZhang ,

https://gist.github.com/Geartrixy/9b29e84fbd215b1583d62f9e9d21acea

I guess this line indicates the issue:

`2020/05/17 20:28:30 [WARN] Provider "registry.terraform.io/-/azurerm" produced an unexpected new value for azurerm_policy_assignment.gg_test, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .description: was null, but now cty.StringVal("")
      - .parameters: was cty.StringVal("{\r\n  \"vaultLocation\": {\r\n      \"value\": \"westeurope\"\r\n  },\r\n  \"backupPolicyId\" : {\r\n          \"value\": \"/subscriptions/979c0fb2-aab9-4e1a-b3aa-7b471302847d/resourceGroups/auto-test-gg/providers/Microsoft.RecoveryServices/vaults/my-vault/backupPolicies/default-vm\"\r\n  },\r\n  \"effect\" : {\r\n      \"value\" : \"deployIfNotExists\"\r\n  }\r\n\r\n}\r\n"), but now cty.StringVal("{\"backupPolicyId\":{\"value\":\"/subscriptions/979c0fb2-aab9-4e1a-b3aa-7b471302847d/resourceGroups/auto-test-gg/providers/Microsoft.RecoveryServices/vaults/my-vault/backupPolicies/default-vm\"},\"effect\":{\"value\":\"deployIfNotExists\"},\"vaultLocation\":{\"value\":\"westeurope\"}}")
`

**Comment by ArcturusZhang** [comment] 2020-05-18 08:20
Hi @Geartrixy thanks for the follow up!
But I suppose this part may not be the root cause...Based on your state file, `backupPolicyId` in the `parameters` attribute should be properly returned by the service itself... and now the problem should be the parameters are not taking effect...

Thanks again for the provided details! I will take some time to try to reproduce this and probably finally find the root cause of this.

**Comment by Geartrixy** [comment] 2020-08-12 06:02
Hi @ArcturusZhang 

did you manage to make any progress here? :)

Thanks!

**Comment by ArcturusZhang** [comment] 2020-08-12 06:36
Hi @Geartrixy sorry for the delay. I just had another try of this using the following script:
```
provider "azurerm" {
  features {}
  version = ">=2.14.0"
}

data "azurerm_subscription" "current" {
}

resource "azurerm_resource_group" "example" {
  name = "test-policy"
  location = "westeurope"
}

resource "azurerm_recovery_services_vault" "example" {
  name                = "tfex-recovery-vault"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  sku                 = "Standard"
}

resource "azurerm_backup_policy_vm" "example" {
  name                = "tfex-recovery-vault-policy"
  resource_group_name = azurerm_resource_group.example.name
  recovery_vault_name = azurerm_recovery_services_vault.example.name

  timezone = "UTC"

  backup {
    frequency = "Daily"
    time      = "23:00"
  }

  retention_daily {
    count = 10
  }

  retention_weekly {
    count    = 42
    weekdays = ["Sunday", "Wednesday", "Friday", "Saturday"]
  }

  retention_monthly {
    count    = 7
    weekdays = ["Sunday", "Wednesday"]
    weeks    = ["First", "Last"]
  }

  retention_yearly {
    count    = 77
    weekdays = ["Sunday"]
    weeks    = ["Last"]
    months   = ["January"]
  }
}

resource "azurerm_policy_assignment" "test" {
  name     = "test-assignment"
  scope                = data.azurerm_subscription.current.id
  policy_definition_id = "/providers/Microsoft.Authorization/policyDefinitions/09ce66bc-1220-4153-8104-e3f51c936913"
  display_name = "blah - Configure backup on VMs of a location to an existing central Vault in the same location"
  location     = azurerm_resource_group.example.location
  not_scopes   = []
  identity {
    type = "SystemAssigned"
  }

  parameters = <<PARAMETERS
{
  "vaultLocation": {
    "value": "westeurope"
  },
  "backupPolicyId" : {
    "value": "${azurerm_backup_policy_vm.example.id}"
  },
  "effect" : {
    "value" : "deployIfNotExists"
  }
}
PARAMETERS
}
```
Terraform apply succeeded and then a plan shows no diff. The backupPolicyID shows up in the state file. But still, the portal shows nothing:
![image](https://user-images.githubusercontent.com/10554446/89982437-4d6fa400-dca8-11ea-9ff8-d50c668e4215.png)

This should be a firm proof that even if there is a problem, it is not in this provider.
Here I have some assumptions.
1. It could be an issue with this policy definition
1. It could be an issue with policy assignment - it is not properly propagate the `backupPolicyId` parameter
1. It could be an issue with azure portal - it is not properly read the value in the parameters.

I will mark this issue `upstream-microsoft` since this should be an issue from Azure itself.

**Comment by ArcturusZhang** [comment] 2020-08-12 06:42
Upstream issue created: https://github.com/Azure/azure-rest-api-specs/issues/10435
=

**Comment by Geartrixy** [comment] 2020-08-12 06:49
Hi @ArcturusZhang ,

appreciate the fast reply and thanks for following up on the issue!

Hopefully we will get some information on the issue soon from them 🤞 

Kind regards

**Comment by ArcturusZhang** [comment] 2020-08-13 06:20
Hi @Geartrixy the service team has some follow up in the upstream issue, could you please also take a look there?

**Comment by ArcturusZhang** [comment] 2020-10-10 08:43
Hi @Geartrixy the service team is suggesting that we should open a support ticket on the portal, since this is only an UI issue on the portal (see the conversations [here](https://github.com/Azure/azure-rest-api-specs/issues/10435)), could you please have a try?

As for the functionality reported in this issue should be fine, therefore I suggest we could close this issue.

**Comment by Geartrixy** [comment] 2021-01-26 11:11
Hi @ArcturusZhang ,

thank you very much for investigating further and linking the issue to azure-rest-api-specs .

Could you provide a link where I can open a support ticket for the portal?

Thanks!

**Comment by ArcturusZhang** [comment] 2021-01-27 08:19
Hi @Geartrixy There is an Azure Support Ticket entry on the up right corner of Azure Portal where you could open an Azure support ticket.

**Comment by favoretti** [comment] 2021-08-19 13:01
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.

**Closed by favoretti** 2021-08-19 13:01 UTC
Labels: question, service/policy
