### ISSUE TITLE
azurerm_storage_account nfs produced an unexpected new value: Root resource was present, but now absent.

### ISSUE THREAD

**Issue by FreddyAyala** [hashicorp/terraform-provider-azurerm#13922] opened 2021-10-27 13:29 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.0.9
on windows_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.7.0
+ provider registry.terraform.io/hashicorp/azurerm v2.81.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

### Affected Resource(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "nfs" {
  name                      = "snfs${random_string.random.result}nfs"
  resource_group_name       = azurerm_resource_group.cyclecloud.name
  location                  =  azurerm_resource_group.cyclecloud.location
  account_tier              = "Standard"
  account_kind              = "StorageV2"
  account_replication_type  = "LRS"
  is_hns_enabled            = true
  nfsv3_enabled             = true
  enable_https_traffic_only = false
  network_rules {
    default_action             = "Deny"
    virtual_network_subnet_ids = [azurerm_subnet.cyclecloud.id]
  }
  depends_on =[azurerm_windows_virtual_machine.front]
}
```

### Debug Output

azurerm_storage_account.nfs: Still creating... [10s elapsed]
azurerm_storage_account.nfs: Still creating... [20s elapsed]
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to azurerm_storage_account.nfs, provider "provider[\"registry.terraform.io/hashicorp/azurerm\"]" produced an unexpected new value: Root resource was present, but now absent.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
### Expected Behaviour

Terraform apply should have been successful

### Actual Behaviour

Terraform apply fails

### Steps to Reproduce

Happens all the time

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment] 2021-11-26 01:01
Duplicate of #5299 - please subscribe to that issue for updates.

**Closed by tombuildsstuff** 2021-11-26 01:01 UTC
Labels: bug, service/storage
