### ISSUE TITLE
Support to reference named values into backend in Terraform

### ISSUE THREAD

**Issue by charlesb87** [hashicorp/terraform-provider-azurerm#14557] opened 2021-12-09 09:40 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In Azure APIM we can't reference named value into APIM Backend to have more dynamic management of secrets inside Azure APIM Backend: As of today, we can only reference secrets as plain parameter into Credentials block.

### New or Affected Resource(s)

* azurerm_api_management_named_value
* azurerm_api_management_backend

**Comment by stephybun** [comment] 2021-12-13 09:09
I'm going to close this since it is a duplicate of #14575. Would you mind subscribing to that issue for updates?

Thanks!

**Closed by stephybun** 2021-12-13 09:09 UTC
Labels: duplicate, enhancement, service/api-management
