### ISSUE TITLE
`azurerm_log_analytics_workspace` changes its `workspace_id` constantly after bump to 3.40

### ISSUE THREAD

**Issue by mkemmerz** [hashicorp/terraform-provider-azurerm#20278] opened 2023-02-02 15:12 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.7

### AzureRM Provider Version

3.40.0

### Affected Resource(s)/Data Source(s)

azurerm_application_insights, azurerm_log_analytics_workspace

### Terraform Configuration Files

```hcl
resource "azurerm_application_insights" "application_insights" {
  name                = var.application_insights_name
  location            = var.location
  resource_group_name = data.azurerm_resource_group.resource_group.name
  workspace_id        = data.azurerm_log_analytics_workspace.log_analytics_workspace.id
  application_type    = var.application_type


}
```

### Debug Output/Panic Output

```shell
Resource is recreated on each terraform apply.
```

### Expected Behaviour

The resource is either not changed or updated on changes. 

### Actual Behaviour

The workspace_id of the Log Analytics Workspace is noticed as changed. This leads to a recreation of Diagnostic Settings and Application Insights on each terraform apply because `workspace_id` enforces a replacement.

This issue occurs in 3.40.0 and above for us. 
This issue is **not** happening in 3.38.0.

We don't create a new Log Analytics but the App Insights is still recreated:

![image](https://user-images.githubusercontent.com/46575727/216365278-cdb2bd91-a916-48f1-a0f0-9aac91343f97.png)

**Comment by jiaweitao001** [comment] 2023-02-03 08:18
Hi @mkemmerz , thanks for opening the issue. Could you please paste some more context code here for diagnoses? I created a new `azurerm_log_analytics_workspace` with a `azurerm_application_insights' in one TF file and `terraform apply` a few times this did not occur.

**Comment by mkemmerz** [comment] 2023-02-03 13:45
It doesn't seem to be any kind of bug but rather how terraform behaves.

Quickly explaining our issue:
We have two terraform modules. Module 1 creates the Log Analytics Workspace. Module 2 create the Application Insights and uses a data import for the Log Analytics Workspace (by name + resource group) created by Module 1.

Our issue was fixed by replacing the data import of the Log Analytics Workspace by using the ID directly instead of referencing it from the data import.

The data import of the Log Analytics Workspace (somehow?) changed between v3.35 and 3.40. Maybe you know what has changed @jiaweitao001 ?

Do you want me to keep this issue open or want me to close it?

**Comment by manicminer** [comment] 2023-02-05 00:47
Thanks for reporting back @mkemmerz. As it seems like you have resolved your issue, or at least gotten to the cause in your configuration, I'll close this one for now. But if I have misread this, or the circumstances otherwise change, please feel free to comment further and we'll be happy to take another look.

**Closed by manicminer** 2023-02-05 00:47 UTC
Labels: question, service/log-analytics
