### ISSUE TITLE
Load balancer is not settings ipv4 at state file

### ISSUE THREAD

**Issue by eladmotola** [hashicorp/terraform-provider-azurerm#12801] opened 2021-08-01 20:16 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
terraform 1.0.1
azurerm - 2.65.0

### Affected Resource(s)

* `azurerm_lb`

### Terraform Configuration Files

```hcl
resource "azurerm_lb" "loadbalancer" {
  name                = "name"
  location            = var.location
  resource_group_name = var.rg_name

  frontend_ip_configuration {
    name                       = "PublicIPAddress"
    public_ip_address_id       = module.public_ip.id
    private_ip_address_version = "IPv4"
  }
}
```

### Expected Behaviour
state file should save private_ip_address_version    = "IPv4" but its not happening

### Actual Behaviour
```
~ frontend_ip_configuration {
            id                            = "id"
            name                          = "PublicIPAddress"
          + private_ip_address_version    = "IPv4"
            # (7 unchanged attributes hidden)
        }
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by heoelri** [comment] 2021-08-05 08:16
@eladmotola based on what i've seen in the code does `private_ip_address_version` require `subnet_id` to be set.

`azurerm/internal/services/loadbalancer/loadbalancer_resource.go` in [line 386-395](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/loadbalancer/loadbalancer_resource.go#L386)
```go
if v := data["subnet_id"].(string); v != "" {
	subnetSet = true
	properties.PrivateIPAddressVersion = network.IPVersionIPv4
	if v := data["private_ip_address_version"].(string); v != "" {
		properties.PrivateIPAddressVersion = network.IPVersion(v)
	}
	properties.Subnet = &network.Subnet{
		ID: &v,
	}
}
```

I've verified that and it successfully saves the value of `private_ip_address_version` when `subnet_id` is set. It also does not make much sense to combine `private_ip_address_version` with `public_ip_address_id` in the load balancer's `frontend_ip_configuration` as a load balancer in Azure has either a public OR private/internal front end.

**Comment by eladmotola** [comment] 2021-08-05 13:05
Hey @heoelri ,
Without  `private_ip_address_version` its happens anyway, so sorry not to mention it. i just added this value to force solving the problem. so its sound like a bug to me...

**Comment by heoelri** [comment] 2021-08-06 07:30
@eladmotola I'm sorry I don't understand. I was refering to your description above:

```
state file should save private_ip_address_version = "IPv4" but its not happening
```

In my tests this works fine when `subnet_id` is set to `true`.

```hcl
resource "azurerm_lb" "loadbalancer" {
  [..]
  frontend_ip_configuration {
    name                       = "PrivateFrontend"
    private_ip_address_version = "IPv4"

    subnet_id = azurerm_subnet.example.id
  }
}
```

I've also tested the other way around with a public ip address instead:

```hcl
resource "azurerm_lb" "loadbalancer" {
  [..]
  frontend_ip_configuration {
    name                       = "ExternalFrontend"
    public_ip_address_id       = azurerm_public_ip.example.id
  }
}
```
In both cases does the second apply report that "Objects have changed outside of Terraform":

```console
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":
```

But all the subsequent ones work fine and do not report any issues and are not trying to re-set the `private_ip_address_version` would you mind sharing a few more details? I'd love to understand the issue better.

**Comment by eladmotola** [comment] 2021-08-08 20:34
Hey @heoelri,
To provide a minimum reproduction of the problem, just copy and paste the example ( I took it from the docs):
```
resource "azurerm_lb" "example" {
  name                = "TestLoadBalancer"
  location            = "West US"
  resource_group_name = azurerm_resource_group.example.name

  frontend_ip_configuration {
    name                 = "PublicIPAddress"
    public_ip_address_id = azurerm_public_ip.example.id
  }
}
```

now when you will try to run `terraform plan` after you create the resource you will see the behavior that I mention above.
In order to fix the problem, I tried to add the attribute of `private_ip_address_version` without success (and now I understand that what i did is not a solution)

I hope it makes more sense

**Comment by kingsleyadam** [comment] 2021-08-10 09:41
I'm also running into this same issue. My resource is managed in a module with some dynamic variables, e.g. if boolean flag public is true.

See

```
  dynamic "frontend_ip_configuration" {
    for_each = each.value.front_end_configs
    content {
      name                          = frontend_ip_configuration.key
      subnet_id                     = each.value.public ? null : var.subnets[frontend_ip_configuration.value.subnet].id
      private_ip_address_allocation = each.value.public ? null : frontend_ip_configuration.value.private_ip_address_allocation
      private_ip_address_version    = "IPv4"
      public_ip_address_id          = each.value.public ? azurerm_public_ip.lb_public_ips[each.key].id : null
    }
  }
```

And also, because my block is dynamic, I can't just ignore the `private_ip_address_version` value. I can only ignore the entire `frontend_ip_configuration` which I don't really want to do.

This causes changes on every apply of my infrastructure.

**Comment by kingsleyadam** [comment] 2021-08-10 09:42
Looks like this duplicates #12396

**Comment by tombuildsstuff** [comment] 2021-08-10 10:26
Duplicate of #12396, thanks @kingsleyadam

**Closed by tombuildsstuff** 2021-08-10 10:26 UTC
Labels: service/load-balancers, upstream-microsoft
