### ISSUE TITLE
Images from a Shared Image Gallery is NOT available in the same manner as Platform Images

### ISSUE THREAD

**Issue by masonhuemmer** [hashicorp/terraform-provider-azurerm#15274] opened 2022-02-04 23:14 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I was told by @tombuildsstuff that "Deploying Images from a Shared Image Gallery is available in the same manner as Platform Images - and this functionality is already available in the Linux and Windows VM/VMSS resources."

However, I opened a ticket with Microsoft Support and am not able to get the same functionality. I am not able to pass in the source image reference to pull  down an image from the Shared Image Gallery. Microsoft Support told me to put in a ticket as they believed this to be an issue with the AzureRM provider, not Microsoft. 

I would like support or a fix so we can use the source image reference when pulling an image from a Shared Image Gallery.

### New or Affected Resource(s)

* azurerm_windows_virtual_machine
* azurerm_linux_virtual_machine
### Potential Terraform Configuration

```
provider "azurerm" {
  features {}
}


data "azurerm_shared_image" "example" {
  name                = "my-image"
  gallery_name        = "my-image-gallery"
  resource_group_name = "example-resources-imageRG"
}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "xxxxximageregion"
}

resource "azurerm_virtual_network" "example" {
  name                = "example-network"
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
}

resource "azurerm_subnet" "example" {
  name                 = "internal"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefixes     = ["10.0.2.0/24"]
}

resource "azurerm_network_interface" "example" {
  name                = "example-nic"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  ip_configuration {
    name                          = "internal"
    subnet_id                     = azurerm_subnet.example.id
    private_ip_address_allocation = "Dynamic"
  }
}

resource "azurerm_windows_virtual_machine" "example" {
  name                = "example-machine"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  size                = "Standard_F2"
  admin_username      = "adminuser"
  admin_password      = "P@$$w0rd1234!"
  network_interface_ids = [
    azurerm_network_interface.example.id,
  ]

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
  }

  source_image_reference {
    publisher = "<Private Compute Gallery Publisher>"
    offer     = "<Private Compute Gallery Offer>"
    sku       = "<Private Compute Gallery Sku>"
    version   = "<Private Compute Gallery Version>"
  }  
}
```

### References

* https://stackoverflow.com/questions/67178590/deploy-azure-vm-based-on-customize-image-available-on-shared-image-gallery
* https://github.com/hashicorp/terraform-provider-azurerm/issues/15255#issuecomment-1029806268

**Comment by tombuildsstuff** [comment] 2022-02-07 07:41
Duplicate of #15255, consolidating into that issue.

**Closed by tombuildsstuff** 2022-02-07 07:41 UTC
