### ISSUE TITLE
`azurerm_cdn_frontdoor_route` caching validation rules exclude valid MIME types

### ISSUE THREAD

**Issue by jared-koiter** [hashicorp/terraform-provider-azurerm#22938] opened 2023-08-14 17:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.3

### AzureRM Provider Version

3.66.0

### Affected Resource(s)/Data Source(s)

azurerm_cdn_frontdoor_route

### Terraform Configuration Files

```hcl
resource "azurerm_cdn_frontdoor_route" "example_route" {
  name                          = "example-route"
  cdn_frontdoor_endpoint_id     = azurerm_cdn_frontdoor_endpoint.example.id
  cdn_frontdoor_origin_group_id = azurerm_cdn_frontdoor_origin_group.example.id
  cdn_frontdoor_origin_ids      = [azurerm_cdn_frontdoor_origin.example.id]
  enabled                       = true

  forwarding_protocol       = "HttpsOnly"
  https_redirect_enabled    = true
  patterns_to_match         = ["/*"]
  supported_protocols       = ["Http", "Https"]

  cdn_frontdoor_custom_domain_ids = [azurerm_cdn_frontdoor_custom_domain.example.id]
  link_to_default_domain          = false

  cache {
    query_string_caching_behavior = "UseQueryString"
    compression_enabled           = true
    content_types_to_compress     = ["image/jpeg"]
  }
}
```

### Debug Output/Panic Output

```shell
Error: expected cache.0.content_types_to_compress.0 to be one of [application/eot application/font application/font-sfnt application/javascript application/json application/opentype application/otf application/pkcs7-mime application/truetype application/ttf application/vnd.ms-fontobject application/xhtml+xml application/xml application/xml+rss application/x-font-opentype application/x-font-truetype application/x-font-ttf application/x-httpd-cgi application/x-mpegurl application/x-opentype application/x-otf application/x-perl application/x-ttf application/x-javascript font/eot font/ttf font/otf font/opentype image/svg+xml text/css text/csv text/html text/javascript text/js text/plain text/richtext text/tab-separated-values text/xml text/x-script text/x-component text/x-java-source], got image/jpeg

   with azurerm_cdn_frontdoor_route.example_route,
   on example.tf line 123, in resource "azurerm_cdn_frontdoor_route" "example_route":
  123:     content_types_to_compress     = ["image/jpeg"]
```

### Expected Behaviour

Front Door route file compression should be enabled with `image/jpeg` listed as the only content type to compress. Also applies to any other valid MIME types not listed in the validation set.

### Actual Behaviour

Error thrown during planning/validation complaining that `image/jpeg` is not a valid content type. Also applies to any other valid MIME types that aren't currently listed in the validation set.

### Steps to Reproduce

1. Set up example Front Door configuration with the route described above.
2. Run `terraform plan` or `terraform validate`.

### References

https://learn.microsoft.com/en-us/azure/frontdoor/standard-premium/how-to-compression#compression-rules describes the requirements for a file to be considered for compression. Besides filesize requirements, the only content type requirement is that it "Be of a MIME type".

https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/cdn/cdn_frontdoor_helpers.go appears to be where the list of content types is currently defined, but is not a complete list of valid MIME types.

**Comment by WodansSon** [comment] 2023-08-15 08:47
Hi @jared-koiter, thank you for opening this issue and bringing it to my attention. When I developed this resource the list of MIME types in the helper file were the list of supported MIME types supplied to me by the service team. I will reach out to them to see if this list has changed or if there have been new rules/conditions applied. 🚀

**Comment by WodansSon** [comment] 2023-08-15 17:18
Hi @jared-koiter, I have heard back from the service team and they have confirmed that the list of supported MIME types in the `cdn_frontdoor_helpers` are correct and they have not changed the list of supported MIME types since it's release. I am going to close this issue as `by design` shortly,  but I will leave it open for the next few days for any follow up questions you may have. Thanks again for opening this issue. 🚀

**Comment by jared-koiter** [comment] 2023-08-15 17:55
Thank you for chasing this down @WodansSon. When I modify this setting in the Azure web portal or via PowerShell it allows for any MIME types to be put in which, along with the lack of a list of supported MIME types in the Azure documentation, led me to believe that it shouldn't have been bounded in the Terraform provider. If the service team is saying otherwise though, then I would call it insufficient documentation/validation on Azure's part and not a bug in the Terraform resource's validation. Having different validation rules in Terraform vs. what Azure will actually allow may cause some confusion, but I'm satisfied to close this issue as working as intended.

**Closed** 2023-08-15 20:15 UTC
Labels: service/cdn, v/3.x
