### ISSUE TITLE
Original Error: determining which Required Resource Providers require registration: the required Resource Provider "Microsoft.TimeSeriesInsights" wasn't returned from the Azure API

### ISSUE THREAD

**Issue by C1022G-Thanh-Tu** [hashicorp/terraform-provider-azurerm#27482] opened 2024-09-24 10:03 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.6

### AzureRM Provider Version

3.71.0

### Affected Resource(s)/Data Source(s)

Any

### Terraform Configuration Files

```hcl
Any
```

### Debug Output/Panic Output

```shell
Planning failed. Terraform encountered an error while generating this plan.
╷
│ Error: Error ensuring Resource Providers are registered.
│
│ Terraform automatically attempts to register the Resource Providers it supports to
│ ensure it's able to provision resources.
│
│ If you don't have permission to register Resource Providers you may wish to use the
│ "skip_provider_registration" flag in the Provider block to disable this functionality.
│
│ Please note that if you opt out of Resource Provider Registration and Terraform tries
│ to provision a resource from a Resource Provider which is unregistered, then the errors
│ may appear misleading - for example:
│
│ > API version 2019-XX-XX was not found for Microsoft.Foo
│
│ Could indicate either that the Resource Provider "Microsoft.Foo" requires registration,
│ but this could also indicate that this Azure Region doesn't support this API version.
│
│ More information on the "skip_provider_registration" flag can be found here:
│ https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#skip_provider_registration
│
│ Original Error: determining which Required Resource Providers require registration: the required Resource Provider "Microsoft.TimeSeriesInsights" wasn't returned from the Azure API
│
│   with provider["registry.terraform.io/hashicorp/azurerm"],
│   on main.tf line 19, in provider "azurerm":
│   19: provider "azurerm" {
│
╵
Releasing state lock. This may take a few moments...
```

**Comment by iaingblack** [comment] 2024-09-24 12:54
FYI - Seems a duplicate of issue 27466. Short story, use version 3.90.0 or add a skip_provider_registration = true tag to provider azurerm block. Works now for me using that version (was on 3.66.0) and Terraform 1.29.0.

https://github.com/hashicorp/terraform-provider-azurerm/issues/27466

**Comment by rcskosir** [comment] 2024-09-24 17:00
Thanks for taking the time to submit this issue. It looks like this is a duplicate of #27466. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of #27466.

**Closed by rcskosir** 2024-09-24 17:00 UTC
Labels: duplicate, provider, v/3.x
