### ISSUE TITLE
azurerm_key_vault_secret : Destroy operation fail in Terraform CLI but secret destroyed in Azure

### ISSUE THREAD

**Issue by JuBouillet** [hashicorp/terraform-provider-azurerm#15101] opened 2022-01-25 07:55 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v1.1.3
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.92.0
```
### Affected Resource(s)

* `azurerm_key_vault_secret`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
  subscription_id = "xxx"
  tenant_id       = "xxx"
}
data "azurerm_client_config" "current" {}

resource "azurerm_resource_group" "rg" {
  name     = "TerraformKeyVaultSecretDeletionFail"
  location = "West Europe"
  tags         = {}
}

resource "azurerm_key_vault" "keyvault" {
  name                       = "testtfkverrorsecretdel"
  location                   = azurerm_resource_group.rg.location
  resource_group_name        = azurerm_resource_group.rg.name
  tenant_id                  = data.azurerm_client_config.current.tenant_id
  sku_name                   = "standard"
  soft_delete_retention_days = 7
  purge_protection_enabled = true

  access_policy {
    tenant_id = data.azurerm_client_config.current.tenant_id
    object_id = data.azurerm_client_config.current.object_id

    key_permissions = [
      "create",
      "get",
      "list"
    ]

    secret_permissions = [
      "set",
      "list",
      "get",
      "delete",
      "purge",
      "recover"
    ]
  }
  tags         = {}
}

resource "azurerm_key_vault_secret" "secret" {
  name         = "secret-sauce"
  value        = "szechuan"
  key_vault_id = azurerm_key_vault.keyvault.id
  tags         = {}
}
```

### Expected Behaviour

When you apply the HCL template above for the first time, it will create all the desired resources (Resource Group, Azure Key Vault and a secret inside the keyvault).

If you remove the azurerm_key_vault_secret, the next terraform apply will remove the secret from the Key Vault.

### Actual Behaviour

When you apply the HCL template above the first time, it will create all the desired resources (Resource Group, Azure Key Vault and a secret inside the keyvault).

If you remove the azurerm_key_vault_secret, the next terraform apply will throw an exception: 

`Error: purging of Secret "secret-sauce" (Key Vault "https://testtfkverrorsecretdel.vault.azure.net/") : keyvault.BaseClient#PurgeDeletedSecret: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="Operation \"purge\" is not allowed because purge protection is enabled for this vault. Key Vault service will automatically purge it after the retention period has passed.\r\nVault: testtfkverrorsecretdel;location=westeurope"`.

However, if you look at the Key Vault in the Azure Portal, the secret is well destroyed despite the error.

In fact, if you do a third "terraform apply", the secret will be detected as deleted by Terraform and the TFSTATE will be updated correctly.

### Steps to Reproduce

1. `terraform apply`
2. Remove the `"azurerm_key_vault_secret"`
3. `terraform apply`

**Comment by tombuildsstuff** [comment] 2022-01-25 10:35
hi @JuBouillet 

Thanks for opening this issue.

As the error message coming back from Azure is stating, it's not possible to perform a Purge operation when Purge Protection is enabled - which happens by default when deleting a Key Vault Certificate / Key / Secret (as the user has already confirmed via the Terraform Plan that they want this Secret removed).

Since this is the behaviour of the Provider, this can be controlled using the `features` block - for example:

```hcl
provider "azurerm" {
  features {
    key_vault {
      purge_soft_delete_on_destroy = false
    }
  }
}
```

Which will skip purging the Secret when it is destroyed - [more information can be found in the Features block documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#features).

Since this is a configuration question rather than a bug in the Azure Provider I'm going to close this issue for the moment but as mentioned above by setting this flag within the `features` block you should be able to disable this functionality when Purge Protection is enabled, which should solve this configuration issue for you.

Thanks!

**Closed by tombuildsstuff** 2022-01-25 10:35 UTC
Labels: question
