### ISSUE TITLE
azurerm_mssql_database does not pick up license_type and terraform tries to apply it on each `terraform apply`

### ISSUE THREAD

**Issue by MagdaPaj** [hashicorp/terraform-provider-azurerm#10448] opened 2021-02-03 14:05 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.5
+ provider registry.terraform.io/hashicorp/azurerm v2.39.0
+ provider registry.terraform.io/hashicorp/random v3.0.1

### Affected Resource(s)

* `azurerm_mssql_database`

### Terraform Configuration Files

```hcl
resource "azurerm_mssql_database" "my-name" {
  name                        = var.db_name
  server_id                   = azurerm_sql_server.my-name.id
  collation                   = "SQL_Latin1_General_CP1_CI_AS"
  license_type                = "LicenseIncluded"
  max_size_gb                 = 1
  sku_name                    = "GP_S_Gen5_1"
  zone_redundant              = false
  auto_pause_delay_in_minutes = 60
  min_capacity                = 0.5
  read_replica_count          = 0
  read_scale                  = false
}
```

### Expected Behaviour

If there is no changes to azurerm_mssql_database, then nothing is updated.

### Actual Behaviour

Without any changes to `azurerm_mssql_database`, terraform detects that there is a missing `license_type                = "LicenseIncluded"` and applies it. And that change is visible every time I run `terraform plan` or `terraform apply`.

![terraform-apply](https://user-images.githubusercontent.com/25376553/106757417-9ccbd700-6630-11eb-9e87-102d82f52b83.png)

### Steps to Reproduce

1. Create `azurerm_mssql_database` with `license_type = "LicenseIncluded"`
2. Run `terraform apply`
3. Wait until resource is created
4. Run `terraform plan`, you will notice that `azurerm_mssql_database` is marked to be updated.
5. Run `terraform apply`, you will notice that  `azurerm_mssql_database` will be updated

### References

* #0000

**Comment by MagdaPaj** [comment] 2021-02-03 14:39
Tested also with `provider registry.terraform.io/hashicorp/azurerm v2.45.1` and the same issue persists. 

And this problem may be related to [this](https://github.com/Azure/azure-rest-api-specs/issues/10715).

**Comment by dcfsc** [comment] 2021-03-08 15:10
Created a new Azure SQL DB with Azurerm 2.50 and the `license_type` value is not accepted, so I can not try `ignore_changes`.
```
Error: Unsupported argument

  on mssql-azuresql.tf line 12, in resource "azurerm_mssql_server" "infra_sqlserver":
  12:   license_type                 = "LicenseIncluded"
```
however still reports
```
  # azurerm_mssql_database.perfmondb will be updated in-place
  ~ resource "azurerm_mssql_database" "perfmondb" {
      + license_type                = "LicenseIncluded"
```
and `apply` does not fail, but also does not make the change go away.
```
$ terraform apply
...
azurerm_mssql_database.perfmondb: Modifications complete after 18s [id=/subscriptions/.../perfmondb-sqldb]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```
and `plan` shows the same "dirty" state
```
$ terraform plan
...
Terraform will perform the following actions:

  # azurerm_mssql_database.perfmondb will be updated in-place
  ~ resource "azurerm_mssql_database" "perfmondb" {
      + license_type                = "LicenseIncluded"

Plan: 0 to add, 1 to change, 0 to destroy.
```

**Comment by samar-upadhyay** [comment] 2021-03-23 20:10
I'm getting the same issue. Stumbled on here while googling. Ran the terraform job twice to validate this is an issue. Any ETA on the fix?

**Comment by olllol** [comment] 2021-06-03 10:02
Same here
Terraform v0.14.8
+ provider registry.terraform.io/hashicorp/azurerm v2.59.0

**Comment by morsik** [comment] 2021-06-14 13:40
I'm running:
```
Terraform v0.15.4
+ registry.terraform.io/hashicorp/azurerm v2.61.0
```

and still same issue :(

**Comment by gerardwolf** [comment] 2021-08-19 22:12
Same here
Terraform v1.0.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/azuread v1.6.0
+ provider registry.terraform.io/hashicorp/azurerm v2.70.0

**Comment by thllxb** [comment] 2021-09-13 15:37
I think it is a duplicate of https://github.com/hashicorp/terraform-provider-azurerm/issues/8346

**Comment by katbyte** [comment] 2022-07-28 01:29
Closing as a duplicate of #8346

**Closed by katbyte** 2022-07-28 01:29 UTC
Labels: bug, upstream-microsoft
