### ISSUE TITLE
azurerm_app_service_certificate_binding failing with Thumbprint is null or empty

### ISSUE THREAD

**Issue by protoblade** [hashicorp/terraform-provider-azurerm#13543] opened 2021-09-29 08:04 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/azuread v1.4.0
+ provider registry.terraform.io/hashicorp/azurerm v2.77.0
### Affected Resource(s)

* `azurerm_app_service_certificate_binding `

### Terraform Configuration Files

```hcl
resource "azurerm_app_service_certificate_binding" "full_cert_binding" {
  hostname_binding_id = azurerm_app_service_custom_hostname_binding.full_custom_domain_binding.id
  certificate_id      = azurerm_app_service_managed_certificate.full_managed_cert.id
  ssl_state           = "SniEnabled"
}

```

### Debug Output

```
Error: creating/updating Custom Hostname Certificate Binding "*****" with certificate name "******" (App Service "*****" / Resource Group "rsg-euwe-pdsk-pddev-1121"): web.AppsClient#CreateOrUpdateHostNameBinding: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Parameter Thumbprint is null or empty." Details=[***"Message":"Parameter Thumbprint is null or empty."***,***"Code":"BadRequest"***,***"ErrorEntity":***"Code":"BadRequest","ExtendedCode":"51011","Message":"Parameter Thumbprint is null or empty.","MessageTemplate":"Parameter ***0*** is null or empty.","Parameters":["Thumbprint"]***]
44

45
  on webapp/main.tf line 151, in resource "azurerm_app_service_certificate_binding" "full_cert_binding":
46
 151: resource "azurerm_app_service_certificate_binding" "full_cert_binding" ***
```
### Expected Behaviour

Terraform apply to finish
### Actual Behaviour

Terraform fails with the mentioned above error
### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by aristosvo** [comment] 2021-09-29 08:30
Hi @protoblade! Which version are you using?

#13353 has caused some problems, so updating to the latest and greatest would solve most of your problems.

**Comment by protoblade** [comment] 2021-09-29 08:40
This is during apply, not during plan and its exiting cleanly with error that thumbnail should not be empty/null but its not something that can be set

**Comment by protoblade** [comment] 2021-09-29 09:37
the same configuration worked until yesterday evening

**Comment by aristosvo** [comment] 2021-09-29 11:36
Hi @protoblade! Issue #13353 is caused by a change in behaviour of the Azure REST API. It is out of our reach to fix this, we can only check whether you are having problem with this specific problem or that it's a different problem.

Can you give us more information about your setup, for instance which region you are using? At this moment in time we cannot validate your problems.

Below setup is the setup which is (among others) used in the Acceptance Tests, which I am able to run successfully against location West Europe:
```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-asmc-1234"
  location = "%s"
}

resource "azurerm_app_service_plan" "test" {
  name                = "acctestASP-1234"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  kind                = "Linux"

  sku {
    tier = "Basic"
    size = "B1"
  }

  reserved = true
}

resource "azurerm_app_service" "test" {
  name                = "acctest1234"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  app_service_plan_id = azurerm_app_service_plan.test.id
}

data "azurerm_dns_zone" "test" {
  name                = "terraformproviders.dev"
  resource_group_name = "dns"
}

resource "azurerm_dns_cname_record" "test" {
  name                = "test1234"
  zone_name           = data.azurerm_dns_zone.test.name
  resource_group_name = data.azurerm_dns_zone.test.resource_group_name
  ttl                 = 300
  record              = azurerm_app_service.test.default_site_hostname
}

resource "azurerm_dns_txt_record" "test" {
  name                = join(".", ["asuid", "test1234"])
  zone_name           = data.azurerm_dns_zone.test.name
  resource_group_name = data.azurerm_dns_zone.test.resource_group_name
  ttl                 = 300

  record {
    value = azurerm_app_service.test.custom_domain_verification_id
  }
}

resource "azurerm_app_service_custom_hostname_binding" "test" {
  hostname            = join(".", [azurerm_dns_cname_record.test.name, azurerm_dns_cname_record.test.zone_name])
  app_service_name    = azurerm_app_service.test.name
  resource_group_name = azurerm_resource_group.test.name
}

resource "azurerm_app_service_managed_certificate" "test" {
  custom_hostname_binding_id = azurerm_app_service_custom_hostname_binding.test.id
}

resource "azurerm_app_service_certificate_binding" "test" {
  hostname_binding_id = azurerm_app_service_custom_hostname_binding.test.id
  certificate_id      = azurerm_app_service_managed_certificate.test.id
  ssl_state           = "SniEnabled"
}
```

**Comment by protoblade** [comment] 2021-09-29 14:17
seems that v 2.78.0 is fixing this issue

**Comment by jackofallops** [comment] 2021-10-01 09:01
I'm going to close this issue for now.  Azure are temporarily rolling back the change that resulted in 13353, but will be issuing communications regarding it being rolled back out again.  In all likelihood, we'll need to leave in the workarounds addressing the issue. The intent is that Azure managed certs will no longer expose values for `thumbprint`, and the validity dates, so these values will be empty going forward.  This does not affect cert from any other sources.

**Closed by jackofallops** 2021-10-01 09:01 UTC
