### ISSUE TITLE
Support for "default_tags" across terraform-provider-azurerm

### ISSUE THREAD

**Issue by Ajf7468** [hashicorp/terraform-provider-azurerm#11682] opened 2021-05-12 17:57 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The AWS provider recently released a functionality of adding a map of "default_tags" to the provider that would be automatically merged with supported resources for tags.  It would not overwrite tags set at a resource level but would provide a default for new resources if not individually specified.

This is a request to bring the same feature to the azurerm provider.

### New or Affected Resource(s)

* terraform-provider-azurerm

### Potential Terraform Configuration

```hcl
provider "azurerm" {
 default_tags {
   tags = {
     Environment = "Test"
     Project     = "Test"
   }
 }
}
```

### References

* [Hashicorp Blog on the Topic](https://www.hashicorp.com/blog/default-tags-in-the-terraform-aws-provider)

**Comment by magodo** [comment] 2021-05-13 05:32
Related to #7034

**Comment by inaun** [comment] 2021-05-26 17:36
This is great functionality introduced in the AWS provider -- hope to see the same functionality reproduced in the azurerm provider. Very helpful to define tags in a single place and have them automatically applied to all resources created!

**Comment by gswallow** [comment] 2021-07-12 19:58
Note that there are policies you can set at the resource group level that enforce tags but I'm fighting the Azure provider's basic "ignore_changes" support right now:

```
resource "azurerm_policy_definition" "add_tag" {
  name = "Add-Tag-To-Resources"
  policy_type = "Custom"
  mode = "Indexed"
  display_name = "Append a tag to resources"
  description = "Adds the specified tag and value when any resource missing this tag is created or updated. Existing resources can be remediated by triggering a remediation task. If the tag exists with a different value it will not be changed. Does not modify tags on resource groups."

  parameters = <<PARAMS
  {
    "tagName": {
      "type": "String",
      "metadata": {
        "displayName": "Tag Name",
        "description": "Name of the tag, such as 'environment'"
      }
    },
    "tagValue": {
      "type": "String",
      "metadata": {
        "displayName": "Tag Value",
        "description": "Value of the tag, such as 'production'"
      }
    }
  }
PARAMS
    
  policy_rule = <<RULE
  {
    "if": {
      "field": "[concat('tags[', parameters('tagName'), ']')]",
      "exists": "false"
    },
    "then": {
      "effect": "modify",
      "details": {
        "roleDefinitionIds": [
          "${data.azurerm_role_definition.contributor.id}"
        ],
        "operations": [
          {
            "operation": "add",
            "field": "[concat('tags[', parameters('tagName'), ']')]",
            "value": "[parameters('tagValue')]"
          }
        ]
      }
    }
  }
RULE
}
```

```
resource "azurerm_resource_group_policy_assignment" "add_tag" {
  for_each = { for tag in var.mandatory_tags : tag.tag_name => tag }
  name = "Add${replace(title(each.value.tag_name), " ", "")}Tag"
  resource_group_id = azurerm_resource_group.default.id
  policy_definition_id = azurerm_policy_definition.add_tag.id
  location = var.region
  identity {
    type = "SystemAssigned"
  }
  parameters = <<-PARAMS
  {
    "tagName": {
      "value": "${each.value.tag_name}"
    },
    "tagValue": {
      "value": "${each.value.tag_value}"
    }
  }
  PARAMS
}
```

```
variable "mandatory_tags" {
  description = "A map of tag-name/tag-value pairs used for cost tracking"
  type        = list(map(string))
  default     = [
    {
      tag_name = "Company"
      tag_value = "xxx"
    },
    {
      tag_name = "Business Unit"
      tag_value = "yyy"
    },
    {
      tag_name = "Contact"
      tag_value = "zzz"
    }
  ]
}

**Comment by etaham** [comment] 2021-12-28 16:10
Hey folks, 
Any update on this? Now that the AWS feature is out and used, can it be lifted into the Azure Provider?

We want to ignore tags applied via policy, but still allow specific tags on specific resources via Terraform.

Thanks!

**Comment by tombuildsstuff** [comment] 2022-01-04 18:20
👋 

Thanks for opening this issue.

Taking a look through this appears to be a duplicate of #13776 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #13776 for updates?

Thanks!

**Closed by tombuildsstuff** 2022-01-04 18:20 UTC
Labels: thinking
