### ISSUE TITLE
azurerm_postgresql_flexible_server_database collaction valiation error

### ISSUE THREAD

**Issue by lupa95** [hashicorp/terraform-provider-azurerm#22936] opened 2023-08-14 11:36 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.4

### AzureRM Provider Version

3.69.0

### Affected Resource(s)/Data Source(s)

azurerm_postgresql_flexible_server_database

### Terraform Configuration Files

```hcl
resource "azurerm_postgresql_flexible_server_database" "example" {
  name      = "mydb"
  server_id = azurerm_postgresql_flexible_server.example.id
  collation = "de_DE.UTF8"
  charset   = "UTF8"
}
```

### Debug Output/Panic Output

```shell
│ Error: collation contains unknown collation de_DE.UTF8
│ 
│   with azurerm_postgresql_flexible_server_database.wis_db,
│   on databases.tf line 4, in resource "azurerm_postgresql_flexible_server_database" "wis_db":
│    4:   collation = "de_DE.UTF8"
│
```

### Expected Behaviour

The provider version `3.68.0` allowed the collation `de_DE.UTF8`, but after upgrading to `3.69.0` a validation error occurs.

Updating the collation to `de_DE.utf8` fixes the validation error, but forces a replacement on the resource, which is not a viable thing to do for a database.

The provider should accept the collation `de_DE.UTF8` to be backwards compatible.

### Actual Behaviour

Provider does not accept collation `de_DE.UTF8`.

### Steps to Reproduce

1. run `terraform validate` --> validation error
2. Replace `de_DE.UTF8` with `de_DE.utf8` in the configuration
3. Run `terraform plan` --> shows force replacement on database resource

### References

There seem to be more people with similar issues, after the validation got changed. https://github.com/hashicorp/terraform-provider-azurerm/pull/22689

**Comment by neil-yechenwei** [comment] 2023-08-15 04:42
Thanks for raising this issue. I assume it's expected since "de_DE.utf8" is valid format. Suggest to either add ignore_changes or specify the corresponding value in tf config.

Doc Reference: https://www.postgresql.org/docs/current/collation.html

**Comment by neil-yechenwei** [comment] 2023-08-15 04:52
Thanks for raising this issue. I assume it's expected behavior since "de_DE.utf8" is valid value. Suggest to update it to "de_DE.utf8" in tf config. Thanks.

Doc Reference: https://www.postgresql.org/docs/current/collation.html

**Comment by lupa95** [comment] 2023-08-15 06:31
You are right, that "de_DE.utf8" is indeed the correct value. However, the older provider version also allowed "de_DE.UTF8" and that's what I have used to deploy the infrastructure. If I update the value to lower case, terraform will try to replace the resource because it thinks the collation changes.

```terraform
# azurerm_postgresql_flexible_server_database.example must be replaced
-/+ resource "azurerm_postgresql_flexible_server_database" "example" {
      ~ collation = "de_DE.UTF8" -> "de_DE.utf8" # forces replacement
      ~ id        = "/subscriptions/XXX/resourceGroups/XXX/providers/Microsoft.DBforPostgreSQL/flexibleServers/XXX/databases/XXX" -> (known after apply)
        name      = "example"
        # (2 unchanged attributes hidden)
    }
```

Since we are talking about a database resource here, I can't just do that.

**Comment by tombuildsstuff** [comment] 2023-08-15 11:36
Duplicate of #22907 which was fixed by #22928 which reworks this validation / will ship in this weeks release.

**Closed by tombuildsstuff** 2023-08-15 11:36 UTC
Labels: service/postgresql, v/3.x

**Comment by lupa95** [comment] 2023-08-21 13:31
I am sorry to reopen this, but `3.70.0` didn't fix the issue. Terraform still does not honor the previously valid collation with upper case.

Is using lifecycle ignore_changes the only fix for this?

**Comment by T3pco** [comment] 2023-08-25 09:41
@tombuildsstuff 
sadly still not working with 3.70.0+ - still wants to replace the db.

terraform plan outout:

Installed hashicorp/azurerm v3.71.0 (signed by HashiCorp)
...
-/+ resource "azurerm_postgresql_flexible_server_database" "db" {
      ~ charset   = "UTF8" -> "utf8"
      ~ collation = "en_US.UTF8" -> "en_US.utf8" # forces replacement
      ~ id        = "/subscriptions/..." -> (known after apply)
        name      = "..."
        # (1 unchanged attribute hidden)
    }`

**Comment by thomeu** [comment] 2023-12-19 15:31
@tadeusz-delphai Did you manage to update version without recreating the database? thanks

**Comment by tadeusz-delphai** [comment] 2023-12-19 15:52
> @tadeusz-delphai Did you manage to update version without recreating the database? thanks

I just tested the azurerm provider version 3.85.0.

No change in behavior since the collation name validator was changed in 3.69.0. The upper-case collation name `en_US.UTF8` crashes with an error `collation contains unknown collation` as described above, switching to a lower-case `en_US.utf8` wants to force a full recreate of the PostgreSQL resource, which is a very invasive operation. The attempted workaround of manually creating different collation objects inside the PostgreSQL cluster didn't make any difference.

For now, I just pin a lower version of the azurerm provider.

**Comment by green-munkey** [comment] 2024-03-15 19:12
I have also ran into this issue with 3.96.0 when migrating from 3.65.0. In our situation, we can't move to another clean DB.  I have also tried using the ignore_changes setting without any luck, so I am checking for any advice on how to move forward in ignoring this setting as we have other components we are trying to fix with the later version of Terraform, so we are stuck in a pickle. 

lifecycle {
    prevent_destroy = true
    ignore_changes = [
      collation,
      charset
    ]
  }

**Comment by green-munkey** [comment] 2024-03-20 20:54
I have also done the following actions and have yet to be successful. 

1. remove azurerm_postgresql_flexible_server_database from the state using **terraform state rm** 
2. then re-import the resource using **terraform import**  

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/15044310/2ddfd0c6-6bac-496b-bbe1-3cc99b7deb3f)

3. then, tried to add a new resource to verify the **terraform plan** command with the same problem 

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/15044310/ab827854-893e-4af4-8f20-5660982a2bac)
