### ISSUE TITLE
Error ensuring resource providers are registered. Issue with new azurerm provider v2.86.0.  Works with v2.85.0

### ISSUE THREAD

**Issue by nimmyarjith** [hashicorp/terraform-provider-azurerm#14259] opened 2021-11-19 07:15 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.13.5 
azurerm v2.86.0

### Affected Resource(s)

TF plan is failing after upgrading to azurerm v2.86.0. It is working with azurerm v2.85.0. 

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

Error: Error ensuring Resource Providers are registered. 
Terraform automatically attempts to register the Resource Providers it supports to 
ensure it's able to provision resources. 
If you don't have permission to register Resource Providers you may wish to use the 
"skip_provider_registration"

### Expected Behaviour

Should execute successfully

### Actual Behaviour

Error: Error ensuring Resource Providers are registered. 
Terraform automatically attempts to register the Resource Providers it supports to 
ensure it's able to provision resources. 
If you don't have permission to register Resource Providers you may wish to use the 
"skip_provider_registration"

### Steps to Reproduce

1. `terraform plan`

### References

* #0000

**Comment by tombuildsstuff** [comment] 2021-11-19 07:22
hi @nimmyarjith 

Thanks for opening this issue.

Azure's concept of a Resource Provider requires that the Resource Provider is registered before any API's within that Resource Provider can be called. As such, rather than failing during an API call / to improve the user experience Terraform automatically attempts to register any Resource Providers that it supports by default - to ensure that the API's are available when they're needed; and since this list is stored within Terraform, we extend this list from time to time as Terraform is updated to support new functionality (provided in new Resource Providers).

If you'd prefer to manage Resource Provider Registration outside of Terraform (for example you're running in a restricted environment) - as mentioned in the error message it's possible to opt-out of this behaviour by setting this field [in the Provider block](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#skip_provider_registration).

Since this is working as intended I'm going to close this issue for the moment - but please let us know if disabling this functionality doesn't work for you and we'll take another look.

Thanks!

**Closed by tombuildsstuff** 2021-11-19 07:22 UTC
Labels: question
