### ISSUE TITLE
customer_managed_key removed from storage_account

### ISSUE THREAD

**Issue by mappoc** [hashicorp/terraform-provider-azurerm#16085] opened 2022-03-27 17:32 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.1.7
on windows_amd64
provider registry.terraform.io/aztfmod/azurecaf v1.2.16
provider registry.terraform.io/hashicorp/azuread v2.19.1
provider registry.terraform.io/hashicorp/azurerm v3.0.2
provider registry.terraform.io/hashicorp/random v3.1.2

### Affected Resource(s)

* `azurerm_storage_account`
* `azurerm_storage_account_customer_managed_key`

### Terraform Configuration Files

```hcl
data "azurerm_key_vault" "infinet_kv" {
  name                = "infinet-kv"
  resource_group_name = "infinet-rg"
}

data "azurerm_key_vault_key" "files_feeds_st" {
  name         = "files-feeds-st"
  key_vault_id = data.azurerm_key_vault.infinet_kv.id
}

resource "azurerm_storage_account" "files_feeds" {
  name                            = lower(random_id.file_storage.hex)
  resource_group_name             = azurerm_resource_group.file_storage.name
  location                        = azurerm_resource_group.file_storage.location
  account_tier                    = "Standard"
  account_replication_type        = "ZRS"
  account_kind                    = "StorageV2"
  access_tier                     = "Hot"
  min_tls_version                 = "TLS1_2"
  allow_nested_items_to_be_public = false
  tags                            = merge(module.label.tags, var.file_storage_tags)

  network_rules {
    default_action             = "Deny"
    bypass                     = ["AzureServices", "Logging", "Metrics"]
  }

  identity {
    type = "SystemAssigned"
  }

  share_properties {
    retention_policy {
      days = 90
    }
  }

}

resource "azurerm_storage_account_customer_managed_key" "files_feeds" {
  storage_account_id = azurerm_storage_account.files_feeds.id
  key_vault_id       = data.azurerm_key_vault.infinet_kv.id
  key_name           = data.azurerm_key_vault_key.files_feeds_st.name
  key_version        = data.azurerm_key_vault_key.files_feeds_st.version
}
```

### Expected Behavior

No change to the existing `azurerm_storage_account` resource.

### Actual Behavior

After upgrading to the v3 azurerm provider, the Customer Managed Key (CMK) is designated for removal in the Plan.

Is this the expected behavior?  Will the key applied by the `azurerm_storage_account_customer_managed_key` resource remain applied?

```hcl
  # azurerm_storage_account.files_feeds will be updated in-place
      - customer_managed_key {
          - key_vault_key_id = "(redacted)" -> null
        }
```

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

None.

### References

None.

**Comment by magodo** [comment] 2022-03-28 03:50
@mappoc Thank you for submitting this, from the comment [here](https://github.com/hashicorp/terraform-provider-azurerm/pull/15082/files#diff-084e86427d8a602a2f79190c44ffc82764e1db56a40f9f6d051836d06312ae59R238-R241), it appears that this is an undocumented change in the upgrade guide, that the `customer_managed_key` block in the `azurerm_storage_account` is not computed any more in v3. This means you can either add that block explicitly, or add a `ignore_changes` in your configuration.

**Comment by tombuildsstuff** [comment] 2022-08-30 07:09
@magodo if this change is missing from the upgrade guide then we should look to add that - however this is intentionally not `Computed` since this can be specified both within the `azurerm_storage_account` resource and via the separate (older) `azurerm_storage_account_customer_managed_key` resource.

Whilst there are several examples where it's possible to configure functionality for a resource (e.g. customer managed key) both within the resource and via a separate virtual resource, historically these have used `Computed: true` to avoid a diff for these fields, however that's not something we should be doing going forwards (since it confuses users that this isn't removed when they removed the block) - and (as in this case) will be removed at the next major version. This is also the case for the `subnets` block within the `azurerm_virtual_network` resource which is currently `Computed` for legacy reasons (the combined Create/Update block) - however in the next major version (4.0) this'll become un-computed too.

As such this change is intentional and we won't be adding `Computed` to this field and as you've mentioned this can be worked around by using `ignore_changes`. If this is missing from the upgrade guide then that's an oversight and we should look to add this in - however ultimately this is working as intended since we're highlighting that a Customer Managed Key is configured using the separate resource, and isn't configured within the `azurerm_storage_account` resource (and so needs to be ignored there).

**Closed** 2022-08-30 10:02 UTC
Labels: question, service/storage
