### ISSUE TITLE
Azurerm - application gateway -> request_routing_rule blocks missing "priority" as required parameter.

### ISSUE THREAD

**Issue by RebeckaYuan** [hashicorp/terraform-provider-azurerm#20851] opened 2023-03-09 02:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.9

### AzureRM Provider Version

3.45.0

### Affected Resource(s)/Data Source(s)

azurerm_application_gateway

### Terraform Configuration Files

```hcl
Resource:
azurerm_application_gateway -> request_routing_rule blocks missing "priority" as required parameter.
```

### Debug Output/Panic Output

```shell
Error: creating Application Gateway: (Name "xxx-agw" / Resource Group "xxx-rg"e=400 -- Original Error: Code="ApplicationGatewayRequestRoutingRulePriorityCannotBeEaf58-0cb674cf81b8/resourceGroups/xxxrg/providers/Microsoft.Network/applicationG rules should have a priority defined starting from api-version 2021-08-01" Details=


e.g.
priority parameter add to the reqeust_routing_rule blocks. 
example "priority = 100".
```

### Expected Behaviour

app gateway get provissioned.

### Actual Behaviour

Error: creating Application Gateway: (Name "xxx-agw" / Resource Group "xxx-rg"e=400 -- Original Error: Code="ApplicationGatewayRequestRoutingRulePriorityCannotBeEaf58-0cb674cf81b8/resourceGroups/xxxrg/providers/Microsoft.Network/applicationG rules should have a priority defined starting from api-version 2021-08-01" Details=

e.g.
priority parameter add to the reqeust_routing_rule blocks. 
example "priority = 100".

### Steps to Reproduce

create any app gateway with request_ruouting_rule without priority parameter.

**Comment by ms-zhenhua** [comment] 2023-03-09 06:15
Hi @RebeckaYuan, seems it is the same issue with https://github.com/hashicorp/terraform-provider-azurerm/issues/19874. `priority` is required if you use `v2 sku`.

**Comment by manicminer** [comment] 2023-03-16 20:31
Duplicate of #19874

**Closed by manicminer** 2023-03-16 20:31 UTC
