### ISSUE TITLE
Support for toggle to force delete azurerm_kubernetes_cluster_node_pool

### ISSUE THREAD

**Issue by t3mi** [hashicorp/terraform-provider-azurerm#10411] opened 2021-02-01 16:09 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In case of small sized node pool or tolerations on it which prevents re-scheduling of the pods configured with pod disruption budget following error occurs during node pool removal:
```hcl
Error: waiting for the deletion of Node Pool "vmss" (Managed Kubernetes Cluster "aks-test" / Resource Group "aks-test-rg"): Code="DeleteVMSSAgentPoolFailed" Message="VMSSAgentPoolReconciler retry failed: {\n  \"code\": \"PodDrainFailure\",\n  \"message\": \"Node 'aks-vmss-17400673-vmss000001' failed to be drained with error: 'Drain did not complete pods [<pod-name>] within 10m0s'\"\n }"
```

### New or Affected Resource(s)

* azurerm_kubernetes_cluster_node_pool

### Potential Terraform Configuration

```hcl
# Configure the Azure Provider
provider "azurerm" {
  features {
    azurerm_kubernetes_cluster_node_pool {
      disable_eviction = true
    }
  }
}
```

### References

* [#83307](https://github.com/kubernetes/kubernetes/issues/83307)

**Comment by tombuildsstuff** [comment] 2021-02-02 11:23
hi @t3mi 

Thanks for opening this issue.

Unfortunately at this time the Azure API doesn't support a means of draining a Node Pool - as such at this point in time the Provider attempts to destroy the Node Pool using the Delete API and waits for it to complete.

Whilst it's possible that the AKS API may provide the option to configure this in the future, [unfortunately it doesn't at this point in time](https://docs.microsoft.com/en-us/rest/api/aks/agentpools) - and since there's no API to support this behaviour at this time, this'd need the AKS Service Team to expose a means of controlling this. As such I'm going to suggest [opening an issue on the AKS Repository instead](https://github.com/Azure/AKS/issues) where someone from that team should be able to take a look - and once it's available we can look at integrating this into Terraform.

Thanks!

**Comment by ams0** [comment] 2021-02-03 11:06
Hitting the same, watching

**Comment by treyhendon** [comment] 2021-02-27 16:16
Would it be possible to issue a delete on the AKS instance first (before the pools) and then have the pools refresh their TF status before issuing their delete (if they still exist)?

My struggle with this error is with completely tearing down an environment - I get the same error.  My end-goal is for all of the assets to go away.  In the UI, I can just delete AKS and it deletes the custom node pools for me.  It seems like Terraform is issuing the delete command on my custom node pools before issuing the delete command to the AKS instance.

**Comment by r3mattia** [comment] 2021-03-24 10:16
I can confirm as I am encountering the same issue when destroying a module with:

- AKS resource with default node pool
- 2x additional node pools associated with the cluster

It tries to destroy the node pools and the cluster simultaneously for a few minutes before eventually returning the same error.

**Comment by r3mattia** [comment] 2021-03-24 10:20
However, it turns out that after re-running `terraform destroy` shortly after this error, the cluster got destroyed, whilst the node pools remain in the `Still destroying` state.

**Comment by treyhendon** [comment] 2021-03-24 10:33
As a work around for others who find this, we added a several kubectl commands to delete all non system/AKS namespaces in the pipeline prior to executing the Terraform step to destroy the environment. It slows the process, but ensures a successful TF destroy.

**Comment by aslafy-z** [comment] 2023-10-23 12:15
```terraform
resource "azurerm_kubernetes_cluster_node_pool" "infra" {
[...]

  node_labels = {
    "example.com/cluster-name" = azurerm_kubernetes_cluster.main.name,
    "example.com/resource-group" = azurerm_kubernetes_cluster.main.resource_group_name,
  }

  provisioner "local-exec" {
    when        = destroy
    command     = <<-EOF
      az aks command invoke -g "${self.node_labels["example.com/resource-group"]}" -n "${self.node_labels["example.com/cluster-name"]}" -c "kubectl drain -l 'kubernetes.azure.com/agentpool=${self.name}' --ignore-daemonsets --delete-emptydir-data --timeout=10m || kubectl drain -l 'kubernetes.azure.com/agentpool=${self.name}' --ignore-daemonsets --delete-emptydir-data --timeout=10m --disable-eviction=true"
    EOF

    interpreter = ["/usr/bin/env", "bash", "-c"]
  }
  ```
  
Here's a workaround that uses the AKS `Run command` primitive that triggers jobs inside the cluster.
Before calling AKS api to destroy, it executes a drain, and after 10 minutes, it some resources are blocked by PDB, drains with forced eviction.
In order for the run command not to fail, I added an annotation to run these jobs on the default node pool by configuring the namespace with

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: aks-command
  annotations:
    scheduler.alpha.kubernetes.io/node-selector: kubernetes.azure.com/agentpool=default
```

**Comment by rcskosir** [comment] 2024-03-15 19:54
Thanks for taking the time to open this issue. It looks like the behavior you requested is not supported by the underlying Azure API so I am going to label this issue as such and close it for now. When it gets added, we can reopen this request or you can create a new one.
https://github.com/Azure/AKS/issues/2090

**Closed by rcskosir** 2024-03-15 19:54 UTC
Labels: enhancement, service/kubernetes-cluster, sdk/not-yet-supported, upstream/microsoft/needs-support-on-azure-api

**Comment by TomBillietKlarrio** [comment] 2024-04-10 14:33
I'm a bit confused here:
* when I delete a nodepool via the Azure UI, it respects the PDB
* when I delete a nodepool via Terraform, it ignored the PDB

When I turn on debug logging in terraform, I see this happening on a delete of a nodepool:
```
2024-04-10T16:22:31.863+0200 [DEBUG] provider.terraform-provider-azurerm_v3.95.0_x5: DELETE https://management.azure.com/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.ContainerService/managedClusters/xxx/agentPools/tom1c50?api-version=2023-06-02-preview&ignore-pod-disruption-budget=true: timestamp=2024-04-10T16:22:31.863+0200
```
So that api seems to indicate there is a parameter for this?
