### ISSUE TITLE
Changing SKU Tier from paid to standard for azurerm_kubernetes_cluster fails

### ISSUE THREAD

**Issue by Mahagon** [hashicorp/terraform-provider-azurerm#20887] opened 2023-03-10 09:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.0

### AzureRM Provider Version

3.47.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "k8s" {
  name                              = "skutest-saas-${var.environment}"
  location                          = data.azurerm_resource_group.saas.location
  resource_group_name               = data.azurerm_resource_group.saas.name
  dns_prefix                        = "k8s"
  kubernetes_version                = "1.24"
  role_based_access_control_enabled = true
  automatic_channel_upgrade         = "patch"
  sku_tier                          = "Standard"
  api_server_access_profile {
    authorized_ip_ranges = concat(var.api_server_authorized_ip_ranges, ["${data.azurerm_public_ip.loadbalancer-saas-buildagent.ip_address}/32"])
  }

  identity {
    type = "SystemAssigned"
  }
  default_node_pool {
    name                         = "system"
    enable_auto_scaling          = true
    min_count                    = var.min_system_agent_count
    max_count                    = var.max_system_agent_count
    vm_size                      = "Standard_E4ds_v5"
    os_disk_type                 = "Ephemeral"
    max_pods                     = 110
    only_critical_addons_enabled = true
    vnet_subnet_id               = azurerm_subnet.k8s-subnet.id
  }

  network_profile {
    load_balancer_sku  = "standard"
    network_plugin     = "azure"
    network_policy     = "calico"
    service_cidr       = "10.140.0.0/14"
    docker_bridge_cidr = "172.17.0.1/16"
    dns_service_ip     = "10.140.0.101"
  }

  maintenance_window {
    allowed {
      day   = "Monday"
      hours = [0, 23]
    }
    allowed {
      day   = "Tuesday"
      hours = [0, 23]
    }
    allowed {
      day   = "Wednesday"
      hours = [0, 23]
    }
    allowed {
      day   = "Thursday"
      hours = [0, 23]
    }
    allowed {
      day   = "Friday"
      hours = [0, 23]
    }
    allowed {
      day   = "Saturday"
      hours = [0, 23]
    }
    allowed {
      day   = "Sunday"
      hours = [0, 23]
    }
  }

  lifecycle {
    prevent_destroy = true
  }

  tags = {
  }
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: updating Managed Cluster (Subscription: "SUBSCRIPTIONID"
│ Resource Group Name: "RESOURCEGROUPNAME"
│ Managed Cluster Name: "CLUSTERNAME"): managedclusters.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="SkuNotAvailable" Message="Standard managed cluster SKU tier is invalid. 'Paid' has been replaced by 'Standard' since v2023-02-01. "
│ 
│   with azurerm_kubernetes_cluster.k8s,
│   on k8s.tf line 1, in resource "azurerm_kubernetes_cluster" "k8s":
│    1: resource "azurerm_kubernetes_cluster" "k8s" {
│ 
╵
```

### Expected Behaviour

Changing the value in the terraformstate fromPaid to Standard

### Actual Behaviour

Azure returns an error message, that Paid has been replaced by Standard

### Steps to Reproduce

1. terraform apply with sku_tier = Paid
2. terraform apply with sku_tier = Standard

### References

#20734 sku_tier standard was introduced in azurerm v3.46.0

**Comment by stevehipwell** [comment] 2023-03-14 11:13
@Mahagon I saw a similar error when testing `v3.46.0` straight after release and I suspect that it might due to the way the Azure API/machinery is deployed. If you wait for [v2023-02-26](https://github.com/Azure/AKS/releases/tag/2023-02-26) to have been [released](https://releases.aks.azure.com/) in your region and try again does it work?

**Comment by Mahagon** [comment] 2023-03-14 16:25
Not sure if i read it wrong, but i guess "Currently in Operation" means it's released right?

Our AKS is deployed in "Germany West Central" and the "Currently in Operation" version is [v20230226](https://github.com/Azure/AKS/releases/tag/2023-02-26).

Still getting the same error

**Comment by stevehipwell** [comment] 2023-03-14 16:55
> Not sure if i read it wrong, but i guess "Currently in Operation" means it's released right?

@Mahagon it should do.

I've not tried this since the version rolled out in our regions but based on it still being broken for you on the latest version I think there might be a provider bug.

**Comment by mcscwizzy** [comment] 2023-03-15 16:33
Ran into this issue today as well, so it is definitely a provider problem.

**Comment by stevehipwell** [comment] 2023-03-15 22:15
I spoke to some of the AKS team today and they confirmed that the API version would be globally available before it was published and usable, I was confusing the AKS release versions which are also date based. So this is a provider issue.

**Comment by george-zubrienko** [comment] 2023-03-28 08:38
The easiest fix for this would be if the provider can update this field in the state on next plan, instead of requesting a cluster SKU upgrade (imo).

**Comment by zioproto** [comment] 2023-03-28 08:39
@lonegunmanb @jiaweitao001 please be aware of this issue. An email has been sent to AKS customers today about this issue.
![Screenshot 2023-03-28 at 10 38 37](https://user-images.githubusercontent.com/789701/228179264-0e52c9fe-458f-49c8-abca-f59c0062b5cf.png)

**Comment by lra** [comment] 2023-03-28 15:20
We got the email from Azure, and we can't update anything from "Paid" to "Standard" because of this issue. This is really confusing when you get this error message:
```
Original Error: Code="SkuNotAvailable" Message="Standard managed cluster SKU tier is invalid. 'Paid' has been replaced by 'Standard' since v2023-02-01. "
```

**Comment by lonegunmanb** [comment] 2023-03-29 02:38
I'd like to submit a pr to solve this issue by doing following change:

1. Upgrade aks client sdk's version from `2023-01-02-preview` to `2023-02-01`.
2. Create a new `pluginsdk.StateUpgraderFunc` struct which would change `sku_tier` from `Paid` to `Standard`.
3. If user set `sku_tier` to `Paid`, then we still send `Standard` to the API.
4. Update readme, warn our users that they should change `Paid` to `Standard` soon since `Paid` has been deprecated.

In general we should submit a seprate pr to upgrade sdk, but in this case we must update existing state and all corresponding logic with new API.

WDYT @stephybun ?

**Comment by ptisma** [comment] 2023-03-31 13:21
> We got the email from Azure, and we can't update anything from "Paid" to "Standard" because of this issue. This is really confusing when you get this error message:
> 
> ```
> Original Error: Code="SkuNotAvailable" Message="Standard managed cluster SKU tier is invalid. 'Paid' has been replaced by 'Standard' since v2023-02-01. "
> ```
> 
> For context we are running the latest version of everything and are on lots of regions:
> 
> ```
> Terraform v1.4.2
> on darwin_arm64
> + provider registry.terraform.io/hashicorp/azurerm v3.49.0
> ```
> 
> The portal already show our clusters on Standard, but not the API: ![Capture d’écran 2023-03-28 à 17 25 43](https://user-images.githubusercontent.com/122286/228288197-bc7607a6-c4b4-4ae3-bdc2-b6e83fdd9957.png)
> 
> ```
>     },
>     "sku": {
>       "name": "Basic",
>       "tier": "Paid"
>     },
> ```

I am getting the same error but using the provider: hashicorp/azurerm version 3.50.0

**Comment by boliu83** [comment] 2023-04-02 04:09
> 
> Literally same thing except I am using the azurerm version 3.50.0, any update on this?

it seems even azurerm 3.50.0 is still using managedcluster API version 2023-01-02-preview so it doesn't support SKU name Base yet.   just use "Paid" sku tier for now until newer azurerm using managedcluster API version v2023-02-01 or higher

**Closed** 2023-04-04 06:48 UTC
Labels: bug, upstream/microsoft, service/kubernetes-cluster, sdk/requires-newer-api-version
