### ISSUE TITLE
Adding domain_name_label to azurerm_public_ip doesn't export fqdn

### ISSUE THREAD

**Issue by PowerOfCreation** [hashicorp/terraform-provider-azurerm#24941] opened 2024-02-20 08:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.3

### AzureRM Provider Version

3.91.0

### Affected Resource(s)/Data Source(s)

azurerm_public_ip,local_file

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "aks" {
  name     = "demo"
  location = "westeurope"
}

resource "random_pet" "domain_name" {
    keepers = {
        rg_id = azurerm_resource_group.aks.id
    }
}

resource "azurerm_public_ip" "aks_load_balancer_ip" {
  name                = "aks-load-balancer-ip"
  resource_group_name = azurerm_resource_group.aks.name
  location            = azurerm_resource_group.aks.location
  allocation_method   = "Static"
  domain_name_label   = "${random_pet.domain_name.id}-demo" # Create this resource without this first
}


resource "local_file" "product_values" {
  filename = "product-values.yaml"
  content  = templatefile("${path.module}/product-values.tpl", {
    domain_name = azurerm_public_ip.aks_load_balancer_ip.fqdn
  })
}
```

### Debug Output/Panic Output

```shell
~ resource "azurerm_public_ip" "aks_load_balancer_ip" {
      + domain_name_label       = "vocal-ape-test-hub"
        id                      = "/subscriptions/[MASKED]/resourceGroups/demo/providers/Microsoft.Network/publicIPAddresses/aks-load-balancer-ip"
        name                    = "aks-load-balancer-ip"
        tags                    = {}
        # (11 unchanged attributes hidden)
    }

   on aks-cluster.tf line 69, in resource "local_file" "product_values":
│   69:   content  = templatefile("${path.module}/product-values.tpl", {
│   70:     # domain_name = "${azurerm_dns_zone.aks.name}"
│   71:     domain_name = azurerm_public_ip.aks_load_balancer_ip.fqdn
│   72:   })
│     ├────────────────
│     │ while calling templatefile(path, vars)
│     │ azurerm_public_ip.aks_load_balancer_ip.fqdn is null
│     │ path.module is "."
```

### Expected Behaviour

According to the documentation as soon as I add domain_name_label there should be a fqdn attribute available.

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/public_ip#fqdn

### Actual Behaviour

There is no fqdn attribute available.

### Steps to Reproduce

1. Create this with terraform apply
```tf
resource "azurerm_resource_group" "aks" {
  name     = "demo"
  location = "westeurope"
}

resource "random_pet" "domain_name" {
    keepers = {
        rg_id = azurerm_resource_group.aks.id
    }
}

resource "azurerm_public_ip" "aks_load_balancer_ip" {
  name                = "aks-load-balancer-ip"
  resource_group_name = azurerm_resource_group.aks.name
  location            = azurerm_resource_group.aks.location
  allocation_method   = "Static"
  # domain_name_label   = "${random_pet.domain_name.id}-demo" # Create this ressouce without this
}
```
2. Add the domain_name_label attribute to azurerm_public_ip.aks_load_balancer_ip as well as this new resource:

```tf
resource "local_file" "product_values" {
  filename = "product-values.yaml"
  content  = templatefile("${path.module}/product-values.tpl", {
    domain_name = azurerm_public_ip.aks_load_balancer_ip.fqdn
  })
}
```

3. Run terraform plan

**Comment by neil-yechenwei** [comment] 2024-02-22 06:57
Thanks for raising this issue. Seems I can get the fqdn with below tf config after domain_name_label is set. Could you try below tf config and latest azurerm provider to see if the issue still exists? Thanks.

tf config:
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-pip-test01"
  location = "westeurope"
}

resource "azurerm_public_ip" "test" {
  name                = "acctestpublicip-test01"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  allocation_method   = "Static"
  domain_name_label   = "acctestdnl-test01"
}

output "fqdn" {
  value = azurerm_public_ip.test.fqdn
}
```

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/19754191/a27cdbd3-37cd-4cb3-aa8c-70ef15ef1c11)

**Comment by rcskosir** [comment] 2024-04-24 19:25
Thanks for taking the time to submit this issue. @neil-yechenwei  was unable to reproduce this behavior. We’re going to close this issue for now, but if you run into this again with the latest Terraform and Provider versions, please feel free to [open a new issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/new/choose).

**Closed by rcskosir** 2024-04-24 19:25 UTC
Labels: waiting-response, service/network, v/3.x
