### ISSUE TITLE
Unable to destroy VM protected items with soft delete enabled

### ISSUE THREAD

**Issue by mpjtaylor** [hashicorp/terraform-provider-azurerm#15438] opened 2022-02-15 17:09 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform 1.1.4
AzureRm 2.90 or 2.95

### Affected Resource(s)

azurerm_backup_protected_vm

### Terraform Configuration Files

```hcl
data "azurerm_backup_policy_vm" "policy" {
  count               = local.backup
  name                = local.vm_backuppolicy
  recovery_vault_name = data.azurerm_recovery_services_vault.vault.name
  resource_group_name = data.azurerm_recovery_services_vault.vault.resource_group_name
  depends_on          = [data.azurerm_recovery_services_vault.vault]
}

resource "azurerm_backup_protected_vm" "backup" {
  count               = local.backup
  recovery_vault_name = data.azurerm_recovery_services_vault.vault.name
  resource_group_name = data.azurerm_recovery_services_vault.vault.resource_group_name
  source_vm_id        = local.virtual_machine_id
  backup_policy_id    = data.azurerm_backup_policy_vm.policy[0].id
}

resource "azurerm_recovery_services_vault" "support" {
  name                = var.vault_name
  location            = var.primary_location
  resource_group_name = var.resource_group_name
  sku                 = var.sku
  soft_delete_enabled = true
}

```

### Debug Output

Error: waiting for Azure Backup protected VM context deadline exceeded

### Expected Behaviour

The virtual machine and backup should be removed from the vault

### Actual Behaviour

Virtual machine cannot be destroyed, the error
Error: waiting for Azure Backup protected VM context deadline exceeded

### Steps to Reproduce

1. `terraform plan`
1. `terraform apply`

### References

[* #4276](https://github.com/hashicorp/terraform-provider-azurerm/issues/4276)

**Comment by tombuildsstuff** [comment] 2022-02-16 15:48
Duplicate of #4276

**Closed by tombuildsstuff** 2022-02-16 15:48 UTC
