### ISSUE TITLE
Provider produced inconsistent final plan when creating private endpoint for Mongodb Atlas

### ISSUE THREAD

**Issue by ammarasheikh** [hashicorp/terraform-provider-azurerm#23212] opened 2023-09-07 14:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

v1.5.6

### AzureRM Provider Version

3.71.0

### Affected Resource(s)/Data Source(s)

azurerm_private_endpoint

### Terraform Configuration Files

```hcl
private_endpoints = [
    {
      name                = "mongo-private-endpoint"
      location            = module.resource_group.location
      resource_group_name = module.resource_group.name

      existing_subnet = {
        virtual_network_name = "xxxxxxxxxxxxxxxxxxx"
        subnet_name          = "xxxxxxxxxxxx"
        resource_group_name  = "xxxxxxxxxxxx"
      }

      private_service_connections = [{
        is_manual_connection = true
        request_message      = "Azure Private Link"
      }]
  }]
```

### Debug Output/Panic Output

```shell
Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.mongodbatlas_project.module.private_endpoints["mongo-alert-poc-pe"].azurerm_private_endpoint.endpoint to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/azurerm" changed the planned action from Update to DeleteThenCreate.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.mongodbatlas_project.module.private_endpoints["mongo-alert-poc-pe"].azurerm_private_endpoint.endpoint to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/azurerm" produced an invalid new value for .custom_dns_configs: was known, but now unknown.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
```

**Comment by neil-yechenwei** [comment] 2023-09-08 08:06
Thanks for raising this issue. Seems I can't reproduce this issue with below tf config that is similar with yours. Could you try below tf config to see if the issue still exists? If it still exists, could you provide a simplest tf config that triggers this issue since you just provided tf variables and it's hard to us to repro the issue? Thanks.

```
provider "azurerm" {
  features {}
}

data "azurerm_subscription" "current" {}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-privatelink-test01"
  location = "westeurope"
}

resource "azurerm_virtual_network" "test" {
  name                = "acctestvnet-test01"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location
  address_space       = ["10.5.0.0/16"]
}

resource "azurerm_subnet" "service" {
  name                 = "acctestsnetservice-test01"
  resource_group_name  = azurerm_resource_group.test.name
  virtual_network_name = azurerm_virtual_network.test.name
  address_prefixes     = ["10.5.1.0/24"]

  enforce_private_link_service_network_policies = true
}

resource "azurerm_subnet" "endpoint" {
  name                 = "acctestsnetendpoint-test01"
  resource_group_name  = azurerm_resource_group.test.name
  virtual_network_name = azurerm_virtual_network.test.name
  address_prefixes     = ["10.5.2.0/24"]

  enforce_private_link_endpoint_network_policies = true
}

resource "azurerm_public_ip" "test" {
  name                = "acctestpip-test01"
  sku                 = "Standard"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  allocation_method   = "Static"
}

resource "azurerm_lb" "test" {
  name                = "acctestlb-test01"
  sku                 = "Standard"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  frontend_ip_configuration {
    name                 = azurerm_public_ip.test.name
    public_ip_address_id = azurerm_public_ip.test.id
  }
}

resource "azurerm_private_link_service" "test" {
  name                           = "acctestPLS-test01"
  location                       = azurerm_resource_group.test.location
  resource_group_name            = azurerm_resource_group.test.name
  auto_approval_subscription_ids = [data.azurerm_subscription.current.subscription_id]
  visibility_subscription_ids    = [data.azurerm_subscription.current.subscription_id]

  nat_ip_configuration {
    name      = "primaryIpConfiguration-test01"
    primary   = true
    subnet_id = azurerm_subnet.service.id
  }

  load_balancer_frontend_ip_configuration_ids = [
    azurerm_lb.test.frontend_ip_configuration.0.id
  ]
}

resource "azurerm_private_endpoint" "test" {
  name                = "acctest-privatelink-test01"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location
  subnet_id           = azurerm_subnet.endpoint.id

  private_service_connection {
    name                              = azurerm_private_link_service.test.name
    is_manual_connection              = true
    request_message                   = "Azure Private Link"
    private_connection_resource_alias = azurerm_private_link_service.test.alias
  }
}
```

**Comment by rcskosir** [comment] 2023-12-06 22:40
Thanks for taking the time to submit this issue. @neil-yechenwei was unable to reproduce this behavior. We’re going to close this issue for now, but if you run into this again with the latest Terraform and Provider versions, please feel free to [open a new issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/new/choose).

**Closed by rcskosir** 2023-12-06 22:40 UTC
Labels: bug, waiting-response, service/network, v/3.x
