### ISSUE TITLE
Databricks got replaced while modifying the tags associated with it

### ISSUE THREAD

**Issue by animsri** [hashicorp/terraform-provider-azurerm#14994] opened 2022-01-17 10:58 UTC
We have created databricks workspace & cluster in azure using terraform. As a part of the change when we have updated the tags found that databricks workspace & cluster got deleted and recreated with the latest tags which led to the loss of notebooks and data created in it, while other resources replace the tags in place with the latest tags but databricks had a different behaviour than other resources.
We are using the latest azurerm package (v2.89.0). Is there any bug or it’s a usual behaviour of databricks?

**Comment by mybayern1974** [comment] 2022-01-17 11:18
@animsri thank you for opening this issue. By checking the [tags property](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/databricks_workspace#tags) within the Databricks resource, updating `tags` is not expected to trigger resource recreation. And I intuitively assume whether there were other properties rather than `tag` got changed at your environment that made recreation happen. To help troubleshoot, could you please provide your terraform config as well as repro steps on how you changed that `tags`?

**Comment by animsri** [comment] 2022-01-17 11:55
Below is the definition of module
resource "azurerm_databricks_workspace" "databrick" {
  name                        = "${var.databrick_name}"
  resource_group_name         = "${var.resource_group_name}"
  location                    = "${var.location}"
  sku                         = "${var.databrick_sku}"
  managed_resource_group_name = "${var.databrick_name}-DBW-managed-resource-group"
  public_network_access_enabled             = true
  # network_security_group_rules_required     = "NoAzureDatabricksRules"

  custom_parameters {
    no_public_ip        = true
    public_subnet_name  = "${azurerm_subnet.public.name}"
    private_subnet_name = "${azurerm_subnet.private.name}"
    virtual_network_id  = "${var.virtual_network_id}"

    public_subnet_network_security_group_association_id  = "${azurerm_subnet_network_security_group_association.public.id}"
    private_subnet_network_security_group_association_id = "${azurerm_subnet_network_security_group_association.private.id}"
  }
  tags = "${var.tags}"
}

We are calling from main.tf as definition below
module "databricks" {
  source = "../modules/databricks"
  databrick_name = "${var.databrick_name}"
  vnet_resource_group_name = "${var.vnet_resource_group_name}"
  resource_group_name = "${var.resource_group_name}"
  location = "${var.location}"
  databrick_sku = "${var.databrick_sku}"
  vnet_name = "${var.vnet_name}"
  virtual_network_id = "${data.azurerm_virtual_network.vnet.id}"
  public_sn_address_prefix = "${var.public_sn_address_prefix}"
  private_sn_address_prefix = "${var.private_sn_address_prefix}"
  tags = "${merge(var.default_tags,tomap({type="data-databricks"}))}"
   depends_on = [
    module.resource_group,
  ]
}

changes in tags:
before
default_tags = {
  environment = "DEV"
  User        = "DATA"
}
After:
default_tags = {
  environment = "DEV"
  User        = "DATA"
 Stream = "Data"
}

We observed that databricks workspace got deleted and recareted with updated tags

**Comment by WodansSon** [comment] 2022-01-21 04:41
@animsri, I am not able to reproduce your reported issue internally. Here is how I attempted to reproduce your reported issue.

1. Created a vars file which contained the default values as stated in your "before" case like this:
```
variable "default_tags" {
  default     = {"environment" = "DEV", "User" = "DATA"}
  description = "Default resource tags"
  type        = map(string)
}
```
2. I created the  `azurerm_databricks_workspace` via Terraform with the following configuration file:
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "repo" {
  name     = "repo-databricks-14994"
  location = "eastus2"
}

resource "azurerm_virtual_network" "repo" {
  name                = "repo-vnet"
  location            = azurerm_resource_group.repo.location
  resource_group_name = azurerm_resource_group.repo.name
  address_space       = ["10.0.0.0/16"]
}

resource "azurerm_subnet" "public" {
  name                 = "repo-sn-public"
  resource_group_name  = azurerm_resource_group.repo.name
  virtual_network_name = azurerm_virtual_network.repo.name
  address_prefixes     = ["10.0.1.0/24"]

  delegation {
    name = "repo"

    service_delegation {
      name = "Microsoft.Databricks/workspaces"

      actions = [
        "Microsoft.Network/virtualNetworks/subnets/join/action",
        "Microsoft.Network/virtualNetworks/subnets/prepareNetworkPolicies/action",
        "Microsoft.Network/virtualNetworks/subnets/unprepareNetworkPolicies/action",
      ]
    }
  }
}

resource "azurerm_subnet" "private" {
  name                 = "repo-sn-private"
  resource_group_name  = azurerm_resource_group.repo.name
  virtual_network_name = azurerm_virtual_network.repo.name
  address_prefixes     = ["10.0.2.0/24"]

  delegation {
    name = "repo"

    service_delegation {
      name = "Microsoft.Databricks/workspaces"

      actions = [
        "Microsoft.Network/virtualNetworks/subnets/join/action",
        "Microsoft.Network/virtualNetworks/subnets/prepareNetworkPolicies/action",
        "Microsoft.Network/virtualNetworks/subnets/unprepareNetworkPolicies/action",
      ]
    }
  }
}

resource "azurerm_network_security_group" "nsg" {
  name                = "repo-nsg-private"
  location            = azurerm_resource_group.repo.location
  resource_group_name = azurerm_resource_group.repo.name
}

resource "azurerm_subnet_network_security_group_association" "public" {
  subnet_id                 = azurerm_subnet.public.id
  network_security_group_id = azurerm_network_security_group.nsg.id
}

resource "azurerm_subnet_network_security_group_association" "private" {
  subnet_id                 = azurerm_subnet.private.id
  network_security_group_id = azurerm_network_security_group.nsg.id
}

resource "azurerm_databricks_workspace" "repo" {
  name                        = "repoDBW"
  resource_group_name         = azurerm_resource_group.repo.name
  location                    = azurerm_resource_group.repo.location
  sku                         = "standard"
  managed_resource_group_name = "repoRG-DBW-managed"

  custom_parameters {
    no_public_ip        = true
    public_subnet_name  = azurerm_subnet.public.name
    private_subnet_name = azurerm_subnet.private.name
    virtual_network_id  = azurerm_virtual_network.repo.id

    public_subnet_network_security_group_association_id  = azurerm_subnet_network_security_group_association.public.id
    private_subnet_network_security_group_association_id = azurerm_subnet_network_security_group_association.private.id
  }

  tags = var.default_tags
}
```
3. I then manually created a cluster and workbook in my workspace via Portal UI then I updated the tags in the configuration file like this:
````
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "repo" {
  name     = "repo-databricks-14994"
  location = "eastus2"
}

resource "azurerm_virtual_network" "repo" {
  name                = "repo-vnet"
  location            = azurerm_resource_group.repo.location
  resource_group_name = azurerm_resource_group.repo.name
  address_space       = ["10.0.0.0/16"]
}

resource "azurerm_subnet" "public" {
  name                 = "repo-sn-public"
  resource_group_name  = azurerm_resource_group.repo.name
  virtual_network_name = azurerm_virtual_network.repo.name
  address_prefixes     = ["10.0.1.0/24"]

  delegation {
    name = "repo"

    service_delegation {
      name = "Microsoft.Databricks/workspaces"

      actions = [
        "Microsoft.Network/virtualNetworks/subnets/join/action",
        "Microsoft.Network/virtualNetworks/subnets/prepareNetworkPolicies/action",
        "Microsoft.Network/virtualNetworks/subnets/unprepareNetworkPolicies/action",
      ]
    }
  }
}

resource "azurerm_subnet" "private" {
  name                 = "repo-sn-private"
  resource_group_name  = azurerm_resource_group.repo.name
  virtual_network_name = azurerm_virtual_network.repo.name
  address_prefixes     = ["10.0.2.0/24"]

  delegation {
    name = "repo"

    service_delegation {
      name = "Microsoft.Databricks/workspaces"

      actions = [
        "Microsoft.Network/virtualNetworks/subnets/join/action",
        "Microsoft.Network/virtualNetworks/subnets/prepareNetworkPolicies/action",
        "Microsoft.Network/virtualNetworks/subnets/unprepareNetworkPolicies/action",
      ]
    }
  }
}

resource "azurerm_network_security_group" "nsg" {
  name                = "repo-nsg-private"
  location            = azurerm_resource_group.repo.location
  resource_group_name = azurerm_resource_group.repo.name
}

resource "azurerm_subnet_network_security_group_association" "public" {
  subnet_id                 = azurerm_subnet.public.id
  network_security_group_id = azurerm_network_security_group.nsg.id
}

resource "azurerm_subnet_network_security_group_association" "private" {
  subnet_id                 = azurerm_subnet.private.id
  network_security_group_id = azurerm_network_security_group.nsg.id
}

resource "azurerm_databricks_workspace" "repo" {
  name                        = "repoDBW"
  resource_group_name         = azurerm_resource_group.repo.name
  location                    = azurerm_resource_group.repo.location
  sku                         = "standard"
  managed_resource_group_name = "repoRG-DBW-managed"

  custom_parameters {
    no_public_ip        = true
    public_subnet_name  = azurerm_subnet.public.name
    private_subnet_name = azurerm_subnet.private.name
    virtual_network_id  = azurerm_virtual_network.repo.id

    public_subnet_network_security_group_association_id  = azurerm_subnet_network_security_group_association.public.id
    private_subnet_network_security_group_association_id = azurerm_subnet_network_security_group_association.private.id
  }

  tags = merge(var.default_tags,{type="data-databricks"})
}
````
The above worked exactly as expected and after the `tag` update I did not observe any data loss. I believe that some other value is being inadvertently changed which causes the workspace to be destroyed and then  re-created. If this answers your question please feel free to close this issue, if you have more questions feel free to reply. 🚀

**Comment by animsri** [comment] 2022-01-21 10:36
thanks @WodansSon  for helping out.

We have enabled this option in databricks workspace creation .
public_network_access_enabled = true

and it is also changing the 
network_security_group_rules_required which we haven't provided as it optional.

Could you please try with below databricks_workspace code:

`resource "azurerm_databricks_workspace" "repo" {
  name                        = "repoDBW"
  resource_group_name         = azurerm_resource_group.repo.name
  location                    = azurerm_resource_group.repo.location
  sku                         = "standard"
  managed_resource_group_name = "repoRG-DBW-managed"
  public_network_access_enabled = true
  custom_parameters {
    no_public_ip        = true
    public_subnet_name  = azurerm_subnet.public.name
    private_subnet_name = azurerm_subnet.private.name
    virtual_network_id  = azurerm_virtual_network.repo.id

    public_subnet_network_security_group_association_id  = azurerm_subnet_network_security_group_association.public.id
    private_subnet_network_security_group_association_id = azurerm_subnet_network_security_group_association.private.id
  }

  tags = merge(var.default_tags,{type="data-databricks"})
}`

**Comment by animsri** [comment] 2022-01-21 10:37
Even i have added the lifecycle policy to ignore change in network_security_group_rules_required it still recreating the databricks after every execution

**Comment by SamanSattari** [comment] 2022-07-28 08:13
@animsri I see the reported issue is quite old. Did you manage to solve this issue?

**Comment by rcskosir** [comment] 2024-03-21 19:35
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!

**Closed by rcskosir** 2024-03-21 19:35 UTC
Labels: question, service/databricks, v/2.x (legacy)
