### ISSUE TITLE
Support for azurerm_data_protection_backup_instance_postgresql_flexible_server and azurerm_data_protection_backup_policy_postgresql_flexible_server

### ISSUE THREAD

**Issue by jargoPL** [hashicorp/terraform-provider-azurerm#24036] opened 2023-11-27 11:48 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

we need ASAP in terraform to have data protection backup like it is for a single server.

for now for single we can create policies:

resource “azurerm_data_protection_backup_policy_postgresql”

we can create a backup for it:
resource “azurerm_data_protection_backup_instance_postgresql”

we need the same for flexible server, since single server will be depracated anyway.

### New or Affected Resource(s)/Data Source(s)

azurerm_protected_backup

### References

We can create vault backup:

`resource "azurerm_data_protection_backup_vault" "backup_vault_prod" {
  name                = "some-backup-vault"
  resource_group_name = var.resource_group_name
  location            = var.location
  datastore_type      = "VaultStore"
  redundancy          = "LocallyRedundant"
  tags                = var.tags
  identity {
    type = "SystemAssigned"
  }
}
`

we cant create for now for flexible server:

`resource "azurerm_data_protection_backup_policy_postgresql_**flexible_server**" "backup_policy" {
  name                = "some-prod-backup-policy"
  resource_group_name = var.resource_group_name
  vault_name          = azurerm_data_protection_backup_vault.backup_vault_prod.name
  backup_repeating_time_intervals = ["R/2023-11-22T02:30:00+00:00/P1W"]
  default_retention_duration = "P12M"`

`resource "azurerm_data_protection_backup_instance_postgresql_**flexible_server**" "db_backup_prod" {
  name             = "some-prod"
  location         = var.location
  vault_id         = azurerm_data_protection_backup_vault.backup_vault_prod.id
  database_id      = var.database_id
  backup_policy_id = azurerm_data_protection_backup_policy_postgresql.backup_policy.id
}`

**Comment by neil-yechenwei** [comment] 2023-12-07 09:05
Thanks for raising this issue. Seems this feature is still in preview per the description in Azure Portal.

**Comment by jargoPL** [comment] 2023-12-07 09:10
Yes it is in preview, but cant we just implement this into azurerm?

**Comment by mybayern1974** [comment] 2023-12-12 04:49
@jargoPL There might be potential regression issues to have AzureRM support Azure preview features, because preview features do not guarantee its backward and forward feature compatibility. E.g. If AzureRM supports it now but this feature will have new versions in the future which however would include breaking changes to the current preview versions, it would be uneasy for AzureRM to catch up with that new version because it's on purpose to bring as few breaking changes as possible to Terraform AzureRM. 

Per the perspective of having people experience this feature in TF: 1) [Terraform AzAPI provider](https://learn.microsoft.com/en-us/azure/developer/terraform/overview-azapi-provider) could be an option 2) We can offline contact with the postgre sql service team to get their insights on whether the current feature could be stable though being marked as preview. When we have any feedback from them we will update here.

**Comment by Xangliev** [comment] 2024-03-26 09:08
Hi @mybayern1974, are there any updates? We would love to have this feature.

**Comment by mybayern1974** [comment] 2024-04-01 02:27
@Xangliev , the latest info I got days ago from the Azure Postgresql service team is the expected feature here is not GA'ed. So it's not the right time for Terraform AzureRM to support this feature right now. As for the timeline of that feature being GA'ed, suggest you could contact the target Azure service team.

**Comment by jargoPL** [comment] 2024-04-01 16:28
I have got info from Microsoft. Its gonna be ready in this semester.
For now Microsoft even turned off CMK for long term backup and its also gonna be up again in semester

**Comment by mepand** [comment] 2024-04-10 06:14
The tentative ETA for GA of LTR support for Azure backup for PostgreSQL Flexible server is end of Q2 CY 2024.

**Comment by vakaobr** [comment] 2024-05-03 08:24
Hello there @mybayern1974 can we get an expected ETA for this feature be introduced as part of AzureRM provider ? Since Microsoft are pushing customers to get off single servers and migrate to Flexible Servers, it should be expected feature parity to be in place ASAP.

**Closed** 2024-06-21 02:23 UTC
Labels: enhancement, preview, service/backup
