### ISSUE TITLE
Can't upgrade azurerm_postgres_flexible_server from12,13,14,15 to version 16

### ISSUE THREAD

**Issue by shaikriyaz-user** [hashicorp/terraform-provider-azurerm#25344] opened 2024-03-21 07:41 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

0.12.31

### AzureRM Provider Version

3.96.0

### Affected Resource(s)/Data Source(s)

azurerm_postgres_flexible_server

### Terraform Configuration Files

```hcl
Error: updating Flexible Server (Subscription: "xyz"
Resource Group Name: "azure_infra"
Flexible Server Name: "postgres"): performing Update: unexpected status 400 with error: ParameterOutOfRange: The value of the 'Version' should be in: [13,14,15]. Verify that the specified parameter value is correct.

  with azurerm_postgresql_flexible_server.postgres_server
```

### Debug Output/Panic Output

```shell
Error: updating Flexible Server (Subscription: "xyz"
Resource Group Name: "azure_infra"
Flexible Server Name: "postgres"): performing Update: unexpected status 400 with error: ParameterOutOfRange: The value of the 'Version' should be in: [13,14,15]. Verify that the specified parameter value is correct.

  with azurerm_postgresql_flexible_server.postgres_server
```

### Expected Behaviour

Should be upgraded to version 16 

### Steps to Reproduce

Create postgresql-db v12|13|14|15 version using terraform
change the version to 16
terraform apply

**Comment by neil-yechenwei** [comment] 2024-03-22 08:43
Thanks for raising this issue. It's service limitation. Service team confirmed that PG16 can't be upgraded from other versions.

**Comment by rcskosir** [comment] 2024-06-04 16:32
Thanks for taking the time to submit this issue. On review, we’ve determined that the described behavior is not under our control due to a service limitation noted above by @neil-yechenwei. As such, I am going to close this issue for now.

**Closed by rcskosir** 2024-06-04 16:32 UTC
Labels: bug, waiting-response, upstream/microsoft, service/postgresql, v/3.x
