### ISSUE TITLE
Terraform plan for Private Endpoint always leads to 5min timeout

### ISSUE THREAD

**Issue by mkemmerz** [hashicorp/terraform-provider-azurerm#16754] opened 2022-05-12 07:36 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

Terraform plan always takes 5 minutes as it runs into a timeout for planning the "azurerm_private_endpoint.private_service_connection".

### Terraform Version

1.1.9

### AzureRM Provider Version

3.5.0

### Affected Resource(s)/Data Source(s)

"azurerm_private_endpoint" and its "private_service_connection"-block

### Terraform Configuration Files

```hcl
resource "azurerm_private_endpoint" "private_endpoint" {
  name                = var.private_endpoint_name
  location            = var.location
  resource_group_name = var.resource_group_name
  subnet_id           = var.subnet_id

  private_service_connection {
    name                           = var.private_endpoint_connection_name
    is_manual_connection           = var.is_manual_connection
    private_connection_resource_id = var.target_resource_id
    subresource_names              = var.subresources_name
  }
}
```

### Debug Output/Panic Output

```shell
[TRACE] provider.terraform-provider-azurerm_v3.5.0_x5: Called downstream: @module=sdk.proto tf_req_id=2d813928-3dc2-dad3-1081-f5724ed7cd81 tf_resource_type=azurerm_key_vault tf_rpc=ReadResource tf_proto_version=5 tf_provider_addr=provider @caller=github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:558 timestamp=2022-05-12T06:48:06.431Z
[TRACE] provider.terraform-provider-azurerm_v3.5.0_x5: Served request: tf_provider_addr=provider tf_rpc=ReadResource @caller=github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:564 @module=sdk.proto tf_proto_version=5 tf_req_id=2d813928-3dc2-dad3-1081-f5724ed7cd81 tf_resource_type=azurerm_key_vault timestamp=2022-05-12T06:48:06.431Z
[ERROR] vertex "module.xxx" error: retrieving `contact` for KeyVault: keyvault.BaseClient#GetCertificateContacts: Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded
[TRACE] vertex "module.xxx": visit complete, with errors
[TRACE] vertex "module.xxx": dynamic subgraph encountered errors: retrieving `contact` for KeyVault: keyvault.BaseClient#GetCertificateContacts: Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded
[ERROR] vertex "module.xxx" error: retrieving `contact` for KeyVault: keyvault.BaseClient#GetCertificateContacts: Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded
[TRACE] vertex "module.xxx": visit complete, with errors
[TRACE] vertex "module.xxx (expand)": dynamic subgraph encountered errors: retrieving `contact` for KeyVault: keyvault.BaseClient#GetCertificateContacts: Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded
[ERROR] vertex "module.xxx (expand)" error: retrieving `contact` for KeyVault: keyvault.BaseClient#GetCertificateContacts: Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded
[TRACE] vertex "module.xxx (expand)": visit complete, with errors
[TRACE] dag/walk: upstream of module.xxx.xxx.azurerm_monitor_diagnostic_setting.diagnostic_settings (expand)" errored, so skipping
[TRACE] dag/walk: upstream of module.xxx.xxx.key_vault_name (expand)" errored, so skipping
[TRACE] dag/walk: upstream of module.xxx.xxx.key_vault_id (expand)" errored, so skipping
[TRACE] dag/walk: upstream of module.xxx.xxx.var.target_resource_id (expand)" errored, so skipping
[TRACE] dag/walk: upstream of module.xxx.xxxx (close)" errored, so skipping
[TRACE] dag/walk: upstream of module.xxx.terraform-private-endpoint-kv.azurerm_private_endpoint.private_endpoint (expand)" errored, so skipping
[TRACE] dag/walk: upstream of module.xxx.terraform-private-endpoint-kv.output.private_ip_address (expand)" errored, so skipping

Provider "registry.terraform.io/hashicorp/azurerm" produced an invalid plan for module.xx.xxx.terraform-xx.azurerm_private_endpoint.private_endpoint, but we are tolerating it because it is using the legacy plugin SDK.
The following problems may be the cause of any confusing errors from downstream operations:
09:17:34        - .tags: planned value cty.MapValEmpty(cty.String) for a non-computed attribute
09:17:34        - .private_service_connection[0].private_connection_resource_alias: planned value cty.StringVal("") for a non-computed attribute
09:17:34        - .private_service_connection[0].request_message: planned value cty.StringVal("") for a non-computed attribute
09:17:34  2022-05-12T07:17:23.150Z [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
09:17:34  2022-05-12T07:17:23.154Z [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/azurerm/3.5.0/linux_amd64/terraform-provider-azurerm_v3.5.0_x5 pid=485
09:17:34  2022-05-12T07:17:23.181Z [DEBUG] provider: plugin exited
09:17:34  2022-05-12T07:17:23.183Z [INFO]  backend/local: plan operation completed
09:17:34  2022-05-12T07:17:23.185Z [INFO]  backend/local: writing plan output to: plan.out
```

### Expected Behaviour

Terraform plan returns quickly after planning the private endpoint.

### Actual Behaviour

Terraform plan always takes 5 minutes as it runs into a timeout for planning the "azurerm_private_endpoint.private_service_connection". Terraform can continue with terraform apply then. The delayis annoying but not breaking.

e.g.
Terraform plan starts at 9:30
Terraform plan ends at 9:35
continue with terraform apply

### Steps to Reproduce

terraform plan

**Comment by joshua-hancox** [comment] 2023-03-02 08:48
I think this is maybe the same as https://github.com/hashicorp/terraform-provider-azurerm/issues/15792, I also have the same problem and added a comment there.

**Comment by rcskosir** [comment] 2024-03-21 19:13
Thanks for taking the time to submit this issue. It looks like this is a duplicate of #15792. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of #15792.

**Closed by rcskosir** 2024-03-21 19:13 UTC
Labels: duplicate, question, v/3.x
