### ISSUE TITLE
Data source azurerm_storage_container fails

### ISSUE THREAD

**Issue by bpons-mir** [hashicorp/terraform-provider-azurerm#25545] opened 2024-04-09 13:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.5

### AzureRM Provider Version

3.98.0

### Affected Resource(s)/Data Source(s)

data azurerm_storage_container

### Terraform Configuration Files

```hcl
data "azurerm_storage_container" "example" {
  name                 = "example"
  storage_account_name = data.azurerm_storage_account.example.name
}
```

### Debug Output/Panic Output

```shell
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: retrieving Container ***example*** (Account ***Account ***example*** (IsEdgeZone false / ZoneName *** / Subdomain Type ***blob*** / DomainSuffix ***core.windows.net***)***): executing request: unexpected status 403 (403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.) with response: ﻿<?xml version=***1.0*** encoding=***utf-8***?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
│ RequestId:XXXX-YYYYYY
│ Time:<TIMESTAMP></Message><AuthenticationErrorDetail>The MAC signature found in the HTTP request 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' is not the same as any computed signature. Server used following string to sign: 'GET
│ 
│ 
│ 
│ 
│ application/xml; charset=utf-8
│ 
│ 
│ 
│ 
│ 
│ 
│ x-ms-date:<TIMESTAMP>
│ x-ms-version:2023-11-03
│ /example/example
│ restype:container'.</AuthenticationErrorDetail></Error>
│ 
│   with data.azurerm_storage_container.example,
│   on storage_data_sources.tf line 12, in data ***azurerm_storage_container*** ***example***:
│   12: data ***azurerm_storage_container*** ***example*** {
```

### Expected Behaviour

It should be able to read the container data source

### Actual Behaviour

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: retrieving Container ***example*** (Account ***Account ***example*** (IsEdgeZone false / ZoneName *** / Subdomain Type ***blob*** / DomainSuffix ***core.windows.net***)***): executing request: unexpected status 403 (403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.) with response: ﻿<?xml version=***1.0*** encoding=***utf-8***?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
│ RequestId:XXXX-YYYYYY
│ Time:<TIMESTAMP></Message><AuthenticationErrorDetail>The MAC signature found in the HTTP request 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' is not the same as any computed signature. Server used following string to sign: 'GET
│ 
│ 
│ 
│ 
│ application/xml; charset=utf-8
│ 
│ 
│ 
│ 
│ 
│ 
│ x-ms-date:<TIMESTAMP>
│ x-ms-version:2023-11-03
│ /example/example
│ restype:container'.</AuthenticationErrorDetail></Error>
│ 
│   with data.azurerm_storage_container.example,
│   on storage_data_sources.tf line 12, in data ***azurerm_storage_container*** ***example***:
│   12: data ***azurerm_storage_container*** ***example*** {

### Steps to Reproduce

Upgrade to azurerm v3.98.0

### Important Factoids

Breaking change with azurerm v3.98.0, works 3.97.1

**Comment by rcskosir** [comment] 2024-04-09 14:34
@bpons-mir Thanks for taking the time to submit this issue. It looks like this is a duplicate of #25527 with the same underlying problem. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of #25527. Please subscribe to #25527 for updates.

**Closed by rcskosir** 2024-04-09 14:34 UTC
Labels: duplicate, service/storage, v/3.x
