### ISSUE TITLE
`azurerm_kubernetes_cluster_node_pool` churns when priority is set to `Spot`

### ISSUE THREAD

**Issue by stevehipwell** [hashicorp/terraform-provider-azurerm#25615] opened 2024-04-15 09:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.7

### AzureRM Provider Version

3.99.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster_node_pool

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster_node_pool" "example" {
  name                  = "internal"
  kubernetes_cluster_id = azurerm_kubernetes_cluster.example.id
  vm_size               = "Standard_DS2_v2"
  node_count            = 1
  priority              = "Spot"
}
```

### Debug Output/Panic Output

```shell
# module.aks.module.node_groups.module.user_node_groups["example"].azurerm_kubernetes_cluster_node_pool.default must be replaced
-/+ resource "azurerm_kubernetes_cluster_node_pool" "default" {
      - custom_ca_trust_enabled = false -> null
      - eviction_policy         = "Delete" -> null # forces replacement
      ~ id                      = "/subscriptions/xxxx/resourceGroups/yyyyy/providers/Microsoft.ContainerService/managedClusters/example/agentPools/example" -> (known after apply)
        name                    = "example"
      ~ node_count              = 1 -> (known after apply)
      ~ node_labels             = {
          - "kubernetes.azure.com/scalesetpriority" = "spot" -> null
            # (4 unchanged elements hidden)
        }
      ~ node_taints             = [
          - "kubernetes.azure.com/scalesetpriority=spot:NoSchedule",
        ]
        # (22 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```

### Expected Behaviour

When creating a `azurerm_kubernetes_cluster_node_pool` resource with `priority` set to `Spot` and everything else set to the default I'd expect no churn when re-running Terraform with no changes.

### Actual Behaviour

The resource churns with the `custom_ca_trust_enabled`, `eviction_policy`, `node_labels` & `node_taints` fields not being correctly stored in state.

If I explicitly set the `eviction_policy` value both it and `custom_ca_trust_enabled` no longer churn.

### Steps to Reproduce

1. Create node pool with spot priority
2. Re-run `terraform plan`

**Comment by ms-henglu** [comment] 2024-04-16 07:48
Hi @stevehipwell ,

Thank you for taking time to open this issue!

But I think this is the expected behavior, it seems that creating a node pool which `priority = "Spot"` should also configure the node labels and node taints like the following:

```hcl
resource "azurerm_kubernetes_cluster_node_pool" "example" {
  name                    = "internal"
  kubernetes_cluster_id   = azurerm_kubernetes_cluster.example.id
  vm_size                 = "Standard_DS2_v2"
  node_count              = 1
  priority                = "Spot"
  custom_ca_trust_enabled = false
  eviction_policy         = "Delete"
  node_labels = {
    "kubernetes.azure.com/scalesetpriority" = "spot"
  }
  node_taints = [
    "kubernetes.azure.com/scalesetpriority=spot:NoSchedule"
  ]
}
```

**Comment by stevehipwell** [comment] 2024-04-16 07:59
@ms-henglu those values are the documented defaults and are all created correctly on the ARM side. It's the Terraform state not capturing them correctly which is the defect. The state Terraform is trying to revert to is invalid as none of those fields can be null.

**Comment by tombuildsstuff** [comment] 2024-04-16 09:10
@stevehipwell the [fields are optional in the Resource in question](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster_node_pool), so you'll need to set them in your Terraform Configuration to remove the diff here - else (as is happening here) Terraform will detect that these values exist on the API side but aren't in your Terraform Configuration, and plan to remove them (which because these are ForceNew, will recreate the node pool).

As such unfortunately this isn't a bug in the Provider, whilst ARM might be setting these default values (which Terraform is in turn setting into the state) - Terraform is correctly highlighting that there's a difference between the Terraform Configuration and the State/Azure API, and hence raising the diff - so this is working as expected. Alternatively should you wish to use the Azure Provided values you can also [use the `ignore_changes` functionality in Terraform Core](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#ignore_changes).

However since this is configuration question raising a legitimate diff (which can be resolved by setting the appropriate value for these fields) rather than a bug in the Provider, I'm going to close this issue for the moment.

Thanks!

**Closed by tombuildsstuff** 2024-04-16 09:10 UTC
Labels: question, service/kubernetes-cluster, v/3.x

**Comment by stevehipwell** [comment] 2024-04-16 09:35
@tombuildsstuff I'm aware of the workaround, but this behaviour is either not working as documented or not working as expected.

> An Eviction Policy can only be configured when priority is set to `Spot` and will default to `Delete` unless otherwise specified.

For `eviction_policy`; the comment above from the [docs](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster_node_pool#eviction_policy) refers to there being a default of `Delete` so this isn't working as documented.

For `node_labels` & `node_taints`; if defaults have to be explicitly provided then shouldn't this be documented? Personally I think this is poor UX and a leaking abstraction that devalues the IaC pattern here, but that's a separate discussion.
