### ISSUE TITLE
azurerm_storage_account not available for BlockBlobStorage account but cannot remove from terraform file

### ISSUE THREAD

**Issue by jcoqueret** [hashicorp/terraform-provider-azurerm#25207] opened 2024-03-11 16:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.4

### AzureRM Provider Version

3.90.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "cache" {
  name                            = "accountname"
  resource_group_name             = "rgname"
  location                        = "eastus"
  account_kind                    = "BlockBlobStorage"
  account_tier                    = "Premium"
  account_replication_type        = "LRS"
  min_tls_version                 = "TLS1_2"
  allow_nested_items_to_be_public = false
  enable_https_traffic_only       = true
}
```

### Debug Output/Panic Output

```shell
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: 1 error occurred:
│       * `access_tier` is only available for accounts of kind: [BlobStorage StorageV2 FileStorage]
│
│
│
│   with azurerm_storage_account.cache,
│   on storage_cache.tf line 1, in resource "azurerm_storage_account" "cache":
│    1: resource "azurerm_storage_account" "cache" {
│
```

### Expected Behaviour

I updated the AzureRM from 3.85.0 to 3.90.0 (the error still exist with 3.95.0).
I know have that error message but cannot remove the `access_tier` property from my terraform file without having the error :
`The argument "account_tier" is required, but no definition was found.`

I expect to execute a plan without any error. If the `Premium` value is the only supported value for a `BlockBlobStorage` account, I should be able to keep that value in the file

**Comment by magodo** [comment] 2024-03-12 03:30
@jcoqueret This issue duplicates to https://github.com/hashicorp/terraform-provider-azurerm/issues/24793, please find the detail and solution from that issue.

Also note that the difference between `access_tier` and `account_tier`:

> I know have that error message but cannot remove the access_tier property from my terraform file without having the error :
The argument "account_tier" is required, but no definition was found.

**Comment by rcskosir** [comment] 2024-03-12 16:58
Thanks for taking the time to submit this issue. It looks like this is a duplicate of #24793. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of #24793.

**Closed by rcskosir** 2024-03-12 16:58 UTC
Labels: duplicate, question, service/storage, v/3.x
