### ISSUE TITLE
Crash on `azurerm_kubernetes_cluster` since v3.29.0

### ISSUE THREAD

**Issue by lra** [hashicorp/terraform-provider-azurerm#19045] opened 2022-10-28 13:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.3

### AzureRM Provider Version

3.29.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "kube_cluster" {
  dns_prefix          = var.name
  kubernetes_version  = var.kubernetes_version
  location            = var.location
  name                = var.name
  node_resource_group = "MC_${var.name}"
  resource_group_name = var.resource_group_name
  sku_tier            = "Paid"

  # if anything about this changes the cluster must be recreated
  # so this is a small, almost no-op pool
  # workloads are meant to be put on non-default pools
  default_node_pool {
    enable_auto_scaling   = true
    enable_node_public_ip = false
    max_count             = 1
    max_pods              = 250
    min_count             = 1
    name                  = "pool0"
    orchestrator_version  = var.kubernetes_version
    type                  = "VirtualMachineScaleSets"
    vm_size               = "Standard_D2s_v4"
    zones                 = var.availability_zones == tolist([0]) || var.resource_group_name == "REDACTED" ? null : var.availability_zones
    vnet_subnet_id        = var.vnet_subnet_id
    tags                  = local.tags
  }

  network_profile {
    load_balancer_sku = "standard"
    network_plugin    = "azure"
    network_policy    = "azure"
    load_balancer_profile {
      outbound_ip_address_ids = var.outbound_ip_ids
      # Default port allocation for small amounts of nodes is low
      # See cluster specification doc for more info
      outbound_ports_allocated = local.outbound_ports_per_node
      idle_timeout_in_minutes  = 20
    }
  }

  role_based_access_control_enabled = true
  azure_active_directory_role_based_access_control {
    managed = true
  }

  identity {
    type = "SystemAssigned"
  }

  linux_profile {
    admin_username = "REDACTED"

    ssh_key {
      key_data = module.ssh_pub_key.public_key
    }
  }

  auto_scaler_profile {
    balance_similar_node_groups   = var.availability_zones == null || var.availability_zones == tolist([0]) ? false : true
    skip_nodes_with_local_storage = false
    skip_nodes_with_system_pods   = var.environment == "prod" || var.environment == "uat" ? true : false
  }

  tags = merge(local.tags, { name = var.name })
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: Plugin did not respond
│ 
│   with module.stack.module.kube_cluster.azurerm_kubernetes_cluster.kube_cluster,
│   on ../../modules/az-aks/main.tf line 63, in resource "azurerm_kubernetes_cluster" "kube_cluster":
│   63: resource "azurerm_kubernetes_cluster" "kube_cluster" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.

[...] (pages of request cancelled

Releasing state lock. This may take a few moments...

Stack trace from the terraform-provider-azurerm_v3.29.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1042ab09c]

goroutine 21833 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/containers.resourceKubernetesClusterRead(0x14001c1ae80, {0x1058d94c0?, 0x14000564c00})
	github.com/hashicorp/terraform-provider-azurerm/internal/services/containers/kubernetes_cluster_resource.go:1885 +0x66c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x1062fba88?, {0x1062fba88?, 0x14001b5eb10?}, 0xd?, {0x1058d94c0?, 0x14000564c00?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.18.0/helper/schema/resource.go:712 +0x138
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0x1400069d420, {0x1062fba88, 0x14001b5eb10}, 0x14002dce270, {0x1058d94c0, 0x14000564c00})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.18.0/helper/schema/resource.go:1015 +0x46c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x1400049e618, {0x1062fba88?, 0x14001b5ea50?}, 0x14002699800)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.18.0/helper/schema/grpc_provider.go:613 +0x40c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x14000af5e00, {0x1062fba88?, 0x14001b5e540?}, 0x1400311dda0)
	github.com/hashicorp/terraform-plugin-go@v0.10.0/tfprotov5/tf5server/server.go:747 +0x39c
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x105f0db00?, 0x14000af5e00}, {0x1062fba88, 0x14001b5e540}, 0x1400311dd40, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.10.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x174
google.golang.org/grpc.(*Server).processUnaryRPC(0x140002aac40, {0x10630dc18, 0x140005d4680}, 0x140019ab7a0, 0x140016731a0, 0x10a412db0, 0x0)
	google.golang.org/grpc@v1.47.0/server.go:1283 +0xb64
google.golang.org/grpc.(*Server).handleStream(0x140002aac40, {0x10630dc18, 0x140005d4680}, 0x140019ab7a0, 0x0)
	google.golang.org/grpc@v1.47.0/server.go:1620 +0x840
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.47.0/server.go:922 +0x88
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.47.0/server.go:920 +0x298

Error: The terraform-provider-azurerm_v3.29.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behaviour

```
$ terraform plan
No changes. Your infrastructure matches the configuration.
```

### Actual Behaviour

```
$ terraform plan
Error: The terraform-provider-azurerm_v3.29.0_x5 plugin crashed!
```

### Steps to Reproduce

1. Set the version of hashicorp/azurerm to 3.29.0
2. Run `terraform init -upgrade && terraform plan`

### Important Factoids

It works fine on 3.28.0

**Comment by stephybun** [comment] 2022-10-28 15:01
Duplicate of #19044

**Closed by stephybun** 2022-10-28 15:01 UTC
Labels: bug, crash
