### ISSUE TITLE
Getting issue creating Azure Open AI service 

### ISSUE THREAD

**Issue by z-monikas** [hashicorp/terraform-provider-azurerm#23784] opened 2023-11-06 09:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

v1.5.2

### AzureRM Provider Version

3.50.0

### Affected Resource(s)/Data Source(s)

azurerm_cognitive_account

### Terraform Configuration Files

```hcl
provider.tf
-------------------------------------------------------------------------------------------------
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "=3.50.0"
    }
  }
}

provider "azurerm" {
  subscription_id = "XXXXXXXXXXXXXXXXX"
  features {}
}


-------------------------------------------------------------------------------------------------
main.tf
-------------------------------------------------------------------------------------------------

resource "azurerm_resource_group" "ResourceGroup" {
  name     = "Test-ResourceGroup"
  location = "West US"
}

resource "azurerm_role_assignment" "MicrosoftGraph" {
  scope = azurerm_resource_group.ResourceGroup.id
  role_definition_name = "Contributor"
  principal_id = "XXXXXXXXXXXXXXXXXXXXXXXX"
}

resource "azurerm_cognitive_account" "Authoring" {
  name                = "test-Authoring"
  location            = azurerm_resource_group.ResourceGroup.location
  resource_group_name = azurerm_resource_group.ResourceGroup.name
  kind                = "LUIS.Authoring"

  sku_name = "F0"



  depends_on = [
    azurerm_resource_group.ResourceGroup
  ]
}

resource "azurerm_cognitive_account" "App" {
  name                = "testApp"
  location            = azurerm_resource_group.ResourceGroup.location
  resource_group_name = azurerm_resource_group.ResourceGroup.name
  kind                = "LUIS"

  sku_name = "S0"


  depends_on = [
    azurerm_resource_group.ResourceGroup
  ]
}

resource "azurerm_cognitive_account" "ReportingApp" {
  name                = "test-ReportingApp"
  location            = azurerm_resource_group.ResourceGroup.location
  resource_group_name = azurerm_resource_group.ResourceGroup.name
  kind                = "LUIS"

  sku_name = "S0"



  depends_on = [
    azurerm_resource_group.ResourceGroup
  ]
}

resource "azurerm_storage_account" "storage_account" {
  name                     = var.storage_name
  resource_group_name      = azurerm_resource_group.ResourceGroup.name
  location                 = azurerm_resource_group.ResourceGroup.location
  account_tier             = "Standard"
  account_replication_type = "GRS"


  depends_on = [
    azurerm_resource_group.ResourceGroup
  ]
}

resource "azurerm_cognitive_account" "SpeechServices" {
  name                = "test-SpeechServices"
  location            = azurerm_resource_group.ResourceGroup.location
  resource_group_name = azurerm_resource_group.ResourceGroup.name
  kind                = "SpeechServices"
  sku_name            = "S0"
}

resource "azurerm_monitor_diagnostic_setting" "diagnostic" {
  name               = var.diagnostic_setting
  target_resource_id = azurerm_cognitive_account.SpeechServices.id
  storage_account_id = azurerm_storage_account.storage_account.id

  log {
    category = "Audit"
    enabled  = true

    retention_policy {
      enabled = true
      days = 0
    }
  }

  log {
    category = "Trace"
    # enabled  = True

    retention_policy {
      enabled = true
      days = 0
    }
  }

  metric {
    category = "AllMetrics"

    retention_policy {
      enabled = true
      days = 0
    }
  }

  depends_on = [
    azurerm_resource_group.ResourceGroup,
    azurerm_storage_account.storage_account,
    azurerm_cognitive_account.SpeechServices
  ]
}

resource "azurerm_cognitive_account" "OpenAIResource" {
  name                = "z-test"
  location            = "East US"
  resource_group_name = azurerm_resource_group.ResourceGroup.name
  kind                = "OpenAI"
  sku_name            = "S0"
}

resource "azurerm_cognitive_deployment" "Deployment" {
  name                 = "test_v1"
  cognitive_account_id = azurerm_cognitive_account.OpenAIResource.id
  model {
    format  = "OpenAI"
    name    = "gpt-35-turbo"
    version = "0301"
  }

  scale {
    type = "Standard"
  }
}
```

### Debug Output/Panic Output

```shell
Issue 1:
Whenever we are created resources manually on azure portal its creating endpoint as below 
https://z-brand.openai.azure.com/
but using terraform script we are getting different endpoint which is 
https://eastus.api.cognitive.microsoft.com/ and this endpoint is same for all resources .

Issue 2
We need endpoint to be Resource name specific i.e, we need resource name in the endpoint.
```

### Expected Behaviour

We want endpoint to be like mentioned below where z-brand keep on changing as per resource name 
https://z-brand.openai.azure.com/

### Actual Behaviour

We are getting same endpoint for all resources 

https://eastus.api.cognitive.microsoft.com/

### Steps to Reproduce

terraform apply

### Important Factoids

No

### References

None

**Comment by liuwuliuyun** [comment] 2023-11-07 01:26
Hi @z-monikas, thanks for raising this issue. I am able to reproduce this locally and looking into this feature request. Will update you in this thread.

**Comment by liuwuliuyun** [comment] 2023-11-07 01:36
Hi @z-monikas , you could change the custom domain by [custom_subdomain_name](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cognitive_account#custom_subdomain_name) in azurerm_cognitive_account. 

Here is an example that is working: 
```
provider "azurerm" {
  features {}

}

resource "azurerm_resource_group" "example" {
  name     = "tfexample-resources"
  location = "West Europe"
}

resource "azurerm_cognitive_account" "example" {
  name                = "yunliuexample-ca"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  custom_subdomain_name = "yunliuexample"
  kind                = "OpenAI"
  sku_name            = "S0"
}

resource "azurerm_cognitive_deployment" "example" {
  name                 = "tttexample-cd"
  cognitive_account_id = azurerm_cognitive_account.example.id
  model {
    format  = "OpenAI"
    name    = "gpt-35-turbo"
    version = "0301"
  }

  scale {
    type = "Standard"
  }
}
```

**Comment by z-monikas** [comment] 2023-11-09 05:59
Hi @liuwuliuyun,

I am getting below error when I made modification . 

**[31m│[0m [0mResource Group Name: "ABCResourceGroup"
[31m│[0m [0mAccount Name: "z-ABC"): cognitiveservicesaccounts.CognitiveServicesAccountsClient#AccountsCreate: Failure sending request: StatusCode=0 -- Original Error: Code="CustomDomainInvalid" Message="Sub domain name 'https://z-ABC.openai.azure.com/' is not valid."[0m**

FYI: I do no want to create a subdomain I am trying to create endpoint of an Open AI resource.

**Comment by liuwuliuyun** [comment] 2023-11-10 03:36
Hi @z-monikas , I just tried again with my sub and it works fine. Could you upgrade your provider version to latest and try again? Thanks. Here is the resource I created. 
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/17947406/f1d6d020-9c64-4c31-9af8-3d92c958f6c9)

**Comment by rcskosir** [comment] 2024-01-24 20:44
Thanks for taking the time to submit this issue. It looks like this has been resolved with the above help from @liuwuliuyun. As such, I am going to mark this issue as closed. If that is not the case, please provide additional information including the version in which you are still experiencing this issue and if there's any differences in PROD that could be affecting it, thanks!

**Closed by rcskosir** 2024-01-24 20:44 UTC
Labels: waiting-response, service/cognitive-services, v/3.x
