### ISSUE TITLE
Key vault private dns zone inconsistent result

### ISSUE THREAD

**Issue by singhparavjot** [hashicorp/terraform-provider-azurerm#17950] opened 2022-08-10 09:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.6

### AzureRM Provider Version

3.6.0

### Affected Resource(s)/Data Source(s)

private_dns_zone

### Terraform Configuration Files

```hcl
resource "azurerm_private_dns_zone" "main" {
  name                = var.somename
  resource_group_name = data.azurerm_resource_group.rg.name
}
```

### Debug Output/Panic Output

```shell
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to
│ module.key_vault_private_dns_zone.azurerm_private_dns_zone.private_dns_zone,
│ provider "provider["registry.terraform.io/hashicorp/azurerm"]" produced
│ an unexpected new value: Root resource was present, but now absent.
│
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
```

### Expected Behaviour

this should create private dns zone. 

### Actual Behaviour

On the first run it throws the above error, and if we run the terraform apply it says resource already exists.
Also, terraform plan is always successful i.e in both runs. 

### Steps to Reproduce

terraform apply

### Important Factoids

we are using modules. to resolve either we delete private link or update the state file.

**Comment by jiaweitao001** [comment] 2022-08-11 05:52
Hi @singhparavjot , thanks for opening this issue. We have tried to reproduce the error you pasted above but it seems fine on our end. Could you please provide the whole code snippet so we can conduct some further investigation? Thanks.

**Comment by rcskosir** [comment] 2023-09-28 20:06
Thanks for opening this issue. Since time has passed and @jiaweitao001 was not able to reproduce this issue, I am going to mark this issue closed as “can’t reproduce”. If you are able to provide more information to help us reproduce this issue we may re-open this issue or open a new issue, thanks!

**Closed by rcskosir** 2023-09-28 20:06 UTC
Labels: question, waiting-response, service/dns, v/3.x
