### ISSUE TITLE
When switching from provisioned to serverless Azure SQL instance, error "serverless databases do not support license type" is reported

### ISSUE THREAD

**Issue by benjamincburns** [hashicorp/terraform-provider-azurerm#13209] opened 2021-09-01 13:28 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
Terraform v1.0.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.74.0
+ provider registry.terraform.io/hashicorp/helm v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.3.2
+ provider registry.terraform.io/hashicorp/null v3.1.0
```

### Affected Resource(s)

* `azurerm_mssql_database`

### Terraform Configuration Files

```hcl
resource "azurerm_mssql_database" "db" {
  name                        = "qbs-db-${var.environment}"
  server_id                   = azurerm_mssql_server.dbserver.id
  sku_name                    = var.db_sku_name
  collation                   = "SQL_Latin1_General_CP1_CI_AS"
  max_size_gb                 = 32
  zone_redundant              = false
  read_scale                  = false
  auto_pause_delay_in_minutes = var.db_auto_pause_delay_in_minutes
  geo_backup_enabled          = true
  min_capacity                = var.db_min_capacity

  short_term_retention_policy {
    retention_days = var.db_short_term_retention_in_days
  }

  dynamic long_term_retention_policy {
    for_each = var.db_weekly_backup_retention_iso_duration == "PT0S" ? [] : [1]
    content {
      weekly_retention = var.db_weekly_backup_retention_iso_duration

      # shouldn't be required, but it's necessary to avoid a bug
      # see https://github.com/hashicorp/terraform-provider-azurerm/issues/13035
      week_of_year = 1
    }
  }
}

```

### Expected Behaviour

It should be possible to change from sku `GP_Gen5_2` to `GP_S_Gen5_2` without error.

### Actual Behaviour

The following error is reported:

```
╷
│ Error: serverless databases do not support license type
│
│   with module.controlplane_infra.azurerm_mssql_database.db,
│   on ../../module/db.tf line 33, in resource "azurerm_mssql_database" "db":
│   33: resource "azurerm_mssql_database" "db" {
│
╵
```

### Steps to Reproduce

Configure an `azurerm_mssql_database` resource with sku `GP_Gen5_2` and run a `terraform apply`, then change the sku to `GP_S_Gen5_2` and run `terraform apply` again.

### References

This was encountered when testing a workaround for #13035.

**Comment by MarioArriaga92** [comment] 2022-05-10 19:16
Also experiencing same issue after apply operation after changing `sku_name     = "BC_Gen5_2"` to `sku_name     = "GP_S_Gen5_1"`, any workaround please?

**Comment by JonathonAnderson** [comment] 2022-05-19 16:33
Same issue here

**Comment by golaat** [comment] 2023-02-22 17:44
Is there any ETA on this or updates on this?

**Comment by katbyte** [comment] 2024-01-10 03:31
This is a duplicate of #21373, even thou this is the older issue i am going to close it as there is more discussion on the newer issue

**Closed by katbyte** 2024-01-10 03:31 UTC
Labels: bug, service/mssql, v/3.x, v/2.x (legacy)
