### ISSUE TITLE
postgresql.ServersClient "Requested feature is not enabled"

### ISSUE THREAD

**Issue by p418** [hashicorp/terraform-provider-azurerm#6959] opened 2020-05-15 17:40 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

* terragrunt version v0.23.2
* Terraform v0.12.23
* provider "azurerm" (hashicorp/azurerm) 2.9.0

### Affected Resource(s)

* `azurerm_postgresql_server`

### Terraform Configuration Files

```terraform
terraform {
  required_version = "~>0.12.0"
  backend "azurerm" {}
}

provider "azurerm" {
  version = "~>2.0"
  features {}
}
```

### Actual Behavior

When trying to `terraform apply` an `azurerm_postgresql_server` resource, I'm getting following error message:

```
PostgreSQL Server "my-pg-server" (Resource Group "my-rg"): postgresql.ServersClient#Update: Failure sending request: StatusCode=405 -- Original Error: Code="FeatureSwitchNotEnabled" Message="Requested feature is not enabled"
   on server.tf line 1, in resource "azurerm_postgresql_server" "server"
```

1. `skip_provider_registration` is not set
2. No error when running `terraform plan`
3. The SP I'm using, has `Owner` role within this subscription

It seems to skip registrating `Microsoft.DBforPostgreSQL` provider.

I have to manually run  `az provider register -n Microsoft.DBforPostgreSQL --subscription ...`  to make it work

### Steps to Reproduce

1. `terraform apply`

**Comment by yupwei68** [comment] 2020-05-18 06:33
Hi @p418 , thanks for opening this issue. Sorry that I cannot reproduce your error. Could you provide more about your terraform resource code? And `Microsoft.DBforPostgreSQL `provider is always registered in Terraform code.

**Comment by larsmaes** [comment] 2020-05-19 16:32
Had the same problem but with mysql.
Reverting from 2.10 to 2.9 solved my problem

**Comment by p418** [comment] 2020-05-20 07:04
@yupwei68 thank you for your reply.
here below, informations given by `terraform plan` :

```terraform
 # azurerm_postgresql_database.database[0] will be created
   + resource "azurerm_postgresql_database" "database" {
       + charset             = "UTF8"
       + collation           = "fr-FR"
       + id                  = (known after apply)
       + name                = "myapp"
       + resource_group_name = "rg-xx-xxxx-myapp-frct-01"
       + server_name         = "pgsql-xx-myapp-frct-01"
     }
   # azurerm_postgresql_server.server will be created
   + resource "azurerm_postgresql_server" "server" {
       + administrator_login              = "myapp"
       + administrator_login_password     = (sensitive value)
       + auto_grow_enabled                = false
       + backup_retention_days            = 7
       + create_mode                      = "Default"
       + fqdn                             = (known after apply)
       + geo_redundant_backup_enabled     = (known after apply)
       + id                               = (known after apply)
       + location                         = "francecentral"
       + name                             = "pgsql-xx-myapp-frct-01"
       + public_network_access_enabled    = false
       + resource_group_name              = "rg-xx-xxxx-myapp-frct-01"
       + sku_name                         = "B_Gen5_1"
       + ssl_enforcement                  = (known after apply)
       + ssl_enforcement_enabled          = true
       + ssl_minimal_tls_version_enforced = "TLS1_2"
       + storage_mb                       = 5120
       + tags                             = {
           + "dbmsType"    = "postgresql"
           + "dbmsVersion" = "11"
           + "environment" = "myenv"
           + "owner"       = "myteam"
           + "provider"    = "terraform"
           + "role"        = "xxxx"
           + "service"     = "myapp"
         }
       + version                          = "11"
       + storage_profile {
           + auto_grow             = (known after apply)
           + backup_retention_days = (known after apply)
           + geo_redundant_backup  = (known after apply)
           + storage_mb            = (known after apply)
         }
     }
 Plan: 2 to add, 0 to change, 0 to destroy.
```

@larsmaes I was using 2.9 when posting this issue.
Since 2.10 release, it seems to be worst unfortunaly.

**Comment by thcp** [comment] 2020-05-22 18:30
@yupwei68 could you please check if public_network_access_enabled matches the tier of the database ? it seems that the basic tier doesnt support Private Ip access.

**Comment by katbyte** [comment] 2020-05-22 19:04
thanks for opening this @larsmaes - looks like we'll have to add some validation for this so we can return a more user friendly error message.

**Comment by whiskeysierra** [comment] 2020-11-19 15:55
Has anyone a link to the Azure docs for those limitations? I couldn't find any. @thcp How did you know that's the case?

**Comment by thcp** [comment] 2020-11-19 18:16
@whiskeysierra I had this commented on a issue a while ago but i cant find it , so please check this link: https://docs.microsoft.com/en-us/azure/postgresql/concepts-data-access-and-security-private-link

**Comment by ludflu** [comment] 2020-12-14 20:24
I was able to get this to work by disabling the infrastructure_encryption_enabled flag. (which I guess is the thing that's not yet enabled)

**Comment by favoretti** [comment] 2021-08-19 13:05
Since this issue seems to have been addressed in the latest versions of the provider (or a valid workaround was provided) - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.

**Closed by favoretti** 2021-08-19 13:05 UTC
Labels: service/postgresql
