### ISSUE TITLE
azurerm_resource_group_template_deployment: Multiple outputs of ARM template not supported

### ISSUE THREAD

**Issue by dr-dolittle** [hashicorp/terraform-provider-azurerm#17473] opened 2022-07-01 09:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.4

### AzureRM Provider Version

3.12

### Affected Resource(s)/Data Source(s)

azurerm_resource_group_template_deployment

### Terraform Configuration Files

```hcl
I experienced that when having two outputs in the arm template, `output_content` contains just one. 


"outputs": {
    "resourceId": {
        "type": "String",
        "value": "[resourceId('Microsoft.ServiceBus/namespaces', parameters('name'))]"
    },
    "fullyQualifiedNamespace": {
        "type": "String",
        "value": "[concat(parameters('name'), '.servicebus.windows.net')]"
    }
}
```
------
```
output resource_id {
  description = "The resource id of the Service Bus namespace."
  value = jsondecode(azurerm_resource_group_template_deployment.service_bus_namespace.output_content).resourceId.value
}

output fully_qualified_namespace {
  description = "The fully qualified Service Bus namespace identifier."
  value = jsondecode(azurerm_resource_group_template_deployment.service_bus_namespace.output_content).fullyQualifiedNamespace.value
}
```
```


### Debug Output/Panic Output

```shell
During plan:

│ Error: Unsupported attribute
│ 
│   on ../../modules/service-bus/outputs.tf line 8, in output "fully_qualified_namespace":
│    8:   value = jsondecode(azurerm_resource_group_template_deployment.service_bus_namespace.output_content).fullyQualifiedNamespace.value
│     ├────────────────
│     │ azurerm_resource_group_template_deployment.service_bus_namespace.output_content is "{\"resourceId\":{\"type\":\"String\",\"value\":\"/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.ServiceBus/namespaces/xxx\"}}"
│ 
│ This object does not have an attribute named "fullyQualifiedNamespace".

```
```


### Expected Behaviour

Output property is available

### Actual Behaviour

Property is not available

### Steps to Reproduce

_No response_

### Important Factoids

_No response_

### References

_No response_

**Comment by magodo** [comment] 2022-07-05 02:32
@dr-dolittle I've tried to reproduce this issue via following config:

```shell
...
resource "azurerm_resource_group_template_deployment" "test" {
  name                = "acctest"
  resource_group_name = azurerm_resource_group.test.name
  deployment_mode     = "Complete"
  template_content    = <<TEMPLATE
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {},
  "variables": {
    "v1": "value1",
    "v2": "value2"
  },
  "resources": [],
  "outputs": {
      "o1": {
          "type": "string",
          "value": "[variables('v1')]"
      },
      "o2": {
          "type": "string",
          "value": "[variables('v2')]"
      },
      "o3": {
          "type": "String",
          "value": "[concat(variables('v2'), '.servicebus.windows.net')]"
      }
  }
}
TEMPLATE
}

output "o1" {
  value = jsondecode(azurerm_resource_group_template_deployment.test.output_content).o1.value
}
output "o2" {
  value = jsondecode(azurerm_resource_group_template_deployment.test.output_content).o2.value
}
output "o3" {
  value = jsondecode(azurerm_resource_group_template_deployment.test.output_content).o3.value
}
```

Output:

```shell
Outputs:

o1 = "value1"
o2 = "value2"
o3 = "value2.servicebus.windows.net"
```

While the output LGTM. Did you check whether the config of your `azurerm_resource_group_template_deployment` matches the remote state, i.e. no diff from `terraform plan`.

**Comment by dr-dolittle** [comment] 2022-07-28 06:46
@magodo Thanks for your response.

I tested it again.

First try:
First deployment -> One output in ARM template -> worked
Second deployment -> Added second output -> Failed -> This object does not have an attribute named "testOutput".

Second try:
First deployment -> Both outputs exist from the very beginning -> worked

So, the problem seems to be that adding additional outputs after an initial deployment does not work. If the multiple outputs exist right from the beginning, it works.

Can this be fixed please?

Thanks

**Comment by magodo** [comment] 2022-07-28 08:48
@dr-dolittle In that case, you'll have to: Add the second output in the ARM template -> apply -> Add the TF output variable referencing that new output.

The output var are evaluated during refresh stage in an apply, which in your case is referencing a non existing property, which is available after the apply finishes. Therefore, it raised the error. This is how Terraform core works, and we can hardly do something at the provider side. As this forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community.html). I'm gonna close this issue for now.

**Closed by magodo** 2022-07-28 08:48 UTC
Labels: question, service/resources
