### ISSUE TITLE
Storage Account should not try to use data-plane APIs (e.g. error reading share properties)

### ISSUE THREAD

**Issue by lorenzo-biava** [hashicorp/terraform-provider-azurerm#14792] opened 2022-01-04 15:42 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_storage_account`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behaviour

Unless specific arguments (like `share_properties`) are actively used, the provider should not try to invoke "data-plane" APIs.

The Storage Account APIs are basically split between "control-plane" (always accessible) and "data-plane" (access can be limited via firewall in various setups). A reasonable use case would be to provision and manage the Storage Account via Terraform, but not provide any access to the data-plane to it (e.g. containers could be configured by the end application, so there would be no need for TF to invoke data-plane APIs).

Ideally the data-plane APIs should not be invoked if the properties are not provided), or there should at least be an argument (or flag of sort) to allow to suppress that behavior and let a Storage Account to be managed only in terms of publicly reachable APIs and settings.

See [this code for reference](https://github.com/hashicorp/terraform-provider-azurerm/blob/v2.86.0/internal/services/storage/storage_account_resource.go#L1800), and the various invocation of the specific clients.

### Actual Behaviour

Unfortunately the provider always tries to invoke some data-plane APIs even when there would be no need for it, requiring direct connectivity between the TF runner and the Storage Account.

For instance, you can create a StorageV2 account, and never bother using File Shares, including a property like `share_properties`. However during refresh TF will try to probe such property from the API, failing if data-plane APIs are not reachable.

```
Error: reading share properties for AzureRM Storage Account "XXXXXXX": storage.FileServicesClient#GetServiceProperties: Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded
```

### Steps to Reproduce

Create a Storage Account with kind=StorageV2 and setup firewall rules so Terraform is unable to connect to it.

### References

Similar issues and unexpected behavior can be found in:

* [#12485](https://github.com/hashicorp/terraform-provider-azurerm/issues/12485)
* [#6659](https://github.com/hashicorp/terraform-provider-azurerm/issues/6659)

**Comment by tombuildsstuff** [comment] 2022-01-04 17:36
hi @lorenzo-biava 

Thanks for opening this issue.

Taking a look through this appears to be a duplicate of #2977 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #2977 for updates?

Thanks!

**Closed by tombuildsstuff** 2022-01-04 17:36 UTC
Labels: duplicate, enhancement, service/storage
