### ISSUE TITLE
azurerm_storage_table does not respect storage_use_azuread

### ISSUE THREAD

**Issue by jan-hudec** [hashicorp/terraform-provider-azurerm#23142] opened 2023-08-31 15:50 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.6

### AzureRM Provider Version

3.71.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_table

### Terraform Configuration Files

```hcl
variable "tenant_id" {}
variable "subscription_id" {}
variable "resource_group_name" {}
variable "account_name" {}

terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
    }
  }
}

provider "azurerm" {
  features {}
  skip_provider_registration = true
  tenant_id                  = var.tenant_id
  subscription_id            = var.subscription_id
  storage_use_azuread        = true
}

data "azurerm_client_config" "current" {}

data "azurerm_resource_group" "rg" {
  name = var.resource_group_name
}

resource "azurerm_storage_account" "sa" {
  name                = var.account_name
  resource_group_name = data.azurerm_resource_group.rg.name
  location            = data.azurerm_resource_group.rg.location

  account_tier                    = "Standard"
  account_kind                    = "StorageV2"
  account_replication_type        = "LRS"
  allow_nested_items_to_be_public = false
  shared_access_key_enabled       = false
  default_to_oauth_authentication = true
}

resource "azurerm_role_assignment" "table_contributor" {
  scope                = azurerm_storage_account.sa.id
  role_definition_name = "Storage Table Data Contributor"
  principal_id         = data.azurerm_client_config.current.object_id
}

resource "azurerm_storage_table" "table" {
  name                 = "whatever"
  storage_account_name = azurerm_storage_account.sa.name

  depends_on = [azurerm_role_assignment.table_contributor]
}
```

### Debug Output/Panic Output

```shell
│ Error: checking for existence of existing Storage Table "whatever" (Account "bflmpsvzwtkf" / Resource Group "********"): tables.Client#Exists: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Unknown" Message="Unknown service error" Details=[{"odata.error":{"code":"KeyBasedAuthenticationNotPermitted","message":{"lang":"en-US","value":"Key based authentication is not permitted on this storage account.\nRequestId:********-****-****-****-******000000\nTime:2023-08-31T15:39:45.0517039Z"}}}]
│
│   with azurerm_storage_table.table,
│   on storage-table-aad.tf line 49, in resource "azurerm_storage_table" "table":
│   49: resource "azurerm_storage_table" "table" {


From the debug log it can be seen that keys get listed, but the actual failing request does not seem to be logged.
```

### Expected Behaviour

The table should have been created.

### Actual Behaviour

Authorization fails with error that key authorization is not allowed. But it isn't supposed to be used, the provider configuration says to use AAD auth.

### Steps to Reproduce

Try applying the provided sample script.

Note that Owner permission is needed for the resource group. Contributor can't give themselves the appropriate data-plane role.

### Important Factoids

I can create the table in portal, with az cli (python client) and access it from the dotnet app.

~~Note that it does work when there is no `auxiliary_tenant_ids` configured. Only that specific combination with auxiliary tenants and storage_use_azuread fails.~~

After more testing today, it's clear it does not work without the auxiliary tenant either.

**Comment by magodo** [comment] 2023-09-01 02:08
@jan-hudec Currently, the table resource only support key based auth:

https://github.com/hashicorp/terraform-provider-azurerm/blob/4916dc0c953363e80ec111dd77ab80ec217ce7ac/internal/services/storage/client/client.go#L287-L288

Regardless whether the `auxiliary_tenant_ids` are used or not.

**Comment by jan-hudec** [comment] 2023-09-01 12:58
@magodo, somehow I thought it started to work when I deleted the secondary tenant, but it appears to have been masked by other problems. It does indeed not work.

Tables definitely do support AzureAD authentication. I have the account configured with keys disabled and I can create the tables in portal, can create them with az (python client library) and access them with dotnet client library from the application. So either the comment or the go client library are out of date.

**Comment by jan-hudec** [comment] 2023-09-01 13:14
I should add that I am not using files (yet), but az offers `--auth-mode login` for them as well, which suggests they also support oidc authentication now.

**Comment by tombuildsstuff** [comment] 2023-09-01 13:41
hi @jan-hudec 

Thanks for opening this issue.

This is a known limitation of the Azure API and is currently [documented in Terraform under the `storage_use_azuread` flag](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#storage_use_azuread) - and checking the Data Plane API's AzureAD authentication page [both for all of the Files operations](https://learn.microsoft.com/en-us/rest/api/storageservices/authorize-with-azure-active-directory#permissions-for-file-service-operations) and for [the `Get/Set ACL` operations](https://learn.microsoft.com/en-us/rest/api/storageservices/authorize-with-azure-active-directory#permissions-for-table-service-operations) for Tables - which we'd need to support this.

Whilst we're planning to update the version of the Data Plane API being used in the not-too-distant future, ultimately the limitation is coming from the Azure API here - and so we'd need all of the endpoints that we access via SharedKey authentication to be available via AzureAD authentication in order to support AzureAD authentication for Files/Tables.

Since that limitation is coming from the Azure API and isn't something we can currently workaround in Terraform - I'm going to mark this issue as `upstream/microsoft`, but once that's supported in the Azure API we can take another look into supporting that.

Thanks!

**Comment by jan-hudec** [comment] 2023-09-04 08:23
Ok, I see. I saw tables work with AD authentication and didn't check all operations. Especially those that don't make much sense without AD—since with the shared keys there is no user identity to use in them.

**Comment by jan-hudec** [comment] 2023-09-04 08:47
Since the situation is the same for blobs, queues and tables, I believe there is nothing to wait for and the support can be enabled for tables (though not files, but the issue is for tables).

Thanks.

**Comment by tombuildsstuff** [comment] 2024-01-23 15:03
Dependent on https://github.com/hashicorp/terraform-provider-azurerm/pull/24213

**Comment by xaviergxf** [comment] 2024-02-20 16:33
I've hit the same issue today. Does anyone have a workaround?
When will this be fixed?

Thanks!

**Comment by swisszeni** [comment] 2024-02-21 19:05
We've used the [AzAPI provider](https://registry.terraform.io/providers/Azure/azapi/latest/docs) as a workaround.

Looks something like this:
```terraform
resource "azapi_resource" "my_table" {
  type      = "Microsoft.Storage/storageAccounts/tableServices/tables@2022-09-01"
  name      = "foo"
  parent_id = "${azurerm_storage_account.storage.id}/tableServices/default"
  body = jsonencode({
    properties = {}
  })
}
```

Works reasonably well for us, though we haven't tested all scenarios.

**Comment by manicminer** [comment] 2024-03-01 01:00
As mentioned above, the Storage Tables API now supports AAD authentication and this will be enabled by #24798. Unfortunately this support won't extend to Files at this time, as contrary to official documentation, this API does not properly support AAD authentication as yet.

**Comment by manicminer** [comment] 2024-03-01 01:52
This issue appears to be a duplicate of #15083, so for clarity I'm going to close this issue in favor of that one. Please subscribe to #15083 for further updates, thanks!

**Closed by manicminer** 2024-03-01 01:52 UTC
Labels: service/storage, v/3.x

**Comment by jan-hudec** [comment] 2024-03-04 09:01
> Unfortunately, setting and/or retrieving ACLS for Storage Tables does not support AAD authentication at this time

My understanding is that

1. That's the same situation as for Blobs.
2. The feature is only for key access anyway, so if you are switching to Entra authentication because you want to switch key authentication off, you are not using the feature.
