### ISSUE TITLE
Error when creating App Config Feature - Error response cannot be parsed: "" error: EOF

### ISSUE THREAD

**Issue by mpigram** [hashicorp/terraform-provider-azurerm#15721] opened 2022-03-07 11:44 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v1.1.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azuread v1.2.2
+ provider registry.terraform.io/hashicorp/azurerm v2.97.0.
```

### Affected Resource(s)

* `azurerm_app_configuration_feature'

### Terraform Configuration Files

```hcl
resource "azurerm_app_configuration" "app_config" {
  name                = format("glasswall-appcfg-%s-gwc-filetrust-%s-prm", var.location_short, var.client_name)
  resource_group_name = var.resource_group_name
  location            = var.resource_group_location
  sku                 = "standard"
}

resource "azurerm_app_configuration_feature" "ifm_feature" {
  configuration_store_id = azurerm_app_configuration.app_config.id
  description            = "Feature Flag for In Flight Monitoring"
  name                   = "InflightMonitoring"
  enabled                = false
}
```

### Expected Behaviour

The app config feature should have been created

### Actual Behaviour

The apply errors out with the following:

```hcl
│ Error: got http status code 403 while checking for key's ".appconfig.featureflag/InflightMonitoring" existence: appconfiguration.BaseClient#GetKeyValue: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: error response cannot be parsed: "" error: EOF
│
│   with module.create_app_config.azurerm_app_configuration_feature.ifm_feature,
│   on modules/app-config/main.tf line 8, in resource "azurerm_app_configuration_feature" "ifm_feature":
│    8: resource "azurerm_app_configuration_feature" "ifm_feature" {
│
│ got http status code 403 while checking for key's
│ ".appconfig.featureflag/InflightMonitoring" existence:
│ appconfiguration.BaseClient#GetKeyValue: Failure responding to request:
│ StatusCode=403 -- Original Error: autorest/azure: error response cannot be
│ parsed: "" error: EOF
```
### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by mpigram** [comment] 2022-03-22 10:28
Is anyone available to look at this? Even if it's a "will be solved with 3.0 patch"

**Comment by vanmash** [comment] 2022-03-29 20:08
Hey @manicminer 
any chance for a fix for v2.x?

**Comment by sinbai** [comment] 2022-04-20 06:51
@mpigram  thank you for posting this issue here. Could you try adding the role "App Configuration Data Owner" to resolve this issue? The examples are as follows. 

```
resource "azurerm_resource_group" "test" {
  name     = "rg-sample"
  location = "eastus"
}

data "azurerm_client_config" "test" {
}

resource "azurerm_role_assignment" "test" {
  scope                = azurerm_resource_group.test.id
  role_definition_name = "App Configuration Data Owner"
  principal_id         = data.azurerm_client_config.test.object_id
}

resource "azurerm_app_configuration" "test" {
  name                = "appconf"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location
  sku                 = "standard"
  
  depends_on = [
    azurerm_role_assignment.test,
  ]
}

resource "azurerm_app_configuration_feature" "test" {
  configuration_store_id = azurerm_app_configuration.test.id
  description            = "test description"
  name                   = "ackey"
  label                  = "ackeylabel"
  enabled                = false
}
```

**Comment by vanmash** [comment] 2022-04-20 13:43
Hey @sinbai, thank you for your valuable comment.
I had the same issue, and after adding **App Configuration Data Owner** role, it works for me (azurerm v2.99).

**Comment by sinbai** [comment] 2022-04-28 07:28
> Hey @sinbai, thank you for your valuable comment. I had the same issue, and after adding **App Configuration Data Owner** role, it works for me (azurerm v2.99).

Thanks for your time.

**Comment by sinbai** [comment] 2022-04-28 07:34
@mpigram Would you mind we close this issue if the issue is resolved by adding **App Configuration Data Owner** role?

**Comment by stephybun** [comment] 2022-05-12 06:49
Closing this issue since it is a configuration question - the solution being to add a role for the App Configuration Data Owner.

**Closed by stephybun** 2022-05-12 06:49 UTC
Labels: question, service/app-configuration
