### ISSUE TITLE
azurerm_kubernetes_cluster shows always changes on api_server_access_profile block setting vnet_integration_enabled

### ISSUE THREAD

**Issue by schmidt-i** [hashicorp/terraform-provider-azurerm#23244] opened 2023-09-12 12:05 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.7

### AzureRM Provider Version

3.72.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}


resource "azurerm_kubernetes_cluster" "example" {
  name                = "example-aks1"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  dns_prefix          = "exampleaks1"

  api_server_access_profile {
    authorized_ip_ranges = []
  }

  default_node_pool {
    name       = "default"
    node_count = 1
    vm_size    = "Standard_D2_v2"
  }

  identity {
    type = "SystemAssigned"
  }

  tags = {
    Environment = "Production"
  }
}


```

### Debug Output/Panic Output

```shell
After a successful apply, the next plan run shows a change on the vnet_integration_enabled setting.



resource "azurerm_kubernetes_cluster" "kubernetes_cluster" {
        id                                  = "xxxxxxxxx"
        name                                = "example-aks1"
        tags                                = {
           "Environment" = "Production"
        }

      + api_server_access_profile {
          + vnet_integration_enabled = false
        }
    }
```

### Expected Behaviour

Plan after apply should show no changes on resource level.

### Actual Behaviour

Plan shows change of vnet_integration_enabled property in api_server_access_profile block

### Steps to Reproduce

terraform apply
terraform plan

**Comment by zioproto** [comment] 2023-09-13 09:56
hello @schmidt-i 

I can't reproduce it.

Your sample code have:

```
  api_server_access_profile {
    authorized_ip_ranges         = ["192.168.1.0/24"]
    vnet_integration_enabled     = false
  }
```

Is it correct in the sample code to reproduce the bug to have the line `vnet_integration_enabled     = false` ?

**Comment by zioproto** [comment] 2023-09-13 09:59
Could you clarify if the subscription where you are testing this have the `EnableAPIServerVnetIntegrationPreview` feature flag enabled or disabled ?

https://learn.microsoft.com/en-us/azure/aks/api-server-vnet-integration#register-the-enableapiservervnetintegrationpreview-feature-flag

**Comment by schmidt-i** [comment] 2023-09-13 10:08
Hi @zioproto, the feature is currently not registered in the subscription where we create the aks cluster: 

```
az feature show --namespace "Microsoft.ContainerService" --name "EnableAPIServerVnetIntegrationPreview"
{
  "id": "/subscriptions/xxxxx/providers/Microsoft.Features/providers/microsoft.ContainerService/features/EnableAPIServerVnetIntegrationPreview",
  "name": "microsoft.ContainerService/EnableAPIServerVnetIntegrationPreview",
  "properties": {
    "state": "NotRegistered"
  },
  "type": "Microsoft.Features/providers/features"
}
```

**Comment by lonegunmanb** [comment] 2023-09-13 10:19
Hi @schmidt-i , in your example code:

```hcl
resource "azurerm_kubernetes_cluster" "example" {
```

But in your error message:

```hcl
resource "azurerm_kubernetes_cluster" "kubernetes_cluster" {
```

It seems like different resource instances?

**Comment by zioproto** [comment] 2023-09-13 10:29
@schmidt-i can you paste your output for:

```
az aks show --name example-aks1 -g example-resources  -o json | jq .apiServerAccessProfile
```

thanks

**Comment by schmidt-i** [comment] 2023-09-13 13:28
> hello @schmidt-i
> 
> I can't reproduce it.
> 
> Your sample code have:
> 
> ```
>   api_server_access_profile {
>     authorized_ip_ranges         = ["192.168.1.0/24"]
>     vnet_integration_enabled     = false
>   }
> ```
> 
> Is it correct in the sample code to reproduce the bug to have the line `vnet_integration_enabled = false` ?

Sorry, i adjusted the sample code to have a working example. I just discovered, that the problematic statement is the empty list in the authorized_ip_ranges. Once this list is empty, you cannot have a successful apply and plan. It will always show up changes. 

I just tested to set the list to an IP address and the set it back to an empty list. The former IP address is not deleted and will stay on the resource. 

So I assume the bug is not on the vnet_integration_enabled setting but it occures if the authorized_ip_ranges is set to an empty set: "[]".

I hope you can reproduce this behaviour.

**Comment by stephybun** [comment] 2023-09-13 13:48
Thanks for taking the time to raise this issue @schmidt-i.

Since this is a duplicate of #20085 I'm going to close this to ensure discussions are consolidated in one place/issue.

Please subscribe to #20085 for updates. Thanks!

**Closed by stephybun** 2023-09-13 13:48 UTC
Labels: duplicate, service/kubernetes-cluster, v/3.x
