### ISSUE TITLE
Error managing azurerm_storage_account

### ISSUE THREAD

**Issue by Pasukaru** [hashicorp/terraform-provider-azurerm#17936] opened 2022-08-09 12:37 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.6

### AzureRM Provider Version

3.17.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
terraform {

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.17.0"
    }
  }

  backend "azurerm" {
    resource_group_name  = "tt-tfstate-rg"
    storage_account_name = "tttfstatesa"
    container_name       = "tfstate-test"
    key                  = "terraform.tfstate"
    subscription_id      = "redacted"
    tenant_id            = "redacted"
  }
}

provider "azurerm" {
  features {}

  subscription_id     = "redacted"
  tenant_id           = "redacted"
  storage_use_azuread = true
}

data "azurerm_client_config" "current" {
}


variable "location" {
  type    = string
  default = "germanywestcentral"
}

resource "random_string" "rand" {
  length  = 3
  special = false
  numeric = false
  upper   = false
  lower   = true
}

resource "azurerm_resource_group" "rg" {
  name     = "storage-account-error-test-${random_string.rand.result}"
  location = var.location
  tags     = {
    "MANAGED_BY" = "TERRAFORM"
  }
}

resource "azurerm_storage_account" "st" {
  name                     = "saerrortest${random_string.rand.result}"
  resource_group_name      = azurerm_resource_group.rg.name
  location                 = azurerm_resource_group.rg.location
  account_kind             = "Storage"
  account_tier             = "Standard"
  account_replication_type = "LRS"
  tags                     = {
    "MANAGED_BY" = "TERRAFORM"
  }
}
```

### Debug Output/Panic Output

```shell
Error: reading queue properties for AzureRM Storage Account "stcommonblofm": queues.Client#GetServiceProperties: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationPermissionMismatch" Message="This request is not authorized to perform this operation using this permission.\nRequestId:bb44d582-0003-0023-47e7-ab6554000000\nTime:2022-08-09T12:01:08.5096770Z"
│
│   with azurerm_storage_account.st,
│   on main.tf line 52, in resource "azurerm_storage_account" "st":
│    52: resource "azurerm_storage_account" "st" {

Debug log: https://gist.github.com/Pasukaru/4699a94627ff0115c9176cada0b716fa
```

### Expected Behaviour

There should be no error managing a azurerm_storage_account resource

### Actual Behaviour

On first try (without the resource existing) `terraform apply` is able to create the resource, but it still fails somewhere along the way with the error above.
Subsequent `terraform plan` result in the same error.

Deleting the resource manually and running `terraform apply` ends up with the same behaviour. It creates the resource, but it also throws the error.

### Steps to Reproduce

1. Use the configuration file above (using the `backend "azurem"` storage container for tfstate has to exist beforehand).
2. Plug in your subscription and tenant id
3. Run `terraform apply`

**Comment by Pasukaru** [comment] 2022-08-09 12:52
I just found this related issue:

https://github.com/hashicorp/terraform-provider-azurerm/issues/12138

Looks like this only happens when using the azurerm backend `storage_use_azuread  = true`.

That ticket is stale since sep 29 where it has been marked as duplicate (of what?).

Is there any workaround, other than not using `storage_use_azuread = true`?

**Comment by magodo** [comment] 2022-08-10 06:20
@Pasukaru I've tried locally with above config, with `storage_use_azuread = true`. It works for me with my SP of the `Contributor` role assigned. As is said in the document of [`storage_use_azuread`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#storage_use_azuread):

> This requires that the User/Service Principal being used has the associated Storage roles - which are added to new Contributor/Owner role-assignments, but have not been backported by Azure to existing role-assignments.

You might want to further ensure you have the right role assigned to your SP in order to use `storage_use_azuread = true`.

**Comment by jhyot** [comment] 2022-11-07 17:54
I am the author of the other ticket https://github.com/hashicorp/terraform-provider-azurerm/issues/12138
Based on all your comments I tried again, and it worked if I have the following roles:

* Storage Account Contributor
* Storage Blob Data Owner
* Storage Queue Data Contributor 

Possibly a subset of those roles also works, but I've tried with these and did not perform further tests.

**Comment by webczat** [comment] 2023-08-22 12:24
Note I shouldn't be expected to be able to authenticate to storage account when I create it. for example, if I have public_network_access=false, I am not expected to get access. Also after disabling shared access key authentication, I have no further workaround as removing storage_use_azuread does not work. Somehow previously adding storage_use_azuread=true worked properly in these cases.

**Comment by lucashby** [comment] 2024-01-22 20:48
> Note I shouldn't be expected to be able to authenticate to storage account when I create it. for example, if I have public_network_access=false, I am not expected to get access. Also after disabling shared access key authentication, I have no further workaround as removing storage_use_azuread does not work. Somehow previously adding storage_use_azuread=true worked properly in these cases.

I would try running it a few times.  Sometimes I have to run my plan up to 5 times to get the error to NOT happen.  Sometimes it works the first time.  This tells me it's not something I can just "fix" with any changes, at least none that I can imagine.  By the way, it happens during the refresh on plan, so my solution has been to add a CLI args with -refresh=false and that does the trick, but that also means I'm not looking at the cloud during planning so it's not a long-term solution.

**Comment by magodo** [comment] 2024-01-24 02:20
Hi *, from the conversation so far, it seems like a service issue instead of the provider, as the SP already has the roles needed. Since I can't reproduce it locally, appreciate someone who can reproduce it open an Azure support ticket towards the SRP, with the correlation request id in the error message, to have the service team digging further.

**Comment by rcskosir** [comment] 2024-06-12 19:57
Thanks for taking the time to submit this issue. @magodo was unable to reproduce this behavior and it appears to be an upstream Azure issue. As such we are going to close this issue for now. I recommend opening an Azure support ticket as noted above if you are still seeing this behavior.

**Closed by rcskosir** 2024-06-12 19:57 UTC
Labels: duplicate, question, service/storage, v/3.x
