### ISSUE TITLE
Kubernetes node deployment failed state

### ISSUE THREAD

**Issue by yanxke** [hashicorp/terraform-provider-azurerm#10505] opened 2021-02-09 02:26 UTC
![image](https://user-images.githubusercontent.com/25883626/107307096-ea827e00-6a3a-11eb-975b-14fa6eeefe52.png)

Provisioning timed out, and then existed in failed state, but Terraform thinks it succeed on the next run and did not make any changes.

Using the latest AzureRM version.

**Comment by stephybun** [comment] 2022-02-15 16:06
Hi @yanxke,

Thanks for raising this issue. Since this is missing essential information needed in order to be able to look into this and reproduce the error I am going to close this issue. If this is still a problem with the latest AzureRM provider please feel free to open another issue by filling out this [bug template](https://github.com/hashicorp/terraform-provider-azurerm/issues/new?assignees=&labels=&template=Bug_Report.md). Thanks!

**Closed by stephybun** 2022-02-15 16:06 UTC
Labels: upstream-microsoft, service/kubernetes-cluster
