### ISSUE TITLE
Support for pool rotation in azurerm_kubernetes_cluster_node_pool

### ISSUE THREAD

**Issue by matzexp** [hashicorp/terraform-provider-azurerm#25528] opened 2024-04-07 11:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

I would like to add a Feature to [azurerm_kubernetes_cluster_node_pool](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster_node_pool) which is already present in [azurerm_kubernetes_cluster](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster) in the default_node_pool.

The desired Feature is to have a rotating pool, if one of the currently set parameters is changed, which forces a new pool to be created.

To make this feature not change existing behavior i would propose to add an optional parameter, which only creates a rotating pool if set. So if `temporary_name_for_rotation` is set, the node_pool will create a pool for rotation.

I'd like to implement this feature myself (if it fits into the terraform provider and does not change desired behavior).
It would be nice if someone could point out the files, where i can look up the current implementation of azurerm_kubernetes_cluster for the rotation of the default pool and where i should start implementing the feature for azurerm_kubernetes_cluster_node_pool.

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster_node_pool

### Potential Terraform Configuration

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_kubernetes_cluster" "example" {
  name                = "example-aks1"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  dns_prefix          = "exampleaks1"

  default_node_pool {
    name       = "default"
    node_count = 1
    vm_size    = "Standard_D2_v2"
  }

  service_principal {
    client_id     = "00000000-0000-0000-0000-000000000000"
    client_secret = "00000000000000000000000000000000"
  }
}

resource "azurerm_kubernetes_cluster_node_pool" "example" {
  name                  = "internal"
  kubernetes_cluster_id = azurerm_kubernetes_cluster.example.id
  vm_size               = "Standard_DS2_v2"
  node_count            = 1

  tags = {
    Environment = "Production"
  }

  temporary_name_for_rotation = "tmp"
}
```

**Comment by stephybun** [comment] 2024-04-08 05:39
Thanks for raising this issue @matzexp. I'm going to close this issue since this appears to be a duplicate of #22265, please subscribe to #22265 for updates.

**Closed by stephybun** 2024-04-08 05:39 UTC
