### ISSUE TITLE
Error: Provider produced inconsistent result after apply (storage_account)

### ISSUE THREAD

**Issue by james-mwakichako** [hashicorp/terraform-provider-azurerm#14298] opened 2021-11-22 23:27 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_storage_account`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 2.86.0"
    }
    random = {
      source  = "hashicorp/random"
      version = ">= 3.1.0"
    }
  }
}

provider "azurerm" {
  features {}
}

resource "random_string" "resource_code" {
  length  = 5
  special = false
  upper   = false
}

resource "azurerm_storage_account" "test_account" {
  name                     = join("", [var.prod_storage_account_name, random_string.resource_code.result])
  resource_group_name      = var.resource_group_name
  location                 = var.resource_group_location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  network_rules {
    default_action             = "Deny"
    virtual_network_subnet_ids = var.landing_zone_subnets
  }

  tags = {
    test = "true"
  }
}
```

### Actual Behaviour

`
Error: Provider produced inconsistent result after apply

When applying changes to
module.base_storage_account.azurerm_storage_account.test_account, provider
"registry.terraform.io/hashicorp/azurerm" produced an unexpected new value:
Root resource was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
`

### Steps to Reproduce

Terraform version `0.14.11`
Azurerm provider version `2.86`

1. `terraform apply`

### References

* #0000

**Comment by peter-kipping-seequent** [comment] 2021-11-23 03:13
So we're seeing the same issue, however I can provide some more information, we are only seeing the issue so far in certain azure regions.
When deploying a storage account into 'australiaeast' we **DO NOT** see this issue.
When deploying a storage account into 'canadacentral' we **DO** see this issue

I have also tested and this same issue is happening on an older provider version of '2.79.1'.

**Comment by james-mwakichako** [comment] 2021-11-23 13:45
Thanks @peter-kipping-seequent . We see this issue when deploying into eastus

**Comment by mcwienczek** [comment] 2021-11-25 10:09
I am having similar issue with `azurerm_storage_share_file` in West Europe.

```
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to module.my_module.azurerm_storage_share_file.backup_file_sql   provider "provider[\"registry.terraform.io/hashicorp/azurerm\"]" produced an unexpected new value: Root resource was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

affected provider versions:

definitely 2.86.0 and 2.84.0

**Comment by tombuildsstuff** [comment] 2021-11-26 00:59
Duplicate of #5299 - please subscribe to that issue for updates.

**Closed by tombuildsstuff** 2021-11-26 00:59 UTC
Labels: service/storage, upstream-microsoft

**Comment by peter-kipping-seequent** [comment] 2021-12-14 23:58
@james-mwakichako has this been fixed for you? I dont think my issue was related to #5299 .

In your example above @james-mwakichako your storage account has a 'network_rules' block, and inside that network rules block you have a virtual_network_subnet_ids section listing a subnet id.

Azure has a restriction where you are unable to use a subnet id here if that subnet IS IN A DIFFERENT AZURE REGION to that of the region your storage account is being created in (with some allowance made for 'paired regions').

The issue here is that you are only told of this issue if you attempt to MODIFY an already existing storage account.

So if you take the terraform included above and comment out the network restrictions block it will apply correctly. If you then uncomment the network restrictions block and attempt an apply you get the following error:

`
│ Error: updating Azure Storage Account network_rules "testcreationaccountoqtzl": storage.AccountsClient#Update: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="NetworkAclsValidationFailure" Message="Validation of network acls failure: ResourceBeingAcledHasWrongLocation:Microsoft.Storage resources in System.Linq.Enumerable+<ExceptIterator>d__731[System.String] cannot be ACL-ed to virtual network /subscriptions/<REDACTED>/resourceGroups/<REDACTED>/providers/Microsoft.Network/virtualNetworks/<REDACTED> in australiaeast. Only resources in australiaeast, australiasoutheast can be ACL-ed to virtual networks in australiaeast.."                                                                                                                                                                                                                 │                                                                                                                                                                                                                                                                                                                            │   with azurerm_storage_account.test_account,                                                                                                                                                                                                                                                                               │   on main.tf line 33, in resource "azurerm_storage_account" "test_account":                                                                                                                                                                                                                                                │   33: resource "azurerm_storage_account" "test_account" {                                                                                                                                                                                                                                                         
`

So what i think is happened is Terraform is attempting to create the storage account with a network restriction that it is unable to deploy. Instead of returning the correct error message it instead returns a different error message that doesn't actually indicated the proper misconfiguration.

This was using Terraform 1.1.0 and azurerm provider 2.89.0. @tombuildsstuff do you think this ticket should be reopened or would you like me to create a new ticket for this issue?

**Comment by james-mwakichako** [comment] 2021-12-15 00:04
@peter-kipping-seequent this has not been fixed on my end. The workaround has been to create the storage account and network rules separately like so 
`resource "azurerm_storage_account" "default" {
  name                     = "${var.name}${random_string.resource_code.result}"
  resource_group_name      = var.resource_group_name
  location                 = var.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_storage_container" "default" {
  for_each              = toset(var.environments)
  name                  = each.value
  storage_account_name  = azurerm_storage_account.default.name
  container_access_type = "private"
}

resource "azurerm_storage_account_network_rules" "test" {
  resource_group_name  = var.resource_group_name
  storage_account_name = azurerm_storage_account.default.name

  default_action             = "Deny"
  ip_rules                   = var.ip_rules
  virtual_network_subnet_ids = var.subnet_ids
  bypass                     = ["AzureServices", "Logging", "Metrics"]
}`

**Comment by peter-kipping-seequent** [comment] 2021-12-15 01:10
@james-mwakichako so is the subnet your listing in your 'virtual_network_subnet_ids' section in a different azure region? We're not seeing this issue if the subnet is in the same region, but are seeing it if its in another region.
I cant see how creating the network rules in a different resource block would get around that azure limitation?
That would imply we're seeing different issues here possibly 😢 .

```
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=2.89.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "=3.1.0"
    }
  }
}

provider "azurerm" {
  features {}
}

resource "random_string" "resource_code" {
  length  = 5
  special = false
  upper   = false
}

locals {
  # Change these values
  vnet_location            = "canadacentral"
  storage_account_location = "canadacentral"
  create_storage_account_vnet_rules = true
}

resource "azurerm_resource_group" "rg" {
  name     = "test-resource-group"
  location = local.vnet_location
}

resource "azurerm_virtual_network" "vnet" {
  name                = "test-virual-network"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  address_space       = ["10.0.0.0/16"]
}

resource "azurerm_subnet" "subnet" {
  name                 = "test-subnet"
  resource_group_name  = azurerm_resource_group.rg.name
  virtual_network_name = azurerm_virtual_network.vnet.name
  address_prefixes     = ["10.0.1.0/24"]
  service_endpoints    = ["Microsoft.Storage"]
}

resource "azurerm_storage_account" "test_account" {
  name                = join("", ["testcreationaccount", random_string.resource_code.result])
  location            = local.storage_account_location
  resource_group_name = azurerm_resource_group.rg.name

  account_tier             = "Standard"
  account_replication_type = "RAGRS"
  account_kind             = "StorageV2"
  access_tier              = "Hot"

  network_rules {
    default_action = "Deny"
    bypass         = ["Logging", "Metrics", "AzureServices"]
    virtual_network_subnet_ids = local.create_storage_account_vnet_rules ? [azurerm_subnet.subnet.id] : []
  }
}
```

Given the above and changing the values for only the locals i created this matrix to show where i have an error purely on an apply with no resources created.
![image](https://user-images.githubusercontent.com/75957833/146104137-68b54f47-1ff6-4fa0-9eba-9de8b0302c76.png)


The only other thing to note is that if you apply with option 3 which succeeds, and then update the config to option 4 and attempt to update, it gives the CORRECT error that should happen when you apply option 4 from the start.

**Comment by james-mwakichako** [comment] 2021-12-16 14:22
@peter-kipping-seequent , thanks for sharing this. I see. It could be very well that these issues aren't related. I went ahead and tested your code by deploying the storage account in southcentralus and the subnet in northcentralus successfully. Could your issue be region related ?
