### ISSUE TITLE
provider produced inconsistent final plan

### ISSUE THREAD

**Issue by sreekanth3107** [hashicorp/terraform-provider-azurerm#23983] opened 2023-11-21 20:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.3

### AzureRM Provider Version

3.80.0

### Affected Resource(s)/Data Source(s)

azurerm_key_vault_secret

### Terraform Configuration Files

```hcl
resource "azurerm_key_vault_secret" "iam_user_access_key_id" {
  provider     = azurerm.key_vault
  name         = "iam-user-access-key-id"
  value        = data.aws_ssm_parameter.user_access_key_param.value
  key_vault_id = var.key_vault_id

}

resource "azurerm_key_vault_secret" "iam_user_access_key_secret" {
  provider     = azurerm.key_vault
  name         = "iam-user-access-key-secret"
  value        = data.aws_ssm_parameter.user_access_secret_param.value
  key_vault_id = var.key_vault_id

}
```

### Debug Output/Panic Output

```shell
Error: Provider produced inconsistent final plan
When expanding the plan for azurerm_key_vault_secret.iam_user_access_key_id
to include new values learned so far during apply, provider
"registry.terraform.io/hashicorp/azurerm" produced an invalid new value for
	
.timeouts: was absent, but now present.
	
This is a bug in the provider, which should be reported in the provider's own issue tracker.

	
Error: Provider produced inconsistent final plan
When expanding the plan for
When expanding the plan for azurerm_key_vault_secret.iam_user_access_key_id
learned so far during apply, provider
to include new values learned so far during apply, provider
"registry.terraform.io/hashicorp/azurerm" produced an invalid new value for
	
.timeouts: was absent, but now present.
	
This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

**Comment by jsong336** [comment] 2023-11-23 18:51
I am getting similar error with applying azurerm_storage_container. Last time it was applied on AzureRM Provider Version=3.63.0
When I set TF_LOG=TRACE, I see following warning during planning
```
Provider "registry.terraform.io/hashicorp/azurerm" produced an invalid plan for azurerm_storage_container.###, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .timeouts: planned for existence but config wants absence
 ```

**Comment by jsong336** [comment] 2023-11-23 18:55
> I am getting similar error with applying azurerm_storage_container. Last time it was applied on AzureRM Provider Version=3.63.0 When I set TF_LOG=TRACE, I see following warning during planning
> 
> ```
> Provider "registry.terraform.io/hashicorp/azurerm" produced an invalid plan for azurerm_storage_container.###, but we are tolerating it because it is using the legacy plugin SDK.
>     The following problems may be the cause of any confusing errors from downstream operations:
>       - .timeouts: planned for existence but config wants absence
> ```

Actually I was able to resolve it by going to to tfstate file and manually removing `.timeouts` fields

**Comment by rcskosir** [comment] 2024-02-09 18:47
@sreekanth3107 Thanks for taking the time to submit this issue. Unfortunately, it looks like the configuration you provided is missing some key pieces for us to do a reproduction. Please update this issue with a more complete configuration so that we are able to work on reproducing this and well as include the trace log for the issue with command: `TF_LOG=TRACE terraform apply`. I am going to close this issue for now, but if you are able to provide us with this additional information, we can reopen.

**Closed by rcskosir** 2024-02-09 18:47 UTC
Labels: bug, waiting-response, service/key-vault, v/3.x
