### ISSUE TITLE
Updating a previously imported azurerm_mysql_server followed by another 'apply' results in destroy/replace

### ISSUE THREAD

**Issue by eehret** [hashicorp/terraform-provider-azurerm#6957] opened 2020-05-15 17:26 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.25
+ provider.azurerm v2.10.0

### Affected Resource(s)
* `azurerm_mysql_server`

### Terraform Configuration Files
I don't have time to produce a sample, sorry!  But I'll try to explain very clearly what I'm seeing.

### Expected Behavior
I should be able to update certain attributes of a previously imported azurerm_mysql_server without a destroy/replace.  
Here's the scenario, and what I expect to happen:
1.  Created an Azure Database for MySQL instance in Azure, which was a replica of another instance.
2.  Import this instance using `terraform import`.
3.  Use `terraform state show` to display the imported resource.  It shows that 'create_mode' = 'Default' which seems wrong to me for a replica, so I update this value to 'Replica' and specify the 'creation_source_server_id' property to point to the source node.
4.  Execute `terraform plan`.   It indicates that now there are pending changes to the 'create_mode' and 'creation_source_server_id' attributes, as expected.  There are no other pending changes shown.
5.  Execute `terraform apply` to apply the changes to 'create_mode' and 'creation_source_server_id' attributes.
6.  Execute another `terraform apply`.  It should show no further pending changes.

### Actual Behavior
At step 6 above, instead of showing no further pending changes, it shows that the case of the 'resource_group_name' and the 'id' are changed to lowercase.  
It appears that the update at step 5 of the procedure above has not preserved the original case of the resource group name.  This is resulting in a destroy/replace that I do not want to perform.
As a workaround I'm going to have to change my configuration to wrap the 'resource_group_name' value in a call to the lower() function.

### Steps to Reproduce
See above

### References

* #0000

**Comment by yupwei68** [comment] 2020-05-18 09:11
Hi @eehret , thanks for opening this issue. Sorry that I can't reproduce this error. There are some details that I want to confirm with you. 
1. `terraform import` an existing resource, the remote resource's `resource_group_name` is in uppercase.
2. change the local code, the `resource_group_name` in local code is also in uppercase, the same with the remote resource. Terraform plan shows:
```
~ resource "azurerm_mysql_server" "test2" {
        administrator_login               = "yup"
        auto_grow_enabled                 = true
        backup_retention_days             = 7
      ~ create_mode                       = "Default" -> "Replica"
      + creation_source_server_id         = "/subscriptions/XX/resourceGroups/ACCTESTRG/providers/Microsoft.DBforMySQL/servers/acctestmysqlsvr"
        fqdn                              = "yupmysql2.mysql.database.azure.com"
        geo_redundant_backup_enabled      = false
        id                                = "/subscriptions/XX/resourceGroups/YUPMYSQL2/providers/Microsoft.DBforMySQL/servers/yupmysql2"
        infrastructure_encryption_enabled = false
        location                          = "eastus"
        name                              = "yupmysql2"
        public_network_access_enabled     = true
        resource_group_name               = "YUPMYSQL2"
        sku_name                          = "GP_Gen5_4"
        ssl_enforcement                   = "Enabled"
        ssl_enforcement_enabled           = true
        ssl_minimal_tls_version_enforced  = "TLSEnforcementDisabled"
       storage_mb                        = 102400
        tags                              = {}
        version                           = "5.7"

        storage_profile {
            auto_grow             = "Enabled"
            backup_retention_days = 7
            geo_redundant_backup  = "Disabled"
            storage_mb            = 102400
        }

        timeouts {}
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

3. Terraform apply, currently get the state of the resource, the `resource_group_name` is still in uppercase:
```
resource "azurerm_mysql_server" "test2" {
    administrator_login               = "yup"
    auto_grow_enabled                 = true
    backup_retention_days             = 7
    create_mode                       = "Replica"
    creation_source_server_id         = "/subscriptions/XX/resourceGroups/ACCTESTRG/providers/Microsoft.DBforMySQL/servers/acctestmysqlsvr"
    fqdn                              = "yupmysql2.mysql.database.azure.com"
    geo_redundant_backup_enabled      = false
    id                                = "/subscriptions/XX/resourceGroups/YUPMYSQL2/providers/Microsoft.DBforMySQL/servers/yupmysql2"
    infrastructure_encryption_enabled = false
    location                          = "eastus"
    name                              = "yupmysql2"
    public_network_access_enabled     = true
    resource_group_name               = "YUPMYSQL2"
    sku_name                          = "GP_Gen5_4"
    ssl_enforcement                   = "Enabled"
    ssl_enforcement_enabled           = true
    ssl_minimal_tls_version_enforced  = "TLSEnforcementDisabled"
    storage_mb                        = 102400
    tags                              = {}
    version                           = "5.7"

    storage_profile {
        auto_grow             = "Enabled"
        backup_retention_days = 7
        geo_redundant_backup  = "Disabled"
        storage_mb            = 102400
    }

    timeouts {}
}
```

**Comment by tombuildsstuff** [comment] 2020-05-18 12:01
Looks like this is a bug in the MySQL API where the Resource ID is being mutated into upper-case - tagged as `upstream-microsoft` to reflect this API bug

**Comment by yupwei68** [comment] 2020-05-21 05:34
Hi @eehret , thanks for opening this issue. Sorry that I can't reproduce this error. I'll list my reproducing steps, please correct me if any misunderstandings.

1. create a replica "yupsql3" from "yupsql2" 
![image](https://user-images.githubusercontent.com/56525716/82526475-b2fb3b00-9b66-11ea-9369-2c718924b47c.png)

2. terraform import the replica "yupsql3":
terraform import azurerm_mysql_server.test "/subscriptions/XX/resourceGroups/YUPSQL2/providers/Microsoft.DBforMySQL/servers/yupsql3"

3. correct the local terraform configuration from the terraform state: (change `create_mode` -> "Replica", add `creation_source_server_id`)
local terraform code:
```
resource "azurerm_mysql_server" "test" {
  name                      = "yupsql3"
  location                  = "eastus"
  resource_group_name       = "YUPSQL2"
  sku_name                  = "GP_Gen5_4"
  version                   = "5.7"
  create_mode               = "Replica"
  creation_source_server_id = "/subscriptions/XX/resourceGroups/YUPSQL2/providers/Microsoft.DBforMySQL/servers/yupsql2"
  ssl_enforcement_enabled   = true
  storage_mb                = 102400
}
```
4. terraform plan:
```
 ~ resource "azurerm_mysql_server" "test" {
        administrator_login               = "yup"
        auto_grow_enabled                 = true
        backup_retention_days             = 7
      ~ create_mode                       = "Default" -> "Replica"
      + creation_source_server_id         = "/subscriptions/XX/resourceGroups/YUPSQL2/providers/Microsoft.DBforMySQL/servers/yupsql2"
        fqdn                              = "yupsql3.mysql.database.azure.com"
        geo_redundant_backup_enabled      = false
        id                                = "/subscriptions/XX/resourceGroups/YUPSQL2/providers/Microsoft.DBforMySQL/servers/yupsql3"
        infrastructure_encryption_enabled = false
        location                          = "eastus"
        name                              = "yupsql3"
        public_network_access_enabled     = true
        resource_group_name               = "YUPSQL2"
        sku_name                          = "GP_Gen5_4"
        ssl_enforcement                   = "Enabled"
        ssl_enforcement_enabled           = true
        ssl_minimal_tls_version_enforced  = "TLSEnforcementDisabled"
        storage_mb                        = 102400
        tags                              = {}
        version                           = "5.7"

        storage_profile {
            auto_grow             = "Enabled"
            backup_retention_days = 7
            geo_redundant_backup  = "Disabled"
            storage_mb            = 102400
        }

        timeouts {}
    }

Plan: 0 to add, 1 to change, 0 to destroy.

```

5. terraform apply with success

6. terraform plan or apply:
`No changes. Infrastructure is up-to-date.`

**Comment by eehret** [comment] 2020-06-09 20:22
@yupwei68 Thanks for trying to reproduce this!   Your steps look correct to me.  The main differences I'm seeing are:
1) I was using MySQL version 8.0 ;
2) My resource group name was mixed case.

I'll include my before and after state for this so you can see what happened:

State before step 4:
`# azurerm_mysql_server.appian_db_01-repl[0] will be updated in-place
  ~ resource "azurerm_mysql_server" "appian_db_01-repl" {
        administrator_login               = "<username>"
        auto_grow_enabled                 = true
        backup_retention_days             = 7
      ~ create_mode                       = "Default" -> "Replica"
      + creation_source_server_id         = "/subscriptions/<subscription_id>/resourceGroups/rg_RASA_APPIAN_STG/providers/Microsoft.DBforMySQL/servers/appian-stg-db-01"
        fqdn                              = "appian-stg-db-01-repl.mysql.database.azure.com"
        geo_redundant_backup_enabled      = true
        id                                = "/subscriptions/<subscription_id>/resourceGroups/rg_RASA_APPIAN_STG/providers/Microsoft.DBforMySQL/servers/appian-stg-db-01-repl"
        infrastructure_encryption_enabled = false
        location                          = "canadaeast"
        name                              = "appian-stg-db-01-repl"
        public_network_access_enabled     = false
        resource_group_name               = "rg_RASA_APPIAN_STG"
        sku_name                          = "GP_Gen5_4"
        ssl_enforcement                   = "Enabled"
        ssl_enforcement_enabled           = true
        ssl_minimal_tls_version_enforced  = "TLSEnforcementDisabled"
        storage_mb                        = 131072
        version                           = "8.0"

        storage_profile {
            auto_grow             = "Enabled"
            backup_retention_days = 7
            geo_redundant_backup  = "Enabled"
            storage_mb            = 131072
        }

        timeouts {}
    }
`

And then at step 6:
`  # azurerm_mysql_server.appian_db_01-repl[0] must be replaced
-/+ resource "azurerm_mysql_server" "appian_db_01-repl" {
        administrator_login               = "<username>"
      + administrator_login_password      = (sensitive value)
        auto_grow_enabled                 = true
        backup_retention_days             = 7
        create_mode                       = "Replica"
        creation_source_server_id         = "/subscriptions/<subscription_id>/resourceGroups/rg_RASA_APPIAN_STG/providers/Microsoft.DBforMySQL/servers/appian-stg-db-01"
      ~ fqdn                              = "appian-stg-db-01-repl.mysql.database.azure.com" -> (known after apply)
        geo_redundant_backup_enabled      = true
      ~ id                                = "/subscriptions/<subscription_id>/resourceGroups/rg_rasa_appian_stg/providers/Microsoft.DBforMySQL/servers/appian-stg-db-01-repl" -> (known after apply)
        infrastructure_encryption_enabled = false
        location                          = "canadaeast"
        name                              = "appian-stg-db-01-repl"
        public_network_access_enabled     = false
      ~ resource_group_name               = "rg_rasa_appian_stg" -> "rg_RASA_APPIAN_STG" # forces replacement
        sku_name                          = "GP_Gen5_4"
      ~ ssl_enforcement                   = "Enabled" -> (known after apply)
        ssl_enforcement_enabled           = true
        ssl_minimal_tls_version_enforced  = "TLSEnforcementDisabled"
        storage_mb                        = 131072
        version                           = "8.0"

      ~ storage_profile {
          ~ auto_grow             = "Enabled" -> (known after apply)
          ~ backup_retention_days = 7 -> (known after apply)
          ~ geo_redundant_backup  = "Enabled" -> (known after apply)
          ~ storage_mb            = 131072 -> (known after apply)
        }

      - timeouts {}
    }

Plan: 1 to add, 0 to change, 1 to destroy.
`

So Terraform or something upstream seems to be changing the resource group name twice:  once when `create_mode` is changed from 'Default' to 'Replica', when the resource group is changed from mixed case to lowercase, and then again at step 6 when Terraform tries to reapply my original resource group name (converting back to mixed case from lowercase).

Ideally nothing should be altering the resource group name at step 4, then I would not be having this problem.

Thanks again :)

**Comment by yupwei68** [comment] 2020-06-10 07:27
Hi @eehret , I have tried in mysql version 8.0, mix-case in resource group name and the provided config , while sorry that I still could not reproduce this error.

**Comment by favoretti** [comment] 2021-08-19 13:05
Since this issue seems to have been addressed in the latest versions of the provider (or a valid workaround was provided) - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.

**Closed by favoretti** 2021-08-19 13:05 UTC
Labels: bug, upstream-microsoft, service/mysql
