### ISSUE TITLE
azurerm_api_management_api_operation (2.95 crash)

### ISSUE THREAD

**Issue by h4t1n** [hashicorp/terraform-provider-azurerm#15339] opened 2022-02-09 14:29 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

terraform 1.1.5
azurerm 2.95.0

### Affected Resource(s)

resources `azurerm_api_management_api_operation, azurerm_api_management_api_schema`

### Terraform Configuration Files

main.tf
```

resource "azurerm_resource_group" "resource_group" {
    name        = "showerror-rg"
    location    = "west europe"
}

resource "azurerm_api_management" "apim" {
    name                        = "showerror-apim"
    location                    = "westeurope"
    resource_group_name         = azurerm_resource_group.resource_group.name
    publisher_name              = "showerror-publisher-name"
    publisher_email             = "showerror@email.com"
    sku_name                    = "Developer_1"
    security {
        enable_frontend_ssl30   = false
        enable_backend_ssl30    = false
        enable_frontend_tls10   = false
        enable_backend_tls10    = false
        enable_frontend_tls11   = true
        enable_backend_tls11    = true
    }
    protocols {
        enable_http2 = true
    }
    identity {
        type = "SystemAssigned"
    }
}

resource "azurerm_api_management_api" "apim_api" {
    name                    = "showerror-api"
    resource_group_name     = azurerm_resource_group.resource_group.name
    api_management_name     = azurerm_api_management.apim.name
    revision                = "1"
    display_name            = "showerror-display-name"
    path                    = "path"
    protocols               = ["https"]
}

resource "azurerm_api_management_api_schema" "api_schema" {
    api_name                = azurerm_api_management_api.apim_api.name
    api_management_name     = azurerm_api_management.apim.name
    resource_group_name     = azurerm_resource_group.resource_group.name
    schema_id               = "12412412525435312345"
    content_type            = "application/vnd.ms-azure-apim.swagger.definitions+json"
    value                   = file("someschema.json")
}

resource "azurerm_api_management_api_operation" "api_operation" {
    depends_on              = [azurerm_api_management_api_schema.api_schema]
    operation_id            = "40000000000000000001"
    api_name                = azurerm_api_management_api.apim_api.name
    api_management_name     = azurerm_api_management.apim.name
    resource_group_name     = azurerm_resource_group.resource_group.name
    display_name            = "manual-invoke"
    method                  = "GET"
    url_template            = "/path"
    response {
        status_code         = 200
        representation {
            content_type    = "application/json"
            type_name       = "Projects"
            schema_id       = "12412412525435312345"
        }
    }
}

```
someschema.json
```
{
	"Projects": {
		"type": "array",
		"items": {
			"type": "object",
			"properties": {
				"ProjectCode": {
					"type": "string"
				},
				"ProjectManagerName": {
					"type": "string"
				},
				"ProjectManagerEmail": {
					"type": "string"
				},
				"LineManagerName": {
					"type": "string"
				},
				"LineManagerEmail": {
					"type": "string"
				},
				"BusinessUnitName": {
					"type": "string"
				}
			},
			"required": [
				"ProjectCode",
				"ProjectManagerName",
				"ProjectManagerEmail",
				"LineManagerName",
				"LineManagerEmail",
				"BusinessUnitName"
			]
		}
	}
}
```

### Panic Output
```
azurerm_api_management_api_operation.api_operation: Creating...
╷
│ Error: Plugin did not respond
│ 
│   with azurerm_api_management_api_operation.api_operation,
│   on main.tf line 49, in resource "azurerm_api_management_api_operation" "api_operation":
│   49: resource "azurerm_api_management_api_operation" "api_operation" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-azurerm_v2.95.0_x5 plugin:

panic: interface conversion: interface {} is []interface {}, not string

goroutine 212 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/apimanagement/schemaz.FlattenApiManagementOperationParameterExampleContract(0xc001f68ba0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/services/apimanagement/schemaz/api_management.go:423 +0x3fc
github.com/hashicorp/terraform-provider-azurerm/internal/services/apimanagement/schemaz.FlattenApiManagementOperationRepresentation(0xc00167b830)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/services/apimanagement/schemaz/api_management.go:196 +0x1db
github.com/hashicorp/terraform-provider-azurerm/internal/services/apimanagement.flattenApiManagementOperationResponseContract(0xc00167b800)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/services/apimanagement/api_management_api_operation_resource.go:359 +0x245
github.com/hashicorp/terraform-provider-azurerm/internal/services/apimanagement.resourceApiManagementApiOperationRead(0xc00198f780, {0x5657420, 0xc001a98000})
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/services/apimanagement/api_management_api_operation_resource.go:213 +0x6b6
github.com/hashicorp/terraform-provider-azurerm/internal/services/apimanagement.resourceApiManagementApiOperationCreateUpdate(0xc00198f780, {0x5657420, 0xc001a98000})
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/services/apimanagement/api_management_api_operation_resource.go:173 +0xbc8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0022db020, {0x6663c18, 0xc000ad4640}, 0x2, {0x5657420, 0xc001a98000})
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:329 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00044d500, {0x6663c18, 0xc000ad4640}, 0xc000c15ba0, 0xc00198f600, {0x5657420, 0xc001a98000})
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:467 +0x871
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000dbc648, {0x6663c18, 0xc000ad4640}, 0xc00065d720)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:977 +0xd8a
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0001c3880, {0x6663cc0, 0xc0011ea990}, 0xc0002be150)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server/server.go:603 +0x30e
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x5ba1ea0, 0xc0001c3880}, {0x6663cc0, 0xc0011ea990}, 0xc00197e780, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00023f340, {0x66b3618, 0xc000194900}, 0xc002261e60, 0xc0011ebc20, 0xaca4ec0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0xc6f
google.golang.org/grpc.(*Server).handleStream(0xc00023f340, {0x66b3618, 0xc000194900}, 0xc002261e60, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1617 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:940 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:938 +0x294

Error: The terraform-provider-azurerm_v2.95.0_x5 plugin crashed!
```
### Expected Behaviour

An API Operation should be created which will use the schema `Projects` from the `azurerm_api_management_api_schema`.

### Actual Behaviour

The crash is weird because it does create the resource, but terraform crashed when it proceeds to write it to .tfstate.
Once it is created, you also cannot import the resource, terraform crashes with a similar error.

### Steps to Reproduce

1. `terraform apply`

**Comment by stephybun** [comment] 2022-02-09 16:13
Duplicate of #14869. Please subscribe to #14869 for updates.

**Closed by stephybun** 2022-02-09 16:13 UTC
Labels: bug, crash, service/api-management
