### ISSUE TITLE
NSG flow log names are being truncated

### ISSUE THREAD

**Issue by Sanket-Kaware** [hashicorp/terraform-provider-azurerm#13424] opened 2021-09-20 17:40 UTC
Hello, This is **breaking our terraform automation to enable the NSG flow logs**. I was going through this https://github.com/hashicorp/terraform-provider-azurerm/blob/485955c183064df242be931543c2039e67f956fe/internal/services/network/parse/flow_log.go#L39 and we noticed that it is truncating the flow log name due to the 80 character limit. This leads to the collision of two objects with almost similar names.

1. Is "Microsoft.Network" prepend really necessary here? Because the azure portal does not currently prepend this.https://github.com/hashicorp/terraform-provider-azurerm/blob/485955c183064df242be931543c2039e67f956fe/internal/services/network/parse/flow_log.go#L43
2. If you do not want to make the above change, can you please finish that in 3.0, so that we can name it ourselves? https://github.com/hashicorp/terraform-provider-azurerm/blob/485955c183064df242be931543c2039e67f956fe/internal/services/network/parse/flow_log.go#L45

**Comment by tombuildsstuff** [comment] 2021-09-21 14:32
Duplicate of #12861

**Closed by tombuildsstuff** 2021-09-21 14:32 UTC

**Comment by Sanket-Kaware** [comment] 2021-09-21 16:49
Hi @tombuildsstuff,  thank you for #12861. But can you answer the two questions mentioned above in the description? Is it possible to do one of these?
