### ISSUE TITLE
azurerm_automation_account does not support the identity block

### ISSUE THREAD

**Issue by jbla9028** [hashicorp/terraform-provider-azurerm#14542] opened 2021-12-08 15:06 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

azurerm_automation_account does not support the identity block to enable the managed identity feature of the automation

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/automation_account
When creating the resource, the identity block doesn't appear to be an option.  If the identity block could be added so when provisioning we can turn on the MSI. Also an output of the managed identity ids so they could be called for role assignment would be important.

* azurerm_2.88.1

### Potential Terraform Configuration

```hcl
resource "azurerm_automation_account" "example" {
  name                = "automationAccount1"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  sku_name = "Basic"

  identity {
    type = "SystemAssigned"
  }

  tags = {
    environment = "development"
  }
}
```

### References

* #0000

**Comment by OmnipotentOwl** [comment] 2022-01-06 16:10
Would this request not be a duplicate of #11503?

**Comment by tombuildsstuff** [comment] 2022-01-06 17:06
indeed - this is a duplicate of #11503, thanks @OmnipotentOwl  - please subscribe to that issue for updates.

**Closed by tombuildsstuff** 2022-01-06 17:06 UTC
Labels: enhancement, service/automation
