### ISSUE TITLE
Support for AutoKey rotation with latest key

### ISSUE THREAD

**Issue by nitmatgeo** [hashicorp/terraform-provider-azurerm#12640] opened 2021-07-19 06:53 UTC
Support for AutoKey rotation in [Encryption Set](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/disk_encryption_set) maybe include an argument `enable_latest_key = true`.
![image](https://user-images.githubusercontent.com/71626368/126115604-a812a648-ee89-422d-9bf5-40ca78b4debe.png)

```
resource "azurerm_disk_encryption_set" "example" {
  name                = "des"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  key_vault_key_id    = azurerm_key_vault_key.example.id
  enable_latest_key = true

  identity {
    type = "SystemAssigned"
  }
}
```

**Comment by nitmatgeo** [comment] 2021-07-20 14:10
@manicminer Is it possible to have any ETA and expected milestone to enable this feature?

**Comment by nitmatgeo** [comment] 2021-08-18 18:04
@manicminer is it possible to expedite this out? Of course, depending on your priorities and maybe this might not have bigger effort as this seems to be setting up a flag in underlying Azure APIs.

**Comment by tombuildsstuff** [comment] 2021-08-19 07:02
Duplicate of #12531

**Closed by tombuildsstuff** 2021-08-19 07:02 UTC
Labels: enhancement, service/disks

**Comment by nitmatgeo** [comment] 2021-08-19 08:13
@tombuildsstuff Am really sorry, I failed to notice that. Looks like I often end up spamming you with Open Issues! 😞
