### ISSUE TITLE
EventHub parsing fails with: expected the segment "consumergroups" to be "consumerGroups"

### ISSUE THREAD

**Issue by JiriKovar** [hashicorp/terraform-provider-azurerm#14271] opened 2021-11-19 13:01 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.0.11
on windows_amd64
hashicorp/azurerm v2.86.0 (signed by HashiCorp)

### Affected Resource(s)

- azurerm_eventhub_consumer_group

### Terraform Configuration Files

```hcl
resource "azurerm_eventhub_consumer_group" "default" {
  count = length(local.consumer_groups)

  name                = element(local.consumer_groups, count.index).consumer_group_name
  resource_group_name = var.resource_group.name
  namespace_name      = azurerm_eventhub_namespace.default.name
  eventhub_name       = element(local.consumer_groups, count.index).event_hub_name
}
```

### Expected Behaviour

Terraform plan works on an existing environment (last terraformed by the azurerm provider version v2.85.0, still succeeds on v2.85.0, but fails with v2.86.0).

### Actual Behaviour

What does NOT work:
- Terraform plan on any of our preexisting environments after migration to v2.86.0

What works:
- Terraforming a new environment from scratch
- Terraform plan on any of our preexisting environments after downgrading back to the v2.85.0.

**Comment by koikonom** [comment] 2021-11-19 17:51
Hello, thanks for taking the time to report this. This is a duplicate of #14266, please subscribe to that issue for updates.

**Closed** 2021-11-19 17:51 UTC
