### ISSUE TITLE
Azure CLI azuread and azurerm conmingled authentication overlapping

### ISSUE THREAD

**Issue by pearcec** [hashicorp/terraform-provider-azurerm#5702] opened 2020-02-12 16:20 UTC
# Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

terraform -v
Terraform v0.12.20
+ provider.azuread v0.7.0
+ provider.azurerm v1.43.0
+ provider.random v2.2.1

### Terraform Configuration Files

provider "azurerm" {
}
provider "azuread" {
}

### Debug Output

```
2020-02-12T15:56:07.673Z [DEBUG] plugin.terraform-provider-azurerm_v1.43.0_x4: [DEBUG] AzureRM Request:
2020-02-12T15:56:07.673Z [DEBUG] plugin.terraform-provider-azurerm_v1.43.0_x4: GET /oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fmanagement.azure.com%2F HTTP/1.1
2020-02-12T15:56:07.673Z [DEBUG] plugin.terraform-provider-azurerm_v1.43.0_x4: Host: localhost:50342
2020-02-12T15:56:07.673Z [DEBUG] plugin.terraform-provider-azurerm_v1.43.0_x4: User-Agent: Go/go1.12.6 (amd64-linux) go-autorest/adal/v1.0.0
2020-02-12T15:56:07.673Z [DEBUG] plugin.terraform-provider-azurerm_v1.43.0_x4: Content-Length: 87
2020-02-12T15:56:07.673Z [DEBUG] plugin.terraform-provider-azurerm_v1.43.0_x4: Content-Type: application/x-www-form-urlencoded
2020-02-12T15:56:07.673Z [DEBUG] plugin.terraform-provider-azurerm_v1.43.0_x4: Metadata: true
2020-02-12T15:56:07.673Z [DEBUG] plugin.terraform-provider-azurerm_v1.43.0_x4: Accept-Encoding: gzip
2020-02-12T15:56:07.673Z [DEBUG] plugin.terraform-provider-azurerm_v1.43.0_x4:
2020-02-12T15:56:07.673Z [DEBUG] plugin.terraform-provider-azurerm_v1.43.0_x4: client_id=&grant_type=client_credentials&resource=https%3A%2F%2Fmanagement.azure.com%2F
2020-02-12T15:56:07.677Z [DEBUG] plugin.terraform-provider-azurerm_v1.43.0_x4: [DEBUG] AzureRM Response for http://localhost:50342/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fmanagement.azure.com%2F:
2020-02-12T15:56:07.677Z [DEBUG] plugin.terraform-provider-azurerm_v1.43.0_x4: HTTP/1.1 200 OK
2020-02-12T15:56:07.677Z [DEBUG] plugin.terraform-provider-azurerm_v1.43.0_x4: Content-Length: 1726
2020-02-12T15:56:07.677Z [DEBUG] plugin.terraform-provider-azurerm_v1.43.0_x4: Connection: keep-alive
2020-02-12T15:56:07.677Z [DEBUG] plugin.terraform-provider-azurerm_v1.43.0_x4: Content-Type: application/json; charset=utf-8
2020-02-12T15:56:07.677Z [DEBUG] plugin.terraform-provider-azurerm_v1.43.0_x4: Date: Wed, 12 Feb 2020 15:56:07 GMT
2020-02-12T15:56:07.677Z [DEBUG] plugin.terraform-provider-azurerm_v1.43.0_x4: Etag: W/"6be-GVFzdlHs5tHogSgoeKVMN1Oso/o"
2020-02-12T15:56:07.677Z [DEBUG] plugin.terraform-provider-azurerm_v1.43.0_x4: X-Powered-By: Express
2020-02-12T15:56:07.677Z [DEBUG] plugin.terraform-provider-azurerm_v1.43.0_x4:
2020-02-12T15:56:07.677Z [DEBUG] plugin.terraform-provider-azurerm_v1.43.0_x4: {"access_token":"redacted","refres
h_token":"","expires_in":"3900","expires_on":"1581523647","not_before":"1581519747","resource":"https://graph.windows.net/","token_type":"Bearer"}
```

### Expected Behavior

Looks like when the azurerm gets a token it is getting a Bearer token from the azuread request.

### Actual Behavior

```
terraform apply
module.group.module.group.data.azuread_users.members: Refreshing state...
module.group.module.group.data.azuread_users.owners: Refreshing state...
module.group.random_id.noise: Refreshing state... [id=DXY]
module.group.module.group.azuread_group.group: Refreshing state... [id=ab0d6f2d-0c7f-47d7-83d1-2e67ff92be3b]

Error: Unable to list provider registration status, it is possible that this is due to invalid credentials or the service principal does not have permission to use the Resource Manager API, Azure error: resources.ProvidersClient#List: Failure responding to request: StatusCode=401 -- Original Error: autorest/azure: Service returned an error. Status=401 Code="InvalidAuthenticationTokenAudience" Message="The access token has been obtained for wrong audience or resource 'https://graph.windows.net/'. It should exactly match with one of the allowed audiences 'https://management.core.windows.net/','https://management.core.windows.net','https://management.azure.com/','https://management.azure.com'."

  on .terraform/modules/adls/main.tf line 1, in provider "azurerm":
   1: provider "azurerm" {



Error: Unable to list provider registration status, it is possible that this is due to invalid credentials or the service principal does not have permission to use the Resource Manager API, Azure error: resources.ProvidersClient#List: Failure responding to request: StatusCode=401 -- Original Error: autorest/azure: Service returned an error. Status=401 Code="InvalidAuthenticationTokenAudience" Message="The access token has been obtained for wrong audience or resource 'https://graph.windows.net/'. It should exactly match with one of the allowed audiences 'https://management.core.windows.net/','https://management.core.windows.net','https://management.azure.com/','https://management.azure.com'."

  on .terraform/modules/rg/main.tf line 1, in provider "azurerm":
   1: provider "azurerm" {
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Running via Azure Cloud Shell

**Comment by pearcec** [comment] 2020-02-12 16:26
When I run
```
az account get-access-token
```
it starts working.

**Comment by pearcec** [comment] 2020-02-12 16:49
> When I run
> 
> ```
> az account get-access-token
> ```
> 
> it starts working.

Running that command doesn't always work.

**Comment by pearcec** [comment] 2020-02-17 17:11
I think what is happening here is I was using target to specify a single module which built a group.  I need to build the group first since terraform couldn't figure it out during the run. So it recommended I target it.  Reading through the azurerm provider code looks like it only sets endpoints when needed.  Unfortunately the Bearer token is set with only the endpoint.  Seems like there should be a process to refresh this.  Especially if you are working on different projects.

I will work on producing an example.

**Comment by tombuildsstuff** [comment] 2020-02-17 17:26
@pearcec it's worth noting when running inside CloudShell we use MSI rather than the Azure CLI for authentication - so I'm not sure the CLI command will be directly reflective unless that's using MSI for authentication too?

Based on the information above it's entirely possible this is a bug in our code - however this sounds like it could be an issue requesting concurrent access tokens from the MSI Service itself? The bearer tokens themselves are requested/valid per-domain due to the way the Azure API works, but they'll refresh themselves as required - providing the tokens requested correctly in the first place.

**Comment by pearcec** [comment] 2020-02-17 18:30
Uh, I believe I am using MSI.  I don't actually log in with az login.  I just run CloudShell and it authenticates.  I tried creating some quick dummy tests and have not been able to reproduce it.  My dummy tests are not using modules.  Where my actually failure is with modules in use.  I will keep trying to create a reproducible error with an example script.

**Comment by justin-p** [comment] 2020-03-13 18:56
I'm facing the same issue, also just using CloudShell. Though I'm just using the azurerm provider.

So far it seems random and i have not been able to reproduce it. First time it `fixed` it self after 15 min. Running `az account get-access-token` did just fix the issue for me.

```
terraform -v
Terraform v0.12.23
+ provider.azurerm v2.1.0
```

**Comment by timtsoit-crypto** [comment] 2020-11-03 02:37
I also have a similar issue when I deploy resources to multiple subscriptions at once

Even the created resources already inside the state file, when I click apply again without any code changes. It always show there are resources will be added or there are resources will be changed. And every time the number of resource adding and resource changing is varying.

ps: My account has linked with multiple subscriptions with contributor role

**Comment by favoretti** [comment] 2021-08-19 09:18
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.

**Closed by favoretti** 2021-08-19 09:18 UTC
Labels: bug, authentication
