### ISSUE TITLE
Front door resource group parameter is validated as a location value

### ISSUE THREAD

**Issue by samjpv** [hashicorp/terraform-provider-azurerm#15202] opened 2022-02-01 00:46 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.1.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.94.0

### Affected Resource(s)

* `azurerm_frontdoor`

### Expected Behaviour

The terraform plan should have been successfully created, with the resource_group_name expecting an existing resource group, rather than a region.

### Actual Behaviour

Terraform plan fails, saying that the resource_group_name parameter is not a supported region on azure. If a region is provided in the parameter, then terraform plan succeeds and apply fails, saying that a resource group name was required.

``` 
│ Error: <resource-group-name> was not found in the list of supported Azure Locations: "westus,westus2,eastus,centralus,centraluseuap,southcentralus,northcentralus,westcentralus,eastus2,eastus2euap,brazilsouth,brazilus,northeurope,westeurope,eastasia,southeastasia,japanwest,japaneast,koreacentral,koreasouth,southindia,westindia,centralindia,australiaeast,australiasoutheast,canadacentral,canadaeast,uksouth,ukwest,francecentral,francesouth,australiacentral,australiacentral2,uaecentral,uaenorth,southafricanorth,southafricawest,switzerlandnorth,switzerlandwest,germanynorth,germanywestcentral,norwayeast,norwaywest,brazilsoutheast,westus3,swedencentral,swedensouth"
│
│   with module.new_frontdoor.azurerm_frontdoor.new_frontdoor,
│   on ../../../Modules/azure_front_door/main.tf line 3, in resource "azurerm_frontdoor" "new_frontdoor":
│    3:   resource_group_name                          = <resource-group-name>
```
### Steps to Reproduce

1. Create terraform for an azurerm_front_door, as per the doc, using an existing resource group for the resource_group_name parameter: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/frontdoor
2. Run terraform init/plan

**Comment by tombuildsstuff** [comment] 2022-02-01 05:16
Duplicate of #15164 which has been fixed in #15174 / will ship in v2.95.0

**Closed by tombuildsstuff** 2022-02-01 05:16 UTC
Labels: bug, duplicate, service/frontdoor
