### ISSUE TITLE
Application Gateway Rewrite “Rule block” - query_string is set to “” when null is passed

### ISSUE THREAD

**Issue by farmanyous** [hashicorp/terraform-provider-azurerm#15201] opened 2022-02-01 00:23 UTC
code

      url{
        path         = "{var_uri_path_1}-rtf/{var_uri_path_2}"
        reroute      = true
        query_string = null  # using this it should configure a rule that checks only the URL path, not both URL path and query string
      }
applied state:
![image](https://user-images.githubusercontent.com/27310883/151894607-8797d9d9-a22e-4475-ba42-f593cd1bcddc.png)

When no value is provided the state file shows that there is a value of "" (an empty string), which probably means the query_string is essentially being replaced by the rewrite rule.

I’m not entirely sure why this is the case, but I’ll do some investigation as to why empty strings are going through when no value is provided.

Originally posted by @dhensby in azurerm_application_gateway - support for rewriting urls with the `url` block by dhensby · Pull Request #10950 · hashicorp/terraform-provider-azurerm · GitHub

**Comment by aristosvo** [comment] 2022-02-01 12:10
Hi @farmanyous!

This is a duplicate of a few other issues (#11563, #13894), and potentially solved in PR #13899.

To work around this you can use query_string = "{var_query_string}" if I'm correct, based on this comment

I'll close this one as duplicate, feel free to comment on one of the other issues!

**Closed** 2022-02-01 12:12 UTC
