### ISSUE TITLE
azurerm_kubernetes_cluster : automatic_channel_upgrade error

### ISSUE THREAD

**Issue by iamsoorya** [hashicorp/terraform-provider-azurerm#20700] opened 2023-02-28 20:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

Terraform 1.3.9 and azrerm 3.45.0

When I want to pass null value or none value for automatic_channel_upgrade, I get an error  # Error: expected automatic_channel_upgrade to be one of [patch rapid stable node-image], got none / null

It used to work earlier. It is now broken.

I had to comment out the line of code as in the below tf file.

# Error: expected automatic_channel_upgrade to be one of [patch rapid stable node-image], got none / null
  #automatic_channel_upgrade       = try(var.automatic_channel_upgrade, null)  # patch, rapid, stable
 

### Terraform Version

1.3.9

### AzureRM Provider Version

3.45.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster 

### Terraform Configuration Files

```hcl
#https://github.com/ThorstenHans/terraforming-aks
#Enable logging for AKS
#Enable RBAC
#tfsec:ignore:azure-container-use-rbac-permissions
#tfsec:ignore:azure-container-logging
#tfsec:ignore:azure-container-limit-authorized-ips
resource "azurerm_kubernetes_cluster" "k8s" {
  name                            = var.cluster_name
  location                        = var.location
  resource_group_name             = var.rg_name
  node_resource_group             = var.rg_name_nodes
  dns_prefix                      = var.dns_prefix   # that forms part of the fully qualified domain name (FQDN) used to access the cluster - is set. 
  kubernetes_version              = var.kubernetes_version
  #api_server_authorized_ip_ranges = var.authorized_ip_ranges
  sku_tier                        = var.sku_tier # "Paid"  ## uptime SLA , free for without
  private_cluster_enabled         = var.private_cluster_enabled
  private_cluster_public_fqdn_enabled = var.private_cluster_public_fqdn_enabled
  public_network_access_enabled = var.public_network_access_enabled
  dns_prefix_private_cluster      = var.private_cluster_enabled == true ? var.dns_prefix_private_cluster : null
  private_dns_zone_id             = var.private_dns_zone_id
  # Error: expected automatic_channel_upgrade to be one of [patch rapid stable node-image], got none / null
  #automatic_channel_upgrade       = try(var.automatic_channel_upgrade, null)  # patch, rapid, stable
  azure_policy_enabled            = try(var.azure_policy_enabled, false)
  http_application_routing_enabled = try(var.http_application_routing_enabled, false)
  role_based_access_control_enabled = var.k8s_rbac_enabled
  run_command_enabled = var.run_command_enabled 
  open_service_mesh_enabled       = try(var.osm_enabled, false)
  image_cleaner_enabled           = var.image_cleaner_enabled
  image_cleaner_interval_hours    = var.image_cleaner_interval_hours
  local_account_disabled          = var.local_account_disabled
  workload_identity_enabled  = var.workload_identity_enabled 
  oidc_issuer_enabled      = var.oidc_issuer_enabled
  azure_active_directory_role_based_access_control {
    managed                = var.managed_aad_enabled #as per tfsec
    tenant_id              = data.azurerm_client_config.current.tenant_id
    admin_group_object_ids = (var.managed_aad_enabled == true) ? var.admin_group_object_ids : null
    azure_rbac_enabled     = (var.managed_aad_enabled == true) ? var.azure_rbac_enabled : null # as per tfsec (var.managed_aad_enabled == true) ? var.azure_rbac_enabled : null
  }
  
  # api_server_access_profile
  api_server_access_profile { # block supports the following:
    authorized_ip_ranges = var.authorized_ip_ranges # (var.authorized_ip_ranges == [] && var.public_network_access_enabled == true) ? ["0.0.0.0/32"] : var.authorized_ip_ranges
    subnet_id = var.api_server_subnet_id
    vnet_integration_enabled = var.api_server_vnet_integration_enabled # (Optional) Should API Server VNet Integration be enabled? For more details please visit Use API Server VNet Integration.
  }
  # auto_scaler_profile
  # confidential_computing
  # http_proxy_config 
  # key_management_service 
  # workload_autoscaler_profile
  # storage_profile
  # web_app_routing

  # monitor_metrics {
  #   annotations_allowed = var.monitor_metrics_annotations_allowed
  #   labels_allowed = var.monitor_metrics_labels_allowed
  # }

  dynamic "aci_connector_linux" {  
    for_each = (var.aci_subnet_name == null) ? [] : [""]
    content {
      subnet_name = var.aci_subnet_name
    }
  }

  #do not allow null values as per tfsec
  oms_agent {    
    log_analytics_workspace_id = var.log_wrkspc_id
  } 

  dynamic "ingress_application_gateway" {  
    for_each = (var.agw_id == null) ? [] : [""]
    content {     
      gateway_id = var.agw_id # (Optional) The ID of the Application Gateway to integrate with the ingress controller of this Kubernetes Cluster. See this page for further details.
      #subnet_cidr = try(var.agw_subnet_cidr, null) #  The subnet CIDR to be used to create an Application Gateway, which in turn will be integrated with the ingress controller of this Kubernetes Cluster. See this page for further details.
      #subnet_id = try(var.agw_subnet_id, null) #  The ID of the subnet on which to create an Application Gateway, which in turn will be integrated with the ingress controller of this Kubernetes Cluster. See this page for further details.
    }   
  }

  #https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver
  key_vault_secrets_provider {
    secret_rotation_enabled = true
    secret_rotation_interval = "30m"
  }

  default_node_pool {
    name                         = var.sys_np_name
    vm_size                      = var.sys_np_vm_size
    enable_auto_scaling          = var.sys_np_enable_auto_scaling
    enable_host_encryption       = true
    enable_node_public_ip        = false  # each node do not require public IP  
    scale_down_mode              = var.sys_np_scale_down_mode
    fips_enabled                 = try(var.sys_np_fips_enabled, false)
    kubelet_disk_type            = try(var.sys_np_kubelet_disk_type, "OS")
    max_pods                     = var.sys_np_max_pods 
    node_public_ip_prefix_id     = null
    node_labels                  = var.sys_np_labels
    only_critical_addons_enabled = var.sys_np_critical_addons
    orchestrator_version         = var.kubernetes_version
    os_disk_size_gb              = var.sys_np_os_disk_size_gb   # P10 128
    os_disk_type                 = "Managed" #  Ephemeral and Managed.
    os_sku                       = "Ubuntu"
    pod_subnet_id                = try(var.sys_np_pod_subnet_id, null)
    type                         = "VirtualMachineScaleSets"
    ultra_ssd_enabled            = try(var.sys_np_ultra_ssd_enabled, false)            
    vnet_subnet_id               = var.k8s_subnet_id     
    node_count                   = try(var.sys_np_default_node_count, 1)    
    max_count                    = (var.sys_np_enable_auto_scaling == true) ? try(var.sys_np_max_count, 1) : null
    min_count                    = (var.sys_np_enable_auto_scaling == true) ? try(var.sys_np_min_count, 1) : null
    zones                        = var.sys_np_zones   
    upgrade_settings {
      max_surge = 3
    }
    
    linux_os_config {
      sysctl_config {
        net_ipv4_tcp_keepalive_time = try(var.net_ipv4_tcp_keepalive_time, 7200)
        net_ipv4_tcp_keepalive_probes = try(var.net_ipv4_tcp_keepalive_probes, 9)
      }
    }
    
    tags                = var.tags_common
  } 

  identity {
    type         = var.id_type
    identity_ids = (var.id_type == "UserAssigned"  || var.id_type == "SystemAssigned, UserAssigned") ? var.cluster_uami_ids : []
  }

  kubelet_identity {
    client_id = var.kubelet_uami_client_id  # - (Required) The Client ID of the user-defined Managed Identity to be assigned to the Kubelets. If not specified a Managed Identity is created automatically.
    object_id = var.kubelet_uami_object_id # (Required) The Object ID of the user-defined Managed Identity assigned to the Kubelets.If not specified a Managed Identity is created automatically.
    user_assigned_identity_id = var.kubelet_uami_id # (Required) The ID of the User Assigned Identity assigned to the Kubelets. If not specified a Managed Identity is created automatically.
  }
  
  #record allows you to configure the settings that enable signing into the worker nodes using SSH.
  linux_profile {
    admin_username             = var.admin_username
    ssh_key {
      key_data                 = var.linux_ssh_pub_key
    }
  }
  
  maintenance_window {
    allowed {
      day   = "Sunday"
      hours = [4, 10]
    }
    #not_allowed {
    #  end   = "23:00:00Z" #2006-01-02T15:04:05Z07:00
    #  start = "10:00:00Z"
    #}
  }

  dynamic "windows_profile" {
    for_each = var.wadmin_user != "" && var.wadmin_password != ""? ["winprof"] : []
    content {
      admin_username = var.wadmin_user
      admin_password = var.wadmin_password
    }
  }

  # sets the advanced networking 
  network_profile {
    network_mode               = try(var.network_mode, "transparent")
    network_plugin             = try(var.network_plugin, "azure")
    load_balancer_sku          = try(var.load_balancer_sku, "Standard")
    load_balancer_profile { #block supports the following : These options are mutually exclusive. Note that when specifying outbound_ip_address_ids (azurerm_public_ip) the SKU must be Standard.
      #outbound_ports_allocated - (Optional) Number of desired SNAT port for each VM in the clusters load balancer. Must be between 0 and 64000 inclusive. Defaults to 0.
      #idle_timeout_in_minutes - (Optional) Desired outbound flow idle timeout in minutes for the cluster load balancer. Must be between 4 and 120 inclusive. Defaults to 30.
      idle_timeout_in_minutes = 30
      #managed_outbound_ip_count - (Optional) Count of desired managed outbound IPs for the cluster load balancer. Must be between 1 and 100 inclusive. Useer has to explicitly set managed_outbound_ip_count to empty slice ([]) to remove it.
      #outbound_ip_prefix_ids - (Optional) The ID of the outbound Public IP Address Prefixes which should be used for the cluster load balancer.User has to explicitly set outbound_ip_prefix_ids to empty slice ([]) to remove it.
      #outbound_ip_address_ids - (Optional) The ID of the Public IP Addresses which should be used for outbound communication for the cluster load balancer.NOTE User has to explicitly set outbound_ip_address_ids to empty slice ([]) to remove it.
    }
    dns_service_ip             = "10.0.0.10"  # Containers DNS server IP address.
    docker_bridge_cidr         = "172.17.0.1/16"  #A CIDR notation IP for Docker bridge.
    service_cidr               = "10.0.0.0/16"  # A CIDR notation IP range from which to assign service cluster IPs.
    ##pod_cidr  applicable whe set to kubenet
    network_policy             = try(var.network_policy, "calico")
    outbound_type              = try(var.network_outbound_type, "userDefinedRouting")  # Possible values are loadBalancer and userDefinedRouting. Defaults to loadBalancer.
  }

  timeouts {
    create = "2h"
    delete = "2h"
  }  

  tags                = var.tags_common
}
```

### Debug Output/Panic Output

```shell
We get below error
# Error: expected automatic_channel_upgrade to be one of [patch rapid stable node-image], got none / null

╷
│ Error: expected automatic_channel_upgrade to be one of [patch rapid stable node-image], got 
│ 
│   with module.AKS-CL-LGRI-ALPS.azurerm_kubernetes_cluster.k8s,
│   on TerraModules/14.AksModule/04.Aks.tf line 21, in resource "azurerm_kubernetes_cluster" "k8s":
│   21:   automatic_channel_upgrade       = try(var.automatic_channel_upgrade, null)  # patch, rapid, stable
│ 
╵
##[error]Bash exited with code '1'.
Finishing: Terraform plan
```

### Expected Behaviour

THe aumatic challen upgrade should take either null or none value.

### Actual Behaviour

We get below error
# Error: expected automatic_channel_upgrade to be one of [patch rapid stable node-image], got none / null

╷
│ Error: expected automatic_channel_upgrade to be one of [patch rapid stable node-image], got 
│ 
│   with module.AKS-CL-LGRI-ALPS.azurerm_kubernetes_cluster.k8s,
│   on TerraModules/14.AksModule/04.Aks.tf line 21, in resource "azurerm_kubernetes_cluster" "k8s":
│   21:   automatic_channel_upgrade       = try(var.automatic_channel_upgrade, null)  # patch, rapid, stable
│ 
╵
##[error]Bash exited with code '1'.
Finishing: Terraform plan

### Steps to Reproduce

automatic_channel_upgrade       = try(var.automatic_channel_upgrade, null)

#none or null both give error
variable "automatic_channel_upgrade" {
  type = string
  default = "none" # or null
}

### References

Can you please fix it in 3.45.1 or next release?

The error is  👍 
We get below error
# Error: expected automatic_channel_upgrade to be one of [patch rapid stable node-image], got none / null

╷
│ Error: expected automatic_channel_upgrade to be one of [patch rapid stable node-image], got 
│ 
│   with module.AKS-CL-LGRI-ALPS.azurerm_kubernetes_cluster.k8s,
│   on TerraModules/14.AksModule/04.Aks.tf line 21, in resource "azurerm_kubernetes_cluster" "k8s":
│   21:   automatic_channel_upgrade       = try(var.automatic_channel_upgrade, null)  # patch, rapid, stable
│ 
╵
##[error]Bash exited with code '1'.
Finishing: Terraform plan

**Comment by stephybun** [comment] 2023-05-05 07:04
Thanks for raising this issue @iamsoorya.

As [stated in the docs](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#automatic_channel_upgrade)

>_Omitting this field sets this value to none_

As a general rule [values like `none` are not exposed directly in the provider](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/topics/schema-design-considerations.md#the-none-value-or-similar) but rather the omission of the property implies the default value or `none` in this case. 
Since this is working as intended and neither a feature request nor a bug I am going to close this issue.

Should you have further questions regarding configuration I'd direct you towards the [Community Discuss forum](https://discuss.hashicorp.com/).

**Closed by stephybun** 2023-05-05 07:04 UTC
Labels: question, service/kubernetes-cluster
