### ISSUE TITLE
azurerm_eventgrid_event_subscription documentation has wrong scope on example

### ISSUE THREAD

**Issue by mehmettahameral** [hashicorp/terraform-provider-azurerm#24106] opened 2023-12-04 11:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.6

### AzureRM Provider Version

3.83.0

### Affected Resource(s)/Data Source(s)

azurerm_eventgrid_event_subscription

### Terraform Configuration Files

```hcl
N/A
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

resource "azurerm_eventgrid_event_subscription" "example" {
  name  = "example-aees"
  scope = **_azurerm_eventgrid_topic_**.example.id

  storage_queue_endpoint {
    storage_account_id = azurerm_storage_account.example.id
    queue_name         = azurerm_storage_queue.example.name
  }
}

### Actual Behaviour

resource "azurerm_eventgrid_event_subscription" "example" {
  name  = "example-aees"
  scope = **_azurerm_resource_group_**.example.id

  storage_queue_endpoint {
    storage_account_id = azurerm_storage_account.example.id
    queue_name         = azurerm_storage_queue.example.name
  }
}

### Steps to Reproduce

- Visit https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/eventgrid_event_subscription 
- View the example of the event grid subsription code
- Under azurerm_eventgrid_event_subscription block, the scope should be azurerm_eventgrid_topic rather than azurerm_resource_group

**Comment by harshavmb** [comment] 2023-12-04 16:40
Hi @mehmettahameral ,

I don't think this is a `bug`. You can see from restapi specs [here](https://learn.microsoft.com/en-us/rest/api/eventgrid/controlplane/event-subscriptions/create-or-update?view=rest-eventgrid-controlplane-2022-06-15&tabs=HTTP#uri-parameters).

> The scope can be a subscription, or a resource group, or a top level resource belonging to a resource provider namespace, or an EventGrid topic.

**Comment by xiaxyi** [comment] 2023-12-27 02:43
Thanks @mehmettahameral for raising this issue, as @harshavmb mentioned, this is not a bug. Besides of referring to the documentation, you can also try the sample code so you'll know the rg can be used as the scope.
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/92154856/a8a12d59-9f70-416f-8739-93d5c131a92e)

**Comment by xiaxyi** [comment] 2023-12-27 02:44
@rcskosir Thanks for labeling this issue, it's not a bug, appreciate if you could remove the bug tag. Thanks!

**Comment by rcskosir** [comment] 2024-02-14 18:22
Thanks for taking the time to submit this issue. On review, we’ve determined that the described behavior is as expected.
Whilst I'd like to thank you for opening this issue as we have no plans to change the scope in the documentation I'm going to close this issue.

**Closed by rcskosir** 2024-02-14 18:22 UTC
Labels: documentation, service/event-grid, v/3.x
