### ISSUE TITLE
Support for Azure Redis Cache to use AD Authentication

### ISSUE THREAD

**Issue by jonathan-fileread** [hashicorp/terraform-provider-azurerm#23777] opened 2023-11-03 22:28 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Azure Redis now allows AD authentication to use identity based authentication (e.g. through defaultazurecredential) to make a connection string to redis. 

Currently this exists in bicep, but not in terraform. We'd love to get a boolean toggle to enable this authentication method! See screenshot below. under Redis > Advanced Settings
<img width="436" alt="Screenshot 2023-11-03 at 6 24 46 PM" src="https://github.com/hashicorp/terraform-provider-azurerm/assets/133816798/4e023629-c2d8-4a91-b639-bf57bfe56edb">

### New or Affected Resource(s)/Data Source(s)

azurerm_redis_cache

### Potential Terraform Configuration

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

# NOTE: the Name used for Redis needs to be globally unique
resource "azurerm_redis_cache" "example" {
  name                = "example-cache"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  capacity            = 2
  family              = "C"
  **entra_authentication = true** <-- this one!
  sku_name            = "Standard"
  enable_non_ssl_port = false
  minimum_tls_version = "1.2"

  redis_configuration {
  }
}
```

### References

https://learn.microsoft.com/en-us/azure/azure-cache-for-redis/cache-azure-active-directory-for-authentication

**Comment by tombuildsstuff** [comment] 2023-11-06 08:47
Support for this is [available in `hashicorp/go-azure-sdk` in API version `2023-08-01`](https://github.com/hashicorp/go-azure-sdk/blob/4b17f17f485125a057f46c46c82f0041a0c492f3/resource-manager/redis/2023-08-01/redis/model_rediscommonpropertiesredisconfiguration.go#L7) - however it appears this needs to be updated to use the new API Version to enable this, so I'm tagging this as such.

**Comment by Waylonwhynot** [comment] 2023-11-21 07:01
When does the Terraform-provider-azurerm support this feature?

**Comment by favoretti** [comment] 2023-11-21 10:52
@Waylonwhynot in a bit, PR is being tested as we speak.

**Comment by dhensby** [comment] 2023-11-21 11:47
duplicate of #15068?

**Comment by favoretti** [comment] 2023-11-21 12:15
> duplicate of #15068?

Is it? Not sure to be honest. #15066 looks more like accessing underlying storage accounts using an either user-assigned or system-assigned managed identity, where as this is authentication towards redis instance itself?

**Comment by dhensby** [comment] 2023-11-21 13:22
Ah - ok - I thought they were related, but if they are distinct then that's fair enough

**Closed** 2023-11-28 20:57 UTC
Labels: enhancement, service/redis, sdk/requires-newer-api-version

**Comment by jonathan-fileread** [comment] 2024-01-04 20:03
thanks @favoretti @manicminer  for pushing this one out. 
While it is enabled, we're still missing functionality to add a redis_user, or access_policies via terraform. Should I create another ticket for this?

![Screenshot 2024-01-04 at 3 02 11 PM](https://github.com/hashicorp/terraform-provider-azurerm/assets/133816798/de765ac0-12cb-4626-985d-f4fac16f6770)
