### ISSUE TITLE
Support for azurerm_machine_learning_datastore_datalake_gen2 with a storage account in an another azure subscription

### ISSUE THREAD

**Issue by ltutar** [hashicorp/terraform-provider-azurerm#27336] opened 2024-09-10 11:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

The current implementation of resource _azurerm_machine_learning_datastore_datalake_gen2_ is not supporting a referral to a storage account in an another Azure subscription. This is also confirmed with [27254)](https://github.com/hashicorp/terraform-provider-azurerm/issues/27254)
It would be nice to have this functionality through Terraform since the Azure UI is providing this functionality.

### New or Affected Resource(s)/Data Source(s)

azurerm_machine_learning_datastore_datalake_gen2

### Potential Terraform Configuration

```hcl
# raw_layer_containers and the data storage are existing in a different Azure subscription.
resource "azurerm_machine_learning_datastore_datalake_gen2" "dsleventdev" {
  name                 = "levent"
  description          = "dsleventdev"
  workspace_id         = module.mlwsleventdev.id
  storage_container_id = data.azurerm_storage_containers.raw_layer_containers.containers[index(data.azurerm_storage_containers.raw_layer_containers.containers[*].name, var.levent_storage_account_container_name)].resource_manager_id
  tags                 = module.foundation.tags
}
```

**Comment by gustavnygren** [comment] 2024-10-27 20:24
Are there any updates on this, or have you been able to find a solution Itutar? Eager to get it to work :)

**Comment by ltutar** [comment] 2024-10-27 20:56
No @gustavnygren I do not have a solution. We have put this part out of terraform implementation and doing it unfortunately manually.

**Comment by gustavnygren** [comment] 2024-10-28 10:05
That's unfortunate. Thank you for responding :)

**Comment by sitengyu-hc** [comment] 2024-11-21 22:43
Closing this issue as it is considered a duplicate of https://github.com/hashicorp/terraform-provider-azurerm/issues/27254, which contains more details. If you think this is a mistake, please reach out and we are happy to re-open the issue

**Closed by sitengyu-hc** 2024-11-21 22:43 UTC
Labels: enhancement, service/machine-learning
