### ISSUE TITLE
Support for remove cdn_frontdoor_origin_ids in azurerm_cdn_frontdoor_route

### ISSUE THREAD

**Issue by benj-ch** [hashicorp/terraform-provider-azurerm#19449] opened 2022-11-28 10:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In Terraform, we have to provide the "cdn_frontdoor_origin_group_id" and the "cdn_frontdoor_origin_ids" properties when we create an "azurerm_cdn_frontdoor_route".
Through Azure Portal, we just provide the "cdn_frontdoor_origin_group_id".

There is no concept of origin inside a route in Azure Front Door Premium / Standard, only origin group.

### New or Affected Resource(s)/Data Source(s)

azurerm_cdn_frontdoor_route

### Potential Terraform Configuration

```hcl
Remove the property "cdn_frontdoor_origin_ids"
```

### References

* https://learn.microsoft.com/en-us/azure/frontdoor/standard-premium/how-to-configure-route

**Comment by WodansSon** [comment] 2022-11-29 03:44
@benj-ch, thank you for opening this issue. You are correct that there is no concept of origin inside of a route resource, however I had to expose this field to force Terraform to create/destroy the resources in the correct order. For example, without the `cdn_frontdoor_origin_ids` Terraform would attempt to create the origin and the route at the same time which would result in an error since the origin would not be associated with the origin group when the route attempted to associate with the origin group. I know it is sorta weird, but it is the lesser of the two evils here so at this point I feel this is the why it has to be unfortunately. 🚀

**Comment by benj-ch** [comment] 2022-11-29 08:28
@WodansSon thank you for your reply.
With your explanation, it makes sense.

My problem is I create "azurerm_cdn_frontdoor_origin" with a "for_each".
How list all the "azurerm_cdn_frontdoor_origin_ids" from a loop in the "azurerm_cdn_frontdoor_origin_group"?

I didn't find a wildcard like azurerm_cdn_frontdoor_origin.myorigins[*].id.

**Comment by benj-ch** [comment] 2022-11-29 10:47
I found a way to create a local value but I don't know if there is a better/simple way to do that

`originids = flatten([
    for x in local.origin : [
      azurerm_cdn_frontdoor_origin.myorigin[x].id
    ]
  ])`

**Comment by WodansSon** [comment] 2022-11-29 23:14
@benj-ch, what you have there seems reasonable to me. With that I am going to go ahead and close this issue as the original issue which was opened is currently by design. 🚀

**Closed by WodansSon** 2022-11-29 23:14 UTC
Labels: question, service/cdn
