### ISSUE TITLE
azurerm_log_analytics_saved_search function_parameters not created in correct order

### ISSUE THREAD

**Issue by phoeniver** [hashicorp/terraform-provider-azurerm#12539] opened 2021-07-09 14:27 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
v1.0
Installed hashicorp/azurerm v2.62.1 
Installed hashicorp/null v2.1.2

### Affected Resource(s)

* `azurerm_log_analytics_saved_search`

### Terraform Configuration Files

main.tf file
```hcl
...
resource "azurerm_log_analytics_saved_search" "function" {
  for_each                   = var.saved_functions
  name                       = each.key
  log_analytics_workspace_id = xxx

  category            = each.value.category
  display_name        = each.value.display_name
  query               = each.value.query
  function_alias      = each.value.function_alias
  function_parameters = each.value.function_parameters

  provider = azurerm.az
}
```
variables.tf file
```hcl
...
variable "saved_functions" {
  description = <<EOS
  Saved functions for each environment.
  EOS
  type = map(object({
    category            = string
    display_name        = string
    query               = string
    function_alias      = string
    function_parameters = list(string)
  }))
}
```
tfvars file
```
...
#saved functions
saved_functions = {
  "function1" = {
    category     = "functions"
    display_name = "test1"
    query        = "test1"
    function_alias = "test1"
    function_parameters = ["A:string", "B:string", "C:string"]
  }
  "function2" = {
    category     = "functions"
    display_name = "test2"
    query        = "test2"
    function_alias = "test2"
    function_parameters = ["A:string", "B:string", "C:string"]
  }
  "function3" = {
    category     = "functions"
    display_name = "test3"
    query        = "test3"
    function_alias = "test3"
    function_parameters = ["C:string", "B:string", "A:string"]
  }
  "function4" = {
    category     = "functions"
    display_name = "test4"
    query        = "test4"
    function_alias = "test4"
    function_parameters = ["D:string", "E:string", "F:string"]
  }
  "function5" = {
    category     = "functions"
    display_name = "test5"
    query        = "test5"
    function_alias = "test5"
    function_parameters = ["D:string", "E:string", "F:string"]
  }
  "function6" = {
    category     = "functions"
    display_name = "test6"
    query        = "test6"
    function_alias = "test6"
    function_parameters = ["F:string", "E:string", "D:string"]
  }
}
```

### Expected Behaviour
terraform should respect the sequence of the parameters, as those functions will be referenced in the queries, with the same sequence as defined in the functions. So when I put `function_parameters = ["C:string", "B:string", "A:string"]` in the tfvar files, it should create a resource with the following
```
    + function_parameters        = [
        + "C:string",
        + "B:string",
        + "A:string",
      ]
```

### Actual Behaviour
```
# azurerm_log_analytics_saved_search.function["function1"] will be created
...
    + function_parameters        = [
        + "A:string",
        + "B:string",
        + "C:string",
      ]
...
# azurerm_log_analytics_saved_search.function["function2"] will be created
...
    + function_parameters        = [
        + "A:string",
        + "B:string",
        + "C:string",
      ]
...
# azurerm_log_analytics_saved_search.function["function3"] will be created
...
    + function_parameters        = [
        + "A:string",
        + "B:string",
        + "C:string",
      ]
...
# azurerm_log_analytics_saved_search.function["function4"] will be created
    + function_parameters        = [
        + "D:string",
        + "E:string",
        + "F:string",
      ]
...
# azurerm_log_analytics_saved_search.function["function5"] will be created
...
    + function_parameters        = [
        + "D:string",
        + "E:string",
        + "F:string",
      ]
...
# azurerm_log_analytics_saved_search.function["function6"] will be created
...
    + function_parameters        = [
        + "D:string",
        + "E:string",
        + "F:string",
      ]
...
```
and what's more, on the azure portal, it's even messier...
![image](https://user-images.githubusercontent.com/12595853/125092606-80c8d780-e09f-11eb-982a-cf254da5f883.png)
The order of the parameters are totally messed up, even not same as the terraform output.

### Steps to Reproduce

1. `terraform apply`

**Comment by Korving-F** [comment] 2022-03-18 12:04
+1 Seems this issue is still present and seems to be caused by the List() operation on the Set in `resourceLogAnalyticsSavedSearchCreate`. See [here](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/loganalytics/log_analytics_saved_search_resource.go).
```bash
# Problematic call ordering the parameters
attrs := v.(*pluginsdk.Set).List()
```

**Comment by rtarasov** [comment] 2023-03-29 09:34
Still have the same problem. +1

**Comment by rtarasov** [comment] 2023-09-18 09:02
Hi Guys! What is the story about this issue? When do you plan to resolve it?
Thank you in advance!

**Comment by HassanMahmud** [comment] 2024-05-03 09:27
This is a serious problem for us. As we would like to use this resource for sentinel log parsers however the order of parameters is essential for this to work.

**Comment by HassanMahmud** [comment] 2024-05-06 09:55
Thanks for the hint @Korving-F I submitted a PR that seems to fix it for me locally. 

Also @rtarasov if you both interested in a fix perhaps go and do a thumbs up on the linked PR to get it merged in faster :)

**Closed** 2024-05-06 18:34 UTC
Labels: bug, service/log-analytics, v/3.x, v/2.x (legacy)
