### ISSUE TITLE
Update to v2.86.0 forces replacement of `azurerm_storage_account`s - 2.86.0 is not back compatible

### ISSUE THREAD

**Issue by sambyng-msft** [hashicorp/terraform-provider-azurerm#14279] opened 2021-11-19 18:15 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Details

Two new fields introduced in the `terraform-provider-azurerm` 2.86.0 will force replacement of pre-existing storage accounts. To me this seems like an urgent bug - it means that v2.86.0 is not back-compatible, the change made to is breaking.

As part of 2.86.0, new fields have been added to the azurerm terraform provider with both `ForceNew` option + default value provided - it looks like this is forcing re-creation of resources that were created with old terraform provider.

e.g. in 2.86.0 the azurerm_storage_account resource has had new fields `queue_encryption_key_type` and `table_encryption_key_type`  added, both with ForceNew and with default values as "Service".

https://github.com/hashicorp/terraform-provider-azurerm/pull/14080/files

Now running this over my existing storage accounts, terraform will force re-create the resources since these new fields did not exist before, and they have ForceNew on them - the change from 'empty' to 'value' forces re-creation.
```
  # module.blobstore.azurerm_storage_account.efix_storage_account[0] must be replaced
-/+ resource "azurerm_storage_account" "efix_storage_account" {
      + queue_encryption_key_type        = "Service" # forces replacement
      + table_encryption_key_type        = "Service" # forces replacement
...
}
```

### FIX

Proposed fix after discussing with @aristosvo : Remove the default value behaviour for the `queue_encryption_key_type` and `table_encryption_key_type` fields. Default will be empty unless specified during the initial create. Update tests and data source accordingly.

### PR for fix below:

https://github.com/hashicorp/terraform-provider-azurerm/pull/14278

### Terraform (and AzureRM Provider) Version

Terraform v1.0.9
Azurerm provider v2.86.0

### Affected Resource(s)

* `azurerm_storage_account` resource and data source

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behaviour

Storage account resources created before 2.86.0 remain the same when terraform AzureRMprovider is bumped to 2.86.0 

### Actual Behaviour

Storage account resources created before 2.86.0 are recreated when TF AzureRM provider is bumped to 2.86.0 

### Steps to Reproduce

1. Define a storage account resource with terraform provider 2.85.0
2. `terraform apply`
3. Bump terraform-provider-azurerm to 2.86.0.
4. `terraform apply -refresh=false`
5. Terraform will re-create the `storage_account_resource` - removing all previously contained data

### References

https://github.com/hashicorp/terraform-provider-azurerm/pull/14080/files
https://github.com/hashicorp/terraform-provider-azurerm/pull/14278

* #0000

**Comment by tombuildsstuff** [comment] 2021-11-22 14:30
hey @sambyng-msft 

Thanks for opening this issue.

Prior to running any commands (plan/apply) by default Terraform runs a `refresh` to load the current state of the Storage Account into memory to be able to provide an up-to-date plan.

Unfortunately the Azure Storage API's behave a little differently to other Azure API's insofar as when a field is introduced in the API with a default value (as in this case) older resources provisioned before this field was available will have an implicit default value which unfortunately isn't returned from the API (and won't be unless it's changed). This differs from resources provisioned _after_ this functionality is available (or in an API version which supports it) where this value will be returned.

What this means for Terraform is that we end up having to set these implicit defaults in Terraform (as we are in this case) by defaulting this in the Read function if a value isn't returned from the API - which whilst isn't ideal, removes this diff from the plan.

Whilst it's possible to set `-refresh=false` as a flag in Terraform, we'd generally discourage using it for the plan/apply stage (although it can be useful in the destroy stage) since it means that Terraform isn't up to date when a plan is run.

I've gone through and tested an upgrade here from v2.80 -> v2.86 and with the defaults for a Terraform Plan/Apply (which uses `-refresh=true`) this is correctly picked up as a change (outside of Terraform, since it's a new field in the API which isn't tracked in the state), but due to the refresh and the default value this shows as a loop:

```hcl
terraform plan
azurerm_resource_group.example: Refreshing state... [id=/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/tharvey-dev]
azurerm_storage_account.example: Refreshing state... [id=/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/tharvey-dev/providers/Microsoft.Storage/storageAccounts/tomdevsa9999]

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

# azurerm_resource_group.example has been changed
~ resource "azurerm_resource_group" "example" {
     id       = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/tharvey-dev"
     name     = "tharvey-dev"
   + tags     = {}
     # (1 unchanged attribute hidden)
 }
# azurerm_storage_account.example has been changed
~ resource "azurerm_storage_account" "example" {
     id                             = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/tharvey-dev/providers/Microsoft.Storage/storageAccounts/tomdevsa9999"
     name                           = "tomdevsa9999"
   + queue_encryption_key_type      = "Service"
   + table_encryption_key_type      = "Service"
     tags                           = {
         "environment" = "staging"
     }
     # (31 unchanged attributes hidden)




     # (4 unchanged blocks hidden)
 }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using
ignore_changes, the following plan may include actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────────────────────────────────────

No changes. Your infrastructure matches the configuration.

Your configuration already matches the changes detected above. If you'd like to update the Terraform state to
match, create and apply a refresh-only plan:
terraform apply -refresh-only
```

As such from Terraform's side this appears to be working as intended - whilst it's possible to use `-refresh=false`, we'd highly recommend not doing so to ensure that the state of Azure (e.g. any configuration drift) is detected and can be reconciled.

In this instance it should be possible to workaround this by running a refresh-only plan (e.g. `terraform apply -refresh-only`) - however we'd strongly encourage you to use `-refresh=true` here.

Since this behaviour is working as intended (to account for new fields in Azure) - whilst I'd like to thank you for opening this issue, I'm going to close this at the moment.

Thanks!

**Closed by tombuildsstuff** 2021-11-22 14:30 UTC
Labels: bug, service/storage
