### ISSUE TITLE
Rulestack commit happens for every rule

### ISSUE THREAD

**Issue by shankar-bala** [hashicorp/terraform-provider-azurerm#23505] opened 2023-10-10 17:18 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

v1.3.7

### AzureRM Provider Version

3.69.0

### Affected Resource(s)/Data Source(s)

azurerm_palo_alto_local_rulestack_rule

### Terraform Configuration Files

```hcl
# create resource group
resource azurerm_resource_group "rg" {
    name = "rg-${var.resource_suffix}"
    location = var.location
    tags = var.tags
} 

# create vnet/subnets

resource "azurerm_virtual_network" "vnet" {
  name                = "vnet-fw-${var.resource_suffix}"
  address_space       = [var.vnet_cidr]
  location            = var.location

  resource_group_name = azurerm_resource_group.rg.name

  tags = {
    Purpose = "terraform testing"
  }
}

# create localrulestack
resource azurerm_palo_alto_local_rulestack "lrs1" {
    name = "lrs-${var.resource_suffix}-1"
    resource_group_name = azurerm_resource_group.rg.name
    location = var.location
    description = "rulestack1"
}

resource azurerm_palo_alto_local_rulestack "lrs2" {
    name = "lrs-${var.resource_suffix}-2"
    resource_group_name = azurerm_resource_group.rg.name
    location = var.location
    description = "rulestack2"
}

# create prefix list
resource "azurerm_palo_alto_local_rulestack_prefix_list" "prefix" {
  name         = "prefix-${var.resource_suffix}"
  prefix_list  = [ "10.0.2.0/26" ]
  rulestack_id = azurerm_palo_alto_local_rulestack.lrs1.id
  description = "prefixlist1"

  depends_on = [ azurerm_palo_alto_local_rulestack.lrs1 ]
}

# create fqdn list
resource azurerm_palo_alto_local_rulestack_fqdn_list "fqdn" {
  name = "fqdn-${var.resource_suffix}"
  rulestack_id = azurerm_palo_alto_local_rulestack.lrs1.id
  fully_qualified_domain_names = ["www.defnews.com"]
  depends_on = [ azurerm_palo_alto_local_rulestack.lrs1 ]
}

# create certificate (self signed)
resource "azurerm_palo_alto_local_rulestack_certificate" "cert" {
  name         = "cert-${var.resource_suffix}"
  rulestack_id = azurerm_palo_alto_local_rulestack.lrs1.id
  self_signed = true
  # key_vault_certificate_id  = "https://kvtesting456.vault.azure.net/certificates/kvtesting"
  depends_on = [ azurerm_palo_alto_local_rulestack.lrs1 ]
}

# creare local rulestack rule
resource "azurerm_palo_alto_local_rulestack_rule" "localrule" {
  name          = "rule-${var.resource_suffix}"
  rulestack_id = azurerm_palo_alto_local_rulestack.lrs1.id
  priority      = 1000
  
  applications  = ["any"]

  source {
    cidrs = ["192.168.16.0/24"]
  }
  destination {
    cidrs = ["192.168.16.0/24"]
  }
  action = "Allow"

  depends_on = [ azurerm_palo_alto_local_rulestack.lrs1 ]
  tags = var.tags
}

# create localrulestack rule2
resource "azurerm_palo_alto_local_rulestack_rule" "localrule2" {
  name          = "rule2-${var.resource_suffix}"
  rulestack_id = azurerm_palo_alto_local_rulestack.lrs1.id
  priority      = 1001
  
  applications  = ["any"]

  source {
    cidrs = ["192.168.16.0/25"]
  }
  destination {
    cidrs = ["192.168.16.0/25"]
  }
  action = "Allow"

  depends_on = [ azurerm_palo_alto_local_rulestack.lrs1 ]
  tags = var.tags
}

resource "azurerm_palo_alto_local_rulestack_rule" "localrule3" {
  name          = "rule3-${var.resource_suffix}"
  rulestack_id = azurerm_palo_alto_local_rulestack.lrs1.id
  priority      = 1002
  
  applications  = ["any"]

  source {
    cidrs = ["192.168.16.0/25"]
  }
  destination {
    cidrs = ["192.168.16.0/25"]
  }
  action = "Allow"

  depends_on = [ azurerm_palo_alto_local_rulestack.lrs1 ]
  tags = var.tags
}

resource "azurerm_palo_alto_local_rulestack_rule" "localrule5" {
  name          = "rule5-${var.resource_suffix}"
  rulestack_id = azurerm_palo_alto_local_rulestack.lrs1.id
  priority      = 1003
  
  applications  = ["any"]

  source {
    cidrs = ["192.168.16.0/25"]
  }
  destination {
    cidrs = ["192.168.16.0/25"]
  }
  action = "Allow"

  depends_on = [ azurerm_palo_alto_local_rulestack.lrs1 ]
  tags = var.tags
}

resource "azurerm_palo_alto_local_rulestack_rule" "localrule4" {
  name          = "rule4-${var.resource_suffix}"
  rulestack_id = azurerm_palo_alto_local_rulestack.lrs1.id
  priority      = 1004
  
  applications  = ["any"]

  source {
    cidrs = ["192.168.16.0/25"]
  }
  destination {
    cidrs = ["192.168.16.0/25"]
  }
  action = "Allow"

  depends_on = [ azurerm_palo_alto_local_rulestack.lrs1 ]
  tags = var.tags
}
```

### Debug Output/Panic Output

```shell
azurerm_palo_alto_local_rulestack_rule.localrule3: Still creating... [2m10s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule5: Creation complete after 2m11s [id=/subscriptions/5b06bdb3-3a0c-4c26-a14d-7a5322b21f07/resourceGroups/rg-tfTest01/providers/PaloAltoNetworks.Cloudngfw/localRulestacks/lrs-tfTest01-1/localRules/1003]
azurerm_palo_alto_local_rulestack_rule.localrule4: Still creating... [2m20s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule3: Still creating... [2m20s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule4: Still creating... [2m30s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule3: Still creating... [2m30s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule3: Still creating... [2m40s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule4: Still creating... [2m40s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule3: Still creating... [2m50s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule4: Still creating... [2m50s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule4: Still creating... [3m0s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule3: Still creating... [3m0s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule4: Still creating... [3m10s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule3: Still creating... [3m10s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule4: Still creating... [3m20s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule3: Still creating... [3m20s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule4: Still creating... [3m30s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule3: Still creating... [3m30s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule3: Still creating... [3m40s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule4: Still creating... [3m40s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule4: Still creating... [3m50s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule3: Still creating... [3m50s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule3: Still creating... [4m0s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule4: Still creating... [4m0s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule3: Still creating... [4m10s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule4: Still creating... [4m10s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule3: Creation complete after 4m10s [id=/subscriptions/5b06bdb3-3a0c-4c26-a14d-7a5322b21f07/resourceGroups/rg-tfTest01/providers/PaloAltoNetworks.Cloudngfw/localRulestacks/lrs-tfTest01-1/localRules/1002]
azurerm_palo_alto_local_rulestack_rule.localrule4: Still creating... [4m20s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule4: Still creating... [4m30s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule4: Still creating... [4m40s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule4: Still creating... [4m50s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule4: Still creating... [5m0s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule4: Still creating... [5m10s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule4: Still creating... [5m20s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule4: Still creating... [5m30s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule4: Still creating... [5m40s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule4: Still creating... [5m50s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule4: Still creating... [6m0s elapsed]
azurerm_palo_alto_local_rulestack_rule.localrule4: Creation complete after 6m8s [id=/subscriptions/5b06bdb3-3a0c-4c26-a14d-7a5322b21f07/resourceGroups/rg-tfTest01/providers/PaloAltoNetworks.Cloudngfw/localRulestacks/lrs-tfTest01-1/localRules/1004]
```

### Expected Behaviour

We would like to perform rulestack commit once after all the rules are created. Instead we are noticing commit happening for every rule which is not correct.

### Actual Behaviour

Perform final rulestack commit only once after all other rulestack related operations are done.

### Steps to Reproduce

Set the environment variables to communicate with azure cloud.
Run terraform apply.
Add more rules., you should see rulestack commit happening for every rule.

### References

This request has been reopened from previous request - https://github.com/hashicorp/terraform-provider-azurerm/issues/23471

In cloudngfw aws, we have a separate terraform resource for rules and commiting rulestack. 

Rules - https://registry.terraform.io/providers/PaloAltoNetworks/cloudngfwaws/latest/docs/resources/security_rule
Rulestack commit - https://registry.terraform.io/providers/PaloAltoNetworks/cloudngfwaws/latest/docs/resources/commit_rulestack

1. Can we have similar approach in cloudngfw azure as well ?
2. Can the commit operation be performed once at the end of terraform apply after all the rules are created  ? 

Commiting after every rule really takes longer when customer have more rules.

**Comment by neil-yechenwei** [comment] 2023-10-11 04:06
Thanks for raising this issue. I assume that the structure of service APIs is different between aws and azure. So seems I didn't find this kind of service API in azure.

**Comment by shankar-bala** [comment] 2023-10-16 16:55
Issue is not just happening due to certificate resources.,if firewall creation is initiated at the same time as other resources., we end up failing with commit timeout errors. 

**Here are the test scenarios we validated with terraform.**
1. Create firewall + rulestack with no rules , tf apply , and then later add 100*rules , tf apply - **worked**
2. Create Only rulestack with 100 rules (no firewall)- **worked**
3. Firewall + only rulestack with no rules - **worked**
4. Firewall + rulestack + 3*rules - failed with commit process unfinished error - **failed**
5. Firewall + Rulestack + 3*rules (with depends_on parameter added with all the rules to the firewall resource) - **worked**

Above commit related error started happening when firewall create call is initiated along with all other resource creations.
By adding “depends_on” and add every rule resource as a dependency, then we are able to create the firewall (because firewall creation is initiated after all the rules are created)

**Issues with approach 5:**
1. Every rule performs implicit commit which takes lot of time.
2. We need to add every rule as a "depends_on" in the firewall resource block.
3. Is there a way to get dynamic block supported in azurerm_palo_alto_local_rulestack_rule resource that performs commit once for all the rules ? this way we can create all the rules in a loop and commit at once..

**Comment by davi-palo** [comment] 2023-10-20 09:11
@neil-yechenwei structure of service APIs are same between AWS and Azure i.e., are PUT operations for rulestack resource and POST operation to commit it.

**Comment by tombuildsstuff** [comment] 2023-10-20 09:39
hi @davi-palo @shankar-bala 

As was discussed in #23471, this is by design - Terraform doesn't mark a resource as "completed" until it's fully provisioned, which in this case means both creating the rule stack and then committing the associated change. Given the design of the Azure API - and that the Provider has no means of knowing when all Rules have been committed, unfortunately we have to call this API after every commit, to ensure that the change is fully committed.

As such this functionality is working as intended (because otherwise Terraform couldn't offer it's consistency guarantees) and as such unfortunately we have no plans to introduce a `commit` resource. Unfortunately a `commit` resource would be problematic for users, and is something that we actively discourage as a Terraform resource.

Whilst the design of this API is going to be problematic for users with a large number of rules, and there might be scope for a separate resource which takes a list of _rules_ (e.g. which ensures that only those rules are configured) - that's not something we've had a feature request for at this point in time, but if that's something you'd be interested in then please feel free to open a new feature request and we can take a look.

However since this is working as intended and as such we have no plans to introduce a `commit` resource, whilst I'd like to thank you for opening this issue - unfortunately I'm going to have to close this at the moment since we have no plans to introduce a separate `commit` resource.

Thanks!

**Closed by tombuildsstuff** 2023-10-20 09:39 UTC
Labels: v/3.x, service/paloalto

**Comment by davi-palo** [comment] 2023-10-20 09:52
@tombuildsstuff thanks for your input and suggestion how to address this. We will open a new feature request for a separate resource which takes a list of rules.
