### ISSUE TITLE
parsing CSV expected the path to contain 2 segments but got 4

### ISSUE THREAD

**Issue by stumueller** [hashicorp/terraform-provider-azurerm#25297] opened 2024-03-18 14:19 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.4

### AzureRM Provider Version

3.96.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_blob

### Terraform Configuration Files

```hcl
resource "azurerm_storage_blob" "lookup_endpoints_csv" {
  name                   = "metadata/learner/endpoints.csv"
  storage_account_name   = var.data_lake_storage_account_name
  storage_container_name = "raw"
  type                   = "Block"
  source                 = "${path.module}/../../metadata/learner/endpoints.csv"
  content_md5            = md5(file("${path.module}/../../metadata/learner/endpoints.csv"))
}

csv contents
name,endpoint
LearnerCulturals,"learner/odata/v3/LearnerCulturals/{ESSChanges}"
LearnerDietarys,"learner/odata/v3/LearnerDietarys/{ESSChanges}$expand=FreeMealEligibilityPeriods"
LearnerGrants,"learner/odata/v3/LearnerGrants/{ESSChanges}$expand=PupilPremiumEligibilitys"
LearnerIdentifiers,"learner/odata/v3/LearnerIdentifiers/{ESSChanges}"
LearnerLookups,"learner/odata/v3/LearnerLookups/{ESSChanges}"
LearnerPersonals,"learner/odata/v3/LearnerPersonals/{ESSChanges}"
LearnerRegistrations,"learner/odata/v3/LearnerRegistrations/{ESSChanges}$expand=Enrolments($expand=EnrolmentStatuses)"
LearnerWelfares,"learner/odata/v3/LearnerWelfares/{ESSChanges}$expand=InCareDetails"
LearnerSENs,"sen/odata/v3/LearnerSENs/{ESSChanges}$expand=SENStatuses"
LearnerSENLookups,"sen/odata/v3/LearnerSENLookups/{ESSChanges}"
```

### Debug Output/Panic Output

```shell
Error: parsing "https://address.blob.core.windows.net/raw/metadata/learner/endpoints.csv": expected the path to contain 2 segments but got 4
│ 
│   with module.common.azurerm_storage_blob.lookup_endpoints_csv,
│   on modules/common/metadata.tf line 1, in resource "azurerm_storage_blob" "lookup_endpoints_csv":
│    1: resource "azurerm_storage_blob" "lookup_endpoints_csv" {
│
```

### Actual Behaviour

Error: parsing "https://address.blob.core.windows.net/raw/metadata/learner/endpoints.csv": expected the path to contain 2 segments but got 4
│ 
│   with module.common.azurerm_storage_blob.lookup_endpoints_csv,
│   on modules/common/metadata.tf line 1, in resource "azurerm_storage_blob" "lookup_endpoints_csv":
│    1: resource "azurerm_storage_blob" "lookup_endpoints_csv" {
│ 

### Important Factoids

Moving back to azurerm provider 3.95.0 fixed this issue

**Comment by tombuildsstuff** [comment] 2024-03-18 14:29
hey @stumueller 

Thanks for opening this issue.

Taking a look through here this appears to be a duplicate of https://github.com/hashicorp/terraform-provider-azurerm/issues/25266, rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of https://github.com/hashicorp/terraform-provider-azurerm/issues/25266 - would you mind subscribing to that issue for updates? However in the interim, as you've mentioned, it should be possible to workaround this issue by pinning to `v3.95.0` of the AzureRM Provider until the fix for this is released.

Thanks!

**Closed by tombuildsstuff** 2024-03-18 14:29 UTC
Labels: bug, duplicate, service/storage, v/3.x
