### ISSUE TITLE
azurerm_storage_management_policy tier_to_archive_after_days_since_modification_greater_than = 0 not working for storage account setup with GRS replication for blob storage.

### ISSUE THREAD

**Issue by drkennetz** [hashicorp/terraform-provider-azurerm#11176] opened 2021-03-31 16:58 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.14.9
+ provider registry.terraform.io/hashicorp/azurerm v2.53.0
```

### Affected Resource(s)

* `azurerm_storage_management_policy`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = ">=2.49.0"
    }
  }
}

provider "azurerm" {
  features {}
}
resource "azurerm_resource_group" "storage_test" {
  name = "storage_test"
  location = "centralus"
}

resource "azurerm_storage_account" "test-storage" {
  name = "teststoragedkennetz"
  resource_group_name = azurerm_resource_group.storage_test.name
  location = "centralus"
  account_tier = "Standard"
  account_replication_type = "GRS"
  account_kind = "BlobStorage"
  access_tier = "Cool"
}

resource "azurerm_storage_container" "test_container" {
  name = "testcontainer"
  storage_account_name = azurerm_storage_account.test-storage.name
  container_access_type = "private"
}

resource "azurerm_storage_management_policy" "longterm" {
  storage_account_id = azurerm_storage_account.test-storage.id

  rule {
    name = "Archive"
    enabled = true
    filters {
      prefix_match = [join("", [azurerm_storage_container.test_container.name, "/*"])]
      blob_types = ["blockBlob"]
    }
    actions {
      base_blob {
        tier_to_archive_after_days_since_modification_greater_than = 0
      }
    }
  }
}
```

### Debug Output
[gist](https://gist.github.com/drkennetz/d47fcd00729d1d8e343b4e693a4711d9)

### Expected Behaviour
A storage account with the management policy: move blobs to archive tier after 0 days of modification.

### Actual Behaviour
The storage account and container were created, and then terraform errored out when creating the policy.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

After investigation, it turns out that the number cannot be 0. I have copied the code in the docs [azurerm_storage_management_policy](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_management_policy)

and tried with this. I have deleted everything except the tier_to_archive portion and tried this number with 0 and 1, and it works with 1 and fails with 0.

### References

* #0000

**Comment by yupwei68** [comment] 2021-04-25 07:21
Duplicated of https://github.com/terraform-providers/terraform-provider-azurerm/issues/6158

**Comment by rcskosir** [comment] 2024-05-02 20:15
Thanks for taking the time to submit this issue. It looks like this is a duplicate of #6158. We like to try to keep discussions consolidated, so we’re going to close this issue.

**Closed by rcskosir** 2024-05-02 20:15 UTC
Labels: question, service/storage, v/2.x (legacy)
