### ISSUE TITLE
AZ PostgreSQL Flexible Server - Static Server Parameter (shared_preload_libraries) Recognizes as update-in-place

### ISSUE THREAD

**Issue by cg-mls** [hashicorp/terraform-provider-azurerm#21356] opened 2023-04-10 16:24 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.7

### AzureRM Provider Version

3.44.1

### Affected Resource(s)/Data Source(s)

azurerm_postgresql_flexible_server_configuration

### Terraform Configuration Files

```hcl
variable "shared_preload_libraries" {
  type        = list(string)
  description = "Must be a string, which is why used with join function"
  default = [
    "wal2json",
    "pg_cron",
    "pg_stat_statements"
  ]
}

resource "azurerm_postgresql_flexible_server_configuration" "shared_preload_libraries" {
  name      = "shared_preload_libraries"
  server_id = azurerm_postgresql_flexible_server.postgres_flexible.id
  value     = join(",", var.shared_preload_libraries)
}
```

Note: I have given a plain string for the value instead of using a variable, it still didn't make a difference, and wanted to make an update in place.

### Debug Output/Panic Output

```shell
~ value     = "pg_cron,pg_stat_statements,wal2json" -> "pg_cron,wal2json,pg_stat_statements"
```

### Expected Behaviour

No changes required.

### Actual Behaviour

Terraform will perform update-in-place

### Steps to Reproduce

Run tf apply and create `shared_preload_libraries` server configuration.
After apply is completed successfully, run another tf apply. You will see that tf will recognize it as a change, and run another apply. That causes server to restart after every single apply even if there are no actual changes. We could use lifecycle ignore changes temporarily, however that is not a long term solution.

### Important Factoids

N/A

### References

I believe there was this pr https://github.com/hashicorp/terraform-provider-azurerm/pull/20044 got merged in for static parameters to cause restart on the server. Might be the root cause of the issue.

**Comment by neil-yechenwei** [comment] 2023-04-13 08:10
Thanks for raising this issue.
Service team confirmed that restarting server against static parameters is expected behavior.
Here the problem is that the sequence of the value is changed in api response after set the server parameter.

**Comment by neil-yechenwei** [comment] 2023-04-14 02:07
Thanks for raising this issue. I assume you have to set the value alphabetically. See more details from [here](https://github.com/hashicorp/terraform-provider-azurerm/pull/21409#discussion_r1165324291).

**Comment by cg-mls** [comment] 2023-04-14 14:23
Thank you, will try to list em alphabetically

**Comment by rcskosir** [comment] 2024-06-06 18:40
Thank you for taking the time to raise this! I am going to close this with @neil-yechenwei‘s response as an answer. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).

**Closed by rcskosir** 2024-06-06 18:40 UTC
Labels: question, service/postgresql, v/3.x
