### ISSUE TITLE
azurerm_role_assignment would be planed to replace

### ISSUE THREAD

**Issue by Shabahang** [hashicorp/terraform-provider-azurerm#22283] opened 2023-06-26 11:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.5

### AzureRM Provider Version

3.61.0

### Affected Resource(s)/Data Source(s)

azurerm_role_assignment

### Terraform Configuration Files

```hcl
when with version 3.61.0 and 3.62.0 , the object azurerm_role_assignment will be planed to replace , while it is not the case on 3.58.0.

   # azurerm_role_assignment.<.....> must be replaced
-/+ resource "azurerm_role_assignment" "<.....>" {
...
...
~ principal_id = "......." -> "........." # forces replacement

Plan: 1 to add, 0 to change, 1 to destroy.
```

### Debug Output/Panic Output

```shell
# azurerm_role_assignment.<.....> must be replaced
-/+ resource "azurerm_role_assignment" "<.....>" {
...
...
~ principal_id = "......." -> "........." # forces replacement

Plan: 1 to add, 0 to change, 1 to destroy.
```

### Expected Behaviour

It should bot be planed to replacement, and it was not in 3.58.0

**Comment by rcskosir** [comment] 2023-06-26 13:45
Thanks for taking the time to submit this issue. Unfortunately, it looks like the configuration you provided is missing some key pieces that we don’t want to make assumptions about. Please update this issue with a more complete configuration of the azurerm_role_assignment so that we are able to work on reproducing this.

**Comment by rcskosir** [comment] 2024-03-19 21:21
Thanks for taking the time to submit this issue. Unfortunately we aren’t able to investigate this without the relevant portions of your Terraform configuration file(s). We are going to close this issue - if you are able to provide us with additional information we may reopen this.

**Closed by rcskosir** 2024-03-19 21:21 UTC
Labels: waiting-response, service/roles, v/3.x
