### ISSUE TITLE
Can't authenticate to Azure using MSI - terraform hangs and nothing happens

### ISSUE THREAD

**Issue by tdevopsottawa** [hashicorp/terraform-provider-azurerm#16501] opened 2022-04-21 23:50 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.9

### AzureRM Provider Version

3.2.0

### Affected Resource(s)/Data Source(s)

Authentication in provider

### Terraform Configuration Files

```hcl
terraform {
  backend "azurerm" {
    container_name       = "tfstate-kubeflow"
    key                  = "nonprod/storage/terraform.tfstate"
    resource_group_name  = "pep-poc-ecomm-01-terraform"
    storage_account_name = "pepecommpocterraform"
    subscription_id      = "80306051-70ac-4ae0-95c7-5e797ba30a9c"
  }
}

resource "azurerm_storage_account" "storage_gen2_kubeflow" {
  name                     = var.kubeflow_storage_name
  resource_group_name      = var.az_resource_group_name
  location                 = var.az_location
  account_tier             = "Standard"
  account_replication_type = var.storage_replication_type
  account_kind             = "StorageV2"
  is_hns_enabled           = true
  tags                     = var.tags
}

resource "azurerm_storage_container" "kubeflow_storage" {
  name                  = "testblob"
  storage_account_name  = azurerm_storage_account.storage_gen2_kubeflow.name
}

provider "azurerm" {
  subscription_id            = "d6a9062c-4c82-4e49-8204-100c57f33583"
  skip_provider_registration = true
  features {}
}

variable "kubeflow_storage_name" {
  type = string
}

variable "az_resource_group_name" {
  type = string
}

variable "az_location" {
  type    = string
  default = "eastus"
}

variable "storage_replication_type" {
  type    = string
  default = "LRS"
}

variable "tags" {
  type    = map(string)
  default = {}
}
```

### Debug Output/Panic Output

```shell
https://gist.github.com/tdevopsottawa/c5ad72f6669dd087039d7878fcd8ed27
```

### Expected Behaviour

Terraform should have authenticated to Azure using the Managed Identity that I have configured in my environment variables.

I have ARM_USE_MSI="true" set in my environment variables along with ARM_SUBSCRIPTION_ID, ARM_TENANT_ID, and ARM_CLIENT_ID.

When I attempt this with none of those environment variables set while logged into Azure CLI, it works fine using my personal user. But with the managed identity it doesn't work and this results.

### Actual Behaviour

After asking me to confirm the variables, it said "Acquiring state lock.. this may take a few moments" and then nothing happened, the screen just hung for over an hour before I force cancelled it.

### Steps to Reproduce

1. export ARM_USE_MSI=true
2. export ARM_SUBSCRIPTION_ID=<id of subscription>
3. export ARM_TENANT_ID=<id of tenant>
4. export ARM_CLIENT_ID=<client id of managed identity>
5. terraform init
6. terraform plan

**Comment by tombuildsstuff** [comment] 2022-04-22 06:24
hi @tdevopsottawa 

Thanks for opening this issue.

Taking a look through here it appears that the MetaData Service isn't available:

> dial tcp 169.254.169.254:80: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

If Terraform is being run within a Container (on say AKS) note that the MetaData Service isn't directly available, and (IIRC) additional configuration is needed for Pod's to be able to communicate with it. This document contains instructions on how to curl the MetaData service to confirm it's accessible, which I think should help: https://docs.microsoft.com/en-us/azure/virtual-machines/windows/instance-metadata-service?tabs=linux

Since this appears to be a configuration/environment issue rather than a bug in the Azure Provider I'm going to close this issue for the moment - but if you can confirm that the MetaData Service is available and this is still occurring then we can take another look.

Thanks!

**Closed by tombuildsstuff** 2022-04-22 06:24 UTC
Labels: question

**Comment by tdevopsottawa** [comment] 2022-04-22 14:39
I'm not running it within a container, I'm running it directly from Windows using the CLI.

**Comment by tdevopsottawa** [comment] 2022-04-22 21:54
I got this comment back from Microsoft:
"If Hashicorp requires communication to IMDS for Terraform to work, it seems like it’s intended to be run from within the VM. When I’ve seen other customer environments using Terraform in the past it’s been from Azure VMs."

This is a pretty big limitation to not be mentioned in the documentation: authenticating to Azure with managed identities is only supported if terraform is being run inside an Azure VM??

**Comment by tombuildsstuff** [comment] 2022-04-23 06:19
@tdevopsottawa MSI is only available within Azure VM's and Containers, both of which need an identity assigned for it to work (whilst App Service also supports MSI, it's not something we support for various reasons).

Unfortunately the Azure IMDS is only available when running inside of Azure, it won't be accessible from your local desktop as the MetaData Service only responds from the Guest VM - that's by design by Azure unfortunately.

Running locally your options for authenticating are:

* [Authenticating using the Azure CLI and a User Account](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/azure_cli)
* [Authenticating using a Service Principal and a Client Certificate](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_certificate)
* [Authenticating using a Service Principal and a Client Secret](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_secret)
* [Authenticating using a Managed Identity (when running inside of an Azure VM, or Azure Container etc)](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/managed_service_identity)

**Comment by tdevopsottawa** [comment] 2022-04-25 15:18
@tombuildsstuff Ok, good to know.

I think the Azurerm documentation here (https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/managed_service_identity) should be modified to make this limitation clear.
