### ISSUE TITLE
Adding NSG to an existing NIC which is associated to VM causes VM to destroy and recreate

### ISSUE THREAD

**Issue by smits23** [hashicorp/terraform-provider-azurerm#11668] opened 2021-05-11 23:59 UTC
Please confirm if adding NSG to an existing NIC should cause VM to destroy and recreate?.

azure rm version : 2.57.0
Tf version 0.15.1

**Comment by magodo** [comment] 2021-05-14 05:35
@smits23 Normally this shouldn't be the case. Could you please provide the steps how to reproduce the issue?

**Comment by smits23** [comment] 2021-05-14 14:18
Sure:
I tested 3 scenarios: 
Scenario1: 
I created 2 local modules 
1. Nsg (which creates NSG resource and all Nsg rules)
2. Module 2 (Nic and Vm) - since I wanted to create an unmanaged disk linux vm used azurerm_virtual_machine
3. Main.tf will First call Nsg module t create Nsg
4. then Call Nic/VM module and pass Nsg resource ID which needs to be attached to the NIC
5. Result: TF Plan indicated the  New NSG, Nic  linked with Nsg and VM destroy and recreate

Scanrio2: 
Created 3 modules NGS, NIC, VM
Same result as above: TF Plan indicated the  New NSG, Nic  linked with Nsg and VM destroy and recreate

Scenario 3: 
Created one module where Nsg, Nic and Vm are all inside one module
Result: No changes to the VM.


Snapshot of main.tf which was calling call 3 modules (scenario3)

## Nsg
module "nsg" {
  source = "./modules/nsg"
  
   rg_name                  = azurerm_resource_group.ib.name
  location                         = azurerm_resource_group.ib.location 
  cost_center                      = var.cost_center
  owner                            = var.owner
  technicalContact                 = var.technicalContact
  environment                      = var.environment  
  nsgName                          = var.nsgName  

}

## NIC
module "nic" {
  source = "./modules/nic"
  
  rg_name                  = azurerm_resource_group.ib.name
  location                         = azurerm_resource_group.ib.location 
  cost_center                      = var.cost_center
  owner                            = var.owner
  technicalContact                 = var.technicalContact
  environment                      = var.environment 
  nic_data                         = var.nic_data 
  nsgId                            = module.nsg.nsgId   

  depends_on = [
    module.nsg
    ]

}


## VM
module "virtual_machine" {
  source = "./modules/virtual_machine"
  
  rg_name                  = azurerm_resource_group.ib.name
  location                         = azurerm_resource_group.ib.location 
  cost_center                      = var.cost_center
  owner                            = var.owner
  technicalContact                 = var.technicalContact
  environment                      = var.environment  
  vm_name                          = var.vm_name
  pwd                              = var.pwd
  storage_disk                     = var.storage_disk
  container_name_disk              = var.container_name_disk
  storage_diag                     = var.storage_diag
  ib_offer                         = var.ib_offer 
  ib_version                       = var.ib_version
  ib_plan_product                  = var.ib_plan_product
  keyvaultRgName                   = var.keyvaultRgName
  keyvaultName                     = var.keyvaultName
  ib_vm_password                   = var.ib_vm_password
  nic_1                            = module.nic.primaryNic_id
  nic_2                            = module.nic.secondaryNic_id


  depends_on = [
    azurerm_resource_group_template_deployment.storage_1,
    azurerm_resource_group_template_deployment.storage_2,
    module.nic
    ]

}

**Comment by smits23** [comment] 2021-05-18 17:03
@magodo  do you have any more questions?

**Comment by magodo** [comment] 2021-05-19 08:23
@smits23 Thank you for providing the three scenarios, is it possible to also provide the content of the moduels, for either scenario1 or senario2, so that I can reproduce/further investigate the issue.

**Comment by smits23** [comment] 2021-05-28 23:14
Attached all modules and main.tf which passes the variables

Order of execution:
Deploy storage accr
Deploy nsg
Deploy Nic 
Deploy VM

After all resources are deployed
I found  in the case when all modules were separated out, if there were any changes made to storage acct or nsg or nic then TF plan says ( vM will be replaced)

One example: Tiniest change can be  an update to tag name on NS\G or Storage account
 

[vm_module.txt](https://github.com/terraform-providers/terraform-provider-azurerm/files/6563645/vm_module.txt)
[nic_module.txt](https://github.com/terraform-providers/terraform-provider-azurerm/files/6563643/nic_module.txt)
[nsg_module.txt](https://github.com/terraform-providers/terraform-provider-azurerm/files/6563647/nsg_module.txt)

[storage_acct_arm_module.txt](https://github.com/terraform-providers/terraform-provider-azurerm/files/6563648/storage_acct_arm_module.txt)



provider "azurerm" {
  subscription_id = var.az_sub_id
  tenant_id       = var.az_tenant_id
  client_id       = var.az_client_id
  client_secret   = var.az_client_secret
  features {}
}


resource "azurerm_resource_group" "ib" {
  name     = var.infobox_rg_name
  location = var.location
}

#deploy storage using arm with tf arm template stored under arm folder
resource "azurerm_resource_group_template_deployment" "storage_1" {
name                = var.storage_diag
resource_group_name = azurerm_resource_group.ib.name  

template_content = file("./arm/storage.tfvars.json")

parameters_content = jsonencode({
    "storageAccountName" = {
      value = var.storage_diag
    }
    "storageaccountsku" = {
      value = "Standard_LRS"
    }
    "storageaccountTier" = {
      value = "Standard"
    } ,
    "container_name": {
            value = var.container_name_diag
        }     
  })

  deployment_mode = "Incremental"

}

resource "azurerm_resource_group_template_deployment" "storage_2" {
name                = var.storage_disk
resource_group_name = azurerm_resource_group.ib.name  

template_content = file("./arm/storage.tfvars.json")

parameters_content = jsonencode({
    "storageAccountName" = {
      value = var.storage_disk
    },
    "storageaccountsku" = {
      value = "Premium_LRS"
    },
    "storageaccountTier" = {
      value = "Premium"
    },
    "container_name": {
            value = var.container_name_disk
        }    
  })

  deployment_mode = "Incremental"

}

## Nsg
module "nsg" {
  source = "./modules/nsg"
  
  infobox_rg_name                  = azurerm_resource_group.ib.name
  location                         = azurerm_resource_group.ib.location  
  nsgName                          = var.nsgName  

}

## NIC
module "nic" {
  source = "./modules/nic"
  
  infobox_rg_name                  = azurerm_resource_group.ib.name
  location                         = azurerm_resource_group.ib.location  
  nic_data                         = var.nic_data 
  nsgId                            = module.nsg.nsgId   

  depends_on = [
    module.nsg
    ]

}


## VM
module "virtual_machine" {
  source = "./modules/virtual_machine"
  
  infobox_rg_name                  = azurerm_resource_group.ib.name
  location                         = azurerm_resource_group.ib.location 
  vm_name                          = var.vm_name
  pwd                              = var.pwd
  storage_disk                     = var.storage_disk
  container_name_disk              = var.container_name_disk
  storage_diag                     = var.storage_diag
  ib_offer                         = var.ib_offer 
  ib_version                       = var.ib_version
  ib_plan_product                  = var.ib_plan_product
  keyvaultRgName                   = var.keyvaultRgName
  keyvaultName                     = var.keyvaultName
  ib_vm_password                   = var.ib_vm_password
  nic_1                            = module.nic.primaryNic_id
  nic_2                            = module.nic.secondaryNic_id


  depends_on = [
    azurerm_resource_group_template_deployment.storage_1,
    azurerm_resource_group_template_deployment.storage_2,
    module.nic
    ]

}

**Comment by smits23** [comment] 2021-05-28 23:14
Sorry for the late response, should you have any questions  about the structure please message me.

**Comment by magodo** [comment] 2021-06-01 00:00
@smits23 From the terraform plan output, do you see which property change results into a replacement of the VM?

**Comment by smits23** [comment] 2021-06-01 13:32
Sure:

Use case 1: 
1. Deploy Storage account, NSG,  NIC and VM (DO NOT ASSOCIATE NSG with NIC RIGH NOW)
2. After deployment 1, update NIC by associating NSG ID with NICs [nsgId  = module.nsg.nsgId  ]
Actual: Tf plan shows: NIC update  & VM replace and recreate

Use case 2 : Deploy all resources, then - Update a tag on storage account and then run TF plan 
Actual: Tf plan shows: Storage account tag update  & VM replace and recreate

**Comment by magodo** [comment] 2021-06-02 05:13
@smits23 can you please also attach the `terraform plan` output here for both use cases? The output should indicate the reason why the VM will be replaced.

**Comment by smits23** [comment] 2021-06-02 14:10
Let me look for the TF Plan and send it over to you.

**Comment by smits23** [comment] 2021-06-07 14:51
![Snag_45ef23](https://user-images.githubusercontent.com/25985686/121038300-cc712400-c775-11eb-9f61-be086ceff768.png)
![Snag_460385](https://user-images.githubusercontent.com/25985686/121038311-cf6c1480-c775-11eb-8757-2bf8cf794bc2.png)
Adding few screenshots of TF plan:

Screenshot 1: show that since we added NSG ID association with NIC -its is destroring  NIC and recreating it
Screenshot 2: VM is replaced

**Comment by magodo** [comment] 2021-06-08 01:23
The NIC is not recreating, but the association. This is as expected. The VM got replaced due to something changed inside the `os_profile`, either the `custom_data` or the `computer_name`, can you further check the input variable `vm_name` and the keyvault secret in the vm module remain the same between provisionings?

Since there are some dependent resources in your provisioning and a bunch of variables, if you can minimize the steps/scale to reproduce this issue so that I can reproduce it locally, it would be easier for me to further investigate.

**Comment by smits23** [comment] 2021-06-08 14:26
VM name and custom data  should not have any change. 

I had recently made changes to my modules and only kept two
1. Storage modules (which is arm with tf deployment, due to a SA deployment issue I was seeing with TF)
2. VM (NIC+NSG+VM)

I realized one of storage account tag was not updated. I made that change in storage account tag and did a TF pan. 
Again TF plan shows new tags (being added in SA) and VM replaced.  But there are no changes what soever in the VM that I am making.

**Comment by smits23** [comment] 2021-06-17 17:55
Hi, do you need any other data from me? 
I am not changing anything inside this VM, why does the plan says VM is getting replaced? Is it any bug related to custom data?

**Comment by magodo** [comment] 2021-06-18 02:13
@smits23 What is the content fed to `custom_data`? Also, do you have a minialized/self-contained tf config that I can run locally to reproduce the issue?

**Comment by smits23** [comment] 2021-06-18 13:19
I need to create a dummy project and send it to you. Give  me few days.

Content of custom data is base64encode("remote_console_enabled: y\ndefault_admin_password: ${data.azurerm_key_vault_secret.secret.value}\ntemp_license: dns dhcp grid")

${data.azurerm_key_vault_secret.secret.value} = secret being pulled from our keyvault. 
Note: I do always see in plan that data source for keyvault always shows changes, not sure if that has any impact.

**Comment by magodo** [comment] 2021-06-18 13:55
That is my initial guess, if the key vault secret value changes, then it will introduce changes in the `custom_data`, which in turns causes the VM to be replaced.

**Comment by smits23** [comment] 2021-06-18 14:18
The secret for the VM  hasn't changed, but we re continuously adding new secrets for other resources. I was hoping that does not cause any impact.
I will test in my test env by removing the Keyvault dependency and using secret from Azdo libraries and see the impact as well. Give me a week's time I will update you the result as well as share a dummy project for testing. Thank you.

**Comment by smits23** [comment] 2021-06-22 16:20
@magodo I did a quick test by removing keyvault data source ref for the VM password 
data "azurerm_key_vault" "keyvault" and  data "azurerm_key_vault_secret" "secret" from my VM module to refer to secret from Azdo variable library group and this time the VM replace/destroy  was prevented. 
I think there is an issue with data source ref with key vault which thinks there are changes in the secret and thus VM  should be replaced.

**Comment by smits23** [comment] 2021-06-22 16:21
I am yet to create a sample project for you to test, I will send it over by end of this week.

**Comment by smits23** [comment] 2021-08-10 00:01
@magodo sorry for such a delay, I have created a sample project for you to test, I am testing the scenario once again to see if it still occurs, and then attach the dummy project for your review and testing. I really appreciate your patience.

**Comment by tombuildsstuff** [comment] 2021-08-10 08:58
hi @smits23 

Taking a look through here whilst this is actually a bug in Terraform Core's refusing of data sources, it's worth noting that the `azurerm_virtual_machine` resource has since been superseded by the `azurerm_linux_virtual_machine` and `azurerm_windows_virtual_machine` resources. Whilst the existing `azurerm_virtual_machine` resource continues to be available in 2.x releases of the Provider, it's feature-frozen and thus no longer receiving any bugfixes or enhancements to maintain compatibility.

Since this is ultimately a bug in Terraform Core rather than the Azure Provider, I'm going to close this issue for the moment, but you [may want to open a bug on the upstream Terraform Core repository](https://github.com/hashicorp/terraform) where someone from that team should be able to take a look. However I'd recommend looking into the [`azurerm_linux_virtual_machine`](https://www.terraform.io/docs/providers/azurerm/r/linux_virtual_machine.html) and [`azurerm_windows_virtual_machine`](https://www.terraform.io/docs/providers/azurerm/r/windows_virtual_machine.html) resources going forward.

Thanks!

**Closed by tombuildsstuff** 2021-08-10 08:58 UTC
Labels: question

**Comment by smits23** [comment] 2021-08-10 15:15
@tombuildsstuff  thanks, the VM that I need is an unmanaged disk and azurerm_linux_virtual_machine will not work for me,
