### ISSUE TITLE
Error creating KeyVault Secret from Service Bus Authorization Rule

### ISSUE THREAD

**Issue by Fazer87** [hashicorp/terraform-provider-azurerm#15366] opened 2022-02-10 17:23 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

**Terraform Version:**
1.1.4
**Providers:**
hashicorp/azurerm v2.95.0...
hashicorp/random v3.1.0...
hashicorp/azuread v2.17.0...

### Affected Resource(s)

- azurerm_key_vault_secret
- azurerm_servicebus_namespace_authorization_rule

### Terraform Configuration Files

```hcl
data "azuread_client_config" "current" {}
data "azurerm_client_config" "current" {}

provider "azurerm" {
  features {}
  skip_provider_registration = true
}


resource "azurerm_key_vault" "Keyvault_primary" {
  name                            = "Project-DEV"
  location                        = azurerm_resource_group.project_resourcegroup_primary.location
  resource_group_name  = azurerm_resource_group.project_resourcegroup_primary.name
  tags                               = azurerm_resource_group.project_resourcegroup_primary.tags
  tenant_id                       = data.azurerm_client_config.current.tenant_id
  soft_delete_retention_days      = 30
  purge_protection_enabled        = false
  sku_name                        = "standard"
  enabled_for_template_deployment = true
  enable_rbac_authorization       = false
}

resource "azurerm_key_vault_access_policy" "Keyvault_TerraformAccess_primary" {
  key_vault_id = azurerm_key_vault.Keyvault_primary.id
  tenant_id    = data.azurerm_client_config.current.tenant_id
  object_id    = data.azurerm_client_config.current.object_id
  key_permissions = [
    "Backup", "Create", "Decrypt", "Delete", "Encrypt", "Get", "Import", "List",
    "Purge", "Recover", "Restore", "Sign", "UnwrapKey", "Update", "Verify", "WrapKey"
  ]
  secret_permissions = [
    "Backup", "Delete", "Get", "List", "Purge", "Recover", "Restore", "Set"
  ]
  certificate_permissions = [
    "Backup", "Create", "Delete", "DeleteIssuers", "Get", "GetIssuers", "Import", "List",
    "ListIssuers", "ManageContacts", "ManageIssuers", "Purge", "Recover", "Restore", "SetIssuers", "Update"
  ]
}

resource "azurerm_servicebus_namespace" "project_ServiceBus_primary" {
  name                = "Project-SB-DEV"
  resource_group_name = azurerm_resource_group.project_resourcegroup_primary.name
  location            = azurerm_resource_group.project_resourcegroup_primary.location
  tags                = azurerm_resource_group.project_resourcegroup_primary.tags
  sku                 = "Basic"
}

resource "azurerm_servicebus_namespace_authorization_rule" "servicebus_applicationauthorizationrule_primary" {
  name         = "MyAccessRule"
  namespace_id = azurerm_servicebus_namespace.servicebus_primary.id
  listen = true
  send   = true
  manage = false
}

resource "azurerm_key_vault_secret" "KVSecret_ServiceBusConnectionString_Primary" {
  name         = "servicebus-connectionstring"
  value        = azurerm_servicebus_namespace_authorization_rule.servicebus_applicationauthorizationrule_primary.primary_connection_string
  key_vault_id = azurerm_key_vault.Keyvault_primary.id
}

```

### Panic Output

N/A - No Panic

### Expected Behaviour

Service Bus Auth Rule Connection string should be saved as a KeyVault secret

### Actual Behaviour

```
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # azurerm_key_vault_secret.KVSecret_ServiceBusConnectionString_Primary will be created
  + resource "azurerm_key_vault_secret" "KVSecret_ServiceBusConnectionString_Primary" {
      + id             = (known after apply)
      + key_vault_id   = "/subscriptions/<Snip>/resourceGroups/<Snip>/providers/Microsoft.KeyVault/vaults/Project-DEV"
      + name           = "servicebus-connectionstring"
      + value          = (sensitive value)
      + version        = (known after apply)
      + versionless_id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
azurerm_key_vault_secret.KVSecret_ServiceBusConnectionString_Primary: Creating...
|
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to
│ azurerm_key_vault_secret.KVSecret_ServiceBusConnectionString_Primary,
│ provider "provider[\"registry.terraform.io/hashicorp/azurerm\"]" produced
│ an unexpected new value: Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.

```

### Steps to Reproduce

1. `terraform apply`

**Comment by Fazer87** [comment] 2022-02-10 17:27
It is worth noting with this bug that although the apply fails, the KeyVault secret successfully creates with the correct value.  On re-running the apply, I get a message telling me that the secret already exists and to import into state if I want it to be TF managed.

Manual inspection of the KeyVault secret against the value of the connection string in the azure portal shows me that the correct value is in the secret and the deploy has worked - it just hasn't made it into state following the error.

**Comment by sinbai** [comment] 2022-02-11 08:28
@Fazer87 thank you for opening this issue. There is a similar issue [#11059](https://github.com/hashicorp/terraform-provider-azurerm/issues/11059). Could you please subscribe to that issue for updates?

**Comment by IvanBodnya** [comment] 2022-03-02 10:16
Was this issue fixed somehow?

**Comment by rcskosir** [comment] 2023-07-26 15:04
Thanks for taking the time to submit this issue. It looks like this is a duplicate of #11059. We like to try to keep discussions consolidated, so we’re going to close this issue.

**Closed by rcskosir** 2023-07-26 15:04 UTC
Labels: bug, service/key-vault, v/2.x (legacy)
