### ISSUE TITLE
Support for changing create_mode of azurerm_mysql_flexible_server without causing recreation of the resource

### ISSUE THREAD

**Issue by GeorgiStefanov2001** [hashicorp/terraform-provider-azurerm#22901] opened 2023-08-10 13:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

After creating an azurerm_mysql_flexible_server with create_mode set to either "Replica", "GeoRestore" or "PointInTimeRestore", there should be the option to change create_mode to "Default" on consequent terraform operations. The need for this arises from the fact that a Replica server can be promoted to an independent server + a Geo or Point-In-Time restored server becomes independent after creation. This means that the server no longer must track the source_server_id of the primary server. In such cases there must be a way to track the server's configuration in Terraform state correctly from this point onwards in order to be able to change its parameters. The only way to do so right now is to use the "Default" create mode, but any changes to create_mode after the server has been created (including setting it to null) cause recreation, which is not an option for production environments. 

### New or Affected Resource(s)/Data Source(s)

azurerm_mysql_flexible_server

### References

A similar issue has been opened for the Azure PostgreSQL Flexible Server - https://github.com/hashicorp/terraform-provider-azurerm/issues/21821

**Comment by neil-yechenwei** [comment] 2023-08-11 06:37
Thanks for raising this issue. Service team confirmed that createMode cannot be changed once it's set while creating.

**Comment by GeorgiStefanov2001** [comment] 2023-08-11 07:59
@neil-yechenwei Thanks for the swift response! Are you aware of a workaround for managing the TF states of such promoted servers right now?

**Comment by neil-yechenwei** [comment] 2023-08-11 08:23
Suggest to either use ignore_changes or specify corresponding value in tf config.

**Comment by rcskosir** [comment] 2024-01-30 20:51
Thank you for taking the time to raise this! I am going to close this since there is no enhancement to be made on our side, with @neil-yechenwei ‘s response that this is by service API design.  If you have further questions such as a workaround this service API design, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).

**Closed by rcskosir** 2024-01-30 20:51 UTC
Labels: enhancement, question, upstream/microsoft, service/mysql

**Comment by zenum4** [comment] 2024-04-24 09:29
@neil-yechenwei @rcskosir I might be wrong here, but isn't it actually a design bug?
The documentation says the following:

> While creating the resource, create_mode cannot be set to Update.

At the same time createMode cannot be changed once it's set while creating and it's by design.
If understand it correctly that effectively means that the create_mode Update can never be used (cannot be set on creation and cannot be changed to later) and, as a result, it's not possible to update the version without the resource recreation (which is not an option on prod).

Please note that the same problem exists for Postgres Flexible Server (#21821).
