### ISSUE TITLE
azurerm_virtual_network and azurerm_subnet changes blocked and fails

### ISSUE THREAD

**Issue by taipignas** [hashicorp/terraform-provider-azurerm#19781] opened 2022-12-22 11:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.7

### AzureRM Provider Version

3.31.0

### Affected Resource(s)/Data Source(s)

azurerm_virtual_network, azurerm_subnet

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_network" "vnet" {
  name                = "${var.env}-123123-vnet"
  address_space       = var.ip_address_range_for_vnet
  resource_group_name = azurerm_resource_group.resource_group.name
  location            = azurerm_resource_group.resource_group.location

  tags = {}
}

resource "azurerm_private_dns_zone" "dns_zone" {
  name                = "privatelink.database.windows.net"
  resource_group_name = azurerm_resource_group.resource_group.name

  soa_record {
    email = "azureprivatedns-host.microsoft.com"
  }

  tags = {}
}

resource "azurerm_route_table" "vnet_route" {
  name                          = "${var.env}-123123-routing-table"
  location                      = azurerm_resource_group.resource_group.location
  resource_group_name           = azurerm_resource_group.resource_group.name
  disable_bgp_route_propagation = false

  route {
    name                   = "Default"
    address_prefix         = "0.0.0.0/0"
    next_hop_type          = "VirtualAppliance"
    next_hop_in_ip_address = var.static_ip
  }

  tags = {}
}

resource "azurerm_private_dns_zone_virtual_network_link" "dns_vnet_link" {
  name                  = "${var.env}-123123-vnet-link"
  resource_group_name   = azurerm_resource_group.resource_group.name
  private_dns_zone_name = azurerm_private_dns_zone.dns_zone.name
  virtual_network_id    = azurerm_virtual_network.vnet.id

  tags = {}
}

resource "azurerm_subnet" "vnet_generic_subnet" {
  name                                      = "${var.env}-123123-generic-subnet"
  resource_group_name                       = azurerm_resource_group.resource_group.name
  virtual_network_name                      = azurerm_virtual_network.vnet.name
  address_prefixes                          = [var.ip_address_range_for_generic_subnet]
  service_endpoints                         = ["Microsoft.Sql"]
  private_endpoint_network_policies_enabled = false
}

resource "azurerm_subnet" "vnet_function_subnet" {
  name                                      = "${var.env}-123123-function-subnet"
  resource_group_name                       = azurerm_resource_group.resource_group.name
  virtual_network_name                      = azurerm_virtual_network.vnet.name
  address_prefixes                          = [var.ip_address_range_for_function_subnet]
  private_endpoint_network_policies_enabled = false
  delegation {
    name = "function-app-delegation"
    service_delegation {
      name    = "Microsoft.Web/serverFarms"
      actions = ["Microsoft.Network/virtualNetworks/subnets/action"]
    }
  }
}

resource "azurerm_subnet_route_table_association" "vnet_route_association" {
  subnet_id      = azurerm_subnet.vnet_generic_subnet.id
  route_table_id = azurerm_route_table.vnet_route.id
}

resource "azurerm_private_endpoint" "db_privateendpoint" {
  name                = "${var.env}-123123-db-private-endpoint"
  location            = azurerm_resource_group.resource_group.location
  resource_group_name = azurerm_resource_group.resource_group.name
  subnet_id           = azurerm_subnet.vnet_generic_subnet.id

  private_dns_zone_group {
    name                 = "default"
    private_dns_zone_ids = [azurerm_private_dns_zone.dns_zone.id]
  }

  private_service_connection {
    name                           = "${var.env}-123123-db-private-endpoint"
    private_connection_resource_id = azurerm_mssql_server.mssql_server.id
    subresource_names              = ["sqlServer"]
    is_manual_connection           = false
  }

  tags = {}
}


resource "azurerm_service_plan" "service_plan" {
  name                = "${var.env}-123123-service-plan"
  resource_group_name = azurerm_resource_group.resource_group.name
  location            = azurerm_resource_group.resource_group.location
  os_type             = "Linux"
  sku_name            = "B1"

  tags = {}
}

resource "azurerm_linux_function_app" "function_app" {
  name                      = "${var.env}-123123-function-app"
  resource_group_name       = azurerm_resource_group.resource_group.name
  location                  = azurerm_resource_group.resource_group.location
  service_plan_id           = azurerm_service_plan.service_plan.id
  virtual_network_subnet_id = azurerm_subnet.vnet_function_subnet.id

  storage_account_name       = azurerm_storage_account.storage_account.name
  storage_account_access_key = azurerm_storage_account.storage_account.primary_access_key

  app_settings = {
    SCM_DO_BUILD_DURING_DEPLOYMENT = false
  }


ip_address_range_for_vnet = "123.123.123.16/28"
ip_address_range_for_generic_subnet = "123.123.123.16/29"
ip_address_range_for_function_subnet = "123.123.123.24/29"
```

### Debug Output/Panic Output

```shell
various errors depending what steps are done manually
```

### Expected Behaviour

terraform completes without manual help, deleted the blocking resources and then recreates them as needed

### Actual Behaviour

terraform fails, i need to manually delete blocking resources first
1. vnet is blocked by subnets
2. generic subnet is blocked by private endpoint
3. function subnet is blocked by function app

### Steps to Reproduce

1. apply the terraform with vnet 123.123.123.16/28 and subnets 123.123.123.16/29, 123.123.123.24/29
2. change terraform configuration to vnet 123.123.123.128/25 and subnets123.123.123.128/26, 123.123.123.192/26 and apply

**Comment by sinbai** [comment] 2022-12-23 11:15
@taipignas thanks for opening this issue. Since the [address_space](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_network#address_space) of azurerm_virtual_network is not a property that forces a new Virtual Network to be created when it is changed, this is by design. The [address_prefixes ](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/subnet#address_prefixes) of azurerm_subnet is also the same. In this case, it seems that we should remove all the resources that using the subnets in tf configuration(this is because subnets  in use could not be updated" ), update vnet and subnets, and then add the removed resources back.

**Comment by rcskosir** [comment] 2024-06-11 20:52
Thank you for taking the time to raise this! I am going to close this with @sinbai‘s response as an answer. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).

**Closed by rcskosir** 2024-06-11 20:52 UTC
Labels: question, service/virtual-networks, v/3.x
