### ISSUE TITLE
Support for v2 Authentication in Azure App Service

### ISSUE THREAD

**Issue by chlsmith** [hashicorp/terraform-provider-azurerm#15853] opened 2022-03-16 12:05 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I see no way to enable Azure App Service v2 authentication with the provider. When I do try to configure auth, I get an error that the app is already on v2.

"Details=[{"Message":"Cannot execute the request for site <mysite> because the site is running on auth version v2."

### New or Affected Resource(s)

azurerm_app_service, azurerm_function_app

### Potential Terraform Configuration

```hcl
resource "azurerm_function_app" "example" {
  app_service_plan_id        = azurerm_app_service_plan.example.id
  location                   = var.location
  name                       = var.name
  resource_group_name        = var.resource_group
  storage_account_name       = var.storage_account_name
  storage_account_access_key = var.storage_account_primary_access_key
  https_only                 = true
  version                    = "~3"
  os_type                    = "linux"
  enabled                    = true
  app_settings = merge({
    "WEBSITE_RUN_FROM_PACKAGE" = "1"
    "FUNCTIONS_WORKER_RUNTIME" = "python"
  }, var.app_settings)
  identity {
    type = "SystemAssigned"
  }

  site_config {
    linux_fx_version = "Python|3.9"
    ftps_state       = "Disabled"
    http2_enabled    = true
  }

  auth_settings {
    enabled = true
    **version=v2**
    microsoft {
      client_id         = var.aad_client_id
      client_secret     = var.aad_client_secret
    }
    unauthenticated_client_action = "RedirectToLoginPage"
  }
```

**Comment by tombuildsstuff** [comment] 2022-03-16 12:51
Duplicate of #12928

**Closed by tombuildsstuff** 2022-03-16 12:51 UTC
