### ISSUE TITLE
azurerm_container_app ingress At least 1 "traffic_weight" blocks are required.

### ISSUE THREAD

**Issue by error0327** [hashicorp/terraform-provider-azurerm#21640] opened 2023-05-03 12:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

│ Error: Insufficient traffic_weight blocks
│ 
│   on modules/container_app/main.tf line 31, in resource "azurerm_container_app" "container_app":
│   31:   ingress {
│ 
│ At least 1 "traffic_weight" blocks are required.

a bug appears to be related to Terraform's validation of the azurerm_container_app resource when revision_mode is set to "Single". Even though traffic_weight is not required when revision_mode is set to "Single", Terraform is still asking you to add a traffic_weight block.

### Terraform Version

1.4.6

### AzureRM Provider Version

1.4.6

### Affected Resource(s)/Data Source(s)

azurerm_container_app

### Terraform Configuration Files

```hcl
resource "azurerm_container_app" "container_app" {
  name                         = "containerapp-${var.env}"
  container_app_environment_id = azurerm_container_app_environment.container_app_environment.id
  resource_group_name          = var.resource_group_name
  revision_mode                = "Single"

  ingress {
    external_enabled = true
    target_port      = 8080
  }
}
```

### Debug Output/Panic Output

```shell
http://
```

### Expected Behaviour

Creating the container_app

### Actual Behaviour

│ Error: Insufficient traffic_weight blocks
│ 
│   on modules/container_app/main.tf line 31, in resource "azurerm_container_app" "container_app":
│   31:   ingress {
│ 
│ At least 1 "traffic_weight" blocks are required.

### Steps to Reproduce

terraform apply

### Important Factoids

No

**Comment by luizbon** [comment] 2023-05-05 05:53
There is a workaround to get the TF working if `latest_revision` is set to `true`.
```
  ingress {
    traffic_weight {
      percentage = 100
      latest_revision = true
    }
  } 
```

**Comment by jtatum** [comment] 2023-07-06 17:00
This appears to be a dupe of #20537.

**Comment by rcskosir** [comment] 2023-07-07 17:43
Thanks for taking the time to submit this issue. And thank you @jtatum for noting the duplication. It looks like this is a duplicate of #20537. We like to try to keep discussions consolidated, so we’re going to close this newer issue in favor of #20537.

**Closed by rcskosir** 2023-07-07 17:43 UTC
Labels: bug, duplicate, service/container-apps
