### ISSUE TITLE
Unable to create a GPT-4o deployment via the terraform-azurerm-openai module 

### ISSUE THREAD

**Issue by MBKraus** [hashicorp/terraform-provider-azurerm#26681] opened 2024-07-18 09:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.4

### AzureRM Provider Version

3.112.0

### Affected Resource(s)/Data Source(s)

Azure/openai/azurerm/latest

### Terraform Configuration Files

```hcl
locals {
  deployment_map = {
    dev = {
      "chat_model_gpt_4o_2024_05_13" = {
        name          = "gpt-4o-2024-05-13"
        model_format  = "OpenAI"
        model_name    = "gpt-4o"
        model_version = "2024-05-13"
        scale_type    = "Standard"
        capacity      = 2
      },
    }
    prod = {
      "chat_model_gpt_4o_2024_05_13" = {
        name          = "gpt-4o-2024-05-13"
        model_format  = "OpenAI"
        model_name    = "gpt-4o"
        model_version = "2024-05-13"
        scale_type    = "Standard"
        capacity      = 6
      },
    }
  }
}

module "openai" {
  source                        = "Azure/openai/azurerm"
  version                       = "0.1.3"
  account_name                  = "${replace(var.namespace, "_", "-")}-openai-service-${var.environment}"
  custom_subdomain_name         = "${replace(var.namespace, "_", "-")}-openai-service-${var.environment}"
  resource_group_name           = azurerm_resource_group.resource_group.name
  location                      = azurerm_resource_group.resource_group.location
  public_network_access_enabled = true
  deployment                    = local.deployment_map[var.environment]
  depends_on = [
    azurerm_resource_group.resource_group,
  ]
}
```

### Debug Output/Panic Output

```shell
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

### Expected Behaviour

A gpt-4o deployment should have been created in Sweden Central

### Actual Behaviour

No gpt-4o deployment got created in Sweden Central. I tried different model_name and model_version formats, but no success. Via the Azure UI/console I can easily create a GPT-4o deployment. Also, all other models (e.g. gpt-3.5 all work fine via the Azure/openai/azurerm module

### References

The module I used: https://registry.terraform.io/modules/Azure/openai/azurerm/latest

**Comment by lonegunmanb** [comment] 2024-07-22 00:37
Greetings @MBKraus thanks for reporting this issue to us! I'm the module's maintainer and I've opened a new issue [here](https://github.com/Azure/terraform-azurerm-openai/issues/87), since it looks like a module's issue, I've posted my reply there, would you mind take a look? If we could continue our discussion there, could you please do me a favor by closing this issue? You're welcome to reopen it once we're sure that this issue is caused by a provider's bug, but now I think it seems more likely a module's issue, thanks for your understanding!

**Closed** 2024-07-22 06:11 UTC
Labels: v/3.x

**Comment by ankursharmalb** [comment] 2024-07-30 18:33
getting this error InvalidResourceProperties: The specified scale type 'Standard' of account deployment is not supported by the model 'gpt-4o'.

**Comment by cffranco94** [comment] 2024-08-01 14:16
@ankursharmalb , i am also having the same issue. did you manage to solve it? I noticed that the scale type in an already deployed gpt4o model is "Global-Standard", I tried, but it did not worked.
