### ISSUE TITLE
No error/warn during creating postgres server

### ISSUE THREAD

**Issue by PedroEss** [hashicorp/terraform-provider-azurerm#21338] opened 2023-04-07 09:37 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

I have discovered an issue during creating postgres server that when we add block identity

```
  identity {
    type         = var.post_identity_type
    identity_ids = [ azurerm_user_assigned_identity.base_postgres.id ]
  }
```
and we will not add block customer_managed_key

```
customer_managed_key {
  key_vault_key_id = ""
  primary_user_assigned_identity_id =""
}
```
the azurerm is going to wait till timeout:

```
{"error":{"code":"ExpiredAuthenticationToken","message":"The access token expiry UTC time '4/6/2023 3:08:09 PM' is earlier than current UTC time '4/6/2023 3:12:04 PM'."}}: 
```

### Terraform Version

1.4.2

### AzureRM Provider Version

3.5.0

### Affected Resource(s)/Data Source(s)

azurerm_postgresql_flexible_server

### Terraform Configuration Files

```hcl
{"error":{"code":"ExpiredAuthenticationToken","message":"The access token expiry UTC time '4/6/2023 3:08:09 PM' is earlier than current UTC time '4/6/2023 3:10:04 PM'."}}: timestamp=2023-04-06T17:10:04.825+0200
2023-04-06T17:12:04.828+0200 [DEBUG] provider.terraform-provider-azurerm_v3.50.0_x5.exe: AzureRM Request: 
GET /subscriptions/xxx/providers/Microsoft.DBforPostgreSQL/locations/westeurope/azureAsyncOperation/987caee0-d3e6-4c1c-a0e4-351b25d57cea?api-version=2022-12-01 HTTP/1.1
Host: management.azure.com
User-Agent: Go/go1.19.3 (386-windows) go-autorest/v14.2.1 hashicorp/go-azure-sdk/servers/2022-12-01 HashiCorp Terraform/1.4.2 (+https://www.terraform.io) Terraform Plugin SDK/2.10.1 terraform-provider-azurerm/dev pid-222c6c49-1b0a-5959-a213-6608f9eb8820
X-Ms-Correlation-Request-Id: 3a0f9906-f570-bc77-4ede-ec2575cc7558
Accept-Encoding: gzip: timestamp=2023-04-06T17:12:04.828+0200
2023-04-06T17:12:04.857+0200 [DEBUG] provider.terraform-provider-azurerm_v3.50.0_x5.exe: AzureRM Response for https://management.azure.com/subscriptions/xxx/providers/Microsoft.DBforPostgreSQL/locations/westeurope/azureAsyncOperation/987caee0-d3e6-4c1c-a0e4-351b25d57cea?api-version=2022-12-01: 
HTTP/2.0 401 Unauthorized
Content-Length: 170
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
Date: Thu, 06 Apr 2023 15:12:04 GMT
Expires: -1
Pragma: no-cache
Strict-Transport-Security: max-age=31536000; includeSubDomains
Www-Authenticate: Bearer authorization_uri="https://login.windows.net/f78ca3a7-dc36-40d2-b6b5-9045ce9a52bf", error="invalid_token", error_description="The access token has expired."
X-Content-Type-Options: nosniff
X-Ms-Correlation-Request-Id: 3a0f9906-f570-bc77-4ede-ec2575cc7558
X-Ms-Failure-Cause: gateway
X-Ms-Request-Id: 4575f387-7c3c-4870-80e5-c3a4648796e0
X-Ms-Routing-Request-Id: GERMANYNORTH:20230406T151204Z:4575f387-7c3c-4870-80e5-c3a4648796e0

{"error":{"code":"ExpiredAuthenticationToken","message":"The access token expiry UTC time '4/6/2023 3:08:09 PM' is earlier than current UTC time '4/6/2023 3:12:04 PM'."}}: timestamp=2023-04-06T17:12:04.856+0200
2023-04-06T17:12:04.857+0200 [ERROR] provider.terraform-provider-azurerm_v3.50.0_x5.exe: Response contains error diagnostic: tf_rpc=ApplyResourceChange @caller=github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/diag/diagnostics.go:55 diagnostic_summary="creating Flexible Server (Subscription: "xxx"
Resource Group Name: "rg-tstpo-paas-dev-weu"
Flexible Server Name: "postgres-tstpo-dev-weunl9-la"): polling after Create: Future#WaitForCompletion: the number of retries has been exceeded: StatusCode=401 -- Original Error: Code="ExpiredAuthenticationToken" Message="The access token expiry UTC time '4/6/2023 3:08:09 PM' is earlier than current UTC time '4/6/2023 3:12:04 PM'."" tf_proto_version=5.3 tf_req_id=fa72eeef-fea2-07b2-0c66-23e1527a907e tf_resource_type=azurerm_postgresql_flexible_server @module=sdk.proto diagnostic_detail= diagnostic_severity=ERROR tf_provider_addr=provider timestamp=2023-04-06T17:12:04.857+0200
2023-04-06T17:12:04.876+0200 [ERROR] vertex "module.postgresql.azurerm_postgresql_flexible_server.serv_db" error: creating Flexible Server (Subscription: "xxx"
Resource Group Name: "rg-tstpo-paas-dev-weu"
Flexible Server Name: "postgres-tstpo-dev-weunl9-la"): polling after Create: Future#WaitForCompletion: the number of retries has been exceeded: StatusCode=401 -- Original Error: Code="ExpiredAuthenticationToken" Message="The access token expiry UTC time '4/6/2023 3:08:09 PM' is earlier than current UTC time '4/6/2023 3:12:04 PM'."
```

### Debug Output/Panic Output

```shell
n/a
```

### Expected Behaviour

Warn/error that section has not been added.

**Comment by neil-yechenwei** [comment] 2023-04-10 02:35
Thanks for raising this issue. Seems I didn't get the error you mentioned with below tf config. Could you try below tf config to see if the issue still exists? Thanks.

tf config:
```
provider "azurerm" {
  features {
    key_vault {
      purge_soft_delete_on_destroy       = false
      purge_soft_deleted_keys_on_destroy = false
    }
  }
}

data "azurerm_client_config" "current" {}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-postgresql-test0111125"
  location = "westeurope"
}

resource "azurerm_user_assigned_identity" "test" {
  name                = "acctestmitest0111125"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
}

resource "azurerm_postgresql_flexible_server" "test" {
  name                   = "acctest-fs-test0111125"
  resource_group_name    = azurerm_resource_group.test.name
  location               = azurerm_resource_group.test.location
  administrator_login    = "adminTerraform"
  administrator_password = "QAZwsx123"
  storage_mb             = 32768
  version                = "12"
  sku_name               = "B_Standard_B1ms"
  zone                   = "1"

  identity {
    type         = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.test.id]
  }
}
```

**Comment by tombuildsstuff** [comment] 2023-04-11 08:24
hey @PedroEss 

Thanks for opening this issue.

Taking a look through here this appears to be a duplicate of #20867, rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of #20867, would you mind subscribing to that issue for updates?

Thanks!

**Closed by tombuildsstuff** 2023-04-11 08:24 UTC
