### ISSUE TITLE
API Management: adding subscriptions and products causes Panic with 412 error

### ISSUE THREAD

**Issue by bradrlaw** [hashicorp/terraform-provider-azurerm#8303] opened 2020-08-31 16:28 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.00
provider.azurerm v2.25.0

### Affected Resource(s)

* `azurerm_api_management`
* `azurerm_api_management_subscription`
* `azurerm_api_management_product`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```
We have subscriptions defined in a map:
subscription_map = {
  "vendor-portal-test-sub1" = {
    product_id   = "test-product"
    display_name = "-test-sub1"
  },
  "vendor-portal-test-sub2" = {
    product_id   = "test-product"
    display_name = "-test-sub2"
  },
  "vendor-portal-test-sub3" = {
    product_id   = "test-product"
    display_name = "-test-sub3"
  },
  "vendor-portal-test-sub4" = {
    product_id   = "test-product"
    display_name = "-test-sub4"
  },
}

They are then used in a module:
module "subscription" {
  source              = "../modules/application/subscriptions"
  for_each            = var.subscription_map
  subscription_id     = each.key
  display_name        = each.value.display_name
  product_id          = each.value.product_id
  api_management_name = local.api_management_service_name
  resource_group_name = var.resource_group_name
  user_id             = module.user.admin_user.id
  state               = "active"
  depends_on          = [module.user, module.product, module.api_management_service, module.application_api]
}

### Panic Output

https://gist.github.com/bradrlaw/fcf2b903c4880253da37fc675e0ccbcb

### Expected Behavior

The products / subscriptions should have been created for the API management instance.

### Actual Behavior

A 412 panic occurs if some of the subscriptions already exist.

### Steps to Reproduce

1. `terraform apply`

It appears if there are subscriptions that already exist then adding new subscriptions / products in between them causes the error.  For example, if subscriptions test_sub1 & test_sub3 already exist, then the above sequence causes the error.  This was the only way we could reliably reproduce the error.  It is hard to diagnose since a subsequent run will work since the it only fails if there is more than one resource to add (next run works for this example since first subscription was created on failed run).

### Important Factoids

No

### References

Looks similar to this issue:
https://github.com/terraform-providers/terraform-provider-azurerm/issues/6648

* #0000

**Comment by yupwei68** [comment] 2020-09-01 06:02
Hi @bradrlaw , thanks for opening this issue. Sorry that I could not reproduce this error. Would you mind providing a detailed configuration for `azurerm_api_management`, `azurerm_api_management_product`, `azurerm_api_management_user` and `azurerm_api_management_subscription`? 
The way I have tested is to add `azurerm_api_management_subscription` to an existing `api_management`, `api_management_user` and `api_management_product` with the same `display_name` as an existing `api_management_subscription`. It's applied with success.

**Comment by bradrlaw** [comment] 2020-09-03 23:52
@yupwei68 @mybayern1974 I am should have a configuration to post soon.  I need to remove all the client identifying information from it first.

**Comment by yupwei68** [comment] 2020-09-25 02:11
This looks like duplication of https://github.com/terraform-providers/terraform-provider-azurerm/issues/8571

**Comment by mybayern1974** [comment] 2020-09-25 04:02
@bradrlaw , per yupwei68's finding, would you mind if we close this issue and you could subscribe #8571 for duplicate? Or feel free to suggest you believe these two issues are not talking about the same.

**Comment by mcalster** [comment] 2020-11-18 20:21
I have encountered the same problem just now, is there any progress on a solution?

**Comment by javierlga** [comment] 2021-05-14 16:14
I have faced this issue as well, triggering another run fixes. I haven't had a chance to set the `TF_LOG` to debug but it seems like Terraform is missing the `If-Match` request header

**Comment by luxaflow** [comment] 2021-11-22 08:39
I'm experiencing the same when creating multiple subscriptions with `azurerm_api_management_subscription` on existing api's and api products.
```
locals {
  apim_subscriptions = {
    "sub_name" = {
      user_id             = data.azurerm_api_management_user.administrator.id
      product_id      = azurerm_api_management_product.apim_product.id
      display_name  = "Product Name: Admin"
      allow_tracing  = true 
      state               = "active"
    }  
  }
}

resource "azurerm_api_management_subscription" "apim_subscriptions" {
  for_each = local.apim_subscriptions

  api_management_name = azurerm_api_management.apim.name
  resource_group_name   = data.azurerm_resource_group.rg.name
  user_id                           = each.value.user_id
  product_id                     = each.value.product_id
  display_name                = each.value.display_name
  state                              = each.value.state
}
```

Will try to set TF_LOG this week for some logging output.

**Comment by xuzhang3** [comment] 2021-11-29 08:04
I can reproduce this error but not always happened.  This issue seems service have race condition for sub creation to the same product(including same sub names). One workaround is add the `depends_on` to each subscription which will change the parallel creation into serial.
Example:
```hcl
resource "azurerm_api_management_subscription" "sub11" {
  api_management_name = data.azurerm_api_management.example.name
  resource_group_name = data.azurerm_api_management.example.resource_group_name
  user_id             = data.azurerm_api_management_user.example.id
  product_id          = data.azurerm_api_management_product.example.id
  display_name        = "Parser API11"
}

resource "azurerm_api_management_subscription" "sub12" {
  api_management_name = data.azurerm_api_management.example.name
  resource_group_name = data.azurerm_api_management.example.resource_group_name
  user_id             = data.azurerm_api_management_user.example.id
  product_id          = data.azurerm_api_management_product.example.id
  display_name        = "Parser API12"
  depends_on = [azurerm_api_management_subscription.sub11]
}

resource "azurerm_api_management_subscription" "sub13" {
  api_management_name = data.azurerm_api_management.example.name
  resource_group_name = data.azurerm_api_management.example.resource_group_name
  user_id             = data.azurerm_api_management_user.example.id
  product_id          = data.azurerm_api_management_product.example.id
  display_name        = "Parser API13"
  depends_on = [azurerm_api_management_subscription.sub12]
}
```

**Closed** 2021-12-03 20:34 UTC
Labels: duplicate, upstream-microsoft, service/api-management
