### ISSUE TITLE
IOT Central public network access and identity block is not working for provider version v3.25.0

### ISSUE THREAD

**Issue by dhanasri-kolagana** [hashicorp/terraform-provider-azurerm#18715] opened 2022-10-12 12:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.2

### AzureRM Provider Version

3.25.0

### Affected Resource(s)/Data Source(s)

IOT central application

### Terraform Configuration Files

```hcl
resource "azurerm_iotcentral_application" "iot_central" {
  name                = var.name
  resource_group_name = var.resource_group_name
  location            = var.location
  sub_domain          = var.sub_domain
  display_name = var.display_name
  sku          = var.sku
  template     = var.template
  tags         = var.tags
  public_network_access_enabled  = false
  identity = {
    type = "SystemAssigned"
  }
  }
```

### Debug Output/Panic Output

```shell
Error: Unsupported argument
│ 
│   on iot-central.tf line 11, in module "iot_central":
│   11:   public_network_access_enabled  = false
│ 
│ An argument named "public_network_access_enabled" is not expected here.
╵
╷
│ Error: Unsupported argument
│ 
│   on iot-central.tf line 12, in module "iot_central":
│   12:   identity = {
│ 
│ An argument named "identity" is not expected here.
╵
Operation failed: failed running terraform plan (exit 1)



Error: Terraform exited with code 1.
Error: Process completed with exit code 1.
```

### Expected Behaviour

Public network access should be disabled and identity assigned to system identity

### Steps to Reproduce

terraform plan

**Comment by Amier3** [comment] 2022-10-12 17:23
@myc2h6o  could you take a look at this when you get a chance? The schema code seems correct to me so i'm not sure what's going on

**Comment by myc2h6o** [comment] 2022-10-13 00:50
Hi @dhanasri-kolagana v3.25.0 shall have these two new arguments. Would you mind setting the environment variable `TF_LOG` to `INFO` as described [here](https://www.terraform.io/internals/debugging) to double check the provider version? e.g. below is the example output I tried from Windows PowerShell, I'm able to use these two properties.
```
$env:TF_LOG="INFO";terraform plan
2022-10-13T08:45:39.051+0800 [INFO]  Terraform version: 1.3.2
2022-10-13T08:45:39.052+0800 [INFO]  Go runtime version: go1.19.1
...
2022-10-13T08:45:43.688+0800 [INFO]  provider.terraform-provider-azurerm_v3.25.0_x5.exe: configuring server automatic 
```

Another thing is that the `identity` is a nested block instead of map, so you would need to update it from 
```hcl
identity = {
    type = "SystemAssigned"
}
```
to
```hcl
identity {
    type = "SystemAssigned"
}
```

**Comment by rcskosir** [comment] 2023-07-20 18:17
Thanks for opening this issue. Since time has passed and @myc2h6o was not able to reproduce this issue, I am going to mark this issue closed as “can’t reproduce”. If you are able to provide more information to help us reproduce this issue we may re-open this issue or open a new issue, thanks!

**Closed by rcskosir** 2023-07-20 18:17 UTC
Labels: bug, waiting-response, service/iot-central, v/3.x
