### ISSUE TITLE
Function App application stack setting dotnet_version does not control dotnet version of the Function App

### ISSUE THREAD

**Issue by SteveKurutz** [hashicorp/terraform-provider-azurerm#16927] opened 2022-05-24 16:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.9

### AzureRM Provider Version

3.7.0

### Affected Resource(s)/Data Source(s)

azurerm_windows_function_app

### Terraform Configuration Files

```hcl
resource "azurerm_windows_function_app" "primary" {
  name                          = (doesn't matter)
  location                      = (doesn't matter)
  resource_group_name           = (doesn't matter)
  service_plan_id               = (doesn't matter)
  storage_account_name          = (doesn't matter)
  storage_uses_managed_identity = true
  functions_extension_version   = "~4"
  https_only                    = "false"
  app_settings                  = (doesn't matter)

  identity {
    type = "SystemAssigned"
  }

  site_config {
    ftps_state          = "Disabled"
    http2_enabled       = "false"
    use_32_bit_worker   = "true"
    websockets_enabled  = "false"
    minimum_tls_version = "1.2"

    application_stack {
      dotnet_version = "6"
    }
  }
}
```

### Debug Output/Panic Output

```shell
Azure console reports a mismatch between function app and dotnet runtimes on Configuration blade, Function runtime settings tab:
Your app is pinned to an unsupported runtime version for 'dotnet'. For better performance, we recommend using one of our supported versions instead: ~3.

See also pasted content in "actual behavior"
```

### Expected Behaviour

using azurerm 2.7 function app code with site_config dotnet_framework_version  = "v6.0", I get:

  "netFrameworkVersion": "v6.0", 
... and there's no mention of windowsFxVersion.  

### Actual Behaviour

Resulting Function app gets this configuration (ARM exported because UI hides this):
                "netFrameworkVersion": "v4.0",

If I go against what documentation says and include the FUNCTIONS_WORKER_RUNTIME app setting, then I also get the following, which doesn't appear to help.
                "windowsFxVersion": "DotNet|6",

![image](https://user-images.githubusercontent.com/47374700/170075048-e30c3fb3-7f08-4079-992b-682e16003587.png)

### Steps to Reproduce

1. Make a function app using azurerm 3.7, with runtime ~4 and dotnet 6
2. Observe outcomes in Azure.

### Important Factoids

Trying to deploy new resources using 3.x to avoid resource types that will be deprecated in 4.x.  

### References

Documentation at https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_function_app states about the application_stack block: "If this is set, there must not be an application setting FUNCTIONS_WORKER_RUNTIME.".  This problem occurs both with and without the FUNCTIONS_WORKER_RUNTIME app setting present.  Even when I deploy without FUNCTIONS_WORKER_RUNTIME in my code, Azure adds it to the settings automatically.

**Comment by SteveKurutz** [comment] 2022-05-24 18:28
Additional info: running "az functionapp config set --net-framework-version "v6.0" --name <name> --resource-group <rg name>" post-deployment fixed my problem, and ib subsequent plan/apply this goes untouched.

**Comment by ASPCKenneth** [comment] 2022-05-25 08:24
I confirm this, also tested it with azurerm 3.6 and eventually 3.1 with same result as described above
Guess it is more related to the new resource type (azurerm_windows_function_app) and not so much the provider version?

**Comment by SteveKurutz** [comment] 2022-05-25 16:00
@ASPCKenneth  - yes and no . . . Yes because that is true, and no because the azurerm_function_app is deprecated and won't be supported in 4.0, so I'm assuming that azurerm_windows_function_app and azurerm_linux_function_app are its replacements that should have feature parity.

**Comment by xiaxyi** [comment] 2022-05-30 09:01
@SteveKurutz The function v4.0 requires .NET6.0 runtime. I will check the relevant properties to see if there is a better way to implement the feature.

**Comment by SteveKurutz** [comment] 2022-06-16 17:56
Thanks @xiaxyi .  This looks on the surface like wires got crossed in the new resource type.  The desired outcome is to be able to set .NET to 6.  However that gets done in AzureRM is fine by me.

**Comment by evandeworp** [comment] 2022-06-17 17:52
This looks like a duplicate of 16417.

**Comment by boukeversteegh** [comment] 2022-09-20 20:14
#16417

**Comment by xiaxyi** [comment] 2023-05-31 06:19
@SteveKurutz The issue should be fixed now, can you confirm if the app stack is set correcly for your windows dotnet function app now?

**Comment by rcskosir** [comment] 2023-08-25 15:36
Thanks for taking the time to submit this issue. It looks like this has been resolved as of https://github.com/hashicorp/terraform-provider-azurerm/pull/19685. As such, I am going to mark this issue as closed.

**Closed by rcskosir** 2023-08-25 15:36 UTC
Labels: waiting-response, service/functions, v/3.x
