### ISSUE TITLE
Error: The terraform-provider-azurerm_v3.50.0_x5 plugin crashed!

### ISSUE THREAD

**Issue by rapides** [hashicorp/terraform-provider-azurerm#21272] opened 2023-04-04 06:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.9

### AzureRM Provider Version

3.50.0

### Affected Resource(s)/Data Source(s)

azurerm_windows_web_app

### Terraform Configuration Files

```hcl
resource "azurerm_windows_web_app" "web_app" {
  name                = "webapp-w-eur"
  resource_group_name = azurerm_resource_group.resource_group.name
  location            = "westeurope"
  service_plan_id     = azurerm_service_plan.service_plan.id

  site_config {
    health_check_path        = "/health"
    ftps_state               = "FtpsOnly"
    remote_debugging_enabled = false
  }

  app_settings = {
    "AzureAd:Domain"                             = "example.com"
    "AzureAd:Instance"                           = "https://login.microsoftonline.com/"
    "AzureAd:SignedOutCallbackPath"              = "/signout-callback-oidc"
    "MICROSOFT_PROVIDER_AUTHENTICATION_SECRET"   = var.microsoft_provider_authentication_secret
    "WEBSITE_ENABLE_SYNC_UPDATE_SITE"            = "true"
    "XDT_MicrosoftApplicationInsights_Mode"      = "Recommended"
  }

  auth_settings_v2 {
    auth_enabled             = true
    default_provider         = "azureactivedirectory"
    forward_proxy_convention = "Standard"
    http_route_api_prefix    = "/.auth"
    require_authentication   = true
    unauthenticated_action   = "RedirectToLoginPage"

    active_directory_v2 {
      client_id                  = var.client_id
      allowed_audiences          = ["api://${var.client_id}"]
      tenant_auth_endpoint       = "https://sts.windows.net/${var.tenant_id}/v2.0"
      client_secret_setting_name = "MICROSOFT_PROVIDER_AUTHENTICATION_SECRET"
    }

    login {
      allowed_external_redirect_urls = ["https://example.com"]
      token_store_enabled            = true
    }
  }

  client_affinity_enabled = true
  https_only              = true

  identity {
    type = "SystemAssigned"
  }

  sticky_settings {
    app_setting_names = [
      "MICROSOFT_PROVIDER_AUTHENTICATION_SECRET"
    ]
  }

  tags = local.tags

  virtual_network_subnet_id = var.virtual_network_subnet_id

  lifecycle {
    ignore_changes = [
      app_settings["WEBSITE_RUN_FROM_PACKAGE"]
    ]
  }
}
```

### Debug Output/Panic Output

```shell
Stack trace from the terraform-provider-azurerm_v3.50.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x49b0923]

goroutine 125 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/appservice/helpers.expandAadAuthV2Settings({0xc001aea0e0, 0x1, 0x0?})
github.com/hashicorp/terraform-provider-azurerm/internal/services/appservice/helpers/auth_v2_schema.go:988 +0x603
github.com/hashicorp/terraform-provider-azurerm/internal/services/appservice/helpers.ExpandAuthV2Settings({0xc0037421a0, 0x1, 0x75cc920?})
github.com/hashicorp/terraform-provider-azurerm/internal/services/appservice/helpers/auth_v2_schema.go:2059 +0x12a
github.com/hashicorp/terraform-provider-azurerm/internal/services/appservice.WindowsWebAppResource.Update.func1({0x75d9ee8, 0xc0033f4ea0}, {0xc00146a000, {0x75daa10, 0xc0006167e0}, 0xc002a25980, 0x0, {0x75dbe30, 0xbb457e8}})
github.com/hashicorp/terraform-provider-azurerm/internal/services/appservice/windows_web_app_resource.go:847 +0x1cc5
github.com/hashicorp/terraform-provider-azurerm/internal/sdk.(*ResourceWrapper).Resource.func7({0x75d9ee8, 0xc0033f4ea0}, 0x1a3185c4682?, {0x61914e0?, 0xc00146a000?})
github.com/hashicorp/terraform-provider-azurerm/internal/sdk/wrapper_resource.go:116 +0x15c
github.com/hashicorp/terraform-provider-azurerm/internal/sdk.diagnosticsWrapper.func1({0x75d9ee8, 0xc0033f4ea0}, 0x0?, {0x61914e0, 0xc00146a000})
github.com/hashicorp/terraform-provider-azurerm/internal/sdk/wrapper_resource.go:185 +0xbe
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc000647c00, {0x75d9f20, 0xc002b1c990}, 0xd?, {0x61914e0, 0xc00146a000})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:741 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000647c00, {0x75d9f20, 0xc002b1c990}, 0xc002b27d40, 0xc002a25800, {0x61914e0, 0xc00146a000})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:847 +0x83a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00059f7d0, {0x75d9f20?, 0xc002b1c870?}, 0xc0028a9540)
github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0019eba40, {0x75d9f20?, 0xc002b1c060?}, 0xc0011fd6c0)
github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x68e5860?, 0xc0019eba40}, {0x75d9f20, 0xc002b1c060}, 0xc0011fd650, 0x0)
github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00026e000, {0x75ea220, 0xc001c8e9c0}, 0xc002b13b00, 0xc0005d66f0, 0xbb04f20, 0x0)
google.golang.org/grpc@v1.51.0/server.go:1340 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc00026e000, {0x75ea220, 0xc001c8e9c0}, 0xc002b13b00, 0x0)
google.golang.org/grpc@v1.51.0/server.go:1713 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
google.golang.org/grpc@v1.51.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
google.golang.org/grpc@v1.51.0/server.go:963 +0x28a

Error: The terraform-provider-azurerm_v3.50.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behaviour

`terraform apply` should be successful

Terraform plan:
```tf
  ~ resource "azurerm_windows_web_app" "web_app" {
        id                                 = "web-app-id"
        name                               = "webapp-w-eur"
        tags                               = { }
        # (21 unchanged attributes hidden)
      ~ auth_settings_v2 {
          + config_file_path                        = ""
          + forward_proxy_custom_host_header_name   = ""
          + forward_proxy_custom_scheme_header_name = ""
            # (9 unchanged attributes hidden)
          ~ active_directory_v2 {
              + client_secret_certificate_thumbprint = ""
              # Warning: this attribute value will be marked as sensitive and will not
              # display in UI output after applying this change. The value is unchanged.
              ~ tenant_auth_endpoint                 = (sensitive value)
                # (10 unchanged attributes hidden)
            }
          - apple_v2 {
              - login_scopes = [] -> null
            }
          - facebook_v2 {
              - login_scopes = [] -> null
            }
          - github_v2 {
              - login_scopes = [] -> null
            }
          - google_v2 {
              - allowed_audiences = [] -> null
              - login_scopes      = [] -> null
            }
          - microsoft_v2 {
              - allowed_audiences = [] -> null
              - login_scopes      = [] -> null
            }
          - twitter_v2 {}
            # (1 unchanged block hidden)
        }
        # (3 unchanged blocks hidden)
    }
Plan: 0 to add, 1 to change, 0 to destroy.
```

### Actual Behaviour

`terraform apply` raises an error. Expected changes are not going to be provided by Terraform. After bumping the version from `3.44.0` to `3.50.0` and adding the `auth_settings_v2` block to `azurerm_windows_web_app` I'm getting given an error message. Auth v2 configuration is already in place and has been configured via the Azure portal. We expect to import this setting under Terraform.

### Steps to Reproduce

1. terraform apply

### References

- https://github.com/hashicorp/terraform-provider-azurerm/issues/21137

**Comment by aristosvo** [comment] 2023-04-04 07:05
Hey @rapides 👋🏽  

Sorry to hear that it didn't work out for you yet. I'm facing the same problem, and the fix is already there and will be in the next v3.51.0 release.

This issue is a duplicate of #21218, as such I'll close this issue for now.

**Closed by aristosvo** 2023-04-04 07:05 UTC
Labels: bug, crash

**Comment by rapides** [comment] 2023-04-05 10:45
Hi @aristosvo, thank you for letting me know. Do you know when v3.51.0 is supposed to be released?

**Comment by aristosvo** [comment] 2023-04-05 11:58
Probably tomorrow, but I cannot guarantee anything!
