### ISSUE TITLE
The terraform-provider-azurerm_v3.5.0_x5.exe plugin crashed!

### ISSUE THREAD

**Issue by devtech234** [hashicorp/terraform-provider-azurerm#18463] opened 2022-09-20 10:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.8

### AzureRM Provider Version

3.5.0

### Affected Resource(s)/Data Source(s)

azurerm_resource_group azurerm_virtual_network azurerm_app_service azurerm_keyvaults

### Terraform Configuration Files

```hcl
#provider block (main.tf): 
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.5.0"
    }
  }

 backend "azurerm" {}
}

provider "azurerm" {
 subscription_id = var.subscription_id
 client_id = var.client_id
 client_secret = var.client_secret
 tenant_id = var.tenant_id
  features {}
}


module vnet {
    source = "../../Resources/vnet"
    subscription = var.subscription
    ParentEnv = var.ParentEnv
    number = var.number
}

module resource_group {
    source = "../../Resources/resource_group"
    location = var.location
    subscription = var.subscription
    BaseEnv = var.BaseEnv
    number = var.number

}

#modules in Resources folder:

#Resources/resource_group/rg.tf:
resource "azurerm_resource_group" "synapse" {
  name = "rg-syn-${var.subscription}-${var.ParentEnv}-${var.number}"
  location = var.location

  tags = {
    Environment = var.ParentEnv
    Purpose = "Synapse Workspace"
  }
}

#Resources/vnet/vnet.tf:
data "azurerm_virtual_network" "vnet" {
  name                = "vnet-${var.subscription}-${var.ParentEnv}" 
  resource_group_name = "rg-vnet-${var.subscription}-${var.ParentEnv}-${var.number}"
}

#there are other resources and modules also which are effected.
```

### Debug Output/Panic Output

```shell
╷
│ Error: Request cancelled
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.
╵
Error: Request cancelled
│ 
│   with module.resource_group.azurerm_resource_group.synapse,
│   on ..\..\Resources\resource_group\rg.tf line 2, in resource "azurerm_resource_group" "synapse":
│    2: resource "azurerm_resource_group" "synapse" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.

│ Error: Request cancelled
│ 
│   with module.vnet.data.azurerm_virtual_network.vnet,
│   on ..\..\Resources\vnet\vnet.tf line 1, in data "azurerm_virtual_network" "vnet":
│    1: data "azurerm_virtual_network" "vnet" {
│ 
│ The plugin.(*GRPCProvider).ValidateDataResourceConfig request was
│ cancelled.
╵

Stack trace from the terraform-provider-azurerm_v3.5.0_x5.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x590f7f0]
```

### Expected Behaviour

The terraform code runs successfully and the resources will be provisioned using azure devops pipelines.

### Actual Behaviour

Plugin crash error and the resources are not provisioned.

### Steps to Reproduce

1. terraform init
2. terraform plan

error is spotted in terraform plan

### Important Factoids

no

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/16494

Similar issue found for azurerm provider version 3.2.0 which is resolved in 3.5.0. FYI, I have tried with versions greater than 3.5.0 such as 3.9.0 and 3.14.0 but still the issue persists. Also tried with terraform version 1.2.9 but there is no change in output.

**Comment by Amier3** [comment] 2022-09-20 13:46
Hey @devtech234 

Unfortunately I wasn't able to replicate this crash, so this might be a crash related to your environment. Are you using a M1 Mac?  We've seen this issue before on M1s (https://github.com/hashicorp/terraform-provider-aws/issues/20274) be resolved by:

 `export GODEBUG=asyncpreemptoff=1`

**Comment by devtech234** [comment] 2022-09-20 14:33
Hi @Amier3 
Thanks for the response!
I am using windows agents from Azure virtual Machine Scale sets to run the terraform scripts.
We are recently seeing this plugin crash error. Before that it used to work fine

**Comment by myc2h6o** [comment] 2022-09-21 08:14
Hi @devtech234 this is not happening for me as well. Would you mind setting the [environment variable](https://www.terraform.io/internals/debugging) `TF_LOG` to `DEBUG`, the extra log may help with the troubleshooting.

**Comment by rcskosir** [comment] 2023-07-19 19:06
Thanks for opening this issue. Since time has passed and @myc2h6o was not able to reproduce this issue, I am going to mark this issue closed as “can’t reproduce”. If you are able to provide more information to help us reproduce this issue we may re-open this issue or open a new issue, thanks!

**Closed by rcskosir** 2023-07-19 19:06 UTC
Labels: bug, crash, backend, v/3.x
