### ISSUE TITLE
Resource design of Service Bus authorization rules means they are lost when the queue is recreated

### ISSUE THREAD

**Issue by infogulch** [hashicorp/terraform-provider-azurerm#14581] opened 2021-12-10 23:34 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Terraform (and AzureRM Provider) Version

### Terraform (and AzureRM Provider) Version

* Terraform v0.12.20 - v0.13.7
* provider.azurerm v1.40.0 - v2.89.0

### Affected Resource(s)

`azurerm_service_bus_queue`
`azurerm_service_bus_authorization_rule`

### Terraform Configuration Files

```terraform
locals {
  queue_name = "message_queue"
}

resource "azurerm_servicebus_queue" "message_queue" {
  name                = local.queue_name
  resource_group_name = azurerm_resource_group.my_group.name
  namespace_name      = azurerm_servicebus_namespace.our_namespace.name
  enable_partitioning = false // !!!
}

resource "azurerm_servicebus_queue_authorization_rule" "write_rule" {
  name                = "message_queue_write_rule"
  namespace_name      = azurerm_servicebus_namespace.our_namespace
  queue_name          = local.queue_name
  resource_group_name = azurerm_resource_group.my_group
  listen              = false 
  send                = true
  manage              = false
}
```

### Expected Behaviour

When terraform recreates `azurerm_servicebus_queue` for any reason, it also recreates `azurerm_servicebus_queue_authorization_rule` at the same time.

### Actual Behaviour

When `enable_partitioning` on `azurerm_servicebus_queue` is changed, it forces the queue to be recreated, but the associated auth rule is *not* recreated at the same time. This applies to any change of the 

### Steps to Reproduce

Steps to Reproduce

1. Set up a service bus queue and an authorization rule for it
1. Change the queue's partitioning_enabled property
1. terraform apply, observe that the queue recreates
1. Observe that there are no authorization rules for the queue
1. terraform apply
1. Observe that the authorization rules have now been recreated

# Scope

This issue was reported before in #5606, and closed with the following comment:

> when recreating the Parent resource using a field other than id doesn't detect that the Child needs recreating.

However, note that [the `azurerm_servicebus_queue` resource *does* export an `id` field][1], but for some reason the authorization rule resource does not use it and accepts a queue name instead.

I am raising this issue again because I think this a **bug in the design of the `azurerm_servicebus_queue_authorization_rule` resource**.

The *true* root problem is that the design of the arguments to this resource unnecessarily runs against the grain. Even if the linked issue in Core is fixed that still wouldn't sufficiently resolve this problem. Note in the example above how the queue name is set in a local variable, so there is not even a theoretical link between these resources. This is a totally reasonable thing to expect users to write yet it will blow up in their face when the queue is recreated. "Solving" the problem at this level will only create different issues and shift the blame onto the user for 'holding it wrong', where designing the resource with the correct pattern in the first place (i.e. using exported ids) would be nigh impossible to misuse and lead users to a "pit of success".

This better design pattern already is used many times in the azurerm provider, for example: [`azurerm_key_vault_secret`][2] references its parent via `key_vault_id`, [`azurerm_lb_rule`][3] references its parent via `loadbalancer_id`, [`azurerm_mssql_virtual_network_rule`][4] references its parent via `server_id`, etc, etc.

**I think [`azurerm_servicebus_queue_authorization_rule`][2] should be changed to accept an `queue_id` argument instead of `namespace_name` and `queue_name` arguments.** This resolution would truly solve the underlying problem of tracking relationships between resources and is less likely for users to accidentally misuse.

### Resources

* Previous issue: #5606
* [Attributes exported from `azurerm_servicebus_queue`][1]
* [`azurerm_key_vault_secret`][3]
* [`azurerm_lb_rule`][4]
* [`azurerm_mssql_virtual_network_rule`][5]
* This appears to be the same root cause in these issues as well, to which the same argument about using ids applies
  * #6415
  * #5296

[1]: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/servicebus_queue#attributes-reference
[2]: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/servicebus_queue_authorization_rule#argument-reference
[3]: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault_secret
[4]: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/lb_rule
[5]: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mssql_virtual_network_rule

**Comment by tombuildsstuff** [comment] 2021-12-13 01:36
hi @infogulch 

Thanks for opening this issue.

As mentioned in https://github.com/hashicorp/terraform-provider-azurerm/issues/5606#issuecomment-613374976 unfortunately this is a bug in Terraform Core rather than the Provider, so whilst we could look to workaround this issue by changing the design of this resource (and the others which are affected here), ultimately this needs to be fixed within Terraform Core (since it applies to numerous resources in different providers, including this one as your references above attest to).

Whilst this bug exists in Terraform Core, when introducing new resources to the Provider we're mindful of this and try to ensure that newer resources use the Resource ID of the parent resource rather than passing the individual fields (which has the other advantage of requiring less fields threaded through between resources).

The challenge for existing resources is that in order to make these changes, we'd need to make a large number of breaking changes to user configs across multiple resources - which is something we try and avoid where possible, so whilst there's some benefits to using the Resource ID between resources, ultimately fixing this en-mass within the Provider has other issues and needs to be fixed in Terraform Core (iirc this functionality used to work in older versions of Terraform Core too, so I believe this is in fact a regression, rather than an enhancement).

Given how invasive these changes would be for users (in terms of Configuration updates needed) - unfortunately we aren't planning to retroactively update the design of the affected resources en-mass at this time - however we may do this in a more piecemeal fashion. For the moment whilst I'd like to thank you for opening this issue, I'm going to close this issue in favour of [the upstream issue on Terraform Core](https://github.com/hashicorp/terraform/issues/24663) - would you mind subscribing to that issue for updates?

Thanks!

**Closed by tombuildsstuff** 2021-12-13 01:36 UTC
Labels: bug, duplicate, upstream-terraform

**Comment by infogulch** [comment] 2021-12-13 03:49
Hi Tom,

Thank you for your thorough response. I'm glad to hear that new resources are designed to use resource IDs to reference parents, for the reason identified in this issue among others. I appreciate that developing and supporting a product that is in active use means considering existing users and use-cases, and agree that making breaking changes to fix design problems in the public interface of the product *without restraint* is generally not a good strategy.

However, I maintain that this is a real issue with the design of these resources, that changing the behavior of terraform core can only ever be a partial fix (I can imagine many examples like the one above), and that even if it were 'fixed' the fix would come with significant downsides (e.g. false positives).

---

Is there a more complete list of resources that exhibit this design issue?

Have you considered that the upcoming planned release of provider version 3.0 may be a good opportunity to trial the "piecemeal" strategy? Pick one from the list of resources with this design problem and update its design together as part of 3.0 to gauge the response from the community and get an indication of their level of tolerance for such changes and how to best communicate them. With that information you can develop a data-backed plan to fix the remaining cases (or not depending on the response). Perhaps you already have a clear idea of how these kinds of changes would be received. Anecdotally, I expect the benefits of fixing this issue would be worth the pain of making updates to terraform code in the environments that I support. (Especially with the use of the new-ish refresh feature.)

Alternatively, have you considered making these changes available as feature flags? Assuming changing resource arguments via feature flags is technically feasible, this would eliminate unexpected breakage for existing users and enable them to accept the redesigned resource arguments at a pace of their choosing, in exchange for increasing the surface area of the provider until the old designs are deprecated (4.0?) and removed (5.0?).

Thank you for your attention on this subject.

**Comment by tombuildsstuff** [comment] 2021-12-13 18:42
hey @infogulch 

Unfortunately this isn't limited to the design of any particular resource - it affects any two resources where there's a reference on a field other than `id`, so this is less about the design of particular resources (although that's one way to workaround the problem in the short-term) - and more a bug/regression in Terraform Core which needs to be resolved since it affects every Provider.

Whilst we make use of feature-flags in the Provider, the scope of the changes needed to workaround this bug in Terraform Core means that this isn't something we're likely to workaround en-mass, since it'd require redesigning every resource in the Provider and as such this has to be fixed in Terraform Core. With regards to breaking changes, in short we've found that the more breaking changes to Configurations that there are, the longer it takes folks to upgrade (and harder it becomes) - which (given how the API's work in Azure) has other issues unfortunately.

Given the number of resources affected by this issue, and the impact it would have (both in terms of time to validate and redesign every resource in the provider) - unfortunately we don't plan to retroactively update the design of these older resources en-mass; and would encourage you instead [to highlight your use-cases on the Terraform Core issue](https://github.com/hashicorp/terraform/issues/24663) so that someone from that team can take a look.

Thanks!
